/** Auto-generated by generate-vercel-redirects.ts — do not edit. */
/**
 * Edge redirects — Hobby plan không hỗ trợ bulkRedirectsPath và giới hạn 1.024 routes.
 * Plain JS (not .ts) — tránh TS "Emit skipped" vì file nằm ngoài rootDir src/.
 * KNOWN_PATHS: URL hợp lệ; path nội dung lạ → HTTP 404 (không soft-200 homepage).
 */
const REDIRECTS = {
  "/about": "/bai-viet/ve-chung-toi",
  "/adminbp": "/admin",
  "/author": "/bai-viet/ve-chung-toi",
  "/bai-viet/bao-gia-cai-tao-nha-cu": "/tin-tuc/bao-gia-cai-tao-nha-cu",
  "/bai-viet/bao-gia-nang-tang-nha-pho": "/tin-tuc/bao-gia-nang-tang-nha-pho",
  "/bai-viet/bao-gia-sua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/bao-gia-xay-dung-biet-thu": "/tin-tuc/bao-gia-xay-dung-biet-thu",
  "/bai-viet/bao-gia-xay-dung-nha-2-tang": "/tin-tuc/bao-gia-xay-dung-nha-2-tang",
  "/bai-viet/bao-gia-xay-dung-nha-3-tang": "/tin-tuc/bao-gia-xay-dung-nha-3-tang",
  "/bai-viet/bao-gia-xay-nha-moi": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/bao-gia-xay-nha-phan-tho-long-an": "/tin-tuc/bao-gia-xay-nha-phan-tho-long-an",
  "/bai-viet/bao-gia-xay-nha-tron-goi-moi-nhat-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/bao-gia-xay-nha-tron-goi-phu-yen": "/tin-tuc/bao-gia-xay-nha-tron-goi-phu-yen",
  "/bai-viet/cai-tao-nha-cu": "/dich-vu/cai-tao-nha-cu",
  "/bai-viet/cai-tao-nha-dak-lak": "/tin-tuc/cai-tao-nha-dak-lak",
  "/bai-viet/cam-nang-xay-nha-2026": "/tin-tuc/cam-nang-xay-nha-2026",
  "/bai-viet/chi-phi-nha-pho-2-tang": "/tin-tuc/chi-phi-nha-pho-2-tang",
  "/bai-viet/chi-phi-xay-nha-2-tang-dak-lak": "/tin-tuc/chi-phi-xay-nha-2-tang-dak-lak",
  "/bai-viet/cong-ty-xay-dung-nha-pho-uy-tin-tphcm": "/tin-tuc/cong-ty-xay-dung-nha-pho-uy-tin-tphcm",
  "/bai-viet/du-toan-chi-phi-xay-nha": "/tin-tuc/du-toan-chi-phi-xay-nha",
  "/bai-viet/hoan-thien-nha": "/dich-vu/hoan-thien-nha",
  "/bai-viet/khuyen-mai-xay-dung": "/dich-vu/khuyen-mai",
  "/bai-viet/kien-truc-sao-khue-don-vi-uy-tin": "/tin-tuc/kien-truc-sao-khue-don-vi-uy-tin",
  "/bai-viet/luat-xay-dung-moi-nhat": "/tin-tuc/luat-xay-dung-moi-nhat",
  "/bai-viet/luu-y-xay-nha-pho": "/tin-tuc/luu-y-xay-nha-pho",
  "/bai-viet/mau-nha-ong-dep-long-an": "/tin-tuc/mau-nha-ong-dep-long-an",
  "/bai-viet/mau-nha-pho-2-tang-binh-duong": "/tin-tuc/mau-nha-pho-2-tang-binh-duong",
  "/bai-viet/mau-nha-pho-3-tang-dep": "/tin-tuc/mau-nha-pho-3-tang-dep",
  "/bai-viet/nang-tang-nha-pho": "/dich-vu/nang-tang-nha-pho",
  "/bai-viet/nha-thau-xay-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/phong-thuy-nha-o": "/tin-tuc/phong-thuy-nha-o",
  "/bai-viet/quy-trinh-thiet-ke": "/dich-vu/thiet-ke-nha",
  "/bai-viet/quy-trinh-xay-nha-tron-goi-a-z": "/tin-tuc/quy-trinh-xay-nha-tron-goi-a-z",
  "/bai-viet/sua-chua-cai-tao-nha-binh-chanh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-binh-thanh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-go-vap": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-hoc-mon": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-quan-1": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-quan-7": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-tan-phu": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-thu-duc": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-cai-tao-nha-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-nha-dak-lak": "/tin-tuc/sua-chua-nha-dak-lak",
  "/bai-viet/sua-chua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-chua-nha-tuy-hoa-phu-yen": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-nha-tron-goi-quan-go-vap": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/sua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bai-viet/thi-cong-nha-pho-phu-yen": "/tin-tuc/thi-cong-nha-pho-phu-yen",
  "/bai-viet/thiet-ke-biet-thu-thu-duc": "/cong-trinh/thiet-ke-nha-biet-thu-thu-duc",
  "/bai-viet/thiet-ke-nha": "/dich-vu/thiet-ke-nha",
  "/bai-viet/thiet-ke-nha-biet-thu-thu-duc": "/cong-trinh/thiet-ke-nha-biet-thu-thu-duc",
  "/bai-viet/thiet-ke-nha-dep-binh-duong": "/tin-tuc/thiet-ke-nha-dep-binh-duong",
  "/bai-viet/thiet-ke-nha-dep-dak-lak": "/tin-tuc/thiet-ke-nha-dep-dak-lak",
  "/bai-viet/thiet-ke-nha-dep-dong-nai": "/tin-tuc/thiet-ke-nha-dep-dong-nai",
  "/bai-viet/thiet-ke-nha-dep-gia-re": "/tin-tuc/thiet-ke-nha-dep-gia-re",
  "/bai-viet/thiet-ke-nha-dep-long-an": "/tin-tuc/thiet-ke-nha-dep-long-an",
  "/bai-viet/thiet-ke-nha-dep-phu-yen": "/tin-tuc/thiet-ke-nha-dep-phu-yen",
  "/bai-viet/thiet-ke-nha-pho-2-tang": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/thiet-ke-nha-pho-dak-lak": "/tin-tuc/thiet-ke-nha-pho-dak-lak",
  "/bai-viet/thiet-ke-nha-pho-hien-dai-tphcm": "/tin-tuc/thiet-ke-nha-pho-hien-dai-tphcm",
  "/bai-viet/thiet-ke-nha-phong-cach-hien-dai": "/cong-trinh/thiet-ke-nha-phong-cach-hien-dai",
  "/bai-viet/thiet-ke-thi-cong-nha-pho-dong-nai": "/tin-tuc/thiet-ke-thi-cong-nha-pho-dong-nai",
  "/bai-viet/thiet-ke-xay-dung-nha-pho-mien-nam": "/tin-tuc/thiet-ke-xay-dung-nha-pho-mien-nam",
  "/bai-viet/thue-thiet-ke-nha-truoc-khi-xay": "/tin-tuc/thue-thiet-ke-nha-truoc-khi-xay",
  "/bai-viet/top-mau-nha-pho-dep-xu-huong": "/tin-tuc/top-mau-nha-pho-dep-xu-huong",
  "/bai-viet/xay-dung-biet-thu": "/dich-vu/xay-dung-biet-thu",
  "/bai-viet/xay-dung-nha-2-tang": "/dich-vu/xay-dung-nha-2-tang",
  "/bai-viet/xay-dung-nha-3-tang": "/dich-vu/xay-dung-nha-3-tang",
  "/bai-viet/xay-dung-nha-dak-lak": "/tin-tuc/xay-dung-nha-dak-lak",
  "/bai-viet/xay-dung-nha-dep": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-dung-nha-dep-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-dung-nha-long-an": "/tin-tuc/xay-dung-nha-long-an",
  "/bai-viet/xay-dung-nha-phu-yen": "/tin-tuc/xay-dung-nha-phu-yen",
  "/bai-viet/xay-dung-nha-tron-goi": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-dung-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-dung-phan-tho": "/dich-vu/xay-dung-phan-tho",
  "/bai-viet/xay-nha-dep-dak-lak": "/tin-tuc/xay-nha-dep-dak-lak",
  "/bai-viet/xay-nha-gia-re-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-nha-moi": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-nha-ngan-sach-1-ty-2": "/tin-tuc/xay-nha-ngan-sach-1-ty-2",
  "/bai-viet/xay-nha-pho-binh-thanh": "/cong-trinh/xay-nha-pho-binh-thanh",
  "/bai-viet/xay-nha-pho-thuan-an": "/cong-trinh/xay-nha-pho-thuan-an",
  "/bai-viet/xay-nha-tron-goi-binh-duong": "/dich-vu/xay-nha-tron-goi-binh-duong",
  "/bai-viet/xay-nha-tron-goi-dak-lak": "/tin-tuc/xay-nha-tron-goi-dak-lak",
  "/bai-viet/xay-nha-tron-goi-dong-nai": "/dich-vu/xay-nha-tron-goi-dong-nai",
  "/bai-viet/xay-nha-tron-goi-gia-re-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xay-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bai-viet/xu-huong-thiet-ke-nha-pho-hien-dai": "/tin-tuc/xu-huong-thiet-ke-nha-pho-hien-dai",
  "/bang-bao-gia": "/bao-gia",
  "/bang-bao-gia-sua-chua-nha-tron-goi-tai-tp-hcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bao-gia-cai-tao-nha-cu": "/tin-tuc/bao-gia-cai-tao-nha-cu",
  "/bao-gia-nang-tang-nha-pho": "/tin-tuc/bao-gia-nang-tang-nha-pho",
  "/bao-gia-sua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/bao-gia-xay-dung-biet-thu": "/tin-tuc/bao-gia-xay-dung-biet-thu",
  "/bao-gia-xay-dung-nha-2-tang": "/tin-tuc/bao-gia-xay-dung-nha-2-tang",
  "/bao-gia-xay-dung-nha-3-tang": "/tin-tuc/bao-gia-xay-dung-nha-3-tang",
  "/bao-gia-xay-nha-moi": "/dich-vu/xay-nha-tron-goi",
  "/bao-gia-xay-nha-phan-tho-long-an": "/tin-tuc/bao-gia-xay-nha-phan-tho-long-an",
  "/bao-gia-xay-nha-tron-goi-moi-nhat-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/bao-gia-xay-nha-tron-goi-phu-yen": "/tin-tuc/bao-gia-xay-nha-tron-goi-phu-yen",
  "/cai-tao-nha-dak-lak": "/tin-tuc/cai-tao-nha-dak-lak",
  "/cam-nang-xay-nha-2026": "/tin-tuc/cam-nang-xay-nha-2026",
  "/category": "/dich-vu",
  "/category/bao-gia": "/bao-gia",
  "/category/sua-chua-nha": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/category/xay-nha-tron-goi": "/dich-vu/xay-nha-tron-goi",
  "/chi-phi-nha-pho-2-tang": "/tin-tuc/chi-phi-nha-pho-2-tang",
  "/chi-phi-xay-nha-2-tang-dak-lak": "/tin-tuc/chi-phi-xay-nha-2-tang-dak-lak",
  "/cong-trinh/xay-nha": "/cong-trinh",
  "/cong-ty-xay-dung-nha-pho-uy-tin-tphcm": "/tin-tuc/cong-ty-xay-dung-nha-pho-uy-tin-tphcm",
  "/contact": "/lien-he",
  "/danh-muc": "/tin-tuc",
  "/danh-muc/bao-gia": "/bao-gia",
  "/danh-muc/bao-gia/xay-nha-tron-goi": "/dich-vu/xay-nha-tron-goi",
  "/dich-vu-sua-nha-tron-goi-sao-khue": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/dich-vu/khuyen-mai-xay-dung": "/dich-vu/khuyen-mai",
  "/dich-vu/sua-chua-nha": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/dich-vu/sua-chua-nha-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/dich-vu/sua-nha": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/dich-vu/thiet-ke-nha-pho-hien-dai-tphcm": "/tin-tuc/thiet-ke-nha-pho-hien-dai-tphcm",
  "/dich-vu/xay-nha-moi": "/dich-vu/xay-nha-tron-goi",
  "/dich-vu/xay-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/don-gia-sua-chua-nha-moi-nhat-tai-tp-hcm-nam-2023": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/du-an": "/cong-trinh",
  "/du-toan-chi-phi-xay-nha": "/tin-tuc/du-toan-chi-phi-xay-nha",
  "/gioi-thieu": "/bai-viet/ve-chung-toi",
  "/gioi-thieu-ve-chung-toi": "/bai-viet/ve-chung-toi",
  "/hoan-thien-nha": "/dich-vu/hoan-thien-nha",
  "/hoat-dong-sao-khue": "/bai-viet/hoat-dong-sao-khue",
  "/khuyen-mai-xay-dung": "/dich-vu/khuyen-mai",
  "/kien-truc-sao-khue-don-vi-uy-tin": "/tin-tuc/kien-truc-sao-khue-don-vi-uy-tin",
  "/kinh-nghiem": "/tin-tuc",
  "/kinh-nghiem-xay-dung": "/tin-tuc",
  "/lien-he-ngay": "/lien-he",
  "/luat-xay-dung": "/tin-tuc/luat-xay-dung-moi-nhat",
  "/luat-xay-dung-moi-nhat": "/tin-tuc/luat-xay-dung-moi-nhat",
  "/luu-y-xay-nha-pho": "/tin-tuc/luu-y-xay-nha-pho",
  "/mau-nha-ong-dep-long-an": "/tin-tuc/mau-nha-ong-dep-long-an",
  "/mau-nha-pho-2-tang-binh-duong": "/tin-tuc/mau-nha-pho-2-tang-binh-duong",
  "/mau-nha-pho-3-tang-dep": "/tin-tuc/mau-nha-pho-3-tang-dep",
  "/mot-so-hinh-anh-cai-tao-nha-tai-kien-truc-sao-khue": "/cai-tao-nha",
  "/nang-tang-nha-pho": "/dich-vu/nang-tang-nha-pho",
  "/nha-thau-xay-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/phong-thuy-nha-o": "/tin-tuc/phong-thuy-nha-o",
  "/pricing": "/bao-gia",
  "/projects": "/cong-trinh",
  "/quy-trinh-thiet-ke": "/dich-vu/thiet-ke-nha",
  "/quy-trinh-xay-dung": "/tin-tuc/quy-trinh-xay-nha-tron-goi-a-z",
  "/quy-trinh-xay-nha-tron-goi-a-z": "/tin-tuc/quy-trinh-xay-nha-tron-goi-a-z",
  "/services": "/dich-vu",
  "/shop": "/",
  "/so-do-to-chuc": "/bai-viet/so-do-to-chuc",
  "/sua-chua-cai-tao-nha-binh-chanh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-binh-thanh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-go-vap": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-hoc-mon": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-quan-1": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-quan-7": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-tan-phu": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-thu-duc": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-cai-tao-nha-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-nha": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-nha-dak-lak": "/tin-tuc/sua-chua-nha-dak-lak",
  "/sua-chua-nha-tron-goi": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-chua-nha-tuy-hoa-phu-yen": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-gia-re-ho-chi-minh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-tphcmsua-nha-gia-re-ho-chi-minh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-tron-goi": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-tron-goi-anh-thuan-thanh-pho-thu-duc": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-tron-goi-quan-tan-binh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/sua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tag": "/tin-tuc",
  "/thi-cong-nha-pho-dong-nai": "/tin-tuc/thiet-ke-thi-cong-nha-pho-dong-nai",
  "/thi-cong-nha-pho-phu-yen": "/tin-tuc/thi-cong-nha-pho-phu-yen",
  "/thiet-ke-biet-thu-thu-duc": "/cong-trinh/thiet-ke-nha-biet-thu-thu-duc",
  "/thiet-ke-nha": "/dich-vu/thiet-ke-nha",
  "/thiet-ke-nha-biet-thu-thu-duc": "/cong-trinh/thiet-ke-nha-biet-thu-thu-duc",
  "/thiet-ke-nha-cap-4-dak-lak": "/tin-tuc/thiet-ke-nha-dep-dak-lak",
  "/thiet-ke-nha-dep-binh-duong": "/tin-tuc/thiet-ke-nha-dep-binh-duong",
  "/thiet-ke-nha-dep-dak-lak": "/tin-tuc/thiet-ke-nha-dep-dak-lak",
  "/thiet-ke-nha-dep-dong-nai": "/tin-tuc/thiet-ke-nha-dep-dong-nai",
  "/thiet-ke-nha-dep-gia-re": "/tin-tuc/thiet-ke-nha-dep-gia-re",
  "/thiet-ke-nha-dep-long-an": "/tin-tuc/thiet-ke-nha-dep-long-an",
  "/thiet-ke-nha-dep-phu-yen": "/tin-tuc/thiet-ke-nha-dep-phu-yen",
  "/thiet-ke-nha-pho-2-tang": "/dich-vu/xay-nha-tron-goi",
  "/thiet-ke-nha-pho-dak-lak": "/tin-tuc/thiet-ke-nha-pho-dak-lak",
  "/thiet-ke-nha-pho-hien-dai-tphcm": "/tin-tuc/thiet-ke-nha-pho-hien-dai-tphcm",
  "/thiet-ke-nha-phong-cach-hien-dai": "/cong-trinh/thiet-ke-nha-phong-cach-hien-dai",
  "/thiet-ke-thi-cong-nha-pho-dong-nai": "/tin-tuc/thiet-ke-thi-cong-nha-pho-dong-nai",
  "/thiet-ke-xay-dung-nha-pho-mien-nam": "/tin-tuc/thiet-ke-xay-dung-nha-pho-mien-nam",
  "/thue-thiet-ke-nha-truoc-khi-xay": "/tin-tuc/thue-thiet-ke-nha-truoc-khi-xay",
  "/tin-tuc/bao-gia-sua-chua-nha-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/bao-gia-sua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/bao-gia-xay-nha-moi": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/bao-gia-xay-nha-tron-goi-moi-nhat-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/cai-tao-nha-binh-chanh": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-binh-thanh": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-go-vap": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-hoc-mon": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-quan-1": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-quan-7": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-tan-binh": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-tan-phu": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-thu-duc": "/cai-tao-nha",
  "/tin-tuc/cai-tao-nha-tphcm": "/cai-tao-nha",
  "/tin-tuc/luat-xay-dung": "/tin-tuc/luat-xay-dung-moi-nhat",
  "/tin-tuc/nha-thau-xay-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/sua-chua-cai-tao-nha-binh-chanh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-binh-thanh": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-go-vap": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-hoc-mon": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-quan-1": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-quan-7": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-tan-phu": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-thu-duc": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-cai-tao-nha-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-nha-tron-goi-tphcm": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-chua-nha-tuy-hoa-phu-yen": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-nha-go-vap": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-nha-thu-duc": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-nha-tron-goi": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/sua-nha-tron-goi-quan-go-vap": "/dich-vu/sua-nha-tron-goi-tphcm",
  "/tin-tuc/thiet-ke-nha-cap-4-dak-lak": "/tin-tuc/thiet-ke-nha-dep-dak-lak",
  "/tin-tuc/thiet-ke-nha-pho-2-tang-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/xay-nha-gia-re-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/xay-nha-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/xay-nha-tron-goi-binh-thanh": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/xay-nha-tron-goi-gia-re-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/tin-tuc/xay-nha-tron-goi-quan-binh-thanh": "/dich-vu/xay-nha-tron-goi",
  "/top-mau-nha-pho-dep-xu-huong": "/tin-tuc/top-mau-nha-pho-dep-xu-huong",
  "/tuyen-dung": "/bai-viet/tuyen-dung",
  "/ve-chung-toi": "/bai-viet/ve-chung-toi",
  "/xay-dung-nha-dak-lak": "/tin-tuc/xay-dung-nha-dak-lak",
  "/xay-dung-nha-dep": "/dich-vu/xay-nha-tron-goi",
  "/xay-dung-nha-dep-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/xay-dung-nha-long-an": "/tin-tuc/xay-dung-nha-long-an",
  "/xay-dung-nha-phu-yen": "/tin-tuc/xay-dung-nha-phu-yen",
  "/xay-dung-nha-tron-goi": "/dich-vu/xay-nha-tron-goi",
  "/xay-dung-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/xay-dung-phan-tho": "/dich-vu/xay-dung-phan-tho",
  "/xay-nha-dep-dak-lak": "/tin-tuc/xay-nha-dep-dak-lak",
  "/xay-nha-gia-re-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-moi": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-ngan-sach-1-ty-2": "/tin-tuc/xay-nha-ngan-sach-1-ty-2",
  "/xay-nha-pho-binh-thanh": "/cong-trinh/xay-nha-pho-binh-thanh",
  "/xay-nha-pho-thuan-an": "/cong-trinh/xay-nha-pho-thuan-an",
  "/xay-nha-tai-tp-hcm": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-tron-goi": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-tron-goi-binh-duong": "/dich-vu/xay-nha-tron-goi-binh-duong",
  "/xay-nha-tron-goi-dak-lak": "/tin-tuc/xay-nha-tron-goi-dak-lak",
  "/xay-nha-tron-goi-dong-nai": "/dich-vu/xay-nha-tron-goi-dong-nai",
  "/xay-nha-tron-goi-gia-re-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-tron-goi-quan-binh-thanh": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-tron-goi-tphcm": "/dich-vu/xay-nha-tron-goi",
  "/xu-huong-thiet-ke-nha-pho-hien-dai": "/tin-tuc/xu-huong-thiet-ke-nha-pho-hien-dai",
};

const KNOWN_PATHS = {
  "/": 1,
  "/404": 1,
  "/about-legacy": 1,
  "/admin": 1,
  "/bai-viet/hoat-dong-sao-khue": 1,
  "/bai-viet/so-do-to-chuc": 1,
  "/bai-viet/tuyen-dung": 1,
  "/bai-viet/ve-chung-toi": 1,
  "/bao-gia": 1,
  "/cai-tao-nha": 1,
  "/cong-trinh": 1,
  "/cong-trinh/thiet-ke-nha-biet-thu-thu-duc": 1,
  "/cong-trinh/thiet-ke-nha-phong-cach-hien-dai": 1,
  "/cong-trinh/xay-nha-pho-binh-thanh": 1,
  "/cong-trinh/xay-nha-pho-thuan-an": 1,
  "/dich-vu": 1,
  "/dich-vu/cai-tao-nha-cu": 1,
  "/dich-vu/hoan-thien-nha": 1,
  "/dich-vu/khuyen-mai": 1,
  "/dich-vu/nang-tang-nha-pho": 1,
  "/dich-vu/sua-nha-tron-goi-tphcm": 1,
  "/dich-vu/thiet-ke-nha": 1,
  "/dich-vu/xay-dung-biet-thu": 1,
  "/dich-vu/xay-dung-nha-2-tang": 1,
  "/dich-vu/xay-dung-nha-3-tang": 1,
  "/dich-vu/xay-dung-phan-tho": 1,
  "/dich-vu/xay-nha-tron-goi": 1,
  "/dich-vu/xay-nha-tron-goi-binh-duong": 1,
  "/dich-vu/xay-nha-tron-goi-dong-nai": 1,
  "/lien-he": 1,
  "/mau-nha": 1,
  "/mau-nha/2-tang": 1,
  "/mau-nha/2-tang/ban-cong-hoa-4x18": 1,
  "/mau-nha/2-tang/chu-l-7x16": 1,
  "/mau-nha/2-tang/gieng-troi-5x20": 1,
  "/mau-nha/2-tang/hien-dai-6x20": 1,
  "/mau-nha/2-tang/indochine-5x16": 1,
  "/mau-nha/2-tang/kinh-ban-cong-5x16": 1,
  "/mau-nha/2-tang/lam-go-5x18": 1,
  "/mau-nha/2-tang/mai-bang-4x20": 1,
  "/mau-nha/2-tang/mai-thai-6x18": 1,
  "/mau-nha/2-tang/mat-tien-da-5x15": 1,
  "/mau-nha/2-tang/mau-trang-den-4x14": 1,
  "/mau-nha/2-tang/pho-hien-dai-4x16": 1,
  "/mau-nha/2-tang/phong-cach-scandi": 1,
  "/mau-nha/2-tang/thoang-sang-4x16": 1,
  "/mau-nha/2-tang/toi-gian-6x16": 1,
  "/mau-nha/3-tang": 1,
  "/mau-nha/3-tang/pho-3-tang-4x16": 1,
  "/mau-nha/3-tang/pho-3-tang-5x18": 1,
  "/mau-nha/3-tang/pho-3-tang-6x16": 1,
  "/mau-nha/3-tang/pho-3-tang-ban-cong": 1,
  "/mau-nha/3-tang/pho-3-tang-hoan-thien": 1,
  "/mau-nha/3-tang/pho-3-tang-kinh": 1,
  "/mau-nha/3-tang/pho-3-tang-lam-dung": 1,
  "/mau-nha/3-tang/pho-3-tang-sk-01": 1,
  "/mau-nha/3-tang/pho-3-tang-sk-02": 1,
  "/mau-nha/3-tang/pho-3-tang-sk-03": 1,
  "/mau-nha/3-tang/pho-3-tang-toi-gian": 1,
  "/mau-nha/3-tang/pho-3-tang-tron-goi": 1,
  "/mau-nha/4-tang": 1,
  "/mau-nha/4-tang/pho-4-tang-ban-cong": 1,
  "/mau-nha/4-tang/pho-4-tang-hien-dai": 1,
  "/mau-nha/4-tang/pho-4-tang-kinh": 1,
  "/mau-nha/4-tang/pho-4-tang-lam-go": 1,
  "/mau-nha/4-tang/pho-4-tang-mat-tien-hep": 1,
  "/mau-nha/4-tang/pho-4-tang-o-ket-hop": 1,
  "/mau-nha/4-tang/pho-4-tang-sang-trong": 1,
  "/mau-nha/4-tang/pho-4-tang-toi-gian": 1,
  "/mau-nha/4-tang/pho-4-tang-tum": 1,
  "/mau-nha/biet-thu": 1,
  "/mau-nha/biet-thu/biet-thu-2-tang": 1,
  "/mau-nha/biet-thu/biet-thu-3-tang": 1,
  "/mau-nha/biet-thu/biet-thu-pho-hien-dai": 1,
  "/mau-nha/biet-thu/biet-thu-sang-trong": 1,
  "/mau-nha/biet-thu/biet-thu-toi-gian": 1,
  "/mau-nha/biet-thu/biet-thu-vuon": 1,
  "/mau-nha/cap-4": 1,
  "/mau-nha/cap-4/gac-lung-5x20": 1,
  "/mau-nha/cap-4/mai-bang-8x14": 1,
  "/mau-nha/cap-4/mai-lech-hien-dai": 1,
  "/mau-nha/cap-4/mai-nhat-toi-gian": 1,
  "/mau-nha/cap-4/mai-thai-hien-dai": 1,
  "/mau-nha/cap-4/mat-tien-hep-6x16": 1,
  "/mau-nha/cap-4/mini-6x12": 1,
  "/mau-nha/cap-4/san-vuon-chu-l": 1,
  "/mau-nha/cap-4/vuon-9x18": 1,
  "/mau-nha/nha-ong": 1,
  "/mau-nha/nha-ong/ong-3m5x16": 1,
  "/mau-nha/nha-ong/ong-4x12": 1,
  "/mau-nha/nha-ong/ong-4x16-gieng-troi": 1,
  "/mau-nha/nha-ong/ong-4x18": 1,
  "/mau-nha/nha-ong/ong-4x20": 1,
  "/mau-nha/nha-ong/ong-5x15": 1,
  "/mau-nha/nha-ong/ong-5x16": 1,
  "/mau-nha/nha-ong/ong-hep-hien-dai": 1,
  "/services-legacy": 1,
  "/thiet-ke": 1,
  "/tin-tuc": 1,
  "/tin-tuc/bao-gia-cai-tao-nha-cu": 1,
  "/tin-tuc/bao-gia-nang-tang-nha-pho": 1,
  "/tin-tuc/bao-gia-xay-dung-biet-thu": 1,
  "/tin-tuc/bao-gia-xay-dung-nha-2-tang": 1,
  "/tin-tuc/bao-gia-xay-dung-nha-3-tang": 1,
  "/tin-tuc/bao-gia-xay-nha-phan-tho-long-an": 1,
  "/tin-tuc/bao-gia-xay-nha-tron-goi-phu-yen": 1,
  "/tin-tuc/cai-tao-nha-dak-lak": 1,
  "/tin-tuc/cam-nang-xay-nha-2026": 1,
  "/tin-tuc/chi-phi-nha-pho-2-tang": 1,
  "/tin-tuc/chi-phi-xay-nha-2-tang-dak-lak": 1,
  "/tin-tuc/cong-ty-xay-dung-nha-pho-uy-tin-tphcm": 1,
  "/tin-tuc/du-toan-chi-phi-xay-nha": 1,
  "/tin-tuc/kien-truc-sao-khue-don-vi-uy-tin": 1,
  "/tin-tuc/luat-xay-dung-moi-nhat": 1,
  "/tin-tuc/luu-y-xay-nha-pho": 1,
  "/tin-tuc/mau-nha-ong-dep-long-an": 1,
  "/tin-tuc/mau-nha-pho-2-tang-binh-duong": 1,
  "/tin-tuc/mau-nha-pho-3-tang-dep": 1,
  "/tin-tuc/phong-thuy-nha-o": 1,
  "/tin-tuc/quy-trinh-xay-nha-tron-goi-a-z": 1,
  "/tin-tuc/sua-chua-nha-dak-lak": 1,
  "/tin-tuc/thi-cong-nha-pho-phu-yen": 1,
  "/tin-tuc/thiet-ke-nha-dep-binh-duong": 1,
  "/tin-tuc/thiet-ke-nha-dep-dak-lak": 1,
  "/tin-tuc/thiet-ke-nha-dep-dong-nai": 1,
  "/tin-tuc/thiet-ke-nha-dep-gia-re": 1,
  "/tin-tuc/thiet-ke-nha-dep-long-an": 1,
  "/tin-tuc/thiet-ke-nha-dep-phu-yen": 1,
  "/tin-tuc/thiet-ke-nha-pho-dak-lak": 1,
  "/tin-tuc/thiet-ke-nha-pho-hien-dai-tphcm": 1,
  "/tin-tuc/thiet-ke-thi-cong-nha-pho-dong-nai": 1,
  "/tin-tuc/thiet-ke-xay-dung-nha-pho-mien-nam": 1,
  "/tin-tuc/thue-thiet-ke-nha-truoc-khi-xay": 1,
  "/tin-tuc/top-mau-nha-pho-dep-xu-huong": 1,
  "/tin-tuc/xay-dung-nha-dak-lak": 1,
  "/tin-tuc/xay-dung-nha-long-an": 1,
  "/tin-tuc/xay-dung-nha-phu-yen": 1,
  "/tin-tuc/xay-nha-dep-dak-lak": 1,
  "/tin-tuc/xay-nha-ngan-sach-1-ty-2": 1,
  "/tin-tuc/xay-nha-tron-goi-dak-lak": 1,
  "/tin-tuc/xu-huong-thiet-ke-nha-pho-hien-dai": 1,
  "/xay-moi": 1,
  "/xay-nha": 1,
};

function redirect301(path, requestUrl) {
  const target = new URL(path, requestUrl);
  target.hostname = "www.kientrucsaokhue.com";
  if (target.pathname.length > 1 && target.pathname.endsWith("/")) {
    target.pathname = target.pathname.slice(0, -1);
  }
  return Response.redirect(target.toString(), 301);
}

function notFound404() {
  const html = `<!DOCTYPE html><html lang="vi"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>404 | Kiến Trúc Sao Khuê</title><link rel="canonical" href="https://www.kientrucsaokhue.com/404"></head><body style="font-family:system-ui,sans-serif;max-width:40rem;margin:3rem auto;padding:0 1rem"><h1>404 — Không tìm thấy trang</h1><p>Trang bạn yêu cầu không tồn tại hoặc đã được di chuyển.</p><p><a href="/">Về trang chủ</a> · <a href="/tin-tuc">Tin tức</a></p></body></html>`;
  return new Response(html, {
    status: 404,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "x-robots-tag": "noindex, nofollow",
      "cache-control": "public, max-age=300",
    },
  });
}

/** WP leftovers (?doc/d888, ?p=930, ?page_id=…) — giữ utm/gclid. */
function cleanSearch(search) {
  if (!search || search === "?") return null;
  const params = new URLSearchParams(search.startsWith("?") ? search.slice(1) : search);
  const kept = new URLSearchParams();
  let hasJunk = false;
  for (const [key, value] of params) {
    if (/^(utm_|gclid|fbclid|gbraid|wbraid|msclkid)/i.test(key)) {
      kept.set(key, value);
      continue;
    }
    if (
      key.includes("/") ||
      key === "p" ||
      key === "page_id" ||
      key === "doc" ||
      key === "attachment_id" ||
      key === "preview"
    ) {
      hasJunk = true;
      continue;
    }
    kept.set(key, value);
  }
  if (!hasJunk) return null;
  const s = kept.toString();
  return s ? `?${s}` : "";
}

function rewriteToApi(pathname, requestUrl) {
  const target = new URL(requestUrl);
  target.pathname = `/api${pathname}`;
  return new Response(null, {
    headers: { "x-middleware-rewrite": target.toString() },
  });
}

export default function middleware(request) {
  const url = new URL(request.url);

  const normalizedPathname =
    url.pathname.length > 1 && url.pathname.endsWith("/")
      ? url.pathname.slice(0, -1)
      : url.pathname;

  // Ưu tiên API động — tránh CDN phục vụ sitemap.xml cũ (~3000 URL factory -ngan).
  if (
    normalizedPathname === "/sitemap.xml" ||
    normalizedPathname === "/robots.txt" ||
    normalizedPathname === "/feed.xml"
  ) {
    return rewriteToApi(normalizedPathname, request.url);
  }

  if (normalizedPathname.startsWith("/gioi-thieu/")) {
    return redirect301(`/bai-viet/${normalizedPathname.slice("/gioi-thieu/".length)}`, request.url);
  }
  if (normalizedPathname.startsWith("/kinh-nghiem-xay-dung/")) {
    return redirect301(`/tin-tuc/${normalizedPathname.slice("/kinh-nghiem-xay-dung/".length)}`, request.url);
  }
  if (normalizedPathname.startsWith("/kinh-nghiem/")) {
    return redirect301(`/tin-tuc/${normalizedPathname.slice("/kinh-nghiem/".length)}`, request.url);
  }
  if (normalizedPathname.startsWith("/danh-muc/")) {
    return redirect301("/tin-tuc", request.url);
  }
  if (normalizedPathname.startsWith("/category/")) {
    return redirect301("/tin-tuc", request.url);
  }
  if (normalizedPathname.startsWith("/tag/") || normalizedPathname === "/tag") {
    return redirect301("/tin-tuc", request.url);
  }

  const dest = REDIRECTS[normalizedPathname];
  if (dest) return redirect301(dest, request.url);

  // Factory / thin đã gỡ known-paths — 301 về hub (không 404 nuốt equity).
  // Keep in sync with sitemap-policy hubForUnknownPathname.
  if (!KNOWN_PATHS[normalizedPathname]) {
    const parts = normalizedPathname.split("/").filter(Boolean);
    const ns = parts[0] || "";
    const leaf = parts[parts.length - 1] || "";
    const contentNs =
      ns === "tin-tuc" || ns === "bai-viet" || ns === "dich-vu" || ns === "cong-trinh";
    const rootSlug = parts.length === 1 && leaf.includes("-");
    if (contentNs || rootSlug) {
      let hub = null;
      if (/^(sua-|sua-chua-|chong-tham|cai-tao|nang-tang|son-|gia-co|lam-moi|cong-ty-sua|bao-gia-sua|bao-gia-cai|chi-phi-cai|chi-phi-sua)/i.test(leaf)) {
        hub = "/dich-vu/sua-nha-tron-goi-tphcm";
      } else if (/^(xay-|thiet-ke|thi-cong|bao-gia-xay|ep-coc|hoan-thien|nha-thau|don-gia|chi-phi-xay|cong-ty-xay)/i.test(leaf)) {
        hub = "/dich-vu/xay-nha-tron-goi";
      } else if (/-sk\d+$/i.test(leaf) || /-ngan$/i.test(leaf)) {
        hub = "/tin-tuc";
      } else if (ns === "dich-vu") {
        hub = "/dich-vu";
      } else if (ns === "cong-trinh") {
        hub = "/cong-trinh";
      } else if (contentNs) {
        hub = "/tin-tuc";
      }
      if (hub) return redirect301(hub, request.url);
    }
  }

  const cleaned = cleanSearch(url.search ?? "");
  if (cleaned !== null) {
    return redirect301(`${normalizedPathname}${cleaned}`, request.url);
  }

  if (url.hostname !== "www.kientrucsaokhue.com" || normalizedPathname !== url.pathname) {
    const search = url.search ?? "";
    return redirect301(`${normalizedPathname}${search}`, request.url);
  }

  // Soft-200 homepage → GSC "Alternate page with proper canonical". Chặn bằng 404.
  if (!KNOWN_PATHS[normalizedPathname]) {
    return notFound404();
  }
}

export const config = {
  matcher: [
    "/((?!api|images|assets|favicon.ico|.*\\.[a-zA-Z0-9]+$).*)",
    "/sitemap.xml",
    "/robots.txt",
    "/feed.xml",
  ],
};
