/**
 * Sinh redirect 301 server-side cho Vercel — Googlebot nhận HTTP redirect, không chỉ JS.
 * Chạy trong `pnpm build`; cập nhật middleware.js + xóa redirects khỏi vercel.json.
 *
 * Hobby plan: không dùng bulkRedirectsPath (chỉ Pro+). Redirects chạy qua middleware.js.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { collectServerRedirects } from "../src/lib/legacy-redirects.ts";

export type VercelRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
  has?: Array<{ type: string; value: string }>;
};

type BulkRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

const TRAILING_SLASH_REDIRECT: VercelRedirect = {
  source: "/:path(.+)/",
  destination: "/:path",
  permanent: true,
};

function needsInlineRedirect(source: string): boolean {
  return source.includes(":") || source.includes("(");
}

export function buildGscRedirects(): VercelRedirect[] {
  const map = collectServerRedirects();

  const redirects: VercelRedirect[] = [...map.entries()].map(([source, destination]) => ({
    source,
    destination,
    permanent: true,
  }));

  redirects.sort((a, b) => a.source.localeCompare(b.source));
  redirects.push(TRAILING_SLASH_REDIRECT);

  return redirects;
}

function toBulkRedirects(all: VercelRedirect[]): BulkRedirect[] {
  return all
    .filter((rule) => !rule.has && !needsInlineRedirect(rule.source))
    .map((rule) => ({
      source: rule.source,
      destination: rule.destination,
      permanent: rule.permanent,
    }));
}

function patchVercelJson(vercelPath: string) {
  const raw = readFileSync(vercelPath, "utf8");
  const config = JSON.parse(raw) as Record<string, unknown>;
  config.redirects = [];
  delete config.bulkRedirectsPath;
  writeFileSync(vercelPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

function writeMiddleware(rules: BulkRedirect[], filePath: string) {
  const entries = rules
    .map((r) => `  ${JSON.stringify(r.source)}: ${JSON.stringify(r.destination)}`)
    .join(",\n");

  writeFileSync(
    filePath,
    `/** Auto-generated by generate-vercel-redirects.ts — do not edit. */
/**
 * Edge redirects — Hobby plan không hỗ trợ bulkRedirectsPath và giới hạn 1.024 routes.
 * Plain JS (not .ts) — tránh TS "Emit skipped" vì file nằm ngoài rootDir src/.
 */
const REDIRECTS = {
${entries},
};

function redirect301(path, requestUrl) {
  return Response.redirect(new URL(path, requestUrl).toString(), 301);
}

export default function middleware(request) {
  const url = new URL(request.url);

  if (url.hostname === "kientrucsaokhue.com") {
    url.hostname = "www.kientrucsaokhue.com";
    return Response.redirect(url.toString(), 301);
  }

  const { pathname } = url;

  if (pathname.length > 1 && pathname.endsWith("/")) {
    url.pathname = pathname.slice(0, -1);
    return Response.redirect(url.toString(), 301);
  }

  if (pathname.startsWith("/gioi-thieu/")) {
    return redirect301(\`/bai-viet/\${pathname.slice("/gioi-thieu/".length)}\`, request.url);
  }
  if (pathname.startsWith("/kinh-nghiem-xay-dung/")) {
    return redirect301(\`/tin-tuc/\${pathname.slice("/kinh-nghiem-xay-dung/".length)}\`, request.url);
  }
  if (pathname.startsWith("/kinh-nghiem/")) {
    return redirect301(\`/tin-tuc/\${pathname.slice("/kinh-nghiem/".length)}\`, request.url);
  }
  if (pathname.startsWith("/danh-muc/")) {
    return redirect301("/tin-tuc", request.url);
  }
  if (pathname.startsWith("/category/")) {
    return redirect301("/tin-tuc", request.url);
  }

  const dest = REDIRECTS[pathname];
  if (dest) return redirect301(dest, request.url);
}

export const config = {
  matcher: [
    "/((?!api|images|assets|favicon.ico|robots.txt|sitemap.xml|feed.xml|.*\\\\.[a-zA-Z0-9]+$).*)",
  ],
};
`,
    "utf8",
  );
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..", "..", "..");
const apiServerDir = join(repoRoot, "artifacts", "api-server");
const middlewareFile = join(apiServerDir, "middleware.js");

const all = buildGscRedirects();
const bulk = toBulkRedirects(all);

writeMiddleware(bulk, middlewareFile);
patchVercelJson(join(repoRoot, "vercel.json"));
patchVercelJson(join(apiServerDir, "vercel.json"));

console.log(`[redirects] ${bulk.length} rules → middleware.js (Hobby Edge Middleware)`);
