/**
 * Sinh redirect 301 server-side cho Vercel — Googlebot nhận HTTP redirect, không chỉ JS.
 * Chạy trong `pnpm build`; cập nhật middleware.js + xóa redirects khỏi vercel.json.
 *
 * Hobby plan: không dùng bulkRedirectsPath (chỉ Pro+). Redirects chạy qua middleware.js.
 * Unknown content paths → HTTP 404 (tránh soft-200 homepage → GSC "Crawled – not indexed").
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { collectServerRedirects } from "../src/lib/legacy-redirects.ts";
import { collectKnownPaths } from "../src/lib/known-paths.ts";
import { seedPosts } from "../../../lib/seed-content/src/index.ts";

export type VercelRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
  has?: Array<{ type: string; value: string }>;
};

type BulkRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

const TRAILING_SLASH_REDIRECT: VercelRedirect = {
  source: "/:path(.+)/",
  destination: "/:path",
  permanent: true,
};

function needsInlineRedirect(source: string): boolean {
  return source.includes(":") || source.includes("(");
}

export function buildGscRedirects(): VercelRedirect[] {
  const map = collectServerRedirects();

  const redirects: VercelRedirect[] = [...map.entries()].map(([source, destination]) => ({
    source,
    destination,
    permanent: true,
  }));

  redirects.sort((a, b) => a.source.localeCompare(b.source));
  redirects.push(TRAILING_SLASH_REDIRECT);

  return redirects;
}

function toBulkRedirects(all: VercelRedirect[]): BulkRedirect[] {
  return all
    .filter((rule) => !rule.has && !needsInlineRedirect(rule.source))
    .map((rule) => ({
      source: rule.source,
      destination: rule.destination,
      permanent: rule.permanent,
    }));
}

function patchVercelJson(vercelPath: string) {
  const raw = readFileSync(vercelPath, "utf8");
  const config = JSON.parse(raw) as Record<string, unknown>;
  config.redirects = [];
  delete config.bulkRedirectsPath;
  writeFileSync(vercelPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

function writeMiddleware(rules: BulkRedirect[], knownPaths: string[], filePath: string) {
  const entries = rules
    .map((r) => `  ${JSON.stringify(r.source)}: ${JSON.stringify(r.destination)}`)
    .join(",\n");

  const knownEntries = knownPaths.map((p) => `  ${JSON.stringify(p)}: 1`).join(",\n");

  writeFileSync(
    filePath,
    `/** Auto-generated by generate-vercel-redirects.ts — do not edit. */
/**
 * Edge redirects — Hobby plan không hỗ trợ bulkRedirectsPath và giới hạn 1.024 routes.
 * Plain JS (not .ts) — tránh TS "Emit skipped" vì file nằm ngoài rootDir src/.
 * KNOWN_PATHS: URL hợp lệ; path nội dung lạ → HTTP 404 (không soft-200 homepage).
 */
const REDIRECTS = {
${entries},
};

const KNOWN_PATHS = {
${knownEntries},
};

function redirect301(path, requestUrl) {
  const target = new URL(path, requestUrl);
  target.hostname = "www.kientrucsaokhue.com";
  if (target.pathname.length > 1 && target.pathname.endsWith("/")) {
    target.pathname = target.pathname.slice(0, -1);
  }
  return Response.redirect(target.toString(), 301);
}

function notFound404() {
  const html = \`<!DOCTYPE html><html lang="vi"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>404 | Kiến Trúc Sao Khuê</title><link rel="canonical" href="https://www.kientrucsaokhue.com/404"></head><body style="font-family:system-ui,sans-serif;max-width:40rem;margin:3rem auto;padding:0 1rem"><h1>404 — Không tìm thấy trang</h1><p>Trang bạn yêu cầu không tồn tại hoặc đã được di chuyển.</p><p><a href="/">Về trang chủ</a> · <a href="/tin-tuc">Tin tức</a></p></body></html>\`;
  return new Response(html, {
    status: 404,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "x-robots-tag": "noindex, nofollow",
      "cache-control": "public, max-age=300",
    },
  });
}

/** WP leftovers (?doc/d888, ?p=930, ?page_id=…) — giữ utm/gclid. */
function cleanSearch(search) {
  if (!search || search === "?") return null;
  const params = new URLSearchParams(search.startsWith("?") ? search.slice(1) : search);
  const kept = new URLSearchParams();
  let hasJunk = false;
  for (const [key, value] of params) {
    if (/^(utm_|gclid|fbclid|gbraid|wbraid|msclkid)/i.test(key)) {
      kept.set(key, value);
      continue;
    }
    if (
      key.includes("/") ||
      key === "p" ||
      key === "page_id" ||
      key === "doc" ||
      key === "attachment_id" ||
      key === "preview"
    ) {
      hasJunk = true;
      continue;
    }
    kept.set(key, value);
  }
  if (!hasJunk) return null;
  const s = kept.toString();
  return s ? \`?\${s}\` : "";
}

function rewriteToApi(pathname, requestUrl) {
  const target = new URL(requestUrl);
  target.pathname = \`/api\${pathname}\`;
  return new Response(null, {
    headers: { "x-middleware-rewrite": target.toString() },
  });
}

export default function middleware(request) {
  const url = new URL(request.url);

  const normalizedPathname =
    url.pathname.length > 1 && url.pathname.endsWith("/")
      ? url.pathname.slice(0, -1)
      : url.pathname;

  // Ưu tiên API động — tránh CDN phục vụ sitemap.xml cũ (~3000 URL factory -ngan).
  if (
    normalizedPathname === "/sitemap.xml" ||
    normalizedPathname === "/robots.txt" ||
    normalizedPathname === "/feed.xml"
  ) {
    return rewriteToApi(normalizedPathname, request.url);
  }

  if (normalizedPathname.startsWith("/gioi-thieu/")) {
    return redirect301(\`/bai-viet/\${normalizedPathname.slice("/gioi-thieu/".length)}\`, request.url);
  }
  if (normalizedPathname.startsWith("/kinh-nghiem-xay-dung/")) {
    return redirect301(\`/tin-tuc/\${normalizedPathname.slice("/kinh-nghiem-xay-dung/".length)}\`, request.url);
  }
  if (normalizedPathname.startsWith("/kinh-nghiem/")) {
    return redirect301(\`/tin-tuc/\${normalizedPathname.slice("/kinh-nghiem/".length)}\`, request.url);
  }
  if (normalizedPathname.startsWith("/danh-muc/")) {
    return redirect301("/tin-tuc", request.url);
  }
  if (normalizedPathname.startsWith("/category/")) {
    return redirect301("/tin-tuc", request.url);
  }
  if (normalizedPathname.startsWith("/tag/") || normalizedPathname === "/tag") {
    return redirect301("/tin-tuc", request.url);
  }

  const dest = REDIRECTS[normalizedPathname];
  if (dest) return redirect301(dest, request.url);

  // Factory *-skNN / *-ngan đã noindex — 301 gom equity về hub (không soft-404).
  {
    const leaf = normalizedPathname.split("/").pop() || "";
    if (/-sk\\d+$/i.test(leaf) || /-ngan$/i.test(leaf)) {
      if (/^sua-|^chong-tham|^cai-tao|^nang-tang|^son-/.test(leaf)) {
        return redirect301("/dich-vu/sua-nha-tron-goi-tphcm", request.url);
      }
      if (/^xay-|^thiet-ke|^thi-cong|^bao-gia-xay|^ep-coc|^hoan-thien/.test(leaf)) {
        return redirect301("/dich-vu/xay-nha-tron-goi", request.url);
      }
      return redirect301("/tin-tuc", request.url);
    }
  }

  const cleaned = cleanSearch(url.search ?? "");
  if (cleaned !== null) {
    return redirect301(\`\${normalizedPathname}\${cleaned}\`, request.url);
  }

  if (url.hostname !== "www.kientrucsaokhue.com" || normalizedPathname !== url.pathname) {
    const search = url.search ?? "";
    return redirect301(\`\${normalizedPathname}\${search}\`, request.url);
  }

  // Soft-200 homepage → GSC "Alternate page with proper canonical". Chặn bằng 404.
  if (!KNOWN_PATHS[normalizedPathname]) {
    return notFound404();
  }
}

export const config = {
  matcher: [
    "/((?!api|images|assets|favicon.ico|.*\\\\.[a-zA-Z0-9]+$).*)",
    "/sitemap.xml",
    "/robots.txt",
    "/feed.xml",
  ],
};
`,
    "utf8",
  );
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..", "..", "..");
const apiServerDir = join(repoRoot, "artifacts", "api-server");
const middlewareFile = join(apiServerDir, "middleware.js");

const all = buildGscRedirects();
const bulk = toBulkRedirects(all);
const known = [...collectKnownPaths(seedPosts)].sort();

writeMiddleware(bulk, known, middlewareFile);
patchVercelJson(join(repoRoot, "vercel.json"));
patchVercelJson(join(apiServerDir, "vercel.json"));

console.log(
  `[redirects] ${bulk.length} rules + ${known.length} known paths → middleware.js (Hobby Edge Middleware)`,
);
