/**
 * Lịch từ khóa SEO — batch 4: 50 bài Đắk Lắk (#247–#296).
 * Tập trung: xây nhà, sửa chữa, cải tạo. Batch #247–#296.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const dakLakKeywordCalendarBatch4: ContentCalendarItem[] = [
  // —— Xây nhà (22) ——
  {
    no: 247,
    title: "Xây Nhà Tại Đắk Lắk Uy Tín Chất Lượng",
    keyword: "xây nhà Đắk Lắk",
    slug: "xay-nha-dak-lak",
    status: "done",
  },
  {
    no: 248,
    title: "Thi Công Nhà Tại Đắk Lắk Chuyên Nghiệp",
    keyword: "thi công nhà Đắk Lắk",
    slug: "thi-cong-nha-dak-lak",
    status: "done",
  },
  {
    no: 249,
    title: "Xây Nhà Mới Tại Đắk Lắk — Quy Trình & Chi Phí",
    keyword: "xây nhà mới Đắk Lắk",
    slug: "xay-nha-moi-dak-lak",
    status: "done",
  },
  {
    no: 250,
    title: "Xây Nhà Phố Tại Đắk Lắk Đẹp Hiện Đại",
    keyword: "xây nhà phố Đắk Lắk",
    slug: "xay-nha-pho-dak-lak",
    status: "done",
  },
  {
    no: 251,
    title: "Xây Nhà Uy Tín Tại Đắk Lắk — Sao Khuê",
    keyword: "xây nhà uy tín Đắk Lắk",
    slug: "xay-nha-uy-tin-dak-lak",
    status: "done",
  },
  {
    no: 252,
    title: "Xây Nhà 4 Tầng Tại Đắk Lắk — Chi Phí Tham Khảo",
    keyword: "xây nhà 4 tầng Đắk Lắk",
    slug: "xay-nha-4-tang-dak-lak",
    status: "done",
  },
  {
    no: 253,
    title: "Xây Nhà Trọ Tại Đắk Lắk Cho Thuê",
    keyword: "xây nhà trọ Đắk Lắk",
    slug: "xay-nha-tro-dak-lak",
    status: "done",
  },
  {
    no: 254,
    title: "Xây Nhà Cấp 3 Tại Đắk Lắk Giá Tốt",
    keyword: "xây nhà cấp 3 Đắk Lắk",
    slug: "xay-nha-cap-3-dak-lak",
    status: "done",
  },
  {
    no: 255,
    title: "Xây Nhà Phần Thô Tại Đắk Lắk",
    keyword: "xây nhà thô Đắk Lắk",
    slug: "xay-nha-tho-dak-lak",
    status: "done",
  },
  {
    no: 256,
    title: "Thi Công Phần Thô Nhà Tại Đắk Lắk",
    keyword: "thi công phần thô Đắk Lắk",
    slug: "thi-cong-phan-tho-dak-lak",
    status: "done",
  },
  {
    no: 257,
    title: "Đội Thợ Xây Nhà Tại Đắk Lắk Có Kinh Nghiệm",
    keyword: "đội thợ xây nhà Đắk Lắk",
    slug: "doi-tho-xay-nha-dak-lak",
    status: "done",
  },
  {
    no: 258,
    title: "Xây Nhà Tại Krông Ana Đắk Lắk",
    keyword: "xây nhà Krông Ana Đắk Lắk",
    slug: "xay-nha-krong-ana-dak-lak",
    status: "done",
  },
  {
    no: 259,
    title: "Xây Nhà Tại Krông Năng Đắk Lắk",
    keyword: "xây nhà Krông Năng Đắk Lắk",
    slug: "xay-nha-krong-nang-dak-lak",
    status: "done",
  },
  {
    no: 260,
    title: "Xây Nhà Tại Cư M'gar Đắk Lắk",
    keyword: "xây nhà Cư M'gar Đắk Lắk",
    slug: "xay-nha-cu-mgar-dak-lak",
    status: "done",
  },
  {
    no: 261,
    title: "Xây Nhà Tại Lắk Đắk Lắk",
    keyword: "xây nhà Lắk Đắk Lắk",
    slug: "xay-nha-lak-dak-lak",
    status: "done",
  },
  {
    no: 262,
    title: "Xây Nhà Tại M'Đrắk Đắk Lắk",
    keyword: "xây nhà M'Đrắk Đắk Lắk",
    slug: "xay-nha-mdak-dak-lak",
    status: "done",
  },
  {
    no: 263,
    title: "Xây Nhà Tại Krông Pắk Đắk Lắk",
    keyword: "xây nhà Krông Pắk Đắk Lắk",
    slug: "xay-nha-krong-pak-dak-lak",
    status: "done",
  },
  {
    no: 264,
    title: "Xây Nhà Kinh Doanh Tại Đắk Lắk",
    keyword: "xây nhà kinh doanh Đắk Lắk",
    slug: "xay-nha-kinh-doanh-dak-lak",
    status: "done",
  },
  {
    no: 265,
    title: "Đơn Giá Xây Nhà Tại Đắk Lắk (2026)",
    keyword: "đơn giá xây nhà Đắk Lắk",
    slug: "don-gia-xay-nha-dak-lak",
    status: "done",
  },
  {
    no: 266,
    title: "Xây Nhà Tại Ea Súp Đắk Lắk",
    keyword: "xây nhà Ea Súp Đắk Lắk",
    slug: "xay-nha-ea-sup-dak-lak",
    status: "done",
  },
  {
    no: 267,
    title: "Xây Nhà Phần Hoàn Thiện Tại Đắk Lắk",
    keyword: "xây nhà phần hoàn thiện Đắk Lắk",
    slug: "xay-nha-phan-hoan-thien-dak-lak",
    status: "done",
  },
  {
    no: 268,
    title: "Xây Nhà Tại Krông Bông Đắk Lắk",
    keyword: "xây nhà Krông Bông Đắk Lắk",
    slug: "xay-nha-krong-bong-dak-lak",
    status: "done",
  },

  // —— Sửa chữa (14) ——
  {
    no: 269,
    title: "Sửa Chữa Cải Tạo Nhà Tại Đắk Lắk Trọn Gói",
    keyword: "sửa chữa cải tạo nhà Đắk Lắk",
    slug: "sua-chua-cai-tao-nha-dak-lak",
    status: "done",
  },
  {
    no: 270,
    title: "Sửa Nhà Cũ Tại Đắk Lắk Uy Tín",
    keyword: "sửa nhà cũ Đắk Lắk",
    slug: "sua-nha-cu-dak-lak",
    status: "done",
  },
  {
    no: 271,
    title: "Sửa Chữa Nhà Trọn Gói Tại Đắk Lắk",
    keyword: "sửa chữa nhà trọn gói Đắk Lắk",
    slug: "sua-chua-nha-tron-goi-dak-lak",
    status: "done",
  },
  {
    no: 272,
    title: "Sửa Chữa Nhà Phố Tại Đắk Lắk",
    keyword: "sửa chữa nhà phố Đắk Lắk",
    slug: "sua-chua-nha-pho-dak-lak",
    status: "done",
  },
  {
    no: 273,
    title: "Sửa Mái Nhà Tại Đắk Lắk Chống Thấm",
    keyword: "sửa mái nhà Đắk Lắk",
    slug: "sua-mai-nha-dak-lak",
    status: "done",
  },
  {
    no: 274,
    title: "Sửa Nhà 2 Tầng Tại Đắk Lắk",
    keyword: "sửa nhà 2 tầng Đắk Lắk",
    slug: "sua-nha-2-tang-dak-lak",
    status: "done",
  },
  {
    no: 275,
    title: "Sửa Điện Nước Nhà Tại Đắk Lắk",
    keyword: "sửa điện nước nhà Đắk Lắk",
    slug: "sua-dien-nuoc-nha-dak-lak",
    status: "done",
  },
  {
    no: 276,
    title: "Sửa Chữa Nhà Tại Ea Kar Đắk Lắk",
    keyword: "sửa chữa nhà Ea Kar Đắk Lắk",
    slug: "sua-chua-nha-ea-kar-dak-lak",
    status: "done",
  },
  {
    no: 277,
    title: "Sửa Chữa Nhà Tại Krông Búk Đắk Lắk",
    keyword: "sửa chữa nhà Krông Búk Đắk Lắk",
    slug: "sua-chua-nha-krong-buk-dak-lak",
    status: "done",
  },
  {
    no: 278,
    title: "Sửa Tường Nứt Nhà Tại Đắk Lắk",
    keyword: "sửa tường nứt nhà Đắk Lắk",
    slug: "sua-tuong-nut-nha-dak-lak",
    status: "done",
  },
  {
    no: 279,
    title: "Sửa Nhà Thấm Dột Tại Đắk Lắk",
    keyword: "sửa nhà thấm dột Đắk Lắk",
    slug: "sua-nha-tham-dot-dak-lak",
    status: "done",
  },
  {
    no: 280,
    title: "Sửa Chữa Nhà Phần Thô Tại Đắk Lắk",
    keyword: "sửa chữa nhà phần thô Đắk Lắk",
    slug: "sua-chua-nha-phan-tho-dak-lak",
    status: "done",
  },
  {
    no: 281,
    title: "Sửa Nhà Trọ Tại Đắk Lắk",
    keyword: "sửa nhà trọ Đắk Lắk",
    slug: "sua-nha-tro-dak-lak",
    status: "done",
  },
  {
    no: 282,
    title: "Sửa Chữa Nhà Tại Krông Ana Đắk Lắk",
    keyword: "sửa chữa nhà Krông Ana Đắk Lắk",
    slug: "sua-chua-nha-krong-ana-dak-lak",
    status: "done",
  },

  // —— Cải tạo (14) ——
  {
    no: 283,
    title: "Cải Tạo Nhà Cũ Tại Đắk Lắk Trọn Gói",
    keyword: "cải tạo nhà cũ Đắk Lắk",
    slug: "cai-tao-nha-cu-dak-lak",
    status: "done",
  },
  {
    no: 284,
    title: "Cải Tạo Nhà Trọn Gói Tại Đắk Lắk",
    keyword: "cải tạo nhà trọn gói Đắk Lắk",
    slug: "cai-tao-nha-tron-goi-dak-lak",
    status: "done",
  },
  {
    no: 285,
    title: "Cải Tạo Nhà Ống Tại Đắk Lắk",
    keyword: "cải tạo nhà ống Đắk Lắk",
    slug: "cai-tao-nha-ong-dak-lak",
    status: "done",
  },
  {
    no: 286,
    title: "Cải Tạo Nhà 2 Tầng Tại Đắk Lắk",
    keyword: "cải tạo nhà 2 tầng Đắk Lắk",
    slug: "cai-tao-nha-2-tang-dak-lak",
    status: "done",
  },
  {
    no: 287,
    title: "Cải Tạo Mặt Tiền Nhà Tại Đắk Lắk",
    keyword: "cải tạo mặt tiền nhà Đắk Lắk",
    slug: "cai-tao-mat-tien-nha-dak-lak",
    status: "done",
  },
  {
    no: 288,
    title: "Nâng Cấp Nhà Cũ Tại Đắk Lắk",
    keyword: "nâng cấp nhà cũ Đắk Lắk",
    slug: "nang-cap-nha-cu-dak-lak",
    status: "done",
  },
  {
    no: 289,
    title: "Tái Thiết Nhà Tại Đắk Lắk Chuyên Nghiệp",
    keyword: "tái thiết nhà Đắk Lắk",
    slug: "tai-thiet-nha-dak-lak",
    status: "done",
  },
  {
    no: 290,
    title: "Cải Tạo Nhà Tại Buôn Ma Thuột",
    keyword: "cải tạo nhà Buôn Ma Thuột",
    slug: "cai-tao-nha-buon-ma-thuot",
    status: "done",
  },
  {
    no: 291,
    title: "Cải Tạo Nhà Tại Buôn Hồ Đắk Lắk",
    keyword: "cải tạo nhà Buôn Hồ Đắk Lắk",
    slug: "cai-tao-nha-buon-ho-dak-lak",
    status: "done",
  },
  {
    no: 292,
    title: "Cải Tạo Sân Thượng Nhà Tại Đắk Lắk",
    keyword: "cải tạo sân thượng Đắk Lắk",
    slug: "cai-tao-san-thuong-dak-lak",
    status: "done",
  },
  {
    no: 293,
    title: "Cải Tạo Nhà Tại Ea Kar Đắk Lắk",
    keyword: "cải tạo nhà Ea Kar Đắk Lắk",
    slug: "cai-tao-nha-ea-kar-dak-lak",
    status: "done",
  },
  {
    no: 294,
    title: "Cải Tạo Nhà Tại Krông Năng Đắk Lắk",
    keyword: "cải tạo nhà Krông Năng Đắk Lắk",
    slug: "cai-tao-nha-krong-nang-dak-lak",
    status: "done",
  },
  {
    no: 295,
    title: "Làm Mới Nhà Cũ Tại Đắk Lắk",
    keyword: "làm mới nhà cũ Đắk Lắk",
    slug: "lam-moi-nha-cu-dak-lak",
    status: "done",
  },
  {
    no: 296,
    title: "Thay Mái Tôn Nhà Tại Đắk Lắk",
    keyword: "thay mái tôn nhà Đắk Lắk",
    slug: "thay-mai-ton-nha-dak-lak",
    status: "done",
  },
];
