/**
 * Lịch từ khóa SEO — batch 5: 100 bài (#297–#396).
 * 50 Đắk Lắk + 50 TP.HCM — bổ sung khoảng trống sau batch #247–#296 và #121–#170.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const dakLakTphcmKeywordCalendarBatch5: ContentCalendarItem[] = [
  // —— Đắk Lắk (50) #297–#346 ——
  { no: 297, title: "Xây Nhà Trọn Gói Tại Buôn Ma Thuột", keyword: "xây nhà trọn gói Buôn Ma Thuột", slug: "xay-nha-tron-goi-buon-ma-thuot", status: "planned" },
  { no: 298, title: "Báo Giá Xây Nhà Tại Buôn Ma Thuột (2026)", keyword: "báo giá xây nhà Buôn Ma Thuột", slug: "bao-gia-xay-nha-buon-ma-thuot", status: "planned" },
  { no: 299, title: "Chi Phí Xây Nhà Tại Buôn Ma Thuột", keyword: "chi phí xây nhà Buôn Ma Thuột", slug: "chi-phi-xay-nha-buon-ma-thuot", status: "planned" },
  { no: 300, title: "Xây Nhà Phần Thô Tại Buôn Ma Thuột", keyword: "xây nhà phần thô Buôn Ma Thuột", slug: "xay-nha-phan-tho-buon-ma-thuot", status: "planned" },
  { no: 301, title: "Thiết Kế Nhà Phố Tại Buôn Ma Thuột", keyword: "thiết kế nhà phố Buôn Ma Thuột", slug: "thiet-ke-nha-pho-buon-ma-thuot", status: "planned" },
  { no: 302, title: "Sửa Nhà Trọn Gói Tại Buôn Ma Thuột", keyword: "sửa nhà trọn gói Buôn Ma Thuột", slug: "sua-nha-tron-goi-buon-ma-thuot", status: "planned" },
  { no: 303, title: "Cải Tạo Nhà Trọn Gói Tại Buôn Ma Thuột", keyword: "cải tạo nhà trọn gói Buôn Ma Thuột", slug: "cai-tao-nha-tron-goi-buon-ma-thuot", status: "planned" },
  { no: 304, title: "Xây Biệt Thự Tại Buôn Ma Thuột", keyword: "xây biệt thự Buôn Ma Thuột", slug: "xay-biet-thu-buon-ma-thuot", status: "planned" },
  { no: 305, title: "Xây Nhà Cấp 4 Tại Buôn Ma Thuột", keyword: "xây nhà cấp 4 Buôn Ma Thuột", slug: "xay-nha-cap-4-buon-ma-thuot", status: "planned" },
  { no: 306, title: "Xây Nhà Tại Ea H'leo Đắk Lắk", keyword: "xây nhà Ea H'leo Đắk Lắk", slug: "xay-nha-ea-hleo-dak-lak", status: "planned" },
  { no: 307, title: "Xây Nhà Tại Cư Kuin Đắk Lắk", keyword: "xây nhà Cư Kuin Đắk Lắk", slug: "xay-nha-cu-kuin-dak-lak", status: "planned" },
  { no: 308, title: "Xây Nhà Tại Buôn Đôn Đắk Lắk", keyword: "xây nhà Buôn Đôn Đắk Lắk", slug: "xay-nha-buon-don-dak-lak", status: "planned" },
  { no: 309, title: "Xây Nhà Nghỉ Tại Đắk Lắk", keyword: "xây nhà nghỉ Đắk Lắk", slug: "xay-nha-nghi-dak-lak", status: "planned" },
  { no: 310, title: "Xây Homestay Tại Đắk Lắk", keyword: "xây homestay Đắk Lắk", slug: "xay-homestay-dak-lak", status: "planned" },
  { no: 311, title: "Xây Nhà Mặt Tiền Tại Đắk Lắk", keyword: "xây nhà mặt tiền Đắk Lắk", slug: "xay-nha-mat-tien-dak-lak", status: "planned" },
  { no: 312, title: "Nâng Tầng Nhà Tại Đắk Lắk", keyword: "nâng tầng nhà Đắk Lắk", slug: "nang-tang-nha-dak-lak", status: "planned" },
  { no: 313, title: "Báo Giá Sửa Nhà Tại Đắk Lắk", keyword: "báo giá sửa nhà Đắk Lắk", slug: "bao-gia-sua-nha-dak-lak", status: "planned" },
  { no: 314, title: "Chi Phí Cải Tạo Nhà Tại Đắk Lắk", keyword: "chi phí cải tạo nhà Đắk Lắk", slug: "chi-phi-cai-tao-nha-dak-lak", status: "planned" },
  { no: 315, title: "Sửa Sân Thượng Tại Đắk Lắk", keyword: "sửa sân thượng Đắk Lắk", slug: "sua-san-thuong-dak-lak", status: "planned" },
  { no: 316, title: "Xây Nhà 1 Tầng Tại Đắk Lắk", keyword: "xây nhà 1 tầng Đắk Lắk", slug: "xay-nha-1-tang-dak-lak", status: "planned" },
  { no: 317, title: "Thi Công Mái Nhà Tại Đắk Lắk", keyword: "thi công mái nhà Đắk Lắk", slug: "thi-cong-mai-nha-dak-lak", status: "planned" },
  { no: 318, title: "Xây Nhà Phường Tân Lợi Buôn Ma Thuột", keyword: "xây nhà phường Tân Lợi Buôn Ma Thuột", slug: "xay-nha-tan-loi-buon-ma-thuot", status: "planned" },
  { no: 319, title: "Xây Nhà Ea Tam Buôn Ma Thuột", keyword: "xây nhà Ea Tam Buôn Ma Thuột", slug: "xay-nha-ea-tam-buon-ma-thuot", status: "planned" },
  { no: 320, title: "Giám Sát Xây Nhà Tại Đắk Lắk", keyword: "giám sát xây nhà Đắk Lắk", slug: "giam-sat-xay-nha-dak-lak", status: "planned" },
  { no: 321, title: "Xây Nhà Từ Xa Tại Đắk Lắk", keyword: "xây nhà từ xa Đắk Lắk", slug: "xay-nha-tu-xa-dak-lak", status: "planned" },
  { no: 322, title: "Báo Giá Cải Tạo Nhà Tại Đắk Lắk", keyword: "báo giá cải tạo nhà Đắk Lắk", slug: "bao-gia-cai-tao-nha-dak-lak", status: "planned" },
  { no: 323, title: "Thiết Kế Nhà 3 Tầng Tại Đắk Lắk", keyword: "thiết kế nhà 3 tầng Đắk Lắk", slug: "thiet-ke-nha-3-tang-dak-lak", status: "planned" },
  { no: 324, title: "Xây Nhà Thô Tại Buôn Ma Thuột", keyword: "xây nhà thô Buôn Ma Thuột", slug: "xay-nha-tho-buon-ma-thuot", status: "planned" },
  { no: 325, title: "Hoàn Thiện Nội Thất Tại Đắk Lắk", keyword: "hoàn thiện nội thất Đắk Lắk", slug: "hoan-thien-noi-that-dak-lak", status: "planned" },
  { no: 326, title: "Thi Công Nội Thất Tại Đắk Lắk", keyword: "thi công nội thất Đắk Lắk", slug: "thi-cong-noi-that-dak-lak", status: "planned" },
  { no: 327, title: "Sửa Chữa Nhà Tại Buôn Đôn Đắk Lắk", keyword: "sửa chữa nhà Buôn Đôn Đắk Lắk", slug: "sua-chua-nha-buon-don-dak-lak", status: "planned" },
  { no: 328, title: "Cải Tạo Nhà Tại Buôn Đôn Đắk Lắk", keyword: "cải tạo nhà Buôn Đôn Đắk Lắk", slug: "cai-tao-nha-buon-don-dak-lak", status: "planned" },
  { no: 329, title: "Xây Nhà Trên Đất Bazan Đắk Lắk", keyword: "xây nhà đất bazan Đắk Lắk", slug: "xay-nha-dat-bazan-dak-lak", status: "planned" },
  { no: 330, title: "Xây Nhà 5 Tầng Tại Đắk Lắk", keyword: "xây nhà 5 tầng Đắk Lắk", slug: "xay-nha-5-tang-dak-lak", status: "planned" },
  { no: 331, title: "Thi Công Chống Thấm Tại Đắk Lắk", keyword: "thi công chống thấm Đắk Lắk", slug: "thi-cong-chong-tham-dak-lak", status: "planned" },
  { no: 332, title: "Làm Mái Nhà Tại Đắk Lắk", keyword: "làm mái nhà Đắk Lắk", slug: "lam-mai-nha-dak-lak", status: "planned" },
  { no: 333, title: "Sơn Nhà Tại Đắk Lắk", keyword: "sơn nhà Đắk Lắk", slug: "son-nha-dak-lak", status: "planned" },
  { no: 334, title: "Ốp Lát Nhà Tại Đắk Lắk", keyword: "ốp lát nhà Đắk Lắk", slug: "op-lat-nha-dak-lak", status: "planned" },
  { no: 335, title: "Xây Nhà Khu Đô Thị Buôn Ma Thuột", keyword: "xây nhà khu đô thị Buôn Ma Thuột", slug: "xay-nha-khu-do-thi-buon-ma-thuot", status: "planned" },
  { no: 336, title: "Thiết Kế Homestay Tại Đắk Lắk", keyword: "thiết kế homestay Đắk Lắk", slug: "thiet-ke-homestay-dak-lak", status: "planned" },
  { no: 337, title: "Nhà Thầu Xây Dựng Tại Buôn Ma Thuột", keyword: "nhà thầu Buôn Ma Thuột", slug: "nha-thau-buon-ma-thuot", status: "planned" },
  { no: 338, title: "Thi Công Phần Hoàn Thiện Buôn Ma Thuột", keyword: "thi công phần hoàn thiện Buôn Ma Thuột", slug: "thi-cong-phan-hoan-thien-buon-ma-thuot", status: "planned" },
  { no: 339, title: "Cải Tạo Nhà Cấp 4 Tại Đắk Lắk", keyword: "cải tạo nhà cấp 4 Đắk Lắk", slug: "cai-tao-nha-cap-4-dak-lak", status: "planned" },
  { no: 340, title: "Sửa Chữa Nhà Tại Cư Kuin Đắk Lắk", keyword: "sửa chữa nhà Cư Kuin Đắk Lắk", slug: "sua-chua-nha-cu-kuin-dak-lak", status: "planned" },
  { no: 341, title: "Mở Rộng Nhà Tại Đắk Lắk", keyword: "mở rộng nhà Đắk Lắk", slug: "mo-rong-nha-dak-lak", status: "planned" },
  { no: 342, title: "Phá Dỡ Nhà Cũ Tại Đắk Lắk", keyword: "phá dỡ nhà cũ Đắk Lắk", slug: "pha-do-nha-cu-dak-lak", status: "planned" },
  { no: 343, title: "Xây Nhà Đẹp Tại Buôn Ma Thuột", keyword: "xây nhà đẹp Buôn Ma Thuột", slug: "xay-nha-dep-buon-ma-thuot", status: "planned" },
  { no: 344, title: "Thiết Kế Biệt Thự Buôn Ma Thuột", keyword: "thiết kế biệt thự Buôn Ma Thuột", slug: "thiet-ke-biet-thu-buon-ma-thuot", status: "planned" },
  { no: 345, title: "Cải Tạo Nhà Tại Ea H'leo Đắk Lắk", keyword: "cải tạo nhà Ea H'leo Đắk Lắk", slug: "cai-tao-nha-ea-hleo-dak-lak", status: "planned" },
  { no: 346, title: "Xây Nhà Vườn Buôn Ma Thuột", keyword: "xây nhà vườn Buôn Ma Thuột", slug: "xay-nha-vuon-buon-ma-thuot", status: "planned" },

  // —— TP.HCM (50) #347–#396 ——
  { no: 347, title: "Xây Nhà Tại TP.HCM Uy Tín Chất Lượng", keyword: "xây nhà TP.HCM", slug: "xay-nha-tphcm", status: "planned" },
  { no: 348, title: "Cải Tạo Nhà Tại TP.HCM Trọn Gói", keyword: "cải tạo nhà TP.HCM", slug: "cai-tao-nha-tphcm", status: "planned" },
  { no: 349, title: "Cải Tạo Nhà Phố Tại TP.HCM", keyword: "cải tạo nhà phố TP.HCM", slug: "cai-tao-nha-pho-tphcm", status: "planned" },
  { no: 350, title: "Cải Tạo Nhà Cũ Tại TP.HCM", keyword: "cải tạo nhà cũ TP.HCM", slug: "cai-tao-nha-cu-tphcm", status: "planned" },
  { no: 351, title: "Làm Mới Nhà Cũ Tại TP.HCM", keyword: "làm mới nhà cũ TP.HCM", slug: "lam-moi-nha-cu-tphcm", status: "planned" },
  { no: 352, title: "Sửa Nhà Cũ Tại TP.HCM", keyword: "sửa nhà cũ TP.HCM", slug: "sua-nha-cu-tphcm", status: "planned" },
  { no: 353, title: "Sửa Chữa Nhà Trọn Gói Tại TP.HCM", keyword: "sửa chữa nhà trọn gói TP.HCM", slug: "sua-chua-nha-tron-goi-tphcm", status: "planned" },
  { no: 354, title: "Cải Tạo Nhà Trọn Gói Tại TP.HCM", keyword: "cải tạo nhà trọn gói TP.HCM", slug: "cai-tao-nha-tron-goi-tphcm", status: "planned" },
  { no: 355, title: "Nâng Tầng Nhà Phố Tại TP.HCM", keyword: "nâng tầng nhà phố TP.HCM", slug: "nang-tang-nha-pho-tphcm", status: "planned" },
  { no: 356, title: "Nâng Tầng Nhà Tại TP.HCM", keyword: "nâng tầng nhà TP.HCM", slug: "nang-tang-nha-tphcm", status: "planned" },
  { no: 357, title: "Xây Nhà Uy Tín Tại TP.HCM", keyword: "xây nhà uy tín TP.HCM", slug: "xay-nha-uy-tin-tphcm", status: "planned" },
  { no: 358, title: "Xây Nhà Giá Rẻ Tại TP.HCM", keyword: "xây nhà giá rẻ TP.HCM", slug: "xay-nha-gia-re-tphcm", status: "planned" },
  { no: 359, title: "Xây Nhà 4 Tầng Tại TP.HCM", keyword: "xây nhà 4 tầng TP.HCM", slug: "xay-nha-4-tang-tphcm", status: "planned" },
  { no: 360, title: "Xây Nhà 5 Tầng Tại TP.HCM", keyword: "xây nhà 5 tầng TP.HCM", slug: "xay-nha-5-tang-tphcm", status: "planned" },
  { no: 361, title: "Xây Nhà Cấp 4 Tại TP.HCM", keyword: "xây nhà cấp 4 TP.HCM", slug: "xay-nha-cap-4-tphcm", status: "planned" },
  { no: 362, title: "Xây Nhà 1 Trệt 1 Lầu Tại TP.HCM", keyword: "xây nhà 1 trệt 1 lầu TP.HCM", slug: "xay-nha-1-tret-1-lau-tphcm", status: "planned" },
  { no: 363, title: "Xây Nhà Trong Hẻm Tại TP.HCM", keyword: "xây nhà trong hẻm TP.HCM", slug: "xay-nha-trong-hem-tphcm", status: "planned" },
  { no: 364, title: "Xây Nhà Mặt Tiền Tại TP.HCM", keyword: "xây nhà mặt tiền TP.HCM", slug: "xay-nha-mat-tien-tphcm", status: "planned" },
  { no: 365, title: "Xây Biệt Thự Tại TP.HCM", keyword: "xây biệt thự TP.HCM", slug: "xay-biet-thu-tphcm", status: "planned" },
  { no: 366, title: "Xây Shophouse Tại TP.HCM", keyword: "xây shophouse TP.HCM", slug: "xay-shophouse-tphcm", status: "planned" },
  { no: 367, title: "Xây Nhà Trọ Tại TP.HCM", keyword: "xây nhà trọ TP.HCM", slug: "xay-nha-tro-tphcm", status: "planned" },
  { no: 368, title: "Nhà Ống Tại TP.HCM — Thiết Kế & Thi Công", keyword: "nhà ống TP.HCM", slug: "nha-ong-tphcm", status: "planned" },
  { no: 369, title: "Đơn Giá Xây Nhà Tại TP.HCM (2026)", keyword: "đơn giá xây nhà TP.HCM", slug: "don-gia-xay-nha-tphcm", status: "planned" },
  { no: 370, title: "Báo Giá Xây Nhà Phần Thô Tại TP.HCM", keyword: "báo giá xây nhà phần thô TP.HCM", slug: "bao-gia-xay-nha-phan-tho-tphcm", status: "planned" },
  { no: 371, title: "Chi Phí Xây Nhà 2 Tầng Tại TP.HCM", keyword: "chi phí xây nhà 2 tầng TP.HCM", slug: "chi-phi-xay-nha-2-tang-tphcm", status: "planned" },
  { no: 372, title: "Chi Phí Cải Tạo Nhà Tại TP.HCM", keyword: "chi phí cải tạo nhà TP.HCM", slug: "chi-phi-cai-tao-nha-tphcm", status: "planned" },
  { no: 373, title: "Hoàn Thiện Nhà Tại TP.HCM", keyword: "hoàn thiện nhà TP.HCM", slug: "hoan-thien-nha-tphcm", status: "planned" },
  { no: 374, title: "Hoàn Thiện Nhà Phần Thô Tại TP.HCM", keyword: "hoàn thiện nhà phần thô TP.HCM", slug: "hoan-thien-nha-phan-tho-tphcm", status: "planned" },
  { no: 375, title: "Thi Công Phần Thô Tại TP.HCM", keyword: "thi công phần thô TP.HCM", slug: "thi-cong-phan-tho-tphcm", status: "planned" },
  { no: 376, title: "Xin Giấy Phép Xây Dựng Tại TP.HCM", keyword: "xin giấy phép xây dựng TP.HCM", slug: "xin-giay-phep-xay-dung-tphcm", status: "planned" },
  { no: 377, title: "Thiết Kế Biệt Thự Tại TP.HCM", keyword: "thiết kế biệt thự TP.HCM", slug: "thiet-ke-biet-thu-tphcm", status: "planned" },
  { no: 378, title: "Thiết Kế Nhà Đẹp Tại TP.HCM", keyword: "thiết kế nhà đẹp TP.HCM", slug: "thiet-ke-nha-dep-tphcm", status: "planned" },
  { no: 379, title: "Kiến Trúc Nhà Phố Tại TP.HCM", keyword: "kiến trúc nhà phố TP.HCM", slug: "kien-truc-nha-pho-tphcm", status: "planned" },
  { no: 380, title: "Mẫu Nhà Phố Tại TP.HCM", keyword: "mẫu nhà phố TP.HCM", slug: "mau-nha-pho-tphcm", status: "planned" },
  { no: 381, title: "Chống Thấm Nhà Tại TP.HCM", keyword: "chống thấm nhà TP.HCM", slug: "chong-tham-nha-tphcm", status: "planned" },
  { no: 382, title: "Sửa Mái Nhà Tại TP.HCM", keyword: "sửa mái nhà TP.HCM", slug: "sua-mai-nha-tphcm", status: "planned" },
  { no: 383, title: "Sửa Nhà Thấm Dột Tại TP.HCM", keyword: "sửa nhà thấm dột TP.HCM", slug: "sua-nha-tham-dot-tphcm", status: "planned" },
  { no: 384, title: "Gia Cố Nhà Cũ Tại TP.HCM", keyword: "gia cố nhà cũ TP.HCM", slug: "gia-co-nha-cu-tphcm", status: "planned" },
  { no: 385, title: "Sửa Tường Nứt Nhà Tại TP.HCM", keyword: "sửa tường nứt nhà TP.HCM", slug: "sua-tuong-nut-nha-tphcm", status: "planned" },
  { no: 386, title: "Sửa Điện Nước Nhà Tại TP.HCM", keyword: "sửa điện nước nhà TP.HCM", slug: "sua-dien-nuoc-nha-tphcm", status: "planned" },
  { no: 387, title: "Cải Tạo Mặt Tiền Nhà Tại TP.HCM", keyword: "cải tạo mặt tiền nhà TP.HCM", slug: "cai-tao-mat-tien-nha-tphcm", status: "planned" },
  { no: 388, title: "Cải Tạo Nhà Ống Tại TP.HCM", keyword: "cải tạo nhà ống TP.HCM", slug: "cai-tao-nha-ong-tphcm", status: "planned" },
  { no: 389, title: "Cải Tạo Sân Thượng Tại TP.HCM", keyword: "cải tạo sân thượng TP.HCM", slug: "cai-tao-san-thuong-tphcm", status: "planned" },
  { no: 390, title: "Xây Nhà Tại Bình Thạnh", keyword: "xây nhà Bình Thạnh", slug: "xay-nha-binh-thanh", status: "planned" },
  { no: 391, title: "Xây Nhà Tại Thủ Đức", keyword: "xây nhà Thủ Đức", slug: "xay-nha-thu-duc", status: "planned" },
  { no: 392, title: "Xây Nhà Quận 7 TP.HCM", keyword: "xây nhà Quận 7", slug: "xay-nha-quan-7", status: "planned" },
  { no: 393, title: "Xây Nhà Quận 2 TP.HCM", keyword: "xây nhà Quận 2", slug: "xay-nha-quan-2", status: "planned" },
  { no: 394, title: "Xây Nhà Gò Vấp", keyword: "xây nhà Gò Vấp", slug: "xay-nha-go-vap", status: "planned" },
  { no: 395, title: "Xây Nhà Tân Phú", keyword: "xây nhà Tân Phú", slug: "xay-nha-tan-phu", status: "planned" },
  { no: 396, title: "Xây Nhà Nhà Bè", keyword: "xây nhà Nhà Bè", slug: "xay-nha-nha-be", status: "planned" },
];
