/**
 * Lịch từ khóa SEO — Long An & Đồng Nai (#91–#120).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const longAnDongNaiKeywordCalendar: ContentCalendarItem[] = [
  // —— Long An (15) ——
  {
    no: 91,
    title: "Công Ty Xây Dựng Uy Tín Tại Long An",
    keyword: "công ty xây dựng Long An",
    slug: "cong-ty-xay-dung-long-an",
    status: "done",
  },
  {
    no: 92,
    title: "Xây Nhà Trọn Gói Giá Tốt Tại Long An",
    keyword: "xây nhà trọn gói Long An",
    slug: "xay-nha-tron-goi-long-an",
    status: "done",
  },
  {
    no: 93,
    title: "Thi Công Nhà Phố Hiện Đại Tại Long An",
    keyword: "thi công nhà phố Long An",
    slug: "thi-cong-nha-pho-long-an",
    status: "done",
  },
  {
    no: 94,
    title: "Dịch Vụ Thiết Kế Nhà Phố Tại Long An",
    keyword: "thiết kế nhà phố Long An",
    slug: "thiet-ke-nha-pho-long-an",
    status: "done",
  },
  {
    no: 95,
    title: "Báo Giá Xây Nhà Trọn Gói Tại Long An",
    keyword: "báo giá xây nhà Long An",
    slug: "bao-gia-xay-nha-long-an",
    status: "done",
  },
  {
    no: 96,
    title: "Chi Phí Xây Nhà Tại Long An Bao Nhiêu?",
    keyword: "chi phí xây nhà Long An",
    slug: "chi-phi-xay-nha-long-an",
    status: "done",
  },
  {
    no: 97,
    title: "Mẫu Nhà Phố Đẹp Tại Long An",
    keyword: "nhà phố Long An",
    slug: "nha-pho-long-an",
    status: "done",
  },
  {
    no: 98,
    title: "Xây Nhà Tại Tân An Long An",
    keyword: "xây nhà Tân An Long An",
    slug: "xay-nha-tan-an-long-an",
    status: "done",
  },
  {
    no: 99,
    title: "Xây Nhà Tại Bến Lức Long An",
    keyword: "xây nhà Bến Lức Long An",
    slug: "xay-nha-ben-luc-long-an",
    status: "done",
  },
  {
    no: 100,
    title: "Xây Nhà Tại Cần Giuộc Long An",
    keyword: "xây nhà Cần Giuộc Long An",
    slug: "xay-nha-can-giuoc-long-an",
    status: "done",
  },
  {
    no: 101,
    title: "Thi Công Nhà Phần Thô Tại Long An",
    keyword: "thi công nhà phần thô Long An",
    slug: "thi-cong-nha-phan-tho-long-an",
    status: "done",
  },
  {
    no: 102,
    title: "Xây Nhà 2 Tầng Tại Long An — Báo Giá & Mẫu",
    keyword: "xây nhà 2 tầng Long An",
    slug: "xay-nha-2-tang-long-an",
    status: "done",
  },
  {
    no: 103,
    title: "Nhà Thầu Xây Dựng Uy Tín Tại Long An",
    keyword: "nhà thầu xây dựng Long An",
    slug: "nha-thau-xay-dung-long-an",
    status: "done",
  },
  {
    no: 104,
    title: "Hoàn Thiện Nhà Phần Thô Tại Long An",
    keyword: "hoàn thiện nhà Long An",
    slug: "hoan-thien-nha-long-an",
    status: "done",
  },
  {
    no: 105,
    title: "Sửa Chữa Nhà Cũ Tại Long An",
    keyword: "sửa chữa nhà Long An",
    slug: "sua-chua-nha-long-an",
    status: "done",
  },

  // —— Đồng Nai (15) ——
  {
    no: 106,
    title: "Công Ty Xây Dựng Uy Tín Tại Đồng Nai",
    keyword: "xây dựng nhà Đồng Nai",
    slug: "xay-dung-nha-dong-nai",
    status: "done",
  },
  {
    no: 107,
    title: "Công Ty Xây Dựng Chuyên Nghiệp Tại Đồng Nai",
    keyword: "công ty xây dựng Đồng Nai",
    slug: "cong-ty-xay-dung-dong-nai",
    status: "done",
  },
  {
    no: 108,
    title: "Thiết Kế Nhà Phố Đẹp Tại Đồng Nai",
    keyword: "thiết kế nhà phố Đồng Nai",
    slug: "thiet-ke-nha-pho-dong-nai",
    status: "done",
  },
  {
    no: 109,
    title: "Báo Giá Xây Nhà Trọn Gói Tại Đồng Nai",
    keyword: "báo giá xây nhà Đồng Nai",
    slug: "bao-gia-xay-nha-dong-nai",
    status: "done",
  },
  {
    no: 110,
    title: "Chi Phí Xây Nhà Tại Đồng Nai (2026)",
    keyword: "chi phí xây nhà Đồng Nai",
    slug: "chi-phi-xay-nha-dong-nai",
    status: "done",
  },
  {
    no: 111,
    title: "Mẫu Nhà Phố Hiện Đại Tại Đồng Nai",
    keyword: "nhà phố Đồng Nai",
    slug: "nha-pho-dong-nai",
    status: "done",
  },
  {
    no: 112,
    title: "Xây Nhà Tại Biên Hòa Đồng Nai",
    keyword: "xây nhà Biên Hòa Đồng Nai",
    slug: "xay-nha-bien-hoa-dong-nai",
    status: "done",
  },
  {
    no: 113,
    title: "Xây Nhà Tại Long Thành Đồng Nai",
    keyword: "xây nhà Long Thành Đồng Nai",
    slug: "xay-nha-long-thanh-dong-nai",
    status: "done",
  },
  {
    no: 114,
    title: "Xây Nhà Tại Nhơn Trạch Đồng Nai",
    keyword: "xây nhà Nhơn Trạch Đồng Nai",
    slug: "xay-nha-nhon-trach-dong-nai",
    status: "done",
  },
  {
    no: 115,
    title: "Thi Công Nhà Trọn Gói Tại Đồng Nai",
    keyword: "thi công nhà trọn gói Đồng Nai",
    slug: "thi-cong-nha-tron-goi-dong-nai",
    status: "done",
  },
  {
    no: 116,
    title: "Xây Nhà 2 Tầng Tại Đồng Nai",
    keyword: "xây nhà 2 tầng Đồng Nai",
    slug: "xay-nha-2-tang-dong-nai",
    status: "done",
  },
  {
    no: 117,
    title: "Top Mẫu Nhà Phố Đẹp Tại Đồng Nai",
    keyword: "mẫu nhà phố Đồng Nai",
    slug: "mau-nha-pho-dong-nai",
    status: "done",
  },
  {
    no: 118,
    title: "Xây Biệt Thự Tại Đồng Nai",
    keyword: "xây biệt thự Đồng Nai",
    slug: "xay-biet-thu-dong-nai",
    status: "done",
  },
  {
    no: 119,
    title: "Nhà Thầu Xây Dựng Uy Tín Tại Đồng Nai",
    keyword: "nhà thầu xây dựng Đồng Nai",
    slug: "nha-thau-xay-dung-dong-nai",
    status: "done",
  },
  {
    no: 120,
    title: "Sửa Chữa Nhà Cũ Tại Đồng Nai",
    keyword: "sửa chữa nhà Đồng Nai",
    slug: "sua-chua-nha-dong-nai",
    status: "done",
  },
];
