/**
 * Lịch từ khóa SEO — batch 3: 30 bài Phú Yên & Đắk Lắk (#61–#90).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const phuYenDakLakKeywordCalendarBatch3: ContentCalendarItem[] = [
  // —— Phú Yên (15) ——
  {
    no: 61,
    title: "Thi Công Nhà Trọn Gói Tại Phú Yên",
    keyword: "thi công nhà trọn gói Phú Yên",
    slug: "thi-cong-nha-tron-goi-phu-yen",
    status: "done",
  },
  {
    no: 62,
    title: "Thiết Kế Biệt Thự Đẹp Tại Phú Yên",
    keyword: "thiết kế biệt thự Phú Yên",
    slug: "thiet-ke-biet-thu-phu-yen",
    status: "done",
  },
  {
    no: 63,
    title: "Xây Nhà 3 Tầng Tại Phú Yên — Chi Phí & Mẫu Đẹp",
    keyword: "xây nhà 3 tầng Phú Yên",
    slug: "xay-nha-3-tang-phu-yen",
    status: "done",
  },
  {
    no: 64,
    title: "Xây Nhà 1 Trệt 1 Lầu Tại Phú Yên",
    keyword: "xây nhà 1 trệt 1 lầu Phú Yên",
    slug: "xay-nha-1-tret-1-lau-phu-yen",
    status: "done",
  },
  {
    no: 65,
    title: "Mẫu Nhà Ống Đẹp Tại Phú Yên",
    keyword: "nhà ống Phú Yên",
    slug: "nha-ong-phu-yen",
    status: "done",
  },
  {
    no: 66,
    title: "Xây Homestay Ven Biển Tại Phú Yên",
    keyword: "xây homestay Phú Yên",
    slug: "xay-homestay-phu-yen",
    status: "done",
  },
  {
    no: 67,
    title: "Sửa Chữa Nhà Cũ Tại Phú Yên",
    keyword: "sửa chữa nhà Phú Yên",
    slug: "sua-chua-nha-phu-yen",
    status: "done",
  },
  {
    no: 68,
    title: "Cải Tạo Nhà Trọn Gói Tại Phú Yên",
    keyword: "cải tạo nhà Phú Yên",
    slug: "cai-tao-nha-phu-yen",
    status: "done",
  },
  {
    no: 69,
    title: "Nâng Tầng Nhà Phố Tại Phú Yên",
    keyword: "nâng tầng nhà Phú Yên",
    slug: "nang-tang-nha-phu-yen",
    status: "done",
  },
  {
    no: 70,
    title: "Xin Giấy Phép Xây Dựng Tại Phú Yên",
    keyword: "xin giấy phép xây dựng Phú Yên",
    slug: "xin-giay-phep-xay-dung-phu-yen",
    status: "done",
  },
  {
    no: 71,
    title: "Xây Nhà Giá Rẻ Tại Phú Yên",
    keyword: "xây nhà giá rẻ Phú Yên",
    slug: "xay-nha-gia-re-phu-yen",
    status: "done",
  },
  {
    no: 72,
    title: "Thi Công Nhà Phố Tại Tuy Hòa",
    keyword: "thi công nhà phố Tuy Hòa",
    slug: "thi-cong-nha-pho-tuy-hoa",
    status: "done",
  },
  {
    no: 73,
    title: "Xây Nhà Tại Đông Hòa Phú Yên",
    keyword: "xây nhà Đông Hòa Phú Yên",
    slug: "xay-nha-dong-hoa-phu-yen",
    status: "done",
  },
  {
    no: 74,
    title: "Xây Nhà Tại Tuy An Phú Yên",
    keyword: "xây nhà Tuy An Phú Yên",
    slug: "xay-nha-tuy-an-phu-yen",
    status: "done",
  },
  {
    no: 75,
    title: "Xây Nhà Vườn Tại Phú Yên",
    keyword: "nhà vườn Phú Yên",
    slug: "xay-nha-vuon-phu-yen",
    status: "done",
  },

  // —— Đắk Lắk (15) ——
  {
    no: 76,
    title: "Thi Công Nhà Trọn Gói Tại Đắk Lắk",
    keyword: "thi công nhà trọn gói Đắk Lắk",
    slug: "thi-cong-nha-tron-goi-dak-lak",
    status: "done",
  },
  {
    no: 77,
    title: "Thiết Kế Nhà Đẹp Tại Đắk Lắk",
    keyword: "thiết kế nhà đẹp Đắk Lắk",
    slug: "thiet-ke-nha-dep-dak-lak",
    status: "done",
  },
  {
    no: 78,
    title: "Xây Nhà 2 Tầng Tại Buôn Ma Thuột",
    keyword: "xây nhà 2 tầng Buôn Ma Thuột",
    slug: "xay-nha-2-tang-buon-ma-thuot",
    status: "done",
  },
  {
    no: 79,
    title: "Mẫu Nhà Ống Đẹp Tại Đắk Lắk",
    keyword: "nhà ống Đắk Lắk",
    slug: "nha-ong-dak-lak",
    status: "done",
  },
  {
    no: 80,
    title: "Xây Nhà Vườn Tại Đắk Lắk",
    keyword: "xây nhà vườn Đắk Lắk",
    slug: "xay-nha-vuon-dak-lak",
    status: "done",
  },
  {
    no: 81,
    title: "Sửa Chữa Nhà Cũ Tại Đắk Lắk",
    keyword: "sửa chữa nhà Đắk Lắk",
    slug: "sua-chua-nha-dak-lak",
    status: "done",
  },
  {
    no: 82,
    title: "Cải Tạo Nhà Trọn Gói Tại Đắk Lắk",
    keyword: "cải tạo nhà Đắk Lắk",
    slug: "cai-tao-nha-dak-lak",
    status: "done",
  },
  {
    no: 83,
    title: "Nâng Tầng Nhà Phố Tại Đắk Lắk",
    keyword: "nâng tầng nhà phố Đắk Lắk",
    slug: "nang-tang-nha-pho-dak-lak",
    status: "done",
  },
  {
    no: 84,
    title: "Xin Giấy Phép Xây Dựng Tại Đắk Lắk",
    keyword: "xin giấy phép xây dựng Đắk Lắk",
    slug: "xin-giay-phep-xay-dung-dak-lak",
    status: "done",
  },
  {
    no: 85,
    title: "Xây Nhà Giá Rẻ Tại Đắk Lắk",
    keyword: "xây nhà giá rẻ Đắk Lắk",
    slug: "xay-nha-gia-re-dak-lak",
    status: "done",
  },
  {
    no: 86,
    title: "Thi Công Nhà Phố Tại Buôn Ma Thuột",
    keyword: "thi công nhà phố Buôn Ma Thuột",
    slug: "thi-cong-nha-pho-buon-ma-thuot",
    status: "done",
  },
  {
    no: 87,
    title: "Xây Shophouse Kinh Doanh Tại Đắk Lắk",
    keyword: "xây shophouse Đắk Lắk",
    slug: "xay-shophouse-dak-lak",
    status: "done",
  },
  {
    no: 88,
    title: "Chi Phí Xây Nhà 3 Tầng Tại Đắk Lắk",
    keyword: "chi phí xây nhà 3 tầng Đắk Lắk",
    slug: "chi-phi-xay-nha-3-tang-dak-lak",
    status: "done",
  },
  {
    no: 89,
    title: "Xây Nhà Tại Ea Kar Đắk Lắk",
    keyword: "xây nhà Ea Kar Đắk Lắk",
    slug: "xay-nha-ea-kar-dak-lak",
    status: "done",
  },
  {
    no: 90,
    title: "Xây Nhà Tại Krông Búk Đắk Lắk",
    keyword: "xây nhà Krông Búk Đắk Lắk",
    slug: "xay-nha-krong-buk-dak-lak",
    status: "done",
  },
];
