/**
 * Lịch từ khóa SEO — 30 bài tập trung Phú Yên & Đắk Lắk (batch 2, #31–#60).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const phuYenDakLakKeywordCalendar: ContentCalendarItem[] = [
  // —— Phú Yên (15) ——
  {
    no: 31,
    title: "Công Ty Xây Dựng Uy Tín Tại Phú Yên",
    keyword: "công ty xây dựng Phú Yên",
    slug: "cong-ty-xay-dung-phu-yen",
    status: "done",
  },
  {
    no: 32,
    title: "Xây Nhà Trọn Gói Tại Tuy Hòa Phú Yên",
    keyword: "xây nhà Tuy Hòa",
    slug: "xay-nha-tuy-hoa",
    status: "done",
  },
  {
    no: 33,
    title: "Mẫu Nhà Phố Đẹp Tại Phú Yên",
    keyword: "nhà phố Phú Yên",
    slug: "nha-pho-phu-yen",
    status: "done",
  },
  {
    no: 34,
    title: "Thi Công Nhà Phần Thô Tại Phú Yên",
    keyword: "thi công nhà phần thô Phú Yên",
    slug: "thi-cong-nha-phan-tho-phu-yen",
    status: "done",
  },
  {
    no: 35,
    title: "Xây Biệt Thự Ven Biển Tại Phú Yên",
    keyword: "xây biệt thự Phú Yên",
    slug: "xay-biet-thu-phu-yen",
    status: "done",
  },
  {
    no: 36,
    title: "Chi Phí Xây Nhà Tại Phú Yên Bao Nhiêu?",
    keyword: "chi phí xây nhà Phú Yên",
    slug: "chi-phi-xay-nha-phu-yen",
    status: "done",
  },
  {
    no: 37,
    title: "Top Mẫu Nhà Phố Hiện Đại Tại Phú Yên",
    keyword: "mẫu nhà phố Phú Yên",
    slug: "mau-nha-pho-phu-yen",
    status: "done",
  },
  {
    no: 38,
    title: "Xây Nhà Ven Biển Tại Phú Yên — Giải Pháp Chống Muối",
    keyword: "xây nhà ven biển Phú Yên",
    slug: "xay-nha-ven-bien-phu-yen",
    status: "done",
  },
  {
    no: 39,
    title: "Dịch Vụ Thiết Kế Nhà Phố Tại Phú Yên",
    keyword: "thiết kế nhà phố Phú Yên",
    slug: "thiet-ke-nha-pho-phu-yen",
    status: "done",
  },
  {
    no: 40,
    title: "Nhà Thầu Xây Dựng Uy Tín Tại Phú Yên",
    keyword: "nhà thầu xây dựng Phú Yên",
    slug: "nha-thau-xay-dung-phu-yen",
    status: "done",
  },
  {
    no: 41,
    title: "Xây Nhà Tại Sông Cầu Phú Yên",
    keyword: "xây nhà Sông Cầu Phú Yên",
    slug: "xay-nha-song-cau-phu-yen",
    status: "done",
  },
  {
    no: 42,
    title: "Xây Nhà Cấp 4 Giá Rẻ Tại Phú Yên",
    keyword: "xây nhà cấp 4 Phú Yên",
    slug: "xay-nha-cap-4-phu-yen",
    status: "done",
  },
  {
    no: 43,
    title: "Hoàn Thiện Nhà Phần Thô Tại Phú Yên",
    keyword: "hoàn thiện nhà Phú Yên",
    slug: "hoan-thien-nha-phu-yen",
    status: "done",
  },
  {
    no: 44,
    title: "Xây Nhà 2 Tầng Tại Phú Yên — Báo Giá & Mẫu Đẹp",
    keyword: "xây nhà 2 tầng Phú Yên",
    slug: "xay-nha-2-tang-phu-yen",
    status: "done",
  },
  {
    no: 45,
    title: "Kiến Trúc Nhà Phố Hiện Đại Tại Phú Yên",
    keyword: "kiến trúc nhà phố Phú Yên",
    slug: "kien-truc-nha-pho-phu-yen",
    status: "done",
  },

  // —— Đắk Lắk (15) ——
  {
    no: 46,
    title: "Công Ty Xây Dựng Uy Tín Tại Đắk Lắk",
    keyword: "công ty xây dựng Đắk Lắk",
    slug: "cong-ty-xay-dung-dak-lak",
    status: "done",
  },
  {
    no: 47,
    title: "Xây Nhà Trọn Gói Tại Buôn Ma Thuột",
    keyword: "xây nhà Buôn Ma Thuột",
    slug: "xay-nha-buon-ma-thuot",
    status: "done",
  },
  {
    no: 48,
    title: "Mẫu Nhà Phố Đẹp Tại Buôn Ma Thuột",
    keyword: "nhà phố Buôn Ma Thuột",
    slug: "nha-pho-buon-ma-thuot",
    status: "done",
  },
  {
    no: 49,
    title: "Thi Công Nhà Phần Thô Tại Đắk Lắk",
    keyword: "thi công nhà phần thô Đắk Lắk",
    slug: "thi-cong-nha-phan-tho-dak-lak",
    status: "done",
  },
  {
    no: 50,
    title: "Xây Biệt Thự Vùng Cao Tại Đắk Lắk",
    keyword: "xây biệt thự Đắk Lắk",
    slug: "xay-biet-thu-dak-lak",
    status: "done",
  },
  {
    no: 51,
    title: "Báo Giá Xây Nhà Trọn Gói Tại Đắk Lắk",
    keyword: "báo giá xây nhà Đắk Lắk",
    slug: "bao-gia-xay-nha-dak-lak",
    status: "done",
  },
  {
    no: 52,
    title: "Top Mẫu Nhà Phố Hiện Đại Tại Đắk Lắk",
    keyword: "mẫu nhà phố Đắk Lắk",
    slug: "mau-nha-pho-dak-lak",
    status: "done",
  },
  {
    no: 53,
    title: "Xây Nhà 1 Trệt 1 Lầu Tại Đắk Lắk",
    keyword: "xây nhà 1 trệt 1 lầu Đắk Lắk",
    slug: "xay-nha-1-tret-1-lau-dak-lak",
    status: "done",
  },
  {
    no: 54,
    title: "Thiết Kế Biệt Thự Hiện Đại Tại Đắk Lắk",
    keyword: "thiết kế biệt thự Đắk Lắk",
    slug: "thiet-ke-biet-thu-dak-lak",
    status: "done",
  },
  {
    no: 55,
    title: "Nhà Thầu Xây Dựng Uy Tín Tại Đắk Lắk",
    keyword: "nhà thầu xây dựng Đắk Lắk",
    slug: "nha-thau-xay-dung-dak-lak",
    status: "done",
  },
  {
    no: 56,
    title: "Xây Nhà Tại Buôn Hồ Đắk Lắk",
    keyword: "xây nhà Buôn Hồ Đắk Lắk",
    slug: "xay-nha-buon-ho-dak-lak",
    status: "done",
  },
  {
    no: 57,
    title: "Xây Nhà Cấp 4 Giá Rẻ Tại Đắk Lắk",
    keyword: "xây nhà cấp 4 Đắk Lắk",
    slug: "xay-nha-cap-4-dak-lak",
    status: "done",
  },
  {
    no: 58,
    title: "Hoàn Thiện Nhà Phần Thô Tại Đắk Lắk",
    keyword: "hoàn thiện nhà Đắk Lắk",
    slug: "hoan-thien-nha-dak-lak",
    status: "done",
  },
  {
    no: 59,
    title: "Xây Nhà 3 Tầng Tại Đắk Lắk — Chi Phí & Quy Trình",
    keyword: "xây nhà 3 tầng Đắk Lắk",
    slug: "xay-nha-3-tang-dak-lak",
    status: "done",
  },
  {
    no: 60,
    title: "Kiến Trúc Nhà Phố Tây Nguyên Tại Đắk Lắk",
    keyword: "kiến trúc nhà phố Đắk Lắk",
    slug: "kien-truc-nha-pho-dak-lak",
    status: "done",
  },
];
