/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 20 (#1447–#1546).
 * Cluster: vật liệu & cấu kiện xây/hoàn thiện.
 * Suffix `-ngan` tránh trùng money pages / batch trước.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch20: ContentCalendarItem[] = [
  { no: 1447, title: "Thép Xây Nhà", keyword: "thép xây nhà", slug: "thep-xay-nha-ngan", status: "done" },
  { no: 1448, title: "Xi Măng Xây Nhà", keyword: "xi măng xây nhà", slug: "xi-mang-xay-nha-ngan", status: "done" },
  { no: 1449, title: "Gạch Xây Nhà", keyword: "gạch xây nhà", slug: "gach-xay-nha-ngan", status: "done" },
  { no: 1450, title: "Cát Đá Xây Nhà", keyword: "cát đá xây nhà", slug: "cat-da-xay-nha-ngan", status: "done" },
  { no: 1451, title: "Bê Tông Xây Nhà", keyword: "bê tông xây nhà", slug: "be-tong-xay-nha-ngan", status: "done" },
  { no: 1452, title: "Thép Việt Nhật", keyword: "thép việt nhật", slug: "thep-viet-nhat-ngan", status: "done" },
  { no: 1453, title: "Thép Hòa Phát", keyword: "thép hòa phát", slug: "thep-hoa-phat-ngan", status: "done" },
  { no: 1454, title: "Xi Măng Hà Tiên", keyword: "xi măng hà tiên", slug: "xi-mang-ha-tien-ngan", status: "done" },
  { no: 1455, title: "Gạch Block Nhà", keyword: "gạch block nhà", slug: "gach-block-nha-ngan", status: "done" },
  { no: 1456, title: "Gạch Ống Nhà", keyword: "gạch ống nhà", slug: "gach-ong-nha-ngan", status: "done" },
  { no: 1457, title: "Gạch Men Nhà", keyword: "gạch men nhà", slug: "gach-men-nha-ngan", status: "done" },
  { no: 1458, title: "Gạch Granite Nhà", keyword: "gạch granite nhà", slug: "gach-granite-nha-ngan", status: "done" },
  { no: 1459, title: "Đá Hoa Cương Nhà", keyword: "đá hoa cương nhà", slug: "da-hoa-cuong-nha-ngan", status: "done" },
  { no: 1460, title: "Đá Marble Nhà", keyword: "đá marble nhà", slug: "da-marble-nha-ngan", status: "done" },
  { no: 1461, title: "Sơn Dulux Nhà", keyword: "sơn dulux nhà", slug: "son-dulux-nha-ngan", status: "done" },
  { no: 1462, title: "Sơn Jotun Nhà", keyword: "sơn jotun nhà", slug: "son-jotun-nha-ngan", status: "done" },
  { no: 1463, title: "Sơn Nippon Nhà", keyword: "sơn nippon nhà", slug: "son-nippon-nha-ngan", status: "done" },
  { no: 1464, title: "Keo Chống Thấm", keyword: "keo chống thấm", slug: "keo-chong-tham-ngan", status: "done" },
  { no: 1465, title: "Sika Chống Thấm", keyword: "sika chống thấm", slug: "sika-chong-tham-ngan", status: "done" },
  { no: 1466, title: "Màng Chống Thấm", keyword: "màng chống thấm", slug: "mang-chong-tham-ngan", status: "done" },
  { no: 1467, title: "Ống PPR Nhà", keyword: "ống ppr nhà", slug: "ong-ppr-nha-ngan", status: "done" },
  { no: 1468, title: "Ống PVC Nhà", keyword: "ống pvc nhà", slug: "ong-pvc-nha-ngan", status: "done" },
  { no: 1469, title: "Dây Điện Nhà", keyword: "dây điện nhà", slug: "day-dien-nha-ngan", status: "done" },
  { no: 1470, title: "Aptomat Nhà", keyword: "aptomat nhà", slug: "aptomat-nha-ngan", status: "done" },
  { no: 1471, title: "Đèn LED Nhà", keyword: "đèn led nhà", slug: "den-led-nha-ngan", status: "done" },
  { no: 1472, title: "Quạt Trần Nhà", keyword: "quạt trần nhà", slug: "quat-tran-nha-ngan", status: "done" },
  { no: 1473, title: "Bồn Cầu Nhà", keyword: "bồn cầu nhà", slug: "bon-cau-nha-ngan", status: "done" },
  { no: 1474, title: "Lavabo Nhà", keyword: "lavabo nhà", slug: "lavabo-nha-ngan", status: "done" },
  { no: 1475, title: "Sen Tắm Nhà", keyword: "sen tắm nhà", slug: "sen-tam-nha-ngan", status: "done" },
  { no: 1476, title: "Bồn Rửa Chén", keyword: "bồn rửa chén", slug: "bon-rua-chen-ngan", status: "done" },
  { no: 1477, title: "Bếp Từ Nhà", keyword: "bếp từ nhà", slug: "bep-tu-nha-ngan", status: "done" },
  { no: 1478, title: "Máy Hút Mùi", keyword: "máy hút mùi", slug: "may-hut-mui-ngan", status: "done" },
  { no: 1479, title: "Tủ Lạnh Âm Tường", keyword: "tủ lạnh âm tường", slug: "tu-lanh-am-tuong-ngan", status: "done" },
  { no: 1480, title: "Máy Giặt Nhà", keyword: "máy giặt nhà", slug: "may-giat-nha-ngan", status: "done" },
  { no: 1481, title: "Bình Nóng Năng Lượng", keyword: "bình nóng năng lượng", slug: "binh-nong-nang-luong-ngan", status: "done" },
  { no: 1482, title: "Pin Năng Lượng Mặt Trời", keyword: "pin năng lượng mặt trời", slug: "pin-nang-luong-mat-troi-ngan", status: "done" },
  { no: 1483, title: "Inverter Nhà", keyword: "inverter nhà", slug: "inverter-nha-ngan", status: "done" },
  { no: 1484, title: "Điều Hòa Multi", keyword: "điều hòa multi", slug: "dieu-hoa-multi-ngan", status: "done" },
  { no: 1485, title: "Điều Hòa Treo Tường", keyword: "điều hòa treo tường", slug: "dieu-hoa-treo-tuong-ngan", status: "done" },
  { no: 1486, title: "Điều Hòa Âm Trần", keyword: "điều hòa âm trần", slug: "dieu-hoa-am-tran-ngan", status: "done" },
  { no: 1487, title: "Cửa Gỗ Nhà", keyword: "cửa gỗ nhà", slug: "cua-go-nha-ngan", status: "done" },
  { no: 1488, title: "Cửa Thép Nhà", keyword: "cửa thép nhà", slug: "cua-thep-nha-ngan", status: "done" },
  { no: 1489, title: "Cửa Nhựa Nhà", keyword: "cửa nhựa nhà", slug: "cua-nhua-nha-ngan", status: "done" },
  { no: 1490, title: "Cửa Kính Cường Lực", keyword: "cửa kính cường lực", slug: "cua-kinh-cuong-luc-ngan", status: "done" },
  { no: 1491, title: "Khóa Vân Tay Nhà", keyword: "khóa vân tay nhà", slug: "khoa-van-tay-nha-ngan", status: "done" },
  { no: 1492, title: "Chuông Cửa Camera", keyword: "chuông cửa camera", slug: "chuong-cua-camera-ngan", status: "done" },
  { no: 1493, title: "Rèm Cửa Nhà", keyword: "rèm cửa nhà", slug: "rem-cua-nha-ngan", status: "done" },
  { no: 1494, title: "Sàn SPC Nhà", keyword: "sàn spc nhà", slug: "san-spc-nha-ngan", status: "done" },
  { no: 1495, title: "Sàn Nhựa Nhà", keyword: "sàn nhựa nhà", slug: "san-nhua-nha-ngan", status: "done" },
  { no: 1496, title: "Thảm Trải Sàn Nhà", keyword: "thảm trải sàn nhà", slug: "tham-trai-san-nha-ngan", status: "done" },
  { no: 1497, title: "Giấy Dán Tường 3D", keyword: "giấy dán tường 3d", slug: "giay-dan-tuong-3d-ngan", status: "done" },
  { no: 1498, title: "Tấm Ốp Lam Sóng", keyword: "tấm ốp lam sóng", slug: "tam-op-lam-song-ngan", status: "done" },
  { no: 1499, title: "Tấm Ốp PVC", keyword: "tấm ốp pvc", slug: "tam-op-pvc-ngan", status: "done" },
  { no: 1500, title: "Tấm Compact WC", keyword: "tấm compact wc", slug: "tam-compact-wc-ngan", status: "done" },
  { no: 1501, title: "Vách Ngăn Compact", keyword: "vách ngăn compact", slug: "vach-ngan-compact-ngan", status: "done" },
  { no: 1502, title: "Lan Can Inox", keyword: "lan can inox", slug: "lan-can-inox-ngan", status: "done" },
  { no: 1503, title: "Lan Can Sắt Mỹ Thuật", keyword: "lan can sắt mỹ thuật", slug: "lan-can-sat-my-thuat-ngan", status: "done" },
  { no: 1504, title: "Cổng Sắt Mỹ Thuật", keyword: "cổng sắt mỹ thuật", slug: "cong-sat-my-thuat-ngan", status: "done" },
  { no: 1505, title: "Cổng Nhôm Đúc", keyword: "cổng nhôm đúc", slug: "cong-nhom-duc-ngan", status: "done" },
  { no: 1506, title: "Cổng Lùa Tự Động", keyword: "cổng lùa tự động", slug: "cong-lua-tu-dong-ngan", status: "done" },
  { no: 1507, title: "Mái Che Polycarbonate", keyword: "mái che polycarbonate", slug: "mai-che-polycarbonate-ngan", status: "done" },
  { no: 1508, title: "Mái Hiên Di Động", keyword: "mái hiên di động", slug: "mai-hien-di-dong-ngan", status: "done" },
  { no: 1509, title: "Bạt Che Nắng", keyword: "bạt che nắng", slug: "bat-che-nang-ngan", status: "done" },
  { no: 1510, title: "Lưới Chống Muỗi", keyword: "lưới chống muỗi", slug: "luoi-chong-muoi-ngan", status: "done" },
  { no: 1511, title: "Lưới An Toàn Ban Công", keyword: "lưới an toàn ban công", slug: "luoi-an-toan-ban-cong-ngan", status: "done" },
  { no: 1512, title: "Kính Low-E Nhà", keyword: "kính low-e nhà", slug: "kinh-low-e-nha-ngan", status: "done" },
  { no: 1513, title: "Kính Hộp Nhà", keyword: "kính hộp nhà", slug: "kinh-hop-nha-ngan", status: "done" },
  { no: 1514, title: "Kính Phản Quang", keyword: "kính phản quang", slug: "kinh-phan-quang-ngan", status: "done" },
  { no: 1515, title: "Phim Cách Nhiệt Kính", keyword: "phim cách nhiệt kính", slug: "phim-cach-nhiet-kinh-ngan", status: "done" },
  { no: 1516, title: "Tấm Cách Nhiệt Mái", keyword: "tấm cách nhiệt mái", slug: "tam-cach-nhiet-mai-ngan", status: "done" },
  { no: 1517, title: "Xốp XPS Cách Nhiệt", keyword: "xốp xps cách nhiệt", slug: "xop-xps-cach-nhiet-ngan", status: "done" },
  { no: 1518, title: "Bông Khoáng Cách Âm", keyword: "bông khoáng cách âm", slug: "bong-khoang-cach-am-ngan", status: "done" },
  { no: 1519, title: "Thạch Cao Cách Âm", keyword: "thạch cao cách âm", slug: "thach-cao-cach-am-ngan", status: "done" },
  { no: 1520, title: "Keo Dán Gạch", keyword: "keo dán gạch", slug: "keo-dan-gach-ngan", status: "done" },
  { no: 1521, title: "Keo Chà Ron", keyword: "keo chà ron", slug: "keo-cha-ron-ngan", status: "done" },
  { no: 1522, title: "Vữa Xây Nhà", keyword: "vữa xây nhà", slug: "vua-xay-nha-ngan", status: "done" },
  { no: 1523, title: "Vữa Tô Nhà", keyword: "vữa tô nhà", slug: "vua-to-nha-ngan", status: "done" },
  { no: 1524, title: "Bột Trét Tường", keyword: "bột trét tường", slug: "bot-tret-tuong-ngan", status: "done" },
  { no: 1525, title: "Sơn Lót Nhà", keyword: "sơn lót nhà", slug: "son-lot-nha-ngan", status: "done" },
  { no: 1526, title: "Sơn Phủ Nhà", keyword: "sơn phủ nhà", slug: "son-phu-nha-ngan", status: "done" },
  { no: 1527, title: "Sơn Epoxy Sàn", keyword: "sơn epoxy sàn", slug: "son-epoxy-san-ngan", status: "done" },
  { no: 1528, title: "Sàn Epoxy Nhà", keyword: "sàn epoxy nhà", slug: "san-epoxy-nha-ngan", status: "done" },
  { no: 1529, title: "Gạch Terrazzo", keyword: "gạch terrazzo", slug: "gach-terrazzo-ngan", status: "done" },
  { no: 1530, title: "Gạch Thông Gió", keyword: "gạch thông gió", slug: "gach-thong-gio-ngan", status: "done" },
  { no: 1531, title: "Gạch Bông Gió", keyword: "gạch bông gió", slug: "gach-bong-gio-ngan", status: "done" },
  { no: 1532, title: "Gạch Kính Nhà", keyword: "gạch kính nhà", slug: "gach-kinh-nha-ngan", status: "done" },
  { no: 1533, title: "Đá Ong Ốp Tường", keyword: "đá ong ốp tường", slug: "da-ong-op-tuong-ngan", status: "done" },
  { no: 1534, title: "Gỗ Nhựa Ngoài Trời", keyword: "gỗ nhựa ngoài trời", slug: "go-nhua-ngoai-troi-ngan", status: "done" },
  { no: 1535, title: "Sàn Gỗ Công Nghiệp", keyword: "sàn gỗ công nghiệp", slug: "san-go-cong-nghiep-ngan", status: "done" },
  { no: 1536, title: "Sàn Gỗ Tự Nhiên", keyword: "sàn gỗ tự nhiên", slug: "san-go-tu-nhien-ngan", status: "done" },
  { no: 1537, title: "Tấm Cemboard", keyword: "tấm cemboard", slug: "tam-cemboard-ngan", status: "done" },
  { no: 1538, title: "Tấm Smartboard", keyword: "tấm smartboard", slug: "tam-smartboard-ngan", status: "done" },
  { no: 1539, title: "Tôn Lạnh Mái", keyword: "tôn lạnh mái", slug: "ton-lanh-mai-ngan", status: "done" },
  { no: 1540, title: "Tôn Cách Nhiệt", keyword: "tôn cách nhiệt", slug: "ton-cach-nhiet-ngan", status: "done" },
  { no: 1541, title: "Ngói Màu Nhà", keyword: "ngói màu nhà", slug: "ngoi-mau-nha-ngan", status: "done" },
  { no: 1542, title: "Ngói Nhật Nhà", keyword: "ngói nhật nhà", slug: "ngoi-nhat-nha-ngan", status: "done" },
  { no: 1543, title: "Xà Gồ Thép Mái", keyword: "xà gồ thép mái", slug: "xa-go-thep-mai-ngan", status: "done" },
  { no: 1544, title: "Kèo Thép Mái", keyword: "kèo thép mái", slug: "keo-thep-mai-ngan", status: "done" },
  { no: 1545, title: "Bu Lông Neo Móng", keyword: "bu lông neo móng", slug: "bu-long-neo-mong-ngan", status: "done" },
  { no: 1546, title: "Thép Đai Nhà", keyword: "thép đai nhà", slug: "thep-dai-nha-ngan", status: "done" },
];
