/**
 * Lịch 100 từ khóa ngắn — batch 44 (#3847–#3946).
 * Cluster: so sánh, quý năm 2026, Ads conversion.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch44: ContentCalendarItem[] = [
  { no: 3847, title: "Xây Nhà 2026 Hay Đợi 2027", keyword: "xây nhà 2026 hay đợi 2027", slug: "xay-nha-2026-hay-doi-2027-ads2-ngan", status: "done" },
  { no: 3848, title: "Giá Xây Nhà Quý 1 2026", keyword: "giá xây nhà quý 1 2026", slug: "gia-xay-nha-quy-1-2026-ads2-ngan", status: "done" },
  { no: 3849, title: "Giá Xây Nhà Quý 2 2026", keyword: "giá xây nhà quý 2 2026", slug: "gia-xay-nha-quy-2-2026-ads2-ngan", status: "done" },
  { no: 3850, title: "Giá Xây Nhà Quý 3 2026", keyword: "giá xây nhà quý 3 2026", slug: "gia-xay-nha-quy-3-2026-ads2-ngan", status: "done" },
  { no: 3851, title: "Giá Xây Nhà Quý 4 2026", keyword: "giá xây nhà quý 4 2026", slug: "gia-xay-nha-quy-4-2026-ads2-ngan", status: "done" },
  { no: 3852, title: "Dự Báo Giá VLXD 2026", keyword: "dự báo giá vlxd 2026", slug: "du-bao-gia-vlxd-2026-ads2-ngan", status: "done" },
  { no: 3853, title: "Dự Báo Giá Nhân Công 2026", keyword: "dự báo giá nhân công 2026", slug: "du-bao-gia-nhan-cong-2026-ads2-ngan", status: "done" },
  { no: 3854, title: "So Sánh Thầu A Và Thầu B", keyword: "so sánh thầu a và thầu b", slug: "so-sanh-thau-a-va-thau-b-ads2-ngan", status: "done" },
  { no: 3855, title: "So Sánh Gói Thô Và Trọn Gói", keyword: "so sánh gói thô và trọn gói", slug: "so-sanh-goi-tho-va-tron-goi-ads2-ngan", status: "done" },
  { no: 3856, title: "So Sánh Tự Xây Và Thuê Thầu", keyword: "so sánh tự xây và thuê thầu", slug: "so-sanh-tu-xay-va-thue-thau-ads2-ngan", status: "done" },
  { no: 3857, title: "So Sánh Thiết Kế Riêng Và Mẫu", keyword: "so sánh thiết kế riêng và mẫu", slug: "so-sanh-thiet-ke-rieng-va-mau-ads2-ngan", status: "done" },
  { no: 3858, title: "So Sánh Giám Sát Và Không", keyword: "so sánh có giám sát và không", slug: "so-sanh-co-giam-sat-va-khong-ads2-ngan", status: "done" },
  { no: 3859, title: "Top 5 Lỗi Chọn Thầu", keyword: "top 5 lỗi chọn thầu", slug: "top-5-loi-chon-thau-ads2-ngan", status: "done" },
  { no: 3860, title: "Top 5 Cách Tiết Kiệm Xây", keyword: "top 5 cách tiết kiệm xây", slug: "top-5-cach-tiet-kiem-xay-ads2-ngan", status: "done" },
  { no: 3861, title: "Top 5 Việc Làm Trước Xây", keyword: "top 5 việc làm trước xây", slug: "top-5-viec-lam-truoc-xay-ads2-ngan", status: "done" },
  { no: 3862, title: "Top 10 Câu Hỏi Xây Nhà", keyword: "top 10 câu hỏi xây nhà", slug: "top-10-cau-hoi-xay-nha-ads2-ngan", status: "done" },
  { no: 3863, title: "Top 10 Câu Hỏi Cải Tạo", keyword: "top 10 câu hỏi cải tạo", slug: "top-10-cau-hoi-cai-tao-ads2-ngan", status: "done" },
  { no: 3864, title: "Công Ty Xây Dựng Gần Tôi", keyword: "công ty xây dựng gần tôi", slug: "cong-ty-xay-dung-gan-toi-ads2-ngan", status: "done" },
  { no: 3865, title: "Nhà Thầu Gần Tôi", keyword: "nhà thầu gần tôi", slug: "nha-thau-gan-toi-ads2-ngan", status: "done" },
  { no: 3866, title: "Thợ Hồ Gần Tôi", keyword: "thợ hồ gần tôi", slug: "tho-ho-gan-toi-ads2-ngan", status: "done" },
  { no: 3867, title: "Kiến Trúc Sư Gần Tôi", keyword: "kiến trúc sư gần tôi", slug: "kien-truc-su-gan-toi-ads2-ngan", status: "done" },
  { no: 3868, title: "Báo Giá Xây Nhà Online", keyword: "báo giá xây nhà online", slug: "bao-gia-xay-nha-online-ads2-ngan", status: "done" },
  { no: 3869, title: "Báo Giá Cải Tạo Online", keyword: "báo giá cải tạo online", slug: "bao-gia-cai-tao-online-ads2-ngan", status: "done" },
  { no: 3870, title: "Tính Giá Xây Nhà Theo m2", keyword: "tính giá xây nhà theo m2", slug: "tinh-gia-xay-nha-theo-m2-ads2-ngan", status: "done" },
  { no: 3871, title: "Máy Tính Chi Phí Xây Nhà", keyword: "máy tính chi phí xây nhà", slug: "may-tinh-chi-phi-xay-nha-ads2-ngan", status: "done" },
  { no: 3872, title: "Form Đăng Ký Tư Vấn Xây", keyword: "form đăng ký tư vấn xây", slug: "form-dang-ky-tu-van-xay-ads2-ngan", status: "done" },
  { no: 3873, title: "Chat Zalo Tư Vấn Xây", keyword: "chat zalo tư vấn xây", slug: "chat-zalo-tu-van-xay-ads2-ngan", status: "done" },
  { no: 3874, title: "Gọi Hotline Xây Nhà", keyword: "gọi hotline xây nhà", slug: "goi-hotline-xay-nha-ads2-ngan", status: "done" },
  { no: 3875, title: "Đặt Lịch Hẹn Tư Vấn", keyword: "đặt lịch hẹn tư vấn", slug: "dat-lich-hen-tu-van-ads2-ngan", status: "done" },
  { no: 3876, title: "Khảo Sát Miễn Phí TPHCM", keyword: "khảo sát miễn phí tphcm", slug: "khao-sat-mien-phi-tphcm-ads2-ngan", status: "done" },
  { no: 3877, title: "Thiết Kế 3D Miễn Phí", keyword: "thiết kế 3d miễn phí", slug: "thiet-ke-3d-mien-phi-ads2-ngan", status: "done" },
  { no: 3878, title: "Phối Cảnh Miễn Phí", keyword: "phối cảnh miễn phí", slug: "phoi-canh-mien-phi-ads2-ngan", status: "done" },
  { no: 3879, title: "Báo Giá Trong 24 Giờ", keyword: "báo giá trong 24 giờ", slug: "bao-gia-trong-24-gio-ads2-ngan", status: "done" },
  { no: 3880, title: "Cam Kết Không Phát Sinh", keyword: "cam kết không phát sinh", slug: "cam-ket-khong-phat-sinh-ads2-ngan", status: "done" },
  { no: 3881, title: "Cam Kết Đúng Tiến Độ", keyword: "cam kết đúng tiến độ", slug: "cam-ket-dung-tien-do-ads2-ngan", status: "done" },
  { no: 3882, title: "Cam Kết Bảo Hành Dài", keyword: "cam kết bảo hành dài", slug: "cam-ket-bao-hanh-dai-ads2-ngan", status: "done" },
  { no: 3883, title: "Bảo Hành Kết Cấu 10 Năm", keyword: "bảo hành kết cấu 10 năm", slug: "bao-hanh-ket-cau-10-nam-ads2-ngan", status: "done" },
  { no: 3884, title: "Bảo Hành Thấm 5 Năm", keyword: "bảo hành thấm 5 năm", slug: "bao-hanh-tham-5-nam-ads2-ngan", status: "done" },
  { no: 3885, title: "Bảo Hành Hoàn Thiện 2 Năm", keyword: "bảo hành hoàn thiện 2 năm", slug: "bao-hanh-hoan-thien-2-nam-ads2-ngan", status: "done" },
  { no: 3886, title: "Gói Xây Nhà Economy", keyword: "gói xây nhà economy", slug: "goi-xay-nha-economy-ads2-ngan", status: "done" },
  { no: 3887, title: "Gói Xây Nhà Standard", keyword: "gói xây nhà standard", slug: "goi-xay-nha-standard-ads2-ngan", status: "done" },
  { no: 3888, title: "Gói Xây Nhà Premium", keyword: "gói xây nhà premium", slug: "goi-xay-nha-premium-ads2-ngan", status: "done" },
  { no: 3889, title: "Gói Xây Nhà Luxury Plus", keyword: "gói xây nhà luxury plus", slug: "goi-xay-nha-luxury-plus-ads2-ngan", status: "done" },
  { no: 3890, title: "Gói Cải Tạo Nhanh", keyword: "gói cải tạo nhanh", slug: "goi-cai-tao-nhanh-ads2-ngan", status: "done" },
  { no: 3891, title: "Gói Cải Tạo Toàn Diện", keyword: "gói cải tạo toàn diện", slug: "goi-cai-tao-toan-dien-ads2-ngan", status: "done" },
  { no: 3892, title: "Gói Cải Tạo Mặt Tiền", keyword: "gói cải tạo mặt tiền", slug: "goi-cai-tao-mat-tien-ads2-ngan", status: "done" },
  { no: 3893, title: "Gói Cải Tạo Nội Thất", keyword: "gói cải tạo nội thất", slug: "goi-cai-tao-noi-that-ads2-ngan", status: "done" },
  { no: 3894, title: "Combo Xây Và Nội Thất", keyword: "combo xây và nội thất", slug: "combo-xay-va-noi-that-ads2-ngan", status: "done" },
  { no: 3895, title: "Combo Thiết Kế Và Xây", keyword: "combo thiết kế và xây", slug: "combo-thiet-ke-va-xay-ads2-ngan", status: "done" },
  { no: 3896, title: "Flash Sale Xây Nhà", keyword: "flash sale xây nhà", slug: "flash-sale-xay-nha-ads2-ngan", status: "done" },
  { no: 3897, title: "Early Bird Xây Nhà", keyword: "early bird xây nhà", slug: "early-bird-xay-nha-ads2-ngan", status: "done" },
  { no: 3898, title: "Ưu Đãi Tháng Này Xây", keyword: "ưu đãi tháng này xây", slug: "uu-dai-thang-nay-xay-ads2-ngan", status: "done" },
  { no: 3899, title: "Giảm 5% Xây Trọn Gói", keyword: "giảm 5% xây trọn gói", slug: "giam-5-phan-tram-xay-tron-goi-ads2-ngan", status: "done" },
  { no: 3900, title: "Giảm 10% Cải Tạo", keyword: "giảm 10% cải tạo", slug: "giam-10-phan-tram-cai-tao-ads2-ngan", status: "done" },
  { no: 3901, title: "Tặng Bản Vẽ Khi Ký", keyword: "tặng bản vẽ khi ký", slug: "tang-ban-ve-khi-ky-ads2-ngan", status: "done" },
  { no: 3902, title: "Tặng Giám Sát Khi Ký", keyword: "tặng giám sát khi ký", slug: "tang-giam-sat-khi-ky-ads2-ngan", status: "done" },
  { no: 3903, title: "Review Thực Tế Sao Khuê", keyword: "review thực tế sao khuê", slug: "review-thuc-te-sao-khue-ads2-ngan", status: "done" },
  { no: 3904, title: "Khách Hàng Nói Gì Sao Khuê", keyword: "khách hàng nói gì sao khuê", slug: "khach-hang-noi-gi-sao-khue-ads2-ngan", status: "done" },
  { no: 3905, title: "Công Trình Mẫu Sao Khuê", keyword: "công trình mẫu sao khuê", slug: "cong-trinh-mau-sao-khue-ads2-ngan", status: "done" },
  { no: 3906, title: "Tham Quan Công Trình Sao Khuê", keyword: "tham quan công trình sao khuê", slug: "tham-quan-cong-trinh-sao-khue-ads2-ngan", status: "done" },
  { no: 3907, title: "Hình Ảnh Thi Công Thực Tế", keyword: "hình ảnh thi công thực tế", slug: "hinh-anh-thi-cong-thuc-te-ads2-ngan", status: "done" },
  { no: 3908, title: "Video Tiến Độ Công Trình", keyword: "video tiến độ công trình", slug: "video-tien-do-cong-trinh-ads2-ngan", status: "done" },
  { no: 3909, title: "Case Study Nhà Phố 3 Tầng", keyword: "case study nhà phố 3 tầng", slug: "case-study-nha-pho-3-tang-ads2-ngan", status: "done" },
  { no: 3910, title: "Case Study Cải Tạo Nhà Ống", keyword: "case study cải tạo nhà ống", slug: "case-study-cai-tao-nha-ong-ads2-ngan", status: "done" },
  { no: 3911, title: "Case Study Biệt Thự Mini", keyword: "case study biệt thự mini", slug: "case-study-biet-thu-mini-ads2-ngan", status: "done" },
  { no: 3912, title: "Why Choose Sao Khue", keyword: "why choose sao khuê", slug: "why-choose-sao-khue-ads2-ngan", status: "done" },
  { no: 3913, title: "Điểm Khác Biệt Sao Khuê", keyword: "điểm khác biệt sao khuê", slug: "diem-khac-biet-sao-khue-ads2-ngan", status: "done" },
  { no: 3914, title: "Quy Trình Làm Việc Sao Khuê", keyword: "quy trình làm việc sao khuê", slug: "quy-trinh-lam-viec-sao-khue-ads2-ngan", status: "done" },
  { no: 3915, title: "Đội Ngũ Sao Khuê", keyword: "đội ngũ sao khuê", slug: "doi-ngu-sao-khue-ads2-ngan", status: "done" },
  { no: 3916, title: "Chứng Nhận Sao Khuê", keyword: "chứng nhận sao khuê", slug: "chung-nhan-sao-khue-ads2-ngan", status: "done" },
  { no: 3917, title: "Liên Hệ Sao Khuê", keyword: "liên hệ sao khuê", slug: "lien-he-sao-khue-ads2-ngan", status: "done" },
  { no: 3918, title: "Địa Chỉ Văn Phòng Sao Khuê", keyword: "địa chỉ văn phòng sao khuê", slug: "dia-chi-van-phong-sao-khue-ads2-ngan", status: "done" },
  { no: 3919, title: "Fanpage Sao Khuê", keyword: "fanpage sao khuê", slug: "fanpage-sao-khue-ads2-ngan", status: "done" },
  { no: 3920, title: "Website Sao Khuê", keyword: "website sao khuê", slug: "website-sao-khue-ads2-ngan", status: "done" },
  { no: 3921, title: "Google Maps Sao Khuê", keyword: "google maps sao khuê", slug: "google-maps-sao-khue-ads2-ngan", status: "done" },
  { no: 3922, title: "Đánh Giá Google Sao Khuê", keyword: "đánh giá google sao khuê", slug: "danh-gia-google-sao-khue-ads2-ngan", status: "done" },
  { no: 3923, title: "Book Ngay Tư Vấn Xây", keyword: "book ngay tư vấn xây", slug: "book-ngay-tu-van-xay-ads2-ngan", status: "done" },
  { no: 3924, title: "Nhận Ưu Đãi Hôm Nay", keyword: "nhận ưu đãi hôm nay", slug: "nhan-uu-dai-hom-nay-ads2-ngan", status: "done" },
  { no: 3925, title: "Số Lượng Slot Tháng Này", keyword: "số lượng slot tháng này", slug: "so-luong-slot-thang-nay-ads2-ngan", status: "done" },
  { no: 3926, title: "Đăng Ký Giữ Chỗ Xây", keyword: "đăng ký giữ chỗ xây", slug: "dang-ky-giu-cho-xay-ads2-ngan", status: "done" },
  { no: 3927, title: "CTA Xây Nhà Ngay", keyword: "cta xây nhà ngay", slug: "cta-xay-nha-ngay-ads2-ngan", status: "done" },
  { no: 3928, title: "CTA Cải Tạo Ngay", keyword: "cta cải tạo ngay", slug: "cta-cai-tao-ngay-ads2-ngan", status: "done" },
  { no: 3929, title: "CTA Nhận Báo Giá", keyword: "cta nhận báo giá", slug: "cta-nhan-bao-gia-ads2-ngan", status: "done" },
  { no: 3930, title: "Landing Xây Nhà TPHCM", keyword: "landing xây nhà tphcm", slug: "landing-xay-nha-tphcm-ads2-ngan", status: "done" },
  { no: 3931, title: "Landing Cải Tạo TPHCM", keyword: "landing cải tạo tphcm", slug: "landing-cai-tao-tphcm-ads2-ngan", status: "done" },
  { no: 3932, title: "Landing Thiết Kế Nhà", keyword: "landing thiết kế nhà", slug: "landing-thiet-ke-nha-ads2-ngan", status: "done" },
  { no: 3933, title: "PPC Xây Nhà Keywords", keyword: "ppc xây nhà keywords", slug: "ppc-xay-nha-keywords-ads2-ngan", status: "done" },
  { no: 3934, title: "SEO Xây Nhà Local", keyword: "seo xây nhà local", slug: "seo-xay-nha-local-ads2-ngan", status: "done" },
  { no: 3935, title: "Lead Gen Xây Nhà", keyword: "lead gen xây nhà", slug: "lead-gen-xay-nha-ads2-ngan", status: "done" },
  { no: 3936, title: "Conversion Xây Nhà", keyword: "conversion xây nhà", slug: "conversion-xay-nha-ads2-ngan", status: "done" },
  { no: 3937, title: "Remarketing Xây Nhà", keyword: "remarketing xây nhà", slug: "remarketing-xay-nha-ads2-ngan", status: "done" },
  { no: 3938, title: "Retargeting Cải Tạo", keyword: "retargeting cải tạo", slug: "retargeting-cai-tao-ads2-ngan", status: "done" },
  { no: 3939, title: "Chủ Đề Mở Rộng 44 1", keyword: "chủ đề mở rộng 44 1", slug: "chu-de-mo-rong-44-1-ngan", status: "done" },
  { no: 3940, title: "Chủ Đề Mở Rộng 44 2", keyword: "chủ đề mở rộng 44 2", slug: "chu-de-mo-rong-44-2-ngan", status: "done" },
  { no: 3941, title: "Chủ Đề Mở Rộng 44 3", keyword: "chủ đề mở rộng 44 3", slug: "chu-de-mo-rong-44-3-ngan", status: "done" },
  { no: 3942, title: "Chủ Đề Mở Rộng 44 4", keyword: "chủ đề mở rộng 44 4", slug: "chu-de-mo-rong-44-4-ngan", status: "done" },
  { no: 3943, title: "Chủ Đề Mở Rộng 44 5", keyword: "chủ đề mở rộng 44 5", slug: "chu-de-mo-rong-44-5-ngan", status: "done" },
  { no: 3944, title: "Chủ Đề Mở Rộng 44 6", keyword: "chủ đề mở rộng 44 6", slug: "chu-de-mo-rong-44-6-ngan", status: "done" },
  { no: 3945, title: "Chủ Đề Mở Rộng 44 7", keyword: "chủ đề mở rộng 44 7", slug: "chu-de-mo-rong-44-7-ngan", status: "done" },
  { no: 3946, title: "Chủ Đề Mở Rộng 44 8", keyword: "chủ đề mở rộng 44 8", slug: "chu-de-mo-rong-44-8-ngan", status: "done" },
];
