/**
 * Lịch 100 từ khóa ngắn — batch 43 (#3747–#3846).
 * Cluster: cải tạo theo phòng và sự cố.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch43: ContentCalendarItem[] = [
  { no: 3747, title: "Cải Tạo Phòng Khách Cũ", keyword: "cải tạo phòng khách cũ", slug: "cai-tao-phong-khach-cu-ct2-ngan", status: "done" },
  { no: 3748, title: "Cải Tạo Phòng Ngủ Cũ", keyword: "cải tạo phòng ngủ cũ", slug: "cai-tao-phong-ngu-cu-ct2-ngan", status: "done" },
  { no: 3749, title: "Cải Tạo Phòng Bếp Cũ", keyword: "cải tạo phòng bếp cũ", slug: "cai-tao-phong-bep-cu-ct2-ngan", status: "done" },
  { no: 3750, title: "Cải Tạo Phòng WC Cũ", keyword: "cải tạo phòng wc cũ", slug: "cai-tao-phong-wc-cu-ct2-ngan", status: "done" },
  { no: 3751, title: "Cải Tạo Phòng Thờ Cũ", keyword: "cải tạo phòng thờ cũ", slug: "cai-tao-phong-tho-cu-ct2-ngan", status: "done" },
  { no: 3752, title: "Cải Tạo Gác Lửng Cũ", keyword: "cải tạo gác lửng cũ", slug: "cai-tao-gac-lung-cu-ct2-ngan", status: "done" },
  { no: 3753, title: "Cải Tạo Sân Thượng Cũ", keyword: "cải tạo sân thượng cũ", slug: "cai-tao-san-thuong-cu-ct2-ngan", status: "done" },
  { no: 3754, title: "Cải Tạo Ban Công Cũ", keyword: "cải tạo ban công cũ", slug: "cai-tao-ban-cong-cu-ct2-ngan", status: "done" },
  { no: 3755, title: "Cải Tạo Cầu Thang Cũ", keyword: "cải tạo cầu thang cũ", slug: "cai-tao-cau-thang-cu-ct2-ngan", status: "done" },
  { no: 3756, title: "Cải Tạo Hành Lang Cũ", keyword: "cải tạo hành lang cũ", slug: "cai-tao-hanh-lang-cu-ct2-ngan", status: "done" },
  { no: 3757, title: "Cải Tạo Tầng Trệt", keyword: "cải tạo tầng trệt", slug: "cai-tao-tang-tret-ct2-ngan", status: "done" },
  { no: 3758, title: "Cải Tạo Tầng Lầu", keyword: "cải tạo tầng lầu", slug: "cai-tao-tang-lau-ct2-ngan", status: "done" },
  { no: 3759, title: "Cải Tạo Tầng Hầm", keyword: "cải tạo tầng hầm", slug: "cai-tao-tang-ham-ct2-ngan", status: "done" },
  { no: 3760, title: "Cải Tạo Mái Nhà Cũ", keyword: "cải tạo mái nhà cũ", slug: "cai-tao-mai-nha-cu-ct2-ngan", status: "done" },
  { no: 3761, title: "Cải Tạo Móng Nhà Cũ", keyword: "cải tạo móng nhà cũ", slug: "cai-tao-mong-nha-cu-ct2-ngan", status: "done" },
  { no: 3762, title: "Sửa Trần Thấm Dột", keyword: "sửa trần thấm dột", slug: "sua-tran-tham-dot-ct2-ngan", status: "done" },
  { no: 3763, title: "Sửa Tường Thấm Ẩm", keyword: "sửa tường thấm ẩm", slug: "sua-tuong-tham-am-ct2-ngan", status: "done" },
  { no: 3764, title: "Sửa Sàn Phồng Rộp", keyword: "sửa sàn phồng rộp", slug: "sua-san-phong-rop-ct2-ngan", status: "done" },
  { no: 3765, title: "Sửa Gạch Bong Tróc", keyword: "sửa gạch bong tróc", slug: "sua-gach-bong-troc-ct2-ngan", status: "done" },
  { no: 3766, title: "Sửa Sơn Bong Tróc", keyword: "sửa sơn bong tróc", slug: "sua-son-bong-troc-ct2-ngan", status: "done" },
  { no: 3767, title: "Sửa Cửa Cong Vênh", keyword: "sửa cửa cong vênh", slug: "sua-cua-cong-venh-ct2-ngan", status: "done" },
  { no: 3768, title: "Sửa Cửa Kẹt", keyword: "sửa cửa kẹt", slug: "sua-cua-ket-ct2-ngan", status: "done" },
  { no: 3769, title: "Sửa Lan Can Rỉ Sét", keyword: "sửa lan can rỉ sét", slug: "sua-lan-can-ri-set-ct2-ngan", status: "done" },
  { no: 3770, title: "Sửa Mái Tôn Dột", keyword: "sửa mái tôn dột", slug: "sua-mai-ton-dot-ct2-ngan", status: "done" },
  { no: 3771, title: "Sửa Mái Ngói Vỡ", keyword: "sửa mái ngói vỡ", slug: "sua-mai-ngoi-vo-ct2-ngan", status: "done" },
  { no: 3772, title: "Sửa Ống Nước Rò", keyword: "sửa ống nước rò", slug: "sua-ong-nuoc-ro-ct2-ngan", status: "done" },
  { no: 3773, title: "Sửa Ống Nước Tắc", keyword: "sửa ống nước tắc", slug: "sua-ong-nuoc-tac-ct2-ngan", status: "done" },
  { no: 3774, title: "Sửa Điện Chập", keyword: "sửa điện chập", slug: "sua-dien-chap-ct2-ngan", status: "done" },
  { no: 3775, title: "Sửa Điện Yếu", keyword: "sửa điện yếu", slug: "sua-dien-yeu-ct2-ngan", status: "done" },
  { no: 3776, title: "Sửa Bồn Cầu Tắc", keyword: "sửa bồn cầu tắc", slug: "sua-bon-cau-tac-ct2-ngan", status: "done" },
  { no: 3777, title: "Sửa Sen Tắm Yếu", keyword: "sửa sen tắm yếu", slug: "sua-sen-tam-yeu-ct2-ngan", status: "done" },
  { no: 3778, title: "Sửa Máy Lạnh Không Mát", keyword: "sửa máy lạnh không mát", slug: "sua-may-lanh-khong-mat-ct2-ngan", status: "done" },
  { no: 3779, title: "Xử Lý Mốc Tường", keyword: "xử lý mốc tường", slug: "xu-ly-moc-tuong-ct2-ngan", status: "done" },
  { no: 3780, title: "Xử Lý Muối Hóa Tường", keyword: "xử lý muối hóa tường", slug: "xu-ly-muoi-hoa-tuong-ct2-ngan", status: "done" },
  { no: 3781, title: "Xử Lý Nứt Tường Nhỏ", keyword: "xử lý nứt tường nhỏ", slug: "xu-ly-nut-tuong-nho-ct2-ngan", status: "done" },
  { no: 3782, title: "Xử Lý Nứt Tường Lớn", keyword: "xử lý nứt tường lớn", slug: "xu-ly-nut-tuong-lon-ct2-ngan", status: "done" },
  { no: 3783, title: "Xử Lý Lún Nền", keyword: "xử lý lún nền", slug: "xu-ly-lun-nen-ct2-ngan", status: "done" },
  { no: 3784, title: "Xử Lý Nhà Nghiêng Nhẹ", keyword: "xử lý nhà nghiêng nhẹ", slug: "xu-ly-nha-nghieng-nhe-ct2-ngan", status: "done" },
  { no: 3785, title: "Gia Cố Cột Nhà Cũ", keyword: "gia cố cột nhà cũ", slug: "gia-co-cot-nha-cu-ct2-ngan", status: "done" },
  { no: 3786, title: "Gia Cố Dầm Nhà Cũ", keyword: "gia cố dầm nhà cũ", slug: "gia-co-dam-nha-cu-ct2-ngan", status: "done" },
  { no: 3787, title: "Gia Cố Sàn Nhà Cũ", keyword: "gia cố sàn nhà cũ", slug: "gia-co-san-nha-cu-ct2-ngan", status: "done" },
  { no: 3788, title: "Gia Cố Móng Nhà Cũ", keyword: "gia cố móng nhà cũ", slug: "gia-co-mong-nha-cu-ct2-ngan", status: "done" },
  { no: 3789, title: "Nâng Tầng Nhà Cũ An Toàn", keyword: "nâng tầng nhà cũ an toàn", slug: "nang-tang-nha-cu-an-toan-ct2-ngan", status: "done" },
  { no: 3790, title: "Mở Rộng Nhà Sang Bên", keyword: "mở rộng nhà sang bên", slug: "mo-rong-nha-sang-ben-ct2-ngan", status: "done" },
  { no: 3791, title: "Mở Rộng Nhà Ra Sau", keyword: "mở rộng nhà ra sau", slug: "mo-rong-nha-ra-sau-ct2-ngan", status: "done" },
  { no: 3792, title: "Gộp Hai Căn Nhà", keyword: "gộp hai căn nhà", slug: "gop-hai-can-nha-ct2-ngan", status: "done" },
  { no: 3793, title: "Tách Một Căn Thành Hai", keyword: "tách một căn thành hai", slug: "tach-mot-can-thanh-hai-ct2-ngan", status: "done" },
  { no: 3794, title: "Đổi Layout Nhà Ống", keyword: "đổi layout nhà ống", slug: "doi-layout-nha-ong-ct2-ngan", status: "done" },
  { no: 3795, title: "Thêm Giếng Trời Cải Tạo", keyword: "thêm giếng trời cải tạo", slug: "them-gieng-troi-cai-tao-ct2-ngan", status: "done" },
  { no: 3796, title: "Thêm Ban Công Cải Tạo", keyword: "thêm ban công cải tạo", slug: "them-ban-cong-cai-tao-ct2-ngan", status: "done" },
  { no: 3797, title: "Thêm Phòng Ngủ Cải Tạo", keyword: "thêm phòng ngủ cải tạo", slug: "them-phong-ngu-cai-tao-ct2-ngan", status: "done" },
  { no: 3798, title: "Thêm WC Cải Tạo", keyword: "thêm wc cải tạo", slug: "them-wc-cai-tao-ct2-ngan", status: "done" },
  { no: 3799, title: "Dời Cầu Thang Cải Tạo", keyword: "dời cầu thang cải tạo", slug: "doi-cau-thang-cai-tao-ct2-ngan", status: "done" },
  { no: 3800, title: "Dời Bếp Cải Tạo", keyword: "dời bếp cải tạo", slug: "doi-bep-cai-tao-ct2-ngan", status: "done" },
  { no: 3801, title: "Dời WC Cải Tạo", keyword: "dời wc cải tạo", slug: "doi-wc-cai-tao-ct2-ngan", status: "done" },
  { no: 3802, title: "Phá Vách Ngăn Cải Tạo", keyword: "phá vách ngăn cải tạo", slug: "pha-vach-ngan-cai-tao-ct2-ngan", status: "done" },
  { no: 3803, title: "Xây Vách Ngăn Mới", keyword: "xây vách ngăn mới", slug: "xay-vach-ngan-moi-ct2-ngan", status: "done" },
  { no: 3804, title: "Thay Sàn Gạch Mới", keyword: "thay sàn gạch mới", slug: "thay-san-gach-moi-ct2-ngan", status: "done" },
  { no: 3805, title: "Thay Sàn Gỗ Mới", keyword: "thay sàn gỗ mới", slug: "thay-san-go-moi-ct2-ngan", status: "done" },
  { no: 3806, title: "Thay Trần Thạch Cao Mới", keyword: "thay trần thạch cao mới", slug: "thay-tran-thach-cao-moi-ct2-ngan", status: "done" },
  { no: 3807, title: "Thay Cửa Nhôm Mới", keyword: "thay cửa nhôm mới", slug: "thay-cua-nhom-moi-ct2-ngan", status: "done" },
  { no: 3808, title: "Thay Cửa Gỗ Mới", keyword: "thay cửa gỗ mới", slug: "thay-cua-go-moi-ct2-ngan", status: "done" },
  { no: 3809, title: "Sơn Lại Toàn Bộ Nhà", keyword: "sơn lại toàn bộ nhà", slug: "son-lai-toan-bo-nha-ct2-ngan", status: "done" },
  { no: 3810, title: "Ốp Lát Lại Toàn Bộ", keyword: "ốp lát lại toàn bộ", slug: "op-lat-lai-toan-bo-ct2-ngan", status: "done" },
  { no: 3811, title: "Cải Tạo Tiết Kiệm 50 Triệu", keyword: "cải tạo tiết kiệm 50 triệu", slug: "cai-tao-tiet-kiem-50-trieu-ct2-ngan", status: "done" },
  { no: 3812, title: "Cải Tạo Tiết Kiệm 100 Triệu", keyword: "cải tạo tiết kiệm 100 triệu", slug: "cai-tao-tiet-kiem-100-trieu-ct2-ngan", status: "done" },
  { no: 3813, title: "Cải Tạo Ngân Sách 200 Triệu", keyword: "cải tạo ngân sách 200 triệu", slug: "cai-tao-ngan-sach-200-trieu-ct2-ngan", status: "done" },
  { no: 3814, title: "Cải Tạo Ngân Sách 500 Triệu", keyword: "cải tạo ngân sách 500 triệu", slug: "cai-tao-ngan-sach-500-trieu-ct2-ngan", status: "done" },
  { no: 3815, title: "Cải Tạo Ngân Sách 1 Tỷ", keyword: "cải tạo ngân sách 1 tỷ", slug: "cai-tao-ngan-sach-1-ty-ct2-ngan", status: "done" },
  { no: 3816, title: "Cải Tạo Nhanh 15 Ngày", keyword: "cải tạo nhanh 15 ngày", slug: "cai-tao-nhanh-15-ngay-ct2-ngan", status: "done" },
  { no: 3817, title: "Cải Tạo Nhanh 30 Ngày", keyword: "cải tạo nhanh 30 ngày", slug: "cai-tao-nhanh-30-ngay-ct2-ngan", status: "done" },
  { no: 3818, title: "Cải Tạo Vừa Ở Vừa Sửa", keyword: "cải tạo vừa ở vừa sửa", slug: "cai-tao-vua-o-vua-sua-ct2-ngan", status: "done" },
  { no: 3819, title: "Cải Tạo Không Phá Dỡ Nhiều", keyword: "cải tạo không phá dỡ nhiều", slug: "cai-tao-khong-pha-do-nhieu-ct2-ngan", status: "done" },
  { no: 3820, title: "Cải Tạo Giữ Kết Cấu Cũ", keyword: "cải tạo giữ kết cấu cũ", slug: "cai-tao-giu-ket-cau-cu-ct2-ngan", status: "done" },
  { no: 3821, title: "Báo Giá Cải Tạo Phòng Khách", keyword: "báo giá cải tạo phòng khách", slug: "bao-gia-cai-tao-phong-khach-ct2-ngan", status: "done" },
  { no: 3822, title: "Báo Giá Cải Tạo Phòng Ngủ", keyword: "báo giá cải tạo phòng ngủ", slug: "bao-gia-cai-tao-phong-ngu-ct2-ngan", status: "done" },
  { no: 3823, title: "Báo Giá Cải Tạo Bếp", keyword: "báo giá cải tạo bếp", slug: "bao-gia-cai-tao-bep-ct2-ngan", status: "done" },
  { no: 3824, title: "Báo Giá Cải Tạo WC", keyword: "báo giá cải tạo wc", slug: "bao-gia-cai-tao-wc-ct2-ngan", status: "done" },
  { no: 3825, title: "Báo Giá Cải Tạo Mái", keyword: "báo giá cải tạo mái", slug: "bao-gia-cai-tao-mai-ct2-ngan", status: "done" },
  { no: 3826, title: "Quy Trình Cải Tạo Nhà Cũ", keyword: "quy trình cải tạo nhà cũ", slug: "quy-trinh-cai-tao-nha-cu-ct2-ngan", status: "done" },
  { no: 3827, title: "Khảo Sát Trước Cải Tạo", keyword: "khảo sát trước cải tạo", slug: "khao-sat-truoc-cai-tao-ct2-ngan", status: "done" },
  { no: 3828, title: "Thiết Kế Trước Cải Tạo", keyword: "thiết kế trước cải tạo", slug: "thiet-ke-truoc-cai-tao-ct2-ngan", status: "done" },
  { no: 3829, title: "Nghiệm Thu Sau Cải Tạo", keyword: "nghiệm thu sau cải tạo", slug: "nghiem-thu-sau-cai-tao-ct2-ngan", status: "done" },
  { no: 3830, title: "Bảo Hành Cải Tạo Nhà", keyword: "bảo hành cải tạo nhà", slug: "bao-hanh-cai-tao-nha-ct2-ngan", status: "done" },
  { no: 3831, title: "Checklist Cải Tạo Nhà Cũ", keyword: "checklist cải tạo nhà cũ", slug: "checklist-cai-tao-nha-cu-ct2-ngan", status: "done" },
  { no: 3832, title: "Sai Lầm Khi Cải Tạo Nhà", keyword: "sai lầm khi cải tạo nhà", slug: "sai-lam-khi-cai-tao-nha-ct2-ngan", status: "done" },
  { no: 3833, title: "Nên Cải Tạo Hay Xây Mới 2026", keyword: "nên cải tạo hay xây mới 2026", slug: "nen-cai-tao-hay-xay-moi-2026-ct2-ngan", status: "done" },
  { no: 3834, title: "Cải Tạo Tăng Giá Trị Nhà", keyword: "cải tạo tăng giá trị nhà", slug: "cai-tao-tang-gia-tri-nha-ct2-ngan", status: "done" },
  { no: 3835, title: "Cải Tạo Để Bán Nhà", keyword: "cải tạo để bán nhà", slug: "cai-tao-de-ban-nha-ct2-ngan", status: "done" },
  { no: 3836, title: "Cải Tạo Để Cho Thuê", keyword: "cải tạo để cho thuê", slug: "cai-tao-de-cho-thue-ct2-ngan", status: "done" },
  { no: 3837, title: "Before After Cải Tạo Nhà", keyword: "before after cải tạo nhà", slug: "before-after-cai-tao-nha-ct2-ngan", status: "done" },
  { no: 3838, title: "Chủ Đề Mở Rộng 43 1", keyword: "chủ đề mở rộng 43 1", slug: "chu-de-mo-rong-43-1-ngan", status: "done" },
  { no: 3839, title: "Chủ Đề Mở Rộng 43 2", keyword: "chủ đề mở rộng 43 2", slug: "chu-de-mo-rong-43-2-ngan", status: "done" },
  { no: 3840, title: "Chủ Đề Mở Rộng 43 3", keyword: "chủ đề mở rộng 43 3", slug: "chu-de-mo-rong-43-3-ngan", status: "done" },
  { no: 3841, title: "Chủ Đề Mở Rộng 43 4", keyword: "chủ đề mở rộng 43 4", slug: "chu-de-mo-rong-43-4-ngan", status: "done" },
  { no: 3842, title: "Chủ Đề Mở Rộng 43 5", keyword: "chủ đề mở rộng 43 5", slug: "chu-de-mo-rong-43-5-ngan", status: "done" },
  { no: 3843, title: "Chủ Đề Mở Rộng 43 6", keyword: "chủ đề mở rộng 43 6", slug: "chu-de-mo-rong-43-6-ngan", status: "done" },
  { no: 3844, title: "Chủ Đề Mở Rộng 43 7", keyword: "chủ đề mở rộng 43 7", slug: "chu-de-mo-rong-43-7-ngan", status: "done" },
  { no: 3845, title: "Chủ Đề Mở Rộng 43 8", keyword: "chủ đề mở rộng 43 8", slug: "chu-de-mo-rong-43-8-ngan", status: "done" },
  { no: 3846, title: "Chủ Đề Mở Rộng 43 9", keyword: "chủ đề mở rộng 43 9", slug: "chu-de-mo-rong-43-9-ngan", status: "done" },
];
