/**
 * Lịch 100 từ khóa SEO — batch 65 (#5947–#6046).
 * Cluster: long-tail thương mại TP.HCM + tỉnh lân cận (indexable, slug *-sk65, không -ngan).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch65: ContentCalendarItem[] = [
  // 1–20: xây nhà / trọn gói khu vực
  { no: 5947, title: "Xây Nhà Phường Thảo Điền", keyword: "xây nhà phường Thảo Điền", slug: "xay-nha-phuong-thao-dien-sk65", status: "done" },
  { no: 5948, title: "Xây Nhà Phường An Phú Thủ Đức", keyword: "xây nhà phường An Phú Thủ Đức", slug: "xay-nha-phuong-an-phu-thu-duc-sk65", status: "done" },
  { no: 5949, title: "Xây Nhà Phường Bình Trưng Đông", keyword: "xây nhà phường Bình Trưng Đông", slug: "xay-nha-phuong-binh-trung-dong-sk65", status: "done" },
  { no: 5950, title: "Xây Nhà Phường Cát Lái", keyword: "xây nhà phường Cát Lái", slug: "xay-nha-phuong-cat-lai-sk65", status: "done" },
  { no: 5951, title: "Xây Nhà Phường Hiệp Phú", keyword: "xây nhà phường Hiệp Phú", slug: "xay-nha-phuong-hiep-phu-sk65", status: "done" },
  { no: 5952, title: "Xây Nhà Phường Tăng Nhơn Phú A", keyword: "xây nhà phường Tăng Nhơn Phú A", slug: "xay-nha-phuong-tang-nhon-phu-a-sk65", status: "done" },
  { no: 5953, title: "Xây Nhà Phường Phước Long B", keyword: "xây nhà phường Phước Long B", slug: "xay-nha-phuong-phuoc-long-b-sk65", status: "done" },
  { no: 5954, title: "Xây Nhà Phường Tân Phú Quận 7", keyword: "xây nhà phường Tân Phú Quận 7", slug: "xay-nha-phuong-tan-phu-quan-7-sk65", status: "done" },
  { no: 5955, title: "Xây Nhà Phường Tân Thuận Đông", keyword: "xây nhà phường Tân Thuận Đông", slug: "xay-nha-phuong-tan-thuan-dong-sk65", status: "done" },
  { no: 5956, title: "Xây Nhà Phường Bình Thuận Quận 7", keyword: "xây nhà phường Bình Thuận Quận 7", slug: "xay-nha-phuong-binh-thuan-quan-7-sk65", status: "done" },
  { no: 5957, title: "Xây Nhà Trọn Gói Quận Bình Thạnh 2026", keyword: "xây nhà trọn gói Bình Thạnh 2026", slug: "xay-nha-tron-goi-binh-thanh-2026-sk65", status: "done" },
  { no: 5958, title: "Xây Nhà Trọn Gói Gò Vấp 2026", keyword: "xây nhà trọn gói Gò Vấp 2026", slug: "xay-nha-tron-goi-go-vap-2026-sk65", status: "done" },
  { no: 5959, title: "Xây Nhà Trọn Gói Thủ Đức 2026", keyword: "xây nhà trọn gói Thủ Đức 2026", slug: "xay-nha-tron-goi-thu-duc-2026-sk65", status: "done" },
  { no: 5960, title: "Xây Nhà Hẻm Xe Máy TP.HCM", keyword: "xây nhà hẻm xe máy TP.HCM", slug: "xay-nha-hem-xe-may-tphcm-sk65", status: "done" },
  { no: 5961, title: "Xây Nhà Hẻm Xe Hơi TP.HCM", keyword: "xây nhà hẻm xe hơi TP.HCM", slug: "xay-nha-hem-xe-hoi-tphcm-sk65", status: "done" },
  { no: 5962, title: "Xây Nhà Liền Kề TP.HCM", keyword: "xây nhà liền kề TP.HCM", slug: "xay-nha-lien-ke-tphcm-sk65", status: "done" },
  { no: 5963, title: "Xây Nhà Có Thang Máy TP.HCM", keyword: "xây nhà có thang máy TP.HCM", slug: "xay-nha-co-thang-may-tphcm-sk65", status: "done" },
  { no: 5964, title: "Xây Nhà Mini 3×10 TP.HCM", keyword: "xây nhà mini 3x10 TP.HCM", slug: "xay-nha-mini-3x10-tphcm-sk65", status: "done" },
  { no: 5965, title: "Xây Nhà 5×20 TP.HCM", keyword: "xây nhà 5x20 TP.HCM", slug: "xay-nha-5x20-tphcm-sk65", status: "done" },
  { no: 5966, title: "Xây Nhà 1 Trệt 3 Lầu TP.HCM", keyword: "xây nhà 1 trệt 3 lầu TP.HCM", slug: "xay-nha-1-tret-3-lau-tphcm-sk65", status: "done" },

  // 21–40: cải tạo / sửa chữa
  { no: 5967, title: "Cải Tạo Nhà Phường 17 Bình Thạnh", keyword: "cải tạo nhà phường 17 Bình Thạnh", slug: "cai-tao-nha-phuong-17-binh-thanh-sk65", status: "done" },
  { no: 5968, title: "Cải Tạo Nhà Phường 5 Gò Vấp", keyword: "cải tạo nhà phường 5 Gò Vấp", slug: "cai-tao-nha-phuong-5-go-vap-sk65", status: "done" },
  { no: 5969, title: "Cải Tạo Nhà Cũ Thành Nhà Mới TP.HCM", keyword: "cải tạo nhà cũ thành nhà mới TP.HCM", slug: "cai-tao-nha-cu-thanh-nha-moi-tphcm-sk65", status: "done" },
  { no: 5970, title: "Cải Tạo Mặt Tiền Nhà Phố 2026", keyword: "cải tạo mặt tiền nhà phố 2026", slug: "cai-tao-mat-tien-nha-pho-2026-sk65", status: "done" },
  { no: 5971, title: "Cải Tạo Nhà Thêm Phòng Ngủ", keyword: "cải tạo nhà thêm phòng ngủ", slug: "cai-tao-nha-them-phong-ngu-sk65", status: "done" },
  { no: 5972, title: "Cải Tạo Nhà Thêm Phòng Làm Việc", keyword: "cải tạo nhà thêm phòng làm việc", slug: "cai-tao-nha-them-phong-lam-viec-sk65", status: "done" },
  { no: 5973, title: "Cải Tạo Sân Thượng Thành Phòng", keyword: "cải tạo sân thượng thành phòng", slug: "cai-tao-san-thuong-thanh-phong-sk65", status: "done" },
  { no: 5974, title: "Cải Tạo Nhà Không Phá Kết Cấu", keyword: "cải tạo nhà không phá kết cấu", slug: "cai-tao-nha-khong-pha-ket-cau-sk65", status: "done" },
  { no: 5975, title: "Sửa Nhà Thấm Trần TP.HCM", keyword: "sửa nhà thấm trần TP.HCM", slug: "sua-nha-tham-tran-tphcm-sk65", status: "done" },
  { no: 5976, title: "Sửa Nhà Nứt Cột Dầm TP.HCM", keyword: "sửa nhà nứt cột dầm TP.HCM", slug: "sua-nha-nut-cot-dam-tphcm-sk65", status: "done" },
  { no: 5977, title: "Sửa Điện Nước Nhà Cũ Trọn Gói", keyword: "sửa điện nước nhà cũ trọn gói", slug: "sua-dien-nuoc-nha-cu-tron-goi-sk65", status: "done" },
  { no: 5978, title: "Chống Thấm Sân Thượng Trọn Gói 2026", keyword: "chống thấm sân thượng trọn gói 2026", slug: "chong-tham-san-thuong-tron-goi-2026-sk65", status: "done" },
  { no: 5979, title: "Chống Thấm Mái Tôn Nhà Phố", keyword: "chống thấm mái tôn nhà phố", slug: "chong-tham-mai-ton-nha-pho-sk65", status: "done" },
  { no: 5980, title: "Nâng Tầng Nhà 2 Thành 3 Tầng", keyword: "nâng tầng nhà 2 thành 3 tầng", slug: "nang-tang-nha-2-thanh-3-tang-sk65", status: "done" },
  { no: 5981, title: "Nâng Tầng Nhà Có Xin Phép Không", keyword: "nâng tầng nhà có xin phép không", slug: "nang-tang-nha-co-xin-phep-khong-sk65", status: "done" },
  { no: 5982, title: "Cải Tạo Nhà Cho Thuê Phòng Trọ", keyword: "cải tạo nhà cho thuê phòng trọ", slug: "cai-tao-nha-cho-thue-phong-tro-sk65", status: "done" },
  { no: 5983, title: "Cải Tạo Nhà Thành Homestay", keyword: "cải tạo nhà thành homestay", slug: "cai-tao-nha-thanh-homestay-sk65", status: "done" },
  { no: 5984, title: "Sửa Chữa Nhà Đang Ở TP.HCM", keyword: "sửa chữa nhà đang ở TP.HCM", slug: "sua-chua-nha-dang-o-tphcm-sk65", status: "done" },
  { no: 5985, title: "Cải Tạo Bếp Mở Phòng Khách", keyword: "cải tạo bếp mở phòng khách", slug: "cai-tao-bep-mo-phong-khach-sk65", status: "done" },
  { no: 5986, title: "Cải Tạo WC Nhà Phố Tiêu Chuẩn", keyword: "cải tạo WC nhà phố tiêu chuẩn", slug: "cai-tao-wc-nha-pho-tieu-chuan-sk65", status: "done" },

  // 41–55: báo giá / chi phí
  { no: 5987, title: "Đơn Giá Xây Nhà Phố 2026 TP.HCM", keyword: "đơn giá xây nhà phố 2026 TP.HCM", slug: "don-gia-xay-nha-pho-2026-tphcm-sk65", status: "done" },
  { no: 5988, title: "Chi Phí Xây Nhà 4×16 Trọn Gói", keyword: "chi phí xây nhà 4x16 trọn gói", slug: "chi-phi-xay-nha-4x16-tron-goi-sk65", status: "done" },
  { no: 5989, title: "Chi Phí Xây Nhà 5×18 Trọn Gói", keyword: "chi phí xây nhà 5x18 trọn gói", slug: "chi-phi-xay-nha-5x18-tron-goi-sk65", status: "done" },
  { no: 5990, title: "Chi Phí Xây Nhà 1 Trệt 2 Lầu 2026", keyword: "chi phí xây nhà 1 trệt 2 lầu 2026", slug: "chi-phi-xay-nha-1-tret-2-lau-2026-sk65", status: "done" },
  { no: 5991, title: "Báo Giá Ép Cọc Nhà Phố 2026", keyword: "báo giá ép cọc nhà phố 2026", slug: "bao-gia-ep-coc-nha-pho-2026-sk65", status: "done" },
  { no: 5992, title: "Báo Giá Xin Phép Xây Dựng TP.HCM", keyword: "báo giá xin phép xây dựng TP.HCM", slug: "bao-gia-xin-phep-xay-dung-tphcm-sk65", status: "done" },
  { no: 5993, title: "Chi Phí Giám Sát Xây Nhà", keyword: "chi phí giám sát xây nhà", slug: "chi-phi-giam-sat-xay-nha-sk65", status: "done" },
  { no: 5994, title: "Chi Phí Thiết Kế Nhà Phố 2026", keyword: "chi phí thiết kế nhà phố 2026", slug: "chi-phi-thiet-ke-nha-pho-2026-sk65", status: "done" },
  { no: 5995, title: "Ngân Sách Xây Nhà 2 Tỷ TP.HCM", keyword: "ngân sách xây nhà 2 tỷ TP.HCM", slug: "ngan-sach-xay-nha-2-ty-tphcm-sk65", status: "done" },
  { no: 5996, title: "Ngân Sách Xây Nhà 3 Tỷ TP.HCM", keyword: "ngân sách xây nhà 3 tỷ TP.HCM", slug: "ngan-sach-xay-nha-3-ty-tphcm-sk65", status: "done" },
  { no: 5997, title: "Ngân Sách Xây Nhà 5 Tỷ TP.HCM", keyword: "ngân sách xây nhà 5 tỷ TP.HCM", slug: "ngan-sach-xay-nha-5-ty-tphcm-sk65", status: "done" },
  { no: 5998, title: "Báo Giá Cải Tạo Nhà 100 Triệu", keyword: "báo giá cải tạo nhà 100 triệu", slug: "bao-gia-cai-tao-nha-100-trieu-sk65", status: "done" },
  { no: 5999, title: "Báo Giá Cải Tạo Nhà 300 Triệu", keyword: "báo giá cải tạo nhà 300 triệu", slug: "bao-gia-cai-tao-nha-300-trieu-sk65", status: "done" },
  { no: 6000, title: "Đơn Giá Nhân Công Xây Nhà 2026", keyword: "đơn giá nhân công xây nhà 2026", slug: "don-gia-nhan-cong-xay-nha-2026-sk65", status: "done" },
  { no: 6001, title: "Chi Phí Phát Sinh Xây Nhà Thường Gặp", keyword: "chi phí phát sinh xây nhà thường gặp", slug: "chi-phi-phat-sinh-xay-nha-thuong-gap-sk65", status: "done" },

  // 56–70: thiết kế / phong cách
  { no: 6002, title: "Thiết Kế Nhà Phố Mái Nhật TP.HCM", keyword: "thiết kế nhà phố mái Nhật TP.HCM", slug: "thiet-ke-nha-pho-mai-nhat-tphcm-sk65", status: "done" },
  { no: 6003, title: "Thiết Kế Nhà Phố Mái Thái Hiện Đại", keyword: "thiết kế nhà phố mái Thái hiện đại", slug: "thiet-ke-nha-pho-mai-thai-hien-dai-sk65", status: "done" },
  { no: 6004, title: "Thiết Kế Nhà Phố Phong Cách Indochine", keyword: "thiết kế nhà phố Indochine", slug: "thiet-ke-nha-pho-indochine-sk65", status: "done" },
  { no: 6005, title: "Thiết Kế Nhà Phố Phong Cách Tối Giản", keyword: "thiết kế nhà phố tối giản", slug: "thiet-ke-nha-pho-toi-gian-sk65", status: "done" },
  { no: 6006, title: "Thiết Kế Nhà Phố Có Giếng Trời", keyword: "thiết kế nhà phố có giếng trời", slug: "thiet-ke-nha-pho-co-gieng-troi-sk65", status: "done" },
  { no: 6007, title: "Thiết Kế Nhà Phố Có Gara Oto", keyword: "thiết kế nhà phố có gara ô tô", slug: "thiet-ke-nha-pho-co-gara-oto-sk65", status: "done" },
  { no: 6008, title: "Thiết Kế Nhà Phố Kết Hợp Kinh Doanh", keyword: "thiết kế nhà phố kết hợp kinh doanh", slug: "thiet-ke-nha-pho-ket-hop-kinh-doanh-sk65", status: "done" },
  { no: 6009, title: "Thiết Kế Biệt Thự Mini TP.HCM", keyword: "thiết kế biệt thự mini TP.HCM", slug: "thiet-ke-biet-thu-mini-tphcm-sk65", status: "done" },
  { no: 6010, title: "Thiết Kế Nhà Vườn Long An", keyword: "thiết kế nhà vườn Long An", slug: "thiet-ke-nha-vuon-long-an-sk65", status: "done" },
  { no: 6011, title: "Thiết Kế Nhà Vườn Đồng Nai", keyword: "thiết kế nhà vườn Đồng Nai", slug: "thiet-ke-nha-vuon-dong-nai-sk65", status: "done" },
  { no: 6012, title: "Mẫu Nhà Phố 2 Tầng Đẹp 2026", keyword: "mẫu nhà phố 2 tầng đẹp 2026", slug: "mau-nha-pho-2-tang-dep-2026-sk65", status: "done" },
  { no: 6013, title: "Mẫu Nhà Phố 3 Tầng Đẹp 2026", keyword: "mẫu nhà phố 3 tầng đẹp 2026", slug: "mau-nha-pho-3-tang-dep-2026-sk65", status: "done" },
  { no: 6014, title: "Thiết Kế Nội Thất Nhà Phố 4m", keyword: "thiết kế nội thất nhà phố 4m", slug: "thiet-ke-noi-that-nha-pho-4m-sk65", status: "done" },
  { no: 6015, title: "Thiết Kế Phòng Khách Nhà Ống", keyword: "thiết kế phòng khách nhà ống", slug: "thiet-ke-phong-khach-nha-ong-sk65", status: "done" },
  { no: 6016, title: "Thiết Kế Phòng Ngủ Master Nhà Phố", keyword: "thiết kế phòng ngủ master nhà phố", slug: "thiet-ke-phong-ngu-master-nha-pho-sk65", status: "done" },

  // 71–85: kỹ thuật / vật liệu
  { no: 6017, title: "Xây Nhà Khung Thép Tiền Chế TP.HCM", keyword: "xây nhà khung thép tiền chế TP.HCM", slug: "xay-nha-khung-thep-tien-che-tphcm-sk65", status: "done" },
  { no: 6018, title: "Xây Nhà Bê Tông Cốt Thép Nhà Phố", keyword: "xây nhà bê tông cốt thép nhà phố", slug: "xay-nha-be-tong-cot-thep-nha-pho-sk65", status: "done" },
  { no: 6019, title: "Đổ Móng Nhà Phố Đúng Cách", keyword: "đổ móng nhà phố đúng cách", slug: "do-mong-nha-pho-dung-cach-sk65", status: "done" },
  { no: 6020, title: "Đổ Sàn Bê Tông Nhà Phố", keyword: "đổ sàn bê tông nhà phố", slug: "do-san-be-tong-nha-pho-sk65", status: "done" },
  { no: 6021, title: "Làm Mái Thái Nhà Phố TP.HCM", keyword: "làm mái Thái nhà phố TP.HCM", slug: "lam-mai-thai-nha-pho-tphcm-sk65", status: "done" },
  { no: 6022, title: "Làm Mái Bằng Chống Thấm", keyword: "làm mái bằng chống thấm", slug: "lam-mai-bang-chong-tham-sk65", status: "done" },
  { no: 6023, title: "Cách Nhiệt Mái Nhà Phố", keyword: "cách nhiệt mái nhà phố", slug: "cach-nhiet-mai-nha-pho-sk65", status: "done" },
  { no: 6024, title: "Lắp Cửa Nhôm Kính Nhà Phố", keyword: "lắp cửa nhôm kính nhà phố", slug: "lap-cua-nhom-kinh-nha-pho-sk65", status: "done" },
  { no: 6025, title: "Ốp Đá Mặt Tiền Nhà Phố", keyword: "ốp đá mặt tiền nhà phố", slug: "op-da-mat-tien-nha-pho-sk65", status: "done" },
  { no: 6026, title: "Sơn Ngoại Thất Nhà Phố Bền Màu", keyword: "sơn ngoại thất nhà phố bền màu", slug: "son-ngoai-that-nha-pho-ben-mau-sk65", status: "done" },
  { no: 6027, title: "Lát Gạch Nhà Phố Chống Trơn", keyword: "lát gạch nhà phố chống trơn", slug: "lat-gach-nha-pho-chong-tron-sk65", status: "done" },
  { no: 6028, title: "Làm Trần Thạch Cao Nhà Phố", keyword: "làm trần thạch cao nhà phố", slug: "lam-tran-thach-cao-nha-pho-sk65", status: "done" },
  { no: 6029, title: "Hệ Thống Điện 3 Pha Nhà Phố", keyword: "hệ thống điện 3 pha nhà phố", slug: "he-thong-dien-3-pha-nha-pho-sk65", status: "done" },
  { no: 6030, title: "Hệ Thống Nước Nóng Năng Lượng Mặt Trời", keyword: "nước nóng năng lượng mặt trời nhà phố", slug: "nuoc-nong-nang-luong-mat-troi-nha-pho-sk65", status: "done" },
  { no: 6031, title: "Gia Cố Móng Nhà Cũ Trước Nâng Tầng", keyword: "gia cố móng nhà cũ trước nâng tầng", slug: "gia-co-mong-nha-cu-truoc-nang-tang-sk65", status: "done" },

  // 86–100: geo tỉnh + quy trình quyết định
  { no: 6032, title: "Xây Nhà Trọn Gói Dĩ An Bình Dương", keyword: "xây nhà trọn gói Dĩ An", slug: "xay-nha-tron-goi-di-an-sk65", status: "done" },
  { no: 6033, title: "Xây Nhà Trọn Gói Thuận An 2026", keyword: "xây nhà trọn gói Thuận An 2026", slug: "xay-nha-tron-goi-thuan-an-2026-sk65", status: "done" },
  { no: 6034, title: "Xây Nhà Trọn Gói Biên Hòa", keyword: "xây nhà trọn gói Biên Hòa", slug: "xay-nha-tron-goi-bien-hoa-sk65", status: "done" },
  { no: 6035, title: "Xây Nhà Trọn Gói Long Thành", keyword: "xây nhà trọn gói Long Thành", slug: "xay-nha-tron-goi-long-thanh-sk65", status: "done" },
  { no: 6036, title: "Xây Nhà Trọn Gói Bến Lức Long An", keyword: "xây nhà trọn gói Bến Lức", slug: "xay-nha-tron-goi-ben-luc-sk65", status: "done" },
  { no: 6037, title: "Xây Nhà Trọn Gói Cần Giuộc", keyword: "xây nhà trọn gói Cần Giuộc", slug: "xay-nha-tron-goi-can-giuoc-sk65", status: "done" },
  { no: 6038, title: "Xây Nhà Trọn Gói Thủ Dầu Một", keyword: "xây nhà trọn gói Thủ Dầu Một", slug: "xay-nha-tron-goi-thu-dau-mot-sk65", status: "done" },
  { no: 6039, title: "Cải Tạo Nhà Dĩ An Bình Dương", keyword: "cải tạo nhà Dĩ An", slug: "cai-tao-nha-di-an-sk65", status: "done" },
  { no: 6040, title: "Cải Tạo Nhà Biên Hòa Đồng Nai", keyword: "cải tạo nhà Biên Hòa", slug: "cai-tao-nha-bien-hoa-sk65", status: "done" },
  { no: 6041, title: "Chọn Nhà Thầu Xây Nhà Uy Tín 2026", keyword: "chọn nhà thầu xây nhà uy tín 2026", slug: "chon-nha-thau-xay-nha-uy-tin-2026-sk65", status: "done" },
  { no: 6042, title: "Checklist Ký Hợp Đồng Xây Nhà 2026", keyword: "checklist ký hợp đồng xây nhà 2026", slug: "checklist-ky-hop-dong-xay-nha-2026-sk65", status: "done" },
  { no: 6043, title: "Cách Đọc Dự Toán Xây Nhà", keyword: "cách đọc dự toán xây nhà", slug: "cach-doc-du-toan-xay-nha-sk65", status: "done" },
  { no: 6044, title: "Lịch Thanh Toán Xây Nhà Hợp Lý", keyword: "lịch thanh toán xây nhà hợp lý", slug: "lich-thanh-toan-xay-nha-hop-ly-sk65", status: "done" },
  { no: 6045, title: "Nghiệm Thu Nhà Phố Trước Bàn Giao", keyword: "nghiệm thu nhà phố trước bàn giao", slug: "nghiem-thu-nha-pho-truoc-ban-giao-sk65", status: "done" },
  { no: 6046, title: "Bảo Hành Xây Nhà 10 Năm Là Gì", keyword: "bảo hành xây nhà 10 năm là gì", slug: "bao-hanh-xay-nha-10-nam-la-gi-sk65", status: "done" },
];
