/**
 * Lịch 100 từ khóa ngắn — batch 33 (#2747–#2846).
 * Cluster: loại hình thương mại, nhà trọ, homestay, PCCC.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch33: ContentCalendarItem[] = [
  { no: 2747, title: "Xây Nhà Ở Kết Hợp Kinh Doanh", keyword: "xây nhà ở kết hợp kinh doanh", slug: "xay-nha-o-ket-hop-kinh-doanh-ngan", status: "done" },
  { no: 2748, title: "Xây Nhà Mặt Tiền Cho Thuê", keyword: "xây nhà mặt tiền cho thuê", slug: "xay-nha-mat-tien-cho-thue-ngan", status: "done" },
  { no: 2749, title: "Xây Nhà Trọ Mini", keyword: "xây nhà trọ mini", slug: "xay-nha-tro-mini-ngan", status: "done" },
  { no: 2750, title: "Xây Nhà Trọ 10 Phòng", keyword: "xây nhà trọ 10 phòng", slug: "xay-nha-tro-10-phong-ngan", status: "done" },
  { no: 2751, title: "Xây Nhà Trọ 20 Phòng", keyword: "xây nhà trọ 20 phòng", slug: "xay-nha-tro-20-phong-ngan", status: "done" },
  { no: 2752, title: "Xây Chung Cư Mini", keyword: "xây chung cư mini", slug: "xay-chung-cu-mini-ngan", status: "done" },
  { no: 2753, title: "Xây Căn Hộ Dịch Vụ", keyword: "xây căn hộ dịch vụ", slug: "xay-can-ho-dich-vu-ngan", status: "done" },
  { no: 2754, title: "Xây Homestay Nhà Phố", keyword: "xây homestay nhà phố", slug: "xay-homestay-nha-pho-ngan", status: "done" },
  { no: 2755, title: "Xây Airbnb Nhà Phố", keyword: "xây airbnb nhà phố", slug: "xay-airbnb-nha-pho-ngan", status: "done" },
  { no: 2756, title: "Xây Boutique Hotel Mini", keyword: "xây boutique hotel mini", slug: "xay-boutique-hotel-mini-ngan", status: "done" },
  { no: 2757, title: "Xây Nhà Hàng Phố", keyword: "xây nhà hàng phố", slug: "xay-nha-hang-pho-ngan", status: "done" },
  { no: 2758, title: "Xây Quán Cafe Nhà Phố", keyword: "xây quán cafe nhà phố", slug: "xay-quan-cafe-nha-pho-ngan", status: "done" },
  { no: 2759, title: "Xây Spa Thẩm Mỹ Viện", keyword: "xây spa thẩm mỹ viện", slug: "xay-spa-tham-my-vien-ngan", status: "done" },
  { no: 2760, title: "Xây Phòng Khám Tư", keyword: "xây phòng khám tư", slug: "xay-phong-kham-tu-ngan", status: "done" },
  { no: 2761, title: "Xây Nha Khoa Tư Nhân", keyword: "xây nha khoa tư nhân", slug: "xay-nha-khoa-tu-nhan-ngan", status: "done" },
  { no: 2762, title: "Xây Phòng Gym Commercial", keyword: "xây phòng gym commercial", slug: "xay-phong-gym-commercial-ngan", status: "done" },
  { no: 2763, title: "Xây Showroom Bán Hàng", keyword: "xây showroom bán hàng", slug: "xay-showroom-ban-hang-ngan", status: "done" },
  { no: 2764, title: "Xây Cửa Hàng Tiện Lợi", keyword: "xây cửa hàng tiện lợi", slug: "xay-cua-hang-tien-loi-ngan", status: "done" },
  { no: 2765, title: "Xây Siêu Thị Mini", keyword: "xây siêu thị mini", slug: "xay-sieu-thi-mini-ngan", status: "done" },
  { no: 2766, title: "Xây Kho Xưởng Nhà Phố", keyword: "xây kho xưởng nhà phố", slug: "xay-kho-xuong-nha-pho-ngan", status: "done" },
  { no: 2767, title: "Xây Văn Phòng Cho Thuê", keyword: "xây văn phòng cho thuê", slug: "xay-van-phong-cho-thue-ngan", status: "done" },
  { no: 2768, title: "Xây Co-working Space", keyword: "xây co-working space", slug: "xay-co-working-space-ngan", status: "done" },
  { no: 2769, title: "Xây Trường Mầm Non Tư", keyword: "xây trường mầm non tư", slug: "xay-truong-mam-non-tu-ngan", status: "done" },
  { no: 2770, title: "Xây Nhà Trẻ Tư Thục", keyword: "xây nhà trẻ tư thục", slug: "xay-nha-tre-tu-thuc-ngan", status: "done" },
  { no: 2771, title: "Xây Trung Tâm Ngoại Ngữ", keyword: "xây trung tâm ngoại ngữ", slug: "xay-trung-tam-ngoai-ngu-ngan", status: "done" },
  { no: 2772, title: "Xây Studio Chụp Ảnh", keyword: "xây studio chụp ảnh", slug: "xay-studio-chup-anh-ngan", status: "done" },
  { no: 2773, title: "Xây Studio Livestream", keyword: "xây studio livestream", slug: "xay-studio-livestream-ngan", status: "done" },
  { no: 2774, title: "Xây Garage Ô Tô", keyword: "xây garage ô tô", slug: "xay-garage-o-to-ngan", status: "done" },
  { no: 2775, title: "Xây Hầm Để Xe", keyword: "xây hầm để xe", slug: "xay-ham-de-xe-ngan", status: "done" },
  { no: 2776, title: "Xây Sân Để Xe Máy", keyword: "xây sân để xe máy", slug: "xay-san-de-xe-may-ngan", status: "done" },
  { no: 2777, title: "Xây Nhà Xe Riêng", keyword: "xây nhà xe riêng", slug: "xay-nha-xe-rieng-ngan", status: "done" },
  { no: 2778, title: "Xây Biệt Thự Mini", keyword: "xây biệt thự mini", slug: "xay-biet-thu-mini-ngan", status: "done" },
  { no: 2779, title: "Xây Biệt Thự Song Lập", keyword: "xây biệt thự song lập", slug: "xay-biet-thu-song-lap-ngan", status: "done" },
  { no: 2780, title: "Xây Biệt Thự Đơn Lập", keyword: "xây biệt thự đơn lập", slug: "xay-biet-thu-don-lap-ngan", status: "done" },
  { no: 2781, title: "Xây Biệt Thự Nghỉ Dưỡng", keyword: "xây biệt thự nghỉ dưỡng", slug: "xay-biet-thu-nghi-duong-ngan", status: "done" },
  { no: 2782, title: "Xây Nhà Vườn Nghỉ Cuối Tuần", keyword: "xây nhà vườn nghỉ cuối tuần", slug: "xay-nha-vuon-nghi-cuoi-tuan-ngan", status: "done" },
  { no: 2783, title: "Xây Farmstay Cơ Bản", keyword: "xây farmstay cơ bản", slug: "xay-farmstay-co-ban-ngan", status: "done" },
  { no: 2784, title: "Xây Nhà Gỗ Hiện Đại", keyword: "xây nhà gỗ hiện đại", slug: "xay-nha-go-hien-dai-ngan", status: "done" },
  { no: 2785, title: "Xây Nhà Khung Thép Nhẹ", keyword: "xây nhà khung thép nhẹ", slug: "xay-nha-khung-thep-nhe-ngan", status: "done" },
  { no: 2786, title: "Xây Nhà LSF Frame", keyword: "xây nhà lsf frame", slug: "xay-nha-lsf-frame-ngan", status: "done" },
  { no: 2787, title: "Xây Nhà Bê Tông Dự Ứng Lực", keyword: "xây nhà bê tông dự ứng lực", slug: "xay-nha-be-tong-du-ung-luc-ngan", status: "done" },
  { no: 2788, title: "Xây Nhà Sàn Không Dầm", keyword: "xây nhà sàn không dầm", slug: "xay-nha-san-khong-dam-ngan", status: "done" },
  { no: 2789, title: "Xây Nhà Không Cột Giữa", keyword: "xây nhà không cột giữa", slug: "xay-nha-khong-cot-giua-ngan", status: "done" },
  { no: 2790, title: "Xây Nhà Thông Tầng", keyword: "xây nhà thông tầng", slug: "xay-nha-thong-tang-ngan", status: "done" },
  { no: 2791, title: "Xây Nhà Duplex", keyword: "xây nhà duplex", slug: "xay-nha-duplex-ngan", status: "done" },
  { no: 2792, title: "Xây Nhà Penthouse", keyword: "xây nhà penthouse", slug: "xay-nha-penthouse-ngan", status: "done" },
  { no: 2793, title: "Cải Tạo Nhà Thành Homestay", keyword: "cải tạo nhà thành homestay", slug: "cai-tao-nha-thanh-homestay-ngan", status: "done" },
  { no: 2794, title: "Cải Tạo Nhà Thành Văn Phòng", keyword: "cải tạo nhà thành văn phòng", slug: "cai-tao-nha-thanh-van-phong-ngan", status: "done" },
  { no: 2795, title: "Cải Tạo Nhà Thành Cafe", keyword: "cải tạo nhà thành cafe", slug: "cai-tao-nha-thanh-cafe-ngan", status: "done" },
  { no: 2796, title: "Cải Tạo Nhà Thành Nhà Trọ", keyword: "cải tạo nhà thành nhà trọ", slug: "cai-tao-nha-thanh-nha-tro-ngan", status: "done" },
  { no: 2797, title: "Cải Tạo Nhà Thành Spa", keyword: "cải tạo nhà thành spa", slug: "cai-tao-nha-thanh-spa-ngan", status: "done" },
  { no: 2798, title: "Cải Tạo Mặt Tiền Kinh Doanh", keyword: "cải tạo mặt tiền kinh doanh", slug: "cai-tao-mat-tien-kinh-doanh-ngan", status: "done" },
  { no: 2799, title: "Cải Tạo Tầng Trệt Shop", keyword: "cải tạo tầng trệt shop", slug: "cai-tao-tang-tret-shop-ngan", status: "done" },
  { no: 2800, title: "Cải Tạo Gác Lửng Kinh Doanh", keyword: "cải tạo gác lửng kinh doanh", slug: "cai-tao-gac-lung-kinh-doanh-ngan", status: "done" },
  { no: 2801, title: "Nâng Tầng Thành Nhà Trọ", keyword: "nâng tầng thành nhà trọ", slug: "nang-tang-thanh-nha-tro-ngan", status: "done" },
  { no: 2802, title: "Thiết Kế Shop Nhà Phố", keyword: "thiết kế shop nhà phố", slug: "thiet-ke-shop-nha-pho-ngan", status: "done" },
  { no: 2803, title: "Thiết Kế Cafe Nhà Phố", keyword: "thiết kế cafe nhà phố", slug: "thiet-ke-cafe-nha-pho-ngan", status: "done" },
  { no: 2804, title: "Thiết Kế Nhà Hàng Phố", keyword: "thiết kế nhà hàng phố", slug: "thiet-ke-nha-hang-pho-ngan", status: "done" },
  { no: 2805, title: "Thiết Kế Homestay", keyword: "thiết kế homestay", slug: "thiet-ke-homestay-ngan", status: "done" },
  { no: 2806, title: "Thiết Kế Nhà Trọ Tối Ưu", keyword: "thiết kế nhà trọ tối ưu", slug: "thiet-ke-nha-tro-toi-uu-ngan", status: "done" },
  { no: 2807, title: "Thiết Kế Văn Phòng Nhà Phố", keyword: "thiết kế văn phòng nhà phố", slug: "thiet-ke-van-phong-nha-pho-ngan", status: "done" },
  { no: 2808, title: "Báo Giá Xây Nhà Trọ", keyword: "báo giá xây nhà trọ", slug: "bao-gia-xay-nha-tro-ngan", status: "done" },
  { no: 2809, title: "Báo Giá Xây Homestay", keyword: "báo giá xây homestay", slug: "bao-gia-xay-homestay-ngan", status: "done" },
  { no: 2810, title: "Báo Giá Xây Showroom", keyword: "báo giá xây showroom", slug: "bao-gia-xay-showroom-ngan", status: "done" },
  { no: 2811, title: "Báo Giá Xây Văn Phòng", keyword: "báo giá xây văn phòng", slug: "bao-gia-xay-van-phong-ngan", status: "done" },
  { no: 2812, title: "Báo Giá Xây Biệt Thự", keyword: "báo giá xây biệt thự", slug: "bao-gia-xay-biet-thu-ngan", status: "done" },
  { no: 2813, title: "Pháp Lý Nhà Ở Kinh Doanh", keyword: "pháp lý nhà ở kinh doanh", slug: "phap-ly-nha-o-kinh-doanh-ngan", status: "done" },
  { no: 2814, title: "Xin Phép Xây Nhà Trọ", keyword: "xin phép xây nhà trọ", slug: "xin-phep-xay-nha-tro-ngan", status: "done" },
  { no: 2815, title: "Xin Phép Xây Homestay", keyword: "xin phép xây homestay", slug: "xin-phep-xay-homestay-ngan", status: "done" },
  { no: 2816, title: "PCCC Nhà Trọ Bắt Buộc", keyword: "pccc nhà trọ bắt buộc", slug: "pccc-nha-tro-bat-buoc-ngan", status: "done" },
  { no: 2817, title: "PCCC Nhà Hàng Cafe", keyword: "pccc nhà hàng cafe", slug: "pccc-nha-hang-cafe-ngan", status: "done" },
  { no: 2818, title: "Thoát Hiểm Nhà Trọ", keyword: "thoát hiểm nhà trọ", slug: "thoat-hiem-nha-tro-ngan", status: "done" },
  { no: 2819, title: "Cầu Thang Thoát Hiểm", keyword: "cầu thang thoát hiểm", slug: "cau-thang-thoat-hiem-ngan", status: "done" },
  { no: 2820, title: "Hệ Thống PCCC Tự Động", keyword: "hệ thống pccc tự động", slug: "he-thong-pccc-tu-dong-ngan", status: "done" },
  { no: 2821, title: "Bình Chữa Cháy Nhà Phố", keyword: "bình chữa cháy nhà phố", slug: "binh-chua-chay-nha-pho-ngan", status: "done" },
  { no: 2822, title: "Tủ Điện PCCC", keyword: "tủ điện pccc", slug: "tu-dien-pccc-ngan", status: "done" },
  { no: 2823, title: "Đầu Báo Khói Nhà", keyword: "đầu báo khói nhà", slug: "dau-bao-khoi-nha-ngan", status: "done" },
  { no: 2824, title: "Vòi Phun Sprinkler Nhà", keyword: "vòi phun sprinkler nhà", slug: "voi-phun-sprinkler-nha-ngan", status: "done" },
  { no: 2825, title: "Thiết Kế Mặt Tiền Thu Hút", keyword: "thiết kế mặt tiền thu hút", slug: "thiet-ke-mat-tien-thu-hut-ngan", status: "done" },
  { no: 2826, title: "Bảng Hiệu Nhà Phố", keyword: "bảng hiệu nhà phố", slug: "bang-hieu-nha-pho-ngan", status: "done" },
  { no: 2827, title: "Ánh Sáng Mặt Tiền Shop", keyword: "ánh sáng mặt tiền shop", slug: "anh-sang-mat-tien-shop-ngan", status: "done" },
  { no: 2828, title: "Vách Kính Shop Nhà Phố", keyword: "vách kính shop nhà phố", slug: "vach-kinh-shop-nha-pho-ngan", status: "done" },
  { no: 2829, title: "Cửa Cuốn Shop", keyword: "cửa cuốn shop", slug: "cua-cuon-shop-ngan", status: "done" },
  { no: 2830, title: "Cửa Kéo Shop", keyword: "cửa kéo shop", slug: "cua-keo-shop-ngan", status: "done" },
  { no: 2831, title: "Sàn Epoxy Xưởng", keyword: "sàn epoxy xưởng", slug: "san-epoxy-xuong-ngan", status: "done" },
  { no: 2832, title: "Sàn Vinyl Văn Phòng", keyword: "sàn vinyl văn phòng", slug: "san-vinyl-van-phong-ngan", status: "done" },
  { no: 2833, title: "Trần Xuyên Sáng Cafe", keyword: "trần xuyên sáng cafe", slug: "tran-xuyen-sang-cafe-ngan", status: "done" },
  { no: 2834, title: "Nội Thất Homestay Trọn Gói", keyword: "nội thất homestay trọn gói", slug: "noi-that-homestay-tron-goi-ngan", status: "done" },
  { no: 2835, title: "Nội Thất Nhà Trọ Tối Giản", keyword: "nội thất nhà trọ tối giản", slug: "noi-that-nha-tro-toi-gian-ngan", status: "done" },
  { no: 2836, title: "Nội Thất Văn Phòng Lean", keyword: "nội thất văn phòng lean", slug: "noi-that-van-phong-lean-ngan", status: "done" },
  { no: 2837, title: "ROI Nhà Trọ TPHCM", keyword: "roi nhà trọ tphcm", slug: "roi-nha-tro-tphcm-ngan", status: "done" },
  { no: 2838, title: "ROI Homestay TPHCM", keyword: "roi homestay tphcm", slug: "roi-homestay-tphcm-ngan", status: "done" },
  { no: 2839, title: "ROI Mặt Tiền Cho Thuê", keyword: "roi mặt tiền cho thuê", slug: "roi-mat-tien-cho-thue-ngan", status: "done" },
  { no: 2840, title: "Chủ Đề Mở Rộng 33 1", keyword: "chủ đề mở rộng 33 1", slug: "chu-de-mo-rong-33-1-ngan", status: "done" },
  { no: 2841, title: "Chủ Đề Mở Rộng 33 2", keyword: "chủ đề mở rộng 33 2", slug: "chu-de-mo-rong-33-2-ngan", status: "done" },
  { no: 2842, title: "Chủ Đề Mở Rộng 33 3", keyword: "chủ đề mở rộng 33 3", slug: "chu-de-mo-rong-33-3-ngan", status: "done" },
  { no: 2843, title: "Chủ Đề Mở Rộng 33 4", keyword: "chủ đề mở rộng 33 4", slug: "chu-de-mo-rong-33-4-ngan", status: "done" },
  { no: 2844, title: "Chủ Đề Mở Rộng 33 5", keyword: "chủ đề mở rộng 33 5", slug: "chu-de-mo-rong-33-5-ngan", status: "done" },
  { no: 2845, title: "Chủ Đề Mở Rộng 33 6", keyword: "chủ đề mở rộng 33 6", slug: "chu-de-mo-rong-33-6-ngan", status: "done" },
  { no: 2846, title: "Chủ Đề Mở Rộng 33 7", keyword: "chủ đề mở rộng 33 7", slug: "chu-de-mo-rong-33-7-ngan", status: "done" },
];
