/**
 * Lịch 100 từ khóa ngắn — batch 51 (#4547–#4646).
 * Cluster: hoàn thiện hạng mục chi tiết.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch51: ContentCalendarItem[] = [
  { no: 4547, title: "Ốp Gạch Nhà Tắm 30x60", keyword: "ốp gạch nhà tắm 30x60", slug: "op-gach-nha-tam-30x60-ht-ngan", status: "done" },
  { no: 4548, title: "Ốp Gạch Nhà Tắm 60x60", keyword: "ốp gạch nhà tắm 60x60", slug: "op-gach-nha-tam-60x60-ht-ngan", status: "done" },
  { no: 4549, title: "Ốp Gạch Nhà Tắm 60x120", keyword: "ốp gạch nhà tắm 60x120", slug: "op-gach-nha-tam-60x120-ht-ngan", status: "done" },
  { no: 4550, title: "Lát Gạch Phòng Khách 80x80", keyword: "lát gạch phòng khách 80x80", slug: "lat-gach-phong-khach-80x80-ht-ngan", status: "done" },
  { no: 4551, title: "Lát Gạch Phòng Khách 60x60", keyword: "lát gạch phòng khách 60x60", slug: "lat-gach-phong-khach-60x60-ht-ngan", status: "done" },
  { no: 4552, title: "Lát Sàn Gỗ Phòng Ngủ", keyword: "lát sàn gỗ phòng ngủ", slug: "lat-san-go-phong-ngu-ht-ngan", status: "done" },
  { no: 4553, title: "Lát Sàn SPC Phòng Khách", keyword: "lát sàn spc phòng khách", slug: "lat-san-spc-phong-khach-ht-ngan", status: "done" },
  { no: 4554, title: "Lát Sàn Vinyl Nhà Phố", keyword: "lát sàn vinyl nhà phố", slug: "lat-san-vinyl-nha-pho-ht-ngan", status: "done" },
  { no: 4555, title: "Ốp Đá Cầu Thang Granite", keyword: "ốp đá cầu thang granite", slug: "op-da-cau-thang-granite-ht-ngan", status: "done" },
  { no: 4556, title: "Ốp Đá Cầu Thang Marble", keyword: "ốp đá cầu thang marble", slug: "op-da-cau-thang-marble-ht-ngan", status: "done" },
  { no: 4557, title: "Ốp Đá Mặt Bếp", keyword: "ốp đá mặt bếp", slug: "op-da-mat-bep-ht-ngan", status: "done" },
  { no: 4558, title: "Ốp Đá Quầy Bar", keyword: "ốp đá quầy bar", slug: "op-da-quay-bar-ht-ngan", status: "done" },
  { no: 4559, title: "Ốp Đá Lavabo", keyword: "ốp đá lavabo", slug: "op-da-lavabo-ht-ngan", status: "done" },
  { no: 4560, title: "Ron Epoxy Nhà Tắm", keyword: "ron epoxy nhà tắm", slug: "ron-epoxy-nha-tam-ht-ngan", status: "done" },
  { no: 4561, title: "Ron Xi Măng Phòng Khách", keyword: "ron xi măng phòng khách", slug: "ron-xi-mang-phong-khach-ht-ngan", status: "done" },
  { no: 4562, title: "Keo Dán Gạch C2", keyword: "keo dán gạch c2", slug: "keo-dan-gach-c2-ht-ngan", status: "done" },
  { no: 4563, title: "Keo Dán Đá", keyword: "keo dán đá", slug: "keo-dan-da-ht-ngan", status: "done" },
  { no: 4564, title: "Sơn Bả Trong Nhà", keyword: "sơn bả trong nhà", slug: "son-ba-trong-nha-ht-ngan", status: "done" },
  { no: 4565, title: "Sơn Bả Ngoài Nhà", keyword: "sơn bả ngoài nhà", slug: "son-ba-ngoai-nha-ht-ngan", status: "done" },
  { no: 4566, title: "Sơn Lót Kiềm", keyword: "sơn lót kiềm", slug: "son-lot-kiem-ht-ngan", status: "done" },
  { no: 4567, title: "Sơn Phủ Bóng", keyword: "sơn phủ bóng", slug: "son-phu-bong-ht-ngan", status: "done" },
  { no: 4568, title: "Sơn Phủ Mờ", keyword: "sơn phủ mờ", slug: "son-phu-mo-ht-ngan", status: "done" },
  { no: 4569, title: "Sơn Hiệu Ứng Bê Tông", keyword: "sơn hiệu ứng bê tông", slug: "son-hieu-ung-be-tong-ht-ngan", status: "done" },
  { no: 4570, title: "Sơn Hiệu Ứng Đá", keyword: "sơn hiệu ứng đá", slug: "son-hieu-ung-da-ht-ngan", status: "done" },
  { no: 4571, title: "Giấy Dán Tường Phòng Ngủ", keyword: "giấy dán tường phòng ngủ", slug: "giay-dan-tuong-phong-ngu-ht-ngan", status: "done" },
  { no: 4572, title: "Giấy Dán Tường Phòng Khách", keyword: "giấy dán tường phòng khách", slug: "giay-dan-tuong-phong-khach-ht-ngan", status: "done" },
  { no: 4573, title: "Trần Thạch Cao Phẳng", keyword: "trần thạch cao phẳng", slug: "tran-thach-cao-phang-ht-ngan", status: "done" },
  { no: 4574, title: "Trần Thạch Cao Giật Cấp", keyword: "trần thạch cao giật cấp", slug: "tran-thach-cao-giat-cap-ht-ngan", status: "done" },
  { no: 4575, title: "Trần Thạch Cao Kết Hợp Đèn", keyword: "trần thạch cao kết hợp đèn", slug: "tran-thach-cao-ket-hop-den-ht-ngan", status: "done" },
  { no: 4576, title: "Trần Xuyên Sáng", keyword: "trần xuyên sáng", slug: "tran-xuyen-sang-ht-ngan", status: "done" },
  { no: 4577, title: "Trần Lam Gỗ", keyword: "trần lam gỗ", slug: "tran-lam-go-ht-ngan", status: "done" },
  { no: 4578, title: "Trần Nhôm Nhà Phố", keyword: "trần nhôm nhà phố", slug: "tran-nhom-nha-pho-ht-ngan", status: "done" },
  { no: 4579, title: "Vách Ngăn Thạch Cao", keyword: "vách ngăn thạch cao", slug: "vach-ngan-thach-cao-ht-ngan", status: "done" },
  { no: 4580, title: "Vách Ngăn Kính Cường Lực", keyword: "vách ngăn kính cường lực", slug: "vach-ngan-kinh-cuong-luc-ht-ngan", status: "done" },
  { no: 4581, title: "Vách Ngăn Gỗ CNC", keyword: "vách ngăn gỗ cnc", slug: "vach-ngan-go-cnc-ht-ngan", status: "done" },
  { no: 4582, title: "Vách Tivi Phòng Khách", keyword: "vách tivi phòng khách", slug: "vach-tivi-phong-khach-ht-ngan", status: "done" },
  { no: 4583, title: "Phào Chỉ Trần PU", keyword: "phào chỉ trần pu", slug: "phao-chi-tran-pu-ht-ngan", status: "done" },
  { no: 4584, title: "Phào Chỉ Tường PU", keyword: "phào chỉ tường pu", slug: "phao-chi-tuong-pu-ht-ngan", status: "done" },
  { no: 4585, title: "Nẹp Đồng Sàn", keyword: "nẹp đồng sàn", slug: "nep-dong-san-ht-ngan", status: "done" },
  { no: 4586, title: "Nẹp Inox Góc Tường", keyword: "nẹp inox góc tường", slug: "nep-inox-goc-tuong-ht-ngan", status: "done" },
  { no: 4587, title: "Len Chân Tường Nhựa", keyword: "len chân tường nhựa", slug: "len-chan-tuong-nhua-ht-ngan", status: "done" },
  { no: 4588, title: "Len Chân Tường Gỗ", keyword: "len chân tường gỗ", slug: "len-chan-tuong-go-ht-ngan", status: "done" },
  { no: 4589, title: "Cửa Đi Nhôm Xingfa", keyword: "cửa đi nhôm xingfa", slug: "cua-di-nhom-xingfa-ht-ngan", status: "done" },
  { no: 4590, title: "Cửa Đi Nhôm PMA", keyword: "cửa đi nhôm pma", slug: "cua-di-nhom-pma-ht-ngan", status: "done" },
  { no: 4591, title: "Cửa Sổ Lùa Nhôm", keyword: "cửa sổ lùa nhôm", slug: "cua-so-lua-nhom-ht-ngan", status: "done" },
  { no: 4592, title: "Cửa Sổ Mở Quay Nhôm", keyword: "cửa sổ mở quay nhôm", slug: "cua-so-mo-quay-nhom-ht-ngan", status: "done" },
  { no: 4593, title: "Cửa Gỗ Công Nghiệp Melamine", keyword: "cửa gỗ công nghiệp melamine", slug: "cua-go-cong-nghiep-melamine-ht-ngan", status: "done" },
  { no: 4594, title: "Cửa Gỗ Tự Nhiên Óc Chó", keyword: "cửa gỗ tự nhiên óc chó", slug: "cua-go-tu-nhien-oc-cho-ht-ngan", status: "done" },
  { no: 4595, title: "Cửa Nhựa Composite", keyword: "cửa nhựa composite", slug: "cua-nhua-composite-ht-ngan", status: "done" },
  { no: 4596, title: "Cửa Nhựa Đài Loan", keyword: "cửa nhựa đài loan", slug: "cua-nhua-dai-loan-ht-ngan", status: "done" },
  { no: 4597, title: "Cửa Cuốn Austdoor", keyword: "cửa cuốn austdoor", slug: "cua-cuon-austdoor-ht-ngan", status: "done" },
  { no: 4598, title: "Cửa Kéo Đài Loan", keyword: "cửa kéo đài loan", slug: "cua-keo-dai-loan-ht-ngan", status: "done" },
  { no: 4599, title: "Lan Can Kính 10mm", keyword: "lan can kính 10mm", slug: "lan-can-kinh-10mm-ht-ngan", status: "done" },
  { no: 4600, title: "Lan Can Kính 12mm", keyword: "lan can kính 12mm", slug: "lan-can-kinh-12mm-ht-ngan", status: "done" },
  { no: 4601, title: "Lan Can Inox Tay Vịn Gỗ", keyword: "lan can inox tay vịn gỗ", slug: "lan-can-inox-tay-vin-go-ht-ngan", status: "done" },
  { no: 4602, title: "Lan Can Sắt Mỹ Thuật", keyword: "lan can sắt mỹ thuật", slug: "lan-can-sat-my-thuat-ht-ngan", status: "done" },
  { no: 4603, title: "Tay Vịn Cầu Thang Gỗ", keyword: "tay vịn cầu thang gỗ", slug: "tay-vin-cau-thang-go-ht-ngan", status: "done" },
  { no: 4604, title: "Bậc Cầu Thang Gỗ", keyword: "bậc cầu thang gỗ", slug: "bac-cau-thang-go-ht-ngan", status: "done" },
  { no: 4605, title: "Bậc Cầu Thang Đá", keyword: "bậc cầu thang đá", slug: "bac-cau-thang-da-ht-ngan", status: "done" },
  { no: 4606, title: "Tủ Bếp Chữ L Acrylic", keyword: "tủ bếp chữ l acrylic", slug: "tu-bep-chu-l-acrylic-ht-ngan", status: "done" },
  { no: 4607, title: "Tủ Bếp Chữ I Melamine", keyword: "tủ bếp chữ i melamine", slug: "tu-bep-chu-i-melamine-ht-ngan", status: "done" },
  { no: 4608, title: "Tủ Bếp Có Đảo", keyword: "tủ bếp có đảo", slug: "tu-bep-co-dao-ht-ngan", status: "done" },
  { no: 4609, title: "Tủ Quần Áo Cánh Lùa", keyword: "tủ quần áo cánh lùa", slug: "tu-quan-ao-canh-lua-ht-ngan", status: "done" },
  { no: 4610, title: "Tủ Quần Áo Cánh Mở", keyword: "tủ quần áo cánh mở", slug: "tu-quan-ao-canh-mo-ht-ngan", status: "done" },
  { no: 4611, title: "Tủ Giày Thông Minh HT", keyword: "tủ giày thông minh", slug: "tu-giay-thong-minh-ht-ngan", status: "done" },
  { no: 4612, title: "Kệ Tivi Gỗ Công Nghiệp", keyword: "kệ tivi gỗ công nghiệp", slug: "ke-tivi-go-cong-nghiep-ht-ngan", status: "done" },
  { no: 4613, title: "Bàn Trang Điểm Âm Tường", keyword: "bàn trang điểm âm tường", slug: "ban-trang-diem-am-tuong-ht-ngan", status: "done" },
  { no: 4614, title: "Giường Ngủ Có Hộc", keyword: "giường ngủ có hộc", slug: "giuong-ngu-co-hoc-ht-ngan", status: "done" },
  { no: 4615, title: "Rèm Vải Phòng Khách", keyword: "rèm vải phòng khách", slug: "rem-vai-phong-khach-ht-ngan", status: "done" },
  { no: 4616, title: "Rèm Cuốn Văn Phòng Nhà", keyword: "rèm cuốn văn phòng nhà", slug: "rem-cuon-van-phong-nha-ht-ngan", status: "done" },
  { no: 4617, title: "Rèm Cầu Vồng", keyword: "rèm cầu vồng", slug: "rem-cau-vong-ht-ngan", status: "done" },
  { no: 4618, title: "Đèn LED Âm Trần 7W", keyword: "đèn led âm trần 7w", slug: "den-led-am-tran-7w-ht-ngan", status: "done" },
  { no: 4619, title: "Đèn LED Âm Trần 12W", keyword: "đèn led âm trần 12w", slug: "den-led-am-tran-12w-ht-ngan", status: "done" },
  { no: 4620, title: "Đèn Thả Bàn Ăn", keyword: "đèn thả bàn ăn", slug: "den-tha-ban-an-ht-ngan", status: "done" },
  { no: 4621, title: "Đèn Đứng Góc Phòng", keyword: "đèn đứng góc phòng", slug: "den-dung-goc-phong-ht-ngan", status: "done" },
  { no: 4622, title: "Ổ Cắm Âm Sàn", keyword: "ổ cắm âm sàn", slug: "o-cam-am-san-ht-ngan", status: "done" },
  { no: 4623, title: "Công Tắc Cảm Ứng HT", keyword: "công tắc cảm ứng", slug: "cong-tac-cam-ung-ht-ngan", status: "done" },
  { no: 4624, title: "Sen Cây Âm Trần", keyword: "sen cây âm trần", slug: "sen-cay-am-tran-ht-ngan", status: "done" },
  { no: 4625, title: "Sen Tắm Nhiệt Độ", keyword: "sen tắm nhiệt độ", slug: "sen-tam-nhiet-do-ht-ngan", status: "done" },
  { no: 4626, title: "Bồn Tắm Nằm", keyword: "bồn tắm nằm", slug: "bon-tam-nam-ht-ngan", status: "done" },
  { no: 4627, title: "Cabin Tắm Kính", keyword: "cabin tắm kính", slug: "cabin-tam-kinh-ht-ngan", status: "done" },
  { no: 4628, title: "Báo Giá Hoàn Thiện m2", keyword: "báo giá hoàn thiện m2", slug: "bao-gia-hoan-thien-m2-ht-ngan", status: "done" },
  { no: 4629, title: "Báo Giá Ốp Lát m2", keyword: "báo giá ốp lát m2", slug: "bao-gia-op-lat-m2-ht-ngan", status: "done" },
  { no: 4630, title: "Báo Giá Sơn Nước m2", keyword: "báo giá sơn nước m2", slug: "bao-gia-son-nuoc-m2-ht-ngan", status: "done" },
  { no: 4631, title: "Báo Giá Trần Thạch Cao m2", keyword: "báo giá trần thạch cao m2", slug: "bao-gia-tran-thach-cao-m2-ht-ngan", status: "done" },
  { no: 4632, title: "Quy Trình Hoàn Thiện Nhà", keyword: "quy trình hoàn thiện nhà", slug: "quy-trinh-hoan-thien-nha-ht-ngan", status: "done" },
  { no: 4633, title: "Thứ Tự Thi Công Hoàn Thiện", keyword: "thứ tự thi công hoàn thiện", slug: "thu-tu-thi-cong-hoan-thien-ht-ngan", status: "done" },
  { no: 4634, title: "Nghiệm Thu Hoàn Thiện", keyword: "nghiệm thu hoàn thiện", slug: "nghiem-thu-hoan-thien-ht-ngan", status: "done" },
  { no: 4635, title: "Checklist Hoàn Thiện Nhà", keyword: "checklist hoàn thiện nhà", slug: "checklist-hoan-thien-nha-ht-ngan", status: "done" },
  { no: 4636, title: "Lỗi Hoàn Thiện Thường Gặp", keyword: "lỗi hoàn thiện thường gặp", slug: "loi-hoan-thien-thuong-gap-ht-ngan", status: "done" },
  { no: 4637, title: "Xu Hướng Hoàn Thiện 2026", keyword: "xu hướng hoàn thiện 2026", slug: "xu-huong-hoan-thien-2026-ht-ngan", status: "done" },
  { no: 4638, title: "Chủ Đề Mở Rộng 51 1", keyword: "chủ đề mở rộng 51 1", slug: "chu-de-mo-rong-51-1-ngan", status: "done" },
  { no: 4639, title: "Chủ Đề Mở Rộng 51 2", keyword: "chủ đề mở rộng 51 2", slug: "chu-de-mo-rong-51-2-ngan", status: "done" },
  { no: 4640, title: "Chủ Đề Mở Rộng 51 3", keyword: "chủ đề mở rộng 51 3", slug: "chu-de-mo-rong-51-3-ngan", status: "done" },
  { no: 4641, title: "Chủ Đề Mở Rộng 51 4", keyword: "chủ đề mở rộng 51 4", slug: "chu-de-mo-rong-51-4-ngan", status: "done" },
  { no: 4642, title: "Chủ Đề Mở Rộng 51 5", keyword: "chủ đề mở rộng 51 5", slug: "chu-de-mo-rong-51-5-ngan", status: "done" },
  { no: 4643, title: "Chủ Đề Mở Rộng 51 6", keyword: "chủ đề mở rộng 51 6", slug: "chu-de-mo-rong-51-6-ngan", status: "done" },
  { no: 4644, title: "Chủ Đề Mở Rộng 51 7", keyword: "chủ đề mở rộng 51 7", slug: "chu-de-mo-rong-51-7-ngan", status: "done" },
  { no: 4645, title: "Chủ Đề Mở Rộng 51 8", keyword: "chủ đề mở rộng 51 8", slug: "chu-de-mo-rong-51-8-ngan", status: "done" },
  { no: 4646, title: "Chủ Đề Mở Rộng 51 9", keyword: "chủ đề mở rộng 51 9", slug: "chu-de-mo-rong-51-9-ngan", status: "done" },
];
