/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 16 (#1047–#1146).
 * Cluster mới: hoàn thiện/vật liệu, nội thất phòng, cải tạo chi tiết, pháp lý, geo quận/tỉnh, Ads commercial.
 * Suffix `-ngan` tránh trùng money pages / batch 15.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch16: ContentCalendarItem[] = [
  // —— A. Hoàn thiện & vật liệu (20) #1047–#1066 ——
  { no: 1047, title: "Hoàn Thiện Nhà Phố", keyword: "hoàn thiện nhà phố", slug: "hoan-thien-nha-pho-ngan", status: "done" },
  { no: 1048, title: "Ốp Lát Nhà", keyword: "ốp lát nhà", slug: "op-lat-nha-ngan", status: "done" },
  { no: 1049, title: "Lát Gạch Nhà", keyword: "lát gạch nhà", slug: "lat-gach-nha-ngan", status: "done" },
  { no: 1050, title: "Sơn Nước Nhà", keyword: "sơn nước nhà", slug: "son-nuoc-nha-ngan", status: "done" },
  { no: 1051, title: "Trần Thạch Cao", keyword: "trần thạch cao", slug: "tran-thach-cao-ngan", status: "done" },
  { no: 1052, title: "Làm Cửa Nhà", keyword: "làm cửa nhà", slug: "lam-cua-nha-ngan", status: "done" },
  { no: 1053, title: "Lắp Đặt Cửa Nhôm", keyword: "lắp đặt cửa nhôm", slug: "lap-dat-cua-nhom-ngan", status: "done" },
  { no: 1054, title: "Sàn Gỗ Nhà", keyword: "sàn gỗ nhà", slug: "san-go-nha-ngan", status: "done" },
  { no: 1055, title: "Giấy Dán Tường", keyword: "giấy dán tường", slug: "giay-dan-tuong-ngan", status: "done" },
  { no: 1056, title: "Đèn Nhà Phố", keyword: "đèn nhà phố", slug: "den-nha-pho-ngan", status: "done" },
  { no: 1057, title: "Tủ Bếp Xây Nhà", keyword: "tủ bếp xây nhà", slug: "tu-bep-xay-nha-ngan", status: "done" },
  { no: 1058, title: "Thiết Bị Vệ Sinh Nhà", keyword: "thiết bị vệ sinh nhà", slug: "thiet-bi-ve-sinh-nha-ngan", status: "done" },
  { no: 1059, title: "Lan Can Nhà", keyword: "lan can nhà", slug: "lan-can-nha-ngan", status: "done" },
  { no: 1060, title: "Cổng Nhà", keyword: "cổng nhà", slug: "cong-nha-ngan", status: "done" },
  { no: 1061, title: "Hàng Rào Nhà", keyword: "hàng rào nhà", slug: "hang-rao-nha-ngan", status: "done" },
  { no: 1062, title: "Mái Tôn Nhà", keyword: "mái tôn nhà", slug: "mai-ton-nha-ngan", status: "done" },
  { no: 1063, title: "Làm Mái Nhà", keyword: "làm mái nhà", slug: "lam-mai-nha-ngan", status: "done" },
  { no: 1064, title: "Chống Nóng Nhà", keyword: "chống nóng nhà", slug: "chong-nong-nha-ngan", status: "done" },
  { no: 1065, title: "Cách Âm Nhà", keyword: "cách âm nhà", slug: "cach-am-nha-ngan", status: "done" },
  { no: 1066, title: "Hoàn Thiện Nội Thất", keyword: "hoàn thiện nội thất", slug: "hoan-thien-noi-that-ngan", status: "done" },

  // —— B. Nội thất theo phòng (15) #1067–#1081 ——
  { no: 1067, title: "Thiết Kế Phòng Ngủ", keyword: "thiết kế phòng ngủ", slug: "thiet-ke-phong-ngu-ngan", status: "done" },
  { no: 1068, title: "Thiết Kế Phòng WC", keyword: "thiết kế phòng wc", slug: "thiet-ke-phong-wc-ngan", status: "done" },
  { no: 1069, title: "Thiết Kế Ban Công", keyword: "thiết kế ban công", slug: "thiet-ke-ban-cong-ngan", status: "done" },
  { no: 1070, title: "Thiết Kế Sân Thượng", keyword: "thiết kế sân thượng", slug: "thiet-ke-san-thuong-ngan", status: "done" },
  { no: 1071, title: "Thiết Kế Giếng Trời", keyword: "thiết kế giếng trời", slug: "thiet-ke-gieng-troi-ngan", status: "done" },
  { no: 1072, title: "Thiết Kế Cầu Thang", keyword: "thiết kế cầu thang", slug: "thiet-ke-cau-thang-ngan", status: "done" },
  { no: 1073, title: "Thiết Kế Gara", keyword: "thiết kế gara", slug: "thiet-ke-gara-ngan", status: "done" },
  { no: 1074, title: "Nội Thất Nhà Phố", keyword: "nội thất nhà phố", slug: "noi-that-nha-pho-ngan", status: "done" },
  { no: 1075, title: "Nội Thất Biệt Thự", keyword: "nội thất biệt thự", slug: "noi-that-biet-thu-ngan", status: "done" },
  { no: 1076, title: "Nội Thất Chung Cư", keyword: "nội thất chung cư", slug: "noi-that-chung-cu-ngan", status: "done" },
  { no: 1077, title: "Tủ Quần Áo Âm Tường", keyword: "tủ quần áo âm tường", slug: "tu-quan-ao-am-tuong-ngan", status: "done" },
  { no: 1078, title: "Vách Ngăn Nhà", keyword: "vách ngăn nhà", slug: "vach-ngan-nha-ngan", status: "done" },
  { no: 1079, title: "Làm Bếp Đẹp", keyword: "làm bếp đẹp", slug: "lam-bep-dep-ngan", status: "done" },
  { no: 1080, title: "Cải Tạo Phòng Ngủ", keyword: "cải tạo phòng ngủ", slug: "cai-tao-phong-ngu-ngan", status: "done" },
  { no: 1081, title: "Cải Tạo WC", keyword: "cải tạo wc", slug: "cai-tao-wc-ngan", status: "done" },

  // —— C. Cải tạo / sửa chi tiết (15) #1082–#1096 ——
  { no: 1082, title: "Sửa Tường Nứt", keyword: "sửa tường nứt", slug: "sua-tuong-nut-ngan", status: "done" },
  { no: 1083, title: "Xử Lý Nhà Nghiêng", keyword: "xử lý nhà nghiêng", slug: "xu-ly-nha-nghieng-ngan", status: "done" },
  { no: 1084, title: "Xử Lý Nhà Lún", keyword: "xử lý nhà lún", slug: "xu-ly-nha-lun-ngan", status: "done" },
  { no: 1085, title: "Sửa Nền Nhà", keyword: "sửa nền nhà", slug: "sua-nen-nha-ngan", status: "done" },
  { no: 1086, title: "Cải Tạo Sân Thượng", keyword: "cải tạo sân thượng", slug: "cai-tao-san-thuong-ngan", status: "done" },
  { no: 1087, title: "Cải Tạo Ban Công", keyword: "cải tạo ban công", slug: "cai-tao-ban-cong-ngan", status: "done" },
  { no: 1088, title: "Cải Tạo Tầng Áp Mái", keyword: "cải tạo tầng áp mái", slug: "cai-tao-tang-ap-mai-ngan", status: "done" },
  { no: 1089, title: "Làm Thêm Tầng Lửng", keyword: "làm thêm tầng lửng", slug: "lam-them-tang-lung-ngan", status: "done" },
  { no: 1090, title: "Đập Thông Nhà", keyword: "đập thông nhà", slug: "dap-thong-nha-ngan", status: "done" },
  { no: 1091, title: "Mở Rộng Phòng", keyword: "mở rộng phòng", slug: "mo-rong-phong-ngan", status: "done" },
  { no: 1092, title: "Cải Tạo Nhà Cấp 4", keyword: "cải tạo nhà cấp 4", slug: "cai-tao-nha-cap-4-ngan", status: "done" },
  { no: 1093, title: "Sửa Nhà Cấp 4", keyword: "sửa nhà cấp 4", slug: "sua-nha-cap-4-ngan", status: "done" },
  { no: 1094, title: "Cải Tạo Nhà Ống", keyword: "cải tạo nhà ống", slug: "cai-tao-nha-ong-ngan", status: "done" },
  { no: 1095, title: "Nâng Nền Nhà", keyword: "nâng nền nhà", slug: "nang-nen-nha-ngan", status: "done" },
  { no: 1096, title: "Gia Cố Móng Nhà", keyword: "gia cố móng nhà", slug: "gia-co-mong-nha-ngan", status: "done" },

  // —— D. Pháp lý & hồ sơ (10) #1097–#1106 ——
  { no: 1097, title: "Hoàn Công Nhà", keyword: "hoàn công nhà", slug: "hoan-cong-nha-ngan", status: "done" },
  { no: 1098, title: "Sổ Hồng Xây Nhà", keyword: "sổ hồng xây nhà", slug: "so-hong-xay-nha-ngan", status: "done" },
  { no: 1099, title: "Thủ Tục Xây Nhà", keyword: "thủ tục xây nhà", slug: "thu-tuc-xay-nha-ngan", status: "done" },
  { no: 1100, title: "Quy Hoạch Xây Nhà", keyword: "quy hoạch xây nhà", slug: "quy-hoach-xay-nha-ngan", status: "done" },
  { no: 1101, title: "Chỉ Giới Xây Dựng", keyword: "chỉ giới xây dựng", slug: "chi-gioi-xay-dung-ngan", status: "done" },
  { no: 1102, title: "Xin Phép Sửa Nhà", keyword: "xin phép sửa nhà", slug: "xin-phep-sua-nha-ngan", status: "done" },
  { no: 1103, title: "Xin Phép Cải Tạo", keyword: "xin phép cải tạo", slug: "xin-phep-cai-tao-ngan", status: "done" },
  { no: 1104, title: "Giấy Phép Nâng Tầng", keyword: "giấy phép nâng tầng", slug: "giay-phep-nang-tang-ngan", status: "done" },
  { no: 1105, title: "Thủ Tục Hoàn Công", keyword: "thủ tục hoàn công", slug: "thu-tuc-hoan-cong-ngan", status: "done" },
  { no: 1106, title: "Hồ Sơ Xin Phép Xây", keyword: "hồ sơ xin phép xây", slug: "ho-so-xin-phep-xay-ngan", status: "done" },

  // —— E. Geo ngắn quận / tỉnh (20) #1107–#1126 ——
  { no: 1107, title: "Xây Nhà Gò Vấp", keyword: "xây nhà Gò Vấp", slug: "xay-nha-go-vap-ngan", status: "done" },
  { no: 1108, title: "Xây Nhà Bình Thạnh", keyword: "xây nhà Bình Thạnh", slug: "xay-nha-binh-thanh-ngan", status: "done" },
  { no: 1109, title: "Xây Nhà Quận 7", keyword: "xây nhà Quận 7", slug: "xay-nha-quan-7-ngan", status: "done" },
  { no: 1110, title: "Xây Nhà Quận 9", keyword: "xây nhà Quận 9", slug: "xay-nha-quan-9-ngan", status: "done" },
  { no: 1111, title: "Xây Nhà Tân Bình", keyword: "xây nhà Tân Bình", slug: "xay-nha-tan-binh-ngan", status: "done" },
  { no: 1112, title: "Xây Nhà Tân Phú", keyword: "xây nhà Tân Phú", slug: "xay-nha-tan-phu-ngan", status: "done" },
  { no: 1113, title: "Xây Nhà Bình Chánh", keyword: "xây nhà Bình Chánh", slug: "xay-nha-binh-chanh-ngan", status: "done" },
  { no: 1114, title: "Xây Nhà Hóc Môn", keyword: "xây nhà Hóc Môn", slug: "xay-nha-hoc-mon-ngan", status: "done" },
  { no: 1115, title: "Xây Nhà Nhà Bè", keyword: "xây nhà Nhà Bè", slug: "xay-nha-nha-be-ngan", status: "done" },
  { no: 1116, title: "Xây Nhà Quận 12", keyword: "xây nhà Quận 12", slug: "xay-nha-quan-12-ngan", status: "done" },
  { no: 1117, title: "Xây Nhà Long An", keyword: "xây nhà Long An", slug: "xay-nha-long-an-ngan", status: "done" },
  { no: 1118, title: "Xây Nhà Biên Hòa", keyword: "xây nhà Biên Hòa", slug: "xay-nha-bien-hoa-ngan", status: "done" },
  { no: 1119, title: "Xây Nhà Thuận An", keyword: "xây nhà Thuận An", slug: "xay-nha-thuan-an-ngan", status: "done" },
  { no: 1120, title: "Xây Nhà Dĩ An", keyword: "xây nhà Dĩ An", slug: "xay-nha-di-an-ngan", status: "done" },
  { no: 1121, title: "Xây Nhà Thủ Dầu Một", keyword: "xây nhà Thủ Dầu Một", slug: "xay-nha-thu-dau-mot-ngan", status: "done" },
  { no: 1122, title: "Xây Nhà Buôn Ma Thuột", keyword: "xây nhà Buôn Ma Thuột", slug: "xay-nha-buon-ma-thuot-ngan", status: "done" },
  { no: 1123, title: "Sửa Nhà Gò Vấp", keyword: "sửa nhà Gò Vấp", slug: "sua-nha-go-vap-ngan", status: "done" },
  { no: 1124, title: "Sửa Nhà Bình Thạnh", keyword: "sửa nhà Bình Thạnh", slug: "sua-nha-binh-thanh-ngan", status: "done" },
  { no: 1125, title: "Cải Tạo Nhà Quận 7", keyword: "cải tạo nhà Quận 7", slug: "cai-tao-nha-quan-7-ngan", status: "done" },
  { no: 1126, title: "Cải Tạo Nhà Thủ Đức", keyword: "cải tạo nhà Thủ Đức", slug: "cai-tao-nha-thu-duc-ngan", status: "done" },

  // —— F. Ads / commercial (20) #1127–#1146 ——
  { no: 1127, title: "Thi Công Trọn Gói", keyword: "thi công trọn gói", slug: "thi-cong-tron-goi-ngan", status: "done" },
  { no: 1128, title: "Xây Dựng Trọn Gói", keyword: "xây dựng trọn gói", slug: "xay-dung-tron-goi-ngan", status: "done" },
  { no: 1129, title: "Nhà Thầu Uy Tín", keyword: "nhà thầu uy tín", slug: "nha-thau-uy-tin-ngan", status: "done" },
  { no: 1130, title: "Công Ty Xây Dựng", keyword: "công ty xây dựng", slug: "cong-ty-xay-dung-ngan", status: "done" },
  { no: 1131, title: "Đơn Vị Thi Công Nhà", keyword: "đơn vị thi công nhà", slug: "don-vi-thi-cong-nha-ngan", status: "done" },
  { no: 1132, title: "Báo Giá Thi Công", keyword: "báo giá thi công", slug: "bao-gia-thi-cong-ngan", status: "done" },
  { no: 1133, title: "Giá Cải Tạo Nhà", keyword: "giá cải tạo nhà", slug: "gia-cai-tao-nha-ngan", status: "done" },
  { no: 1134, title: "Đơn Giá Cải Tạo", keyword: "đơn giá cải tạo", slug: "don-gia-cai-tao-ngan", status: "done" },
  { no: 1135, title: "Chi Phí Sửa Nhà", keyword: "chi phí sửa nhà", slug: "chi-phi-sua-nha-ngan", status: "done" },
  { no: 1136, title: "Bảng Giá Cải Tạo", keyword: "bảng giá cải tạo", slug: "bang-gia-cai-tao-ngan", status: "done" },
  { no: 1137, title: "Xây Nhà Nhanh", keyword: "xây nhà nhanh", slug: "xay-nha-nhanh-ngan", status: "done" },
  { no: 1138, title: "Xây Nhà Đúng Tiến Độ", keyword: "xây nhà đúng tiến độ", slug: "xay-nha-dung-tien-do-ngan", status: "done" },
  { no: 1139, title: "Xây Nhà Không Phát Sinh", keyword: "xây nhà không phát sinh", slug: "xay-nha-khong-phat-sinh-ngan", status: "done" },
  { no: 1140, title: "Thi Công Giá Rẻ", keyword: "thi công giá rẻ", slug: "thi-cong-gia-re-ngan", status: "done" },
  { no: 1141, title: "Thầu Xây Dựng", keyword: "thầu xây dựng", slug: "thau-xay-dung-ngan", status: "done" },
  { no: 1142, title: "Nhận Thi Công Nhà", keyword: "nhận thi công nhà", slug: "nhan-thi-cong-nha-ngan", status: "done" },
  { no: 1143, title: "Làm Nhà Trọn Gói", keyword: "làm nhà trọn gói", slug: "lam-nha-tron-goi-ngan", status: "done" },
  { no: 1144, title: "Xây Nhà Chuyên Nghiệp", keyword: "xây nhà chuyên nghiệp", slug: "xay-nha-chuyen-nghiep-ngan", status: "done" },
  { no: 1145, title: "Dịch Vụ Xây Nhà", keyword: "dịch vụ xây nhà", slug: "dich-vu-xay-nha-ngan", status: "done" },
  { no: 1146, title: "Dịch Vụ Cải Tạo Nhà", keyword: "dịch vụ cải tạo nhà", slug: "dich-vu-cai-tao-nha-ngan", status: "done" },
];
