/**
 * Lịch 100 từ khóa SEO — batch 67 (#6147–#6246).
 * Cluster: Q.1–12 long-tail + hoàn thiện cao cấp + FAQ quyết định (indexable *-sk67).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch67: ContentCalendarItem[] = [
  { no: 6147, title: "Xây Nhà Trọn Gói Quận 1 2026", keyword: "xây nhà trọn gói Quận 1 2026", slug: "xay-nha-tron-goi-quan-1-2026-sk67", status: "done" },
  { no: 6148, title: "Xây Nhà Trọn Gói Quận 3 2026", keyword: "xây nhà trọn gói Quận 3 2026", slug: "xay-nha-tron-goi-quan-3-2026-sk67", status: "done" },
  { no: 6149, title: "Xây Nhà Trọn Gói Quận 4 2026", keyword: "xây nhà trọn gói Quận 4 2026", slug: "xay-nha-tron-goi-quan-4-2026-sk67", status: "done" },
  { no: 6150, title: "Xây Nhà Trọn Gói Quận 5 2026", keyword: "xây nhà trọn gói Quận 5 2026", slug: "xay-nha-tron-goi-quan-5-2026-sk67", status: "done" },
  { no: 6151, title: "Xây Nhà Trọn Gói Quận 6 2026", keyword: "xây nhà trọn gói Quận 6 2026", slug: "xay-nha-tron-goi-quan-6-2026-sk67", status: "done" },
  { no: 6152, title: "Xây Nhà Trọn Gói Quận 8 2026", keyword: "xây nhà trọn gói Quận 8 2026", slug: "xay-nha-tron-goi-quan-8-2026-sk67", status: "done" },
  { no: 6153, title: "Xây Nhà Trọn Gói Quận 10 2026", keyword: "xây nhà trọn gói Quận 10 2026", slug: "xay-nha-tron-goi-quan-10-2026-sk67", status: "done" },
  { no: 6154, title: "Xây Nhà Trọn Gói Quận 11 2026", keyword: "xây nhà trọn gói Quận 11 2026", slug: "xay-nha-tron-goi-quan-11-2026-sk67", status: "done" },
  { no: 6155, title: "Xây Nhà Trọn Gói Quận 12 2026", keyword: "xây nhà trọn gói Quận 12 2026", slug: "xay-nha-tron-goi-quan-12-2026-sk67", status: "done" },
  { no: 6156, title: "Xây Nhà Phường Bến Nghé", keyword: "xây nhà phường Bến Nghé", slug: "xay-nha-phuong-ben-nghe-sk67", status: "done" },
  { no: 6157, title: "Xây Nhà Phường Đa Kao", keyword: "xây nhà phường Đa Kao", slug: "xay-nha-phuong-da-kao-sk67", status: "done" },
  { no: 6158, title: "Xây Nhà Phường Cầu Kho", keyword: "xây nhà phường Cầu Kho", slug: "xay-nha-phuong-cau-kho-sk67", status: "done" },
  { no: 6159, title: "Xây Nhà Phường Nguyễn Cư Trinh", keyword: "xây nhà phường Nguyễn Cư Trinh", slug: "xay-nha-phuong-nguyen-cu-trinh-sk67", status: "done" },
  { no: 6160, title: "Xây Nhà Phường 1 Quận 3", keyword: "xây nhà phường 1 Quận 3", slug: "xay-nha-phuong-1-quan-3-sk67", status: "done" },
  { no: 6161, title: "Xây Nhà Phường 14 Quận 10", keyword: "xây nhà phường 14 Quận 10", slug: "xay-nha-phuong-14-quan-10-sk67", status: "done" },
  { no: 6162, title: "Xây Nhà Phường 5 Quận 8", keyword: "xây nhà phường 5 Quận 8", slug: "xay-nha-phuong-5-quan-8-sk67", status: "done" },
  { no: 6163, title: "Xây Nhà Phường Hiệp Thành Q.12", keyword: "xây nhà phường Hiệp Thành Quận 12", slug: "xay-nha-phuong-hiep-thanh-quan-12-sk67", status: "done" },
  { no: 6164, title: "Xây Nhà Phường Trung Mỹ Tây", keyword: "xây nhà phường Trung Mỹ Tây", slug: "xay-nha-phuong-trung-my-tay-sk67", status: "done" },
  { no: 6165, title: "Xây Nhà Phường Thạnh Xuân", keyword: "xây nhà phường Thạnh Xuân", slug: "xay-nha-phuong-thanh-xuan-sk67", status: "done" },
  { no: 6166, title: "Xây Nhà Phường An Phú Đông", keyword: "xây nhà phường An Phú Đông", slug: "xay-nha-phuong-an-phu-dong-sk67", status: "done" },

  { no: 6167, title: "Cải Tạo Nhà Quận 1", keyword: "cải tạo nhà Quận 1", slug: "cai-tao-nha-quan-1-sk67", status: "done" },
  { no: 6168, title: "Cải Tạo Nhà Quận 3", keyword: "cải tạo nhà Quận 3", slug: "cai-tao-nha-quan-3-sk67", status: "done" },
  { no: 6169, title: "Cải Tạo Nhà Quận 10", keyword: "cải tạo nhà Quận 10", slug: "cai-tao-nha-quan-10-sk67", status: "done" },
  { no: 6170, title: "Cải Tạo Nhà Quận 11", keyword: "cải tạo nhà Quận 11", slug: "cai-tao-nha-quan-11-sk67", status: "done" },
  { no: 6171, title: "Cải Tạo Nhà Thêm Tầng Tum", keyword: "cải tạo nhà thêm tầng tum", slug: "cai-tao-nha-them-tang-tum-sk67", status: "done" },
  { no: 6172, title: "Cải Tạo Nhà Đổi Cầu Thang", keyword: "cải tạo nhà đổi cầu thang", slug: "cai-tao-nha-doi-cau-thang-sk67", status: "done" },
  { no: 6173, title: "Cải Tạo Nhà Mở Cửa Sổ Lớn", keyword: "cải tạo nhà mở cửa sổ lớn", slug: "cai-tao-nha-mo-cua-so-lon-sk67", status: "done" },
  { no: 6174, title: "Cải Tạo Nhà Thêm Ban Công", keyword: "cải tạo nhà thêm ban công", slug: "cai-tao-nha-them-ban-cong-sk67", status: "done" },
  { no: 6175, title: "Sửa Nhà Thấm Sàn WC Tầng Trên", keyword: "sửa nhà thấm sàn WC tầng trên", slug: "sua-nha-tham-san-wc-tang-tren-sk67", status: "done" },
  { no: 6176, title: "Sửa Nhà Thấm Trần Phòng Ngủ", keyword: "sửa nhà thấm trần phòng ngủ", slug: "sua-nha-tham-tran-phong-ngu-sk67", status: "done" },
  { no: 6177, title: "Sửa Nhà Nứt Sàn Bê Tông", keyword: "sửa nhà nứt sàn bê tông", slug: "sua-nha-nut-san-be-tong-sk67", status: "done" },
  { no: 6178, title: "Sửa Hệ Thống Ống Nước Cũ", keyword: "sửa hệ thống ống nước cũ", slug: "sua-he-thong-ong-nuoc-cu-sk67", status: "done" },
  { no: 6179, title: "Thay Toàn Bộ Hệ Điện Nhà Cũ", keyword: "thay toàn bộ hệ điện nhà cũ", slug: "thay-toan-bo-he-dien-nha-cu-sk67", status: "done" },
  { no: 6180, title: "Nâng Tầng Nhà Cấp 4 Thành 3 Tầng", keyword: "nâng tầng nhà cấp 4 thành 3 tầng", slug: "nang-tang-nha-cap-4-thanh-3-tang-sk67", status: "done" },
  { no: 6181, title: "Cải Tạo Nhà Thành Shop Online", keyword: "cải tạo nhà thành shop online", slug: "cai-tao-nha-thanh-shop-online-sk67", status: "done" },
  { no: 6182, title: "Cải Tạo Nhà Thành Phòng Gym", keyword: "cải tạo nhà thành phòng gym", slug: "cai-tao-nha-thanh-phong-gym-sk67", status: "done" },
  { no: 6183, title: "Cải Tạo Nhà Cho Ba Thế Hệ", keyword: "cải tạo nhà cho ba thế hệ", slug: "cai-tao-nha-cho-ba-the-he-sk67", status: "done" },
  { no: 6184, title: "Sửa Chữa Nhà Sau Cải Tạo Hỏng", keyword: "sửa chữa nhà sau cải tạo hỏng", slug: "sua-chua-nha-sau-cai-tao-hong-sk67", status: "done" },
  { no: 6185, title: "Cải Tạo Nhà Giảm Tiếng Ồn Đường", keyword: "cải tạo nhà giảm tiếng ồn đường", slug: "cai-tao-nha-giam-tieng-on-duong-sk67", status: "done" },
  { no: 6186, title: "Cải Tạo Nhà Tăng Chiều Cao Thông Thủy", keyword: "cải tạo nhà tăng chiều cao thông thủy", slug: "cai-tao-nha-tang-chieu-cao-thong-thuy-sk67", status: "done" },

  { no: 6187, title: "Đơn Giá Hoàn Thiện Cao Cấp 2026", keyword: "đơn giá hoàn thiện cao cấp 2026", slug: "don-gia-hoan-thien-cao-cap-2026-sk67", status: "done" },
  { no: 6188, title: "Chi Phí Xây Nhà Có Thang Máy", keyword: "chi phí xây nhà có thang máy", slug: "chi-phi-xay-nha-co-thang-may-sk67", status: "done" },
  { no: 6189, title: "Chi Phí Xây Nhà Có Hầm Để Xe", keyword: "chi phí xây nhà có hầm để xe", slug: "chi-phi-xay-nha-co-ham-de-xe-sk67", status: "done" },
  { no: 6190, title: "Chi Phí Xây Nhà 6×20 Trọn Gói", keyword: "chi phí xây nhà 6x20 trọn gói", slug: "chi-phi-xay-nha-6x20-tron-goi-sk67", status: "done" },
  { no: 6191, title: "Chi Phí Xây Nhà 5×25 Trọn Gói", keyword: "chi phí xây nhà 5x25 trọn gói", slug: "chi-phi-xay-nha-5x25-tron-goi-sk67", status: "done" },
  { no: 6192, title: "Báo Giá Thiết Kế 3D Nhà Phố", keyword: "báo giá thiết kế 3D nhà phố", slug: "bao-gia-thiet-ke-3d-nha-pho-sk67", status: "done" },
  { no: 6193, title: "Báo Giá Giám Sát Thi Công Ngày", keyword: "báo giá giám sát thi công theo ngày", slug: "bao-gia-giam-sat-thi-cong-theo-ngay-sk67", status: "done" },
  { no: 6194, title: "Ngân Sách Xây Nhà 10 Tỷ TP.HCM", keyword: "ngân sách xây nhà 10 tỷ TP.HCM", slug: "ngan-sach-xay-nha-10-ty-tphcm-sk67", status: "done" },
  { no: 6195, title: "Ngân Sách Cải Tạo Nhà 1 Tỷ", keyword: "ngân sách cải tạo nhà 1 tỷ", slug: "ngan-sach-cai-tao-nha-1-ty-sk67", status: "done" },
  { no: 6196, title: "Chi Phí Chống Thấm Toàn Nhà", keyword: "chi phí chống thấm toàn nhà", slug: "chi-phi-chong-tham-toan-nha-sk67", status: "done" },
  { no: 6197, title: "Chi Phí Làm Mới Mặt Tiền 2026", keyword: "chi phí làm mới mặt tiền 2026", slug: "chi-phi-lam-moi-mat-tien-2026-sk67", status: "done" },
  { no: 6198, title: "Báo Giá Sơn Nhà Trong Ngoài", keyword: "báo giá sơn nhà trong ngoài", slug: "bao-gia-son-nha-trong-ngoai-sk67", status: "done" },
  { no: 6199, title: "Báo Giá Lát Gạch Toàn Nhà", keyword: "báo giá lát gạch toàn nhà", slug: "bao-gia-lat-gach-toan-nha-sk67", status: "done" },
  { no: 6200, title: "Chi Phí Lắp Đặt Điều Hòa Multi", keyword: "chi phí lắp điều hòa multi nhà phố", slug: "chi-phi-lap-dieu-hoa-multi-nha-pho-sk67", status: "done" },
  { no: 6201, title: "Cách Ước Lượng Chi Phí Xây Nhà Nhanh", keyword: "cách ước lượng chi phí xây nhà nhanh", slug: "cach-uoc-luong-chi-phi-xay-nha-nhanh-sk67", status: "done" },

  { no: 6202, title: "Thiết Kế Nhà Phố Phong Cách Japandi", keyword: "thiết kế nhà phố Japandi", slug: "thiet-ke-nha-pho-japandi-sk67", status: "done" },
  { no: 6203, title: "Thiết Kế Nhà Phố Phong Cách Wabi Sabi", keyword: "thiết kế nhà phố Wabi Sabi", slug: "thiet-ke-nha-pho-wabi-sabi-sk67", status: "done" },
  { no: 6204, title: "Thiết Kế Nhà Phố Phong Cách Tropical", keyword: "thiết kế nhà phố tropical", slug: "thiet-ke-nha-pho-tropical-sk67", status: "done" },
  { no: 6205, title: "Thiết Kế Nhà Phố Có Hồ Cá Koi", keyword: "thiết kế nhà phố có hồ cá koi", slug: "thiet-ke-nha-pho-co-ho-ca-koi-sk67", status: "done" },
  { no: 6206, title: "Thiết Kế Nhà Phố Có Sân Thượng BBQ", keyword: "thiết kế nhà phố có sân thượng BBQ", slug: "thiet-ke-nha-pho-co-san-thuong-bbq-sk67", status: "done" },
  { no: 6207, title: "Thiết Kế Nhà Phố 5 Phòng Ngủ", keyword: "thiết kế nhà phố 5 phòng ngủ", slug: "thiet-ke-nha-pho-5-phong-ngu-sk67", status: "done" },
  { no: 6208, title: "Thiết Kế Nhà Phố Có Phòng Karaoke", keyword: "thiết kế nhà phố có phòng karaoke", slug: "thiet-ke-nha-pho-co-phong-karaoke-sk67", status: "done" },
  { no: 6209, title: "Thiết Kế Nhà Phố Có Phòng Giặt", keyword: "thiết kế nhà phố có phòng giặt", slug: "thiet-ke-nha-pho-co-phong-giat-sk67", status: "done" },
  { no: 6210, title: "Thiết Kế Biệt Thự Song Lập TP.HCM", keyword: "thiết kế biệt thự song lập TP.HCM", slug: "thiet-ke-biet-thu-song-lap-tphcm-sk67", status: "done" },
  { no: 6211, title: "Thiết Kế Nhà Vườn Củ Chi", keyword: "thiết kế nhà vườn Củ Chi", slug: "thiet-ke-nha-vuon-cu-chi-sk67", status: "done" },
  { no: 6212, title: "Mẫu Nhà Phố 5 Tầng Đẹp 2026", keyword: "mẫu nhà phố 5 tầng đẹp 2026", slug: "mau-nha-pho-5-tang-dep-2026-sk67", status: "done" },
  { no: 6213, title: "Mẫu Nhà Phố Mặt Tiền 6m 2026", keyword: "mẫu nhà phố mặt tiền 6m 2026", slug: "mau-nha-pho-mat-tien-6m-2026-sk67", status: "done" },
  { no: 6214, title: "Thiết Kế Bếp Đảo Nhà Phố", keyword: "thiết kế bếp đảo nhà phố", slug: "thiet-ke-bep-dao-nha-pho-sk67", status: "done" },
  { no: 6215, title: "Thiết Kế Cầu Thang Kính", keyword: "thiết kế cầu thang kính", slug: "thiet-ke-cau-thang-kinh-sk67", status: "done" },
  { no: 6216, title: "Thiết Kế Thông Tầng Phòng Khách", keyword: "thiết kế thông tầng phòng khách", slug: "thiet-ke-thong-tang-phong-khach-sk67", status: "done" },

  { no: 6217, title: "Xây Nhà Cách Âm Phòng Karaoke", keyword: "xây nhà cách âm phòng karaoke", slug: "xay-nha-cach-am-phong-karaoke-sk67", status: "done" },
  { no: 6218, title: "Xây Nhà Chống Thấm Ngược", keyword: "xây nhà chống thấm ngược", slug: "xay-nha-chong-tham-nguoc-sk67", status: "done" },
  { no: 6219, title: "Đổ Móng Băng Nhà Phố", keyword: "đổ móng băng nhà phố", slug: "do-mong-bang-nha-pho-sk67", status: "done" },
  { no: 6220, title: "Đổ Móng Cọc Nhà Phố", keyword: "đổ móng cọc nhà phố", slug: "do-mong-coc-nha-pho-sk67", status: "done" },
  { no: 6221, title: "Làm Mái Hiên Nhà Phố", keyword: "làm mái hiên nhà phố", slug: "lam-mai-hien-nha-pho-sk67", status: "done" },
  { no: 6222, title: "Làm Sân Thượng Sân Vườn", keyword: "làm sân thượng sân vườn", slug: "lam-san-thuong-san-vuon-sk67", status: "done" },
  { no: 6223, title: "Chống Nóng Mái Tôn Nhà Phố", keyword: "chống nóng mái tôn nhà phố", slug: "chong-nong-mai-ton-nha-pho-sk67", status: "done" },
  { no: 6224, title: "Lắp Cửa Cuốn Nhà Phố", keyword: "lắp cửa cuốn nhà phố", slug: "lap-cua-cuon-nha-pho-sk67", status: "done" },
  { no: 6225, title: "Ốp Gỗ Nhựa Composite Mặt Tiền", keyword: "ốp gỗ nhựa composite mặt tiền", slug: "op-go-nhua-composite-mat-tien-sk67", status: "done" },
  { no: 6226, title: "Sơn Epoxy Sàn Nhà Để Xe", keyword: "sơn epoxy sàn nhà để xe", slug: "son-epoxy-san-nha-de-xe-sk67", status: "done" },
  { no: 6227, title: "Lát Đá Hoa Cương Cầu Thang", keyword: "lát đá hoa cương cầu thang", slug: "lat-da-hoa-cuong-cau-thang-sk67", status: "done" },
  { no: 6228, title: "Làm Vách Ngăn Thạch Cao", keyword: "làm vách ngăn thạch cao", slug: "lam-vach-ngan-thach-cao-sk67", status: "done" },
  { no: 6229, title: "Lắp Camera An Ninh Nhà Phố", keyword: "lắp camera an ninh nhà phố", slug: "lap-camera-an-ninh-nha-pho-sk67", status: "done" },
  { no: 6230, title: "Lắp Hệ Thống Lọc Nước Tổng", keyword: "lắp hệ thống lọc nước tổng", slug: "lap-he-thong-loc-nuoc-tong-sk67", status: "done" },
  { no: 6231, title: "Gia Cố Dầm Nhà Cũ Trước Nâng Tầng", keyword: "gia cố dầm nhà cũ trước nâng tầng", slug: "gia-co-dam-nha-cu-truoc-nang-tang-sk67", status: "done" },

  { no: 6232, title: "Xây Nhà Trọn Gói Vũng Tàu", keyword: "xây nhà trọn gói Vũng Tàu", slug: "xay-nha-tron-goi-vung-tau-sk67", status: "done" },
  { no: 6233, title: "Xây Nhà Trọn Gói Bà Rịa", keyword: "xây nhà trọn gói Bà Rịa", slug: "xay-nha-tron-goi-ba-ria-sk67", status: "done" },
  { no: 6234, title: "Xây Nhà Trọn Gói Tây Ninh", keyword: "xây nhà trọn gói Tây Ninh", slug: "xay-nha-tron-goi-tay-ninh-sk67", status: "done" },
  { no: 6235, title: "Xây Nhà Trọn Gói Bình Phước", keyword: "xây nhà trọn gói Bình Phước", slug: "xay-nha-tron-goi-binh-phuoc-sk67", status: "done" },
  { no: 6236, title: "Xây Nhà Trọn Gói Long Khánh", keyword: "xây nhà trọn gói Long Khánh", slug: "xay-nha-tron-goi-long-khanh-sk67", status: "done" },
  { no: 6237, title: "Xây Nhà Trọn Gói Trảng Bàng", keyword: "xây nhà trọn gói Trảng Bàng", slug: "xay-nha-tron-goi-trang-bang-sk67", status: "done" },
  { no: 6238, title: "Xây Nhà Trọn Gói Phú Giáo", keyword: "xây nhà trọn gói Phú Giáo", slug: "xay-nha-tron-goi-phu-giao-sk67", status: "done" },
  { no: 6239, title: "Cải Tạo Nhà Vũng Tàu", keyword: "cải tạo nhà Vũng Tàu", slug: "cai-tao-nha-vung-tau-sk67", status: "done" },
  { no: 6240, title: "Cải Tạo Nhà Tây Ninh", keyword: "cải tạo nhà Tây Ninh", slug: "cai-tao-nha-tay-ninh-sk67", status: "done" },
  { no: 6241, title: "Nên Xây Nhà Vào Tháng Nào", keyword: "nên xây nhà vào tháng nào", slug: "nen-xay-nha-vao-thang-nao-sk67", status: "done" },
  { no: 6242, title: "Xây Nhà Cần Chuẩn Bị Bao Nhiêu Tiền", keyword: "xây nhà cần chuẩn bị bao nhiêu tiền", slug: "xay-nha-can-chuan-bi-bao-nhieu-tien-sk67", status: "done" },
  { no: 6243, title: "Cải Tạo Hay Xây Mới Rẻ Hơn", keyword: "cải tạo hay xây mới rẻ hơn", slug: "cai-tao-hay-xay-moi-re-hon-sk67", status: "done" },
  { no: 6244, title: "Nhà Thầu Có Bảo Hiểm Công Trình Không", keyword: "nhà thầu có bảo hiểm công trình không", slug: "nha-thau-co-bao-hiem-cong-trinh-khong-sk67", status: "done" },
  { no: 6245, title: "Cách Theo Dõi Tiến Độ Xây Nhà Online", keyword: "cách theo dõi tiến độ xây nhà online", slug: "cach-theo-doi-tien-do-xay-nha-online-sk67", status: "done" },
  { no: 6246, title: "Khi Nào Nên Đổi Nhà Thầu Giữa Chừng", keyword: "khi nào nên đổi nhà thầu giữa chừng", slug: "khi-nao-nen-doi-nha-thau-giua-chung-sk67", status: "done" },
];
