/**
 * Lịch 100 từ khóa SEO — batch 66 (#6047–#6146).
 * Cluster: Ads intent + phường/quận còn thiếu + hoàn thiện/MEP (indexable *-sk66).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch66: ContentCalendarItem[] = [
  // 1–20 geo / phường
  { no: 6047, title: "Xây Nhà Phường 21 Bình Thạnh", keyword: "xây nhà phường 21 Bình Thạnh", slug: "xay-nha-phuong-21-binh-thanh-sk66", status: "done" },
  { no: 6048, title: "Xây Nhà Phường 26 Bình Thạnh", keyword: "xây nhà phường 26 Bình Thạnh", slug: "xay-nha-phuong-26-binh-thanh-sk66", status: "done" },
  { no: 6049, title: "Xây Nhà Phường 7 Gò Vấp", keyword: "xây nhà phường 7 Gò Vấp", slug: "xay-nha-phuong-7-go-vap-sk66", status: "done" },
  { no: 6050, title: "Xây Nhà Phường 15 Tân Bình", keyword: "xây nhà phường 15 Tân Bình", slug: "xay-nha-phuong-15-tan-binh-sk66", status: "done" },
  { no: 6051, title: "Xây Nhà Phường 4 Tân Phú", keyword: "xây nhà phường 4 Tân Phú", slug: "xay-nha-phuong-4-tan-phu-sk66", status: "done" },
  { no: 6052, title: "Xây Nhà Phường Bình Hưng Hòa", keyword: "xây nhà phường Bình Hưng Hòa", slug: "xay-nha-phuong-binh-hung-hoa-sk66", status: "done" },
  { no: 6053, title: "Xây Nhà Phường An Lạc Bình Tân", keyword: "xây nhà phường An Lạc Bình Tân", slug: "xay-nha-phuong-an-lac-binh-tan-sk66", status: "done" },
  { no: 6054, title: "Xây Nhà Phường Tân Tạo", keyword: "xây nhà phường Tân Tạo", slug: "xay-nha-phuong-tan-tao-sk66", status: "done" },
  { no: 6055, title: "Xây Nhà Phường Linh Trung", keyword: "xây nhà phường Linh Trung", slug: "xay-nha-phuong-linh-trung-sk66", status: "done" },
  { no: 6056, title: "Xây Nhà Phường Tam Phú", keyword: "xây nhà phường Tam Phú", slug: "xay-nha-phuong-tam-phu-sk66", status: "done" },
  { no: 6057, title: "Xây Nhà Phường Phú Hữu", keyword: "xây nhà phường Phú Hữu", slug: "xay-nha-phuong-phu-huu-sk66", status: "done" },
  { no: 6058, title: "Xây Nhà Phường Long Trường", keyword: "xây nhà phường Long Trường", slug: "xay-nha-phuong-long-truong-sk66", status: "done" },
  { no: 6059, title: "Xây Nhà Phường Phước Long A", keyword: "xây nhà phường Phước Long A", slug: "xay-nha-phuong-phuoc-long-a-sk66", status: "done" },
  { no: 6060, title: "Xây Nhà Trọn Gói Quận 2 Cũ", keyword: "xây nhà trọn gói Quận 2 cũ", slug: "xay-nha-tron-goi-quan-2-cu-sk66", status: "done" },
  { no: 6061, title: "Xây Nhà Trọn Gói Quận 9 Cũ", keyword: "xây nhà trọn gói Quận 9 cũ", slug: "xay-nha-tron-goi-quan-9-cu-sk66", status: "done" },
  { no: 6062, title: "Xây Nhà Trọn Gói Quận Thủ Đức Cũ", keyword: "xây nhà trọn gói Quận Thủ Đức cũ", slug: "xay-nha-tron-goi-quan-thu-duc-cu-sk66", status: "done" },
  { no: 6063, title: "Xây Nhà Hóc Môn 2026", keyword: "xây nhà Hóc Môn 2026", slug: "xay-nha-hoc-mon-2026-sk66", status: "done" },
  { no: 6064, title: "Xây Nhà Củ Chi 2026", keyword: "xây nhà Củ Chi 2026", slug: "xay-nha-cu-chi-2026-sk66", status: "done" },
  { no: 6065, title: "Xây Nhà Bình Chánh 2026", keyword: "xây nhà Bình Chánh 2026", slug: "xay-nha-binh-chanh-2026-sk66", status: "done" },
  { no: 6066, title: "Xây Nhà Nhà Bè 2026", keyword: "xây nhà Nhà Bè 2026", slug: "xay-nha-nha-be-2026-sk66", status: "done" },

  // 21–40 cải tạo / sửa
  { no: 6067, title: "Cải Tạo Nhà Phường 12 Tân Bình", keyword: "cải tạo nhà phường 12 Tân Bình", slug: "cai-tao-nha-phuong-12-tan-binh-sk66", status: "done" },
  { no: 6068, title: "Cải Tạo Nhà Phường 8 Phú Nhuận", keyword: "cải tạo nhà phường 8 Phú Nhuận", slug: "cai-tao-nha-phuong-8-phu-nhuan-sk66", status: "done" },
  { no: 6069, title: "Cải Tạo Nhà Cấp 4 Thành 2 Tầng", keyword: "cải tạo nhà cấp 4 thành 2 tầng", slug: "cai-tao-nha-cap-4-thanh-2-tang-sk66", status: "done" },
  { no: 6070, title: "Cải Tạo Nhà Ống Thiếu Sáng", keyword: "cải tạo nhà ống thiếu sáng", slug: "cai-tao-nha-ong-thieu-sang-sk66", status: "done" },
  { no: 6071, title: "Cải Tạo Nhà Thêm Lửng", keyword: "cải tạo nhà thêm lửng", slug: "cai-tao-nha-them-lung-sk66", status: "done" },
  { no: 6072, title: "Cải Tạo Nhà Mở Rộng Phía Sau", keyword: "cải tạo nhà mở rộng phía sau", slug: "cai-tao-nha-mo-rong-phia-sau-sk66", status: "done" },
  { no: 6073, title: "Cải Tạo Nhà Đổi Mặt Tiền Đá", keyword: "cải tạo nhà đổi mặt tiền đá", slug: "cai-tao-nha-doi-mat-tien-da-sk66", status: "done" },
  { no: 6074, title: "Cải Tạo Nhà Đổi Mặt Tiền Gạch", keyword: "cải tạo nhà đổi mặt tiền gạch", slug: "cai-tao-nha-doi-mat-tien-gach-sk66", status: "done" },
  { no: 6075, title: "Sửa Nhà Thấm Tường Ngoài", keyword: "sửa nhà thấm tường ngoài", slug: "sua-nha-tham-tuong-ngoai-sk66", status: "done" },
  { no: 6076, title: "Sửa Nhà Thấm Chân Tường", keyword: "sửa nhà thấm chân tường", slug: "sua-nha-tham-chan-tuong-sk66", status: "done" },
  { no: 6077, title: "Sửa Nhà Nứt Tường Liền Kề", keyword: "sửa nhà nứt tường liền kề", slug: "sua-nha-nut-tuong-lien-ke-sk66", status: "done" },
  { no: 6078, title: "Sửa Mái Tôn Dột TP.HCM", keyword: "sửa mái tôn dột TP.HCM", slug: "sua-mai-ton-dot-tphcm-sk66", status: "done" },
  { no: 6079, title: "Thay Mái Tôn Thành Mái Thái", keyword: "thay mái tôn thành mái Thái", slug: "thay-mai-ton-thanh-mai-thai-sk66", status: "done" },
  { no: 6080, title: "Nâng Tầng Nhà 3 Thành 4 Tầng", keyword: "nâng tầng nhà 3 thành 4 tầng", slug: "nang-tang-nha-3-thanh-4-tang-sk66", status: "done" },
  { no: 6081, title: "Cải Tạo Gác Lửng Thành Phòng Ngủ", keyword: "cải tạo gác lửng thành phòng ngủ", slug: "cai-tao-gac-lung-thanh-phong-ngu-sk66", status: "done" },
  { no: 6082, title: "Cải Tạo Nhà Cho Người Cao Tuổi", keyword: "cải tạo nhà cho người cao tuổi", slug: "cai-tao-nha-cho-nguoi-cao-tuoi-sk66", status: "done" },
  { no: 6083, title: "Cải Tạo Nhà Có Thang Máy Mini", keyword: "cải tạo nhà có thang máy mini", slug: "cai-tao-nha-co-thang-may-mini-sk66", status: "done" },
  { no: 6084, title: "Sửa Chữa Nhà Sau Mưa Ngập", keyword: "sửa chữa nhà sau mưa ngập", slug: "sua-chua-nha-sau-mua-ngap-sk66", status: "done" },
  { no: 6085, title: "Cải Tạo Nhà Kết Hợp Văn Phòng", keyword: "cải tạo nhà kết hợp văn phòng", slug: "cai-tao-nha-ket-hop-van-phong-sk66", status: "done" },
  { no: 6086, title: "Cải Tạo Nhà Kết Hợp Spa", keyword: "cải tạo nhà kết hợp spa", slug: "cai-tao-nha-ket-hop-spa-sk66", status: "done" },

  // 41–55 giá / ngân sách
  { no: 6087, title: "Đơn Giá Xây Phần Thô 2026 TP.HCM", keyword: "đơn giá xây phần thô 2026 TP.HCM", slug: "don-gia-xay-phan-tho-2026-tphcm-sk66", status: "done" },
  { no: 6088, title: "Đơn Giá Xây Trọn Gói 2026 TP.HCM", keyword: "đơn giá xây trọn gói 2026 TP.HCM", slug: "don-gia-xay-tron-goi-2026-tphcm-sk66", status: "done" },
  { no: 6089, title: "Chi Phí Xây Nhà 4×14 Trọn Gói", keyword: "chi phí xây nhà 4x14 trọn gói", slug: "chi-phi-xay-nha-4x14-tron-goi-sk66", status: "done" },
  { no: 6090, title: "Chi Phí Xây Nhà 4×18 Trọn Gói", keyword: "chi phí xây nhà 4x18 trọn gói", slug: "chi-phi-xay-nha-4x18-tron-goi-sk66", status: "done" },
  { no: 6091, title: "Chi Phí Xây Nhà 5×16 Trọn Gói", keyword: "chi phí xây nhà 5x16 trọn gói", slug: "chi-phi-xay-nha-5x16-tron-goi-sk66", status: "done" },
  { no: 6092, title: "Chi Phí Xây Nhà 1 Trệt 1 Lầu 2026", keyword: "chi phí xây nhà 1 trệt 1 lầu 2026", slug: "chi-phi-xay-nha-1-tret-1-lau-2026-sk66", status: "done" },
  { no: 6093, title: "Báo Giá Khoan Cọc Nhồi Nhà Phố", keyword: "báo giá khoan cọc nhồi nhà phố", slug: "bao-gia-khoan-coc-nhoi-nha-pho-sk66", status: "done" },
  { no: 6094, title: "Báo Giá Phá Dỡ Nhà Cũ TP.HCM", keyword: "báo giá phá dỡ nhà cũ TP.HCM", slug: "bao-gia-pha-do-nha-cu-tphcm-sk66", status: "done" },
  { no: 6095, title: "Ngân Sách Xây Nhà 1,5 Tỷ TP.HCM", keyword: "ngân sách xây nhà 1.5 tỷ TP.HCM", slug: "ngan-sach-xay-nha-1-5-ty-tphcm-sk66", status: "done" },
  { no: 6096, title: "Ngân Sách Xây Nhà 4 Tỷ TP.HCM", keyword: "ngân sách xây nhà 4 tỷ TP.HCM", slug: "ngan-sach-xay-nha-4-ty-tphcm-sk66", status: "done" },
  { no: 6097, title: "Ngân Sách Xây Nhà 7 Tỷ TP.HCM", keyword: "ngân sách xây nhà 7 tỷ TP.HCM", slug: "ngan-sach-xay-nha-7-ty-tphcm-sk66", status: "done" },
  { no: 6098, title: "Báo Giá Cải Tạo Nhà 200 Triệu", keyword: "báo giá cải tạo nhà 200 triệu", slug: "bao-gia-cai-tao-nha-200-trieu-sk66", status: "done" },
  { no: 6099, title: "Báo Giá Cải Tạo Nhà 500 Triệu", keyword: "báo giá cải tạo nhà 500 triệu", slug: "bao-gia-cai-tao-nha-500-trieu-sk66", status: "done" },
  { no: 6100, title: "Chi Phí Xin Phép Nâng Tầng TP.HCM", keyword: "chi phí xin phép nâng tầng TP.HCM", slug: "chi-phi-xin-phep-nang-tang-tphcm-sk66", status: "done" },
  { no: 6101, title: "Cách Tính m2 Sàn Xây Dựng", keyword: "cách tính m2 sàn xây dựng", slug: "cach-tinh-m2-san-xay-dung-sk66", status: "done" },

  // 56–70 thiết kế
  { no: 6102, title: "Thiết Kế Nhà Phố Phong Cách Scandinavian", keyword: "thiết kế nhà phố Scandinavian", slug: "thiet-ke-nha-pho-scandinavian-sk66", status: "done" },
  { no: 6103, title: "Thiết Kế Nhà Phố Phong Cách Industrial", keyword: "thiết kế nhà phố industrial", slug: "thiet-ke-nha-pho-industrial-sk66", status: "done" },
  { no: 6104, title: "Thiết Kế Nhà Phố Phong Cách Luxury", keyword: "thiết kế nhà phố luxury", slug: "thiet-ke-nha-pho-luxury-sk66", status: "done" },
  { no: 6105, title: "Thiết Kế Nhà Phố Có Sân Trong", keyword: "thiết kế nhà phố có sân trong", slug: "thiet-ke-nha-pho-co-san-trong-sk66", status: "done" },
  { no: 6106, title: "Thiết Kế Nhà Phố Có Ban Công Xanh", keyword: "thiết kế nhà phố có ban công xanh", slug: "thiet-ke-nha-pho-co-ban-cong-xanh-sk66", status: "done" },
  { no: 6107, title: "Thiết Kế Nhà Phố 3 Phòng Ngủ", keyword: "thiết kế nhà phố 3 phòng ngủ", slug: "thiet-ke-nha-pho-3-phong-ngu-sk66", status: "done" },
  { no: 6108, title: "Thiết Kế Nhà Phố 4 Phòng Ngủ", keyword: "thiết kế nhà phố 4 phòng ngủ", slug: "thiet-ke-nha-pho-4-phong-ngu-sk66", status: "done" },
  { no: 6109, title: "Thiết Kế Nhà Phố Có Phòng Thờ", keyword: "thiết kế nhà phố có phòng thờ", slug: "thiet-ke-nha-pho-co-phong-tho-sk66", status: "done" },
  { no: 6110, title: "Thiết Kế Biệt Thự Phố TP.HCM", keyword: "thiết kế biệt thự phố TP.HCM", slug: "thiet-ke-biet-thu-pho-tphcm-sk66", status: "done" },
  { no: 6111, title: "Thiết Kế Nhà Vườn Bình Dương", keyword: "thiết kế nhà vườn Bình Dương", slug: "thiet-ke-nha-vuon-binh-duong-sk66", status: "done" },
  { no: 6112, title: "Mẫu Nhà Phố 4 Tầng Đẹp 2026", keyword: "mẫu nhà phố 4 tầng đẹp 2026", slug: "mau-nha-pho-4-tang-dep-2026-sk66", status: "done" },
  { no: 6113, title: "Mẫu Nhà Cấp 4 Mái Thái 2026", keyword: "mẫu nhà cấp 4 mái Thái 2026", slug: "mau-nha-cap-4-mai-thai-2026-sk66", status: "done" },
  { no: 6114, title: "Thiết Kế Bếp Chữ U Nhà Phố", keyword: "thiết kế bếp chữ U nhà phố", slug: "thiet-ke-bep-chu-u-nha-pho-sk66", status: "done" },
  { no: 6115, title: "Thiết Kế Cầu Thang Xương Cá", keyword: "thiết kế cầu thang xương cá", slug: "thiet-ke-cau-thang-xuong-ca-sk66", status: "done" },
  { no: 6116, title: "Thiết Kế Giếng Trời Lấy Sáng", keyword: "thiết kế giếng trời lấy sáng", slug: "thiet-ke-gieng-troi-lay-sang-sk66", status: "done" },

  // 71–85 kỹ thuật / hoàn thiện
  { no: 6117, title: "Xây Nhà Panel Cách Nhiệt", keyword: "xây nhà panel cách nhiệt", slug: "xay-nha-panel-cach-nhiet-sk66", status: "done" },
  { no: 6118, title: "Xây Nhà Tường Bao Cách Âm", keyword: "xây nhà tường bao cách âm", slug: "xay-nha-tuong-bao-cach-am-sk66", status: "done" },
  { no: 6119, title: "Đổ Cột Nhà Phố Đúng Chuẩn", keyword: "đổ cột nhà phố đúng chuẩn", slug: "do-cot-nha-pho-dung-chuan-sk66", status: "done" },
  { no: 6120, title: "Đổ Dầm Sàn Nhà Phố", keyword: "đổ dầm sàn nhà phố", slug: "do-dam-san-nha-pho-sk66", status: "done" },
  { no: 6121, title: "Làm Mái Ngói Nhà Phố", keyword: "làm mái ngói nhà phố", slug: "lam-mai-ngoi-nha-pho-sk66", status: "done" },
  { no: 6122, title: "Làm Mái Kính Lấy Sáng", keyword: "làm mái kính lấy sáng", slug: "lam-mai-kinh-lay-sang-sk66", status: "done" },
  { no: 6123, title: "Chống Nóng Tường Tây Nhà Phố", keyword: "chống nóng tường Tây nhà phố", slug: "chong-nong-tuong-tay-nha-pho-sk66", status: "done" },
  { no: 6124, title: "Lắp Cửa Gỗ Công Nghiệp Nhà Phố", keyword: "lắp cửa gỗ công nghiệp nhà phố", slug: "lap-cua-go-cong-nghiep-nha-pho-sk66", status: "done" },
  { no: 6125, title: "Ốp Gạch Thẻ Mặt Tiền", keyword: "ốp gạch thẻ mặt tiền", slug: "op-gach-the-mat-tien-sk66", status: "done" },
  { no: 6126, title: "Sơn Nội Thất Không Mùi", keyword: "sơn nội thất không mùi", slug: "son-noi-that-khong-mui-sk66", status: "done" },
  { no: 6127, title: "Lát Sàn Gỗ Công Nghiệp Nhà Phố", keyword: "lát sàn gỗ công nghiệp nhà phố", slug: "lat-san-go-cong-nghiep-nha-pho-sk66", status: "done" },
  { no: 6128, title: "Làm Trần Thạch Cao Giấu Đèn", keyword: "làm trần thạch cao giấu đèn", slug: "lam-tran-thach-cao-giau-den-sk66", status: "done" },
  { no: 6129, title: "Lắp Điện Thông Minh Nhà Phố", keyword: "lắp điện thông minh nhà phố", slug: "lap-dien-thong-minh-nha-pho-sk66", status: "done" },
  { no: 6130, title: "Lắp Máy Nước Nóng Trung Tâm", keyword: "lắp máy nước nóng trung tâm", slug: "lap-may-nuoc-nong-trung-tam-sk66", status: "done" },
  { no: 6131, title: "Gia Cổ Cột Nhà Cũ Trước Cải Tạo", keyword: "gia cố cột nhà cũ trước cải tạo", slug: "gia-co-cot-nha-cu-truoc-cai-tao-sk66", status: "done" },

  // 86–100 tỉnh + quyết định
  { no: 6132, title: "Xây Nhà Trọn Gói Tân Uyên", keyword: "xây nhà trọn gói Tân Uyên", slug: "xay-nha-tron-goi-tan-uyen-sk66", status: "done" },
  { no: 6133, title: "Xây Nhà Trọn Gói Bàu Bàng", keyword: "xây nhà trọn gói Bàu Bàng", slug: "xay-nha-tron-goi-bau-bang-sk66", status: "done" },
  { no: 6134, title: "Xây Nhà Trọn Gói Nhơn Trạch", keyword: "xây nhà trọn gói Nhơn Trạch", slug: "xay-nha-tron-goi-nhon-trach-sk66", status: "done" },
  { no: 6135, title: "Xây Nhà Trọn Gói Trảng Bom", keyword: "xây nhà trọn gói Trảng Bom", slug: "xay-nha-tron-goi-trang-bom-sk66", status: "done" },
  { no: 6136, title: "Xây Nhà Trọn Gói Đức Hòa", keyword: "xây nhà trọn gói Đức Hòa", slug: "xay-nha-tron-goi-duc-hoa-sk66", status: "done" },
  { no: 6137, title: "Xây Nhà Trọn Gói Cần Đước", keyword: "xây nhà trọn gói Cần Đước", slug: "xay-nha-tron-goi-can-duoc-sk66", status: "done" },
  { no: 6138, title: "Xây Nhà Trọn Gói Bến Cát", keyword: "xây nhà trọn gói Bến Cát", slug: "xay-nha-tron-goi-ben-cat-sk66", status: "done" },
  { no: 6139, title: "Cải Tạo Nhà Thuận An Bình Dương", keyword: "cải tạo nhà Thuận An", slug: "cai-tao-nha-thuan-an-sk66", status: "done" },
  { no: 6140, title: "Cải Tạo Nhà Long Thành Đồng Nai", keyword: "cải tạo nhà Long Thành", slug: "cai-tao-nha-long-thanh-sk66", status: "done" },
  { no: 6141, title: "So Sánh Thầu Trọn Gói Và Thầu Thô", keyword: "so sánh thầu trọn gói và thầu thô", slug: "so-sanh-thau-tron-goi-va-thau-tho-sk66", status: "done" },
  { no: 6142, title: "Câu Hỏi Khi Gặp Nhà Thầu Xây Nhà", keyword: "câu hỏi khi gặp nhà thầu xây nhà", slug: "cau-hoi-khi-gap-nha-thau-xay-nha-sk66", status: "done" },
  { no: 6143, title: "Cách Kiểm Tra Vật Tư Trên Công Trường", keyword: "cách kiểm tra vật tư trên công trường", slug: "cach-kiem-tra-vat-tu-cong-truong-sk66", status: "done" },
  { no: 6144, title: "Mốc Nghiệm Thu Xây Nhà Phải Có", keyword: "mốc nghiệm thu xây nhà phải có", slug: "moc-nghiem-thu-xay-nha-phai-co-sk66", status: "done" },
  { no: 6145, title: "Hồ Sơ Bàn Giao Nhà Mới Xây", keyword: "hồ sơ bàn giao nhà mới xây", slug: "ho-so-ban-giao-nha-moi-xay-sk66", status: "done" },
  { no: 6146, title: "Khi Nào Nên Khảo Sát Địa Chất", keyword: "khi nào nên khảo sát địa chất", slug: "khi-nao-nen-khao-sat-dia-chat-sk66", status: "done" },
];
