/**
 * Lịch 100 từ khóa SEO — batch 69 (#6347–#6446).
 * Cluster: Gò Vấp/Bình Thạnh phường + shophouse/PCCC + FAQ Ads (indexable *-sk69).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch69: ContentCalendarItem[] = [
  { no: 6347, title: "Xây Nhà Trọn Gói Gò Vấp 2026", keyword: "xây nhà trọn gói Gò Vấp 2026", slug: "xay-nha-tron-goi-go-vap-2026-sk69", status: "done" },
  { no: 6348, title: "Xây Nhà Phường 1 Gò Vấp", keyword: "xây nhà phường 1 Gò Vấp", slug: "xay-nha-phuong-1-go-vap-sk69", status: "done" },
  { no: 6349, title: "Xây Nhà Phường 3 Gò Vấp", keyword: "xây nhà phường 3 Gò Vấp", slug: "xay-nha-phuong-3-go-vap-sk69", status: "done" },
  { no: 6350, title: "Xây Nhà Phường 6 Gò Vấp", keyword: "xây nhà phường 6 Gò Vấp", slug: "xay-nha-phuong-6-go-vap-sk69", status: "done" },
  { no: 6351, title: "Xây Nhà Phường 8 Gò Vấp", keyword: "xây nhà phường 8 Gò Vấp", slug: "xay-nha-phuong-8-go-vap-sk69", status: "done" },
  { no: 6352, title: "Xây Nhà Phường 10 Gò Vấp", keyword: "xây nhà phường 10 Gò Vấp", slug: "xay-nha-phuong-10-go-vap-sk69", status: "done" },
  { no: 6353, title: "Xây Nhà Phường 12 Gò Vấp", keyword: "xây nhà phường 12 Gò Vấp", slug: "xay-nha-phuong-12-go-vap-sk69", status: "done" },
  { no: 6354, title: "Xây Nhà Phường 14 Gò Vấp", keyword: "xây nhà phường 14 Gò Vấp", slug: "xay-nha-phuong-14-go-vap-sk69", status: "done" },
  { no: 6355, title: "Xây Nhà Phường 16 Gò Vấp", keyword: "xây nhà phường 16 Gò Vấp", slug: "xay-nha-phuong-16-go-vap-sk69", status: "done" },
  { no: 6356, title: "Xây Nhà Phường 19 Bình Thạnh", keyword: "xây nhà phường 19 Bình Thạnh", slug: "xay-nha-phuong-19-binh-thanh-sk69", status: "done" },
  { no: 6357, title: "Xây Nhà Phường 22 Bình Thạnh", keyword: "xây nhà phường 22 Bình Thạnh", slug: "xay-nha-phuong-22-binh-thanh-sk69", status: "done" },
  { no: 6358, title: "Xây Nhà Phường 24 Bình Thạnh", keyword: "xây nhà phường 24 Bình Thạnh", slug: "xay-nha-phuong-24-binh-thanh-sk69", status: "done" },
  { no: 6359, title: "Xây Nhà Phường 25 Bình Thạnh", keyword: "xây nhà phường 25 Bình Thạnh", slug: "xay-nha-phuong-25-binh-thanh-sk69", status: "done" },
  { no: 6360, title: "Xây Nhà Phường 27 Bình Thạnh", keyword: "xây nhà phường 27 Bình Thạnh", slug: "xay-nha-phuong-27-binh-thanh-sk69", status: "done" },
  { no: 6361, title: "Xây Nhà Phường 28 Bình Thạnh", keyword: "xây nhà phường 28 Bình Thạnh", slug: "xay-nha-phuong-28-binh-thanh-sk69", status: "done" },
  { no: 6362, title: "Xây Nhà Gần Chợ Gò Vấp", keyword: "xây nhà gần chợ Gò Vấp", slug: "xay-nha-gan-cho-go-vap-sk69", status: "done" },
  { no: 6363, title: "Xây Nhà Gần Phan Văn Trị", keyword: "xây nhà gần Phan Văn Trị", slug: "xay-nha-gan-phan-van-tri-sk69", status: "done" },
  { no: 6364, title: "Xây Nhà Gần Quang Trung Gò Vấp", keyword: "xây nhà gần Quang Trung Gò Vấp", slug: "xay-nha-gan-quang-trung-go-vap-sk69", status: "done" },
  { no: 6365, title: "Xây Nhà Gần Xô Viết Nghệ Tĩnh", keyword: "xây nhà gần Xô Viết Nghệ Tĩnh", slug: "xay-nha-gan-xo-viet-nghe-tinh-sk69", status: "done" },
  { no: 6366, title: "Xây Nhà Gần Đinh Bộ Lĩnh", keyword: "xây nhà gần Đinh Bộ Lĩnh", slug: "xay-nha-gan-dinh-bo-linh-sk69", status: "done" },

  { no: 6367, title: "Cải Tạo Nhà Gò Vấp 2026", keyword: "cải tạo nhà Gò Vấp 2026", slug: "cai-tao-nha-go-vap-2026-sk69", status: "done" },
  { no: 6368, title: "Cải Tạo Nhà Bình Thạnh 2026", keyword: "cải tạo nhà Bình Thạnh 2026", slug: "cai-tao-nha-binh-thanh-2026-sk69", status: "done" },
  { no: 6369, title: "Cải Tạo Shophouse Gò Vấp", keyword: "cải tạo shophouse Gò Vấp", slug: "cai-tao-shophouse-go-vap-sk69", status: "done" },
  { no: 6370, title: "Cải Tạo Shophouse Bình Thạnh", keyword: "cải tạo shophouse Bình Thạnh", slug: "cai-tao-shophouse-binh-thanh-sk69", status: "done" },
  { no: 6371, title: "Cải Tạo Nhà Thêm Quầy Thuốc", keyword: "cải tạo nhà thêm quầy thuốc", slug: "cai-tao-nha-them-quay-thuoc-sk69", status: "done" },
  { no: 6372, title: "Cải Tạo Nhà Thêm Tiệm Tóc", keyword: "cải tạo nhà thêm tiệm tóc", slug: "cai-tao-nha-them-tiem-toc-sk69", status: "done" },
  { no: 6373, title: "Cải Tạo Nhà Thêm Quán Cafe", keyword: "cải tạo nhà thêm quán cafe", slug: "cai-tao-nha-them-quan-cafe-sk69", status: "done" },
  { no: 6374, title: "Cải Tạo Nhà Thêm Cửa Hàng Tiện Lợi", keyword: "cải tạo nhà thêm cửa hàng tiện lợi", slug: "cai-tao-nha-them-cua-hang-tien-loi-sk69", status: "done" },
  { no: 6375, title: "Sửa Nhà Thấm Mái Tôn Gò Vấp", keyword: "sửa nhà thấm mái tôn Gò Vấp", slug: "sua-nha-tham-mai-ton-go-vap-sk69", status: "done" },
  { no: 6376, title: "Sửa Nhà Thấm Tường Bình Thạnh", keyword: "sửa nhà thấm tường Bình Thạnh", slug: "sua-nha-tham-tuong-binh-thanh-sk69", status: "done" },
  { no: 6377, title: "Sửa Nhà Nứt Cột Liền Kề", keyword: "sửa nhà nứt cột liền kề", slug: "sua-nha-nut-cot-lien-ke-sk69", status: "done" },
  { no: 6378, title: "Sửa Hệ Thống Điện Quá Tải", keyword: "sửa hệ thống điện quá tải", slug: "sua-he-thong-dien-qua-tai-sk69", status: "done" },
  { no: 6379, title: "Thay Ống Cống Nhà Phố Cũ", keyword: "thay ống cống nhà phố cũ", slug: "thay-ong-cong-nha-pho-cu-sk69", status: "done" },
  { no: 6380, title: "Nâng Tầng Nhà Shophouse", keyword: "nâng tầng nhà shophouse", slug: "nang-tang-nha-shophouse-sk69", status: "done" },
  { no: 6381, title: "Cải Tạo Nhà Thành Phòng Khám", keyword: "cải tạo nhà thành phòng khám", slug: "cai-tao-nha-thanh-phong-kham-sk69", status: "done" },
  { no: 6382, title: "Cải Tạo Nhà Thành Trường Mầm Non", keyword: "cải tạo nhà thành trường mầm non", slug: "cai-tao-nha-thanh-truong-mam-non-sk69", status: "done" },
  { no: 6383, title: "Cải Tạo Nhà Cho Gia Đình 3 Thế Hệ", keyword: "cải tạo nhà cho gia đình 3 thế hệ", slug: "cai-tao-nha-cho-gia-dinh-3-the-he-sk69", status: "done" },
  { no: 6384, title: "Sửa Chữa Nhà Sau Cải Tạo Rẻ", keyword: "sửa chữa nhà sau cải tạo kém", slug: "sua-chua-nha-sau-cai-tao-kem-sk69", status: "done" },
  { no: 6385, title: "Cải Tạo Nhà Giảm Ồn Mặt Tiền", keyword: "cải tạo nhà giảm ồn mặt tiền", slug: "cai-tao-nha-giam-on-mat-tien-sk69", status: "done" },
  { no: 6386, title: "Cải Tạo Nhà Tăng Ánh Sáng Tự Nhiên", keyword: "cải tạo nhà tăng ánh sáng tự nhiên", slug: "cai-tao-nha-tang-anh-sang-tu-nhien-sk69", status: "done" },

  { no: 6387, title: "Đơn Giá Xây Shophouse 2026", keyword: "đơn giá xây shophouse 2026", slug: "don-gia-xay-shophouse-2026-sk69", status: "done" },
  { no: 6388, title: "Chi Phí Xây Nhà Có PCCC", keyword: "chi phí xây nhà có PCCC", slug: "chi-phi-xay-nha-co-pccc-sk69", status: "done" },
  { no: 6389, title: "Chi Phí Xây Nhà 4×17 Trọn Gói", keyword: "chi phí xây nhà 4x17 trọn gói", slug: "chi-phi-xay-nha-4x17-tron-goi-sk69", status: "done" },
  { no: 6390, title: "Chi Phí Xây Nhà 5×17 Trọn Gói", keyword: "chi phí xây nhà 5x17 trọn gói", slug: "chi-phi-xay-nha-5x17-tron-goi-sk69", status: "done" },
  { no: 6391, title: "Chi Phí Xây Nhà 5×19 Trọn Gói", keyword: "chi phí xây nhà 5x19 trọn gói", slug: "chi-phi-xay-nha-5x19-tron-goi-sk69", status: "done" },
  { no: 6392, title: "Báo Giá Thiết Kế Shophouse", keyword: "báo giá thiết kế shophouse", slug: "bao-gia-thiet-ke-shophouse-sk69", status: "done" },
  { no: 6393, title: "Báo Giá Lắp Hệ Thống PCCC Nhà Phố", keyword: "báo giá lắp PCCC nhà phố", slug: "bao-gia-lap-pccc-nha-pho-sk69", status: "done" },
  { no: 6394, title: "Ngân Sách Xây Nhà 6 Tỷ TP.HCM", keyword: "ngân sách xây nhà 6 tỷ TP.HCM", slug: "ngan-sach-xay-nha-6-ty-tphcm-sk69", status: "done" },
  { no: 6395, title: "Ngân Sách Cải Tạo Nhà 600 Triệu", keyword: "ngân sách cải tạo nhà 600 triệu", slug: "ngan-sach-cai-tao-nha-600-trieu-sk69", status: "done" },
  { no: 6396, title: "Chi Phí Chống Thấm Shophouse", keyword: "chi phí chống thấm shophouse", slug: "chi-phi-chong-tham-shophouse-sk69", status: "done" },
  { no: 6397, title: "Chi Phí Làm Mặt Tiền Kính", keyword: "chi phí làm mặt tiền kính", slug: "chi-phi-lam-mat-tien-kinh-sk69", status: "done" },
  { no: 6398, title: "Báo Giá Sơn Mặt Tiền Shophouse", keyword: "báo giá sơn mặt tiền shophouse", slug: "bao-gia-son-mat-tien-shophouse-sk69", status: "done" },
  { no: 6399, title: "Báo Giá Lát Gạch Chống Trơn Trệt", keyword: "báo giá lát gạch chống trơn trệt", slug: "bao-gia-lat-gach-chong-tron-tret-sk69", status: "done" },
  { no: 6400, title: "Chi Phí Lắp Điện 3 Pha Shophouse", keyword: "chi phí lắp điện 3 pha shophouse", slug: "chi-phi-lap-dien-3-pha-shophouse-sk69", status: "done" },
  { no: 6401, title: "Cách Tính Chi Phí Xây Shophouse", keyword: "cách tính chi phí xây shophouse", slug: "cach-tinh-chi-phi-xay-shophouse-sk69", status: "done" },

  { no: 6402, title: "Thiết Kế Shophouse 1 Trệt 3 Lầu", keyword: "thiết kế shophouse 1 trệt 3 lầu", slug: "thiet-ke-shophouse-1-tret-3-lau-sk69", status: "done" },
  { no: 6403, title: "Thiết Kế Shophouse Mặt Tiền 4m", keyword: "thiết kế shophouse mặt tiền 4m", slug: "thiet-ke-shophouse-mat-tien-4m-sk69", status: "done" },
  { no: 6404, title: "Thiết Kế Shophouse Mặt Tiền 5m", keyword: "thiết kế shophouse mặt tiền 5m", slug: "thiet-ke-shophouse-mat-tien-5m-sk69", status: "done" },
  { no: 6405, title: "Thiết Kế Nhà Phố Có Quầy Bar", keyword: "thiết kế nhà phố có quầy bar", slug: "thiet-ke-nha-pho-co-quay-bar-sk69", status: "done" },
  { no: 6406, title: "Thiết Kế Nhà Phố Có Showroom", keyword: "thiết kế nhà phố có showroom", slug: "thiet-ke-nha-pho-co-showroom-sk69", status: "done" },
  { no: 6407, title: "Thiết Kế Nhà Phố 6 Phòng Ngủ", keyword: "thiết kế nhà phố 6 phòng ngủ", slug: "thiet-ke-nha-pho-6-phong-ngu-sk69", status: "done" },
  { no: 6408, title: "Thiết Kế Nhà Phố Có Phòng Meeting", keyword: "thiết kế nhà phố có phòng meeting", slug: "thiet-ke-nha-pho-co-phong-meeting-sk69", status: "done" },
  { no: 6409, title: "Thiết Kế Nhà Phố Có Kho Hàng", keyword: "thiết kế nhà phố có kho hàng", slug: "thiet-ke-nha-pho-co-kho-hang-sk69", status: "done" },
  { no: 6410, title: "Thiết Kế Biệt Thự Phố Gò Vấp", keyword: "thiết kế biệt thự phố Gò Vấp", slug: "thiet-ke-biet-thu-pho-go-vap-sk69", status: "done" },
  { no: 6411, title: "Thiết Kế Nhà Vườn Bình Chánh", keyword: "thiết kế nhà vườn Bình Chánh", slug: "thiet-ke-nha-vuon-binh-chanh-sk69", status: "done" },
  { no: 6412, title: "Mẫu Nhà Phố Mặt Tiền 3,5m 2026", keyword: "mẫu nhà phố mặt tiền 3.5m 2026", slug: "mau-nha-pho-mat-tien-3-5m-2026-sk69", status: "done" },
  { no: 6413, title: "Mẫu Shophouse 2026 TP.HCM", keyword: "mẫu shophouse 2026 TP.HCM", slug: "mau-shophouse-2026-tphcm-sk69", status: "done" },
  { no: 6414, title: "Thiết Kế Bếp Công Nghiệp Nhà Phố", keyword: "thiết kế bếp công nghiệp nhà phố", slug: "thiet-ke-bep-cong-nghiep-nha-pho-sk69", status: "done" },
  { no: 6415, title: "Thiết Kế Cầu Thang Thoát Hiểm", keyword: "thiết kế cầu thang thoát hiểm", slug: "thiet-ke-cau-thang-thoat-hiem-sk69", status: "done" },
  { no: 6416, title: "Thiết Kế Giếng Trời Shophouse", keyword: "thiết kế giếng trời shophouse", slug: "thiet-ke-gieng-troi-shophouse-sk69", status: "done" },

  { no: 6417, title: "Xây Nhà Đáp Ứng PCCC TP.HCM", keyword: "xây nhà đáp ứng PCCC TP.HCM", slug: "xay-nha-dap-ung-pccc-tphcm-sk69", status: "done" },
  { no: 6418, title: "Xây Nhà Có Lối Thoát Hiểm", keyword: "xây nhà có lối thoát hiểm", slug: "xay-nha-co-loi-thoat-hiem-sk69", status: "done" },
  { no: 6419, title: "Đổ Móng Nhà Shophouse", keyword: "đổ móng nhà shophouse", slug: "do-mong-nha-shophouse-sk69", status: "done" },
  { no: 6420, title: "Đổ Sàn Trệt Chịu Tải Kinh Doanh", keyword: "đổ sàn trệt chịu tải kinh doanh", slug: "do-san-tret-chiu-tai-kinh-doanh-sk69", status: "done" },
  { no: 6421, title: "Làm Mái Shophouse Chống Thấm", keyword: "làm mái shophouse chống thấm", slug: "lam-mai-shophouse-chong-tham-sk69", status: "done" },
  { no: 6422, title: "Làm Biển Hiệu Mặt Tiền Nhà Phố", keyword: "làm biển hiệu mặt tiền nhà phố", slug: "lam-bien-hieu-mat-tien-nha-pho-sk69", status: "done" },
  { no: 6423, title: "Chống Nóng Mặt Tiền Kính", keyword: "chống nóng mặt tiền kính", slug: "chong-nong-mat-tien-kinh-sk69", status: "done" },
  { no: 6424, title: "Lắp Cửa Kính Cường Lực Trệt", keyword: "lắp cửa kính cường lực trệt", slug: "lap-cua-kinh-cuong-luc-tret-sk69", status: "done" },
  { no: 6425, title: "Ốp Alu Mặt Tiền Shophouse", keyword: "ốp alu mặt tiền shophouse", slug: "op-alu-mat-tien-shophouse-sk69", status: "done" },
  { no: 6426, title: "Sơn Chống Cháy Kết Cấu Thép", keyword: "sơn chống cháy kết cấu thép", slug: "son-chong-chay-ket-cau-thep-sk69", status: "done" },
  { no: 6427, title: "Lát Gạch Chống Axit Bếp Quán", keyword: "lát gạch chống axit bếp quán", slug: "lat-gach-chong-axit-bep-quan-sk69", status: "done" },
  { no: 6428, title: "Làm Vách Ngăn Chống Cháy", keyword: "làm vách ngăn chống cháy", slug: "lam-vach-ngan-chong-chay-sk69", status: "done" },
  { no: 6429, title: "Lắp Báo Cháy Báo Khói Nhà Phố", keyword: "lắp báo cháy báo khói nhà phố", slug: "lap-bao-chay-bao-khoi-nha-pho-sk69", status: "done" },
  { no: 6430, title: "Lắp Hệ Thống Hút Mùi Quán", keyword: "lắp hệ thống hút mùi quán", slug: "lap-he-thong-hut-mui-quan-sk69", status: "done" },
  { no: 6431, title: "Gia Cố Sàn Trệt Cho Máy Nặng", keyword: "gia cố sàn trệt cho máy nặng", slug: "gia-co-san-tret-cho-may-nang-sk69", status: "done" },

  { no: 6432, title: "Xây Nhà Trọn Gói Long Thành 2026", keyword: "xây nhà trọn gói Long Thành 2026", slug: "xay-nha-tron-goi-long-thanh-2026-sk69", status: "done" },
  { no: 6433, title: "Xây Nhà Trọn Gói Nhơn Trạch 2026", keyword: "xây nhà trọn gói Nhơn Trạch 2026", slug: "xay-nha-tron-goi-nhon-trach-2026-sk69", status: "done" },
  { no: 6434, title: "Xây Nhà Trọn Gói Dĩ An 2026", keyword: "xây nhà trọn gói Dĩ An 2026", slug: "xay-nha-tron-goi-di-an-2026-sk69", status: "done" },
  { no: 6435, title: "Xây Nhà Trọn Gói Thuận An Mới", keyword: "xây nhà trọn gói Thuận An mới", slug: "xay-nha-tron-goi-thuan-an-moi-sk69", status: "done" },
  { no: 6436, title: "Xây Nhà Trọn Gói Bến Lức 2026", keyword: "xây nhà trọn gói Bến Lức 2026", slug: "xay-nha-tron-goi-ben-luc-2026-sk69", status: "done" },
  { no: 6437, title: "Xây Nhà Trọn Gói Đức Hòa 2026", keyword: "xây nhà trọn gói Đức Hòa 2026", slug: "xay-nha-tron-goi-duc-hoa-2026-sk69", status: "done" },
  { no: 6438, title: "Xây Nhà Trọn Gói Cần Giuộc 2026", keyword: "xây nhà trọn gói Cần Giuộc 2026", slug: "xay-nha-tron-goi-can-giuoc-2026-sk69", status: "done" },
  { no: 6439, title: "Cải Tạo Nhà Dĩ An 2026", keyword: "cải tạo nhà Dĩ An 2026", slug: "cai-tao-nha-di-an-2026-sk69", status: "done" },
  { no: 6440, title: "Cải Tạo Nhà Biên Hòa 2026", keyword: "cải tạo nhà Biên Hòa 2026", slug: "cai-tao-nha-bien-hoa-2026-sk69", status: "done" },
  { no: 6441, title: "Xây Shophouse Cần Giấy Phép Gì", keyword: "xây shophouse cần giấy phép gì", slug: "xay-shophouse-can-giay-phep-gi-sk69", status: "done" },
  { no: 6442, title: "Nhà Ở Kết Hợp Kinh Doanh Có PCCC Không", keyword: "nhà ở kết hợp kinh doanh có PCCC không", slug: "nha-o-ket-hop-kinh-doanh-co-pccc-khong-sk69", status: "done" },
  { no: 6443, title: "Xây Nhà Cho Thuê Có Nên Tách Điện", keyword: "xây nhà cho thuê có nên tách điện", slug: "xay-nha-cho-thue-co-nen-tach-dien-sk69", status: "done" },
  { no: 6444, title: "Cách Chọn Gói Trọn Gói Hay Thô", keyword: "cách chọn gói trọn gói hay thô", slug: "cach-chon-goi-tron-goi-hay-tho-sk69", status: "done" },
  { no: 6445, title: "Checklist Khảo Sát Shophouse", keyword: "checklist khảo sát shophouse", slug: "checklist-khao-sat-shophouse-sk69", status: "done" },
  { no: 6446, title: "Khi Nào Nên Gọi Kỹ Sư Kết Cấu", keyword: "khi nào nên gọi kỹ sư kết cấu", slug: "khi-nao-nen-goi-ky-su-ket-cau-sk69", status: "done" },
];
