/**
 * Lịch 100 từ khóa ngắn — batch 35 (#2947–#3046).
 * Cluster: nội thất phòng, hoàn thiện chi tiết, phong cách.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch35: ContentCalendarItem[] = [
  { no: 2947, title: "Thiết Kế Phòng Khách Nhà Phố", keyword: "thiết kế phòng khách nhà phố", slug: "thiet-ke-phong-khach-nha-pho-nt-ngan", status: "done" },
  { no: 2948, title: "Thiết Kế Phòng Ngủ Master", keyword: "thiết kế phòng ngủ master", slug: "thiet-ke-phong-ngu-master-nt-ngan", status: "done" },
  { no: 2949, title: "Thiết Kế Phòng Ngủ Nhỏ", keyword: "thiết kế phòng ngủ nhỏ", slug: "thiet-ke-phong-ngu-nho-nt-ngan", status: "done" },
  { no: 2950, title: "Thiết Kế Phòng Bếp Hiện Đại", keyword: "thiết kế phòng bếp hiện đại", slug: "thiet-ke-phong-bep-hien-dai-nt-ngan", status: "done" },
  { no: 2951, title: "Thiết Kế Phòng Ăn Nhà Phố", keyword: "thiết kế phòng ăn nhà phố", slug: "thiet-ke-phong-an-nha-pho-nt-ngan", status: "done" },
  { no: 2952, title: "Thiết Kế Phòng WC Hiện Đại", keyword: "thiết kế phòng wc hiện đại", slug: "thiet-ke-phong-wc-hien-dai-nt-ngan", status: "done" },
  { no: 2953, title: "Thiết Kế Phòng WC Khách", keyword: "thiết kế phòng wc khách", slug: "thiet-ke-phong-wc-khach-nt-ngan", status: "done" },
  { no: 2954, title: "Thiết Kế Phòng Giặt", keyword: "thiết kế phòng giặt", slug: "thiet-ke-phong-giat-nt-ngan", status: "done" },
  { no: 2955, title: "Thiết Kế Phòng Thờ Nhà Phố", keyword: "thiết kế phòng thờ nhà phố", slug: "thiet-ke-phong-tho-nha-pho-nt-ngan", status: "done" },
  { no: 2956, title: "Thiết Kế Phòng Kho", keyword: "thiết kế phòng kho", slug: "thiet-ke-phong-kho-nt-ngan", status: "done" },
  { no: 2957, title: "Thiết Kế Gác Lửng Nội Thất", keyword: "thiết kế gác lửng nội thất", slug: "thiet-ke-gac-lung-noi-that-nt-ngan", status: "done" },
  { no: 2958, title: "Thiết Kế Sân Thượng Nội Thất", keyword: "thiết kế sân thượng nội thất", slug: "thiet-ke-san-thuong-noi-that-nt-ngan", status: "done" },
  { no: 2959, title: "Thiết Kế Ban Công Nội Thất", keyword: "thiết kế ban công nội thất", slug: "thiet-ke-ban-cong-noi-that-nt-ngan", status: "done" },
  { no: 2960, title: "Nội Thất Phong Cách Tối Giản", keyword: "nội thất phong cách tối giản", slug: "noi-that-phong-cach-toi-gian-ngan", status: "done" },
  { no: 2961, title: "Nội Thất Phong Cách Scandinavian", keyword: "nội thất phong cách scandinavian", slug: "noi-that-phong-cach-scandinavian-ngan", status: "done" },
  { no: 2962, title: "Nội Thất Phong Cách Industrial", keyword: "nội thất phong cách industrial", slug: "noi-that-phong-cach-industrial-ngan", status: "done" },
  { no: 2963, title: "Nội Thất Phong Cách Japandi", keyword: "nội thất phong cách japandi", slug: "noi-that-phong-cach-japandi-ngan", status: "done" },
  { no: 2964, title: "Nội Thất Phong Cách Đông Dương", keyword: "nội thất phong cách đông dương", slug: "noi-that-phong-cach-dong-duong-ngan", status: "done" },
  { no: 2965, title: "Nội Thất Phong Cách Luxury", keyword: "nội thất phong cách luxury", slug: "noi-that-phong-cach-luxury-ngan", status: "done" },
  { no: 2966, title: "Nội Thất Phong Cách Wabi Sabi", keyword: "nội thất phong cách wabi sabi", slug: "noi-that-phong-cach-wabi-sabi-ngan", status: "done" },
  { no: 2967, title: "Chọn Sofa Phòng Khách", keyword: "chọn sofa phòng khách", slug: "chon-sofa-phong-khach-ngan", status: "done" },
  { no: 2968, title: "Chọn Bàn Ăn Nhà Phố", keyword: "chọn bàn ăn nhà phố", slug: "chon-ban-an-nha-pho-ngan", status: "done" },
  { no: 2969, title: "Chọn Giường Ngủ", keyword: "chọn giường ngủ", slug: "chon-giuong-ngu-ngan", status: "done" },
  { no: 2970, title: "Chọn Tủ Quần Áo", keyword: "chọn tủ quần áo", slug: "chon-tu-quan-ao-ngan", status: "done" },
  { no: 2971, title: "Chọn Tủ Bếp", keyword: "chọn tủ bếp", slug: "chon-tu-bep-ngan", status: "done" },
  { no: 2972, title: "Chọn Đá Bếp", keyword: "chọn đá bếp", slug: "chon-da-bep-ngan", status: "done" },
  { no: 2973, title: "Chọn Bếp Từ", keyword: "chọn bếp từ", slug: "chon-bep-tu-ngan", status: "done" },
  { no: 2974, title: "Chọn Máy Hút Mùi", keyword: "chọn máy hút mùi", slug: "chon-may-hut-mui-ngan", status: "done" },
  { no: 2975, title: "Chọn Chậu Rửa Bát", keyword: "chọn chậu rửa bát", slug: "chon-chau-rua-bat-ngan", status: "done" },
  { no: 2976, title: "Chọn Vòi Rửa Bát", keyword: "chọn vòi rửa bát", slug: "chon-voi-rua-bat-ngan", status: "done" },
  { no: 2977, title: "Chọn Gạch Nhà Tắm", keyword: "chọn gạch nhà tắm", slug: "chon-gach-nha-tam-ngan", status: "done" },
  { no: 2978, title: "Chọn Sen Cây", keyword: "chọn sen cây", slug: "chon-sen-cay-ngan", status: "done" },
  { no: 2979, title: "Chọn Lavabo", keyword: "chọn lavabo", slug: "chon-lavabo-ngan", status: "done" },
  { no: 2980, title: "Chọn Gương Nhà Tắm", keyword: "chọn gương nhà tắm", slug: "chon-guong-nha-tam-ngan", status: "done" },
  { no: 2981, title: "Chọn Đèn Trần Nhà", keyword: "chọn đèn trần nhà", slug: "chon-den-tran-nha-ngan", status: "done" },
  { no: 2982, title: "Chọn Đèn Phòng Ngủ", keyword: "chọn đèn phòng ngủ", slug: "chon-den-phong-ngu-ngan", status: "done" },
  { no: 2983, title: "Chọn Rèm Cửa", keyword: "chọn rèm cửa", slug: "chon-rem-cua-ngan", status: "done" },
  { no: 2984, title: "Chọn Giấy Dán Tường", keyword: "chọn giấy dán tường", slug: "chon-giay-dan-tuong-ngan", status: "done" },
  { no: 2985, title: "Chọn Thảm Trải Sàn", keyword: "chọn thảm trải sàn", slug: "chon-tham-trai-san-ngan", status: "done" },
  { no: 2986, title: "Chọn Tranh Trang Trí", keyword: "chọn tranh trang trí", slug: "chon-tranh-trang-tri-ngan", status: "done" },
  { no: 2987, title: "Hoàn Thiện Trần Thạch Cao Chi Tiết", keyword: "hoàn thiện trần thạch cao chi tiết", slug: "hoan-thien-tran-thach-cao-chi-tiet-ngan", status: "done" },
  { no: 2988, title: "Hoàn Thiện Sơn Nước Chi Tiết", keyword: "hoàn thiện sơn nước chi tiết", slug: "hoan-thien-son-nuoc-chi-tiet-ngan", status: "done" },
  { no: 2989, title: "Hoàn Thiện Ốp Lát Chi Tiết", keyword: "hoàn thiện ốp lát chi tiết", slug: "hoan-thien-op-lat-chi-tiet-ngan", status: "done" },
  { no: 2990, title: "Hoàn Thiện Hệ Điện Chi Tiết", keyword: "hoàn thiện hệ điện chi tiết", slug: "hoan-thien-he-dien-chi-tiet-ngan", status: "done" },
  { no: 2991, title: "Hoàn Thiện Hệ Nước Chi Tiết", keyword: "hoàn thiện hệ nước chi tiết", slug: "hoan-thien-he-nuoc-chi-tiet-ngan", status: "done" },
  { no: 2992, title: "Nẹp Inox Trang Trí", keyword: "nẹp inox trang trí", slug: "nep-inox-trang-tri-ngan", status: "done" },
  { no: 2993, title: "Nẹp Đồng Trang Trí", keyword: "nẹp đồng trang trí", slug: "nep-dong-trang-tri-ngan", status: "done" },
  { no: 2994, title: "Phào Chỉ Trần Nhà", keyword: "phào chỉ trần nhà", slug: "phao-chi-tran-nha-ngan", status: "done" },
  { no: 2995, title: "Phào Chỉ Tường Nhà", keyword: "phào chỉ tường nhà", slug: "phao-chi-tuong-nha-ngan", status: "done" },
  { no: 2996, title: "Vách CNC Phòng Khách", keyword: "vách cnc phòng khách", slug: "vach-cnc-phong-khach-ngan", status: "done" },
  { no: 2997, title: "Vách Lam Gỗ Phòng Khách", keyword: "vách lam gỗ phòng khách", slug: "vach-lam-go-phong-khach-ngan", status: "done" },
  { no: 2998, title: "Vách Kính Cường Lực Nội Thất", keyword: "vách kính cường lực nội thất", slug: "vach-kinh-cuong-luc-noi-that-ngan", status: "done" },
  { no: 2999, title: "Cầu Thang Gỗ Óc Chó", keyword: "cầu thang gỗ óc chó", slug: "cau-thang-go-oc-cho-ngan", status: "done" },
  { no: 3000, title: "Cầu Thang Kính Không Trụ", keyword: "cầu thang kính không trụ", slug: "cau-thang-kinh-khong-tru-ngan", status: "done" },
  { no: 3001, title: "Cầu Thang Xoắn Ốc Nội Thất", keyword: "cầu thang xoắn ốc nội thất", slug: "cau-thang-xoan-oc-noi-that-ngan", status: "done" },
  { no: 3002, title: "Tay Vịn Cầu Thang", keyword: "tay vịn cầu thang", slug: "tay-vin-cau-thang-ngan", status: "done" },
  { no: 3003, title: "Chiếu Nghỉ Cầu Thang", keyword: "chiếu nghỉ cầu thang", slug: "chieu-nghi-cau-thang-ngan", status: "done" },
  { no: 3004, title: "Tủ Âm Tường Tối Ưu", keyword: "tủ âm tường tối ưu", slug: "tu-am-tuong-toi-uu-ngan", status: "done" },
  { no: 3005, title: "Kệ Tivi Treo Tường", keyword: "kệ tivi treo tường", slug: "ke-tivi-treo-tuong-ngan", status: "done" },
  { no: 3006, title: "Bàn Làm Việc Góc", keyword: "bàn làm việc góc", slug: "ban-lam-viec-goc-ngan", status: "done" },
  { no: 3007, title: "Giường Tầng Trẻ Em", keyword: "giường tầng trẻ em", slug: "giuong-tang-tre-em-ngan", status: "done" },
  { no: 3008, title: "Bàn Học Cho Bé", keyword: "bàn học cho bé", slug: "ban-hoc-cho-be-ngan", status: "done" },
  { no: 3009, title: "Tủ Giày Thông Minh", keyword: "tủ giày thông minh", slug: "tu-giay-thong-minh-ngan", status: "done" },
  { no: 3010, title: "Tủ Đồ Dưới Cầu Thang", keyword: "tủ đồ dưới cầu thang", slug: "tu-do-duoi-cau-thang-ngan", status: "done" },
  { no: 3011, title: "Màu Sơn Phòng Khách", keyword: "màu sơn phòng khách", slug: "mau-son-phong-khach-ngan", status: "done" },
  { no: 3012, title: "Màu Sơn Phòng Ngủ", keyword: "màu sơn phòng ngủ", slug: "mau-son-phong-ngu-ngan", status: "done" },
  { no: 3013, title: "Màu Sơn Phòng Bếp", keyword: "màu sơn phòng bếp", slug: "mau-son-phong-bep-ngan", status: "done" },
  { no: 3014, title: "Phối Màu Nội Thất", keyword: "phối màu nội thất", slug: "phoi-mau-noi-that-ngan", status: "done" },
  { no: 3015, title: "Ánh Sáng Tự Nhiên Nội Thất", keyword: "ánh sáng tự nhiên nội thất", slug: "anh-sang-tu-nhien-noi-that-ngan", status: "done" },
  { no: 3016, title: "Ánh Sáng Nhân Tạo Nội Thất", keyword: "ánh sáng nhân tạo nội thất", slug: "anh-sang-nhan-tao-noi-that-ngan", status: "done" },
  { no: 3017, title: "Đèn Downlight Âm Trần", keyword: "đèn downlight âm trần", slug: "den-downlight-am-tran-ngan", status: "done" },
  { no: 3018, title: "Đèn Track Light", keyword: "đèn track light", slug: "den-track-light-ngan", status: "done" },
  { no: 3019, title: "Đèn Chùm Phòng Khách", keyword: "đèn chùm phòng khách", slug: "den-chum-phong-khach-ngan", status: "done" },
  { no: 3020, title: "Đèn Tường Trang Trí", keyword: "đèn tường trang trí", slug: "den-tuong-trang-tri-ngan", status: "done" },
  { no: 3021, title: "Nội Thất Gỗ Công Nghiệp", keyword: "nội thất gỗ công nghiệp", slug: "noi-that-go-cong-nghiep-ngan", status: "done" },
  { no: 3022, title: "Nội Thất Gỗ Tự Nhiên", keyword: "nội thất gỗ tự nhiên", slug: "noi-that-go-tu-nhien-ngan", status: "done" },
  { no: 3023, title: "Nội Thất MDF Chống Ẩm", keyword: "nội thất mdf chống ẩm", slug: "noi-that-mdf-chong-am-ngan", status: "done" },
  { no: 3024, title: "Nội Thất Acrylic Bóng Gương", keyword: "nội thất acrylic bóng gương", slug: "noi-that-acrylic-bong-guong-ngan", status: "done" },
  { no: 3025, title: "Báo Giá Nội Thất Trọn Gói", keyword: "báo giá nội thất trọn gói", slug: "bao-gia-noi-that-tron-goi-nt-ngan", status: "done" },
  { no: 3026, title: "Báo Giá Nội Thất Phòng Khách", keyword: "báo giá nội thất phòng khách", slug: "bao-gia-noi-that-phong-khach-ngan", status: "done" },
  { no: 3027, title: "Báo Giá Nội Thất Phòng Ngủ", keyword: "báo giá nội thất phòng ngủ", slug: "bao-gia-noi-that-phong-ngu-ngan", status: "done" },
  { no: 3028, title: "Báo Giá Nội Thất Bếp", keyword: "báo giá nội thất bếp", slug: "bao-gia-noi-that-bep-ngan", status: "done" },
  { no: 3029, title: "Báo Giá Nội Thất WC", keyword: "báo giá nội thất wc", slug: "bao-gia-noi-that-wc-ngan", status: "done" },
  { no: 3030, title: "Thi Công Nội Thất Bao Lâu", keyword: "thi công nội thất bao lâu", slug: "thi-cong-noi-that-bao-lau-ngan", status: "done" },
  { no: 3031, title: "Quy Trình Thi Công Nội Thất", keyword: "quy trình thi công nội thất", slug: "quy-trinh-thi-cong-noi-that-ngan", status: "done" },
  { no: 3032, title: "Nghiệm Thu Nội Thất", keyword: "nghiệm thu nội thất", slug: "nghiem-thu-noi-that-ngan", status: "done" },
  { no: 3033, title: "Bảo Hành Nội Thất", keyword: "bảo hành nội thất", slug: "bao-hanh-noi-that-ngan", status: "done" },
  { no: 3034, title: "Sửa Chữa Nội Thất", keyword: "sửa chữa nội thất", slug: "sua-chua-noi-that-ngan", status: "done" },
  { no: 3035, title: "Làm Mới Nội Thất Cũ", keyword: "làm mới nội thất cũ", slug: "lam-moi-noi-that-cu-ngan", status: "done" },
  { no: 3036, title: "Thay Đổi Layout Nội Thất", keyword: "thay đổi layout nội thất", slug: "thay-doi-layout-noi-that-ngan", status: "done" },
  { no: 3037, title: "Nội Thất Nhà Hẹp", keyword: "nội thất nhà hẹp", slug: "noi-that-nha-hep-ngan", status: "done" },
  { no: 3038, title: "Nội Thất Nhà Nhỏ Dưới 40m2", keyword: "nội thất nhà nhỏ dưới 40m2", slug: "noi-that-nha-nho-duoi-40m2-ngan", status: "done" },
  { no: 3039, title: "Nội Thất Tối Ưu Diện Tích", keyword: "nội thất tối ưu diện tích", slug: "noi-that-toi-uu-dien-tich-ngan", status: "done" },
  { no: 3040, title: "Nội Thất Đa Năng", keyword: "nội thất đa năng", slug: "noi-that-da-nang-ngan", status: "done" },
  { no: 3041, title: "Nội Thất Gấp Gọn", keyword: "nội thất gấp gọn", slug: "noi-that-gap-gon-ngan", status: "done" },
  { no: 3042, title: "Xu Hướng Nội Thất Nhà Phố 2026", keyword: "xu hướng nội thất nhà phố 2026", slug: "xu-huong-noi-that-nha-pho-2026-ngan", status: "done" },
  { no: 3043, title: "Xu Hướng Màu Sơn 2026", keyword: "xu hướng màu sơn 2026", slug: "xu-huong-mau-son-2026-ngan", status: "done" },
  { no: 3044, title: "Xu Hướng Sàn Nhà 2026", keyword: "xu hướng sàn nhà 2026", slug: "xu-huong-san-nha-2026-ngan", status: "done" },
  { no: 3045, title: "Xu Hướng Trần Nhà 2026", keyword: "xu hướng trần nhà 2026", slug: "xu-huong-tran-nha-2026-ngan", status: "done" },
  { no: 3046, title: "Combo Nội Thất Tiết Kiệm", keyword: "combo nội thất tiết kiệm", slug: "combo-noi-that-tiet-kiem-ngan", status: "done" },
];
