/**
 * Lịch 100 từ khóa ngắn — batch 36 (#3047–#3146).
 * Cluster: kỹ thuật thi công, giai đoạn, QC chất lượng.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch36: ContentCalendarItem[] = [
  { no: 3047, title: "Ép Cọc Bê Tông Cốt Thép", keyword: "ép cọc bê tông cốt thép", slug: "ep-coc-be-tong-cot-thep-ngan", status: "done" },
  { no: 3048, title: "Ép Cọc Tre Nhà Phố", keyword: "ép cọc tre nhà phố", slug: "ep-coc-tre-nha-pho-ngan", status: "done" },
  { no: 3049, title: "Khoan Cọc Nhồi Mini", keyword: "khoan cọc nhồi mini", slug: "khoan-coc-nhoi-mini-ngan", status: "done" },
  { no: 3050, title: "Đóng Cọc Bê Tông", keyword: "đóng cọc bê tông", slug: "dong-coc-be-tong-ngan", status: "done" },
  { no: 3051, title: "Đào Móng Nhà Phố", keyword: "đào móng nhà phố", slug: "dao-mong-nha-pho-ngan", status: "done" },
  { no: 3052, title: "Đổ Bê Tông Móng", keyword: "đổ bê tông móng", slug: "do-be-tong-mong-kt-ngan", status: "done" },
  { no: 3053, title: "Đổ Bê Tông Cột", keyword: "đổ bê tông cột", slug: "do-be-tong-cot-kt-ngan", status: "done" },
  { no: 3054, title: "Đổ Bê Tông Dầm", keyword: "đổ bê tông dầm", slug: "do-be-tong-dam-ngan", status: "done" },
  { no: 3055, title: "Đổ Bê Tông Sàn", keyword: "đổ bê tông sàn", slug: "do-be-tong-san-kt-ngan", status: "done" },
  { no: 3056, title: "Đổ Bê Tông Mái", keyword: "đổ bê tông mái", slug: "do-be-tong-mai-ngan", status: "done" },
  { no: 3057, title: "Buộc Thép Cột", keyword: "buộc thép cột", slug: "buoc-thep-cot-ngan", status: "done" },
  { no: 3058, title: "Buộc Thép Dầm", keyword: "buộc thép dầm", slug: "buoc-thep-dam-ngan", status: "done" },
  { no: 3059, title: "Buộc Thép Sàn", keyword: "buộc thép sàn", slug: "buoc-thep-san-ngan", status: "done" },
  { no: 3060, title: "Ghép Ván Khuôn Cột", keyword: "ghép ván khuôn cột", slug: "ghep-van-khuon-cot-ngan", status: "done" },
  { no: 3061, title: "Ghép Ván Khuôn Sàn", keyword: "ghép ván khuôn sàn", slug: "ghep-van-khuon-san-ngan", status: "done" },
  { no: 3062, title: "Tháo Ván Khuôn Bao Lâu", keyword: "tháo ván khuôn bao lâu", slug: "thao-van-khuon-bao-lau-ngan", status: "done" },
  { no: 3063, title: "Bảo Dưỡng Bê Tông", keyword: "bảo dưỡng bê tông", slug: "bao-duong-be-tong-kt-ngan", status: "done" },
  { no: 3064, title: "Xây Tường Gạch", keyword: "xây tường gạch", slug: "xay-tuong-gach-ngan", status: "done" },
  { no: 3065, title: "Xây Tường 100", keyword: "xây tường 100", slug: "xay-tuong-100-ngan", status: "done" },
  { no: 3066, title: "Xây Tường 200", keyword: "xây tường 200", slug: "xay-tuong-200-ngan", status: "done" },
  { no: 3067, title: "Trát Tường Trong", keyword: "trát tường trong", slug: "trat-tuong-trong-ngan", status: "done" },
  { no: 3068, title: "Trát Tường Ngoài", keyword: "trát tường ngoài", slug: "trat-tuong-ngoai-ngan", status: "done" },
  { no: 3069, title: "Cán Nền Sàn", keyword: "cán nền sàn", slug: "can-nen-san-ngan", status: "done" },
  { no: 3070, title: "Cán Nền Chống Dốc", keyword: "cán nền chống dốc", slug: "can-nen-chong-doc-ngan", status: "done" },
  { no: 3071, title: "Chống Thấm Móng", keyword: "chống thấm móng", slug: "chong-tham-mong-kt-ngan", status: "done" },
  { no: 3072, title: "Chống Thấm Sàn Vệ Sinh", keyword: "chống thấm sàn vệ sinh", slug: "chong-tham-san-ve-sinh-ngan", status: "done" },
  { no: 3073, title: "Chống Thấm Sân Thượng Kỹ Thuật", keyword: "chống thấm sân thượng kỹ thuật", slug: "chong-tham-san-thuong-ky-thuat-ngan", status: "done" },
  { no: 3074, title: "Lợp Mái Tôn Kỹ Thuật", keyword: "lợp mái tôn kỹ thuật", slug: "lop-mai-ton-ky-thuat-ngan", status: "done" },
  { no: 3075, title: "Lợp Mái Ngói Kỹ Thuật", keyword: "lợp mái ngói kỹ thuật", slug: "lop-mai-ngoi-ky-thuat-ngan", status: "done" },
  { no: 3076, title: "Lắp Đặt Cửa Nhôm Kỹ Thuật", keyword: "lắp đặt cửa nhôm kỹ thuật", slug: "lap-dat-cua-nhom-ky-thuat-ngan", status: "done" },
  { no: 3077, title: "Lắp Đặt Cửa Gỗ Kỹ Thuật", keyword: "lắp đặt cửa gỗ kỹ thuật", slug: "lap-dat-cua-go-ky-thuat-ngan", status: "done" },
  { no: 3078, title: "Ốp Lát Gạch Kỹ Thuật", keyword: "ốp lát gạch kỹ thuật", slug: "op-lat-gach-ky-thuat-ngan", status: "done" },
  { no: 3079, title: "Ốp Đá Granite Kỹ Thuật", keyword: "ốp đá granite kỹ thuật", slug: "op-da-granite-ky-thuat-ngan", status: "done" },
  { no: 3080, title: "Ốp Đá Marble Kỹ Thuật", keyword: "ốp đá marble kỹ thuật", slug: "op-da-marble-ky-thuat-ngan", status: "done" },
  { no: 3081, title: "Sơn Bả Matit", keyword: "sơn bả matit", slug: "son-ba-matit-ngan", status: "done" },
  { no: 3082, title: "Sơn Lót Nhà", keyword: "sơn lót nhà", slug: "son-lot-nha-kt-ngan", status: "done" },
  { no: 3083, title: "Sơn Phủ Nhà", keyword: "sơn phủ nhà", slug: "son-phu-nha-kt-ngan", status: "done" },
  { no: 3084, title: "Thi Công Trần Thạch Cao Kỹ Thuật", keyword: "thi công trần thạch cao kỹ thuật", slug: "thi-cong-tran-thach-cao-ky-thuat-ngan", status: "done" },
  { no: 3085, title: "Thi Công Hệ Thống Điện Âm", keyword: "thi công hệ thống điện âm", slug: "thi-cong-he-thong-dien-am-ngan", status: "done" },
  { no: 3086, title: "Thi Công Hệ Thống Nước Âm", keyword: "thi công hệ thống nước âm", slug: "thi-cong-he-thong-nuoc-am-ngan", status: "done" },
  { no: 3087, title: "Thi Công Ống Cấp Nước", keyword: "thi công ống cấp nước", slug: "thi-cong-ong-cap-nuoc-ngan", status: "done" },
  { no: 3088, title: "Thi Công Ống Thoát Nước", keyword: "thi công ống thoát nước", slug: "thi-cong-ong-thoat-nuoc-ngan", status: "done" },
  { no: 3089, title: "Thi Công Hộp Kỹ Thuật", keyword: "thi công hộp kỹ thuật", slug: "thi-cong-hop-ky-thuat-ngan", status: "done" },
  { no: 3090, title: "Thi Công Giếng Trời Kỹ Thuật", keyword: "thi công giếng trời kỹ thuật", slug: "thi-cong-gieng-troi-ky-thuat-ngan", status: "done" },
  { no: 3091, title: "Giai Đoạn Phần Móng", keyword: "giai đoạn phần móng", slug: "giai-doan-phan-mong-ngan", status: "done" },
  { no: 3092, title: "Giai Đoạn Phần Thân", keyword: "giai đoạn phần thân", slug: "giai-doan-phan-than-ngan", status: "done" },
  { no: 3093, title: "Giai Đoạn Phần Mái", keyword: "giai đoạn phần mái", slug: "giai-doan-phan-mai-ngan", status: "done" },
  { no: 3094, title: "Giai Đoạn Hoàn Thiện Thô", keyword: "giai đoạn hoàn thiện thô", slug: "giai-doan-hoan-thien-tho-ngan", status: "done" },
  { no: 3095, title: "Giai Đoạn Hoàn Thiện Mịn", keyword: "giai đoạn hoàn thiện mịn", slug: "giai-doan-hoan-thien-min-ngan", status: "done" },
  { no: 3096, title: "Tiến Độ Xây Nhà 2 Tháng", keyword: "tiến độ xây nhà 2 tháng", slug: "tien-do-xay-nha-2-thang-ngan", status: "done" },
  { no: 3097, title: "Tiến Độ Xây Nhà 3 Tháng", keyword: "tiến độ xây nhà 3 tháng", slug: "tien-do-xay-nha-3-thang-ngan", status: "done" },
  { no: 3098, title: "Tiến Độ Xây Nhà 4 Tháng", keyword: "tiến độ xây nhà 4 tháng", slug: "tien-do-xay-nha-4-thang-ngan", status: "done" },
  { no: 3099, title: "Tiến Độ Xây Nhà 6 Tháng", keyword: "tiến độ xây nhà 6 tháng", slug: "tien-do-xay-nha-6-thang-ngan", status: "done" },
  { no: 3100, title: "Tiến Độ Cải Tạo 1 Tháng", keyword: "tiến độ cải tạo 1 tháng", slug: "tien-do-cai-tao-1-thang-ngan", status: "done" },
  { no: 3101, title: "Tiến Độ Cải Tạo 2 Tháng", keyword: "tiến độ cải tạo 2 tháng", slug: "tien-do-cai-tao-2-thang-ngan", status: "done" },
  { no: 3102, title: "Nhật Ký Công Trình", keyword: "nhật ký công trình", slug: "nhat-ky-cong-trinh-kt-ngan", status: "done" },
  { no: 3103, title: "Biên Bản Nghiệm Thu Móng", keyword: "biên bản nghiệm thu móng", slug: "bien-ban-nghiem-thu-mong-ngan", status: "done" },
  { no: 3104, title: "Biên Bản Nghiệm Thu Cột", keyword: "biên bản nghiệm thu cột", slug: "bien-ban-nghiem-thu-cot-ngan", status: "done" },
  { no: 3105, title: "Biên Bản Nghiệm Thu Sàn", keyword: "biên bản nghiệm thu sàn", slug: "bien-ban-nghiem-thu-san-ngan", status: "done" },
  { no: 3106, title: "Biên Bản Nghiệm Thu Điện", keyword: "biên bản nghiệm thu điện", slug: "bien-ban-nghiem-thu-dien-ngan", status: "done" },
  { no: 3107, title: "Biên Bản Nghiệm Thu Nước", keyword: "biên bản nghiệm thu nước", slug: "bien-ban-nghiem-thu-nuoc-ngan", status: "done" },
  { no: 3108, title: "Kiểm Tra Thép Trước Đổ", keyword: "kiểm tra thép trước đổ", slug: "kiem-tra-thep-truoc-do-ngan", status: "done" },
  { no: 3109, title: "Kiểm Tra Ván Khuôn", keyword: "kiểm tra ván khuôn", slug: "kiem-tra-van-khuon-ngan", status: "done" },
  { no: 3110, title: "Kiểm Tra Độ Sụt Bê Tông", keyword: "kiểm tra độ sụt bê tông", slug: "kiem-tra-do-sut-be-tong-ngan", status: "done" },
  { no: 3111, title: "Lấy Mẫu Bê Tông", keyword: "lấy mẫu bê tông", slug: "lay-mau-be-tong-ngan", status: "done" },
  { no: 3112, title: "Thử Áp Hệ Nước", keyword: "thử áp hệ nước", slug: "thu-ap-he-nuoc-ngan", status: "done" },
  { no: 3113, title: "Thử Tải Hệ Điện", keyword: "thử tải hệ điện", slug: "thu-tai-he-dien-ngan", status: "done" },
  { no: 3114, title: "Ngâm Nước Chống Thấm", keyword: "ngâm nước chống thấm", slug: "ngam-nuoc-chong-tham-ngan", status: "done" },
  { no: 3115, title: "QC Chất Lượng Hồ Vữa", keyword: "qc chất lượng hồ vữa", slug: "qc-chat-luong-ho-vua-ngan", status: "done" },
  { no: 3116, title: "QC Chất Lượng Gạch", keyword: "qc chất lượng gạch", slug: "qc-chat-luong-gach-ngan", status: "done" },
  { no: 3117, title: "QC Độ Thẳng Tường", keyword: "qc độ thẳng tường", slug: "qc-do-thang-tuong-ngan", status: "done" },
  { no: 3118, title: "QC Độ Phẳng Sàn", keyword: "qc độ phẳng sàn", slug: "qc-do-phang-san-ngan", status: "done" },
  { no: 3119, title: "QC Ron Gạch", keyword: "qc ron gạch", slug: "qc-ron-gach-ngan", status: "done" },
  { no: 3120, title: "QC Lớp Sơn", keyword: "qc lớp sơn", slug: "qc-lop-son-ngan", status: "done" },
  { no: 3121, title: "An Toàn Lao Động Công Trường", keyword: "an toàn lao động công trường", slug: "an-toan-lao-dong-cong-truong-ngan", status: "done" },
  { no: 3122, title: "Giàn Giáo An Toàn", keyword: "giàn giáo an toàn", slug: "gian-giao-an-toan-ngan", status: "done" },
  { no: 3123, title: "Rào Chắn Công Trường", keyword: "rào chắn công trường", slug: "rao-chan-cong-truong-ngan", status: "done" },
  { no: 3124, title: "Che Chắn Bụi Công Trường", keyword: "che chắn bụi công trường", slug: "che-chan-bui-cong-truong-ngan", status: "done" },
  { no: 3125, title: "Xử Lý Phế Thải Xây Dựng", keyword: "xử lý phế thải xây dựng", slug: "xu-ly-phe-thai-xay-dung-ngan", status: "done" },
  { no: 3126, title: "Tạm Dừng Thi Công Khi Mưa", keyword: "tạm dừng thi công khi mưa", slug: "tam-dung-thi-cong-khi-mua-ngan", status: "done" },
  { no: 3127, title: "Thi Công Mùa Mưa", keyword: "thi công mùa mưa", slug: "thi-cong-mua-mua-ngan", status: "done" },
  { no: 3128, title: "Thi Công Mùa Nắng", keyword: "thi công mùa nắng", slug: "thi-cong-mua-nang-ngan", status: "done" },
  { no: 3129, title: "Ca Đêm Thi Công", keyword: "ca đêm thi công", slug: "ca-dem-thi-cong-ngan", status: "done" },
  { no: 3130, title: "Đổ Bê Tông Ban Đêm", keyword: "đổ bê tông ban đêm", slug: "do-be-tong-ban-dem-ngan", status: "done" },
  { no: 3131, title: "Máy Trộn Bê Tông Tại Chỗ", keyword: "máy trộn bê tông tại chỗ", slug: "may-tron-be-tong-tai-cho-ngan", status: "done" },
  { no: 3132, title: "Bê Tông Tươi Xe Bơm", keyword: "bê tông tươi xe bơm", slug: "be-tong-tuoi-xe-bom-ngan", status: "done" },
  { no: 3133, title: "Cần Cẩu Mini Nhà Phố", keyword: "cần cẩu mini nhà phố", slug: "can-cau-mini-nha-pho-ngan", status: "done" },
  { no: 3134, title: "Vận Thăng Công Trình", keyword: "vận thăng công trình", slug: "van-thang-cong-trinh-ngan", status: "done" },
  { no: 3135, title: "Máy Cắt Sắt Công Trình", keyword: "máy cắt sắt công trình", slug: "may-cat-sat-cong-trinh-ngan", status: "done" },
  { no: 3136, title: "Máy Đầm Dùi Bê Tông", keyword: "máy đầm dùi bê tông", slug: "may-dam-dui-be-tong-ngan", status: "done" },
  { no: 3137, title: "Sai Số Cho Phép Thi Công", keyword: "sai số cho phép thi công", slug: "sai-so-cho-phep-thi-cong-ngan", status: "done" },
  { no: 3138, title: "Sửa Lỗi Thi Công Bê Tông", keyword: "sửa lỗi thi công bê tông", slug: "sua-loi-thi-cong-be-tong-ngan", status: "done" },
  { no: 3139, title: "Sửa Lỗi Thi Công Tường", keyword: "sửa lỗi thi công tường", slug: "sua-loi-thi-cong-tuong-ngan", status: "done" },
  { no: 3140, title: "Sửa Lỗi Thi Công Ốp Lát", keyword: "sửa lỗi thi công ốp lát", slug: "sua-loi-thi-cong-op-lat-ngan", status: "done" },
  { no: 3141, title: "Sửa Lỗi Thi Công Sơn", keyword: "sửa lỗi thi công sơn", slug: "sua-loi-thi-cong-son-ngan", status: "done" },
  { no: 3142, title: "Checklist QC Hàng Ngày", keyword: "checklist qc hàng ngày", slug: "checklist-qc-hang-ngay-ngan", status: "done" },
  { no: 3143, title: "Checklist QC Theo Giai Đoạn", keyword: "checklist qc theo giai đoạn", slug: "checklist-qc-theo-giai-doan-ngan", status: "done" },
  { no: 3144, title: "Chủ Đề Mở Rộng 36 1", keyword: "chủ đề mở rộng 36 1", slug: "chu-de-mo-rong-36-1-ngan", status: "done" },
  { no: 3145, title: "Chủ Đề Mở Rộng 36 2", keyword: "chủ đề mở rộng 36 2", slug: "chu-de-mo-rong-36-2-ngan", status: "done" },
  { no: 3146, title: "Chủ Đề Mở Rộng 36 3", keyword: "chủ đề mở rộng 36 3", slug: "chu-de-mo-rong-36-3-ngan", status: "done" },
];
