/**
 * Lịch 100 từ khóa ngắn — batch 31 (#2547–#2646).
 * Cluster: nhà xanh, smart home, khí hậu, tiết kiệm năng lượng.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch31: ContentCalendarItem[] = [
  { no: 2547, title: "Nhà Xanh Tiết Kiệm Điện", keyword: "nhà xanh tiết kiệm điện", slug: "nha-xanh-tiet-kiem-dien-ngan", status: "done" },
  { no: 2548, title: "Nhà Thông Minh Cơ Bản", keyword: "nhà thông minh cơ bản", slug: "nha-thong-minh-co-ban-ngan", status: "done" },
  { no: 2549, title: "Nhà Thông Minh Cao Cấp", keyword: "nhà thông minh cao cấp", slug: "nha-thong-minh-cao-cap-ngan", status: "done" },
  { no: 2550, title: "Lắp Đặt Smart Home", keyword: "lắp đặt smart home", slug: "lap-dat-smart-home-ngan", status: "done" },
  { no: 2551, title: "Công Tắc Cảm Ứng Nhà", keyword: "công tắc cảm ứng nhà", slug: "cong-tac-cam-ung-nha-ngan", status: "done" },
  { no: 2552, title: "Đèn LED Thông Minh", keyword: "đèn led thông minh", slug: "den-led-thong-minh-ngan", status: "done" },
  { no: 2553, title: "Camera An Ninh Nhà Phố", keyword: "camera an ninh nhà phố", slug: "camera-an-ninh-nha-pho-ngan", status: "done" },
  { no: 2554, title: "Khóa Cửa Vân Tay", keyword: "khóa cửa vân tay", slug: "khoa-cua-van-tay-ngan", status: "done" },
  { no: 2555, title: "Khóa Cửa Thông Minh", keyword: "khóa cửa thông minh", slug: "khoa-cua-thong-minh-ngan", status: "done" },
  { no: 2556, title: "Chuông Cửa Có Camera", keyword: "chuông cửa có camera", slug: "chuong-cua-co-camera-ngan", status: "done" },
  { no: 2557, title: "Hệ Thống Báo Cháy Nhà", keyword: "hệ thống báo cháy nhà", slug: "he-thong-bao-chay-nha-ngan", status: "done" },
  { no: 2558, title: "Báo Động Chống Trộm Nhà", keyword: "báo động chống trộm nhà", slug: "bao-dong-chong-trom-nha-ngan", status: "done" },
  { no: 2559, title: "Pin Năng Lượng Mặt Trời Nhà", keyword: "pin năng lượng mặt trời nhà", slug: "pin-nang-luong-mat-troi-nha-ngan", status: "done" },
  { no: 2560, title: "Điện Mặt Trời Áp Mái", keyword: "điện mặt trời áp mái", slug: "dien-mat-troi-ap-mai-ngan", status: "done" },
  { no: 2561, title: "Máy Nước Nóng Năng Lượng Mặt Trời", keyword: "máy nước nóng năng lượng mặt trời", slug: "may-nuoc-nong-nlmt-ngan", status: "done" },
  { no: 2562, title: "Thu Gom Nước Mưa Nhà", keyword: "thu gom nước mưa nhà", slug: "thu-gom-nuoc-mua-nha-ngan", status: "done" },
  { no: 2563, title: "Xử Lý Nước Thải Gia Đình", keyword: "xử lý nước thải gia đình", slug: "xu-ly-nuoc-thai-gia-dinh-ngan", status: "done" },
  { no: 2564, title: "Bể Phốt Không Mùi", keyword: "bể phốt không mùi", slug: "be-phot-khong-mui-ngan", status: "done" },
  { no: 2565, title: "Nhà Chống Nóng TPHCM", keyword: "nhà chống nóng tphcm", slug: "nha-chong-nong-tphcm-ngan", status: "done" },
  { no: 2566, title: "Nhà Chống Ẩm TPHCM", keyword: "nhà chống ẩm tphcm", slug: "nha-chong-am-tphcm-ngan", status: "done" },
  { no: 2567, title: "Nhà Chống Ồn Đường Phố", keyword: "nhà chống ồn đường phố", slug: "nha-chong-on-duong-pho-ngan", status: "done" },
  { no: 2568, title: "Nhà Thông Gió Tự Nhiên", keyword: "nhà thông gió tự nhiên", slug: "nha-thong-gio-tu-nhien-ngan", status: "done" },
  { no: 2569, title: "Giếng Trời Thông Gió", keyword: "giếng trời thông gió", slug: "gieng-troi-thong-gio-ngan", status: "done" },
  { no: 2570, title: "Giếng Trời Lấy Sáng", keyword: "giếng trời lấy sáng", slug: "gieng-troi-lay-sang-ngan", status: "done" },
  { no: 2571, title: "Cửa Sổ Trời Nhà Phố", keyword: "cửa sổ trời nhà phố", slug: "cua-so-troi-nha-pho-ngan", status: "done" },
  { no: 2572, title: "Mái Kính Lấy Sáng", keyword: "mái kính lấy sáng", slug: "mai-kinh-lay-sang-ngan", status: "done" },
  { no: 2573, title: "Mái Che Poly Nhà", keyword: "mái che poly nhà", slug: "mai-che-poly-nha-ngan", status: "done" },
  { no: 2574, title: "Mái Che Sân Thượng", keyword: "mái che sân thượng", slug: "mai-che-san-thuong-ngan", status: "done" },
  { no: 2575, title: "Cách Nhiệt Tường Nhà", keyword: "cách nhiệt tường nhà", slug: "cach-nhiet-tuong-nha-ngan", status: "done" },
  { no: 2576, title: "Cách Nhiệt Trần Nhà", keyword: "cách nhiệt trần nhà", slug: "cach-nhiet-tran-nha-ngan", status: "done" },
  { no: 2577, title: "Sơn Chống Nóng Tường", keyword: "sơn chống nóng tường", slug: "son-chong-nong-tuong-ngan", status: "done" },
  { no: 2578, title: "Sơn Chống Thấm Ngoài Trời", keyword: "sơn chống thấm ngoài trời", slug: "son-chong-tham-ngoai-troi-ngan", status: "done" },
  { no: 2579, title: "Vật Liệu Xanh Xây Nhà", keyword: "vật liệu xanh xây nhà", slug: "vat-lieu-xanh-xay-nha-ngan", status: "done" },
  { no: 2580, title: "Gạch Không Nung Xây Nhà", keyword: "gạch không nung xây nhà", slug: "gach-khong-nung-xay-nha-ngan", status: "done" },
  { no: 2581, title: "Gỗ Nhựa Ngoài Trời", keyword: "gỗ nhựa ngoài trời", slug: "go-nhua-ngoai-troi-eco-ngan", status: "done" },
  { no: 2582, title: "Sàn Tre Công Nghiệp", keyword: "sàn tre công nghiệp", slug: "san-tre-cong-nghiep-ngan", status: "done" },
  { no: 2583, title: "Sơn Sinh Thái Nhà", keyword: "sơn sinh thái nhà", slug: "son-sinh-thai-nha-ngan", status: "done" },
  { no: 2584, title: "Keo Chống Thấm Xanh", keyword: "keo chống thấm xanh", slug: "keo-chong-tham-xanh-ngan", status: "done" },
  { no: 2585, title: "Nhà Passive House Cơ Bản", keyword: "nhà passive house cơ bản", slug: "nha-passive-house-co-ban-ngan", status: "done" },
  { no: 2586, title: "Thiết Kế Bioclimatic", keyword: "thiết kế bioclimatic", slug: "thiet-ke-bioclimatic-ngan", status: "done" },
  { no: 2587, title: "Hướng Nhà Tốt TPHCM", keyword: "hướng nhà tốt tphcm", slug: "huong-nha-tot-tphcm-ngan", status: "done" },
  { no: 2588, title: "Nhà Hướng Đông Nam", keyword: "nhà hướng đông nam", slug: "nha-huong-dong-nam-ngan", status: "done" },
  { no: 2589, title: "Nhà Hướng Tây Nắng", keyword: "nhà hướng tây nắng", slug: "nha-huong-tay-nang-ngan", status: "done" },
  { no: 2590, title: "Che Nắng Mặt Tiền Tây", keyword: "che nắng mặt tiền tây", slug: "che-nang-mat-tien-tay-ngan", status: "done" },
  { no: 2591, title: "Lam Chắn Nắng Nhà Phố", keyword: "lam chắn nắng nhà phố", slug: "lam-chan-nang-nha-pho-ngan", status: "done" },
  { no: 2592, title: "Ban Công Xanh Nhà Phố", keyword: "ban công xanh nhà phố", slug: "ban-cong-xanh-nha-pho-ngan", status: "done" },
  { no: 2593, title: "Vườn Đứng Nhà Phố", keyword: "vườn đứng nhà phố", slug: "vuon-dung-nha-pho-ngan", status: "done" },
  { no: 2594, title: "Sân Thượng Xanh", keyword: "sân thượng xanh", slug: "san-thuong-xanh-eco-ngan", status: "done" },
  { no: 2595, title: "Trồng Cây Sân Thượng", keyword: "trồng cây sân thượng", slug: "trong-cay-san-thuong-eco-ngan", status: "done" },
  { no: 2596, title: "Hồ Cá Koi Nhà Phố", keyword: "hồ cá koi nhà phố", slug: "ho-ca-koi-nha-pho-ngan", status: "done" },
  { no: 2597, title: "Tiểu Cảnh Sân Trước", keyword: "tiểu cảnh sân trước", slug: "tieu-canh-san-truoc-ngan", status: "done" },
  { no: 2598, title: "Tiểu Cảnh Giếng Trời", keyword: "tiểu cảnh giếng trời", slug: "tieu-canh-gieng-troi-ngan", status: "done" },
  { no: 2599, title: "Máy Lạnh Inverter Tiết Kiệm", keyword: "máy lạnh inverter tiết kiệm", slug: "may-lanh-inverter-tiet-kiem-ngan", status: "done" },
  { no: 2600, title: "VRV Multi Nhà Phố", keyword: "vrv multi nhà phố", slug: "vrv-multi-nha-pho-ngan", status: "done" },
  { no: 2601, title: "Quạt Trần Thông Minh", keyword: "quạt trần thông minh", slug: "quat-tran-thong-minh-ngan", status: "done" },
  { no: 2602, title: "Máy Lọc Không Khí Nhà", keyword: "máy lọc không khí nhà", slug: "may-loc-khong-khi-nha-ngan", status: "done" },
  { no: 2603, title: "Hút Mùi Bếp Công Nghiệp Mini", keyword: "hút mùi bếp công nghiệp mini", slug: "hut-mui-bep-cong-nghiep-mini-ngan", status: "done" },
  { no: 2604, title: "Thông Gió Nhà Bếp", keyword: "thông gió nhà bếp", slug: "thong-gio-nha-bep-ngan", status: "done" },
  { no: 2605, title: "Thông Gió WC", keyword: "thông gió wc", slug: "thong-gio-wc-ngan", status: "done" },
  { no: 2606, title: "Chống Ẩm Tầng Hầm", keyword: "chống ẩm tầng hầm", slug: "chong-am-tang-ham-ngan", status: "done" },
  { no: 2607, title: "Chống Ngập Nhà Phố", keyword: "chống ngập nhà phố", slug: "chong-ngap-nha-pho-ngan", status: "done" },
  { no: 2608, title: "Nâng Cốt Nền Chống Ngập", keyword: "nâng cốt nền chống ngập", slug: "nang-cot-nen-chong-ngap-ngan", status: "done" },
  { no: 2609, title: "Rãnh Thoát Nước Mặt Tiền", keyword: "rãnh thoát nước mặt tiền", slug: "ranh-thoat-nuoc-mat-tien-ngan", status: "done" },
  { no: 2610, title: "Bơm Chống Ngập Gia Đình", keyword: "bơm chống ngập gia đình", slug: "bom-chong-ngap-gia-dinh-ngan", status: "done" },
  { no: 2611, title: "Nhà Chống Bão Cơ Bản", keyword: "nhà chống bão cơ bản", slug: "nha-chong-bao-co-ban-ngan", status: "done" },
  { no: 2612, title: "Gia Cố Mái Chống Bão", keyword: "gia cố mái chống bão", slug: "gia-co-mai-chong-bao-ngan", status: "done" },
  { no: 2613, title: "Cửa Chống Bão Nhà Phố", keyword: "cửa chống bão nhà phố", slug: "cua-chong-bao-nha-pho-ngan", status: "done" },
  { no: 2614, title: "Kính An Toàn Nhà Phố", keyword: "kính an toàn nhà phố", slug: "kinh-an-toan-nha-pho-ngan", status: "done" },
  { no: 2615, title: "Kính Cách Nhiệt Low-E", keyword: "kính cách nhiệt low-e", slug: "kinh-cach-nhiet-low-e-ngan", status: "done" },
  { no: 2616, title: "Kính Cách Âm Nhà Phố", keyword: "kính cách âm nhà phố", slug: "kinh-cach-am-nha-pho-ngan", status: "done" },
  { no: 2617, title: "Vách Kính Cách Âm", keyword: "vách kính cách âm", slug: "vach-kinh-cach-am-ngan", status: "done" },
  { no: 2618, title: "Cửa Cách Âm Phòng Ngủ", keyword: "cửa cách âm phòng ngủ", slug: "cua-cach-am-phong-ngu-ngan", status: "done" },
  { no: 2619, title: "Vách Ngăn Cách Âm", keyword: "vách ngăn cách âm", slug: "vach-ngan-cach-am-ngan", status: "done" },
  { no: 2620, title: "Trần Cách Âm Phòng Karaoke", keyword: "trần cách âm phòng karaoke", slug: "tran-cach-am-phong-karaoke-ngan", status: "done" },
  { no: 2621, title: "Phòng Karaoke Tại Gia", keyword: "phòng karaoke tại gia", slug: "phong-karaoke-tai-gia-ngan", status: "done" },
  { no: 2622, title: "Phòng Gym Tại Gia", keyword: "phòng gym tại gia", slug: "phong-gym-tai-gia-ngan", status: "done" },
  { no: 2623, title: "Phòng Làm Việc Tại Gia", keyword: "phòng làm việc tại gia", slug: "phong-lam-viec-tai-gia-ngan", status: "done" },
  { no: 2624, title: "Góc Học Tập Trẻ Em", keyword: "góc học tập trẻ em", slug: "goc-hoc-tap-tre-em-ngan", status: "done" },
  { no: 2625, title: "Phòng Chơi Trẻ Em", keyword: "phòng chơi trẻ em", slug: "phong-choi-tre-em-ngan", status: "done" },
  { no: 2626, title: "Phòng Ngủ Ông Bà", keyword: "phòng ngủ ông bà", slug: "phong-ngu-ong-ba-ngan", status: "done" },
  { no: 2627, title: "Thiết Kế Nhà Đa Thế Hệ", keyword: "thiết kế nhà đa thế hệ", slug: "thiet-ke-nha-da-the-he-ngan", status: "done" },
  { no: 2628, title: "Nhà Cho Người Cao Tuổi", keyword: "nhà cho người cao tuổi", slug: "nha-cho-nguoi-cao-tuoi-ngan", status: "done" },
  { no: 2629, title: "Nhà Không Rào Cản", keyword: "nhà không rào cản", slug: "nha-khong-rao-can-ngan", status: "done" },
  { no: 2630, title: "Thang Máy Mini Nhà Phố", keyword: "thang máy mini nhà phố", slug: "thang-may-mini-nha-pho-ngan", status: "done" },
  { no: 2631, title: "Thang Máy Gia Đình Giá", keyword: "thang máy gia đình giá", slug: "thang-may-gia-dinh-gia-ngan", status: "done" },
  { no: 2632, title: "Dự Trữ Không Gian Thang Máy", keyword: "dự trữ không gian thang máy", slug: "du-tru-khong-gian-thang-may-ngan", status: "done" },
  { no: 2633, title: "Nhà Sẵn Sàng Thang Máy", keyword: "nhà sẵn sàng thang máy", slug: "nha-san-sang-thang-may-ngan", status: "done" },
  { no: 2634, title: "Thiết Kế Nhà Linh Hoạt", keyword: "thiết kế nhà linh hoạt", slug: "thiet-ke-nha-linh-hoat-ngan", status: "done" },
  { no: 2635, title: "Nhà Module Lắp Ghép", keyword: "nhà module lắp ghép", slug: "nha-module-lap-ghep-ngan", status: "done" },
  { no: 2636, title: "Nhà Prefab Hiện Đại", keyword: "nhà prefab hiện đại", slug: "nha-prefab-hien-dai-ngan", status: "done" },
  { no: 2637, title: "Nhà Container Cải Tạo", keyword: "nhà container cải tạo", slug: "nha-container-cai-tao-ngan", status: "done" },
  { no: 2638, title: "Nhà Lắp Sẵn 1 Tầng", keyword: "nhà lắp sẵn 1 tầng", slug: "nha-lap-san-1-tang-ngan", status: "done" },
  { no: 2639, title: "Nhà Lắp Sẵn 2 Tầng", keyword: "nhà lắp sẵn 2 tầng", slug: "nha-lap-san-2-tang-ngan", status: "done" },
  { no: 2640, title: "Xu Hướng Nhà Xanh 2026", keyword: "xu hướng nhà xanh 2026", slug: "xu-huong-nha-xanh-2026-ngan", status: "done" },
  { no: 2641, title: "Xu Hướng Smart Home 2026", keyword: "xu hướng smart home 2026", slug: "xu-huong-smart-home-2026-ngan", status: "done" },
  { no: 2642, title: "Chứng Chỉ Công Trình Xanh", keyword: "chứng chỉ công trình xanh", slug: "chung-chi-cong-trinh-xanh-ngan", status: "done" },
  { no: 2643, title: "Nhà Đạt Chuẩn EDGE", keyword: "nhà đạt chuẩn edge", slug: "nha-dat-chuan-edge-ngan", status: "done" },
  { no: 2644, title: "Chủ Đề Mở Rộng 31 1", keyword: "chủ đề mở rộng 31 1", slug: "chu-de-mo-rong-31-1-ngan", status: "done" },
  { no: 2645, title: "Chủ Đề Mở Rộng 31 2", keyword: "chủ đề mở rộng 31 2", slug: "chu-de-mo-rong-31-2-ngan", status: "done" },
  { no: 2646, title: "Chủ Đề Mở Rộng 31 3", keyword: "chủ đề mở rộng 31 3", slug: "chu-de-mo-rong-31-3-ngan", status: "done" },
];
