/**
 * Lịch 100 từ khóa ngắn — batch 56 (#5047–#5146).
 * Cluster: chống thấm, mái, thoát nước chuyên sâu.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch56: ContentCalendarItem[] = [
  { no: 5047, title: "Chống Thấm Sân Thượng CT", keyword: "chống thấm sân thượng", slug: "chong-tham-san-thuong-ct-ngan", status: "done" },
  { no: 5048, title: "Chống Thấm Mái BTCT CT", keyword: "chống thấm mái btct", slug: "chong-tham-mai-btct-ct-ngan", status: "done" },
  { no: 5049, title: "Chống Thấm Mái Tôn CT", keyword: "chống thấm mái tôn", slug: "chong-tham-mai-ton-ct-ngan", status: "done" },
  { no: 5050, title: "Chống Thấm Mái Ngói CT", keyword: "chống thấm mái ngói", slug: "chong-tham-mai-ngoi-ct-ngan", status: "done" },
  { no: 5051, title: "Chống Thấm Tường Ngoài CT", keyword: "chống thấm tường ngoài", slug: "chong-tham-tuong-ngoai-ct-ngan", status: "done" },
  { no: 5052, title: "Chống Thấm Tường Trong CT", keyword: "chống thấm tường trong", slug: "chong-tham-tuong-trong-ct-ngan", status: "done" },
  { no: 5053, title: "Chống Thấm Sàn WC CT", keyword: "chống thấm sàn wc", slug: "chong-tham-san-wc-ct-ngan", status: "done" },
  { no: 5054, title: "Chống Thấm Sàn Bếp CT", keyword: "chống thấm sàn bếp", slug: "chong-tham-san-bep-ct-ngan", status: "done" },
  { no: 5055, title: "Chống Thấm Ban Công CT", keyword: "chống thấm ban công", slug: "chong-tham-ban-cong-ct-ngan", status: "done" },
  { no: 5056, title: "Chống Thấm Logia CT", keyword: "chống thấm logia", slug: "chong-tham-logia-ct-ngan", status: "done" },
  { no: 5057, title: "Chống Thấm Hầm Xe CT", keyword: "chống thấm hầm xe", slug: "chong-tham-ham-xe-ct-ngan", status: "done" },
  { no: 5058, title: "Chống Thấm Bể Nước CT", keyword: "chống thấm bể nước", slug: "chong-tham-be-nuoc-ct-ngan", status: "done" },
  { no: 5059, title: "Chống Thấm Bể Bơi CT", keyword: "chống thấm bể bơi", slug: "chong-tham-be-boi-ct-ngan", status: "done" },
  { no: 5060, title: "Chống Thấm Cổ Ống CT", keyword: "chống thấm cổ ống", slug: "chong-tham-co-ong-ct-ngan", status: "done" },
  { no: 5061, title: "Chống Thấm Mạch Ngừng CT", keyword: "chống thấm mạch ngừng", slug: "chong-tham-mach-ngung-ct-ngan", status: "done" },
  { no: 5062, title: "Chống Thấm Khe Co Giãn CT", keyword: "chống thấm khe co giãn", slug: "chong-tham-khe-co-gian-ct-ngan", status: "done" },
  { no: 5063, title: "Chống Thấm Gốc Xi Măng CT", keyword: "chống thấm gốc xi măng", slug: "chong-tham-goc-xi-mang-ct-ngan", status: "done" },
  { no: 5064, title: "Chống Thấm Gốc Bitum CT", keyword: "chống thấm gốc bitum", slug: "chong-tham-goc-bitum-ct-ngan", status: "done" },
  { no: 5065, title: "Chống Thấm Gốc Polyurethane", keyword: "chống thấm gốc polyurethane", slug: "chong-tham-goc-pu-ct-ngan", status: "done" },
  { no: 5066, title: "Chống Thấm Gốc Acrylic CT", keyword: "chống thấm gốc acrylic", slug: "chong-tham-goc-acrylic-ct-ngan", status: "done" },
  { no: 5067, title: "Màng Khò Nóng CT", keyword: "màng khò nóng chống thấm", slug: "mang-kho-nong-ct-ngan", status: "done" },
  { no: 5068, title: "Màng Tự Dính CT", keyword: "màng tự dính chống thấm", slug: "mang-tu-dinh-ct-ngan", status: "done" },
  { no: 5069, title: "Vải Không Dệt Chống Thấm", keyword: "vải không dệt chống thấm", slug: "vai-khong-det-chong-tham-ct-ngan", status: "done" },
  { no: 5070, title: "Sơn Chống Thấm Đàn Hồi", keyword: "sơn chống thấm đàn hồi", slug: "son-chong-tham-dan-hoi-ct-ngan", status: "done" },
  { no: 5071, title: "Keo Bơm Vết Nứt CT", keyword: "keo bơm vết nứt", slug: "keo-bom-vet-nut-ct-ngan", status: "done" },
  { no: 5072, title: "Xử Lý Thấm Trần Nhà", keyword: "xử lý thấm trần nhà", slug: "xu-ly-tham-tran-nha-ct-ngan", status: "done" },
  { no: 5073, title: "Xử Lý Thấm Tường Mưa", keyword: "xử lý thấm tường mưa", slug: "xu-ly-tham-tuong-mua-ct-ngan", status: "done" },
  { no: 5074, title: "Xử Lý Thấm Sàn WC CT", keyword: "xử lý thấm sàn wc", slug: "xu-ly-tham-san-wc-ct-ngan", status: "done" },
  { no: 5075, title: "Xử Lý Thấm Cổ Ống CT", keyword: "xử lý thấm cổ ống", slug: "xu-ly-tham-co-ong-ct-ngan", status: "done" },
  { no: 5076, title: "Xử Lý Thấm Mái Tôn CT", keyword: "xử lý thấm mái tôn", slug: "xu-ly-tham-mai-ton-ct-ngan", status: "done" },
  { no: 5077, title: "Ngâm Nước Nghiệm Thu CT", keyword: "ngâm nước nghiệm thu chống thấm", slug: "ngam-nuoc-nghiem-thu-ct-ngan", status: "done" },
  { no: 5078, title: "Thời Gian Ngâm Nước CT", keyword: "thời gian ngâm nước chống thấm", slug: "thoi-gian-ngam-nuoc-ct-ngan", status: "done" },
  { no: 5079, title: "Quy Trình Chống Thấm CT", keyword: "quy trình chống thấm", slug: "quy-trinh-chong-tham-ct-ngan", status: "done" },
  { no: 5080, title: "Chuẩn Bị Bề Mặt Chống Thấm", keyword: "chuẩn bị bề mặt chống thấm", slug: "chuan-bi-be-mat-chong-tham-ct-ngan", status: "done" },
  { no: 5081, title: "Số Lớp Chống Thấm Đạt", keyword: "số lớp chống thấm đạt", slug: "so-lop-chong-tham-dat-ct-ngan", status: "done" },
  { no: 5082, title: "Bảo Dưỡng Sau Chống Thấm", keyword: "bảo dưỡng sau chống thấm", slug: "bao-duong-sau-chong-tham-ct-ngan", status: "done" },
  { no: 5083, title: "Thoát Nước Sân Thượng CT", keyword: "thoát nước sân thượng", slug: "thoat-nuoc-san-thuong-ct-ngan", status: "done" },
  { no: 5084, title: "Thoát Nước Mái Tôn CT", keyword: "thoát nước mái tôn", slug: "thoat-nuoc-mai-ton-ct-ngan", status: "done" },
  { no: 5085, title: "Thoát Nước Ban Công CT", keyword: "thoát nước ban công", slug: "thoat-nuoc-ban-cong-ct-ngan", status: "done" },
  { no: 5086, title: "Thoát Nước Mặt Tiền CT", keyword: "thoát nước mặt tiền", slug: "thoat-nuoc-mat-tien-ct-ngan", status: "done" },
  { no: 5087, title: "Ống Xuống Nước Mưa CT", keyword: "ống xuống nước mưa", slug: "ong-xuong-nuoc-mua-ct-ngan", status: "done" },
  { no: 5088, title: "Phễu Thu Nước Mái CT", keyword: "phễu thu nước mái", slug: "pheu-thu-nuoc-mai-ct-ngan", status: "done" },
  { no: 5089, title: "Rãnh Thoát Nước Sân CT", keyword: "rãnh thoát nước sân", slug: "ranh-thoat-nuoc-san-ct-ngan", status: "done" },
  { no: 5090, title: "Độ Dốc Thoát Nước CT", keyword: "độ dốc thoát nước", slug: "do-doc-thoat-nuoc-ct-ngan", status: "done" },
  { no: 5091, title: "Chống Ùn Tắc Thoát Nước", keyword: "chống ùn tắc thoát nước", slug: "chong-un-tac-thoat-nuoc-ct-ngan", status: "done" },
  { no: 5092, title: "Lọc Rác Phễu Thu CT", keyword: "lọc rác phễu thu", slug: "loc-rac-pheu-thu-ct-ngan", status: "done" },
  { no: 5093, title: "Cách Nhiệt Mái Tôn CT", keyword: "cách nhiệt mái tôn", slug: "cach-nhiet-mai-ton-ct-ngan", status: "done" },
  { no: 5094, title: "Cách Nhiệt Mái BTCT CT", keyword: "cách nhiệt mái btct", slug: "cach-nhiet-mai-btct-ct-ngan", status: "done" },
  { no: 5095, title: "Tấm Cách Nhiệt Mái CT", keyword: "tấm cách nhiệt mái", slug: "tam-cach-nhiet-mai-ct-ngan", status: "done" },
  { no: 5096, title: "Sơn Chống Nóng Mái CT", keyword: "sơn chống nóng mái", slug: "son-chong-nong-mai-ct-ngan", status: "done" },
  { no: 5097, title: "Trần Giả Cách Nhiệt CT", keyword: "trần giả cách nhiệt", slug: "tran-gia-cach-nhiet-ct-ngan", status: "done" },
  { no: 5098, title: "Lợp Mái Tôn 2 Lớp CT", keyword: "lợp mái tôn 2 lớp", slug: "lop-mai-ton-2-lop-ct-ngan", status: "done" },
  { no: 5099, title: "Lợp Mái Tôn 3 Lớp CT", keyword: "lợp mái tôn 3 lớp", slug: "lop-mai-ton-3-lop-ct-ngan", status: "done" },
  { no: 5100, title: "Xà Gồ Mái Tôn CT", keyword: "xà gồ mái tôn", slug: "xa-go-mai-ton-ct-ngan", status: "done" },
  { no: 5101, title: "Kèo Thép Mái Tôn CT", keyword: "kèo thép mái tôn", slug: "keo-thep-mai-ton-ct-ngan", status: "done" },
  { no: 5102, title: "Diềm Mái Tôn CT", keyword: "diềm mái tôn", slug: "diem-mai-ton-ct-ngan", status: "done" },
  { no: 5103, title: "Úp Nóc Mái Tôn CT", keyword: "úp nóc mái tôn", slug: "up-noc-mai-ton-ct-ngan", status: "done" },
  { no: 5104, title: "Lợp Ngói Nhật CT", keyword: "lợp ngói nhật", slug: "lop-ngoi-nhat-ct-ngan", status: "done" },
  { no: 5105, title: "Lợp Ngói Thái CT", keyword: "lợp ngói thái", slug: "lop-ngoi-thai-ct-ngan", status: "done" },
  { no: 5106, title: "Cầu Phong Mái Ngói CT", keyword: "cầu phong mái ngói", slug: "cau-phong-mai-ngoi-ct-ngan", status: "done" },
  { no: 5107, title: "Màng Chống Thấm Dưới Ngói", keyword: "màng chống thấm dưới ngói", slug: "mang-chong-tham-duoi-ngoi-ct-ngan", status: "done" },
  { no: 5108, title: "Báo Giá Chống Thấm m2 CT", keyword: "báo giá chống thấm m2", slug: "bao-gia-chong-tham-m2-ct-ngan", status: "done" },
  { no: 5109, title: "Báo Giá Chống Thấm Sân Thượng", keyword: "báo giá chống thấm sân thượng", slug: "bao-gia-chong-tham-san-thuong-ct-ngan", status: "done" },
  { no: 5110, title: "Báo Giá Chống Thấm WC CT", keyword: "báo giá chống thấm wc", slug: "bao-gia-chong-tham-wc-ct-ngan", status: "done" },
  { no: 5111, title: "Báo Giá Lợp Mái Tôn CT", keyword: "báo giá lợp mái tôn", slug: "bao-gia-lop-mai-ton-ct-ngan", status: "done" },
  { no: 5112, title: "Báo Giá Lợp Mái Ngói CT", keyword: "báo giá lợp mái ngói", slug: "bao-gia-lop-mai-ngoi-ct-ngan", status: "done" },
  { no: 5113, title: "Chi Phí Sửa Mái Dột CT", keyword: "chi phí sửa mái dột", slug: "chi-phi-sua-mai-dot-ct-ngan", status: "done" },
  { no: 5114, title: "Chi Phí Thay Mái Tôn CT", keyword: "chi phí thay mái tôn", slug: "chi-phi-thay-mai-ton-ct-ngan", status: "done" },
  { no: 5115, title: "Bảo Hành Chống Thấm CT", keyword: "bảo hành chống thấm", slug: "bao-hanh-chong-tham-ct-ngan", status: "done" },
  { no: 5116, title: "Bảo Hành Mái Tôn CT", keyword: "bảo hành mái tôn", slug: "bao-hanh-mai-ton-ct-ngan", status: "done" },
  { no: 5117, title: "Checklist Chống Thấm CT", keyword: "checklist chống thấm", slug: "checklist-chong-tham-ct-ngan", status: "done" },
  { no: 5118, title: "Checklist Nghiệm Thu Mái CT", keyword: "checklist nghiệm thu mái", slug: "checklist-nghiem-thu-mai-ct-ngan", status: "done" },
  { no: 5119, title: "Lỗi Chống Thấm Thường Gặp", keyword: "lỗi chống thấm thường gặp", slug: "loi-chong-tham-thuong-gap-ct-ngan", status: "done" },
  { no: 5120, title: "Vì Sao Chống Thấm Thất Bại", keyword: "vì sao chống thấm thất bại", slug: "vi-sao-chong-tham-that-bai-ct-ngan", status: "done" },
  { no: 5121, title: "Chọn Đơn Vị Chống Thấm", keyword: "chọn đơn vị chống thấm", slug: "chon-don-vi-chong-tham-ct-ngan", status: "done" },
  { no: 5122, title: "Chống Thấm Trước Ốp Lát", keyword: "chống thấm trước ốp lát", slug: "chong-tham-truoc-op-lat-ct-ngan", status: "done" },
  { no: 5123, title: "Chống Thấm Sau Ốp Lát", keyword: "chống thấm sau ốp lát", slug: "chong-tham-sau-op-lat-ct-ngan", status: "done" },
  { no: 5124, title: "Chống Thấm Mùa Mưa CT", keyword: "chống thấm mùa mưa", slug: "chong-tham-mua-mua-ct-ngan", status: "done" },
  { no: 5125, title: "Chống Thấm Khẩn Cấp CT", keyword: "chống thấm khẩn cấp", slug: "chong-tham-khan-cap-ct-ngan", status: "done" },
  { no: 5126, title: "Dịch Vụ Chống Thấm TPHCM CT", keyword: "dịch vụ chống thấm tphcm", slug: "dich-vu-chong-tham-tphcm-ct-ngan", status: "done" },
  { no: 5127, title: "Thợ Chống Thấm Uy Tín CT", keyword: "thợ chống thấm uy tín", slug: "tho-chong-tham-uy-tin-ct-ngan", status: "done" },
  { no: 5128, title: "Xu Hướng Chống Thấm 2026", keyword: "xu hướng chống thấm 2026", slug: "xu-huong-chong-tham-2026-ct-ngan", status: "done" },
  { no: 5129, title: "Vật Liệu Chống Thấm Mới", keyword: "vật liệu chống thấm mới", slug: "vat-lieu-chong-tham-moi-ct-ngan", status: "done" },
  { no: 5130, title: "Chống Thấm Xanh CT", keyword: "chống thấm xanh", slug: "chong-tham-xanh-ct-ngan", status: "done" },
  { no: 5131, title: "Thu Gom Nước Mưa Từ Mái", keyword: "thu gom nước mưa từ mái", slug: "thu-gom-nuoc-mua-tu-mai-ct-ngan", status: "done" },
  { no: 5132, title: "Chủ Đề Mở Rộng 56 1", keyword: "chủ đề mở rộng 56 1", slug: "chu-de-mo-rong-56-1-ngan", status: "done" },
  { no: 5133, title: "Chủ Đề Mở Rộng 56 2", keyword: "chủ đề mở rộng 56 2", slug: "chu-de-mo-rong-56-2-ngan", status: "done" },
  { no: 5134, title: "Chủ Đề Mở Rộng 56 3", keyword: "chủ đề mở rộng 56 3", slug: "chu-de-mo-rong-56-3-ngan", status: "done" },
  { no: 5135, title: "Chủ Đề Mở Rộng 56 4", keyword: "chủ đề mở rộng 56 4", slug: "chu-de-mo-rong-56-4-ngan", status: "done" },
  { no: 5136, title: "Chủ Đề Mở Rộng 56 5", keyword: "chủ đề mở rộng 56 5", slug: "chu-de-mo-rong-56-5-ngan", status: "done" },
  { no: 5137, title: "Chủ Đề Mở Rộng 56 6", keyword: "chủ đề mở rộng 56 6", slug: "chu-de-mo-rong-56-6-ngan", status: "done" },
  { no: 5138, title: "Chủ Đề Mở Rộng 56 7", keyword: "chủ đề mở rộng 56 7", slug: "chu-de-mo-rong-56-7-ngan", status: "done" },
  { no: 5139, title: "Chủ Đề Mở Rộng 56 8", keyword: "chủ đề mở rộng 56 8", slug: "chu-de-mo-rong-56-8-ngan", status: "done" },
  { no: 5140, title: "Chủ Đề Mở Rộng 56 9", keyword: "chủ đề mở rộng 56 9", slug: "chu-de-mo-rong-56-9-ngan", status: "done" },
  { no: 5141, title: "Chủ Đề Mở Rộng 56 10", keyword: "chủ đề mở rộng 56 10", slug: "chu-de-mo-rong-56-10-ngan", status: "done" },
  { no: 5142, title: "Chủ Đề Mở Rộng 56 11", keyword: "chủ đề mở rộng 56 11", slug: "chu-de-mo-rong-56-11-ngan", status: "done" },
  { no: 5143, title: "Chủ Đề Mở Rộng 56 12", keyword: "chủ đề mở rộng 56 12", slug: "chu-de-mo-rong-56-12-ngan", status: "done" },
  { no: 5144, title: "Chủ Đề Mở Rộng 56 13", keyword: "chủ đề mở rộng 56 13", slug: "chu-de-mo-rong-56-13-ngan", status: "done" },
  { no: 5145, title: "Chủ Đề Mở Rộng 56 14", keyword: "chủ đề mở rộng 56 14", slug: "chu-de-mo-rong-56-14-ngan", status: "done" },
  { no: 5146, title: "Chủ Đề Mở Rộng 56 15", keyword: "chủ đề mở rộng 56 15", slug: "chu-de-mo-rong-56-15-ngan", status: "done" },
];
