/**
 * Lịch 100 từ khóa ngắn — batch 57 (#5147–#5246).
 * Cluster: geo Thủ Đức, Q12, trục khu vực mới.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch57: ContentCalendarItem[] = [
  { no: 5147, title: "Xây Nhà Linh Xuân", keyword: "xây nhà Linh Xuân", slug: "xay-nha-linh-xuan-td-ngan", status: "done" },
  { no: 5148, title: "Xây Nhà Linh Trung", keyword: "xây nhà Linh Trung", slug: "xay-nha-linh-trung-td-ngan", status: "done" },
  { no: 5149, title: "Xây Nhà Linh Chiểu", keyword: "xây nhà Linh Chiểu", slug: "xay-nha-linh-chieu-td-ngan", status: "done" },
  { no: 5150, title: "Xây Nhà Linh Tây", keyword: "xây nhà Linh Tây", slug: "xay-nha-linh-tay-td-ngan", status: "done" },
  { no: 5151, title: "Xây Nhà Linh Đông", keyword: "xây nhà Linh Đông", slug: "xay-nha-linh-dong-td-ngan", status: "done" },
  { no: 5152, title: "Xây Nhà Trường Thọ", keyword: "xây nhà Trường Thọ", slug: "xay-nha-truong-tho-td-ngan", status: "done" },
  { no: 5153, title: "Xây Nhà Bình Chiểu", keyword: "xây nhà Bình Chiểu", slug: "xay-nha-binh-chieu-td-ngan", status: "done" },
  { no: 5154, title: "Xây Nhà Hiệp Bình Chánh", keyword: "xây nhà Hiệp Bình Chánh", slug: "xay-nha-hiep-binh-chanh-td-ngan", status: "done" },
  { no: 5155, title: "Xây Nhà Hiệp Bình Phước", keyword: "xây nhà Hiệp Bình Phước", slug: "xay-nha-hiep-binh-phuoc-td-ngan", status: "done" },
  { no: 5156, title: "Xây Nhà Tam Bình TD", keyword: "xây nhà Tam Bình Thủ Đức", slug: "xay-nha-tam-binh-td-ngan", status: "done" },
  { no: 5157, title: "Xây Nhà Tam Phú", keyword: "xây nhà Tam Phú", slug: "xay-nha-tam-phu-td-ngan", status: "done" },
  { no: 5158, title: "Xây Nhà Thủ Thiêm", keyword: "xây nhà Thủ Thiêm", slug: "xay-nha-thu-thiem-td-ngan", status: "done" },
  { no: 5159, title: "Xây Nhà An Khánh TD", keyword: "xây nhà An Khánh Thủ Đức", slug: "xay-nha-an-khanh-td-ngan", status: "done" },
  { no: 5160, title: "Xây Nhà An Lợi Đông", keyword: "xây nhà An Lợi Đông", slug: "xay-nha-an-loi-dong-td-ngan", status: "done" },
  { no: 5161, title: "Xây Nhà Bình Trưng Đông", keyword: "xây nhà Bình Trưng Đông", slug: "xay-nha-binh-trung-dong-td-ngan", status: "done" },
  { no: 5162, title: "Xây Nhà Bình Trưng Tây", keyword: "xây nhà Bình Trưng Tây", slug: "xay-nha-binh-trung-tay-td-ngan", status: "done" },
  { no: 5163, title: "Xây Nhà Cát Lái", keyword: "xây nhà Cát Lái", slug: "xay-nha-cat-lai-td-ngan", status: "done" },
  { no: 5164, title: "Xây Nhà Thạnh Mỹ Lợi", keyword: "xây nhà Thạnh Mỹ Lợi", slug: "xay-nha-thanh-my-loi-td-ngan", status: "done" },
  { no: 5165, title: "Xây Nhà Phước Long A", keyword: "xây nhà Phước Long A", slug: "xay-nha-phuoc-long-a-td-ngan", status: "done" },
  { no: 5166, title: "Xây Nhà Phước Long B", keyword: "xây nhà Phước Long B", slug: "xay-nha-phuoc-long-b-td-ngan", status: "done" },
  { no: 5167, title: "Xây Nhà Tăng Nhơn Phú A", keyword: "xây nhà Tăng Nhơn Phú A", slug: "xay-nha-tang-nhon-phu-a-td-ngan", status: "done" },
  { no: 5168, title: "Xây Nhà Tăng Nhơn Phú B", keyword: "xây nhà Tăng Nhơn Phú B", slug: "xay-nha-tang-nhon-phu-b-td-ngan", status: "done" },
  { no: 5169, title: "Xây Nhà Long Trường", keyword: "xây nhà Long Trường", slug: "xay-nha-long-truong-td-ngan", status: "done" },
  { no: 5170, title: "Xây Nhà Long Phước TD", keyword: "xây nhà Long Phước Thủ Đức", slug: "xay-nha-long-phuoc-td-ngan", status: "done" },
  { no: 5171, title: "Xây Nhà Trường Thạnh", keyword: "xây nhà Trường Thạnh", slug: "xay-nha-truong-thanh-td-ngan", status: "done" },
  { no: 5172, title: "Xây Nhà Phú Hữu", keyword: "xây nhà Phú Hữu", slug: "xay-nha-phu-huu-td-ngan", status: "done" },
  { no: 5173, title: "Xây Nhà Hiệp Phú", keyword: "xây nhà Hiệp Phú", slug: "xay-nha-hiep-phu-td-ngan", status: "done" },
  { no: 5174, title: "Xây Nhà Tân Phú TD", keyword: "xây nhà Tân Phú Thủ Đức", slug: "xay-nha-tan-phu-td-ngan", status: "done" },
  { no: 5175, title: "Xây Nhà Long Bình TD", keyword: "xây nhà Long Bình Thủ Đức", slug: "xay-nha-long-binh-td-ngan", status: "done" },
  { no: 5176, title: "Xây Nhà Long Thạnh Mỹ", keyword: "xây nhà Long Thạnh Mỹ", slug: "xay-nha-long-thanh-my-td-ngan", status: "done" },
  { no: 5177, title: "Xây Nhà Gần ĐHQG", keyword: "xây nhà gần ĐHQG", slug: "xay-nha-gan-dhqg-td-ngan", status: "done" },
  { no: 5178, title: "Xây Nhà Gần Suối Tiên", keyword: "xây nhà gần Suối Tiên", slug: "xay-nha-gan-suoi-tien-td-ngan", status: "done" },
  { no: 5179, title: "Xây Nhà Gần Vincom Thủ Đức", keyword: "xây nhà gần Vincom Thủ Đức", slug: "xay-nha-gan-vincom-thu-duc-td-ngan", status: "done" },
  { no: 5180, title: "Xây Nhà Gần Ga Metro Bình Thái", keyword: "xây nhà gần ga metro Bình Thái", slug: "xay-nha-gan-metro-binh-thai-td-ngan", status: "done" },
  { no: 5181, title: "Xây Nhà Gần Ga Metro Thủ Đức", keyword: "xây nhà gần ga metro Thủ Đức", slug: "xay-nha-gan-metro-thu-duc-td-ngan", status: "done" },
  { no: 5182, title: "Xây Nhà Gần Xa Lộ Hà Nội", keyword: "xây nhà gần Xa lộ Hà Nội", slug: "xay-nha-gan-xa-lo-ha-noi-td-ngan", status: "done" },
  { no: 5183, title: "Xây Nhà Gần Phạm Văn Đồng", keyword: "xây nhà gần Phạm Văn Đồng", slug: "xay-nha-gan-pham-van-dong-td-ngan", status: "done" },
  { no: 5184, title: "Xây Nhà Gần Võ Nguyên Giáp", keyword: "xây nhà gần Võ Nguyên Giáp", slug: "xay-nha-gan-vo-nguyen-giap-td-ngan", status: "done" },
  { no: 5185, title: "Xây Nhà Gần Nguyễn Duy Trinh", keyword: "xây nhà gần Nguyễn Duy Trinh", slug: "xay-nha-gan-nguyen-duy-trinh-td-ngan", status: "done" },
  { no: 5186, title: "Xây Nhà Gần Đồng Văn Cống", keyword: "xây nhà gần Đồng Văn Cống", slug: "xay-nha-gan-dong-van-cong-td-ngan", status: "done" },
  { no: 5187, title: "Cải Tạo Nhà Linh Xuân", keyword: "cải tạo nhà Linh Xuân", slug: "cai-tao-nha-linh-xuan-td-ngan", status: "done" },
  { no: 5188, title: "Cải Tạo Nhà Hiệp Bình Chánh", keyword: "cải tạo nhà Hiệp Bình Chánh", slug: "cai-tao-nha-hiep-binh-chanh-td-ngan", status: "done" },
  { no: 5189, title: "Cải Tạo Nhà Cát Lái", keyword: "cải tạo nhà Cát Lái", slug: "cai-tao-nha-cat-lai-td-ngan", status: "done" },
  { no: 5190, title: "Cải Tạo Nhà Phước Long", keyword: "cải tạo nhà Phước Long", slug: "cai-tao-nha-phuoc-long-td-ngan", status: "done" },
  { no: 5191, title: "Cải Tạo Nhà Tăng Nhơn Phú", keyword: "cải tạo nhà Tăng Nhơn Phú", slug: "cai-tao-nha-tang-nhon-phu-td-ngan", status: "done" },
  { no: 5192, title: "Cải Tạo Nhà Thủ Thiêm", keyword: "cải tạo nhà Thủ Thiêm", slug: "cai-tao-nha-thu-thiem-td-ngan", status: "done" },
  { no: 5193, title: "Thiết Kế Nhà Linh Trung", keyword: "thiết kế nhà Linh Trung", slug: "thiet-ke-nha-linh-trung-td-ngan", status: "done" },
  { no: 5194, title: "Thiết Kế Nhà Hiệp Bình Phước", keyword: "thiết kế nhà Hiệp Bình Phước", slug: "thiet-ke-nha-hiep-binh-phuoc-td-ngan", status: "done" },
  { no: 5195, title: "Thiết Kế Nhà Cát Lái", keyword: "thiết kế nhà Cát Lái", slug: "thiet-ke-nha-cat-lai-td-ngan", status: "done" },
  { no: 5196, title: "Thiết Kế Nhà Phước Long A", keyword: "thiết kế nhà Phước Long A", slug: "thiet-ke-nha-phuoc-long-a-td-ngan", status: "done" },
  { no: 5197, title: "Thiết Kế Nhà Thủ Thiêm", keyword: "thiết kế nhà Thủ Thiêm", slug: "thiet-ke-nha-thu-thiem-td-ngan", status: "done" },
  { no: 5198, title: "Báo Giá Xây Nhà Thủ Đức TD", keyword: "báo giá xây nhà Thủ Đức", slug: "bao-gia-xay-nha-thu-duc-td-ngan", status: "done" },
  { no: 5199, title: "Báo Giá Xây Nhà Linh Xuân", keyword: "báo giá xây nhà Linh Xuân", slug: "bao-gia-xay-nha-linh-xuan-td-ngan", status: "done" },
  { no: 5200, title: "Báo Giá Xây Nhà Cát Lái", keyword: "báo giá xây nhà Cát Lái", slug: "bao-gia-xay-nha-cat-lai-td-ngan", status: "done" },
  { no: 5201, title: "Báo Giá Xây Nhà Hiệp Bình", keyword: "báo giá xây nhà Hiệp Bình", slug: "bao-gia-xay-nha-hiep-binh-td-ngan", status: "done" },
  { no: 5202, title: "Báo Giá Cải Tạo Thủ Đức", keyword: "báo giá cải tạo Thủ Đức", slug: "bao-gia-cai-tao-thu-duc-td-ngan", status: "done" },
  { no: 5203, title: "Nhà Thầu Thủ Đức TD", keyword: "nhà thầu Thủ Đức", slug: "nha-thau-thu-duc-td-ngan", status: "done" },
  { no: 5204, title: "Nhà Thầu Linh Xuân", keyword: "nhà thầu Linh Xuân", slug: "nha-thau-linh-xuan-td-ngan", status: "done" },
  { no: 5205, title: "Nhà Thầu Cát Lái", keyword: "nhà thầu Cát Lái", slug: "nha-thau-cat-lai-td-ngan", status: "done" },
  { no: 5206, title: "Nhà Thầu Hiệp Bình Chánh", keyword: "nhà thầu Hiệp Bình Chánh", slug: "nha-thau-hiep-binh-chanh-td-ngan", status: "done" },
  { no: 5207, title: "Nhà Thầu Phước Long", keyword: "nhà thầu Phước Long", slug: "nha-thau-phuoc-long-td-ngan", status: "done" },
  { no: 5208, title: "Xây Nhà Phố Thủ Đức", keyword: "xây nhà phố Thủ Đức", slug: "xay-nha-pho-thu-duc-td-ngan", status: "done" },
  { no: 5209, title: "Xây Nhà Ống Thủ Đức", keyword: "xây nhà ống Thủ Đức", slug: "xay-nha-ong-thu-duc-td-ngan", status: "done" },
  { no: 5210, title: "Xây Biệt Thự Thủ Đức", keyword: "xây biệt thự Thủ Đức", slug: "xay-biet-thu-thu-duc-td-ngan", status: "done" },
  { no: 5211, title: "Xây Nhà Vườn Thủ Đức", keyword: "xây nhà vườn Thủ Đức", slug: "xay-nha-vuon-thu-duc-td-ngan", status: "done" },
  { no: 5212, title: "Xây Nhà Trọ Thủ Đức", keyword: "xây nhà trọ Thủ Đức", slug: "xay-nha-tro-thu-duc-td-ngan", status: "done" },
  { no: 5213, title: "Xin Phép Xây Nhà Thủ Đức", keyword: "xin phép xây nhà Thủ Đức", slug: "xin-phep-xay-nha-thu-duc-td-ngan", status: "done" },
  { no: 5214, title: "Đơn Giá Xây Nhà Thủ Đức", keyword: "đơn giá xây nhà Thủ Đức", slug: "don-gia-xay-nha-thu-duc-td-ngan", status: "done" },
  { no: 5215, title: "Xây Nhà KĐT Vinhomes Grand Park", keyword: "xây nhà gần Vinhomes Grand Park", slug: "xay-nha-gan-vinhomes-grand-park-td-ngan", status: "done" },
  { no: 5216, title: "Xây Nhà KĐT Sala", keyword: "xây nhà gần Sala", slug: "xay-nha-gan-sala-td-ngan", status: "done" },
  { no: 5217, title: "Xây Nhà KĐT Thủ Thiêm", keyword: "xây nhà gần Thủ Thiêm", slug: "xay-nha-gan-thu-thiem-kdt-td-ngan", status: "done" },
  { no: 5218, title: "Xây Nhà Gần ĐHSPKT", keyword: "xây nhà gần ĐH SPKT", slug: "xay-nha-gan-dhspkt-td-ngan", status: "done" },
  { no: 5219, title: "Xây Nhà Gần ĐH Nông Lâm", keyword: "xây nhà gần ĐH Nông Lâm", slug: "xay-nha-gan-dh-nong-lam-td-ngan", status: "done" },
  { no: 5220, title: "Xây Nhà Gần Khu CNC", keyword: "xây nhà gần khu CNC", slug: "xay-nha-gan-khu-cnc-td-ngan", status: "done" },
  { no: 5221, title: "Xây Nhà Gần Sài Gòn Zoo", keyword: "xây nhà gần Thảo Cầm Viên mới", slug: "xay-nha-gan-thao-cam-vien-moi-td-ngan", status: "done" },
  { no: 5222, title: "Cải Tạo Mặt Tiền Thủ Đức", keyword: "cải tạo mặt tiền Thủ Đức", slug: "cai-tao-mat-tien-thu-duc-td-ngan", status: "done" },
  { no: 5223, title: "Nâng Tầng Nhà Thủ Đức", keyword: "nâng tầng nhà Thủ Đức", slug: "nang-tang-nha-thu-duc-td-ngan", status: "done" },
  { no: 5224, title: "Sửa Nhà Thủ Đức", keyword: "sửa nhà Thủ Đức", slug: "sua-nha-thu-duc-td-ngan", status: "done" },
  { no: 5225, title: "Chống Thấm Nhà Thủ Đức", keyword: "chống thấm nhà Thủ Đức", slug: "chong-tham-nha-thu-duc-td-ngan", status: "done" },
  { no: 5226, title: "Thiết Kế Nội Thất Thủ Đức", keyword: "thiết kế nội thất Thủ Đức", slug: "thiet-ke-noi-that-thu-duc-td-ngan", status: "done" },
  { no: 5227, title: "Xây Nhà An Phú Đông", keyword: "xây nhà An Phú Đông", slug: "xay-nha-an-phu-dong-td-ngan", status: "done" },
  { no: 5228, title: "Xây Nhà Thạnh Xuân", keyword: "xây nhà Thạnh Xuân", slug: "xay-nha-thanh-xuan-q12-ngan", status: "done" },
  { no: 5229, title: "Xây Nhà Thới An", keyword: "xây nhà Thới An", slug: "xay-nha-thoi-an-q12-ngan", status: "done" },
  { no: 5230, title: "Xây Nhà Trung Mỹ Tây", keyword: "xây nhà Trung Mỹ Tây", slug: "xay-nha-trung-my-tay-q12-ngan", status: "done" },
  { no: 5231, title: "Xây Nhà Tân Chánh Hiệp", keyword: "xây nhà Tân Chánh Hiệp", slug: "xay-nha-tan-chanh-hiep-q12-ngan", status: "done" },
  { no: 5232, title: "Xây Nhà Tân Thới Hiệp", keyword: "xây nhà Tân Thới Hiệp", slug: "xay-nha-tan-thoi-hiep-q12-ngan", status: "done" },
  { no: 5233, title: "Xây Nhà Đông Hưng Thuận", keyword: "xây nhà Đông Hưng Thuận", slug: "xay-nha-dong-hung-thuan-q12-ngan", status: "done" },
  { no: 5234, title: "Xây Nhà Tân Hưng Thuận", keyword: "xây nhà Tân Hưng Thuận", slug: "xay-nha-tan-hung-thuan-q12-ngan", status: "done" },
  { no: 5235, title: "Xây Nhà Hiệp Thành Q12", keyword: "xây nhà Hiệp Thành Q12", slug: "xay-nha-hiep-thanh-q12-ngan", status: "done" },
  { no: 5236, title: "Xây Nhà Thạnh Lộc Q12", keyword: "xây nhà Thạnh Lộc Q12", slug: "xay-nha-thanh-loc-q12-ngan", status: "done" },
  { no: 5237, title: "Xây Nhà An Phú Đông Q12", keyword: "xây nhà An Phú Đông Q12", slug: "xay-nha-an-phu-dong-q12-ngan", status: "done" },
  { no: 5238, title: "Nhà Thầu Quận 12", keyword: "nhà thầu Quận 12", slug: "nha-thau-quan-12-td-ngan", status: "done" },
  { no: 5239, title: "Báo Giá Xây Nhà Quận 12", keyword: "báo giá xây nhà Quận 12", slug: "bao-gia-xay-nha-quan-12-td-ngan", status: "done" },
  { no: 5240, title: "Cải Tạo Nhà Quận 12", keyword: "cải tạo nhà Quận 12", slug: "cai-tao-nha-quan-12-td-ngan", status: "done" },
  { no: 5241, title: "Chủ Đề Mở Rộng 57 1", keyword: "chủ đề mở rộng 57 1", slug: "chu-de-mo-rong-57-1-ngan", status: "done" },
  { no: 5242, title: "Chủ Đề Mở Rộng 57 2", keyword: "chủ đề mở rộng 57 2", slug: "chu-de-mo-rong-57-2-ngan", status: "done" },
  { no: 5243, title: "Chủ Đề Mở Rộng 57 3", keyword: "chủ đề mở rộng 57 3", slug: "chu-de-mo-rong-57-3-ngan", status: "done" },
  { no: 5244, title: "Chủ Đề Mở Rộng 57 4", keyword: "chủ đề mở rộng 57 4", slug: "chu-de-mo-rong-57-4-ngan", status: "done" },
  { no: 5245, title: "Chủ Đề Mở Rộng 57 5", keyword: "chủ đề mở rộng 57 5", slug: "chu-de-mo-rong-57-5-ngan", status: "done" },
  { no: 5246, title: "Chủ Đề Mở Rộng 57 6", keyword: "chủ đề mở rộng 57 6", slug: "chu-de-mo-rong-57-6-ngan", status: "done" },
];
