/**
 * Lịch 100 từ khóa ngắn — batch 61 (#5547–#5646).
 * Cluster: thiết bị, phụ kiện, vật tư phụ công trình.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch61: ContentCalendarItem[] = [
  { no: 5547, title: "Camera Giám Sát Công Trình", keyword: "camera giám sát công trình", slug: "camera-giam-sat-cong-trinh-tb-ngan", status: "done" },
  { no: 5548, title: "Máy Chấm Công Công Trình", keyword: "máy chấm công công trình", slug: "may-cham-cong-cong-trinh-tb-ngan", status: "done" },
  { no: 5549, title: "Đèn Công Trường", keyword: "đèn công trường", slug: "den-cong-truong-tb-ngan", status: "done" },
  { no: 5550, title: "Máy Phát Điện Công Trình", keyword: "máy phát điện công trình", slug: "may-phat-dien-cong-trinh-tb-ngan", status: "done" },
  { no: 5551, title: "Máy Bơm Nước Công Trình", keyword: "máy bơm nước công trình", slug: "may-bom-nuoc-cong-trinh-tb-ngan", status: "done" },
  { no: 5552, title: "Máy Trộn Hồ Tại Chỗ", keyword: "máy trộn hồ tại chỗ", slug: "may-tron-ho-tai-cho-tb-ngan", status: "done" },
  { no: 5553, title: "Máy Đầm Cóc", keyword: "máy đầm cóc", slug: "may-dam-coc-tb-ngan", status: "done" },
  { no: 5554, title: "Máy Cắt Gạch", keyword: "máy cắt gạch", slug: "may-cat-gach-tb-ngan", status: "done" },
  { no: 5555, title: "Máy Mài Sàn", keyword: "máy mài sàn", slug: "may-mai-san-tb-ngan", status: "done" },
  { no: 5556, title: "Máy Phun Sơn", keyword: "máy phun sơn", slug: "may-phun-son-tb-ngan", status: "done" },
  { no: 5557, title: "Máy Khoan Bê Tông", keyword: "máy khoan bê tông", slug: "may-khoan-be-tong-tb-ngan", status: "done" },
  { no: 5558, title: "Máy Hàn Công Trình", keyword: "máy hàn công trình", slug: "may-han-cong-trinh-tb-ngan", status: "done" },
  { no: 5559, title: "Giàn Giáo Nêm", keyword: "giàn giáo nêm", slug: "gian-giao-nem-tb-ngan", status: "done" },
  { no: 5560, title: "Giàn Giáo Ống", keyword: "giàn giáo ống", slug: "gian-giao-ong-tb-ngan", status: "done" },
  { no: 5561, title: "Ván Ép Cốp Pha", keyword: "ván ép cốp pha", slug: "van-ep-cop-pha-tb-ngan", status: "done" },
  { no: 5562, title: "Cốp Pha Thép", keyword: "cốp pha thép", slug: "cop-pha-thep-tb-ngan", status: "done" },
  { no: 5563, title: "Cốp Pha Nhôm", keyword: "cốp pha nhôm", slug: "cop-pha-nhom-tb-ngan", status: "done" },
  { no: 5564, title: "Chống Thép Sàn", keyword: "chống thép sàn", slug: "chong-thep-san-tb-ngan", status: "done" },
  { no: 5565, title: "Ty Ren Cốp Pha", keyword: "ty ren cốp pha", slug: "ty-ren-cop-pha-tb-ngan", status: "done" },
  { no: 5566, title: "Dây Buộc Thép", keyword: "dây buộc thép", slug: "day-buoc-thep-tb-ngan", status: "done" },
  { no: 5567, title: "Băng Keo Chống Thấm", keyword: "băng keo chống thấm", slug: "bang-keo-chong-tham-tb-ngan", status: "done" },
  { no: 5568, title: "Lưới Thủy Tinh", keyword: "lưới thủy tinh", slug: "luoi-thuy-tinh-tb-ngan", status: "done" },
  { no: 5569, title: "Lưới Mắt Cáo", keyword: "lưới mắt cáo", slug: "luoi-mat-cao-tb-ngan", status: "done" },
  { no: 5570, title: "Màng Nylon Công Trình", keyword: "màng nylon công trình", slug: "mang-nylon-cong-trinh-tb-ngan", status: "done" },
  { no: 5571, title: "Bao Tay Lao Động", keyword: "bao tay lao động", slug: "bao-tay-lao-dong-tb-ngan", status: "done" },
  { no: 5572, title: "Mũ Bảo Hộ Công Trình", keyword: "mũ bảo hộ công trình", slug: "mu-bao-ho-cong-trinh-tb-ngan", status: "done" },
  { no: 5573, title: "Giày Bảo Hộ Xây Dựng", keyword: "giày bảo hộ xây dựng", slug: "giay-bao-ho-xay-dung-tb-ngan", status: "done" },
  { no: 5574, title: "Dây An Toàn Treo", keyword: "dây an toàn treo", slug: "day-an-toan-treo-tb-ngan", status: "done" },
  { no: 5575, title: "Thước Laser Đo Nhà", keyword: "thước laser đo nhà", slug: "thuoc-laser-do-nha-tb-ngan", status: "done" },
  { no: 5576, title: "Máy Cân Mực Laser", keyword: "máy cân mực laser", slug: "may-can-muc-laser-tb-ngan", status: "done" },
  { no: 5577, title: "Máy Đo Độ Ẩm Tường", keyword: "máy đo độ ẩm tường", slug: "may-do-do-am-tuong-tb-ngan", status: "done" },
  { no: 5578, title: "Máy Đo Điện Áp", keyword: "máy đo điện áp", slug: "may-do-dien-ap-tb-ngan", status: "done" },
  { no: 5579, title: "Ống Nhựa Xoắn Điện", keyword: "ống nhựa xoắn điện", slug: "ong-nhua-xoan-dien-tb-ngan", status: "done" },
  { no: 5580, title: "Hộp Nối Điện Âm", keyword: "hộp nối điện âm", slug: "hop-noi-dien-am-tb-ngan", status: "done" },
  { no: 5581, title: "Ống Luồn Dây Điện", keyword: "ống luồn dây điện", slug: "ong-luon-day-dien-tb-ngan", status: "done" },
  { no: 5582, title: "Băng Keo Điện", keyword: "băng keo điện", slug: "bang-keo-dien-tb-ngan", status: "done" },
  { no: 5583, title: "Cút Nối Ống Nước", keyword: "cút nối ống nước", slug: "cut-noi-ong-nuoc-tb-ngan", status: "done" },
  { no: 5584, title: "Tê Ống Nước", keyword: "tê ống nước", slug: "te-ong-nuoc-tb-ngan", status: "done" },
  { no: 5585, title: "Van Khóa Nước", keyword: "van khóa nước", slug: "van-khoa-nuoc-tb-ngan", status: "done" },
  { no: 5586, title: "Phốt Chống Thấm Ống", keyword: "phốt chống thấm ống", slug: "phot-chong-tham-ong-tb-ngan", status: "done" },
  { no: 5587, title: "Ron Cao Su Cửa", keyword: "ron cao su cửa", slug: "ron-cao-su-cua-tb-ngan", status: "done" },
  { no: 5588, title: "Bản Lề Cửa", keyword: "bản lề cửa", slug: "ban-le-cua-tb-ngan", status: "done" },
  { no: 5589, title: "Khóa Tay Gạt", keyword: "khóa tay gạt", slug: "khoa-tay-gat-tb-ngan", status: "done" },
  { no: 5590, title: "Khóa Âm Cửa", keyword: "khóa âm cửa", slug: "khoa-am-cua-tb-ngan", status: "done" },
  { no: 5591, title: "Tay Nắm Cửa", keyword: "tay nắm cửa", slug: "tay-nam-cua-tb-ngan", status: "done" },
  { no: 5592, title: "Thanh Trượt Cửa Lùa", keyword: "thanh trượt cửa lùa", slug: "thanh-truot-cua-lua-tb-ngan", status: "done" },
  { no: 5593, title: "Bánh Xe Cửa Lùa", keyword: "bánh xe cửa lùa", slug: "banh-xe-cua-lua-tb-ngan", status: "done" },
  { no: 5594, title: "Ray Cửa Lùa", keyword: "ray cửa lùa", slug: "ray-cua-lua-tb-ngan", status: "done" },
  { no: 5595, title: "Nẹp Chỉ Trần", keyword: "nẹp chỉ trần", slug: "nep-chi-tran-tb-ngan", status: "done" },
  { no: 5596, title: "Đinh Vít Trần", keyword: "đinh vít trần", slug: "dinh-vit-tran-tb-ngan", status: "done" },
  { no: 5597, title: "Khung Xương Trần", keyword: "khung xương trần", slug: "khung-xuong-tran-tb-ngan", status: "done" },
  { no: 5598, title: "Ke Góc Trần", keyword: "ke góc trần", slug: "ke-goc-tran-tb-ngan", status: "done" },
  { no: 5599, title: "Bột Bả Matit", keyword: "bột bả matit", slug: "bot-ba-matit-tb-ngan", status: "done" },
  { no: 5600, title: "Giấy Nhám Tường", keyword: "giấy nhám tường", slug: "giay-nham-tuong-tb-ngan", status: "done" },
  { no: 5601, title: "Con Lăn Sơn", keyword: "con lăn sơn", slug: "con-lan-son-tb-ngan", status: "done" },
  { no: 5602, title: "Cọ Sơn Cạnh", keyword: "cọ sơn cạnh", slug: "co-son-canh-tb-ngan", status: "done" },
  { no: 5603, title: "Băng Keo Che Sơn", keyword: "băng keo che sơn", slug: "bang-keo-che-son-tb-ngan", status: "done" },
  { no: 5604, title: "Keo Dán Gỗ", keyword: "keo dán gỗ", slug: "keo-dan-go-tb-ngan", status: "done" },
  { no: 5605, title: "Keo Silicon Trong Suốt", keyword: "keo silicon trong suốt", slug: "keo-silicon-trong-suot-tb-ngan", status: "done" },
  { no: 5606, title: "Keo Silicon Trung Tính", keyword: "keo silicon trung tính", slug: "keo-silicon-trung-tinh-tb-ngan", status: "done" },
  { no: 5607, title: "Foam Bọt Nở", keyword: "foam bọt nở", slug: "foam-bot-no-tb-ngan", status: "done" },
  { no: 5608, title: "Đinh Công Nghiệp", keyword: "đinh công nghiệp", slug: "dinh-cong-nghiep-tb-ngan", status: "done" },
  { no: 5609, title: "Vít Tự Khoan", keyword: "vít tự khoan", slug: "vit-tu-khoan-tb-ngan", status: "done" },
  { no: 5610, title: "Tắc Kê Nở", keyword: "tắc kê nở", slug: "tac-ke-no-tb-ngan", status: "done" },
  { no: 5611, title: "Neo Hóa Chất", keyword: "neo hóa chất", slug: "neo-hoa-chat-tb-ngan", status: "done" },
  { no: 5612, title: "Bulong Neo Móng", keyword: "bulong neo móng", slug: "bulong-neo-mong-tb-ngan", status: "done" },
  { no: 5613, title: "Thép Buộc Đai", keyword: "thép buộc đai", slug: "thep-buoc-dai-tb-ngan", status: "done" },
  { no: 5614, title: "Con Kê Thép", keyword: "con kê thép", slug: "con-ke-thep-tb-ngan", status: "done" },
  { no: 5615, title: "Báo Giá Thuê Giàn Giáo", keyword: "báo giá thuê giàn giáo", slug: "bao-gia-thue-gian-giao-tb-ngan", status: "done" },
  { no: 5616, title: "Báo Giá Thuê Máy Trộn", keyword: "báo giá thuê máy trộn", slug: "bao-gia-thue-may-tron-tb-ngan", status: "done" },
  { no: 5617, title: "Báo Giá Thuê Cần Cẩu Mini", keyword: "báo giá thuê cần cẩu mini", slug: "bao-gia-thue-can-cau-mini-tb-ngan", status: "done" },
  { no: 5618, title: "Báo Giá Thuê Vận Thăng", keyword: "báo giá thuê vận thăng", slug: "bao-gia-thue-van-thang-tb-ngan", status: "done" },
  { no: 5619, title: "Cho Thuê Thiết Bị Xây", keyword: "cho thuê thiết bị xây", slug: "cho-thue-thiet-bi-xay-tb-ngan", status: "done" },
  { no: 5620, title: "Mua Hay Thuê Máy Xây", keyword: "mua hay thuê máy xây", slug: "mua-hay-thue-may-xay-tb-ngan", status: "done" },
  { no: 5621, title: "Bảo Dưỡng Máy Xây Dựng", keyword: "bảo dưỡng máy xây dựng", slug: "bao-duong-may-xay-dung-tb-ngan", status: "done" },
  { no: 5622, title: "An Toàn Thiết Bị Công Trường", keyword: "an toàn thiết bị công trường", slug: "an-toan-thiet-bi-cong-truong-tb-ngan", status: "done" },
  { no: 5623, title: "Checklist Thiết Bị Công Trình", keyword: "checklist thiết bị công trình", slug: "checklist-thiet-bi-cong-trinh-tb-ngan", status: "done" },
  { no: 5624, title: "Vật Tư Phụ Xây Nhà", keyword: "vật tư phụ xây nhà", slug: "vat-tu-phu-xay-nha-tb-ngan", status: "done" },
  { no: 5625, title: "Chi Phí Vật Tư Phụ", keyword: "chi phí vật tư phụ", slug: "chi-phi-vat-tu-phu-tb-ngan", status: "done" },
  { no: 5626, title: "Kho Vật Tư Công Trình", keyword: "kho vật tư công trình", slug: "kho-vat-tu-cong-trinh-tb-ngan", status: "done" },
  { no: 5627, title: "Quản Lý Vật Tư Công Trường", keyword: "quản lý vật tư công trường", slug: "quan-ly-vat-tu-cong-truong-tb-ngan", status: "done" },
  { no: 5628, title: "Định Mức Vật Tư Phụ", keyword: "định mức vật tư phụ", slug: "dinh-muc-vat-tu-phu-tb-ngan", status: "done" },
  { no: 5629, title: "Nhà Cung Cấp Vật Tư Xây", keyword: "nhà cung cấp vật tư xây", slug: "nha-cung-cap-vat-tu-xay-tb-ngan", status: "done" },
  { no: 5630, title: "Đại Lý Vật Tư Gần Công Trình", keyword: "đại lý vật tư gần công trình", slug: "dai-ly-vat-tu-gan-cong-trinh-tb-ngan", status: "done" },
  { no: 5631, title: "Giao Vật Tư Đúng Tiến Độ", keyword: "giao vật tư đúng tiến độ", slug: "giao-vat-tu-dung-tien-do-tb-ngan", status: "done" },
  { no: 5632, title: "Kiểm Hàng Vật Tư Nhập", keyword: "kiểm hàng vật tư nhập", slug: "kiem-hang-vat-tu-nhap-tb-ngan", status: "done" },
  { no: 5633, title: "Xu Hướng Thiết Bị Xây 2026", keyword: "xu hướng thiết bị xây 2026", slug: "xu-huong-thiet-bi-xay-2026-tb-ngan", status: "done" },
  { no: 5634, title: "Chủ Đề Mở Rộng 61 1", keyword: "chủ đề mở rộng 61 1", slug: "chu-de-mo-rong-61-1-ngan", status: "done" },
  { no: 5635, title: "Chủ Đề Mở Rộng 61 2", keyword: "chủ đề mở rộng 61 2", slug: "chu-de-mo-rong-61-2-ngan", status: "done" },
  { no: 5636, title: "Chủ Đề Mở Rộng 61 3", keyword: "chủ đề mở rộng 61 3", slug: "chu-de-mo-rong-61-3-ngan", status: "done" },
  { no: 5637, title: "Chủ Đề Mở Rộng 61 4", keyword: "chủ đề mở rộng 61 4", slug: "chu-de-mo-rong-61-4-ngan", status: "done" },
  { no: 5638, title: "Chủ Đề Mở Rộng 61 5", keyword: "chủ đề mở rộng 61 5", slug: "chu-de-mo-rong-61-5-ngan", status: "done" },
  { no: 5639, title: "Chủ Đề Mở Rộng 61 6", keyword: "chủ đề mở rộng 61 6", slug: "chu-de-mo-rong-61-6-ngan", status: "done" },
  { no: 5640, title: "Chủ Đề Mở Rộng 61 7", keyword: "chủ đề mở rộng 61 7", slug: "chu-de-mo-rong-61-7-ngan", status: "done" },
  { no: 5641, title: "Chủ Đề Mở Rộng 61 8", keyword: "chủ đề mở rộng 61 8", slug: "chu-de-mo-rong-61-8-ngan", status: "done" },
  { no: 5642, title: "Chủ Đề Mở Rộng 61 9", keyword: "chủ đề mở rộng 61 9", slug: "chu-de-mo-rong-61-9-ngan", status: "done" },
  { no: 5643, title: "Chủ Đề Mở Rộng 61 10", keyword: "chủ đề mở rộng 61 10", slug: "chu-de-mo-rong-61-10-ngan", status: "done" },
  { no: 5644, title: "Chủ Đề Mở Rộng 61 11", keyword: "chủ đề mở rộng 61 11", slug: "chu-de-mo-rong-61-11-ngan", status: "done" },
  { no: 5645, title: "Chủ Đề Mở Rộng 61 12", keyword: "chủ đề mở rộng 61 12", slug: "chu-de-mo-rong-61-12-ngan", status: "done" },
  { no: 5646, title: "Chủ Đề Mở Rộng 61 13", keyword: "chủ đề mở rộng 61 13", slug: "chu-de-mo-rong-61-13-ngan", status: "done" },
];
