/**
 * Lịch 100 từ khóa ngắn — batch 40 (#3447–#3546).
 * Cluster: mặt tiền, ngoại thất, cảnh quan.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch40: ContentCalendarItem[] = [
  { no: 3447, title: "Mặt Tiền Nhà Phố Hiện Đại", keyword: "mặt tiền nhà phố hiện đại", slug: "mat-tien-nha-pho-hien-dai-fc-ngan", status: "done" },
  { no: 3448, title: "Mặt Tiền Nhà Phố Tối Giản", keyword: "mặt tiền nhà phố tối giản", slug: "mat-tien-nha-pho-toi-gian-fc-ngan", status: "done" },
  { no: 3449, title: "Mặt Tiền Nhà Phố Luxury", keyword: "mặt tiền nhà phố luxury", slug: "mat-tien-nha-pho-luxury-fc-ngan", status: "done" },
  { no: 3450, title: "Mặt Tiền Nhà Phố Indochine", keyword: "mặt tiền nhà phố indochine", slug: "mat-tien-nha-pho-indochine-fc-ngan", status: "done" },
  { no: 3451, title: "Mặt Tiền Ốp Đá", keyword: "mặt tiền ốp đá", slug: "mat-tien-op-da-fc-ngan", status: "done" },
  { no: 3452, title: "Mặt Tiền Ốp Gạch", keyword: "mặt tiền ốp gạch", slug: "mat-tien-op-gach-fc-ngan", status: "done" },
  { no: 3453, title: "Mặt Tiền Sơn Giả Đá", keyword: "mặt tiền sơn giả đá", slug: "mat-tien-son-gia-da-fc-ngan", status: "done" },
  { no: 3454, title: "Mặt Tiền Gỗ Nhựa", keyword: "mặt tiền gỗ nhựa", slug: "mat-tien-go-nhua-fc-ngan", status: "done" },
  { no: 3455, title: "Mặt Tiền Lam Nhôm", keyword: "mặt tiền lam nhôm", slug: "mat-tien-lam-nhom-fc-ngan", status: "done" },
  { no: 3456, title: "Mặt Tiền Lam Gỗ", keyword: "mặt tiền lam gỗ", slug: "mat-tien-lam-go-fc-ngan", status: "done" },
  { no: 3457, title: "Mặt Tiền Kính Cường Lực", keyword: "mặt tiền kính cường lực", slug: "mat-tien-kinh-cuong-luc-fc-ngan", status: "done" },
  { no: 3458, title: "Mặt Tiền Tường Rào Kết Hợp", keyword: "mặt tiền tường rào kết hợp", slug: "mat-tien-tuong-rao-ket-hop-fc-ngan", status: "done" },
  { no: 3459, title: "Cổng Nhà Phố Hiện Đại", keyword: "cổng nhà phố hiện đại", slug: "cong-nha-pho-hien-dai-fc-ngan", status: "done" },
  { no: 3460, title: "Cổng Sắt CNC", keyword: "cổng sắt cnc", slug: "cong-sat-cnc-fc-ngan", status: "done" },
  { no: 3461, title: "Cổng Nhôm Đúc", keyword: "cổng nhôm đúc", slug: "cong-nhom-duc-fc-ngan", status: "done" },
  { no: 3462, title: "Cổng Tự Động Nhà Phố", keyword: "cổng tự động nhà phố", slug: "cong-tu-dong-nha-pho-fc-ngan", status: "done" },
  { no: 3463, title: "Tường Rào Nhà Phố", keyword: "tường rào nhà phố", slug: "tuong-rao-nha-pho-fc-ngan", status: "done" },
  { no: 3464, title: "Tường Rào Kết Hợp Cây Xanh", keyword: "tường rào kết hợp cây xanh", slug: "tuong-rao-ket-hop-cay-xanh-fc-ngan", status: "done" },
  { no: 3465, title: "Hàng Rào Sắt Mỹ Thuật", keyword: "hàng rào sắt mỹ thuật", slug: "hang-rao-sat-my-thuat-fc-ngan", status: "done" },
  { no: 3466, title: "Hàng Rào Inox", keyword: "hàng rào inox", slug: "hang-rao-inox-fc-ngan", status: "done" },
  { no: 3467, title: "Sân Trước Nhà Phố", keyword: "sân trước nhà phố", slug: "san-truoc-nha-pho-fc-ngan", status: "done" },
  { no: 3468, title: "Sân Sau Nhà Phố", keyword: "sân sau nhà phố", slug: "san-sau-nha-pho-fc-ngan", status: "done" },
  { no: 3469, title: "Sân Bên Hông Nhà", keyword: "sân bên hông nhà", slug: "san-ben-hong-nha-fc-ngan", status: "done" },
  { no: 3470, title: "Lát Sân Gạch Block", keyword: "lát sân gạch block", slug: "lat-san-gach-block-fc-ngan", status: "done" },
  { no: 3471, title: "Lát Sân Đá Tự Nhiên", keyword: "lát sân đá tự nhiên", slug: "lat-san-da-tu-nhien-fc-ngan", status: "done" },
  { no: 3472, title: "Lát Sân Bê Tông Vân Gỗ", keyword: "lát sân bê tông vân gỗ", slug: "lat-san-be-tong-van-go-fc-ngan", status: "done" },
  { no: 3473, title: "Đường Dẫn Vào Nhà", keyword: "đường dẫn vào nhà", slug: "duong-dan-vao-nha-fc-ngan", status: "done" },
  { no: 3474, title: "Bậc Tam Cấp Mặt Tiền", keyword: "bậc tam cấp mặt tiền", slug: "bac-tam-cap-mat-tien-fc-ngan", status: "done" },
  { no: 3475, title: "Mái Hiên Nhà Phố", keyword: "mái hiên nhà phố", slug: "mai-hien-nha-pho-fc-ngan", status: "done" },
  { no: 3476, title: "Mái Vòm Mặt Tiền", keyword: "mái vòm mặt tiền", slug: "mai-vom-mat-tien-fc-ngan", status: "done" },
  { no: 3477, title: "Ô Văng Cửa Sổ", keyword: "ô văng cửa sổ", slug: "o-vang-cua-so-fc-ngan", status: "done" },
  { no: 3478, title: "Ban Công Mặt Tiền", keyword: "ban công mặt tiền", slug: "ban-cong-mat-tien-fc-ngan", status: "done" },
  { no: 3479, title: "Ban Công Lan Can Kính", keyword: "ban công lan can kính", slug: "ban-cong-lan-can-kinh-fc-ngan", status: "done" },
  { no: 3480, title: "Ban Công Lan Can Sắt", keyword: "ban công lan can sắt", slug: "ban-cong-lan-can-sat-fc-ngan", status: "done" },
  { no: 3481, title: "Logia Nhà Phố", keyword: "logia nhà phố", slug: "logia-nha-pho-fc-ngan", status: "done" },
  { no: 3482, title: "Sân Thượng Trang Trí", keyword: "sân thượng trang trí", slug: "san-thuong-trang-tri-fc-ngan", status: "done" },
  { no: 3483, title: "Sân Thượng Có Mái Che", keyword: "sân thượng có mái che", slug: "san-thuong-co-mai-che-fc-ngan", status: "done" },
  { no: 3484, title: "Sân Thượng Không Mái", keyword: "sân thượng không mái", slug: "san-thuong-khong-mai-fc-ngan", status: "done" },
  { no: 3485, title: "Vườn Trước Nhà Nhỏ", keyword: "vườn trước nhà nhỏ", slug: "vuon-truoc-nha-nho-fc-ngan", status: "done" },
  { no: 3486, title: "Vườn Sau Nhà Nhỏ", keyword: "vườn sau nhà nhỏ", slug: "vuon-sau-nha-nho-fc-ngan", status: "done" },
  { no: 3487, title: "Vườn Đứng Mặt Tiền", keyword: "vườn đứng mặt tiền", slug: "vuon-dung-mat-tien-fc-ngan", status: "done" },
  { no: 3488, title: "Tường Xanh Mặt Tiền", keyword: "tường xanh mặt tiền", slug: "tuong-xanh-mat-tien-fc-ngan", status: "done" },
  { no: 3489, title: "Cây Bonsai Sân Trước", keyword: "cây bonsai sân trước", slug: "cay-bonsai-san-truoc-fc-ngan", status: "done" },
  { no: 3490, title: "Cây Ăn Trái Sân Sau", keyword: "cây ăn trái sân sau", slug: "cay-an-trai-san-sau-fc-ngan", status: "done" },
  { no: 3491, title: "Bồn Hoa Mặt Tiền", keyword: "bồn hoa mặt tiền", slug: "bon-hoa-mat-tien-fc-ngan", status: "done" },
  { no: 3492, title: "Đèn Sân Vườn Nhà Phố", keyword: "đèn sân vườn nhà phố", slug: "den-san-vuon-nha-pho-fc-ngan", status: "done" },
  { no: 3493, title: "Đèn Chiếu Mặt Tiền", keyword: "đèn chiếu mặt tiền", slug: "den-chieu-mat-tien-fc-ngan", status: "done" },
  { no: 3494, title: "Đèn Cổng Nhà", keyword: "đèn cổng nhà", slug: "den-cong-nha-fc-ngan", status: "done" },
  { no: 3495, title: "Hệ Thống Tưới Cây Tự Động", keyword: "hệ thống tưới cây tự động", slug: "he-thong-tuoi-cay-tu-dong-fc-ngan", status: "done" },
  { no: 3496, title: "Hồ Cá Mini Sân Trước", keyword: "hồ cá mini sân trước", slug: "ho-ca-mini-san-truoc-fc-ngan", status: "done" },
  { no: 3497, title: "Thác Nước Mini Nhà Phố", keyword: "thác nước mini nhà phố", slug: "thac-nuoc-mini-nha-pho-fc-ngan", status: "done" },
  { no: 3498, title: "Đá Cuội Trang Trí Sân", keyword: "đá cuội trang trí sân", slug: "da-cuoi-trang-tri-san-fc-ngan", status: "done" },
  { no: 3499, title: "Sỏi Trang Trí Vườn", keyword: "sỏi trang trí vườn", slug: "soi-trang-tri-vuon-fc-ngan", status: "done" },
  { no: 3500, title: "Chổi Cỏ Nhật Bản", keyword: "cỏ nhật bản sân vườn", slug: "co-nhat-ban-san-vuon-fc-ngan", status: "done" },
  { no: 3501, title: "Cỏ Nhung Nhật", keyword: "cỏ nhung nhật sân", slug: "co-nhung-nhat-san-fc-ngan", status: "done" },
  { no: 3502, title: "Gạch Chuyên Dụng Ngoài Trời", keyword: "gạch chuyên dụng ngoài trời", slug: "gach-chuyen-dung-ngoai-troi-fc-ngan", status: "done" },
  { no: 3503, title: "Sơn Ngoại Thất Chống Phai", keyword: "sơn ngoại thất chống phai", slug: "son-ngoai-that-chong-phai-fc-ngan", status: "done" },
  { no: 3504, title: "Sơn Ngoại Thất Chống Rêu", keyword: "sơn ngoại thất chống rêu", slug: "son-ngoai-that-chong-reu-fc-ngan", status: "done" },
  { no: 3505, title: "Chống Thấm Mặt Tiền", keyword: "chống thấm mặt tiền", slug: "chong-tham-mat-tien-fc-ngan", status: "done" },
  { no: 3506, title: "Vệ Sinh Mặt Tiền Nhà", keyword: "vệ sinh mặt tiền nhà", slug: "ve-sinh-mat-tien-nha-fc-ngan", status: "done" },
  { no: 3507, title: "Sơn Lại Mặt Tiền", keyword: "sơn lại mặt tiền", slug: "son-lai-mat-tien-fc-ngan", status: "done" },
  { no: 3508, title: "Cải Tạo Mặt Tiền Cũ", keyword: "cải tạo mặt tiền cũ", slug: "cai-tao-mat-tien-cu-fc-ngan", status: "done" },
  { no: 3509, title: "Nâng Cấp Cổng Rào", keyword: "nâng cấp cổng rào", slug: "nang-cap-cong-rao-fc-ngan", status: "done" },
  { no: 3510, title: "Thay Lan Can Ban Công", keyword: "thay lan can ban công", slug: "thay-lan-can-ban-cong-fc-ngan", status: "done" },
  { no: 3511, title: "Làm Mới Sân Trước", keyword: "làm mới sân trước", slug: "lam-moi-san-truoc-fc-ngan", status: "done" },
  { no: 3512, title: "Báo Giá Mặt Tiền Nhà Phố", keyword: "báo giá mặt tiền nhà phố", slug: "bao-gia-mat-tien-nha-pho-fc-ngan", status: "done" },
  { no: 3513, title: "Báo Giá Cổng Rào Nhà", keyword: "báo giá cổng rào nhà", slug: "bao-gia-cong-rao-nha-fc-ngan", status: "done" },
  { no: 3514, title: "Báo Giá Sân Vườn Nhà Phố", keyword: "báo giá sân vườn nhà phố", slug: "bao-gia-san-vuon-nha-pho-fc-ngan", status: "done" },
  { no: 3515, title: "Báo Giá Sân Thượng", keyword: "báo giá sân thượng", slug: "bao-gia-san-thuong-fc-ngan", status: "done" },
  { no: 3516, title: "Chi Phí Ốp Đá Mặt Tiền", keyword: "chi phí ốp đá mặt tiền", slug: "chi-phi-op-da-mat-tien-fc-ngan", status: "done" },
  { no: 3517, title: "Chi Phí Lam Nhôm Mặt Tiền", keyword: "chi phí lam nhôm mặt tiền", slug: "chi-phi-lam-nhom-mat-tien-fc-ngan", status: "done" },
  { no: 3518, title: "Chi Phí Vườn Đứng", keyword: "chi phí vườn đứng", slug: "chi-phi-vuon-dung-fc-ngan", status: "done" },
  { no: 3519, title: "Thiết Kế Cảnh Quan Nhà Phố", keyword: "thiết kế cảnh quan nhà phố", slug: "thiet-ke-canh-quan-nha-pho-fc-ngan", status: "done" },
  { no: 3520, title: "Thiết Kế Sân Vườn Nhỏ", keyword: "thiết kế sân vườn nhỏ", slug: "thiet-ke-san-vuon-nho-fc-ngan", status: "done" },
  { no: 3521, title: "Thiết Kế Sân Thượng Xanh", keyword: "thiết kế sân thượng xanh", slug: "thiet-ke-san-thuong-xanh-fc-ngan", status: "done" },
  { no: 3522, title: "Xu Hướng Mặt Tiền 2026", keyword: "xu hướng mặt tiền nhà 2026", slug: "xu-huong-mat-tien-nha-2026-fc-ngan", status: "done" },
  { no: 3523, title: "Xu Hướng Cảnh Quan 2026", keyword: "xu hướng cảnh quan 2026", slug: "xu-huong-canh-quan-2026-fc-ngan", status: "done" },
  { no: 3524, title: "Mặt Tiền Nhà Hẹp 3m", keyword: "mặt tiền nhà hẹp 3m", slug: "mat-tien-nha-hep-3m-fc-ngan", status: "done" },
  { no: 3525, title: "Mặt Tiền Nhà Hẹp 4m", keyword: "mặt tiền nhà hẹp 4m", slug: "mat-tien-nha-hep-4m-fc-ngan", status: "done" },
  { no: 3526, title: "Mặt Tiền Nhà 5m", keyword: "mặt tiền nhà 5m", slug: "mat-tien-nha-5m-fc-ngan", status: "done" },
  { no: 3527, title: "Mặt Tiền Nhà 6m", keyword: "mặt tiền nhà 6m", slug: "mat-tien-nha-6m-fc-ngan", status: "done" },
  { no: 3528, title: "Mặt Tiền Nhà 8m", keyword: "mặt tiền nhà 8m", slug: "mat-tien-nha-8m-fc-ngan", status: "done" },
  { no: 3529, title: "Mặt Tiền Biệt Thự", keyword: "mặt tiền biệt thự", slug: "mat-tien-biet-thu-fc-ngan", status: "done" },
  { no: 3530, title: "Mặt Tiền Nhà Vườn", keyword: "mặt tiền nhà vườn", slug: "mat-tien-nha-vuon-fc-ngan", status: "done" },
  { no: 3531, title: "Mặt Tiền Shop Nhà Phố", keyword: "mặt tiền shop nhà phố", slug: "mat-tien-shop-nha-pho-fc-ngan", status: "done" },
  { no: 3532, title: "Bảng Hiệu Kết Hợp Mặt Tiền", keyword: "bảng hiệu kết hợp mặt tiền", slug: "bang-hieu-ket-hop-mat-tien-fc-ngan", status: "done" },
  { no: 3533, title: "Ánh Sáng Trang Trí Mặt Tiền", keyword: "ánh sáng trang trí mặt tiền", slug: "anh-sang-trang-tri-mat-tien-fc-ngan", status: "done" },
  { no: 3534, title: "Led Viền Mặt Tiền", keyword: "led viền mặt tiền", slug: "led-vien-mat-tien-fc-ngan", status: "done" },
  { no: 3535, title: "Camera Cổng Nhà", keyword: "camera cổng nhà", slug: "camera-cong-nha-fc-ngan", status: "done" },
  { no: 3536, title: "Chuông Cổng Có Hình", keyword: "chuông cổng có hình", slug: "chuong-cong-co-hinh-fc-ngan", status: "done" },
  { no: 3537, title: "Khóa Cổng Vân Tay", keyword: "khóa cổng vân tay", slug: "khoa-cong-van-tay-fc-ngan", status: "done" },
  { no: 3538, title: "Motor Cổng Lùa", keyword: "motor cổng lùa", slug: "motor-cong-lua-fc-ngan", status: "done" },
  { no: 3539, title: "Motor Cổng Mở Quay", keyword: "motor cổng mở quay", slug: "motor-cong-mo-quay-fc-ngan", status: "done" },
  { no: 3540, title: "Nghiệm Thu Ngoại Thất", keyword: "nghiệm thu ngoại thất", slug: "nghiem-thu-ngoai-that-fc-ngan", status: "done" },
  { no: 3541, title: "Bảo Dưỡng Ngoại Thất", keyword: "bảo dưỡng ngoại thất", slug: "bao-duong-ngoai-that-fc-ngan", status: "done" },
  { no: 3542, title: "Bảo Hành Mặt Tiền", keyword: "bảo hành mặt tiền", slug: "bao-hanh-mat-tien-fc-ngan", status: "done" },
  { no: 3543, title: "Checklist Ngoại Thất Nhà", keyword: "checklist ngoại thất nhà", slug: "checklist-ngoai-that-nha-fc-ngan", status: "done" },
  { no: 3544, title: "Lỗi Thường Gặp Mặt Tiền", keyword: "lỗi thường gặp mặt tiền", slug: "loi-thuong-gap-mat-tien-fc-ngan", status: "done" },
  { no: 3545, title: "Cách Chọn Vật Liệu Mặt Tiền", keyword: "cách chọn vật liệu mặt tiền", slug: "cach-chon-vat-lieu-mat-tien-fc-ngan", status: "done" },
  { no: 3546, title: "Cách Chọn Cổng Rào", keyword: "cách chọn cổng rào", slug: "cach-chon-cong-rao-fc-ngan", status: "done" },
];
