/**
 * Lịch 100 từ khóa ngắn — batch 45 (#3947–#4046).
 * Cluster: phong cách kiến trúc, mặt bằng, mẫu nhà.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch45: ContentCalendarItem[] = [
  { no: 3947, title: "Nhà Phong Cách Hiện Đại", keyword: "nhà phong cách hiện đại", slug: "nha-phong-cach-hien-dai-st-ngan", status: "done" },
  { no: 3948, title: "Nhà Phong Cách Tối Giản", keyword: "nhà phong cách tối giản", slug: "nha-phong-cach-toi-gian-st-ngan", status: "done" },
  { no: 3949, title: "Nhà Phong Cách Scandinavian", keyword: "nhà phong cách scandinavian", slug: "nha-phong-cach-scandinavian-st-ngan", status: "done" },
  { no: 3950, title: "Nhà Phong Cách Industrial", keyword: "nhà phong cách industrial", slug: "nha-phong-cach-industrial-st-ngan", status: "done" },
  { no: 3951, title: "Nhà Phong Cách Japandi", keyword: "nhà phong cách japandi", slug: "nha-phong-cach-japandi-st-ngan", status: "done" },
  { no: 3952, title: "Nhà Phong Cách Đông Dương", keyword: "nhà phong cách đông dương", slug: "nha-phong-cach-dong-duong-st-ngan", status: "done" },
  { no: 3953, title: "Nhà Phong Cách Cổ Điển", keyword: "nhà phong cách cổ điển", slug: "nha-phong-cach-co-dien-st-ngan", status: "done" },
  { no: 3954, title: "Nhà Phong Cách Tân Cổ Điển", keyword: "nhà phong cách tân cổ điển", slug: "nha-phong-cach-tan-co-dien-st-ngan", status: "done" },
  { no: 3955, title: "Nhà Phong Cách Địa Trung Hải", keyword: "nhà phong cách địa trung hải", slug: "nha-phong-cach-dia-trung-hai-st-ngan", status: "done" },
  { no: 3956, title: "Nhà Phong Cách Tropical", keyword: "nhà phong cách tropical", slug: "nha-phong-cach-tropical-st-ngan", status: "done" },
  { no: 3957, title: "Nhà Phong Cách Farmhouse", keyword: "nhà phong cách farmhouse", slug: "nha-phong-cach-farmhouse-st-ngan", status: "done" },
  { no: 3958, title: "Nhà Phong Cách Luxury Modern", keyword: "nhà phong cách luxury modern", slug: "nha-phong-cach-luxury-modern-st-ngan", status: "done" },
  { no: 3959, title: "Mẫu Nhà Ống 3x10", keyword: "mẫu nhà ống 3x10", slug: "mau-nha-ong-3x10-st-ngan", status: "done" },
  { no: 3960, title: "Mẫu Nhà Ống 3x12", keyword: "mẫu nhà ống 3x12", slug: "mau-nha-ong-3x12-st-ngan", status: "done" },
  { no: 3961, title: "Mẫu Nhà Ống 4x12", keyword: "mẫu nhà ống 4x12", slug: "mau-nha-ong-4x12-st-ngan", status: "done" },
  { no: 3962, title: "Mẫu Nhà Ống 4x15", keyword: "mẫu nhà ống 4x15", slug: "mau-nha-ong-4x15-st-ngan", status: "done" },
  { no: 3963, title: "Mẫu Nhà Ống 4x16", keyword: "mẫu nhà ống 4x16", slug: "mau-nha-ong-4x16-st-ngan", status: "done" },
  { no: 3964, title: "Mẫu Nhà Ống 5x15", keyword: "mẫu nhà ống 5x15", slug: "mau-nha-ong-5x15-st-ngan", status: "done" },
  { no: 3965, title: "Mẫu Nhà Ống 5x18", keyword: "mẫu nhà ống 5x18", slug: "mau-nha-ong-5x18-st-ngan", status: "done" },
  { no: 3966, title: "Mẫu Nhà Ống 5x20", keyword: "mẫu nhà ống 5x20", slug: "mau-nha-ong-5x20-st-ngan", status: "done" },
  { no: 3967, title: "Mẫu Nhà Ống 6x15", keyword: "mẫu nhà ống 6x15", slug: "mau-nha-ong-6x15-st-ngan", status: "done" },
  { no: 3968, title: "Mẫu Nhà Ống 6x18", keyword: "mẫu nhà ống 6x18", slug: "mau-nha-ong-6x18-st-ngan", status: "done" },
  { no: 3969, title: "Mẫu Nhà Ống 6x20", keyword: "mẫu nhà ống 6x20", slug: "mau-nha-ong-6x20-st-ngan", status: "done" },
  { no: 3970, title: "Mẫu Nhà Lệch Tầng 4x12", keyword: "mẫu nhà lệch tầng 4x12", slug: "mau-nha-lech-tang-4x12-st-ngan", status: "done" },
  { no: 3971, title: "Mẫu Nhà Lệch Tầng 5x15", keyword: "mẫu nhà lệch tầng 5x15", slug: "mau-nha-lech-tang-5x15-st-ngan", status: "done" },
  { no: 3972, title: "Mẫu Nhà Có Giếng Trời", keyword: "mẫu nhà có giếng trời", slug: "mau-nha-co-gieng-troi-st-ngan", status: "done" },
  { no: 3973, title: "Mẫu Nhà Có Sân Vườn", keyword: "mẫu nhà có sân vườn", slug: "mau-nha-co-san-vuon-st-ngan", status: "done" },
  { no: 3974, title: "Mẫu Nhà Có Hồ Cá", keyword: "mẫu nhà có hồ cá", slug: "mau-nha-co-ho-ca-st-ngan", status: "done" },
  { no: 3975, title: "Mẫu Nhà Có Gác Lửng", keyword: "mẫu nhà có gác lửng", slug: "mau-nha-co-gac-lung-st-ngan", status: "done" },
  { no: 3976, title: "Mẫu Nhà Có Hầm Xe", keyword: "mẫu nhà có hầm xe", slug: "mau-nha-co-ham-xe-st-ngan", status: "done" },
  { no: 3977, title: "Mẫu Nhà 1 Trệt 1 Lầu", keyword: "mẫu nhà 1 trệt 1 lầu", slug: "mau-nha-1-tret-1-lau-st-ngan", status: "done" },
  { no: 3978, title: "Mẫu Nhà 1 Trệt 2 Lầu", keyword: "mẫu nhà 1 trệt 2 lầu", slug: "mau-nha-1-tret-2-lau-st-ngan", status: "done" },
  { no: 3979, title: "Mẫu Nhà 1 Trệt 3 Lầu", keyword: "mẫu nhà 1 trệt 3 lầu", slug: "mau-nha-1-tret-3-lau-st-ngan", status: "done" },
  { no: 3980, title: "Mẫu Nhà 1 Trệt 4 Lầu", keyword: "mẫu nhà 1 trệt 4 lầu", slug: "mau-nha-1-tret-4-lau-st-ngan", status: "done" },
  { no: 3981, title: "Mẫu Nhà Cấp 4 Mái Thái", keyword: "mẫu nhà cấp 4 mái thái", slug: "mau-nha-cap-4-mai-thai-st-ngan", status: "done" },
  { no: 3982, title: "Mẫu Nhà Cấp 4 Mái Nhật", keyword: "mẫu nhà cấp 4 mái nhật", slug: "mau-nha-cap-4-mai-nhat-st-ngan", status: "done" },
  { no: 3983, title: "Mẫu Nhà Cấp 4 Mái Bằng", keyword: "mẫu nhà cấp 4 mái bằng", slug: "mau-nha-cap-4-mai-bang-st-ngan", status: "done" },
  { no: 3984, title: "Mẫu Biệt Thự 1 Tầng", keyword: "mẫu biệt thự 1 tầng", slug: "mau-biet-thu-1-tang-st-ngan", status: "done" },
  { no: 3985, title: "Mẫu Biệt Thự 2 Tầng", keyword: "mẫu biệt thự 2 tầng", slug: "mau-biet-thu-2-tang-st-ngan", status: "done" },
  { no: 3986, title: "Mẫu Biệt Thự 3 Tầng", keyword: "mẫu biệt thự 3 tầng", slug: "mau-biet-thu-3-tang-st-ngan", status: "done" },
  { no: 3987, title: "Mặt Bằng Nhà Ống 3 Phòng Ngủ", keyword: "mặt bằng nhà ống 3 phòng ngủ", slug: "mat-bang-nha-ong-3-phong-ngu-st-ngan", status: "done" },
  { no: 3988, title: "Mặt Bằng Nhà Ống 4 Phòng Ngủ", keyword: "mặt bằng nhà ống 4 phòng ngủ", slug: "mat-bang-nha-ong-4-phong-ngu-st-ngan", status: "done" },
  { no: 3989, title: "Mặt Bằng Nhà Có Phòng Thờ", keyword: "mặt bằng nhà có phòng thờ", slug: "mat-bang-nha-co-phong-tho-st-ngan", status: "done" },
  { no: 3990, title: "Mặt Bằng Nhà Có Phòng Làm Việc", keyword: "mặt bằng nhà có phòng làm việc", slug: "mat-bang-nha-co-phong-lam-viec-st-ngan", status: "done" },
  { no: 3991, title: "Mặt Bằng Nhà Shop House", keyword: "mặt bằng nhà shop house", slug: "mat-bang-nha-shop-house-st-ngan", status: "done" },
  { no: 3992, title: "Bản Vẽ Nhà Phố Miễn Phí", keyword: "bản vẽ nhà phố miễn phí", slug: "ban-ve-nha-pho-mien-phi-st-ngan", status: "done" },
  { no: 3993, title: "Bản Vẽ Nhà Cấp 4 Miễn Phí", keyword: "bản vẽ nhà cấp 4 miễn phí", slug: "ban-ve-nha-cap-4-mien-phi-st-ngan", status: "done" },
  { no: 3994, title: "File CAD Nhà Phố", keyword: "file cad nhà phố", slug: "file-cad-nha-pho-st-ngan", status: "done" },
  { no: 3995, title: "File Sketchup Nhà Phố", keyword: "file sketchup nhà phố", slug: "file-sketchup-nha-pho-st-ngan", status: "done" },
  { no: 3996, title: "Phối Cảnh 3D Nhà Phố", keyword: "phối cảnh 3d nhà phố", slug: "phoi-canh-3d-nha-pho-st-ngan", status: "done" },
  { no: 3997, title: "Phối Cảnh Nội Thất 3D", keyword: "phối cảnh nội thất 3d", slug: "phoi-canh-noi-that-3d-st-ngan", status: "done" },
  { no: 3998, title: "Tour Ảo Nhà Mẫu", keyword: "tour ảo nhà mẫu", slug: "tour-ao-nha-mau-st-ngan", status: "done" },
  { no: 3999, title: "Nhà Mẫu Thực Tế", keyword: "nhà mẫu thực tế", slug: "nha-mau-thuc-te-st-ngan", status: "done" },
  { no: 4000, title: "Ý Tưởng Thiết Kế Nhà Hẹp", keyword: "ý tưởng thiết kế nhà hẹp", slug: "y-tuong-thiet-ke-nha-hep-st-ngan", status: "done" },
  { no: 4001, title: "Ý Tưởng Thiết Kế Nhà Nhỏ", keyword: "ý tưởng thiết kế nhà nhỏ", slug: "y-tuong-thiet-ke-nha-nho-st-ngan", status: "done" },
  { no: 4002, title: "Ý Tưởng Tối Ưu Ánh Sáng", keyword: "ý tưởng tối ưu ánh sáng", slug: "y-tuong-toi-uu-anh-sang-st-ngan", status: "done" },
  { no: 4003, title: "Ý Tưởng Tối Ưu Thông Gió", keyword: "ý tưởng tối ưu thông gió", slug: "y-tuong-toi-uu-thong-gio-st-ngan", status: "done" },
  { no: 4004, title: "Ý Tưởng Tối Ưu Công Năng", keyword: "ý tưởng tối ưu công năng", slug: "y-tuong-toi-uu-cong-nang-st-ngan", status: "done" },
  { no: 4005, title: "Thiết Kế Nhà Theo Tuổi", keyword: "thiết kế nhà theo tuổi", slug: "thiet-ke-nha-theo-tuoi-st-ngan", status: "done" },
  { no: 4006, title: "Thiết Kế Nhà Theo Mệnh", keyword: "thiết kế nhà theo mệnh", slug: "thiet-ke-nha-theo-menh-st-ngan", status: "done" },
  { no: 4007, title: "Thiết Kế Nhà Mệnh Kim", keyword: "thiết kế nhà mệnh kim", slug: "thiet-ke-nha-menh-kim-st-ngan", status: "done" },
  { no: 4008, title: "Thiết Kế Nhà Mệnh Mộc", keyword: "thiết kế nhà mệnh mộc", slug: "thiet-ke-nha-menh-moc-st-ngan", status: "done" },
  { no: 4009, title: "Thiết Kế Nhà Mệnh Thủy", keyword: "thiết kế nhà mệnh thủy", slug: "thiet-ke-nha-menh-thuy-st-ngan", status: "done" },
  { no: 4010, title: "Thiết Kế Nhà Mệnh Hỏa", keyword: "thiết kế nhà mệnh hỏa", slug: "thiet-ke-nha-menh-hoa-st-ngan", status: "done" },
  { no: 4011, title: "Thiết Kế Nhà Mệnh Thổ", keyword: "thiết kế nhà mệnh thổ", slug: "thiet-ke-nha-menh-tho-st-ngan", status: "done" },
  { no: 4012, title: "Tỷ Lệ Vàng Trong Kiến Trúc", keyword: "tỷ lệ vàng trong kiến trúc", slug: "ty-le-vang-trong-kien-truc-st-ngan", status: "done" },
  { no: 4013, title: "Module Không Gian Nhà Phố", keyword: "module không gian nhà phố", slug: "module-khong-gian-nha-pho-st-ngan", status: "done" },
  { no: 4014, title: "Zoning Công Năng Nhà Ở", keyword: "zoning công năng nhà ở", slug: "zoning-cong-nang-nha-o-st-ngan", status: "done" },
  { no: 4015, title: "Circulation Trong Nhà Phố", keyword: "circulation trong nhà phố", slug: "circulation-trong-nha-pho-st-ngan", status: "done" },
  { no: 4016, title: "Privacy Trong Nhà Ống", keyword: "privacy trong nhà ống", slug: "privacy-trong-nha-ong-st-ngan", status: "done" },
  { no: 4017, title: "Open Plan Nhà Phố", keyword: "open plan nhà phố", slug: "open-plan-nha-pho-st-ngan", status: "done" },
  { no: 4018, title: "Semi Open Plan Nhà", keyword: "semi open plan nhà", slug: "semi-open-plan-nha-st-ngan", status: "done" },
  { no: 4019, title: "Double Height Phòng Khách", keyword: "double height phòng khách", slug: "double-height-phong-khach-st-ngan", status: "done" },
  { no: 4020, title: "Void Giếng Trời Nhà Phố", keyword: "void giếng trời nhà phố", slug: "void-gieng-troi-nha-pho-st-ngan", status: "done" },
  { no: 4021, title: "Split Level Nhà Phố", keyword: "split level nhà phố", slug: "split-level-nha-pho-st-ngan", status: "done" },
  { no: 4022, title: "Courtyard House Hiện Đại", keyword: "courtyard house hiện đại", slug: "courtyard-house-hien-dai-st-ngan", status: "done" },
  { no: 4023, title: "Narrow House Design", keyword: "narrow house design", slug: "narrow-house-design-st-ngan", status: "done" },
  { no: 4024, title: "Tiny House Việt Nam", keyword: "tiny house việt nam", slug: "tiny-house-viet-nam-st-ngan", status: "done" },
  { no: 4025, title: "Container House Việt Nam", keyword: "container house việt nam", slug: "container-house-viet-nam-st-ngan", status: "done" },
  { no: 4026, title: "Prefab House Việt Nam", keyword: "prefab house việt nam", slug: "prefab-house-viet-nam-st-ngan", status: "done" },
  { no: 4027, title: "Báo Giá Thiết Kế Kiến Trúc", keyword: "báo giá thiết kế kiến trúc", slug: "bao-gia-thiet-ke-kien-truc-st-ngan", status: "done" },
  { no: 4028, title: "Báo Giá Thiết Kế Nội Thất", keyword: "báo giá thiết kế nội thất", slug: "bao-gia-thiet-ke-noi-that-st-ngan", status: "done" },
  { no: 4029, title: "Gói Thiết Kế Cơ Bản", keyword: "gói thiết kế cơ bản", slug: "goi-thiet-ke-co-ban-st-ngan", status: "done" },
  { no: 4030, title: "Gói Thiết Kế Chi Tiết", keyword: "gói thiết kế chi tiết", slug: "goi-thiet-ke-chi-tiet-st-ngan", status: "done" },
  { no: 4031, title: "Gói Thiết Kế Trọn Bộ", keyword: "gói thiết kế trọn bộ", slug: "goi-thiet-ke-tron-bo-st-ngan", status: "done" },
  { no: 4032, title: "Hồ Sơ Thiết Kế Xây Dựng", keyword: "hồ sơ thiết kế xây dựng", slug: "ho-so-thiet-ke-xay-dung-st-ngan", status: "done" },
  { no: 4033, title: "Bản Vẽ Kết Cấu Nhà Phố", keyword: "bản vẽ kết cấu nhà phố", slug: "ban-ve-ket-cau-nha-pho-st-ngan", status: "done" },
  { no: 4034, title: "Bản Vẽ Kiến Trúc Nhà Phố", keyword: "bản vẽ kiến trúc nhà phố", slug: "ban-ve-kien-truc-nha-pho-st-ngan", status: "done" },
  { no: 4035, title: "Bản Vẽ Điện Nước Nhà", keyword: "bản vẽ điện nước nhà", slug: "ban-ve-dien-nuoc-nha-st-ngan", status: "done" },
  { no: 4036, title: "Triển Khai Bản Vẽ Thi Công", keyword: "triển khai bản vẽ thi công", slug: "trien-khai-ban-ve-thi-cong-st-ngan", status: "done" },
  { no: 4037, title: "Chỉnh Sửa Bản Vẽ Thiết Kế", keyword: "chỉnh sửa bản vẽ thiết kế", slug: "chinh-sua-ban-ve-thiet-ke-st-ngan", status: "done" },
  { no: 4038, title: "Xu Hướng Kiến Trúc 2026", keyword: "xu hướng kiến trúc 2026", slug: "xu-huong-kien-truc-2026-st-ngan", status: "done" },
  { no: 4039, title: "Xu Hướng Mặt Bằng 2026", keyword: "xu hướng mặt bằng 2026", slug: "xu-huong-mat-bang-2026-st-ngan", status: "done" },
  { no: 4040, title: "Xu Hướng Mẫu Nhà 2026", keyword: "xu hướng mẫu nhà 2026", slug: "xu-huong-mau-nha-2026-st-ngan", status: "done" },
  { no: 4041, title: "Inspiration Nhà Phố Đẹp", keyword: "inspiration nhà phố đẹp", slug: "inspiration-nha-pho-dep-st-ngan", status: "done" },
  { no: 4042, title: "Moodboard Thiết Kế Nhà", keyword: "moodboard thiết kế nhà", slug: "moodboard-thiet-ke-nha-st-ngan", status: "done" },
  { no: 4043, title: "Concept Design Nhà Phố", keyword: "concept design nhà phố", slug: "concept-design-nha-pho-st-ngan", status: "done" },
  { no: 4044, title: "Schematic Design Nhà", keyword: "schematic design nhà", slug: "schematic-design-nha-st-ngan", status: "done" },
  { no: 4045, title: "Design Development Nhà", keyword: "design development nhà", slug: "design-development-nha-st-ngan", status: "done" },
  { no: 4046, title: "Chủ Đề Mở Rộng 45 1", keyword: "chủ đề mở rộng 45 1", slug: "chu-de-mo-rong-45-1-ngan", status: "done" },
];
