/**
 * Lịch 100 từ khóa ngắn — batch 30 (#2447–#2546).
 * Cluster: chi phí, đơn giá, vật tư, tối ưu ngân sách.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch30: ContentCalendarItem[] = [
  { no: 2447, title: "Đơn Giá Xây Nhà 2026", keyword: "đơn giá xây nhà 2026", slug: "don-gia-xay-nha-2026-ngan", status: "done" },
  { no: 2448, title: "Đơn Giá Cải Tạo 2026", keyword: "đơn giá cải tạo 2026", slug: "don-gia-cai-tao-2026-ngan", status: "done" },
  { no: 2449, title: "Đơn Giá Phần Thô 2026", keyword: "đơn giá phần thô 2026", slug: "don-gia-phan-tho-2026-ngan", status: "done" },
  { no: 2450, title: "Đơn Giá Hoàn Thiện 2026", keyword: "đơn giá hoàn thiện 2026", slug: "don-gia-hoan-thien-2026-ngan", status: "done" },
  { no: 2451, title: "Giá Nhân Công Xây Nhà", keyword: "giá nhân công xây nhà", slug: "gia-nhan-cong-xay-nha-ngan", status: "done" },
  { no: 2452, title: "Giá Nhân Công Thợ Hồ", keyword: "giá nhân công thợ hồ", slug: "gia-nhan-cong-tho-ho-ngan", status: "done" },
  { no: 2453, title: "Giá Nhân Công Thợ Điện", keyword: "giá nhân công thợ điện", slug: "gia-nhan-cong-tho-dien-ngan", status: "done" },
  { no: 2454, title: "Giá Nhân Công Thợ Nước", keyword: "giá nhân công thợ nước", slug: "gia-nhan-cong-tho-nuoc-ngan", status: "done" },
  { no: 2455, title: "Giá Nhân Công Thợ Sơn", keyword: "giá nhân công thợ sơn", slug: "gia-nhan-cong-tho-son-ngan", status: "done" },
  { no: 2456, title: "Giá Nhân Công Thợ Ốp Lát", keyword: "giá nhân công thợ ốp lát", slug: "gia-nhan-cong-tho-op-lat-ngan", status: "done" },
  { no: 2457, title: "Giá Xi Măng Xây Nhà", keyword: "giá xi măng xây nhà", slug: "gia-xi-mang-xay-nha-ngan", status: "done" },
  { no: 2458, title: "Giá Thép Xây Nhà", keyword: "giá thép xây nhà", slug: "gia-thep-xay-nha-ngan", status: "done" },
  { no: 2459, title: "Giá Gạch Xây Nhà", keyword: "giá gạch xây nhà", slug: "gia-gach-xay-nha-ngan", status: "done" },
  { no: 2460, title: "Giá Cát Đá Xây Nhà", keyword: "giá cát đá xây nhà", slug: "gia-cat-da-xay-nha-ngan", status: "done" },
  { no: 2461, title: "Giá Bê Tông Tươi", keyword: "giá bê tông tươi", slug: "gia-be-tong-tuoi-ngan", status: "done" },
  { no: 2462, title: "Giá Tôn Lợp Mái", keyword: "giá tôn lợp mái", slug: "gia-ton-lop-mai-ngan", status: "done" },
  { no: 2463, title: "Giá Ngói Lợp Mái", keyword: "giá ngói lợp mái", slug: "gia-ngoi-lop-mai-ngan", status: "done" },
  { no: 2464, title: "Giá Sơn Nhà Phố", keyword: "giá sơn nhà phố", slug: "gia-son-nha-pho-ngan", status: "done" },
  { no: 2465, title: "Giá Gạch Ốp Lát", keyword: "giá gạch ốp lát", slug: "gia-gach-op-lat-ngan", status: "done" },
  { no: 2466, title: "Giá Trần Thạch Cao", keyword: "giá trần thạch cao", slug: "gia-tran-thach-cao-ngan", status: "done" },
  { no: 2467, title: "Giá Cửa Nhôm Kính", keyword: "giá cửa nhôm kính", slug: "gia-cua-nhom-kinh-ngan", status: "done" },
  { no: 2468, title: "Giá Cửa Gỗ Công Nghiệp", keyword: "giá cửa gỗ công nghiệp", slug: "gia-cua-go-cong-nghiep-ngan", status: "done" },
  { no: 2469, title: "Giá Lan Can Inox", keyword: "giá lan can inox", slug: "gia-lan-can-inox-ngan", status: "done" },
  { no: 2470, title: "Giá Lan Can Kính", keyword: "giá lan can kính", slug: "gia-lan-can-kinh-ngan", status: "done" },
  { no: 2471, title: "Giá Cầu Thang Gỗ", keyword: "giá cầu thang gỗ", slug: "gia-cau-thang-go-ngan", status: "done" },
  { no: 2472, title: "Giá Cầu Thang Sắt", keyword: "giá cầu thang sắt", slug: "gia-cau-thang-sat-ngan", status: "done" },
  { no: 2473, title: "Giá Sàn Gỗ Công Nghiệp", keyword: "giá sàn gỗ công nghiệp", slug: "gia-san-go-cong-nghiep-ngan", status: "done" },
  { no: 2474, title: "Giá Sàn Nhựa SPC", keyword: "giá sàn nhựa spc", slug: "gia-san-nhua-spc-ngan", status: "done" },
  { no: 2475, title: "Giá Tủ Bếp Acrylic", keyword: "giá tủ bếp acrylic", slug: "gia-tu-bep-acrylic-ngan", status: "done" },
  { no: 2476, title: "Giá Tủ Bếp Melamine", keyword: "giá tủ bếp melamine", slug: "gia-tu-bep-melamine-ngan", status: "done" },
  { no: 2477, title: "Giá Bồn Cầu Inax", keyword: "giá bồn cầu inax", slug: "gia-bon-cau-inax-ngan", status: "done" },
  { no: 2478, title: "Giá Sen Tắm Toto", keyword: "giá sen tắm toto", slug: "gia-sen-tam-toto-ngan", status: "done" },
  { no: 2479, title: "Giá Máy Nước Nóng", keyword: "giá máy nước nóng", slug: "gia-may-nuoc-nong-ngan", status: "done" },
  { no: 2480, title: "Giá Bơm Nước Gia Đình", keyword: "giá bơm nước gia đình", slug: "gia-bom-nuoc-gia-dinh-ngan", status: "done" },
  { no: 2481, title: "Giá Hệ Thống Điện Nhà", keyword: "giá hệ thống điện nhà", slug: "gia-he-thong-dien-nha-ngan", status: "done" },
  { no: 2482, title: "Giá Hệ Thống Nước Nhà", keyword: "giá hệ thống nước nhà", slug: "gia-he-thong-nuoc-nha-ngan", status: "done" },
  { no: 2483, title: "Chi Phí Xin Phép Xây", keyword: "chi phí xin phép xây", slug: "chi-phi-xin-phep-xay-ngan", status: "done" },
  { no: 2484, title: "Chi Phí Giám Sát Xây", keyword: "chi phí giám sát xây", slug: "chi-phi-giam-sat-xay-ngan", status: "done" },
  { no: 2485, title: "Chi Phí Thiết Kế Nhà", keyword: "chi phí thiết kế nhà", slug: "chi-phi-thiet-ke-nha-ngan", status: "done" },
  { no: 2486, title: "Chi Phí Khảo Sát Địa Chất", keyword: "chi phí khảo sát địa chất", slug: "chi-phi-khao-sat-dia-chat-ngan", status: "done" },
  { no: 2487, title: "Chi Phí Ép Cọc Nhà Phố", keyword: "chi phí ép cọc nhà phố", slug: "chi-phi-ep-coc-nha-pho-ngan", status: "done" },
  { no: 2488, title: "Chi Phí Phá Dỡ Nhà Cũ", keyword: "chi phí phá dỡ nhà cũ", slug: "chi-phi-pha-do-nha-cu-ngan", status: "done" },
  { no: 2489, title: "Chi Phí Vận Chuyển Phế Thải", keyword: "chi phí vận chuyển phế thải", slug: "chi-phi-van-chuyen-phe-thai-ngan", status: "done" },
  { no: 2490, title: "Chi Phí Chống Thấm Mái", keyword: "chi phí chống thấm mái", slug: "chi-phi-chong-tham-mai-ngan", status: "done" },
  { no: 2491, title: "Chi Phí Chống Thấm WC", keyword: "chi phí chống thấm wc", slug: "chi-phi-chong-tham-wc-ngan", status: "done" },
  { no: 2492, title: "Chi Phí Cách Nhiệt Mái", keyword: "chi phí cách nhiệt mái", slug: "chi-phi-cach-nhiet-mai-ngan", status: "done" },
  { no: 2493, title: "Chi Phí Cách Âm Phòng", keyword: "chi phí cách âm phòng", slug: "chi-phi-cach-am-phong-ngan", status: "done" },
  { no: 2494, title: "Tối Ưu Ngân Sách Xây Nhà", keyword: "tối ưu ngân sách xây nhà", slug: "toi-uu-ngan-sach-xay-nha-ngan", status: "done" },
  { no: 2495, title: "Cắt Giảm Chi Phí Xây Nhà", keyword: "cắt giảm chi phí xây nhà", slug: "cat-giam-chi-phi-xay-nha-ngan", status: "done" },
  { no: 2496, title: "Tiết Kiệm Chi Phí Cải Tạo", keyword: "tiết kiệm chi phí cải tạo", slug: "tiet-kiem-chi-phi-cai-tao-ngan", status: "done" },
  { no: 2497, title: "So Sánh Giá Thầu Xây", keyword: "so sánh giá thầu xây", slug: "so-sanh-gia-thau-xay-ngan", status: "done" },
  { no: 2498, title: "Báo Giá Ẩn Xây Nhà", keyword: "báo giá ẩn xây nhà", slug: "bao-gia-an-xay-nha-ngan", status: "done" },
  { no: 2499, title: "Phí Phát Sinh Xây Nhà", keyword: "phí phát sinh xây nhà", slug: "phi-phat-sinh-xay-nha-ngan", status: "done" },
  { no: 2500, title: "Dự Phòng Ngân Sách Xây", keyword: "dự phòng ngân sách xây", slug: "du-phong-ngan-sach-xay-ngan", status: "done" },
  { no: 2501, title: "Tỷ Lệ Phát Sinh Hợp Lý", keyword: "tỷ lệ phát sinh hợp lý", slug: "ty-le-phat-sinh-hop-ly-ngan", status: "done" },
  { no: 2502, title: "Giá Xây Nhà 40m2", keyword: "giá xây nhà 40m2", slug: "gia-xay-nha-40m2-ngan", status: "done" },
  { no: 2503, title: "Giá Xây Nhà 50m2", keyword: "giá xây nhà 50m2", slug: "gia-xay-nha-50m2-ngan", status: "done" },
  { no: 2504, title: "Giá Xây Nhà 60m2", keyword: "giá xây nhà 60m2", slug: "gia-xay-nha-60m2-ngan", status: "done" },
  { no: 2505, title: "Giá Xây Nhà 80m2", keyword: "giá xây nhà 80m2", slug: "gia-xay-nha-80m2-ngan", status: "done" },
  { no: 2506, title: "Giá Xây Nhà 100m2", keyword: "giá xây nhà 100m2", slug: "gia-xay-nha-100m2-ngan", status: "done" },
  { no: 2507, title: "Giá Xây Nhà 120m2", keyword: "giá xây nhà 120m2", slug: "gia-xay-nha-120m2-ngan", status: "done" },
  { no: 2508, title: "Giá Xây Nhà 150m2", keyword: "giá xây nhà 150m2", slug: "gia-xay-nha-150m2-ngan", status: "done" },
  { no: 2509, title: "Giá Xây Nhà 200m2", keyword: "giá xây nhà 200m2", slug: "gia-xay-nha-200m2-ngan", status: "done" },
  { no: 2510, title: "Giá Xây 1 Tầng", keyword: "giá xây 1 tầng", slug: "gia-xay-1-tang-ngan", status: "done" },
  { no: 2511, title: "Giá Xây 2 Tầng", keyword: "giá xây 2 tầng", slug: "gia-xay-2-tang-ngan", status: "done" },
  { no: 2512, title: "Giá Xây 3 Tầng", keyword: "giá xây 3 tầng", slug: "gia-xay-3-tang-ngan", status: "done" },
  { no: 2513, title: "Giá Xây 4 Tầng", keyword: "giá xây 4 tầng", slug: "gia-xay-4-tang-ngan", status: "done" },
  { no: 2514, title: "Giá Xây 5 Tầng", keyword: "giá xây 5 tầng", slug: "gia-xay-5-tang-ngan", status: "done" },
  { no: 2515, title: "Giá Nâng Thêm 1 Tầng", keyword: "giá nâng thêm 1 tầng", slug: "gia-nang-them-1-tang-ngan", status: "done" },
  { no: 2516, title: "Giá Sửa Mái Tôn", keyword: "giá sửa mái tôn", slug: "gia-sua-mai-ton-ngan", status: "done" },
  { no: 2517, title: "Giá Sửa Mái Ngói", keyword: "giá sửa mái ngói", slug: "gia-sua-mai-ngoi-ngan", status: "done" },
  { no: 2518, title: "Giá Sơn Lại Nhà", keyword: "giá sơn lại nhà", slug: "gia-son-lai-nha-ngan", status: "done" },
  { no: 2519, title: "Giá Ốp Lát Lại Nhà", keyword: "giá ốp lát lại nhà", slug: "gia-op-lat-lai-nha-ngan", status: "done" },
  { no: 2520, title: "Giá Thay Trần Thạch Cao", keyword: "giá thay trần thạch cao", slug: "gia-thay-tran-thach-cao-ngan", status: "done" },
  { no: 2521, title: "Giá Làm Mới Nhà Cũ", keyword: "giá làm mới nhà cũ", slug: "gia-lam-moi-nha-cu-ngan", status: "done" },
  { no: 2522, title: "Bảng Giá Vật Tư Xây 2026", keyword: "bảng giá vật tư xây 2026", slug: "bang-gia-vat-tu-xay-2026-ngan", status: "done" },
  { no: 2523, title: "Bảng Giá Nhân Công 2026", keyword: "bảng giá nhân công 2026", slug: "bang-gia-nhan-cong-2026-ngan", status: "done" },
  { no: 2524, title: "Bảng Giá Trọn Gói 2026", keyword: "bảng giá trọn gói 2026", slug: "bang-gia-tron-goi-2026-ngan", status: "done" },
  { no: 2525, title: "Ước Tính Chi Phí Xây Online", keyword: "ước tính chi phí xây online", slug: "uoc-tinh-chi-phi-xay-online-ngan", status: "done" },
  { no: 2526, title: "Công Thức Tính Giá Xây m2", keyword: "công thức tính giá xây m2", slug: "cong-thuc-tinh-gia-xay-m2-ngan", status: "done" },
  { no: 2527, title: "Cách Đọc Báo Giá Xây", keyword: "cách đọc báo giá xây", slug: "cach-doc-bao-gia-xay-ngan", status: "done" },
  { no: 2528, title: "Checklist So Báo Giá Thầu", keyword: "checklist so báo giá thầu", slug: "checklist-so-bao-gia-thau-ngan", status: "done" },
  { no: 2529, title: "Ẩn Phí Trong Báo Giá Xây", keyword: "ẩn phí trong báo giá xây", slug: "an-phi-trong-bao-gia-xay-ngan", status: "done" },
  { no: 2530, title: "Giá Xây Nhà Kinh Tế", keyword: "giá xây nhà kinh tế", slug: "gia-xay-nha-kinh-te-ngan", status: "done" },
  { no: 2531, title: "Giá Xây Nhà Trung Cấp", keyword: "giá xây nhà trung cấp", slug: "gia-xay-nha-trung-cap-ngan", status: "done" },
  { no: 2532, title: "Giá Xây Nhà Cao Cấp", keyword: "giá xây nhà cao cấp", slug: "gia-xay-nha-cao-cap-ngan", status: "done" },
  { no: 2533, title: "Giá Xây Nhà Luxury", keyword: "giá xây nhà luxury", slug: "gia-xay-nha-luxury-ngan", status: "done" },
  { no: 2534, title: "Chi Phí Nội Thất Cơ Bản", keyword: "chi phí nội thất cơ bản", slug: "chi-phi-noi-that-co-ban-ngan", status: "done" },
  { no: 2535, title: "Chi Phí Nội Thất Cao Cấp", keyword: "chi phí nội thất cao cấp", slug: "chi-phi-noi-that-cao-cap-ngan", status: "done" },
  { no: 2536, title: "Chi Phí Smart Home Cơ Bản", keyword: "chi phí smart home cơ bản", slug: "chi-phi-smart-home-co-ban-ngan", status: "done" },
  { no: 2537, title: "ROI Cải Tạo Nhà Phố", keyword: "roi cải tạo nhà phố", slug: "roi-cai-tao-nha-pho-ngan", status: "done" },
  { no: 2538, title: "ROI Xây Nhà Cho Thuê", keyword: "roi xây nhà cho thuê", slug: "roi-xay-nha-cho-thue-ngan", status: "done" },
  { no: 2539, title: "Vay Ngân Hàng Xây Nhà", keyword: "vay ngân hàng xây nhà", slug: "vay-ngan-hang-xay-nha-ngan", status: "done" },
  { no: 2540, title: "Lãi Suất Vay Xây Nhà", keyword: "lãi suất vay xây nhà", slug: "lai-suat-vay-xay-nha-ngan", status: "done" },
  { no: 2541, title: "Giải Ngân Theo Tiến Độ Xây", keyword: "giải ngân theo tiến độ xây", slug: "giai-ngan-theo-tien-do-xay-ngan", status: "done" },
  { no: 2542, title: "Thanh Toán Theo Đợt Xây", keyword: "thanh toán theo đợt xây", slug: "thanh-toan-theo-dot-xay-ngan", status: "done" },
  { no: 2543, title: "Giữ Lại Bảo Hành Xây", keyword: "giữ lại bảo hành xây", slug: "giu-lai-bao-hanh-xay-ngan", status: "done" },
  { no: 2544, title: "Tỷ Lệ Tạm Ứng Xây Nhà", keyword: "tỷ lệ tạm ứng xây nhà", slug: "ty-le-tam-ung-xay-nha-ngan", status: "done" },
  { no: 2545, title: "Chi Phí Bảo Trì Nhà Hàng Năm", keyword: "chi phí bảo trì nhà hàng năm", slug: "chi-phi-bao-tri-nha-hang-nam-ngan", status: "done" },
  { no: 2546, title: "Quỹ Bảo Trì Nhà Phố", keyword: "quỹ bảo trì nhà phố", slug: "quy-bao-tri-nha-pho-ngan", status: "done" },
];
