/**
 * Lịch 100 từ khóa ngắn — batch 58 (#5247–#5346).
 * Cluster: phong thủy, hướng nhà, tuổi xây.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch58: ContentCalendarItem[] = [
  { no: 5247, title: "Hướng Nhà Đông Tốt Không", keyword: "hướng nhà đông tốt không", slug: "huong-nha-dong-tot-khong-pt-ngan", status: "done" },
  { no: 5248, title: "Hướng Nhà Tây Tốt Không", keyword: "hướng nhà tây tốt không", slug: "huong-nha-tay-tot-khong-pt-ngan", status: "done" },
  { no: 5249, title: "Hướng Nhà Nam Tốt Không", keyword: "hướng nhà nam tốt không", slug: "huong-nha-nam-tot-khong-pt-ngan", status: "done" },
  { no: 5250, title: "Hướng Nhà Bắc Tốt Không", keyword: "hướng nhà bắc tốt không", slug: "huong-nha-bac-tot-khong-pt-ngan", status: "done" },
  { no: 5251, title: "Hướng Đông Nam Nhà Phố", keyword: "hướng đông nam nhà phố", slug: "huong-dong-nam-nha-pho-pt-ngan", status: "done" },
  { no: 5252, title: "Hướng Tây Nam Nhà Phố", keyword: "hướng tây nam nhà phố", slug: "huong-tay-nam-nha-pho-pt-ngan", status: "done" },
  { no: 5253, title: "Hướng Đông Bắc Nhà Phố", keyword: "hướng đông bắc nhà phố", slug: "huong-dong-bac-nha-pho-pt-ngan", status: "done" },
  { no: 5254, title: "Hướng Tây Bắc Nhà Phố", keyword: "hướng tây bắc nhà phố", slug: "huong-tay-bac-nha-pho-pt-ngan", status: "done" },
  { no: 5255, title: "Chọn Hướng Nhà Theo Tuổi", keyword: "chọn hướng nhà theo tuổi", slug: "chon-huong-nha-theo-tuoi-pt-ngan", status: "done" },
  { no: 5256, title: "Hướng Nhà Tuổi Tý", keyword: "hướng nhà tuổi tý", slug: "huong-nha-tuoi-ty-pt-ngan", status: "done" },
  { no: 5257, title: "Hướng Nhà Tuổi Sửu", keyword: "hướng nhà tuổi sửu", slug: "huong-nha-tuoi-suu-pt-ngan", status: "done" },
  { no: 5258, title: "Hướng Nhà Tuổi Dần", keyword: "hướng nhà tuổi dần", slug: "huong-nha-tuoi-dan-pt-ngan", status: "done" },
  { no: 5259, title: "Hướng Nhà Tuổi Mão", keyword: "hướng nhà tuổi mão", slug: "huong-nha-tuoi-mao-pt-ngan", status: "done" },
  { no: 5260, title: "Hướng Nhà Tuổi Thìn", keyword: "hướng nhà tuổi thìn", slug: "huong-nha-tuoi-thin-pt-ngan", status: "done" },
  { no: 5261, title: "Hướng Nhà Tuổi Tỵ", keyword: "hướng nhà tuổi tỵ", slug: "huong-nha-tuoi-ty-ran-pt-ngan", status: "done" },
  { no: 5262, title: "Hướng Nhà Tuổi Ngọ", keyword: "hướng nhà tuổi ngọ", slug: "huong-nha-tuoi-ngo-pt-ngan", status: "done" },
  { no: 5263, title: "Hướng Nhà Tuổi Mùi", keyword: "hướng nhà tuổi mùi", slug: "huong-nha-tuoi-mui-pt-ngan", status: "done" },
  { no: 5264, title: "Hướng Nhà Tuổi Thân", keyword: "hướng nhà tuổi thân", slug: "huong-nha-tuoi-than-pt-ngan", status: "done" },
  { no: 5265, title: "Hướng Nhà Tuổi Dậu", keyword: "hướng nhà tuổi dậu", slug: "huong-nha-tuoi-dau-pt-ngan", status: "done" },
  { no: 5266, title: "Hướng Nhà Tuổi Tuất", keyword: "hướng nhà tuổi tuất", slug: "huong-nha-tuoi-tuat-pt-ngan", status: "done" },
  { no: 5267, title: "Hướng Nhà Tuổi Hợi", keyword: "hướng nhà tuổi hợi", slug: "huong-nha-tuoi-hoi-pt-ngan", status: "done" },
  { no: 5268, title: "Năm Xây Nhà 2026", keyword: "năm xây nhà 2026", slug: "nam-xay-nha-2026-pt-ngan", status: "done" },
  { no: 5269, title: "Tuổi Xây Nhà 2026", keyword: "tuổi xây nhà 2026", slug: "tuoi-xay-nha-2026-pt-ngan", status: "done" },
  { no: 5270, title: "Tuổi Phạm Thái Tuế 2026", keyword: "tuổi phạm thái tuế 2026", slug: "tuoi-pham-thai-tue-2026-pt-ngan", status: "done" },
  { no: 5271, title: "Cải Tạo Có Phạm Tuổi Không", keyword: "cải tạo có phạm tuổi không", slug: "cai-tao-co-pham-tuoi-khong-pt-ngan", status: "done" },
  { no: 5272, title: "Mượn Tuổi Xây Nhà", keyword: "mượn tuổi xây nhà", slug: "muon-tuoi-xay-nha-pt-ngan", status: "done" },
  { no: 5273, title: "Cách Mượn Tuổi Xây", keyword: "cách mượn tuổi xây", slug: "cach-muon-tuoi-xay-pt-ngan", status: "done" },
  { no: 5274, title: "Ngày Động Thổ Tốt", keyword: "ngày động thổ tốt", slug: "ngay-dong-tho-tot-pt-ngan", status: "done" },
  { no: 5275, title: "Ngày Đổ Móng Tốt", keyword: "ngày đổ móng tốt", slug: "ngay-do-mong-tot-pt-ngan", status: "done" },
  { no: 5276, title: "Ngày Lợp Mái Tốt", keyword: "ngày lợp mái tốt", slug: "ngay-lop-mai-tot-pt-ngan", status: "done" },
  { no: 5277, title: "Ngày Nhập Trạch Tốt", keyword: "ngày nhập trạch tốt", slug: "ngay-nhap-trach-tot-pt-ngan", status: "done" },
  { no: 5278, title: "Lễ Động Thổ Xây Nhà", keyword: "lễ động thổ xây nhà", slug: "le-dong-tho-xay-nha-pt-ngan", status: "done" },
  { no: 5279, title: "Lễ Cất Nóc Xây Nhà", keyword: "lễ cất nóc xây nhà", slug: "le-cat-noc-xay-nha-pt-ngan", status: "done" },
  { no: 5280, title: "Lễ Nhập Trạch Nhà Mới", keyword: "lễ nhập trạch nhà mới", slug: "le-nhap-trach-nha-moi-pt-ngan", status: "done" },
  { no: 5281, title: "Bài Trí Phòng Thờ Phong Thủy", keyword: "bài trí phòng thờ phong thủy", slug: "bai-tri-phong-tho-phong-thuy-pt-ngan", status: "done" },
  { no: 5282, title: "Hướng Bàn Thờ Đúng", keyword: "hướng bàn thờ đúng", slug: "huong-ban-tho-dung-pt-ngan", status: "done" },
  { no: 5283, title: "Vị Trí Bếp Phong Thủy PT", keyword: "vị trí bếp phong thủy", slug: "vi-tri-bep-phong-thuy-pt-ngan", status: "done" },
  { no: 5284, title: "Bếp Không Đối Cửa", keyword: "bếp không đối cửa", slug: "bep-khong-doi-cua-pt-ngan", status: "done" },
  { no: 5285, title: "WC Không Đối Cửa Chính", keyword: "wc không đối cửa chính", slug: "wc-khong-doi-cua-chinh-pt-ngan", status: "done" },
  { no: 5286, title: "Giường Ngủ Phong Thủy", keyword: "giường ngủ phong thủy", slug: "giuong-ngu-phong-thuy-pt-ngan", status: "done" },
  { no: 5287, title: "Cửa Chính Phong Thủy PT", keyword: "cửa chính phong thủy", slug: "cua-chinh-phong-thuy-pt-ngan", status: "done" },
  { no: 5288, title: "Cầu Thang Phong Thủy", keyword: "cầu thang phong thủy", slug: "cau-thang-phong-thuy-pt-ngan", status: "done" },
  { no: 5289, title: "Giếng Trời Phong Thủy", keyword: "giếng trời phong thủy", slug: "gieng-troi-phong-thuy-pt-ngan", status: "done" },
  { no: 5290, title: "Gương Phong Thủy Nhà", keyword: "gương phong thủy nhà", slug: "guong-phong-thuy-nha-pt-ngan", status: "done" },
  { no: 5291, title: "Cây Phong Thủy Trong Nhà", keyword: "cây phong thủy trong nhà", slug: "cay-phong-thuy-trong-nha-pt-ngan", status: "done" },
  { no: 5292, title: "Màu Sơn Theo Mệnh PT", keyword: "màu sơn theo mệnh", slug: "mau-son-theo-menh-pt-ngan", status: "done" },
  { no: 5293, title: "Màu Sơn Mệnh Kim PT", keyword: "màu sơn mệnh kim", slug: "mau-son-menh-kim-pt-ngan", status: "done" },
  { no: 5294, title: "Màu Sơn Mệnh Mộc PT", keyword: "màu sơn mệnh mộc", slug: "mau-son-menh-moc-pt-ngan", status: "done" },
  { no: 5295, title: "Màu Sơn Mệnh Thủy PT", keyword: "màu sơn mệnh thủy", slug: "mau-son-menh-thuy-pt-ngan", status: "done" },
  { no: 5296, title: "Màu Sơn Mệnh Hỏa PT", keyword: "màu sơn mệnh hỏa", slug: "mau-son-menh-hoa-pt-ngan", status: "done" },
  { no: 5297, title: "Màu Sơn Mệnh Thổ PT", keyword: "màu sơn mệnh thổ", slug: "mau-son-menh-tho-pt-ngan", status: "done" },
  { no: 5298, title: "Số Tầng Nhà Phong Thủy", keyword: "số tầng nhà phong thủy", slug: "so-tang-nha-phong-thuy-pt-ngan", status: "done" },
  { no: 5299, title: "Số Phòng Ngủ Phong Thủy", keyword: "số phòng ngủ phong thủy", slug: "so-phong-ngu-phong-thuy-pt-ngan", status: "done" },
  { no: 5300, title: "Hình Dáng Nhà Phong Thủy", keyword: "hình dáng nhà phong thủy", slug: "hinh-dang-nha-phong-thuy-pt-ngan", status: "done" },
  { no: 5301, title: "Nhà Lô Đất Tam Giác", keyword: "nhà lô đất tam giác", slug: "nha-lo-dat-tam-giac-pt-ngan", status: "done" },
  { no: 5302, title: "Nhà Lô Đất Chữ L", keyword: "nhà lô đất chữ l", slug: "nha-lo-dat-chu-l-pt-ngan", status: "done" },
  { no: 5303, title: "Nhà Lô Đất Méo", keyword: "nhà lô đất méo", slug: "nha-lo-dat-meo-pt-ngan", status: "done" },
  { no: 5304, title: "Đất Đầu Hẻm Phong Thủy", keyword: "đất đầu hẻm phong thủy", slug: "dat-dau-hem-phong-thuy-pt-ngan", status: "done" },
  { no: 5305, title: "Đất Cuối Hẻm Phong Thủy", keyword: "đất cuối hẻm phong thủy", slug: "dat-cuoi-hem-phong-thuy-pt-ngan", status: "done" },
  { no: 5306, title: "Đất Gần Chùa Phong Thủy", keyword: "đất gần chùa phong thủy", slug: "dat-gan-chua-phong-thuy-pt-ngan", status: "done" },
  { no: 5307, title: "Đất Gần Nghĩa Trang", keyword: "đất gần nghĩa trang", slug: "dat-gan-nghia-trang-pt-ngan", status: "done" },
  { no: 5308, title: "Đất Gần Điện Cao Thế", keyword: "đất gần điện cao thế", slug: "dat-gan-dien-cao-the-pt-ngan", status: "done" },
  { no: 5309, title: "Hóa Giải Phong Thủy Nhà", keyword: "hóa giải phong thủy nhà", slug: "hoa-giai-phong-thuy-nha-pt-ngan", status: "done" },
  { no: 5310, title: "Hóa Giải Nhà Hướng Xấu", keyword: "hóa giải nhà hướng xấu", slug: "hoa-giai-nha-huong-xau-pt-ngan", status: "done" },
  { no: 5311, title: "Hóa Giải WC Đối Cửa", keyword: "hóa giải wc đối cửa", slug: "hoa-giai-wc-doi-cua-pt-ngan", status: "done" },
  { no: 5312, title: "Hóa Giải Cột Giữa Nhà", keyword: "hóa giải cột giữa nhà", slug: "hoa-giai-cot-giua-nha-pt-ngan", status: "done" },
  { no: 5313, title: "Hóa Giải Xà Đà Phòng Ngủ", keyword: "hóa giải xà đà phòng ngủ", slug: "hoa-giai-xa-da-phong-ngu-pt-ngan", status: "done" },
  { no: 5314, title: "Tư Vấn Phong Thủy Xây Nhà", keyword: "tư vấn phong thủy xây nhà", slug: "tu-van-phong-thuy-xay-nha-pt-ngan", status: "done" },
  { no: 5315, title: "Kiến Trúc Sư Hiểu Phong Thủy", keyword: "kiến trúc sư hiểu phong thủy", slug: "kien-truc-su-hieu-phong-thuy-pt-ngan", status: "done" },
  { no: 5316, title: "Thiết Kế Nhà Hợp Phong Thủy", keyword: "thiết kế nhà hợp phong thủy", slug: "thiet-ke-nha-hop-phong-thuy-pt-ngan", status: "done" },
  { no: 5317, title: "Cân Bằng Phong Thủy Và Công Năng", keyword: "cân bằng phong thủy và công năng", slug: "can-bang-phong-thuy-va-cong-nang-pt-ngan", status: "done" },
  { no: 5318, title: "Phong Thủy Hiện Đại", keyword: "phong thủy hiện đại", slug: "phong-thuy-hien-dai-pt-ngan", status: "done" },
  { no: 5319, title: "Phong Thủy Nhà Ống", keyword: "phong thủy nhà ống", slug: "phong-thuy-nha-ong-pt-ngan", status: "done" },
  { no: 5320, title: "Phong Thủy Nhà Phố Hẹp", keyword: "phong thủy nhà phố hẹp", slug: "phong-thuy-nha-pho-hep-pt-ngan", status: "done" },
  { no: 5321, title: "Phong Thủy Biệt Thự", keyword: "phong thủy biệt thự", slug: "phong-thuy-biet-thu-pt-ngan", status: "done" },
  { no: 5322, title: "Ngũ Hành Trong Nhà Ở", keyword: "ngũ hành trong nhà ở", slug: "ngu-hanh-trong-nha-o-pt-ngan", status: "done" },
  { no: 5323, title: "Khí Trong Nhà Phong Thủy", keyword: "khí trong nhà phong thủy", slug: "khi-trong-nha-phong-thuy-pt-ngan", status: "done" },
  { no: 5324, title: "Minh Đường Nhà Phố", keyword: "minh đường nhà phố", slug: "minh-duong-nha-pho-pt-ngan", status: "done" },
  { no: 5325, title: "Huyền Vũ Nhà Phố", keyword: "huyền vũ nhà phố", slug: "huyen-vu-nha-pho-pt-ngan", status: "done" },
  { no: 5326, title: "Thanh Long Bạch Hổ", keyword: "thanh long bạch hổ", slug: "thanh-long-bach-ho-pt-ngan", status: "done" },
  { no: 5327, title: "Checklist Phong Thủy Trước Xây", keyword: "checklist phong thủy trước xây", slug: "checklist-phong-thuy-truoc-xay-pt-ngan", status: "done" },
  { no: 5328, title: "Sai Lầm Phong Thủy Xây Nhà", keyword: "sai lầm phong thủy xây nhà", slug: "sai-lam-phong-thuy-xay-nha-pt-ngan", status: "done" },
  { no: 5329, title: "Myth Phong Thủy Xây Nhà", keyword: "myth phong thủy xây nhà", slug: "myth-phong-thuy-xay-nha-pt-ngan", status: "done" },
  { no: 5330, title: "Chủ Đề Mở Rộng 58 1", keyword: "chủ đề mở rộng 58 1", slug: "chu-de-mo-rong-58-1-ngan", status: "done" },
  { no: 5331, title: "Chủ Đề Mở Rộng 58 2", keyword: "chủ đề mở rộng 58 2", slug: "chu-de-mo-rong-58-2-ngan", status: "done" },
  { no: 5332, title: "Chủ Đề Mở Rộng 58 3", keyword: "chủ đề mở rộng 58 3", slug: "chu-de-mo-rong-58-3-ngan", status: "done" },
  { no: 5333, title: "Chủ Đề Mở Rộng 58 4", keyword: "chủ đề mở rộng 58 4", slug: "chu-de-mo-rong-58-4-ngan", status: "done" },
  { no: 5334, title: "Chủ Đề Mở Rộng 58 5", keyword: "chủ đề mở rộng 58 5", slug: "chu-de-mo-rong-58-5-ngan", status: "done" },
  { no: 5335, title: "Chủ Đề Mở Rộng 58 6", keyword: "chủ đề mở rộng 58 6", slug: "chu-de-mo-rong-58-6-ngan", status: "done" },
  { no: 5336, title: "Chủ Đề Mở Rộng 58 7", keyword: "chủ đề mở rộng 58 7", slug: "chu-de-mo-rong-58-7-ngan", status: "done" },
  { no: 5337, title: "Chủ Đề Mở Rộng 58 8", keyword: "chủ đề mở rộng 58 8", slug: "chu-de-mo-rong-58-8-ngan", status: "done" },
  { no: 5338, title: "Chủ Đề Mở Rộng 58 9", keyword: "chủ đề mở rộng 58 9", slug: "chu-de-mo-rong-58-9-ngan", status: "done" },
  { no: 5339, title: "Chủ Đề Mở Rộng 58 10", keyword: "chủ đề mở rộng 58 10", slug: "chu-de-mo-rong-58-10-ngan", status: "done" },
  { no: 5340, title: "Chủ Đề Mở Rộng 58 11", keyword: "chủ đề mở rộng 58 11", slug: "chu-de-mo-rong-58-11-ngan", status: "done" },
  { no: 5341, title: "Chủ Đề Mở Rộng 58 12", keyword: "chủ đề mở rộng 58 12", slug: "chu-de-mo-rong-58-12-ngan", status: "done" },
  { no: 5342, title: "Chủ Đề Mở Rộng 58 13", keyword: "chủ đề mở rộng 58 13", slug: "chu-de-mo-rong-58-13-ngan", status: "done" },
  { no: 5343, title: "Chủ Đề Mở Rộng 58 14", keyword: "chủ đề mở rộng 58 14", slug: "chu-de-mo-rong-58-14-ngan", status: "done" },
  { no: 5344, title: "Chủ Đề Mở Rộng 58 15", keyword: "chủ đề mở rộng 58 15", slug: "chu-de-mo-rong-58-15-ngan", status: "done" },
  { no: 5345, title: "Chủ Đề Mở Rộng 58 16", keyword: "chủ đề mở rộng 58 16", slug: "chu-de-mo-rong-58-16-ngan", status: "done" },
  { no: 5346, title: "Chủ Đề Mở Rộng 58 17", keyword: "chủ đề mở rộng 58 17", slug: "chu-de-mo-rong-58-17-ngan", status: "done" },
];
