/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 19 (#1347–#1446).
 * Cluster: kết cấu/móng, mái & thoát nước, phòng chức năng, so sánh gói, geo huyện/xa lộ, FAQ mua hàng.
 * Suffix `-ngan` tránh trùng money pages / batch 15–18.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch19: ContentCalendarItem[] = [
  // —— A. Kết cấu & móng (15) #1347–#1361 ——
  { no: 1347, title: "Đổ Móng Nhà", keyword: "đổ móng nhà", slug: "do-mong-nha-ngan", status: "done" },
  { no: 1348, title: "Móng Cọc Nhà", keyword: "móng cọc nhà", slug: "mong-coc-nha-ngan", status: "done" },
  { no: 1349, title: "Móng Băng Nhà", keyword: "móng băng nhà", slug: "mong-bang-nha-ngan", status: "done" },
  { no: 1350, title: "Móng Đơn Nhà", keyword: "móng đơn nhà", slug: "mong-don-nha-ngan", status: "done" },
  { no: 1351, title: "Đà Kiềng Nhà", keyword: "đà kiềng nhà", slug: "da-kieng-nha-ngan", status: "done" },
  { no: 1352, title: "Đổ Cột Nhà", keyword: "đổ cột nhà", slug: "do-cot-nha-ngan", status: "done" },
  { no: 1353, title: "Đổ Sàn Nhà", keyword: "đổ sàn nhà", slug: "do-san-nha-ngan", status: "done" },
  { no: 1354, title: "Đổ Trần Nhà", keyword: "đổ trần nhà", slug: "do-tran-nha-ngan", status: "done" },
  { no: 1355, title: "Gia Cố Cột Nhà", keyword: "gia cố cột nhà", slug: "gia-co-cot-nha-ngan", status: "done" },
  { no: 1356, title: "Gia Cố Dầm Nhà", keyword: "gia cố dầm nhà", slug: "gia-co-dam-nha-ngan", status: "done" },
  { no: 1357, title: "Gia Cố Sàn Nhà", keyword: "gia cố sàn nhà", slug: "gia-co-san-nha-ngan", status: "done" },
  { no: 1358, title: "Ép Cọc Nhà", keyword: "ép cọc nhà", slug: "ep-coc-nha-ngan", status: "done" },
  { no: 1359, title: "Khoan Cọc Nhồi", keyword: "khoan cọc nhồi", slug: "khoan-coc-nhoi-ngan", status: "done" },
  { no: 1360, title: "Khảo Sát Địa Chất", keyword: "khảo sát địa chất", slug: "khao-sat-dia-chat-ngan", status: "done" },
  { no: 1361, title: "Kết Cấu Nhà Phố", keyword: "kết cấu nhà phố", slug: "ket-cau-nha-pho-ngan", status: "done" },

  // —— B. Mái & thoát nước (15) #1362–#1376 ——
  { no: 1362, title: "Làm Mái Tôn", keyword: "làm mái tôn", slug: "lam-mai-ton-ngan", status: "done" },
  { no: 1363, title: "Làm Mái Ngói", keyword: "làm mái ngói", slug: "lam-mai-ngoi-ngan", status: "done" },
  { no: 1364, title: "Mái Bê Tông", keyword: "mái bê tông", slug: "mai-be-tong-ngan", status: "done" },
  { no: 1365, title: "Mái Thái Nhà", keyword: "mái thái nhà", slug: "mai-thai-nha-ngan", status: "done" },
  { no: 1366, title: "Mái Nhật Nhà", keyword: "mái nhật nhà", slug: "mai-nhat-nha-ngan", status: "done" },
  { no: 1367, title: "Sửa Mái Tôn", keyword: "sửa mái tôn", slug: "sua-mai-ton-ngan", status: "done" },
  { no: 1368, title: "Thay Mái Nhà", keyword: "thay mái nhà", slug: "thay-mai-nha-ngan", status: "done" },
  { no: 1369, title: "Thoát Nước Mái", keyword: "thoát nước mái", slug: "thoat-nuoc-mai-ngan", status: "done" },
  { no: 1370, title: "Thoát Nước Sân", keyword: "thoát nước sân", slug: "thoat-nuoc-san-ngan", status: "done" },
  { no: 1371, title: "Hệ Thống Thoát Nước", keyword: "hệ thống thoát nước", slug: "he-thong-thoat-nuoc-ngan", status: "done" },
  { no: 1372, title: "Chống Dột Mái", keyword: "chống dột mái", slug: "chong-dot-mai-ngan", status: "done" },
  { no: 1373, title: "Cách Nhiệt Mái", keyword: "cách nhiệt mái", slug: "cach-nhiet-mai-ngan", status: "done" },
  { no: 1374, title: "Trần Tôn Nhà", keyword: "trần tôn nhà", slug: "tran-ton-nha-ngan", status: "done" },
  { no: 1375, title: "Xà Gồ Mái", keyword: "xà gồ mái", slug: "xa-go-mai-ngan", status: "done" },
  { no: 1376, title: "Báo Giá Làm Mái", keyword: "báo giá làm mái", slug: "bao-gia-lam-mai-ngan", status: "done" },

  // —— C. Phòng chức năng (15) #1377–#1391 ——
  { no: 1377, title: "Xây Phòng Ngủ", keyword: "xây phòng ngủ", slug: "xay-phong-ngu-ngan", status: "done" },
  { no: 1378, title: "Xây Phòng Khách", keyword: "xây phòng khách", slug: "xay-phong-khach-ngan", status: "done" },
  { no: 1379, title: "Xây Phòng Bếp", keyword: "xây phòng bếp", slug: "xay-phong-bep-ngan", status: "done" },
  { no: 1380, title: "Xây Phòng WC", keyword: "xây phòng wc", slug: "xay-phong-wc-ngan", status: "done" },
  { no: 1381, title: "Xây Phòng Thờ", keyword: "xây phòng thờ", slug: "xay-phong-tho-ngan", status: "done" },
  { no: 1382, title: "Xây Phòng Làm Việc", keyword: "xây phòng làm việc", slug: "xay-phong-lam-viec-ngan", status: "done" },
  { no: 1383, title: "Xây Phòng Giặt", keyword: "xây phòng giặt", slug: "xay-phong-giat-ngan", status: "done" },
  { no: 1384, title: "Xây Kho Nhà", keyword: "xây kho nhà", slug: "xay-kho-nha-ngan", status: "done" },
  { no: 1385, title: "Xây Gara Ô Tô", keyword: "xây gara ô tô", slug: "xay-gara-o-to-ngan", status: "done" },
  { no: 1386, title: "Xây Sân Phơi", keyword: "xây sân phơi", slug: "xay-san-phoi-ngan", status: "done" },
  { no: 1387, title: "Xây Giếng Trời", keyword: "xây giếng trời", slug: "xay-gieng-troi-ngan", status: "done" },
  { no: 1388, title: "Xây Cầu Thang", keyword: "xây cầu thang", slug: "xay-cau-thang-ngan", status: "done" },
  { no: 1389, title: "Xây Lửng Nhà", keyword: "xây lửng nhà", slug: "xay-lung-nha-ngan", status: "done" },
  { no: 1390, title: "Xây Tầng Hầm", keyword: "xây tầng hầm", slug: "xay-tang-ham-ngan", status: "done" },
  { no: 1391, title: "Xây Tầng Thượng", keyword: "xây tầng thượng", slug: "xay-tang-thuong-ngan", status: "done" },

  // —— D. So sánh gói / ý định (15) #1392–#1406 ——
  { no: 1392, title: "Xây Thô Hay Trọn Gói", keyword: "xây thô hay trọn gói", slug: "xay-tho-hay-tron-goi-ngan", status: "done" },
  { no: 1393, title: "Xây Mới Hay Cải Tạo", keyword: "xây mới hay cải tạo", slug: "xay-moi-hay-cai-tao-ngan", status: "done" },
  { no: 1394, title: "Thuê Thầu Hay Tự Xây", keyword: "thuê thầu hay tự xây", slug: "thue-thau-hay-tu-xay-ngan", status: "done" },
  { no: 1395, title: "Giá Xây Nhà 2026", keyword: "giá xây nhà 2026", slug: "gia-xay-nha-2026-ngan", status: "done" },
  { no: 1396, title: "Đơn Giá Xây 2026", keyword: "đơn giá xây 2026", slug: "don-gia-xay-2026-ngan", status: "done" },
  { no: 1397, title: "Bảng Giá Xây 2026", keyword: "bảng giá xây 2026", slug: "bang-gia-xay-2026-ngan", status: "done" },
  { no: 1398, title: "Chi Phí Cải Tạo 2026", keyword: "chi phí cải tạo 2026", slug: "chi-phi-cai-tao-2026-ngan", status: "done" },
  { no: 1399, title: "Xây Nhà Trả Góp", keyword: "xây nhà trả góp", slug: "xay-nha-tra-gop-ngan", status: "done" },
  { no: 1400, title: "Xây Nhà Vay Ngân Hàng", keyword: "xây nhà vay ngân hàng", slug: "xay-nha-vay-ngan-hang-ngan", status: "done" },
  { no: 1401, title: "Tiến Độ Thanh Toán Xây", keyword: "tiến độ thanh toán xây", slug: "tien-do-thanh-toan-xay-ngan", status: "done" },
  { no: 1402, title: "Đặt Cọc Xây Nhà", keyword: "đặt cọc xây nhà", slug: "dat-coc-xay-nha-ngan", status: "done" },
  { no: 1403, title: "Phát Sinh Xây Nhà", keyword: "phát sinh xây nhà", slug: "phat-sinh-xay-nha-ngan", status: "done" },
  { no: 1404, title: "Cam Kết Không Phát Sinh", keyword: "cam kết không phát sinh", slug: "cam-ket-khong-phat-sinh-ngan", status: "done" },
  { no: 1405, title: "Bảo Hành 10 Năm", keyword: "bảo hành 10 năm", slug: "bao-hanh-10-nam-ngan", status: "done" },
  { no: 1406, title: "Nghiệm Thu Từng Giai Đoạn", keyword: "nghiệm thu từng giai đoạn", slug: "nghiem-thu-tung-giai-doan-ngan", status: "done" },

  // —— E. Geo huyện / vành đai (20) #1407–#1426 ——
  { no: 1407, title: "Xây Nhà Cần Thơ", keyword: "xây nhà Cần Thơ", slug: "xay-nha-can-tho-ngan", status: "done" },
  { no: 1408, title: "Xây Nhà Vũng Tàu", keyword: "xây nhà Vũng Tàu", slug: "xay-nha-vung-tau-ngan", status: "done" },
  { no: 1409, title: "Xây Nhà Bà Rịa", keyword: "xây nhà Bà Rịa", slug: "xay-nha-ba-ria-ngan", status: "done" },
  { no: 1410, title: "Xây Nhà Tây Ninh", keyword: "xây nhà Tây Ninh", slug: "xay-nha-tay-ninh-ngan", status: "done" },
  { no: 1411, title: "Xây Nhà Bình Phước", keyword: "xây nhà Bình Phước", slug: "xay-nha-binh-phuoc-ngan", status: "done" },
  { no: 1412, title: "Xây Nhà Trảng Bom", keyword: "xây nhà Trảng Bom", slug: "xay-nha-trang-bom-ngan", status: "done" },
  { no: 1413, title: "Xây Nhà Long Khánh", keyword: "xây nhà Long Khánh", slug: "xay-nha-long-khanh-ngan", status: "done" },
  { no: 1414, title: "Xây Nhà Thủ Đức Đông", keyword: "xây nhà Thủ Đức Đông", slug: "xay-nha-thu-duc-dong-ngan", status: "done" },
  { no: 1415, title: "Xây Nhà Hiệp Bình", keyword: "xây nhà Hiệp Bình", slug: "xay-nha-hiep-binh-ngan", status: "done" },
  { no: 1416, title: "Xây Nhà Linh Xuân", keyword: "xây nhà Linh Xuân", slug: "xay-nha-linh-xuan-ngan", status: "done" },
  { no: 1417, title: "Xây Nhà Tam Bình", keyword: "xây nhà Tam Bình", slug: "xay-nha-tam-binh-ngan", status: "done" },
  { no: 1418, title: "Xây Nhà Bình Chiểu", keyword: "xây nhà Bình Chiểu", slug: "xay-nha-binh-chieu-ngan", status: "done" },
  { no: 1419, title: "Sửa Nhà Cần Thơ", keyword: "sửa nhà Cần Thơ", slug: "sua-nha-can-tho-ngan", status: "done" },
  { no: 1420, title: "Sửa Nhà Vũng Tàu", keyword: "sửa nhà Vũng Tàu", slug: "sua-nha-vung-tau-ngan", status: "done" },
  { no: 1421, title: "Cải Tạo Nhà Cần Thơ", keyword: "cải tạo nhà Cần Thơ", slug: "cai-tao-nha-can-tho-ngan", status: "done" },
  { no: 1422, title: "Cải Tạo Nhà Vũng Tàu", keyword: "cải tạo nhà Vũng Tàu", slug: "cai-tao-nha-vung-tau-ngan", status: "done" },
  { no: 1423, title: "Xây Nhà Trọn Gói Cần Thơ", keyword: "xây nhà trọn gói Cần Thơ", slug: "xay-nha-tron-goi-can-tho-ngan", status: "done" },
  { no: 1424, title: "Xây Nhà Trọn Gói Vũng Tàu", keyword: "xây nhà trọn gói Vũng Tàu", slug: "xay-nha-tron-goi-vung-tau-ngan", status: "done" },
  { no: 1425, title: "Xây Nhà Trọn Gói Tây Ninh", keyword: "xây nhà trọn gói Tây Ninh", slug: "xay-nha-tron-goi-tay-ninh-ngan", status: "done" },
  { no: 1426, title: "Xây Nhà Trọn Gói Bình Phước", keyword: "xây nhà trọn gói Bình Phước", slug: "xay-nha-tron-goi-binh-phuoc-ngan", status: "done" },

  // —— F. FAQ / ý định tìm hiểu (20) #1427–#1446 ——
  { no: 1427, title: "Xây Nhà Mất Bao Lâu", keyword: "xây nhà mất bao lâu", slug: "xay-nha-mat-bao-lau-ngan", status: "done" },
  { no: 1428, title: "Cải Tạo Nhà Mất Bao Lâu", keyword: "cải tạo nhà mất bao lâu", slug: "cai-tao-nha-mat-bao-lau-ngan", status: "done" },
  { no: 1429, title: "Xây Nhà Cần Giấy Tờ Gì", keyword: "xây nhà cần giấy tờ gì", slug: "xay-nha-can-giay-to-gi-ngan", status: "done" },
  { no: 1430, title: "Xin Phép Xây Mất Bao Lâu", keyword: "xin phép xây mất bao lâu", slug: "xin-phep-xay-mat-bao-lau-ngan", status: "done" },
  { no: 1431, title: "Xây Nhà Có Cần Kiến Trúc Sư", keyword: "xây nhà có cần kiến trúc sư", slug: "xay-nha-co-can-kien-truc-su-ngan", status: "done" },
  { no: 1432, title: "Nên Xây Mấy Tầng", keyword: "nên xây mấy tầng", slug: "nen-xay-may-tang-ngan", status: "done" },
  { no: 1433, title: "Nên Chọn Phần Thô", keyword: "nên chọn phần thô", slug: "nen-chon-phan-tho-ngan", status: "done" },
  { no: 1434, title: "Nên Chọn Trọn Gói", keyword: "nên chọn trọn gói", slug: "nen-chon-tron-goi-ngan", status: "done" },
  { no: 1435, title: "Cách Tiết Kiệm Xây Nhà", keyword: "cách tiết kiệm xây nhà", slug: "cach-tiet-kiem-xay-nha-ngan", status: "done" },
  { no: 1436, title: "Cách Tránh Phát Sinh", keyword: "cách tránh phát sinh", slug: "cach-tranh-phat-sinh-ngan", status: "done" },
  { no: 1437, title: "Dấu Hiệu Thầu Xấu", keyword: "dấu hiệu thầu xấu", slug: "dau-hieu-thau-xau-ngan", status: "done" },
  { no: 1438, title: "Hỏi Thầu Trước Khi Ký", keyword: "hỏi thầu trước khi ký", slug: "hoi-thau-truoc-khi-ky-ngan", status: "done" },
  { no: 1439, title: "Checklist Xây Nhà", keyword: "checklist xây nhà", slug: "checklist-xay-nha-ngan", status: "done" },
  { no: 1440, title: "Checklist Cải Tạo Nhà", keyword: "checklist cải tạo nhà", slug: "checklist-cai-tao-nha-ngan", status: "done" },
  { no: 1441, title: "Lỗi Thường Gặp Xây Nhà", keyword: "lỗi thường gặp xây nhà", slug: "loi-thuong-gap-xay-nha-ngan", status: "done" },
  { no: 1442, title: "Lỗi Thường Gặp Cải Tạo", keyword: "lỗi thường gặp cải tạo", slug: "loi-thuong-gap-cai-tao-ngan", status: "done" },
  { no: 1443, title: "Mùa Nào Nên Xây Nhà", keyword: "mùa nào nên xây nhà", slug: "mua-nao-nen-xay-nha-ngan", status: "done" },
  { no: 1444, title: "Xây Nhà Mùa Mưa", keyword: "xây nhà mùa mưa", slug: "xay-nha-mua-mua-ngan", status: "done" },
  { no: 1445, title: "Chuẩn Bị Trước Khi Xây", keyword: "chuẩn bị trước khi xây", slug: "chuan-bi-truoc-khi-xay-ngan", status: "done" },
  { no: 1446, title: "Việc Cần Làm Sau Bàn Giao", keyword: "việc cần làm sau bàn giao", slug: "viec-can-lam-sau-ban-giao-ngan", status: "done" },
];
