/**
 * Lịch 100 từ khóa ngắn — batch 62 (#5647–#5746).
 * Cluster: geo Bình Tân, Tân Phú, Hóc Môn, Củ Chi.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch62: ContentCalendarItem[] = [
  { no: 5647, title: "Xây Nhà Bình Hưng Hòa", keyword: "xây nhà Bình Hưng Hòa", slug: "xay-nha-binh-hung-hoa-btan-ngan", status: "done" },
  { no: 5648, title: "Xây Nhà Bình Hưng Hòa A", keyword: "xây nhà Bình Hưng Hòa A", slug: "xay-nha-binh-hung-hoa-a-btan-ngan", status: "done" },
  { no: 5649, title: "Xây Nhà Bình Hưng Hòa B", keyword: "xây nhà Bình Hưng Hòa B", slug: "xay-nha-binh-hung-hoa-b-btan-ngan", status: "done" },
  { no: 5650, title: "Xây Nhà Bình Trị Đông", keyword: "xây nhà Bình Trị Đông", slug: "xay-nha-binh-tri-dong-btan-ngan", status: "done" },
  { no: 5651, title: "Xây Nhà Bình Trị Đông A", keyword: "xây nhà Bình Trị Đông A", slug: "xay-nha-binh-tri-dong-a-btan-ngan", status: "done" },
  { no: 5652, title: "Xây Nhà Bình Trị Đông B", keyword: "xây nhà Bình Trị Đông B", slug: "xay-nha-binh-tri-dong-b-btan-ngan", status: "done" },
  { no: 5653, title: "Xây Nhà An Lạc", keyword: "xây nhà An Lạc", slug: "xay-nha-an-lac-btan-ngan", status: "done" },
  { no: 5654, title: "Xây Nhà An Lạc A", keyword: "xây nhà An Lạc A", slug: "xay-nha-an-lac-a-btan-ngan", status: "done" },
  { no: 5655, title: "Xây Nhà Tân Tạo", keyword: "xây nhà Tân Tạo", slug: "xay-nha-tan-tao-btan-ngan", status: "done" },
  { no: 5656, title: "Xây Nhà Tân Tạo A", keyword: "xây nhà Tân Tạo A", slug: "xay-nha-tan-tao-a-btan-ngan", status: "done" },
  { no: 5657, title: "Xây Nhà Bình Hưng Hòa A Gần Aeon", keyword: "xây nhà gần Aeon Bình Tân", slug: "xay-nha-gan-aeon-binh-tan-ngan", status: "done" },
  { no: 5658, title: "Xây Nhà Gần Tên Lửa", keyword: "xây nhà gần Tên Lửa", slug: "xay-nha-gan-ten-lua-ngan", status: "done" },
  { no: 5659, title: "Xây Nhà Gần Kinh Dương Vương", keyword: "xây nhà gần Kinh Dương Vương", slug: "xay-nha-gan-kinh-duong-vuong-ngan", status: "done" },
  { no: 5660, title: "Xây Nhà Gần Quốc Lộ 1A Bình Tân", keyword: "xây nhà gần QL1A Bình Tân", slug: "xay-nha-gan-ql1a-binh-tan-ngan", status: "done" },
  { no: 5661, title: "Xây Nhà Hòa Thạnh", keyword: "xây nhà Hòa Thạnh", slug: "xay-nha-hoa-thanh-tphu-ngan", status: "done" },
  { no: 5662, title: "Xây Nhà Hiệp Tân", keyword: "xây nhà Hiệp Tân", slug: "xay-nha-hiep-tan-tphu-ngan", status: "done" },
  { no: 5663, title: "Xây Nhà Hòa Thạnh Tân Phú", keyword: "xây nhà Hòa Thạnh Tân Phú", slug: "xay-nha-hoa-thanh-tan-phu-ngan", status: "done" },
  { no: 5664, title: "Xây Nhà Phú Thọ Hòa", keyword: "xây nhà Phú Thọ Hòa", slug: "xay-nha-phu-tho-hoa-tp-ngan", status: "done" },
  { no: 5665, title: "Xây Nhà Phú Trung", keyword: "xây nhà Phú Trung", slug: "xay-nha-phu-trung-ngan", status: "done" },
  { no: 5666, title: "Xây Nhà Sơn Kỳ", keyword: "xây nhà Sơn Kỳ", slug: "xay-nha-son-ky-tp-ngan", status: "done" },
  { no: 5667, title: "Xây Nhà Tân Quý", keyword: "xây nhà Tân Quý", slug: "xay-nha-tan-quy-tp-ngan", status: "done" },
  { no: 5668, title: "Xây Nhà Tân Sơn Nhì", keyword: "xây nhà Tân Sơn Nhì", slug: "xay-nha-tan-son-nhi-ngan", status: "done" },
  { no: 5669, title: "Xây Nhà Tây Thạnh", keyword: "xây nhà Tây Thạnh", slug: "xay-nha-tay-thanh-tp-ngan", status: "done" },
  { no: 5670, title: "Xây Nhà Tân Thành", keyword: "xây nhà Tân Thành Tân Phú", slug: "xay-nha-tan-thanh-tan-phu-ngan", status: "done" },
  { no: 5671, title: "Xây Nhà Gần Công Viên Đầm Sen", keyword: "xây nhà gần Đầm Sen", slug: "xay-nha-gan-dam-sen-ngan", status: "done" },
  { no: 5672, title: "Xây Nhà Gần Lũy Bán Bích", keyword: "xây nhà gần Lũy Bán Bích", slug: "xay-nha-gan-luy-ban-bich-ngan", status: "done" },
  { no: 5673, title: "Xây Nhà Gần Âu Cơ", keyword: "xây nhà gần Âu Cơ", slug: "xay-nha-gan-au-co-ngan", status: "done" },
  { no: 5674, title: "Xây Nhà Xuân Thới Sơn", keyword: "xây nhà Xuân Thới Sơn", slug: "xay-nha-xuan-thoi-son-hm-ngan", status: "done" },
  { no: 5675, title: "Xây Nhà Xuân Thới Đông", keyword: "xây nhà Xuân Thới Đông", slug: "xay-nha-xuan-thoi-dong-hm-ngan", status: "done" },
  { no: 5676, title: "Xây Nhà Xuân Thới Thượng", keyword: "xây nhà Xuân Thới Thượng", slug: "xay-nha-xuan-thoi-thuong-hm-ngan", status: "done" },
  { no: 5677, title: "Xây Nhà Đông Thạnh", keyword: "xây nhà Đông Thạnh", slug: "xay-nha-dong-thanh-hm-ngan", status: "done" },
  { no: 5678, title: "Xây Nhà Tân Thới Nhì", keyword: "xây nhà Tân Thới Nhì", slug: "xay-nha-tan-thoi-nhi-hm-ngan", status: "done" },
  { no: 5679, title: "Xây Nhà Trung Chánh", keyword: "xây nhà Trung Chánh", slug: "xay-nha-trung-chanh-hm-ngan", status: "done" },
  { no: 5680, title: "Xây Nhà Thới Tam Thôn", keyword: "xây nhà Thới Tam Thôn", slug: "xay-nha-thoi-tam-thon-hm-ngan", status: "done" },
  { no: 5681, title: "Xây Nhà Bà Điểm", keyword: "xây nhà Bà Điểm", slug: "xay-nha-ba-diem-hm-ngan", status: "done" },
  { no: 5682, title: "Xây Nhà Nhị Bình", keyword: "xây nhà Nhị Bình", slug: "xay-nha-nhi-binh-hm-ngan", status: "done" },
  { no: 5683, title: "Xây Nhà Tân Hiệp Hóc Môn", keyword: "xây nhà Tân Hiệp Hóc Môn", slug: "xay-nha-tan-hiep-hoc-mon-ngan", status: "done" },
  { no: 5684, title: "Xây Nhà Thái Mỹ", keyword: "xây nhà Thái Mỹ", slug: "xay-nha-thai-my-ngan", status: "done" },
  { no: 5685, title: "Xây Nhà Trung Lập Hạ", keyword: "xây nhà Trung Lập Hạ", slug: "xay-nha-trung-lap-ha-ngan", status: "done" },
  { no: 5686, title: "Xây Nhà Trung Lập Thượng", keyword: "xây nhà Trung Lập Thượng", slug: "xay-nha-trung-lap-thuong-ngan", status: "done" },
  { no: 5687, title: "Xây Nhà Phước Thạnh", keyword: "xây nhà Phước Thạnh Củ Chi", slug: "xay-nha-phuoc-thanh-cu-chi-ngan", status: "done" },
  { no: 5688, title: "Xây Nhà Phước Hiệp", keyword: "xây nhà Phước Hiệp", slug: "xay-nha-phuoc-hiep-ngan", status: "done" },
  { no: 5689, title: "Xây Nhà An Nhơn Tây", keyword: "xây nhà An Nhơn Tây", slug: "xay-nha-an-nhon-tay-ngan", status: "done" },
  { no: 5690, title: "Xây Nhà Nhuận Đức", keyword: "xây nhà Nhuận Đức", slug: "xay-nha-nhuan-duc-ngan", status: "done" },
  { no: 5691, title: "Xây Nhà Phạm Văn Cội", keyword: "xây nhà Phạm Văn Cội", slug: "xay-nha-pham-van-coi-ngan", status: "done" },
  { no: 5692, title: "Xây Nhà Phú Hòa Đông", keyword: "xây nhà Phú Hòa Đông", slug: "xay-nha-phu-hoa-dong-ngan", status: "done" },
  { no: 5693, title: "Xây Nhà Tân Thông Hội", keyword: "xây nhà Tân Thông Hội", slug: "xay-nha-tan-thong-hoi-ngan", status: "done" },
  { no: 5694, title: "Xây Nhà Tân Phú Trung", keyword: "xây nhà Tân Phú Trung", slug: "xay-nha-tan-phu-trung-ngan", status: "done" },
  { no: 5695, title: "Xây Nhà Hòa Phú Củ Chi", keyword: "xây nhà Hòa Phú Củ Chi", slug: "xay-nha-hoa-phu-cu-chi-ngan", status: "done" },
  { no: 5696, title: "Xây Nhà Bình Mỹ Củ Chi", keyword: "xây nhà Bình Mỹ Củ Chi", slug: "xay-nha-binh-my-cu-chi-ngan", status: "done" },
  { no: 5697, title: "Xây Nhà Gần Khu Du Lịch Củ Chi", keyword: "xây nhà gần khu du lịch Củ Chi", slug: "xay-nha-gan-kdl-cu-chi-ngan", status: "done" },
  { no: 5698, title: "Xây Nhà Gần Hồ Dầu Tiếng", keyword: "xây nhà gần Hồ Dầu Tiếng", slug: "xay-nha-gan-ho-dau-tieng-ngan", status: "done" },
  { no: 5699, title: "Cải Tạo Nhà Bình Tân", keyword: "cải tạo nhà Bình Tân", slug: "cai-tao-nha-binh-tan-geo-ngan", status: "done" },
  { no: 5700, title: "Cải Tạo Nhà Tân Phú TP", keyword: "cải tạo nhà Tân Phú", slug: "cai-tao-nha-tan-phu-geo-ngan", status: "done" },
  { no: 5701, title: "Cải Tạo Nhà Hóc Môn", keyword: "cải tạo nhà Hóc Môn", slug: "cai-tao-nha-hoc-mon-geo-ngan", status: "done" },
  { no: 5702, title: "Cải Tạo Nhà Củ Chi", keyword: "cải tạo nhà Củ Chi", slug: "cai-tao-nha-cu-chi-geo-ngan", status: "done" },
  { no: 5703, title: "Cải Tạo Nhà An Lạc", keyword: "cải tạo nhà An Lạc", slug: "cai-tao-nha-an-lac-ngan", status: "done" },
  { no: 5704, title: "Cải Tạo Nhà Sơn Kỳ", keyword: "cải tạo nhà Sơn Kỳ", slug: "cai-tao-nha-son-ky-ngan", status: "done" },
  { no: 5705, title: "Cải Tạo Nhà Bà Điểm", keyword: "cải tạo nhà Bà Điểm", slug: "cai-tao-nha-ba-diem-ngan", status: "done" },
  { no: 5706, title: "Thiết Kế Nhà Bình Tân", keyword: "thiết kế nhà Bình Tân", slug: "thiet-ke-nha-binh-tan-geo-ngan", status: "done" },
  { no: 5707, title: "Thiết Kế Nhà Tân Phú TP", keyword: "thiết kế nhà Tân Phú", slug: "thiet-ke-nha-tan-phu-geo-ngan", status: "done" },
  { no: 5708, title: "Thiết Kế Nhà Hóc Môn", keyword: "thiết kế nhà Hóc Môn", slug: "thiet-ke-nha-hoc-mon-geo-ngan", status: "done" },
  { no: 5709, title: "Thiết Kế Nhà Củ Chi", keyword: "thiết kế nhà Củ Chi", slug: "thiet-ke-nha-cu-chi-geo-ngan", status: "done" },
  { no: 5710, title: "Báo Giá Xây Nhà Bình Tân", keyword: "báo giá xây nhà Bình Tân", slug: "bao-gia-xay-nha-binh-tan-geo-ngan", status: "done" },
  { no: 5711, title: "Báo Giá Xây Nhà Tân Phú", keyword: "báo giá xây nhà Tân Phú", slug: "bao-gia-xay-nha-tan-phu-geo-ngan", status: "done" },
  { no: 5712, title: "Báo Giá Xây Nhà Hóc Môn", keyword: "báo giá xây nhà Hóc Môn", slug: "bao-gia-xay-nha-hoc-mon-geo-ngan", status: "done" },
  { no: 5713, title: "Báo Giá Xây Nhà Củ Chi", keyword: "báo giá xây nhà Củ Chi", slug: "bao-gia-xay-nha-cu-chi-geo-ngan", status: "done" },
  { no: 5714, title: "Nhà Thầu Bình Tân", keyword: "nhà thầu Bình Tân", slug: "nha-thau-binh-tan-geo-ngan", status: "done" },
  { no: 5715, title: "Nhà Thầu Tân Phú TP", keyword: "nhà thầu Tân Phú", slug: "nha-thau-tan-phu-geo-ngan", status: "done" },
  { no: 5716, title: "Nhà Thầu Hóc Môn", keyword: "nhà thầu Hóc Môn", slug: "nha-thau-hoc-mon-geo-ngan", status: "done" },
  { no: 5717, title: "Nhà Thầu Củ Chi", keyword: "nhà thầu Củ Chi", slug: "nha-thau-cu-chi-geo-ngan", status: "done" },
  { no: 5718, title: "Xây Nhà Phố Bình Tân", keyword: "xây nhà phố Bình Tân", slug: "xay-nha-pho-binh-tan-ngan", status: "done" },
  { no: 5719, title: "Xây Nhà Ống Tân Phú", keyword: "xây nhà ống Tân Phú", slug: "xay-nha-ong-tan-phu-ngan", status: "done" },
  { no: 5720, title: "Xây Nhà Vườn Hóc Môn", keyword: "xây nhà vườn Hóc Môn", slug: "xay-nha-vuon-hoc-mon-ngan", status: "done" },
  { no: 5721, title: "Xây Nhà Vườn Củ Chi", keyword: "xây nhà vườn Củ Chi", slug: "xay-nha-vuon-cu-chi-ngan", status: "done" },
  { no: 5722, title: "Xây Nhà Trọ Bình Tân", keyword: "xây nhà trọ Bình Tân", slug: "xay-nha-tro-binh-tan-ngan", status: "done" },
  { no: 5723, title: "Xây Biệt Thự Củ Chi", keyword: "xây biệt thự Củ Chi", slug: "xay-biet-thu-cu-chi-ngan", status: "done" },
  { no: 5724, title: "Xin Phép Xây Bình Tân", keyword: "xin phép xây Bình Tân", slug: "xin-phep-xay-binh-tan-ngan", status: "done" },
  { no: 5725, title: "Xin Phép Xây Hóc Môn", keyword: "xin phép xây Hóc Môn", slug: "xin-phep-xay-hoc-mon-ngan", status: "done" },
  { no: 5726, title: "Đơn Giá Xây Bình Tân", keyword: "đơn giá xây Bình Tân", slug: "don-gia-xay-binh-tan-ngan", status: "done" },
  { no: 5727, title: "Đơn Giá Xây Củ Chi", keyword: "đơn giá xây Củ Chi", slug: "don-gia-xay-cu-chi-ngan", status: "done" },
  { no: 5728, title: "Nâng Tầng Nhà Bình Tân", keyword: "nâng tầng nhà Bình Tân", slug: "nang-tang-nha-binh-tan-ngan", status: "done" },
  { no: 5729, title: "Nâng Tầng Nhà Tân Phú", keyword: "nâng tầng nhà Tân Phú", slug: "nang-tang-nha-tan-phu-ngan", status: "done" },
  { no: 5730, title: "Sửa Nhà Bình Tân", keyword: "sửa nhà Bình Tân", slug: "sua-nha-binh-tan-ngan", status: "done" },
  { no: 5731, title: "Sửa Nhà Hóc Môn", keyword: "sửa nhà Hóc Môn", slug: "sua-nha-hoc-mon-ngan", status: "done" },
  { no: 5732, title: "Chống Thấm Nhà Bình Tân", keyword: "chống thấm nhà Bình Tân", slug: "chong-tham-nha-binh-tan-ngan", status: "done" },
  { no: 5733, title: "Chống Thấm Nhà Củ Chi", keyword: "chống thấm nhà Củ Chi", slug: "chong-tham-nha-cu-chi-ngan", status: "done" },
  { no: 5734, title: "Xây Nhà Gần Metro Số 2", keyword: "xây nhà gần metro số 2 Tân Phú", slug: "xay-nha-gan-metro-2-tan-phu-ngan", status: "done" },
  { no: 5735, title: "Xây Nhà Gần Vành Đai 3", keyword: "xây nhà gần vành đai 3", slug: "xay-nha-gan-vanh-dai-3-ngan", status: "done" },
  { no: 5736, title: "Xây Nhà Gần Vành Đai 4", keyword: "xây nhà gần vành đai 4", slug: "xay-nha-gan-vanh-dai-4-ngan", status: "done" },
  { no: 5737, title: "Chủ Đề Mở Rộng 62 1", keyword: "chủ đề mở rộng 62 1", slug: "chu-de-mo-rong-62-1-ngan", status: "done" },
  { no: 5738, title: "Chủ Đề Mở Rộng 62 2", keyword: "chủ đề mở rộng 62 2", slug: "chu-de-mo-rong-62-2-ngan", status: "done" },
  { no: 5739, title: "Chủ Đề Mở Rộng 62 3", keyword: "chủ đề mở rộng 62 3", slug: "chu-de-mo-rong-62-3-ngan", status: "done" },
  { no: 5740, title: "Chủ Đề Mở Rộng 62 4", keyword: "chủ đề mở rộng 62 4", slug: "chu-de-mo-rong-62-4-ngan", status: "done" },
  { no: 5741, title: "Chủ Đề Mở Rộng 62 5", keyword: "chủ đề mở rộng 62 5", slug: "chu-de-mo-rong-62-5-ngan", status: "done" },
  { no: 5742, title: "Chủ Đề Mở Rộng 62 6", keyword: "chủ đề mở rộng 62 6", slug: "chu-de-mo-rong-62-6-ngan", status: "done" },
  { no: 5743, title: "Chủ Đề Mở Rộng 62 7", keyword: "chủ đề mở rộng 62 7", slug: "chu-de-mo-rong-62-7-ngan", status: "done" },
  { no: 5744, title: "Chủ Đề Mở Rộng 62 8", keyword: "chủ đề mở rộng 62 8", slug: "chu-de-mo-rong-62-8-ngan", status: "done" },
  { no: 5745, title: "Chủ Đề Mở Rộng 62 9", keyword: "chủ đề mở rộng 62 9", slug: "chu-de-mo-rong-62-9-ngan", status: "done" },
  { no: 5746, title: "Chủ Đề Mở Rộng 62 10", keyword: "chủ đề mở rộng 62 10", slug: "chu-de-mo-rong-62-10-ngan", status: "done" },
];
