/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 24 (#1847–#1946).
 * Cluster: Ads intent, gói dịch vụ, cam kết, thương hiệu.
 * Suffix `-ngan` tránh trùng money pages / batch trước.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch24: ContentCalendarItem[] = [
  { no: 1847, title: "Báo Giá Xây Nhà Online", keyword: "báo giá xây nhà online", slug: "bao-gia-xay-nha-online-ngan", status: "done" },
  { no: 1848, title: "Tính Chi Phí Xây Nhà", keyword: "tính chi phí xây nhà", slug: "tinh-chi-phi-xay-nha-ngan", status: "done" },
  { no: 1849, title: "Ước Tính Chi Phí Xây", keyword: "ước tính chi phí xây", slug: "uoc-tinh-chi-phi-xay-ngan", status: "done" },
  { no: 1850, title: "Máy Tính Xây Nhà", keyword: "máy tính xây nhà", slug: "may-tinh-xay-nha-ngan", status: "done" },
  { no: 1851, title: "Form Báo Giá Xây Nhà", keyword: "form báo giá xây nhà", slug: "form-bao-gia-xay-nha-ngan", status: "done" },
  { no: 1852, title: "Đăng Ký Tư Vấn Xây", keyword: "đăng ký tư vấn xây", slug: "dang-ky-tu-van-xay-ngan", status: "done" },
  { no: 1853, title: "Để Lại SĐT Xây Nhà", keyword: "để lại sđt xây nhà", slug: "de-lai-sdt-xay-nha-ngan", status: "done" },
  { no: 1854, title: "Gọi Ngay Xây Nhà", keyword: "gọi ngay xây nhà", slug: "goi-ngay-xay-nha-ngan", status: "done" },
  { no: 1855, title: "Zalo Tư Vấn Xây Nhà", keyword: "zalo tư vấn xây nhà", slug: "zalo-tu-van-xay-nha-ngan", status: "done" },
  { no: 1856, title: "Chat Tư Vấn Xây Nhà", keyword: "chat tư vấn xây nhà", slug: "chat-tu-van-xay-nha-ngan", status: "done" },
  { no: 1857, title: "Xem Công Trình Thực Tế", keyword: "xem công trình thực tế", slug: "xem-cong-trinh-thuc-te-ngan", status: "done" },
  { no: 1858, title: "Tham Quan Nhà Mẫu", keyword: "tham quan nhà mẫu", slug: "tham-quan-nha-mau-ngan", status: "done" },
  { no: 1859, title: "Review Nhà Thầu", keyword: "review nhà thầu", slug: "review-nha-thau-ngan", status: "done" },
  { no: 1860, title: "Đánh Giá Sao Khuê", keyword: "đánh giá Sao Khuê", slug: "danh-gia-sao-khue-ngan", status: "done" },
  { no: 1861, title: "Feedback Khách Hàng Xây", keyword: "feedback khách hàng xây", slug: "feedback-khach-hang-xay-ngan", status: "done" },
  { no: 1862, title: "Hình Ảnh Công Trình", keyword: "hình ảnh công trình", slug: "hinh-anh-cong-trinh-ngan", status: "done" },
  { no: 1863, title: "Video Thi Công Nhà", keyword: "video thi công nhà", slug: "video-thi-cong-nha-ngan", status: "done" },
  { no: 1864, title: "Before After Cải Tạo", keyword: "before after cải tạo", slug: "before-after-cai-tao-ngan", status: "done" },
  { no: 1865, title: "Case Study Xây Nhà", keyword: "case study xây nhà", slug: "case-study-xay-nha-ngan", status: "done" },
  { no: 1866, title: "Hồ Sơ Năng Lực Thầu", keyword: "hồ sơ năng lực thầu", slug: "ho-so-nang-luc-thau-ngan", status: "done" },
  { no: 1867, title: "Giấy Phép Kinh Doanh Xây", keyword: "giấy phép kinh doanh xây", slug: "giay-phep-kinh-doanh-xay-ngan", status: "done" },
  { no: 1868, title: "Chứng Chỉ Hành Nghề Xây", keyword: "chứng chỉ hành nghề xây", slug: "chung-chi-hanh-nghe-xay-ngan", status: "done" },
  { no: 1869, title: "Bảo Hiểm Công Trình", keyword: "bảo hiểm công trình", slug: "bao-hiem-cong-trinh-ngan", status: "done" },
  { no: 1870, title: "Bảo Hiểm Thợ Xây", keyword: "bảo hiểm thợ xây", slug: "bao-hiem-tho-xay-ngan", status: "done" },
  { no: 1871, title: "Cam Kết Tiến Độ Xây", keyword: "cam kết tiến độ xây", slug: "cam-ket-tien-do-xay-ngan", status: "done" },
  { no: 1872, title: "Phạt Trễ Tiến Độ", keyword: "phạt trễ tiến độ", slug: "phat-tre-tien-do-ngan", status: "done" },
  { no: 1873, title: "Thưởng Đúng Tiến Độ", keyword: "thưởng đúng tiến độ", slug: "thuong-dung-tien-do-ngan", status: "done" },
  { no: 1874, title: "Điều Khoản Phát Sinh", keyword: "điều khoản phát sinh", slug: "dieu-khoan-phat-sinh-ngan", status: "done" },
  { no: 1875, title: "Phụ Lục Hợp Đồng Xây", keyword: "phụ lục hợp đồng xây", slug: "phu-luc-hop-dong-xay-ngan", status: "done" },
  { no: 1876, title: "Thanh Lý Hợp Đồng Xây", keyword: "thanh lý hợp đồng xây", slug: "thanh-ly-hop-dong-xay-ngan", status: "done" },
  { no: 1877, title: "Tạm Ứng Xây Nhà", keyword: "tạm ứng xây nhà", slug: "tam-ung-xay-nha-ngan", status: "done" },
  { no: 1878, title: "Thanh Toán Theo Giai Đoạn", keyword: "thanh toán theo giai đoạn", slug: "thanh-toan-theo-giai-doan-ngan", status: "done" },
  { no: 1879, title: "Thanh Toán Cuối Xây", keyword: "thanh toán cuối xây", slug: "thanh-toan-cuoi-xay-ngan", status: "done" },
  { no: 1880, title: "Giữ Lại Bảo Hành", keyword: "giữ lại bảo hành", slug: "giu-lai-bao-hanh-ngan", status: "done" },
  { no: 1881, title: "Bảo Lãnh Hợp Đồng", keyword: "bảo lãnh hợp đồng", slug: "bao-lanh-hop-dong-ngan", status: "done" },
  { no: 1882, title: "So Sánh Báo Giá Thầu", keyword: "so sánh báo giá thầu", slug: "so-sanh-bao-gia-thau-ngan", status: "done" },
  { no: 1883, title: "Chọn Thầu Theo Điểm", keyword: "chọn thầu theo điểm", slug: "chon-thau-theo-diem-ngan", status: "done" },
  { no: 1884, title: "Thầu Uy Tín Gần Nhà", keyword: "thầu uy tín gần nhà", slug: "thau-uy-tin-gan-nha-ngan", status: "done" },
  { no: 1885, title: "Thầu Có Bảo Hành Dài", keyword: "thầu có bảo hành dài", slug: "thau-co-bao-hanh-dai-ngan", status: "done" },
  { no: 1886, title: "Thầu Không Bán Thầu Lại", keyword: "thầu không bán thầu lại", slug: "thau-khong-ban-thau-lai-ngan", status: "done" },
  { no: 1887, title: "Thầu Thi Công Trực Tiếp", keyword: "thầu thi công trực tiếp", slug: "thau-thi-cong-truc-tiep-ngan", status: "done" },
  { no: 1888, title: "Đội Thợ Cố Định", keyword: "đội thợ cố định", slug: "doi-tho-co-dinh-ngan", status: "done" },
  { no: 1889, title: "Giám Sát Online", keyword: "giám sát online", slug: "giam-sat-online-ngan", status: "done" },
  { no: 1890, title: "Camera Công Trường", keyword: "camera công trường", slug: "camera-cong-truong-ngan", status: "done" },
  { no: 1891, title: "Báo Cáo Tuần Xây", keyword: "báo cáo tuần xây", slug: "bao-cao-tuan-xay-ngan", status: "done" },
  { no: 1892, title: "Nhật Ký Ảnh Xây", keyword: "nhật ký ảnh xây", slug: "nhat-ky-anh-xay-ngan", status: "done" },
  { no: 1893, title: "App Theo Dõi Xây Nhà", keyword: "app theo dõi xây nhà", slug: "app-theo-doi-xay-nha-ngan", status: "done" },
  { no: 1894, title: "Portal Khách Hàng Xây", keyword: "portal khách hàng xây", slug: "portal-khach-hang-xay-ngan", status: "done" },
  { no: 1895, title: "Ưu Đãi Xây Nhà", keyword: "ưu đãi xây nhà", slug: "uu-dai-xay-nha-ngan", status: "done" },
  { no: 1896, title: "Khuyến Mãi Xây Nhà", keyword: "khuyến mãi xây nhà", slug: "khuyen-mai-xay-nha-ngan", status: "done" },
  { no: 1897, title: "Quà Tặng Khi Ký HĐ", keyword: "quà tặng khi ký hđ", slug: "qua-tang-khi-ky-hd-ngan", status: "done" },
  { no: 1898, title: "Giảm Giá Thiết Kế", keyword: "giảm giá thiết kế", slug: "giam-gia-thiet-ke-ngan", status: "done" },
  { no: 1899, title: "Miễn Phí Thiết Kế 3D", keyword: "miễn phí thiết kế 3d", slug: "mien-phi-thiet-ke-3d-ngan", status: "done" },
  { no: 1900, title: "Miễn Phí Xin Phép", keyword: "miễn phí xin phép", slug: "mien-phi-xin-phep-ngan", status: "done" },
  { no: 1901, title: "Combo Xây Trọn Gói", keyword: "combo xây trọn gói", slug: "combo-xay-tron-goi-ngan", status: "done" },
  { no: 1902, title: "Gói Xây Tiết Kiệm", keyword: "gói xây tiết kiệm", slug: "goi-xay-tiet-kiem-ngan", status: "done" },
  { no: 1903, title: "Gói Xây Tiêu Chuẩn", keyword: "gói xây tiêu chuẩn", slug: "goi-xay-tieu-chuan-ngan", status: "done" },
  { no: 1904, title: "Gói Xây Cao Cấp", keyword: "gói xây cao cấp", slug: "goi-xay-cao-cap-ngan", status: "done" },
  { no: 1905, title: "Gói Xây Luxury", keyword: "gói xây luxury", slug: "goi-xay-luxury-ngan", status: "done" },
  { no: 1906, title: "Gói Cải Tạo Nhanh", keyword: "gói cải tạo nhanh", slug: "goi-cai-tao-nhanh-ngan", status: "done" },
  { no: 1907, title: "Gói Sửa Nhà 7 Ngày", keyword: "gói sửa nhà 7 ngày", slug: "goi-sua-nha-7-ngay-ngan", status: "done" },
  { no: 1908, title: "Gói Chống Thấm Trọn", keyword: "gói chống thấm trọn", slug: "goi-chong-tham-tron-ngan", status: "done" },
  { no: 1909, title: "Gói Sơn Nhà Trọn", keyword: "gói sơn nhà trọn", slug: "goi-son-nha-tron-ngan", status: "done" },
  { no: 1910, title: "Gói Điện Nước Trọn", keyword: "gói điện nước trọn", slug: "goi-dien-nuoc-tron-ngan", status: "done" },
  { no: 1911, title: "Gói Nội Thất Cơ Bản", keyword: "gói nội thất cơ bản", slug: "goi-noi-that-co-ban-ngan", status: "done" },
  { no: 1912, title: "Gói Nội Thất Cao Cấp", keyword: "gói nội thất cao cấp", slug: "goi-noi-that-cao-cap-ngan", status: "done" },
  { no: 1913, title: "Xây Nhà Black Friday", keyword: "xây nhà black friday", slug: "xay-nha-black-friday-ngan", status: "done" },
  { no: 1914, title: "Xây Nhà Tết", keyword: "xây nhà tết", slug: "xay-nha-tet-ngan", status: "done" },
  { no: 1915, title: "Xây Nhà Đầu Năm", keyword: "xây nhà đầu năm", slug: "xay-nha-dau-nam-ngan", status: "done" },
  { no: 1916, title: "Xây Nhà Cuối Năm", keyword: "xây nhà cuối năm", slug: "xay-nha-cuoi-nam-ngan", status: "done" },
  { no: 1917, title: "Flash Sale Xây Nhà", keyword: "flash sale xây nhà", slug: "flash-sale-xay-nha-ngan", status: "done" },
  { no: 1918, title: "Voucher Xây Nhà", keyword: "voucher xây nhà", slug: "voucher-xay-nha-ngan", status: "done" },
  { no: 1919, title: "Referral Xây Nhà", keyword: "referral xây nhà", slug: "referral-xay-nha-ngan", status: "done" },
  { no: 1920, title: "Giới Thiệu Bạn Bè Xây", keyword: "giới thiệu bạn bề xây", slug: "gioi-thieu-ban-be-xay-ngan", status: "done" },
  { no: 1921, title: "Affiliate Xây Nhà", keyword: "affiliate xây nhà", slug: "affiliate-xay-nha-ngan", status: "done" },
  { no: 1922, title: "Đối Tác Môi Giới Xây", keyword: "đối tác môi giới xây", slug: "doi-tac-moi-gioi-xay-ngan", status: "done" },
  { no: 1923, title: "Cộng Tác Viên Xây Nhà", keyword: "cộng tác viên xây nhà", slug: "cong-tac-vien-xay-nha-ngan", status: "done" },
  { no: 1924, title: "Franchise Xây Nhà", keyword: "franchise xây nhà", slug: "franchise-xay-nha-ngan", status: "done" },
  { no: 1925, title: "Chi Nhánh Xây Nhà", keyword: "chi nhánh xây nhà", slug: "chi-nhanh-xay-nha-ngan", status: "done" },
  { no: 1926, title: "Showroom Xây Nhà", keyword: "showroom xây nhà", slug: "showroom-xay-nha-ngan", status: "done" },
  { no: 1927, title: "Văn Phòng Tư Vấn Xây", keyword: "văn phòng tư vấn xây", slug: "van-phong-tu-van-xay-ngan", status: "done" },
  { no: 1928, title: "Địa Chỉ Sao Khuê", keyword: "địa chỉ Sao Khuê", slug: "dia-chi-sao-khue-ngan", status: "done" },
  { no: 1929, title: "Maps Sao Khuê", keyword: "maps Sao Khuê", slug: "maps-sao-khue-ngan", status: "done" },
  { no: 1930, title: "Giờ Làm Việc Sao Khuê", keyword: "giờ làm việc Sao Khuê", slug: "gio-lam-viec-sao-khue-ngan", status: "done" },
  { no: 1931, title: "Tuyển Dụng Sao Khuê", keyword: "tuyển dụng Sao Khuê", slug: "tuyen-dung-sao-khue-ngan", status: "done" },
  { no: 1932, title: "Tin Tức Sao Khuê", keyword: "tin tức Sao Khuê", slug: "tin-tuc-sao-khue-ngan", status: "done" },
  { no: 1933, title: "Blog Xây Nhà Sao Khuê", keyword: "blog xây nhà Sao Khuê", slug: "blog-xay-nha-sao-khue-ngan", status: "done" },
  { no: 1934, title: "Fanpage Sao Khuê", keyword: "fanpage Sao Khuê", slug: "fanpage-sao-khue-ngan", status: "done" },
  { no: 1935, title: "Youtube Sao Khuê", keyword: "youtube Sao Khuê", slug: "youtube-sao-khue-ngan", status: "done" },
  { no: 1936, title: "Tiktok Sao Khuê", keyword: "tiktok Sao Khuê", slug: "tiktok-sao-khue-ngan", status: "done" },
  { no: 1937, title: "Landing Page Xây Nhà", keyword: "landing page xây nhà", slug: "landing-page-xay-nha-ngan", status: "done" },
  { no: 1938, title: "Quảng Cáo Xây Nhà Google", keyword: "quảng cáo xây nhà google", slug: "quang-cao-xay-nha-google-ngan", status: "done" },
  { no: 1939, title: "Quảng Cáo Xây Nhà Facebook", keyword: "quảng cáo xây nhà facebook", slug: "quang-cao-xay-nha-facebook-ngan", status: "done" },
  { no: 1940, title: "Lead Xây Nhà", keyword: "lead xây nhà", slug: "lead-xay-nha-ngan", status: "done" },
  { no: 1941, title: "CRM Xây Nhà", keyword: "crm xây nhà", slug: "crm-xay-nha-ngan", status: "done" },
  { no: 1942, title: "CSKH Sau Xây", keyword: "cskh sau xây", slug: "cskh-sau-xay-ngan", status: "done" },
  { no: 1943, title: "NPS Khách Hàng Xây", keyword: "nps khách hàng xây", slug: "nps-khach-hang-xay-ngan", status: "done" },
  { no: 1944, title: "Survey Hài Lòng Xây", keyword: "survey hài lòng xây", slug: "survey-hai-long-xay-ngan", status: "done" },
  { no: 1945, title: "Upsell Nội Thất Xây", keyword: "upsell nội thất xây", slug: "upsell-noi-that-xay-ngan", status: "done" },
  { no: 1946, title: "Cross Sell Cải Tạo", keyword: "cross sell cải tạo", slug: "cross-sell-cai-tao-ngan", status: "done" },
];
