/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 22 (#1647–#1746).
 * Cluster: phong thủy, lối sống, nhà thông minh, tiện ích.
 * Suffix `-ngan` tránh trùng money pages / batch trước.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch22: ContentCalendarItem[] = [
  { no: 1647, title: "Phong Thủy Xây Nhà", keyword: "phong thủy xây nhà", slug: "phong-thuy-xay-nha-ngan", status: "done" },
  { no: 1648, title: "Hướng Nhà Tốt", keyword: "hướng nhà tốt", slug: "huong-nha-tot-ngan", status: "done" },
  { no: 1649, title: "Hướng Đông Nam Nhà", keyword: "hướng đông nam nhà", slug: "huong-dong-nam-nha-ngan", status: "done" },
  { no: 1650, title: "Hướng Tây Nhà", keyword: "hướng tây nhà", slug: "huong-tay-nha-ngan", status: "done" },
  { no: 1651, title: "Cửa Chính Phong Thủy", keyword: "cửa chính phong thủy", slug: "cua-chinh-phong-thuy-ngan", status: "done" },
  { no: 1652, title: "Bếp Phong Thủy", keyword: "bếp phong thủy", slug: "bep-phong-thuy-ngan", status: "done" },
  { no: 1653, title: "Phòng Ngủ Phong Thủy", keyword: "phòng ngủ phong thủy", slug: "phong-ngu-phong-thuy-ngan", status: "done" },
  { no: 1654, title: "WC Phong Thủy", keyword: "wc phong thủy", slug: "wc-phong-thuy-ngan", status: "done" },
  { no: 1655, title: "Cầu Thang Phong Thủy", keyword: "cầu thang phong thủy", slug: "cau-thang-phong-thuy-ngan", status: "done" },
  { no: 1656, title: "Giếng Trời Phong Thủy", keyword: "giếng trời phong thủy", slug: "gieng-troi-phong-thuy-ngan", status: "done" },
  { no: 1657, title: "Màu Sơn Phong Thủy", keyword: "màu sơn phong thủy", slug: "mau-son-phong-thuy-ngan", status: "done" },
  { no: 1658, title: "Ngày Động Thổ", keyword: "ngày động thổ", slug: "ngay-dong-tho-ngan", status: "done" },
  { no: 1659, title: "Lễ Động Thổ", keyword: "lễ động thổ", slug: "le-dong-tho-ngan", status: "done" },
  { no: 1660, title: "Lễ Cất Nóc", keyword: "lễ cất nóc", slug: "le-cat-noc-ngan", status: "done" },
  { no: 1661, title: "Lễ Nhập Trạch", keyword: "lễ nhập trạch", slug: "le-nhap-trach-ngan", status: "done" },
  { no: 1662, title: "Nhà Cho Người Già", keyword: "nhà cho người già", slug: "nha-cho-nguoi-gia-ngan", status: "done" },
  { no: 1663, title: "Nhà Cho Trẻ Em", keyword: "nhà cho trẻ em", slug: "nha-cho-tre-em-ngan", status: "done" },
  { no: 1664, title: "Nhà Ba Thế Hệ", keyword: "nhà ba thế hệ", slug: "nha-ba-the-he-ngan", status: "done" },
  { no: 1665, title: "Nhà Ở Kết Hợp Kinh Doanh", keyword: "nhà ở kết hợp kinh doanh", slug: "nha-o-ket-hop-kinh-doanh-ngan", status: "done" },
  { no: 1666, title: "Nhà Cho Thuê", keyword: "nhà cho thuê", slug: "nha-cho-thue-ngan", status: "done" },
  { no: 1667, title: "Nhà Homestay", keyword: "nhà homestay", slug: "nha-homestay-ngan", status: "done" },
  { no: 1668, title: "Nhà Airbnb", keyword: "nhà airbnb", slug: "nha-airbnb-ngan", status: "done" },
  { no: 1669, title: "Nhà Offline Store", keyword: "nhà offline store", slug: "nha-offline-store-ngan", status: "done" },
  { no: 1670, title: "Nhà Văn Phòng Nhỏ", keyword: "nhà văn phòng nhỏ", slug: "nha-van-phong-nho-ngan", status: "done" },
  { no: 1671, title: "Studio Nhà Phố", keyword: "studio nhà phố", slug: "studio-nha-pho-ngan", status: "done" },
  { no: 1672, title: "Duplex Nhà Phố", keyword: "duplex nhà phố", slug: "duplex-nha-pho-ngan", status: "done" },
  { no: 1673, title: "Penthouse Nhà Phố", keyword: "penthouse nhà phố", slug: "penthouse-nha-pho-ngan", status: "done" },
  { no: 1674, title: "Nhà Có Hồ Bơi", keyword: "nhà có hồ bơi", slug: "nha-co-ho-boi-ngan", status: "done" },
  { no: 1675, title: "Nhà Có Phòng Gym", keyword: "nhà có phòng gym", slug: "nha-co-phong-gym-ngan", status: "done" },
  { no: 1676, title: "Nhà Có Phòng Karaoke", keyword: "nhà có phòng karaoke", slug: "nha-co-phong-karaoke-ngan", status: "done" },
  { no: 1677, title: "Nhà Có Rạp Phim", keyword: "nhà có rạp phim", slug: "nha-co-rap-phim-ngan", status: "done" },
  { no: 1678, title: "Nhà Có Thư Viện", keyword: "nhà có thư viện", slug: "nha-co-thu-vien-ngan", status: "done" },
  { no: 1679, title: "Nhà Có Phòng Spa", keyword: "nhà có phòng spa", slug: "nha-co-phong-spa-ngan", status: "done" },
  { no: 1680, title: "Nhà Có Sân Golf Mini", keyword: "nhà có sân golf mini", slug: "nha-co-san-golf-mini-ngan", status: "done" },
  { no: 1681, title: "Nhà Pet Friendly", keyword: "nhà pet friendly", slug: "nha-pet-friendly-ngan", status: "done" },
  { no: 1682, title: "Nhà Không Gian Mở", keyword: "nhà không gian mở", slug: "nha-khong-gian-mo-ngan", status: "done" },
  { no: 1683, title: "Nhà Thông Tầng", keyword: "nhà thông tầng", slug: "nha-thong-tang-ngan", status: "done" },
  { no: 1684, title: "Nhà Có Gác Lửng", keyword: "nhà có gác lửng", slug: "nha-co-gac-lung-ngan", status: "done" },
  { no: 1685, title: "Nhà Có Sân Trong", keyword: "nhà có sân trong", slug: "nha-co-san-trong-ngan", status: "done" },
  { no: 1686, title: "Nhà Có Vườn Trên Mái", keyword: "nhà có vườn trên mái", slug: "nha-co-vuon-tren-mai-ngan", status: "done" },
  { no: 1687, title: "Nhà Tiết Kiệm Điện", keyword: "nhà tiết kiệm điện", slug: "nha-tiet-kiem-dien-ngan", status: "done" },
  { no: 1688, title: "Nhà Tiết Kiệm Nước", keyword: "nhà tiết kiệm nước", slug: "nha-tiet-kiem-nuoc-ngan", status: "done" },
  { no: 1689, title: "Nhà Xanh Công Nghệ", keyword: "nhà xanh công nghệ", slug: "nha-xanh-cong-nghe-ngan", status: "done" },
  { no: 1690, title: "Nhà Net Zero", keyword: "nhà net zero", slug: "nha-net-zero-ngan", status: "done" },
  { no: 1691, title: "Nhà Passive Smart", keyword: "nhà ultra smart", slug: "nha-ultra-smart-ngan", status: "done" },
  { no: 1692, title: "Điều Khiển Nhà Bằng App", keyword: "điều khiển nhà bằng app", slug: "dieu-khien-nha-bang-app-ngan", status: "done" },
  { no: 1693, title: "Cảm Biến Chuyển Động Nhà", keyword: "cảm biến chuyển động nhà", slug: "cam-bien-chuyen-dong-nha-ngan", status: "done" },
  { no: 1694, title: "Báo Khói Nhà", keyword: "báo khói nhà", slug: "bao-khoi-nha-ngan", status: "done" },
  { no: 1695, title: "Báo Ngập Nước Nhà", keyword: "báo ngập nước nhà", slug: "bao-ngap-nuoc-nha-ngan", status: "done" },
  { no: 1696, title: "Khóa Thông Minh Nhà", keyword: "khóa thông minh nhà", slug: "khoa-thong-minh-nha-ngan", status: "done" },
  { no: 1697, title: "Rèm Tự Động Nhà", keyword: "rèm tự động nhà", slug: "rem-tu-dong-nha-ngan", status: "done" },
  { no: 1698, title: "Tưới Cây Tự Động", keyword: "tưới cây tự động", slug: "tuoi-cay-tu-dong-ngan", status: "done" },
  { no: 1699, title: "Hút Bụi Robot Nhà", keyword: "hút bụi robot nhà", slug: "hut-bui-robot-nha-ngan", status: "done" },
  { no: 1700, title: "Máy Lọc Không Khí", keyword: "máy lọc không khí", slug: "may-loc-khong-khi-ngan", status: "done" },
  { no: 1701, title: "Máy Hút Ẩm Nhà", keyword: "máy hút ẩm nhà", slug: "may-hut-am-nha-ngan", status: "done" },
  { no: 1702, title: "Máy Cấp Khí Tươi", keyword: "máy cấp khí tươi", slug: "may-cap-khi-tuoi-ngan", status: "done" },
  { no: 1703, title: "Hệ Thống Âm Thanh Nhà", keyword: "hệ thống âm thanh nhà", slug: "he-thong-am-thanh-nha-ngan", status: "done" },
  { no: 1704, title: "Chiếu Sáng Thông Minh", keyword: "chiếu sáng thông minh", slug: "chieu-sang-thong-minh-ngan", status: "done" },
  { no: 1705, title: "Đèn Cảm Ứng Nhà", keyword: "đèn cảm ứng nhà", slug: "den-cam-ung-nha-ngan", status: "done" },
  { no: 1706, title: "Nhà Phong Cách Wabi Sabi", keyword: "nhà phong cách wabi sabi", slug: "nha-phong-cach-wabi-sabi-ngan", status: "done" },
  { no: 1707, title: "Nhà Phong Cách Japandi", keyword: "nhà phong cách japandi", slug: "nha-phong-cach-japandi-ngan", status: "done" },
  { no: 1708, title: "Nhà Phong Cách Mid Century", keyword: "nhà phong cách mid century", slug: "nha-phong-cach-mid-century-ngan", status: "done" },
  { no: 1709, title: "Nhà Phong Cách Farmhouse", keyword: "nhà phong cách farmhouse", slug: "nha-phong-cach-farmhouse-ngan", status: "done" },
  { no: 1710, title: "Nhà Phong Cách Coastal", keyword: "nhà phong cách coastal", slug: "nha-phong-cach-coastal-ngan", status: "done" },
  { no: 1711, title: "Nhà Phong Cách Bohemian", keyword: "nhà phong cách bohemian", slug: "nha-phong-cach-bohemian-ngan", status: "done" },
  { no: 1712, title: "Nhà Màu Be", keyword: "nhà màu be", slug: "nha-mau-be-ngan", status: "done" },
  { no: 1713, title: "Nhà Màu Trắng", keyword: "nhà màu trắng", slug: "nha-mau-trang-ngan", status: "done" },
  { no: 1714, title: "Nhà Màu Xám", keyword: "nhà màu xám", slug: "nha-mau-xam-ngan", status: "done" },
  { no: 1715, title: "Nhà Màu Xanh Olive", keyword: "nhà màu xanh olive", slug: "nha-mau-xanh-olive-ngan", status: "done" },
  { no: 1716, title: "Nội Thất Gỗ Óc Chó", keyword: "nội thất gỗ óc chó", slug: "noi-that-go-oc-cho-ngan", status: "done" },
  { no: 1717, title: "Nội Thất Gỗ Sồi", keyword: "nội thất gỗ sồi", slug: "noi-that-go-soi-ngan", status: "done" },
  { no: 1718, title: "Bàn Ăn Nhà Phố", keyword: "bàn ăn nhà phố", slug: "ban-an-nha-pho-ngan", status: "done" },
  { no: 1719, title: "Sofa Nhà Phố", keyword: "sofa nhà phố", slug: "sofa-nha-pho-ngan", status: "done" },
  { no: 1720, title: "Giường Ngủ Nhà", keyword: "giường ngủ nhà", slug: "giuong-ngu-nha-ngan", status: "done" },
  { no: 1721, title: "Tủ Bếp Acrylic", keyword: "tủ bếp acrylic", slug: "tu-bep-acrylic-ngan", status: "done" },
  { no: 1722, title: "Tủ Bếp Melamine", keyword: "tủ bếp melamine", slug: "tu-bep-melamine-ngan", status: "done" },
  { no: 1723, title: "Đảo Bếp Nhà", keyword: "đảo bếp nhà", slug: "dao-bep-nha-ngan", status: "done" },
  { no: 1724, title: "Quầy Bar Nhà", keyword: "quầy bar nhà", slug: "quay-bar-nha-ngan", status: "done" },
  { no: 1725, title: "Phòng Xông Hơi", keyword: "phòng xông hơi", slug: "phong-xong-hoi-ngan", status: "done" },
  { no: 1726, title: "Bồn Tắm Nằm", keyword: "bồn tắm nằm", slug: "bon-tam-nam-ngan", status: "done" },
  { no: 1727, title: "Sen Cây Mưa", keyword: "sen cây mưa", slug: "sen-cay-mua-ngan", status: "done" },
  { no: 1728, title: "Gương LED WC", keyword: "gương led wc", slug: "guong-led-wc-ngan", status: "done" },
  { no: 1729, title: "Tủ Lavabo", keyword: "tủ lavabo", slug: "tu-lavabo-ngan", status: "done" },
  { no: 1730, title: "Kệ Treo WC", keyword: "kệ treo wc", slug: "ke-treo-wc-ngan", status: "done" },
  { no: 1731, title: "Máy Sấy Tay", keyword: "máy sấy tay", slug: "may-say-tay-ngan", status: "done" },
  { no: 1732, title: "Cây Xanh Trong Nhà", keyword: "cây xanh trong nhà", slug: "cay-xanh-trong-nha-ngan", status: "done" },
  { no: 1733, title: "Tường Cây Xanh", keyword: "tường cây xanh", slug: "tuong-cay-xanh-ngan", status: "done" },
  { no: 1734, title: "Vườn Thủy Canh Nhà", keyword: "vườn thủy canh nhà", slug: "vuon-thuy-canh-nha-ngan", status: "done" },
  { no: 1735, title: "Nhà Trồng Rau Sạch", keyword: "nhà trồng rau sạch", slug: "nha-trong-rau-sach-ngan", status: "done" },
  { no: 1736, title: "Nhà Nuôi Cá Cảnh", keyword: "nhà nuôi cá cảnh", slug: "nha-nuoi-ca-canh-ngan", status: "done" },
  { no: 1737, title: "Sân Chơi Trẻ Em Trong Nhà", keyword: "sân chơi trẻ em trong nhà", slug: "san-choi-tre-em-trong-nha-ngan", status: "done" },
  { no: 1738, title: "Góc Học Tập Nhà", keyword: "góc học tập nhà", slug: "goc-hoc-tap-nha-ngan", status: "done" },
  { no: 1739, title: "Góc Làm Việc Tại Nhà", keyword: "góc làm việc tại nhà", slug: "goc-lam-viec-tai-nha-ngan", status: "done" },
  { no: 1740, title: "Phòng Zoom Meeting", keyword: "phòng zoom meeting", slug: "phong-zoom-meeting-ngan", status: "done" },
  { no: 1741, title: "Nhà Có Phòng Game", keyword: "nhà có phòng game", slug: "nha-co-phong-game-ngan", status: "done" },
  { no: 1742, title: "Nhà Có Phòng Studio", keyword: "nhà có phòng studio", slug: "nha-co-phong-studio-ngan", status: "done" },
  { no: 1743, title: "Nhà Có Góc Podcast", keyword: "nhà có góc podcast", slug: "nha-co-goc-podcast-ngan", status: "done" },
  { no: 1744, title: "Nhà Có Kệ Sách Âm", keyword: "nhà có kệ sách âm", slug: "nha-co-ke-sach-am-ngan", status: "done" },
  { no: 1745, title: "Nhà Có Ánh Sáng Giếng", keyword: "nhà có ánh sáng giếng", slug: "nha-co-anh-sang-gieng-ngan", status: "done" },
  { no: 1746, title: "Nhà Có Sân Phơi Kín", keyword: "nhà có sân phơi kín", slug: "nha-co-san-phoi-kin-ngan", status: "done" },
];
