/**
 * Lịch 100 từ khóa SEO — batch 70 (#6447–#6546).
 * Cluster: Thủ Đức/Q.7 phường + nhà cho thuê + FAQ ngân sách (indexable *-sk70).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch70: ContentCalendarItem[] = [
  { no: 6447, title: "Xây Nhà Trọn Gói Thủ Đức 2026 Mới", keyword: "xây nhà trọn gói Thủ Đức 2026 mới", slug: "xay-nha-tron-goi-thu-duc-2026-moi-sk70", status: "done" },
  { no: 6448, title: "Xây Nhà Phường Bình Chiểu", keyword: "xây nhà phường Bình Chiểu", slug: "xay-nha-phuong-binh-chieu-sk70", status: "done" },
  { no: 6449, title: "Xây Nhà Phường Hiệp Bình Chánh", keyword: "xây nhà phường Hiệp Bình Chánh", slug: "xay-nha-phuong-hiep-binh-chanh-sk70", status: "done" },
  { no: 6450, title: "Xây Nhà Phường Hiệp Bình Phước", keyword: "xây nhà phường Hiệp Bình Phước", slug: "xay-nha-phuong-hiep-binh-phuoc-sk70", status: "done" },
  { no: 6451, title: "Xây Nhà Phường Linh Chiểu", keyword: "xây nhà phường Linh Chiểu", slug: "xay-nha-phuong-linh-chieu-sk70", status: "done" },
  { no: 6452, title: "Xây Nhà Phường Linh Đông", keyword: "xây nhà phường Linh Đông", slug: "xay-nha-phuong-linh-dong-sk70", status: "done" },
  { no: 6453, title: "Xây Nhà Phường Linh Tây", keyword: "xây nhà phường Linh Tây", slug: "xay-nha-phuong-linh-tay-sk70", status: "done" },
  { no: 6454, title: "Xây Nhà Phường Trường Thọ", keyword: "xây nhà phường Trường Thọ", slug: "xay-nha-phuong-truong-tho-sk70", status: "done" },
  { no: 6455, title: "Xây Nhà Phường Tam Bình Thủ Đức", keyword: "xây nhà phường Tam Bình Thủ Đức", slug: "xay-nha-phuong-tam-binh-thu-duc-sk70", status: "done" },
  { no: 6456, title: "Xây Nhà Phường Tân Phú Thủ Đức", keyword: "xây nhà phường Tân Phú Thủ Đức", slug: "xay-nha-phuong-tan-phu-thu-duc-sk70", status: "done" },
  { no: 6457, title: "Xây Nhà Phường Phú Mỹ Quận 7", keyword: "xây nhà phường Phú Mỹ Quận 7", slug: "xay-nha-phuong-phu-my-quan-7-sk70", status: "done" },
  { no: 6458, title: "Xây Nhà Phường Tân Phong Quận 7", keyword: "xây nhà phường Tân Phong Quận 7", slug: "xay-nha-phuong-tan-phong-quan-7-sk70", status: "done" },
  { no: 6459, title: "Xây Nhà Phường Tân Quy Quận 7", keyword: "xây nhà phường Tân Quy Quận 7", slug: "xay-nha-phuong-tan-quy-quan-7-sk70", status: "done" },
  { no: 6460, title: "Xây Nhà Phường Tân Kiểng", keyword: "xây nhà phường Tân Kiểng", slug: "xay-nha-phuong-tan-kieng-sk70", status: "done" },
  { no: 6461, title: "Xây Nhà Phường Phú Thuận Quận 7", keyword: "xây nhà phường Phú Thuận Quận 7", slug: "xay-nha-phuong-phu-thuan-quan-7-sk70", status: "done" },
  { no: 6462, title: "Xây Nhà Gần Landmark 81", keyword: "xây nhà gần Landmark 81", slug: "xay-nha-gan-landmark-81-sk70", status: "done" },
  { no: 6463, title: "Xây Nhà Gần Vinhomes Grand Park", keyword: "xây nhà gần Vinhomes Grand Park", slug: "xay-nha-gan-vinhomes-grand-park-sk70", status: "done" },
  { no: 6464, title: "Xây Nhà Gần Phú Mỹ Hưng", keyword: "xây nhà gần Phú Mỹ Hưng", slug: "xay-nha-gan-phu-my-hung-sk70", status: "done" },
  { no: 6465, title: "Xây Nhà Gần Đại Học Quốc Gia", keyword: "xây nhà gần Đại học Quốc gia", slug: "xay-nha-gan-dai-hoc-quoc-gia-sk70", status: "done" },
  { no: 6466, title: "Xây Nhà Gần Suối Tiên", keyword: "xây nhà gần Suối Tiên", slug: "xay-nha-gan-suoi-tien-sk70", status: "done" },

  { no: 6467, title: "Cải Tạo Nhà Thủ Đức 2026", keyword: "cải tạo nhà Thủ Đức 2026", slug: "cai-tao-nha-thu-duc-2026-sk70", status: "done" },
  { no: 6468, title: "Cải Tạo Nhà Quận 7 2026", keyword: "cải tạo nhà Quận 7 2026", slug: "cai-tao-nha-quan-7-2026-sk70", status: "done" },
  { no: 6469, title: "Cải Tạo Nhà Cho Thuê Nguyên Căn", keyword: "cải tạo nhà cho thuê nguyên căn", slug: "cai-tao-nha-cho-thue-nguyen-can-sk70", status: "done" },
  { no: 6470, title: "Cải Tạo Nhà Cho Thuê Từng Tầng", keyword: "cải tạo nhà cho thuê từng tầng", slug: "cai-tao-nha-cho-thue-tung-tang-sk70", status: "done" },
  { no: 6471, title: "Cải Tạo Nhà Thêm Studio Airbnb", keyword: "cải tạo nhà thêm studio Airbnb", slug: "cai-tao-nha-them-studio-airbnb-sk70", status: "done" },
  { no: 6472, title: "Cải Tạo Nhà Thêm Phòng Sleepbox", keyword: "cải tạo nhà thêm phòng sleepbox", slug: "cai-tao-nha-them-phong-sleepbox-sk70", status: "done" },
  { no: 6473, title: "Cải Tạo Nhà Đổi Mặt Tiền Kính", keyword: "cải tạo nhà đổi mặt tiền kính", slug: "cai-tao-nha-doi-mat-tien-kinh-sk70", status: "done" },
  { no: 6474, title: "Cải Tạo Nhà Đổi Mặt Tiền Lam", keyword: "cải tạo nhà đổi mặt tiền lam", slug: "cai-tao-nha-doi-mat-tien-lam-sk70", status: "done" },
  { no: 6475, title: "Sửa Nhà Thấm Sân Thượng Thủ Đức", keyword: "sửa nhà thấm sân thượng Thủ Đức", slug: "sua-nha-tham-san-thuong-thu-duc-sk70", status: "done" },
  { no: 6476, title: "Sửa Nhà Thấm Tường Quận 7", keyword: "sửa nhà thấm tường Quận 7", slug: "sua-nha-tham-tuong-quan-7-sk70", status: "done" },
  { no: 6477, title: "Sửa Nhà Nứt Dầm Sàn", keyword: "sửa nhà nứt dầm sàn", slug: "sua-nha-nut-dam-san-sk70", status: "done" },
  { no: 6478, title: "Sửa Hệ Thống Nước Nóng Trung Tâm", keyword: "sửa hệ thống nước nóng trung tâm", slug: "sua-he-thong-nuoc-nong-trung-tam-sk70", status: "done" },
  { no: 6479, title: "Thay Toàn Bộ Ống PVC Nhà Cũ", keyword: "thay toàn bộ ống PVC nhà cũ", slug: "thay-toan-bo-ong-pvc-nha-cu-sk70", status: "done" },
  { no: 6480, title: "Nâng Tầng Nhà Cho Thuê", keyword: "nâng tầng nhà cho thuê", slug: "nang-tang-nha-cho-thue-sk70", status: "done" },
  { no: 6481, title: "Cải Tạo Nhà Thành Mini Hotel", keyword: "cải tạo nhà thành mini hotel", slug: "cai-tao-nha-thanh-mini-hotel-sk70", status: "done" },
  { no: 6482, title: "Cải Tạo Nhà Thành Homestay Thủ Đức", keyword: "cải tạo nhà thành homestay Thủ Đức", slug: "cai-tao-nha-thanh-homestay-thu-duc-sk70", status: "done" },
  { no: 6483, title: "Cải Tạo Nhà Cho Sinh Viên Thuê", keyword: "cải tạo nhà cho sinh viên thuê", slug: "cai-tao-nha-cho-sinh-vien-thue-sk70", status: "done" },
  { no: 6484, title: "Sửa Chữa Nhà Sau Lũ Ngập", keyword: "sửa chữa nhà sau lũ ngập", slug: "sua-chua-nha-sau-lu-ngap-sk70", status: "done" },
  { no: 6485, title: "Cải Tạo Nhà Giảm Nhiệt Độ Trong Nhà", keyword: "cải tạo nhà giảm nhiệt độ trong nhà", slug: "cai-tao-nha-giam-nhiet-do-trong-nha-sk70", status: "done" },
  { no: 6486, title: "Cải Tạo Nhà Tăng Diện Tích Sử Dụng", keyword: "cải tạo nhà tăng diện tích sử dụng", slug: "cai-tao-nha-tang-dien-tich-su-dung-sk70", status: "done" },

  { no: 6487, title: "Đơn Giá Xây Nhà Cho Thuê 2026", keyword: "đơn giá xây nhà cho thuê 2026", slug: "don-gia-xay-nha-cho-thue-2026-sk70", status: "done" },
  { no: 6488, title: "Chi Phí Xây Nhà 8 Phòng Cho Thuê", keyword: "chi phí xây nhà 8 phòng cho thuê", slug: "chi-phi-xay-nha-8-phong-cho-thue-sk70", status: "done" },
  { no: 6489, title: "Chi Phí Xây Nhà 4×19 Trọn Gói", keyword: "chi phí xây nhà 4x19 trọn gói", slug: "chi-phi-xay-nha-4x19-tron-goi-sk70", status: "done" },
  { no: 6490, title: "Chi Phí Xây Nhà 5×21 Trọn Gói", keyword: "chi phí xây nhà 5x21 trọn gói", slug: "chi-phi-xay-nha-5x21-tron-goi-sk70", status: "done" },
  { no: 6491, title: "Chi Phí Xây Nhà 6×16 Trọn Gói", keyword: "chi phí xây nhà 6x16 trọn gói", slug: "chi-phi-xay-nha-6x16-tron-goi-sk70", status: "done" },
  { no: 6492, title: "Báo Giá Thiết Kế Nhà Cho Thuê", keyword: "báo giá thiết kế nhà cho thuê", slug: "bao-gia-thiet-ke-nha-cho-thue-sk70", status: "done" },
  { no: 6493, title: "Báo Giá Lắp Đồng Hồ Điện Từng Phòng", keyword: "báo giá lắp đồng hồ điện từng phòng", slug: "bao-gia-lap-dong-ho-dien-tung-phong-sk70", status: "done" },
  { no: 6494, title: "Ngân Sách Xây Nhà 9 Tỷ TP.HCM", keyword: "ngân sách xây nhà 9 tỷ TP.HCM", slug: "ngan-sach-xay-nha-9-ty-tphcm-sk70", status: "done" },
  { no: 6495, title: "Ngân Sách Cải Tạo Nhà 400 Triệu", keyword: "ngân sách cải tạo nhà 400 triệu", slug: "ngan-sach-cai-tao-nha-400-trieu-sk70", status: "done" },
  { no: 6496, title: "Chi Phí Chống Thấm Nhà Cho Thuê", keyword: "chi phí chống thấm nhà cho thuê", slug: "chi-phi-chong-tham-nha-cho-thue-sk70", status: "done" },
  { no: 6497, title: "Chi Phí Làm WC Riêng Từng Phòng", keyword: "chi phí làm WC riêng từng phòng", slug: "chi-phi-lam-wc-rieng-tung-phong-sk70", status: "done" },
  { no: 6498, title: "Báo Giá Sơn Nhà Cho Thuê", keyword: "báo giá sơn nhà cho thuê", slug: "bao-gia-son-nha-cho-thue-sk70", status: "done" },
  { no: 6499, title: "Báo Giá Lát Gạch Phòng Trọ", keyword: "báo giá lát gạch phòng trọ", slug: "bao-gia-lat-gach-phong-tro-sk70", status: "done" },
  { no: 6500, title: "Chi Phí Lắp Camera Nhà Cho Thuê", keyword: "chi phí lắp camera nhà cho thuê", slug: "chi-phi-lap-camera-nha-cho-thue-sk70", status: "done" },
  { no: 6501, title: "Cách Ước ROI Xây Nhà Cho Thuê", keyword: "cách ước ROI xây nhà cho thuê", slug: "cach-uoc-roi-xay-nha-cho-thue-sk70", status: "done" },

  { no: 6502, title: "Thiết Kế Nhà Cho Thuê 1 Trệt 3 Lầu", keyword: "thiết kế nhà cho thuê 1 trệt 3 lầu", slug: "thiet-ke-nha-cho-thue-1-tret-3-lau-sk70", status: "done" },
  { no: 6503, title: "Thiết Kế Nhà Cho Thuê Mặt Tiền 4m", keyword: "thiết kế nhà cho thuê mặt tiền 4m", slug: "thiet-ke-nha-cho-thue-mat-tien-4m-sk70", status: "done" },
  { no: 6504, title: "Thiết Kế Nhà Cho Thuê Mặt Tiền 5m", keyword: "thiết kế nhà cho thuê mặt tiền 5m", slug: "thiet-ke-nha-cho-thue-mat-tien-5m-sk70", status: "done" },
  { no: 6505, title: "Thiết Kế Nhà Phố Có Phòng Manager", keyword: "thiết kế nhà phố có phòng manager", slug: "thiet-ke-nha-pho-co-phong-manager-sk70", status: "done" },
  { no: 6506, title: "Thiết Kế Nhà Phố Có Sân Để Xe Máy", keyword: "thiết kế nhà phố có sân để xe máy", slug: "thiet-ke-nha-pho-co-san-de-xe-may-sk70", status: "done" },
  { no: 6507, title: "Thiết Kế Nhà Phố 8 Phòng Ngủ", keyword: "thiết kế nhà phố 8 phòng ngủ", slug: "thiet-ke-nha-pho-8-phong-ngu-sk70", status: "done" },
  { no: 6508, title: "Thiết Kế Nhà Phố Có Phòng Giặt Chung", keyword: "thiết kế nhà phố có phòng giặt chung", slug: "thiet-ke-nha-pho-co-phong-giat-chung-sk70", status: "done" },
  { no: 6509, title: "Thiết Kế Nhà Phố Có Kho Rác", keyword: "thiết kế nhà phố có kho rác", slug: "thiet-ke-nha-pho-co-kho-rac-sk70", status: "done" },
  { no: 6510, title: "Thiết Kế Biệt Thự Phố Thủ Đức", keyword: "thiết kế biệt thự phố Thủ Đức", slug: "thiet-ke-biet-thu-pho-thu-duc-sk70", status: "done" },
  { no: 6511, title: "Thiết Kế Nhà Vườn Nhà Bè", keyword: "thiết kế nhà vườn Nhà Bè", slug: "thiet-ke-nha-vuon-nha-be-sk70", status: "done" },
  { no: 6512, title: "Mẫu Nhà Cho Thuê 2026 TP.HCM", keyword: "mẫu nhà cho thuê 2026 TP.HCM", slug: "mau-nha-cho-thue-2026-tphcm-sk70", status: "done" },
  { no: 6513, title: "Mẫu Nhà Phố Mặt Tiền 7m 2026", keyword: "mẫu nhà phố mặt tiền 7m 2026", slug: "mau-nha-pho-mat-tien-7m-2026-sk70", status: "done" },
  { no: 6514, title: "Thiết Kế Bếp Mini Phòng Trọ", keyword: "thiết kế bếp mini phòng trọ", slug: "thiet-ke-bep-mini-phong-tro-sk70", status: "done" },
  { no: 6515, title: "Thiết Kế Cầu Thang Nhà Cho Thuê", keyword: "thiết kế cầu thang nhà cho thuê", slug: "thiet-ke-cau-thang-nha-cho-thue-sk70", status: "done" },
  { no: 6516, title: "Thiết Kế Giếng Trời Nhà Cho Thuê", keyword: "thiết kế giếng trời nhà cho thuê", slug: "thiet-ke-gieng-troi-nha-cho-thue-sk70", status: "done" },

  { no: 6517, title: "Xây Nhà Tách Điện Nước Từng Phòng", keyword: "xây nhà tách điện nước từng phòng", slug: "xay-nha-tach-dien-nuoc-tung-phong-sk70", status: "done" },
  { no: 6518, title: "Xây Nhà Có Lối Đi Chung", keyword: "xây nhà có lối đi chung", slug: "xay-nha-co-loi-di-chung-sk70", status: "done" },
  { no: 6519, title: "Đổ Móng Nhà Nhiều Phòng Thuê", keyword: "đổ móng nhà nhiều phòng thuê", slug: "do-mong-nha-nhieu-phong-thue-sk70", status: "done" },
  { no: 6520, title: "Đổ Sàn Cách Âm Phòng Thuê", keyword: "đổ sàn cách âm phòng thuê", slug: "do-san-cach-am-phong-thue-sk70", status: "done" },
  { no: 6521, title: "Làm Mái Nhà Cho Thuê Chống Thấm", keyword: "làm mái nhà cho thuê chống thấm", slug: "lam-mai-nha-cho-thue-chong-tham-sk70", status: "done" },
  { no: 6522, title: "Làm Sân Để Xe Nhà Cho Thuê", keyword: "làm sân để xe nhà cho thuê", slug: "lam-san-de-xe-nha-cho-thue-sk70", status: "done" },
  { no: 6523, title: "Chống Nóng Phòng Thuê Mái Tôn", keyword: "chống nóng phòng thuê mái tôn", slug: "chong-nong-phong-thue-mai-ton-sk70", status: "done" },
  { no: 6524, title: "Lắp Cửa Phòng Thuê An Toàn", keyword: "lắp cửa phòng thuê an toàn", slug: "lap-cua-phong-thue-an-toan-sk70", status: "done" },
  { no: 6525, title: "Ốp Gạch WC Phòng Trọ", keyword: "ốp gạch WC phòng trọ", slug: "op-gach-wc-phong-tro-sk70", status: "done" },
  { no: 6526, title: "Sơn Trong Nhà Cho Thuê Bền", keyword: "sơn trong nhà cho thuê bền", slug: "son-trong-nha-cho-thue-ben-sk70", status: "done" },
  { no: 6527, title: "Lát Gạch Hành Lang Nhà Trọ", keyword: "lát gạch hành lang nhà trọ", slug: "lat-gach-hanh-lang-nha-tro-sk70", status: "done" },
  { no: 6528, title: "Làm Vách Ngăn Phòng Trọ", keyword: "làm vách ngăn phòng trọ", slug: "lam-vach-ngan-phong-tro-sk70", status: "done" },
  { no: 6529, title: "Lắp Khóa Vân Tay Phòng Thuê", keyword: "lắp khóa vân tay phòng thuê", slug: "lap-khoa-van-tay-phong-thue-sk70", status: "done" },
  { no: 6530, title: "Lắp Wifi Toàn Nhà Cho Thuê", keyword: "lắp wifi toàn nhà cho thuê", slug: "lap-wifi-toan-nha-cho-thue-sk70", status: "done" },
  { no: 6531, title: "Gia Cố Nhà Cũ Trước Khi Cho Thuê", keyword: "gia cố nhà cũ trước khi cho thuê", slug: "gia-co-nha-cu-truoc-khi-cho-thue-sk70", status: "done" },

  { no: 6532, title: "Xây Nhà Trọn Gói Củ Chi Mới", keyword: "xây nhà trọn gói Củ Chi mới", slug: "xay-nha-tron-goi-cu-chi-moi-sk70", status: "done" },
  { no: 6533, title: "Xây Nhà Trọn Gói Hóc Môn Mới", keyword: "xây nhà trọn gói Hóc Môn mới", slug: "xay-nha-tron-goi-hoc-mon-moi-sk70", status: "done" },
  { no: 6534, title: "Xây Nhà Trọn Gói Bình Chánh Mới", keyword: "xây nhà trọn gói Bình Chánh mới", slug: "xay-nha-tron-goi-binh-chanh-moi-sk70", status: "done" },
  { no: 6535, title: "Xây Nhà Trọn Gói Nhà Bè Mới", keyword: "xây nhà trọn gói Nhà Bè mới", slug: "xay-nha-tron-goi-nha-be-moi-sk70", status: "done" },
  { no: 6536, title: "Xây Nhà Trọn Gói Cần Đước 2026", keyword: "xây nhà trọn gói Cần Đước 2026", slug: "xay-nha-tron-goi-can-duoc-2026-sk70", status: "done" },
  { no: 6537, title: "Xây Nhà Trọn Gói Tân Uyên 2026", keyword: "xây nhà trọn gói Tân Uyên 2026", slug: "xay-nha-tron-goi-tan-uyen-2026-sk70", status: "done" },
  { no: 6538, title: "Xây Nhà Trọn Gói Bến Cát 2026", keyword: "xây nhà trọn gói Bến Cát 2026", slug: "xay-nha-tron-goi-ben-cat-2026-sk70", status: "done" },
  { no: 6539, title: "Cải Tạo Nhà Củ Chi 2026", keyword: "cải tạo nhà Củ Chi 2026", slug: "cai-tao-nha-cu-chi-2026-sk70", status: "done" },
  { no: 6540, title: "Cải Tạo Nhà Hóc Môn 2026", keyword: "cải tạo nhà Hóc Môn 2026", slug: "cai-tao-nha-hoc-mon-2026-sk70", status: "done" },
  { no: 6541, title: "Xây Nhà Cho Thuê Có Cần PCCC", keyword: "xây nhà cho thuê có cần PCCC", slug: "xay-nha-cho-thue-co-can-pccc-sk70", status: "done" },
  { no: 6542, title: "Nhà Cho Thuê Nên Bao Nhiêu Phòng", keyword: "nhà cho thuê nên bao nhiêu phòng", slug: "nha-cho-thue-nen-bao-nhieu-phong-sk70", status: "done" },
  { no: 6543, title: "Xây Nhà Cho Thuê Có Nên Làm Thang Máy", keyword: "xây nhà cho thuê có nên làm thang máy", slug: "xay-nha-cho-thue-co-nen-lam-thang-may-sk70", status: "done" },
  { no: 6544, title: "Cách Chọn Vật Tư Nhà Cho Thuê", keyword: "cách chọn vật tư nhà cho thuê", slug: "cach-chon-vat-tu-nha-cho-thue-sk70", status: "done" },
  { no: 6545, title: "Checklist Bàn Giao Nhà Cho Thuê", keyword: "checklist bàn giao nhà cho thuê", slug: "checklist-ban-giao-nha-cho-thue-sk70", status: "done" },
  { no: 6546, title: "Khi Nào Nên Đầu Tư Xây Nhà Cho Thuê", keyword: "khi nào nên đầu tư xây nhà cho thuê", slug: "khi-nao-nen-dau-tu-xay-nha-cho-thue-sk70", status: "done" },
];
