/**
 * Lịch 100 từ khóa SEO — batch 72 (#6647–#6746).
 * Cluster: Q.4/Q.5/Q.6 + nội thất hoàn thiện + FAQ tiến độ (indexable *-sk72).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch72: ContentCalendarItem[] = [
  { no: 6647, title: "Xây Nhà Trọn Gói Quận 4 Mới 2026", keyword: "xây nhà trọn gói Quận 4 mới 2026", slug: "xay-nha-tron-goi-quan-4-moi-2026-sk72", status: "done" },
  { no: 6648, title: "Xây Nhà Trọn Gói Quận 5 Mới 2026", keyword: "xây nhà trọn gói Quận 5 mới 2026", slug: "xay-nha-tron-goi-quan-5-moi-2026-sk72", status: "done" },
  { no: 6649, title: "Xây Nhà Trọn Gói Quận 6 Mới 2026", keyword: "xây nhà trọn gói Quận 6 mới 2026", slug: "xay-nha-tron-goi-quan-6-moi-2026-sk72", status: "done" },
  { no: 6650, title: "Xây Nhà Phường 1 Quận 4", keyword: "xây nhà phường 1 Quận 4", slug: "xay-nha-phuong-1-quan-4-sk72", status: "done" },
  { no: 6651, title: "Xây Nhà Phường 2 Quận 4", keyword: "xây nhà phường 2 Quận 4", slug: "xay-nha-phuong-2-quan-4-sk72", status: "done" },
  { no: 6652, title: "Xây Nhà Phường 6 Quận 4", keyword: "xây nhà phường 6 Quận 4", slug: "xay-nha-phuong-6-quan-4-sk72", status: "done" },
  { no: 6653, title: "Xây Nhà Phường 13 Quận 4", keyword: "xây nhà phường 13 Quận 4", slug: "xay-nha-phuong-13-quan-4-sk72", status: "done" },
  { no: 6654, title: "Xây Nhà Phường 15 Quận 4", keyword: "xây nhà phường 15 Quận 4", slug: "xay-nha-phuong-15-quan-4-sk72", status: "done" },
  { no: 6655, title: "Xây Nhà Phường 1 Quận 5", keyword: "xây nhà phường 1 Quận 5", slug: "xay-nha-phuong-1-quan-5-sk72", status: "done" },
  { no: 6656, title: "Xây Nhà Phường 4 Quận 5", keyword: "xây nhà phường 4 Quận 5", slug: "xay-nha-phuong-4-quan-5-sk72", status: "done" },
  { no: 6657, title: "Xây Nhà Phường 7 Quận 5", keyword: "xây nhà phường 7 Quận 5", slug: "xay-nha-phuong-7-quan-5-sk72", status: "done" },
  { no: 6658, title: "Xây Nhà Phường 9 Quận 5", keyword: "xây nhà phường 9 Quận 5", slug: "xay-nha-phuong-9-quan-5-sk72", status: "done" },
  { no: 6659, title: "Xây Nhà Phường 14 Quận 5", keyword: "xây nhà phường 14 Quận 5", slug: "xay-nha-phuong-14-quan-5-sk72", status: "done" },
  { no: 6660, title: "Xây Nhà Phường 1 Quận 6", keyword: "xây nhà phường 1 Quận 6", slug: "xay-nha-phuong-1-quan-6-sk72", status: "done" },
  { no: 6661, title: "Xây Nhà Phường 2 Quận 6", keyword: "xây nhà phường 2 Quận 6", slug: "xay-nha-phuong-2-quan-6-sk72", status: "done" },
  { no: 6662, title: "Xây Nhà Phường 7 Quận 6", keyword: "xây nhà phường 7 Quận 6", slug: "xay-nha-phuong-7-quan-6-sk72", status: "done" },
  { no: 6663, title: "Xây Nhà Phường 10 Quận 6", keyword: "xây nhà phường 10 Quận 6", slug: "xay-nha-phuong-10-quan-6-sk72", status: "done" },
  { no: 6664, title: "Xây Nhà Phường 13 Quận 6", keyword: "xây nhà phường 13 Quận 6", slug: "xay-nha-phuong-13-quan-6-sk72", status: "done" },
  { no: 6665, title: "Xây Nhà Gần Cầu Khánh Hội", keyword: "xây nhà gần cầu Khánh Hội", slug: "xay-nha-gan-cau-khanh-hoi-sk72", status: "done" },
  { no: 6666, title: "Xây Nhà Gần Chợ An Đông", keyword: "xây nhà gần chợ An Đông", slug: "xay-nha-gan-cho-an-dong-sk72", status: "done" },

  { no: 6667, title: "Cải Tạo Nhà Quận 4 2026", keyword: "cải tạo nhà Quận 4 2026", slug: "cai-tao-nha-quan-4-2026-sk72", status: "done" },
  { no: 6668, title: "Cải Tạo Nhà Quận 5 2026", keyword: "cải tạo nhà Quận 5 2026", slug: "cai-tao-nha-quan-5-2026-sk72", status: "done" },
  { no: 6669, title: "Cải Tạo Nhà Quận 6 2026", keyword: "cải tạo nhà Quận 6 2026", slug: "cai-tao-nha-quan-6-2026-sk72", status: "done" },
  { no: 6670, title: "Cải Tạo Nhà Shophouse Quận 5", keyword: "cải tạo nhà shophouse Quận 5", slug: "cai-tao-nha-shophouse-quan-5-sk72", status: "done" },
  { no: 6671, title: "Cải Tạo Nhà Thêm Quán Ăn", keyword: "cải tạo nhà thêm quán ăn", slug: "cai-tao-nha-them-quan-an-sk72", status: "done" },
  { no: 6672, title: "Cải Tạo Nhà Thêm Tiệm Vàng", keyword: "cải tạo nhà thêm tiệm vàng", slug: "cai-tao-nha-them-tiem-vang-sk72", status: "done" },
  { no: 6673, title: "Cải Tạo Nhà Thêm Phòng Khám Nha", keyword: "cải tạo nhà thêm phòng khám nha", slug: "cai-tao-nha-them-phong-kham-nha-sk72", status: "done" },
  { no: 6674, title: "Cải Tạo Nhà Đổi Mặt Tiền Gạch Thẻ", keyword: "cải tạo nhà đổi mặt tiền gạch thẻ", slug: "cai-tao-nha-doi-mat-tien-gach-the-sk72", status: "done" },
  { no: 6675, title: "Sửa Nhà Thấm Trần Quận 4", keyword: "sửa nhà thấm trần Quận 4", slug: "sua-nha-tham-tran-quan-4-sk72", status: "done" },
  { no: 6676, title: "Sửa Nhà Thấm Tường Quận 5", keyword: "sửa nhà thấm tường Quận 5", slug: "sua-nha-tham-tuong-quan-5-sk72", status: "done" },
  { no: 6677, title: "Sửa Nhà Nứt Cột Quận 6", keyword: "sửa nhà nứt cột Quận 6", slug: "sua-nha-nut-cot-quan-6-sk72", status: "done" },
  { no: 6678, title: "Sửa Hệ Thống Điện Nhà Cũ Quận 5", keyword: "sửa hệ thống điện nhà cũ Quận 5", slug: "sua-he-thong-dien-nha-cu-quan-5-sk72", status: "done" },
  { no: 6679, title: "Thay Cửa Nhôm Kính Toàn Nhà", keyword: "thay cửa nhôm kính toàn nhà", slug: "thay-cua-nhom-kinh-toan-nha-sk72", status: "done" },
  { no: 6680, title: "Nâng Tầng Nhà Liền Kề Quận 5", keyword: "nâng tầng nhà liền kề Quận 5", slug: "nang-tang-nha-lien-ke-quan-5-sk72", status: "done" },
  { no: 6681, title: "Cải Tạo Nhà Thành Spa Mini", keyword: "cải tạo nhà thành spa mini", slug: "cai-tao-nha-thanh-spa-mini-sk72", status: "done" },
  { no: 6682, title: "Cải Tạo Nhà Thành Tiệm Nail", keyword: "cải tạo nhà thành tiệm nail", slug: "cai-tao-nha-thanh-tiem-nail-sk72", status: "done" },
  { no: 6683, title: "Cải Tạo Nhà Cho Gia Đình 4 Thế Hệ", keyword: "cải tạo nhà cho gia đình 4 thế hệ", slug: "cai-tao-nha-cho-gia-dinh-4-the-he-sk72", status: "done" },
  { no: 6684, title: "Sửa Chữa Nhà Sau Cải Tạo Mặt Tiền", keyword: "sửa chữa nhà sau cải tạo mặt tiền", slug: "sua-chua-nha-sau-cai-tao-mat-tien-sk72", status: "done" },
  { no: 6685, title: "Cải Tạo Nhà Giảm Nắng Mặt Tiền", keyword: "cải tạo nhà giảm nắng mặt tiền", slug: "cai-tao-nha-giam-nang-mat-tien-sk72", status: "done" },
  { no: 6686, title: "Cải Tạo Nhà Tăng Chiều Rộng Cảm Giác", keyword: "cải tạo nhà tăng chiều rộng cảm giác", slug: "cai-tao-nha-tang-chieu-rong-cam-giac-sk72", status: "done" },

  { no: 6687, title: "Đơn Giá Hoàn Thiện Nội Thất 2026", keyword: "đơn giá hoàn thiện nội thất 2026", slug: "don-gia-hoan-thien-noi-that-2026-sk72", status: "done" },
  { no: 6688, title: "Chi Phí Làm Tủ Bếp Nhà Phố", keyword: "chi phí làm tủ bếp nhà phố", slug: "chi-phi-lam-tu-bep-nha-pho-sk72", status: "done" },
  { no: 6689, title: "Chi Phí Xây Nhà 4×11 Trọn Gói", keyword: "chi phí xây nhà 4x11 trọn gói", slug: "chi-phi-xay-nha-4x11-tron-goi-sk72", status: "done" },
  { no: 6690, title: "Chi Phí Xây Nhà 5×13 Trọn Gói", keyword: "chi phí xây nhà 5x13 trọn gói", slug: "chi-phi-xay-nha-5x13-tron-goi-sk72", status: "done" },
  { no: 6691, title: "Chi Phí Xây Nhà 6×15 Trọn Gói", keyword: "chi phí xây nhà 6x15 trọn gói", slug: "chi-phi-xay-nha-6x15-tron-goi-sk72", status: "done" },
  { no: 6692, title: "Báo Giá Làm Trần Thạch Cao Toàn Nhà", keyword: "báo giá làm trần thạch cao toàn nhà", slug: "bao-gia-lam-tran-thach-cao-toan-nha-sk72", status: "done" },
  { no: 6693, title: "Báo Giá Lắp Cửa Gỗ Công Nghiệp", keyword: "báo giá lắp cửa gỗ công nghiệp", slug: "bao-gia-lap-cua-go-cong-nghiep-sk72", status: "done" },
  { no: 6694, title: "Ngân Sách Xây Nhà 3,5 Tỷ TP.HCM", keyword: "ngân sách xây nhà 3.5 tỷ TP.HCM", slug: "ngan-sach-xay-nha-3-5-ty-tphcm-sk72", status: "done" },
  { no: 6695, title: "Ngân Sách Cải Tạo Nhà 250 Triệu", keyword: "ngân sách cải tạo nhà 250 triệu", slug: "ngan-sach-cai-tao-nha-250-trieu-sk72", status: "done" },
  { no: 6696, title: "Chi Phí Hoàn Thiện WC Cao Cấp", keyword: "chi phí hoàn thiện WC cao cấp", slug: "chi-phi-hoan-thien-wc-cao-cap-sk72", status: "done" },
  { no: 6697, title: "Chi Phí Làm Tủ Quần Áo Âm Tường", keyword: "chi phí làm tủ quần áo âm tường", slug: "chi-phi-lam-tu-quan-ao-am-tuong-sk72", status: "done" },
  { no: 6698, title: "Báo Giá Sơn Nội Thất Toàn Nhà", keyword: "báo giá sơn nội thất toàn nhà", slug: "bao-gia-son-noi-that-toan-nha-sk72", status: "done" },
  { no: 6699, title: "Báo Giá Lát Sàn Gỗ Toàn Nhà", keyword: "báo giá lát sàn gỗ toàn nhà", slug: "bao-gia-lat-san-go-toan-nha-sk72", status: "done" },
  { no: 6700, title: "Chi Phí Lắp Hệ Thống Đèn LED", keyword: "chi phí lắp hệ thống đèn LED", slug: "chi-phi-lap-he-thong-den-led-sk72", status: "done" },
  { no: 6701, title: "Cách Ước Chi Phí Nội Thất Nhà Phố", keyword: "cách ước chi phí nội thất nhà phố", slug: "cach-uoc-chi-phi-noi-that-nha-pho-sk72", status: "done" },

  { no: 6702, title: "Thiết Kế Nội Thất Nhà Phố 4m", keyword: "thiết kế nội thất nhà phố 4m", slug: "thiet-ke-noi-that-nha-pho-4m-sk72", status: "done" },
  { no: 6703, title: "Thiết Kế Nội Thất Nhà Phố 5m", keyword: "thiết kế nội thất nhà phố 5m", slug: "thiet-ke-noi-that-nha-pho-5m-sk72", status: "done" },
  { no: 6704, title: "Thiết Kế Phòng Khách Nhà Ống Hẹp", keyword: "thiết kế phòng khách nhà ống hẹp", slug: "thiet-ke-phong-khach-nha-ong-hep-sk72", status: "done" },
  { no: 6705, title: "Thiết Kế Phòng Ngủ Master Có Ban Công", keyword: "thiết kế phòng ngủ master có ban công", slug: "thiet-ke-phong-ngu-master-co-ban-cong-sk72", status: "done" },
  { no: 6706, title: "Thiết Kế Phòng Thờ Nhà Phố Hiện Đại", keyword: "thiết kế phòng thờ nhà phố hiện đại", slug: "thiet-ke-phong-tho-nha-pho-hien-dai-sk72", status: "done" },
  { no: 6707, title: "Thiết Kế Nhà Phố Có Phòng Karaoke Mini", keyword: "thiết kế nhà phố có phòng karaoke mini", slug: "thiet-ke-nha-pho-co-phong-karaoke-mini-sk72", status: "done" },
  { no: 6708, title: "Thiết Kế Nhà Phố Có Phòng Đọc Sách", keyword: "thiết kế nhà phố có phòng đọc sách", slug: "thiet-ke-nha-pho-co-phong-doc-sach-sk72", status: "done" },
  { no: 6709, title: "Thiết Kế Nhà Phố Có Phòng Giặt Phơi", keyword: "thiết kế nhà phố có phòng giặt phơi", slug: "thiet-ke-nha-pho-co-phong-giat-phoi-sk72", status: "done" },
  { no: 6710, title: "Thiết Kế Biệt Thự Phố Quận 5", keyword: "thiết kế biệt thự phố Quận 5", slug: "thiet-ke-biet-thu-pho-quan-5-sk72", status: "done" },
  { no: 6711, title: "Thiết Kế Nhà Vườn Long An Mới", keyword: "thiết kế nhà vườn Long An mới", slug: "thiet-ke-nha-vuon-long-an-moi-sk72", status: "done" },
  { no: 6712, title: "Mẫu Nội Thất Nhà Phố 2026", keyword: "mẫu nội thất nhà phố 2026", slug: "mau-noi-that-nha-pho-2026-sk72", status: "done" },
  { no: 6713, title: "Mẫu Nhà Phố Mặt Tiền 3m 2026", keyword: "mẫu nhà phố mặt tiền 3m 2026", slug: "mau-nha-pho-mat-tien-3m-2026-sk72", status: "done" },
  { no: 6714, title: "Thiết Kế Bếp Liên Thông Phòng Khách", keyword: "thiết kế bếp liên thông phòng khách", slug: "thiet-ke-bep-lien-thong-phong-khach-sk72", status: "done" },
  { no: 6715, title: "Thiết Kế Cầu Thang Góc Nhà Hẹp", keyword: "thiết kế cầu thang góc nhà hẹp", slug: "thiet-ke-cau-thang-goc-nha-hep-sk72", status: "done" },
  { no: 6716, title: "Thiết Kế Giếng Trời Nhà Ống Hẹp", keyword: "thiết kế giếng trời nhà ống hẹp", slug: "thiet-ke-gieng-troi-nha-ong-hep-sk72", status: "done" },

  { no: 6717, title: "Xây Nhà Hoàn Thiện Gói Cơ Bản", keyword: "xây nhà hoàn thiện gói cơ bản", slug: "xay-nha-hoan-thien-goi-co-ban-sk72", status: "done" },
  { no: 6718, title: "Xây Nhà Hoàn Thiện Gói Cao Cấp", keyword: "xây nhà hoàn thiện gói cao cấp", slug: "xay-nha-hoan-thien-goi-cao-cap-sk72", status: "done" },
  { no: 6719, title: "Đổ Móng Nhà Hẻm Quận 5", keyword: "đổ móng nhà hẻm Quận 5", slug: "do-mong-nha-hem-quan-5-sk72", status: "done" },
  { no: 6720, title: "Đổ Sàn Nhà Liền Kề Quận 6", keyword: "đổ sàn nhà liền kề Quận 6", slug: "do-san-nha-lien-ke-quan-6-sk72", status: "done" },
  { no: 6721, title: "Làm Mái Thái Nhà Phố Quận 4", keyword: "làm mái Thái nhà phố Quận 4", slug: "lam-mai-thai-nha-pho-quan-4-sk72", status: "done" },
  { no: 6722, title: "Làm Sân Thượng Phơi Đồ", keyword: "làm sân thượng phơi đồ", slug: "lam-san-thuong-phoi-do-sk72", status: "done" },
  { no: 6723, title: "Chống Nóng Tường Tiếp Giáp Hẻm", keyword: "chống nóng tường tiếp giáp hẻm", slug: "chong-nong-tuong-tiep-giap-hem-sk72", status: "done" },
  { no: 6724, title: "Lắp Cửa Sổ Lấy Sáng Nhà Ống", keyword: "lắp cửa sổ lấy sáng nhà ống", slug: "lap-cua-so-lay-sang-nha-ong-sk72", status: "done" },
  { no: 6725, title: "Ốp Gạch Thẻ Mặt Tiền Quận 5", keyword: "ốp gạch thẻ mặt tiền Quận 5", slug: "op-gach-the-mat-tien-quan-5-sk72", status: "done" },
  { no: 6726, title: "Sơn Ngoại Thất Mặt Tiền Shophouse", keyword: "sơn ngoại thất mặt tiền shophouse", slug: "son-ngoai-that-mat-tien-shophouse-sk72", status: "done" },
  { no: 6727, title: "Lát Gạch 80x80 Phòng Khách", keyword: "lát gạch 80x80 phòng khách", slug: "lat-gach-80x80-phong-khach-sk72", status: "done" },
  { no: 6728, title: "Làm Vách Kính Phòng Khách", keyword: "làm vách kính phòng khách", slug: "lam-vach-kinh-phong-khach-sk72", status: "done" },
  { no: 6729, title: "Lắp Rèm Cửa Nhà Phố", keyword: "lắp rèm cửa nhà phố", slug: "lap-rem-cua-nha-pho-sk72", status: "done" },
  { no: 6730, title: "Lắp Hệ Thống Âm Thanh Gia Đình", keyword: "lắp hệ thống âm thanh gia đình", slug: "lap-he-thong-am-thanh-gia-dinh-sk72", status: "done" },
  { no: 6731, title: "Gia Cố Nhà Cũ Trước Hoàn Thiện", keyword: "gia cố nhà cũ trước hoàn thiện", slug: "gia-co-nha-cu-truoc-hoan-thien-sk72", status: "done" },

  { no: 6732, title: "Xây Nhà Trọn Gói Biên Hòa Mới 2026", keyword: "xây nhà trọn gói Biên Hòa mới 2026", slug: "xay-nha-tron-goi-bien-hoa-moi-2026-sk72", status: "done" },
  { no: 6733, title: "Xây Nhà Trọn Gói Dĩ An Mới 2026", keyword: "xây nhà trọn gói Dĩ An mới 2026", slug: "xay-nha-tron-goi-di-an-moi-2026-sk72", status: "done" },
  { no: 6734, title: "Xây Nhà Trọn Gói Thuận An Update", keyword: "xây nhà trọn gói Thuận An update", slug: "xay-nha-tron-goi-thuan-an-update-sk72", status: "done" },
  { no: 6735, title: "Xây Nhà Trọn Gói Tân An 2026", keyword: "xây nhà trọn gói Tân An 2026", slug: "xay-nha-tron-goi-tan-an-2026-sk72", status: "done" },
  { no: 6736, title: "Xây Nhà Trọn Gói Cẩm Mỹ 2026", keyword: "xây nhà trọn gói Cẩm Mỹ 2026", slug: "xay-nha-tron-goi-cam-my-2026-sk72", status: "done" },
  { no: 6737, title: "Xây Nhà Trọn Gói Định Quán 2026", keyword: "xây nhà trọn gói Định Quán 2026", slug: "xay-nha-tron-goi-dinh-quan-2026-sk72", status: "done" },
  { no: 6738, title: "Xây Nhà Trọn Gói Bàu Bàng 2026", keyword: "xây nhà trọn gói Bàu Bàng 2026", slug: "xay-nha-tron-goi-bau-bang-2026-sk72", status: "done" },
  { no: 6739, title: "Cải Tạo Nhà Quận 4 Shophouse", keyword: "cải tạo nhà Quận 4 shophouse", slug: "cai-tao-nha-quan-4-shophouse-sk72", status: "done" },
  { no: 6740, title: "Cải Tạo Nhà Quận 6 Hẻm Hẹp", keyword: "cải tạo nhà Quận 6 hẻm hẹp", slug: "cai-tao-nha-quan-6-hem-hep-sk72", status: "done" },
  { no: 6741, title: "Xây Nhà Mất Bao Lâu 1 Trệt 2 Lầu", keyword: "xây nhà mất bao lâu 1 trệt 2 lầu", slug: "xay-nha-mat-bao-lau-1-tret-2-lau-sk72", status: "done" },
  { no: 6742, title: "Hoàn Thiện Nhà Mất Bao Lâu", keyword: "hoàn thiện nhà mất bao lâu", slug: "hoan-thien-nha-mat-bao-lau-sk72", status: "done" },
  { no: 6743, title: "Xây Nhà Có Nên Làm Nội Thất Sẵn", keyword: "xây nhà có nên làm nội thất sẵn", slug: "xay-nha-co-nen-lam-noi-that-san-sk72", status: "done" },
  { no: 6744, title: "Cách Chọn Gói Hoàn Thiện Nhà Phố", keyword: "cách chọn gói hoàn thiện nhà phố", slug: "cach-chon-goi-hoan-thien-nha-pho-sk72", status: "done" },
  { no: 6745, title: "Checklist Nghiệm Thu Hoàn Thiện", keyword: "checklist nghiệm thu hoàn thiện", slug: "checklist-nghiem-thu-hoan-thien-sk72", status: "done" },
  { no: 6746, title: "Khi Nào Nên Bắt Đầu Làm Nội Thất", keyword: "khi nào nên bắt đầu làm nội thất", slug: "khi-nao-nen-bat-dau-lam-noi-that-sk72", status: "done" },
];
