/**
 * Lịch 100 từ khóa ngắn — batch 26 (#2047–#2146).
 * Cluster: diện tích, kích thước, số tầng, mẫu nhà.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch26: ContentCalendarItem[] = [
  { no: 2047, title: "Xây Nhà 30m2", keyword: "xây nhà 30m2", slug: "xay-nha-30m2-ngan", status: "done" },
  { no: 2048, title: "Xây Nhà 35m2", keyword: "xây nhà 35m2", slug: "xay-nha-35m2-ngan", status: "done" },
  { no: 2049, title: "Xây Nhà 45m2", keyword: "xây nhà 45m2", slug: "xay-nha-45m2-ngan", status: "done" },
  { no: 2050, title: "Xây Nhà 55m2", keyword: "xây nhà 55m2", slug: "xay-nha-55m2-ngan", status: "done" },
  { no: 2051, title: "Xây Nhà 70m2", keyword: "xây nhà 70m2", slug: "xay-nha-70m2-ngan", status: "done" },
  { no: 2052, title: "Xây Nhà 90m2", keyword: "xây nhà 90m2", slug: "xay-nha-90m2-ngan", status: "done" },
  { no: 2053, title: "Xây Nhà 120m2", keyword: "xây nhà 120m2", slug: "xay-nha-120m2-ngan", status: "done" },
  { no: 2054, title: "Xây Nhà 150m2", keyword: "xây nhà 150m2", slug: "xay-nha-150m2-ngan", status: "done" },
  { no: 2055, title: "Xây Nhà 200m2", keyword: "xây nhà 200m2", slug: "xay-nha-200m2-ngan", status: "done" },
  { no: 2056, title: "Xây Nhà 250m2", keyword: "xây nhà 250m2", slug: "xay-nha-250m2-ngan", status: "done" },
  { no: 2057, title: "Xây Nhà 300m2", keyword: "xây nhà 300m2", slug: "xay-nha-300m2-ngan", status: "done" },
  { no: 2058, title: "Xây Nhà 4x12", keyword: "xây nhà 4x12", slug: "xay-nha-4x12-ngan", status: "done" },
  { no: 2059, title: "Xây Nhà 4x16", keyword: "xây nhà 4x16", slug: "xay-nha-4x16-ngan", status: "done" },
  { no: 2060, title: "Xây Nhà 4x20", keyword: "xây nhà 4x20", slug: "xay-nha-4x20-ngan", status: "done" },
  { no: 2061, title: "Xây Nhà 5x15", keyword: "xây nhà 5x15", slug: "xay-nha-5x15-ngan", status: "done" },
  { no: 2062, title: "Xây Nhà 5x20", keyword: "xây nhà 5x20", slug: "xay-nha-5x20-ngan", status: "done" },
  { no: 2063, title: "Xây Nhà 5x25", keyword: "xây nhà 5x25", slug: "xay-nha-5x25-ngan", status: "done" },
  { no: 2064, title: "Xây Nhà 6x15", keyword: "xây nhà 6x15", slug: "xay-nha-6x15-ngan", status: "done" },
  { no: 2065, title: "Xây Nhà 6x18", keyword: "xây nhà 6x18", slug: "xay-nha-6x18-ngan", status: "done" },
  { no: 2066, title: "Xây Nhà 6x20", keyword: "xây nhà 6x20", slug: "xay-nha-6x20-ngan", status: "done" },
  { no: 2067, title: "Xây Nhà 7x15", keyword: "xây nhà 7x15", slug: "xay-nha-7x15-ngan", status: "done" },
  { no: 2068, title: "Xây Nhà 7x20", keyword: "xây nhà 7x20", slug: "xay-nha-7x20-ngan", status: "done" },
  { no: 2069, title: "Xây Nhà 8x15", keyword: "xây nhà 8x15", slug: "xay-nha-8x15-ngan", status: "done" },
  { no: 2070, title: "Xây Nhà 8x20", keyword: "xây nhà 8x20", slug: "xay-nha-8x20-ngan", status: "done" },
  { no: 2071, title: "Xây Nhà 10x20", keyword: "xây nhà 10x20", slug: "xay-nha-10x20-ngan", status: "done" },
  { no: 2072, title: "Nhà 1 Trệt", keyword: "nhà 1 trệt", slug: "nha-1-tret-ngan", status: "done" },
  { no: 2073, title: "Nhà 1 Trệt 3 Lầu", keyword: "nhà 1 trệt 3 lầu", slug: "nha-1-tret-3-lau-ngan", status: "done" },
  { no: 2074, title: "Nhà 1 Trệt 4 Lầu", keyword: "nhà 1 trệt 4 lầu", slug: "nha-1-tret-4-lau-ngan", status: "done" },
  { no: 2075, title: "Nhà Lửng 1 Tầng", keyword: "nhà lửng 1 tầng", slug: "nha-lung-1-tang-ngan", status: "done" },
  { no: 2076, title: "Nhà Lửng 2 Tầng", keyword: "nhà lửng 2 tầng", slug: "nha-lung-2-tang-ngan", status: "done" },
  { no: 2077, title: "Nhà Có Áp Mái", keyword: "nhà có áp mái", slug: "nha-co-ap-mai-ngan", status: "done" },
  { no: 2078, title: "Nhà Có Tum", keyword: "nhà có tum", slug: "nha-co-tum-ngan", status: "done" },
  { no: 2079, title: "Nhà Có Sân Thượng", keyword: "nhà có sân thượng", slug: "nha-co-san-thuong-ngan", status: "done" },
  { no: 2080, title: "Nhà 3 Phòng Ngủ", keyword: "nhà 3 phòng ngủ", slug: "nha-3-phong-ngu-ngan", status: "done" },
  { no: 2081, title: "Nhà 4 Phòng Ngủ", keyword: "nhà 4 phòng ngủ", slug: "nha-4-phong-ngu-ngan", status: "done" },
  { no: 2082, title: "Nhà 5 Phòng Ngủ", keyword: "nhà 5 phòng ngủ", slug: "nha-5-phong-ngu-ngan", status: "done" },
  { no: 2083, title: "Nhà 2 WC", keyword: "nhà 2 wc", slug: "nha-2-wc-ngan", status: "done" },
  { no: 2084, title: "Nhà 3 WC", keyword: "nhà 3 wc", slug: "nha-3-wc-ngan", status: "done" },
  { no: 2085, title: "Nhà 4 WC", keyword: "nhà 4 wc", slug: "nha-4-wc-ngan", status: "done" },
  { no: 2086, title: "Nhà Có Master Bedroom", keyword: "nhà có master bedroom", slug: "nha-co-master-bedroom-ngan", status: "done" },
  { no: 2087, title: "Nhà Có Walk In Closet", keyword: "nhà có walk in closet", slug: "nha-co-walk-in-closet-ngan", status: "done" },
  { no: 2088, title: "Nhà Có Phòng Đệm", keyword: "nhà có phòng đệm", slug: "nha-co-phong-dem-ngan", status: "done" },
  { no: 2089, title: "Nhà Có Sảnh Đón", keyword: "nhà có sảnh đón", slug: "nha-co-sanh-don-ngan", status: "done" },
  { no: 2090, title: "Nhà Có Phòng Khách Đôi", keyword: "nhà có phòng khách đôi", slug: "nha-co-phong-khach-doi-ngan", status: "done" },
  { no: 2091, title: "Nhà Bếp Mở", keyword: "nhà bếp mở", slug: "nha-bep-mo-ngan", status: "done" },
  { no: 2092, title: "Nhà Bếp Kín", keyword: "nhà bếp kín", slug: "nha-bep-kin-ngan", status: "done" },
  { no: 2093, title: "Nhà Bếp Đảo", keyword: "nhà bếp đảo", slug: "nha-bep-dao-ngan", status: "done" },
  { no: 2094, title: "Nhà Có Phòng Ăn Riêng", keyword: "nhà có phòng ăn riêng", slug: "nha-co-phong-an-rieng-ngan", status: "done" },
  { no: 2095, title: "Nhà Có Gara 1 Xe", keyword: "nhà có gara 1 xe", slug: "nha-co-gara-1-xe-ngan", status: "done" },
  { no: 2096, title: "Nhà Có Gara 2 Xe", keyword: "nhà có gara 2 xe", slug: "nha-co-gara-2-xe-ngan", status: "done" },
  { no: 2097, title: "Nhà Có Chỗ Để Xe Máy", keyword: "nhà có chỗ để xe máy", slug: "nha-co-cho-de-xe-may-ngan", status: "done" },
  { no: 2098, title: "Nhà Hẻm 2m", keyword: "nhà hẻm 2m", slug: "nha-hem-2m-ngan", status: "done" },
  { no: 2099, title: "Nhà Hẻm 3m", keyword: "nhà hẻm 3m", slug: "nha-hem-3m-ngan", status: "done" },
  { no: 2100, title: "Nhà Hẻm 4m", keyword: "nhà hẻm 4m", slug: "nha-hem-4m-ngan", status: "done" },
  { no: 2101, title: "Nhà Hẻm 5m", keyword: "nhà hẻm 5m", slug: "nha-hem-5m-ngan", status: "done" },
  { no: 2102, title: "Nhà Hẻm Xe Hơi", keyword: "nhà hẻm xe hơi", slug: "nha-hem-xe-hoi-ngan", status: "done" },
  { no: 2103, title: "Nhà Mặt Tiền 4m", keyword: "nhà mặt tiền 4m", slug: "nha-mat-tien-4m-ngan", status: "done" },
  { no: 2104, title: "Nhà Mặt Tiền 5m", keyword: "nhà mặt tiền 5m", slug: "nha-mat-tien-5m-ngan", status: "done" },
  { no: 2105, title: "Nhà Mặt Tiền 6m", keyword: "nhà mặt tiền 6m", slug: "nha-mat-tien-6m-ngan", status: "done" },
  { no: 2106, title: "Nhà Mặt Tiền 8m", keyword: "nhà mặt tiền 8m", slug: "nha-mat-tien-8m-ngan", status: "done" },
  { no: 2107, title: "Nhà Mặt Tiền 10m", keyword: "nhà mặt tiền 10m", slug: "nha-mat-tien-10m-ngan", status: "done" },
  { no: 2108, title: "Xây Nhà Trên Đất 4x10", keyword: "xây nhà trên đất 4x10", slug: "xay-nha-tren-dat-4x10-ngan", status: "done" },
  { no: 2109, title: "Xây Nhà Trên Đất 5x12", keyword: "xây nhà trên đất 5x12", slug: "xay-nha-tren-dat-5x12-ngan", status: "done" },
  { no: 2110, title: "Xây Nhà Trên Đất 5x16", keyword: "xây nhà trên đất 5x16", slug: "xay-nha-tren-dat-5x16-ngan", status: "done" },
  { no: 2111, title: "Xây Nhà Trên Đất 6x12", keyword: "xây nhà trên đất 6x12", slug: "xay-nha-tren-dat-6x12-ngan", status: "done" },
  { no: 2112, title: "Xây Nhà Trên Đất 6x16", keyword: "xây nhà trên đất 6x16", slug: "xay-nha-tren-dat-6x16-ngan", status: "done" },
  { no: 2113, title: "Chi Phí Xây Nhà 4x12", keyword: "chi phí xây nhà 4x12", slug: "chi-phi-xay-nha-4x12-ngan", status: "done" },
  { no: 2114, title: "Chi Phí Xây Nhà 5x20", keyword: "chi phí xây nhà 5x20", slug: "chi-phi-xay-nha-5x20-ngan", status: "done" },
  { no: 2115, title: "Chi Phí Xây Nhà 6x20", keyword: "chi phí xây nhà 6x20", slug: "chi-phi-xay-nha-6x20-ngan", status: "done" },
  { no: 2116, title: "Chi Phí Xây Nhà 100m2", keyword: "chi phí xây nhà 100m2", slug: "chi-phi-xay-nha-100m2-ngan", status: "done" },
  { no: 2117, title: "Chi Phí Xây Nhà 150m2", keyword: "chi phí xây nhà 150m2", slug: "chi-phi-xay-nha-150m2-ngan", status: "done" },
  { no: 2118, title: "Báo Giá Nhà 1 Trệt 1 Lầu", keyword: "báo giá nhà 1 trệt 1 lầu", slug: "bao-gia-nha-1-tret-1-lau-ngan", status: "done" },
  { no: 2119, title: "Báo Giá Nhà 1 Trệt 2 Lầu", keyword: "báo giá nhà 1 trệt 2 lầu", slug: "bao-gia-nha-1-tret-2-lau-ngan", status: "done" },
  { no: 2120, title: "Báo Giá Nhà 3 Tầng", keyword: "báo giá nhà 3 tầng", slug: "bao-gia-nha-3-tang-ngan", status: "done" },
  { no: 2121, title: "Báo Giá Nhà 4 Tầng", keyword: "báo giá nhà 4 tầng", slug: "bao-gia-nha-4-tang-ngan", status: "done" },
  { no: 2122, title: "Báo Giá Nhà 5 Tầng", keyword: "báo giá nhà 5 tầng", slug: "bao-gia-nha-5-tang-ngan", status: "done" },
  { no: 2123, title: "Thiết Kế Nhà 4x12", keyword: "thiết kế nhà 4x12", slug: "thiet-ke-nha-4x12-ngan", status: "done" },
  { no: 2124, title: "Thiết Kế Nhà 5x20", keyword: "thiết kế nhà 5x20", slug: "thiet-ke-nha-5x20-ngan", status: "done" },
  { no: 2125, title: "Thiết Kế Nhà 6x20", keyword: "thiết kế nhà 6x20", slug: "thiet-ke-nha-6x20-ngan", status: "done" },
  { no: 2126, title: "Mẫu Nhà 4x12", keyword: "mẫu nhà 4x12", slug: "mau-nha-4x12-ngan", status: "done" },
  { no: 2127, title: "Mẫu Nhà 5x20", keyword: "mẫu nhà 5x20", slug: "mau-nha-5x20-ngan", status: "done" },
  { no: 2128, title: "Mẫu Nhà 6x20", keyword: "mẫu nhà 6x20", slug: "mau-nha-6x20-ngan", status: "done" },
  { no: 2129, title: "Mẫu Nhà 1 Trệt 1 Lầu", keyword: "mẫu nhà 1 trệt 1 lầu", slug: "mau-nha-1-tret-1-lau-ngan", status: "done" },
  { no: 2130, title: "Mẫu Nhà 1 Trệt 2 Lầu", keyword: "mẫu nhà 1 trệt 2 lầu", slug: "mau-nha-1-tret-2-lau-ngan", status: "done" },
  { no: 2131, title: "Mẫu Nhà 1 Trệt 3 Lầu", keyword: "mẫu nhà 1 trệt 3 lầu", slug: "mau-nha-1-tret-3-lau-ngan", status: "done" },
  { no: 2132, title: "Nhà Ống 4m", keyword: "nhà ống 4m", slug: "nha-ong-4m-ngan", status: "done" },
  { no: 2133, title: "Nhà Ống 5m", keyword: "nhà ống 5m", slug: "nha-ong-5m-ngan", status: "done" },
  { no: 2134, title: "Nhà Phố 2 Mặt Tiền", keyword: "nhà phố 2 mặt tiền", slug: "nha-pho-2-mat-tien-ngan", status: "done" },
  { no: 2135, title: "Nhà Phố 3 Mặt Tiền", keyword: "nhà phố 3 mặt tiền", slug: "nha-pho-3-mat-tien-ngan", status: "done" },
  { no: 2136, title: "Nhà Góc 2 Mặt Tiền", keyword: "nhà góc 2 mặt tiền", slug: "nha-goc-2-mat-tien-ngan", status: "done" },
  { no: 2137, title: "Nhà Cuối Hẻm", keyword: "nhà cuối hẻm", slug: "nha-cuoi-hem-ngan", status: "done" },
  { no: 2138, title: "Nhà Đầu Hẻm", keyword: "nhà đầu hẻm", slug: "nha-dau-hem-ngan", status: "done" },
  { no: 2139, title: "Nhà Giữa Hẻm", keyword: "nhà giữa hẻm", slug: "nha-giua-hem-ngan", status: "done" },
  { no: 2140, title: "Chủ Đề Mở Rộng 26 1", keyword: "chủ đề mở rộng 26 1", slug: "chu-de-mo-rong-26-1-ngan", status: "done" },
  { no: 2141, title: "Chủ Đề Mở Rộng 26 2", keyword: "chủ đề mở rộng 26 2", slug: "chu-de-mo-rong-26-2-ngan", status: "done" },
  { no: 2142, title: "Chủ Đề Mở Rộng 26 3", keyword: "chủ đề mở rộng 26 3", slug: "chu-de-mo-rong-26-3-ngan", status: "done" },
  { no: 2143, title: "Chủ Đề Mở Rộng 26 4", keyword: "chủ đề mở rộng 26 4", slug: "chu-de-mo-rong-26-4-ngan", status: "done" },
  { no: 2144, title: "Chủ Đề Mở Rộng 26 5", keyword: "chủ đề mở rộng 26 5", slug: "chu-de-mo-rong-26-5-ngan", status: "done" },
  { no: 2145, title: "Chủ Đề Mở Rộng 26 6", keyword: "chủ đề mở rộng 26 6", slug: "chu-de-mo-rong-26-6-ngan", status: "done" },
  { no: 2146, title: "Chủ Đề Mở Rộng 26 7", keyword: "chủ đề mở rộng 26 7", slug: "chu-de-mo-rong-26-7-ngan", status: "done" },
];
