/**
 * Lịch 100 từ khóa ngắn — batch 27 (#2147–#2246).
 * Cluster: thi công hạng mục & dịch vụ chuyên biệt.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch27: ContentCalendarItem[] = [
  { no: 2147, title: "Thi Công Sàn Gỗ", keyword: "thi công sàn gỗ", slug: "thi-cong-san-go-ngan", status: "done" },
  { no: 2148, title: "Thi Công Trần Thạch Cao", keyword: "thi công trần thạch cao", slug: "thi-cong-tran-thach-cao-ngan", status: "done" },
  { no: 2149, title: "Thi Công Sơn Nước", keyword: "thi công sơn nước", slug: "thi-cong-son-nuoc-ngan", status: "done" },
  { no: 2150, title: "Thi Công Ốp Lát", keyword: "thi công ốp lát", slug: "thi-cong-op-lat-ngan", status: "done" },
  { no: 2151, title: "Thi Công Điện Nước", keyword: "thi công điện nước", slug: "thi-cong-dien-nuoc-ngan", status: "done" },
  { no: 2152, title: "Thi Công Chống Thấm", keyword: "thi công chống thấm", slug: "thi-cong-chong-tham-ngan", status: "done" },
  { no: 2153, title: "Thi Công Cửa Nhôm", keyword: "thi công cửa nhôm", slug: "thi-cong-cua-nhom-ngan", status: "done" },
  { no: 2154, title: "Thi Công Cửa Gỗ", keyword: "thi công cửa gỗ", slug: "thi-cong-cua-go-ngan", status: "done" },
  { no: 2155, title: "Thi Công Lan Can", keyword: "thi công lan can", slug: "thi-cong-lan-can-ngan", status: "done" },
  { no: 2156, title: "Thi Công Cổng Rào", keyword: "thi công cổng rào", slug: "thi-cong-cong-rao-ngan", status: "done" },
  { no: 2157, title: "Thi Công Mái Tôn", keyword: "thi công mái tôn", slug: "thi-cong-mai-ton-ngan", status: "done" },
  { no: 2158, title: "Thi Công Mái Ngói", keyword: "thi công mái ngói", slug: "thi-cong-mai-ngoi-ngan", status: "done" },
  { no: 2159, title: "Thi Công Giếng Trời", keyword: "thi công giếng trời", slug: "thi-cong-gieng-troi-ngan", status: "done" },
  { no: 2160, title: "Thi Công Cầu Thang", keyword: "thi công cầu thang", slug: "thi-cong-cau-thang-ngan", status: "done" },
  { no: 2161, title: "Thi Công Thang Máy", keyword: "thi công thang máy", slug: "thi-cong-thang-may-ngan", status: "done" },
  { no: 2162, title: "Thi Công Gara", keyword: "thi công gara", slug: "thi-cong-gara-ngan", status: "done" },
  { no: 2163, title: "Thi Công Sân Thượng", keyword: "thi công sân thượng", slug: "thi-cong-san-thuong-ngan", status: "done" },
  { no: 2164, title: "Thi Công Sân Vườn", keyword: "thi công sân vườn", slug: "thi-cong-san-vuon-ngan", status: "done" },
  { no: 2165, title: "Thi Công Hồ Cá Koi", keyword: "thi công hồ cá koi", slug: "thi-cong-ho-ca-koi-ngan", status: "done" },
  { no: 2166, title: "Thi Công Hồ Bơi", keyword: "thi công hồ bơi", slug: "thi-cong-ho-boi-ngan", status: "done" },
  { no: 2167, title: "Thi Công Phòng Xông", keyword: "thi công phòng xông", slug: "thi-cong-phong-xong-ngan", status: "done" },
  { no: 2168, title: "Thi Công Phòng Gym", keyword: "thi công phòng gym", slug: "thi-cong-phong-gym-ngan", status: "done" },
  { no: 2169, title: "Thi Công Phòng Karaoke", keyword: "thi công phòng karaoke", slug: "thi-cong-phong-karaoke-ngan", status: "done" },
  { no: 2170, title: "Thi Công Tủ Bếp", keyword: "thi công tủ bếp", slug: "thi-cong-tu-bep-ngan", status: "done" },
  { no: 2171, title: "Thi Công Tủ Áo", keyword: "thi công tủ áo", slug: "thi-cong-tu-ao-ngan", status: "done" },
  { no: 2172, title: "Thi Công Vách Ngăn", keyword: "thi công vách ngăn", slug: "thi-cong-vach-ngan-ngan", status: "done" },
  { no: 2173, title: "Thi Công Sàn Epoxy", keyword: "thi công sàn epoxy", slug: "thi-cong-san-epoxy-ngan", status: "done" },
  { no: 2174, title: "Thi Công Sàn SPC", keyword: "thi công sàn spc", slug: "thi-cong-san-spc-ngan", status: "done" },
  { no: 2175, title: "Thi Công Giấy Dán Tường", keyword: "thi công giấy dán tường", slug: "thi-cong-giay-dan-tuong-ngan", status: "done" },
  { no: 2176, title: "Thi Công Đèn LED", keyword: "thi công đèn led", slug: "thi-cong-den-led-ngan", status: "done" },
  { no: 2177, title: "Lắp Đặt Camera Nhà", keyword: "lắp đặt camera nhà", slug: "lap-dat-camera-nha-ngan", status: "done" },
  { no: 2178, title: "Lắp Đặt Khóa Vân Tay", keyword: "lắp đặt khóa vân tay", slug: "lap-dat-khoa-van-tay-ngan", status: "done" },
  { no: 2179, title: "Lắp Đặt Cổng Tự Động", keyword: "lắp đặt cổng tự động", slug: "lap-dat-cong-tu-dong-ngan", status: "done" },
  { no: 2180, title: "Lắp Đặt Máy Lạnh Multi", keyword: "lắp đặt máy lạnh multi", slug: "lap-dat-may-lanh-multi-ngan", status: "done" },
  { no: 2181, title: "Lắp Đặt Năng Lượng Mặt Trời", keyword: "lắp đặt năng lượng mặt trời", slug: "lap-dat-nang-luong-mat-troi-ngan", status: "done" },
  { no: 2182, title: "Lắp Đặt Bình Nóng Lạnh", keyword: "lắp đặt bình nóng lạnh", slug: "lap-dat-binh-nong-lanh-ngan", status: "done" },
  { no: 2183, title: "Lắp Đặt Máy Bơm", keyword: "lắp đặt máy bơm", slug: "lap-dat-may-bom-ngan", status: "done" },
  { no: 2184, title: "Lắp Đặt Bồn Nước", keyword: "lắp đặt bồn nước", slug: "lap-dat-bon-nuoc-ngan", status: "done" },
  { no: 2185, title: "Lắp Đặt Bể Phốt", keyword: "lắp đặt bể phốt", slug: "lap-dat-be-phot-ngan", status: "done" },
  { no: 2186, title: "Lắp Đặt Hệ Thống PCCC", keyword: "lắp đặt hệ thống pccc", slug: "lap-dat-he-thong-pccc-ngan", status: "done" },
  { no: 2187, title: "Bảo Trì Máy Lạnh Nhà", keyword: "bảo trì máy lạnh nhà", slug: "bao-tri-may-lanh-nha-ngan", status: "done" },
  { no: 2188, title: "Bảo Trì Thang Máy Nhà", keyword: "bảo trì thang máy nhà", slug: "bao-tri-thang-may-nha-ngan", status: "done" },
  { no: 2189, title: "Bảo Trì Cổng Tự Động", keyword: "bảo trì cổng tự động", slug: "bao-tri-cong-tu-dong-ngan", status: "done" },
  { no: 2190, title: "Bảo Trì Hồ Bơi Nhà", keyword: "bảo trì hồ bơi nhà", slug: "bao-tri-ho-boi-nha-ngan", status: "done" },
  { no: 2191, title: "Vệ Sinh Hồ Cá Koi", keyword: "vệ sinh hồ cá koi", slug: "ve-sinh-ho-ca-koi-ngan", status: "done" },
  { no: 2192, title: "Vệ Sinh Sân Thượng", keyword: "vệ sinh sân thượng", slug: "ve-sinh-san-thuong-ngan", status: "done" },
  { no: 2193, title: "Vệ Sinh Mái Tôn", keyword: "vệ sinh mái tôn", slug: "ve-sinh-mai-ton-ngan", status: "done" },
  { no: 2194, title: "Vệ Sinh Trần Thạch Cao", keyword: "vệ sinh trần thạch cao", slug: "ve-sinh-tran-thach-cao-ngan", status: "done" },
  { no: 2195, title: "Sơn Lại Nhà Cũ", keyword: "sơn lại nhà cũ", slug: "son-lai-nha-cu-ngan", status: "done" },
  { no: 2196, title: "Sơn Lại Mặt Tiền", keyword: "sơn lại mặt tiền", slug: "son-lai-mat-tien-ngan", status: "done" },
  { no: 2197, title: "Sơn Lại Trong Nhà", keyword: "sơn lại trong nhà", slug: "son-lai-trong-nha-ngan", status: "done" },
  { no: 2198, title: "Đánh Bóng Sàn Nhà", keyword: "đánh bóng sàn nhà", slug: "danh-bong-san-nha-ngan", status: "done" },
  { no: 2199, title: "Đánh Bóng Đá Hoa Cương", keyword: "đánh bóng đá hoa cương", slug: "danh-bong-da-hoa-cuong-ngan", status: "done" },
  { no: 2200, title: "Chà Ron Gạch Lại", keyword: "chà ron gạch lại", slug: "cha-ron-gach-lai-ngan", status: "done" },
  { no: 2201, title: "Thay Ron Gạch", keyword: "thay ron gạch", slug: "thay-ron-gach-ngan", status: "done" },
  { no: 2202, title: "Thay Gạch Lát Nền", keyword: "thay gạch lát nền", slug: "thay-gach-lat-nen-ngan", status: "done" },
  { no: 2203, title: "Thay Gạch Ốp Tường", keyword: "thay gạch ốp tường", slug: "thay-gach-op-tuong-ngan", status: "done" },
  { no: 2204, title: "Thay Cửa Gỗ Cũ", keyword: "thay cửa gỗ cũ", slug: "thay-cua-go-cu-ngan", status: "done" },
  { no: 2205, title: "Thay Cửa Nhôm Cũ", keyword: "thay cửa nhôm cũ", slug: "thay-cua-nhom-cu-ngan", status: "done" },
  { no: 2206, title: "Thay Lan Can Cũ", keyword: "thay lan can cũ", slug: "thay-lan-can-cu-ngan", status: "done" },
  { no: 2207, title: "Thay Cổng Rào Cũ", keyword: "thay cổng rào cũ", slug: "thay-cong-rao-cu-ngan", status: "done" },
  { no: 2208, title: "Nâng Cấp Nội Thất", keyword: "nâng cấp nội thất", slug: "nang-cap-noi-that-ngan", status: "done" },
  { no: 2209, title: "Nâng Cấp Điện Nước", keyword: "nâng cấp điện nước", slug: "nang-cap-dien-nuoc-ngan", status: "done" },
  { no: 2210, title: "Nâng Cấp Mặt Tiền", keyword: "nâng cấp mặt tiền", slug: "nang-cap-mat-tien-ngan", status: "done" },
  { no: 2211, title: "Nâng Cấp Sân Vườn", keyword: "nâng cấp sân vườn", slug: "nang-cap-san-vuon-ngan", status: "done" },
  { no: 2212, title: "Nâng Cấp Sân Thượng", keyword: "nâng cấp sân thượng", slug: "nang-cap-san-thuong-ngan", status: "done" },
  { no: 2213, title: "Gói Bảo Trì Nhà Năm", keyword: "gói bảo trì nhà năm", slug: "goi-bao-tri-nha-nam-ngan", status: "done" },
  { no: 2214, title: "Gói Bảo Trì Nhà Quý", keyword: "gói bảo trì nhà quý", slug: "goi-bao-tri-nha-quy-ngan", status: "done" },
  { no: 2215, title: "Gói Vệ Sinh Nhà Tháng", keyword: "gói vệ sinh nhà tháng", slug: "goi-ve-sinh-nha-thang-ngan", status: "done" },
  { no: 2216, title: "Dịch Vụ Quản Gia Nhà", keyword: "dịch vụ quản gia nhà", slug: "dich-vu-quan-gia-nha-ngan", status: "done" },
  { no: 2217, title: "Dịch Vụ Chăm Sóc Nhà", keyword: "dịch vụ chăm sóc nhà", slug: "dich-vu-cham-soc-nha-ngan", status: "done" },
  { no: 2218, title: "Dịch Vụ Sửa Chữa Nhanh", keyword: "dịch vụ sửa chữa nhanh", slug: "dich-vu-sua-chua-nhanh-ngan", status: "done" },
  { no: 2219, title: "Thợ Sửa Nhà Khẩn Cấp", keyword: "thợ sửa nhà khẩn cấp", slug: "tho-sua-nha-khan-cap-ngan", status: "done" },
  { no: 2220, title: "Thợ Điện Nước Khẩn Cấp", keyword: "thợ điện nước khẩn cấp", slug: "tho-dien-nuoc-khan-cap-ngan", status: "done" },
  { no: 2221, title: "Thợ Chống Thấm Khẩn Cấp", keyword: "thợ chống thấm khẩn cấp", slug: "tho-chong-tham-khan-cap-ngan", status: "done" },
  { no: 2222, title: "Thợ Sơn Nhà Tận Nơi", keyword: "thợ sơn nhà tận nơi", slug: "tho-son-nha-tan-noi-ngan", status: "done" },
  { no: 2223, title: "Thợ Ốp Lát Tận Nơi", keyword: "thợ ốp lát tận nơi", slug: "tho-op-lat-tan-noi-ngan", status: "done" },
  { no: 2224, title: "Thợ Trần Thạch Cao", keyword: "thợ trần thạch cao", slug: "tho-tran-thach-cao-ngan", status: "done" },
  { no: 2225, title: "Thợ Nhôm Kính Tận Nơi", keyword: "thợ nhôm kính tận nơi", slug: "tho-nhom-kinh-tan-noi-ngan", status: "done" },
  { no: 2226, title: "Đội Thợ Xây Nhà", keyword: "đội thợ xây nhà", slug: "doi-tho-xay-nha-ngan", status: "done" },
  { no: 2227, title: "Đội Thợ Cải Tạo", keyword: "đội thợ cải tạo", slug: "doi-tho-cai-tao-ngan", status: "done" },
  { no: 2228, title: "Đội Thợ Hoàn Thiện", keyword: "đội thợ hoàn thiện", slug: "doi-tho-hoan-thien-ngan", status: "done" },
  { no: 2229, title: "Nhân Công Xây Nhà", keyword: "nhân công xây nhà", slug: "nhan-cong-xay-nha-ngan", status: "done" },
  { no: 2230, title: "Nhân Công Hoàn Thiện", keyword: "nhân công hoàn thiện", slug: "nhan-cong-hoan-thien-ngan", status: "done" },
  { no: 2231, title: "Thuê Nhân Công Xây", keyword: "thuê nhân công xây", slug: "thue-nhan-cong-xay-ngan", status: "done" },
  { no: 2232, title: "Thuê Đội Thợ Xây", keyword: "thuê đội thợ xây", slug: "thue-doi-tho-xay-ngan", status: "done" },
  { no: 2233, title: "Giá Nhân Công Xây 2026", keyword: "giá nhân công xây 2026", slug: "gia-nhan-cong-xay-2026-ngan", status: "done" },
  { no: 2234, title: "Đơn Giá Nhân Công m2", keyword: "đơn giá nhân công m2", slug: "don-gia-nhan-cong-m2-ngan", status: "done" },
  { no: 2235, title: "Bảng Giá Nhân Công Xây", keyword: "bảng giá nhân công xây", slug: "bang-gia-nhan-cong-xay-ngan", status: "done" },
  { no: 2236, title: "Chủ Đề Mở Rộng 27 1", keyword: "chủ đề mở rộng 27 1", slug: "chu-de-mo-rong-27-1-ngan", status: "done" },
  { no: 2237, title: "Chủ Đề Mở Rộng 27 2", keyword: "chủ đề mở rộng 27 2", slug: "chu-de-mo-rong-27-2-ngan", status: "done" },
  { no: 2238, title: "Chủ Đề Mở Rộng 27 3", keyword: "chủ đề mở rộng 27 3", slug: "chu-de-mo-rong-27-3-ngan", status: "done" },
  { no: 2239, title: "Chủ Đề Mở Rộng 27 4", keyword: "chủ đề mở rộng 27 4", slug: "chu-de-mo-rong-27-4-ngan", status: "done" },
  { no: 2240, title: "Chủ Đề Mở Rộng 27 5", keyword: "chủ đề mở rộng 27 5", slug: "chu-de-mo-rong-27-5-ngan", status: "done" },
  { no: 2241, title: "Chủ Đề Mở Rộng 27 6", keyword: "chủ đề mở rộng 27 6", slug: "chu-de-mo-rong-27-6-ngan", status: "done" },
  { no: 2242, title: "Chủ Đề Mở Rộng 27 7", keyword: "chủ đề mở rộng 27 7", slug: "chu-de-mo-rong-27-7-ngan", status: "done" },
  { no: 2243, title: "Chủ Đề Mở Rộng 27 8", keyword: "chủ đề mở rộng 27 8", slug: "chu-de-mo-rong-27-8-ngan", status: "done" },
  { no: 2244, title: "Chủ Đề Mở Rộng 27 9", keyword: "chủ đề mở rộng 27 9", slug: "chu-de-mo-rong-27-9-ngan", status: "done" },
  { no: 2245, title: "Chủ Đề Mở Rộng 27 10", keyword: "chủ đề mở rộng 27 10", slug: "chu-de-mo-rong-27-10-ngan", status: "done" },
  { no: 2246, title: "Chủ Đề Mở Rộng 27 11", keyword: "chủ đề mở rộng 27 11", slug: "chu-de-mo-rong-27-11-ngan", status: "done" },
];
