/**
 * Lịch 100 từ khóa ngắn — batch 37 (#3147–#3246).
 * Cluster: geo Hà Nội, miền Bắc, miền Trung.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch37: ContentCalendarItem[] = [
  { no: 3147, title: "Xây Nhà Cầu Giấy", keyword: "xây nhà Cầu Giấy", slug: "xay-nha-cau-giay-ngan", status: "done" },
  { no: 3148, title: "Xây Nhà Đống Đa", keyword: "xây nhà Đống Đa", slug: "xay-nha-dong-da-ngan", status: "done" },
  { no: 3149, title: "Xây Nhà Ba Đình", keyword: "xây nhà Ba Đình", slug: "xay-nha-ba-dinh-ngan", status: "done" },
  { no: 3150, title: "Xây Nhà Hoàn Kiếm", keyword: "xây nhà Hoàn Kiếm", slug: "xay-nha-hoan-kiem-ngan", status: "done" },
  { no: 3151, title: "Xây Nhà Hai Bà Trưng", keyword: "xây nhà Hai Bà Trưng", slug: "xay-nha-hai-ba-trung-ngan", status: "done" },
  { no: 3152, title: "Xây Nhà Hoàng Mai", keyword: "xây nhà Hoàng Mai", slug: "xay-nha-hoang-mai-ngan", status: "done" },
  { no: 3153, title: "Xây Nhà Thanh Xuân", keyword: "xây nhà Thanh Xuân", slug: "xay-nha-thanh-xuan-hn-ngan", status: "done" },
  { no: 3154, title: "Xây Nhà Tây Hồ", keyword: "xây nhà Tây Hồ", slug: "xay-nha-tay-ho-ngan", status: "done" },
  { no: 3155, title: "Xây Nhà Long Biên", keyword: "xây nhà Long Biên", slug: "xay-nha-long-bien-ngan", status: "done" },
  { no: 3156, title: "Xây Nhà Hà Đông", keyword: "xây nhà Hà Đông", slug: "xay-nha-ha-dong-ngan", status: "done" },
  { no: 3157, title: "Xây Nhà Nam Từ Liêm", keyword: "xây nhà Nam Từ Liêm", slug: "xay-nha-nam-tu-liem-ngan", status: "done" },
  { no: 3158, title: "Xây Nhà Bắc Từ Liêm", keyword: "xây nhà Bắc Từ Liêm", slug: "xay-nha-bac-tu-liem-ngan", status: "done" },
  { no: 3159, title: "Xây Nhà Cầu Diễn", keyword: "xây nhà Cầu Diễn", slug: "xay-nha-cau-dien-ngan", status: "done" },
  { no: 3160, title: "Xây Nhà Mỹ Đình", keyword: "xây nhà Mỹ Đình", slug: "xay-nha-my-dinh-ngan", status: "done" },
  { no: 3161, title: "Xây Nhà Gia Lâm", keyword: "xây nhà Gia Lâm", slug: "xay-nha-gia-lam-ngan", status: "done" },
  { no: 3162, title: "Xây Nhà Đông Anh", keyword: "xây nhà Đông Anh", slug: "xay-nha-dong-anh-ngan", status: "done" },
  { no: 3163, title: "Xây Nhà Sóc Sơn", keyword: "xây nhà Sóc Sơn", slug: "xay-nha-soc-son-ngan", status: "done" },
  { no: 3164, title: "Xây Nhà Hoài Đức", keyword: "xây nhà Hoài Đức", slug: "xay-nha-hoai-duc-ngan", status: "done" },
  { no: 3165, title: "Xây Nhà Thanh Trì", keyword: "xây nhà Thanh Trì", slug: "xay-nha-thanh-tri-ngan", status: "done" },
  { no: 3166, title: "Xây Nhà Thường Tín", keyword: "xây nhà Thường Tín", slug: "xay-nha-thuong-tin-ngan", status: "done" },
  { no: 3167, title: "Xây Nhà Hải Dương", keyword: "xây nhà Hải Dương", slug: "xay-nha-hai-duong-tinh-ngan", status: "done" },
  { no: 3168, title: "Xây Nhà Hải Phòng", keyword: "xây nhà Hải Phòng", slug: "xay-nha-hai-phong-tinh-ngan", status: "done" },
  { no: 3169, title: "Xây Nhà Quảng Ninh", keyword: "xây nhà Quảng Ninh", slug: "xay-nha-quang-ninh-tinh-ngan", status: "done" },
  { no: 3170, title: "Xây Nhà Bắc Ninh", keyword: "xây nhà Bắc Ninh", slug: "xay-nha-bac-ninh-tinh-ngan", status: "done" },
  { no: 3171, title: "Xây Nhà Bắc Giang", keyword: "xây nhà Bắc Giang", slug: "xay-nha-bac-giang-tinh-ngan", status: "done" },
  { no: 3172, title: "Xây Nhà Hưng Yên", keyword: "xây nhà Hưng Yên", slug: "xay-nha-hung-yen-tinh-ngan", status: "done" },
  { no: 3173, title: "Xây Nhà Vĩnh Phúc", keyword: "xây nhà Vĩnh Phúc", slug: "xay-nha-vinh-phuc-tinh-ngan", status: "done" },
  { no: 3174, title: "Xây Nhà Thái Nguyên", keyword: "xây nhà Thái Nguyên", slug: "xay-nha-thai-nguyen-tinh-ngan", status: "done" },
  { no: 3175, title: "Xây Nhà Phú Thọ", keyword: "xây nhà Phú Thọ", slug: "xay-nha-phu-tho-tinh-ngan", status: "done" },
  { no: 3176, title: "Xây Nhà Nam Định", keyword: "xây nhà Nam Định", slug: "xay-nha-nam-dinh-tinh-ngan", status: "done" },
  { no: 3177, title: "Xây Nhà Thái Bình", keyword: "xây nhà Thái Bình", slug: "xay-nha-thai-binh-tinh-ngan", status: "done" },
  { no: 3178, title: "Xây Nhà Ninh Bình", keyword: "xây nhà Ninh Bình", slug: "xay-nha-ninh-binh-tinh-ngan", status: "done" },
  { no: 3179, title: "Xây Nhà Thanh Hóa", keyword: "xây nhà Thanh Hóa", slug: "xay-nha-thanh-hoa-tinh-ngan", status: "done" },
  { no: 3180, title: "Xây Nhà Nghệ An", keyword: "xây nhà Nghệ An", slug: "xay-nha-nghe-an-tinh-ngan", status: "done" },
  { no: 3181, title: "Xây Nhà Hà Tĩnh", keyword: "xây nhà Hà Tĩnh", slug: "xay-nha-ha-tinh-tinh-ngan", status: "done" },
  { no: 3182, title: "Xây Nhà Quảng Bình", keyword: "xây nhà Quảng Bình", slug: "xay-nha-quang-binh-tinh-ngan", status: "done" },
  { no: 3183, title: "Xây Nhà Quảng Trị", keyword: "xây nhà Quảng Trị", slug: "xay-nha-quang-tri-tinh-ngan", status: "done" },
  { no: 3184, title: "Xây Nhà Huế", keyword: "xây nhà Huế", slug: "xay-nha-hue-tinh-ngan", status: "done" },
  { no: 3185, title: "Xây Nhà Đà Nẵng", keyword: "xây nhà Đà Nẵng", slug: "xay-nha-da-nang-tinh-ngan", status: "done" },
  { no: 3186, title: "Xây Nhà Quảng Nam", keyword: "xây nhà Quảng Nam", slug: "xay-nha-quang-nam-tinh-ngan", status: "done" },
  { no: 3187, title: "Xây Nhà Quảng Ngãi", keyword: "xây nhà Quảng Ngãi", slug: "xay-nha-quang-ngai-tinh-ngan", status: "done" },
  { no: 3188, title: "Xây Nhà Bình Định", keyword: "xây nhà Bình Định", slug: "xay-nha-binh-dinh-tinh-ngan", status: "done" },
  { no: 3189, title: "Xây Nhà Phú Yên", keyword: "xây nhà Phú Yên", slug: "xay-nha-phu-yen-tinh-ngan", status: "done" },
  { no: 3190, title: "Xây Nhà Khánh Hòa", keyword: "xây nhà Khánh Hòa", slug: "xay-nha-khanh-hoa-tinh-ngan", status: "done" },
  { no: 3191, title: "Xây Nhà Nha Trang", keyword: "xây nhà Nha Trang", slug: "xay-nha-nha-trang-tinh-ngan", status: "done" },
  { no: 3192, title: "Xây Nhà Ninh Thuận", keyword: "xây nhà Ninh Thuận", slug: "xay-nha-ninh-thuan-tinh-ngan", status: "done" },
  { no: 3193, title: "Xây Nhà Bình Thuận", keyword: "xây nhà Bình Thuận", slug: "xay-nha-binh-thuan-tinh-ngan", status: "done" },
  { no: 3194, title: "Xây Nhà Phan Thiết", keyword: "xây nhà Phan Thiết", slug: "xay-nha-phan-thiet-tinh-ngan", status: "done" },
  { no: 3195, title: "Xây Nhà Buôn Ma Thuột", keyword: "xây nhà Buôn Ma Thuột", slug: "xay-nha-buon-ma-thuot-tinh-ngan", status: "done" },
  { no: 3196, title: "Xây Nhà Đà Lạt", keyword: "xây nhà Đà Lạt", slug: "xay-nha-da-lat-tinh-ngan", status: "done" },
  { no: 3197, title: "Xây Nhà Pleiku", keyword: "xây nhà Pleiku", slug: "xay-nha-pleiku-tinh-ngan", status: "done" },
  { no: 3198, title: "Cải Tạo Nhà Cầu Giấy", keyword: "cải tạo nhà Cầu Giấy", slug: "cai-tao-nha-cau-giay-ngan", status: "done" },
  { no: 3199, title: "Cải Tạo Nhà Hà Đông", keyword: "cải tạo nhà Hà Đông", slug: "cai-tao-nha-ha-dong-ngan", status: "done" },
  { no: 3200, title: "Cải Tạo Nhà Long Biên", keyword: "cải tạo nhà Long Biên", slug: "cai-tao-nha-long-bien-ngan", status: "done" },
  { no: 3201, title: "Cải Tạo Nhà Đà Nẵng", keyword: "cải tạo nhà Đà Nẵng", slug: "cai-tao-nha-da-nang-geo-ngan", status: "done" },
  { no: 3202, title: "Cải Tạo Nhà Nha Trang", keyword: "cải tạo nhà Nha Trang", slug: "cai-tao-nha-nha-trang-geo-ngan", status: "done" },
  { no: 3203, title: "Cải Tạo Nhà Đà Lạt", keyword: "cải tạo nhà Đà Lạt", slug: "cai-tao-nha-da-lat-geo-ngan", status: "done" },
  { no: 3204, title: "Thiết Kế Nhà Cầu Giấy", keyword: "thiết kế nhà Cầu Giấy", slug: "thiet-ke-nha-cau-giay-ngan", status: "done" },
  { no: 3205, title: "Thiết Kế Nhà Hà Đông", keyword: "thiết kế nhà Hà Đông", slug: "thiet-ke-nha-ha-dong-ngan", status: "done" },
  { no: 3206, title: "Thiết Kế Nhà Đà Nẵng", keyword: "thiết kế nhà Đà Nẵng", slug: "thiet-ke-nha-da-nang-geo-ngan", status: "done" },
  { no: 3207, title: "Thiết Kế Nhà Nha Trang", keyword: "thiết kế nhà Nha Trang", slug: "thiet-ke-nha-nha-trang-geo-ngan", status: "done" },
  { no: 3208, title: "Thiết Kế Nhà Đà Lạt", keyword: "thiết kế nhà Đà Lạt", slug: "thiet-ke-nha-da-lat-geo-ngan", status: "done" },
  { no: 3209, title: "Báo Giá Xây Nhà Hà Nội", keyword: "báo giá xây nhà Hà Nội", slug: "bao-gia-xay-nha-ha-noi-ngan", status: "done" },
  { no: 3210, title: "Báo Giá Xây Nhà Hải Phòng", keyword: "báo giá xây nhà Hải Phòng", slug: "bao-gia-xay-nha-hai-phong-ngan", status: "done" },
  { no: 3211, title: "Báo Giá Xây Nhà Đà Nẵng", keyword: "báo giá xây nhà Đà Nẵng", slug: "bao-gia-xay-nha-da-nang-geo-ngan", status: "done" },
  { no: 3212, title: "Báo Giá Xây Nhà Nha Trang", keyword: "báo giá xây nhà Nha Trang", slug: "bao-gia-xay-nha-nha-trang-geo-ngan", status: "done" },
  { no: 3213, title: "Báo Giá Xây Nhà Đà Lạt", keyword: "báo giá xây nhà Đà Lạt", slug: "bao-gia-xay-nha-da-lat-geo-ngan", status: "done" },
  { no: 3214, title: "Nhà Thầu Hà Nội", keyword: "nhà thầu Hà Nội", slug: "nha-thau-ha-noi-ngan", status: "done" },
  { no: 3215, title: "Nhà Thầu Hải Phòng", keyword: "nhà thầu Hải Phòng", slug: "nha-thau-hai-phong-ngan", status: "done" },
  { no: 3216, title: "Nhà Thầu Đà Nẵng", keyword: "nhà thầu Đà Nẵng", slug: "nha-thau-da-nang-ngan", status: "done" },
  { no: 3217, title: "Nhà Thầu Nha Trang", keyword: "nhà thầu Nha Trang", slug: "nha-thau-nha-trang-ngan", status: "done" },
  { no: 3218, title: "Nhà Thầu Đà Lạt", keyword: "nhà thầu Đà Lạt", slug: "nha-thau-da-lat-ngan", status: "done" },
  { no: 3219, title: "Xây Nhà Ống Hà Nội", keyword: "xây nhà ống Hà Nội", slug: "xay-nha-ong-ha-noi-ngan", status: "done" },
  { no: 3220, title: "Xây Nhà Phố Hà Nội", keyword: "xây nhà phố Hà Nội", slug: "xay-nha-pho-ha-noi-ngan", status: "done" },
  { no: 3221, title: "Xây Biệt Thự Hà Nội", keyword: "xây biệt thự Hà Nội", slug: "xay-biet-thu-ha-noi-ngan", status: "done" },
  { no: 3222, title: "Xây Nhà Vườn Hà Nội", keyword: "xây nhà vườn Hà Nội", slug: "xay-nha-vuon-ha-noi-ngan", status: "done" },
  { no: 3223, title: "Xây Nhà Ven Biển Đà Nẵng", keyword: "xây nhà ven biển Đà Nẵng", slug: "xay-nha-ven-bien-da-nang-ngan", status: "done" },
  { no: 3224, title: "Xây Nhà Ven Biển Nha Trang", keyword: "xây nhà ven biển Nha Trang", slug: "xay-nha-ven-bien-nha-trang-ngan", status: "done" },
  { no: 3225, title: "Xây Nhà Núi Đà Lạt", keyword: "xây nhà núi Đà Lạt", slug: "xay-nha-nui-da-lat-ngan", status: "done" },
  { no: 3226, title: "Xây Nhà Chống Lạnh Đà Lạt", keyword: "xây nhà chống lạnh Đà Lạt", slug: "xay-nha-chong-lanh-da-lat-ngan", status: "done" },
  { no: 3227, title: "Xây Nhà Chống Bão Miền Trung", keyword: "xây nhà chống bão miền Trung", slug: "xay-nha-chong-bao-mien-trung-ngan", status: "done" },
  { no: 3228, title: "Xây Nhà Chống Lũ Miền Trung", keyword: "xây nhà chống lũ miền Trung", slug: "xay-nha-chong-lu-mien-trung-ngan", status: "done" },
  { no: 3229, title: "Xin Phép Xây Nhà Hà Nội", keyword: "xin phép xây nhà Hà Nội", slug: "xin-phep-xay-nha-ha-noi-ngan", status: "done" },
  { no: 3230, title: "Xin Phép Xây Nhà Đà Nẵng", keyword: "xin phép xây nhà Đà Nẵng", slug: "xin-phep-xay-nha-da-nang-ngan", status: "done" },
  { no: 3231, title: "Đơn Giá Xây Nhà Hà Nội", keyword: "đơn giá xây nhà Hà Nội", slug: "don-gia-xay-nha-ha-noi-ngan", status: "done" },
  { no: 3232, title: "Đơn Giá Xây Nhà Đà Nẵng", keyword: "đơn giá xây nhà Đà Nẵng", slug: "don-gia-xay-nha-da-nang-ngan", status: "done" },
  { no: 3233, title: "Đơn Giá Xây Nhà Nha Trang", keyword: "đơn giá xây nhà Nha Trang", slug: "don-gia-xay-nha-nha-trang-ngan", status: "done" },
  { no: 3234, title: "Xây Nhà KĐT Dương Nội", keyword: "xây nhà Dương Nội", slug: "xay-nha-duong-noi-ngan", status: "done" },
  { no: 3235, title: "Xây Nhà KĐT Văn Quán", keyword: "xây nhà Văn Quán", slug: "xay-nha-van-quan-ngan", status: "done" },
  { no: 3236, title: "Xây Nhà KĐT Linh Đàm", keyword: "xây nhà Linh Đàm", slug: "xay-nha-linh-dam-ngan", status: "done" },
  { no: 3237, title: "Xây Nhà KĐT Ciputra", keyword: "xây nhà Ciputra", slug: "xay-nha-ciputra-ngan", status: "done" },
  { no: 3238, title: "Xây Nhà KĐT Ecopark", keyword: "xây nhà Ecopark", slug: "xay-nha-ecopark-ngan", status: "done" },
  { no: 3239, title: "Xây Nhà KĐT Vinhomes Ocean Park", keyword: "xây nhà Vinhomes Ocean Park", slug: "xay-nha-vinhomes-ocean-park-ngan", status: "done" },
  { no: 3240, title: "Xây Nhà KĐT Vinhomes Smart City", keyword: "xây nhà Vinhomes Smart City", slug: "xay-nha-vinhomes-smart-city-ngan", status: "done" },
  { no: 3241, title: "Xây Nhà Ngũ Hành Sơn", keyword: "xây nhà Ngũ Hành Sơn", slug: "xay-nha-ngu-hanh-son-ngan", status: "done" },
  { no: 3242, title: "Xây Nhà Sơn Trà", keyword: "xây nhà Sơn Trà", slug: "xay-nha-son-tra-ngan", status: "done" },
  { no: 3243, title: "Xây Nhà Hải Châu", keyword: "xây nhà Hải Châu", slug: "xay-nha-hai-chau-ngan", status: "done" },
  { no: 3244, title: "Xây Nhà Thanh Khê", keyword: "xây nhà Thanh Khê", slug: "xay-nha-thanh-khe-ngan", status: "done" },
  { no: 3245, title: "Xây Nhà Liên Chiểu", keyword: "xây nhà Liên Chiểu", slug: "xay-nha-lien-chieu-ngan", status: "done" },
  { no: 3246, title: "Xây Nhà Cẩm Lệ", keyword: "xây nhà Cẩm Lệ", slug: "xay-nha-cam-le-ngan", status: "done" },
];
