/**
 * Lịch 100 từ khóa ngắn — batch 64 (#5847–#5946).
 * Cluster: FAQ quyết định, local Ads, brand conversion.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch64: ContentCalendarItem[] = [
  { no: 5847, title: "Xây Nhà Cần Giấy Tờ Gì", keyword: "xây nhà cần giấy tờ gì", slug: "xay-nha-can-giay-to-gi-faq3-ngan", status: "done" },
  { no: 5848, title: "Cải Tạo Cần Giấy Tờ Gì", keyword: "cải tạo cần giấy tờ gì", slug: "cai-tao-nha-can-giay-to-gi-faq3-ngan", status: "done" },
  { no: 5849, title: "Xây Nhà Hỏi Thầu Gì", keyword: "xây nhà hỏi thầu gì", slug: "xay-nha-hoi-thau-gi-faq3-ngan", status: "done" },
  { no: 5850, title: "Ký Hợp Đồng Cần Chú Ý Gì", keyword: "ký hợp đồng cần chú ý gì", slug: "ky-hop-dong-can-chu-y-gi-faq3-ngan", status: "done" },
  { no: 5851, title: "Thanh Toán Xây Như Thế Nào", keyword: "thanh toán xây như thế nào", slug: "thanh-toan-xay-nhu-the-nao-faq3-ngan", status: "done" },
  { no: 5852, title: "Giữ Lại Bao Nhiêu Phần Trăm", keyword: "giữ lại bao nhiêu %", slug: "giu-lai-bao-nhieu-phan-tram-faq3-ngan", status: "done" },
  { no: 5853, title: "Bảo Hành Xây Bao Lâu", keyword: "bảo hành xây bao lâu", slug: "bao-hanh-xay-bao-lau-faq3-ngan", status: "done" },
  { no: 5854, title: "Phát Sinh Bao Nhiêu Là Bình Thường", keyword: "phát sinh bao nhiêu là bình thường", slug: "phat-sinh-bao-nhieu-binh-thuong-faq3-ngan", status: "done" },
  { no: 5855, title: "Nhà Thầu Trễ Phải Làm Sao", keyword: "nhà thầu trễ phải làm sao", slug: "nha-thau-tre-phai-lam-sao-faq3-ngan", status: "done" },
  { no: 5856, title: "Chất Lượng Kém Phải Làm Sao", keyword: "chất lượng kém phải làm sao", slug: "chat-luong-kem-phai-lam-sao-faq3-ngan", status: "done" },
  { no: 5857, title: "Có Nên Đặt Cọc Trước", keyword: "có nên đặt cọc trước", slug: "co-nen-dat-coc-truoc-faq3-ngan", status: "done" },
  { no: 5858, title: "Cọc Bao Nhiêu Là Hợp Lý", keyword: "cọc bao nhiêu là hợp lý", slug: "coc-bao-nhieu-hop-ly-faq3-ngan", status: "done" },
  { no: 5859, title: "Có Nên Công Chứng Hợp Đồng", keyword: "có nên công chứng hợp đồng", slug: "co-nen-cong-chung-hop-dong-faq3-ngan", status: "done" },
  { no: 5860, title: "Có Nên Thuê Luật Sư Xây", keyword: "có nên thuê luật sư xây", slug: "co-nen-thue-luat-su-xay-faq3-ngan", status: "done" },
  { no: 5861, title: "Giám Sát Có Đắt Không", keyword: "giám sát có đắt không", slug: "giam-sat-co-dat-khong-faq3-ngan", status: "done" },
  { no: 5862, title: "Thiết Kế Có Bắt Buộc Không", keyword: "thiết kế có bắt buộc không", slug: "thiet-ke-co-bat-buoc-khong-faq3-ngan", status: "done" },
  { no: 5863, title: "Xây Không Bản Vẽ Được Không", keyword: "xây không bản vẽ được không", slug: "xay-khong-ban-ve-duoc-khong-faq3-ngan", status: "done" },
  { no: 5864, title: "Tự Mua Vật Tư Có Lợi Không", keyword: "tự mua vật tư có lợi không", slug: "tu-mua-vat-tu-co-loi-khong-faq3-ngan", status: "done" },
  { no: 5865, title: "Thầu Bao Vật Tư Có Lợi Không", keyword: "thầu bao vật tư có lợi không", slug: "thau-bao-vat-tu-co-loi-khong-faq3-ngan", status: "done" },
  { no: 5866, title: "Giá Rẻ Có Đáng Ngờ Không", keyword: "giá rẻ có đáng ngờ không", slug: "gia-re-co-dang-ngo-khong-faq3-ngan", status: "done" },
  { no: 5867, title: "Làm Sao Biết Thầu Uy Tín", keyword: "làm sao biết thầu uy tín", slug: "lam-sao-biet-thau-uy-tin-faq3-ngan", status: "done" },
  { no: 5868, title: "Xem Công Trình Mẫu Ở Đâu", keyword: "xem công trình mẫu ở đâu", slug: "xem-cong-trinh-mau-o-dau-faq3-ngan", status: "done" },
  { no: 5869, title: "Thời Điểm Xây Tốt Nhất", keyword: "thời điểm xây tốt nhất", slug: "thoi-diem-xay-tot-nhat-faq3-ngan", status: "done" },
  { no: 5870, title: "Xây Mùa Mưa Có Sao Không", keyword: "xây mùa mưa có sao không", slug: "xay-mua-mua-co-sao-khong-faq3-ngan", status: "done" },
  { no: 5871, title: "Xây Mùa Nắng Có Sao Không", keyword: "xây mùa nắng có sao không", slug: "xay-mua-nang-co-sao-khong-faq3-ngan", status: "done" },
  { no: 5872, title: "Hàng Xóm Phản Đối Xây", keyword: "hàng xóm phản đối xây", slug: "hang-xom-phan-doi-xay-faq3-ngan", status: "done" },
  { no: 5873, title: "Xây Ảnh Hưởng Nhà Bên Cạnh", keyword: "xây ảnh hưởng nhà bên cạnh", slug: "xay-anh-huong-nha-ben-canh-faq3-ngan", status: "done" },
  { no: 5874, title: "Ép Cọc Rung Nhà Hàng Xóm", keyword: "ép cọc rung nhà hàng xóm", slug: "ep-coc-rung-nha-hang-xom-faq3-ngan", status: "done" },
  { no: 5875, title: "Bụi Tiếng Ồn Công Trình", keyword: "bụi tiếng ồn công trình", slug: "bui-tieng-on-cong-trinh-faq3-ngan", status: "done" },
  { no: 5876, title: "Nghiệm Thu Cần Có Ai", keyword: "nghiệm thu cần có ai", slug: "nghiem-thu-can-co-ai-faq3-ngan", status: "done" },
  { no: 5877, title: "Bàn Giao Cần Kiểm Tra Gì", keyword: "bàn giao cần kiểm tra gì", slug: "ban-giao-can-kiem-tra-gi-faq3-ngan", status: "done" },
  { no: 5878, title: "Sau Bàn Giao Làm Gì", keyword: "sau bàn giao làm gì", slug: "sau-ban-giao-lam-gi-faq3-ngan", status: "done" },
  { no: 5879, title: "Nhập Trạch Khi Nào", keyword: "nhập trạch khi nào", slug: "nhap-trach-khi-nao-faq3-ngan", status: "done" },
  { no: 5880, title: "Sơn Bao Lâu Mới Ở Được", keyword: "sơn bao lâu mới ở được", slug: "son-bao-lau-moi-o-duoc-faq3-ngan", status: "done" },
  { no: 5881, title: "Nhà Mới Có Mùi Sơn", keyword: "nhà mới có mùi sơn", slug: "nha-moi-co-mui-son-faq3-ngan", status: "done" },
  { no: 5882, title: "Xây Nhà Gần Tôi TPHCM", keyword: "xây nhà gần tôi tphcm", slug: "xay-nha-gan-toi-tphcm-ads6-ngan", status: "done" },
  { no: 5883, title: "Cải Tạo Gần Tôi TPHCM", keyword: "cải tạo gần tôi tphcm", slug: "cai-tao-gan-toi-tphcm-ads6-ngan", status: "done" },
  { no: 5884, title: "Nhà Thầu Gần Tôi Quận", keyword: "nhà thầu gần tôi quận", slug: "nha-thau-gan-toi-quan-ads6-ngan", status: "done" },
  { no: 5885, title: "Thợ Xây Gần Đây", keyword: "thợ xây gần đây", slug: "tho-xay-gan-day-ads6-ngan", status: "done" },
  { no: 5886, title: "Kiến Trúc Sư Gần Đây", keyword: "kiến trúc sư gần đây", slug: "kien-truc-su-gan-day-ads6-ngan", status: "done" },
  { no: 5887, title: "Báo Giá Nhanh Trong Ngày", keyword: "báo giá nhanh trong ngày", slug: "bao-gia-nhanh-trong-ngay-ads6-ngan", status: "done" },
  { no: 5888, title: "Khảo Sát Hôm Nay", keyword: "khảo sát hôm nay", slug: "khao-sat-hom-nay-ads6-ngan", status: "done" },
  { no: 5889, title: "Tư Vấn Ngay Bây Giờ", keyword: "tư vấn ngay bây giờ", slug: "tu-van-ngay-bay-gio-ads6-ngan", status: "done" },
  { no: 5890, title: "Gọi Ngay Sao Khuê", keyword: "gọi ngay sao khuê", slug: "goi-ngay-sao-khue-ads6-ngan", status: "done" },
  { no: 5891, title: "Chat Ngay Sao Khuê", keyword: "chat ngay sao khuê", slug: "chat-ngay-sao-khue-ads6-ngan", status: "done" },
  { no: 5892, title: "Đặt Hẹn Sao Khuê", keyword: "đặt hẹn sao khuê", slug: "dat-hen-sao-khue-ads6-ngan", status: "done" },
  { no: 5893, title: "Nhận Ưu Đãi Sao Khuê", keyword: "nhận ưu đãi sao khuê", slug: "nhan-uu-dai-sao-khue-ads6-ngan", status: "done" },
  { no: 5894, title: "Bảng Giá Sao Khuê 2026", keyword: "bảng giá sao khuê 2026", slug: "bang-gia-sao-khue-2026-ads6-ngan", status: "done" },
  { no: 5895, title: "Gói Dịch Vụ Sao Khuê", keyword: "gói dịch vụ sao khuê", slug: "goi-dich-vu-sao-khue-ads6-ngan", status: "done" },
  { no: 5896, title: "Quy Trình Sao Khuê", keyword: "quy trình sao khuê", slug: "quy-trinh-sao-khue-ads6-ngan", status: "done" },
  { no: 5897, title: "Cam Kết Sao Khuê", keyword: "cam kết sao khuê", slug: "cam-ket-sao-khue-ads6-ngan", status: "done" },
  { no: 5898, title: "Bảo Hành Sao Khuê", keyword: "bảo hành sao khuê", slug: "bao-hanh-sao-khue-ads6-ngan", status: "done" },
  { no: 5899, title: "Công Trình Sao Khuê", keyword: "công trình sao khuê", slug: "cong-trinh-sao-khue-ads6-ngan", status: "done" },
  { no: 5900, title: "Khách Hàng Sao Khuê", keyword: "khách hàng sao khuê", slug: "khach-hang-sao-khue-ads6-ngan", status: "done" },
  { no: 5901, title: "Review Sao Khuê", keyword: "review sao khuê", slug: "review-sao-khue-ads6-ngan", status: "done" },
  { no: 5902, title: "Đánh Giá Sao Khuê", keyword: "đánh giá sao khuê", slug: "danh-gia-sao-khue-ads6-ngan", status: "done" },
  { no: 5903, title: "Sao Khuê Ở Đâu", keyword: "sao khuê ở đâu", slug: "sao-khue-o-dau-ads6-ngan", status: "done" },
  { no: 5904, title: "Văn Phòng Sao Khuê", keyword: "văn phòng sao khuê", slug: "van-phong-sao-khue-ads6-ngan", status: "done" },
  { no: 5905, title: "Website Kiến Trúc Sao Khuê", keyword: "website kiến trúc sao khuê", slug: "website-kien-truc-sao-khue-ads6-ngan", status: "done" },
  { no: 5906, title: "Fanpage Sao Khuê Xây Nhà", keyword: "fanpage sao khuê xây nhà", slug: "fanpage-sao-khue-xay-nha-ads6-ngan", status: "done" },
  { no: 5907, title: "YouTube Sao Khuê", keyword: "youtube sao khuê", slug: "youtube-sao-khue-ads6-ngan", status: "done" },
  { no: 5908, title: "TikTok Sao Khuê", keyword: "tiktok sao khuê", slug: "tiktok-sao-khue-ads6-ngan", status: "done" },
  { no: 5909, title: "Best Builder TPHCM", keyword: "best builder tphcm", slug: "best-builder-tphcm-ads6-ngan", status: "done" },
  { no: 5910, title: "Top Builder 2026", keyword: "top builder 2026", slug: "top-builder-2026-ads6-ngan", status: "done" },
  { no: 5911, title: "Trusted Builder Near Me", keyword: "trusted builder near me", slug: "trusted-builder-near-me-ads6-ngan", status: "done" },
  { no: 5912, title: "Licensed Contractor TPHCM", keyword: "licensed contractor tphcm", slug: "licensed-contractor-tphcm-ads6-ngan", status: "done" },
  { no: 5913, title: "Insured Builder TPHCM", keyword: "insured builder tphcm", slug: "insured-builder-tphcm-ads6-ngan", status: "done" },
  { no: 5914, title: "Fixed Price Xây Nhà", keyword: "fixed price xây nhà", slug: "fixed-price-xay-nha-ads6-ngan", status: "done" },
  { no: 5915, title: "No Hidden Fees Xây", keyword: "no hidden fees xây", slug: "no-hidden-fees-xay-ads6-ngan", status: "done" },
  { no: 5916, title: "On Time Delivery Xây", keyword: "on time delivery xây", slug: "on-time-delivery-xay-ads6-ngan", status: "done" },
  { no: 5917, title: "Quality Guaranteed Xây", keyword: "quality guaranteed xây", slug: "quality-guaranteed-xay-ads6-ngan", status: "done" },
  { no: 5918, title: "Free Site Visit TPHCM", keyword: "free site visit tphcm", slug: "free-site-visit-tphcm-ads6-ngan", status: "done" },
  { no: 5919, title: "Free Quote Today", keyword: "free quote today", slug: "free-quote-today-ads6-ngan", status: "done" },
  { no: 5920, title: "Same Day Quote Xây", keyword: "same day quote xây", slug: "same-day-quote-xay-ads6-ngan", status: "done" },
  { no: 5921, title: "Instant Estimate Xây", keyword: "instant estimate xây", slug: "instant-estimate-xay-ads6-ngan", status: "done" },
  { no: 5922, title: "Book Appointment Xây", keyword: "book appointment xây", slug: "book-appointment-xay-ads6-ngan", status: "done" },
  { no: 5923, title: "Schedule Free Consult", keyword: "schedule free consult", slug: "schedule-free-consult-ads6-ngan", status: "done" },
  { no: 5924, title: "Talk To Builder Now", keyword: "talk to builder now", slug: "talk-to-builder-now-ads6-ngan", status: "done" },
  { no: 5925, title: "Get Proposal Today", keyword: "get proposal today", slug: "get-proposal-today-ads6-ngan", status: "done" },
  { no: 5926, title: "Start Your Build 2026", keyword: "start your build 2026", slug: "start-your-build-2026-ads6-ngan", status: "done" },
  { no: 5927, title: "Renovate Your Home Now", keyword: "renovate your home now", slug: "renovate-your-home-now-ads6-ngan", status: "done" },
  { no: 5928, title: "Limited Slots August", keyword: "limited slots august", slug: "limited-slots-august-ads6-ngan", status: "done" },
  { no: 5929, title: "Closing Offer This Week", keyword: "closing offer this week", slug: "closing-offer-this-week-ads6-ngan", status: "done" },
  { no: 5930, title: "Last Chance Promo Xây", keyword: "last chance promo xây", slug: "last-chance-promo-xay-ads6-ngan", status: "done" },
  { no: 5931, title: "CTA Xây Với Sao Khuê", keyword: "cta xây với sao khuê", slug: "cta-xay-voi-sao-khue-ads6-ngan", status: "done" },
  { no: 5932, title: "CTA Cải Tạo Với Sao Khuê", keyword: "cta cải tạo với sao khuê", slug: "cta-cai-tao-voi-sao-khue-ads6-ngan", status: "done" },
  { no: 5933, title: "Final Call Xây Nhà", keyword: "final call xây nhà", slug: "final-call-xay-nha-ads6-ngan", status: "done" },
  { no: 5934, title: "Chủ Đề Mở Rộng 64 1", keyword: "chủ đề mở rộng 64 1", slug: "chu-de-mo-rong-64-1-ngan", status: "done" },
  { no: 5935, title: "Chủ Đề Mở Rộng 64 2", keyword: "chủ đề mở rộng 64 2", slug: "chu-de-mo-rong-64-2-ngan", status: "done" },
  { no: 5936, title: "Chủ Đề Mở Rộng 64 3", keyword: "chủ đề mở rộng 64 3", slug: "chu-de-mo-rong-64-3-ngan", status: "done" },
  { no: 5937, title: "Chủ Đề Mở Rộng 64 4", keyword: "chủ đề mở rộng 64 4", slug: "chu-de-mo-rong-64-4-ngan", status: "done" },
  { no: 5938, title: "Chủ Đề Mở Rộng 64 5", keyword: "chủ đề mở rộng 64 5", slug: "chu-de-mo-rong-64-5-ngan", status: "done" },
  { no: 5939, title: "Chủ Đề Mở Rộng 64 6", keyword: "chủ đề mở rộng 64 6", slug: "chu-de-mo-rong-64-6-ngan", status: "done" },
  { no: 5940, title: "Chủ Đề Mở Rộng 64 7", keyword: "chủ đề mở rộng 64 7", slug: "chu-de-mo-rong-64-7-ngan", status: "done" },
  { no: 5941, title: "Chủ Đề Mở Rộng 64 8", keyword: "chủ đề mở rộng 64 8", slug: "chu-de-mo-rong-64-8-ngan", status: "done" },
  { no: 5942, title: "Chủ Đề Mở Rộng 64 9", keyword: "chủ đề mở rộng 64 9", slug: "chu-de-mo-rong-64-9-ngan", status: "done" },
  { no: 5943, title: "Chủ Đề Mở Rộng 64 10", keyword: "chủ đề mở rộng 64 10", slug: "chu-de-mo-rong-64-10-ngan", status: "done" },
  { no: 5944, title: "Chủ Đề Mở Rộng 64 11", keyword: "chủ đề mở rộng 64 11", slug: "chu-de-mo-rong-64-11-ngan", status: "done" },
  { no: 5945, title: "Chủ Đề Mở Rộng 64 12", keyword: "chủ đề mở rộng 64 12", slug: "chu-de-mo-rong-64-12-ngan", status: "done" },
  { no: 5946, title: "Chủ Đề Mở Rộng 64 13", keyword: "chủ đề mở rộng 64 13", slug: "chu-de-mo-rong-64-13-ngan", status: "done" },
];
