/**
 * Lịch 100 từ khóa ngắn — batch 60 (#5447–#5546).
 * Cluster: diện tích, số tầng, ngân sách cụ thể.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch60: ContentCalendarItem[] = [
  { no: 5447, title: "Xây Nhà 3x8 2 Tầng", keyword: "xây nhà 3x8 2 tầng", slug: "xay-nha-3x8-2-tang-dt-ngan", status: "done" },
  { no: 5448, title: "Xây Nhà 3x10 2 Tầng", keyword: "xây nhà 3x10 2 tầng", slug: "xay-nha-3x10-2-tang-dt-ngan", status: "done" },
  { no: 5449, title: "Xây Nhà 3x10 3 Tầng", keyword: "xây nhà 3x10 3 tầng", slug: "xay-nha-3x10-3-tang-dt-ngan", status: "done" },
  { no: 5450, title: "Xây Nhà 3x12 3 Tầng", keyword: "xây nhà 3x12 3 tầng", slug: "xay-nha-3x12-3-tang-dt-ngan", status: "done" },
  { no: 5451, title: "Xây Nhà 4x10 2 Tầng", keyword: "xây nhà 4x10 2 tầng", slug: "xay-nha-4x10-2-tang-dt-ngan", status: "done" },
  { no: 5452, title: "Xây Nhà 4x10 3 Tầng", keyword: "xây nhà 4x10 3 tầng", slug: "xay-nha-4x10-3-tang-dt-ngan", status: "done" },
  { no: 5453, title: "Xây Nhà 4x12 3 Tầng", keyword: "xây nhà 4x12 3 tầng", slug: "xay-nha-4x12-3-tang-dt-ngan", status: "done" },
  { no: 5454, title: "Xây Nhà 4x12 4 Tầng", keyword: "xây nhà 4x12 4 tầng", slug: "xay-nha-4x12-4-tang-dt-ngan", status: "done" },
  { no: 5455, title: "Xây Nhà 4x15 3 Tầng", keyword: "xây nhà 4x15 3 tầng", slug: "xay-nha-4x15-3-tang-dt-ngan", status: "done" },
  { no: 5456, title: "Xây Nhà 4x15 4 Tầng", keyword: "xây nhà 4x15 4 tầng", slug: "xay-nha-4x15-4-tang-dt-ngan", status: "done" },
  { no: 5457, title: "Xây Nhà 4x16 4 Tầng", keyword: "xây nhà 4x16 4 tầng", slug: "xay-nha-4x16-4-tang-dt-ngan", status: "done" },
  { no: 5458, title: "Xây Nhà 5x12 3 Tầng", keyword: "xây nhà 5x12 3 tầng", slug: "xay-nha-5x12-3-tang-dt-ngan", status: "done" },
  { no: 5459, title: "Xây Nhà 5x15 3 Tầng", keyword: "xây nhà 5x15 3 tầng", slug: "xay-nha-5x15-3-tang-dt-ngan", status: "done" },
  { no: 5460, title: "Xây Nhà 5x15 4 Tầng", keyword: "xây nhà 5x15 4 tầng", slug: "xay-nha-5x15-4-tang-dt-ngan", status: "done" },
  { no: 5461, title: "Xây Nhà 5x18 4 Tầng", keyword: "xây nhà 5x18 4 tầng", slug: "xay-nha-5x18-4-tang-dt-ngan", status: "done" },
  { no: 5462, title: "Xây Nhà 5x20 4 Tầng", keyword: "xây nhà 5x20 4 tầng", slug: "xay-nha-5x20-4-tang-dt-ngan", status: "done" },
  { no: 5463, title: "Xây Nhà 6x15 3 Tầng", keyword: "xây nhà 6x15 3 tầng", slug: "xay-nha-6x15-3-tang-dt-ngan", status: "done" },
  { no: 5464, title: "Xây Nhà 6x18 3 Tầng", keyword: "xây nhà 6x18 3 tầng", slug: "xay-nha-6x18-3-tang-dt-ngan", status: "done" },
  { no: 5465, title: "Xây Nhà 6x20 4 Tầng", keyword: "xây nhà 6x20 4 tầng", slug: "xay-nha-6x20-4-tang-dt-ngan", status: "done" },
  { no: 5466, title: "Xây Nhà 7x15 3 Tầng", keyword: "xây nhà 7x15 3 tầng", slug: "xay-nha-7x15-3-tang-dt-ngan", status: "done" },
  { no: 5467, title: "Xây Nhà 8x20 2 Tầng", keyword: "xây nhà 8x20 2 tầng", slug: "xay-nha-8x20-2-tang-dt-ngan", status: "done" },
  { no: 5468, title: "Xây Nhà 8x20 3 Tầng", keyword: "xây nhà 8x20 3 tầng", slug: "xay-nha-8x20-3-tang-dt-ngan", status: "done" },
  { no: 5469, title: "Xây Nhà 10x20 Biệt Thự", keyword: "xây nhà 10x20 biệt thự", slug: "xay-nha-10x20-biet-thu-dt-ngan", status: "done" },
  { no: 5470, title: "Xây Nhà Cấp 4 5x20", keyword: "xây nhà cấp 4 5x20", slug: "xay-nha-cap-4-5x20-dt-ngan", status: "done" },
  { no: 5471, title: "Xây Nhà Cấp 4 6x20", keyword: "xây nhà cấp 4 6x20", slug: "xay-nha-cap-4-6x20-dt-ngan", status: "done" },
  { no: 5472, title: "Xây Nhà Cấp 4 Có Gác Lửng", keyword: "xây nhà cấp 4 có gác lửng", slug: "xay-nha-cap-4-co-gac-lung-dt-ngan", status: "done" },
  { no: 5473, title: "Chi Phí Xây Nhà 40m2", keyword: "chi phí xây nhà 40m2", slug: "chi-phi-xay-nha-40m2-dt-ngan", status: "done" },
  { no: 5474, title: "Chi Phí Xây Nhà 50m2", keyword: "chi phí xây nhà 50m2", slug: "chi-phi-xay-nha-50m2-dt-ngan", status: "done" },
  { no: 5475, title: "Chi Phí Xây Nhà 60m2", keyword: "chi phí xây nhà 60m2", slug: "chi-phi-xay-nha-60m2-dt-ngan", status: "done" },
  { no: 5476, title: "Chi Phí Xây Nhà 70m2", keyword: "chi phí xây nhà 70m2", slug: "chi-phi-xay-nha-70m2-dt-ngan", status: "done" },
  { no: 5477, title: "Chi Phí Xây Nhà 80m2", keyword: "chi phí xây nhà 80m2", slug: "chi-phi-xay-nha-80m2-dt-ngan", status: "done" },
  { no: 5478, title: "Chi Phí Xây Nhà 90m2", keyword: "chi phí xây nhà 90m2", slug: "chi-phi-xay-nha-90m2-dt-ngan", status: "done" },
  { no: 5479, title: "Chi Phí Xây Nhà 100m2 DT", keyword: "chi phí xây nhà 100m2", slug: "chi-phi-xay-nha-100m2-dt-ngan", status: "done" },
  { no: 5480, title: "Chi Phí Xây Nhà 120m2 DT", keyword: "chi phí xây nhà 120m2", slug: "chi-phi-xay-nha-120m2-dt-ngan", status: "done" },
  { no: 5481, title: "Chi Phí Xây Nhà 150m2 DT", keyword: "chi phí xây nhà 150m2", slug: "chi-phi-xay-nha-150m2-dt-ngan", status: "done" },
  { no: 5482, title: "Chi Phí Xây Nhà 200m2 DT", keyword: "chi phí xây nhà 200m2", slug: "chi-phi-xay-nha-200m2-dt-ngan", status: "done" },
  { no: 5483, title: "Xây Nhà 800 Triệu", keyword: "xây nhà 800 triệu", slug: "xay-nha-800-trieu-dt-ngan", status: "done" },
  { no: 5484, title: "Xây Nhà 1 Tỷ Đồng", keyword: "xây nhà 1 tỷ đồng", slug: "xay-nha-1-ty-dong-dt-ngan", status: "done" },
  { no: 5485, title: "Xây Nhà 1.5 Tỷ", keyword: "xây nhà 1.5 tỷ", slug: "xay-nha-1-5-ty-dt-ngan", status: "done" },
  { no: 5486, title: "Xây Nhà 2 Tỷ Đồng", keyword: "xây nhà 2 tỷ đồng", slug: "xay-nha-2-ty-dong-dt-ngan", status: "done" },
  { no: 5487, title: "Xây Nhà 2.5 Tỷ", keyword: "xây nhà 2.5 tỷ", slug: "xay-nha-2-5-ty-dt-ngan", status: "done" },
  { no: 5488, title: "Xây Nhà 3 Tỷ Đồng", keyword: "xây nhà 3 tỷ đồng", slug: "xay-nha-3-ty-dong-dt-ngan", status: "done" },
  { no: 5489, title: "Xây Nhà 4 Tỷ Đồng", keyword: "xây nhà 4 tỷ đồng", slug: "xay-nha-4-ty-dong-dt-ngan", status: "done" },
  { no: 5490, title: "Xây Nhà 5 Tỷ Đồng", keyword: "xây nhà 5 tỷ đồng", slug: "xay-nha-5-ty-dong-dt-ngan", status: "done" },
  { no: 5491, title: "Xây Nhà 7 Tỷ Đồng", keyword: "xây nhà 7 tỷ đồng", slug: "xay-nha-7-ty-dong-dt-ngan", status: "done" },
  { no: 5492, title: "Xây Nhà 10 Tỷ Đồng", keyword: "xây nhà 10 tỷ đồng", slug: "xay-nha-10-ty-dong-dt-ngan", status: "done" },
  { no: 5493, title: "Cải Tạo Nhà 100 Triệu", keyword: "cải tạo nhà 100 triệu", slug: "cai-tao-nha-100-trieu-dt-ngan", status: "done" },
  { no: 5494, title: "Cải Tạo Nhà 200 Triệu DT", keyword: "cải tạo nhà 200 triệu", slug: "cai-tao-nha-200-trieu-dt-ngan", status: "done" },
  { no: 5495, title: "Cải Tạo Nhà 300 Triệu", keyword: "cải tạo nhà 300 triệu", slug: "cai-tao-nha-300-trieu-dt-ngan", status: "done" },
  { no: 5496, title: "Cải Tạo Nhà 500 Triệu DT", keyword: "cải tạo nhà 500 triệu", slug: "cai-tao-nha-500-trieu-dt-ngan", status: "done" },
  { no: 5497, title: "Cải Tạo Nhà 700 Triệu", keyword: "cải tạo nhà 700 triệu", slug: "cai-tao-nha-700-trieu-dt-ngan", status: "done" },
  { no: 5498, title: "Cải Tạo Nhà 1 Tỷ DT", keyword: "cải tạo nhà 1 tỷ", slug: "cai-tao-nha-1-ty-dt-ngan", status: "done" },
  { no: 5499, title: "Nhà 2 Tầng 3 Phòng Ngủ", keyword: "nhà 2 tầng 3 phòng ngủ", slug: "nha-2-tang-3-phong-ngu-dt-ngan", status: "done" },
  { no: 5500, title: "Nhà 3 Tầng 4 Phòng Ngủ", keyword: "nhà 3 tầng 4 phòng ngủ", slug: "nha-3-tang-4-phong-ngu-dt-ngan", status: "done" },
  { no: 5501, title: "Nhà 4 Tầng 5 Phòng Ngủ", keyword: "nhà 4 tầng 5 phòng ngủ", slug: "nha-4-tang-5-phong-ngu-dt-ngan", status: "done" },
  { no: 5502, title: "Nhà 5 Tầng Có Thang Máy", keyword: "nhà 5 tầng có thang máy", slug: "nha-5-tang-co-thang-may-dt-ngan", status: "done" },
  { no: 5503, title: "Nhà Lửng 1 Trệt 1 Lửng", keyword: "nhà lửng 1 trệt 1 lửng", slug: "nha-lung-1-tret-1-lung-dt-ngan", status: "done" },
  { no: 5504, title: "Nhà 1 Trệt 1 Lầu 1 Áp Mái", keyword: "nhà 1 trệt 1 lầu 1 áp mái", slug: "nha-1-tret-1-lau-1-ap-mai-dt-ngan", status: "done" },
  { no: 5505, title: "Nhà Có Hầm 1 Trệt 2 Lầu", keyword: "nhà có hầm 1 trệt 2 lầu", slug: "nha-co-ham-1-tret-2-lau-dt-ngan", status: "done" },
  { no: 5506, title: "Nhà Có Hầm 1 Trệt 3 Lầu", keyword: "nhà có hầm 1 trệt 3 lầu", slug: "nha-co-ham-1-tret-3-lau-dt-ngan", status: "done" },
  { no: 5507, title: "Diện Tích Sàn Xây Dựng", keyword: "diện tích sàn xây dựng", slug: "dien-tich-san-xay-dung-dt-ngan", status: "done" },
  { no: 5508, title: "Cách Tính Diện Tích Xây", keyword: "cách tính diện tích xây", slug: "cach-tinh-dien-tich-xay-dt-ngan", status: "done" },
  { no: 5509, title: "Hệ Số Diện Tích Xây", keyword: "hệ số diện tích xây", slug: "he-so-dien-tich-xay-dt-ngan", status: "done" },
  { no: 5510, title: "Diện Tích Thông Thủy", keyword: "diện tích thông thủy", slug: "dien-tich-thong-thuy-dt-ngan", status: "done" },
  { no: 5511, title: "Diện Tích Tim Tường", keyword: "diện tích tim tường", slug: "dien-tich-tim-tuong-dt-ngan", status: "done" },
  { no: 5512, title: "Mật Độ Xây 60 Phần Trăm", keyword: "mật độ xây 60%", slug: "mat-do-xay-60-phan-tram-dt-ngan", status: "done" },
  { no: 5513, title: "Mật Độ Xây 80 Phần Trăm", keyword: "mật độ xây 80%", slug: "mat-do-xay-80-phan-tram-dt-ngan", status: "done" },
  { no: 5514, title: "Mật Độ Xây 100 Phần Trăm", keyword: "mật độ xây 100%", slug: "mat-do-xay-100-phan-tram-dt-ngan", status: "done" },
  { no: 5515, title: "Nhà Hẹp 3m Làm Sao Đẹp", keyword: "nhà hẹp 3m làm sao đẹp", slug: "nha-hep-3m-lam-sao-dep-dt-ngan", status: "done" },
  { no: 5516, title: "Nhà Hẹp 3.5m Layout", keyword: "nhà hẹp 3.5m layout", slug: "nha-hep-3-5m-layout-dt-ngan", status: "done" },
  { no: 5517, title: "Nhà Hẹp 4m Layout Đẹp", keyword: "nhà hẹp 4m layout đẹp", slug: "nha-hep-4m-layout-dep-dt-ngan", status: "done" },
  { no: 5518, title: "Nhà Nông 12m Layout", keyword: "nhà nông 12m layout", slug: "nha-nong-12m-layout-dt-ngan", status: "done" },
  { no: 5519, title: "Nhà Nông 15m Layout", keyword: "nhà nông 15m layout", slug: "nha-nong-15m-layout-dt-ngan", status: "done" },
  { no: 5520, title: "Nhà Nông 20m Layout", keyword: "nhà nông 20m layout", slug: "nha-nong-20m-layout-dt-ngan", status: "done" },
  { no: 5521, title: "Báo Giá Nhà 4x12 Trọn Gói", keyword: "báo giá nhà 4x12 trọn gói", slug: "bao-gia-nha-4x12-tron-goi-dt-ngan", status: "done" },
  { no: 5522, title: "Báo Giá Nhà 5x15 Trọn Gói", keyword: "báo giá nhà 5x15 trọn gói", slug: "bao-gia-nha-5x15-tron-goi-dt-ngan", status: "done" },
  { no: 5523, title: "Báo Giá Nhà 5x20 Trọn Gói", keyword: "báo giá nhà 5x20 trọn gói", slug: "bao-gia-nha-5x20-tron-goi-dt-ngan", status: "done" },
  { no: 5524, title: "Báo Giá Nhà 6x20 Trọn Gói", keyword: "báo giá nhà 6x20 trọn gói", slug: "bao-gia-nha-6x20-tron-goi-dt-ngan", status: "done" },
  { no: 5525, title: "Xây Nhà Phần Thô 4x12", keyword: "xây nhà phần thô 4x12", slug: "xay-nha-phan-tho-4x12-dt-ngan", status: "done" },
  { no: 5526, title: "Xây Nhà Phần Thô 5x15", keyword: "xây nhà phần thô 5x15", slug: "xay-nha-phan-tho-5x15-dt-ngan", status: "done" },
  { no: 5527, title: "Xây Nhà Phần Thô 5x20", keyword: "xây nhà phần thô 5x20", slug: "xay-nha-phan-tho-5x20-dt-ngan", status: "done" },
  { no: 5528, title: "Hoàn Thiện Nhà 4x12", keyword: "hoàn thiện nhà 4x12", slug: "hoan-thien-nha-4x12-dt-ngan", status: "done" },
  { no: 5529, title: "Hoàn Thiện Nhà 5x15", keyword: "hoàn thiện nhà 5x15", slug: "hoan-thien-nha-5x15-dt-ngan", status: "done" },
  { no: 5530, title: "Hoàn Thiện Nhà 5x20", keyword: "hoàn thiện nhà 5x20", slug: "hoan-thien-nha-5x20-dt-ngan", status: "done" },
  { no: 5531, title: "Tiến Độ Nhà 3 Tầng", keyword: "tiến độ nhà 3 tầng", slug: "tien-do-nha-3-tang-dt-ngan", status: "done" },
  { no: 5532, title: "Tiến Độ Nhà 4 Tầng", keyword: "tiến độ nhà 4 tầng", slug: "tien-do-nha-4-tang-dt-ngan", status: "done" },
  { no: 5533, title: "Tiến Độ Nhà 5 Tầng", keyword: "tiến độ nhà 5 tầng", slug: "tien-do-nha-5-tang-dt-ngan", status: "done" },
  { no: 5534, title: "Mẫu Nhà 4x12 Hiện Đại", keyword: "mẫu nhà 4x12 hiện đại", slug: "mau-nha-4x12-hien-dai-dt-ngan", status: "done" },
  { no: 5535, title: "Mẫu Nhà 5x15 Hiện Đại", keyword: "mẫu nhà 5x15 hiện đại", slug: "mau-nha-5x15-hien-dai-dt-ngan", status: "done" },
  { no: 5536, title: "Mẫu Nhà 5x20 Hiện Đại", keyword: "mẫu nhà 5x20 hiện đại", slug: "mau-nha-5x20-hien-dai-dt-ngan", status: "done" },
  { no: 5537, title: "Mẫu Nhà 4x12 Mái Thái", keyword: "mẫu nhà 4x12 mái thái", slug: "mau-nha-4x12-mai-thai-dt-ngan", status: "done" },
  { no: 5538, title: "Mẫu Nhà 5x15 Mái Nhật", keyword: "mẫu nhà 5x15 mái nhật", slug: "mau-nha-5x15-mai-nhat-dt-ngan", status: "done" },
  { no: 5539, title: "Checklist Chọn Diện Tích Xây", keyword: "checklist chọn diện tích xây", slug: "checklist-chon-dien-tich-xay-dt-ngan", status: "done" },
  { no: 5540, title: "Nên Xây Mấy Tầng", keyword: "nên xây mấy tầng", slug: "nen-xay-may-tang-dt-ngan", status: "done" },
  { no: 5541, title: "Diện Tích Bao Nhiêu Là Đủ", keyword: "diện tích bao nhiêu là đủ", slug: "dien-tich-bao-nhieu-la-du-dt-ngan", status: "done" },
  { no: 5542, title: "Tối Ưu Diện Tích Nhà Hẹp", keyword: "tối ưu diện tích nhà hẹp", slug: "toi-uu-dien-tich-nha-hep-dt-ngan", status: "done" },
  { no: 5543, title: "Tối Ưu Ngân Sách Theo m2", keyword: "tối ưu ngân sách theo m2", slug: "toi-uu-ngan-sach-theo-m2-dt-ngan", status: "done" },
  { no: 5544, title: "Chủ Đề Mở Rộng 60 1", keyword: "chủ đề mở rộng 60 1", slug: "chu-de-mo-rong-60-1-ngan", status: "done" },
  { no: 5545, title: "Chủ Đề Mở Rộng 60 2", keyword: "chủ đề mở rộng 60 2", slug: "chu-de-mo-rong-60-2-ngan", status: "done" },
  { no: 5546, title: "Chủ Đề Mở Rộng 60 3", keyword: "chủ đề mở rộng 60 3", slug: "chu-de-mo-rong-60-3-ngan", status: "done" },
];
