/**
 * Lịch 100 từ khóa ngắn — batch 46 (#4047–#4146).
 * Cluster: vật liệu chi tiết, so sánh vật liệu.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch46: ContentCalendarItem[] = [
  { no: 4047, title: "Gạch Block Xây Nhà", keyword: "gạch block xây nhà", slug: "gach-block-xay-nha-vl-ngan", status: "done" },
  { no: 4048, title: "Gạch Ống Xây Nhà", keyword: "gạch ống xây nhà", slug: "gach-ong-xay-nha-vl-ngan", status: "done" },
  { no: 4049, title: "Gạch Đặc Xây Nhà", keyword: "gạch đặc xây nhà", slug: "gach-dac-xay-nha-vl-ngan", status: "done" },
  { no: 4050, title: "Gạch Không Nung AAC", keyword: "gạch không nung aac", slug: "gach-khong-nung-aac-vl-ngan", status: "done" },
  { no: 4051, title: "Gạch Bê Tông Nhẹ", keyword: "gạch bê tông nhẹ", slug: "gach-be-tong-nhe-vl-ngan", status: "done" },
  { no: 4052, title: "Gạch Clinker Mặt Tiền", keyword: "gạch clinker mặt tiền", slug: "gach-clinker-mat-tien-vl-ngan", status: "done" },
  { no: 4053, title: "Gạch Thẻ Ốp Tường", keyword: "gạch thẻ ốp tường", slug: "gach-the-op-tuong-vl-ngan", status: "done" },
  { no: 4054, title: "Gạch Mosaic Trang Trí", keyword: "gạch mosaic trang trí", slug: "gach-mosaic-trang-tri-vl-ngan", status: "done" },
  { no: 4055, title: "Gạch Thông Minh Ốp Lát", keyword: "gạch thông minh ốp lát", slug: "gach-thong-minh-op-lat-vl-ngan", status: "done" },
  { no: 4056, title: "Đá Granite Đen Ấn Độ", keyword: "đá granite đen ấn độ", slug: "da-granite-den-an-do-vl-ngan", status: "done" },
  { no: 4057, title: "Đá Granite Trắng Suối La", keyword: "đá granite trắng suối la", slug: "da-granite-trang-suoi-la-vl-ngan", status: "done" },
  { no: 4058, title: "Đá Marble Olivia", keyword: "đá marble olivia", slug: "da-marble-olivia-vl-ngan", status: "done" },
  { no: 4059, title: "Đá Marble Carrara", keyword: "đá marble carrara", slug: "da-marble-carrara-vl-ngan", status: "done" },
  { no: 4060, title: "Đá Nhân Tạo Bếp", keyword: "đá nhân tạo bếp", slug: "da-nhan-tao-bep-vl-ngan", status: "done" },
  { no: 4061, title: "Đá Quartz Bếp", keyword: "đá quartz bếp", slug: "da-quartz-bep-vl-ngan", status: "done" },
  { no: 4062, title: "Đá Compact Bếp", keyword: "đá compact bếp", slug: "da-compact-bep-vl-ngan", status: "done" },
  { no: 4063, title: "Gỗ Óc Chó Nội Thất", keyword: "gỗ óc chó nội thất", slug: "go-oc-cho-noi-that-vl-ngan", status: "done" },
  { no: 4064, title: "Gỗ Sồi Nội Thất", keyword: "gỗ sồi nội thất", slug: "go-soi-noi-that-vl-ngan", status: "done" },
  { no: 4065, title: "Gỗ Teak Nội Thất", keyword: "gỗ teak nội thất", slug: "go-teak-noi-that-vl-ngan", status: "done" },
  { no: 4066, title: "Gỗ Xoan Đào Nội Thất", keyword: "gỗ xoan đào nội thất", slug: "go-xoan-dao-noi-that-vl-ngan", status: "done" },
  { no: 4067, title: "Gỗ MDF Chống Ẩm", keyword: "gỗ mdf chống ẩm", slug: "go-mdf-chong-am-vl-ngan", status: "done" },
  { no: 4068, title: "Gỗ HDF Sàn", keyword: "gỗ hdf sàn", slug: "go-hdf-san-vl-ngan", status: "done" },
  { no: 4069, title: "Gỗ Plywood Nội Thất", keyword: "gỗ plywood nội thất", slug: "go-plywood-noi-that-vl-ngan", status: "done" },
  { no: 4070, title: "Nhựa PVC Cửa", keyword: "nhựa pvc cửa", slug: "nhua-pvc-cua-vl-ngan", status: "done" },
  { no: 4071, title: "Nhựa UPVC Cửa Sổ", keyword: "nhựa upvc cửa sổ", slug: "nhua-upvc-cua-so-vl-ngan", status: "done" },
  { no: 4072, title: "Nhôm Hệ 55", keyword: "nhôm hệ 55", slug: "nhom-he-55-vl-ngan", status: "done" },
  { no: 4073, title: "Nhôm Hệ 65", keyword: "nhôm hệ 65", slug: "nhom-he-65-vl-ngan", status: "done" },
  { no: 4074, title: "Nhôm Hệ 93", keyword: "nhôm hệ 93", slug: "nhom-he-93-vl-ngan", status: "done" },
  { no: 4075, title: "Kính Tempered 8mm", keyword: "kính tempered 8mm", slug: "kinh-tempered-8mm-vl-ngan", status: "done" },
  { no: 4076, title: "Kính Tempered 10mm", keyword: "kính tempered 10mm", slug: "kinh-tempered-10mm-vl-ngan", status: "done" },
  { no: 4077, title: "Kính Laminated An Toàn", keyword: "kính laminated an toàn", slug: "kinh-laminated-an-toan-vl-ngan", status: "done" },
  { no: 4078, title: "Kính Low-E Cách Nhiệt", keyword: "kính low-e cách nhiệt", slug: "kinh-low-e-cach-nhiet-vl-ngan", status: "done" },
  { no: 4079, title: "Kính Reflective Mặt Tiền", keyword: "kính reflective mặt tiền", slug: "kinh-reflective-mat-tien-vl-ngan", status: "done" },
  { no: 4080, title: "Tôn Lạnh Cách Nhiệt", keyword: "tôn lạnh cách nhiệt", slug: "ton-lanh-cach-nhiet-vl-ngan", status: "done" },
  { no: 4081, title: "Tôn Cách Nhiệt 3 Lớp", keyword: "tôn cách nhiệt 3 lớp", slug: "ton-cach-nhiet-3-lop-vl-ngan", status: "done" },
  { no: 4082, title: "Ngói Bitum Phủ Đá", keyword: "ngói bitum phủ đá", slug: "ngoi-bitum-phu-da-vl-ngan", status: "done" },
  { no: 4083, title: "Ngói Nhựa ASA", keyword: "ngói nhựa asa", slug: "ngoi-nhua-asa-vl-ngan", status: "done" },
  { no: 4084, title: "Ngói Xi Măng Màu", keyword: "ngói xi măng màu", slug: "ngoi-xi-mang-mau-vl-ngan", status: "done" },
  { no: 4085, title: "Sơn Epoxy Sàn", keyword: "sơn epoxy sàn", slug: "son-epoxy-san-vl-ngan", status: "done" },
  { no: 4086, title: "Sơn Polyurethane", keyword: "sơn polyurethane", slug: "son-polyurethane-vl-ngan", status: "done" },
  { no: 4087, title: "Sơn Chống Thấm Gốc Xi", keyword: "sơn chống thấm gốc xi", slug: "son-chong-tham-goc-xi-vl-ngan", status: "done" },
  { no: 4088, title: "Sơn Chống Thấm Gốc Nhựa", keyword: "sơn chống thấm gốc nhựa", slug: "son-chong-tham-goc-nhua-vl-ngan", status: "done" },
  { no: 4089, title: "Màng Chống Thấm Khò Nóng", keyword: "màng chống thấm khò nóng", slug: "mang-chong-tham-kho-nong-vl-ngan", status: "done" },
  { no: 4090, title: "Màng Chống Thấm Tự Dính", keyword: "màng chống thấm tự dính", slug: "mang-chong-tham-tu-dinh-vl-ngan", status: "done" },
  { no: 4091, title: "Keo Chống Thấm Polyurea", keyword: "keo chống thấm polyurea", slug: "keo-chong-tham-polyurea-vl-ngan", status: "done" },
  { no: 4092, title: "Foam Cách Nhiệt Phun", keyword: "foam cách nhiệt phun", slug: "foam-cach-nhiet-phun-vl-ngan", status: "done" },
  { no: 4093, title: "Xốp XPS Cách Nhiệt", keyword: "xốp xps cách nhiệt", slug: "xop-xps-cach-nhiet-vl-ngan", status: "done" },
  { no: 4094, title: "Xốp EPS Cách Nhiệt", keyword: "xốp eps cách nhiệt", slug: "xop-eps-cach-nhiet-vl-ngan", status: "done" },
  { no: 4095, title: "Bông Thủy Tinh Cách Âm", keyword: "bông thủy tinh cách âm", slug: "bong-thuy-tinh-cach-am-vl-ngan", status: "done" },
  { no: 4096, title: "Bông Khoáng Cách Âm", keyword: "bông khoáng cách âm", slug: "bong-khoang-cach-am-vl-ngan", status: "done" },
  { no: 4097, title: "Tấm Cemboard", keyword: "tấm cemboard", slug: "tam-cemboard-vl-ngan", status: "done" },
  { no: 4098, title: "Tấm Smartboard", keyword: "tấm smartboard", slug: "tam-smartboard-vl-ngan", status: "done" },
  { no: 4099, title: "Tấm Duraflex", keyword: "tấm duraflex", slug: "tam-duraflex-vl-ngan", status: "done" },
  { no: 4100, title: "Tấm Thạch Cao Chịu Ẩm", keyword: "tấm thạch cao chịu ẩm", slug: "tam-thach-cao-chiu-am-vl-ngan", status: "done" },
  { no: 4101, title: "Tấm Thạch Cao Chịu Lửa", keyword: "tấm thạch cao chịu lửa", slug: "tam-thach-cao-chiu-lua-vl-ngan", status: "done" },
  { no: 4102, title: "Inox 304 Lan Can", keyword: "inox 304 lan can", slug: "inox-304-lan-can-vl-ngan", status: "done" },
  { no: 4103, title: "Inox 201 Lan Can", keyword: "inox 201 lan can", slug: "inox-201-lan-can-vl-ngan", status: "done" },
  { no: 4104, title: "Sắt Hộp 40x40", keyword: "sắt hộp 40x40", slug: "sat-hop-40x40-vl-ngan", status: "done" },
  { no: 4105, title: "Sắt Hộp 50x50", keyword: "sắt hộp 50x50", slug: "sat-hop-50x50-vl-ngan", status: "done" },
  { no: 4106, title: "Thép Hình I Xây Nhà", keyword: "thép hình i xây nhà", slug: "thep-hinh-i-xay-nha-vl-ngan", status: "done" },
  { no: 4107, title: "Thép Hình H Xây Nhà", keyword: "thép hình h xây nhà", slug: "thep-hinh-h-xay-nha-vl-ngan", status: "done" },
  { no: 4108, title: "So Sánh Gạch Block Và Ống", keyword: "so sánh gạch block và ống", slug: "so-sanh-gach-block-va-ong-vl-ngan", status: "done" },
  { no: 4109, title: "So Sánh AAC Và Gạch Nung", keyword: "so sánh aac và gạch nung", slug: "so-sanh-aac-va-gach-nung-vl-ngan", status: "done" },
  { no: 4110, title: "So Sánh Granite Và Marble", keyword: "so sánh granite và marble", slug: "so-sanh-granite-va-marble-vl-ngan", status: "done" },
  { no: 4111, title: "So Sánh Quartz Và Granite", keyword: "so sánh quartz và granite", slug: "so-sanh-quartz-va-granite-vl-ngan", status: "done" },
  { no: 4112, title: "So Sánh MDF Và Plywood", keyword: "so sánh mdf và plywood", slug: "so-sanh-mdf-va-plywood-vl-ngan", status: "done" },
  { no: 4113, title: "So Sánh Nhôm Và UPVC", keyword: "so sánh nhôm và upvc", slug: "so-sanh-nhom-va-upvc-vl-ngan", status: "done" },
  { no: 4114, title: "So Sánh Tôn Và Ngói", keyword: "so sánh tôn và ngói", slug: "so-sanh-ton-va-ngoi-vl-ngan", status: "done" },
  { no: 4115, title: "So Sánh XPS Và EPS", keyword: "so sánh xps và eps", slug: "so-sanh-xps-va-eps-vl-ngan", status: "done" },
  { no: 4116, title: "So Sánh Inox 304 Và 201", keyword: "so sánh inox 304 và 201", slug: "so-sanh-inox-304-va-201-vl-ngan", status: "done" },
  { no: 4117, title: "Cách Chọn Gạch Ốp Lát", keyword: "cách chọn gạch ốp lát", slug: "cach-chon-gach-op-lat-vl-ngan", status: "done" },
  { no: 4118, title: "Cách Chọn Đá Bếp", keyword: "cách chọn đá bếp", slug: "cach-chon-da-bep-vl-ngan", status: "done" },
  { no: 4119, title: "Cách Chọn Gỗ Nội Thất", keyword: "cách chọn gỗ nội thất", slug: "cach-chon-go-noi-that-vl-ngan", status: "done" },
  { no: 4120, title: "Cách Chọn Nhôm Kính", keyword: "cách chọn nhôm kính", slug: "cach-chon-nhom-kinh-vl-ngan", status: "done" },
  { no: 4121, title: "Cách Chọn Tôn Lợp", keyword: "cách chọn tôn lợp", slug: "cach-chon-ton-lop-vl-ngan", status: "done" },
  { no: 4122, title: "Cách Chọn Sơn Ngoại Thất", keyword: "cách chọn sơn ngoại thất", slug: "cach-chon-son-ngoai-that-vl-ngan", status: "done" },
  { no: 4123, title: "Cách Chọn Sơn Nội Thất", keyword: "cách chọn sơn nội thất", slug: "cach-chon-son-noi-that-vl-ngan", status: "done" },
  { no: 4124, title: "Cách Chọn Vật Liệu Chống Thấm", keyword: "cách chọn vật liệu chống thấm", slug: "cach-chon-vat-lieu-chong-tham-vl-ngan", status: "done" },
  { no: 4125, title: "Bảng Giá Gạch Ốp Lát 2026", keyword: "bảng giá gạch ốp lát 2026", slug: "bang-gia-gach-op-lat-2026-vl-ngan", status: "done" },
  { no: 4126, title: "Bảng Giá Đá Granite 2026", keyword: "bảng giá đá granite 2026", slug: "bang-gia-da-granite-2026-vl-ngan", status: "done" },
  { no: 4127, title: "Bảng Giá Nhôm Kính 2026", keyword: "bảng giá nhôm kính 2026", slug: "bang-gia-nhom-kinh-2026-vl-ngan", status: "done" },
  { no: 4128, title: "Bảng Giá Tôn Lợp 2026", keyword: "bảng giá tôn lợp 2026", slug: "bang-gia-ton-lop-2026-vl-ngan", status: "done" },
  { no: 4129, title: "Bảng Giá Sơn Dulux 2026", keyword: "bảng giá sơn dulux 2026", slug: "bang-gia-son-dulux-2026-vl-ngan", status: "done" },
  { no: 4130, title: "Vật Liệu Xanh Tiết Kiệm", keyword: "vật liệu xanh tiết kiệm", slug: "vat-lieu-xanh-tiet-kiem-vl-ngan", status: "done" },
  { no: 4131, title: "Vật Liệu Tái Chế Xây Nhà", keyword: "vật liệu tái chế xây nhà", slug: "vat-lieu-tai-che-xay-nha-vl-ngan", status: "done" },
  { no: 4132, title: "Vật Liệu Local Source", keyword: "vật liệu local source", slug: "vat-lieu-local-source-vl-ngan", status: "done" },
  { no: 4133, title: "Kiểm Tra Chất Lượng Vật Tư", keyword: "kiểm tra chất lượng vật tư", slug: "kiem-tra-chat-luong-vat-tu-vl-ngan", status: "done" },
  { no: 4134, title: "Nhận Biết Vật Tư Fake", keyword: "nhận biết vật tư fake", slug: "nhan-biet-vat-tu-fake-vl-ngan", status: "done" },
  { no: 4135, title: "Bảo Quản Vật Tư Công Trình", keyword: "bảo quản vật tư công trình", slug: "bao-quan-vat-tu-cong-trinh-vl-ngan", status: "done" },
  { no: 4136, title: "Định Mức Vật Tư Xây Nhà", keyword: "định mức vật tư xây nhà", slug: "dinh-muc-vat-tu-xay-nha-vl-ngan", status: "done" },
  { no: 4137, title: "Định Mức Xi Măng m2", keyword: "định mức xi măng m2", slug: "dinh-muc-xi-mang-m2-vl-ngan", status: "done" },
  { no: 4138, title: "Định Mức Thép m2", keyword: "định mức thép m2", slug: "dinh-muc-thep-m2-vl-ngan", status: "done" },
  { no: 4139, title: "Định Mức Gạch m2", keyword: "định mức gạch m2", slug: "dinh-muc-gach-m2-vl-ngan", status: "done" },
  { no: 4140, title: "Định Mức Cát Đá m2", keyword: "định mức cát đá m2", slug: "dinh-muc-cat-da-m2-vl-ngan", status: "done" },
  { no: 4141, title: "Chủ Đề Mở Rộng 46 1", keyword: "chủ đề mở rộng 46 1", slug: "chu-de-mo-rong-46-1-ngan", status: "done" },
  { no: 4142, title: "Chủ Đề Mở Rộng 46 2", keyword: "chủ đề mở rộng 46 2", slug: "chu-de-mo-rong-46-2-ngan", status: "done" },
  { no: 4143, title: "Chủ Đề Mở Rộng 46 3", keyword: "chủ đề mở rộng 46 3", slug: "chu-de-mo-rong-46-3-ngan", status: "done" },
  { no: 4144, title: "Chủ Đề Mở Rộng 46 4", keyword: "chủ đề mở rộng 46 4", slug: "chu-de-mo-rong-46-4-ngan", status: "done" },
  { no: 4145, title: "Chủ Đề Mở Rộng 46 5", keyword: "chủ đề mở rộng 46 5", slug: "chu-de-mo-rong-46-5-ngan", status: "done" },
  { no: 4146, title: "Chủ Đề Mở Rộng 46 6", keyword: "chủ đề mở rộng 46 6", slug: "chu-de-mo-rong-46-6-ngan", status: "done" },
];
