/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 21 (#1547–#1646).
 * Cluster: kỹ thuật thi công, phá dỡ, nghiệm thu, pháp lý kỹ thuật.
 * Suffix `-ngan` tránh trùng money pages / batch trước.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch21: ContentCalendarItem[] = [
  { no: 1547, title: "Đóng Cọc Tre", keyword: "đóng cọc tre", slug: "dong-coc-tre-ngan", status: "done" },
  { no: 1548, title: "Ép Cọc Bê Tông", keyword: "ép cọc bê tông", slug: "ep-coc-be-tong-ngan", status: "done" },
  { no: 1549, title: "Ép Cọc Vuông", keyword: "ép cọc vuông", slug: "ep-coc-vuong-ngan", status: "done" },
  { no: 1550, title: "Ép Cọc Tròn", keyword: "ép cọc tròn", slug: "ep-coc-tron-ngan", status: "done" },
  { no: 1551, title: "Khoan Nhồi Barrette", keyword: "khoan nhồi barrette", slug: "khoan-nhoi-barrette-ngan", status: "done" },
  { no: 1552, title: "Đào Móng Nhà", keyword: "đào móng nhà", slug: "dao-mong-nha-ngan", status: "done" },
  { no: 1553, title: "Đắp Đất Nền", keyword: "đắp đất nền", slug: "dap-dat-nen-ngan", status: "done" },
  { no: 1554, title: "Lu Nền Nhà", keyword: "lu nền nhà", slug: "lu-nen-nha-ngan", status: "done" },
  { no: 1555, title: "San Lấp Mặt Bằng", keyword: "san lấp mặt bằng", slug: "san-lap-mat-bang-ngan", status: "done" },
  { no: 1556, title: "Phá Dỡ Nhà Cũ", keyword: "phá dỡ nhà cũ", slug: "pha-do-nha-cu-ngan", status: "done" },
  { no: 1557, title: "Phá Tường Nhà", keyword: "phá tường nhà", slug: "pha-tuong-nha-ngan", status: "done" },
  { no: 1558, title: "Đục Tường Nhà", keyword: "đục tường nhà", slug: "duc-tuong-nha-ngan", status: "done" },
  { no: 1559, title: "Xây Tường Nhà", keyword: "xây tường nhà", slug: "xay-tuong-nha-ngan", status: "done" },
  { no: 1560, title: "Tô Tường Nhà", keyword: "tô tường nhà", slug: "to-tuong-nha-ngan", status: "done" },
  { no: 1561, title: "Trát Tường Nhà", keyword: "trát tường nhà", slug: "trat-tuong-nha-ngan", status: "done" },
  { no: 1562, title: "Ốp Tường Nhà", keyword: "ốp tường nhà", slug: "op-tuong-nha-ngan", status: "done" },
  { no: 1563, title: "Ốp Gạch WC", keyword: "ốp gạch wc", slug: "op-gach-wc-ngan", status: "done" },
  { no: 1564, title: "Ốp Gạch Bếp", keyword: "ốp gạch bếp", slug: "op-gach-bep-ngan", status: "done" },
  { no: 1565, title: "Lát Nền Nhà", keyword: "lát nền nhà", slug: "lat-nen-nha-ngan", status: "done" },
  { no: 1566, title: "Lát Gạch Sân", keyword: "lát gạch sân", slug: "lat-gach-san-ngan", status: "done" },
  { no: 1567, title: "Đổ Bê Tông Móng", keyword: "đổ bê tông móng", slug: "do-be-tong-mong-ngan", status: "done" },
  { no: 1568, title: "Đổ Bê Tông Cột", keyword: "đổ bê tông cột", slug: "do-be-tong-cot-ngan", status: "done" },
  { no: 1569, title: "Đổ Bê Tông Sàn", keyword: "đổ bê tông sàn", slug: "do-be-tong-san-ngan", status: "done" },
  { no: 1570, title: "Đầm Bê Tông", keyword: "đầm bê tông", slug: "dam-be-tong-ngan", status: "done" },
  { no: 1571, title: "Bảo Dưỡng Bê Tông", keyword: "bảo dưỡng bê tông", slug: "bao-duong-be-tong-ngan", status: "done" },
  { no: 1572, title: "Cốt Thép Cột", keyword: "cốt thép cột", slug: "cot-thep-cot-ngan", status: "done" },
  { no: 1573, title: "Cốt Thép Dầm", keyword: "cốt thép dầm", slug: "cot-thep-dam-ngan", status: "done" },
  { no: 1574, title: "Cốt Thép Sàn", keyword: "cốt thép sàn", slug: "cot-thep-san-ngan", status: "done" },
  { no: 1575, title: "Nghiệm Thu Thép", keyword: "nghiệm thu thép", slug: "nghiem-thu-thep-ngan", status: "done" },
  { no: 1576, title: "Nghiệm Thu Bê Tông", keyword: "nghiệm thu bê tông", slug: "nghiem-thu-be-tong-ngan", status: "done" },
  { no: 1577, title: "Chống Thấm Móng", keyword: "chống thấm móng", slug: "chong-tham-mong-ngan", status: "done" },
  { no: 1578, title: "Chống Thấm Hầm", keyword: "chống thấm hầm", slug: "chong-tham-ham-ngan", status: "done" },
  { no: 1579, title: "Chống Thấm Hồ Bơi", keyword: "chống thấm hồ bơi", slug: "chong-tham-ho-boi-ngan", status: "done" },
  { no: 1580, title: "Xử Lý Nứt Dầm", keyword: "xử lý nứt dầm", slug: "xu-ly-nut-dam-ngan", status: "done" },
  { no: 1581, title: "Xử Lý Nứt Cột", keyword: "xử lý nứt cột", slug: "xu-ly-nut-cot-ngan", status: "done" },
  { no: 1582, title: "Carbon Fiber Gia Cố", keyword: "carbon fiber gia cố", slug: "carbon-fiber-gia-co-ngan", status: "done" },
  { no: 1583, title: "Gia Cố Sợi Carbon", keyword: "gia cố sợi carbon", slug: "gia-co-soi-carbon-ngan", status: "done" },
  { no: 1584, title: "Chống Rung Nhà", keyword: "chống rung nhà", slug: "chong-rung-nha-ngan", status: "done" },
  { no: 1585, title: "Chống Ồn Nhà", keyword: "chống ồn nhà", slug: "chong-on-nha-ngan", status: "done" },
  { no: 1586, title: "Cách Âm Tường", keyword: "cách âm tường", slug: "cach-am-tuong-ngan", status: "done" },
  { no: 1587, title: "Cách Âm Trần", keyword: "cách âm trần", slug: "cach-am-tran-ngan", status: "done" },
  { no: 1588, title: "Cách Âm Sàn", keyword: "cách âm sàn", slug: "cach-am-san-ngan", status: "done" },
  { no: 1589, title: "Chống Cháy Nhà", keyword: "chống cháy nhà", slug: "chong-chay-nha-ngan", status: "done" },
  { no: 1590, title: "Sơn Chống Cháy", keyword: "sơn chống cháy", slug: "son-chong-chay-ngan", status: "done" },
  { no: 1591, title: "Cửa Chống Cháy", keyword: "cửa chống cháy", slug: "cua-chong-chay-ngan", status: "done" },
  { no: 1592, title: "Thang Thoát Hiểm", keyword: "thang thoát hiểm", slug: "thang-thoat-hiem-ngan", status: "done" },
  { no: 1593, title: "Lắp Đặt Thang Máy", keyword: "lắp đặt thang máy", slug: "lap-dat-thang-may-ngan", status: "done" },
  { no: 1594, title: "Hố Pit Thang Máy", keyword: "hố pit thang máy", slug: "ho-pit-thang-may-ngan", status: "done" },
  { no: 1595, title: "Khung Thép Tiền Chế", keyword: "khung thép tiền chế", slug: "khung-thep-tien-che-ngan", status: "done" },
  { no: 1596, title: "Nhà Khung Thép Nhẹ", keyword: "nhà khung thép nhẹ", slug: "nha-khung-thep-nhe-ngan", status: "done" },
  { no: 1597, title: "Nhà Container", keyword: "nhà container", slug: "nha-container-ngan", status: "done" },
  { no: 1598, title: "Nhà Lắp Ghép", keyword: "nhà lắp ghép", slug: "nha-lap-ghep-ngan", status: "done" },
  { no: 1599, title: "Nhà 3D Printing", keyword: "nhà 3d printing", slug: "nha-3d-printing-ngan", status: "done" },
  { no: 1600, title: "Thi Công Ban Đêm", keyword: "thi công ban đêm", slug: "thi-cong-ban-dem-ngan", status: "done" },
  { no: 1601, title: "Thi Công Trong Hẻm", keyword: "thi công trong hẻm", slug: "thi-cong-trong-hem-ngan", status: "done" },
  { no: 1602, title: "Vận Chuyển Vật Tư Hẻm", keyword: "vận chuyển vật tư hẻm", slug: "van-chuyen-vat-tu-hem-ngan", status: "done" },
  { no: 1603, title: "Cẩu Tháp Nhà Phố", keyword: "cẩu tháp nhà phố", slug: "cau-thap-nha-pho-ngan", status: "done" },
  { no: 1604, title: "Xe Bơm Bê Tông", keyword: "xe bơm bê tông", slug: "xe-bom-be-tong-ngan", status: "done" },
  { no: 1605, title: "Giàn Giáo Nhà", keyword: "giàn giáo nhà", slug: "gian-giao-nha-ngan", status: "done" },
  { no: 1606, title: "An Toàn Lao Động Xây", keyword: "an toàn lao động xây", slug: "an-toan-lao-dong-xay-ngan", status: "done" },
  { no: 1607, title: "Bảo Hộ Lao Động Xây", keyword: "bảo hộ lao động xây", slug: "bao-ho-lao-dong-xay-ngan", status: "done" },
  { no: 1608, title: "Dọn Dẹp Công Trình", keyword: "dọn dẹp công trình", slug: "don-dep-cong-trinh-ngan", status: "done" },
  { no: 1609, title: "Vệ Sinh Sau Xây", keyword: "vệ sinh sau xây", slug: "ve-sinh-sau-xay-ngan", status: "done" },
  { no: 1610, title: "Bàn Giao Chìa Khóa", keyword: "bàn giao chìa khóa", slug: "ban-giao-chia-khoa-ngan", status: "done" },
  { no: 1611, title: "Hướng Dẫn Sử Dụng Nhà", keyword: "hướng dẫn sử dụng nhà", slug: "huong-dan-su-dung-nha-ngan", status: "done" },
  { no: 1612, title: "Bảo Trì Định Kỳ Nhà", keyword: "bảo trì định kỳ nhà", slug: "bao-tri-dinh-ky-nha-ngan", status: "done" },
  { no: 1613, title: "Sửa Chữa Bảo Hành", keyword: "sửa chữa bảo hành", slug: "sua-chua-bao-hanh-ngan", status: "done" },
  { no: 1614, title: "Kiểm Định Nhà", keyword: "kiểm định nhà", slug: "kiem-dinh-nha-ngan", status: "done" },
  { no: 1615, title: "Đánh Giá Kết Cấu Nhà", keyword: "đánh giá kết cấu nhà", slug: "danh-gia-ket-cau-nha-ngan", status: "done" },
  { no: 1616, title: "Đo Đạc Hiện Trạng", keyword: "đo đạc hiện trạng", slug: "do-dac-hien-trang-ngan", status: "done" },
  { no: 1617, title: "Scan 3D Nhà", keyword: "scan 3d nhà", slug: "scan-3d-nha-ngan", status: "done" },
  { no: 1618, title: "BIM Thiết Kế Nhà", keyword: "bim thiết kế nhà", slug: "bim-thiet-ke-nha-ngan", status: "done" },
  { no: 1619, title: "Bản Vẽ Shopdrawing", keyword: "bản vẽ shopdrawing", slug: "ban-ve-shopdrawing-ngan", status: "done" },
  { no: 1620, title: "Bản Vẽ Kết Cấu", keyword: "bản vẽ kết cấu", slug: "ban-ve-ket-cau-ngan", status: "done" },
  { no: 1621, title: "Bản Vẽ Điện Nước", keyword: "bản vẽ điện nước", slug: "ban-ve-dien-nuoc-ngan", status: "done" },
  { no: 1622, title: "Bản Vẽ Kiến Trúc", keyword: "bản vẽ kiến trúc", slug: "ban-ve-kien-truc-ngan", status: "done" },
  { no: 1623, title: "Phối Cảnh 3D Nhà", keyword: "phối cảnh 3d nhà", slug: "phoi-canh-3d-nha-ngan", status: "done" },
  { no: 1624, title: "Tour Ảo Nhà", keyword: "tour ảo nhà", slug: "tour-ao-nha-ngan", status: "done" },
  { no: 1625, title: "Mô Hình Nhà", keyword: "mô hình nhà", slug: "mo-hinh-nha-ngan", status: "done" },
  { no: 1626, title: "Triển Khai Bản Vẽ", keyword: "triển khai bản vẽ", slug: "trien-khai-ban-ve-ngan", status: "done" },
  { no: 1627, title: "Điều Chỉnh Bản Vẽ", keyword: "điều chỉnh bản vẽ", slug: "dieu-chinh-ban-ve-ngan", status: "done" },
  { no: 1628, title: "Xin Phép Sửa Bản Vẽ", keyword: "xin phép sửa bản vẽ", slug: "xin-phep-sua-ban-ve-ngan", status: "done" },
  { no: 1629, title: "Hoàn Công Bản Vẽ", keyword: "hoàn công bản vẽ", slug: "hoan-cong-ban-ve-ngan", status: "done" },
  { no: 1630, title: "Cập Nhật Sổ Hồng", keyword: "cập nhật sổ hồng", slug: "cap-nhat-so-hong-ngan", status: "done" },
  { no: 1631, title: "Tách Thửa Xây Nhà", keyword: "tách thửa xây nhà", slug: "tach-thua-xay-nha-ngan", status: "done" },
  { no: 1632, title: "Hợp Thửa Xây Nhà", keyword: "hợp thửa xây nhà", slug: "hop-thua-xay-nha-ngan", status: "done" },
  { no: 1633, title: "Chuyển Đổi Đất Ở", keyword: "chuyển đổi đất ở", slug: "chuyen-doi-dat-o-ngan", status: "done" },
  { no: 1634, title: "Quy Hoạch 1/500", keyword: "quy hoạch 1/500", slug: "quy-hoach-1-500-ngan", status: "done" },
  { no: 1635, title: "Chỉ Giới Đường Đỏ", keyword: "chỉ giới đường đỏ", slug: "chi-gioi-duong-do-ngan", status: "done" },
  { no: 1636, title: "Khoảng Lùi Xây Dựng", keyword: "khoảng lùi xây dựng", slug: "khoang-lui-xay-dung-ngan", status: "done" },
  { no: 1637, title: "Mật Độ Xây Dựng", keyword: "mật độ xây dựng", slug: "mat-do-xay-dung-ngan", status: "done" },
  { no: 1638, title: "Hệ Số Sử Dụng Đất", keyword: "hệ số sử dụng đất", slug: "he-so-su-dung-dat-ngan", status: "done" },
  { no: 1639, title: "Chiều Cao Xây Dựng", keyword: "chiều cao xây dựng", slug: "chieu-cao-xay-dung-ngan", status: "done" },
  { no: 1640, title: "Khoan Cọc Nhồi Barrette", keyword: "khoan cọc nhồi barrette", slug: "khoan-coc-nhoi-barrette-ct-ngan", status: "done" },
  { no: 1641, title: "Phun Vữa Gia Cố", keyword: "phun vữa gia cố", slug: "phun-vua-gia-co-ngan", status: "done" },
  { no: 1642, title: "Neo Đất Đinh", keyword: "neo đất đinh", slug: "neo-dat-dinh-ngan", status: "done" },
  { no: 1643, title: "Tường Vây Nhà", keyword: "tường vây nhà", slug: "tuong-vay-nha-ngan", status: "done" },
  { no: 1644, title: "Chống Sạt Lở Móng", keyword: "chống sạt lở móng", slug: "chong-sat-lo-mong-ngan", status: "done" },
  { no: 1645, title: "Hạ Thủy Điện Nhà", keyword: "hạ thủy điện nhà", slug: "ha-thuy-dien-nha-ngan", status: "done" },
  { no: 1646, title: "Đấu Nối Điện Nhà", keyword: "đấu nối điện nhà", slug: "dau-noi-dien-nha-ngan", status: "done" },
];
