/**
 * Lịch 100 từ khóa ngắn — batch 47 (#4147–#4246).
 * Cluster: geo Đông Nam Bộ, KĐT, trục đường.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch47: ContentCalendarItem[] = [
  { no: 4147, title: "Xây Nhà An Phú Thuận An", keyword: "xây nhà An Phú Thuận An", slug: "xay-nha-an-phu-thuan-an-geo2-ngan", status: "done" },
  { no: 4148, title: "Xây Nhà Bình Chuẩn", keyword: "xây nhà Bình Chuẩn", slug: "xay-nha-binh-chuan-geo2-ngan", status: "done" },
  { no: 4149, title: "Xây Nhà Bình Hòa BD", keyword: "xây nhà Bình Hòa Bình Dương", slug: "xay-nha-binh-hoa-bd-geo2-ngan", status: "done" },
  { no: 4150, title: "Xây Nhà Vĩnh Phú BD", keyword: "xây nhà Vĩnh Phú Bình Dương", slug: "xay-nha-vinh-phu-bd-geo2-ngan", status: "done" },
  { no: 4151, title: "Xây Nhà Lái Thiêu", keyword: "xây nhà Lái Thiêu", slug: "xay-nha-lai-thieu-geo2-ngan", status: "done" },
  { no: 4152, title: "Xây Nhà Bình Nhâm", keyword: "xây nhà Bình Nhâm", slug: "xay-nha-binh-nham-geo2-ngan", status: "done" },
  { no: 4153, title: "Xây Nhà Hưng Định", keyword: "xây nhà Hưng Định", slug: "xay-nha-hung-dinh-geo2-ngan", status: "done" },
  { no: 4154, title: "Xây Nhà An Thạnh BD", keyword: "xây nhà An Thạnh Bình Dương", slug: "xay-nha-an-thanh-bd-geo2-ngan", status: "done" },
  { no: 4155, title: "Xây Nhà Thuận Giao", keyword: "xây nhà Thuận Giao", slug: "xay-nha-thuan-giao-geo2-ngan", status: "done" },
  { no: 4156, title: "Xây Nhà Đông Hòa BD", keyword: "xây nhà Đông Hòa Bình Dương", slug: "xay-nha-dong-hoa-bd-geo2-ngan", status: "done" },
  { no: 4157, title: "Xây Nhà Tân Đông Hiệp", keyword: "xây nhà Tân Đông Hiệp", slug: "xay-nha-tan-dong-hiep-geo2-ngan", status: "done" },
  { no: 4158, title: "Xây Nhà Tân Bình Dĩ An", keyword: "xây nhà Tân Bình Dĩ An", slug: "xay-nha-tan-binh-di-an-geo2-ngan", status: "done" },
  { no: 4159, title: "Xây Nhà Dĩ An Phường", keyword: "xây nhà phường Dĩ An", slug: "xay-nha-phuong-di-an-geo2-ngan", status: "done" },
  { no: 4160, title: "Xây Nhà An Bình Dĩ An", keyword: "xây nhà An Bình Dĩ An", slug: "xay-nha-an-binh-di-an-geo2-ngan", status: "done" },
  { no: 4161, title: "Xây Nhà Đông Hòa Dĩ An", keyword: "xây nhà Đông Hòa Dĩ An", slug: "xay-nha-dong-hoa-di-an-geo2-ngan", status: "done" },
  { no: 4162, title: "Xây Nhà Bình An Dĩ An", keyword: "xây nhà Bình An Dĩ An", slug: "xay-nha-binh-an-di-an-geo2-ngan", status: "done" },
  { no: 4163, title: "Xây Nhà Phú Hòa TDM", keyword: "xây nhà Phú Hòa Thủ Dầu Một", slug: "xay-nha-phu-hoa-tdm-geo2-ngan", status: "done" },
  { no: 4164, title: "Xây Nhà Hiệp Thành TDM", keyword: "xây nhà Hiệp Thành Thủ Dầu Một", slug: "xay-nha-hiep-thanh-tdm-geo2-ngan", status: "done" },
  { no: 4165, title: "Xây Nhà Chánh Nghĩa", keyword: "xây nhà Chánh Nghĩa", slug: "xay-nha-chanh-nghia-geo2-ngan", status: "done" },
  { no: 4166, title: "Xây Nhà Phú Lợi TDM", keyword: "xây nhà Phú Lợi Thủ Dầu Một", slug: "xay-nha-phu-loi-tdm-geo2-ngan", status: "done" },
  { no: 4167, title: "Xây Nhà Phú Cường TDM", keyword: "xây nhà Phú Cường Thủ Dầu Một", slug: "xay-nha-phu-cuong-tdm-geo2-ngan", status: "done" },
  { no: 4168, title: "Xây Nhà Định Hòa TDM", keyword: "xây nhà Định Hòa Thủ Dầu Một", slug: "xay-nha-dinh-hoa-tdm-geo2-ngan", status: "done" },
  { no: 4169, title: "Xây Nhà Tân Hiệp Biên Hòa", keyword: "xây nhà Tân Hiệp Biên Hòa", slug: "xay-nha-tan-hiep-bien-hoa-geo2-ngan", status: "done" },
  { no: 4170, title: "Xây Nhà Tân Mai Biên Hòa", keyword: "xây nhà Tân Mai Biên Hòa", slug: "xay-nha-tan-mai-bien-hoa-geo2-ngan", status: "done" },
  { no: 4171, title: "Xây Nhà Tam Hiệp Biên Hòa", keyword: "xây nhà Tam Hiệp Biên Hòa", slug: "xay-nha-tam-hiep-bien-hoa-geo2-ngan", status: "done" },
  { no: 4172, title: "Xây Nhà Quyết Thắng BH", keyword: "xây nhà Quyết Thắng Biên Hòa", slug: "xay-nha-quyet-thang-bh-geo2-ngan", status: "done" },
  { no: 4173, title: "Xây Nhà Trung Dũng BH", keyword: "xây nhà Trung Dũng Biên Hòa", slug: "xay-nha-trung-dung-bh-geo2-ngan", status: "done" },
  { no: 4174, title: "Xây Nhà Quang Vinh BH", keyword: "xây nhà Quang Vinh Biên Hòa", slug: "xay-nha-quang-vinh-bh-geo2-ngan", status: "done" },
  { no: 4175, title: "Xây Nhà Bửu Long", keyword: "xây nhà Bửu Long", slug: "xay-nha-buu-long-geo2-ngan", status: "done" },
  { no: 4176, title: "Xây Nhà Bửu Hòa", keyword: "xây nhà Bửu Hòa", slug: "xay-nha-buu-hoa-geo2-ngan", status: "done" },
  { no: 4177, title: "Xây Nhà Long Bình Tân", keyword: "xây nhà Long Bình Tân", slug: "xay-nha-long-binh-tan-geo2-ngan", status: "done" },
  { no: 4178, title: "Xây Nhà An Hòa Biên Hòa", keyword: "xây nhà An Hòa Biên Hòa", slug: "xay-nha-an-hoa-bien-hoa-geo2-ngan", status: "done" },
  { no: 4179, title: "Xây Nhà Phước Tân", keyword: "xây nhà Phước Tân", slug: "xay-nha-phuoc-tan-geo2-ngan", status: "done" },
  { no: 4180, title: "Xây Nhà Tam Phước", keyword: "xây nhà Tam Phước", slug: "xay-nha-tam-phuoc-geo2-ngan", status: "done" },
  { no: 4181, title: "Xây Nhà Long Phước DN", keyword: "xây nhà Long Phước Đồng Nai", slug: "xay-nha-long-phuoc-dn-geo2-ngan", status: "done" },
  { no: 4182, title: "Xây Nhà An Phước Long Thành", keyword: "xây nhà An Phước Long Thành", slug: "xay-nha-an-phuoc-long-thanh-geo2-ngan", status: "done" },
  { no: 4183, title: "Xây Nhà Bình Sơn Long Thành", keyword: "xây nhà Bình Sơn Long Thành", slug: "xay-nha-binh-son-long-thanh-geo2-ngan", status: "done" },
  { no: 4184, title: "Xây Nhà Lộc An Long Thành", keyword: "xây nhà Lộc An Long Thành", slug: "xay-nha-loc-an-long-thanh-geo2-ngan", status: "done" },
  { no: 4185, title: "Xây Nhà Long An Long Thành", keyword: "xây nhà Long An Long Thành", slug: "xay-nha-long-an-long-thanh-geo2-ngan", status: "done" },
  { no: 4186, title: "Xây Nhà Phước Thái", keyword: "xây nhà Phước Thái", slug: "xay-nha-phuoc-thai-geo2-ngan", status: "done" },
  { no: 4187, title: "Xây Nhà Phước Bình NT", keyword: "xây nhà Phước Bình Nhơn Trạch", slug: "xay-nha-phuoc-binh-nt-geo2-ngan", status: "done" },
  { no: 4188, title: "Xây Nhà Long Thọ", keyword: "xây nhà Long Thọ", slug: "xay-nha-long-tho-geo2-ngan", status: "done" },
  { no: 4189, title: "Xây Nhà Phú Hội NT", keyword: "xây nhà Phú Hội Nhơn Trạch", slug: "xay-nha-phu-hoi-nt-geo2-ngan", status: "done" },
  { no: 4190, title: "Xây Nhà Phước An NT", keyword: "xây nhà Phước An Nhơn Trạch", slug: "xay-nha-phuoc-an-nt-geo2-ngan", status: "done" },
  { no: 4191, title: "Xây Nhà Vĩnh Thanh NT", keyword: "xây nhà Vĩnh Thanh Nhơn Trạch", slug: "xay-nha-vinh-thanh-nt-geo2-ngan", status: "done" },
  { no: 4192, title: "Xây Nhà Đại Phước", keyword: "xây nhà Đại Phước", slug: "xay-nha-dai-phuoc-geo2-ngan", status: "done" },
  { no: 4193, title: "Xây Nhà Phú Đông NT", keyword: "xây nhà Phú Đông Nhơn Trạch", slug: "xay-nha-phu-dong-nt-geo2-ngan", status: "done" },
  { no: 4194, title: "Xây Nhà Hựu Thạnh", keyword: "xây nhà Hựu Thạnh", slug: "xay-nha-huu-thanh-geo2-ngan", status: "done" },
  { no: 4195, title: "Xây Nhà Đức Lập Thượng", keyword: "xây nhà Đức Lập Thượng", slug: "xay-nha-duc-lap-thuong-geo2-ngan", status: "done" },
  { no: 4196, title: "Xây Nhà Đức Lập Hạ", keyword: "xây nhà Đức Lập Hạ", slug: "xay-nha-duc-lap-ha-geo2-ngan", status: "done" },
  { no: 4197, title: "Xây Nhà Mỹ Hạnh Bắc", keyword: "xây nhà Mỹ Hạnh Bắc", slug: "xay-nha-my-hanh-bac-geo2-ngan", status: "done" },
  { no: 4198, title: "Xây Nhà Mỹ Hạnh Nam", keyword: "xây nhà Mỹ Hạnh Nam", slug: "xay-nha-my-hanh-nam-geo2-ngan", status: "done" },
  { no: 4199, title: "Xây Nhà Lương Hòa", keyword: "xây nhà Lương Hòa", slug: "xay-nha-luong-hoa-geo2-ngan", status: "done" },
  { no: 4200, title: "Xây Nhà Tân Bửu", keyword: "xây nhà Tân Bửu", slug: "xay-nha-tan-buu-geo2-ngan", status: "done" },
  { no: 4201, title: "Xây Nhà Thạnh Lợi BL", keyword: "xây nhà Thạnh Lợi Bến Lức", slug: "xay-nha-thanh-loi-bl-geo2-ngan", status: "done" },
  { no: 4202, title: "Xây Nhà Lương Bình", keyword: "xây nhà Lương Bình", slug: "xay-nha-luong-binh-geo2-ngan", status: "done" },
  { no: 4203, title: "Xây Nhà An Thạnh BL", keyword: "xây nhà An Thạnh Bến Lức", slug: "xay-nha-an-thanh-bl-geo2-ngan", status: "done" },
  { no: 4204, title: "Xây Nhà Phước Lý", keyword: "xây nhà Phước Lý", slug: "xay-nha-phuoc-ly-geo2-ngan", status: "done" },
  { no: 4205, title: "Xây Nhà Long Thượng", keyword: "xây nhà Long Thượng", slug: "xay-nha-long-thuong-geo2-ngan", status: "done" },
  { no: 4206, title: "Xây Nhà Long Hậu", keyword: "xây nhà Long Hậu", slug: "xay-nha-long-hau-geo2-ngan", status: "done" },
  { no: 4207, title: "Xây Nhà Phước Lâm", keyword: "xây nhà Phước Lâm", slug: "xay-nha-phuoc-lam-geo2-ngan", status: "done" },
  { no: 4208, title: "Xây Nhà Mỹ Lộc CG", keyword: "xây nhà Mỹ Lộc Cần Giuộc", slug: "xay-nha-my-loc-cg-geo2-ngan", status: "done" },
  { no: 4209, title: "Xây Nhà KĐT Vsip 1", keyword: "xây nhà gần VSIP 1", slug: "xay-nha-gan-vsip-1-geo2-ngan", status: "done" },
  { no: 4210, title: "Xây Nhà KĐT Vsip 2", keyword: "xây nhà gần VSIP 2", slug: "xay-nha-gan-vsip-2-geo2-ngan", status: "done" },
  { no: 4211, title: "Xây Nhà KĐT Becamex", keyword: "xây nhà gần Becamex", slug: "xay-nha-gan-becamex-geo2-ngan", status: "done" },
  { no: 4212, title: "Xây Nhà KĐT Aqua City", keyword: "xây nhà gần Aqua City", slug: "xay-nha-gan-aqua-city-geo2-ngan", status: "done" },
  { no: 4213, title: "Xây Nhà KĐT Novaworld", keyword: "xây nhà gần NovaWorld", slug: "xay-nha-gan-novaworld-geo2-ngan", status: "done" },
  { no: 4214, title: "Xây Nhà KĐT Mizuki", keyword: "xây nhà gần Mizuki", slug: "xay-nha-gan-mizuki-geo2-ngan", status: "done" },
  { no: 4215, title: "Xây Nhà KĐT Waterpoint", keyword: "xây nhà gần Waterpoint", slug: "xay-nha-gan-waterpoint-geo2-ngan", status: "done" },
  { no: 4216, title: "Xây Nhà Trục QL1A", keyword: "xây nhà gần QL1A", slug: "xay-nha-gan-ql1a-geo2-ngan", status: "done" },
  { no: 4217, title: "Xây Nhà Trục QL13", keyword: "xây nhà gần QL13", slug: "xay-nha-gan-ql13-geo2-ngan", status: "done" },
  { no: 4218, title: "Xây Nhà Trục QL51", keyword: "xây nhà gần QL51", slug: "xay-nha-gan-ql51-geo2-ngan", status: "done" },
  { no: 4219, title: "Xây Nhà Trục QL22", keyword: "xây nhà gần QL22", slug: "xay-nha-gan-ql22-geo2-ngan", status: "done" },
  { no: 4220, title: "Xây Nhà Trục QL50", keyword: "xây nhà gần QL50", slug: "xay-nha-gan-ql50-geo2-ngan", status: "done" },
  { no: 4221, title: "Xây Nhà Cao Tốc HCM Long Thành", keyword: "xây nhà gần cao tốc Long Thành", slug: "xay-nha-gan-cao-toc-long-thanh-geo2-ngan", status: "done" },
  { no: 4222, title: "Xây Nhà Cao Tốc Trung Lương Mỹ Thuận", keyword: "xây nhà gần cao tốc Mỹ Thuận", slug: "xay-nha-gan-cao-toc-my-thuan-geo2-ngan", status: "done" },
  { no: 4223, title: "Xây Nhà Metro Số 1", keyword: "xây nhà gần metro số 1", slug: "xay-nha-gan-metro-1-geo2-ngan", status: "done" },
  { no: 4224, title: "Xây Nhà Metro Số 2", keyword: "xây nhà gần metro số 2", slug: "xay-nha-gan-metro-2-geo2-ngan", status: "done" },
  { no: 4225, title: "Cải Tạo Nhà Thuận An", keyword: "cải tạo nhà Thuận An", slug: "cai-tao-nha-thuan-an-geo2-ngan", status: "done" },
  { no: 4226, title: "Cải Tạo Nhà Dĩ An BD", keyword: "cải tạo nhà Dĩ An", slug: "cai-tao-nha-di-an-bd-geo2-ngan", status: "done" },
  { no: 4227, title: "Cải Tạo Nhà Long Thành DN", keyword: "cải tạo nhà Long Thành", slug: "cai-tao-nha-long-thanh-dn-geo2-ngan", status: "done" },
  { no: 4228, title: "Cải Tạo Nhà Nhơn Trạch DN", keyword: "cải tạo nhà Nhơn Trạch", slug: "cai-tao-nha-nhon-trach-dn-geo2-ngan", status: "done" },
  { no: 4229, title: "Thiết Kế Nhà Thuận An", keyword: "thiết kế nhà Thuận An", slug: "thiet-ke-nha-thuan-an-geo2-ngan", status: "done" },
  { no: 4230, title: "Thiết Kế Nhà Dĩ An BD", keyword: "thiết kế nhà Dĩ An BD", slug: "thiet-ke-nha-di-an-bd-geo2-ngan", status: "done" },
  { no: 4231, title: "Thiết Kế Nhà Biên Hòa Phường", keyword: "thiết kế nhà Biên Hòa", slug: "thiet-ke-nha-bien-hoa-phuong-geo2-ngan", status: "done" },
  { no: 4232, title: "Báo Giá Xây Nhà Thuận An", keyword: "báo giá xây nhà Thuận An", slug: "bao-gia-xay-nha-thuan-an-geo2-ngan", status: "done" },
  { no: 4233, title: "Báo Giá Xây Nhà Dĩ An BD", keyword: "báo giá xây nhà Dĩ An", slug: "bao-gia-xay-nha-di-an-bd-geo2-ngan", status: "done" },
  { no: 4234, title: "Báo Giá Xây Nhà Long Thành DN", keyword: "báo giá xây nhà Long Thành DN", slug: "bao-gia-xay-nha-long-thanh-dn-geo2-ngan", status: "done" },
  { no: 4235, title: "Nhà Thầu Thuận An", keyword: "nhà thầu Thuận An", slug: "nha-thau-thuan-an-geo2-ngan", status: "done" },
  { no: 4236, title: "Nhà Thầu Dĩ An", keyword: "nhà thầu Dĩ An", slug: "nha-thau-di-an-geo2-ngan", status: "done" },
  { no: 4237, title: "Nhà Thầu Long Thành", keyword: "nhà thầu Long Thành", slug: "nha-thau-long-thanh-geo2-ngan", status: "done" },
  { no: 4238, title: "Nhà Thầu Nhơn Trạch", keyword: "nhà thầu Nhơn Trạch", slug: "nha-thau-nhon-trach-geo2-ngan", status: "done" },
  { no: 4239, title: "Xây Nhà Ven Sông Đồng Nai", keyword: "xây nhà ven sông Đồng Nai", slug: "xay-nha-ven-song-dong-nai-geo2-ngan", status: "done" },
  { no: 4240, title: "Xây Nhà Ven Sông Sài Gòn BD", keyword: "xây nhà ven sông Sài Gòn BD", slug: "xay-nha-ven-song-sai-gon-bd-geo2-ngan", status: "done" },
  { no: 4241, title: "Xây Biệt Thự Thuận An", keyword: "xây biệt thự Thuận An", slug: "xay-biet-thu-thuan-an-geo2-ngan", status: "done" },
  { no: 4242, title: "Xây Biệt Thự Long Thành", keyword: "xây biệt thự Long Thành", slug: "xay-biet-thu-long-thanh-geo2-ngan", status: "done" },
  { no: 4243, title: "Xây Nhà Vườn Nhơn Trạch", keyword: "xây nhà vườn Nhơn Trạch", slug: "xay-nha-vuon-nhon-trach-geo2-ngan", status: "done" },
  { no: 4244, title: "Xây Nhà Vườn Đức Hòa", keyword: "xây nhà vườn Đức Hòa LA", slug: "xay-nha-vuon-duc-hoa-la-geo2-ngan", status: "done" },
  { no: 4245, title: "Chủ Đề Mở Rộng 47 1", keyword: "chủ đề mở rộng 47 1", slug: "chu-de-mo-rong-47-1-ngan", status: "done" },
  { no: 4246, title: "Chủ Đề Mở Rộng 47 2", keyword: "chủ đề mở rộng 47 2", slug: "chu-de-mo-rong-47-2-ngan", status: "done" },
];
