/**
 * Lịch 100 từ khóa ngắn — batch 32 (#2647–#2746).
 * Cluster: geo tỉnh thành vùng phụ cận & miền Nam.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch32: ContentCalendarItem[] = [
  { no: 2647, title: "Xây Nhà Thủ Dầu Một", keyword: "xây nhà Thủ Dầu Một", slug: "xay-nha-thu-dau-mot-bd-ngan", status: "done" },
  { no: 2648, title: "Xây Nhà Dĩ An", keyword: "xây nhà Dĩ An", slug: "xay-nha-di-an-bd-ngan", status: "done" },
  { no: 2649, title: "Xây Nhà Thuận An", keyword: "xây nhà Thuận An", slug: "xay-nha-thuan-an-bd-ngan", status: "done" },
  { no: 2650, title: "Xây Nhà Tân Uyên", keyword: "xây nhà Tân Uyên", slug: "xay-nha-tan-uyen-bd-ngan", status: "done" },
  { no: 2651, title: "Xây Nhà Bến Cát", keyword: "xây nhà Bến Cát", slug: "xay-nha-ben-cat-bd-ngan", status: "done" },
  { no: 2652, title: "Xây Nhà Bàu Bàng", keyword: "xây nhà Bàu Bàng", slug: "xay-nha-bau-bang-ngan", status: "done" },
  { no: 2653, title: "Xây Nhà Phú Giáo", keyword: "xây nhà Phú Giáo", slug: "xay-nha-phu-giao-ngan", status: "done" },
  { no: 2654, title: "Xây Nhà Dầu Tiếng", keyword: "xây nhà Dầu Tiếng", slug: "xay-nha-dau-tieng-ngan", status: "done" },
  { no: 2655, title: "Xây Nhà Biên Hòa", keyword: "xây nhà Biên Hòa", slug: "xay-nha-bien-hoa-tinh-ngan", status: "done" },
  { no: 2656, title: "Xây Nhà Long Thành", keyword: "xây nhà Long Thành", slug: "xay-nha-long-thanh-dn-ngan", status: "done" },
  { no: 2657, title: "Xây Nhà Nhơn Trạch", keyword: "xây nhà Nhơn Trạch", slug: "xay-nha-nhon-trach-dn-ngan", status: "done" },
  { no: 2658, title: "Xây Nhà Trảng Bom", keyword: "xây nhà Trảng Bom", slug: "xay-nha-trang-bom-dn-ngan", status: "done" },
  { no: 2659, title: "Xây Nhà Vĩnh Cửu", keyword: "xây nhà Vĩnh Cửu", slug: "xay-nha-vinh-cuu-ngan", status: "done" },
  { no: 2660, title: "Xây Nhà Thống Nhất", keyword: "xây nhà Thống Nhất", slug: "xay-nha-thong-nhat-ngan", status: "done" },
  { no: 2661, title: "Xây Nhà Định Quán", keyword: "xây nhà Định Quán", slug: "xay-nha-dinh-quan-ngan", status: "done" },
  { no: 2662, title: "Xây Nhà Xuân Lộc", keyword: "xây nhà Xuân Lộc", slug: "xay-nha-xuan-loc-ngan", status: "done" },
  { no: 2663, title: "Xây Nhà Cẩm Mỹ", keyword: "xây nhà Cẩm Mỹ", slug: "xay-nha-cam-my-ngan", status: "done" },
  { no: 2664, title: "Xây Nhà Tân Phú Đồng Nai", keyword: "xây nhà Tân Phú Đồng Nai", slug: "xay-nha-tan-phu-dong-nai-ngan", status: "done" },
  { no: 2665, title: "Xây Nhà Tân An", keyword: "xây nhà Tân An", slug: "xay-nha-tan-an-ngan", status: "done" },
  { no: 2666, title: "Xây Nhà Bến Lức", keyword: "xây nhà Bến Lức", slug: "xay-nha-ben-luc-la-ngan", status: "done" },
  { no: 2667, title: "Xây Nhà Cần Giuộc", keyword: "xây nhà Cần Giuộc", slug: "xay-nha-can-giuoc-ngan", status: "done" },
  { no: 2668, title: "Xây Nhà Cần Đước", keyword: "xây nhà Cần Đước", slug: "xay-nha-can-duoc-ngan", status: "done" },
  { no: 2669, title: "Xây Nhà Đức Hòa", keyword: "xây nhà Đức Hòa", slug: "xay-nha-duc-hoa-la-ngan", status: "done" },
  { no: 2670, title: "Xây Nhà Đức Huệ", keyword: "xây nhà Đức Huệ", slug: "xay-nha-duc-hue-ngan", status: "done" },
  { no: 2671, title: "Xây Nhà Thủ Thừa", keyword: "xây nhà Thủ Thừa", slug: "xay-nha-thu-thua-ngan", status: "done" },
  { no: 2672, title: "Xây Nhà Châu Thành Long An", keyword: "xây nhà Châu Thành Long An", slug: "xay-nha-chau-thanh-long-an-ngan", status: "done" },
  { no: 2673, title: "Xây Nhà Tân Trụ", keyword: "xây nhà Tân Trụ", slug: "xay-nha-tan-tru-ngan", status: "done" },
  { no: 2674, title: "Xây Nhà Tây Ninh Thành Phố", keyword: "xây nhà Tây Ninh", slug: "xay-nha-tay-ninh-tp-ngan", status: "done" },
  { no: 2675, title: "Xây Nhà Trảng Bàng", keyword: "xây nhà Trảng Bàng", slug: "xay-nha-trang-bang-ngan", status: "done" },
  { no: 2676, title: "Xây Nhà Gò Dầu", keyword: "xây nhà Gò Dầu", slug: "xay-nha-go-dau-ngan", status: "done" },
  { no: 2677, title: "Xây Nhà Hòa Thành", keyword: "xây nhà Hòa Thành", slug: "xay-nha-hoa-thanh-tn-ngan", status: "done" },
  { no: 2678, title: "Xây Nhà Dương Minh Châu", keyword: "xây nhà Dương Minh Châu", slug: "xay-nha-duong-minh-chau-ngan", status: "done" },
  { no: 2679, title: "Xây Nhà Châu Thành Tây Ninh", keyword: "xây nhà Châu Thành Tây Ninh", slug: "xay-nha-chau-thanh-tay-ninh-ngan", status: "done" },
  { no: 2680, title: "Xây Nhà Vũng Tàu", keyword: "xây nhà Vũng Tàu", slug: "xay-nha-vung-tau-brvt-ngan", status: "done" },
  { no: 2681, title: "Xây Nhà Bà Rịa", keyword: "xây nhà Bà Rịa", slug: "xay-nha-ba-ria-brvt-ngan", status: "done" },
  { no: 2682, title: "Xây Nhà Phú Mỹ BRVT", keyword: "xây nhà Phú Mỹ", slug: "xay-nha-phu-my-brvt-ngan", status: "done" },
  { no: 2683, title: "Xây Nhà Long Điền", keyword: "xây nhà Long Điền", slug: "xay-nha-long-dien-ngan", status: "done" },
  { no: 2684, title: "Xây Nhà Đất Đỏ", keyword: "xây nhà Đất Đỏ", slug: "xay-nha-dat-do-ngan", status: "done" },
  { no: 2685, title: "Xây Nhà Xuyên Mộc", keyword: "xây nhà Xuyên Mộc", slug: "xay-nha-xuyen-moc-ngan", status: "done" },
  { no: 2686, title: "Xây Nhà Châu Đức", keyword: "xây nhà Châu Đức", slug: "xay-nha-chau-duc-ngan", status: "done" },
  { no: 2687, title: "Xây Nhà Côn Đảo", keyword: "xây nhà Côn Đảo", slug: "xay-nha-con-dao-ngan", status: "done" },
  { no: 2688, title: "Xây Nhà Mỹ Tho", keyword: "xây nhà Mỹ Tho", slug: "xay-nha-my-tho-tinh-ngan", status: "done" },
  { no: 2689, title: "Xây Nhà Gò Công", keyword: "xây nhà Gò Công", slug: "xay-nha-go-cong-ngan", status: "done" },
  { no: 2690, title: "Xây Nhà Cai Lậy", keyword: "xây nhà Cai Lậy", slug: "xay-nha-cai-lay-ngan", status: "done" },
  { no: 2691, title: "Xây Nhà Bến Tre", keyword: "xây nhà Bến Tre", slug: "xay-nha-ben-tre-tinh-ngan", status: "done" },
  { no: 2692, title: "Xây Nhà Trà Vinh", keyword: "xây nhà Trà Vinh", slug: "xay-nha-tra-vinh-tinh-ngan", status: "done" },
  { no: 2693, title: "Xây Nhà Vĩnh Long", keyword: "xây nhà Vĩnh Long", slug: "xay-nha-vinh-long-tinh-ngan", status: "done" },
  { no: 2694, title: "Xây Nhà Sa Đéc", keyword: "xây nhà Sa Đéc", slug: "xay-nha-sa-dec-ngan", status: "done" },
  { no: 2695, title: "Xây Nhà Cao Lãnh", keyword: "xây nhà Cao Lãnh", slug: "xay-nha-cao-lanh-ngan", status: "done" },
  { no: 2696, title: "Xây Nhà Long Xuyên", keyword: "xây nhà Long Xuyên", slug: "xay-nha-long-xuyen-ngan", status: "done" },
  { no: 2697, title: "Xây Nhà Châu Đốc", keyword: "xây nhà Châu Đốc", slug: "xay-nha-chau-doc-tinh-ngan", status: "done" },
  { no: 2698, title: "Xây Nhà Rạch Giá", keyword: "xây nhà Rạch Giá", slug: "xay-nha-rach-gia-tinh-ngan", status: "done" },
  { no: 2699, title: "Xây Nhà Hà Tiên", keyword: "xây nhà Hà Tiên", slug: "xay-nha-ha-tien-ngan", status: "done" },
  { no: 2700, title: "Xây Nhà Cà Mau", keyword: "xây nhà Cà Mau", slug: "xay-nha-ca-mau-tinh-ngan", status: "done" },
  { no: 2701, title: "Xây Nhà Bạc Liêu", keyword: "xây nhà Bạc Liêu", slug: "xay-nha-bac-lieu-tinh-ngan", status: "done" },
  { no: 2702, title: "Xây Nhà Sóc Trăng", keyword: "xây nhà Sóc Trăng", slug: "xay-nha-soc-trang-tinh-ngan", status: "done" },
  { no: 2703, title: "Xây Nhà Cần Thơ Ninh Kiều", keyword: "xây nhà Ninh Kiều", slug: "xay-nha-ninh-kieu-ngan", status: "done" },
  { no: 2704, title: "Xây Nhà Cần Thơ Cái Răng", keyword: "xây nhà Cái Răng", slug: "xay-nha-cai-rang-ngan", status: "done" },
  { no: 2705, title: "Xây Nhà Cần Thơ Bình Thủy", keyword: "xây nhà Bình Thủy", slug: "xay-nha-binh-thuy-ngan", status: "done" },
  { no: 2706, title: "Xây Nhà Cần Thơ Ô Môn", keyword: "xây nhà Ô Môn", slug: "xay-nha-o-mon-ngan", status: "done" },
  { no: 2707, title: "Xây Nhà Cần Thơ Thốt Nốt", keyword: "xây nhà Thốt Nốt", slug: "xay-nha-thot-not-ngan", status: "done" },
  { no: 2708, title: "Cải Tạo Nhà Thủ Dầu Một", keyword: "cải tạo nhà Thủ Dầu Một", slug: "cai-tao-nha-thu-dau-mot-ngan", status: "done" },
  { no: 2709, title: "Cải Tạo Nhà Biên Hòa", keyword: "cải tạo nhà Biên Hòa", slug: "cai-tao-nha-bien-hoa-ngan", status: "done" },
  { no: 2710, title: "Cải Tạo Nhà Tân An", keyword: "cải tạo nhà Tân An", slug: "cai-tao-nha-tan-an-ngan", status: "done" },
  { no: 2711, title: "Cải Tạo Nhà Vũng Tàu", keyword: "cải tạo nhà Vũng Tàu", slug: "cai-tao-nha-vung-tau-brvt-ngan", status: "done" },
  { no: 2712, title: "Cải Tạo Nhà Mỹ Tho", keyword: "cải tạo nhà Mỹ Tho", slug: "cai-tao-nha-my-tho-ngan", status: "done" },
  { no: 2713, title: "Cải Tạo Nhà Cần Thơ", keyword: "cải tạo nhà Cần Thơ", slug: "cai-tao-nha-can-tho-ct-ngan", status: "done" },
  { no: 2714, title: "Thiết Kế Nhà Dĩ An", keyword: "thiết kế nhà Dĩ An", slug: "thiet-ke-nha-di-an-ngan", status: "done" },
  { no: 2715, title: "Thiết Kế Nhà Thuận An", keyword: "thiết kế nhà Thuận An", slug: "thiet-ke-nha-thuan-an-ngan", status: "done" },
  { no: 2716, title: "Thiết Kế Nhà Long Thành", keyword: "thiết kế nhà Long Thành", slug: "thiet-ke-nha-long-thanh-ngan", status: "done" },
  { no: 2717, title: "Thiết Kế Nhà Nhơn Trạch", keyword: "thiết kế nhà Nhơn Trạch", slug: "thiet-ke-nha-nhon-trach-ngan", status: "done" },
  { no: 2718, title: "Thiết Kế Nhà Đức Hòa", keyword: "thiết kế nhà Đức Hòa", slug: "thiet-ke-nha-duc-hoa-ngan", status: "done" },
  { no: 2719, title: "Thiết Kế Nhà Bến Lức", keyword: "thiết kế nhà Bến Lức", slug: "thiet-ke-nha-ben-luc-ngan", status: "done" },
  { no: 2720, title: "Báo Giá Xây Nhà Bình Dương", keyword: "báo giá xây nhà Bình Dương", slug: "bao-gia-xay-nha-binh-duong-ngan", status: "done" },
  { no: 2721, title: "Báo Giá Xây Nhà Đồng Nai", keyword: "báo giá xây nhà Đồng Nai", slug: "bao-gia-xay-nha-dong-nai-ngan", status: "done" },
  { no: 2722, title: "Báo Giá Xây Nhà Long An", keyword: "báo giá xây nhà Long An", slug: "bao-gia-xay-nha-long-an-ngan", status: "done" },
  { no: 2723, title: "Báo Giá Xây Nhà Tây Ninh", keyword: "báo giá xây nhà Tây Ninh", slug: "bao-gia-xay-nha-tay-ninh-ngan", status: "done" },
  { no: 2724, title: "Báo Giá Xây Nhà BRVT", keyword: "báo giá xây nhà bà rịa vũng tàu", slug: "bao-gia-xay-nha-brvt-ngan", status: "done" },
  { no: 2725, title: "Báo Giá Xây Nhà Tiền Giang", keyword: "báo giá xây nhà Tiền Giang", slug: "bao-gia-xay-nha-tien-giang-ngan", status: "done" },
  { no: 2726, title: "Báo Giá Xây Nhà Cần Thơ", keyword: "báo giá xây nhà Cần Thơ", slug: "bao-gia-xay-nha-can-tho-ngan", status: "done" },
  { no: 2727, title: "Nhà Thầu Bình Dương", keyword: "nhà thầu Bình Dương", slug: "nha-thau-binh-duong-ngan", status: "done" },
  { no: 2728, title: "Nhà Thầu Đồng Nai", keyword: "nhà thầu Đồng Nai", slug: "nha-thau-dong-nai-ngan", status: "done" },
  { no: 2729, title: "Nhà Thầu Long An", keyword: "nhà thầu Long An", slug: "nha-thau-long-an-ngan", status: "done" },
  { no: 2730, title: "Nhà Thầu Tây Ninh", keyword: "nhà thầu Tây Ninh", slug: "nha-thau-tay-ninh-ngan", status: "done" },
  { no: 2731, title: "Nhà Thầu BRVT", keyword: "nhà thầu bà rịa vũng tàu", slug: "nha-thau-brvt-ngan", status: "done" },
  { no: 2732, title: "Nhà Thầu Tiền Giang", keyword: "nhà thầu Tiền Giang", slug: "nha-thau-tien-giang-ngan", status: "done" },
  { no: 2733, title: "Nhà Thầu Cần Thơ", keyword: "nhà thầu Cần Thơ", slug: "nha-thau-can-tho-ngan", status: "done" },
  { no: 2734, title: "Xây Nhà KCN VSIP", keyword: "xây nhà gần VSIP", slug: "xay-nha-gan-vsip-ngan", status: "done" },
  { no: 2735, title: "Xây Nhà KCN Mỹ Phước", keyword: "xây nhà gần Mỹ Phước", slug: "xay-nha-gan-my-phuoc-ngan", status: "done" },
  { no: 2736, title: "Xây Nhà KCN Biên Hòa", keyword: "xây nhà gần KCN Biên Hòa", slug: "xay-nha-gan-kcn-bien-hoa-ngan", status: "done" },
  { no: 2737, title: "Xây Nhà Sân Bay Long Thành", keyword: "xây nhà gần sân bay Long Thành", slug: "xay-nha-gan-san-bay-long-thanh-ngan", status: "done" },
  { no: 2738, title: "Xây Nhà Cao Tốc Trung Lương", keyword: "xây nhà gần cao tốc Trung Lương", slug: "xay-nha-gan-cao-toc-trung-luong-ngan", status: "done" },
  { no: 2739, title: "Xây Nhà Cao Tốc Bến Lức", keyword: "xây nhà gần cao tốc Bến Lức", slug: "xay-nha-gan-cao-toc-ben-luc-ngan", status: "done" },
  { no: 2740, title: "Xây Biệt Thự Biên Hòa", keyword: "xây biệt thự Biên Hòa", slug: "xay-biet-thu-bien-hoa-ngan", status: "done" },
  { no: 2741, title: "Xây Biệt Thự Thủ Dầu Một", keyword: "xây biệt thự Thủ Dầu Một", slug: "xay-biet-thu-thu-dau-mot-ngan", status: "done" },
  { no: 2742, title: "Xây Biệt Thự Vũng Tàu", keyword: "xây biệt thự Vũng Tàu", slug: "xay-biet-thu-vung-tau-ngan", status: "done" },
  { no: 2743, title: "Xây Nhà Vườn Long An", keyword: "xây nhà vườn Long An", slug: "xay-nha-vuon-long-an-ngan", status: "done" },
  { no: 2744, title: "Xây Nhà Vườn Đồng Nai", keyword: "xây nhà vườn Đồng Nai", slug: "xay-nha-vuon-dong-nai-ngan", status: "done" },
  { no: 2745, title: "Xây Nhà Vườn Bình Dương", keyword: "xây nhà vườn Bình Dương", slug: "xay-nha-vuon-binh-duong-ngan", status: "done" },
  { no: 2746, title: "Chủ Đề Mở Rộng 32 1", keyword: "chủ đề mở rộng 32 1", slug: "chu-de-mo-rong-32-1-ngan", status: "done" },
];
