/**
 * Lịch 100 từ khóa SEO — batch 71 (#6547–#6646).
 * Cluster: Q.8/Q.12/Bình Tân + chống thấm chuyên sâu + FAQ vật tư (indexable *-sk71).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch71: ContentCalendarItem[] = [
  { no: 6547, title: "Xây Nhà Trọn Gói Quận 8 Mới 2026", keyword: "xây nhà trọn gói Quận 8 mới 2026", slug: "xay-nha-tron-goi-quan-8-moi-2026-sk71", status: "done" },
  { no: 6548, title: "Xây Nhà Phường 1 Quận 8", keyword: "xây nhà phường 1 Quận 8", slug: "xay-nha-phuong-1-quan-8-sk71", status: "done" },
  { no: 6549, title: "Xây Nhà Phường 4 Quận 8", keyword: "xây nhà phường 4 Quận 8", slug: "xay-nha-phuong-4-quan-8-sk71", status: "done" },
  { no: 6550, title: "Xây Nhà Phường 6 Quận 8", keyword: "xây nhà phường 6 Quận 8", slug: "xay-nha-phuong-6-quan-8-sk71", status: "done" },
  { no: 6551, title: "Xây Nhà Phường 7 Quận 8", keyword: "xây nhà phường 7 Quận 8", slug: "xay-nha-phuong-7-quan-8-sk71", status: "done" },
  { no: 6552, title: "Xây Nhà Phường 15 Quận 8", keyword: "xây nhà phường 15 Quận 8", slug: "xay-nha-phuong-15-quan-8-sk71", status: "done" },
  { no: 6553, title: "Xây Nhà Phường 16 Quận 8", keyword: "xây nhà phường 16 Quận 8", slug: "xay-nha-phuong-16-quan-8-sk71", status: "done" },
  { no: 6554, title: "Xây Nhà Phường Đông Hưng Thuận", keyword: "xây nhà phường Đông Hưng Thuận", slug: "xay-nha-phuong-dong-hung-thuan-sk71", status: "done" },
  { no: 6555, title: "Xây Nhà Phường Tân Chánh Hiệp", keyword: "xây nhà phường Tân Chánh Hiệp", slug: "xay-nha-phuong-tan-chanh-hiep-sk71", status: "done" },
  { no: 6556, title: "Xây Nhà Phường Tân Thới Hiệp", keyword: "xây nhà phường Tân Thới Hiệp", slug: "xay-nha-phuong-tan-thoi-hiep-sk71", status: "done" },
  { no: 6557, title: "Xây Nhà Phường Thới An", keyword: "xây nhà phường Thới An", slug: "xay-nha-phuong-thoi-an-sk71", status: "done" },
  { no: 6558, title: "Xây Nhà Phường An Lạc A", keyword: "xây nhà phường An Lạc A", slug: "xay-nha-phuong-an-lac-a-sk71", status: "done" },
  { no: 6559, title: "Xây Nhà Phường Bình Hưng Hòa A", keyword: "xây nhà phường Bình Hưng Hòa A", slug: "xay-nha-phuong-binh-hung-hoa-a-sk71", status: "done" },
  { no: 6560, title: "Xây Nhà Phường Bình Hưng Hòa B", keyword: "xây nhà phường Bình Hưng Hòa B", slug: "xay-nha-phuong-binh-hung-hoa-b-sk71", status: "done" },
  { no: 6561, title: "Xây Nhà Phường Tân Tạo A", keyword: "xây nhà phường Tân Tạo A", slug: "xay-nha-phuong-tan-tao-a-sk71", status: "done" },
  { no: 6562, title: "Xây Nhà Gần Chợ Lớn", keyword: "xây nhà gần Chợ Lớn", slug: "xay-nha-gan-cho-lon-sk71", status: "done" },
  { no: 6563, title: "Xây Nhà Gần Kênh Tẻ", keyword: "xây nhà gần kênh Tẻ", slug: "xay-nha-gan-kenh-te-sk71", status: "done" },
  { no: 6564, title: "Xây Nhà Gần Aeon Bình Tân", keyword: "xây nhà gần Aeon Bình Tân", slug: "xay-nha-gan-aeon-binh-tan-sk71", status: "done" },
  { no: 6565, title: "Xây Nhà Gần Tên Lửa", keyword: "xây nhà gần Tên Lửa", slug: "xay-nha-gan-ten-lua-sk71", status: "done" },
  { no: 6566, title: "Xây Nhà Gần Quốc Lộ 1A", keyword: "xây nhà gần Quốc lộ 1A", slug: "xay-nha-gan-quoc-lo-1a-sk71", status: "done" },

  { no: 6567, title: "Cải Tạo Nhà Quận 8 2026", keyword: "cải tạo nhà Quận 8 2026", slug: "cai-tao-nha-quan-8-2026-sk71", status: "done" },
  { no: 6568, title: "Cải Tạo Nhà Quận 12 2026", keyword: "cải tạo nhà Quận 12 2026", slug: "cai-tao-nha-quan-12-2026-sk71", status: "done" },
  { no: 6569, title: "Cải Tạo Nhà Bình Tân 2026", keyword: "cải tạo nhà Bình Tân 2026", slug: "cai-tao-nha-binh-tan-2026-sk71", status: "done" },
  { no: 6570, title: "Cải Tạo Nhà Gần Kênh Rạch", keyword: "cải tạo nhà gần kênh rạch", slug: "cai-tao-nha-gan-kenh-rach-sk71", status: "done" },
  { no: 6571, title: "Cải Tạo Nhà Nâng Cao Độ Nền", keyword: "cải tạo nhà nâng cao độ nền", slug: "cai-tao-nha-nang-cao-do-nen-sk71", status: "done" },
  { no: 6572, title: "Cải Tạo Nhà Chống Ngập Hộ", keyword: "cải tạo nhà chống ngập hộ", slug: "cai-tao-nha-chong-ngap-ho-sk71", status: "done" },
  { no: 6573, title: "Cải Tạo Nhà Đổi Hệ Thống Thoát Nước", keyword: "cải tạo nhà đổi hệ thống thoát nước", slug: "cai-tao-nha-doi-he-thong-thoat-nuoc-sk71", status: "done" },
  { no: 6574, title: "Cải Tạo Nhà Thêm Tầng Lửng Kinh Doanh", keyword: "cải tạo nhà thêm tầng lửng kinh doanh", slug: "cai-tao-nha-them-tang-lung-kinh-doanh-sk71", status: "done" },
  { no: 6575, title: "Sửa Nhà Thấm Chân Tường Quận 8", keyword: "sửa nhà thấm chân tường Quận 8", slug: "sua-nha-tham-chan-tuong-quan-8-sk71", status: "done" },
  { no: 6576, title: "Sửa Nhà Thấm Sân Thượng Bình Tân", keyword: "sửa nhà thấm sân thượng Bình Tân", slug: "sua-nha-tham-san-thuong-binh-tan-sk71", status: "done" },
  { no: 6577, title: "Sửa Nhà Nứt Tường Do Lún", keyword: "sửa nhà nứt tường do lún", slug: "sua-nha-nut-tuong-do-lun-sk71", status: "done" },
  { no: 6578, title: "Sửa Hệ Thống Bơm Nước Ngầm", keyword: "sửa hệ thống bơm nước ngầm", slug: "sua-he-thong-bom-nuoc-ngam-sk71", status: "done" },
  { no: 6579, title: "Thay Toàn Bộ Ống Cấp Thoát", keyword: "thay toàn bộ ống cấp thoát", slug: "thay-toan-bo-ong-cap-thoat-sk71", status: "done" },
  { no: 6580, title: "Nâng Tầng Nhà Nền Yếu", keyword: "nâng tầng nhà nền yếu", slug: "nang-tang-nha-nen-yeu-sk71", status: "done" },
  { no: 6581, title: "Cải Tạo Nhà Thành Kho Nhỏ", keyword: "cải tạo nhà thành kho nhỏ", slug: "cai-tao-nha-thanh-kho-nho-sk71", status: "done" },
  { no: 6582, title: "Cải Tạo Nhà Thành Xưởng Nhỏ", keyword: "cải tạo nhà thành xưởng nhỏ", slug: "cai-tao-nha-thanh-xuong-nho-sk71", status: "done" },
  { no: 6583, title: "Cải Tạo Nhà Cho Gia Đình Đông Con", keyword: "cải tạo nhà cho gia đình đông con", slug: "cai-tao-nha-cho-gia-dinh-dong-con-sk71", status: "done" },
  { no: 6584, title: "Sửa Chữa Nhà Sau Ngập Nước", keyword: "sửa chữa nhà sau ngập nước", slug: "sua-chua-nha-sau-ngap-nuoc-sk71", status: "done" },
  { no: 6585, title: "Cải Tạo Nhà Giảm Ẩm Tường", keyword: "cải tạo nhà giảm ẩm tường", slug: "cai-tao-nha-giam-am-tuong-sk71", status: "done" },
  { no: 6586, title: "Cải Tạo Nhà Tăng Cao Độ Trệt", keyword: "cải tạo nhà tăng cao độ trệt", slug: "cai-tao-nha-tang-cao-do-tret-sk71", status: "done" },

  { no: 6587, title: "Đơn Giá Chống Thấm Nhà Phố 2026", keyword: "đơn giá chống thấm nhà phố 2026", slug: "don-gia-chong-tham-nha-pho-2026-sk71", status: "done" },
  { no: 6588, title: "Chi Phí Ép Cọc Nhà Nền Yếu", keyword: "chi phí ép cọc nhà nền yếu", slug: "chi-phi-ep-coc-nha-nen-yeu-sk71", status: "done" },
  { no: 6589, title: "Chi Phí Xây Nhà 4×13 Trọn Gói", keyword: "chi phí xây nhà 4x13 trọn gói", slug: "chi-phi-xay-nha-4x13-tron-goi-sk71", status: "done" },
  { no: 6590, title: "Chi Phí Xây Nhà 5×14 Trọn Gói", keyword: "chi phí xây nhà 5x14 trọn gói", slug: "chi-phi-xay-nha-5x14-tron-goi-sk71", status: "done" },
  { no: 6591, title: "Chi Phí Xây Nhà 6×18 Trọn Gói", keyword: "chi phí xây nhà 6x18 trọn gói", slug: "chi-phi-xay-nha-6x18-tron-goi-sk71", status: "done" },
  { no: 6592, title: "Báo Giá Khoan Địa Chất Nhà Phố", keyword: "báo giá khoan địa chất nhà phố", slug: "bao-gia-khoan-dia-chat-nha-pho-sk71", status: "done" },
  { no: 6593, title: "Báo Giá Chống Thấm Ngược Sân", keyword: "báo giá chống thấm ngược sân", slug: "bao-gia-chong-tham-nguoc-san-sk71", status: "done" },
  { no: 6594, title: "Ngân Sách Xây Nhà 2,5 Tỷ TP.HCM", keyword: "ngân sách xây nhà 2.5 tỷ TP.HCM", slug: "ngan-sach-xay-nha-2-5-ty-tphcm-sk71", status: "done" },
  { no: 6595, title: "Ngân Sách Cải Tạo Nhà 150 Triệu", keyword: "ngân sách cải tạo nhà 150 triệu", slug: "ngan-sach-cai-tao-nha-150-trieu-sk71", status: "done" },
  { no: 6596, title: "Chi Phí Chống Thấm Toàn Bộ Mái", keyword: "chi phí chống thấm toàn bộ mái", slug: "chi-phi-chong-tham-toan-bo-mai-sk71", status: "done" },
  { no: 6597, title: "Chi Phí Làm Mới Hệ Thoát Nước", keyword: "chi phí làm mới hệ thoát nước", slug: "chi-phi-lam-moi-he-thoat-nuoc-sk71", status: "done" },
  { no: 6598, title: "Báo Giá Sơn Chống Thấm Ngoài Trời", keyword: "báo giá sơn chống thấm ngoài trời", slug: "bao-gia-son-chong-tham-ngoai-troi-sk71", status: "done" },
  { no: 6599, title: "Báo Giá Lát Gạch Nền Chống Ngập", keyword: "báo giá lát gạch nền chống ngập", slug: "bao-gia-lat-gach-nen-chong-ngap-sk71", status: "done" },
  { no: 6600, title: "Chi Phí Lắp Bơm Tăng Áp Nhà Phố", keyword: "chi phí lắp bơm tăng áp nhà phố", slug: "chi-phi-lap-bom-tang-ap-nha-pho-sk71", status: "done" },
  { no: 6601, title: "Cách Tính Chi Phí Ép Cọc", keyword: "cách tính chi phí ép cọc", slug: "cach-tinh-chi-phi-ep-coc-sk71", status: "done" },

  { no: 6602, title: "Thiết Kế Nhà Phố Nền Thấp", keyword: "thiết kế nhà phố nền thấp", slug: "thiet-ke-nha-pho-nen-thap-sk71", status: "done" },
  { no: 6603, title: "Thiết Kế Nhà Phố Có Bậc Tam Cấp Cao", keyword: "thiết kế nhà phố có bậc tam cấp cao", slug: "thiet-ke-nha-pho-co-bac-tam-cap-cao-sk71", status: "done" },
  { no: 6604, title: "Thiết Kế Nhà Phố Có Hầm Kỹ Thuật", keyword: "thiết kế nhà phố có hầm kỹ thuật", slug: "thiet-ke-nha-pho-co-ham-ky-thuat-sk71", status: "done" },
  { no: 6605, title: "Thiết Kế Nhà Phố Có Sân Sau Thoát Nước", keyword: "thiết kế nhà phố có sân sau thoát nước", slug: "thiet-ke-nha-pho-co-san-sau-thoat-nuoc-sk71", status: "done" },
  { no: 6606, title: "Thiết Kế Nhà Phố Có Bể Nước Ngầm", keyword: "thiết kế nhà phố có bể nước ngầm", slug: "thiet-ke-nha-pho-co-be-nuoc-ngam-sk71", status: "done" },
  { no: 6607, title: "Thiết Kế Nhà Phố 7 Phòng Ngủ", keyword: "thiết kế nhà phố 7 phòng ngủ", slug: "thiet-ke-nha-pho-7-phong-ngu-sk71", status: "done" },
  { no: 6608, title: "Thiết Kế Nhà Phố Có Phòng Máy", keyword: "thiết kế nhà phố có phòng máy", slug: "thiet-ke-nha-pho-co-phong-may-sk71", status: "done" },
  { no: 6609, title: "Thiết Kế Nhà Phố Có Kho Vật Tư", keyword: "thiết kế nhà phố có kho vật tư", slug: "thiet-ke-nha-pho-co-kho-vat-tu-sk71", status: "done" },
  { no: 6610, title: "Thiết Kế Biệt Thự Phố Bình Tân", keyword: "thiết kế biệt thự phố Bình Tân", slug: "thiet-ke-biet-thu-pho-binh-tan-sk71", status: "done" },
  { no: 6611, title: "Thiết Kế Nhà Vườn Củ Chi Mới", keyword: "thiết kế nhà vườn Củ Chi mới", slug: "thiet-ke-nha-vuon-cu-chi-moi-sk71", status: "done" },
  { no: 6612, title: "Mẫu Nhà Phố Chống Ngập 2026", keyword: "mẫu nhà phố chống ngập 2026", slug: "mau-nha-pho-chong-ngap-2026-sk71", status: "done" },
  { no: 6613, title: "Mẫu Nhà Phố Mặt Tiền 8m 2026", keyword: "mẫu nhà phố mặt tiền 8m 2026", slug: "mau-nha-pho-mat-tien-8m-2026-sk71", status: "done" },
  { no: 6614, title: "Thiết Kế Bếp Nhà Phố Nền Thấp", keyword: "thiết kế bếp nhà phố nền thấp", slug: "thiet-ke-bep-nha-pho-nen-thap-sk71", status: "done" },
  { no: 6615, title: "Thiết Kế Cầu Thang Nhà Nền Yếu", keyword: "thiết kế cầu thang nhà nền yếu", slug: "thiet-ke-cau-thang-nha-nen-yeu-sk71", status: "done" },
  { no: 6616, title: "Thiết Kế Giếng Trời Thoát Mưa", keyword: "thiết kế giếng trời thoát mưa", slug: "thiet-ke-gieng-troi-thoat-mua-sk71", status: "done" },

  { no: 6617, title: "Xây Nhà Ép Cọc Trước Khi Đổ Móng", keyword: "xây nhà ép cọc trước khi đổ móng", slug: "xay-nha-ep-coc-truoc-khi-do-mong-sk71", status: "done" },
  { no: 6618, title: "Xây Nhà Có Hệ Thoát Nước Mưa", keyword: "xây nhà có hệ thoát nước mưa", slug: "xay-nha-co-he-thoat-nuoc-mua-sk71", status: "done" },
  { no: 6619, title: "Đổ Móng Nhà Gần Kênh", keyword: "đổ móng nhà gần kênh", slug: "do-mong-nha-gan-kenh-sk71", status: "done" },
  { no: 6620, title: "Đổ Sàn Trệt Cao Hơn Mặt Đường", keyword: "đổ sàn trệt cao hơn mặt đường", slug: "do-san-tret-cao-hon-mat-duong-sk71", status: "done" },
  { no: 6621, title: "Làm Mái Có Máng Xối Lớn", keyword: "làm mái có máng xối lớn", slug: "lam-mai-co-mang-xoi-lon-sk71", status: "done" },
  { no: 6622, title: "Làm Sân Sau Có Hố Gas", keyword: "làm sân sau có hố gas", slug: "lam-san-sau-co-ho-gas-sk71", status: "done" },
  { no: 6623, title: "Chống Thấm Chân Tường Ngoài", keyword: "chống thấm chân tường ngoài", slug: "chong-tham-chan-tuong-ngoai-sk71", status: "done" },
  { no: 6624, title: "Lắp Cửa Chống Ngập Nhà Phố", keyword: "lắp cửa chống ngập nhà phố", slug: "lap-cua-chong-ngap-nha-pho-sk71", status: "done" },
  { no: 6625, title: "Ốp Đá Chân Tường Chống Ẩm", keyword: "ốp đá chân tường chống ẩm", slug: "op-da-chan-tuong-chong-am-sk71", status: "done" },
  { no: 6626, title: "Sơn Chống Thấm Tầng Hầm", keyword: "sơn chống thấm tầng hầm", slug: "son-chong-tham-tang-ham-sk71", status: "done" },
  { no: 6627, title: "Lát Gạch Sân Chống Trơn Mưa", keyword: "lát gạch sân chống trơn mưa", slug: "lat-gach-san-chong-tron-mua-sk71", status: "done" },
  { no: 6628, title: "Làm Vách Chống Ẩm WC", keyword: "làm vách chống ẩm WC", slug: "lam-vach-chong-am-wc-sk71", status: "done" },
  { no: 6629, title: "Lắp Van Một Chiều Thoát Nước", keyword: "lắp van một chiều thoát nước", slug: "lap-van-mot-chieu-thoat-nuoc-sk71", status: "done" },
  { no: 6630, title: "Lắp Bơm Chìm Hố Thu", keyword: "lắp bơm chìm hố thu", slug: "lap-bom-chim-ho-thu-sk71", status: "done" },
  { no: 6631, title: "Gia Cố Móng Nhà Gần Kênh", keyword: "gia cố móng nhà gần kênh", slug: "gia-co-mong-nha-gan-kenh-sk71", status: "done" },

  { no: 6632, title: "Xây Nhà Trọn Gói Trảng Bom 2026", keyword: "xây nhà trọn gói Trảng Bom 2026", slug: "xay-nha-tron-goi-trang-bom-2026-sk71", status: "done" },
  { no: 6633, title: "Xây Nhà Trọn Gói Long Khánh 2026", keyword: "xây nhà trọn gói Long Khánh 2026", slug: "xay-nha-tron-goi-long-khanh-2026-sk71", status: "done" },
  { no: 6634, title: "Xây Nhà Trọn Gói Xuân Lộc 2026", keyword: "xây nhà trọn gói Xuân Lộc 2026", slug: "xay-nha-tron-goi-xuan-loc-2026-sk71", status: "done" },
  { no: 6635, title: "Xây Nhà Trọn Gói Châu Thành 2026", keyword: "xây nhà trọn gói Châu Thành 2026", slug: "xay-nha-tron-goi-chau-thanh-2026-sk71", status: "done" },
  { no: 6636, title: "Xây Nhà Trọn Gói Thủ Thừa 2026", keyword: "xây nhà trọn gói Thủ Thừa 2026", slug: "xay-nha-tron-goi-thu-thua-2026-sk71", status: "done" },
  { no: 6637, title: "Xây Nhà Trọn Gói Bắc Tân Uyên 2026", keyword: "xây nhà trọn gói Bắc Tân Uyên 2026", slug: "xay-nha-tron-goi-bac-tan-uyen-2026-sk71", status: "done" },
  { no: 6638, title: "Xây Nhà Trọn Gói Phú Giáo 2026", keyword: "xây nhà trọn gói Phú Giáo 2026", slug: "xay-nha-tron-goi-phu-giao-2026-sk71", status: "done" },
  { no: 6639, title: "Cải Tạo Nhà Quận 8 Gần Kênh", keyword: "cải tạo nhà Quận 8 gần kênh", slug: "cai-tao-nha-quan-8-gan-kenh-sk71", status: "done" },
  { no: 6640, title: "Cải Tạo Nhà Bình Tân Nền Thấp", keyword: "cải tạo nhà Bình Tân nền thấp", slug: "cai-tao-nha-binh-tan-nen-thap-sk71", status: "done" },
  { no: 6641, title: "Xây Nhà Nền Yếu Cần Ép Cọc Không", keyword: "xây nhà nền yếu cần ép cọc không", slug: "xay-nha-nen-yeu-can-ep-coc-khong-sk71", status: "done" },
  { no: 6642, title: "Nhà Gần Kênh Cần Chống Thấm Gì", keyword: "nhà gần kênh cần chống thấm gì", slug: "nha-gan-kenh-can-chong-tham-gi-sk71", status: "done" },
  { no: 6643, title: "Xây Nhà Có Nên Khoan Địa Chất", keyword: "xây nhà có nên khoan địa chất", slug: "xay-nha-co-nen-khoan-dia-chat-sk71", status: "done" },
  { no: 6644, title: "Cách Chọn Vật Tư Chống Thấm", keyword: "cách chọn vật tư chống thấm", slug: "cach-chon-vat-tu-chong-tham-sk71", status: "done" },
  { no: 6645, title: "Checklist Nghiệm Thu Chống Thấm", keyword: "checklist nghiệm thu chống thấm", slug: "checklist-nghiem-thu-chong-tham-sk71", status: "done" },
  { no: 6646, title: "Khi Nào Nên Gia Cố Móng Nhà Cũ", keyword: "khi nào nên gia cố móng nhà cũ", slug: "khi-nao-nen-gia-co-mong-nha-cu-sk71", status: "done" },
];
