/**
 * Lịch 100 từ khóa ngắn — batch 41 (#3547–#3646).
 * Cluster: MEP điện nước HVAC chi tiết.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch41: ContentCalendarItem[] = [
  { no: 3547, title: "Hệ Thống Điện 1 Pha Nhà Phố", keyword: "hệ thống điện 1 pha nhà phố", slug: "he-thong-dien-1-pha-mep-ngan", status: "done" },
  { no: 3548, title: "Hệ Thống Điện 3 Pha Nhà Phố", keyword: "hệ thống điện 3 pha nhà phố", slug: "he-thong-dien-3-pha-mep-ngan", status: "done" },
  { no: 3549, title: "Tủ Điện Tổng Nhà Phố", keyword: "tủ điện tổng nhà phố", slug: "tu-dien-tong-nha-pho-mep-ngan", status: "done" },
  { no: 3550, title: "Tủ Điện Tầng", keyword: "tủ điện tầng", slug: "tu-dien-tang-mep-ngan", status: "done" },
  { no: 3551, title: "Aptomat Chống Giật", keyword: "aptomat chống giật", slug: "aptomat-chong-giat-mep-ngan", status: "done" },
  { no: 3552, title: "Aptomat Chống Sét", keyword: "aptomat chống sét", slug: "aptomat-chong-set-mep-ngan", status: "done" },
  { no: 3553, title: "Tiếp Địa Nhà Phố", keyword: "tiếp địa nhà phố", slug: "tiep-dia-nha-pho-mep-ngan", status: "done" },
  { no: 3554, title: "Chống Sét Nhà Phố", keyword: "chống sét nhà phố", slug: "chong-set-nha-pho-mep-ngan", status: "done" },
  { no: 3555, title: "Ống Ruột Gà Điện", keyword: "ống ruột gà điện", slug: "ong-ruot-ga-dien-mep-ngan", status: "done" },
  { no: 3556, title: "Ống PVC Đi Dây Điện", keyword: "ống pvc đi dây điện", slug: "ong-pvc-di-day-dien-mep-ngan", status: "done" },
  { no: 3557, title: "Dây Điện Âm Tường", keyword: "dây điện âm tường", slug: "day-dien-am-tuong-mep-ngan", status: "done" },
  { no: 3558, title: "Dây Điện Nổi", keyword: "dây điện nổi", slug: "day-dien-noi-mep-ngan", status: "done" },
  { no: 3559, title: "Ổ Cắm Âm Tường", keyword: "ổ cắm âm tường", slug: "o-cam-am-tuong-mep-ngan", status: "done" },
  { no: 3560, title: "Ổ Cắm USB Nhà Phố", keyword: "ổ cắm usb nhà phố", slug: "o-cam-usb-nha-pho-mep-ngan", status: "done" },
  { no: 3561, title: "Công Tắc Đôi", keyword: "công tắc đôi", slug: "cong-tac-doi-mep-ngan", status: "done" },
  { no: 3562, title: "Công Tắc Ba", keyword: "công tắc ba", slug: "cong-tac-ba-mep-ngan", status: "done" },
  { no: 3563, title: "Công Tắc Cảm Ứng Hiện Diện", keyword: "công tắc cảm ứng hiện diện", slug: "cong-tac-cam-ung-hien-dien-mep-ngan", status: "done" },
  { no: 3564, title: "Đèn Cảm Biến Chuyển Động", keyword: "đèn cảm biến chuyển động", slug: "den-cam-bien-chuyen-dong-mep-ngan", status: "done" },
  { no: 3565, title: "Đèn Khẩn Cấp Nhà", keyword: "đèn khẩn cấp nhà", slug: "den-khan-cap-nha-mep-ngan", status: "done" },
  { no: 3566, title: "Hệ Thống Chiếu Sáng Ngoài Trời", keyword: "hệ thống chiếu sáng ngoài trời", slug: "he-thong-chieu-sang-ngoai-troi-mep-ngan", status: "done" },
  { no: 3567, title: "Bơm Tăng Áp Nhà Phố", keyword: "bơm tăng áp nhà phố", slug: "bom-tang-ap-nha-pho-mep-ngan", status: "done" },
  { no: 3568, title: "Bơm Hút Giếng", keyword: "bơm hút giếng", slug: "bom-hut-gieng-mep-ngan", status: "done" },
  { no: 3569, title: "Bồn Nước Inox 500L", keyword: "bồn nước inox 500l", slug: "bon-nuoc-inox-500l-mep-ngan", status: "done" },
  { no: 3570, title: "Bồn Nước Inox 1000L", keyword: "bồn nước inox 1000l", slug: "bon-nuoc-inox-1000l-mep-ngan", status: "done" },
  { no: 3571, title: "Bồn Nước Nhựa Composite", keyword: "bồn nước nhựa composite", slug: "bon-nuoc-nhua-composite-mep-ngan", status: "done" },
  { no: 3572, title: "Ống PPR Cấp Nước", keyword: "ống ppr cấp nước", slug: "ong-ppr-cap-nuoc-mep-ngan", status: "done" },
  { no: 3573, title: "Ống HDPE Cấp Nước", keyword: "ống hdpe cấp nước", slug: "ong-hdpe-cap-nuoc-mep-ngan", status: "done" },
  { no: 3574, title: "Ống uPVC Thoát Nước", keyword: "ống upvc thoát nước", slug: "ong-upvc-thoat-nuoc-mep-ngan", status: "done" },
  { no: 3575, title: "Ống Thoát Nước Mưa", keyword: "ống thoát nước mưa", slug: "ong-thoat-nuoc-mua-mep-ngan", status: "done" },
  { no: 3576, title: "Hố Ga Nhà Phố", keyword: "hố ga nhà phố", slug: "ho-ga-nha-pho-mep-ngan", status: "done" },
  { no: 3577, title: "Bể Tự Hoại 3 Ngăn", keyword: "bể tự hoại 3 ngăn", slug: "be-tu-hoai-3-ngan-mep-ngan", status: "done" },
  { no: 3578, title: "Bể Tự Hoại Composite", keyword: "bể tự hoại composite", slug: "be-tu-hoai-composite-mep-ngan", status: "done" },
  { no: 3579, title: "Van Một Chiều Nước", keyword: "van một chiều nước", slug: "van-mot-chieu-nuoc-mep-ngan", status: "done" },
  { no: 3580, title: "Van Giảm Áp", keyword: "van giảm áp", slug: "van-giam-ap-mep-ngan", status: "done" },
  { no: 3581, title: "Lọc Nước Đầu Nguồn", keyword: "lọc nước đầu nguồn", slug: "loc-nuoc-dau-nguon-mep-ngan", status: "done" },
  { no: 3582, title: "Máy Lọc Nước RO Gia Đình", keyword: "máy lọc nước ro gia đình", slug: "may-loc-nuoc-ro-gia-dinh-mep-ngan", status: "done" },
  { no: 3583, title: "Máy Nước Nóng Trung Tâm", keyword: "máy nước nóng trung tâm", slug: "may-nuoc-nong-trung-tam-mep-ngan", status: "done" },
  { no: 3584, title: "Máy Nước Nóng Trực Tiếp", keyword: "máy nước nóng trực tiếp", slug: "may-nuoc-nong-truc-tiep-mep-ngan", status: "done" },
  { no: 3585, title: "Máy Nước Nóng Gián Tiếp", keyword: "máy nước nóng gián tiếp", slug: "may-nuoc-nong-gian-tiep-mep-ngan", status: "done" },
  { no: 3586, title: "Hệ Thống Máy Lạnh Multi", keyword: "hệ thống máy lạnh multi", slug: "he-thong-may-lanh-multi-mep-ngan", status: "done" },
  { no: 3587, title: "Máy Lạnh Âm Trần", keyword: "máy lạnh âm trần", slug: "may-lanh-am-tran-mep-ngan", status: "done" },
  { no: 3588, title: "Máy Lạnh Tủ Đứng", keyword: "máy lạnh tủ đứng", slug: "may-lanh-tu-dung-mep-ngan", status: "done" },
  { no: 3589, title: "Ống Đồng Máy Lạnh", keyword: "ống đồng máy lạnh", slug: "ong-dong-may-lanh-mep-ngan", status: "done" },
  { no: 3590, title: "Ống Thoát Nước Condensate", keyword: "ống thoát nước condensate", slug: "ong-thoat-nuoc-condensate-mep-ngan", status: "done" },
  { no: 3591, title: "Giàn Nóng Máy Lạnh Vị Trí", keyword: "giàn nóng máy lạnh vị trí", slug: "gian-nong-may-lanh-vi-tri-mep-ngan", status: "done" },
  { no: 3592, title: "Thông Gió Cơ Khí Nhà", keyword: "thông gió cơ khí nhà", slug: "thong-gio-co-khi-nha-mep-ngan", status: "done" },
  { no: 3593, title: "Quạt Hút Trần", keyword: "quạt hút trần", slug: "quat-hut-tran-mep-ngan", status: "done" },
  { no: 3594, title: "Quạt Hút Tường", keyword: "quạt hút tường", slug: "quat-hut-tuong-mep-ngan", status: "done" },
  { no: 3595, title: "Ống Gió Nhựa", keyword: "ống gió nhựa", slug: "ong-gio-nhua-mep-ngan", status: "done" },
  { no: 3596, title: "Ống Gió Tôn Mạ", keyword: "ống gió tôn mạ", slug: "ong-gio-ton-ma-mep-ngan", status: "done" },
  { no: 3597, title: "Hệ Thống Internet Nhà", keyword: "hệ thống internet nhà", slug: "he-thong-internet-nha-mep-ngan", status: "done" },
  { no: 3598, title: "Mạng LAN Nhà Phố", keyword: "mạng lan nhà phố", slug: "mang-lan-nha-pho-mep-ngan", status: "done" },
  { no: 3599, title: "Wifi Mesh Nhà Phố", keyword: "wifi mesh nhà phố", slug: "wifi-mesh-nha-pho-mep-ngan", status: "done" },
  { no: 3600, title: "Tủ Rack Nhà Phố", keyword: "tủ rack nhà phố", slug: "tu-rack-nha-pho-mep-ngan", status: "done" },
  { no: 3601, title: "Hệ Thống Camera IP", keyword: "hệ thống camera ip", slug: "he-thong-camera-ip-mep-ngan", status: "done" },
  { no: 3602, title: "Đầu Ghi Hình NVR", keyword: "đầu ghi hình nvr", slug: "dau-ghi-hinh-nvr-mep-ngan", status: "done" },
  { no: 3603, title: "Chuông Cửa Video", keyword: "chuông cửa video", slug: "chuong-cua-video-mep-ngan", status: "done" },
  { no: 3604, title: "Intercom Nhà Phố", keyword: "intercom nhà phố", slug: "intercom-nha-pho-mep-ngan", status: "done" },
  { no: 3605, title: "Hệ Thống Âm Thanh Nhà", keyword: "hệ thống âm thanh nhà", slug: "he-thong-am-thanh-nha-mep-ngan", status: "done" },
  { no: 3606, title: "Loa Âm Trần", keyword: "loa âm trần", slug: "loa-am-tran-mep-ngan", status: "done" },
  { no: 3607, title: "TV Outlet Nhà Phố", keyword: "tv outlet nhà phố", slug: "tv-outlet-nha-pho-mep-ngan", status: "done" },
  { no: 3608, title: "Điểm Mạng Mỗi Phòng", keyword: "điểm mạng mỗi phòng", slug: "diem-mang-moi-phong-mep-ngan", status: "done" },
  { no: 3609, title: "Báo Giá Hệ Điện Nhà Phố", keyword: "báo giá hệ điện nhà phố", slug: "bao-gia-he-dien-nha-pho-mep-ngan", status: "done" },
  { no: 3610, title: "Báo Giá Hệ Nước Nhà Phố", keyword: "báo giá hệ nước nhà phố", slug: "bao-gia-he-nuoc-nha-pho-mep-ngan", status: "done" },
  { no: 3611, title: "Báo Giá Máy Lạnh Nhà Phố", keyword: "báo giá máy lạnh nhà phố", slug: "bao-gia-may-lanh-nha-pho-mep-ngan", status: "done" },
  { no: 3612, title: "Báo Giá Thông Gió Nhà", keyword: "báo giá thông gió nhà", slug: "bao-gia-thong-gio-nha-mep-ngan", status: "done" },
  { no: 3613, title: "Chi Phí Đi Điện Âm", keyword: "chi phí đi điện âm", slug: "chi-phi-di-dien-am-mep-ngan", status: "done" },
  { no: 3614, title: "Chi Phí Đi Nước Âm", keyword: "chi phí đi nước âm", slug: "chi-phi-di-nuoc-am-mep-ngan", status: "done" },
  { no: 3615, title: "Quy Trình Thi Công Điện", keyword: "quy trình thi công điện", slug: "quy-trinh-thi-cong-dien-mep-ngan", status: "done" },
  { no: 3616, title: "Quy Trình Thi Công Nước", keyword: "quy trình thi công nước", slug: "quy-trinh-thi-cong-nuoc-mep-ngan", status: "done" },
  { no: 3617, title: "Nghiệm Thu Hệ Điện", keyword: "nghiệm thu hệ điện", slug: "nghiem-thu-he-dien-mep-ngan", status: "done" },
  { no: 3618, title: "Nghiệm Thu Hệ Nước", keyword: "nghiệm thu hệ nước", slug: "nghiem-thu-he-nuoc-mep-ngan", status: "done" },
  { no: 3619, title: "Nghiệm Thu Máy Lạnh", keyword: "nghiệm thu máy lạnh", slug: "nghiem-thu-may-lanh-mep-ngan", status: "done" },
  { no: 3620, title: "Bảo Trì Hệ Điện Nhà", keyword: "bảo trì hệ điện nhà", slug: "bao-tri-he-dien-nha-mep-ngan", status: "done" },
  { no: 3621, title: "Bảo Trì Hệ Nước Nhà", keyword: "bảo trì hệ nước nhà", slug: "bao-tri-he-nuoc-nha-mep-ngan", status: "done" },
  { no: 3622, title: "Bảo Trì Máy Lạnh Định Kỳ", keyword: "bảo trì máy lạnh định kỳ", slug: "bao-tri-may-lanh-dinh-ky-mep-ngan", status: "done" },
  { no: 3623, title: "Sửa Chữa Điện Nhà", keyword: "sửa chữa điện nhà", slug: "sua-chua-dien-nha-mep-ngan", status: "done" },
  { no: 3624, title: "Sửa Chữa Nước Nhà", keyword: "sửa chữa nước nhà", slug: "sua-chua-nuoc-nha-mep-ngan", status: "done" },
  { no: 3625, title: "Thay Thế Ống Nước Cũ", keyword: "thay thế ống nước cũ", slug: "thay-the-ong-nuoc-cu-mep-ngan", status: "done" },
  { no: 3626, title: "Thay Thế Dây Điện Cũ", keyword: "thay thế dây điện cũ", slug: "thay-the-day-dien-cu-mep-ngan", status: "done" },
  { no: 3627, title: "Nâng Cấp Tủ Điện", keyword: "nâng cấp tủ điện", slug: "nang-cap-tu-dien-mep-ngan", status: "done" },
  { no: 3628, title: "Nâng Cấp Bơm Nước", keyword: "nâng cấp bơm nước", slug: "nang-cap-bom-nuoc-mep-ngan", status: "done" },
  { no: 3629, title: "Checklist MEP Trước Đổ Trần", keyword: "checklist mep trước đổ trần", slug: "checklist-mep-truoc-do-tran-ngan", status: "done" },
  { no: 3630, title: "Checklist MEP Trước Sơn", keyword: "checklist mep trước sơn", slug: "checklist-mep-truoc-son-ngan", status: "done" },
  { no: 3631, title: "Lỗi Thường Gặp Hệ Điện", keyword: "lỗi thường gặp hệ điện", slug: "loi-thuong-gap-he-dien-mep-ngan", status: "done" },
  { no: 3632, title: "Lỗi Thường Gặp Hệ Nước", keyword: "lỗi thường gặp hệ nước", slug: "loi-thuong-gap-he-nuoc-mep-ngan", status: "done" },
  { no: 3633, title: "Lỗi Thường Gặp Máy Lạnh", keyword: "lỗi thường gặp máy lạnh", slug: "loi-thuong-gap-may-lanh-mep-ngan", status: "done" },
  { no: 3634, title: "Tiết Kiệm Điện Nhà Phố", keyword: "tiết kiệm điện nhà phố", slug: "tiet-kiem-dien-nha-pho-mep-ngan", status: "done" },
  { no: 3635, title: "Tiết Kiệm Nước Nhà Phố", keyword: "tiết kiệm nước nhà phố", slug: "tiet-kiem-nuoc-nha-pho-mep-ngan", status: "done" },
  { no: 3636, title: "Đồng Hồ Điện Thông Minh", keyword: "đồng hồ điện thông minh", slug: "dong-ho-dien-thong-minh-mep-ngan", status: "done" },
  { no: 3637, title: "Đồng Hồ Nước Thông Minh", keyword: "đồng hồ nước thông minh", slug: "dong-ho-nuoc-thong-minh-mep-ngan", status: "done" },
  { no: 3638, title: "UPS Gia Đình", keyword: "ups gia đình", slug: "ups-gia-dinh-mep-ngan", status: "done" },
  { no: 3639, title: "Máy Phát Điện Gia Đình", keyword: "máy phát điện gia đình", slug: "may-phat-dien-gia-dinh-mep-ngan", status: "done" },
  { no: 3640, title: "Inverter Hybrid Nhà", keyword: "inverter hybrid nhà", slug: "inverter-hybrid-nha-mep-ngan", status: "done" },
  { no: 3641, title: "Tích Hợp Smart Home MEP", keyword: "tích hợp smart home mep", slug: "tich-hop-smart-home-mep-ngan", status: "done" },
  { no: 3642, title: "Bản Vẽ Điện Nhà Phố", keyword: "bản vẽ điện nhà phố", slug: "ban-ve-dien-nha-pho-mep-ngan", status: "done" },
  { no: 3643, title: "Bản Vẽ Nước Nhà Phố", keyword: "bản vẽ nước nhà phố", slug: "ban-ve-nuoc-nha-pho-mep-ngan", status: "done" },
  { no: 3644, title: "Bản Vẽ Điều Hòa Nhà", keyword: "bản vẽ điều hòa nhà", slug: "ban-ve-dieu-hoa-nha-mep-ngan", status: "done" },
  { no: 3645, title: "Chủ Đề Mở Rộng 41 1", keyword: "chủ đề mở rộng 41 1", slug: "chu-de-mo-rong-41-1-ngan", status: "done" },
  { no: 3646, title: "Chủ Đề Mở Rộng 41 2", keyword: "chủ đề mở rộng 41 2", slug: "chu-de-mo-rong-41-2-ngan", status: "done" },
];
