/**
 * Lịch 100 từ khóa ngắn — batch 52 (#4647–#4746).
 * Cluster: geo Tây Nguyên, duyên hải miền Trung.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch52: ContentCalendarItem[] = [
  { no: 4647, title: "Xây Nhà Buôn Hồ", keyword: "xây nhà Buôn Hồ", slug: "xay-nha-buon-ho-geo3-ngan", status: "done" },
  { no: 4648, title: "Xây Nhà Ea Hleo", keyword: "xây nhà Ea Hleo", slug: "xay-nha-ea-hleo-geo3-ngan", status: "done" },
  { no: 4649, title: "Xây Nhà Krông Buk", keyword: "xây nhà Krông Buk", slug: "xay-nha-krong-buk-geo3-ngan", status: "done" },
  { no: 4650, title: "Xây Nhà Krông Pắc", keyword: "xây nhà Krông Pắc", slug: "xay-nha-krong-pac-geo3-ngan", status: "done" },
  { no: 4651, title: "Xây Nhà Cư Mgar", keyword: "xây nhà Cư Mgar", slug: "xay-nha-cu-mgar-geo3-ngan", status: "done" },
  { no: 4652, title: "Xây Nhà Buôn Đôn", keyword: "xây nhà Buôn Đôn", slug: "xay-nha-buon-don-geo3-ngan", status: "done" },
  { no: 4653, title: "Xây Nhà Ea Súp", keyword: "xây nhà Ea Súp", slug: "xay-nha-ea-sup-geo3-ngan", status: "done" },
  { no: 4654, title: "Xây Nhà M Đrắk", keyword: "xây nhà M Đrắk", slug: "xay-nha-m-drak-geo3-ngan", status: "done" },
  { no: 4655, title: "Xây Nhà Krông Ana", keyword: "xây nhà Krông Ana", slug: "xay-nha-krong-ana-geo3-ngan", status: "done" },
  { no: 4656, title: "Xây Nhà Lắk", keyword: "xây nhà Lắk", slug: "xay-nha-lak-geo3-ngan", status: "done" },
  { no: 4657, title: "Xây Nhà Cư Kuin", keyword: "xây nhà Cư Kuin", slug: "xay-nha-cu-kuin-geo3-ngan", status: "done" },
  { no: 4658, title: "Xây Nhà Gia Nghĩa", keyword: "xây nhà Gia Nghĩa", slug: "xay-nha-gia-nghia-geo3-ngan", status: "done" },
  { no: 4659, title: "Xây Nhà Đắk Mil", keyword: "xây nhà Đắk Mil", slug: "xay-nha-dak-mil-geo3-ngan", status: "done" },
  { no: 4660, title: "Xây Nhà Đắk Song", keyword: "xây nhà Đắk Song", slug: "xay-nha-dak-song-geo3-ngan", status: "done" },
  { no: 4661, title: "Xây Nhà Cư Jút", keyword: "xây nhà Cư Jút", slug: "xay-nha-cu-jut-geo3-ngan", status: "done" },
  { no: 4662, title: "Xây Nhà Đắk RLấp", keyword: "xây nhà Đắk RLấp", slug: "xay-nha-dak-rlap-geo3-ngan", status: "done" },
  { no: 4663, title: "Xây Nhà Đắk Glong", keyword: "xây nhà Đắk Glong", slug: "xay-nha-dak-glong-geo3-ngan", status: "done" },
  { no: 4664, title: "Xây Nhà Krông Nô", keyword: "xây nhà Krông Nô", slug: "xay-nha-krong-no-geo3-ngan", status: "done" },
  { no: 4665, title: "Xây Nhà Đắk Tô", keyword: "xây nhà Đắk Tô", slug: "xay-nha-dak-to-geo3-ngan", status: "done" },
  { no: 4666, title: "Xây Nhà Ngọc Hồi", keyword: "xây nhà Ngọc Hồi", slug: "xay-nha-ngoc-hoi-geo3-ngan", status: "done" },
  { no: 4667, title: "Xây Nhà Sa Thầy", keyword: "xây nhà Sa Thầy", slug: "xay-nha-sa-thay-geo3-ngan", status: "done" },
  { no: 4668, title: "Xây Nhà Kon Plông", keyword: "xây nhà Kon Plông", slug: "xay-nha-kon-plong-geo3-ngan", status: "done" },
  { no: 4669, title: "Xây Nhà Đắk Hà", keyword: "xây nhà Đắk Hà", slug: "xay-nha-dak-ha-geo3-ngan", status: "done" },
  { no: 4670, title: "Xây Nhà Kon Rẫy", keyword: "xây nhà Kon Rẫy", slug: "xay-nha-kon-ray-geo3-ngan", status: "done" },
  { no: 4671, title: "Xây Nhà An Khê", keyword: "xây nhà An Khê", slug: "xay-nha-an-khe-geo3-ngan", status: "done" },
  { no: 4672, title: "Xây Nhà Ayun Pa", keyword: "xây nhà Ayun Pa", slug: "xay-nha-ayun-pa-geo3-ngan", status: "done" },
  { no: 4673, title: "Xây Nhà Chư Sê", keyword: "xây nhà Chư Sê", slug: "xay-nha-chu-se-geo3-ngan", status: "done" },
  { no: 4674, title: "Xây Nhà Chư Păh", keyword: "xây nhà Chư Păh", slug: "xay-nha-chu-pah-geo3-ngan", status: "done" },
  { no: 4675, title: "Xây Nhà Ia Grai", keyword: "xây nhà Ia Grai", slug: "xay-nha-ia-grai-geo3-ngan", status: "done" },
  { no: 4676, title: "Xây Nhà Đức Cơ", keyword: "xây nhà Đức Cơ", slug: "xay-nha-duc-co-geo3-ngan", status: "done" },
  { no: 4677, title: "Xây Nhà Chư Prông", keyword: "xây nhà Chư Prông", slug: "xay-nha-chu-prong-geo3-ngan", status: "done" },
  { no: 4678, title: "Xây Nhà KBang", keyword: "xây nhà KBang", slug: "xay-nha-kbang-geo3-ngan", status: "done" },
  { no: 4679, title: "Xây Nhà Kông Chro", keyword: "xây nhà Kông Chro", slug: "xay-nha-kong-chro-geo3-ngan", status: "done" },
  { no: 4680, title: "Xây Nhà Mang Yang", keyword: "xây nhà Mang Yang", slug: "xay-nha-mang-yang-geo3-ngan", status: "done" },
  { no: 4681, title: "Xây Nhà Đak Đoa", keyword: "xây nhà Đak Đoa", slug: "xay-nha-dak-doa-geo3-ngan", status: "done" },
  { no: 4682, title: "Xây Nhà Bảo Lộc", keyword: "xây nhà Bảo Lộc", slug: "xay-nha-bao-loc-geo3-ngan", status: "done" },
  { no: 4683, title: "Xây Nhà Đức Trọng", keyword: "xây nhà Đức Trọng", slug: "xay-nha-duc-trong-geo3-ngan", status: "done" },
  { no: 4684, title: "Xây Nhà Di Linh", keyword: "xây nhà Di Linh", slug: "xay-nha-di-linh-geo3-ngan", status: "done" },
  { no: 4685, title: "Xây Nhà Bảo Lâm LĐ", keyword: "xây nhà Bảo Lâm Lâm Đồng", slug: "xay-nha-bao-lam-ld-geo3-ngan", status: "done" },
  { no: 4686, title: "Xây Nhà Đạ Huoai", keyword: "xây nhà Đạ Huoai", slug: "xay-nha-da-huoai-geo3-ngan", status: "done" },
  { no: 4687, title: "Xây Nhà Đạ Tẻh", keyword: "xây nhà Đạ Tẻh", slug: "xay-nha-da-teh-geo3-ngan", status: "done" },
  { no: 4688, title: "Xây Nhà Cát Tiên", keyword: "xây nhà Cát Tiên", slug: "xay-nha-cat-tien-geo3-ngan", status: "done" },
  { no: 4689, title: "Xây Nhà Đơn Dương", keyword: "xây nhà Đơn Dương", slug: "xay-nha-don-duong-geo3-ngan", status: "done" },
  { no: 4690, title: "Xây Nhà Lạc Dương", keyword: "xây nhà Lạc Dương", slug: "xay-nha-lac-duong-geo3-ngan", status: "done" },
  { no: 4691, title: "Xây Nhà Đam Rông", keyword: "xây nhà Đam Rông", slug: "xay-nha-dam-rong-geo3-ngan", status: "done" },
  { no: 4692, title: "Xây Nhà Cam Ranh", keyword: "xây nhà Cam Ranh", slug: "xay-nha-cam-ranh-geo3-ngan", status: "done" },
  { no: 4693, title: "Xây Nhà Ninh Hòa", keyword: "xây nhà Ninh Hòa", slug: "xay-nha-ninh-hoa-geo3-ngan", status: "done" },
  { no: 4694, title: "Xây Nhà Vạn Ninh", keyword: "xây nhà Vạn Ninh", slug: "xay-nha-van-ninh-geo3-ngan", status: "done" },
  { no: 4695, title: "Xây Nhà Diên Khánh", keyword: "xây nhà Diên Khánh", slug: "xay-nha-dien-khanh-geo3-ngan", status: "done" },
  { no: 4696, title: "Xây Nhà Cam Lâm", keyword: "xây nhà Cam Lâm", slug: "xay-nha-cam-lam-geo3-ngan", status: "done" },
  { no: 4697, title: "Xây Nhà Khánh Vĩnh", keyword: "xây nhà Khánh Vĩnh", slug: "xay-nha-khanh-vinh-geo3-ngan", status: "done" },
  { no: 4698, title: "Xây Nhà Khánh Sơn", keyword: "xây nhà Khánh Sơn", slug: "xay-nha-khanh-son-geo3-ngan", status: "done" },
  { no: 4699, title: "Xây Nhà Tuy Hòa", keyword: "xây nhà Tuy Hòa", slug: "xay-nha-tuy-hoa-geo3-ngan", status: "done" },
  { no: 4700, title: "Xây Nhà Sông Cầu", keyword: "xây nhà Sông Cầu", slug: "xay-nha-song-cau-geo3-ngan", status: "done" },
  { no: 4701, title: "Xây Nhà Đông Hòa PY", keyword: "xây nhà Đông Hòa Phú Yên", slug: "xay-nha-dong-hoa-py-geo3-ngan", status: "done" },
  { no: 4702, title: "Xây Nhà Tây Hòa", keyword: "xây nhà Tây Hòa", slug: "xay-nha-tay-hoa-geo3-ngan", status: "done" },
  { no: 4703, title: "Xây Nhà Quy Nhơn", keyword: "xây nhà Quy Nhơn", slug: "xay-nha-quy-nhon-geo3-ngan", status: "done" },
  { no: 4704, title: "Xây Nhà An Nhơn", keyword: "xây nhà An Nhơn", slug: "xay-nha-an-nhon-geo3-ngan", status: "done" },
  { no: 4705, title: "Xây Nhà Hoài Nhơn", keyword: "xây nhà Hoài Nhơn", slug: "xay-nha-hoai-nhon-geo3-ngan", status: "done" },
  { no: 4706, title: "Xây Nhà Phù Cát", keyword: "xây nhà Phù Cát", slug: "xay-nha-phu-cat-geo3-ngan", status: "done" },
  { no: 4707, title: "Xây Nhà Tuy Phước", keyword: "xây nhà Tuy Phước", slug: "xay-nha-tuy-phuoc-geo3-ngan", status: "done" },
  { no: 4708, title: "Xây Nhà Tây Sơn BD", keyword: "xây nhà Tây Sơn Bình Định", slug: "xay-nha-tay-son-bd-geo3-ngan", status: "done" },
  { no: 4709, title: "Xây Nhà Hội An", keyword: "xây nhà Hội An", slug: "xay-nha-hoi-an-geo3-ngan", status: "done" },
  { no: 4710, title: "Xây Nhà Tam Kỳ", keyword: "xây nhà Tam Kỳ", slug: "xay-nha-tam-ky-geo3-ngan", status: "done" },
  { no: 4711, title: "Xây Nhà Điện Bàn", keyword: "xây nhà Điện Bàn", slug: "xay-nha-dien-ban-geo3-ngan", status: "done" },
  { no: 4712, title: "Xây Nhà Núi Thành", keyword: "xây nhà Núi Thành", slug: "xay-nha-nui-thanh-geo3-ngan", status: "done" },
  { no: 4713, title: "Xây Nhà Duy Xuyên", keyword: "xây nhà Duy Xuyên", slug: "xay-nha-duy-xuyen-geo3-ngan", status: "done" },
  { no: 4714, title: "Xây Nhà Quảng Ngãi TP", keyword: "xây nhà Quảng Ngãi", slug: "xay-nha-quang-ngai-tp-geo3-ngan", status: "done" },
  { no: 4715, title: "Xây Nhà Đức Phổ", keyword: "xây nhà Đức Phổ", slug: "xay-nha-duc-pho-geo3-ngan", status: "done" },
  { no: 4716, title: "Xây Nhà Sơn Tịnh", keyword: "xây nhà Sơn Tịnh", slug: "xay-nha-son-tinh-geo3-ngan", status: "done" },
  { no: 4717, title: "Xây Nhà Tư Nghĩa", keyword: "xây nhà Tư Nghĩa", slug: "xay-nha-tu-nghia-geo3-ngan", status: "done" },
  { no: 4718, title: "Cải Tạo Nhà Buôn Ma Thuột", keyword: "cải tạo nhà Buôn Ma Thuột", slug: "cai-tao-nha-bmt-geo3-ngan", status: "done" },
  { no: 4719, title: "Cải Tạo Nhà Pleiku", keyword: "cải tạo nhà Pleiku", slug: "cai-tao-nha-pleiku-geo3-ngan", status: "done" },
  { no: 4720, title: "Cải Tạo Nhà Bảo Lộc", keyword: "cải tạo nhà Bảo Lộc", slug: "cai-tao-nha-bao-loc-geo3-ngan", status: "done" },
  { no: 4721, title: "Cải Tạo Nhà Quy Nhơn", keyword: "cải tạo nhà Quy Nhơn", slug: "cai-tao-nha-quy-nhon-geo3-ngan", status: "done" },
  { no: 4722, title: "Cải Tạo Nhà Hội An", keyword: "cải tạo nhà Hội An", slug: "cai-tao-nha-hoi-an-geo3-ngan", status: "done" },
  { no: 4723, title: "Thiết Kế Nhà Buôn Ma Thuột", keyword: "thiết kế nhà Buôn Ma Thuột", slug: "thiet-ke-nha-bmt-geo3-ngan", status: "done" },
  { no: 4724, title: "Thiết Kế Nhà Pleiku", keyword: "thiết kế nhà Pleiku", slug: "thiet-ke-nha-pleiku-geo3-ngan", status: "done" },
  { no: 4725, title: "Thiết Kế Nhà Bảo Lộc", keyword: "thiết kế nhà Bảo Lộc", slug: "thiet-ke-nha-bao-loc-geo3-ngan", status: "done" },
  { no: 4726, title: "Thiết Kế Nhà Quy Nhơn", keyword: "thiết kế nhà Quy Nhơn", slug: "thiet-ke-nha-quy-nhon-geo3-ngan", status: "done" },
  { no: 4727, title: "Báo Giá Xây Nhà Đắk Lắk", keyword: "báo giá xây nhà Đắk Lắk", slug: "bao-gia-xay-nha-dak-lak-geo3-ngan", status: "done" },
  { no: 4728, title: "Báo Giá Xây Nhà Gia Lai", keyword: "báo giá xây nhà Gia Lai", slug: "bao-gia-xay-nha-gia-lai-geo3-ngan", status: "done" },
  { no: 4729, title: "Báo Giá Xây Nhà Lâm Đồng", keyword: "báo giá xây nhà Lâm Đồng", slug: "bao-gia-xay-nha-lam-dong-geo3-ngan", status: "done" },
  { no: 4730, title: "Báo Giá Xây Nhà Khánh Hòa", keyword: "báo giá xây nhà Khánh Hòa", slug: "bao-gia-xay-nha-khanh-hoa-geo3-ngan", status: "done" },
  { no: 4731, title: "Báo Giá Xây Nhà Bình Định", keyword: "báo giá xây nhà Bình Định", slug: "bao-gia-xay-nha-binh-dinh-geo3-ngan", status: "done" },
  { no: 4732, title: "Nhà Thầu Buôn Ma Thuột", keyword: "nhà thầu Buôn Ma Thuột", slug: "nha-thau-bmt-geo3-ngan", status: "done" },
  { no: 4733, title: "Nhà Thầu Pleiku", keyword: "nhà thầu Pleiku", slug: "nha-thau-pleiku-geo3-ngan", status: "done" },
  { no: 4734, title: "Nhà Thầu Bảo Lộc", keyword: "nhà thầu Bảo Lộc", slug: "nha-thau-bao-loc-geo3-ngan", status: "done" },
  { no: 4735, title: "Nhà Thầu Quy Nhơn", keyword: "nhà thầu Quy Nhơn", slug: "nha-thau-quy-nhon-geo3-ngan", status: "done" },
  { no: 4736, title: "Xây Nhà Cao Nguyên Chống Lạnh", keyword: "xây nhà cao nguyên chống lạnh", slug: "xay-nha-cao-nguyen-chong-lanh-geo3-ngan", status: "done" },
  { no: 4737, title: "Xây Nhà Ven Biển Chống Ăn Mòn", keyword: "xây nhà ven biển chống ăn mòn", slug: "xay-nha-ven-bien-chong-an-mon-geo3-ngan", status: "done" },
  { no: 4738, title: "Xây Nhà Ven Biển Chống Bão", keyword: "xây nhà ven biển chống bão", slug: "xay-nha-ven-bien-chong-bao-geo3-ngan", status: "done" },
  { no: 4739, title: "Xây Biệt Thự Đà Lạt", keyword: "xây biệt thự Đà Lạt", slug: "xay-biet-thu-da-lat-geo3-ngan", status: "done" },
  { no: 4740, title: "Xây Biệt Thự Quy Nhơn", keyword: "xây biệt thự Quy Nhơn", slug: "xay-biet-thu-quy-nhon-geo3-ngan", status: "done" },
  { no: 4741, title: "Xây Homestay Đà Lạt", keyword: "xây homestay Đà Lạt", slug: "xay-homestay-da-lat-geo3-ngan", status: "done" },
  { no: 4742, title: "Xây Homestay Hội An", keyword: "xây homestay Hội An", slug: "xay-homestay-hoi-an-geo3-ngan", status: "done" },
  { no: 4743, title: "Xây Nhà Vườn Tây Nguyên", keyword: "xây nhà vườn Tây Nguyên", slug: "xay-nha-vuon-tay-nguyen-geo3-ngan", status: "done" },
  { no: 4744, title: "Xây Nhà Farmstay Lâm Đồng", keyword: "xây nhà farmstay Lâm Đồng", slug: "xay-nha-farmstay-lam-dong-geo3-ngan", status: "done" },
  { no: 4745, title: "Chủ Đề Mở Rộng 52 1", keyword: "chủ đề mở rộng 52 1", slug: "chu-de-mo-rong-52-1-ngan", status: "done" },
  { no: 4746, title: "Chủ Đề Mở Rộng 52 2", keyword: "chủ đề mở rộng 52 2", slug: "chu-de-mo-rong-52-2-ngan", status: "done" },
];
