/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 17 (#1147–#1246).
 * Cluster: chống thấm/MEP, ngân sách, kinh nghiệm, nâng tầng, geo mở rộng, thương hiệu dịch vụ.
 * Suffix `-ngan` tránh trùng money pages / batch 15–16.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch17: ContentCalendarItem[] = [
  // —— A. Chống thấm & bảo trì (15) #1147–#1161 ——
  { no: 1147, title: "Chống Thấm Mái", keyword: "chống thấm mái", slug: "chong-tham-mai-ngan", status: "done" },
  { no: 1148, title: "Chống Thấm Sân Thượng", keyword: "chống thấm sân thượng", slug: "chong-tham-san-thuong-ngan", status: "done" },
  { no: 1149, title: "Chống Thấm WC", keyword: "chống thấm wc", slug: "chong-tham-wc-ngan", status: "done" },
  { no: 1150, title: "Chống Thấm Tường", keyword: "chống thấm tường", slug: "chong-tham-tuong-ngan", status: "done" },
  { no: 1151, title: "Chống Thấm Trần", keyword: "chống thấm trần", slug: "chong-tham-tran-ngan", status: "done" },
  { no: 1152, title: "Xử Lý Thấm Dột", keyword: "xử lý thấm dột", slug: "xu-ly-tham-dot-ngan", status: "done" },
  { no: 1153, title: "Sửa Nhà Thấm Nước", keyword: "sửa nhà thấm nước", slug: "sua-nha-tham-nuoc-ngan", status: "done" },
  { no: 1154, title: "Bảo Trì Nhà Phố", keyword: "bảo trì nhà phố", slug: "bao-tri-nha-pho-ngan", status: "done" },
  { no: 1155, title: "Bảo Dưỡng Nhà", keyword: "bảo dưỡng nhà", slug: "bao-duong-nha-ngan", status: "done" },
  { no: 1156, title: "Sơn Chống Thấm", keyword: "sơn chống thấm", slug: "son-chong-tham-ngan", status: "done" },
  { no: 1157, title: "Chống Thấm Ngược", keyword: "chống thấm ngược", slug: "chong-tham-nguoc-ngan", status: "done" },
  { no: 1158, title: "Chống Thấm Hồ Cá", keyword: "chống thấm hồ cá", slug: "chong-tham-ho-ca-ngan", status: "done" },
  { no: 1159, title: "Chống Thấm Bể Nước", keyword: "chống thấm bể nước", slug: "chong-tham-be-nuoc-ngan", status: "done" },
  { no: 1160, title: "Xử Lý Nứt Tường", keyword: "xử lý nứt tường", slug: "xu-ly-nut-tuong-ngan", status: "done" },
  { no: 1161, title: "Xử Lý Nứt Trần", keyword: "xử lý nứt trần", slug: "xu-ly-nut-tran-ngan", status: "done" },

  // —— B. Điện nước / MEP (15) #1162–#1176 ——
  { no: 1162, title: "Hệ Thống Điện Nhà", keyword: "hệ thống điện nhà", slug: "he-thong-dien-nha-ngan", status: "done" },
  { no: 1163, title: "Hệ Thống Nước Nhà", keyword: "hệ thống nước nhà", slug: "he-thong-nuoc-nha-ngan", status: "done" },
  { no: 1164, title: "Điện Nước Nhà Phố", keyword: "điện nước nhà phố", slug: "dien-nuoc-nha-pho-ngan", status: "done" },
  { no: 1165, title: "Lắp Đặt Điện Nhà", keyword: "lắp đặt điện nhà", slug: "lap-dat-dien-nha-ngan", status: "done" },
  { no: 1166, title: "Lắp Đặt Nước Nhà", keyword: "lắp đặt nước nhà", slug: "lap-dat-nuoc-nha-ngan", status: "done" },
  { no: 1167, title: "Sửa Ống Nước", keyword: "sửa ống nước", slug: "sua-ong-nuoc-ngan", status: "done" },
  { no: 1168, title: "Thay Đường Ống Nước", keyword: "thay đường ống nước", slug: "thay-duong-ong-nuoc-ngan", status: "done" },
  { no: 1169, title: "Bơm Nước Nhà", keyword: "bơm nước nhà", slug: "bom-nuoc-nha-ngan", status: "done" },
  { no: 1170, title: "Bình Nóng Lạnh Nhà", keyword: "bình nóng lạnh nhà", slug: "binh-nong-lanh-nha-ngan", status: "done" },
  { no: 1171, title: "Máy Lạnh Nhà Phố", keyword: "máy lạnh nhà phố", slug: "may-lanh-nha-pho-ngan", status: "done" },
  { no: 1172, title: "Thông Gió Nhà", keyword: "thông gió nhà", slug: "thong-gio-nha-ngan", status: "done" },
  { no: 1173, title: "Hút Mùi Bếp", keyword: "hút mùi bếp", slug: "hut-mui-bep-ngan", status: "done" },
  { no: 1174, title: "Camera Nhà Phố", keyword: "camera nhà phố", slug: "camera-nha-pho-ngan", status: "done" },
  { no: 1175, title: "Khóa Cổng Điện Tử", keyword: "khóa cổng điện tử", slug: "khoa-cong-dien-tu-ngan", status: "done" },
  { no: 1176, title: "Hệ Thống PCCC Nhà", keyword: "hệ thống pccc nhà", slug: "he-thong-pccc-nha-ngan", status: "done" },

  // —— C. Ngân sách & quy mô (15) #1177–#1191 ——
  { no: 1177, title: "Xây Nhà 500 Triệu", keyword: "xây nhà 500 triệu", slug: "xay-nha-500-trieu-ngan", status: "done" },
  { no: 1178, title: "Xây Nhà 800 Triệu", keyword: "xây nhà 800 triệu", slug: "xay-nha-800-trieu-ngan", status: "done" },
  { no: 1179, title: "Xây Nhà 1 Tỷ", keyword: "xây nhà 1 tỷ", slug: "xay-nha-1-ty-ngan", status: "done" },
  { no: 1180, title: "Xây Nhà 1 Tỷ 5", keyword: "xây nhà 1 tỷ 5", slug: "xay-nha-1-ty-5-ngan", status: "done" },
  { no: 1181, title: "Xây Nhà 2 Tỷ", keyword: "xây nhà 2 tỷ", slug: "xay-nha-2-ty-ngan", status: "done" },
  { no: 1182, title: "Xây Nhà 3 Tỷ", keyword: "xây nhà 3 tỷ", slug: "xay-nha-3-ty-ngan", status: "done" },
  { no: 1183, title: "Xây Nhà Diện Tích Nhỏ", keyword: "xây nhà diện tích nhỏ", slug: "xay-nha-dien-tich-nho-ngan", status: "done" },
  { no: 1184, title: "Xây Nhà 40m2", keyword: "xây nhà 40m2", slug: "xay-nha-40m2-ngan", status: "done" },
  { no: 1185, title: "Xây Nhà 50m2", keyword: "xây nhà 50m2", slug: "xay-nha-50m2-ngan", status: "done" },
  { no: 1186, title: "Xây Nhà 60m2", keyword: "xây nhà 60m2", slug: "xay-nha-60m2-ngan", status: "done" },
  { no: 1187, title: "Xây Nhà 80m2", keyword: "xây nhà 80m2", slug: "xay-nha-80m2-ngan", status: "done" },
  { no: 1188, title: "Xây Nhà 100m2", keyword: "xây nhà 100m2", slug: "xay-nha-100m2-ngan", status: "done" },
  { no: 1189, title: "Chi Phí Xây Nhà Phố", keyword: "chi phí xây nhà phố", slug: "chi-phi-xay-nha-pho-ngan", status: "done" },
  { no: 1190, title: "Chi Phí Xây Biệt Thự", keyword: "chi phí xây biệt thự", slug: "chi-phi-xay-biet-thu-ngan", status: "done" },
  { no: 1191, title: "Ngân Sách Xây Nhà", keyword: "ngân sách xây nhà", slug: "ngan-sach-xay-nha-ngan", status: "done" },

  // —— D. Nâng tầng / cơi nới (15) #1192–#1206 ——
  { no: 1192, title: "Nâng Tầng Nhà Phố", keyword: "nâng tầng nhà phố", slug: "nang-tang-nha-pho-ngan", status: "done" },
  { no: 1193, title: "Nâng Thêm 1 Tầng", keyword: "nâng thêm 1 tầng", slug: "nang-them-1-tang-ngan", status: "done" },
  { no: 1194, title: "Nâng Thêm 2 Tầng", keyword: "nâng thêm 2 tầng", slug: "nang-them-2-tang-ngan", status: "done" },
  { no: 1195, title: "Cơi Nới Nhà", keyword: "cơi nới nhà", slug: "coi-noi-nha-ngan", status: "done" },
  { no: 1196, title: "Cơi Nới Nhà Phố", keyword: "cơi nới nhà phố", slug: "coi-noi-nha-pho-ngan", status: "done" },
  { no: 1197, title: "Xây Thêm Tầng", keyword: "xây thêm tầng", slug: "xay-them-tang-ngan", status: "done" },
  { no: 1198, title: "Xây Thêm Lầu", keyword: "xây thêm lầu", slug: "xay-them-lau-ngan", status: "done" },
  { no: 1199, title: "Gia Cố Trước Nâng Tầng", keyword: "gia cố trước nâng tầng", slug: "gia-co-truoc-nang-tang-ngan", status: "done" },
  { no: 1200, title: "Chi Phí Nâng Tầng", keyword: "chi phí nâng tầng", slug: "chi-phi-nang-tang-ngan", status: "done" },
  { no: 1201, title: "Báo Giá Nâng Tầng", keyword: "báo giá nâng tầng", slug: "bao-gia-nang-tang-ngan", status: "done" },
  { no: 1202, title: "Nâng Tầng Nhà Cũ", keyword: "nâng tầng nhà cũ", slug: "nang-tang-nha-cu-ngan", status: "done" },
  { no: 1203, title: "Nâng Tầng An Toàn", keyword: "nâng tầng an toàn", slug: "nang-tang-an-toan-ngan", status: "done" },
  { no: 1204, title: "Cải Tạo Nâng Tầng", keyword: "cải tạo nâng tầng", slug: "cai-tao-nang-tang-ngan", status: "done" },
  { no: 1205, title: "Xin Phép Nâng Tầng", keyword: "xin phép nâng tầng", slug: "xin-phep-nang-tang-ngan", status: "done" },
  { no: 1206, title: "Thi Công Nâng Tầng", keyword: "thi công nâng tầng", slug: "thi-cong-nang-tang-ngan", status: "done" },

  // —— E. Geo mở rộng (20) #1207–#1226 ——
  { no: 1207, title: "Xây Nhà Quận 1", keyword: "xây nhà Quận 1", slug: "xay-nha-quan-1-ngan", status: "done" },
  { no: 1208, title: "Xây Nhà Quận 3", keyword: "xây nhà Quận 3", slug: "xay-nha-quan-3-ngan", status: "done" },
  { no: 1209, title: "Xây Nhà Quận 10", keyword: "xây nhà Quận 10", slug: "xay-nha-quan-10-ngan", status: "done" },
  { no: 1210, title: "Xây Nhà Phú Nhuận", keyword: "xây nhà Phú Nhuận", slug: "xay-nha-phu-nhuan-ngan", status: "done" },
  { no: 1211, title: "Xây Nhà Bình Tân", keyword: "xây nhà Bình Tân", slug: "xay-nha-binh-tan-ngan", status: "done" },
  { no: 1212, title: "Xây Nhà Củ Chi", keyword: "xây nhà Củ Chi", slug: "xay-nha-cu-chi-ngan", status: "done" },
  { no: 1213, title: "Xây Nhà Cần Giờ", keyword: "xây nhà Cần Giờ", slug: "xay-nha-can-gio-ngan", status: "done" },
  { no: 1214, title: "Xây Nhà Phú Yên", keyword: "xây nhà Phú Yên", slug: "xay-nha-phu-yen-ngan", status: "done" },
  { no: 1215, title: "Xây Nhà Tuy Hòa", keyword: "xây nhà Tuy Hòa", slug: "xay-nha-tuy-hoa-ngan", status: "done" },
  { no: 1216, title: "Xây Nhà Đắk Lắk", keyword: "xây nhà Đắk Lắk", slug: "xay-nha-dak-lak-ngan", status: "done" },
  { no: 1217, title: "Sửa Nhà Quận 7", keyword: "sửa nhà Quận 7", slug: "sua-nha-quan-7-ngan", status: "done" },
  { no: 1218, title: "Sửa Nhà Thủ Đức", keyword: "sửa nhà Thủ Đức", slug: "sua-nha-thu-duc-ngan", status: "done" },
  { no: 1219, title: "Sửa Nhà Tân Bình", keyword: "sửa nhà Tân Bình", slug: "sua-nha-tan-binh-ngan", status: "done" },
  { no: 1220, title: "Cải Tạo Nhà Gò Vấp", keyword: "cải tạo nhà Gò Vấp", slug: "cai-tao-nha-go-vap-ngan", status: "done" },
  { no: 1221, title: "Cải Tạo Nhà Bình Thạnh", keyword: "cải tạo nhà Bình Thạnh", slug: "cai-tao-nha-binh-thanh-ngan", status: "done" },
  { no: 1222, title: "Cải Tạo Nhà Tân Phú", keyword: "cải tạo nhà Tân Phú", slug: "cai-tao-nha-tan-phu-ngan", status: "done" },
  { no: 1223, title: "Xây Nhà Trọn Gói Quận 7", keyword: "xây nhà trọn gói Quận 7", slug: "xay-nha-tron-goi-quan-7-ngan", status: "done" },
  { no: 1224, title: "Xây Nhà Trọn Gói Gò Vấp", keyword: "xây nhà trọn gói Gò Vấp", slug: "xay-nha-tron-goi-go-vap-ngan", status: "done" },
  { no: 1225, title: "Xây Nhà Trọn Gói Bình Dương", keyword: "xây nhà trọn gói Bình Dương", slug: "xay-nha-tron-goi-binh-duong-ngan", status: "done" },
  { no: 1226, title: "Xây Nhà Trọn Gói Đồng Nai", keyword: "xây nhà trọn gói Đồng Nai", slug: "xay-nha-tron-goi-dong-nai-ngan", status: "done" },

  // —— F. Kinh nghiệm & chọn thầu (20) #1227–#1246 ——
  { no: 1227, title: "Kinh Nghiệm Xây Nhà", keyword: "kinh nghiệm xây nhà", slug: "kinh-nghiem-xay-nha-ngan", status: "done" },
  { no: 1228, title: "Kinh Nghiệm Cải Tạo Nhà", keyword: "kinh nghiệm cải tạo nhà", slug: "kinh-nghiem-cai-tao-nha-ngan", status: "done" },
  { no: 1229, title: "Kinh Nghiệm Sửa Nhà", keyword: "kinh nghiệm sửa nhà", slug: "kinh-nghiem-sua-nha-ngan", status: "done" },
  { no: 1230, title: "Cách Chọn Nhà Thầu", keyword: "cách chọn nhà thầu", slug: "cach-chon-nha-thau-ngan", status: "done" },
  { no: 1231, title: "Chọn Thầu Xây Nhà", keyword: "chọn thầu xây nhà", slug: "chon-thau-xay-nha-ngan", status: "done" },
  { no: 1232, title: "Hợp Đồng Xây Nhà", keyword: "hợp đồng xây nhà", slug: "hop-dong-xay-nha-ngan", status: "done" },
  { no: 1233, title: "Hợp Đồng Thi Công", keyword: "hợp đồng thi công", slug: "hop-dong-thi-cong-ngan", status: "done" },
  { no: 1234, title: "Nghiệm Thu Xây Nhà", keyword: "nghiệm thu xây nhà", slug: "nghiem-thu-xay-nha-ngan", status: "done" },
  { no: 1235, title: "Giám Sát Thi Công", keyword: "giám sát thi công", slug: "giam-sat-thi-cong-ngan", status: "done" },
  { no: 1236, title: "Nhật Ký Công Trình", keyword: "nhật ký công trình", slug: "nhat-ky-cong-trinh-ngan", status: "done" },
  { no: 1237, title: "Vật Tư Xây Nhà", keyword: "vật tư xây nhà", slug: "vat-tu-xay-nha-ngan", status: "done" },
  { no: 1238, title: "Chọn Vật Liệu Xây Nhà", keyword: "chọn vật liệu xây nhà", slug: "chon-vat-lieu-xay-nha-ngan", status: "done" },
  { no: 1239, title: "Xây Nhà Tiết Kiệm", keyword: "xây nhà tiết kiệm", slug: "xay-nha-tiet-kiem-ngan", status: "done" },
  { no: 1240, title: "Xây Nhà An Toàn", keyword: "xây nhà an toàn", slug: "xay-nha-an-toan-ngan", status: "done" },
  { no: 1241, title: "Xây Nhà Bền Đẹp", keyword: "xây nhà bền đẹp", slug: "xay-nha-ben-dep-ngan", status: "done" },
  { no: 1242, title: "Thi Công Chuyên Nghiệp", keyword: "thi công chuyên nghiệp", slug: "thi-cong-chuyen-nghiep-ngan", status: "done" },
  { no: 1243, title: "Đội Thi Công Nhà", keyword: "đội thi công nhà", slug: "doi-thi-cong-nha-ngan", status: "done" },
  { no: 1244, title: "Nhà Thầu Trực Tiếp", keyword: "nhà thầu trực tiếp", slug: "nha-thau-truc-tiep-ngan", status: "done" },
  { no: 1245, title: "Không Bán Thầu", keyword: "không bán thầu", slug: "khong-ban-thau-ngan", status: "done" },
  { no: 1246, title: "Bảo Hành Xây Nhà", keyword: "bảo hành xây nhà", slug: "bao-hanh-xay-nha-ngan", status: "done" },
];
