/**
 * Lịch 100 từ khóa ngắn — batch 50 (#4447–#4546).
 * Cluster: kết cấu, móng, gia cố chuyên sâu.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch50: ContentCalendarItem[] = [
  { no: 4447, title: "Móng Băng Nhà Phố", keyword: "móng băng nhà phố", slug: "mong-bang-nha-pho-kc-ngan", status: "done" },
  { no: 4448, title: "Móng Đơn Nhà Phố", keyword: "móng đơn nhà phố", slug: "mong-don-nha-pho-kc-ngan", status: "done" },
  { no: 4449, title: "Móng Bè Nhà Phố", keyword: "móng bè nhà phố", slug: "mong-be-nha-pho-kc-ngan", status: "done" },
  { no: 4450, title: "Móng Cọc Nhà Phố", keyword: "móng cọc nhà phố", slug: "mong-coc-nha-pho-kc-ngan", status: "done" },
  { no: 4451, title: "Đài Móng Nhà Phố", keyword: "đài móng nhà phố", slug: "dai-mong-nha-pho-kc-ngan", status: "done" },
  { no: 4452, title: "Giằng Móng Nhà Phố", keyword: "giằng móng nhà phố", slug: "giang-mong-nha-pho-kc-ngan", status: "done" },
  { no: 4453, title: "Cọc Ép Bê Tông 200", keyword: "cọc ép bê tông 200", slug: "coc-ep-be-tong-200-kc-ngan", status: "done" },
  { no: 4454, title: "Cọc Ép Bê Tông 250", keyword: "cọc ép bê tông 250", slug: "coc-ep-be-tong-250-kc-ngan", status: "done" },
  { no: 4455, title: "Cọc Ép Bê Tông 300", keyword: "cọc ép bê tông 300", slug: "coc-ep-be-tong-300-kc-ngan", status: "done" },
  { no: 4456, title: "Cọc Khoan Nhồi D300", keyword: "cọc khoan nhồi d300", slug: "coc-khoan-nhoi-d300-kc-ngan", status: "done" },
  { no: 4457, title: "Cọc Khoan Nhồi D400", keyword: "cọc khoan nhồi d400", slug: "coc-khoan-nhoi-d400-kc-ngan", status: "done" },
  { no: 4458, title: "Cọc Tre Gia Cố Nền", keyword: "cọc tre gia cố nền", slug: "coc-tre-gia-co-nen-kc-ngan", status: "done" },
  { no: 4459, title: "Cọc Xi Măng Đất", keyword: "cọc xi măng đất", slug: "coc-xi-mang-dat-kc-ngan", status: "done" },
  { no: 4460, title: "Khảo Sát Địa Chất Nhà Phố", keyword: "khảo sát địa chất nhà phố", slug: "khao-sat-dia-chat-nha-pho-kc-ngan", status: "done" },
  { no: 4461, title: "Báo Cáo Địa Chất Xây Nhà", keyword: "báo cáo địa chất xây nhà", slug: "bao-cao-dia-chat-xay-nha-kc-ngan", status: "done" },
  { no: 4462, title: "Đất Yếu Xây Nhà", keyword: "đất yếu xây nhà", slug: "dat-yeu-xay-nha-kc-ngan", status: "done" },
  { no: 4463, title: "Đất Sét Xây Nhà", keyword: "đất sét xây nhà", slug: "dat-set-xay-nha-kc-ngan", status: "done" },
  { no: 4464, title: "Đất Cát Xây Nhà", keyword: "đất cát xây nhà", slug: "dat-cat-xay-nha-kc-ngan", status: "done" },
  { no: 4465, title: "Mực Nước Ngầm Công Trình", keyword: "mực nước ngầm công trình", slug: "muc-nuoc-ngam-cong-trinh-kc-ngan", status: "done" },
  { no: 4466, title: "Chống Thấm Hầm Móng", keyword: "chống thấm hầm móng", slug: "chong-tham-ham-mong-kc-ngan", status: "done" },
  { no: 4467, title: "Cột Bê Tông Cốt Thép", keyword: "cột bê tông cốt thép", slug: "cot-be-tong-cot-thep-kc-ngan", status: "done" },
  { no: 4468, title: "Dầm Bê Tông Cốt Thép", keyword: "dầm bê tông cốt thép", slug: "dam-be-tong-cot-thep-kc-ngan", status: "done" },
  { no: 4469, title: "Sàn Bê Tông Cốt Thép", keyword: "sàn bê tông cốt thép", slug: "san-be-tong-cot-thep-kc-ngan", status: "done" },
  { no: 4470, title: "Sàn Phẳng Không Dầm", keyword: "sàn phẳng không dầm", slug: "san-phang-khong-dam-kc-ngan", status: "done" },
  { no: 4471, title: "Sàn Dự Ứng Lực Nhà Phố", keyword: "sàn dự ứng lực nhà phố", slug: "san-du-ung-luc-nha-pho-kc-ngan", status: "done" },
  { no: 4472, title: "Sàn Bubble Deck", keyword: "sàn bubble deck", slug: "san-bubble-deck-kc-ngan", status: "done" },
  { no: 4473, title: "Vách Chịu Lực Nhà Phố", keyword: "vách chịu lực nhà phố", slug: "vach-chiu-luc-nha-pho-kc-ngan", status: "done" },
  { no: 4474, title: "Lõi Thang Nhà Phố", keyword: "lõi thang nhà phố", slug: "loi-thang-nha-pho-kc-ngan", status: "done" },
  { no: 4475, title: "Khung Thép Nhà Phố", keyword: "khung thép nhà phố", slug: "khung-thep-nha-pho-kc-ngan", status: "done" },
  { no: 4476, title: "Khung Thép Nhẹ LSF", keyword: "khung thép nhẹ lsf", slug: "khung-thep-nhe-lsf-kc-ngan", status: "done" },
  { no: 4477, title: "Liên Kết Thép Bê Tông", keyword: "liên kết thép bê tông", slug: "lien-ket-thep-be-tong-kc-ngan", status: "done" },
  { no: 4478, title: "Neo Thép Cột Dầm", keyword: "neo thép cột dầm", slug: "neo-thep-cot-dam-kc-ngan", status: "done" },
  { no: 4479, title: "Thép Chờ Nâng Tầng", keyword: "thép chờ nâng tầng", slug: "thep-cho-nang-tang-kc-ngan", status: "done" },
  { no: 4480, title: "Gia Cố Kết Cấu Nhà Cũ", keyword: "gia cố kết cấu nhà cũ", slug: "gia-co-ket-cau-nha-cu-kc-ngan", status: "done" },
  { no: 4481, title: "Gia Cố Cột Bằng Carbon", keyword: "gia cố cột bằng carbon", slug: "gia-co-cot-bang-carbon-kc-ngan", status: "done" },
  { no: 4482, title: "Gia Cố Dầm Bằng Thép", keyword: "gia cố dầm bằng thép", slug: "gia-co-dam-bang-thep-kc-ngan", status: "done" },
  { no: 4483, title: "Gia Cố Sàn Bằng CFRP", keyword: "gia cố sàn bằng cfrp", slug: "gia-co-san-bang-cfrp-kc-ngan", status: "done" },
  { no: 4484, title: "Jacketing Cột Nhà Cũ", keyword: "jacketing cột nhà cũ", slug: "jacketing-cot-nha-cu-kc-ngan", status: "done" },
  { no: 4485, title: "Underpinning Móng Nhà", keyword: "underpinning móng nhà", slug: "underpinning-mong-nha-kc-ngan", status: "done" },
  { no: 4486, title: "Micropile Gia Cố Móng", keyword: "micropile gia cố móng", slug: "micropile-gia-co-mong-kc-ngan", status: "done" },
  { no: 4487, title: "Kiểm Định Kết Cấu Nhà", keyword: "kiểm định kết cấu nhà", slug: "kiem-dinh-ket-cau-nha-kc-ngan", status: "done" },
  { no: 4488, title: "Đánh Giá An Toàn Kết Cấu", keyword: "đánh giá an toàn kết cấu", slug: "danh-gia-an-toan-ket-cau-kc-ngan", status: "done" },
  { no: 4489, title: "Tính Toán Kết Cấu Nhà Phố", keyword: "tính toán kết cấu nhà phố", slug: "tinh-toan-ket-cau-nha-pho-kc-ngan", status: "done" },
  { no: 4490, title: "Phần Mềm Kết Cấu Nhà", keyword: "phần mềm kết cấu nhà", slug: "phan-mem-ket-cau-nha-kc-ngan", status: "done" },
  { no: 4491, title: "Bản Vẽ Kết Cấu Chi Tiết", keyword: "bản vẽ kết cấu chi tiết", slug: "ban-ve-ket-cau-chi-tiet-kc-ngan", status: "done" },
  { no: 4492, title: "Mác Bê Tông Móng", keyword: "mác bê tông móng", slug: "mac-be-tong-mong-kc-ngan", status: "done" },
  { no: 4493, title: "Mác Bê Tông Cột", keyword: "mác bê tông cột", slug: "mac-be-tong-cot-kc-ngan", status: "done" },
  { no: 4494, title: "Mác Bê Tông Sàn", keyword: "mác bê tông sàn", slug: "mac-be-tong-san-kc-ngan", status: "done" },
  { no: 4495, title: "Thép CB300 V Và CB400 V", keyword: "thép cb300v và cb400v", slug: "thep-cb300v-va-cb400v-kc-ngan", status: "done" },
  { no: 4496, title: "Đường Kính Thép Cột", keyword: "đường kính thép cột", slug: "duong-kinh-thep-cot-kc-ngan", status: "done" },
  { no: 4497, title: "Khoảng Cách Thép Sàn", keyword: "khoảng cách thép sàn", slug: "khoang-cach-thep-san-kc-ngan", status: "done" },
  { no: 4498, title: "Lớp Bảo Vệ Bê Tông", keyword: "lớp bảo vệ bê tông", slug: "lop-bao-ve-be-tong-kc-ngan", status: "done" },
  { no: 4499, title: "Chống Ăn Mòn Cốt Thép", keyword: "chống ăn mòn cốt thép", slug: "chong-an-mon-cot-thep-kc-ngan", status: "done" },
  { no: 4500, title: "Rạn Nứt Bê Tông Cho Phép", keyword: "rạn nứt bê tông cho phép", slug: "ran-nut-be-tong-cho-phep-kc-ngan", status: "done" },
  { no: 4501, title: "Võng Sàn Cho Phép", keyword: "võng sàn cho phép", slug: "vong-san-cho-phep-kc-ngan", status: "done" },
  { no: 4502, title: "Độ Nghiêng Nhà Cho Phép", keyword: "độ nghiêng nhà cho phép", slug: "do-nghieng-nha-cho-phep-kc-ngan", status: "done" },
  { no: 4503, title: "Lún Cho Phép Nhà Phố", keyword: "lún cho phép nhà phố", slug: "lun-cho-phep-nha-pho-kc-ngan", status: "done" },
  { no: 4504, title: "Chống Động Đất Nhà Phố", keyword: "chống động đất nhà phố", slug: "chong-dong-dat-nha-pho-kc-ngan", status: "done" },
  { no: 4505, title: "Chống Gió Bão Kết Cấu", keyword: "chống gió bão kết cấu", slug: "chong-gio-bao-ket-cau-kc-ngan", status: "done" },
  { no: 4506, title: "Tường Chịu Lực Hay Chèn", keyword: "tường chịu lực hay chèn", slug: "tuong-chiu-luc-hay-chen-kc-ngan", status: "done" },
  { no: 4507, title: "Tường Xây Không Chịu Lực", keyword: "tường xây không chịu lực", slug: "tuong-xay-khong-chiu-luc-kc-ngan", status: "done" },
  { no: 4508, title: "Lintel Cửa Sổ Cửa Đi", keyword: "lintel cửa sổ cửa đi", slug: "lintel-cua-so-cua-di-kc-ngan", status: "done" },
  { no: 4509, title: "Giằng Tường Nhà Phố", keyword: "giằng tường nhà phố", slug: "giang-tuong-nha-pho-kc-ngan", status: "done" },
  { no: 4510, title: "Mái BTCT Nhà Phố", keyword: "mái btct nhà phố", slug: "mai-btct-nha-pho-kc-ngan", status: "done" },
  { no: 4511, title: "Mái Khung Thép Tôn", keyword: "mái khung thép tôn", slug: "mai-khung-thep-ton-kc-ngan", status: "done" },
  { no: 4512, title: "Kèo Thép Nhà Phố", keyword: "kèo thép nhà phố", slug: "keo-thep-nha-pho-kc-ngan", status: "done" },
  { no: 4513, title: "Xà Gồ Mái Tôn", keyword: "xà gồ mái tôn", slug: "xa-go-mai-ton-kc-ngan", status: "done" },
  { no: 4514, title: "Chống Nóng Kết Cấu Mái", keyword: "chống nóng kết cấu mái", slug: "chong-nong-ket-cau-mai-kc-ngan", status: "done" },
  { no: 4515, title: "Báo Giá Ép Cọc Nhà Phố", keyword: "báo giá ép cọc nhà phố", slug: "bao-gia-ep-coc-nha-pho-kc-ngan", status: "done" },
  { no: 4516, title: "Báo Giá Khoan Cọc Nhồi", keyword: "báo giá khoan cọc nhồi", slug: "bao-gia-khoan-coc-nhoi-kc-ngan", status: "done" },
  { no: 4517, title: "Báo Giá Gia Cố Kết Cấu", keyword: "báo giá gia cố kết cấu", slug: "bao-gia-gia-co-ket-cau-kc-ngan", status: "done" },
  { no: 4518, title: "Báo Giá Kiểm Định Nhà", keyword: "báo giá kiểm định nhà", slug: "bao-gia-kiem-dinh-nha-kc-ngan", status: "done" },
  { no: 4519, title: "Chi Phí Móng Nhà 4 Tầng", keyword: "chi phí móng nhà 4 tầng", slug: "chi-phi-mong-nha-4-tang-kc-ngan", status: "done" },
  { no: 4520, title: "Chi Phí Móng Nhà 5 Tầng", keyword: "chi phí móng nhà 5 tầng", slug: "chi-phi-mong-nha-5-tang-kc-ngan", status: "done" },
  { no: 4521, title: "Số Lượng Cọc Nhà Ống", keyword: "số lượng cọc nhà ống", slug: "so-luong-coc-nha-ong-kc-ngan", status: "done" },
  { no: 4522, title: "Chiều Dài Cọc Nhà Phố", keyword: "chiều dài cọc nhà phố", slug: "chieu-dai-coc-nha-pho-kc-ngan", status: "done" },
  { no: 4523, title: "Nghiệm Thu Ép Cọc", keyword: "nghiệm thu ép cọc", slug: "nghiem-thu-ep-coc-kc-ngan", status: "done" },
  { no: 4524, title: "Nghiệm Thu Khoan Nhồi", keyword: "nghiệm thu khoan nhồi", slug: "nghiem-thu-khoan-nhoi-kc-ngan", status: "done" },
  { no: 4525, title: "Thử Tải Cọc Nhà Phố", keyword: "thử tải cọc nhà phố", slug: "thu-tai-coc-nha-pho-kc-ngan", status: "done" },
  { no: 4526, title: "Biên Bản Nghiệm Thu Kết Cấu", keyword: "biên bản nghiệm thu kết cấu", slug: "bien-ban-nghiem-thu-ket-cau-kc-ngan", status: "done" },
  { no: 4527, title: "Sai Lầm Kết Cấu Thường Gặp", keyword: "sai lầm kết cấu thường gặp", slug: "sai-lam-ket-cau-thuong-gap-kc-ngan", status: "done" },
  { no: 4528, title: "Dấu Hiệu Kết Cấu Yếu", keyword: "dấu hiệu kết cấu yếu", slug: "dau-hieu-ket-cau-yeu-kc-ngan", status: "done" },
  { no: 4529, title: "Khi Nào Cần Gia Cố Nhà", keyword: "khi nào cần gia cố nhà", slug: "khi-nao-can-gia-co-nha-kc-ngan", status: "done" },
  { no: 4530, title: "Nâng Tầng Có Cần Gia Cố", keyword: "nâng tầng có cần gia cố", slug: "nang-tang-co-can-gia-co-kc-ngan", status: "done" },
  { no: 4531, title: "Phá Dỡ Có Ảnh Hưởng Kết Cấu", keyword: "phá dỡ có ảnh hưởng kết cấu", slug: "pha-do-co-anh-huong-ket-cau-kc-ngan", status: "done" },
  { no: 4532, title: "Kết Cấu Nhà Lệch Tầng", keyword: "kết cấu nhà lệch tầng", slug: "ket-cau-nha-lech-tang-kc-ngan", status: "done" },
  { no: 4533, title: "Kết Cấu Nhà Thông Tầng", keyword: "kết cấu nhà thông tầng", slug: "ket-cau-nha-thong-tang-kc-ngan", status: "done" },
  { no: 4534, title: "Kết Cấu Console Ban Công", keyword: "kết cấu console ban công", slug: "ket-cau-console-ban-cong-kc-ngan", status: "done" },
  { no: 4535, title: "Kết Cấu Sân Thượng", keyword: "kết cấu sân thượng", slug: "ket-cau-san-thuong-kc-ngan", status: "done" },
  { no: 4536, title: "Kết Cấu Bể Bơi Trên Mái", keyword: "kết cấu bể bơi trên mái", slug: "ket-cau-be-boi-tren-mai-kc-ngan", status: "done" },
  { no: 4537, title: "Kết Cấu Thang Máy Mini", keyword: "kết cấu thang máy mini", slug: "ket-cau-thang-may-mini-kc-ngan", status: "done" },
  { no: 4538, title: "Xu Hướng Kết Cấu 2026", keyword: "xu hướng kết cấu 2026", slug: "xu-huong-ket-cau-2026-kc-ngan", status: "done" },
  { no: 4539, title: "Kết Cấu Xanh Nhà Phố", keyword: "kết cấu xanh nhà phố", slug: "ket-cau-xanh-nha-pho-kc-ngan", status: "done" },
  { no: 4540, title: "Kết Cấu Prefab Nhà Ở", keyword: "kết cấu prefab nhà ở", slug: "ket-cau-prefab-nha-o-kc-ngan", status: "done" },
  { no: 4541, title: "Kết Cấu Modular Nhà", keyword: "kết cấu modular nhà", slug: "ket-cau-modular-nha-kc-ngan", status: "done" },
  { no: 4542, title: "Checklist Kết Cấu Trước Đổ", keyword: "checklist kết cấu trước đổ", slug: "checklist-ket-cau-truoc-do-kc-ngan", status: "done" },
  { no: 4543, title: "Checklist Kết Cấu Nghiệm Thu", keyword: "checklist kết cấu nghiệm thu", slug: "checklist-ket-cau-nghiem-thu-kc-ngan", status: "done" },
  { no: 4544, title: "Chủ Đề Mở Rộng 50 1", keyword: "chủ đề mở rộng 50 1", slug: "chu-de-mo-rong-50-1-ngan", status: "done" },
  { no: 4545, title: "Chủ Đề Mở Rộng 50 2", keyword: "chủ đề mở rộng 50 2", slug: "chu-de-mo-rong-50-2-ngan", status: "done" },
  { no: 4546, title: "Chủ Đề Mở Rộng 50 3", keyword: "chủ đề mở rộng 50 3", slug: "chu-de-mo-rong-50-3-ngan", status: "done" },
];
