/**
 * Lịch 100 từ khóa SEO — batch 68 (#6247–#6346).
 * Cluster: Phú Nhuận/Tân Bình/Tân Phú + MEP + biệt thự/nhà vườn (indexable *-sk68).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch68: ContentCalendarItem[] = [
  { no: 6247, title: "Xây Nhà Trọn Gói Phú Nhuận 2026", keyword: "xây nhà trọn gói Phú Nhuận 2026", slug: "xay-nha-tron-goi-phu-nhuan-2026-sk68", status: "done" },
  { no: 6248, title: "Xây Nhà Trọn Gói Tân Bình 2026", keyword: "xây nhà trọn gói Tân Bình 2026", slug: "xay-nha-tron-goi-tan-binh-2026-sk68", status: "done" },
  { no: 6249, title: "Xây Nhà Trọn Gói Tân Phú 2026", keyword: "xây nhà trọn gói Tân Phú 2026", slug: "xay-nha-tron-goi-tan-phu-2026-sk68", status: "done" },
  { no: 6250, title: "Xây Nhà Trọn Gói Bình Tân 2026", keyword: "xây nhà trọn gói Bình Tân 2026", slug: "xay-nha-tron-goi-binh-tan-2026-sk68", status: "done" },
  { no: 6251, title: "Xây Nhà Phường 1 Phú Nhuận", keyword: "xây nhà phường 1 Phú Nhuận", slug: "xay-nha-phuong-1-phu-nhuan-sk68", status: "done" },
  { no: 6252, title: "Xây Nhà Phường 2 Phú Nhuận", keyword: "xây nhà phường 2 Phú Nhuận", slug: "xay-nha-phuong-2-phu-nhuan-sk68", status: "done" },
  { no: 6253, title: "Xây Nhà Phường 5 Phú Nhuận", keyword: "xây nhà phường 5 Phú Nhuận", slug: "xay-nha-phuong-5-phu-nhuan-sk68", status: "done" },
  { no: 6254, title: "Xây Nhà Phường 7 Tân Bình", keyword: "xây nhà phường 7 Tân Bình", slug: "xay-nha-phuong-7-tan-binh-sk68", status: "done" },
  { no: 6255, title: "Xây Nhà Phường 11 Tân Bình", keyword: "xây nhà phường 11 Tân Bình", slug: "xay-nha-phuong-11-tan-binh-sk68", status: "done" },
  { no: 6256, title: "Xây Nhà Phường 13 Tân Bình", keyword: "xây nhà phường 13 Tân Bình", slug: "xay-nha-phuong-13-tan-binh-sk68", status: "done" },
  { no: 6257, title: "Xây Nhà Phường Tây Thạnh", keyword: "xây nhà phường Tây Thạnh", slug: "xay-nha-phuong-tay-thanh-sk68", status: "done" },
  { no: 6258, title: "Xây Nhà Phường Sơn Kỳ", keyword: "xây nhà phường Sơn Kỳ", slug: "xay-nha-phuong-son-ky-sk68", status: "done" },
  { no: 6259, title: "Xây Nhà Phường Tân Quý", keyword: "xây nhà phường Tân Quý", slug: "xay-nha-phuong-tan-quy-sk68", status: "done" },
  { no: 6260, title: "Xây Nhà Phường Hiệp Tân", keyword: "xây nhà phường Hiệp Tân", slug: "xay-nha-phuong-hiep-tan-sk68", status: "done" },
  { no: 6261, title: "Xây Nhà Phường Bình Trị Đông", keyword: "xây nhà phường Bình Trị Đông", slug: "xay-nha-phuong-binh-tri-dong-sk68", status: "done" },
  { no: 6262, title: "Xây Nhà Phường Bình Trị Đông A", keyword: "xây nhà phường Bình Trị Đông A", slug: "xay-nha-phuong-binh-tri-dong-a-sk68", status: "done" },
  { no: 6263, title: "Xây Nhà Phường Bình Trị Đông B", keyword: "xây nhà phường Bình Trị Đông B", slug: "xay-nha-phuong-binh-tri-dong-b-sk68", status: "done" },
  { no: 6264, title: "Xây Nhà Gần Sân Bay Tân Sơn Nhất", keyword: "xây nhà gần sân bay Tân Sơn Nhất", slug: "xay-nha-gan-san-bay-tan-son-nhat-sk68", status: "done" },
  { no: 6265, title: "Xây Nhà Hẻm 3m Tân Bình", keyword: "xây nhà hẻm 3m Tân Bình", slug: "xay-nha-hem-3m-tan-binh-sk68", status: "done" },
  { no: 6266, title: "Xây Nhà Hẻm 4m Phú Nhuận", keyword: "xây nhà hẻm 4m Phú Nhuận", slug: "xay-nha-hem-4m-phu-nhuan-sk68", status: "done" },

  { no: 6267, title: "Cải Tạo Nhà Phú Nhuận", keyword: "cải tạo nhà Phú Nhuận", slug: "cai-tao-nha-phu-nhuan-sk68", status: "done" },
  { no: 6268, title: "Cải Tạo Nhà Tân Bình", keyword: "cải tạo nhà Tân Bình", slug: "cai-tao-nha-tan-binh-sk68", status: "done" },
  { no: 6269, title: "Cải Tạo Nhà Tân Phú", keyword: "cải tạo nhà Tân Phú", slug: "cai-tao-nha-tan-phu-sk68", status: "done" },
  { no: 6270, title: "Cải Tạo Nhà Bình Tân", keyword: "cải tạo nhà Bình Tân", slug: "cai-tao-nha-binh-tan-sk68", status: "done" },
  { no: 6271, title: "Cải Tạo Nhà Thêm Phòng Trẻ Em", keyword: "cải tạo nhà thêm phòng trẻ em", slug: "cai-tao-nha-them-phong-tre-em-sk68", status: "done" },
  { no: 6272, title: "Cải Tạo Nhà Thêm Phòng Khách Lớn", keyword: "cải tạo nhà thêm phòng khách lớn", slug: "cai-tao-nha-them-phong-khach-lon-sk68", status: "done" },
  { no: 6273, title: "Cải Tạo Nhà Đổi Sàn Gạch Sang Gỗ", keyword: "cải tạo nhà đổi sàn gạch sang gỗ", slug: "cai-tao-nha-doi-san-gach-sang-go-sk68", status: "done" },
  { no: 6274, title: "Cải Tạo Nhà Đổi Trần Thạch Cao", keyword: "cải tạo nhà đổi trần thạch cao", slug: "cai-tao-nha-doi-tran-thach-cao-sk68", status: "done" },
  { no: 6275, title: "Sửa Nhà Thấm Ban Công", keyword: "sửa nhà thấm ban công", slug: "sua-nha-tham-ban-cong-sk68", status: "done" },
  { no: 6276, title: "Sửa Nhà Thấm Khe Tường Chung", keyword: "sửa nhà thấm khe tường chung", slug: "sua-nha-tham-khe-tuong-chung-sk68", status: "done" },
  { no: 6277, title: "Sửa Nhà Nứt Vách Ngăn", keyword: "sửa nhà nứt vách ngăn", slug: "sua-nha-nut-vach-ngan-sk68", status: "done" },
  { no: 6278, title: "Sửa Hệ Thống Thoát Nước Sân", keyword: "sửa hệ thống thoát nước sân", slug: "sua-he-thong-thoat-nuoc-san-sk68", status: "done" },
  { no: 6279, title: "Thay Ống Cấp Nước Toàn Nhà", keyword: "thay ống cấp nước toàn nhà", slug: "thay-ong-cap-nuoc-toan-nha-sk68", status: "done" },
  { no: 6280, title: "Nâng Tầng Nhà Có Gác Lửng", keyword: "nâng tầng nhà có gác lửng", slug: "nang-tang-nha-co-gac-lung-sk68", status: "done" },
  { no: 6281, title: "Cải Tạo Nhà Thành Studio Cho Thuê", keyword: "cải tạo nhà thành studio cho thuê", slug: "cai-tao-nha-thanh-studio-cho-thue-sk68", status: "done" },
  { no: 6282, title: "Cải Tạo Nhà Thành Coworking", keyword: "cải tạo nhà thành coworking", slug: "cai-tao-nha-thanh-coworking-sk68", status: "done" },
  { no: 6283, title: "Cải Tạo Nhà Cho Gia Đình Đông Người", keyword: "cải tạo nhà cho gia đình đông người", slug: "cai-tao-nha-cho-gia-dinh-dong-nguoi-sk68", status: "done" },
  { no: 6284, title: "Sửa Chữa Nhà Sau Động Đất Nhẹ", keyword: "sửa chữa nhà sau rung chấn", slug: "sua-chua-nha-sau-rung-chan-sk68", status: "done" },
  { no: 6285, title: "Cải Tạo Nhà Giảm Nắng Tây", keyword: "cải tạo nhà giảm nắng Tây", slug: "cai-tao-nha-giam-nang-tay-sk68", status: "done" },
  { no: 6286, title: "Cải Tạo Nhà Tăng Gió Thoáng", keyword: "cải tạo nhà tăng gió thoáng", slug: "cai-tao-nha-tang-gio-thoang-sk68", status: "done" },

  { no: 6287, title: "Đơn Giá Xây Nhà Bình Dương 2026", keyword: "đơn giá xây nhà Bình Dương 2026", slug: "don-gia-xay-nha-binh-duong-2026-sk68", status: "done" },
  { no: 6288, title: "Đơn Giá Xây Nhà Đồng Nai 2026", keyword: "đơn giá xây nhà Đồng Nai 2026", slug: "don-gia-xay-nha-dong-nai-2026-sk68", status: "done" },
  { no: 6289, title: "Chi Phí Xây Nhà 4×15 Trọn Gói", keyword: "chi phí xây nhà 4x15 trọn gói", slug: "chi-phi-xay-nha-4x15-tron-goi-sk68", status: "done" },
  { no: 6290, title: "Chi Phí Xây Nhà 5×15 Trọn Gói", keyword: "chi phí xây nhà 5x15 trọn gói", slug: "chi-phi-xay-nha-5x15-tron-goi-sk68", status: "done" },
  { no: 6291, title: "Chi Phí Xây Nhà 5×22 Trọn Gói", keyword: "chi phí xây nhà 5x22 trọn gói", slug: "chi-phi-xay-nha-5x22-tron-goi-sk68", status: "done" },
  { no: 6292, title: "Báo Giá Thiết Kế Nội Thất Nhà Phố", keyword: "báo giá thiết kế nội thất nhà phố", slug: "bao-gia-thiet-ke-noi-that-nha-pho-sk68", status: "done" },
  { no: 6293, title: "Báo Giá Lắp Thang Máy Gia Đình", keyword: "báo giá lắp thang máy gia đình", slug: "bao-gia-lap-thang-may-gia-dinh-sk68", status: "done" },
  { no: 6294, title: "Ngân Sách Xây Nhà 8 Tỷ TP.HCM", keyword: "ngân sách xây nhà 8 tỷ TP.HCM", slug: "ngan-sach-xay-nha-8-ty-tphcm-sk68", status: "done" },
  { no: 6295, title: "Ngân Sách Cải Tạo Nhà 800 Triệu", keyword: "ngân sách cải tạo nhà 800 triệu", slug: "ngan-sach-cai-tao-nha-800-trieu-sk68", status: "done" },
  { no: 6296, title: "Chi Phí Chống Thấm Mái Và Sân", keyword: "chi phí chống thấm mái và sân", slug: "chi-phi-chong-tham-mai-va-san-sk68", status: "done" },
  { no: 6297, title: "Chi Phí Làm Mới Mặt Tiền Ốp Đá", keyword: "chi phí làm mới mặt tiền ốp đá", slug: "chi-phi-lam-moi-mat-tien-op-da-sk68", status: "done" },
  { no: 6298, title: "Báo Giá Sơn Epoxy Nhà Xưởng Nhỏ", keyword: "báo giá sơn epoxy nhà xưởng nhỏ", slug: "bao-gia-son-epoxy-nha-xuong-nho-sk68", status: "done" },
  { no: 6299, title: "Báo Giá Lát Gạch 60x60 Toàn Nhà", keyword: "báo giá lát gạch 60x60 toàn nhà", slug: "bao-gia-lat-gach-60x60-toan-nha-sk68", status: "done" },
  { no: 6300, title: "Chi Phí Lắp Đặt Năng Lượng Mặt Trời", keyword: "chi phí lắp năng lượng mặt trời nhà phố", slug: "chi-phi-lap-nang-luong-mat-troi-nha-pho-sk68", status: "done" },
  { no: 6301, title: "Cách So Sánh Báo Giá Xây Nhà", keyword: "cách so sánh báo giá xây nhà", slug: "cach-so-sanh-bao-gia-xay-nha-sk68", status: "done" },

  { no: 6302, title: "Thiết Kế Nhà Phố Phong Cách Neo Classic", keyword: "thiết kế nhà phố Neo Classic", slug: "thiet-ke-nha-pho-neo-classic-sk68", status: "done" },
  { no: 6303, title: "Thiết Kế Nhà Phố Phong Cách Mid Century", keyword: "thiết kế nhà phố Mid Century", slug: "thiet-ke-nha-pho-mid-century-sk68", status: "done" },
  { no: 6304, title: "Thiết Kế Nhà Phố Phong Cách Farmhouse", keyword: "thiết kế nhà phố farmhouse", slug: "thiet-ke-nha-pho-farmhouse-sk68", status: "done" },
  { no: 6305, title: "Thiết Kế Nhà Phố Có Thư Viện", keyword: "thiết kế nhà phố có thư viện", slug: "thiet-ke-nha-pho-co-thu-vien-sk68", status: "done" },
  { no: 6306, title: "Thiết Kế Nhà Phố Có Phòng Chiếu Phim", keyword: "thiết kế nhà phố có phòng chiếu phim", slug: "thiet-ke-nha-pho-co-phong-chieu-phim-sk68", status: "done" },
  { no: 6307, title: "Thiết Kế Nhà Phố 2 Phòng Ngủ", keyword: "thiết kế nhà phố 2 phòng ngủ", slug: "thiet-ke-nha-pho-2-phong-ngu-sk68", status: "done" },
  { no: 6308, title: "Thiết Kế Nhà Phố Có Phòng Game", keyword: "thiết kế nhà phố có phòng game", slug: "thiet-ke-nha-pho-co-phong-game-sk68", status: "done" },
  { no: 6309, title: "Thiết Kế Nhà Phố Có Phòng Kho", keyword: "thiết kế nhà phố có phòng kho", slug: "thiet-ke-nha-pho-co-phong-kho-sk68", status: "done" },
  { no: 6310, title: "Thiết Kế Biệt Thự Đơn Lập TP.HCM", keyword: "thiết kế biệt thự đơn lập TP.HCM", slug: "thiet-ke-biet-thu-don-lap-tphcm-sk68", status: "done" },
  { no: 6311, title: "Thiết Kế Nhà Vườn Hóc Môn", keyword: "thiết kế nhà vườn Hóc Môn", slug: "thiet-ke-nha-vuon-hoc-mon-sk68", status: "done" },
  { no: 6312, title: "Mẫu Nhà Phố Mặt Tiền 4m 2026", keyword: "mẫu nhà phố mặt tiền 4m 2026", slug: "mau-nha-pho-mat-tien-4m-2026-sk68", status: "done" },
  { no: 6313, title: "Mẫu Nhà Phố Mặt Tiền 5m 2026", keyword: "mẫu nhà phố mặt tiền 5m 2026", slug: "mau-nha-pho-mat-tien-5m-2026-sk68", status: "done" },
  { no: 6314, title: "Thiết Kế Bếp Chữ L Nhà Phố", keyword: "thiết kế bếp chữ L nhà phố", slug: "thiet-ke-bep-chu-l-nha-pho-sk68", status: "done" },
  { no: 6315, title: "Thiết Kế Cầu Thang Gỗ Hiện Đại", keyword: "thiết kế cầu thang gỗ hiện đại", slug: "thiet-ke-cau-thang-go-hien-dai-sk68", status: "done" },
  { no: 6316, title: "Thiết Kế Giếng Trời Có Cây Xanh", keyword: "thiết kế giếng trời có cây xanh", slug: "thiet-ke-gieng-troi-co-cay-xanh-sk68", status: "done" },

  { no: 6317, title: "Xây Nhà Cách Nhiệt Tường Ngoài", keyword: "xây nhà cách nhiệt tường ngoài", slug: "xay-nha-cach-nhiet-tuong-ngoai-sk68", status: "done" },
  { no: 6318, title: "Xây Nhà Chống Thấm Chân Tường", keyword: "xây nhà chống thấm chân tường", slug: "xay-nha-chong-tham-chan-tuong-sk68", status: "done" },
  { no: 6319, title: "Đổ Móng Bè Nhà Phố", keyword: "đổ móng bè nhà phố", slug: "do-mong-be-nha-pho-sk68", status: "done" },
  { no: 6320, title: "Đổ Đà Kiềng Nhà Phố", keyword: "đổ đà kiềng nhà phố", slug: "do-da-kieng-nha-pho-sk68", status: "done" },
  { no: 6321, title: "Làm Mái Chồng Nóng Nhà Phố", keyword: "làm mái chống nóng nhà phố", slug: "lam-mai-chong-nong-nha-pho-sk68", status: "done" },
  { no: 6322, title: "Làm Sân Trước Nhà Phố", keyword: "làm sân trước nhà phố", slug: "lam-san-truoc-nha-pho-sk68", status: "done" },
  { no: 6323, title: "Chống Nóng Tường Tiếp Giáp", keyword: "chống nóng tường tiếp giáp", slug: "chong-nong-tuong-tiep-giap-sk68", status: "done" },
  { no: 6324, title: "Lắp Cửa Sổ Nhôm Xingfa", keyword: "lắp cửa sổ nhôm Xingfa", slug: "lap-cua-so-nhom-xingfa-sk68", status: "done" },
  { no: 6325, title: "Ốp Lam Gỗ Nhựa Mặt Tiền", keyword: "ốp lam gỗ nhựa mặt tiền", slug: "op-lam-go-nhua-mat-tien-sk68", status: "done" },
  { no: 6326, title: "Sơn Chống Thấm Màu Ngoại Thất", keyword: "sơn chống thấm màu ngoại thất", slug: "son-chong-tham-mau-ngoai-that-sk68", status: "done" },
  { no: 6327, title: "Lát Gạch Granite Cầu Thang", keyword: "lát gạch granite cầu thang", slug: "lat-gach-granite-cau-thang-sk68", status: "done" },
  { no: 6328, title: "Làm Vách Kính Cường Lực", keyword: "làm vách kính cường lực", slug: "lam-vach-kinh-cuong-luc-sk68", status: "done" },
  { no: 6329, title: "Lắp Khóa Cửa Vân Tay Nhà Phố", keyword: "lắp khóa cửa vân tay nhà phố", slug: "lap-khoa-cua-van-tay-nha-pho-sk68", status: "done" },
  { no: 6330, title: "Lắp Hệ Thống Tưới Cây Tự Động", keyword: "lắp hệ thống tưới cây tự động", slug: "lap-he-thong-tuoi-cay-tu-dong-sk68", status: "done" },
  { no: 6331, title: "Gia Cố Móng Nhà Liền Kề", keyword: "gia cố móng nhà liền kề", slug: "gia-co-mong-nha-lien-ke-sk68", status: "done" },

  { no: 6332, title: "Xây Nhà Trọn Gói Cẩm Mỹ Đồng Nai", keyword: "xây nhà trọn gói Cẩm Mỹ", slug: "xay-nha-tron-goi-cam-my-sk68", status: "done" },
  { no: 6333, title: "Xây Nhà Trọn Gói Xuân Lộc", keyword: "xây nhà trọn gói Xuân Lộc", slug: "xay-nha-tron-goi-xuan-loc-sk68", status: "done" },
  { no: 6334, title: "Xây Nhà Trọn Gói Định Quán", keyword: "xây nhà trọn gói Định Quán", slug: "xay-nha-tron-goi-dinh-quan-sk68", status: "done" },
  { no: 6335, title: "Xây Nhà Trọn Gói Châu Thành Long An", keyword: "xây nhà trọn gói Châu Thành Long An", slug: "xay-nha-tron-goi-chau-thanh-long-an-sk68", status: "done" },
  { no: 6336, title: "Xây Nhà Trọn Gói Thủ Thừa", keyword: "xây nhà trọn gói Thủ Thừa", slug: "xay-nha-tron-goi-thu-thua-sk68", status: "done" },
  { no: 6337, title: "Xây Nhà Trọn Gói Tân An", keyword: "xây nhà trọn gói Tân An", slug: "xay-nha-tron-goi-tan-an-sk68", status: "done" },
  { no: 6338, title: "Xây Nhà Trọn Gói Bắc Tân Uyên", keyword: "xây nhà trọn gói Bắc Tân Uyên", slug: "xay-nha-tron-goi-bac-tan-uyen-sk68", status: "done" },
  { no: 6339, title: "Cải Tạo Nhà Long Khánh", keyword: "cải tạo nhà Long Khánh", slug: "cai-tao-nha-long-khanh-sk68", status: "done" },
  { no: 6340, title: "Cải Tạo Nhà Tân An Long An", keyword: "cải tạo nhà Tân An", slug: "cai-tao-nha-tan-an-sk68", status: "done" },
  { no: 6341, title: "Xây Nhà Cần Bao Nhiêu Tháng", keyword: "xây nhà cần bao nhiêu tháng", slug: "xay-nha-can-bao-nhieu-thang-sk68", status: "done" },
  { no: 6342, title: "Cải Tạo Nhà Có Phải Xin Phép Không", keyword: "cải tạo nhà có phải xin phép không", slug: "cai-tao-nha-co-phai-xin-phep-khong-sk68", status: "done" },
  { no: 6343, title: "Xây Nhà Có Nên Thuê Giám Sát Riêng", keyword: "xây nhà có nên thuê giám sát riêng", slug: "xay-nha-co-nen-thue-giam-sat-rieng-sk68", status: "done" },
  { no: 6344, title: "Nhà Thầu Có Cung Cấp Bản Vẽ Không", keyword: "nhà thầu có cung cấp bản vẽ không", slug: "nha-thau-co-cung-cap-ban-ve-khong-sk68", status: "done" },
  { no: 6345, title: "Cách Chụp Ảnh Hiện Trạng Gửi Thầu", keyword: "cách chụp ảnh hiện trạng gửi thầu", slug: "cach-chup-anh-hien-trang-gui-thau-sk68", status: "done" },
  { no: 6346, title: "Khi Nào Nên Tạm Dừng Công Trình", keyword: "khi nào nên tạm dừng công trình", slug: "khi-nao-nen-tam-dung-cong-trinh-sk68", status: "done" },
];
