/**
 * Lịch 100 từ khóa ngắn — batch 25 (#1947–#2046).
 * Cluster: bệnh công trình / xử lý sự cố nhà.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch25: ContentCalendarItem[] = [
  { no: 1947, title: "Nhà Bị Thấm Trần", keyword: "nhà bị thấm trần", slug: "nha-bi-tham-tran-ngan", status: "done" },
  { no: 1948, title: "Nhà Bị Thấm Tường", keyword: "nhà bị thấm tường", slug: "nha-bi-tham-tuong-ngan", status: "done" },
  { no: 1949, title: "Nhà Bị Nứt Tường", keyword: "nhà bị nứt tường", slug: "nha-bi-nut-tuong-ngan", status: "done" },
  { no: 1950, title: "Nhà Bị Nứt Trần", keyword: "nhà bị nứt trần", slug: "nha-bi-nut-tran-ngan", status: "done" },
  { no: 1951, title: "Nhà Bị Nghiêng", keyword: "nhà bị nghiêng", slug: "nha-bi-nghieng-ngan", status: "done" },
  { no: 1952, title: "Nhà Bị Lún", keyword: "nhà bị lún", slug: "nha-bi-lun-ngan", status: "done" },
  { no: 1953, title: "Nhà Bị Lún Không Đều", keyword: "nhà bị lún không đều", slug: "nha-bi-lun-khong-deu-ngan", status: "done" },
  { no: 1954, title: "Nhà Bị Rung", keyword: "nhà bị rung", slug: "nha-bi-rung-ngan", status: "done" },
  { no: 1955, title: "Nhà Bị Ồn", keyword: "nhà bị ồn", slug: "nha-bi-on-ngan", status: "done" },
  { no: 1956, title: "Nhà Bị Nóng", keyword: "nhà bị nóng", slug: "nha-bi-nong-ngan", status: "done" },
  { no: 1957, title: "Nhà Bị Ẩm", keyword: "nhà bị ẩm", slug: "nha-bi-am-ngan", status: "done" },
  { no: 1958, title: "Nhà Bị Mốc", keyword: "nhà bị mốc", slug: "nha-bi-moc-ngan", status: "done" },
  { no: 1959, title: "Nhà Bị Muối Hóa", keyword: "nhà bị muối hóa", slug: "nha-bi-muoi-hoa-ngan", status: "done" },
  { no: 1960, title: "Nhà Bị Phồng Sơn", keyword: "nhà bị phồng sơn", slug: "nha-bi-phong-son-ngan", status: "done" },
  { no: 1961, title: "Nhà Bị Bong Tróc Sơn", keyword: "nhà bị bong tróc sơn", slug: "nha-bi-bong-troc-son-ngan", status: "done" },
  { no: 1962, title: "Nhà Bị Nồm", keyword: "nhà bị nồm", slug: "nha-bi-nom-ngan", status: "done" },
  { no: 1963, title: "Nhà Bị Hôi", keyword: "nhà bị hôi", slug: "nha-bi-hoi-ngan", status: "done" },
  { no: 1964, title: "Nhà Bị Ruồi Muỗi", keyword: "nhà bị ruồi muỗi", slug: "nha-bi-ruoi-muoi-ngan", status: "done" },
  { no: 1965, title: "Nhà Bị Mối", keyword: "nhà bị mối", slug: "nha-bi-moi-ngan", status: "done" },
  { no: 1966, title: "Nhà Bị Mọt", keyword: "nhà bị mọt", slug: "nha-bi-mot-ngan", status: "done" },
  { no: 1967, title: "Sàn Nhà Bị Phồng", keyword: "sàn nhà bị phồng", slug: "san-nha-bi-phong-ngan", status: "done" },
  { no: 1968, title: "Sàn Nhà Bị Rộp", keyword: "sàn nhà bị rộp", slug: "san-nha-bi-rop-ngan", status: "done" },
  { no: 1969, title: "Gạch Lát Bị Rỗng", keyword: "gạch lát bị rỗng", slug: "gach-lat-bi-rong-ngan", status: "done" },
  { no: 1970, title: "Gạch Ốp Bị Bong", keyword: "gạch ốp bị bong", slug: "gach-op-bi-bong-ngan", status: "done" },
  { no: 1971, title: "Ron Gạch Bị Đen", keyword: "ron gạch bị đen", slug: "ron-gach-bi-den-ngan", status: "done" },
  { no: 1972, title: "Trần Thạch Cao Bị Sụp", keyword: "trần thạch cao bị sụp", slug: "tran-thach-cao-bi-sup-ngan", status: "done" },
  { no: 1973, title: "Trần Thạch Cao Bị Ố", keyword: "trần thạch cao bị ố", slug: "tran-thach-cao-bi-o-ngan", status: "done" },
  { no: 1974, title: "Cửa Gỗ Bị Cong", keyword: "cửa gỗ bị cong", slug: "cua-go-bi-cong-ngan", status: "done" },
  { no: 1975, title: "Cửa Nhôm Bị Kẹt", keyword: "cửa nhôm bị kẹt", slug: "cua-nhom-bi-ket-ngan", status: "done" },
  { no: 1976, title: "Cửa Kính Bị Ồn", keyword: "cửa kính bị ồn", slug: "cua-kinh-bi-on-ngan", status: "done" },
  { no: 1977, title: "Lan Can Bị Rỉ", keyword: "lan can bị rỉ", slug: "lan-can-bi-ri-ngan", status: "done" },
  { no: 1978, title: "Mái Tôn Bị Dột", keyword: "mái tôn bị dột", slug: "mai-ton-bi-dot-ngan", status: "done" },
  { no: 1979, title: "Mái Tôn Bị Nóng", keyword: "mái tôn bị nóng", slug: "mai-ton-bi-nong-ngan", status: "done" },
  { no: 1980, title: "Mái Tôn Bị Ồn Mưa", keyword: "mái tôn bị ồn mưa", slug: "mai-ton-bi-on-mua-ngan", status: "done" },
  { no: 1981, title: "Ống Nước Bị Tắc", keyword: "ống nước bị tắc", slug: "ong-nuoc-bi-tac-ngan", status: "done" },
  { no: 1982, title: "Ống Nước Bị Rò", keyword: "ống nước bị rò", slug: "ong-nuoc-bi-ro-ngan", status: "done" },
  { no: 1983, title: "Ống Nước Bị Ồn", keyword: "ống nước bị ồn", slug: "ong-nuoc-bi-on-ngan", status: "done" },
  { no: 1984, title: "Bồn Cầu Bị Tắc", keyword: "bồn cầu bị tắc", slug: "bon-cau-bi-tac-ngan", status: "done" },
  { no: 1985, title: "Bồn Cầu Bị Rò", keyword: "bồn cầu bị rò", slug: "bon-cau-bi-ro-ngan", status: "done" },
  { no: 1986, title: "Sen Tắm Áp Lực Yếu", keyword: "sen tắm áp lực yếu", slug: "sen-tam-ap-luc-yeu-ngan", status: "done" },
  { no: 1987, title: "Điện Nhà Bị Nhảy", keyword: "điện nhà bị nhảy", slug: "dien-nha-bi-nhay-ngan", status: "done" },
  { no: 1988, title: "Điện Nhà Bị Chập", keyword: "điện nhà bị chập", slug: "dien-nha-bi-chap-ngan", status: "done" },
  { no: 1989, title: "Đèn Nhà Hay Cháy", keyword: "đèn nhà hay cháy", slug: "den-nha-hay-chay-ngan", status: "done" },
  { no: 1990, title: "Máy Lạnh Không Mát", keyword: "máy lạnh không mát", slug: "may-lanh-khong-mat-ngan", status: "done" },
  { no: 1991, title: "Máy Lạnh Chảy Nước", keyword: "máy lạnh chảy nước", slug: "may-lanh-chay-nuoc-ngan", status: "done" },
  { no: 1992, title: "Nhà Bí Khí", keyword: "nhà bí khí", slug: "nha-bi-khi-ngan", status: "done" },
  { no: 1993, title: "Nhà Thiếu Sáng", keyword: "nhà thiếu sáng", slug: "nha-thieu-sang-ngan", status: "done" },
  { no: 1994, title: "Nhà Bí Bếp", keyword: "nhà bí bếp", slug: "nha-bi-bep-ngan", status: "done" },
  { no: 1995, title: "Nhà Bí WC", keyword: "nhà bí wc", slug: "nha-bi-wc-ngan", status: "done" },
  { no: 1996, title: "Nhà Hôi WC", keyword: "nhà hôi wc", slug: "nha-hoi-wc-ngan", status: "done" },
  { no: 1997, title: "Nhà Hôi Cống", keyword: "nhà hôi cống", slug: "nha-hoi-cong-ngan", status: "done" },
  { no: 1998, title: "Sân Thượng Ngập Nước", keyword: "sân thượng ngập nước", slug: "san-thuong-ngap-nuoc-ngan", status: "done" },
  { no: 1999, title: "Sân Trước Ngập", keyword: "sân trước ngập", slug: "san-truoc-ngap-ngan", status: "done" },
  { no: 2000, title: "Nhà Ngập Khi Mưa", keyword: "nhà ngập khi mưa", slug: "nha-ngap-khi-mua-ngan", status: "done" },
  { no: 2001, title: "Tường Nhà Bị Rêu", keyword: "tường nhà bị rêu", slug: "tuong-nha-bi-reu-ngan", status: "done" },
  { no: 2002, title: "Tường Nhà Bị Ố Vàng", keyword: "tường nhà bị ố vàng", slug: "tuong-nha-bi-o-vang-ngan", status: "done" },
  { no: 2003, title: "Cột Nhà Bị Nứt", keyword: "cột nhà bị nứt", slug: "cot-nha-bi-nut-ngan", status: "done" },
  { no: 2004, title: "Dầm Nhà Bị Nứt", keyword: "dầm nhà bị nứt", slug: "dam-nha-bi-nut-ngan", status: "done" },
  { no: 2005, title: "Sàn Nhà Bị Võng", keyword: "sàn nhà bị võng", slug: "san-nha-bi-vong-ngan", status: "done" },
  { no: 2006, title: "Cầu Thang Bị Rung", keyword: "cầu thang bị rung", slug: "cau-thang-bi-rung-ngan", status: "done" },
  { no: 2007, title: "Cầu Thang Bị Trơn", keyword: "cầu thang bị trơn", slug: "cau-thang-bi-tron-ngan", status: "done" },
  { no: 2008, title: "Ban Công Bị Dột", keyword: "ban công bị dột", slug: "ban-cong-bi-dot-ngan", status: "done" },
  { no: 2009, title: "Ban Công Bị Nứt", keyword: "ban công bị nứt", slug: "ban-cong-bi-nut-ngan", status: "done" },
  { no: 2010, title: "Giếng Trời Bị Dột", keyword: "giếng trời bị dột", slug: "gieng-troi-bi-dot-ngan", status: "done" },
  { no: 2011, title: "Giếng Trời Bị Nóng", keyword: "giếng trời bị nóng", slug: "gieng-troi-bi-nong-ngan", status: "done" },
  { no: 2012, title: "Nhà Bị Mất Điện Thường Xuyên", keyword: "nhà bị mất điện thường xuyên", slug: "nha-bi-mat-dien-thuong-xuyen-ngan", status: "done" },
  { no: 2013, title: "Nhà Bị Áp Lực Nước Yếu", keyword: "nhà bị áp lực nước yếu", slug: "nha-bi-ap-luc-nuoc-yeu-ngan", status: "done" },
  { no: 2014, title: "Bể Phốt Đầy", keyword: "bể phốt đầy", slug: "be-phot-day-ngan", status: "done" },
  { no: 2015, title: "Bể Phốt Hôi", keyword: "bể phốt hôi", slug: "be-phot-hoi-ngan", status: "done" },
  { no: 2016, title: "Hút Bể Phốt Định Kỳ", keyword: "hút bể phốt định kỳ", slug: "hut-be-phot-dinh-ky-ngan", status: "done" },
  { no: 2017, title: "Thông Cống Nghẹt", keyword: "thông cống nghẹt", slug: "thong-cong-nghet-ngan", status: "done" },
  { no: 2018, title: "Xử Lý Mối Nhà", keyword: "xử lý mối nhà", slug: "xu-ly-moi-nha-ngan", status: "done" },
  { no: 2019, title: "Phòng Chống Mối", keyword: "phòng chống mối", slug: "phong-chong-moi-ngan", status: "done" },
  { no: 2020, title: "Xử Lý Mốc Tường", keyword: "xử lý mốc tường", slug: "xu-ly-moc-tuong-ngan", status: "done" },
  { no: 2021, title: "Xử Lý Ẩm Tường", keyword: "xử lý ẩm tường", slug: "xu-ly-am-tuong-ngan", status: "done" },
  { no: 2022, title: "Xử Lý Muối Hóa Tường", keyword: "xử lý muối hóa tường", slug: "xu-ly-muoi-hoa-tuong-ngan", status: "done" },
  { no: 2023, title: "Xử Lý Nồm Nhà", keyword: "xử lý nồm nhà", slug: "xu-ly-nom-nha-ngan", status: "done" },
  { no: 2024, title: "Xử Lý Nhà Bí", keyword: "xử lý nhà bí", slug: "xu-ly-nha-bi-ngan", status: "done" },
  { no: 2025, title: "Xử Lý Nhà Thiếu Sáng", keyword: "xử lý nhà thiếu sáng", slug: "xu-ly-nha-thieu-sang-ngan", status: "done" },
  { no: 2026, title: "Xử Lý Nhà Nóng", keyword: "xử lý nhà nóng", slug: "xu-ly-nha-nong-ngan", status: "done" },
  { no: 2027, title: "Xử Lý Nhà Ồn", keyword: "xử lý nhà ồn", slug: "xu-ly-nha-on-ngan", status: "done" },
  { no: 2028, title: "Gia Cố Nhà Nghiêng", keyword: "gia cố nhà nghiêng", slug: "gia-co-nha-nghieng-ngan", status: "done" },
  { no: 2029, title: "Gia Cố Nhà Lún", keyword: "gia cố nhà lún", slug: "gia-co-nha-lun-ngan", status: "done" },
  { no: 2030, title: "Nâng Nhà Bị Lún", keyword: "nâng nhà bị lún", slug: "nang-nha-bi-lun-ngan", status: "done" },
  { no: 2031, title: "Ép Cọc Gia Cố Nhà Cũ", keyword: "ép cọc gia cố nhà cũ", slug: "ep-coc-gia-co-nha-cu-ngan", status: "done" },
  { no: 2032, title: "Neo Đất Chống Lún", keyword: "neo đất chống lún", slug: "neo-dat-chong-lun-ngan", status: "done" },
  { no: 2033, title: "Sửa Nhà Sau Mưa Bão", keyword: "sửa nhà sau mưa bão", slug: "sua-nha-sau-mua-bao-ngan", status: "done" },
  { no: 2034, title: "Sửa Nhà Sau Ngập", keyword: "sửa nhà sau ngập", slug: "sua-nha-sau-ngap-ngan", status: "done" },
  { no: 2035, title: "Khôi Phục Nhà Sau Hỏa Hoạn", keyword: "khôi phục nhà sau hỏa hoạn", slug: "khoi-phuc-nha-sau-hoa-hoan-ngan", status: "done" },
  { no: 2036, title: "Sửa Nhà Sau Động Đất", keyword: "sửa nhà sau động đất", slug: "sua-nha-sau-dong-dat-ngan", status: "done" },
  { no: 2037, title: "Kiểm Tra An Toàn Nhà Cũ", keyword: "kiểm tra an toàn nhà cũ", slug: "kiem-tra-an-toan-nha-cu-ngan", status: "done" },
  { no: 2038, title: "Đánh Giá Nguy Cơ Sập", keyword: "đánh giá nguy cơ sập", slug: "danh-gia-nguy-co-sap-ngan", status: "done" },
  { no: 2039, title: "Gia Cố Khẩn Cấp Nhà", keyword: "gia cố khẩn cấp nhà", slug: "gia-co-khan-cap-nha-ngan", status: "done" },
  { no: 2040, title: "Chống Sập Nhà Cũ", keyword: "chống sập nhà cũ", slug: "chong-sap-nha-cu-ngan", status: "done" },
  { no: 2041, title: "Gia Cố Tường Bao", keyword: "gia cố tường bao", slug: "gia-co-tuong-bao-ngan", status: "done" },
  { no: 2042, title: "Gia Cố Mái Cũ", keyword: "gia cố mái cũ", slug: "gia-co-mai-cu-ngan", status: "done" },
  { no: 2043, title: "Thay Mái Tôn Cũ", keyword: "thay mái tôn cũ", slug: "thay-mai-ton-cu-ngan", status: "done" },
  { no: 2044, title: "Thay Hệ Thống Điện Cũ", keyword: "thay hệ thống điện cũ", slug: "thay-he-thong-dien-cu-ngan", status: "done" },
  { no: 2045, title: "Thay Hệ Thống Nước Cũ", keyword: "thay hệ thống nước cũ", slug: "thay-he-thong-nuoc-cu-ngan", status: "done" },
  { no: 2046, title: "Nâng Cấp Nhà Cũ", keyword: "nâng cấp nhà cũ", slug: "nang-cap-nha-cu-ngan", status: "done" },
];
