/**
 * Lịch 100 từ khóa ngắn — batch 38 (#3247–#3346).
 * Cluster: pháp lý, tài chính, bảo hiểm, hợp đồng sâu.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch38: ContentCalendarItem[] = [
  { no: 3247, title: "Hồ Sơ Xin Phép Xây Dựng", keyword: "hồ sơ xin phép xây dựng", slug: "ho-so-xin-phep-xay-dung-ngan", status: "done" },
  { no: 3248, title: "Thời Gian Xin Phép Xây", keyword: "thời gian xin phép xây", slug: "thoi-gian-xin-phep-xay-ngan", status: "done" },
  { no: 3249, title: "Lệ Phí Xin Phép Xây", keyword: "lệ phí xin phép xây", slug: "le-phi-xin-phep-xay-ngan", status: "done" },
  { no: 3250, title: "Giấy Phép Xây Dựng Hết Hạn", keyword: "giấy phép xây dựng hết hạn", slug: "giay-phep-xay-dung-het-han-ngan", status: "done" },
  { no: 3251, title: "Gia Hạn Giấy Phép Xây", keyword: "gia hạn giấy phép xây", slug: "gia-han-giay-phep-xay-ngan", status: "done" },
  { no: 3252, title: "Sửa Đổi Giấy Phép Xây", keyword: "sửa đổi giấy phép xây", slug: "sua-doi-giay-phep-xay-ngan", status: "done" },
  { no: 3253, title: "Xây Không Phép Xử Lý", keyword: "xây không phép xử lý", slug: "xay-khong-phep-xu-ly-ngan", status: "done" },
  { no: 3254, title: "Phạt Xây Vượt Phép", keyword: "phạt xây vượt phép", slug: "phat-xay-vuot-phep-ngan", status: "done" },
  { no: 3255, title: "Phạt Xây Sai Phép", keyword: "phạt xây sai phép", slug: "phat-xay-sai-phep-ngan", status: "done" },
  { no: 3256, title: "Hợp Thức Hóa Công Trình", keyword: "hợp thức hóa công trình", slug: "hop-thuc-hoa-cong-trinh-ngan", status: "done" },
  { no: 3257, title: "Cấp Phép Xây Nhà Cải Tạo", keyword: "cấp phép xây nhà cải tạo", slug: "cap-phep-xay-nha-cai-tao-ngan", status: "done" },
  { no: 3258, title: "Thông Báo Cải Tạo Nhà", keyword: "thông báo cải tạo nhà", slug: "thong-bao-cai-tao-nha-ngan", status: "done" },
  { no: 3259, title: "Quy Hoạch Xây Dựng Khu Vực", keyword: "quy hoạch xây dựng khu vực", slug: "quy-hoach-xay-dung-khu-vuc-ngan", status: "done" },
  { no: 3260, title: "Chỉ Giới Đường Đỏ", keyword: "chỉ giới đường đỏ", slug: "chi-gioi-duong-do-pl-ngan", status: "done" },
  { no: 3261, title: "Chỉ Giới Xây Dựng", keyword: "chỉ giới xây dựng", slug: "chi-gioi-xay-dung-pl-ngan", status: "done" },
  { no: 3262, title: "Mật Độ Xây Dựng Cho Phép", keyword: "mật độ xây dựng cho phép", slug: "mat-do-xay-dung-cho-phep-ngan", status: "done" },
  { no: 3263, title: "Hệ Số Sử Dụng Đất", keyword: "hệ số sử dụng đất", slug: "he-so-su-dung-dat-pl-ngan", status: "done" },
  { no: 3264, title: "Chiều Cao Tầng Cho Phép", keyword: "chiều cao tầng cho phép", slug: "chieu-cao-tang-cho-phep-ngan", status: "done" },
  { no: 3265, title: "Khoảng Lùi Công Trình", keyword: "khoảng lùi công trình", slug: "khoang-lui-cong-trinh-ngan", status: "done" },
  { no: 3266, title: "Quyền Sử Dụng Đất Xây Nhà", keyword: "quyền sử dụng đất xây nhà", slug: "quyen-su-dung-dat-xay-nha-ngan", status: "done" },
  { no: 3267, title: "Đất Ở Xây Nhà", keyword: "đất ở xây nhà", slug: "dat-o-xay-nha-ngan", status: "done" },
  { no: 3268, title: "Đất Nông Nghiệp Xây Nhà", keyword: "đất nông nghiệp xây nhà", slug: "dat-nong-nghiep-xay-nha-ngan", status: "done" },
  { no: 3269, title: "Chuyển Đổi Đất Xây Nhà", keyword: "chuyển đổi đất xây nhà", slug: "chuyen-doi-dat-xay-nha-ngan", status: "done" },
  { no: 3270, title: "Sổ Hồng Xây Nhà", keyword: "sổ hồng xây nhà", slug: "so-hong-xay-nha-pl-ngan", status: "done" },
  { no: 3271, title: "Sổ Đỏ Xây Nhà", keyword: "sổ đỏ xây nhà", slug: "so-do-xay-nha-ngan", status: "done" },
  { no: 3272, title: "Thế Chấp Sổ Vay Xây", keyword: "thế chấp sổ vay xây", slug: "the-chap-so-vay-xay-ngan", status: "done" },
  { no: 3273, title: "Vay Xây Sửa Nhà", keyword: "vay xây sửa nhà", slug: "vay-xay-sua-nha-ngan", status: "done" },
  { no: 3274, title: "Vay Mua Đất Xây Nhà", keyword: "vay mua đất xây nhà", slug: "vay-mua-dat-xay-nha-ngan", status: "done" },
  { no: 3275, title: "Gói Vay Xây Nhà Ngân Hàng", keyword: "gói vay xây nhà ngân hàng", slug: "goi-vay-xay-nha-ngan-hang-ngan", status: "done" },
  { no: 3276, title: "Hồ Sơ Vay Xây Nhà", keyword: "hồ sơ vay xây nhà", slug: "ho-so-vay-xay-nha-ngan", status: "done" },
  { no: 3277, title: "Điều Kiện Vay Xây Nhà", keyword: "điều kiện vay xây nhà", slug: "dieu-kien-vay-xay-nha-ngan", status: "done" },
  { no: 3278, title: "Bảo Hiểm Công Trình Xây", keyword: "bảo hiểm công trình xây", slug: "bao-hiem-cong-trinh-xay-ngan", status: "done" },
  { no: 3279, title: "Bảo Hiểm Trách Nhiệm Thầu", keyword: "bảo hiểm trách nhiệm thầu", slug: "bao-hiem-trach-nhiem-thau-ngan", status: "done" },
  { no: 3280, title: "Bảo Hiểm Tai Nạn Lao Động", keyword: "bảo hiểm tai nạn lao động", slug: "bao-hiem-tai-nan-lao-dong-ngan", status: "done" },
  { no: 3281, title: "Bảo Hiểm Nhà Ở", keyword: "bảo hiểm nhà ở", slug: "bao-hiem-nha-o-ngan", status: "done" },
  { no: 3282, title: "Bảo Hiểm Cháy Nổ Nhà", keyword: "bảo hiểm cháy nổ nhà", slug: "bao-hiem-chay-no-nha-ngan", status: "done" },
  { no: 3283, title: "Hợp Đồng Thiết Kế Nhà", keyword: "hợp đồng thiết kế nhà", slug: "hop-dong-thiet-ke-nha-ngan", status: "done" },
  { no: 3284, title: "Hợp Đồng Thi Công Xây", keyword: "hợp đồng thi công xây", slug: "hop-dong-thi-cong-xay-ngan", status: "done" },
  { no: 3285, title: "Hợp Đồng Trọn Gói Xây", keyword: "hợp đồng trọn gói xây", slug: "hop-dong-tron-goi-xay-ngan", status: "done" },
  { no: 3286, title: "Hợp Đồng Đơn Giá Xây", keyword: "hợp đồng đơn giá xây", slug: "hop-dong-don-gia-xay-ngan", status: "done" },
  { no: 3287, title: "Hợp Đồng Nhân Công Xây", keyword: "hợp đồng nhân công xây", slug: "hop-dong-nhan-cong-xay-ngan", status: "done" },
  { no: 3288, title: "Điều Khoản Phát Sinh HĐ", keyword: "điều khoản phát sinh hợp đồng", slug: "dieu-khoan-phat-sinh-hd-ngan", status: "done" },
  { no: 3289, title: "Điều Khoản Bảo Hành HĐ", keyword: "điều khoản bảo hành hợp đồng", slug: "dieu-khoan-bao-hanh-hd-ngan", status: "done" },
  { no: 3290, title: "Điều Khoản Phạt Trễ HĐ", keyword: "điều khoản phạt trễ hợp đồng", slug: "dieu-khoan-phat-tre-hd-ngan", status: "done" },
  { no: 3291, title: "Điều Khoản Tạm Ứng HĐ", keyword: "điều khoản tạm ứng hợp đồng", slug: "dieu-khoan-tam-ung-hd-ngan", status: "done" },
  { no: 3292, title: "Điều Khoản Nghiệm Thu HĐ", keyword: "điều khoản nghiệm thu hợp đồng", slug: "dieu-khoan-nghiem-thu-hd-ngan", status: "done" },
  { no: 3293, title: "Phụ Lục Hợp Đồng Xây", keyword: "phụ lục hợp đồng xây", slug: "phu-luc-hop-dong-xay-pl-ngan", status: "done" },
  { no: 3294, title: "Thanh Lý Hợp Đồng Xây", keyword: "thanh lý hợp đồng xây", slug: "thanh-ly-hop-dong-xay-pl-ngan", status: "done" },
  { no: 3295, title: "Chấm Dứt Hợp Đồng Xây", keyword: "chấm dứt hợp đồng xây", slug: "cham-dut-hop-dong-xay-ngan", status: "done" },
  { no: 3296, title: "Trọng Tài Tranh Chấp Xây", keyword: "trọng tài tranh chấp xây", slug: "trong-tai-tranh-chap-xay-ngan", status: "done" },
  { no: 3297, title: "Luật Xây Dựng Cơ Bản", keyword: "luật xây dựng cơ bản", slug: "luat-xay-dung-co-ban-ngan", status: "done" },
  { no: 3298, title: "Nghị Định Xây Dựng Nhà Ở", keyword: "nghị định xây dựng nhà ở", slug: "nghi-dinh-xay-dung-nha-o-ngan", status: "done" },
  { no: 3299, title: "Tiêu Chuẩn Xây Dựng Việt Nam", keyword: "tiêu chuẩn xây dựng việt nam", slug: "tieu-chuan-xay-dung-viet-nam-ngan", status: "done" },
  { no: 3300, title: "Quy Chuẩn Kỹ Thuật Xây", keyword: "quy chuẩn kỹ thuật xây", slug: "quy-chuan-ky-thuat-xay-ngan", status: "done" },
  { no: 3301, title: "An Toàn Kết Cấu Nhà Ở", keyword: "an toàn kết cấu nhà ở", slug: "an-toan-ket-cau-nha-o-ngan", status: "done" },
  { no: 3302, title: "Chứng Chỉ Hành Nghề KTS", keyword: "chứng chỉ hành nghề kts", slug: "chung-chi-hanh-nghe-kts-ngan", status: "done" },
  { no: 3303, title: "Chứng Chỉ Hành Nghề Giám Sát", keyword: "chứng chỉ hành nghề giám sát", slug: "chung-chi-hanh-nghe-giam-sat-ngan", status: "done" },
  { no: 3304, title: "Năng Lực Nhà Thầu Xây", keyword: "năng lực nhà thầu xây", slug: "nang-luc-nha-thau-xay-ngan", status: "done" },
  { no: 3305, title: "Giấy Phép Kinh Doanh Xây", keyword: "giấy phép kinh doanh xây", slug: "giay-phep-kinh-doanh-xay-pl-ngan", status: "done" },
  { no: 3306, title: "MST Công Ty Xây Dựng", keyword: "mst công ty xây dựng", slug: "mst-cong-ty-xay-dung-ngan", status: "done" },
  { no: 3307, title: "Hóa Đơn VAT Xây Nhà", keyword: "hóa đơn vat xây nhà", slug: "hoa-don-vat-xay-nha-ngan", status: "done" },
  { no: 3308, title: "Thuế Xây Nhà Cá Nhân", keyword: "thuế xây nhà cá nhân", slug: "thue-xay-nha-ca-nhan-ngan", status: "done" },
  { no: 3309, title: "Chi Phí Pháp Lý Xây Nhà", keyword: "chi phí pháp lý xây nhà", slug: "chi-phi-phap-ly-xay-nha-ngan", status: "done" },
  { no: 3310, title: "Công Chứng Hợp Đồng Xây", keyword: "công chứng hợp đồng xây", slug: "cong-chung-hop-dong-xay-ngan", status: "done" },
  { no: 3311, title: "Ủy Quyền Xây Nhà", keyword: "ủy quyền xây nhà", slug: "uy-quyen-xay-nha-ngan", status: "done" },
  { no: 3312, title: "Đồng Sở Hữu Xây Nhà", keyword: "đồng sở hữu xây nhà", slug: "dong-so-huu-xay-nha-ngan", status: "done" },
  { no: 3313, title: "Xây Nhà Trên Đất Chung", keyword: "xây nhà trên đất chung", slug: "xay-nha-tren-dat-chung-ngan", status: "done" },
  { no: 3314, title: "Tách Thửa Xây Nhà", keyword: "tách thửa xây nhà", slug: "tach-thua-xay-nha-pl-ngan", status: "done" },
  { no: 3315, title: "Hợp Thửa Xây Nhà", keyword: "hợp thửa xây nhà", slug: "hop-thua-xay-nha-pl-ngan", status: "done" },
  { no: 3316, title: "Giấy Phép Môi Trường Xây", keyword: "giấy phép môi trường xây", slug: "giay-phep-moi-truong-xay-ngan", status: "done" },
  { no: 3317, title: "Cam Kết Bảo Vệ Môi Trường", keyword: "cam kết bảo vệ môi trường", slug: "cam-ket-bao-ve-moi-truong-ngan", status: "done" },
  { no: 3318, title: "Thẩm Duyệt PCCC Nhà Ở", keyword: "thẩm duyệt pccc nhà ở", slug: "tham-duyet-pccc-nha-o-ngan", status: "done" },
  { no: 3319, title: "Nghiệm Thu PCCC Nhà Ở", keyword: "nghiệm thu pccc nhà ở", slug: "nghiem-thu-pccc-nha-o-ngan", status: "done" },
  { no: 3320, title: "Biên Bản Hiện Trường Xây", keyword: "biên bản hiện trường xây", slug: "bien-ban-hien-truong-xay-ngan", status: "done" },
  { no: 3321, title: "Khiếu Nại Hàng Xóm Xây", keyword: "khiếu nại hàng xóm xây", slug: "khieu-nai-hang-xom-xay-ngan", status: "done" },
  { no: 3322, title: "Tranh Chấp Ranh Giới Đất", keyword: "tranh chấp ranh giới đất", slug: "tranh-chap-ranh-gioi-dat-ngan", status: "done" },
  { no: 3323, title: "Hỗ Trợ Pháp Lý Xây Nhà", keyword: "hỗ trợ pháp lý xây nhà", slug: "ho-tro-phap-ly-xay-nha-ngan", status: "done" },
  { no: 3324, title: "Tư Vấn Luật Xây Dựng", keyword: "tư vấn luật xây dựng", slug: "tu-van-luat-xay-dung-ngan", status: "done" },
  { no: 3325, title: "Checklist Pháp Lý Trước Xây", keyword: "checklist pháp lý trước xây", slug: "checklist-phap-ly-truoc-xay-ngan", status: "done" },
  { no: 3326, title: "Checklist Pháp Lý Sau Xây", keyword: "checklist pháp lý sau xây", slug: "checklist-phap-ly-sau-xay-ngan", status: "done" },
  { no: 3327, title: "Hoàn Công Nhà Ở", keyword: "hoàn công nhà ở", slug: "hoan-cong-nha-o-ngan", status: "done" },
  { no: 3328, title: "Hồ Sơ Hoàn Công", keyword: "hồ sơ hoàn công", slug: "ho-so-hoan-cong-ngan", status: "done" },
  { no: 3329, title: "Thời Gian Hoàn Công", keyword: "thời gian hoàn công", slug: "thoi-gian-hoan-cong-ngan", status: "done" },
  { no: 3330, title: "Chi Phí Hoàn Công", keyword: "chi phí hoàn công", slug: "chi-phi-hoan-cong-ngan", status: "done" },
  { no: 3331, title: "Cập Nhật Sổ Sau Xây", keyword: "cập nhật sổ sau xây", slug: "cap-nhat-so-sau-xay-ngan", status: "done" },
  { no: 3332, title: "Đăng Ký Biến Động Đất Đai", keyword: "đăng ký biến động đất đai", slug: "dang-ky-bien-dong-dat-dai-ngan", status: "done" },
  { no: 3333, title: "Thuế Trước Bạ Nhà Đất", keyword: "thuế trước bạ nhà đất", slug: "thue-truoc-ba-nha-dat-ngan", status: "done" },
  { no: 3334, title: "Lệ Phí Trước Bạ Xây Mới", keyword: "lệ phí trước bạ xây mới", slug: "le-phi-truoc-ba-xay-moi-ngan", status: "done" },
  { no: 3335, title: "Giá Tính Thuế Nhà Ở", keyword: "giá tính thuế nhà ở", slug: "gia-tinh-thue-nha-o-ngan", status: "done" },
  { no: 3336, title: "Miễn Giảm Thuế Xây Nhà", keyword: "miễn giảm thuế xây nhà", slug: "mien-giam-thue-xay-nha-ngan", status: "done" },
  { no: 3337, title: "Rủi Ro Pháp Lý Xây Nhà", keyword: "rủi ro pháp lý xây nhà", slug: "rui-ro-phap-ly-xay-nha-ngan", status: "done" },
  { no: 3338, title: "Rủi Ro Tài Chính Xây Nhà", keyword: "rủi ro tài chính xây nhà", slug: "rui-ro-tai-chinh-xay-nha-ngan", status: "done" },
  { no: 3339, title: "Quản Lý Dòng Tiền Xây Nhà", keyword: "quản lý dòng tiền xây nhà", slug: "quan-ly-dong-tien-xay-nha-ngan", status: "done" },
  { no: 3340, title: "Escrow Thanh Toán Xây", keyword: "escrow thanh toán xây", slug: "escrow-thanh-toan-xay-ngan", status: "done" },
  { no: 3341, title: "Chứng Từ Thanh Toán Xây", keyword: "chứng từ thanh toán xây", slug: "chung-tu-thanh-toan-xay-ngan", status: "done" },
  { no: 3342, title: "Chủ Đề Mở Rộng 38 1", keyword: "chủ đề mở rộng 38 1", slug: "chu-de-mo-rong-38-1-ngan", status: "done" },
  { no: 3343, title: "Chủ Đề Mở Rộng 38 2", keyword: "chủ đề mở rộng 38 2", slug: "chu-de-mo-rong-38-2-ngan", status: "done" },
  { no: 3344, title: "Chủ Đề Mở Rộng 38 3", keyword: "chủ đề mở rộng 38 3", slug: "chu-de-mo-rong-38-3-ngan", status: "done" },
  { no: 3345, title: "Chủ Đề Mở Rộng 38 4", keyword: "chủ đề mở rộng 38 4", slug: "chu-de-mo-rong-38-4-ngan", status: "done" },
  { no: 3346, title: "Chủ Đề Mở Rộng 38 5", keyword: "chủ đề mở rộng 38 5", slug: "chu-de-mo-rong-38-5-ngan", status: "done" },
];
