/**
 * Lịch 100 từ khóa ngắn — batch 28 (#2247–#2346).
 * Cluster: geo phường/KĐT TP.HCM.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch28: ContentCalendarItem[] = [
  { no: 2247, title: "Xây Nhà Thảo Điền", keyword: "xây nhà Thảo Điền", slug: "xay-nha-thao-dien-ngan", status: "done" },
  { no: 2248, title: "Xây Nhà An Phú", keyword: "xây nhà An Phú", slug: "xay-nha-an-phu-ngan", status: "done" },
  { no: 2249, title: "Xây Nhà Bình An", keyword: "xây nhà Bình An", slug: "xay-nha-binh-an-ngan", status: "done" },
  { no: 2250, title: "Xây Nhà Cat Lai", keyword: "xây nhà Cát Lái", slug: "xay-nha-cat-lai-ngan", status: "done" },
  { no: 2251, title: "Xây Nhà Phú Hữu", keyword: "xây nhà Phú Hữu", slug: "xay-nha-phu-huu-ngan", status: "done" },
  { no: 2252, title: "Xây Nhà Tăng Nhơn Phú", keyword: "xây nhà Tăng Nhơn Phú", slug: "xay-nha-tang-nhon-phu-ngan", status: "done" },
  { no: 2253, title: "Xây Nhà Long Trường", keyword: "xây nhà Long Trường", slug: "xay-nha-long-truong-ngan", status: "done" },
  { no: 2254, title: "Xây Nhà Long Phước", keyword: "xây nhà Long Phước", slug: "xay-nha-long-phuoc-ngan", status: "done" },
  { no: 2255, title: "Xây Nhà Trường Thọ", keyword: "xây nhà Trường Thọ", slug: "xay-nha-truong-tho-ngan", status: "done" },
  { no: 2256, title: "Xây Nhà Bình Thọ", keyword: "xây nhà Bình Thọ", slug: "xay-nha-binh-tho-ngan", status: "done" },
  { no: 2257, title: "Xây Nhà Linh Chiểu", keyword: "xây nhà Linh Chiểu", slug: "xay-nha-linh-chieu-ngan", status: "done" },
  { no: 2258, title: "Xây Nhà Linh Trung", keyword: "xây nhà Linh Trung", slug: "xay-nha-linh-trung-ngan", status: "done" },
  { no: 2259, title: "Xây Nhà Linh Đông", keyword: "xây nhà Linh Đông", slug: "xay-nha-linh-dong-ngan", status: "done" },
  { no: 2260, title: "Xây Nhà Hiệp Phú", keyword: "xây nhà Hiệp Phú", slug: "xay-nha-hiep-phu-ngan", status: "done" },
  { no: 2261, title: "Xây Nhà Tân Phú Thủ Đức", keyword: "xây nhà Tân Phú Thủ Đức", slug: "xay-nha-tan-phu-thu-duc-ngan", status: "done" },
  { no: 2262, title: "Xây Nhà Phước Long", keyword: "xây nhà Phước Long", slug: "xay-nha-phuoc-long-ngan", status: "done" },
  { no: 2263, title: "Xây Nhà An Khánh", keyword: "xây nhà An Khánh", slug: "xay-nha-an-khanh-ngan", status: "done" },
  { no: 2264, title: "Xây Nhà Thủ Thiêm Mới", keyword: "xây nhà Thủ Thiêm mới", slug: "xay-nha-thu-thiem-moi-ngan", status: "done" },
  { no: 2265, title: "Xây Nhà Vinhomes", keyword: "xây nhà Vinhomes", slug: "xay-nha-vinhomes-ngan", status: "done" },
  { no: 2266, title: "Cải Tạo Nhà Vinhomes", keyword: "cải tạo nhà Vinhomes", slug: "cai-tao-nha-vinhomes-ngan", status: "done" },
  { no: 2267, title: "Xây Nhà KĐT Phú Mỹ Hưng", keyword: "xây nhà KĐT Phú Mỹ Hưng", slug: "xay-nha-kdt-phu-my-hung-ngan", status: "done" },
  { no: 2268, title: "Cải Tạo Nhà Phú Mỹ Hưng", keyword: "cải tạo nhà Phú Mỹ Hưng", slug: "cai-tao-nha-phu-my-hung-ngan", status: "done" },
  { no: 2269, title: "Xây Nhà Sala", keyword: "xây nhà Sala", slug: "xay-nha-sala-ngan", status: "done" },
  { no: 2270, title: "Xây Nhà Landmark", keyword: "xây nhà Landmark", slug: "xay-nha-landmark-ngan", status: "done" },
  { no: 2271, title: "Sửa Nhà Thảo Điền", keyword: "sửa nhà Thảo Điền", slug: "sua-nha-thao-dien-ngan", status: "done" },
  { no: 2272, title: "Sửa Nhà An Phú", keyword: "sửa nhà An Phú", slug: "sua-nha-an-phu-ngan", status: "done" },
  { no: 2273, title: "Cải Tạo Nhà Thảo Điền", keyword: "cải tạo nhà Thảo Điền", slug: "cai-tao-nha-thao-dien-ngan", status: "done" },
  { no: 2274, title: "Cải Tạo Nhà An Phú", keyword: "cải tạo nhà An Phú", slug: "cai-tao-nha-an-phu-ngan", status: "done" },
  { no: 2275, title: "Xây Nhà Trọn Gói Thảo Điền", keyword: "xây nhà trọn gói Thảo Điền", slug: "xay-nha-tron-goi-thao-dien-ngan", status: "done" },
  { no: 2276, title: "Xây Nhà Trọn Gói An Phú", keyword: "xây nhà trọn gói An Phú", slug: "xay-nha-tron-goi-an-phu-ngan", status: "done" },
  { no: 2277, title: "Xây Nhà Quận Bình Tân", keyword: "xây nhà quận Bình Tân", slug: "xay-nha-quan-binh-tan-ngan", status: "done" },
  { no: 2278, title: "Xây Nhà An Lạc", keyword: "xây nhà An Lạc", slug: "xay-nha-an-lac-ngan", status: "done" },
  { no: 2279, title: "Xây Nhà Bình Trị Đông", keyword: "xây nhà Bình Trị Đông", slug: "xay-nha-binh-tri-dong-ngan", status: "done" },
  { no: 2280, title: "Xây Nhà Tân Tạo", keyword: "xây nhà Tân Tạo", slug: "xay-nha-tan-tao-ngan", status: "done" },
  { no: 2281, title: "Xây Nhà Bình Hưng Hòa", keyword: "xây nhà Bình Hưng Hòa", slug: "xay-nha-binh-hung-hoa-ngan", status: "done" },
  { no: 2282, title: "Xây Nhà Sơn Kỳ", keyword: "xây nhà Sơn Kỳ", slug: "xay-nha-son-ky-ngan", status: "done" },
  { no: 2283, title: "Xây Nhà Tân Quý", keyword: "xây nhà Tân Quý", slug: "xay-nha-tan-quy-ngan", status: "done" },
  { no: 2284, title: "Xây Nhà Hòa Thạnh", keyword: "xây nhà Hòa Thạnh", slug: "xay-nha-hoa-thanh-ngan", status: "done" },
  { no: 2285, title: "Xây Nhà Phú Thọ Hòa", keyword: "xây nhà Phú Thọ Hòa", slug: "xay-nha-phu-tho-hoa-ngan", status: "done" },
  { no: 2286, title: "Xây Nhà Tây Thạnh", keyword: "xây nhà Tây Thạnh", slug: "xay-nha-tay-thanh-ngan", status: "done" },
  { no: 2287, title: "Xây Nhà Hiệp Thành", keyword: "xây nhà Hiệp Thành", slug: "xay-nha-hiep-thanh-ngan", status: "done" },
  { no: 2288, title: "Xây Nhà Thạnh Xuân", keyword: "xây nhà Thạnh Xuân", slug: "xay-nha-thanh-xuan-ngan", status: "done" },
  { no: 2289, title: "Xây Nhà Thạnh Lộc", keyword: "xây nhà Thạnh Lộc", slug: "xay-nha-thanh-loc-ngan", status: "done" },
  { no: 2290, title: "Xây Nhà An Phú Đông", keyword: "xây nhà An Phú Đông", slug: "xay-nha-an-phu-dong-ngan", status: "done" },
  { no: 2291, title: "Xây Nhà Trung Mỹ Tây", keyword: "xây nhà Trung Mỹ Tây", slug: "xay-nha-trung-my-tay-ngan", status: "done" },
  { no: 2292, title: "Xây Nhà Tân Chánh Hiệp", keyword: "xây nhà Tân Chánh Hiệp", slug: "xay-nha-tan-chanh-hiep-ngan", status: "done" },
  { no: 2293, title: "Xây Nhà Đông Hưng Thuận", keyword: "xây nhà Đông Hưng Thuận", slug: "xay-nha-dong-hung-thuan-ngan", status: "done" },
  { no: 2294, title: "Xây Nhà Tân Hưng Thuận", keyword: "xây nhà Tân Hưng Thuận", slug: "xay-nha-tan-hung-thuan-ngan", status: "done" },
  { no: 2295, title: "Xây Nhà Tân Thới Nhất", keyword: "xây nhà Tân Thới Nhất", slug: "xay-nha-tan-thoi-nhat-ngan", status: "done" },
  { no: 2296, title: "Xây Nhà Bà Điểm", keyword: "xây nhà Bà Điểm", slug: "xay-nha-ba-diem-ngan", status: "done" },
  { no: 2297, title: "Xây Nhà Xuân Thới Sơn", keyword: "xây nhà Xuân Thới Sơn", slug: "xay-nha-xuan-thoi-son-ngan", status: "done" },
  { no: 2298, title: "Xây Nhà Đông Thạnh", keyword: "xây nhà Đông Thạnh", slug: "xay-nha-dong-thanh-ngan", status: "done" },
  { no: 2299, title: "Xây Nhà Nhị Bình", keyword: "xây nhà Nhị Bình", slug: "xay-nha-nhi-binh-ngan", status: "done" },
  { no: 2300, title: "Xây Nhà Trung Chánh", keyword: "xây nhà Trung Chánh", slug: "xay-nha-trung-chanh-ngan", status: "done" },
  { no: 2301, title: "Xây Nhà Thới Tam Thôn", keyword: "xây nhà Thới Tam Thôn", slug: "xay-nha-thoi-tam-thon-ngan", status: "done" },
  { no: 2302, title: "Xây Nhà Xuân Thới Đông", keyword: "xây nhà Xuân Thới Đông", slug: "xay-nha-xuan-thoi-dong-ngan", status: "done" },
  { no: 2303, title: "Xây Nhà Tân Thới Nhì", keyword: "xây nhà Tân Thới Nhì", slug: "xay-nha-tan-thoi-nhi-ngan", status: "done" },
  { no: 2304, title: "Xây Nhà Xuân Thới Thượng", keyword: "xây nhà Xuân Thới Thượng", slug: "xay-nha-xuan-thoi-thuong-ngan", status: "done" },
  { no: 2305, title: "Xây Nhà Phạm Văn Hai", keyword: "xây nhà Phạm Văn Hai", slug: "xay-nha-pham-van-hai-ngan", status: "done" },
  { no: 2306, title: "Xây Nhà Vĩnh Lộc A", keyword: "xây nhà Vĩnh Lộc A", slug: "xay-nha-vinh-loc-a-ngan", status: "done" },
  { no: 2307, title: "Xây Nhà Vĩnh Lộc B", keyword: "xây nhà Vĩnh Lộc B", slug: "xay-nha-vinh-loc-b-ngan", status: "done" },
  { no: 2308, title: "Xây Nhà Bình Hưng", keyword: "xây nhà Bình Hưng", slug: "xay-nha-binh-hung-ngan", status: "done" },
  { no: 2309, title: "Xây Nhà Phong Phú", keyword: "xây nhà Phong Phú", slug: "xay-nha-phong-phu-ngan", status: "done" },
  { no: 2310, title: "Xây Nhà Đa Phước", keyword: "xây nhà Đa Phước", slug: "xay-nha-da-phuoc-ngan", status: "done" },
  { no: 2311, title: "Xây Nhà Hưng Long", keyword: "xây nhà Hưng Long", slug: "xay-nha-hung-long-ngan", status: "done" },
  { no: 2312, title: "Xây Nhà Quy Đức", keyword: "xây nhà Quy Đức", slug: "xay-nha-quy-duc-ngan", status: "done" },
  { no: 2313, title: "Xây Nhà An Phú Tây", keyword: "xây nhà An Phú Tây", slug: "xay-nha-an-phu-tay-ngan", status: "done" },
  { no: 2314, title: "Xây Nhà Tân Quý Tây", keyword: "xây nhà Tân Quý Tây", slug: "xay-nha-tan-quy-tay-ngan", status: "done" },
  { no: 2315, title: "Xây Nhà Bình Chánh Trung", keyword: "xây nhà Bình Chánh", slug: "xay-nha-binh-chanh-trung-ngan", status: "done" },
  { no: 2316, title: "Xây Nhà Nhà Bè Thị Trấn", keyword: "xây nhà Nhà Bè", slug: "xay-nha-nha-be-thi-tran-ngan", status: "done" },
  { no: 2317, title: "Xây Nhà Phú Xuân", keyword: "xây nhà Phú Xuân", slug: "xay-nha-phu-xuan-ngan", status: "done" },
  { no: 2318, title: "Xây Nhà Nhơn Đức", keyword: "xây nhà Nhơn Đức", slug: "xay-nha-nhon-duc-ngan", status: "done" },
  { no: 2319, title: "Xây Nhà Phước Kiển", keyword: "xây nhà Phước Kiển", slug: "xay-nha-phuoc-kien-ngan", status: "done" },
  { no: 2320, title: "Xây Nhà Phước Lộc", keyword: "xây nhà Phước Lộc", slug: "xay-nha-phuoc-loc-ngan", status: "done" },
  { no: 2321, title: "Xây Nhà Long Thới", keyword: "xây nhà Long Thới", slug: "xay-nha-long-thoi-ngan", status: "done" },
  { no: 2322, title: "Xây Nhà Hiệp Phước", keyword: "xây nhà Hiệp Phước", slug: "xay-nha-hiep-phuoc-ngan", status: "done" },
  { no: 2323, title: "Xây Nhà Cần Thạnh", keyword: "xây nhà Cần Thạnh", slug: "xay-nha-can-thanh-ngan", status: "done" },
  { no: 2324, title: "Xây Nhà Long Hòa", keyword: "xây nhà Long Hòa", slug: "xay-nha-long-hoa-ngan", status: "done" },
  { no: 2325, title: "Xây Nhà Tam Thôn Hiệp", keyword: "xây nhà Tam Thôn Hiệp", slug: "xay-nha-tam-thon-hiep-ngan", status: "done" },
  { no: 2326, title: "Xây Nhà An Thới Đông", keyword: "xây nhà An Thới Đông", slug: "xay-nha-an-thoi-dong-ngan", status: "done" },
  { no: 2327, title: "Xây Nhà Lý Nhơn", keyword: "xây nhà Lý Nhơn", slug: "xay-nha-ly-nhon-ngan", status: "done" },
  { no: 2328, title: "Xây Nhà Thạnh An", keyword: "xây nhà Thạnh An", slug: "xay-nha-thanh-an-ngan", status: "done" },
  { no: 2329, title: "Thiết Kế Nhà Thảo Điền", keyword: "thiết kế nhà Thảo Điền", slug: "thiet-ke-nha-thao-dien-ngan", status: "done" },
  { no: 2330, title: "Thiết Kế Nhà An Phú", keyword: "thiết kế nhà An Phú", slug: "thiet-ke-nha-an-phu-ngan", status: "done" },
  { no: 2331, title: "Báo Giá Xây Nhà Thảo Điền", keyword: "báo giá xây nhà Thảo Điền", slug: "bao-gia-xay-nha-thao-dien-ngan", status: "done" },
  { no: 2332, title: "Báo Giá Xây Nhà An Phú", keyword: "báo giá xây nhà An Phú", slug: "bao-gia-xay-nha-an-phu-ngan", status: "done" },
  { no: 2333, title: "Nhà Thầu Thảo Điền", keyword: "nhà thầu Thảo Điền", slug: "nha-thau-thao-dien-ngan", status: "done" },
  { no: 2334, title: "Nhà Thầu An Phú", keyword: "nhà thầu An Phú", slug: "nha-thau-an-phu-ngan", status: "done" },
  { no: 2335, title: "Nhà Thầu Thủ Đức", keyword: "nhà thầu Thủ Đức", slug: "nha-thau-thu-duc-ngan", status: "done" },
  { no: 2336, title: "Nhà Thầu Bình Tân", keyword: "nhà thầu Bình Tân", slug: "nha-thau-binh-tan-ngan", status: "done" },
  { no: 2337, title: "Nhà Thầu Quận 12", keyword: "nhà thầu Quận 12", slug: "nha-thau-quan-12-ngan", status: "done" },
  { no: 2338, title: "Nhà Thầu Hóc Môn", keyword: "nhà thầu Hóc Môn", slug: "nha-thau-hoc-mon-ngan", status: "done" },
  { no: 2339, title: "Nhà Thầu Bình Chánh", keyword: "nhà thầu Bình Chánh", slug: "nha-thau-binh-chanh-ngan", status: "done" },
  { no: 2340, title: "Nhà Thầu Nhà Bè", keyword: "nhà thầu Nhà Bè", slug: "nha-thau-nha-be-ngan", status: "done" },
  { no: 2341, title: "Nhà Thầu Củ Chi", keyword: "nhà thầu Củ Chi", slug: "nha-thau-cu-chi-ngan", status: "done" },
  { no: 2342, title: "Nhà Thầu Cần Giờ", keyword: "nhà thầu Cần Giờ", slug: "nha-thau-can-gio-ngan", status: "done" },
  { no: 2343, title: "Chủ Đề Mở Rộng 28 1", keyword: "chủ đề mở rộng 28 1", slug: "chu-de-mo-rong-28-1-ngan", status: "done" },
  { no: 2344, title: "Chủ Đề Mở Rộng 28 2", keyword: "chủ đề mở rộng 28 2", slug: "chu-de-mo-rong-28-2-ngan", status: "done" },
  { no: 2345, title: "Chủ Đề Mở Rộng 28 3", keyword: "chủ đề mở rộng 28 3", slug: "chu-de-mo-rong-28-3-ngan", status: "done" },
  { no: 2346, title: "Chủ Đề Mở Rộng 28 4", keyword: "chủ đề mở rộng 28 4", slug: "chu-de-mo-rong-28-4-ngan", status: "done" },
];
