/**
 * Lịch 100 từ khóa ngắn — batch 54 (#4847–#4946).
 * Cluster: so sánh gói, intent mua, Ads cuối funnel.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch54: ContentCalendarItem[] = [
  { no: 4847, title: "Gói Xây Nhà 3 Triệu m2", keyword: "gói xây nhà 3 triệu m2", slug: "goi-xay-nha-3-trieu-m2-ads4-ngan", status: "done" },
  { no: 4848, title: "Gói Xây Nhà 4 Triệu m2", keyword: "gói xây nhà 4 triệu m2", slug: "goi-xay-nha-4-trieu-m2-ads4-ngan", status: "done" },
  { no: 4849, title: "Gói Xây Nhà 5 Triệu m2", keyword: "gói xây nhà 5 triệu m2", slug: "goi-xay-nha-5-trieu-m2-ads4-ngan", status: "done" },
  { no: 4850, title: "Gói Xây Nhà 6 Triệu m2", keyword: "gói xây nhà 6 triệu m2", slug: "goi-xay-nha-6-trieu-m2-ads4-ngan", status: "done" },
  { no: 4851, title: "Gói Xây Nhà 7 Triệu m2", keyword: "gói xây nhà 7 triệu m2", slug: "goi-xay-nha-7-trieu-m2-ads4-ngan", status: "done" },
  { no: 4852, title: "Gói Xây Nhà 8 Triệu m2", keyword: "gói xây nhà 8 triệu m2", slug: "goi-xay-nha-8-trieu-m2-ads4-ngan", status: "done" },
  { no: 4853, title: "Gói Thô 3 Triệu m2", keyword: "gói thô 3 triệu m2", slug: "goi-tho-3-trieu-m2-ads4-ngan", status: "done" },
  { no: 4854, title: "Gói Thô 3.5 Triệu m2", keyword: "gói thô 3.5 triệu m2", slug: "goi-tho-3-5-trieu-m2-ads4-ngan", status: "done" },
  { no: 4855, title: "Gói Thô 4 Triệu m2", keyword: "gói thô 4 triệu m2", slug: "goi-tho-4-trieu-m2-ads4-ngan", status: "done" },
  { no: 4856, title: "Gói Hoàn Thiện 2 Triệu m2", keyword: "gói hoàn thiện 2 triệu m2", slug: "goi-hoan-thien-2-trieu-m2-ads4-ngan", status: "done" },
  { no: 4857, title: "Gói Hoàn Thiện 3 Triệu m2", keyword: "gói hoàn thiện 3 triệu m2", slug: "goi-hoan-thien-3-trieu-m2-ads4-ngan", status: "done" },
  { no: 4858, title: "Gói Hoàn Thiện 4 Triệu m2", keyword: "gói hoàn thiện 4 triệu m2", slug: "goi-hoan-thien-4-trieu-m2-ads4-ngan", status: "done" },
  { no: 4859, title: "So Sánh Gói 5 Triệu Và 6 Triệu", keyword: "so sánh gói 5 triệu và 6 triệu", slug: "so-sanh-goi-5-va-6-trieu-ads4-ngan", status: "done" },
  { no: 4860, title: "So Sánh Gói 6 Triệu Và 7 Triệu", keyword: "so sánh gói 6 triệu và 7 triệu", slug: "so-sanh-goi-6-va-7-trieu-ads4-ngan", status: "done" },
  { no: 4861, title: "Gói Nào Phù Hợp Ngân Sách 2 Tỷ", keyword: "gói nào phù hợp ngân sách 2 tỷ", slug: "goi-nao-phu-hop-2-ty-ads4-ngan", status: "done" },
  { no: 4862, title: "Gói Nào Phù Hợp Ngân Sách 3 Tỷ", keyword: "gói nào phù hợp ngân sách 3 tỷ", slug: "goi-nao-phu-hop-3-ty-ads4-ngan", status: "done" },
  { no: 4863, title: "Gói Nào Phù Hợp Ngân Sách 5 Tỷ", keyword: "gói nào phù hợp ngân sách 5 tỷ", slug: "goi-nao-phu-hop-5-ty-ads4-ngan", status: "done" },
  { no: 4864, title: "Báo Giá Chi Tiết Theo Gói", keyword: "báo giá chi tiết theo gói", slug: "bao-gia-chi-tiet-theo-goi-ads4-ngan", status: "done" },
  { no: 4865, title: "Báo Giá Minh Bạch Xây Nhà", keyword: "báo giá minh bạch xây nhà", slug: "bao-gia-minh-bach-xay-nha-ads4-ngan", status: "done" },
  { no: 4866, title: "Báo Giá Không Ẩn Phí", keyword: "báo giá không ẩn phí", slug: "bao-gia-khong-an-phi-ads4-ngan", status: "done" },
  { no: 4867, title: "Nhận Báo Giá Miễn Phí Ngay", keyword: "nhận báo giá miễn phí ngay", slug: "nhan-bao-gia-mien-phi-ngay-ads4-ngan", status: "done" },
  { no: 4868, title: "So Báo Giá 3 Nhà Thầu", keyword: "so báo giá 3 nhà thầu", slug: "so-bao-gia-3-nha-thau-ads4-ngan", status: "done" },
  { no: 4869, title: "Tư Vấn Chọn Gói Xây", keyword: "tư vấn chọn gói xây", slug: "tu-van-chon-goi-xay-ads4-ngan", status: "done" },
  { no: 4870, title: "Tư Vấn Chọn Gói Cải Tạo", keyword: "tư vấn chọn gói cải tạo", slug: "tu-van-chon-goi-cai-tao-ads4-ngan", status: "done" },
  { no: 4871, title: "Đặt Cọc Giữ Chỗ Xây", keyword: "đặt cọc giữ chỗ xây", slug: "dat-coc-giu-cho-xay-ads4-ngan", status: "done" },
  { no: 4872, title: "Ký Hợp Đồng Xây Online", keyword: "ký hợp đồng xây online", slug: "ky-hop-dong-xay-online-ads4-ngan", status: "done" },
  { no: 4873, title: "Thanh Toán Linh Hoạt Xây", keyword: "thanh toán linh hoạt xây", slug: "thanh-toan-linh-hoat-xay-ads4-ngan", status: "done" },
  { no: 4874, title: "Trả Góp Xây Nhà", keyword: "trả góp xây nhà", slug: "tra-gop-xay-nha-ads4-ngan", status: "done" },
  { no: 4875, title: "Hỗ Trợ Vay Xây Nhà", keyword: "hỗ trợ vay xây nhà", slug: "ho-tro-vay-xay-nha-ads4-ngan", status: "done" },
  { no: 4876, title: "Ưu Đãi Ký Hợp Đồng Tháng Này", keyword: "ưu đãi ký hợp đồng tháng này", slug: "uu-dai-ky-hop-dong-thang-nay-ads4-ngan", status: "done" },
  { no: 4877, title: "Giảm Giá Thiết Kế Khi Xây", keyword: "giảm giá thiết kế khi xây", slug: "giam-gia-thiet-ke-khi-xay-ads4-ngan", status: "done" },
  { no: 4878, title: "Tặng Nội Thất Cơ Bản", keyword: "tặng nội thất cơ bản", slug: "tang-noi-that-co-ban-ads4-ngan", status: "done" },
  { no: 4879, title: "Tặng Chống Thấm Cao Cấp", keyword: "tặng chống thấm cao cấp", slug: "tang-chong-tham-cao-cap-ads4-ngan", status: "done" },
  { no: 4880, title: "Tặng Bảo Hành Mở Rộng", keyword: "tặng bảo hành mở rộng", slug: "tang-bao-hanh-mo-rong-ads4-ngan", status: "done" },
  { no: 4881, title: "Slot Thi Công Còn Bao Nhiêu", keyword: "slot thi công còn bao nhiêu", slug: "slot-thi-cong-con-bao-nhieu-ads4-ngan", status: "done" },
  { no: 4882, title: "Đặt Lịch Khảo Sát Hôm Nay", keyword: "đặt lịch khảo sát hôm nay", slug: "dat-lich-khao-sat-hom-nay-ads4-ngan", status: "done" },
  { no: 4883, title: "Khảo Sát Trong 24h", keyword: "khảo sát trong 24h", slug: "khao-sat-trong-24h-ads4-ngan", status: "done" },
  { no: 4884, title: "Báo Giá Trong 48h", keyword: "báo giá trong 48h", slug: "bao-gia-trong-48h-ads4-ngan", status: "done" },
  { no: 4885, title: "Ký Hợp Đồng Trong Tuần", keyword: "ký hợp đồng trong tuần", slug: "ky-hop-dong-trong-tuan-ads4-ngan", status: "done" },
  { no: 4886, title: "Khởi Công Trong 15 Ngày", keyword: "khởi công trong 15 ngày", slug: "khoi-cong-trong-15-ngay-ads4-ngan", status: "done" },
  { no: 4887, title: "Công Trình Đang Thi Công", keyword: "công trình đang thi công", slug: "cong-trinh-dang-thi-cong-ads4-ngan", status: "done" },
  { no: 4888, title: "Xem Công Trình Thực Tế", keyword: "xem công trình thực tế", slug: "xem-cong-trinh-thuc-te-ads4-ngan", status: "done" },
  { no: 4889, title: "Tour Công Trình Cuối Tuần", keyword: "tour công trình cuối tuần", slug: "tour-cong-trinh-cuoi-tuan-ads4-ngan", status: "done" },
  { no: 4890, title: "Open House Cuối Tháng", keyword: "open house cuối tháng", slug: "open-house-cuoi-thang-ads4-ngan", status: "done" },
  { no: 4891, title: "Testimonial Video Khách", keyword: "testimonial video khách", slug: "testimonial-video-khach-ads4-ngan", status: "done" },
  { no: 4892, title: "Review 5 Sao Xây Nhà", keyword: "review 5 sao xây nhà", slug: "review-5-sao-xay-nha-ads4-ngan", status: "done" },
  { no: 4893, title: "Khách Hàng Quanh Quận Tôi", keyword: "khách hàng quanh quận tôi", slug: "khach-hang-quanh-quan-toi-ads4-ngan", status: "done" },
  { no: 4894, title: "Dự Án Gần Khu Vực Bạn", keyword: "dự án gần khu vực bạn", slug: "du-an-gan-khu-vuc-ban-ads4-ngan", status: "done" },
  { no: 4895, title: "Nhà Thầu Uy Tín Gần Bạn", keyword: "nhà thầu uy tín gần bạn", slug: "nha-thau-uy-tin-gan-ban-ads4-ngan", status: "done" },
  { no: 4896, title: "Công Ty Xây Có Giấy Phép", keyword: "công ty xây có giấy phép", slug: "cong-ty-xay-co-giay-phep-ads4-ngan", status: "done" },
  { no: 4897, title: "Công Ty Xây Có Bảo Hiểm", keyword: "công ty xây có bảo hiểm", slug: "cong-ty-xay-co-bao-hiem-ads4-ngan", status: "done" },
  { no: 4898, title: "Công Ty Xây Có Showroom", keyword: "công ty xây có showroom", slug: "cong-ty-xay-co-showroom-ads4-ngan", status: "done" },
  { no: 4899, title: "Sao Khuê Có Gì Khác", keyword: "sao khuê có gì khác", slug: "sao-khue-co-gi-khac-ads4-ngan", status: "done" },
  { no: 4900, title: "Vì Sao Chọn Sao Khuê", keyword: "vì sao chọn sao khuê", slug: "vi-sao-chon-sao-khue-ads4-ngan", status: "done" },
  { no: 4901, title: "Cam Kết Của Sao Khuê", keyword: "cam kết của sao khuê", slug: "cam-ket-cua-sao-khue-ads4-ngan", status: "done" },
  { no: 4902, title: "Quy Trình Sao Khuê 5 Bước", keyword: "quy trình sao khuê 5 bước", slug: "quy-trinh-sao-khue-5-buoc-ads4-ngan", status: "done" },
  { no: 4903, title: "Liên Hệ Sao Khuê Ngay", keyword: "liên hệ sao khuê ngay", slug: "lien-he-sao-khue-ngay-ads4-ngan", status: "done" },
  { no: 4904, title: "Zalo Sao Khuê", keyword: "zalo sao khuê", slug: "zalo-sao-khue-ads4-ngan", status: "done" },
  { no: 4905, title: "Hotline Sao Khuê", keyword: "hotline sao khuê", slug: "hotline-sao-khue-ads4-ngan", status: "done" },
  { no: 4906, title: "Email Sao Khuê", keyword: "email sao khuê", slug: "email-sao-khue-ads4-ngan", status: "done" },
  { no: 4907, title: "Form Liên Hệ Xây Nhà", keyword: "form liên hệ xây nhà", slug: "form-lien-he-xay-nha-ads4-ngan", status: "done" },
  { no: 4908, title: "Form Liên Hệ Cải Tạo", keyword: "form liên hệ cải tạo", slug: "form-lien-he-cai-tao-ads4-ngan", status: "done" },
  { no: 4909, title: "CTA Nhận Tư Vấn Miễn Phí", keyword: "cta nhận tư vấn miễn phí", slug: "cta-nhan-tu-van-mien-phi-ads4-ngan", status: "done" },
  { no: 4910, title: "CTA Đặt Khảo Sát", keyword: "cta đặt khảo sát", slug: "cta-dat-khao-sat-ads4-ngan", status: "done" },
  { no: 4911, title: "CTA Xem Bảng Giá", keyword: "cta xem bảng giá", slug: "cta-xem-bang-gia-ads4-ngan", status: "done" },
  { no: 4912, title: "CTA Tải Checklist Xây", keyword: "cta tải checklist xây", slug: "cta-tai-checklist-xay-ads4-ngan", status: "done" },
  { no: 4913, title: "CTA Tải Mẫu Hợp Đồng", keyword: "cta tải mẫu hợp đồng", slug: "cta-tai-mau-hop-dong-ads4-ngan", status: "done" },
  { no: 4914, title: "Lead Magnet Xây Nhà", keyword: "lead magnet xây nhà", slug: "lead-magnet-xay-nha-ads4-ngan", status: "done" },
  { no: 4915, title: "Ebook Xây Nhà Miễn Phí", keyword: "ebook xây nhà miễn phí", slug: "ebook-xay-nha-mien-phi-ads4-ngan", status: "done" },
  { no: 4916, title: "Webinar Tư Vấn Xây 2026", keyword: "webinar tư vấn xây 2026", slug: "webinar-tu-van-xay-2026-ads4-ngan", status: "done" },
  { no: 4917, title: "Consultation Call Xây", keyword: "consultation call xây", slug: "consultation-call-xay-ads4-ngan", status: "done" },
  { no: 4918, title: "Discovery Call Cải Tạo", keyword: "discovery call cải tạo", slug: "discovery-call-cai-tao-ads4-ngan", status: "done" },
  { no: 4919, title: "Proposal Xây Nhà PDF", keyword: "proposal xây nhà pdf", slug: "proposal-xay-nha-pdf-ads4-ngan", status: "done" },
  { no: 4920, title: "Quotation Xây Nhà Excel", keyword: "quotation xây nhà excel", slug: "quotation-xay-nha-excel-ads4-ngan", status: "done" },
  { no: 4921, title: "Compare Quotes Xây Nhà", keyword: "compare quotes xây nhà", slug: "compare-quotes-xay-nha-ads4-ngan", status: "done" },
  { no: 4922, title: "Ready To Build 2026", keyword: "ready to build 2026", slug: "ready-to-build-2026-ads4-ngan", status: "done" },
  { no: 4923, title: "Start Building Today", keyword: "start building today", slug: "start-building-today-ads4-ngan", status: "done" },
  { no: 4924, title: "Renovate Now 2026", keyword: "renovate now 2026", slug: "renovate-now-2026-ads4-ngan", status: "done" },
  { no: 4925, title: "Get Started Xây Nhà", keyword: "get started xây nhà", slug: "get-started-xay-nha-ads4-ngan", status: "done" },
  { no: 4926, title: "Talk To Expert Xây", keyword: "talk to expert xây", slug: "talk-to-expert-xay-ads4-ngan", status: "done" },
  { no: 4927, title: "Book Free Consult", keyword: "book free consult", slug: "book-free-consult-ads4-ngan", status: "done" },
  { no: 4928, title: "Limited Offer Xây Nhà", keyword: "limited offer xây nhà", slug: "limited-offer-xay-nha-ads4-ngan", status: "done" },
  { no: 4929, title: "Last Slots This Month", keyword: "last slots this month", slug: "last-slots-this-month-ads4-ngan", status: "done" },
  { no: 4930, title: "Act Now Xây Nhà", keyword: "act now xây nhà", slug: "act-now-xay-nha-ads4-ngan", status: "done" },
  { no: 4931, title: "Don't Wait Xây Nhà", keyword: "dont wait xây nhà", slug: "dont-wait-xay-nha-ads4-ngan", status: "done" },
  { no: 4932, title: "Final CTA Sao Khuê", keyword: "final cta sao khuê", slug: "final-cta-sao-khue-ads4-ngan", status: "done" },
  { no: 4933, title: "Chủ Đề Mở Rộng 54 1", keyword: "chủ đề mở rộng 54 1", slug: "chu-de-mo-rong-54-1-ngan", status: "done" },
  { no: 4934, title: "Chủ Đề Mở Rộng 54 2", keyword: "chủ đề mở rộng 54 2", slug: "chu-de-mo-rong-54-2-ngan", status: "done" },
  { no: 4935, title: "Chủ Đề Mở Rộng 54 3", keyword: "chủ đề mở rộng 54 3", slug: "chu-de-mo-rong-54-3-ngan", status: "done" },
  { no: 4936, title: "Chủ Đề Mở Rộng 54 4", keyword: "chủ đề mở rộng 54 4", slug: "chu-de-mo-rong-54-4-ngan", status: "done" },
  { no: 4937, title: "Chủ Đề Mở Rộng 54 5", keyword: "chủ đề mở rộng 54 5", slug: "chu-de-mo-rong-54-5-ngan", status: "done" },
  { no: 4938, title: "Chủ Đề Mở Rộng 54 6", keyword: "chủ đề mở rộng 54 6", slug: "chu-de-mo-rong-54-6-ngan", status: "done" },
  { no: 4939, title: "Chủ Đề Mở Rộng 54 7", keyword: "chủ đề mở rộng 54 7", slug: "chu-de-mo-rong-54-7-ngan", status: "done" },
  { no: 4940, title: "Chủ Đề Mở Rộng 54 8", keyword: "chủ đề mở rộng 54 8", slug: "chu-de-mo-rong-54-8-ngan", status: "done" },
  { no: 4941, title: "Chủ Đề Mở Rộng 54 9", keyword: "chủ đề mở rộng 54 9", slug: "chu-de-mo-rong-54-9-ngan", status: "done" },
  { no: 4942, title: "Chủ Đề Mở Rộng 54 10", keyword: "chủ đề mở rộng 54 10", slug: "chu-de-mo-rong-54-10-ngan", status: "done" },
  { no: 4943, title: "Chủ Đề Mở Rộng 54 11", keyword: "chủ đề mở rộng 54 11", slug: "chu-de-mo-rong-54-11-ngan", status: "done" },
  { no: 4944, title: "Chủ Đề Mở Rộng 54 12", keyword: "chủ đề mở rộng 54 12", slug: "chu-de-mo-rong-54-12-ngan", status: "done" },
  { no: 4945, title: "Chủ Đề Mở Rộng 54 13", keyword: "chủ đề mở rộng 54 13", slug: "chu-de-mo-rong-54-13-ngan", status: "done" },
  { no: 4946, title: "Chủ Đề Mở Rộng 54 14", keyword: "chủ đề mở rộng 54 14", slug: "chu-de-mo-rong-54-14-ngan", status: "done" },
];
