/**
 * Lịch 100 từ khóa ngắn — batch 48 (#4247–#4346).
 * Cluster: quản lý dự án, giám sát, tiến độ chuyên sâu.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch48: ContentCalendarItem[] = [
  { no: 4247, title: "Quản Lý Dự Án Xây Nhà", keyword: "quản lý dự án xây nhà", slug: "quan-ly-du-an-xay-nha-pm-ngan", status: "done" },
  { no: 4248, title: "Project Manager Xây Nhà", keyword: "project manager xây nhà", slug: "project-manager-xay-nha-pm-ngan", status: "done" },
  { no: 4249, title: "Lập Kế Hoạch Xây Nhà", keyword: "lập kế hoạch xây nhà", slug: "lap-ke-hoach-xay-nha-pm-ngan", status: "done" },
  { no: 4250, title: "Lập Tiến Độ Gantt Xây", keyword: "lập tiến độ gantt xây", slug: "lap-tien-do-gantt-xay-pm-ngan", status: "done" },
  { no: 4251, title: "Critical Path Xây Nhà", keyword: "critical path xây nhà", slug: "critical-path-xay-nha-pm-ngan", status: "done" },
  { no: 4252, title: "Milestone Xây Nhà", keyword: "milestone xây nhà", slug: "milestone-xay-nha-pm-ngan", status: "done" },
  { no: 4253, title: "Baseline Tiến Độ Xây", keyword: "baseline tiến độ xây", slug: "baseline-tien-do-xay-pm-ngan", status: "done" },
  { no: 4254, title: "Cập Nhật Tiến Độ Hàng Tuần", keyword: "cập nhật tiến độ hàng tuần", slug: "cap-nhat-tien-do-hang-tuan-pm-ngan", status: "done" },
  { no: 4255, title: "Báo Cáo Tiến Độ Chủ Nhà", keyword: "báo cáo tiến độ chủ nhà", slug: "bao-cao-tien-do-chu-nha-pm-ngan", status: "done" },
  { no: 4256, title: "Họp Hiện Trường Xây", keyword: "họp hiện trường xây", slug: "hop-hien-truong-xay-pm-ngan", status: "done" },
  { no: 4257, title: "Biên Bản Họp Công Trình", keyword: "biên bản họp công trình", slug: "bien-ban-hop-cong-trinh-pm-ngan", status: "done" },
  { no: 4258, title: "RFI Công Trình Xây", keyword: "rfi công trình xây", slug: "rfi-cong-trinh-xay-pm-ngan", status: "done" },
  { no: 4259, title: "Submittal Vật Tư Xây", keyword: "submittal vật tư xây", slug: "submittal-vat-tu-xay-pm-ngan", status: "done" },
  { no: 4260, title: "Shop Drawing Nhà Phố", keyword: "shop drawing nhà phố", slug: "shop-drawing-nha-pho-pm-ngan", status: "done" },
  { no: 4261, title: "Change Order Xây Nhà", keyword: "change order xây nhà", slug: "change-order-xay-nha-pm-ngan", status: "done" },
  { no: 4262, title: "Variation Order Xây", keyword: "variation order xây", slug: "variation-order-xay-pm-ngan", status: "done" },
  { no: 4263, title: "Claim Phát Sinh Xây", keyword: "claim phát sinh xây", slug: "claim-phat-sinh-xay-pm-ngan", status: "done" },
  { no: 4264, title: "EOT Gia Hạn Tiến Độ", keyword: "eot gia hạn tiến độ", slug: "eot-gia-han-tien-do-pm-ngan", status: "done" },
  { no: 4265, title: "Risk Register Xây Nhà", keyword: "risk register xây nhà", slug: "risk-register-xay-nha-pm-ngan", status: "done" },
  { no: 4266, title: "Quản Lý Rủi Ro Công Trình", keyword: "quản lý rủi ro công trình", slug: "quan-ly-rui-ro-cong-trinh-pm-ngan", status: "done" },
  { no: 4267, title: "Quản Lý Chi Phí Công Trình", keyword: "quản lý chi phí công trình", slug: "quan-ly-chi-phi-cong-trinh-pm-ngan", status: "done" },
  { no: 4268, title: "Cost Control Xây Nhà", keyword: "cost control xây nhà", slug: "cost-control-xay-nha-pm-ngan", status: "done" },
  { no: 4269, title: "Earned Value Xây Nhà", keyword: "earned value xây nhà", slug: "earned-value-xay-nha-pm-ngan", status: "done" },
  { no: 4270, title: "Cash Flow Xây Nhà", keyword: "cash flow xây nhà", slug: "cash-flow-xay-nha-pm-ngan", status: "done" },
  { no: 4271, title: "Bill of Quantities Nhà", keyword: "bill of quantities nhà", slug: "bill-of-quantities-nha-pm-ngan", status: "done" },
  { no: 4272, title: "Đo Bóc Khối Lượng Xây", keyword: "đo bóc khối lượng xây", slug: "do-boc-khoi-luong-xay-pm-ngan", status: "done" },
  { no: 4273, title: "Nghiệm Thu Khối Lượng", keyword: "nghiệm thu khối lượng", slug: "nghiem-thu-khoi-luong-pm-ngan", status: "done" },
  { no: 4274, title: "Thanh Toán Theo Khối Lượng", keyword: "thanh toán theo khối lượng", slug: "thanh-toan-theo-khoi-luong-pm-ngan", status: "done" },
  { no: 4275, title: "Giám Sát Thi Công Nhà Phố", keyword: "giám sát thi công nhà phố", slug: "giam-sat-thi-cong-nha-pho-pm-ngan", status: "done" },
  { no: 4276, title: "Giám Sát Hiện Trường", keyword: "giám sát hiện trường", slug: "giam-sat-hien-truong-pm-ngan", status: "done" },
  { no: 4277, title: "Giám Sát Chất Lượng", keyword: "giám sát chất lượng", slug: "giam-sat-chat-luong-pm-ngan", status: "done" },
  { no: 4278, title: "Giám Sát An Toàn", keyword: "giám sát an toàn", slug: "giam-sat-an-toan-pm-ngan", status: "done" },
  { no: 4279, title: "Tư Vấn Giám Sát Độc Lập", keyword: "tư vấn giám sát độc lập", slug: "tu-van-giam-sat-doc-lap-pm-ngan", status: "done" },
  { no: 4280, title: "Chủ Nhiệm Dự Án Xây", keyword: "chủ nhiệm dự án xây", slug: "chu-nhiem-du-an-xay-pm-ngan", status: "done" },
  { no: 4281, title: "Chỉ Huy Trưởng Công Trình", keyword: "chỉ huy trưởng công trình", slug: "chi-huy-truong-cong-trinh-pm-ngan", status: "done" },
  { no: 4282, title: "Đội Ngũ Thi Công Nhà Phố", keyword: "đội ngũ thi công nhà phố", slug: "doi-ngu-thi-cong-nha-pho-pm-ngan", status: "done" },
  { no: 4283, title: "Phân Công Nhân Lực Xây", keyword: "phân công nhân lực xây", slug: "phan-cong-nhan-luc-xay-pm-ngan", status: "done" },
  { no: 4284, title: "Quản Lý Nhà Thầu Phụ", keyword: "quản lý nhà thầu phụ", slug: "quan-ly-nha-thau-phu-pm-ngan", status: "done" },
  { no: 4285, title: "Coordination MEP Xây", keyword: "coordination mep xây", slug: "coordination-mep-xay-pm-ngan", status: "done" },
  { no: 4286, title: "Clash Detection Bản Vẽ", keyword: "clash detection bản vẽ", slug: "clash-detection-ban-ve-pm-ngan", status: "done" },
  { no: 4287, title: "BIM Nhà Phố Cơ Bản", keyword: "bim nhà phố cơ bản", slug: "bim-nha-pho-co-ban-pm-ngan", status: "done" },
  { no: 4288, title: "Revit Nhà Phố", keyword: "revit nhà phố", slug: "revit-nha-pho-pm-ngan", status: "done" },
  { no: 4289, title: "App Quản Lý Công Trình", keyword: "app quản lý công trình", slug: "app-quan-ly-cong-trinh-pm-ngan", status: "done" },
  { no: 4290, title: "Phần Mềm Tiến Độ Xây", keyword: "phần mềm tiến độ xây", slug: "phan-mem-tien-do-xay-pm-ngan", status: "done" },
  { no: 4291, title: "Photo Log Công Trình", keyword: "photo log công trình", slug: "photo-log-cong-trinh-pm-ngan", status: "done" },
  { no: 4292, title: "Drone Survey Công Trình", keyword: "drone survey công trình", slug: "drone-survey-cong-trinh-pm-ngan", status: "done" },
  { no: 4293, title: "Time Lapse Công Trình", keyword: "time lapse công trình", slug: "time-lapse-cong-trinh-pm-ngan", status: "done" },
  { no: 4294, title: "Daily Report Công Trình", keyword: "daily report công trình", slug: "daily-report-cong-trinh-pm-ngan", status: "done" },
  { no: 4295, title: "Weekly Report Công Trình", keyword: "weekly report công trình", slug: "weekly-report-cong-trinh-pm-ngan", status: "done" },
  { no: 4296, title: "Punch List Cuối Công Trình", keyword: "punch list cuối công trình", slug: "punch-list-cuoi-cong-trinh-pm-ngan", status: "done" },
  { no: 4297, title: "Snagging Trước Bàn Giao", keyword: "snagging trước bàn giao", slug: "snagging-truoc-ban-giao-pm-ngan", status: "done" },
  { no: 4298, title: "Commissioning Hệ Thống", keyword: "commissioning hệ thống", slug: "commissioning-he-thong-pm-ngan", status: "done" },
  { no: 4299, title: "Handover Package Nhà", keyword: "handover package nhà", slug: "handover-package-nha-pm-ngan", status: "done" },
  { no: 4300, title: "As Built Drawing Bàn Giao", keyword: "as built drawing bàn giao", slug: "as-built-drawing-ban-giao-pm-ngan", status: "done" },
  { no: 4301, title: "O&M Manual Bàn Giao", keyword: "o&m manual bàn giao", slug: "om-manual-ban-giao-pm-ngan", status: "done" },
  { no: 4302, title: "Warranty Certificate Nhà", keyword: "warranty certificate nhà", slug: "warranty-certificate-nha-pm-ngan", status: "done" },
  { no: 4303, title: "Defect Liability Period", keyword: "defect liability period", slug: "defect-liability-period-pm-ngan", status: "done" },
  { no: 4304, title: "Retention Money Xây Nhà", keyword: "retention money xây nhà", slug: "retention-money-xay-nha-pm-ngan", status: "done" },
  { no: 4305, title: "Final Account Xây Nhà", keyword: "final account xây nhà", slug: "final-account-xay-nha-pm-ngan", status: "done" },
  { no: 4306, title: "Close Out Dự Án Xây", keyword: "close out dự án xây", slug: "close-out-du-an-xay-pm-ngan", status: "done" },
  { no: 4307, title: "Lesson Learned Xây Nhà", keyword: "lesson learned xây nhà", slug: "lesson-learned-xay-nha-pm-ngan", status: "done" },
  { no: 4308, title: "KPI Nhà Thầu Xây", keyword: "kpi nhà thầu xây", slug: "kpi-nha-thau-xay-pm-ngan", status: "done" },
  { no: 4309, title: "Scorecard Đánh Giá Thầu", keyword: "scorecard đánh giá thầu", slug: "scorecard-danh-gia-thau-pm-ngan", status: "done" },
  { no: 4310, title: "Vendor Evaluation Xây", keyword: "vendor evaluation xây", slug: "vendor-evaluation-xay-pm-ngan", status: "done" },
  { no: 4311, title: "Prequalification Nhà Thầu", keyword: "prequalification nhà thầu", slug: "prequalification-nha-thau-pm-ngan", status: "done" },
  { no: 4312, title: "Tender Package Xây Nhà", keyword: "tender package xây nhà", slug: "tender-package-xay-nha-pm-ngan", status: "done" },
  { no: 4313, title: "So Thầu Xây Nhà", keyword: "so thầu xây nhà", slug: "so-thau-xay-nha-pm-ngan", status: "done" },
  { no: 4314, title: "Negotiating Hợp Đồng Xây", keyword: "negotiating hợp đồng xây", slug: "negotiating-hop-dong-xay-pm-ngan", status: "done" },
  { no: 4315, title: "Kick Off Meeting Xây", keyword: "kick off meeting xây", slug: "kick-off-meeting-xay-pm-ngan", status: "done" },
  { no: 4316, title: "Site Induction Công Trình", keyword: "site induction công trình", slug: "site-induction-cong-trinh-pm-ngan", status: "done" },
  { no: 4317, title: "Method Statement Xây", keyword: "method statement xây", slug: "method-statement-xay-pm-ngan", status: "done" },
  { no: 4318, title: "ITP Inspection Test Plan", keyword: "itp inspection test plan", slug: "itp-inspection-test-plan-pm-ngan", status: "done" },
  { no: 4319, title: "NCR Non Conformance", keyword: "ncr non conformance", slug: "ncr-non-conformance-pm-ngan", status: "done" },
  { no: 4320, title: "CAR Corrective Action", keyword: "car corrective action", slug: "car-corrective-action-pm-ngan", status: "done" },
  { no: 4321, title: "Toolbox Talk Công Trình", keyword: "toolbox talk công trình", slug: "toolbox-talk-cong-trinh-pm-ngan", status: "done" },
  { no: 4322, title: "Permit To Work Công Trình", keyword: "permit to work công trình", slug: "permit-to-work-cong-trinh-pm-ngan", status: "done" },
  { no: 4323, title: "Hot Work Permit Xây", keyword: "hot work permit xây", slug: "hot-work-permit-xay-pm-ngan", status: "done" },
  { no: 4324, title: "Lifting Plan Công Trình", keyword: "lifting plan công trình", slug: "lifting-plan-cong-trinh-pm-ngan", status: "done" },
  { no: 4325, title: "Traffic Management Site", keyword: "traffic management site", slug: "traffic-management-site-pm-ngan", status: "done" },
  { no: 4326, title: "Waste Management Site", keyword: "waste management site", slug: "waste-management-site-pm-ngan", status: "done" },
  { no: 4327, title: "Environmental Plan Xây", keyword: "environmental plan xây", slug: "environmental-plan-xay-pm-ngan", status: "done" },
  { no: 4328, title: "Quality Plan Xây Nhà", keyword: "quality plan xây nhà", slug: "quality-plan-xay-nha-pm-ngan", status: "done" },
  { no: 4329, title: "HSE Plan Công Trình", keyword: "hse plan công trình", slug: "hse-plan-cong-trinh-pm-ngan", status: "done" },
  { no: 4330, title: "Emergency Response Site", keyword: "emergency response site", slug: "emergency-response-site-pm-ngan", status: "done" },
  { no: 4331, title: "First Aid Công Trình", keyword: "first aid công trình", slug: "first-aid-cong-trinh-pm-ngan", status: "done" },
  { no: 4332, title: "PPE Công Trường Xây", keyword: "ppe công trường xây", slug: "ppe-cong-truong-xay-pm-ngan", status: "done" },
  { no: 4333, title: "Scaffolding Inspection", keyword: "scaffolding inspection", slug: "scaffolding-inspection-pm-ngan", status: "done" },
  { no: 4334, title: "Formwork Inspection", keyword: "formwork inspection", slug: "formwork-inspection-pm-ngan", status: "done" },
  { no: 4335, title: "Rebar Inspection", keyword: "rebar inspection", slug: "rebar-inspection-pm-ngan", status: "done" },
  { no: 4336, title: "Concrete Pour Checklist", keyword: "concrete pour checklist", slug: "concrete-pour-checklist-pm-ngan", status: "done" },
  { no: 4337, title: "Waterproofing Checklist", keyword: "waterproofing checklist", slug: "waterproofing-checklist-pm-ngan", status: "done" },
  { no: 4338, title: "MEP Rough In Checklist", keyword: "mep rough in checklist", slug: "mep-rough-in-checklist-pm-ngan", status: "done" },
  { no: 4339, title: "Finishing Checklist Xây", keyword: "finishing checklist xây", slug: "finishing-checklist-xay-pm-ngan", status: "done" },
  { no: 4340, title: "Pre Handover Checklist", keyword: "pre handover checklist", slug: "pre-handover-checklist-pm-ngan", status: "done" },
  { no: 4341, title: "Client Walkthrough Nhà", keyword: "client walkthrough nhà", slug: "client-walkthrough-nha-pm-ngan", status: "done" },
  { no: 4342, title: "Soft Opening Nhà Ở", keyword: "soft opening nhà ở", slug: "soft-opening-nha-o-pm-ngan", status: "done" },
  { no: 4343, title: "Chủ Đề Mở Rộng 48 1", keyword: "chủ đề mở rộng 48 1", slug: "chu-de-mo-rong-48-1-ngan", status: "done" },
  { no: 4344, title: "Chủ Đề Mở Rộng 48 2", keyword: "chủ đề mở rộng 48 2", slug: "chu-de-mo-rong-48-2-ngan", status: "done" },
  { no: 4345, title: "Chủ Đề Mở Rộng 48 3", keyword: "chủ đề mở rộng 48 3", slug: "chu-de-mo-rong-48-3-ngan", status: "done" },
  { no: 4346, title: "Chủ Đề Mở Rộng 48 4", keyword: "chủ đề mở rộng 48 4", slug: "chu-de-mo-rong-48-4-ngan", status: "done" },
];
