/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 15 (#947–#1046).
 * Tập trung cụm 2–4 từ cho Ads + SEO; tránh trùng money pages / landing /xay-nha|/cai-tao-nha.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch15: ContentCalendarItem[] = [
  // —— A. Xây nhà (20) #947–#966 ——
  { no: 947, title: "Xây Nhà Mới", keyword: "xây nhà mới", slug: "xay-nha-moi-ngan", status: "done" },
  { no: 948, title: "Xây Nhà Phố", keyword: "xây nhà phố", slug: "xay-nha-pho-ngan", status: "done" },
  { no: 949, title: "Xây Biệt Thự", keyword: "xây biệt thự", slug: "xay-biet-thu-ngan", status: "done" },
  { no: 950, title: "Xây Nhà Cấp 4", keyword: "xây nhà cấp 4", slug: "xay-nha-cap-4-ngan", status: "done" },
  { no: 951, title: "Xây Nhà Ống", keyword: "xây nhà ống", slug: "xay-nha-ong-ngan", status: "done" },
  { no: 952, title: "Xây Nhà Liền Kề", keyword: "xây nhà liền kề", slug: "xay-nha-lien-ke-ngan", status: "done" },
  { no: 953, title: "Xây Nhà Mini", keyword: "xây nhà mini", slug: "xay-nha-mini-ngan", status: "done" },
  { no: 954, title: "Xây Nhà Trọ", keyword: "xây nhà trọ", slug: "xay-nha-tro-ngan", status: "done" },
  { no: 955, title: "Xây Nhà Xưởng", keyword: "xây nhà xưởng", slug: "xay-nha-xuong-ngan", status: "done" },
  { no: 956, title: "Xây Nhà Văn Phòng", keyword: "xây nhà văn phòng", slug: "xay-nha-van-phong-ngan", status: "done" },
  { no: 957, title: "Xây Móng Nhà", keyword: "xây móng nhà", slug: "xay-mong-nha-ngan", status: "done" },
  { no: 958, title: "Xây Phần Thô", keyword: "xây phần thô", slug: "xay-phan-tho-ngan", status: "done" },
  { no: 959, title: "Xây Nhà Chìa Khóa", keyword: "xây nhà chìa khóa", slug: "xay-nha-chia-khoa-ngan", status: "done" },
  { no: 960, title: "Xây Nhà Giá Rẻ", keyword: "xây nhà giá rẻ", slug: "xay-nha-gia-re-ngan", status: "done" },
  { no: 961, title: "Xây Nhà Uy Tín", keyword: "xây nhà uy tín", slug: "xay-nha-uy-tin-ngan", status: "done" },
  { no: 962, title: "Nhà Thầu Xây Nhà", keyword: "nhà thầu xây nhà", slug: "nha-thau-xay-nha-ngan", status: "done" },
  { no: 963, title: "Đơn Vị Xây Nhà", keyword: "đơn vị xây nhà", slug: "don-vi-xay-nha-ngan", status: "done" },
  { no: 964, title: "Công Ty Xây Nhà", keyword: "công ty xây nhà", slug: "cong-ty-xay-nha-ngan", status: "done" },
  { no: 965, title: "Thi Công Xây Nhà", keyword: "thi công xây nhà", slug: "thi-cong-xay-nha-ngan", status: "done" },
  { no: 966, title: "Xây Dựng Nhà Ở", keyword: "xây dựng nhà ở", slug: "xay-dung-nha-o-ngan", status: "done" },

  // —— B. Cải tạo / sửa nhà (20) #967–#986 ——
  { no: 967, title: "Sửa Nhà", keyword: "sửa nhà", slug: "sua-nha-ngan", status: "done" },
  { no: 968, title: "Sửa Nhà Cũ", keyword: "sửa nhà cũ", slug: "sua-nha-cu-ngan", status: "done" },
  { no: 969, title: "Sửa Chữa Nhà", keyword: "sửa chữa nhà", slug: "sua-chua-nha-ngan", status: "done" },
  { no: 970, title: "Cải Tạo Nhà", keyword: "cải tạo nhà", slug: "cai-tao-nha-ngan", status: "done" },
  { no: 971, title: "Cải Tạo Nhà Cũ", keyword: "cải tạo nhà cũ", slug: "cai-tao-nha-cu-ngan", status: "done" },
  { no: 972, title: "Cải Tạo Nhà Phố", keyword: "cải tạo nhà phố", slug: "cai-tao-nha-pho-ngan", status: "done" },
  { no: 973, title: "Nâng Tầng Nhà", keyword: "nâng tầng nhà", slug: "nang-tang-nha-ngan", status: "done" },
  { no: 974, title: "Gia Cố Nhà", keyword: "gia cố nhà", slug: "gia-co-nha-ngan", status: "done" },
  { no: 975, title: "Chống Thấm Nhà", keyword: "chống thấm nhà", slug: "chong-tham-nha-ngan", status: "done" },
  { no: 976, title: "Sửa Mái Nhà", keyword: "sửa mái nhà", slug: "sua-mai-nha-ngan", status: "done" },
  { no: 977, title: "Sơn Nhà", keyword: "sơn nhà", slug: "son-nha-ngan", status: "done" },
  { no: 978, title: "Làm Mới Nhà", keyword: "làm mới nhà", slug: "lam-moi-nha-ngan", status: "done" },
  { no: 979, title: "Cải Tạo Mặt Tiền", keyword: "cải tạo mặt tiền", slug: "cai-tao-mat-tien-ngan", status: "done" },
  { no: 980, title: "Sửa Điện Nước", keyword: "sửa điện nước", slug: "sua-dien-nuoc-ngan", status: "done" },
  { no: 981, title: "Sửa Nhà Trọn Gói", keyword: "sửa nhà trọn gói", slug: "sua-nha-tron-goi-ngan", status: "done" },
  { no: 982, title: "Cải Tạo Trọn Gói", keyword: "cải tạo trọn gói", slug: "cai-tao-tron-goi-ngan", status: "done" },
  { no: 983, title: "Sửa Nhà Giá Rẻ", keyword: "sửa nhà giá rẻ", slug: "sua-nha-gia-re-ngan", status: "done" },
  { no: 984, title: "Cải Tạo Nội Thất", keyword: "cải tạo nội thất", slug: "cai-tao-noi-that-ngan", status: "done" },
  { no: 985, title: "Mở Rộng Nhà", keyword: "mở rộng nhà", slug: "mo-rong-nha-ngan", status: "done" },
  { no: 986, title: "Cải Tạo Phòng Bếp", keyword: "cải tạo phòng bếp", slug: "cai-tao-phong-bep-ngan", status: "done" },

  // —— C. Báo giá / chi phí (15) #987–#1001 ——
  { no: 987, title: "Báo Giá Xây Nhà", keyword: "báo giá xây nhà", slug: "bao-gia-xay-nha-ngan", status: "done" },
  { no: 988, title: "Chi Phí Xây Nhà", keyword: "chi phí xây nhà", slug: "chi-phi-xay-nha-ngan", status: "done" },
  { no: 989, title: "Đơn Giá Xây Nhà", keyword: "đơn giá xây nhà", slug: "don-gia-xay-nha-ngan", status: "done" },
  { no: 990, title: "Giá Xây Nhà", keyword: "giá xây nhà", slug: "gia-xay-nha-ngan", status: "done" },
  { no: 991, title: "Báo Giá Phần Thô", keyword: "báo giá phần thô", slug: "bao-gia-phan-tho-ngan", status: "done" },
  { no: 992, title: "Báo Giá Trọn Gói", keyword: "báo giá trọn gói", slug: "bao-gia-tron-goi-ngan", status: "done" },
  { no: 993, title: "Báo Giá Cải Tạo", keyword: "báo giá cải tạo", slug: "bao-gia-cai-tao-ngan", status: "done" },
  { no: 994, title: "Chi Phí Cải Tạo", keyword: "chi phí cải tạo", slug: "chi-phi-cai-tao-ngan", status: "done" },
  { no: 995, title: "Báo Giá Sửa Nhà", keyword: "báo giá sửa nhà", slug: "bao-gia-sua-nha-ngan", status: "done" },
  { no: 996, title: "Dự Toán Xây Nhà", keyword: "dự toán xây nhà", slug: "du-toan-xay-nha-ngan", status: "done" },
  { no: 997, title: "Giá Xây M2", keyword: "giá xây m2", slug: "gia-xay-m2-ngan", status: "done" },
  { no: 998, title: "Đơn Giá m2 Xây Nhà", keyword: "đơn giá m2 xây nhà", slug: "don-gia-m2-xay-nha-ngan", status: "done" },
  { no: 999, title: "Chi Phí Xây Móng", keyword: "chi phí xây móng", slug: "chi-phi-xay-mong-ngan", status: "done" },
  { no: 1000, title: "Bảng Giá Xây Nhà", keyword: "bảng giá xây nhà", slug: "bang-gia-xay-nha-ngan", status: "done" },
  { no: 1001, title: "Báo Giá Thiết Kế", keyword: "báo giá thiết kế", slug: "bao-gia-thiet-ke-ngan", status: "done" },

  // —— D. Thiết kế (15) #1002–#1016 ——
  { no: 1002, title: "Thiết Kế Nhà", keyword: "thiết kế nhà", slug: "thiet-ke-nha-ngan", status: "done" },
  { no: 1003, title: "Thiết Kế Nhà Phố", keyword: "thiết kế nhà phố", slug: "thiet-ke-nha-pho-ngan", status: "done" },
  { no: 1004, title: "Thiết Kế Biệt Thự", keyword: "thiết kế biệt thự", slug: "thiet-ke-biet-thu-ngan", status: "done" },
  { no: 1005, title: "Thiết Kế Nội Thất", keyword: "thiết kế nội thất", slug: "thiet-ke-noi-that-ngan", status: "done" },
  { no: 1006, title: "Thiết Kế 3D Nhà", keyword: "thiết kế 3d nhà", slug: "thiet-ke-3d-nha-ngan", status: "done" },
  { no: 1007, title: "Kiến Trúc Sư Nhà", keyword: "kiến trúc sư nhà", slug: "kien-truc-su-nha-ngan", status: "done" },
  { no: 1008, title: "Mẫu Nhà Đẹp", keyword: "mẫu nhà đẹp", slug: "mau-nha-dep-ngan", status: "done" },
  { no: 1009, title: "Mẫu Nhà Phố", keyword: "mẫu nhà phố", slug: "mau-nha-pho-ngan", status: "done" },
  { no: 1010, title: "Mẫu Nhà 2 Tầng", keyword: "mẫu nhà 2 tầng", slug: "mau-nha-2-tang-ngan", status: "done" },
  { no: 1011, title: "Mẫu Nhà 3 Tầng", keyword: "mẫu nhà 3 tầng", slug: "mau-nha-3-tang-ngan", status: "done" },
  { no: 1012, title: "Mẫu Nhà Cấp 4", keyword: "mẫu nhà cấp 4", slug: "mau-nha-cap-4-ngan", status: "done" },
  { no: 1013, title: "Thiết Kế Mặt Tiền", keyword: "thiết kế mặt tiền", slug: "thiet-ke-mat-tien-ngan", status: "done" },
  { no: 1014, title: "Thiết Kế Phòng Khách", keyword: "thiết kế phòng khách", slug: "thiet-ke-phong-khach-ngan", status: "done" },
  { no: 1015, title: "Thiết Kế Nhà Hiện Đại", keyword: "thiết kế nhà hiện đại", slug: "thiet-ke-nha-hien-dai-ngan", status: "done" },
  { no: 1016, title: "Bản Vẽ Nhà", keyword: "bản vẽ nhà", slug: "ban-ve-nha-ngan", status: "done" },

  // —— E. Loại tầng / quy mô (15) #1017–#1031 ——
  { no: 1017, title: "Xây Nhà 1 Tầng", keyword: "xây nhà 1 tầng", slug: "xay-nha-1-tang-ngan", status: "done" },
  { no: 1018, title: "Xây Nhà 2 Tầng", keyword: "xây nhà 2 tầng", slug: "xay-nha-2-tang-ngan", status: "done" },
  { no: 1019, title: "Xây Nhà 3 Tầng", keyword: "xây nhà 3 tầng", slug: "xay-nha-3-tang-ngan", status: "done" },
  { no: 1020, title: "Xây Nhà 4 Tầng", keyword: "xây nhà 4 tầng", slug: "xay-nha-4-tang-ngan", status: "done" },
  { no: 1021, title: "Xây Nhà 5 Tầng", keyword: "xây nhà 5 tầng", slug: "xay-nha-5-tang-ngan", status: "done" },
  { no: 1022, title: "Nhà 1 Trệt 1 Lầu", keyword: "nhà 1 trệt 1 lầu", slug: "nha-1-tret-1-lau-ngan", status: "done" },
  { no: 1023, title: "Nhà 1 Trệt 2 Lầu", keyword: "nhà 1 trệt 2 lầu", slug: "nha-1-tret-2-lau-ngan", status: "done" },
  { no: 1024, title: "Xây Nhà Hẻm", keyword: "xây nhà hẻm", slug: "xay-nha-hem-ngan", status: "done" },
  { no: 1025, title: "Xây Nhà Đất Hẹp", keyword: "xây nhà đất hẹp", slug: "xay-nha-dat-hep-ngan", status: "done" },
  { no: 1026, title: "Xây Nhà Mặt Tiền", keyword: "xây nhà mặt tiền", slug: "xay-nha-mat-tien-ngan", status: "done" },
  { no: 1027, title: "Hoàn Thiện Nhà", keyword: "hoàn thiện nhà", slug: "hoan-thien-nha-ngan", status: "done" },
  { no: 1028, title: "Xây Nhà Tiền Chế", keyword: "xây nhà tiền chế", slug: "xay-nha-tien-che-ngan", status: "done" },
  { no: 1029, title: "Xây Nhà Khung Thép", keyword: "xây nhà khung thép", slug: "xay-nha-khung-thep-ngan", status: "done" },
  { no: 1030, title: "Xây Nhà Có Thang Máy", keyword: "xây nhà có thang máy", slug: "xay-nha-thang-may-ngan", status: "done" },
  { no: 1031, title: "Xây Nhà Sân Vườn", keyword: "xây nhà sân vườn", slug: "xay-nha-san-vuon-ngan", status: "done" },

  // —— F. Dịch vụ & quy trình (15) #1032–#1046 ——
  { no: 1032, title: "Xin Phép Xây Dựng", keyword: "xin phép xây dựng", slug: "xin-phep-xay-dung-ngan", status: "done" },
  { no: 1033, title: "Giấy Phép Xây Nhà", keyword: "giấy phép xây nhà", slug: "giay-phep-xay-nha-ngan", status: "done" },
  { no: 1034, title: "Giám Sát Xây Nhà", keyword: "giám sát xây nhà", slug: "giam-sat-xay-nha-ngan", status: "done" },
  { no: 1035, title: "Quy Trình Xây Nhà", keyword: "quy trình xây nhà", slug: "quy-trinh-xay-nha-ngan", status: "done" },
  { no: 1036, title: "Khảo Sát Xây Nhà", keyword: "khảo sát xây nhà", slug: "khao-sat-xay-nha-ngan", status: "done" },
  { no: 1037, title: "Tư Vấn Xây Nhà", keyword: "tư vấn xây nhà", slug: "tu-van-xay-nha-ngan", status: "done" },
  { no: 1038, title: "Nhận Thầu Xây Nhà", keyword: "nhận thầu xây nhà", slug: "nhan-thau-xay-nha-ngan", status: "done" },
  { no: 1039, title: "Xây Nhà Trọn Gói", keyword: "xây nhà trọn gói", slug: "xay-nha-tron-goi-ngan", status: "done" },
  { no: 1040, title: "Sửa Nhà Uy Tín", keyword: "sửa nhà uy tín", slug: "sua-nha-uy-tin-ngan", status: "done" },
  { no: 1041, title: "Cải Tạo Uy Tín", keyword: "cải tạo uy tín", slug: "cai-tao-uy-tin-ngan", status: "done" },
  { no: 1042, title: "Thi Công Nhà Phố", keyword: "thi công nhà phố", slug: "thi-cong-nha-pho-ngan", status: "done" },
  { no: 1043, title: "Thi Công Biệt Thự", keyword: "thi công biệt thự", slug: "thi-cong-biet-thu-ngan", status: "done" },
  { no: 1044, title: "Xây Nhà Bình Dương", keyword: "xây nhà Bình Dương", slug: "xay-nha-binh-duong-ngan", status: "done" },
  { no: 1045, title: "Xây Nhà Đồng Nai", keyword: "xây nhà Đồng Nai", slug: "xay-nha-dong-nai-ngan", status: "done" },
  { no: 1046, title: "Xây Nhà Thủ Đức", keyword: "xây nhà Thủ Đức", slug: "xay-nha-thu-duc-ngan", status: "done" },
];
