/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 23 (#1747–#1846).
 * Cluster: geo tỉnh/thành mở rộng + view/đất.
 * Suffix `-ngan` tránh trùng money pages / batch trước.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch23: ContentCalendarItem[] = [
  { no: 1747, title: "Xây Nhà An Giang", keyword: "xây nhà An Giang", slug: "xay-nha-an-giang-ngan", status: "done" },
  { no: 1748, title: "Xây Nhà Kiên Giang", keyword: "xây nhà Kiên Giang", slug: "xay-nha-kien-giang-ngan", status: "done" },
  { no: 1749, title: "Xây Nhà Cà Mau", keyword: "xây nhà Cà Mau", slug: "xay-nha-ca-mau-ngan", status: "done" },
  { no: 1750, title: "Xây Nhà Bạc Liêu", keyword: "xây nhà Bạc Liêu", slug: "xay-nha-bac-lieu-ngan", status: "done" },
  { no: 1751, title: "Xây Nhà Sóc Trăng", keyword: "xây nhà Sóc Trăng", slug: "xay-nha-soc-trang-ngan", status: "done" },
  { no: 1752, title: "Xây Nhà Trà Vinh", keyword: "xây nhà Trà Vinh", slug: "xay-nha-tra-vinh-ngan", status: "done" },
  { no: 1753, title: "Xây Nhà Vĩnh Long", keyword: "xây nhà Vĩnh Long", slug: "xay-nha-vinh-long-ngan", status: "done" },
  { no: 1754, title: "Xây Nhà Đồng Tháp", keyword: "xây nhà Đồng Tháp", slug: "xay-nha-dong-thap-ngan", status: "done" },
  { no: 1755, title: "Xây Nhà Tiền Giang", keyword: "xây nhà Tiền Giang", slug: "xay-nha-tien-giang-ngan", status: "done" },
  { no: 1756, title: "Xây Nhà Bến Tre", keyword: "xây nhà Bến Tre", slug: "xay-nha-ben-tre-ngan", status: "done" },
  { no: 1757, title: "Xây Nhà Hậu Giang", keyword: "xây nhà Hậu Giang", slug: "xay-nha-hau-giang-ngan", status: "done" },
  { no: 1758, title: "Xây Nhà Mỹ Tho", keyword: "xây nhà Mỹ Tho", slug: "xay-nha-my-tho-ngan", status: "done" },
  { no: 1759, title: "Xây Nhà Rạch Giá", keyword: "xây nhà Rạch Giá", slug: "xay-nha-rach-gia-ngan", status: "done" },
  { no: 1760, title: "Xây Nhà Châu Đốc", keyword: "xây nhà Châu Đốc", slug: "xay-nha-chau-doc-ngan", status: "done" },
  { no: 1761, title: "Xây Nhà Nha Trang", keyword: "xây nhà Nha Trang", slug: "xay-nha-nha-trang-ngan", status: "done" },
  { no: 1762, title: "Xây Nhà Đà Lạt", keyword: "xây nhà Đà Lạt", slug: "xay-nha-da-lat-ngan", status: "done" },
  { no: 1763, title: "Xây Nhà Quy Nhơn", keyword: "xây nhà Quy Nhơn", slug: "xay-nha-quy-nhon-ngan", status: "done" },
  { no: 1764, title: "Xây Nhà Hội An", keyword: "xây nhà Hội An", slug: "xay-nha-hoi-an-ngan", status: "done" },
  { no: 1765, title: "Xây Nhà Huế", keyword: "xây nhà Huế", slug: "xay-nha-hue-ngan", status: "done" },
  { no: 1766, title: "Xây Nhà Đà Nẵng", keyword: "xây nhà Đà Nẵng", slug: "xay-nha-da-nang-ngan", status: "done" },
  { no: 1767, title: "Xây Nhà Quảng Ngãi", keyword: "xây nhà Quảng Ngãi", slug: "xay-nha-quang-ngai-ngan", status: "done" },
  { no: 1768, title: "Xây Nhà Quảng Nam", keyword: "xây nhà Quảng Nam", slug: "xay-nha-quang-nam-ngan", status: "done" },
  { no: 1769, title: "Xây Nhà Bình Định", keyword: "xây nhà Bình Định", slug: "xay-nha-binh-dinh-ngan", status: "done" },
  { no: 1770, title: "Xây Nhà Phú Quốc", keyword: "xây nhà Phú Quốc", slug: "xay-nha-phu-quoc-ngan", status: "done" },
  { no: 1771, title: "Xây Nhà Phan Thiết", keyword: "xây nhà Phan Thiết", slug: "xay-nha-phan-thiet-ngan", status: "done" },
  { no: 1772, title: "Xây Nhà Phan Rang", keyword: "xây nhà Phan Rang", slug: "xay-nha-phan-rang-ngan", status: "done" },
  { no: 1773, title: "Xây Nhà Cam Ranh", keyword: "xây nhà Cam Ranh", slug: "xay-nha-cam-ranh-ngan", status: "done" },
  { no: 1774, title: "Xây Nhà Buôn Hồ", keyword: "xây nhà Buôn Hồ", slug: "xay-nha-buon-ho-ngan", status: "done" },
  { no: 1775, title: "Xây Nhà Gia Nghĩa", keyword: "xây nhà Gia Nghĩa", slug: "xay-nha-gia-nghia-ngan", status: "done" },
  { no: 1776, title: "Xây Nhà Kon Tum", keyword: "xây nhà Kon Tum", slug: "xay-nha-kon-tum-ngan", status: "done" },
  { no: 1777, title: "Xây Nhà Pleiku", keyword: "xây nhà Pleiku", slug: "xay-nha-pleiku-ngan", status: "done" },
  { no: 1778, title: "Xây Nhà Ban Mê", keyword: "xây nhà Ban Mê", slug: "xay-nha-ban-me-ngan", status: "done" },
  { no: 1779, title: "Sửa Nhà An Giang", keyword: "sửa nhà An Giang", slug: "sua-nha-an-giang-ngan", status: "done" },
  { no: 1780, title: "Sửa Nhà Kiên Giang", keyword: "sửa nhà Kiên Giang", slug: "sua-nha-kien-giang-ngan", status: "done" },
  { no: 1781, title: "Sửa Nhà Nha Trang", keyword: "sửa nhà Nha Trang", slug: "sua-nha-nha-trang-ngan", status: "done" },
  { no: 1782, title: "Sửa Nhà Đà Lạt", keyword: "sửa nhà Đà Lạt", slug: "sua-nha-da-lat-ngan", status: "done" },
  { no: 1783, title: "Sửa Nhà Đà Nẵng", keyword: "sửa nhà Đà Nẵng", slug: "sua-nha-da-nang-ngan", status: "done" },
  { no: 1784, title: "Sửa Nhà Huế", keyword: "sửa nhà Huế", slug: "sua-nha-hue-ngan", status: "done" },
  { no: 1785, title: "Cải Tạo Nhà An Giang", keyword: "cải tạo nhà An Giang", slug: "cai-tao-nha-an-giang-ngan", status: "done" },
  { no: 1786, title: "Cải Tạo Nhà Nha Trang", keyword: "cải tạo nhà Nha Trang", slug: "cai-tao-nha-nha-trang-ngan", status: "done" },
  { no: 1787, title: "Cải Tạo Nhà Đà Lạt", keyword: "cải tạo nhà Đà Lạt", slug: "cai-tao-nha-da-lat-ngan", status: "done" },
  { no: 1788, title: "Cải Tạo Nhà Đà Nẵng", keyword: "cải tạo nhà Đà Nẵng", slug: "cai-tao-nha-da-nang-ngan", status: "done" },
  { no: 1789, title: "Cải Tạo Nhà Huế", keyword: "cải tạo nhà Huế", slug: "cai-tao-nha-hue-ngan", status: "done" },
  { no: 1790, title: "Xây Nhà Trọn Gói An Giang", keyword: "xây nhà trọn gói An Giang", slug: "xay-nha-tron-goi-an-giang-ngan", status: "done" },
  { no: 1791, title: "Xây Nhà Trọn Gói Nha Trang", keyword: "xây nhà trọn gói Nha Trang", slug: "xay-nha-tron-goi-nha-trang-ngan", status: "done" },
  { no: 1792, title: "Xây Nhà Trọn Gói Đà Lạt", keyword: "xây nhà trọn gói Đà Lạt", slug: "xay-nha-tron-goi-da-lat-ngan", status: "done" },
  { no: 1793, title: "Xây Nhà Trọn Gói Đà Nẵng", keyword: "xây nhà trọn gói Đà Nẵng", slug: "xay-nha-tron-goi-da-nang-ngan", status: "done" },
  { no: 1794, title: "Xây Nhà Trọn Gói Huế", keyword: "xây nhà trọn gói Huế", slug: "xay-nha-tron-goi-hue-ngan", status: "done" },
  { no: 1795, title: "Xây Nhà Trọn Gói Phú Quốc", keyword: "xây nhà trọn gói Phú Quốc", slug: "xay-nha-tron-goi-phu-quoc-ngan", status: "done" },
  { no: 1796, title: "Xây Nhà Trọn Gói Phan Thiết", keyword: "xây nhà trọn gói Phan Thiết", slug: "xay-nha-tron-goi-phan-thiet-ngan", status: "done" },
  { no: 1797, title: "Thiết Kế Nhà An Giang", keyword: "thiết kế nhà An Giang", slug: "thiet-ke-nha-an-giang-ngan", status: "done" },
  { no: 1798, title: "Thiết Kế Nhà Nha Trang", keyword: "thiết kế nhà Nha Trang", slug: "thiet-ke-nha-nha-trang-ngan", status: "done" },
  { no: 1799, title: "Thiết Kế Nhà Đà Lạt", keyword: "thiết kế nhà Đà Lạt", slug: "thiet-ke-nha-da-lat-ngan", status: "done" },
  { no: 1800, title: "Thiết Kế Nhà Đà Nẵng", keyword: "thiết kế nhà Đà Nẵng", slug: "thiet-ke-nha-da-nang-ngan", status: "done" },
  { no: 1801, title: "Thiết Kế Nhà Huế", keyword: "thiết kế nhà Huế", slug: "thiet-ke-nha-hue-ngan", status: "done" },
  { no: 1802, title: "Báo Giá Xây Nhà An Giang", keyword: "báo giá xây nhà An Giang", slug: "bao-gia-xay-nha-an-giang-ngan", status: "done" },
  { no: 1803, title: "Báo Giá Xây Nhà Nha Trang", keyword: "báo giá xây nhà Nha Trang", slug: "bao-gia-xay-nha-nha-trang-ngan", status: "done" },
  { no: 1804, title: "Báo Giá Xây Nhà Đà Lạt", keyword: "báo giá xây nhà Đà Lạt", slug: "bao-gia-xay-nha-da-lat-ngan", status: "done" },
  { no: 1805, title: "Báo Giá Xây Nhà Đà Nẵng", keyword: "báo giá xây nhà Đà Nẵng", slug: "bao-gia-xay-nha-da-nang-ngan", status: "done" },
  { no: 1806, title: "Báo Giá Xây Nhà Huế", keyword: "báo giá xây nhà Huế", slug: "bao-gia-xay-nha-hue-ngan", status: "done" },
  { no: 1807, title: "Xây Nhà Ven Biển", keyword: "xây nhà ven biển", slug: "xay-nha-ven-bien-ngan", status: "done" },
  { no: 1808, title: "Xây Nhà Ven Sông", keyword: "xây nhà ven sông", slug: "xay-nha-ven-song-ngan", status: "done" },
  { no: 1809, title: "Xây Nhà Đồi Núi", keyword: "xây nhà đồi núi", slug: "xay-nha-doi-nui-ngan", status: "done" },
  { no: 1810, title: "Xây Nhà Nông Thôn", keyword: "xây nhà nông thôn", slug: "xay-nha-nong-thon-ngan", status: "done" },
  { no: 1811, title: "Xây Nhà Thị Xã", keyword: "xây nhà thị xã", slug: "xay-nha-thi-xa-ngan", status: "done" },
  { no: 1812, title: "Xây Nhà Trung Tâm", keyword: "xây nhà trung tâm", slug: "xay-nha-trung-tam-ngan", status: "done" },
  { no: 1813, title: "Xây Nhà Khu Dân Cư", keyword: "xây nhà khu dân cư", slug: "xay-nha-khu-dan-cu-ngan", status: "done" },
  { no: 1814, title: "Xây Nhà Khu Đô Thị", keyword: "xây nhà khu đô thị", slug: "xay-nha-khu-do-thi-ngan", status: "done" },
  { no: 1815, title: "Xây Nhà Dự Án", keyword: "xây nhà dự án", slug: "xay-nha-du-an-ngan", status: "done" },
  { no: 1816, title: "Xây Nhà Đất Nền", keyword: "xây nhà đất nền", slug: "xay-nha-dat-nen-ngan", status: "done" },
  { no: 1817, title: "Xây Nhà Đất Thổ Cư", keyword: "xây nhà đất thổ cư", slug: "xay-nha-dat-tho-cu-ngan", status: "done" },
  { no: 1818, title: "Xây Nhà Đất Ruộng", keyword: "xây nhà đất ruộng", slug: "xay-nha-dat-ruong-ngan", status: "done" },
  { no: 1819, title: "Xây Nhà Đất Vườn", keyword: "xây nhà đất vườn", slug: "xay-nha-dat-vuon-ngan", status: "done" },
  { no: 1820, title: "Xây Nhà Mặt Tiền Đường", keyword: "xây nhà mặt tiền đường", slug: "xay-nha-mat-tien-duong-ngan", status: "done" },
  { no: 1821, title: "Xây Nhà Mặt Tiền Chợ", keyword: "xây nhà mặt tiền chợ", slug: "xay-nha-mat-tien-cho-ngan", status: "done" },
  { no: 1822, title: "Xây Nhà Gần Trường", keyword: "xây nhà gần trường", slug: "xay-nha-gan-truong-ngan", status: "done" },
  { no: 1823, title: "Xây Nhà Gần Bệnh Viện", keyword: "xây nhà gần bệnh viện", slug: "xay-nha-gan-benh-vien-ngan", status: "done" },
  { no: 1824, title: "Xây Nhà Gần Metro", keyword: "xây nhà gần metro", slug: "xay-nha-gan-metro-ngan", status: "done" },
  { no: 1825, title: "Xây Nhà Gần Cao Tốc", keyword: "xây nhà gần cao tốc", slug: "xay-nha-gan-cao-toc-ngan", status: "done" },
  { no: 1826, title: "Xây Nhà Gần Sân Bay", keyword: "xây nhà gần sân bay", slug: "xay-nha-gan-san-bay-ngan", status: "done" },
  { no: 1827, title: "Xây Nhà Gần Cảng", keyword: "xây nhà gần cảng", slug: "xay-nha-gan-cang-ngan", status: "done" },
  { no: 1828, title: "Xây Nhà Gần KCN", keyword: "xây nhà gần kcn", slug: "xay-nha-gan-kcn-ngan", status: "done" },
  { no: 1829, title: "Xây Nhà View Sông", keyword: "xây nhà view sông", slug: "xay-nha-view-song-ngan", status: "done" },
  { no: 1830, title: "Xây Nhà View Biển", keyword: "xây nhà view biển", slug: "xay-nha-view-bien-ngan", status: "done" },
  { no: 1831, title: "Xây Nhà View Núi", keyword: "xây nhà view núi", slug: "xay-nha-view-nui-ngan", status: "done" },
  { no: 1832, title: "Xây Nhà View Hồ", keyword: "xây nhà view hồ", slug: "xay-nha-view-ho-ngan", status: "done" },
  { no: 1833, title: "Xây Nhà View Công Viên", keyword: "xây nhà view công viên", slug: "xay-nha-view-cong-vien-ngan", status: "done" },
  { no: 1834, title: "Thi Công Nhà Miền Tây", keyword: "thi công nhà miền tây", slug: "thi-cong-nha-mien-tay-ngan", status: "done" },
  { no: 1835, title: "Thi Công Nhà Miền Trung", keyword: "thi công nhà miền trung", slug: "thi-cong-nha-mien-trung-ngan", status: "done" },
  { no: 1836, title: "Thi Công Nhà Tây Nguyên", keyword: "thi công nhà tây nguyên", slug: "thi-cong-nha-tay-nguyen-ngan", status: "done" },
  { no: 1837, title: "Thi Công Nhà Nam Bộ", keyword: "thi công nhà nam bộ", slug: "thi-cong-nha-nam-bo-ngan", status: "done" },
  { no: 1838, title: "Nhà Thầu Miền Tây", keyword: "nhà thầu miền tây", slug: "nha-thau-mien-tay-ngan", status: "done" },
  { no: 1839, title: "Nhà Thầu Miền Trung", keyword: "nhà thầu miền trung", slug: "nha-thau-mien-trung-ngan", status: "done" },
  { no: 1840, title: "Nhà Thầu Tây Nguyên", keyword: "nhà thầu tây nguyên", slug: "nha-thau-tay-nguyen-ngan", status: "done" },
  { no: 1841, title: "Đơn Vị Xây Nhà Miền Tây", keyword: "đơn vị xây nhà miền tây", slug: "don-vi-xay-nha-mien-tay-ngan", status: "done" },
  { no: 1842, title: "Đơn Vị Xây Nhà Miền Trung", keyword: "đơn vị xây nhà miền trung", slug: "don-vi-xay-nha-mien-trung-ngan", status: "done" },
  { no: 1843, title: "Công Ty Xây Dựng Miền Tây", keyword: "công ty xây dựng miền tây", slug: "cong-ty-xay-dung-mien-tay-ngan", status: "done" },
  { no: 1844, title: "Công Ty Xây Dựng Miền Trung", keyword: "công ty xây dựng miền trung", slug: "cong-ty-xay-dung-mien-trung-ngan", status: "done" },
  { no: 1845, title: "Xây Nhà Trọn Gói Hội An", keyword: "xây nhà trọn gói Hội An", slug: "xay-nha-tron-goi-hoi-an-ngan", status: "done" },
  { no: 1846, title: "Xây Nhà Trọn Gói Quy Nhơn", keyword: "xây nhà trọn gói Quy Nhơn", slug: "xay-nha-tron-goi-quy-nhon-ngan", status: "done" },
];
