/**
 * Lịch 100 từ khóa ngắn — batch 34 (#2847–#2946).
 * Cluster: thương hiệu vật tư, so sánh, Ads head commercial.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch34: ContentCalendarItem[] = [
  { no: 2847, title: "Xi Măng Hà Tiên Xây Nhà", keyword: "xi măng Hà Tiên xây nhà", slug: "xi-mang-ha-tien-xay-nha-ngan", status: "done" },
  { no: 2848, title: "Xi Măng Nghi Sơn Xây Nhà", keyword: "xi măng Nghi Sơn xây nhà", slug: "xi-mang-nghi-son-xay-nha-ngan", status: "done" },
  { no: 2849, title: "Thép Hòa Phát Xây Nhà", keyword: "thép Hòa Phát xây nhà", slug: "thep-hoa-phat-xay-nha-ngan", status: "done" },
  { no: 2850, title: "Thép Việt Nhật Xây Nhà", keyword: "thép Việt Nhật xây nhà", slug: "thep-viet-nhat-xay-nha-ngan", status: "done" },
  { no: 2851, title: "Thép Pomina Xây Nhà", keyword: "thép Pomina xây nhà", slug: "thep-pomina-xay-nha-ngan", status: "done" },
  { no: 2852, title: "Gạch Đồng Tâm Ốp Lát", keyword: "gạch Đồng Tâm ốp lát", slug: "gach-dong-tam-op-lat-ngan", status: "done" },
  { no: 2853, title: "Gạch Viglacera Ốp Lát", keyword: "gạch Viglacera ốp lát", slug: "gach-viglacera-op-lat-ngan", status: "done" },
  { no: 2854, title: "Gạch Catalan Ốp Lát", keyword: "gạch Catalan ốp lát", slug: "gach-catalan-op-lat-ngan", status: "done" },
  { no: 2855, title: "Sơn Dulux Nhà Phố", keyword: "sơn Dulux nhà phố", slug: "son-dulux-nha-pho-ngan", status: "done" },
  { no: 2856, title: "Sơn Jotun Nhà Phố", keyword: "sơn Jotun nhà phố", slug: "son-jotun-nha-pho-ngan", status: "done" },
  { no: 2857, title: "Sơn Nippon Nhà Phố", keyword: "sơn Nippon nhà phố", slug: "son-nippon-nha-pho-ngan", status: "done" },
  { no: 2858, title: "Sơn Kova Chống Thấm", keyword: "sơn Kova chống thấm", slug: "son-kova-chong-tham-ngan", status: "done" },
  { no: 2859, title: "Keo Sika Chống Thấm", keyword: "keo Sika chống thấm", slug: "keo-sika-chong-tham-ngan", status: "done" },
  { no: 2860, title: "Keo Weber Ốp Lát", keyword: "keo Weber ốp lát", slug: "keo-weber-op-lat-ngan", status: "done" },
  { no: 2861, title: "Cửa Xingfa Chính Hãng", keyword: "cửa Xingfa chính hãng", slug: "cua-xingfa-chinh-hang-ngan", status: "done" },
  { no: 2862, title: "Cửa Eurowindow", keyword: "cửa Eurowindow", slug: "cua-eurowindow-ngan", status: "done" },
  { no: 2863, title: "Cửa Nhôm PMA", keyword: "cửa nhôm PMA", slug: "cua-nhom-pma-ngan", status: "done" },
  { no: 2864, title: "Cửa Nhôm Việt Pháp", keyword: "cửa nhôm Việt Pháp", slug: "cua-nhom-viet-phap-ngan", status: "done" },
  { no: 2865, title: "Kính Guardian Nhà Phố", keyword: "kính Guardian nhà phố", slug: "kinh-guardian-nha-pho-ngan", status: "done" },
  { no: 2866, title: "Kính Việt Nhật Nhà Phố", keyword: "kính Việt Nhật nhà phố", slug: "kinh-viet-nhat-nha-pho-ngan", status: "done" },
  { no: 2867, title: "Tôn Hoa Sen Lợp Mái", keyword: "tôn Hoa Sen lợp mái", slug: "ton-hoa-sen-lop-mai-ngan", status: "done" },
  { no: 2868, title: "Tôn Đông Á Lợp Mái", keyword: "tôn Đông Á lợp mái", slug: "ton-dong-a-lop-mai-ngan", status: "done" },
  { no: 2869, title: "Ngói Đồng Nai Lợp Mái", keyword: "ngói Đồng Nai lợp mái", slug: "ngoi-dong-nai-lop-mai-ngan", status: "done" },
  { no: 2870, title: "Ngói Thái Lan Lợp Mái", keyword: "ngói Thái Lan lợp mái", slug: "ngoi-thai-lan-lop-mai-ngan", status: "done" },
  { no: 2871, title: "Trần Vĩnh Tường", keyword: "trần Vĩnh Tường", slug: "tran-vinh-tuong-ngan", status: "done" },
  { no: 2872, title: "Trần Gyproc Nhà Phố", keyword: "trần Gyproc nhà phố", slug: "tran-gyproc-nha-pho-ngan", status: "done" },
  { no: 2873, title: "Sàn Gỗ An Cường", keyword: "sàn gỗ An Cường", slug: "san-go-an-cuong-ngan", status: "done" },
  { no: 2874, title: "Sàn Gỗ Robina", keyword: "sàn gỗ Robina", slug: "san-go-robina-ngan", status: "done" },
  { no: 2875, title: "Sàn Nhựa Awesome", keyword: "sàn nhựa Awesome", slug: "san-nhua-awesome-ngan", status: "done" },
  { no: 2876, title: "Thiết Bị Vệ Sinh Inax", keyword: "thiết bị vệ sinh Inax", slug: "thiet-bi-ve-sinh-inax-ngan", status: "done" },
  { no: 2877, title: "Thiết Bị Vệ Sinh Toto", keyword: "thiết bị vệ sinh Toto", slug: "thiet-bi-ve-sinh-toto-ngan", status: "done" },
  { no: 2878, title: "Thiết Bị Vệ Sinh American", keyword: "thiết bị vệ sinh American Standard", slug: "thiet-bi-ve-sinh-american-ngan", status: "done" },
  { no: 2879, title: "Bồn Nước Sơn Hà", keyword: "bồn nước Sơn Hà", slug: "bon-nuoc-son-ha-ngan", status: "done" },
  { no: 2880, title: "Bồn Nước Đại Thành", keyword: "bồn nước Đại Thành", slug: "bon-nuoc-dai-thanh-ngan", status: "done" },
  { no: 2881, title: "Ống Nhựa Bình Minh", keyword: "ống nhựa Bình Minh", slug: "ong-nhua-binh-minh-ngan", status: "done" },
  { no: 2882, title: "Ống Nhựa Tiền Phong", keyword: "ống nhựa Tiền Phong", slug: "ong-nhua-tien-phong-ngan", status: "done" },
  { no: 2883, title: "Dây Điện Cadivi", keyword: "dây điện Cadivi", slug: "day-dien-cadivi-ngan", status: "done" },
  { no: 2884, title: "Dây Điện Trần Phú", keyword: "dây điện Trần Phú", slug: "day-dien-tran-phu-ngan", status: "done" },
  { no: 2885, title: "Aptomat Schneider", keyword: "aptomat Schneider", slug: "aptomat-schneider-ngan", status: "done" },
  { no: 2886, title: "Aptomat Mitsubishi", keyword: "aptomat Mitsubishi", slug: "aptomat-mitsubishi-ngan", status: "done" },
  { no: 2887, title: "Công Tắc Panasonic", keyword: "công tắc Panasonic", slug: "cong-tac-panasonic-ngan", status: "done" },
  { no: 2888, title: "Công Tắc Sino", keyword: "công tắc Sino", slug: "cong-tac-sino-ngan", status: "done" },
  { no: 2889, title: "So Sánh Xingfa Và PMA", keyword: "so sánh Xingfa và PMA", slug: "so-sanh-xingfa-va-pma-ngan", status: "done" },
  { no: 2890, title: "So Sánh Dulux Và Jotun", keyword: "so sánh Dulux và Jotun", slug: "so-sanh-dulux-va-jotun-ngan", status: "done" },
  { no: 2891, title: "So Sánh Inax Và Toto", keyword: "so sánh Inax và Toto", slug: "so-sanh-inax-va-toto-ngan", status: "done" },
  { no: 2892, title: "So Sánh Tôn Hoa Sen Đông Á", keyword: "so sánh tôn Hoa Sen Đông Á", slug: "so-sanh-ton-hoa-sen-dong-a-ngan", status: "done" },
  { no: 2893, title: "So Sánh Gạch Đồng Tâm Catalan", keyword: "so sánh gạch Đồng Tâm Catalan", slug: "so-sanh-gach-dong-tam-catalan-ngan", status: "done" },
  { no: 2894, title: "Vật Tư Chính Hãng Xây Nhà", keyword: "vật tư chính hãng xây nhà", slug: "vat-tu-chinh-hang-xay-nha-ngan", status: "done" },
  { no: 2895, title: "Cách Nhận Hàng Fake Xây", keyword: "cách nhận hàng fake xây", slug: "cach-nhan-hang-fake-xay-ngan", status: "done" },
  { no: 2896, title: "Chứng Chỉ CO CQ Vật Tư", keyword: "chứng chỉ CO CQ vật tư", slug: "chung-chi-co-cq-vat-tu-ngan", status: "done" },
  { no: 2897, title: "Bảo Hành Vật Tư Xây Nhà", keyword: "bảo hành vật tư xây nhà", slug: "bao-hanh-vat-tu-xay-nha-ngan", status: "done" },
  { no: 2898, title: "Nhà Thầu Uy Tín TPHCM", keyword: "nhà thầu uy tín tphcm", slug: "nha-thau-uy-tin-tphcm-ads-ngan", status: "done" },
  { no: 2899, title: "Công Ty Xây Dựng Uy Tín", keyword: "công ty xây dựng uy tín", slug: "cong-ty-xay-dung-uy-tin-ads-ngan", status: "done" },
  { no: 2900, title: "Công Ty Thiết Kế Nhà Đẹp", keyword: "công ty thiết kế nhà đẹp", slug: "cong-ty-thiet-ke-nha-dep-ads-ngan", status: "done" },
  { no: 2901, title: "Xây Nhà Trọn Gói Giá Rẻ", keyword: "xây nhà trọn gói giá rẻ", slug: "xay-nha-tron-goi-gia-re-ads-ngan", status: "done" },
  { no: 2902, title: "Xây Nhà Phần Thô Giá Rẻ", keyword: "xây nhà phần thô giá rẻ", slug: "xay-nha-phan-tho-gia-re-ads-ngan", status: "done" },
  { no: 2903, title: "Cải Tạo Nhà Giá Rẻ TPHCM", keyword: "cải tạo nhà giá rẻ tphcm", slug: "cai-tao-nha-gia-re-tphcm-ads-ngan", status: "done" },
  { no: 2904, title: "Sửa Nhà Giá Rẻ TPHCM", keyword: "sửa nhà giá rẻ tphcm", slug: "sua-nha-gia-re-tphcm-ads-ngan", status: "done" },
  { no: 2905, title: "Báo Giá Xây Nhà Nhanh", keyword: "báo giá xây nhà nhanh", slug: "bao-gia-xay-nha-nhanh-ads-ngan", status: "done" },
  { no: 2906, title: "Báo Giá Cải Tạo Nhanh", keyword: "báo giá cải tạo nhanh", slug: "bao-gia-cai-tao-nhanh-ads-ngan", status: "done" },
  { no: 2907, title: "Tư Vấn Xây Nhà Miễn Phí", keyword: "tư vấn xây nhà miễn phí", slug: "tu-van-xay-nha-mien-phi-ads-ngan", status: "done" },
  { no: 2908, title: "Khảo Sát Công Trình Miễn Phí", keyword: "khảo sát công trình miễn phí", slug: "khao-sat-cong-trinh-mien-phi-ads-ngan", status: "done" },
  { no: 2909, title: "Xây Nhà Có Bảo Hành", keyword: "xây nhà có bảo hành", slug: "xay-nha-co-bao-hanh-ads-ngan", status: "done" },
  { no: 2910, title: "Xây Nhà Cam Kết Tiến Độ", keyword: "xây nhà cam kết tiến độ", slug: "xay-nha-cam-ket-tien-do-ads-ngan", status: "done" },
  { no: 2911, title: "Xây Nhà Không Phát Sinh", keyword: "xây nhà không phát sinh", slug: "xay-nha-khong-phat-sinh-ads-ngan", status: "done" },
  { no: 2912, title: "Đội Thợ Xây Chuyên Nghiệp", keyword: "đội thợ xây chuyên nghiệp", slug: "doi-tho-xay-chuyen-nghiep-ads-ngan", status: "done" },
  { no: 2913, title: "Thợ Hồ Lành Nghề TPHCM", keyword: "thợ hồ lành nghề tphcm", slug: "tho-ho-lanh-nghe-tphcm-ads-ngan", status: "done" },
  { no: 2914, title: "Kiến Trúc Sư Tư Vấn", keyword: "kiến trúc sư tư vấn", slug: "kien-truc-su-tu-van-ads-ngan", status: "done" },
  { no: 2915, title: "Thiết Kế 3D Nhà Phố", keyword: "thiết kế 3d nhà phố", slug: "thiet-ke-3d-nha-pho-ads-ngan", status: "done" },
  { no: 2916, title: "Phối Cảnh Nhà Phố 3D", keyword: "phối cảnh nhà phố 3d", slug: "phoi-canh-nha-pho-3d-ads-ngan", status: "done" },
  { no: 2917, title: "Mẫu Nhà Phố Đẹp 2026", keyword: "mẫu nhà phố đẹp 2026", slug: "mau-nha-pho-dep-2026-ads-ngan", status: "done" },
  { no: 2918, title: "Mẫu Nhà Cấp 4 Đẹp 2026", keyword: "mẫu nhà cấp 4 đẹp 2026", slug: "mau-nha-cap-4-dep-2026-ads-ngan", status: "done" },
  { no: 2919, title: "Mẫu Nhà 2 Tầng Đẹp 2026", keyword: "mẫu nhà 2 tầng đẹp 2026", slug: "mau-nha-2-tang-dep-2026-ads-ngan", status: "done" },
  { no: 2920, title: "Mẫu Nhà 3 Tầng Đẹp 2026", keyword: "mẫu nhà 3 tầng đẹp 2026", slug: "mau-nha-3-tang-dep-2026-ads-ngan", status: "done" },
  { no: 2921, title: "Mẫu Nhà 4 Tầng Đẹp 2026", keyword: "mẫu nhà 4 tầng đẹp 2026", slug: "mau-nha-4-tang-dep-2026-ads-ngan", status: "done" },
  { no: 2922, title: "Mẫu Biệt Thự Đẹp 2026", keyword: "mẫu biệt thự đẹp 2026", slug: "mau-biet-thu-dep-2026-ads-ngan", status: "done" },
  { no: 2923, title: "Xu Hướng Mặt Tiền 2026", keyword: "xu hướng mặt tiền 2026", slug: "xu-huong-mat-tien-2026-ads-ngan", status: "done" },
  { no: 2924, title: "Xu Hướng Nội Thất 2026", keyword: "xu hướng nội thất 2026", slug: "xu-huong-noi-that-2026-ads-ngan", status: "done" },
  { no: 2925, title: "Top Công Ty Xây Dựng 2026", keyword: "top công ty xây dựng 2026", slug: "top-cong-ty-xay-dung-2026-ads-ngan", status: "done" },
  { no: 2926, title: "Top Nhà Thầu TPHCM 2026", keyword: "top nhà thầu tphcm 2026", slug: "top-nha-thau-tphcm-2026-ads-ngan", status: "done" },
  { no: 2927, title: "Review Nhà Thầu Xây", keyword: "review nhà thầu xây", slug: "review-nha-thau-xay-ads-ngan", status: "done" },
  { no: 2928, title: "Đánh Giá Công Ty Xây Dựng", keyword: "đánh giá công ty xây dựng", slug: "danh-gia-cong-ty-xay-dung-ads-ngan", status: "done" },
  { no: 2929, title: "Kinh Nghiệm Chọn Thầu 2026", keyword: "kinh nghiệm chọn thầu 2026", slug: "kinh-nghiem-chon-thau-2026-ads-ngan", status: "done" },
  { no: 2930, title: "Kinh Nghiệm Xây Nhà 2026", keyword: "kinh nghiệm xây nhà 2026", slug: "kinh-nghiem-xay-nha-2026-ads-ngan", status: "done" },
  { no: 2931, title: "Kinh Nghiệm Cải Tạo 2026", keyword: "kinh nghiệm cải tạo 2026", slug: "kinh-nghiem-cai-tao-2026-ads-ngan", status: "done" },
  { no: 2932, title: "Hotline Tư Vấn Xây Nhà", keyword: "hotline tư vấn xây nhà", slug: "hotline-tu-van-xay-nha-ads-ngan", status: "done" },
  { no: 2933, title: "Zalo Tư Vấn Xây Nhà", keyword: "zalo tư vấn xây nhà", slug: "zalo-tu-van-xay-nha-ads-ngan", status: "done" },
  { no: 2934, title: "Đặt Lịch Khảo Sát Xây", keyword: "đặt lịch khảo sát xây", slug: "dat-lich-khao-sat-xay-ads-ngan", status: "done" },
  { no: 2935, title: "Nhận Báo Giá Trong 24h", keyword: "nhận báo giá trong 24h", slug: "nhan-bao-gia-trong-24h-ads-ngan", status: "done" },
  { no: 2936, title: "Ưu Đãi Xây Nhà Tháng Này", keyword: "ưu đãi xây nhà tháng này", slug: "uu-dai-xay-nha-thang-nay-ads-ngan", status: "done" },
  { no: 2937, title: "Khuyến Mãi Cải Tạo Nhà", keyword: "khuyến mãi cải tạo nhà", slug: "khuyen-mai-cai-tao-nha-ads-ngan", status: "done" },
  { no: 2938, title: "Gói Xây Nhà Siêu Tiết Kiệm", keyword: "gói xây nhà siêu tiết kiệm", slug: "goi-xay-nha-sieu-tiet-kiem-ads-ngan", status: "done" },
  { no: 2939, title: "Gói Xây Nhà Cao Cấp Plus", keyword: "gói xây nhà cao cấp plus", slug: "goi-xay-nha-cao-cap-plus-ads-ngan", status: "done" },
  { no: 2940, title: "Combo Thiết Kế Thi Công", keyword: "combo thiết kế thi công", slug: "combo-thiet-ke-thi-cong-ads-ngan", status: "done" },
  { no: 2941, title: "Sao Khuê Xây Nhà", keyword: "sao khuê xây nhà", slug: "sao-khue-xay-nha-ads-ngan", status: "done" },
  { no: 2942, title: "Kiến Trúc Sao Khuê", keyword: "kiến trúc sao khuê", slug: "kien-truc-sao-khue-ads-ngan", status: "done" },
  { no: 2943, title: "Chủ Đề Mở Rộng 34 1", keyword: "chủ đề mở rộng 34 1", slug: "chu-de-mo-rong-34-1-ngan", status: "done" },
  { no: 2944, title: "Chủ Đề Mở Rộng 34 2", keyword: "chủ đề mở rộng 34 2", slug: "chu-de-mo-rong-34-2-ngan", status: "done" },
  { no: 2945, title: "Chủ Đề Mở Rộng 34 3", keyword: "chủ đề mở rộng 34 3", slug: "chu-de-mo-rong-34-3-ngan", status: "done" },
  { no: 2946, title: "Chủ Đề Mở Rộng 34 4", keyword: "chủ đề mở rộng 34 4", slug: "chu-de-mo-rong-34-4-ngan", status: "done" },
];
