/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch 18 (#1247–#1346).
 * Cluster: mặt tiền/ngoại thất, phong cách thiết kế, nhôm kính ngắn, sân vườn, dịch vụ Ads, geo vệ tinh.
 * Suffix `-ngan` tránh trùng money pages / batch 15–17.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch18: ContentCalendarItem[] = [
  // —— A. Mặt tiền & ngoại thất (15) #1247–#1261 ——
  { no: 1247, title: "Mặt Tiền Nhà Phố", keyword: "mặt tiền nhà phố", slug: "mat-tien-nha-pho-ngan", status: "done" },
  { no: 1248, title: "Làm Mặt Tiền Nhà", keyword: "làm mặt tiền nhà", slug: "lam-mat-tien-nha-ngan", status: "done" },
  { no: 1249, title: "Ốp Mặt Tiền", keyword: "ốp mặt tiền", slug: "op-mat-tien-ngan", status: "done" },
  { no: 1250, title: "Sơn Mặt Tiền", keyword: "sơn mặt tiền", slug: "son-mat-tien-ngan", status: "done" },
  { no: 1251, title: "Mặt Tiền Hiện Đại", keyword: "mặt tiền hiện đại", slug: "mat-tien-hien-dai-ngan", status: "done" },
  { no: 1252, title: "Mặt Tiền Nhà Ống", keyword: "mặt tiền nhà ống", slug: "mat-tien-nha-ong-ngan", status: "done" },
  { no: 1253, title: "Trang Trí Mặt Tiền", keyword: "trang trí mặt tiền", slug: "trang-tri-mat-tien-ngan", status: "done" },
  { no: 1254, title: "Cải Tạo Ngoại Thất", keyword: "cải tạo ngoại thất", slug: "cai-tao-ngoai-that-ngan", status: "done" },
  { no: 1255, title: "Làm Mái Hiên", keyword: "làm mái hiên", slug: "lam-mai-hien-ngan", status: "done" },
  { no: 1256, title: "Làm Ban Công Đẹp", keyword: "làm ban công đẹp", slug: "lam-ban-cong-dep-ngan", status: "done" },
  { no: 1257, title: "Lan Can Ban Công", keyword: "lan can ban công", slug: "lan-can-ban-cong-ngan", status: "done" },
  { no: 1258, title: "Ốp Đá Mặt Tiền", keyword: "ốp đá mặt tiền", slug: "op-da-mat-tien-ngan", status: "done" },
  { no: 1259, title: "Ốp Gạch Mặt Tiền", keyword: "ốp gạch mặt tiền", slug: "op-gach-mat-tien-ngan", status: "done" },
  { no: 1260, title: "Chiếu Sáng Mặt Tiền", keyword: "chiếu sáng mặt tiền", slug: "chieu-sang-mat-tien-ngan", status: "done" },
  { no: 1261, title: "Cổng Rào Nhà Phố", keyword: "cổng rào nhà phố", slug: "cong-rao-nha-pho-ngan", status: "done" },

  // —— B. Phong cách thiết kế (15) #1262–#1276 ——
  { no: 1262, title: "Nhà Phong Cách Hiện Đại", keyword: "nhà phong cách hiện đại", slug: "nha-phong-cach-hien-dai-ngan", status: "done" },
  { no: 1263, title: "Nhà Phong Cách Tối Giản", keyword: "nhà phong cách tối giản", slug: "nha-phong-cach-toi-gian-ngan", status: "done" },
  { no: 1264, title: "Nhà Phong Cách Indochine", keyword: "nhà phong cách indochine", slug: "nha-phong-cach-indochine-ngan", status: "done" },
  { no: 1265, title: "Nhà Phong Cách Nhật", keyword: "nhà phong cách nhật", slug: "nha-phong-cach-nhat-ngan", status: "done" },
  { no: 1266, title: "Nhà Phong Cách Bắc Âu", keyword: "nhà phong cách bắc âu", slug: "nha-phong-cach-bac-au-ngan", status: "done" },
  { no: 1267, title: "Nhà Phong Cách Industrial", keyword: "nhà phong cách industrial", slug: "nha-phong-cach-industrial-ngan", status: "done" },
  { no: 1268, title: "Nhà Phong Cách Cổ Điển", keyword: "nhà phong cách cổ điển", slug: "nha-phong-cach-co-dien-ngan", status: "done" },
  { no: 1269, title: "Nhà Phong Cách Tropical", keyword: "nhà phong cách tropical", slug: "nha-phong-cach-tropical-ngan", status: "done" },
  { no: 1270, title: "Thiết Kế Nhà Skandi", keyword: "thiết kế nhà skandi", slug: "thiet-ke-nha-skandi-ngan", status: "done" },
  { no: 1271, title: "Thiết Kế Nhà Luxury", keyword: "thiết kế nhà luxury", slug: "thiet-ke-nha-luxury-ngan", status: "done" },
  { no: 1272, title: "Thiết Kế Nhà Xanh", keyword: "thiết kế nhà xanh", slug: "thiet-ke-nha-xanh-ngan", status: "done" },
  { no: 1273, title: "Thiết Kế Nhà Thông Minh", keyword: "thiết kế nhà thông minh", slug: "thiet-ke-nha-thong-minh-ngan", status: "done" },
  { no: 1274, title: "Mẫu Nhà Hiện Đại", keyword: "mẫu nhà hiện đại", slug: "mau-nha-hien-dai-ngan", status: "done" },
  { no: 1275, title: "Mẫu Nhà Tối Giản", keyword: "mẫu nhà tối giản", slug: "mau-nha-toi-gian-ngan", status: "done" },
  { no: 1276, title: "Xu Hướng Thiết Kế Nhà", keyword: "xu hướng thiết kế nhà", slug: "xu-huong-thiet-ke-nha-ngan", status: "done" },

  // —— C. Nhôm kính ngắn (15) #1277–#1291 ——
  { no: 1277, title: "Cửa Nhôm Kính", keyword: "cửa nhôm kính", slug: "cua-nhom-kinh-ngan", status: "done" },
  { no: 1278, title: "Vách Nhôm Kính", keyword: "vách nhôm kính", slug: "vach-nhom-kinh-ngan", status: "done" },
  { no: 1279, title: "Cửa Xingfa", keyword: "cửa xingfa", slug: "cua-xingfa-ngan", status: "done" },
  { no: 1280, title: "Cửa Nhôm Xingfa", keyword: "cửa nhôm xingfa", slug: "cua-nhom-xingfa-ngan", status: "done" },
  { no: 1281, title: "Lan Can Kính", keyword: "lan can kính", slug: "lan-can-kinh-ngan", status: "done" },
  { no: 1282, title: "Mái Kính", keyword: "mái kính", slug: "mai-kinh-ngan", status: "done" },
  { no: 1283, title: "Vách Kính Cường Lực", keyword: "vách kính cường lực", slug: "vach-kinh-cuong-luc-ngan", status: "done" },
  { no: 1284, title: "Cửa Lùa Nhôm", keyword: "cửa lùa nhôm", slug: "cua-lua-nhom-ngan", status: "done" },
  { no: 1285, title: "Cửa Mở Quay Nhôm", keyword: "cửa mở quay nhôm", slug: "cua-mo-quay-nhom-ngan", status: "done" },
  { no: 1286, title: "Báo Giá Nhôm Kính", keyword: "báo giá nhôm kính", slug: "bao-gia-nhom-kinh-ngan", status: "done" },
  { no: 1287, title: "Thi Công Nhôm Kính", keyword: "thi công nhôm kính", slug: "thi-cong-nhom-kinh-ngan", status: "done" },
  { no: 1288, title: "Nhôm Kính Nhà Phố", keyword: "nhôm kính nhà phố", slug: "nhom-kinh-nha-pho-ngan", status: "done" },
  { no: 1289, title: "Mặt Dựng Nhôm Kính", keyword: "mặt dựng nhôm kính", slug: "mat-dung-nhom-kinh-ngan", status: "done" },
  { no: 1290, title: "Vách Ngăn Kính", keyword: "vách ngăn kính", slug: "vach-ngan-kinh-ngan", status: "done" },
  { no: 1291, title: "Cửa Sổ Nhôm Kính", keyword: "cửa sổ nhôm kính", slug: "cua-so-nhom-kinh-ngan", status: "done" },

  // —— D. Sân vườn & cảnh quan (15) #1292–#1306 ——
  { no: 1292, title: "Sân Vườn Nhà Phố", keyword: "sân vườn nhà phố", slug: "san-vuon-nha-pho-ngan", status: "done" },
  { no: 1293, title: "Thiết Kế Sân Vườn", keyword: "thiết kế sân vườn", slug: "thiet-ke-san-vuon-ngan", status: "done" },
  { no: 1294, title: "Làm Sân Vườn", keyword: "làm sân vườn", slug: "lam-san-vuon-ngan", status: "done" },
  { no: 1295, title: "Sân Trước Nhà", keyword: "sân trước nhà", slug: "san-truoc-nha-ngan", status: "done" },
  { no: 1296, title: "Sân Sau Nhà", keyword: "sân sau nhà", slug: "san-sau-nha-ngan", status: "done" },
  { no: 1297, title: "Tiểu Cảnh Sân Vườn", keyword: "tiểu cảnh sân vườn", slug: "tieu-canh-san-vuon-ngan", status: "done" },
  { no: 1298, title: "Hồ Cá Koi Nhà", keyword: "hồ cá koi nhà", slug: "ho-ca-koi-nha-ngan", status: "done" },
  { no: 1299, title: "Sân Thượng Xanh", keyword: "sân thượng xanh", slug: "san-thuong-xanh-ngan", status: "done" },
  { no: 1300, title: "Trồng Cây Sân Thượng", keyword: "trồng cây sân thượng", slug: "trong-cay-san-thuong-ngan", status: "done" },
  { no: 1301, title: "Lát Sân Nhà", keyword: "lát sân nhà", slug: "lat-san-nha-ngan", status: "done" },
  { no: 1302, title: "Làm Đường Đi Sân", keyword: "làm đường đi sân", slug: "lam-duong-di-san-ngan", status: "done" },
  { no: 1303, title: "Hàng Rào Xanh", keyword: "hàng rào xanh", slug: "hang-rao-xanh-ngan", status: "done" },
  { no: 1304, title: "Cảnh Quan Nhà Phố", keyword: "cảnh quan nhà phố", slug: "canh-quan-nha-pho-ngan", status: "done" },
  { no: 1305, title: "Sân Chơi Trẻ Em", keyword: "sân chơi trẻ em", slug: "san-choi-tre-em-ngan", status: "done" },
  { no: 1306, title: "Khu BBQ Sân Vườn", keyword: "khu bbq sân vườn", slug: "khu-bbq-san-vuon-ngan", status: "done" },

  // —— E. Geo vệ tinh (20) #1307–#1326 ——
  { no: 1307, title: "Xây Nhà Quận 2", keyword: "xây nhà Quận 2", slug: "xay-nha-quan-2-ngan", status: "done" },
  { no: 1308, title: "Xây Nhà Quận 4", keyword: "xây nhà Quận 4", slug: "xay-nha-quan-4-ngan", status: "done" },
  { no: 1309, title: "Xây Nhà Quận 5", keyword: "xây nhà Quận 5", slug: "xay-nha-quan-5-ngan", status: "done" },
  { no: 1310, title: "Xây Nhà Quận 6", keyword: "xây nhà Quận 6", slug: "xay-nha-quan-6-ngan", status: "done" },
  { no: 1311, title: "Xây Nhà Quận 8", keyword: "xây nhà Quận 8", slug: "xay-nha-quan-8-ngan", status: "done" },
  { no: 1312, title: "Xây Nhà Quận 11", keyword: "xây nhà Quận 11", slug: "xay-nha-quan-11-ngan", status: "done" },
  { no: 1313, title: "Xây Nhà Thủ Thiêm", keyword: "xây nhà Thủ Thiêm", slug: "xay-nha-thu-thiem-ngan", status: "done" },
  { no: 1314, title: "Xây Nhà Bến Cát", keyword: "xây nhà Bến Cát", slug: "xay-nha-ben-cat-ngan", status: "done" },
  { no: 1315, title: "Xây Nhà Tân Uyên", keyword: "xây nhà Tân Uyên", slug: "xay-nha-tan-uyen-ngan", status: "done" },
  { no: 1316, title: "Xây Nhà Long Thành", keyword: "xây nhà Long Thành", slug: "xay-nha-long-thanh-ngan", status: "done" },
  { no: 1317, title: "Xây Nhà Nhơn Trạch", keyword: "xây nhà Nhơn Trạch", slug: "xay-nha-nhon-trach-ngan", status: "done" },
  { no: 1318, title: "Xây Nhà Bến Lức", keyword: "xây nhà Bến Lức", slug: "xay-nha-ben-luc-ngan", status: "done" },
  { no: 1319, title: "Xây Nhà Đức Hòa", keyword: "xây nhà Đức Hòa", slug: "xay-nha-duc-hoa-ngan", status: "done" },
  { no: 1320, title: "Sửa Nhà Quận 1", keyword: "sửa nhà Quận 1", slug: "sua-nha-quan-1-ngan", status: "done" },
  { no: 1321, title: "Sửa Nhà Quận 3", keyword: "sửa nhà Quận 3", slug: "sua-nha-quan-3-ngan", status: "done" },
  { no: 1322, title: "Cải Tạo Nhà Quận 10", keyword: "cải tạo nhà Quận 10", slug: "cai-tao-nha-quan-10-ngan", status: "done" },
  { no: 1323, title: "Cải Tạo Nhà Phú Nhuận", keyword: "cải tạo nhà Phú Nhuận", slug: "cai-tao-nha-phu-nhuan-ngan", status: "done" },
  { no: 1324, title: "Xây Nhà Trọn Gói Thủ Đức", keyword: "xây nhà trọn gói Thủ Đức", slug: "xay-nha-tron-goi-thu-duc-ngan", status: "done" },
  { no: 1325, title: "Xây Nhà Trọn Gói Bình Thạnh", keyword: "xây nhà trọn gói Bình Thạnh", slug: "xay-nha-tron-goi-binh-thanh-ngan", status: "done" },
  { no: 1326, title: "Xây Nhà Trọn Gói Long An", keyword: "xây nhà trọn gói Long An", slug: "xay-nha-tron-goi-long-an-ngan", status: "done" },

  // —— F. Dịch vụ Ads / ý định mua (20) #1327–#1346 ——
  { no: 1327, title: "Thuê Thiết Kế Nhà", keyword: "thuê thiết kế nhà", slug: "thue-thiet-ke-nha-ngan", status: "done" },
  { no: 1328, title: "Thuê Thầu Xây Nhà", keyword: "thuê thầu xây nhà", slug: "thue-thau-xay-nha-ngan", status: "done" },
  { no: 1329, title: "Tìm Nhà Thầu Xây", keyword: "tìm nhà thầu xây", slug: "tim-nha-thau-xay-ngan", status: "done" },
  { no: 1330, title: "Đặt Lịch Khảo Sát", keyword: "đặt lịch khảo sát", slug: "dat-lich-khao-sat-ngan", status: "done" },
  { no: 1331, title: "Khảo Sát Miễn Phí", keyword: "khảo sát miễn phí", slug: "khao-sat-mien-phi-ngan", status: "done" },
  { no: 1332, title: "Tư Vấn Miễn Phí Xây Nhà", keyword: "tư vấn miễn phí xây nhà", slug: "tu-van-mien-phi-xay-nha-ngan", status: "done" },
  { no: 1333, title: "Báo Giá Nhanh Xây Nhà", keyword: "báo giá nhanh xây nhà", slug: "bao-gia-nhanh-xay-nha-ngan", status: "done" },
  { no: 1334, title: "Nhận Báo Giá Xây Nhà", keyword: "nhận báo giá xây nhà", slug: "nhan-bao-gia-xay-nha-ngan", status: "done" },
  { no: 1335, title: "Liên Hệ Xây Nhà", keyword: "liên hệ xây nhà", slug: "lien-he-xay-nha-ngan", status: "done" },
  { no: 1336, title: "Hotline Xây Nhà", keyword: "hotline xây nhà", slug: "hotline-xay-nha-ngan", status: "done" },
  { no: 1337, title: "Xây Nhà Sao Khuê", keyword: "xây nhà Sao Khuê", slug: "xay-nha-sao-khue-ngan", status: "done" },
  { no: 1338, title: "Cải Tạo Sao Khuê", keyword: "cải tạo Sao Khuê", slug: "cai-tao-sao-khue-ngan", status: "done" },
  { no: 1339, title: "Thiết Kế Sao Khuê", keyword: "thiết kế Sao Khuê", slug: "thiet-ke-sao-khue-ngan", status: "done" },
  { no: 1340, title: "Công Ty Sao Khuê", keyword: "công ty Sao Khuê", slug: "cong-ty-sao-khue-ngan", status: "done" },
  { no: 1341, title: "Xây Nhà Gần Đây", keyword: "xây nhà gần đây", slug: "xay-nha-gan-day-ngan", status: "done" },
  { no: 1342, title: "Thầu Xây Gần Đây", keyword: "thầu xây gần đây", slug: "thau-xay-gan-day-ngan", status: "done" },
  { no: 1343, title: "Sửa Nhà Gần Đây", keyword: "sửa nhà gần đây", slug: "sua-nha-gan-day-ngan", status: "done" },
  { no: 1344, title: "Đơn Vị Xây Nhà Uy Tín", keyword: "đơn vị xây nhà uy tín", slug: "don-vi-xay-nha-uy-tin-ngan", status: "done" },
  { no: 1345, title: "Công Ty Xây Dựng Uy Tín", keyword: "công ty xây dựng uy tín", slug: "cong-ty-xay-dung-uy-tin-ngan", status: "done" },
  { no: 1346, title: "Nhà Thầu Xây Dựng Uy Tín", keyword: "nhà thầu xây dựng uy tín", slug: "nha-thau-xay-dung-uy-tin-ngan", status: "done" },
];
