/**
 * Lịch 100 từ khóa SEO — batch 73 (#6747–#6846).
 * Cluster: Q.10/Q.11/Q.3 + pháp lý GPXD + FAQ hợp đồng (indexable *-sk73).
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch73: ContentCalendarItem[] = [
  { no: 6747, title: "Xây Nhà Trọn Gói Quận 10 Mới 2026", keyword: "xây nhà trọn gói Quận 10 mới 2026", slug: "xay-nha-tron-goi-quan-10-moi-2026-sk73", status: "done" },
  { no: 6748, title: "Xây Nhà Trọn Gói Quận 11 Mới 2026", keyword: "xây nhà trọn gói Quận 11 mới 2026", slug: "xay-nha-tron-goi-quan-11-moi-2026-sk73", status: "done" },
  { no: 6749, title: "Xây Nhà Trọn Gói Quận 3 Mới 2026", keyword: "xây nhà trọn gói Quận 3 mới 2026", slug: "xay-nha-tron-goi-quan-3-moi-2026-sk73", status: "done" },
  { no: 6750, title: "Xây Nhà Phường 1 Quận 10", keyword: "xây nhà phường 1 Quận 10", slug: "xay-nha-phuong-1-quan-10-sk73", status: "done" },
  { no: 6751, title: "Xây Nhà Phường 2 Quận 10", keyword: "xây nhà phường 2 Quận 10", slug: "xay-nha-phuong-2-quan-10-sk73", status: "done" },
  { no: 6752, title: "Xây Nhà Phường 5 Quận 10", keyword: "xây nhà phường 5 Quận 10", slug: "xay-nha-phuong-5-quan-10-sk73", status: "done" },
  { no: 6753, title: "Xây Nhà Phường 8 Quận 10", keyword: "xây nhà phường 8 Quận 10", slug: "xay-nha-phuong-8-quan-10-sk73", status: "done" },
  { no: 6754, title: "Xây Nhà Phường 12 Quận 10", keyword: "xây nhà phường 12 Quận 10", slug: "xay-nha-phuong-12-quan-10-sk73", status: "done" },
  { no: 6755, title: "Xây Nhà Phường 15 Quận 10", keyword: "xây nhà phường 15 Quận 10", slug: "xay-nha-phuong-15-quan-10-sk73", status: "done" },
  { no: 6756, title: "Xây Nhà Phường 1 Quận 11", keyword: "xây nhà phường 1 Quận 11", slug: "xay-nha-phuong-1-quan-11-sk73", status: "done" },
  { no: 6757, title: "Xây Nhà Phường 3 Quận 11", keyword: "xây nhà phường 3 Quận 11", slug: "xay-nha-phuong-3-quan-11-sk73", status: "done" },
  { no: 6758, title: "Xây Nhà Phường 5 Quận 11", keyword: "xây nhà phường 5 Quận 11", slug: "xay-nha-phuong-5-quan-11-sk73", status: "done" },
  { no: 6759, title: "Xây Nhà Phường 10 Quận 11", keyword: "xây nhà phường 10 Quận 11", slug: "xay-nha-phuong-10-quan-11-sk73", status: "done" },
  { no: 6760, title: "Xây Nhà Phường 15 Quận 11", keyword: "xây nhà phường 15 Quận 11", slug: "xay-nha-phuong-15-quan-11-sk73", status: "done" },
  { no: 6761, title: "Xây Nhà Phường 2 Quận 3", keyword: "xây nhà phường 2 Quận 3", slug: "xay-nha-phuong-2-quan-3-sk73", status: "done" },
  { no: 6762, title: "Xây Nhà Phường 5 Quận 3", keyword: "xây nhà phường 5 Quận 3", slug: "xay-nha-phuong-5-quan-3-sk73", status: "done" },
  { no: 6763, title: "Xây Nhà Phường 9 Quận 3", keyword: "xây nhà phường 9 Quận 3", slug: "xay-nha-phuong-9-quan-3-sk73", status: "done" },
  { no: 6764, title: "Xây Nhà Phường 12 Quận 3", keyword: "xây nhà phường 12 Quận 3", slug: "xay-nha-phuong-12-quan-3-sk73", status: "done" },
  { no: 6765, title: "Xây Nhà Gần Bệnh Viện Chợ Rẫy", keyword: "xây nhà gần Bệnh viện Chợ Rẫy", slug: "xay-nha-gan-benh-vien-cho-ray-sk73", status: "done" },
  { no: 6766, title: "Xây Nhà Gần Công Viên Lê Thị Riêng", keyword: "xây nhà gần công viên Lê Thị Riêng", slug: "xay-nha-gan-cong-vien-le-thi-rieng-sk73", status: "done" },

  { no: 6767, title: "Cải Tạo Nhà Quận 10 2026", keyword: "cải tạo nhà Quận 10 2026", slug: "cai-tao-nha-quan-10-2026-sk73", status: "done" },
  { no: 6768, title: "Cải Tạo Nhà Quận 11 2026", keyword: "cải tạo nhà Quận 11 2026", slug: "cai-tao-nha-quan-11-2026-sk73", status: "done" },
  { no: 6769, title: "Cải Tạo Nhà Quận 3 2026", keyword: "cải tạo nhà Quận 3 2026", slug: "cai-tao-nha-quan-3-2026-sk73", status: "done" },
  { no: 6770, title: "Cải Tạo Nhà Xin Phép Cải Tạo", keyword: "cải tạo nhà xin phép cải tạo", slug: "cai-tao-nha-xin-phep-cai-tao-sk73", status: "done" },
  { no: 6771, title: "Cải Tạo Nhà Không Đúng Phép", keyword: "cải tạo nhà không đúng phép rủi ro", slug: "cai-tao-nha-khong-dung-phep-rui-ro-sk73", status: "done" },
  { no: 6772, title: "Cải Tạo Nhà Đổi Công Năng", keyword: "cải tạo nhà đổi công năng", slug: "cai-tao-nha-doi-cong-nang-sk73", status: "done" },
  { no: 6773, title: "Cải Tạo Nhà Mở Rộng Mặt Tiền", keyword: "cải tạo nhà mở rộng mặt tiền", slug: "cai-tao-nha-mo-rong-mat-tien-sk73", status: "done" },
  { no: 6774, title: "Cải Tạo Nhà Trong Hẻm Hẹp Q.10", keyword: "cải tạo nhà trong hẻm hẹp Quận 10", slug: "cai-tao-nha-trong-hem-hep-quan-10-sk73", status: "done" },
  { no: 6775, title: "Sửa Nhà Thấm Trần Quận 10", keyword: "sửa nhà thấm trần Quận 10", slug: "sua-nha-tham-tran-quan-10-sk73", status: "done" },
  { no: 6776, title: "Sửa Nhà Thấm Tường Quận 11", keyword: "sửa nhà thấm tường Quận 11", slug: "sua-nha-tham-tuong-quan-11-sk73", status: "done" },
  { no: 6777, title: "Sửa Nhà Nứt Cột Quận 3", keyword: "sửa nhà nứt cột Quận 3", slug: "sua-nha-nut-cot-quan-3-sk73", status: "done" },
  { no: 6778, title: "Sửa Hệ Thống Điện Nhà Cũ Quận 10", keyword: "sửa hệ thống điện nhà cũ Quận 10", slug: "sua-he-thong-dien-nha-cu-quan-10-sk73", status: "done" },
  { no: 6779, title: "Thay Toàn Bộ Hệ Nước Quận 11", keyword: "thay toàn bộ hệ nước Quận 11", slug: "thay-toan-bo-he-nuoc-quan-11-sk73", status: "done" },
  { no: 6780, title: "Nâng Tầng Nhà Có Phải Xin Phép", keyword: "nâng tầng nhà có phải xin phép", slug: "nang-tang-nha-co-phai-xin-phep-sk73", status: "done" },
  { no: 6781, title: "Cải Tạo Nhà Thành Văn Phòng Nhỏ", keyword: "cải tạo nhà thành văn phòng nhỏ", slug: "cai-tao-nha-thanh-van-phong-nho-sk73", status: "done" },
  { no: 6782, title: "Cải Tạo Nhà Thành Phòng Trọ Sinh Viên", keyword: "cải tạo nhà thành phòng trọ sinh viên", slug: "cai-tao-nha-thanh-phong-tro-sinh-vien-sk73", status: "done" },
  { no: 6783, title: "Cải Tạo Nhà Cho Người Khuyết Tật", keyword: "cải tạo nhà cho người khuyết tật", slug: "cai-tao-nha-cho-nguoi-khuyet-tat-sk73", status: "done" },
  { no: 6784, title: "Sửa Chữa Nhà Sau Khi Bị Phạt Xây", keyword: "sửa chữa nhà sau khi bị phạt xây", slug: "sua-chua-nha-sau-khi-bi-phat-xay-sk73", status: "done" },
  { no: 6785, title: "Cải Tạo Nhà Theo Giấy Phép Cũ", keyword: "cải tạo nhà theo giấy phép cũ", slug: "cai-tao-nha-theo-giay-phep-cu-sk73", status: "done" },
  { no: 6786, title: "Cải Tạo Nhà Điều Chỉnh Bản Vẽ", keyword: "cải tạo nhà điều chỉnh bản vẽ", slug: "cai-tao-nha-dieu-chinh-ban-ve-sk73", status: "done" },

  { no: 6787, title: "Chi Phí Xin Giấy Phép Xây Dựng 2026", keyword: "chi phí xin giấy phép xây dựng 2026", slug: "chi-phi-xin-giay-phep-xay-dung-2026-sk73", status: "done" },
  { no: 6788, title: "Chi Phí Làm Hồ Sơ Thiết Kế Xin Phép", keyword: "chi phí làm hồ sơ thiết kế xin phép", slug: "chi-phi-lam-ho-so-thiet-ke-xin-phep-sk73", status: "done" },
  { no: 6789, title: "Chi Phí Xây Nhà 4×10 Trọn Gói", keyword: "chi phí xây nhà 4x10 trọn gói", slug: "chi-phi-xay-nha-4x10-tron-goi-sk73", status: "done" },
  { no: 6790, title: "Chi Phí Xây Nhà 5×12 Trọn Gói", keyword: "chi phí xây nhà 5x12 trọn gói", slug: "chi-phi-xay-nha-5x12-tron-goi-sk73", status: "done" },
  { no: 6791, title: "Chi Phí Xây Nhà 6×14 Trọn Gói", keyword: "chi phí xây nhà 6x14 trọn gói", slug: "chi-phi-xay-nha-6x14-tron-goi-sk73", status: "done" },
  { no: 6792, title: "Báo Giá Tư Vấn Pháp Lý Xây Nhà", keyword: "báo giá tư vấn pháp lý xây nhà", slug: "bao-gia-tu-van-phap-ly-xay-nha-sk73", status: "done" },
  { no: 6793, title: "Báo Giá Làm Hoàn Công Nhà Phố", keyword: "báo giá làm hoàn công nhà phố", slug: "bao-gia-lam-hoan-cong-nha-pho-sk73", status: "done" },
  { no: 6794, title: "Ngân Sách Xây Nhà 4,5 Tỷ TP.HCM", keyword: "ngân sách xây nhà 4.5 tỷ TP.HCM", slug: "ngan-sach-xay-nha-4-5-ty-tphcm-sk73", status: "done" },
  { no: 6795, title: "Ngân Sách Cải Tạo Nhà 350 Triệu", keyword: "ngân sách cải tạo nhà 350 triệu", slug: "ngan-sach-cai-tao-nha-350-trieu-sk73", status: "done" },
  { no: 6796, title: "Chi Phí Phạt Xây Không Phép", keyword: "chi phí phạt xây không phép", slug: "chi-phi-phat-xay-khong-phep-sk73", status: "done" },
  { no: 6797, title: "Chi Phí Điều Chỉnh Giấy Phép", keyword: "chi phí điều chỉnh giấy phép xây dựng", slug: "chi-phi-dieu-chinh-giay-phep-xay-dung-sk73", status: "done" },
  { no: 6798, title: "Báo Giá Giám Sát Theo Tuần", keyword: "báo giá giám sát thi công theo tuần", slug: "bao-gia-giam-sat-thi-cong-theo-tuan-sk73", status: "done" },
  { no: 6799, title: "Báo Giá Làm Biên Bản Nghiệm Thu", keyword: "báo giá làm biên bản nghiệm thu", slug: "bao-gia-lam-bien-ban-nghiem-thu-sk73", status: "done" },
  { no: 6800, title: "Chi Phí Công Chứng Hợp Đồng Xây", keyword: "chi phí công chứng hợp đồng xây", slug: "chi-phi-cong-chung-hop-dong-xay-sk73", status: "done" },
  { no: 6801, title: "Cách Ước Tổng Chi Phí Pháp Lý Xây", keyword: "cách ước tổng chi phí pháp lý xây", slug: "cach-uoc-tong-chi-phi-phap-ly-xay-sk73", status: "done" },

  { no: 6802, title: "Thiết Kế Nhà Phố Theo Lộ Giới", keyword: "thiết kế nhà phố theo lộ giới", slug: "thiet-ke-nha-pho-theo-lo-gioi-sk73", status: "done" },
  { no: 6803, title: "Thiết Kế Nhà Phố Đúng Mật Độ", keyword: "thiết kế nhà phố đúng mật độ xây dựng", slug: "thiet-ke-nha-pho-dung-mat-do-xay-dung-sk73", status: "done" },
  { no: 6804, title: "Thiết Kế Nhà Phố Đúng Chiều Cao", keyword: "thiết kế nhà phố đúng chiều cao quy hoạch", slug: "thiet-ke-nha-pho-dung-chieu-cao-quy-hoach-sk73", status: "done" },
  { no: 6805, title: "Thiết Kế Nhà Phố Có Chỉ Giới Xây Dựng", keyword: "thiết kế nhà phố có chỉ giới xây dựng", slug: "thiet-ke-nha-pho-co-chi-gioi-xay-dung-sk73", status: "done" },
  { no: 6806, title: "Thiết Kế Hồ Sơ Xin Phép Xây Dựng", keyword: "thiết kế hồ sơ xin phép xây dựng", slug: "thiet-ke-ho-so-xin-phep-xay-dung-sk73", status: "done" },
  { no: 6807, title: "Thiết Kế Nhà Phố 9 Phòng Ngủ", keyword: "thiết kế nhà phố 9 phòng ngủ", slug: "thiet-ke-nha-pho-9-phong-ngu-sk73", status: "done" },
  { no: 6808, title: "Thiết Kế Nhà Phố Có Phòng Bác Sĩ", keyword: "thiết kế nhà phố có phòng bác sĩ", slug: "thiet-ke-nha-pho-co-phong-bac-si-sk73", status: "done" },
  { no: 6809, title: "Thiết Kế Nhà Phố Có Phòng Archive", keyword: "thiết kế nhà phố có phòng lưu trữ", slug: "thiet-ke-nha-pho-co-phong-luu-tru-sk73", status: "done" },
  { no: 6810, title: "Thiết Kế Biệt Thự Phố Quận 3", keyword: "thiết kế biệt thự phố Quận 3", slug: "thiet-ke-biet-thu-pho-quan-3-sk73", status: "done" },
  { no: 6811, title: "Thiết Kế Nhà Vườn Đồng Nai Mới", keyword: "thiết kế nhà vườn Đồng Nai mới", slug: "thiet-ke-nha-vuon-dong-nai-moi-sk73", status: "done" },
  { no: 6812, title: "Mẫu Bản Vẽ Xin Phép Nhà Phố 2026", keyword: "mẫu bản vẽ xin phép nhà phố 2026", slug: "mau-ban-ve-xin-phep-nha-pho-2026-sk73", status: "done" },
  { no: 6813, title: "Mẫu Nhà Phố Đúng Quy Hoạch 2026", keyword: "mẫu nhà phố đúng quy hoạch 2026", slug: "mau-nha-pho-dung-quy-hoach-2026-sk73", status: "done" },
  { no: 6814, title: "Thiết Kế Bếp Nhà Phố Đúng Phép", keyword: "thiết kế bếp nhà phố đúng phép", slug: "thiet-ke-bep-nha-pho-dung-phep-sk73", status: "done" },
  { no: 6815, title: "Thiết Kế Cầu Thang Theo Tiêu Chuẩn", keyword: "thiết kế cầu thang theo tiêu chuẩn", slug: "thiet-ke-cau-thang-theo-tieu-chuan-sk73", status: "done" },
  { no: 6816, title: "Thiết Kế Giếng Trời Theo Quy Chuẩn", keyword: "thiết kế giếng trời theo quy chuẩn", slug: "thiet-ke-gieng-troi-theo-quy-chuan-sk73", status: "done" },

  { no: 6817, title: "Xây Nhà Đúng Giấy Phép Xây Dựng", keyword: "xây nhà đúng giấy phép xây dựng", slug: "xay-nha-dung-giay-phep-xay-dung-sk73", status: "done" },
  { no: 6818, title: "Xây Nhà Có Biên Bản Hàng Xóm", keyword: "xây nhà có biên bản hàng xóm", slug: "xay-nha-co-bien-ban-hang-xom-sk73", status: "done" },
  { no: 6819, title: "Đổ Móng Sau Khi Có Giấy Phép", keyword: "đổ móng sau khi có giấy phép", slug: "do-mong-sau-khi-co-giay-phep-sk73", status: "done" },
  { no: 6820, title: "Đổ Sàn Theo Bản Vẽ Được Duyệt", keyword: "đổ sàn theo bản vẽ được duyệt", slug: "do-san-theo-ban-ve-duoc-duyet-sk73", status: "done" },
  { no: 6821, title: "Làm Mái Đúng Chiều Cao Phép", keyword: "làm mái đúng chiều cao phép", slug: "lam-mai-dung-chieu-cao-phep-sk73", status: "done" },
  { no: 6822, title: "Làm Hoàn Công Sau Bàn Giao", keyword: "làm hoàn công sau bàn giao", slug: "lam-hoan-cong-sau-ban-giao-sk73", status: "done" },
  { no: 6823, title: "Chống Thấm Trước Nghiệm Thu", keyword: "chống thấm trước nghiệm thu", slug: "chong-tham-truoc-nghiem-thu-sk73", status: "done" },
  { no: 6824, title: "Lắp Cửa Theo Bản Vẽ Kiến Trúc", keyword: "lắp cửa theo bản vẽ kiến trúc", slug: "lap-cua-theo-ban-ve-kien-truc-sk73", status: "done" },
  { no: 6825, title: "Ốp Mặt Tiền Đúng Chỉ Giới", keyword: "ốp mặt tiền đúng chỉ giới", slug: "op-mat-tien-dung-chi-gioi-sk73", status: "done" },
  { no: 6826, title: "Sơn Nhà Sau Khi Nghiệm Thu Thô", keyword: "sơn nhà sau khi nghiệm thu thô", slug: "son-nha-sau-khi-nghiem-thu-tho-sk73", status: "done" },
  { no: 6827, title: "Lát Gạch Sau Khi Chống Thấm Đạt", keyword: "lát gạch sau khi chống thấm đạt", slug: "lat-gach-sau-khi-chong-tham-dat-sk73", status: "done" },
  { no: 6828, title: "Làm Vách Ngăn Không Đụng Kết Cấu", keyword: "làm vách ngăn không đụng kết cấu", slug: "lam-vach-ngan-khong-dung-ket-cau-sk73", status: "done" },
  { no: 6829, title: "Lắp Camera Giám Sát Công Trình", keyword: "lắp camera giám sát công trình", slug: "lap-camera-giam-sat-cong-trinh-sk73", status: "done" },
  { no: 6830, title: "Lắp Hệ Thống Nhật Ký Thi Công", keyword: "lắp hệ thống nhật ký thi công số", slug: "lap-he-thong-nhat-ky-thi-cong-so-sk73", status: "done" },
  { no: 6831, title: "Gia Cố Nhà Cũ Trước Khi Xin Phép", keyword: "gia cố nhà cũ trước khi xin phép", slug: "gia-co-nha-cu-truoc-khi-xin-phep-sk73", status: "done" },

  { no: 6832, title: "Xây Nhà Trọn Gói Thủ Dầu Một 2026", keyword: "xây nhà trọn gói Thủ Dầu Một 2026", slug: "xay-nha-tron-goi-thu-dau-mot-2026-sk73", status: "done" },
  { no: 6833, title: "Xây Nhà Trọn Gói Long Thành Update", keyword: "xây nhà trọn gói Long Thành update", slug: "xay-nha-tron-goi-long-thanh-update-sk73", status: "done" },
  { no: 6834, title: "Xây Nhà Trọn Gói Nhơn Trạch Update", keyword: "xây nhà trọn gói Nhơn Trạch update", slug: "xay-nha-tron-goi-nhon-trach-update-sk73", status: "done" },
  { no: 6835, title: "Xây Nhà Trọn Gói Bến Lức Update", keyword: "xây nhà trọn gói Bến Lức update", slug: "xay-nha-tron-goi-ben-luc-update-sk73", status: "done" },
  { no: 6836, title: "Xây Nhà Trọn Gói Đức Hòa Update", keyword: "xây nhà trọn gói Đức Hòa update", slug: "xay-nha-tron-goi-duc-hoa-update-sk73", status: "done" },
  { no: 6837, title: "Xây Nhà Trọn Gói Cần Giuộc Update", keyword: "xây nhà trọn gói Cần Giuộc update", slug: "xay-nha-tron-goi-can-giuoc-update-sk73", status: "done" },
  { no: 6838, title: "Xây Nhà Trọn Gói Vũng Tàu 2026", keyword: "xây nhà trọn gói Vũng Tàu 2026", slug: "xay-nha-tron-goi-vung-tau-2026-sk73", status: "done" },
  { no: 6839, title: "Cải Tạo Nhà Quận 10 Hẻm Hẹp", keyword: "cải tạo nhà Quận 10 hẻm hẹp", slug: "cai-tao-nha-quan-10-hem-hep-sk73", status: "done" },
  { no: 6840, title: "Cải Tạo Nhà Quận 3 Liền Kề", keyword: "cải tạo nhà Quận 3 liền kề", slug: "cai-tao-nha-quan-3-lien-ke-sk73", status: "done" },
  { no: 6841, title: "Xin Giấy Phép Xây Dựng Mất Bao Lâu", keyword: "xin giấy phép xây dựng mất bao lâu", slug: "xin-giay-phep-xay-dung-mat-bao-lau-sk73", status: "done" },
  { no: 6842, title: "Hợp Đồng Xây Nhà Cần Có Điều Khoản Gì", keyword: "hợp đồng xây nhà cần có điều khoản gì", slug: "hop-dong-xay-nha-can-co-dieu-khoan-gi-sk73", status: "done" },
  { no: 6843, title: "Xây Nhà Có Nên Công Chứng Hợp Đồng", keyword: "xây nhà có nên công chứng hợp đồng", slug: "xay-nha-co-nen-cong-chung-hop-dong-sk73", status: "done" },
  { no: 6844, title: "Cách Đọc Điều Khoản Phát Sinh", keyword: "cách đọc điều khoản phát sinh hợp đồng", slug: "cach-doc-dieu-khoan-phat-sinh-hop-dong-sk73", status: "done" },
  { no: 6845, title: "Checklist Ký Hợp Đồng Xây Nhà", keyword: "checklist ký hợp đồng xây nhà", slug: "checklist-ky-hop-dong-xay-nha-sk73", status: "done" },
  { no: 6846, title: "Khi Nào Nên Tạm Ứng Đợt Tiếp Theo", keyword: "khi nào nên tạm ứng đợt tiếp theo", slug: "khi-nao-nen-tam-ung-dot-tiep-theo-sk73", status: "done" },
];
