/**
 * Lịch 100 từ khóa ngắn — batch 29 (#2347–#2446).
 * Cluster: quyết định mua, FAQ, quy trình khách hàng.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch29: ContentCalendarItem[] = [
  { no: 2347, title: "Nên Xây Nhà Hay Mua Sẵn", keyword: "nên xây nhà hay mua sẵn", slug: "nen-xay-nha-hay-mua-san-ngan", status: "done" },
  { no: 2348, title: "Nên Xây Hay Mua Chung Cư", keyword: "nên xây hay mua chung cư", slug: "nen-xay-hay-mua-chung-cu-ngan", status: "done" },
  { no: 2349, title: "Nên Cải Tạo Hay Bán Đất", keyword: "nên cải tạo hay bán đất", slug: "nen-cai-tao-hay-ban-dat-ngan", status: "done" },
  { no: 2350, title: "Nên Nâng Tầng Hay Xây Mới", keyword: "nên nâng tầng hay xây mới", slug: "nen-nang-tang-hay-xay-moi-ngan", status: "done" },
  { no: 2351, title: "Nên Thuê KTS Hay Gói Thầu", keyword: "nên thuê kts hay gói thầu", slug: "nen-thue-kts-hay-goi-thau-ngan", status: "done" },
  { no: 2352, title: "Nên Chọn Thầu Gần Hay Xa", keyword: "nên chọn thầu gần hay xa", slug: "nen-chon-thau-gan-hay-xa-ngan", status: "done" },
  { no: 2353, title: "Nên Chọn Gói Rẻ Hay Cao Cấp", keyword: "nên chọn gói rẻ hay cao cấp", slug: "nen-chon-goi-re-hay-cao-cap-ngan", status: "done" },
  { no: 2354, title: "Xây Nhà Bao Nhiêu Là Đủ", keyword: "xây nhà bao nhiêu là đủ", slug: "xay-nha-bao-nhieu-la-du-ngan", status: "done" },
  { no: 2355, title: "Cải Tạo Bao Nhiêu Là Đủ", keyword: "cải tạo bao nhiêu là đủ", slug: "cai-tao-bao-nhieu-la-du-ngan", status: "done" },
  { no: 2356, title: "Ngân Sách 1 Tỷ Xây Được Gì", keyword: "ngân sách 1 tỷ xây được gì", slug: "ngan-sach-1-ty-xay-duoc-gi-ngan", status: "done" },
  { no: 2357, title: "Ngân Sách 2 Tỷ Xây Được Gì", keyword: "ngân sách 2 tỷ xây được gì", slug: "ngan-sach-2-ty-xay-duoc-gi-ngan", status: "done" },
  { no: 2358, title: "Ngân Sách 3 Tỷ Xây Được Gì", keyword: "ngân sách 3 tỷ xây được gì", slug: "ngan-sach-3-ty-xay-duoc-gi-ngan", status: "done" },
  { no: 2359, title: "Ngân Sách 5 Tỷ Xây Được Gì", keyword: "ngân sách 5 tỷ xây được gì", slug: "ngan-sach-5-ty-xay-duoc-gi-ngan", status: "done" },
  { no: 2360, title: "Xây Nhà Cần Chuẩn Bị Gì", keyword: "xây nhà cần chuẩn bị gì", slug: "xay-nha-can-chuan-bi-gi-ngan", status: "done" },
  { no: 2361, title: "Cải Tạo Cần Chuẩn Bị Gì", keyword: "cải tạo cần chuẩn bị gì", slug: "cai-tao-can-chuan-bi-gi-ngan", status: "done" },
  { no: 2362, title: "Trước Khi Ký Hợp Đồng Xây", keyword: "trước khi ký hợp đồng xây", slug: "truoc-khi-ky-hop-dong-xay-ngan", status: "done" },
  { no: 2363, title: "Sau Khi Ký Hợp Đồng Xây", keyword: "sau khi ký hợp đồng xây", slug: "sau-khi-ky-hop-dong-xay-ngan", status: "done" },
  { no: 2364, title: "Trong Quá Trình Thi Công", keyword: "trong quá trình thi công", slug: "trong-qua-trinh-thi-cong-ngan", status: "done" },
  { no: 2365, title: "Khi Nghiệm Thu Nhà", keyword: "khi nghiệm thu nhà", slug: "khi-nghiem-thu-nha-ngan", status: "done" },
  { no: 2366, title: "Sau Khi Bàn Giao Nhà", keyword: "sau khi bàn giao nhà", slug: "sau-khi-ban-giao-nha-ngan", status: "done" },
  { no: 2367, title: "Quyền Lợi Chủ Nhà Khi Xây", keyword: "quyền lợi chủ nhà khi xây", slug: "quyen-loi-chu-nha-khi-xay-ngan", status: "done" },
  { no: 2368, title: "Nghĩa Vụ Chủ Nhà Khi Xây", keyword: "nghĩa vụ chủ nhà khi xây", slug: "nghia-vu-chu-nha-khi-xay-ngan", status: "done" },
  { no: 2369, title: "Quyền Lợi Nhà Thầu", keyword: "quyền lợi nhà thầu", slug: "quyen-loi-nha-thau-ngan", status: "done" },
  { no: 2370, title: "Nghĩa Vụ Nhà Thầu", keyword: "nghĩa vụ nhà thầu", slug: "nghia-vu-nha-thau-ngan", status: "done" },
  { no: 2371, title: "Tranh Chấp Hợp Đồng Xây", keyword: "tranh chấp hợp đồng xây", slug: "tranh-chap-hop-dong-xay-ngan", status: "done" },
  { no: 2372, title: "Hòa Giải Tranh Chấp Xây", keyword: "hòa giải tranh chấp xây", slug: "hoa-giai-tranh-chap-xay-ngan", status: "done" },
  { no: 2373, title: "Đơn Phương Chấm Dứt HĐ", keyword: "đơn phương chấm dứt hợp đồng xây", slug: "don-phuong-cham-dut-hd-xay-ngan", status: "done" },
  { no: 2374, title: "Đòi Bảo Hành Xây Nhà", keyword: "đòi bảo hành xây nhà", slug: "doi-bao-hanh-xay-nha-ngan", status: "done" },
  { no: 2375, title: "Khiếu Nại Chất Lượng Xây", keyword: "khiếu nại chất lượng xây", slug: "khieu-nai-chat-luong-xay-ngan", status: "done" },
  { no: 2376, title: "Biên Bản Nghiệm Thu Mẫu", keyword: "biên bản nghiệm thu mẫu", slug: "bien-ban-nghiem-thu-mau-ngan", status: "done" },
  { no: 2377, title: "Biên Bản Bàn Giao Mẫu", keyword: "biên bản bàn giao mẫu", slug: "bien-ban-ban-giao-mau-ngan", status: "done" },
  { no: 2378, title: "Hợp Đồng Xây Mẫu", keyword: "hợp đồng xây mẫu", slug: "hop-dong-xay-mau-ngan", status: "done" },
  { no: 2379, title: "Phụ Lục Phát Sinh Mẫu", keyword: "phụ lục phát sinh mẫu", slug: "phu-luc-phat-sinh-mau-ngan", status: "done" },
  { no: 2380, title: "Checklist Nghiệm Thu Thô", keyword: "checklist nghiệm thu thô", slug: "checklist-nghiem-thu-tho-ngan", status: "done" },
  { no: 2381, title: "Checklist Nghiệm Thu Hoàn Thiện", keyword: "checklist nghiệm thu hoàn thiện", slug: "checklist-nghiem-thu-hoan-thien-ngan", status: "done" },
  { no: 2382, title: "Checklist Bàn Giao Chìa Khóa", keyword: "checklist bàn giao chìa khóa", slug: "checklist-ban-giao-chia-khoa-ngan", status: "done" },
  { no: 2383, title: "Câu Hỏi Thường Gặp Xây Nhà", keyword: "câu hỏi thường gặp xây nhà", slug: "cau-hoi-thuong-gap-xay-nha-ngan", status: "done" },
  { no: 2384, title: "Câu Hỏi Thường Gặp Cải Tạo", keyword: "câu hỏi thường gặp cải tạo", slug: "cau-hoi-thuong-gap-cai-tao-ngan", status: "done" },
  { no: 2385, title: "Myth Xây Nhà Sai", keyword: "myth xây nhà sai", slug: "myth-xay-nha-sai-ngan", status: "done" },
  { no: 2386, title: "Hiểu Lầm Khi Xây Nhà", keyword: "hiểu lầm khi xây nhà", slug: "hieu-lam-khi-xay-nha-ngan", status: "done" },
  { no: 2387, title: "Hiểu Lầm Khi Cải Tạo", keyword: "hiểu lầm khi cải tạo", slug: "hieu-lam-khi-cai-tao-ngan", status: "done" },
  { no: 2388, title: "Hiểu Lầm Về Trọn Gói", keyword: "hiểu lầm về trọn gói", slug: "hieu-lam-ve-tron-goi-ngan", status: "done" },
  { no: 2389, title: "Hiểu Lầm Về Phần Thô", keyword: "hiểu lầm về phần thô", slug: "hieu-lam-ve-phan-tho-ngan", status: "done" },
  { no: 2390, title: "Hiểu Lầm Về Đơn Giá m2", keyword: "hiểu lầm về đơn giá m2", slug: "hieu-lam-ve-don-gia-m2-ngan", status: "done" },
  { no: 2391, title: "Vì Sao Báo Giá Chênh Lệch", keyword: "vì sao báo giá chênh lệch", slug: "vi-sao-bao-gia-chenh-lech-ngan", status: "done" },
  { no: 2392, title: "Vì Sao Phát Sinh Xây Nhà", keyword: "vì sao phát sinh xây nhà", slug: "vi-sao-phat-sinh-xay-nha-ngan", status: "done" },
  { no: 2393, title: "Vì Sao Trễ Tiến Độ Xây", keyword: "vì sao trễ tiến độ xây", slug: "vi-sao-tre-tien-do-xay-ngan", status: "done" },
  { no: 2394, title: "Vì Sao Nhà Thấm Sau Xây", keyword: "vì sao nhà thấm sau xây", slug: "vi-sao-nha-tham-sau-xay-ngan", status: "done" },
  { no: 2395, title: "Vì Sao Nên Khảo Sát Trước", keyword: "vì sao nên khảo sát trước", slug: "vi-sao-nen-khao-sat-truoc-ngan", status: "done" },
  { no: 2396, title: "Vì Sao Nên Có Giám Sát", keyword: "vì sao nên có giám sát", slug: "vi-sao-nen-co-giam-sat-ngan", status: "done" },
  { no: 2397, title: "Vì Sao Không Nên Bán Thầu", keyword: "vì sao không nên bán thầu", slug: "vi-sao-khong-nen-ban-thau-ngan", status: "done" },
  { no: 2398, title: "Lợi Ích Xây Trọn Gói", keyword: "lợi ích xây trọn gói", slug: "loi-ich-xay-tron-goi-ngan", status: "done" },
  { no: 2399, title: "Lợi Ích Xây Phần Thô", keyword: "lợi ích xây phần thô", slug: "loi-ich-xay-phan-tho-ngan", status: "done" },
  { no: 2400, title: "Lợi Ích Thiết Kế Trước", keyword: "lợi ích thiết kế trước", slug: "loi-ich-thiet-ke-truoc-ngan", status: "done" },
  { no: 2401, title: "Lợi Ích Cải Tạo Thay Xây Mới", keyword: "lợi ích cải tạo thay xây mới", slug: "loi-ich-cai-tao-thay-xay-moi-ngan", status: "done" },
  { no: 2402, title: "Rủi Ro Tự Xây Nhà", keyword: "rủi ro tự xây nhà", slug: "rui-ro-tu-xay-nha-ngan", status: "done" },
  { no: 2403, title: "Rủi Ro Thuê Thầu Rẻ", keyword: "rủi ro thuê thầu rẻ", slug: "rui-ro-thue-thau-re-ngan", status: "done" },
  { no: 2404, title: "Rủi Ro Không Xin Phép", keyword: "rủi ro không xin phép", slug: "rui-ro-khong-xin-phep-ngan", status: "done" },
  { no: 2405, title: "Rủi Ro Không Hợp Đồng", keyword: "rủi ro không hợp đồng", slug: "rui-ro-khong-hop-dong-ngan", status: "done" },
  { no: 2406, title: "Rủi Ro Không Bảo Hành", keyword: "rủi ro không bảo hành", slug: "rui-ro-khong-bao-hanh-ngan", status: "done" },
  { no: 2407, title: "Top Tiêu Chí Chọn Thầu", keyword: "top tiêu chí chọn thầu", slug: "top-tieu-chi-chon-thau-ngan", status: "done" },
  { no: 2408, title: "Top Câu Hỏi Cho Thầu", keyword: "top câu hỏi cho thầu", slug: "top-cau-hoi-cho-thau-ngan", status: "done" },
  { no: 2409, title: "Top Sai Lầm Chủ Nhà", keyword: "top sai lầm chủ nhà", slug: "top-sai-lam-chu-nha-ngan", status: "done" },
  { no: 2410, title: "Top Việc Nên Làm Trước Xây", keyword: "top việc nên làm trước xây", slug: "top-viec-nen-lam-truoc-xay-ngan", status: "done" },
  { no: 2411, title: "Top Việc Nên Tránh Khi Xây", keyword: "top việc nên tránh khi xây", slug: "top-viec-nen-tranh-khi-xay-ngan", status: "done" },
  { no: 2412, title: "Roadmap Xây Nhà 2026", keyword: "roadmap xây nhà 2026", slug: "roadmap-xay-nha-2026-ngan", status: "done" },
  { no: 2413, title: "Timeline Xây Nhà Phố", keyword: "timeline xây nhà phố", slug: "timeline-xay-nha-pho-ngan", status: "done" },
  { no: 2414, title: "Timeline Cải Tạo Nhà", keyword: "timeline cải tạo nhà", slug: "timeline-cai-tao-nha-ngan", status: "done" },
  { no: 2415, title: "Milestone Thanh Toán Xây", keyword: "milestone thanh toán xây", slug: "milestone-thanh-toan-xay-ngan", status: "done" },
  { no: 2416, title: "KPI Giám Sát Công Trình", keyword: "kpi giám sát công trình", slug: "kpi-giam-sat-cong-trinh-ngan", status: "done" },
  { no: 2417, title: "QC Checklist Xây Nhà", keyword: "qc checklist xây nhà", slug: "qc-checklist-xay-nha-ngan", status: "done" },
  { no: 2418, title: "Snag List Bàn Giao", keyword: "snag list bàn giao", slug: "snag-list-ban-giao-ngan", status: "done" },
  { no: 2419, title: "Punch List Sửa Chữa", keyword: "punch list sửa chữa", slug: "punch-list-sua-chua-ngan", status: "done" },
  { no: 2420, title: "As-Built Drawing Nhà", keyword: "as-built drawing nhà", slug: "as-built-drawing-nha-ngan", status: "done" },
  { no: 2421, title: "O&M Manual Nhà", keyword: "o&m manual nhà", slug: "om-manual-nha-ngan", status: "done" },
  { no: 2422, title: "Warranty Claim Xây Nhà", keyword: "warranty claim xây nhà", slug: "warranty-claim-xay-nha-ngan", status: "done" },
  { no: 2423, title: "After Sales Xây Nhà", keyword: "after sales xây nhà", slug: "after-sales-xay-nha-ngan", status: "done" },
  { no: 2424, title: "Loyalty Khách Hàng Xây", keyword: "loyalty khách hàng xây", slug: "loyalty-khach-hang-xay-ngan", status: "done" },
  { no: 2425, title: "Referral Program Xây", keyword: "referral program xây", slug: "referral-program-xay-ngan", status: "done" },
  { no: 2426, title: "Testimonial Xây Nhà", keyword: "testimonial xây nhà", slug: "testimonial-xay-nha-ngan", status: "done" },
  { no: 2427, title: "Case Study Cải Tạo", keyword: "case study cải tạo", slug: "case-study-cai-tao-ngan", status: "done" },
  { no: 2428, title: "Portfolio Công Trình", keyword: "portfolio công trình", slug: "portfolio-cong-trinh-ngan", status: "done" },
  { no: 2429, title: "Showroom Vật Tư Xây", keyword: "showroom vật tư xây", slug: "showroom-vat-tu-xay-ngan", status: "done" },
  { no: 2430, title: "Tour Công Trình Mở", keyword: "tour công trình mở", slug: "tour-cong-trinh-mo-ngan", status: "done" },
  { no: 2431, title: "Open House Xây Nhà", keyword: "open house xây nhà", slug: "open-house-xay-nha-ngan", status: "done" },
  { no: 2432, title: "Workshop Xây Nhà", keyword: "workshop xây nhà", slug: "workshop-xay-nha-ngan", status: "done" },
  { no: 2433, title: "Webinar Tư Vấn Xây", keyword: "webinar tư vấn xây", slug: "webinar-tu-van-xay-ngan", status: "done" },
  { no: 2434, title: "Ebook Kinh Nghiệm Xây", keyword: "ebook kinh nghiệm xây", slug: "ebook-kinh-nghiem-xay-ngan", status: "done" },
  { no: 2435, title: "Checklist PDF Xây Nhà", keyword: "checklist pdf xây nhà", slug: "checklist-pdf-xay-nha-ngan", status: "done" },
  { no: 2436, title: "Chủ Đề Mở Rộng 29 1", keyword: "chủ đề mở rộng 29 1", slug: "chu-de-mo-rong-29-1-ngan", status: "done" },
  { no: 2437, title: "Chủ Đề Mở Rộng 29 2", keyword: "chủ đề mở rộng 29 2", slug: "chu-de-mo-rong-29-2-ngan", status: "done" },
  { no: 2438, title: "Chủ Đề Mở Rộng 29 3", keyword: "chủ đề mở rộng 29 3", slug: "chu-de-mo-rong-29-3-ngan", status: "done" },
  { no: 2439, title: "Chủ Đề Mở Rộng 29 4", keyword: "chủ đề mở rộng 29 4", slug: "chu-de-mo-rong-29-4-ngan", status: "done" },
  { no: 2440, title: "Chủ Đề Mở Rộng 29 5", keyword: "chủ đề mở rộng 29 5", slug: "chu-de-mo-rong-29-5-ngan", status: "done" },
  { no: 2441, title: "Chủ Đề Mở Rộng 29 6", keyword: "chủ đề mở rộng 29 6", slug: "chu-de-mo-rong-29-6-ngan", status: "done" },
  { no: 2442, title: "Chủ Đề Mở Rộng 29 7", keyword: "chủ đề mở rộng 29 7", slug: "chu-de-mo-rong-29-7-ngan", status: "done" },
  { no: 2443, title: "Chủ Đề Mở Rộng 29 8", keyword: "chủ đề mở rộng 29 8", slug: "chu-de-mo-rong-29-8-ngan", status: "done" },
  { no: 2444, title: "Chủ Đề Mở Rộng 29 9", keyword: "chủ đề mở rộng 29 9", slug: "chu-de-mo-rong-29-9-ngan", status: "done" },
  { no: 2445, title: "Chủ Đề Mở Rộng 29 10", keyword: "chủ đề mở rộng 29 10", slug: "chu-de-mo-rong-29-10-ngan", status: "done" },
  { no: 2446, title: "Chủ Đề Mở Rộng 29 11", keyword: "chủ đề mở rộng 29 11", slug: "chu-de-mo-rong-29-11-ngan", status: "done" },
];
