/**
 * Lịch 100 từ khóa ngắn — batch 39 (#3347–#3446).
 * Cluster: kịch bản gia đình, so sánh, mùa vụ, lifestyle Ads.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch39: ContentCalendarItem[] = [
  { no: 3347, title: "Xây Nhà Cho Gia Đình 3 Người", keyword: "xây nhà cho gia đình 3 người", slug: "xay-nha-cho-gia-dinh-3-nguoi-ngan", status: "done" },
  { no: 3348, title: "Xây Nhà Cho Gia Đình 4 Người", keyword: "xây nhà cho gia đình 4 người", slug: "xay-nha-cho-gia-dinh-4-nguoi-ngan", status: "done" },
  { no: 3349, title: "Xây Nhà Cho Gia Đình 5 Người", keyword: "xây nhà cho gia đình 5 người", slug: "xay-nha-cho-gia-dinh-5-nguoi-ngan", status: "done" },
  { no: 3350, title: "Xây Nhà Cho Gia Đình 3 Thế Hệ", keyword: "xây nhà cho gia đình 3 thế hệ", slug: "xay-nha-cho-gia-dinh-3-the-he-ngan", status: "done" },
  { no: 3351, title: "Xây Nhà Cho Vợ Chồng Trẻ", keyword: "xây nhà cho vợ chồng trẻ", slug: "xay-nha-cho-vo-chong-tre-ngan", status: "done" },
  { no: 3352, title: "Xây Nhà Cho Người Độc Thân", keyword: "xây nhà cho người độc thân", slug: "xay-nha-cho-nguoi-doc-than-ngan", status: "done" },
  { no: 3353, title: "Xây Nhà Cho Người Về Hưu", keyword: "xây nhà cho người về hưu", slug: "xay-nha-cho-nguoi-ve-huu-ngan", status: "done" },
  { no: 3354, title: "Xây Nhà Cho Con Cái", keyword: "xây nhà cho con cái", slug: "xay-nha-cho-con-cai-ngan", status: "done" },
  { no: 3355, title: "Xây Nhà Tặng Cha Mẹ", keyword: "xây nhà tặng cha mẹ", slug: "xay-nha-tang-cha-me-ngan", status: "done" },
  { no: 3356, title: "Xây Nhà Sau Kết Hôn", keyword: "xây nhà sau kết hôn", slug: "xay-nha-sau-ket-hon-ngan", status: "done" },
  { no: 3357, title: "Xây Nhà Khi Có Em Bé", keyword: "xây nhà khi có em bé", slug: "xay-nha-khi-co-em-be-ngan", status: "done" },
  { no: 3358, title: "Cải Tạo Nhà Khi Có Em Bé", keyword: "cải tạo nhà khi có em bé", slug: "cai-tao-nha-khi-co-em-be-ngan", status: "done" },
  { no: 3359, title: "Cải Tạo Nhà Khi Con Lớn", keyword: "cải tạo nhà khi con lớn", slug: "cai-tao-nha-khi-con-lon-ngan", status: "done" },
  { no: 3360, title: "Cải Tạo Nhà Khi Cha Mẹ Ở Chung", keyword: "cải tạo nhà khi cha mẹ ở chung", slug: "cai-tao-nha-khi-cha-me-o-chung-ngan", status: "done" },
  { no: 3361, title: "Xây Nhà Để Ở Hay Cho Thuê", keyword: "xây nhà để ở hay cho thuê", slug: "xay-nha-de-o-hay-cho-thue-ngan", status: "done" },
  { no: 3362, title: "Xây Nhà Đầu Tư Hay Ở", keyword: "xây nhà đầu tư hay ở", slug: "xay-nha-dau-tu-hay-o-ngan", status: "done" },
  { no: 3363, title: "Xây Nhà Cấp 4 Hay 2 Tầng", keyword: "xây nhà cấp 4 hay 2 tầng", slug: "xay-nha-cap-4-hay-2-tang-ngan", status: "done" },
  { no: 3364, title: "Xây Nhà 2 Tầng Hay 3 Tầng", keyword: "xây nhà 2 tầng hay 3 tầng", slug: "xay-nha-2-tang-hay-3-tang-ngan", status: "done" },
  { no: 3365, title: "Xây Nhà 3 Tầng Hay 4 Tầng", keyword: "xây nhà 3 tầng hay 4 tầng", slug: "xay-nha-3-tang-hay-4-tang-ngan", status: "done" },
  { no: 3366, title: "Xây Nhà Phố Hay Biệt Thự", keyword: "xây nhà phố hay biệt thự", slug: "xay-nha-pho-hay-biet-thu-ngan", status: "done" },
  { no: 3367, title: "Xây Nhà Ống Hay Nhà Lệch Tầng", keyword: "xây nhà ống hay nhà lệch tầng", slug: "xay-nha-ong-hay-nha-lech-tang-ngan", status: "done" },
  { no: 3368, title: "Mái Bằng Hay Mái Thái", keyword: "mái bằng hay mái thái", slug: "mai-bang-hay-mai-thai-ngan", status: "done" },
  { no: 3369, title: "Mái Tôn Hay Mái Ngói", keyword: "mái tôn hay mái ngói", slug: "mai-ton-hay-mai-ngoi-ngan", status: "done" },
  { no: 3370, title: "Sàn Gỗ Hay Gạch Men", keyword: "sàn gỗ hay gạch men", slug: "san-go-hay-gach-men-ngan", status: "done" },
  { no: 3371, title: "Sàn Nhựa Hay Sàn Gỗ", keyword: "sàn nhựa hay sàn gỗ", slug: "san-nhua-hay-san-go-ngan", status: "done" },
  { no: 3372, title: "Cửa Nhôm Hay Cửa Gỗ", keyword: "cửa nhôm hay cửa gỗ", slug: "cua-nhom-hay-cua-go-ngan", status: "done" },
  { no: 3373, title: "Cửa Nhựa Hay Cửa Nhôm", keyword: "cửa nhựa hay cửa nhôm", slug: "cua-nhua-hay-cua-nhom-ngan", status: "done" },
  { no: 3374, title: "Sơn Nước Hay Sơn Dầu", keyword: "sơn nước hay sơn dầu", slug: "son-nuoc-hay-son-dau-ngan", status: "done" },
  { no: 3375, title: "Trần Thạch Cao Hay Trần Gỗ", keyword: "trần thạch cao hay trần gỗ", slug: "tran-thach-cao-hay-tran-go-ngan", status: "done" },
  { no: 3376, title: "Bếp Đảo Hay Bếp Chữ L", keyword: "bếp đảo hay bếp chữ l", slug: "bep-dao-hay-bep-chu-l-ngan", status: "done" },
  { no: 3377, title: "Bếp Chữ U Hay Chữ I", keyword: "bếp chữ u hay chữ i", slug: "bep-chu-u-hay-chu-i-ngan", status: "done" },
  { no: 3378, title: "WC Khô Hay WC Ướt", keyword: "wc khô hay wc ướt", slug: "wc-kho-hay-wc-uot-ngan", status: "done" },
  { no: 3379, title: "Giếng Trời Hay Cửa Sổ", keyword: "giếng trời hay cửa sổ", slug: "gieng-troi-hay-cua-so-ngan", status: "done" },
  { no: 3380, title: "Xây Mùa Xuân", keyword: "xây nhà mùa xuân", slug: "xay-nha-mua-xuan-ngan", status: "done" },
  { no: 3381, title: "Xây Mùa Hè", keyword: "xây nhà mùa hè", slug: "xay-nha-mua-he-ngan", status: "done" },
  { no: 3382, title: "Xây Mùa Thu", keyword: "xây nhà mùa thu", slug: "xay-nha-mua-thu-ngan", status: "done" },
  { no: 3383, title: "Xây Mùa Đông", keyword: "xây nhà mùa đông", slug: "xay-nha-mua-dong-ngan", status: "done" },
  { no: 3384, title: "Xây Nhà Trước Tết", keyword: "xây nhà trước tết", slug: "xay-nha-truoc-tet-ngan", status: "done" },
  { no: 3385, title: "Xây Nhà Sau Tết", keyword: "xây nhà sau tết", slug: "xay-nha-sau-tet-ngan", status: "done" },
  { no: 3386, title: "Cải Tạo Trước Tết", keyword: "cải tạo trước tết", slug: "cai-tao-truoc-tet-ngan", status: "done" },
  { no: 3387, title: "Cải Tạo Sau Tết", keyword: "cải tạo sau tết", slug: "cai-tao-sau-tet-ngan", status: "done" },
  { no: 3388, title: "Xây Nhà Năm 2026", keyword: "xây nhà năm 2026", slug: "xay-nha-nam-2026-ngan", status: "done" },
  { no: 3389, title: "Cải Tạo Nhà Năm 2026", keyword: "cải tạo nhà năm 2026", slug: "cai-tao-nha-nam-2026-ngan", status: "done" },
  { no: 3390, title: "Nên Xây Nhà Tháng Nào", keyword: "nên xây nhà tháng nào", slug: "nen-xay-nha-thang-nao-ngan", status: "done" },
  { no: 3391, title: "Nên Cải Tạo Tháng Nào", keyword: "nên cải tạo tháng nào", slug: "nen-cai-tao-thang-nao-ngan", status: "done" },
  { no: 3392, title: "Xây Nhà Khi Giá VLXD Tăng", keyword: "xây nhà khi giá vlxd tăng", slug: "xay-nha-khi-gia-vlxd-tang-ngan", status: "done" },
  { no: 3393, title: "Xây Nhà Khi Giá VLXD Giảm", keyword: "xây nhà khi giá vlxd giảm", slug: "xay-nha-khi-gia-vlxd-giam-ngan", status: "done" },
  { no: 3394, title: "Chờ Giá Vật Tư Hay Xây Ngay", keyword: "chờ giá vật tư hay xây ngay", slug: "cho-gia-vat-tu-hay-xay-ngay-ngan", status: "done" },
  { no: 3395, title: "Xây Nhà Khi Lãi Suất Cao", keyword: "xây nhà khi lãi suất cao", slug: "xay-nha-khi-lai-suat-cao-ngan", status: "done" },
  { no: 3396, title: "Xây Nhà Khi Lãi Suất Thấp", keyword: "xây nhà khi lãi suất thấp", slug: "xay-nha-khi-lai-suat-thap-ngan", status: "done" },
  { no: 3397, title: "Nhà Đẹp Cho Đón Khách", keyword: "nhà đẹp cho đón khách", slug: "nha-dep-cho-don-khach-ngan", status: "done" },
  { no: 3398, title: "Nhà Đẹp Cho Chụp Ảnh", keyword: "nhà đẹp cho chụp ảnh", slug: "nha-dep-cho-chup-anh-ngan", status: "done" },
  { no: 3399, title: "Nhà Đẹp Cho Quay Video", keyword: "nhà đẹp cho quay video", slug: "nha-dep-cho-quay-video-ngan", status: "done" },
  { no: 3400, title: "Nhà Phong Thủy Tốt", keyword: "nhà phong thủy tốt", slug: "nha-phong-thuy-tot-ngan", status: "done" },
  { no: 3401, title: "Hướng Cửa Chính Phong Thủy", keyword: "hướng cửa chính phong thủy", slug: "huong-cua-chinh-phong-thuy-ngan", status: "done" },
  { no: 3402, title: "Vị Trí Bếp Phong Thủy", keyword: "vị trí bếp phong thủy", slug: "vi-tri-bep-phong-thuy-ngan", status: "done" },
  { no: 3403, title: "Vị Trí Phòng Ngủ Phong Thủy", keyword: "vị trí phòng ngủ phong thủy", slug: "vi-tri-phong-ngu-phong-thuy-ngan", status: "done" },
  { no: 3404, title: "Vị Trí WC Phong Thủy", keyword: "vị trí wc phong thủy", slug: "vi-tri-wc-phong-thuy-ngan", status: "done" },
  { no: 3405, title: "Màu Sơn Phong Thủy", keyword: "màu sơn phong thủy", slug: "mau-son-phong-thuy-ls-ngan", status: "done" },
  { no: 3406, title: "Cây Cảnh Phong Thủy Nhà", keyword: "cây cảnh phong thủy nhà", slug: "cay-canh-phong-thuy-nha-ngan", status: "done" },
  { no: 3407, title: "Nhà Cho Pet", keyword: "nhà cho pet", slug: "nha-cho-pet-ngan", status: "done" },
  { no: 3408, title: "Góc Chơi Cho Chó Mèo", keyword: "góc chơi cho chó mèo", slug: "goc-choi-cho-cho-meo-ngan", status: "done" },
  { no: 3409, title: "Sân Chơi Trẻ Em Trong Nhà", keyword: "sân chơi trẻ em trong nhà", slug: "san-choi-tre-em-trong-nha-ls-ngan", status: "done" },
  { no: 3410, title: "Góc Đọc Sách Nhà Phố", keyword: "góc đọc sách nhà phố", slug: "goc-doc-sach-nha-pho-ngan", status: "done" },
  { no: 3411, title: "Góc Cà Phê Tại Gia", keyword: "góc cà phê tại gia", slug: "goc-ca-phe-tai-gia-ngan", status: "done" },
  { no: 3412, title: "Góc Làm Vườn Mini", keyword: "góc làm vườn mini", slug: "goc-lam-vuon-mini-ngan", status: "done" },
  { no: 3413, title: "Nhà Ở Kết Hợp Làm Việc", keyword: "nhà ở kết hợp làm việc", slug: "nha-o-ket-hop-lam-viec-ngan", status: "done" },
  { no: 3414, title: "Nhà Ở Kết Hợp Shop Online", keyword: "nhà ở kết hợp shop online", slug: "nha-o-ket-hop-shop-online-ngan", status: "done" },
  { no: 3415, title: "Nhà Ở Kết Hợp Studio", keyword: "nhà ở kết hợp studio", slug: "nha-o-ket-hop-studio-ngan", status: "done" },
  { no: 3416, title: "Trước Khi Xây Nhà Hỏi Gì", keyword: "trước khi xây nhà hỏi gì", slug: "truoc-khi-xay-nha-hoi-gi-ngan", status: "done" },
  { no: 3417, title: "Trước Khi Cải Tạo Hỏi Gì", keyword: "trước khi cải tạo hỏi gì", slug: "truoc-khi-cai-tao-hoi-gi-ngan", status: "done" },
  { no: 3418, title: "Câu Hỏi Cho Kiến Trúc Sư", keyword: "câu hỏi cho kiến trúc sư", slug: "cau-hoi-cho-kien-truc-su-ngan", status: "done" },
  { no: 3419, title: "Câu Hỏi Cho Nhà Thầu", keyword: "câu hỏi cho nhà thầu", slug: "cau-hoi-cho-nha-thau-faq-ngan", status: "done" },
  { no: 3420, title: "Red Flag Nhà Thầu Xấu", keyword: "red flag nhà thầu xấu", slug: "red-flag-nha-thau-xau-ngan", status: "done" },
  { no: 3421, title: "Green Flag Nhà Thầu Tốt", keyword: "green flag nhà thầu tốt", slug: "green-flag-nha-thau-tot-ngan", status: "done" },
  { no: 3422, title: "Checklist Chủ Nhà Mới", keyword: "checklist chủ nhà mới", slug: "checklist-chu-nha-moi-ngan", status: "done" },
  { no: 3423, title: "Checklist Chủ Nhà Cải Tạo", keyword: "checklist chủ nhà cải tạo", slug: "checklist-chu-nha-cai-tao-ngan", status: "done" },
  { no: 3424, title: "Nhật Ký Xây Nhà Thực Tế", keyword: "nhật ký xây nhà thực tế", slug: "nhat-ky-xay-nha-thuc-te-ngan", status: "done" },
  { no: 3425, title: "Nhật Ký Cải Tạo Thực Tế", keyword: "nhật ký cải tạo thực tế", slug: "nhat-ky-cai-tao-thuc-te-ngan", status: "done" },
  { no: 3426, title: "Bài Học Xây Nhà Lần Đầu", keyword: "bài học xây nhà lần đầu", slug: "bai-hoc-xay-nha-lan-dau-ngan", status: "done" },
  { no: 3427, title: "Bài Học Cải Tạo Lần Đầu", keyword: "bài học cải tạo lần đầu", slug: "bai-hoc-cai-tao-lan-dau-ngan", status: "done" },
  { no: 3428, title: "Sai Lầm Đắt Giá Khi Xây", keyword: "sai lầm đắt giá khi xây", slug: "sai-lam-dat-gia-khi-xay-ngan", status: "done" },
  { no: 3429, title: "Sai Lầm Đắt Giá Khi Cải Tạo", keyword: "sai lầm đắt giá khi cải tạo", slug: "sai-lam-dat-gia-khi-cai-tao-ngan", status: "done" },
  { no: 3430, title: "Xây Nhà Tiết Kiệm Thông Minh", keyword: "xây nhà tiết kiệm thông minh", slug: "xay-nha-tiet-kiem-thong-minh-ngan", status: "done" },
  { no: 3431, title: "Cải Tạo Tiết Kiệm Thông Minh", keyword: "cải tạo tiết kiệm thông minh", slug: "cai-tao-tiet-kiem-thong-minh-ngan", status: "done" },
  { no: 3432, title: "Ưu Đãi Xây Nhà Hôm Nay", keyword: "ưu đãi xây nhà hôm nay", slug: "uu-dai-xay-nha-hom-nay-ads-ngan", status: "done" },
  { no: 3433, title: "Ưu Đãi Cải Tạo Hôm Nay", keyword: "ưu đãi cải tạo hôm nay", slug: "uu-dai-cai-tao-hom-nay-ads-ngan", status: "done" },
  { no: 3434, title: "Tặng Thiết Kế Khi Ký Thầu", keyword: "tặng thiết kế khi ký thầu", slug: "tang-thiet-ke-khi-ky-thau-ads-ngan", status: "done" },
  { no: 3435, title: "Giảm Giá Xây Phần Thô", keyword: "giảm giá xây phần thô", slug: "giam-gia-xay-phan-tho-ads-ngan", status: "done" },
  { no: 3436, title: "Giảm Giá Xây Trọn Gói", keyword: "giảm giá xây trọn gói", slug: "giam-gia-xay-tron-goi-ads-ngan", status: "done" },
  { no: 3437, title: "Liên Hệ Tư Vấn Ngay", keyword: "liên hệ tư vấn ngay", slug: "lien-he-tu-van-ngay-ads-ngan", status: "done" },
  { no: 3438, title: "Đăng Ký Nhận Báo Giá", keyword: "đăng ký nhận báo giá", slug: "dang-ky-nhan-bao-gia-ads-ngan", status: "done" },
  { no: 3439, title: "Gọi Ngay Nhận Khảo Sát", keyword: "gọi ngay nhận khảo sát", slug: "goi-ngay-nhan-khao-sat-ads-ngan", status: "done" },
  { no: 3440, title: "Xây Nhà Sao Khuê 2026", keyword: "xây nhà sao khuê 2026", slug: "xay-nha-sao-khue-2026-ads-ngan", status: "done" },
  { no: 3441, title: "Cải Tạo Sao Khuê 2026", keyword: "cải tạo sao khuê 2026", slug: "cai-tao-sao-khue-2026-ads-ngan", status: "done" },
  { no: 3442, title: "Chủ Đề Mở Rộng 39 1", keyword: "chủ đề mở rộng 39 1", slug: "chu-de-mo-rong-39-1-ngan", status: "done" },
  { no: 3443, title: "Chủ Đề Mở Rộng 39 2", keyword: "chủ đề mở rộng 39 2", slug: "chu-de-mo-rong-39-2-ngan", status: "done" },
  { no: 3444, title: "Chủ Đề Mở Rộng 39 3", keyword: "chủ đề mở rộng 39 3", slug: "chu-de-mo-rong-39-3-ngan", status: "done" },
  { no: 3445, title: "Chủ Đề Mở Rộng 39 4", keyword: "chủ đề mở rộng 39 4", slug: "chu-de-mo-rong-39-4-ngan", status: "done" },
  { no: 3446, title: "Chủ Đề Mở Rộng 39 5", keyword: "chủ đề mở rộng 39 5", slug: "chu-de-mo-rong-39-5-ngan", status: "done" },
];
