/**
 * Lịch 100 từ khóa ngắn — batch 55 (#4947–#5046).
 * Cluster: phòng chức năng, layout, công năng sống.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch55: ContentCalendarItem[] = [
  { no: 4947, title: "Phòng Khách Liên Thông Bếp", keyword: "phòng khách liên thông bếp", slug: "phong-khach-lien-thong-bep-cn-ngan", status: "done" },
  { no: 4948, title: "Phòng Khách Có Giếng Trời", keyword: "phòng khách có giếng trời", slug: "phong-khach-co-gieng-troi-cn-ngan", status: "done" },
  { no: 4949, title: "Phòng Khách Thông Tầng", keyword: "phòng khách thông tầng", slug: "phong-khach-thong-tang-cn-ngan", status: "done" },
  { no: 4950, title: "Phòng Khách Nhà Hẹp", keyword: "phòng khách nhà hẹp", slug: "phong-khach-nha-hep-cn-ngan", status: "done" },
  { no: 4951, title: "Phòng Ngủ Master Có WC", keyword: "phòng ngủ master có wc", slug: "phong-ngu-master-co-wc-cn-ngan", status: "done" },
  { no: 4952, title: "Phòng Ngủ Master Có Walk In", keyword: "phòng ngủ master có walk in", slug: "phong-ngu-master-co-walk-in-cn-ngan", status: "done" },
  { no: 4953, title: "Phòng Ngủ Master Có Ban Công", keyword: "phòng ngủ master có ban công", slug: "phong-ngu-master-co-ban-cong-cn-ngan", status: "done" },
  { no: 4954, title: "Phòng Ngủ Trẻ Em 2 Bé", keyword: "phòng ngủ trẻ em 2 bé", slug: "phong-ngu-tre-em-2-be-cn-ngan", status: "done" },
  { no: 4955, title: "Phòng Ngủ Teen", keyword: "phòng ngủ teen", slug: "phong-ngu-teen-cn-ngan", status: "done" },
  { no: 4956, title: "Phòng Ngủ Ông Bà Tầng Trệt", keyword: "phòng ngủ ông bà tầng trệt", slug: "phong-ngu-ong-ba-tang-tret-cn-ngan", status: "done" },
  { no: 4957, title: "Phòng Ngủ Khách", keyword: "phòng ngủ khách", slug: "phong-ngu-khach-cn-ngan", status: "done" },
  { no: 4958, title: "Phòng Bếp Mở", keyword: "phòng bếp mở", slug: "phong-bep-mo-cn-ngan", status: "done" },
  { no: 4959, title: "Phòng Bếp Đóng", keyword: "phòng bếp đóng", slug: "phong-bep-dong-cn-ngan", status: "done" },
  { no: 4960, title: "Phòng Bếp Có Bàn Ăn", keyword: "phòng bếp có bàn ăn", slug: "phong-bep-co-ban-an-cn-ngan", status: "done" },
  { no: 4961, title: "Phòng Bếp Có Đảo Bếp", keyword: "phòng bếp có đảo bếp", slug: "phong-bep-co-dao-bep-cn-ngan", status: "done" },
  { no: 4962, title: "Phòng Bếp Có Pantry", keyword: "phòng bếp có pantry", slug: "phong-bep-co-pantry-cn-ngan", status: "done" },
  { no: 4963, title: "Phòng Ăn Riêng", keyword: "phòng ăn riêng", slug: "phong-an-rieng-cn-ngan", status: "done" },
  { no: 4964, title: "Phòng Ăn Kết Hợp Khách", keyword: "phòng ăn kết hợp khách", slug: "phong-an-ket-hop-khach-cn-ngan", status: "done" },
  { no: 4965, title: "WC Khách Tầng Trệt", keyword: "wc khách tầng trệt", slug: "wc-khach-tang-tret-cn-ngan", status: "done" },
  { no: 4966, title: "WC Chung Tầng Lầu", keyword: "wc chung tầng lầu", slug: "wc-chung-tang-lau-cn-ngan", status: "done" },
  { no: 4967, title: "WC Master En Suite", keyword: "wc master en suite", slug: "wc-master-en-suite-cn-ngan", status: "done" },
  { no: 4968, title: "WC Có Bồn Tắm", keyword: "wc có bồn tắm", slug: "wc-co-bon-tam-cn-ngan", status: "done" },
  { no: 4969, title: "WC Có Cabin Tắm", keyword: "wc có cabin tắm", slug: "wc-co-cabin-tam-cn-ngan", status: "done" },
  { no: 4970, title: "Phòng Giặt Riêng", keyword: "phòng giặt riêng", slug: "phong-giat-rieng-cn-ngan", status: "done" },
  { no: 4971, title: "Phòng Giặt Kết Hợp Phơi", keyword: "phòng giặt kết hợp phơi", slug: "phong-giat-ket-hop-phoi-cn-ngan", status: "done" },
  { no: 4972, title: "Khu Phơi Đồ Sân Thượng", keyword: "khu phơi đồ sân thượng", slug: "khu-phoi-do-san-thuong-cn-ngan", status: "done" },
  { no: 4973, title: "Phòng Thờ Tầng Trệt", keyword: "phòng thờ tầng trệt", slug: "phong-tho-tang-tret-cn-ngan", status: "done" },
  { no: 4974, title: "Phòng Thờ Tầng Thượng", keyword: "phòng thờ tầng thượng", slug: "phong-tho-tang-thuong-cn-ngan", status: "done" },
  { no: 4975, title: "Phòng Thờ Riêng Biệt", keyword: "phòng thờ riêng biệt", slug: "phong-tho-rieng-biet-cn-ngan", status: "done" },
  { no: 4976, title: "Phòng Làm Việc Tại Nhà", keyword: "phòng làm việc tại nhà", slug: "phong-lam-viec-tai-nha-cn-ngan", status: "done" },
  { no: 4977, title: "Góc Làm Việc Phòng Ngủ", keyword: "góc làm việc phòng ngủ", slug: "goc-lam-viec-phong-ngu-cn-ngan", status: "done" },
  { no: 4978, title: "Phòng Giải Trí Gia Đình", keyword: "phòng giải trí gia đình", slug: "phong-giai-tri-gia-dinh-cn-ngan", status: "done" },
  { no: 4979, title: "Phòng Karaoke Cách Âm", keyword: "phòng karaoke cách âm", slug: "phong-karaoke-cach-am-cn-ngan", status: "done" },
  { no: 4980, title: "Phòng Gym Mini Nhà", keyword: "phòng gym mini nhà", slug: "phong-gym-mini-nha-cn-ngan", status: "done" },
  { no: 4981, title: "Phòng Yoga Tại Nhà", keyword: "phòng yoga tại nhà", slug: "phong-yoga-tai-nha-cn-ngan", status: "done" },
  { no: 4982, title: "Phòng Đọc Sách", keyword: "phòng đọc sách", slug: "phong-doc-sach-cn-ngan", status: "done" },
  { no: 4983, title: "Phòng Chơi Trẻ Em CN", keyword: "phòng chơi trẻ em", slug: "phong-choi-tre-em-cn-ngan", status: "done" },
  { no: 4984, title: "Phòng Kho Đồ Dưới Cầu Thang", keyword: "phòng kho đồ dưới cầu thang", slug: "phong-kho-do-duoi-cau-thang-cn-ngan", status: "done" },
  { no: 4985, title: "Phòng Kho Tầng Hầm", keyword: "phòng kho tầng hầm", slug: "phong-kho-tang-ham-cn-ngan", status: "done" },
  { no: 4986, title: "Hầm Để Xe 1 Ô Tô", keyword: "hầm để xe 1 ô tô", slug: "ham-de-xe-1-o-to-cn-ngan", status: "done" },
  { no: 4987, title: "Hầm Để Xe 2 Ô Tô", keyword: "hầm để xe 2 ô tô", slug: "ham-de-xe-2-o-to-cn-ngan", status: "done" },
  { no: 4988, title: "Sân Để Xe Máy Tầng Trệt", keyword: "sân để xe máy tầng trệt", slug: "san-de-xe-may-tang-tret-cn-ngan", status: "done" },
  { no: 4989, title: "Garage Riêng Nhà Phố", keyword: "garage riêng nhà phố", slug: "garage-rieng-nha-pho-cn-ngan", status: "done" },
  { no: 4990, title: "Sảnh Đón Nhà Phố", keyword: "sảnh đón nhà phố", slug: "sanh-don-nha-pho-cn-ngan", status: "done" },
  { no: 4991, title: "Hành Lang Thông Tầng", keyword: "hành lang thông tầng", slug: "hanh-lang-thong-tang-cn-ngan", status: "done" },
  { no: 4992, title: "Hành Lang Bên Hông", keyword: "hành lang bên hông", slug: "hanh-lang-ben-hong-cn-ngan", status: "done" },
  { no: 4993, title: "Gác Lửng Phòng Khách", keyword: "gác lửng phòng khách", slug: "gac-lung-phong-khach-cn-ngan", status: "done" },
  { no: 4994, title: "Gác Lửng Phòng Ngủ", keyword: "gác lửng phòng ngủ", slug: "gac-lung-phong-ngu-cn-ngan", status: "done" },
  { no: 4995, title: "Gác Lửng Kho Đồ", keyword: "gác lửng kho đồ", slug: "gac-lung-kho-do-cn-ngan", status: "done" },
  { no: 4996, title: "Ban Công Phòng Ngủ", keyword: "ban công phòng ngủ", slug: "ban-cong-phong-ngu-cn-ngan", status: "done" },
  { no: 4997, title: "Ban Công Phòng Khách", keyword: "ban công phòng khách", slug: "ban-cong-phong-khach-cn-ngan", status: "done" },
  { no: 4998, title: "Logia Phơi Đồ", keyword: "logia phơi đồ", slug: "logia-phoi-do-cn-ngan", status: "done" },
  { no: 4999, title: "Sân Thượng Làm Vườn", keyword: "sân thượng làm vườn", slug: "san-thuong-lam-vuon-cn-ngan", status: "done" },
  { no: 5000, title: "Sân Thượng Tiếp Khách", keyword: "sân thượng tiếp khách", slug: "san-thuong-tiep-khach-cn-ngan", status: "done" },
  { no: 5001, title: "Sân Thượng Có Bếp Nướng", keyword: "sân thượng có bếp nướng", slug: "san-thuong-co-bep-nuong-cn-ngan", status: "done" },
  { no: 5002, title: "Sân Trước Tiếp Khách", keyword: "sân trước tiếp khách", slug: "san-truoc-tiep-khach-cn-ngan", status: "done" },
  { no: 5003, title: "Sân Sau Giặt Phơi", keyword: "sân sau giặt phơi", slug: "san-sau-giat-phoi-cn-ngan", status: "done" },
  { no: 5004, title: "Giếng Trời Giữa Nhà", keyword: "giếng trời giữa nhà", slug: "gieng-troi-giua-nha-cn-ngan", status: "done" },
  { no: 5005, title: "Giếng Trời Cuối Nhà", keyword: "giếng trời cuối nhà", slug: "gieng-troi-cuoi-nha-cn-ngan", status: "done" },
  { no: 5006, title: "Giếng Trời Bên Hông", keyword: "giếng trời bên hông", slug: "gieng-troi-ben-hong-cn-ngan", status: "done" },
  { no: 5007, title: "Cầu Thang Giữa Nhà", keyword: "cầu thang giữa nhà", slug: "cau-thang-giua-nha-cn-ngan", status: "done" },
  { no: 5008, title: "Cầu Thang Bên Hông", keyword: "cầu thang bên hông", slug: "cau-thang-ben-hong-cn-ngan", status: "done" },
  { no: 5009, title: "Cầu Thang Cuối Nhà", keyword: "cầu thang cuối nhà", slug: "cau-thang-cuoi-nha-cn-ngan", status: "done" },
  { no: 5010, title: "Cầu Thang Xoắn Tiết Kiệm", keyword: "cầu thang xoắn tiết kiệm", slug: "cau-thang-xoan-tiet-kiem-cn-ngan", status: "done" },
  { no: 5011, title: "Cầu Thang Thẳng Nhà Hẹp", keyword: "cầu thang thẳng nhà hẹp", slug: "cau-thang-thang-nha-hep-cn-ngan", status: "done" },
  { no: 5012, title: "Không Gian Đa Năng", keyword: "không gian đa năng", slug: "khong-gian-da-nang-cn-ngan", status: "done" },
  { no: 5013, title: "Phòng Đa Năng Biến Đổi", keyword: "phòng đa năng biến đổi", slug: "phong-da-nang-bien-doi-cn-ngan", status: "done" },
  { no: 5014, title: "Vách Ngăn Di Động", keyword: "vách ngăn di động", slug: "vach-ngan-di-dong-cn-ngan", status: "done" },
  { no: 5015, title: "Nội Thất Gấp Gọn CN", keyword: "nội thất gấp gọn", slug: "noi-that-gap-gon-cn-ngan", status: "done" },
  { no: 5016, title: "Tối Ưu Công Năng Nhà 40m2", keyword: "tối ưu công năng nhà 40m2", slug: "toi-uu-cong-nang-nha-40m2-cn-ngan", status: "done" },
  { no: 5017, title: "Tối Ưu Công Năng Nhà 50m2", keyword: "tối ưu công năng nhà 50m2", slug: "toi-uu-cong-nang-nha-50m2-cn-ngan", status: "done" },
  { no: 5018, title: "Tối Ưu Công Năng Nhà 60m2", keyword: "tối ưu công năng nhà 60m2", slug: "toi-uu-cong-nang-nha-60m2-cn-ngan", status: "done" },
  { no: 5019, title: "Tối Ưu Công Năng Nhà 80m2", keyword: "tối ưu công năng nhà 80m2", slug: "toi-uu-cong-nang-nha-80m2-cn-ngan", status: "done" },
  { no: 5020, title: "Layout Nhà 3 Phòng Ngủ", keyword: "layout nhà 3 phòng ngủ", slug: "layout-nha-3-phong-ngu-cn-ngan", status: "done" },
  { no: 5021, title: "Layout Nhà 4 Phòng Ngủ", keyword: "layout nhà 4 phòng ngủ", slug: "layout-nha-4-phong-ngu-cn-ngan", status: "done" },
  { no: 5022, title: "Layout Nhà 5 Phòng Ngủ", keyword: "layout nhà 5 phòng ngủ", slug: "layout-nha-5-phong-ngu-cn-ngan", status: "done" },
  { no: 5023, title: "Layout Shop House Tầng Trệt", keyword: "layout shop house tầng trệt", slug: "layout-shop-house-tang-tret-cn-ngan", status: "done" },
  { no: 5024, title: "Layout Nhà Ở Kết Hợp VP", keyword: "layout nhà ở kết hợp vp", slug: "layout-nha-o-ket-hop-vp-cn-ngan", status: "done" },
  { no: 5025, title: "Flow Di Chuyển Trong Nhà", keyword: "flow di chuyển trong nhà", slug: "flow-di-chuyen-trong-nha-cn-ngan", status: "done" },
  { no: 5026, title: "Vùng Ướt Vùng Khô", keyword: "vùng ướt vùng khô", slug: "vung-uot-vung-kho-cn-ngan", status: "done" },
  { no: 5027, title: "Vùng Công Cộng Riêng Tư", keyword: "vùng công cộng riêng tư", slug: "vung-cong-cong-rieng-tu-cn-ngan", status: "done" },
  { no: 5028, title: "Ánh Sáng Phòng Khách", keyword: "ánh sáng phòng khách", slug: "anh-sang-phong-khach-cn-ngan", status: "done" },
  { no: 5029, title: "Ánh Sáng Phòng Ngủ", keyword: "ánh sáng phòng ngủ", slug: "anh-sang-phong-ngu-cn-ngan", status: "done" },
  { no: 5030, title: "Ánh Sáng Phòng Bếp", keyword: "ánh sáng phòng bếp", slug: "anh-sang-phong-bep-cn-ngan", status: "done" },
  { no: 5031, title: "Thông Gió Phòng WC", keyword: "thông gió phòng wc", slug: "thong-gio-phong-wc-cn-ngan", status: "done" },
  { no: 5032, title: "Thông Gió Phòng Bếp CN", keyword: "thông gió phòng bếp", slug: "thong-gio-phong-bep-cn-ngan", status: "done" },
  { no: 5033, title: "Cách Âm Phòng Ngủ", keyword: "cách âm phòng ngủ", slug: "cach-am-phong-ngu-cn-ngan", status: "done" },
  { no: 5034, title: "Cách Âm Phòng Karaoke CN", keyword: "cách âm phòng karaoke", slug: "cach-am-phong-karaoke-cn-ngan", status: "done" },
  { no: 5035, title: "Báo Giá Thiết Kế Công Năng", keyword: "báo giá thiết kế công năng", slug: "bao-gia-thiet-ke-cong-nang-cn-ngan", status: "done" },
  { no: 5036, title: "Tư Vấn Layout Nhà Phố", keyword: "tư vấn layout nhà phố", slug: "tu-van-layout-nha-pho-cn-ngan", status: "done" },
  { no: 5037, title: "Sai Lầm Layout Thường Gặp", keyword: "sai lầm layout thường gặp", slug: "sai-lam-layout-thuong-gap-cn-ngan", status: "done" },
  { no: 5038, title: "Checklist Công Năng Nhà Ở", keyword: "checklist công năng nhà ở", slug: "checklist-cong-nang-nha-o-cn-ngan", status: "done" },
  { no: 5039, title: "Xu Hướng Layout 2026", keyword: "xu hướng layout 2026", slug: "xu-huong-layout-2026-cn-ngan", status: "done" },
  { no: 5040, title: "Nhà Đa Thế Hệ Layout", keyword: "nhà đa thế hệ layout", slug: "nha-da-the-he-layout-cn-ngan", status: "done" },
  { no: 5041, title: "Nhà Cho Người Khuyết Tật", keyword: "nhà cho người khuyết tật", slug: "nha-cho-nguoi-khuyet-tat-cn-ngan", status: "done" },
  { no: 5042, title: "Nhà Universal Design", keyword: "nhà universal design", slug: "nha-universal-design-cn-ngan", status: "done" },
  { no: 5043, title: "Chủ Đề Mở Rộng 55 1", keyword: "chủ đề mở rộng 55 1", slug: "chu-de-mo-rong-55-1-ngan", status: "done" },
  { no: 5044, title: "Chủ Đề Mở Rộng 55 2", keyword: "chủ đề mở rộng 55 2", slug: "chu-de-mo-rong-55-2-ngan", status: "done" },
  { no: 5045, title: "Chủ Đề Mở Rộng 55 3", keyword: "chủ đề mở rộng 55 3", slug: "chu-de-mo-rong-55-3-ngan", status: "done" },
  { no: 5046, title: "Chủ Đề Mở Rộng 55 4", keyword: "chủ đề mở rộng 55 4", slug: "chu-de-mo-rong-55-4-ngan", status: "done" },
];
