/**
 * Lịch 100 từ khóa ngắn — batch 59 (#5347–#5446).
 * Cluster: seasonal, remarketing, Ads content hub.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch59: ContentCalendarItem[] = [
  { no: 5347, title: "Xây Nhà Tháng 1 2026", keyword: "xây nhà tháng 1 2026", slug: "xay-nha-thang-1-2026-ads5-ngan", status: "done" },
  { no: 5348, title: "Xây Nhà Tháng 2 2026", keyword: "xây nhà tháng 2 2026", slug: "xay-nha-thang-2-2026-ads5-ngan", status: "done" },
  { no: 5349, title: "Xây Nhà Tháng 3 2026", keyword: "xây nhà tháng 3 2026", slug: "xay-nha-thang-3-2026-ads5-ngan", status: "done" },
  { no: 5350, title: "Xây Nhà Tháng 4 2026", keyword: "xây nhà tháng 4 2026", slug: "xay-nha-thang-4-2026-ads5-ngan", status: "done" },
  { no: 5351, title: "Xây Nhà Tháng 5 2026", keyword: "xây nhà tháng 5 2026", slug: "xay-nha-thang-5-2026-ads5-ngan", status: "done" },
  { no: 5352, title: "Xây Nhà Tháng 6 2026", keyword: "xây nhà tháng 6 2026", slug: "xay-nha-thang-6-2026-ads5-ngan", status: "done" },
  { no: 5353, title: "Xây Nhà Tháng 7 2026", keyword: "xây nhà tháng 7 2026", slug: "xay-nha-thang-7-2026-ads5-ngan", status: "done" },
  { no: 5354, title: "Xây Nhà Tháng 8 2026", keyword: "xây nhà tháng 8 2026", slug: "xay-nha-thang-8-2026-ads5-ngan", status: "done" },
  { no: 5355, title: "Xây Nhà Tháng 9 2026", keyword: "xây nhà tháng 9 2026", slug: "xay-nha-thang-9-2026-ads5-ngan", status: "done" },
  { no: 5356, title: "Xây Nhà Tháng 10 2026", keyword: "xây nhà tháng 10 2026", slug: "xay-nha-thang-10-2026-ads5-ngan", status: "done" },
  { no: 5357, title: "Xây Nhà Tháng 11 2026", keyword: "xây nhà tháng 11 2026", slug: "xay-nha-thang-11-2026-ads5-ngan", status: "done" },
  { no: 5358, title: "Xây Nhà Tháng 12 2026", keyword: "xây nhà tháng 12 2026", slug: "xay-nha-thang-12-2026-ads5-ngan", status: "done" },
  { no: 5359, title: "Cải Tạo Tháng Này", keyword: "cải tạo tháng này", slug: "cai-tao-thang-nay-ads5-ngan", status: "done" },
  { no: 5360, title: "Ưu Đãi Xây Nhà Tuần Này", keyword: "ưu đãi xây nhà tuần này", slug: "uu-dai-xay-nha-tuan-nay-ads5-ngan", status: "done" },
  { no: 5361, title: "Flash Deal Cải Tạo", keyword: "flash deal cải tạo", slug: "flash-deal-cai-tao-ads5-ngan", status: "done" },
  { no: 5362, title: "Weekend Survey Miễn Phí", keyword: "weekend survey miễn phí", slug: "weekend-survey-mien-phi-ads5-ngan", status: "done" },
  { no: 5363, title: "Nhắc Lại Báo Giá Xây", keyword: "nhắc lại báo giá xây", slug: "nhac-lai-bao-gia-xay-ads5-ngan", status: "done" },
  { no: 5364, title: "Bạn Đã Xem Báo Giá Chưa", keyword: "bạn đã xem báo giá chưa", slug: "ban-da-xem-bao-gia-chua-ads5-ngan", status: "done" },
  { no: 5365, title: "Vẫn Còn Quan Tâm Xây Nhà", keyword: "vẫn còn quan tâm xây nhà", slug: "van-con-quan-tam-xay-nha-ads5-ngan", status: "done" },
  { no: 5366, title: "Hoàn Tất Đăng Ký Tư Vấn", keyword: "hoàn tất đăng ký tư vấn", slug: "hoan-tat-dang-ky-tu-van-ads5-ngan", status: "done" },
  { no: 5367, title: "Tiếp Tục Quy Trình Xây", keyword: "tiếp tục quy trình xây", slug: "tiep-tuc-quy-trinh-xay-ads5-ngan", status: "done" },
  { no: 5368, title: "Khách Hàng Quay Lại Sao Khuê", keyword: "khách hàng quay lại sao khuê", slug: "khach-hang-quay-lai-sao-khue-ads5-ngan", status: "done" },
  { no: 5369, title: "Remarketing Xây Nhà TPHCM", keyword: "remarketing xây nhà tphcm", slug: "remarketing-xay-nha-tphcm-ads5-ngan", status: "done" },
  { no: 5370, title: "Remarketing Cải Tạo TPHCM", keyword: "remarketing cải tạo tphcm", slug: "remarketing-cai-tao-tphcm-ads5-ngan", status: "done" },
  { no: 5371, title: "Lookalike Khách Xây Nhà", keyword: "lookalike khách xây nhà", slug: "lookalike-khach-xay-nha-ads5-ngan", status: "done" },
  { no: 5372, title: "Audience Chủ Nhà TPHCM", keyword: "audience chủ nhà tphcm", slug: "audience-chu-nha-tphcm-ads5-ngan", status: "done" },
  { no: 5373, title: "Intent Xây Nhà Cao", keyword: "intent xây nhà cao", slug: "intent-xay-nha-cao-ads5-ngan", status: "done" },
  { no: 5374, title: "Intent Cải Tạo Cao", keyword: "intent cải tạo cao", slug: "intent-cai-tao-cao-ads5-ngan", status: "done" },
  { no: 5375, title: "Bottom Funnel Xây Nhà", keyword: "bottom funnel xây nhà", slug: "bottom-funnel-xay-nha-ads5-ngan", status: "done" },
  { no: 5376, title: "Middle Funnel Cải Tạo", keyword: "middle funnel cải tạo", slug: "middle-funnel-cai-tao-ads5-ngan", status: "done" },
  { no: 5377, title: "Top Funnel Mẫu Nhà", keyword: "top funnel mẫu nhà", slug: "top-funnel-mau-nha-ads5-ngan", status: "done" },
  { no: 5378, title: "Content Hub Xây Nhà", keyword: "content hub xây nhà", slug: "content-hub-xay-nha-ads5-ngan", status: "done" },
  { no: 5379, title: "Pillar Page Xây Nhà", keyword: "pillar page xây nhà", slug: "pillar-page-xay-nha-ads5-ngan", status: "done" },
  { no: 5380, title: "Cluster Cải Tạo Nhà", keyword: "cluster cải tạo nhà", slug: "cluster-cai-tao-nha-ads5-ngan", status: "done" },
  { no: 5381, title: "Internal Link Xây Nhà", keyword: "internal link xây nhà", slug: "internal-link-xay-nha-ads5-ngan", status: "done" },
  { no: 5382, title: "Topic Authority Xây Dựng", keyword: "topic authority xây dựng", slug: "topic-authority-xay-dung-ads5-ngan", status: "done" },
  { no: 5383, title: "Local SEO Xây Nhà", keyword: "local seo xây nhà", slug: "local-seo-xay-nha-ads5-ngan", status: "done" },
  { no: 5384, title: "Google Business Xây Nhà", keyword: "google business xây nhà", slug: "google-business-xay-nha-ads5-ngan", status: "done" },
  { no: 5385, title: "Map Pack Nhà Thầu", keyword: "map pack nhà thầu", slug: "map-pack-nha-thau-ads5-ngan", status: "done" },
  { no: 5386, title: "Review Generation Xây", keyword: "review generation xây", slug: "review-generation-xay-ads5-ngan", status: "done" },
  { no: 5387, title: "UGC Công Trình Thực", keyword: "ugc công trình thực", slug: "ugc-cong-trinh-thuc-ads5-ngan", status: "done" },
  { no: 5388, title: "Before After Gallery", keyword: "before after gallery", slug: "before-after-gallery-ads5-ngan", status: "done" },
  { no: 5389, title: "Case Study Series Xây", keyword: "case study series xây", slug: "case-study-series-xay-ads5-ngan", status: "done" },
  { no: 5390, title: "Video Series Thi Công", keyword: "video series thi công", slug: "video-series-thi-cong-ads5-ngan", status: "done" },
  { no: 5391, title: "Livestream Tư Vấn Xây", keyword: "livestream tư vấn xây", slug: "livestream-tu-van-xay-ads5-ngan", status: "done" },
  { no: 5392, title: "Stories Công Trình Ngày", keyword: "stories công trình ngày", slug: "stories-cong-trinh-ngay-ads5-ngan", status: "done" },
  { no: 5393, title: "Reels Mẫu Nhà Đẹp", keyword: "reels mẫu nhà đẹp", slug: "reels-mau-nha-dep-ads5-ngan", status: "done" },
  { no: 5394, title: "TikTok Xây Nhà Tips", keyword: "tiktok xây nhà tips", slug: "tiktok-xay-nha-tips-ads5-ngan", status: "done" },
  { no: 5395, title: "YouTube Xây Nhà Guide", keyword: "youtube xây nhà guide", slug: "youtube-xay-nha-guide-ads5-ngan", status: "done" },
  { no: 5396, title: "Podcast Kinh Nghiệm Xây", keyword: "podcast kinh nghiệm xây", slug: "podcast-kinh-nghiem-xay-ads5-ngan", status: "done" },
  { no: 5397, title: "Newsletter Xây Nhà", keyword: "newsletter xây nhà", slug: "newsletter-xay-nha-ads5-ngan", status: "done" },
  { no: 5398, title: "Email Nurture Xây Nhà", keyword: "email nurture xây nhà", slug: "email-nurture-xay-nha-ads5-ngan", status: "done" },
  { no: 5399, title: "SMS Nhắc Khảo Sát", keyword: "sms nhắc khảo sát", slug: "sms-nhac-khao-sat-ads5-ngan", status: "done" },
  { no: 5400, title: "Zalo OA Sao Khuê", keyword: "zalo oa sao khuê", slug: "zalo-oa-sao-khue-ads5-ngan", status: "done" },
  { no: 5401, title: "Chatbot Tư Vấn Xây", keyword: "chatbot tư vấn xây", slug: "chatbot-tu-van-xay-ads5-ngan", status: "done" },
  { no: 5402, title: "Quiz Chọn Gói Xây", keyword: "quiz chọn gói xây", slug: "quiz-chon-goi-xay-ads5-ngan", status: "done" },
  { no: 5403, title: "Calculator Chi Phí Xây", keyword: "calculator chi phí xây", slug: "calculator-chi-phi-xay-ads5-ngan", status: "done" },
  { no: 5404, title: "Estimate Tool Online", keyword: "estimate tool online", slug: "estimate-tool-online-ads5-ngan", status: "done" },
  { no: 5405, title: "Config Nhà Mơ Ước", keyword: "config nhà mơ ước", slug: "config-nha-mo-uoc-ads5-ngan", status: "done" },
  { no: 5406, title: "Wishlist Mẫu Nhà", keyword: "wishlist mẫu nhà", slug: "wishlist-mau-nha-ads5-ngan", status: "done" },
  { no: 5407, title: "Save For Later Xây", keyword: "save for later xây", slug: "save-for-later-xay-ads5-ngan", status: "done" },
  { no: 5408, title: "Share Báo Giá Bạn Bè", keyword: "share báo giá bạn bè", slug: "share-bao-gia-ban-be-ads5-ngan", status: "done" },
  { no: 5409, title: "Referral Xây Nhà", keyword: "referral xây nhà", slug: "referral-xay-nha-ads5-ngan", status: "done" },
  { no: 5410, title: "Affiliate Đối Tác Xây", keyword: "affiliate đối tác xây", slug: "affiliate-doi-tac-xay-ads5-ngan", status: "done" },
  { no: 5411, title: "Partner Architect Program", keyword: "partner architect program", slug: "partner-architect-program-ads5-ngan", status: "done" },
  { no: 5412, title: "Loyalty After Build", keyword: "loyalty after build", slug: "loyalty-after-build-ads5-ngan", status: "done" },
  { no: 5413, title: "Warranty Reminder", keyword: "warranty reminder", slug: "warranty-reminder-ads5-ngan", status: "done" },
  { no: 5414, title: "Maintenance Reminder Ads", keyword: "maintenance reminder ads", slug: "maintenance-reminder-ads-ads5-ngan", status: "done" },
  { no: 5415, title: "Upsell Nội Thất Sau Xây", keyword: "upsell nội thất sau xây", slug: "upsell-noi-that-sau-xay-ads5-ngan", status: "done" },
  { no: 5416, title: "Cross Sell Cải Tạo Mặt Tiền", keyword: "cross sell cải tạo mặt tiền", slug: "cross-sell-cai-tao-mat-tien-ads5-ngan", status: "done" },
  { no: 5417, title: "Anniversary Nhà 1 Năm", keyword: "anniversary nhà 1 năm", slug: "anniversary-nha-1-nam-ads5-ngan", status: "done" },
  { no: 5418, title: "Happy Customer Campaign", keyword: "happy customer campaign", slug: "happy-customer-campaign-ads5-ngan", status: "done" },
  { no: 5419, title: "Brand Search Sao Khuê", keyword: "brand search sao khuê", slug: "brand-search-sao-khue-ads5-ngan", status: "done" },
  { no: 5420, title: "Competitor Conquest Xây", keyword: "competitor conquest xây", slug: "competitor-conquest-xay-ads5-ngan", status: "done" },
  { no: 5421, title: "Category Domination Xây", keyword: "category domination xây", slug: "category-domination-xay-ads5-ngan", status: "done" },
  { no: 5422, title: "Seasonal Push Tết 2027", keyword: "seasonal push tết 2027", slug: "seasonal-push-tet-2027-ads5-ngan", status: "done" },
  { no: 5423, title: "Pre Tết Cải Tạo Rush", keyword: "pre tết cải tạo rush", slug: "pre-tet-cai-tao-rush-ads5-ngan", status: "done" },
  { no: 5424, title: "Post Tết Xây Nhà Wave", keyword: "post tết xây nhà wave", slug: "post-tet-xay-nha-wave-ads5-ngan", status: "done" },
  { no: 5425, title: "Rainy Season Promo", keyword: "rainy season promo", slug: "rainy-season-promo-ads5-ngan", status: "done" },
  { no: 5426, title: "Dry Season Build Push", keyword: "dry season build push", slug: "dry-season-build-push-ads5-ngan", status: "done" },
  { no: 5427, title: "Year End Closing Xây", keyword: "year end closing xây", slug: "year-end-closing-xay-ads5-ngan", status: "done" },
  { no: 5428, title: "New Year New Home 2027", keyword: "new year new home 2027", slug: "new-year-new-home-2027-ads5-ngan", status: "done" },
  { no: 5429, title: "Q1 Pipeline Xây Nhà", keyword: "q1 pipeline xây nhà", slug: "q1-pipeline-xay-nha-ads5-ngan", status: "done" },
  { no: 5430, title: "Q2 Pipeline Cải Tạo", keyword: "q2 pipeline cải tạo", slug: "q2-pipeline-cai-tao-ads5-ngan", status: "done" },
  { no: 5431, title: "Always On Lead Gen", keyword: "always on lead gen", slug: "always-on-lead-gen-ads5-ngan", status: "done" },
  { no: 5432, title: "Conversion Rate Xây Nhà", keyword: "conversion rate xây nhà", slug: "conversion-rate-xay-nha-ads5-ngan", status: "done" },
  { no: 5433, title: "ROAS Campaign Xây", keyword: "roas campaign xây", slug: "roas-campaign-xay-ads5-ngan", status: "done" },
  { no: 5434, title: "CPA Lead Xây Nhà", keyword: "cpa lead xây nhà", slug: "cpa-lead-xay-nha-ads5-ngan", status: "done" },
  { no: 5435, title: "LTV Khách Xây Nhà", keyword: "ltv khách xây nhà", slug: "ltv-khach-xay-nha-ads5-ngan", status: "done" },
  { no: 5436, title: "Chủ Đề Mở Rộng 59 1", keyword: "chủ đề mở rộng 59 1", slug: "chu-de-mo-rong-59-1-ngan", status: "done" },
  { no: 5437, title: "Chủ Đề Mở Rộng 59 2", keyword: "chủ đề mở rộng 59 2", slug: "chu-de-mo-rong-59-2-ngan", status: "done" },
  { no: 5438, title: "Chủ Đề Mở Rộng 59 3", keyword: "chủ đề mở rộng 59 3", slug: "chu-de-mo-rong-59-3-ngan", status: "done" },
  { no: 5439, title: "Chủ Đề Mở Rộng 59 4", keyword: "chủ đề mở rộng 59 4", slug: "chu-de-mo-rong-59-4-ngan", status: "done" },
  { no: 5440, title: "Chủ Đề Mở Rộng 59 5", keyword: "chủ đề mở rộng 59 5", slug: "chu-de-mo-rong-59-5-ngan", status: "done" },
  { no: 5441, title: "Chủ Đề Mở Rộng 59 6", keyword: "chủ đề mở rộng 59 6", slug: "chu-de-mo-rong-59-6-ngan", status: "done" },
  { no: 5442, title: "Chủ Đề Mở Rộng 59 7", keyword: "chủ đề mở rộng 59 7", slug: "chu-de-mo-rong-59-7-ngan", status: "done" },
  { no: 5443, title: "Chủ Đề Mở Rộng 59 8", keyword: "chủ đề mở rộng 59 8", slug: "chu-de-mo-rong-59-8-ngan", status: "done" },
  { no: 5444, title: "Chủ Đề Mở Rộng 59 9", keyword: "chủ đề mở rộng 59 9", slug: "chu-de-mo-rong-59-9-ngan", status: "done" },
  { no: 5445, title: "Chủ Đề Mở Rộng 59 10", keyword: "chủ đề mở rộng 59 10", slug: "chu-de-mo-rong-59-10-ngan", status: "done" },
  { no: 5446, title: "Chủ Đề Mở Rộng 59 11", keyword: "chủ đề mở rộng 59 11", slug: "chu-de-mo-rong-59-11-ngan", status: "done" },
];
