/**
 * Lịch 100 từ khóa ngắn — batch 63 (#5747–#5846).
 * Cluster: công nghệ mới, prefab, thép, BIM.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch63: ContentCalendarItem[] = [
  { no: 5747, title: "Bê Tông Siêu Tính Năng", keyword: "bê tông siêu tính năng", slug: "be-tong-sieu-tinh-nang-cn2-ngan", status: "done" },
  { no: 5748, title: "Bê Tông Tự Lèn", keyword: "bê tông tự lèn", slug: "be-tong-tu-len-cn2-ngan", status: "done" },
  { no: 5749, title: "Bê Tông Nhẹ Cách Nhiệt", keyword: "bê tông nhẹ cách nhiệt", slug: "be-tong-nhe-cach-nhiet-cn2-ngan", status: "done" },
  { no: 5750, title: "Bê Tông Sợi Thép", keyword: "bê tông sợi thép", slug: "be-tong-soi-thep-cn2-ngan", status: "done" },
  { no: 5751, title: "Bê Tông In 3D", keyword: "bê tông in 3d", slug: "be-tong-in-3d-cn2-ngan", status: "done" },
  { no: 5752, title: "In Nhà 3D Việt Nam", keyword: "in nhà 3d việt nam", slug: "in-nha-3d-viet-nam-cn2-ngan", status: "done" },
  { no: 5753, title: "Công Nghệ Prefab Nhà Ở", keyword: "công nghệ prefab nhà ở", slug: "cong-nghe-prefab-nha-o-cn2-ngan", status: "done" },
  { no: 5754, title: "Panel Tường Prefab", keyword: "panel tường prefab", slug: "panel-tuong-prefab-cn2-ngan", status: "done" },
  { no: 5755, title: "Sàn Prefab Nhà Phố", keyword: "sàn prefab nhà phố", slug: "san-prefab-nha-pho-cn2-ngan", status: "done" },
  { no: 5756, title: "Module Bathroom Prefab", keyword: "module bathroom prefab", slug: "module-bathroom-prefab-cn2-ngan", status: "done" },
  { no: 5757, title: "Khung Thép Tiền Chế Nhà", keyword: "khung thép tiền chế nhà", slug: "khung-thep-tien-che-nha-cn2-ngan", status: "done" },
  { no: 5758, title: "Nhà Thép Tiền Chế 1 Tầng", keyword: "nhà thép tiền chế 1 tầng", slug: "nha-thep-tien-che-1-tang-cn2-ngan", status: "done" },
  { no: 5759, title: "Nhà Thép Tiền Chế 2 Tầng", keyword: "nhà thép tiền chế 2 tầng", slug: "nha-thep-tien-che-2-tang-cn2-ngan", status: "done" },
  { no: 5760, title: "CLB Wall Panel", keyword: "clb wall panel", slug: "clb-wall-panel-cn2-ngan", status: "done" },
  { no: 5761, title: "ALC Panel Tường", keyword: "alc panel tường", slug: "alc-panel-tuong-cn2-ngan", status: "done" },
  { no: 5762, title: "EPS Cement Panel", keyword: "eps cement panel", slug: "eps-cement-panel-cn2-ngan", status: "done" },
  { no: 5763, title: "Tấm Panel Cách Nhiệt PU", keyword: "tấm panel cách nhiệt pu", slug: "tam-panel-cach-nhiet-pu-cn2-ngan", status: "done" },
  { no: 5764, title: "Vách Panel Phòng Sạch Mini", keyword: "vách panel phòng sạch mini", slug: "vach-panel-phong-sach-mini-cn2-ngan", status: "done" },
  { no: 5765, title: "Sàn Raised Floor Nhà", keyword: "sàn raised floor nhà", slug: "san-raised-floor-nha-cn2-ngan", status: "done" },
  { no: 5766, title: "Sàn Access Floor", keyword: "sàn access floor", slug: "san-access-floor-cn2-ngan", status: "done" },
  { no: 5767, title: "Hệ Thống BIM Level 2", keyword: "hệ thống bim level 2", slug: "he-thong-bim-level-2-cn2-ngan", status: "done" },
  { no: 5768, title: "Digital Twin Nhà Ở", keyword: "digital twin nhà ở", slug: "digital-twin-nha-o-cn2-ngan", status: "done" },
  { no: 5769, title: "IoT Giám Sát Công Trình", keyword: "iot giám sát công trình", slug: "iot-giam-sat-cong-trinh-cn2-ngan", status: "done" },
  { no: 5770, title: "Sensor Độ Ẩm Tường", keyword: "sensor độ ẩm tường", slug: "sensor-do-am-tuong-cn2-ngan", status: "done" },
  { no: 5771, title: "Sensor Nứt Kết Cấu", keyword: "sensor nứt kết cấu", slug: "sensor-nut-ket-cau-cn2-ngan", status: "done" },
  { no: 5772, title: "Drone Kiểm Tra Mái", keyword: "drone kiểm tra mái", slug: "drone-kiem-tra-mai-cn2-ngan", status: "done" },
  { no: 5773, title: "Thermal Camera Nhà", keyword: "thermal camera nhà", slug: "thermal-camera-nha-cn2-ngan", status: "done" },
  { no: 5774, title: "Scan 3D Hiện Trạng Nhà", keyword: "scan 3d hiện trạng nhà", slug: "scan-3d-hien-trang-nha-cn2-ngan", status: "done" },
  { no: 5775, title: "Point Cloud Cải Tạo", keyword: "point cloud cải tạo", slug: "point-cloud-cai-tao-cn2-ngan", status: "done" },
  { no: 5776, title: "AR Visualize Nhà Mới", keyword: "ar visualize nhà mới", slug: "ar-visualize-nha-moi-cn2-ngan", status: "done" },
  { no: 5777, title: "VR Tour Thiết Kế Nhà", keyword: "vr tour thiết kế nhà", slug: "vr-tour-thiet-ke-nha-cn2-ngan", status: "done" },
  { no: 5778, title: "So Sánh Prefab Và Xây Truyền Thống", keyword: "so sánh prefab và xây truyền thống", slug: "so-sanh-prefab-va-xay-truyen-thong-cn2-ngan", status: "done" },
  { no: 5779, title: "So Sánh Thép Và BTCT", keyword: "so sánh thép và btct", slug: "so-sanh-thep-va-btct-cn2-ngan", status: "done" },
  { no: 5780, title: "So Sánh AAC Và Gạch Đất Nung", keyword: "so sánh aac và gạch đất nung", slug: "so-sanh-aac-va-gach-dat-nung-cn2-ngan", status: "done" },
  { no: 5781, title: "So Sánh Panel Và Xây Tường", keyword: "so sánh panel và xây tường", slug: "so-sanh-panel-va-xay-tuong-cn2-ngan", status: "done" },
  { no: 5782, title: "Ưu Nhược Điểm Nhà Prefab", keyword: "ưu nhược điểm nhà prefab", slug: "uu-nhuoc-diem-nha-prefab-cn2-ngan", status: "done" },
  { no: 5783, title: "Ưu Nhược Điểm Nhà Thép", keyword: "ưu nhược điểm nhà thép", slug: "uu-nhuoc-diem-nha-thep-cn2-ngan", status: "done" },
  { no: 5784, title: "Chi Phí Nhà Prefab m2", keyword: "chi phí nhà prefab m2", slug: "chi-phi-nha-prefab-m2-cn2-ngan", status: "done" },
  { no: 5785, title: "Chi Phí Nhà Thép m2", keyword: "chi phí nhà thép m2", slug: "chi-phi-nha-thep-m2-cn2-ngan", status: "done" },
  { no: 5786, title: "Tiến Độ Prefab Nhanh Hơn", keyword: "tiến độ prefab nhanh hơn", slug: "tien-do-prefab-nhanh-hon-cn2-ngan", status: "done" },
  { no: 5787, title: "Pháp Lý Nhà Prefab", keyword: "pháp lý nhà prefab", slug: "phap-ly-nha-prefab-cn2-ngan", status: "done" },
  { no: 5788, title: "Xin Phép Nhà Thép Tiền Chế", keyword: "xin phép nhà thép tiền chế", slug: "xin-phep-nha-thep-tien-che-cn2-ngan", status: "done" },
  { no: 5789, title: "Chống Cháy Nhà Thép", keyword: "chống cháy nhà thép", slug: "chong-chay-nha-thep-cn2-ngan", status: "done" },
  { no: 5790, title: "Cách Âm Nhà Prefab", keyword: "cách âm nhà prefab", slug: "cach-am-nha-prefab-cn2-ngan", status: "done" },
  { no: 5791, title: "Cách Nhiệt Nhà Prefab", keyword: "cách nhiệt nhà prefab", slug: "cach-nhiet-nha-prefab-cn2-ngan", status: "done" },
  { no: 5792, title: "Tuổi Thọ Nhà Prefab", keyword: "tuổi thọ nhà prefab", slug: "tuoi-tho-nha-prefab-cn2-ngan", status: "done" },
  { no: 5793, title: "Tuổi Thọ Nhà Thép", keyword: "tuổi thọ nhà thép", slug: "tuoi-tho-nha-thep-cn2-ngan", status: "done" },
  { no: 5794, title: "Bảo Dưỡng Nhà Thép", keyword: "bảo dưỡng nhà thép", slug: "bao-duong-nha-thep-cn2-ngan", status: "done" },
  { no: 5795, title: "Sơn Chống Gỉ Khung Thép", keyword: "sơn chống gỉ khung thép", slug: "son-chong-gi-khung-thep-cn2-ngan", status: "done" },
  { no: 5796, title: "Mạ Kẽm Kết Cấu Thép", keyword: "mạ kẽm kết cấu thép", slug: "ma-kem-ket-cau-thep-cn2-ngan", status: "done" },
  { no: 5797, title: "Bu Lông Cường Độ Cao", keyword: "bu lông cường độ cao", slug: "bu-long-cuong-do-cao-cn2-ngan", status: "done" },
  { no: 5798, title: "Hàn Kết Cấu Thép Nhà", keyword: "hàn kết cấu thép nhà", slug: "han-ket-cau-thep-nha-cn2-ngan", status: "done" },
  { no: 5799, title: "Nghiệm Thu Nhà Prefab", keyword: "nghiệm thu nhà prefab", slug: "nghiem-thu-nha-prefab-cn2-ngan", status: "done" },
  { no: 5800, title: "Nghiệm Thu Khung Thép", keyword: "nghiệm thu khung thép", slug: "nghiem-thu-khung-thep-cn2-ngan", status: "done" },
  { no: 5801, title: "Xu Hướng Prefab 2026", keyword: "xu hướng prefab 2026", slug: "xu-huong-prefab-2026-cn2-ngan", status: "done" },
  { no: 5802, title: "Xu Hướng Nhà Thép 2026", keyword: "xu hướng nhà thép 2026", slug: "xu-huong-nha-thep-2026-cn2-ngan", status: "done" },
  { no: 5803, title: "Xu Hướng BIM Xây Nhà", keyword: "xu hướng bim xây nhà", slug: "xu-huong-bim-xay-nha-cn2-ngan", status: "done" },
  { no: 5804, title: "Green Concrete Việt Nam", keyword: "green concrete việt nam", slug: "green-concrete-viet-nam-cn2-ngan", status: "done" },
  { no: 5805, title: "Xi Măng Carbon Thấp", keyword: "xi măng carbon thấp", slug: "xi-mang-carbon-thap-cn2-ngan", status: "done" },
  { no: 5806, title: "Vật Liệu Tái Chế Xây", keyword: "vật liệu tái chế xây", slug: "vat-lieu-tai-che-xay-cn2-ngan", status: "done" },
  { no: 5807, title: "Gạch Từ Tro Bay", keyword: "gạch từ tro bay", slug: "gach-tu-tro-bay-cn2-ngan", status: "done" },
  { no: 5808, title: "Gỗ Engineered Nội Thất", keyword: "gỗ engineered nội thất", slug: "go-engineered-noi-that-cn2-ngan", status: "done" },
  { no: 5809, title: "Bamboo Construction", keyword: "bamboo construction", slug: "bamboo-construction-cn2-ngan", status: "done" },
  { no: 5810, title: "Nhà Tre Hiện Đại", keyword: "nhà tre hiện đại", slug: "nha-tre-hien-dai-cn2-ngan", status: "done" },
  { no: 5811, title: "Rammed Earth Nhà Ở", keyword: "rammed earth nhà ở", slug: "rammed-earth-nha-o-cn2-ngan", status: "done" },
  { no: 5812, title: "Nhà Đất Nện Việt Nam", keyword: "nhà đất nện việt nam", slug: "nha-dat-nen-viet-nam-cn2-ngan", status: "done" },
  { no: 5813, title: "Passive House Việt Nam", keyword: "passive house việt nam", slug: "passive-house-viet-nam-cn2-ngan", status: "done" },
  { no: 5814, title: "Nearly Zero Energy House", keyword: "nearly zero energy house", slug: "nearly-zero-energy-house-cn2-ngan", status: "done" },
  { no: 5815, title: "Heat Pump Nhà Phố", keyword: "heat pump nhà phố", slug: "heat-pump-nha-pho-cn2-ngan", status: "done" },
  { no: 5816, title: "ERV Thông Gió Thu Hồi Nhiệt", keyword: "erv thông gió thu hồi nhiệt", slug: "erv-thong-gio-thu-hoi-nhiet-cn2-ngan", status: "done" },
  { no: 5817, title: "HRV Nhà Ở", keyword: "hrv nhà ở", slug: "hrv-nha-o-cn2-ngan", status: "done" },
  { no: 5818, title: "Pin Lưu Trữ Gia Đình", keyword: "pin lưu trữ gia đình", slug: "pin-luu-tru-gia-dinh-cn2-ngan", status: "done" },
  { no: 5819, title: "Microgrid Nhà Ở", keyword: "microgrid nhà ở", slug: "microgrid-nha-o-cn2-ngan", status: "done" },
  { no: 5820, title: "Báo Giá Nhà Prefab", keyword: "báo giá nhà prefab", slug: "bao-gia-nha-prefab-cn2-ngan", status: "done" },
  { no: 5821, title: "Báo Giá Nhà Thép Tiền Chế", keyword: "báo giá nhà thép tiền chế", slug: "bao-gia-nha-thep-tien-che-cn2-ngan", status: "done" },
  { no: 5822, title: "Nhà Thầu Prefab TPHCM", keyword: "nhà thầu prefab tphcm", slug: "nha-thau-prefab-tphcm-cn2-ngan", status: "done" },
  { no: 5823, title: "Nhà Thầu Thép Tiền Chế", keyword: "nhà thầu thép tiền chế", slug: "nha-thau-thep-tien-che-cn2-ngan", status: "done" },
  { no: 5824, title: "Có Nên Xây Prefab 2026", keyword: "có nên xây prefab 2026", slug: "co-nen-xay-prefab-2026-cn2-ngan", status: "done" },
  { no: 5825, title: "Có Nên Xây Nhà Thép", keyword: "có nên xây nhà thép", slug: "co-nen-xay-nha-thep-cn2-ngan", status: "done" },
  { no: 5826, title: "Khi Nào Chọn Prefab", keyword: "khi nào chọn prefab", slug: "khi-nao-chon-prefab-cn2-ngan", status: "done" },
  { no: 5827, title: "Khi Nào Chọn BTCT", keyword: "khi nào chọn btct", slug: "khi-nao-chon-btct-cn2-ngan", status: "done" },
  { no: 5828, title: "Checklist Công Nghệ Xây Mới", keyword: "checklist công nghệ xây mới", slug: "checklist-cong-nghe-xay-moi-cn2-ngan", status: "done" },
  { no: 5829, title: "Chủ Đề Mở Rộng 63 1", keyword: "chủ đề mở rộng 63 1", slug: "chu-de-mo-rong-63-1-ngan", status: "done" },
  { no: 5830, title: "Chủ Đề Mở Rộng 63 2", keyword: "chủ đề mở rộng 63 2", slug: "chu-de-mo-rong-63-2-ngan", status: "done" },
  { no: 5831, title: "Chủ Đề Mở Rộng 63 3", keyword: "chủ đề mở rộng 63 3", slug: "chu-de-mo-rong-63-3-ngan", status: "done" },
  { no: 5832, title: "Chủ Đề Mở Rộng 63 4", keyword: "chủ đề mở rộng 63 4", slug: "chu-de-mo-rong-63-4-ngan", status: "done" },
  { no: 5833, title: "Chủ Đề Mở Rộng 63 5", keyword: "chủ đề mở rộng 63 5", slug: "chu-de-mo-rong-63-5-ngan", status: "done" },
  { no: 5834, title: "Chủ Đề Mở Rộng 63 6", keyword: "chủ đề mở rộng 63 6", slug: "chu-de-mo-rong-63-6-ngan", status: "done" },
  { no: 5835, title: "Chủ Đề Mở Rộng 63 7", keyword: "chủ đề mở rộng 63 7", slug: "chu-de-mo-rong-63-7-ngan", status: "done" },
  { no: 5836, title: "Chủ Đề Mở Rộng 63 8", keyword: "chủ đề mở rộng 63 8", slug: "chu-de-mo-rong-63-8-ngan", status: "done" },
  { no: 5837, title: "Chủ Đề Mở Rộng 63 9", keyword: "chủ đề mở rộng 63 9", slug: "chu-de-mo-rong-63-9-ngan", status: "done" },
  { no: 5838, title: "Chủ Đề Mở Rộng 63 10", keyword: "chủ đề mở rộng 63 10", slug: "chu-de-mo-rong-63-10-ngan", status: "done" },
  { no: 5839, title: "Chủ Đề Mở Rộng 63 11", keyword: "chủ đề mở rộng 63 11", slug: "chu-de-mo-rong-63-11-ngan", status: "done" },
  { no: 5840, title: "Chủ Đề Mở Rộng 63 12", keyword: "chủ đề mở rộng 63 12", slug: "chu-de-mo-rong-63-12-ngan", status: "done" },
  { no: 5841, title: "Chủ Đề Mở Rộng 63 13", keyword: "chủ đề mở rộng 63 13", slug: "chu-de-mo-rong-63-13-ngan", status: "done" },
  { no: 5842, title: "Chủ Đề Mở Rộng 63 14", keyword: "chủ đề mở rộng 63 14", slug: "chu-de-mo-rong-63-14-ngan", status: "done" },
  { no: 5843, title: "Chủ Đề Mở Rộng 63 15", keyword: "chủ đề mở rộng 63 15", slug: "chu-de-mo-rong-63-15-ngan", status: "done" },
  { no: 5844, title: "Chủ Đề Mở Rộng 63 16", keyword: "chủ đề mở rộng 63 16", slug: "chu-de-mo-rong-63-16-ngan", status: "done" },
  { no: 5845, title: "Chủ Đề Mở Rộng 63 17", keyword: "chủ đề mở rộng 63 17", slug: "chu-de-mo-rong-63-17-ngan", status: "done" },
  { no: 5846, title: "Chủ Đề Mở Rộng 63 18", keyword: "chủ đề mở rộng 63 18", slug: "chu-de-mo-rong-63-18-ngan", status: "done" },
];
