/**
 * Lịch 100 từ khóa ngắn — batch 42 (#3647–#3746).
 * Cluster: geo ĐBSCL huyện/thị xã.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch42: ContentCalendarItem[] = [
  { no: 3647, title: "Xây Nhà Châu Thành TG", keyword: "xây nhà Châu Thành Tiền Giang", slug: "xay-nha-chau-thanh-tg-mk-ngan", status: "done" },
  { no: 3648, title: "Xây Nhà Chợ Gạo", keyword: "xây nhà Chợ Gạo", slug: "xay-nha-cho-gao-mk-ngan", status: "done" },
  { no: 3649, title: "Xây Nhà Tân Phước TG", keyword: "xây nhà Tân Phước", slug: "xay-nha-tan-phuoc-tg-mk-ngan", status: "done" },
  { no: 3650, title: "Xây Nhà Gò Công Tây", keyword: "xây nhà Gò Công Tây", slug: "xay-nha-go-cong-tay-mk-ngan", status: "done" },
  { no: 3651, title: "Xây Nhà Gò Công Đông", keyword: "xây nhà Gò Công Đông", slug: "xay-nha-go-cong-dong-mk-ngan", status: "done" },
  { no: 3652, title: "Xây Nhà Châu Thành BT", keyword: "xây nhà Châu Thành Bến Tre", slug: "xay-nha-chau-thanh-bt-mk-ngan", status: "done" },
  { no: 3653, title: "Xây Nhà Chợ Lách", keyword: "xây nhà Chợ Lách", slug: "xay-nha-cho-lach-mk-ngan", status: "done" },
  { no: 3654, title: "Xây Nhà Mỏ Cày Nam", keyword: "xây nhà Mỏ Cày Nam", slug: "xay-nha-mo-cay-nam-mk-ngan", status: "done" },
  { no: 3655, title: "Xây Nhà Mỏ Cày Bắc", keyword: "xây nhà Mỏ Cày Bắc", slug: "xay-nha-mo-cay-bac-mk-ngan", status: "done" },
  { no: 3656, title: "Xây Nhà Giồng Trôm", keyword: "xây nhà Giồng Trôm", slug: "xay-nha-giong-trom-mk-ngan", status: "done" },
  { no: 3657, title: "Xây Nhà Ba Tri", keyword: "xây nhà Ba Tri", slug: "xay-nha-ba-tri-mk-ngan", status: "done" },
  { no: 3658, title: "Xây Nhà Bình Đại", keyword: "xây nhà Bình Đại", slug: "xay-nha-binh-dai-mk-ngan", status: "done" },
  { no: 3659, title: "Xây Nhà Thạnh Phú BT", keyword: "xây nhà Thạnh Phú Bến Tre", slug: "xay-nha-thanh-phu-bt-mk-ngan", status: "done" },
  { no: 3660, title: "Xây Nhà Trà Ôn", keyword: "xây nhà Trà Ôn", slug: "xay-nha-tra-on-mk-ngan", status: "done" },
  { no: 3661, title: "Xây Nhà Vũng Liêm", keyword: "xây nhà Vũng Liêm", slug: "xay-nha-vung-liem-mk-ngan", status: "done" },
  { no: 3662, title: "Xây Nhà Mang Thít", keyword: "xây nhà Mang Thít", slug: "xay-nha-mang-thit-mk-ngan", status: "done" },
  { no: 3663, title: "Xây Nhà Long Hồ", keyword: "xây nhà Long Hồ", slug: "xay-nha-long-ho-mk-ngan", status: "done" },
  { no: 3664, title: "Xây Nhà Tam Bình", keyword: "xây nhà Tam Bình", slug: "xay-nha-tam-binh-mk-ngan", status: "done" },
  { no: 3665, title: "Xây Nhà Bình Minh VL", keyword: "xây nhà Bình Minh Vĩnh Long", slug: "xay-nha-binh-minh-vl-mk-ngan", status: "done" },
  { no: 3666, title: "Xây Nhà Càng Long", keyword: "xây nhà Càng Long", slug: "xay-nha-cang-long-mk-ngan", status: "done" },
  { no: 3667, title: "Xây Nhà Cầu Kè", keyword: "xây nhà Cầu Kè", slug: "xay-nha-cau-ke-mk-ngan", status: "done" },
  { no: 3668, title: "Xây Nhà Tiểu Cần", keyword: "xây nhà Tiểu Cần", slug: "xay-nha-tieu-can-mk-ngan", status: "done" },
  { no: 3669, title: "Xây Nhà Châu Thành TV", keyword: "xây nhà Châu Thành Trà Vinh", slug: "xay-nha-chau-thanh-tv-mk-ngan", status: "done" },
  { no: 3670, title: "Xây Nhà Cầu Ngang", keyword: "xây nhà Cầu Ngang", slug: "xay-nha-cau-ngang-mk-ngan", status: "done" },
  { no: 3671, title: "Xây Nhà Trà Cú", keyword: "xây nhà Trà Cú", slug: "xay-nha-tra-cu-mk-ngan", status: "done" },
  { no: 3672, title: "Xây Nhà Duyên Hải", keyword: "xây nhà Duyên Hải", slug: "xay-nha-duyen-hai-mk-ngan", status: "done" },
  { no: 3673, title: "Xây Nhà Lai Vung", keyword: "xây nhà Lai Vung", slug: "xay-nha-lai-vung-mk-ngan", status: "done" },
  { no: 3674, title: "Xây Nhà Lấp Vò", keyword: "xây nhà Lấp Vò", slug: "xay-nha-lap-vo-mk-ngan", status: "done" },
  { no: 3675, title: "Xây Nhà Thanh Bình ĐT", keyword: "xây nhà Thanh Bình Đồng Tháp", slug: "xay-nha-thanh-binh-dt-mk-ngan", status: "done" },
  { no: 3676, title: "Xây Nhà Tân Hồng", keyword: "xây nhà Tân Hồng", slug: "xay-nha-tan-hong-mk-ngan", status: "done" },
  { no: 3677, title: "Xây Nhà Hồng Ngự", keyword: "xây nhà Hồng Ngự", slug: "xay-nha-hong-ngu-mk-ngan", status: "done" },
  { no: 3678, title: "Xây Nhà Tam Nông ĐT", keyword: "xây nhà Tam Nông Đồng Tháp", slug: "xay-nha-tam-nong-dt-mk-ngan", status: "done" },
  { no: 3679, title: "Xây Nhà Tháp Mười", keyword: "xây nhà Tháp Mười", slug: "xay-nha-thap-muoi-mk-ngan", status: "done" },
  { no: 3680, title: "Xây Nhà Châu Thành AG", keyword: "xây nhà Châu Thành An Giang", slug: "xay-nha-chau-thanh-ag-mk-ngan", status: "done" },
  { no: 3681, title: "Xây Nhà Chợ Mới AG", keyword: "xây nhà Chợ Mới An Giang", slug: "xay-nha-cho-moi-ag-mk-ngan", status: "done" },
  { no: 3682, title: "Xây Nhà Thoại Sơn", keyword: "xây nhà Thoại Sơn", slug: "xay-nha-thoai-son-mk-ngan", status: "done" },
  { no: 3683, title: "Xây Nhà Tri Tôn", keyword: "xây nhà Tri Tôn", slug: "xay-nha-tri-ton-mk-ngan", status: "done" },
  { no: 3684, title: "Xây Nhà Tịnh Biên", keyword: "xây nhà Tịnh Biên", slug: "xay-nha-tinh-bien-mk-ngan", status: "done" },
  { no: 3685, title: "Xây Nhà An Phú AG", keyword: "xây nhà An Phú An Giang", slug: "xay-nha-an-phu-ag-mk-ngan", status: "done" },
  { no: 3686, title: "Xây Nhà Phú Tân AG", keyword: "xây nhà Phú Tân An Giang", slug: "xay-nha-phu-tan-ag-mk-ngan", status: "done" },
  { no: 3687, title: "Xây Nhà Tân Hiệp KG", keyword: "xây nhà Tân Hiệp Kiên Giang", slug: "xay-nha-tan-hiep-kg-mk-ngan", status: "done" },
  { no: 3688, title: "Xây Nhà Châu Thành KG", keyword: "xây nhà Châu Thành Kiên Giang", slug: "xay-nha-chau-thanh-kg-mk-ngan", status: "done" },
  { no: 3689, title: "Xây Nhà Giồng Riềng", keyword: "xây nhà Giồng Riềng", slug: "xay-nha-giong-rieng-mk-ngan", status: "done" },
  { no: 3690, title: "Xây Nhà Gò Quao", keyword: "xây nhà Gò Quao", slug: "xay-nha-go-quao-mk-ngan", status: "done" },
  { no: 3691, title: "Xây Nhà An Biên", keyword: "xây nhà An Biên", slug: "xay-nha-an-bien-mk-ngan", status: "done" },
  { no: 3692, title: "Xây Nhà An Minh", keyword: "xây nhà An Minh", slug: "xay-nha-an-minh-mk-ngan", status: "done" },
  { no: 3693, title: "Xây Nhà Vĩnh Thuận", keyword: "xây nhà Vĩnh Thuận", slug: "xay-nha-vinh-thuan-mk-ngan", status: "done" },
  { no: 3694, title: "Xây Nhà Phú Quốc", keyword: "xây nhà Phú Quốc", slug: "xay-nha-phu-quoc-mk-ngan", status: "done" },
  { no: 3695, title: "Xây Nhà Hà Tiên KG", keyword: "xây nhà Hà Tiên Kiên Giang", slug: "xay-nha-ha-tien-kg-mk-ngan", status: "done" },
  { no: 3696, title: "Xây Nhà Kiên Lương", keyword: "xây nhà Kiên Lương", slug: "xay-nha-kien-luong-mk-ngan", status: "done" },
  { no: 3697, title: "Xây Nhà Hồng Dân", keyword: "xây nhà Hồng Dân", slug: "xay-nha-hong-dan-mk-ngan", status: "done" },
  { no: 3698, title: "Xây Nhà Phước Long BL", keyword: "xây nhà Phước Long Bạc Liêu", slug: "xay-nha-phuoc-long-bl-mk-ngan", status: "done" },
  { no: 3699, title: "Xây Nhà Vĩnh Lợi", keyword: "xây nhà Vĩnh Lợi", slug: "xay-nha-vinh-loi-mk-ngan", status: "done" },
  { no: 3700, title: "Xây Nhà Giá Rai", keyword: "xây nhà Giá Rai", slug: "xay-nha-gia-rai-mk-ngan", status: "done" },
  { no: 3701, title: "Xây Nhà Đông Hải BL", keyword: "xây nhà Đông Hải Bạc Liêu", slug: "xay-nha-dong-hai-bl-mk-ngan", status: "done" },
  { no: 3702, title: "Xây Nhà Hòa Bình BL", keyword: "xây nhà Hòa Bình Bạc Liêu", slug: "xay-nha-hoa-binh-bl-mk-ngan", status: "done" },
  { no: 3703, title: "Xây Nhà Trần Đề", keyword: "xây nhà Trần Đề", slug: "xay-nha-tran-de-mk-ngan", status: "done" },
  { no: 3704, title: "Xây Nhà Mỹ Xuyên", keyword: "xây nhà Mỹ Xuyên", slug: "xay-nha-my-xuyen-mk-ngan", status: "done" },
  { no: 3705, title: "Xây Nhà Long Phú", keyword: "xây nhà Long Phú", slug: "xay-nha-long-phu-mk-ngan", status: "done" },
  { no: 3706, title: "Xây Nhà Thạnh Trị", keyword: "xây nhà Thạnh Trị", slug: "xay-nha-thanh-tri-st-mk-ngan", status: "done" },
  { no: 3707, title: "Xây Nhà Châu Thành ST", keyword: "xây nhà Châu Thành Sóc Trăng", slug: "xay-nha-chau-thanh-st-mk-ngan", status: "done" },
  { no: 3708, title: "Xây Nhà Kế Sách", keyword: "xây nhà Kế Sách", slug: "xay-nha-ke-sach-mk-ngan", status: "done" },
  { no: 3709, title: "Xây Nhà Mỹ Tú", keyword: "xây nhà Mỹ Tú", slug: "xay-nha-my-tu-mk-ngan", status: "done" },
  { no: 3710, title: "Xây Nhà Ngã Năm", keyword: "xây nhà Ngã Năm", slug: "xay-nha-nga-nam-mk-ngan", status: "done" },
  { no: 3711, title: "Xây Nhà Vĩnh Châu", keyword: "xây nhà Vĩnh Châu", slug: "xay-nha-vinh-chau-mk-ngan", status: "done" },
  { no: 3712, title: "Xây Nhà U Minh", keyword: "xây nhà U Minh", slug: "xay-nha-u-minh-mk-ngan", status: "done" },
  { no: 3713, title: "Xây Nhà Thới Bình", keyword: "xây nhà Thới Bình", slug: "xay-nha-thoi-binh-mk-ngan", status: "done" },
  { no: 3714, title: "Xây Nhà Trần Văn Thời", keyword: "xây nhà Trần Văn Thời", slug: "xay-nha-tran-van-thoi-mk-ngan", status: "done" },
  { no: 3715, title: "Xây Nhà Cái Nước", keyword: "xây nhà Cái Nước", slug: "xay-nha-cai-nuoc-mk-ngan", status: "done" },
  { no: 3716, title: "Xây Nhà Đầm Dơi", keyword: "xây nhà Đầm Dơi", slug: "xay-nha-dam-doi-mk-ngan", status: "done" },
  { no: 3717, title: "Xây Nhà Năm Căn", keyword: "xây nhà Năm Căn", slug: "xay-nha-nam-can-mk-ngan", status: "done" },
  { no: 3718, title: "Xây Nhà Ngọc Hiển", keyword: "xây nhà Ngọc Hiển", slug: "xay-nha-ngoc-hien-mk-ngan", status: "done" },
  { no: 3719, title: "Xây Nhà Phú Tân CM", keyword: "xây nhà Phú Tân Cà Mau", slug: "xay-nha-phu-tan-cm-mk-ngan", status: "done" },
  { no: 3720, title: "Cải Tạo Nhà Phú Quốc", keyword: "cải tạo nhà Phú Quốc", slug: "cai-tao-nha-phu-quoc-mk-ngan", status: "done" },
  { no: 3721, title: "Cải Tạo Nhà Châu Đốc AG", keyword: "cải tạo nhà Châu Đốc", slug: "cai-tao-nha-chau-doc-ag-mk-ngan", status: "done" },
  { no: 3722, title: "Cải Tạo Nhà Rạch Giá", keyword: "cải tạo nhà Rạch Giá", slug: "cai-tao-nha-rach-gia-mk-ngan", status: "done" },
  { no: 3723, title: "Cải Tạo Nhà Sa Đéc", keyword: "cải tạo nhà Sa Đéc", slug: "cai-tao-nha-sa-dec-mk-ngan", status: "done" },
  { no: 3724, title: "Thiết Kế Nhà Phú Quốc", keyword: "thiết kế nhà Phú Quốc", slug: "thiet-ke-nha-phu-quoc-mk-ngan", status: "done" },
  { no: 3725, title: "Thiết Kế Nhà Châu Đốc", keyword: "thiết kế nhà Châu Đốc", slug: "thiet-ke-nha-chau-doc-mk-ngan", status: "done" },
  { no: 3726, title: "Thiết Kế Nhà Rạch Giá", keyword: "thiết kế nhà Rạch Giá", slug: "thiet-ke-nha-rach-gia-mk-ngan", status: "done" },
  { no: 3727, title: "Báo Giá Xây Nhà Kiên Giang", keyword: "báo giá xây nhà Kiên Giang", slug: "bao-gia-xay-nha-kien-giang-mk-ngan", status: "done" },
  { no: 3728, title: "Báo Giá Xây Nhà An Giang", keyword: "báo giá xây nhà An Giang", slug: "bao-gia-xay-nha-an-giang-mk-ngan", status: "done" },
  { no: 3729, title: "Báo Giá Xây Nhà Đồng Tháp", keyword: "báo giá xây nhà Đồng Tháp", slug: "bao-gia-xay-nha-dong-thap-mk-ngan", status: "done" },
  { no: 3730, title: "Báo Giá Xây Nhà Vĩnh Long", keyword: "báo giá xây nhà Vĩnh Long", slug: "bao-gia-xay-nha-vinh-long-mk-ngan", status: "done" },
  { no: 3731, title: "Báo Giá Xây Nhà Bến Tre", keyword: "báo giá xây nhà Bến Tre", slug: "bao-gia-xay-nha-ben-tre-mk-ngan", status: "done" },
  { no: 3732, title: "Báo Giá Xây Nhà Trà Vinh", keyword: "báo giá xây nhà Trà Vinh", slug: "bao-gia-xay-nha-tra-vinh-mk-ngan", status: "done" },
  { no: 3733, title: "Báo Giá Xây Nhà Sóc Trăng", keyword: "báo giá xây nhà Sóc Trăng", slug: "bao-gia-xay-nha-soc-trang-mk-ngan", status: "done" },
  { no: 3734, title: "Báo Giá Xây Nhà Bạc Liêu", keyword: "báo giá xây nhà Bạc Liêu", slug: "bao-gia-xay-nha-bac-lieu-mk-ngan", status: "done" },
  { no: 3735, title: "Báo Giá Xây Nhà Cà Mau", keyword: "báo giá xây nhà Cà Mau", slug: "bao-gia-xay-nha-ca-mau-mk-ngan", status: "done" },
  { no: 3736, title: "Nhà Thầu Kiên Giang", keyword: "nhà thầu Kiên Giang", slug: "nha-thau-kien-giang-mk-ngan", status: "done" },
  { no: 3737, title: "Nhà Thầu An Giang", keyword: "nhà thầu An Giang", slug: "nha-thau-an-giang-mk-ngan", status: "done" },
  { no: 3738, title: "Nhà Thầu Đồng Tháp", keyword: "nhà thầu Đồng Tháp", slug: "nha-thau-dong-thap-mk-ngan", status: "done" },
  { no: 3739, title: "Nhà Thầu Phú Quốc", keyword: "nhà thầu Phú Quốc", slug: "nha-thau-phu-quoc-mk-ngan", status: "done" },
  { no: 3740, title: "Xây Nhà Ven Sông ĐBSCL", keyword: "xây nhà ven sông ĐBSCL", slug: "xay-nha-ven-song-dbscl-mk-ngan", status: "done" },
  { no: 3741, title: "Xây Nhà Chống Lún ĐBSCL", keyword: "xây nhà chống lún ĐBSCL", slug: "xay-nha-chong-lun-dbscl-mk-ngan", status: "done" },
  { no: 3742, title: "Xây Nhà Chống Ngập ĐBSCL", keyword: "xây nhà chống ngập ĐBSCL", slug: "xay-nha-chong-ngap-dbscl-mk-ngan", status: "done" },
  { no: 3743, title: "Xây Nhà Trên Đất Yếu", keyword: "xây nhà trên đất yếu", slug: "xay-nha-tren-dat-yeu-mk-ngan", status: "done" },
  { no: 3744, title: "Xây Nhà Gần Biển Cà Mau", keyword: "xây nhà gần biển Cà Mau", slug: "xay-nha-gan-bien-ca-mau-mk-ngan", status: "done" },
  { no: 3745, title: "Xây Biệt Thự Phú Quốc", keyword: "xây biệt thự Phú Quốc", slug: "xay-biet-thu-phu-quoc-mk-ngan", status: "done" },
  { no: 3746, title: "Xây Homestay Phú Quốc", keyword: "xây homestay Phú Quốc", slug: "xay-homestay-phu-quoc-mk-ngan", status: "done" },
];
