/**
 * Lịch 100 từ khóa ngắn — batch 53 (#4747–#4846).
 * Cluster: bảo trì, bảo hành, vòng đời nhà.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch53: ContentCalendarItem[] = [
  { no: 4747, title: "Bảo Trì Nhà Định Kỳ", keyword: "bảo trì nhà định kỳ", slug: "bao-tri-nha-dinh-ky-bt-ngan", status: "done" },
  { no: 4748, title: "Bảo Trì Nhà Hàng Năm", keyword: "bảo trì nhà hàng năm", slug: "bao-tri-nha-hang-nam-bt-ngan", status: "done" },
  { no: 4749, title: "Bảo Trì Nhà Hàng Quý", keyword: "bảo trì nhà hàng quý", slug: "bao-tri-nha-hang-quy-bt-ngan", status: "done" },
  { no: 4750, title: "Checklist Bảo Trì Nhà", keyword: "checklist bảo trì nhà", slug: "checklist-bao-tri-nha-bt-ngan", status: "done" },
  { no: 4751, title: "Bảo Trì Mái Nhà", keyword: "bảo trì mái nhà", slug: "bao-tri-mai-nha-bt-ngan", status: "done" },
  { no: 4752, title: "Bảo Trì Hệ Thống Điện", keyword: "bảo trì hệ thống điện", slug: "bao-tri-he-thong-dien-bt-ngan", status: "done" },
  { no: 4753, title: "Bảo Trì Hệ Thống Nước", keyword: "bảo trì hệ thống nước", slug: "bao-tri-he-thong-nuoc-bt-ngan", status: "done" },
  { no: 4754, title: "Bảo Trì Máy Lạnh Nhà", keyword: "bảo trì máy lạnh nhà", slug: "bao-tri-may-lanh-nha-bt-ngan", status: "done" },
  { no: 4755, title: "Bảo Trì Bơm Nước", keyword: "bảo trì bơm nước", slug: "bao-tri-bom-nuoc-bt-ngan", status: "done" },
  { no: 4756, title: "Bảo Trì Bể Phốt", keyword: "bảo trì bể phốt", slug: "bao-tri-be-phot-bt-ngan", status: "done" },
  { no: 4757, title: "Hút Bể Phốt Định Kỳ", keyword: "hút bể phốt định kỳ", slug: "hut-be-phot-dinh-ky-bt-ngan", status: "done" },
  { no: 4758, title: "Thông Cống Nhà Phố", keyword: "thông cống nhà phố", slug: "thong-cong-nha-pho-bt-ngan", status: "done" },
  { no: 4759, title: "Vệ Sinh Mái Tôn", keyword: "vệ sinh mái tôn", slug: "ve-sinh-mai-ton-bt-ngan", status: "done" },
  { no: 4760, title: "Vệ Sinh Sân Thượng", keyword: "vệ sinh sân thượng", slug: "ve-sinh-san-thuong-bt-ngan", status: "done" },
  { no: 4761, title: "Vệ Sinh Giếng Trời", keyword: "vệ sinh giếng trời", slug: "ve-sinh-gieng-troi-bt-ngan", status: "done" },
  { no: 4762, title: "Vệ Sinh Cửa Kính", keyword: "vệ sinh cửa kính", slug: "ve-sinh-cua-kinh-bt-ngan", status: "done" },
  { no: 4763, title: "Bảo Dưỡng Sơn Ngoại Thất", keyword: "bảo dưỡng sơn ngoại thất", slug: "bao-duong-son-ngoai-that-bt-ngan", status: "done" },
  { no: 4764, title: "Bảo Dưỡng Gỗ Nội Thất", keyword: "bảo dưỡng gỗ nội thất", slug: "bao-duong-go-noi-that-bt-ngan", status: "done" },
  { no: 4765, title: "Bảo Dưỡng Sàn Gỗ", keyword: "bảo dưỡng sàn gỗ", slug: "bao-duong-san-go-bt-ngan", status: "done" },
  { no: 4766, title: "Đánh Bóng Sàn Đá", keyword: "đánh bóng sàn đá", slug: "danh-bong-san-da-bt-ngan", status: "done" },
  { no: 4767, title: "Chống Thấm Định Kỳ", keyword: "chống thấm định kỳ", slug: "chong-tham-dinh-ky-bt-ngan", status: "done" },
  { no: 4768, title: "Kiểm Tra Thấm Mùa Mưa", keyword: "kiểm tra thấm mùa mưa", slug: "kiem-tra-tham-mua-mua-bt-ngan", status: "done" },
  { no: 4769, title: "Kiểm Tra Điện An Toàn", keyword: "kiểm tra điện an toàn", slug: "kiem-tra-dien-an-toan-bt-ngan", status: "done" },
  { no: 4770, title: "Thay Pin Báo Cháy", keyword: "thay pin báo cháy", slug: "thay-pin-bao-chay-bt-ngan", status: "done" },
  { no: 4771, title: "Thay Lọc Máy Lạnh", keyword: "thay lọc máy lạnh", slug: "thay-loc-may-lanh-bt-ngan", status: "done" },
  { no: 4772, title: "Thay Lọc Nước RO", keyword: "thay lọc nước ro", slug: "thay-loc-nuoc-ro-bt-ngan", status: "done" },
  { no: 4773, title: "Bảo Hành Kết Cấu Nhà", keyword: "bảo hành kết cấu nhà", slug: "bao-hanh-ket-cau-nha-bt-ngan", status: "done" },
  { no: 4774, title: "Bảo Hành Chống Thấm", keyword: "bảo hành chống thấm", slug: "bao-hanh-chong-tham-bt-ngan", status: "done" },
  { no: 4775, title: "Bảo Hành Sơn Nhà", keyword: "bảo hành sơn nhà", slug: "bao-hanh-son-nha-bt-ngan", status: "done" },
  { no: 4776, title: "Bảo Hành Ốp Lát", keyword: "bảo hành ốp lát", slug: "bao-hanh-op-lat-bt-ngan", status: "done" },
  { no: 4777, title: "Bảo Hành Điện Nước", keyword: "bảo hành điện nước", slug: "bao-hanh-dien-nuoc-bt-ngan", status: "done" },
  { no: 4778, title: "Bảo Hành Cửa Nhôm", keyword: "bảo hành cửa nhôm", slug: "bao-hanh-cua-nhom-bt-ngan", status: "done" },
  { no: 4779, title: "Bảo Hành Nội Thất", keyword: "bảo hành nội thất", slug: "bao-hanh-noi-that-bt-ngan", status: "done" },
  { no: 4780, title: "Cách Đòi Bảo Hành Xây", keyword: "cách đòi bảo hành xây", slug: "cach-doi-bao-hanh-xay-bt-ngan", status: "done" },
  { no: 4781, title: "Thời Hạn Bảo Hành Xây", keyword: "thời hạn bảo hành xây", slug: "thoi-han-bao-hanh-xay-bt-ngan", status: "done" },
  { no: 4782, title: "Điều Khoản Bảo Hành Hợp Đồng", keyword: "điều khoản bảo hành hợp đồng", slug: "dieu-khoan-bao-hanh-hop-dong-bt-ngan", status: "done" },
  { no: 4783, title: "Sửa Chữa Trong Bảo Hành", keyword: "sửa chữa trong bảo hành", slug: "sua-chua-trong-bao-hanh-bt-ngan", status: "done" },
  { no: 4784, title: "Sửa Chữa Ngoài Bảo Hành", keyword: "sửa chữa ngoài bảo hành", slug: "sua-chua-ngoai-bao-hanh-bt-ngan", status: "done" },
  { no: 4785, title: "Chi Phí Bảo Trì Nhà Năm", keyword: "chi phí bảo trì nhà năm", slug: "chi-phi-bao-tri-nha-nam-bt-ngan", status: "done" },
  { no: 4786, title: "Ngân Sách Bảo Trì Nhà", keyword: "ngân sách bảo trì nhà", slug: "ngan-sach-bao-tri-nha-bt-ngan", status: "done" },
  { no: 4787, title: "Gói Bảo Trì Nhà Năm", keyword: "gói bảo trì nhà năm", slug: "goi-bao-tri-nha-nam-bt-ngan", status: "done" },
  { no: 4788, title: "Dịch Vụ Bảo Trì Nhà Phố", keyword: "dịch vụ bảo trì nhà phố", slug: "dich-vu-bao-tri-nha-pho-bt-ngan", status: "done" },
  { no: 4789, title: "Bảo Trì Nhà Cho Thuê", keyword: "bảo trì nhà cho thuê", slug: "bao-tri-nha-cho-thue-bt-ngan", status: "done" },
  { no: 4790, title: "Bảo Trì Nhà Vắng Chủ", keyword: "bảo trì nhà vắng chủ", slug: "bao-tri-nha-vang-chu-bt-ngan", status: "done" },
  { no: 4791, title: "Tuổi Thọ Nhà Phố", keyword: "tuổi thọ nhà phố", slug: "tuoi-tho-nha-pho-bt-ngan", status: "done" },
  { no: 4792, title: "Tuổi Thọ Mái Tôn", keyword: "tuổi thọ mái tôn", slug: "tuoi-tho-mai-ton-bt-ngan", status: "done" },
  { no: 4793, title: "Tuổi Thọ Mái Ngói", keyword: "tuổi thọ mái ngói", slug: "tuoi-tho-mai-ngoi-bt-ngan", status: "done" },
  { no: 4794, title: "Tuổi Thọ Sơn Ngoại Thất", keyword: "tuổi thọ sơn ngoại thất", slug: "tuoi-tho-son-ngoai-that-bt-ngan", status: "done" },
  { no: 4795, title: "Tuổi Thọ Sàn Gỗ", keyword: "tuổi thọ sàn gỗ", slug: "tuoi-tho-san-go-bt-ngan", status: "done" },
  { no: 4796, title: "Tuổi Thọ Cửa Nhôm", keyword: "tuổi thọ cửa nhôm", slug: "tuoi-tho-cua-nhom-bt-ngan", status: "done" },
  { no: 4797, title: "Khi Nào Sơn Lại Nhà", keyword: "khi nào sơn lại nhà", slug: "khi-nao-son-lai-nha-bt-ngan", status: "done" },
  { no: 4798, title: "Khi Nào Thay Mái Tôn", keyword: "khi nào thay mái tôn", slug: "khi-nao-thay-mai-ton-bt-ngan", status: "done" },
  { no: 4799, title: "Khi Nào Thay Ống Nước", keyword: "khi nào thay ống nước", slug: "khi-nao-thay-ong-nuoc-bt-ngan", status: "done" },
  { no: 4800, title: "Khi Nào Thay Dây Điện", keyword: "khi nào thay dây điện", slug: "khi-nao-thay-day-dien-bt-ngan", status: "done" },
  { no: 4801, title: "Dấu Hiệu Nhà Cần Bảo Trì", keyword: "dấu hiệu nhà cần bảo trì", slug: "dau-hieu-nha-can-bao-tri-bt-ngan", status: "done" },
  { no: 4802, title: "Dấu Hiệu Thấm Sắp Xảy Ra", keyword: "dấu hiệu thấm sắp xảy ra", slug: "dau-hieu-tham-sap-xay-ra-bt-ngan", status: "done" },
  { no: 4803, title: "Dấu Hiệu Hệ Điện Yếu", keyword: "dấu hiệu hệ điện yếu", slug: "dau-hieu-he-dien-yeu-bt-ngan", status: "done" },
  { no: 4804, title: "Dấu Hiệu Hệ Nước Lỗi", keyword: "dấu hiệu hệ nước lỗi", slug: "dau-hieu-he-nuoc-loi-bt-ngan", status: "done" },
  { no: 4805, title: "Phòng Ngừa Mối Nhà Gỗ", keyword: "phòng ngừa mối nhà gỗ", slug: "phong-ngua-moi-nha-go-bt-ngan", status: "done" },
  { no: 4806, title: "Phòng Ngừa Mốc Nhà", keyword: "phòng ngừa mốc nhà", slug: "phong-ngua-moc-nha-bt-ngan", status: "done" },
  { no: 4807, title: "Phòng Ngừa Rỉ Sét Lan Can", keyword: "phòng ngừa rỉ sét lan can", slug: "phong-ngua-ri-set-lan-can-bt-ngan", status: "done" },
  { no: 4808, title: "Phòng Ngừa Tắc Cống", keyword: "phòng ngừa tắc cống", slug: "phong-ngua-tac-cong-bt-ngan", status: "done" },
  { no: 4809, title: "Bảo Trì Trước Mùa Mưa", keyword: "bảo trì trước mùa mưa", slug: "bao-tri-truoc-mua-mua-bt-ngan", status: "done" },
  { no: 4810, title: "Bảo Trì Sau Mùa Mưa", keyword: "bảo trì sau mùa mưa", slug: "bao-tri-sau-mua-mua-bt-ngan", status: "done" },
  { no: 4811, title: "Bảo Trì Trước Tết", keyword: "bảo trì trước tết", slug: "bao-tri-truoc-tet-bt-ngan", status: "done" },
  { no: 4812, title: "Dọn Dẹp Công Trình Sau Xây", keyword: "dọn dẹp công trình sau xây", slug: "don-dep-cong-trinh-sau-xay-bt-ngan", status: "done" },
  { no: 4813, title: "Vệ Sinh Công Nghiệp Sau Bàn Giao", keyword: "vệ sinh công nghiệp sau bàn giao", slug: "ve-sinh-cong-nghiep-sau-ban-giao-bt-ngan", status: "done" },
  { no: 4814, title: "Chăm Sóc Nhà Mới Xây", keyword: "chăm sóc nhà mới xây", slug: "cham-soc-nha-moi-xay-bt-ngan", status: "done" },
  { no: 4815, title: "Chăm Sóc Nhà Sau Cải Tạo", keyword: "chăm sóc nhà sau cải tạo", slug: "cham-soc-nha-sau-cai-tao-bt-ngan", status: "done" },
  { no: 4816, title: "Hướng Dẫn Sử Dụng Nhà Mới", keyword: "hướng dẫn sử dụng nhà mới", slug: "huong-dan-su-dung-nha-moi-bt-ngan", status: "done" },
  { no: 4817, title: "Sổ Tay Bảo Trì Nhà", keyword: "sổ tay bảo trì nhà", slug: "so-tay-bao-tri-nha-bt-ngan", status: "done" },
  { no: 4818, title: "Lịch Bảo Trì 12 Tháng", keyword: "lịch bảo trì 12 tháng", slug: "lich-bao-tri-12-thang-bt-ngan", status: "done" },
  { no: 4819, title: "App Nhắc Bảo Trì Nhà", keyword: "app nhắc bảo trì nhà", slug: "app-nhac-bao-tri-nha-bt-ngan", status: "done" },
  { no: 4820, title: "Bảo Hiểm Nhà Và Bảo Trì", keyword: "bảo hiểm nhà và bảo trì", slug: "bao-hiem-nha-va-bao-tri-bt-ngan", status: "done" },
  { no: 4821, title: "Chi Phí Vòng Đời Nhà Ở", keyword: "chi phí vòng đời nhà ở", slug: "chi-phi-vong-doi-nha-o-bt-ngan", status: "done" },
  { no: 4822, title: "Tối Ưu Chi Phí Sở Hữu Nhà", keyword: "tối ưu chi phí sở hữu nhà", slug: "toi-uu-chi-phi-so-huu-nha-bt-ngan", status: "done" },
  { no: 4823, title: "Giá Trị Thanh Lý Nhà Cũ", keyword: "giá trị thanh lý nhà cũ", slug: "gia-tri-thanh-ly-nha-cu-bt-ngan", status: "done" },
  { no: 4824, title: "Nâng Cấp Nhà Thay Thế Mới", keyword: "nâng cấp nhà thay thế mới", slug: "nang-cap-nha-thay-the-moi-bt-ngan", status: "done" },
  { no: 4825, title: "Retrofit Nhà Phố", keyword: "retrofit nhà phố", slug: "retrofit-nha-pho-bt-ngan", status: "done" },
  { no: 4826, title: "Nâng Cấp Năng Lượng Nhà", keyword: "nâng cấp năng lượng nhà", slug: "nang-cap-nang-luong-nha-bt-ngan", status: "done" },
  { no: 4827, title: "Nâng Cấp Cách Nhiệt Nhà", keyword: "nâng cấp cách nhiệt nhà", slug: "nang-cap-cach-nhiet-nha-bt-ngan", status: "done" },
  { no: 4828, title: "Nâng Cấp Cách Âm Nhà", keyword: "nâng cấp cách âm nhà", slug: "nang-cap-cach-am-nha-bt-ngan", status: "done" },
  { no: 4829, title: "Nâng Cấp Smart Home Cũ", keyword: "nâng cấp smart home cũ", slug: "nang-cap-smart-home-cu-bt-ngan", status: "done" },
  { no: 4830, title: "Báo Giá Bảo Trì Nhà Năm", keyword: "báo giá bảo trì nhà năm", slug: "bao-gia-bao-tri-nha-nam-bt-ngan", status: "done" },
  { no: 4831, title: "Báo Giá Sơn Lại Nhà", keyword: "báo giá sơn lại nhà", slug: "bao-gia-son-lai-nha-bt-ngan", status: "done" },
  { no: 4832, title: "Báo Giá Thay Mái Tôn", keyword: "báo giá thay mái tôn", slug: "bao-gia-thay-mai-ton-bt-ngan", status: "done" },
  { no: 4833, title: "Đặt Lịch Bảo Trì Nhà", keyword: "đặt lịch bảo trì nhà", slug: "dat-lich-bao-tri-nha-bt-ngan", status: "done" },
  { no: 4834, title: "Hotline Bảo Hành Xây", keyword: "hotline bảo hành xây", slug: "hotline-bao-hanh-xay-bt-ngan", status: "done" },
  { no: 4835, title: "After Sales Sao Khuê", keyword: "after sales sao khuê", slug: "after-sales-sao-khue-bt-ngan", status: "done" },
  { no: 4836, title: "Chủ Đề Mở Rộng 53 1", keyword: "chủ đề mở rộng 53 1", slug: "chu-de-mo-rong-53-1-ngan", status: "done" },
  { no: 4837, title: "Chủ Đề Mở Rộng 53 2", keyword: "chủ đề mở rộng 53 2", slug: "chu-de-mo-rong-53-2-ngan", status: "done" },
  { no: 4838, title: "Chủ Đề Mở Rộng 53 3", keyword: "chủ đề mở rộng 53 3", slug: "chu-de-mo-rong-53-3-ngan", status: "done" },
  { no: 4839, title: "Chủ Đề Mở Rộng 53 4", keyword: "chủ đề mở rộng 53 4", slug: "chu-de-mo-rong-53-4-ngan", status: "done" },
  { no: 4840, title: "Chủ Đề Mở Rộng 53 5", keyword: "chủ đề mở rộng 53 5", slug: "chu-de-mo-rong-53-5-ngan", status: "done" },
  { no: 4841, title: "Chủ Đề Mở Rộng 53 6", keyword: "chủ đề mở rộng 53 6", slug: "chu-de-mo-rong-53-6-ngan", status: "done" },
  { no: 4842, title: "Chủ Đề Mở Rộng 53 7", keyword: "chủ đề mở rộng 53 7", slug: "chu-de-mo-rong-53-7-ngan", status: "done" },
  { no: 4843, title: "Chủ Đề Mở Rộng 53 8", keyword: "chủ đề mở rộng 53 8", slug: "chu-de-mo-rong-53-8-ngan", status: "done" },
  { no: 4844, title: "Chủ Đề Mở Rộng 53 9", keyword: "chủ đề mở rộng 53 9", slug: "chu-de-mo-rong-53-9-ngan", status: "done" },
  { no: 4845, title: "Chủ Đề Mở Rộng 53 10", keyword: "chủ đề mở rộng 53 10", slug: "chu-de-mo-rong-53-10-ngan", status: "done" },
  { no: 4846, title: "Chủ Đề Mở Rộng 53 11", keyword: "chủ đề mở rộng 53 11", slug: "chu-de-mo-rong-53-11-ngan", status: "done" },
];
