/**
 * Lịch 100 từ khóa xây nhà TP.HCM — batch #12 (#597–#696).
 * Tránh trùng slug batch #5–#6; tập trung combo xây nhà + quận/phường/loại hình.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const xayNhaTphcmKeywordCalendarBatch7: ContentCalendarItem[] = [
  // —— A. Xây nhà trọn gói + quận/huyện (22) #597–#618 ——
  { no: 597, title: "Xây Nhà Trọn Gói Quận 1", keyword: "xây nhà trọn gói Quận 1", slug: "xay-nha-tron-goi-quan-1", status: "planned" },
  { no: 598, title: "Xây Nhà Trọn Gói Quận 2", keyword: "xây nhà trọn gói Quận 2", slug: "xay-nha-tron-goi-quan-2", status: "planned" },
  { no: 599, title: "Xây Nhà Trọn Gói Quận 3", keyword: "xây nhà trọn gói Quận 3", slug: "xay-nha-tron-goi-quan-3", status: "planned" },
  { no: 600, title: "Xây Nhà Trọn Gói Quận 4", keyword: "xây nhà trọn gói Quận 4", slug: "xay-nha-tron-goi-quan-4", status: "planned" },
  { no: 601, title: "Xây Nhà Trọn Gói Quận 5", keyword: "xây nhà trọn gói Quận 5", slug: "xay-nha-tron-goi-quan-5", status: "planned" },
  { no: 602, title: "Xây Nhà Trọn Gói Quận 6", keyword: "xây nhà trọn gói Quận 6", slug: "xay-nha-tron-goi-quan-6", status: "planned" },
  { no: 603, title: "Xây Nhà Trọn Gói Quận 7", keyword: "xây nhà trọn gói Quận 7", slug: "xay-nha-tron-goi-quan-7", status: "done" },
  { no: 604, title: "Xây Nhà Trọn Gói Quận 8", keyword: "xây nhà trọn gói Quận 8", slug: "xay-nha-tron-goi-quan-8", status: "planned" },
  { no: 605, title: "Xây Nhà Trọn Gói Quận 10", keyword: "xây nhà trọn gói Quận 10", slug: "xay-nha-tron-goi-quan-10", status: "planned" },
  { no: 606, title: "Xây Nhà Trọn Gói Quận 11", keyword: "xây nhà trọn gói Quận 11", slug: "xay-nha-tron-goi-quan-11", status: "planned" },
  { no: 607, title: "Xây Nhà Trọn Gói Quận 12", keyword: "xây nhà trọn gói Quận 12", slug: "xay-nha-tron-goi-quan-12", status: "planned" },
  { no: 608, title: "Xây Nhà Trọn Gói Bình Thạnh", keyword: "xây nhà trọn gói Bình Thạnh", slug: "xay-nha-tron-goi-binh-thanh", status: "done" },
  { no: 609, title: "Xây Nhà Trọn Gói Thủ Đức", keyword: "xây nhà trọn gói Thủ Đức", slug: "xay-nha-tron-goi-thu-duc", status: "done" },
  { no: 610, title: "Xây Nhà Trọn Gói Gò Vấp", keyword: "xây nhà trọn gói Gò Vấp", slug: "xay-nha-tron-goi-go-vap", status: "done" },
  { no: 611, title: "Xây Nhà Trọn Gói Tân Bình", keyword: "xây nhà trọn gói Tân Bình", slug: "xay-nha-tron-goi-tan-binh", status: "done" },
  { no: 612, title: "Xây Nhà Trọn Gói Bình Tân", keyword: "xây nhà trọn gói Bình Tân", slug: "xay-nha-tron-goi-binh-tan", status: "done" },
  { no: 613, title: "Xây Nhà Trọn Gói Tân Phú", keyword: "xây nhà trọn gói Tân Phú", slug: "xay-nha-tron-goi-tan-phu", status: "done" },
  { no: 614, title: "Xây Nhà Trọn Gói Phú Nhuận", keyword: "xây nhà trọn gói Phú Nhuận", slug: "xay-nha-tron-goi-phu-nhuan", status: "done" },
  { no: 615, title: "Xây Nhà Trọn Gói Hóc Môn", keyword: "xây nhà trọn gói Hóc Môn", slug: "xay-nha-tron-goi-hoc-mon", status: "planned" },
  { no: 616, title: "Xây Nhà Trọn Gói Bình Chánh", keyword: "xây nhà trọn gói Bình Chánh", slug: "xay-nha-tron-goi-binh-chanh", status: "planned" },
  { no: 617, title: "Xây Nhà Trọn Gói Nhà Bè", keyword: "xây nhà trọn gói Nhà Bè", slug: "xay-nha-tron-goi-nha-be", status: "done" },
  { no: 618, title: "Xây Nhà Trọn Gói Củ Chi", keyword: "xây nhà trọn gói Củ Chi", slug: "xay-nha-tron-goi-cu-chi", status: "planned" },

  // —— B. Xây nhà phố + quận/huyện (22) #619–#640 ——
  { no: 619, title: "Xây Nhà Phố Quận 1", keyword: "xây nhà phố Quận 1", slug: "xay-nha-pho-quan-1", status: "planned" },
  { no: 620, title: "Xây Nhà Phố Quận 2", keyword: "xây nhà phố Quận 2", slug: "xay-nha-pho-quan-2", status: "planned" },
  { no: 621, title: "Xây Nhà Phố Quận 3", keyword: "xây nhà phố Quận 3", slug: "xay-nha-pho-quan-3", status: "planned" },
  { no: 622, title: "Xây Nhà Phố Quận 4", keyword: "xây nhà phố Quận 4", slug: "xay-nha-pho-quan-4", status: "planned" },
  { no: 623, title: "Xây Nhà Phố Quận 5", keyword: "xây nhà phố Quận 5", slug: "xay-nha-pho-quan-5", status: "planned" },
  { no: 624, title: "Xây Nhà Phố Quận 6", keyword: "xây nhà phố Quận 6", slug: "xay-nha-pho-quan-6", status: "planned" },
  { no: 625, title: "Xây Nhà Phố Quận 7", keyword: "xây nhà phố Quận 7", slug: "xay-nha-pho-quan-7", status: "planned" },
  { no: 626, title: "Xây Nhà Phố Quận 8", keyword: "xây nhà phố Quận 8", slug: "xay-nha-pho-quan-8", status: "planned" },
  { no: 627, title: "Xây Nhà Phố Quận 10", keyword: "xây nhà phố Quận 10", slug: "xay-nha-pho-quan-10", status: "planned" },
  { no: 628, title: "Xây Nhà Phố Quận 11", keyword: "xây nhà phố Quận 11", slug: "xay-nha-pho-quan-11", status: "planned" },
  { no: 629, title: "Xây Nhà Phố Quận 12", keyword: "xây nhà phố Quận 12", slug: "xay-nha-pho-quan-12", status: "planned" },
  { no: 630, title: "Xây Nhà Phố Bình Thạnh", keyword: "xây nhà phố Bình Thạnh", slug: "xay-nha-pho-binh-thanh-tphcm", status: "planned" },
  { no: 631, title: "Xây Nhà Phố Thủ Đức", keyword: "xây nhà phố Thủ Đức", slug: "xay-nha-pho-thu-duc-tphcm", status: "planned" },
  { no: 632, title: "Xây Nhà Phố Gò Vấp", keyword: "xây nhà phố Gò Vấp", slug: "xay-nha-pho-go-vap", status: "planned" },
  { no: 633, title: "Xây Nhà Phố Tân Bình", keyword: "xây nhà phố Tân Bình", slug: "xay-nha-pho-tan-binh", status: "planned" },
  { no: 634, title: "Xây Nhà Phố Bình Tân", keyword: "xây nhà phố Bình Tân", slug: "xay-nha-pho-binh-tan", status: "planned" },
  { no: 635, title: "Xây Nhà Phố Tân Phú", keyword: "xây nhà phố Tân Phú", slug: "xay-nha-pho-tan-phu", status: "planned" },
  { no: 636, title: "Xây Nhà Phố Phú Nhuận", keyword: "xây nhà phố Phú Nhuận", slug: "xay-nha-pho-phu-nhuan", status: "planned" },
  { no: 637, title: "Xây Nhà Phố Hóc Môn", keyword: "xây nhà phố Hóc Môn", slug: "xay-nha-pho-hoc-mon", status: "planned" },
  { no: 638, title: "Xây Nhà Phố Bình Chánh", keyword: "xây nhà phố Bình Chánh", slug: "xay-nha-pho-binh-chanh", status: "planned" },
  { no: 639, title: "Xây Nhà Phố Nhà Bè", keyword: "xây nhà phố Nhà Bè", slug: "xay-nha-pho-nha-be", status: "planned" },
  { no: 640, title: "Xây Nhà Phố Củ Chi", keyword: "xây nhà phố Củ Chi", slug: "xay-nha-pho-cu-chi", status: "planned" },

  // —— C. Xây nhà + phường/khu (24) #641–#664 ——
  { no: 641, title: "Xây Nhà Phường 25 Bình Thạnh", keyword: "xây nhà Phường 25 Bình Thạnh", slug: "xay-nha-phuong-25-binh-thanh", status: "planned" },
  { no: 642, title: "Xây Nhà Phường 13 Bình Thạnh", keyword: "xây nhà Phường 13 Bình Thạnh", slug: "xay-nha-phuong-13-binh-thanh", status: "planned" },
  { no: 643, title: "Xây Nhà Phường 26 Bình Thạnh", keyword: "xây nhà Phường 26 Bình Thạnh", slug: "xay-nha-phuong-26-binh-thanh", status: "planned" },
  { no: 644, title: "Xây Nhà Phường 15 Tân Bình", keyword: "xây nhà Phường 15 Tân Bình", slug: "xay-nha-phuong-15-tan-binh", status: "planned" },
  { no: 645, title: "Xây Nhà Phường 4 Tân Bình", keyword: "xây nhà Phường 4 Tân Bình", slug: "xay-nha-phuong-4-tan-binh", status: "planned" },
  { no: 646, title: "Xây Nhà Phường 7 Gò Vấp", keyword: "xây nhà Phường 7 Gò Vấp", slug: "xay-nha-phuong-7-go-vap", status: "planned" },
  { no: 647, title: "Xây Nhà Phường 10 Gò Vấp", keyword: "xây nhà Phường 10 Gò Vấp", slug: "xay-nha-phuong-10-go-vap", status: "planned" },
  { no: 648, title: "Xây Nhà Phường 14 Quận 10", keyword: "xây nhà Phường 14 Quận 10", slug: "xay-nha-phuong-14-quan-10", status: "planned" },
  { no: 649, title: "Xây Nhà Phường 15 Quận 10", keyword: "xây nhà Phường 15 Quận 10", slug: "xay-nha-phuong-15-quan-10", status: "planned" },
  { no: 650, title: "Xây Nhà Phường Tân Hưng Quận 7", keyword: "xây nhà Phường Tân Hưng Quận 7", slug: "xay-nha-phuong-tan-hung-quan-7", status: "planned" },
  { no: 651, title: "Xây Nhà Phường Tân Phong Quận 7", keyword: "xây nhà Phường Tân Phong Quận 7", slug: "xay-nha-phuong-tan-phong-quan-7", status: "planned" },
  { no: 652, title: "Xây Nhà Phường An Khánh Quận 2", keyword: "xây nhà Phường An Khánh Quận 2", slug: "xay-nha-phuong-an-khanh-quan-2", status: "planned" },
  { no: 653, title: "Xây Nhà Phường Thảo Điền Quận 2", keyword: "xây nhà Phường Thảo Điền Quận 2", slug: "xay-nha-phuong-thao-dien-quan-2", status: "planned" },
  { no: 654, title: "Xây Nhà Phường Linh Trung Thủ Đức", keyword: "xây nhà Phường Linh Trung Thủ Đức", slug: "xay-nha-phuong-linh-trung-thu-duc", status: "planned" },
  { no: 655, title: "Xây Nhà Phường Hiệp Bình Thủ Đức", keyword: "xây nhà Phường Hiệp Bình Thủ Đức", slug: "xay-nha-phuong-hiep-binh-thu-duc", status: "planned" },
  { no: 656, title: "Xây Nhà Phường Long Phước Thủ Đức", keyword: "xây nhà Phường Long Phước Thủ Đức", slug: "xay-nha-phuong-long-phuoc-thu-duc", status: "planned" },
  { no: 657, title: "Xây Nhà Phường Bình Hưng Hòa Bình Tân", keyword: "xây nhà Phường Bình Hưng Hòa Bình Tân", slug: "xay-nha-phuong-binh-hung-hoa-binh-tan", status: "planned" },
  { no: 658, title: "Xây Nhà Phường An Lạc Bình Tân", keyword: "xây nhà Phường An Lạc Bình Tân", slug: "xay-nha-phuong-an-lac-binh-tan", status: "planned" },
  { no: 659, title: "Xây Nhà Phường Tân Hưng Thuận Quận 12", keyword: "xây nhà Phường Tân Hưng Thuận Quận 12", slug: "xay-nha-phuong-tan-hung-thuan-quan-12", status: "planned" },
  { no: 660, title: "Xây Nhà Phường Hiệp Thành Quận 12", keyword: "xây nhà Phường Hiệp Thành Quận 12", slug: "xay-nha-phuong-hiep-thanh-quan-12", status: "planned" },
  { no: 661, title: "Xây Nhà Phường Tân Sơn Nhì Tân Phú", keyword: "xây nhà Phường Tân Sơn Nhì Tân Phú", slug: "xay-nha-phuong-tan-son-nhi-tan-phu", status: "planned" },
  { no: 662, title: "Xây Nhà Phường Phú Thạnh Tân Phú", keyword: "xây nhà Phường Phú Thạnh Tân Phú", slug: "xay-nha-phuong-phu-thanh-tan-phu", status: "planned" },
  { no: 663, title: "Xây Nhà Phường 5 Quận 8", keyword: "xây nhà Phường 5 Quận 8", slug: "xay-nha-phuong-5-quan-8", status: "planned" },
  { no: 664, title: "Xây Nhà Phường 11 Quận 8", keyword: "xây nhà Phường 11 Quận 8", slug: "xay-nha-phuong-11-quan-8", status: "planned" },

  // —— D. Xây nhà diện tích / tầng (12) #665–#676 ——
  { no: 665, title: "Xây Nhà 4x15 TP.HCM", keyword: "xây nhà 4x15 TP.HCM", slug: "xay-nha-4x15-tphcm", status: "planned" },
  { no: 666, title: "Xây Nhà 5x20 TP.HCM", keyword: "xây nhà 5x20 TP.HCM", slug: "xay-nha-5x20-tphcm", status: "planned" },
  { no: 667, title: "Xây Nhà 4x20 TP.HCM", keyword: "xây nhà 4x20 TP.HCM", slug: "xay-nha-4x20-tphcm", status: "planned" },
  { no: 668, title: "Xây Nhà 3x10 TP.HCM", keyword: "xây nhà 3x10 TP.HCM", slug: "xay-nha-3x10-tphcm", status: "planned" },
  { no: 669, title: "Xây Nhà 100m2 TP.HCM", keyword: "xây nhà 100m2 TP.HCM", slug: "xay-nha-100m2-tphcm", status: "planned" },
  { no: 670, title: "Xây Nhà 120m2 TP.HCM", keyword: "xây nhà 120m2 TP.HCM", slug: "xay-nha-120m2-tphcm", status: "planned" },
  { no: 671, title: "Xây Nhà 150m2 TP.HCM", keyword: "xây nhà 150m2 TP.HCM", slug: "xay-nha-150m2-tphcm", status: "planned" },
  { no: 672, title: "Xây Nhà 200m2 TP.HCM", keyword: "xây nhà 200m2 TP.HCM", slug: "xay-nha-200m2-tphcm", status: "planned" },
  { no: 673, title: "Xây Nhà 7 Tầng TP.HCM", keyword: "xây nhà 7 tầng TP.HCM", slug: "xay-nha-7-tang-tphcm", status: "planned" },
  { no: 674, title: "Xây Nhà 8 Tầng TP.HCM", keyword: "xây nhà 8 tầng TP.HCM", slug: "xay-nha-8-tang-tphcm", status: "planned" },
  { no: 675, title: "Xây Nhà Cấp 3 TP.HCM", keyword: "xây nhà cấp 3 TP.HCM", slug: "xay-nha-cap-3-tphcm", status: "planned" },
  { no: 676, title: "Xây Nhà 2 Tầng Mặt Tiền TP.HCM", keyword: "xây nhà 2 tầng mặt tiền TP.HCM", slug: "xay-nha-2-tang-mat-tien-tphcm", status: "planned" },

  // —— E. Xây nhà loại hình (12) #677–#688 ——
  { no: 677, title: "Xây Nhà Song Lập TP.HCM", keyword: "xây nhà song lập TP.HCM", slug: "xay-nha-song-lap-tphcm", status: "planned" },
  { no: 678, title: "Xây Nhà Duplex TP.HCM", keyword: "xây nhà duplex TP.HCM", slug: "xay-nha-duplex-tphcm", status: "planned" },
  { no: 679, title: "Xây Nhà Có Hồ Bơi TP.HCM", keyword: "xây nhà có hồ bơi TP.HCM", slug: "xay-nha-co-ho-boi-tphcm", status: "planned" },
  { no: 680, title: "Xây Nhà Có Thang Máy TP.HCM", keyword: "xây nhà có thang máy TP.HCM", slug: "xay-nha-co-thang-may-tphcm", status: "planned" },
  { no: 681, title: "Xây Nhà Thương Mại TP.HCM", keyword: "xây nhà thương mại TP.HCM", slug: "xay-nha-thuong-mai-tphcm", status: "planned" },
  { no: 682, title: "Xây Nhà Khu Dân Cư TP.HCM", keyword: "xây nhà khu dân cư TP.HCM", slug: "xay-nha-khu-dan-cu-tphcm", status: "planned" },
  { no: 683, title: "Xây Nhà Đất Nhỏ TP.HCM", keyword: "xây nhà đất nhỏ TP.HCM", slug: "xay-nha-dat-nho-tphcm", status: "planned" },
  { no: 684, title: "Xây Nhà Gác Lửng TP.HCM", keyword: "xây nhà gác lửng TP.HCM", slug: "xay-nha-gac-lung-tphcm", status: "planned" },
  { no: 685, title: "Xây Nhà Cấp 3 Hiện Đại TP.HCM", keyword: "xây nhà cấp 3 hiện đại TP.HCM", slug: "xay-nha-cap-3-hien-dai-tphcm", status: "planned" },
  { no: 686, title: "Xây Nhà Biệt Thự Mini TP.HCM", keyword: "xây nhà biệt thự mini TP.HCM", slug: "xay-nha-biet-thu-mini-tphcm", status: "planned" },
  { no: 687, title: "Xây Nhà 3 Mặt Tiền TP.HCM", keyword: "xây nhà 3 mặt tiền TP.HCM", slug: "xay-nha-3-mat-tien-tphcm", status: "planned" },
  { no: 688, title: "Xây Nhà Đẹp Giá Rẻ TP.HCM", keyword: "xây nhà đẹp giá rẻ TP.HCM", slug: "xay-nha-dep-gia-re-tphcm", status: "planned" },

  // —— F. Xây nhà khu vực / combo ngắn (8) #689–#696 ——
  { no: 689, title: "Xây Nhà Quận 9 Thủ Đức", keyword: "xây nhà Quận 9 Thủ Đức", slug: "xay-nha-quan-9-thu-duc", status: "planned" },
  { no: 690, title: "Xây Nhà KDC Bình Chánh", keyword: "xây nhà KDC Bình Chánh", slug: "xay-nha-kdc-binh-chanh", status: "planned" },
  { no: 691, title: "Xây Nhà KDC Nhà Bè", keyword: "xây nhà KDC Nhà Bè", slug: "xay-nha-kdc-nha-be", status: "planned" },
  { no: 692, title: "Xây Nhà Ven Sông TP.HCM", keyword: "xây nhà ven sông TP.HCM", slug: "xay-nha-ven-song-tphcm", status: "planned" },
  { no: 693, title: "Xây Nhà Nhanh TP.HCM", keyword: "xây nhà nhanh TP.HCM", slug: "xay-nha-nhanh-tphcm", status: "planned" },
  { no: 694, title: "Xây Nhà Tiết Kiệm TP.HCM", keyword: "xây nhà tiết kiệm TP.HCM", slug: "xay-nha-tiet-kiem-tphcm", status: "planned" },
  { no: 695, title: "Xây Nhà Mới TP.HCM", keyword: "xây nhà mới TP.HCM", slug: "xay-nha-moi-tphcm", status: "planned" },
  { no: 696, title: "Xây Nhà Trọn Gói Quận 9", keyword: "xây nhà trọn gói Quận 9", slug: "xay-nha-tron-goi-quan-9", status: "planned" },
];
