/**
 * Lịch 100 từ khóa xây nhà / cải tạo TP.HCM — batch #14 (#797–#896).
 * Slug đối chiếu 740 slug hiện có, không trùng.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const xayCaiTaoTphcmKeywordCalendarBatch9: ContentCalendarItem[] = [
  // —— A. Cải tạo nhà theo phường (20) #797–#816 ——
  { no: 797, title: "Cải Tạo Nhà Phường 25 Bình Thạnh", keyword: "cải tạo nhà Phường 25 Bình Thạnh", slug: "cai-tao-nha-phuong-25-binh-thanh", status: "planned" },
  { no: 798, title: "Cải Tạo Nhà Phường 13 Bình Thạnh", keyword: "cải tạo nhà Phường 13 Bình Thạnh", slug: "cai-tao-nha-phuong-13-binh-thanh", status: "planned" },
  { no: 799, title: "Cải Tạo Nhà Phường 26 Bình Thạnh", keyword: "cải tạo nhà Phường 26 Bình Thạnh", slug: "cai-tao-nha-phuong-26-binh-thanh", status: "planned" },
  { no: 800, title: "Cải Tạo Nhà Phường Thảo Điền Thủ Đức", keyword: "cải tạo nhà Phường Thảo Điền Thủ Đức", slug: "cai-tao-nha-phuong-thao-dien-thu-duc", status: "planned" },
  { no: 801, title: "Cải Tạo Nhà Phường An Phú Thủ Đức", keyword: "cải tạo nhà Phường An Phú Thủ Đức", slug: "cai-tao-nha-phuong-an-phu-thu-duc", status: "planned" },
  { no: 802, title: "Cải Tạo Nhà Phường Hiệp Bình Chánh", keyword: "cải tạo nhà Phường Hiệp Bình Chánh", slug: "cai-tao-nha-phuong-hiep-binh-chanh", status: "planned" },
  { no: 803, title: "Cải Tạo Nhà Phường Linh Trung Thủ Đức", keyword: "cải tạo nhà Phường Linh Trung Thủ Đức", slug: "cai-tao-nha-phuong-linh-trung-thu-duc", status: "planned" },
  { no: 804, title: "Cải Tạo Nhà Phường Long Phước Thủ Đức", keyword: "cải tạo nhà Phường Long Phước Thủ Đức", slug: "cai-tao-nha-phuong-long-phuoc-thu-duc", status: "planned" },
  { no: 805, title: "Cải Tạo Nhà Phường 7 Gò Vấp", keyword: "cải tạo nhà Phường 7 Gò Vấp", slug: "cai-tao-nha-phuong-7-go-vap", status: "planned" },
  { no: 806, title: "Cải Tạo Nhà Phường 10 Gò Vấp", keyword: "cải tạo nhà Phường 10 Gò Vấp", slug: "cai-tao-nha-phuong-10-go-vap", status: "planned" },
  { no: 807, title: "Cải Tạo Nhà Phường 15 Tân Bình", keyword: "cải tạo nhà Phường 15 Tân Bình", slug: "cai-tao-nha-phuong-15-tan-binh", status: "planned" },
  { no: 808, title: "Cải Tạo Nhà Phường 4 Tân Bình", keyword: "cải tạo nhà Phường 4 Tân Bình", slug: "cai-tao-nha-phuong-4-tan-binh", status: "planned" },
  { no: 809, title: "Cải Tạo Nhà Phường Tân Sơn Nhì", keyword: "cải tạo nhà Phường Tân Sơn Nhì", slug: "cai-tao-nha-phuong-tan-son-nhi", status: "planned" },
  { no: 810, title: "Cải Tạo Nhà Phường Phú Thạnh Tân Phú", keyword: "cải tạo nhà Phường Phú Thạnh Tân Phú", slug: "cai-tao-nha-phuong-phu-thanh-tan-phu", status: "planned" },
  { no: 811, title: "Cải Tạo Nhà Phường An Lạc Bình Tân", keyword: "cải tạo nhà Phường An Lạc Bình Tân", slug: "cai-tao-nha-phuong-an-lac-binh-tan", status: "planned" },
  { no: 812, title: "Cải Tạo Nhà Phường Bình Trị Đông", keyword: "cải tạo nhà Phường Bình Trị Đông", slug: "cai-tao-nha-phuong-binh-tri-dong", status: "planned" },
  { no: 813, title: "Cải Tạo Nhà Phường Tân Phong Quận 7", keyword: "cải tạo nhà Phường Tân Phong Quận 7", slug: "cai-tao-nha-phuong-tan-phong-quan-7", status: "planned" },
  { no: 814, title: "Cải Tạo Nhà Phường Tân Hưng Quận 7", keyword: "cải tạo nhà Phường Tân Hưng Quận 7", slug: "cai-tao-nha-phuong-tan-hung-quan-7", status: "planned" },
  { no: 815, title: "Cải Tạo Nhà Phường Hiệp Thành Quận 12", keyword: "cải tạo nhà Phường Hiệp Thành Quận 12", slug: "cai-tao-nha-phuong-hiep-thanh-quan-12", status: "planned" },
  { no: 816, title: "Cải Tạo Nhà Phường Tân Hưng Thuận", keyword: "cải tạo nhà Phường Tân Hưng Thuận", slug: "cai-tao-nha-phuong-tan-hung-thuan", status: "planned" },

  // —— B. Sửa nhà theo phường (20) #817–#836 ——
  { no: 817, title: "Sửa Nhà Phường 25 Bình Thạnh", keyword: "sửa nhà Phường 25 Bình Thạnh", slug: "sua-nha-phuong-25-binh-thanh", status: "planned" },
  { no: 818, title: "Sửa Nhà Phường 13 Bình Thạnh", keyword: "sửa nhà Phường 13 Bình Thạnh", slug: "sua-nha-phuong-13-binh-thanh", status: "planned" },
  { no: 819, title: "Sửa Nhà Phường Thảo Điền", keyword: "sửa nhà Phường Thảo Điền", slug: "sua-nha-phuong-thao-dien", status: "planned" },
  { no: 820, title: "Sửa Nhà Phường An Phú Thủ Đức", keyword: "sửa nhà Phường An Phú Thủ Đức", slug: "sua-nha-phuong-an-phu-thu-duc", status: "planned" },
  { no: 821, title: "Sửa Nhà Phường Linh Trung", keyword: "sửa nhà Phường Linh Trung", slug: "sua-nha-phuong-linh-trung", status: "planned" },
  { no: 822, title: "Sửa Nhà Phường Hiệp Bình Chánh", keyword: "sửa nhà Phường Hiệp Bình Chánh", slug: "sua-nha-phuong-hiep-binh-chanh", status: "planned" },
  { no: 823, title: "Sửa Nhà Phường 7 Gò Vấp", keyword: "sửa nhà Phường 7 Gò Vấp", slug: "sua-nha-phuong-7-go-vap", status: "planned" },
  { no: 824, title: "Sửa Nhà Phường 10 Gò Vấp", keyword: "sửa nhà Phường 10 Gò Vấp", slug: "sua-nha-phuong-10-go-vap", status: "planned" },
  { no: 825, title: "Sửa Nhà Phường 15 Tân Bình", keyword: "sửa nhà Phường 15 Tân Bình", slug: "sua-nha-phuong-15-tan-binh", status: "planned" },
  { no: 826, title: "Sửa Nhà Phường 4 Tân Bình", keyword: "sửa nhà Phường 4 Tân Bình", slug: "sua-nha-phuong-4-tan-binh", status: "planned" },
  { no: 827, title: "Sửa Nhà Phường Tân Sơn Nhì", keyword: "sửa nhà Phường Tân Sơn Nhì", slug: "sua-nha-phuong-tan-son-nhi", status: "planned" },
  { no: 828, title: "Sửa Nhà Phường Phú Thạnh", keyword: "sửa nhà Phường Phú Thạnh", slug: "sua-nha-phuong-phu-thanh", status: "planned" },
  { no: 829, title: "Sửa Nhà Phường An Lạc", keyword: "sửa nhà Phường An Lạc", slug: "sua-nha-phuong-an-lac", status: "planned" },
  { no: 830, title: "Sửa Nhà Phường Bình Hưng Hòa", keyword: "sửa nhà Phường Bình Hưng Hòa", slug: "sua-nha-phuong-binh-hung-hoa", status: "planned" },
  { no: 831, title: "Sửa Nhà Phường Tân Phong Quận 7", keyword: "sửa nhà Phường Tân Phong Quận 7", slug: "sua-nha-phuong-tan-phong-quan-7", status: "planned" },
  { no: 832, title: "Sửa Nhà Phường Tân Hưng Quận 7", keyword: "sửa nhà Phường Tân Hưng Quận 7", slug: "sua-nha-phuong-tan-hung-quan-7", status: "planned" },
  { no: 833, title: "Sửa Nhà Phường Hiệp Thành Quận 12", keyword: "sửa nhà Phường Hiệp Thành Quận 12", slug: "sua-nha-phuong-hiep-thanh-quan-12", status: "planned" },
  { no: 834, title: "Sửa Nhà Phường Tân Hưng Thuận", keyword: "sửa nhà Phường Tân Hưng Thuận", slug: "sua-nha-phuong-tan-hung-thuan", status: "planned" },
  { no: 835, title: "Sửa Nhà Phường 5 Quận 8", keyword: "sửa nhà Phường 5 Quận 8", slug: "sua-nha-phuong-5-quan-8", status: "planned" },
  { no: 836, title: "Sửa Nhà Phường 11 Quận 8", keyword: "sửa nhà Phường 11 Quận 8", slug: "sua-nha-phuong-11-quan-8", status: "planned" },

  // —— C. Xây dựng và cải tạo nhà hẻm (15) #837–#851 ——
  { no: 837, title: "Xây Nhà Hẻm Nhỏ TP.HCM", keyword: "xây nhà hẻm nhỏ TP.HCM", slug: "xay-nha-hem-nho-tphcm", status: "planned" },
  { no: 838, title: "Xây Nhà Hẻm 2m TP.HCM", keyword: "xây nhà hẻm 2m TP.HCM", slug: "xay-nha-hem-2m-tphcm", status: "planned" },
  { no: 839, title: "Xây Nhà Hẻm 3m TP.HCM", keyword: "xây nhà hẻm 3m TP.HCM", slug: "xay-nha-hem-3m-tphcm", status: "planned" },
  { no: 840, title: "Xây Nhà Hẻm 4m TP.HCM", keyword: "xây nhà hẻm 4m TP.HCM", slug: "xay-nha-hem-4m-tphcm", status: "planned" },
  { no: 841, title: "Xây Nhà Hẻm Cụt TP.HCM", keyword: "xây nhà hẻm cụt TP.HCM", slug: "xay-nha-hem-cut-tphcm", status: "planned" },
  { no: 842, title: "Xây Nhà Hẻm Xe Máy TP.HCM", keyword: "xây nhà hẻm xe máy TP.HCM", slug: "xay-nha-hem-xe-may-tphcm", status: "planned" },
  { no: 843, title: "Xây Nhà Hẻm Xe Tải TP.HCM", keyword: "xây nhà hẻm xe tải TP.HCM", slug: "xay-nha-hem-xe-tai-tphcm", status: "planned" },
  { no: 844, title: "Cải Tạo Nhà Trong Hẻm TP.HCM", keyword: "cải tạo nhà trong hẻm TP.HCM", slug: "cai-tao-nha-trong-hem-tphcm", status: "planned" },
  { no: 845, title: "Sửa Nhà Trong Hẻm TP.HCM", keyword: "sửa nhà trong hẻm TP.HCM", slug: "sua-nha-trong-hem-tphcm", status: "planned" },
  { no: 846, title: "Nâng Tầng Nhà Hẻm Nhỏ", keyword: "nâng tầng nhà hẻm nhỏ", slug: "nang-tang-nha-hem-nho-tphcm", status: "planned" },
  { no: 847, title: "Đổ Bê Tông Nhà Trong Hẻm", keyword: "đổ bê tông nhà trong hẻm", slug: "do-be-tong-nha-trong-hem-tphcm", status: "planned" },
  { no: 848, title: "Vận Chuyển Vật Tư Xây Nhà Trong Hẻm", keyword: "vận chuyển vật tư xây nhà trong hẻm", slug: "van-chuyen-vat-tu-xay-nha-trong-hem", status: "planned" },
  { no: 849, title: "Chi Phí Xây Nhà Hẻm Nhỏ", keyword: "chi phí xây nhà hẻm nhỏ", slug: "chi-phi-xay-nha-hem-nho-tphcm", status: "planned" },
  { no: 850, title: "Báo Giá Sửa Nhà Trong Hẻm", keyword: "báo giá sửa nhà trong hẻm", slug: "bao-gia-sua-nha-trong-hem-tphcm", status: "planned" },
  { no: 851, title: "Thi Công Móng Nhà Trong Hẻm", keyword: "thi công móng nhà trong hẻm", slug: "thi-cong-mong-nha-trong-hem-tphcm", status: "planned" },

  // —— D. Cải tạo từng không gian (15) #852–#866 ——
  { no: 852, title: "Cải Tạo Phòng Khách TP.HCM", keyword: "cải tạo phòng khách TP.HCM", slug: "cai-tao-phong-khach-tphcm", status: "planned" },
  { no: 853, title: "Cải Tạo Phòng Ngủ TP.HCM", keyword: "cải tạo phòng ngủ TP.HCM", slug: "cai-tao-phong-ngu-tphcm", status: "planned" },
  { no: 854, title: "Cải Tạo Phòng Bếp TP.HCM", keyword: "cải tạo phòng bếp TP.HCM", slug: "cai-tao-phong-bep-tphcm", status: "planned" },
  { no: 855, title: "Cải Tạo Nhà Vệ Sinh TP.HCM", keyword: "cải tạo nhà vệ sinh TP.HCM", slug: "cai-tao-nha-ve-sinh-tphcm", status: "planned" },
  { no: 856, title: "Cải Tạo Cầu Thang TP.HCM", keyword: "cải tạo cầu thang TP.HCM", slug: "cai-tao-cau-thang-tphcm", status: "planned" },
  { no: 857, title: "Cải Tạo Ban Công TP.HCM", keyword: "cải tạo ban công TP.HCM", slug: "cai-tao-ban-cong-tphcm", status: "planned" },
  { no: 858, title: "Cải Tạo Sân Thượng Thành Phòng", keyword: "cải tạo sân thượng thành phòng", slug: "cai-tao-san-thuong-thanh-phong", status: "planned" },
  { no: 859, title: "Cải Tạo Sân Trước Nhà Phố", keyword: "cải tạo sân trước nhà phố", slug: "cai-tao-san-truoc-nha-pho-tphcm", status: "planned" },
  { no: 860, title: "Cải Tạo Giếng Trời Nhà Phố", keyword: "cải tạo giếng trời nhà phố", slug: "cai-tao-gieng-troi-nha-pho", status: "planned" },
  { no: 861, title: "Cải Tạo Tầng Trệt Nhà Phố", keyword: "cải tạo tầng trệt nhà phố", slug: "cai-tao-tang-tret-nha-pho", status: "planned" },
  { no: 862, title: "Cải Tạo Tầng Lửng TP.HCM", keyword: "cải tạo tầng lửng TP.HCM", slug: "cai-tao-tang-lung-tphcm", status: "planned" },
  { no: 863, title: "Cải Tạo Mái Nhà Phố TP.HCM", keyword: "cải tạo mái nhà phố TP.HCM", slug: "cai-tao-mai-nha-pho-tphcm", status: "planned" },
  { no: 864, title: "Cải Tạo Phòng Thờ TP.HCM", keyword: "cải tạo phòng thờ TP.HCM", slug: "cai-tao-phong-tho-tphcm", status: "planned" },
  { no: 865, title: "Cải Tạo Gara Nhà Phố", keyword: "cải tạo gara nhà phố", slug: "cai-tao-gara-nha-pho-tphcm", status: "planned" },
  { no: 866, title: "Cải Tạo Nhà Có Người Đang Ở", keyword: "cải tạo nhà có người đang ở", slug: "cai-tao-nha-dang-o-tphcm", status: "planned" },

  // —— E. Gia cố và xử lý kết cấu (15) #867–#881 ——
  { no: 867, title: "Gia Cố Móng Nhà Cũ TP.HCM", keyword: "gia cố móng nhà cũ TP.HCM", slug: "gia-co-mong-nha-cu-tphcm", status: "planned" },
  { no: 868, title: "Gia Cố Cột Nhà Cũ TP.HCM", keyword: "gia cố cột nhà cũ TP.HCM", slug: "gia-co-cot-nha-cu-tphcm", status: "planned" },
  { no: 869, title: "Gia Cố Dầm Nhà Cũ TP.HCM", keyword: "gia cố dầm nhà cũ TP.HCM", slug: "gia-co-dam-nha-cu-tphcm", status: "planned" },
  { no: 870, title: "Gia Cố Sàn Nhà Cũ TP.HCM", keyword: "gia cố sàn nhà cũ TP.HCM", slug: "gia-co-san-nha-cu-tphcm", status: "planned" },
  { no: 871, title: "Gia Cố Nhà Trước Khi Nâng Tầng", keyword: "gia cố nhà trước khi nâng tầng", slug: "gia-co-nha-truoc-khi-nang-tang", status: "planned" },
  { no: 872, title: "Xử Lý Nhà Bị Nghiêng TP.HCM", keyword: "xử lý nhà bị nghiêng TP.HCM", slug: "xu-ly-nha-bi-nghieng-tphcm", status: "planned" },
  { no: 873, title: "Xử Lý Nhà Bị Lún TP.HCM", keyword: "xử lý nhà bị lún TP.HCM", slug: "xu-ly-nha-bi-lun-tphcm", status: "planned" },
  { no: 874, title: "Xử Lý Nứt Cột Nhà TP.HCM", keyword: "xử lý nứt cột nhà TP.HCM", slug: "xu-ly-nut-cot-nha-tphcm", status: "planned" },
  { no: 875, title: "Xử Lý Nứt Dầm Nhà TP.HCM", keyword: "xử lý nứt dầm nhà TP.HCM", slug: "xu-ly-nut-dam-nha-tphcm", status: "planned" },
  { no: 876, title: "Xử Lý Nứt Sàn Bê Tông", keyword: "xử lý nứt sàn bê tông", slug: "xu-ly-nut-san-be-tong-tphcm", status: "planned" },
  { no: 877, title: "Thay Mái Nhà Cũ TP.HCM", keyword: "thay mái nhà cũ TP.HCM", slug: "thay-mai-nha-cu-tphcm", status: "planned" },
  { no: 878, title: "Thay Sàn Nhà Cũ TP.HCM", keyword: "thay sàn nhà cũ TP.HCM", slug: "thay-san-nha-cu-tphcm", status: "planned" },
  { no: 879, title: "Thay Cầu Thang Nhà Cũ", keyword: "thay cầu thang nhà cũ", slug: "thay-cau-thang-nha-cu-tphcm", status: "planned" },
  { no: 880, title: "Cấy Thép Nâng Tầng TP.HCM", keyword: "cấy thép nâng tầng TP.HCM", slug: "cay-thep-nang-tang-tphcm", status: "planned" },
  { no: 881, title: "Kiểm Định Kết Cấu Nhà Cũ", keyword: "kiểm định kết cấu nhà cũ", slug: "kiem-dinh-ket-cau-nha-cu-tphcm", status: "planned" },

  // —— F. Pháp lý, chi phí và nhu cầu xây nhà (15) #882–#896 ——
  { no: 882, title: "Xin Phép Sửa Chữa Nhà TP.HCM", keyword: "xin phép sửa chữa nhà TP.HCM", slug: "xin-phep-sua-chua-nha-tphcm", status: "planned" },
  { no: 883, title: "Xin Phép Cải Tạo Nhà TP.HCM", keyword: "xin phép cải tạo nhà TP.HCM", slug: "xin-phep-cai-tao-nha-tphcm", status: "planned" },
  { no: 884, title: "Xin Phép Xây Nhà Trong Hẻm", keyword: "xin phép xây nhà trong hẻm", slug: "xin-phep-xay-nha-trong-hem-tphcm", status: "planned" },
  { no: 885, title: "Hoàn Công Nhà Ở TP.HCM", keyword: "hoàn công nhà ở TP.HCM", slug: "hoan-cong-nha-o-tphcm", status: "planned" },
  { no: 886, title: "Hoàn Công Nhà Xây Sai Phép", keyword: "hoàn công nhà xây sai phép", slug: "hoan-cong-nha-xay-sai-phep-tphcm", status: "planned" },
  { no: 887, title: "Tháo Dỡ Nhà Cũ TP.HCM", keyword: "tháo dỡ nhà cũ TP.HCM", slug: "thao-do-nha-cu-tphcm", status: "planned" },
  { no: 888, title: "Chi Phí Tháo Dỡ Nhà Cũ", keyword: "chi phí tháo dỡ nhà cũ", slug: "chi-phi-thao-do-nha-cu-tphcm", status: "planned" },
  { no: 889, title: "Xây Nhà Ngân Sách 800 Triệu", keyword: "xây nhà ngân sách 800 triệu", slug: "xay-nha-ngan-sach-800-trieu-tphcm", status: "planned" },
  { no: 890, title: "Xây Nhà Ngân Sách 1 Tỷ", keyword: "xây nhà ngân sách 1 tỷ", slug: "xay-nha-ngan-sach-1-ty-tphcm", status: "planned" },
  { no: 891, title: "Xây Nhà Ngân Sách 1,5 Tỷ", keyword: "xây nhà ngân sách 1,5 tỷ", slug: "xay-nha-ngan-sach-1-ty-5-tphcm", status: "planned" },
  { no: 892, title: "Xây Nhà Ngân Sách 2 Tỷ", keyword: "xây nhà ngân sách 2 tỷ", slug: "xay-nha-ngan-sach-2-ty-tphcm", status: "planned" },
  { no: 893, title: "Xây Nhà Cho Gia Đình 3 Thế Hệ", keyword: "xây nhà cho gia đình 3 thế hệ", slug: "xay-nha-cho-gia-dinh-3-the-he", status: "planned" },
  { no: 894, title: "Xây Nhà Kết Hợp Kinh Doanh", keyword: "xây nhà kết hợp kinh doanh", slug: "xay-nha-ket-hop-kinh-doanh-tphcm", status: "planned" },
  { no: 895, title: "Xây Nhà Kết Hợp Văn Phòng", keyword: "xây nhà kết hợp văn phòng", slug: "xay-nha-ket-hop-van-phong-tphcm", status: "planned" },
  { no: 896, title: "Xây Nhà Kết Hợp Cho Thuê", keyword: "xây nhà kết hợp cho thuê", slug: "xay-nha-ket-hop-cho-thue-tphcm", status: "planned" },
];
