/**
 * Lịch 100 từ khóa xây nhà / cải tạo TP.HCM — batch #13 (#697–#796).
 * Slug đã đối chiếu 640 slug hiện có, không trùng.
 * Nhóm: cải tạo theo quận, nâng tầng theo quận, chống thấm theo quận,
 * thiết kế thi công theo quận, sửa nhà theo quận, cải tạo loại hình, xây nhà kiểu/kích thước mới.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const xayCaiTaoTphcmKeywordCalendarBatch8: ContentCalendarItem[] = [
  // —— A. Cải tạo nhà theo quận/huyện (22) #697–#718 ——
  { no: 697, title: "Cải Tạo Nhà Quận 1", keyword: "cải tạo nhà Quận 1", slug: "cai-tao-nha-quan-1", status: "planned" },
  { no: 698, title: "Cải Tạo Nhà Quận 2", keyword: "cải tạo nhà Quận 2", slug: "cai-tao-nha-quan-2", status: "planned" },
  { no: 699, title: "Cải Tạo Nhà Quận 3", keyword: "cải tạo nhà Quận 3", slug: "cai-tao-nha-quan-3", status: "planned" },
  { no: 700, title: "Cải Tạo Nhà Quận 4", keyword: "cải tạo nhà Quận 4", slug: "cai-tao-nha-quan-4", status: "planned" },
  { no: 701, title: "Cải Tạo Nhà Quận 5", keyword: "cải tạo nhà Quận 5", slug: "cai-tao-nha-quan-5", status: "planned" },
  { no: 702, title: "Cải Tạo Nhà Quận 6", keyword: "cải tạo nhà Quận 6", slug: "cai-tao-nha-quan-6", status: "planned" },
  { no: 703, title: "Cải Tạo Nhà Quận 7", keyword: "cải tạo nhà Quận 7", slug: "cai-tao-nha-quan-7", status: "planned" },
  { no: 704, title: "Cải Tạo Nhà Quận 8", keyword: "cải tạo nhà Quận 8", slug: "cai-tao-nha-quan-8", status: "planned" },
  { no: 705, title: "Cải Tạo Nhà Quận 9", keyword: "cải tạo nhà Quận 9", slug: "cai-tao-nha-quan-9", status: "planned" },
  { no: 706, title: "Cải Tạo Nhà Quận 10", keyword: "cải tạo nhà Quận 10", slug: "cai-tao-nha-quan-10", status: "planned" },
  { no: 707, title: "Cải Tạo Nhà Quận 11", keyword: "cải tạo nhà Quận 11", slug: "cai-tao-nha-quan-11", status: "planned" },
  { no: 708, title: "Cải Tạo Nhà Quận 12", keyword: "cải tạo nhà Quận 12", slug: "cai-tao-nha-quan-12", status: "planned" },
  { no: 709, title: "Cải Tạo Nhà Bình Thạnh", keyword: "cải tạo nhà Bình Thạnh", slug: "cai-tao-nha-binh-thanh", status: "planned" },
  { no: 710, title: "Cải Tạo Nhà Thủ Đức", keyword: "cải tạo nhà Thủ Đức", slug: "cai-tao-nha-thu-duc", status: "planned" },
  { no: 711, title: "Cải Tạo Nhà Gò Vấp", keyword: "cải tạo nhà Gò Vấp", slug: "cai-tao-nha-go-vap", status: "planned" },
  { no: 712, title: "Cải Tạo Nhà Tân Bình", keyword: "cải tạo nhà Tân Bình", slug: "cai-tao-nha-tan-binh", status: "planned" },
  { no: 713, title: "Cải Tạo Nhà Bình Tân", keyword: "cải tạo nhà Bình Tân", slug: "cai-tao-nha-binh-tan", status: "planned" },
  { no: 714, title: "Cải Tạo Nhà Tân Phú", keyword: "cải tạo nhà Tân Phú", slug: "cai-tao-nha-tan-phu", status: "planned" },
  { no: 715, title: "Cải Tạo Nhà Phú Nhuận", keyword: "cải tạo nhà Phú Nhuận", slug: "cai-tao-nha-phu-nhuan", status: "planned" },
  { no: 716, title: "Cải Tạo Nhà Hóc Môn", keyword: "cải tạo nhà Hóc Môn", slug: "cai-tao-nha-hoc-mon", status: "planned" },
  { no: 717, title: "Cải Tạo Nhà Bình Chánh", keyword: "cải tạo nhà Bình Chánh", slug: "cai-tao-nha-binh-chanh", status: "planned" },
  { no: 718, title: "Cải Tạo Nhà Nhà Bè", keyword: "cải tạo nhà Nhà Bè", slug: "cai-tao-nha-nha-be", status: "planned" },

  // —— B. Nâng tầng nhà theo quận (15) #719–#733 ——
  { no: 719, title: "Nâng Tầng Nhà Quận 1", keyword: "nâng tầng nhà Quận 1", slug: "nang-tang-nha-quan-1", status: "planned" },
  { no: 720, title: "Nâng Tầng Nhà Quận 3", keyword: "nâng tầng nhà Quận 3", slug: "nang-tang-nha-quan-3", status: "planned" },
  { no: 721, title: "Nâng Tầng Nhà Quận 4", keyword: "nâng tầng nhà Quận 4", slug: "nang-tang-nha-quan-4", status: "planned" },
  { no: 722, title: "Nâng Tầng Nhà Quận 5", keyword: "nâng tầng nhà Quận 5", slug: "nang-tang-nha-quan-5", status: "planned" },
  { no: 723, title: "Nâng Tầng Nhà Quận 6", keyword: "nâng tầng nhà Quận 6", slug: "nang-tang-nha-quan-6", status: "planned" },
  { no: 724, title: "Nâng Tầng Nhà Quận 8", keyword: "nâng tầng nhà Quận 8", slug: "nang-tang-nha-quan-8", status: "planned" },
  { no: 725, title: "Nâng Tầng Nhà Quận 10", keyword: "nâng tầng nhà Quận 10", slug: "nang-tang-nha-quan-10", status: "planned" },
  { no: 726, title: "Nâng Tầng Nhà Quận 11", keyword: "nâng tầng nhà Quận 11", slug: "nang-tang-nha-quan-11", status: "planned" },
  { no: 727, title: "Nâng Tầng Nhà Quận 12", keyword: "nâng tầng nhà Quận 12", slug: "nang-tang-nha-quan-12", status: "planned" },
  { no: 728, title: "Nâng Tầng Nhà Bình Thạnh", keyword: "nâng tầng nhà Bình Thạnh", slug: "nang-tang-nha-binh-thanh", status: "planned" },
  { no: 729, title: "Nâng Tầng Nhà Thủ Đức", keyword: "nâng tầng nhà Thủ Đức", slug: "nang-tang-nha-thu-duc", status: "planned" },
  { no: 730, title: "Nâng Tầng Nhà Gò Vấp", keyword: "nâng tầng nhà Gò Vấp", slug: "nang-tang-nha-go-vap", status: "planned" },
  { no: 731, title: "Nâng Tầng Nhà Tân Bình", keyword: "nâng tầng nhà Tân Bình", slug: "nang-tang-nha-tan-binh", status: "planned" },
  { no: 732, title: "Nâng Tầng Nhà Bình Tân", keyword: "nâng tầng nhà Bình Tân", slug: "nang-tang-nha-binh-tan", status: "planned" },
  { no: 733, title: "Nâng Tầng Nhà Phú Nhuận", keyword: "nâng tầng nhà Phú Nhuận", slug: "nang-tang-nha-phu-nhuan", status: "planned" },

  // —— C. Chống thấm nhà theo quận (12) #734–#745 ——
  { no: 734, title: "Chống Thấm Nhà Quận 1", keyword: "chống thấm nhà Quận 1", slug: "chong-tham-nha-quan-1", status: "planned" },
  { no: 735, title: "Chống Thấm Nhà Quận 2", keyword: "chống thấm nhà Quận 2", slug: "chong-tham-nha-quan-2", status: "planned" },
  { no: 736, title: "Chống Thấm Nhà Quận 7", keyword: "chống thấm nhà Quận 7", slug: "chong-tham-nha-quan-7", status: "planned" },
  { no: 737, title: "Chống Thấm Nhà Quận 8", keyword: "chống thấm nhà Quận 8", slug: "chong-tham-nha-quan-8", status: "planned" },
  { no: 738, title: "Chống Thấm Nhà Quận 9", keyword: "chống thấm nhà Quận 9", slug: "chong-tham-nha-quan-9", status: "planned" },
  { no: 739, title: "Chống Thấm Nhà Quận 12", keyword: "chống thấm nhà Quận 12", slug: "chong-tham-nha-quan-12", status: "planned" },
  { no: 740, title: "Chống Thấm Nhà Bình Thạnh", keyword: "chống thấm nhà Bình Thạnh", slug: "chong-tham-nha-binh-thanh", status: "planned" },
  { no: 741, title: "Chống Thấm Nhà Thủ Đức", keyword: "chống thấm nhà Thủ Đức", slug: "chong-tham-nha-thu-duc", status: "planned" },
  { no: 742, title: "Chống Thấm Nhà Gò Vấp", keyword: "chống thấm nhà Gò Vấp", slug: "chong-tham-nha-go-vap", status: "planned" },
  { no: 743, title: "Chống Thấm Nhà Tân Phú", keyword: "chống thấm nhà Tân Phú", slug: "chong-tham-nha-tan-phu", status: "planned" },
  { no: 744, title: "Chống Thấm Nhà Bình Tân", keyword: "chống thấm nhà Bình Tân", slug: "chong-tham-nha-binh-tan", status: "planned" },
  { no: 745, title: "Chống Thấm Nhà Bình Chánh", keyword: "chống thấm nhà Bình Chánh", slug: "chong-tham-nha-binh-chanh", status: "planned" },

  // —— D. Thiết kế thi công nhà theo quận (15) #746–#760 ——
  { no: 746, title: "Thiết Kế Thi Công Nhà Quận 1", keyword: "thiết kế thi công nhà Quận 1", slug: "thiet-ke-thi-cong-nha-quan-1", status: "planned" },
  { no: 747, title: "Thiết Kế Thi Công Nhà Quận 2", keyword: "thiết kế thi công nhà Quận 2", slug: "thiet-ke-thi-cong-nha-quan-2", status: "planned" },
  { no: 748, title: "Thiết Kế Thi Công Nhà Quận 3", keyword: "thiết kế thi công nhà Quận 3", slug: "thiet-ke-thi-cong-nha-quan-3", status: "planned" },
  { no: 749, title: "Thiết Kế Thi Công Nhà Quận 7", keyword: "thiết kế thi công nhà Quận 7", slug: "thiet-ke-thi-cong-nha-quan-7", status: "planned" },
  { no: 750, title: "Thiết Kế Thi Công Nhà Quận 9", keyword: "thiết kế thi công nhà Quận 9", slug: "thiet-ke-thi-cong-nha-quan-9", status: "planned" },
  { no: 751, title: "Thiết Kế Thi Công Nhà Quận 10", keyword: "thiết kế thi công nhà Quận 10", slug: "thiet-ke-thi-cong-nha-quan-10", status: "planned" },
  { no: 752, title: "Thiết Kế Thi Công Nhà Quận 12", keyword: "thiết kế thi công nhà Quận 12", slug: "thiet-ke-thi-cong-nha-quan-12", status: "planned" },
  { no: 753, title: "Thiết Kế Thi Công Nhà Bình Thạnh", keyword: "thiết kế thi công nhà Bình Thạnh", slug: "thiet-ke-thi-cong-nha-binh-thanh", status: "planned" },
  { no: 754, title: "Thiết Kế Thi Công Nhà Thủ Đức", keyword: "thiết kế thi công nhà Thủ Đức", slug: "thiet-ke-thi-cong-nha-thu-duc", status: "planned" },
  { no: 755, title: "Thiết Kế Thi Công Nhà Gò Vấp", keyword: "thiết kế thi công nhà Gò Vấp", slug: "thiet-ke-thi-cong-nha-go-vap", status: "planned" },
  { no: 756, title: "Thiết Kế Thi Công Nhà Tân Bình", keyword: "thiết kế thi công nhà Tân Bình", slug: "thiet-ke-thi-cong-nha-tan-binh", status: "planned" },
  { no: 757, title: "Thiết Kế Thi Công Nhà Tân Phú", keyword: "thiết kế thi công nhà Tân Phú", slug: "thiet-ke-thi-cong-nha-tan-phu", status: "planned" },
  { no: 758, title: "Thiết Kế Thi Công Nhà Bình Tân", keyword: "thiết kế thi công nhà Bình Tân", slug: "thiet-ke-thi-cong-nha-binh-tan", status: "planned" },
  { no: 759, title: "Thiết Kế Thi Công Nhà Hóc Môn", keyword: "thiết kế thi công nhà Hóc Môn", slug: "thiet-ke-thi-cong-nha-hoc-mon", status: "planned" },
  { no: 760, title: "Thiết Kế Thi Công Nhà Bình Chánh", keyword: "thiết kế thi công nhà Bình Chánh", slug: "thiet-ke-thi-cong-nha-binh-chanh", status: "planned" },

  // —— E. Sửa nhà theo quận (12) #761–#772 ——
  { no: 761, title: "Sửa Nhà Quận 1", keyword: "sửa nhà Quận 1", slug: "sua-nha-quan-1", status: "planned" },
  { no: 762, title: "Sửa Nhà Quận 2", keyword: "sửa nhà Quận 2", slug: "sua-nha-quan-2", status: "planned" },
  { no: 763, title: "Sửa Nhà Quận 7", keyword: "sửa nhà Quận 7", slug: "sua-nha-quan-7", status: "planned" },
  { no: 764, title: "Sửa Nhà Quận 8", keyword: "sửa nhà Quận 8", slug: "sua-nha-quan-8", status: "planned" },
  { no: 765, title: "Sửa Nhà Quận 10", keyword: "sửa nhà Quận 10", slug: "sua-nha-quan-10", status: "planned" },
  { no: 766, title: "Sửa Nhà Quận 12", keyword: "sửa nhà Quận 12", slug: "sua-nha-quan-12", status: "planned" },
  { no: 767, title: "Sửa Nhà Bình Thạnh", keyword: "sửa nhà Bình Thạnh", slug: "sua-nha-binh-thanh", status: "planned" },
  { no: 768, title: "Sửa Nhà Thủ Đức", keyword: "sửa nhà Thủ Đức", slug: "sua-nha-thu-duc", status: "planned" },
  { no: 769, title: "Sửa Nhà Gò Vấp", keyword: "sửa nhà Gò Vấp", slug: "sua-nha-go-vap", status: "planned" },
  { no: 770, title: "Sửa Nhà Tân Bình", keyword: "sửa nhà Tân Bình", slug: "sua-nha-tan-binh", status: "planned" },
  { no: 771, title: "Sửa Nhà Tân Phú", keyword: "sửa nhà Tân Phú", slug: "sua-nha-tan-phu", status: "planned" },
  { no: 772, title: "Sửa Nhà Bình Tân", keyword: "sửa nhà Bình Tân", slug: "sua-nha-binh-tan", status: "planned" },

  // —— F. Cải tạo loại hình công trình (8) #773–#780 ——
  { no: 773, title: "Cải Tạo Chung Cư TP.HCM", keyword: "cải tạo chung cư TP.HCM", slug: "cai-tao-chung-cu-tphcm", status: "planned" },
  { no: 774, title: "Cải Tạo Căn Hộ TP.HCM", keyword: "cải tạo căn hộ TP.HCM", slug: "cai-tao-can-ho-tphcm", status: "planned" },
  { no: 775, title: "Cải Tạo Nhà Cấp 4 TP.HCM", keyword: "cải tạo nhà cấp 4 TP.HCM", slug: "cai-tao-nha-cap-4-tphcm", status: "planned" },
  { no: 776, title: "Cải Tạo Nhà 2 Tầng TP.HCM", keyword: "cải tạo nhà 2 tầng TP.HCM", slug: "cai-tao-nha-2-tang-tphcm", status: "planned" },
  { no: 777, title: "Cải Tạo Nhà 3 Tầng TP.HCM", keyword: "cải tạo nhà 3 tầng TP.HCM", slug: "cai-tao-nha-3-tang-tphcm", status: "planned" },
  { no: 778, title: "Cải Tạo Biệt Thự TP.HCM", keyword: "cải tạo biệt thự TP.HCM", slug: "cai-tao-biet-thu-tphcm", status: "planned" },
  { no: 779, title: "Cải Tạo Văn Phòng TP.HCM", keyword: "cải tạo văn phòng TP.HCM", slug: "cai-tao-van-phong-tphcm", status: "planned" },
  { no: 780, title: "Cải Tạo Quán Cafe TP.HCM", keyword: "cải tạo quán cafe TP.HCM", slug: "cai-tao-quan-cafe-tphcm", status: "planned" },

  // —— G. Xây nhà kiểu dáng / kích thước mới (16) #781–#796 ——
  { no: 781, title: "Xây Nhà 4x16 TP.HCM", keyword: "xây nhà 4x16 TP.HCM", slug: "xay-nha-4x16-tphcm", status: "planned" },
  { no: 782, title: "Xây Nhà 5x15 TP.HCM", keyword: "xây nhà 5x15 TP.HCM", slug: "xay-nha-5x15-tphcm", status: "planned" },
  { no: 783, title: "Xây Nhà 6x15 TP.HCM", keyword: "xây nhà 6x15 TP.HCM", slug: "xay-nha-6x15-tphcm", status: "planned" },
  { no: 784, title: "Xây Nhà 4x12 TP.HCM", keyword: "xây nhà 4x12 TP.HCM", slug: "xay-nha-4x12-tphcm", status: "planned" },
  { no: 785, title: "Xây Nhà 80m2 TP.HCM", keyword: "xây nhà 80m2 TP.HCM", slug: "xay-nha-80m2-tphcm", status: "planned" },
  { no: 786, title: "Xây Nhà 60m2 TP.HCM", keyword: "xây nhà 60m2 TP.HCM", slug: "xay-nha-60m2-tphcm", status: "planned" },
  { no: 787, title: "Xây Nhà 250m2 TP.HCM", keyword: "xây nhà 250m2 TP.HCM", slug: "xay-nha-250m2-tphcm", status: "planned" },
  { no: 788, title: "Xây Nhà 9 Tầng TP.HCM", keyword: "xây nhà 9 tầng TP.HCM", slug: "xay-nha-9-tang-tphcm", status: "planned" },
  { no: 789, title: "Xây Nhà Sân Vườn TP.HCM", keyword: "xây nhà sân vườn TP.HCM", slug: "xay-nha-san-vuon-tphcm", status: "planned" },
  { no: 790, title: "Xây Nhà Thông Tầng TP.HCM", keyword: "xây nhà thông tầng TP.HCM", slug: "xay-nha-thong-tang-tphcm", status: "planned" },
  { no: 791, title: "Xây Nhà Lệch Tầng TP.HCM", keyword: "xây nhà lệch tầng TP.HCM", slug: "xay-nha-lech-tang-tphcm", status: "planned" },
  { no: 792, title: "Xây Nhà Mái Thái TP.HCM", keyword: "xây nhà mái thái TP.HCM", slug: "xay-nha-mai-thai-tphcm", status: "planned" },
  { no: 793, title: "Xây Nhà Mái Bằng TP.HCM", keyword: "xây nhà mái bằng TP.HCM", slug: "xay-nha-mai-bang-tphcm", status: "planned" },
  { no: 794, title: "Xây Nhà Tân Cổ Điển TP.HCM", keyword: "xây nhà tân cổ điển TP.HCM", slug: "xay-nha-tan-co-dien-tphcm", status: "planned" },
  { no: 795, title: "Xây Nhà Hiện Đại TP.HCM", keyword: "xây nhà hiện đại TP.HCM", slug: "xay-nha-hien-dai-tphcm", status: "planned" },
  { no: 796, title: "Xây Nhà 2 Mặt Tiền TP.HCM", keyword: "xây nhà 2 mặt tiền TP.HCM", slug: "xay-nha-2-mat-tien-tphcm", status: "planned" },
];
