// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/appearance-management/AppearanceManagement.tsx": () => import("../components/mockups/appearance-management/AppearanceManagement.tsx"),
  "./components/mockups/cms-dashboard/Dashboard.tsx": () => import("../components/mockups/cms-dashboard/Dashboard.tsx"),
  "./components/mockups/cms-login/Login.tsx": () => import("../components/mockups/cms-login/Login.tsx"),
  "./components/mockups/image-library/ImageLibrary.tsx": () => import("../components/mockups/image-library/ImageLibrary.tsx"),
  "./components/mockups/news-management/NewsManagement.tsx": () => import("../components/mockups/news-management/NewsManagement.tsx"),
  "./components/mockups/product-management/ProductManagement.tsx": () => import("../components/mockups/product-management/ProductManagement.tsx"),
  "./components/mockups/service-management/ServiceManagement.tsx": () => import("../components/mockups/service-management/ServiceManagement.tsx"),
  "./components/mockups/settings/Settings.tsx": () => import("../components/mockups/settings/Settings.tsx"),
};
