/**
 * Generator: short-keyword batches 55–59 (500 articles, #4947–#5446).
 * Run: npx tsx scripts/gen-short-keyword-batches-55-59.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${55 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${55 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${55 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 55 — phòng chức năng sâu / công năng sống
  const b55 = pairs([
    ["Phòng Khách Liên Thông Bếp", "phòng khách liên thông bếp", "phong-khach-lien-thong-bep-cn"],
    ["Phòng Khách Có Giếng Trời", "phòng khách có giếng trời", "phong-khach-co-gieng-troi-cn"],
    ["Phòng Khách Thông Tầng", "phòng khách thông tầng", "phong-khach-thong-tang-cn"],
    ["Phòng Khách Nhà Hẹp", "phòng khách nhà hẹp", "phong-khach-nha-hep-cn"],
    ["Phòng Ngủ Master Có WC", "phòng ngủ master có wc", "phong-ngu-master-co-wc-cn"],
    ["Phòng Ngủ Master Có Walk In", "phòng ngủ master có walk in", "phong-ngu-master-co-walk-in-cn"],
    ["Phòng Ngủ Master Có Ban Công", "phòng ngủ master có ban công", "phong-ngu-master-co-ban-cong-cn"],
    ["Phòng Ngủ Trẻ Em 2 Bé", "phòng ngủ trẻ em 2 bé", "phong-ngu-tre-em-2-be-cn"],
    ["Phòng Ngủ Teen", "phòng ngủ teen", "phong-ngu-teen-cn"],
    ["Phòng Ngủ Ông Bà Tầng Trệt", "phòng ngủ ông bà tầng trệt", "phong-ngu-ong-ba-tang-tret-cn"],
    ["Phòng Ngủ Khách", "phòng ngủ khách", "phong-ngu-khach-cn"],
    ["Phòng Bếp Mở", "phòng bếp mở", "phong-bep-mo-cn"],
    ["Phòng Bếp Đóng", "phòng bếp đóng", "phong-bep-dong-cn"],
    ["Phòng Bếp Có Bàn Ăn", "phòng bếp có bàn ăn", "phong-bep-co-ban-an-cn"],
    ["Phòng Bếp Có Đảo Bếp", "phòng bếp có đảo bếp", "phong-bep-co-dao-bep-cn"],
    ["Phòng Bếp Có Pantry", "phòng bếp có pantry", "phong-bep-co-pantry-cn"],
    ["Phòng Ăn Riêng", "phòng ăn riêng", "phong-an-rieng-cn"],
    ["Phòng Ăn Kết Hợp Khách", "phòng ăn kết hợp khách", "phong-an-ket-hop-khach-cn"],
    ["WC Khách Tầng Trệt", "wc khách tầng trệt", "wc-khach-tang-tret-cn"],
    ["WC Chung Tầng Lầu", "wc chung tầng lầu", "wc-chung-tang-lau-cn"],
    ["WC Master En Suite", "wc master en suite", "wc-master-en-suite-cn"],
    ["WC Có Bồn Tắm", "wc có bồn tắm", "wc-co-bon-tam-cn"],
    ["WC Có Cabin Tắm", "wc có cabin tắm", "wc-co-cabin-tam-cn"],
    ["Phòng Giặt Riêng", "phòng giặt riêng", "phong-giat-rieng-cn"],
    ["Phòng Giặt Kết Hợp Phơi", "phòng giặt kết hợp phơi", "phong-giat-ket-hop-phoi-cn"],
    ["Khu Phơi Đồ Sân Thượng", "khu phơi đồ sân thượng", "khu-phoi-do-san-thuong-cn"],
    ["Phòng Thờ Tầng Trệt", "phòng thờ tầng trệt", "phong-tho-tang-tret-cn"],
    ["Phòng Thờ Tầng Thượng", "phòng thờ tầng thượng", "phong-tho-tang-thuong-cn"],
    ["Phòng Thờ Riêng Biệt", "phòng thờ riêng biệt", "phong-tho-rieng-biet-cn"],
    ["Phòng Làm Việc Tại Nhà", "phòng làm việc tại nhà", "phong-lam-viec-tai-nha-cn"],
    ["Góc Làm Việc Phòng Ngủ", "góc làm việc phòng ngủ", "goc-lam-viec-phong-ngu-cn"],
    ["Phòng Giải Trí Gia Đình", "phòng giải trí gia đình", "phong-giai-tri-gia-dinh-cn"],
    ["Phòng Karaoke Cách Âm", "phòng karaoke cách âm", "phong-karaoke-cach-am-cn"],
    ["Phòng Gym Mini Nhà", "phòng gym mini nhà", "phong-gym-mini-nha-cn"],
    ["Phòng Yoga Tại Nhà", "phòng yoga tại nhà", "phong-yoga-tai-nha-cn"],
    ["Phòng Đọc Sách", "phòng đọc sách", "phong-doc-sach-cn"],
    ["Phòng Chơi Trẻ Em CN", "phòng chơi trẻ em", "phong-choi-tre-em-cn"],
    ["Phòng Kho Đồ Dưới Cầu Thang", "phòng kho đồ dưới cầu thang", "phong-kho-do-duoi-cau-thang-cn"],
    ["Phòng Kho Tầng Hầm", "phòng kho tầng hầm", "phong-kho-tang-ham-cn"],
    ["Hầm Để Xe 1 Ô Tô", "hầm để xe 1 ô tô", "ham-de-xe-1-o-to-cn"],
    ["Hầm Để Xe 2 Ô Tô", "hầm để xe 2 ô tô", "ham-de-xe-2-o-to-cn"],
    ["Sân Để Xe Máy Tầng Trệt", "sân để xe máy tầng trệt", "san-de-xe-may-tang-tret-cn"],
    ["Garage Riêng Nhà Phố", "garage riêng nhà phố", "garage-rieng-nha-pho-cn"],
    ["Sảnh Đón Nhà Phố", "sảnh đón nhà phố", "sanh-don-nha-pho-cn"],
    ["Hành Lang Thông Tầng", "hành lang thông tầng", "hanh-lang-thong-tang-cn"],
    ["Hành Lang Bên Hông", "hành lang bên hông", "hanh-lang-ben-hong-cn"],
    ["Gác Lửng Phòng Khách", "gác lửng phòng khách", "gac-lung-phong-khach-cn"],
    ["Gác Lửng Phòng Ngủ", "gác lửng phòng ngủ", "gac-lung-phong-ngu-cn"],
    ["Gác Lửng Kho Đồ", "gác lửng kho đồ", "gac-lung-kho-do-cn"],
    ["Ban Công Phòng Ngủ", "ban công phòng ngủ", "ban-cong-phong-ngu-cn"],
    ["Ban Công Phòng Khách", "ban công phòng khách", "ban-cong-phong-khach-cn"],
    ["Logia Phơi Đồ", "logia phơi đồ", "logia-phoi-do-cn"],
    ["Sân Thượng Làm Vườn", "sân thượng làm vườn", "san-thuong-lam-vuon-cn"],
    ["Sân Thượng Tiếp Khách", "sân thượng tiếp khách", "san-thuong-tiep-khach-cn"],
    ["Sân Thượng Có Bếp Nướng", "sân thượng có bếp nướng", "san-thuong-co-bep-nuong-cn"],
    ["Sân Trước Tiếp Khách", "sân trước tiếp khách", "san-truoc-tiep-khach-cn"],
    ["Sân Sau Giặt Phơi", "sân sau giặt phơi", "san-sau-giat-phoi-cn"],
    ["Giếng Trời Giữa Nhà", "giếng trời giữa nhà", "gieng-troi-giua-nha-cn"],
    ["Giếng Trời Cuối Nhà", "giếng trời cuối nhà", "gieng-troi-cuoi-nha-cn"],
    ["Giếng Trời Bên Hông", "giếng trời bên hông", "gieng-troi-ben-hong-cn"],
    ["Cầu Thang Giữa Nhà", "cầu thang giữa nhà", "cau-thang-giua-nha-cn"],
    ["Cầu Thang Bên Hông", "cầu thang bên hông", "cau-thang-ben-hong-cn"],
    ["Cầu Thang Cuối Nhà", "cầu thang cuối nhà", "cau-thang-cuoi-nha-cn"],
    ["Cầu Thang Xoắn Tiết Kiệm", "cầu thang xoắn tiết kiệm", "cau-thang-xoan-tiet-kiem-cn"],
    ["Cầu Thang Thẳng Nhà Hẹp", "cầu thang thẳng nhà hẹp", "cau-thang-thang-nha-hep-cn"],
    ["Không Gian Đa Năng", "không gian đa năng", "khong-gian-da-nang-cn"],
    ["Phòng Đa Năng Biến Đổi", "phòng đa năng biến đổi", "phong-da-nang-bien-doi-cn"],
    ["Vách Ngăn Di Động", "vách ngăn di động", "vach-ngan-di-dong-cn"],
    ["Nội Thất Gấp Gọn CN", "nội thất gấp gọn", "noi-that-gap-gon-cn"],
    ["Tối Ưu Công Năng Nhà 40m2", "tối ưu công năng nhà 40m2", "toi-uu-cong-nang-nha-40m2-cn"],
    ["Tối Ưu Công Năng Nhà 50m2", "tối ưu công năng nhà 50m2", "toi-uu-cong-nang-nha-50m2-cn"],
    ["Tối Ưu Công Năng Nhà 60m2", "tối ưu công năng nhà 60m2", "toi-uu-cong-nang-nha-60m2-cn"],
    ["Tối Ưu Công Năng Nhà 80m2", "tối ưu công năng nhà 80m2", "toi-uu-cong-nang-nha-80m2-cn"],
    ["Layout Nhà 3 Phòng Ngủ", "layout nhà 3 phòng ngủ", "layout-nha-3-phong-ngu-cn"],
    ["Layout Nhà 4 Phòng Ngủ", "layout nhà 4 phòng ngủ", "layout-nha-4-phong-ngu-cn"],
    ["Layout Nhà 5 Phòng Ngủ", "layout nhà 5 phòng ngủ", "layout-nha-5-phong-ngu-cn"],
    ["Layout Shop House Tầng Trệt", "layout shop house tầng trệt", "layout-shop-house-tang-tret-cn"],
    ["Layout Nhà Ở Kết Hợp VP", "layout nhà ở kết hợp vp", "layout-nha-o-ket-hop-vp-cn"],
    ["Flow Di Chuyển Trong Nhà", "flow di chuyển trong nhà", "flow-di-chuyen-trong-nha-cn"],
    ["Vùng Ướt Vùng Khô", "vùng ướt vùng khô", "vung-uot-vung-kho-cn"],
    ["Vùng Công Cộng Riêng Tư", "vùng công cộng riêng tư", "vung-cong-cong-rieng-tu-cn"],
    ["Ánh Sáng Phòng Khách", "ánh sáng phòng khách", "anh-sang-phong-khach-cn"],
    ["Ánh Sáng Phòng Ngủ", "ánh sáng phòng ngủ", "anh-sang-phong-ngu-cn"],
    ["Ánh Sáng Phòng Bếp", "ánh sáng phòng bếp", "anh-sang-phong-bep-cn"],
    ["Thông Gió Phòng WC", "thông gió phòng wc", "thong-gio-phong-wc-cn"],
    ["Thông Gió Phòng Bếp CN", "thông gió phòng bếp", "thong-gio-phong-bep-cn"],
    ["Cách Âm Phòng Ngủ", "cách âm phòng ngủ", "cach-am-phong-ngu-cn"],
    ["Cách Âm Phòng Karaoke CN", "cách âm phòng karaoke", "cach-am-phong-karaoke-cn"],
    ["Báo Giá Thiết Kế Công Năng", "báo giá thiết kế công năng", "bao-gia-thiet-ke-cong-nang-cn"],
    ["Tư Vấn Layout Nhà Phố", "tư vấn layout nhà phố", "tu-van-layout-nha-pho-cn"],
    ["Sai Lầm Layout Thường Gặp", "sai lầm layout thường gặp", "sai-lam-layout-thuong-gap-cn"],
    ["Checklist Công Năng Nhà Ở", "checklist công năng nhà ở", "checklist-cong-nang-nha-o-cn"],
    ["Xu Hướng Layout 2026", "xu hướng layout 2026", "xu-huong-layout-2026-cn"],
    ["Nhà Đa Thế Hệ Layout", "nhà đa thế hệ layout", "nha-da-the-he-layout-cn"],
    ["Nhà Cho Người Khuyết Tật", "nhà cho người khuyết tật", "nha-cho-nguoi-khuyet-tat-cn"],
    ["Nhà Universal Design", "nhà universal design", "nha-universal-design-cn"],
  ]);

  // 56 — chống thấm / mái / thoát nước chuyên sâu
  const b56 = pairs([
    ["Chống Thấm Sân Thượng CT", "chống thấm sân thượng", "chong-tham-san-thuong-ct"],
    ["Chống Thấm Mái BTCT CT", "chống thấm mái btct", "chong-tham-mai-btct-ct"],
    ["Chống Thấm Mái Tôn CT", "chống thấm mái tôn", "chong-tham-mai-ton-ct"],
    ["Chống Thấm Mái Ngói CT", "chống thấm mái ngói", "chong-tham-mai-ngoi-ct"],
    ["Chống Thấm Tường Ngoài CT", "chống thấm tường ngoài", "chong-tham-tuong-ngoai-ct"],
    ["Chống Thấm Tường Trong CT", "chống thấm tường trong", "chong-tham-tuong-trong-ct"],
    ["Chống Thấm Sàn WC CT", "chống thấm sàn wc", "chong-tham-san-wc-ct"],
    ["Chống Thấm Sàn Bếp CT", "chống thấm sàn bếp", "chong-tham-san-bep-ct"],
    ["Chống Thấm Ban Công CT", "chống thấm ban công", "chong-tham-ban-cong-ct"],
    ["Chống Thấm Logia CT", "chống thấm logia", "chong-tham-logia-ct"],
    ["Chống Thấm Hầm Xe CT", "chống thấm hầm xe", "chong-tham-ham-xe-ct"],
    ["Chống Thấm Bể Nước CT", "chống thấm bể nước", "chong-tham-be-nuoc-ct"],
    ["Chống Thấm Bể Bơi CT", "chống thấm bể bơi", "chong-tham-be-boi-ct"],
    ["Chống Thấm Cổ Ống CT", "chống thấm cổ ống", "chong-tham-co-ong-ct"],
    ["Chống Thấm Mạch Ngừng CT", "chống thấm mạch ngừng", "chong-tham-mach-ngung-ct"],
    ["Chống Thấm Khe Co Giãn CT", "chống thấm khe co giãn", "chong-tham-khe-co-gian-ct"],
    ["Chống Thấm Gốc Xi Măng CT", "chống thấm gốc xi măng", "chong-tham-goc-xi-mang-ct"],
    ["Chống Thấm Gốc Bitum CT", "chống thấm gốc bitum", "chong-tham-goc-bitum-ct"],
    ["Chống Thấm Gốc Polyurethane", "chống thấm gốc polyurethane", "chong-tham-goc-pu-ct"],
    ["Chống Thấm Gốc Acrylic CT", "chống thấm gốc acrylic", "chong-tham-goc-acrylic-ct"],
    ["Màng Khò Nóng CT", "màng khò nóng chống thấm", "mang-kho-nong-ct"],
    ["Màng Tự Dính CT", "màng tự dính chống thấm", "mang-tu-dinh-ct"],
    ["Vải Không Dệt Chống Thấm", "vải không dệt chống thấm", "vai-khong-det-chong-tham-ct"],
    ["Sơn Chống Thấm Đàn Hồi", "sơn chống thấm đàn hồi", "son-chong-tham-dan-hoi-ct"],
    ["Keo Bơm Vết Nứt CT", "keo bơm vết nứt", "keo-bom-vet-nut-ct"],
    ["Xử Lý Thấm Trần Nhà", "xử lý thấm trần nhà", "xu-ly-tham-tran-nha-ct"],
    ["Xử Lý Thấm Tường Mưa", "xử lý thấm tường mưa", "xu-ly-tham-tuong-mua-ct"],
    ["Xử Lý Thấm Sàn WC CT", "xử lý thấm sàn wc", "xu-ly-tham-san-wc-ct"],
    ["Xử Lý Thấm Cổ Ống CT", "xử lý thấm cổ ống", "xu-ly-tham-co-ong-ct"],
    ["Xử Lý Thấm Mái Tôn CT", "xử lý thấm mái tôn", "xu-ly-tham-mai-ton-ct"],
    ["Ngâm Nước Nghiệm Thu CT", "ngâm nước nghiệm thu chống thấm", "ngam-nuoc-nghiem-thu-ct"],
    ["Thời Gian Ngâm Nước CT", "thời gian ngâm nước chống thấm", "thoi-gian-ngam-nuoc-ct"],
    ["Quy Trình Chống Thấm CT", "quy trình chống thấm", "quy-trinh-chong-tham-ct"],
    ["Chuẩn Bị Bề Mặt Chống Thấm", "chuẩn bị bề mặt chống thấm", "chuan-bi-be-mat-chong-tham-ct"],
    ["Số Lớp Chống Thấm Đạt", "số lớp chống thấm đạt", "so-lop-chong-tham-dat-ct"],
    ["Bảo Dưỡng Sau Chống Thấm", "bảo dưỡng sau chống thấm", "bao-duong-sau-chong-tham-ct"],
    ["Thoát Nước Sân Thượng CT", "thoát nước sân thượng", "thoat-nuoc-san-thuong-ct"],
    ["Thoát Nước Mái Tôn CT", "thoát nước mái tôn", "thoat-nuoc-mai-ton-ct"],
    ["Thoát Nước Ban Công CT", "thoát nước ban công", "thoat-nuoc-ban-cong-ct"],
    ["Thoát Nước Mặt Tiền CT", "thoát nước mặt tiền", "thoat-nuoc-mat-tien-ct"],
    ["Ống Xuống Nước Mưa CT", "ống xuống nước mưa", "ong-xuong-nuoc-mua-ct"],
    ["Phễu Thu Nước Mái CT", "phễu thu nước mái", "pheu-thu-nuoc-mai-ct"],
    ["Rãnh Thoát Nước Sân CT", "rãnh thoát nước sân", "ranh-thoat-nuoc-san-ct"],
    ["Độ Dốc Thoát Nước CT", "độ dốc thoát nước", "do-doc-thoat-nuoc-ct"],
    ["Chống Ùn Tắc Thoát Nước", "chống ùn tắc thoát nước", "chong-un-tac-thoat-nuoc-ct"],
    ["Lọc Rác Phễu Thu CT", "lọc rác phễu thu", "loc-rac-pheu-thu-ct"],
    ["Cách Nhiệt Mái Tôn CT", "cách nhiệt mái tôn", "cach-nhiet-mai-ton-ct"],
    ["Cách Nhiệt Mái BTCT CT", "cách nhiệt mái btct", "cach-nhiet-mai-btct-ct"],
    ["Tấm Cách Nhiệt Mái CT", "tấm cách nhiệt mái", "tam-cach-nhiet-mai-ct"],
    ["Sơn Chống Nóng Mái CT", "sơn chống nóng mái", "son-chong-nong-mai-ct"],
    ["Trần Giả Cách Nhiệt CT", "trần giả cách nhiệt", "tran-gia-cach-nhiet-ct"],
    ["Lợp Mái Tôn 2 Lớp CT", "lợp mái tôn 2 lớp", "lop-mai-ton-2-lop-ct"],
    ["Lợp Mái Tôn 3 Lớp CT", "lợp mái tôn 3 lớp", "lop-mai-ton-3-lop-ct"],
    ["Xà Gồ Mái Tôn CT", "xà gồ mái tôn", "xa-go-mai-ton-ct"],
    ["Kèo Thép Mái Tôn CT", "kèo thép mái tôn", "keo-thep-mai-ton-ct"],
    ["Diềm Mái Tôn CT", "diềm mái tôn", "diem-mai-ton-ct"],
    ["Úp Nóc Mái Tôn CT", "úp nóc mái tôn", "up-noc-mai-ton-ct"],
    ["Lợp Ngói Nhật CT", "lợp ngói nhật", "lop-ngoi-nhat-ct"],
    ["Lợp Ngói Thái CT", "lợp ngói thái", "lop-ngoi-thai-ct"],
    ["Cầu Phong Mái Ngói CT", "cầu phong mái ngói", "cau-phong-mai-ngoi-ct"],
    ["Màng Chống Thấm Dưới Ngói", "màng chống thấm dưới ngói", "mang-chong-tham-duoi-ngoi-ct"],
    ["Báo Giá Chống Thấm m2 CT", "báo giá chống thấm m2", "bao-gia-chong-tham-m2-ct"],
    ["Báo Giá Chống Thấm Sân Thượng", "báo giá chống thấm sân thượng", "bao-gia-chong-tham-san-thuong-ct"],
    ["Báo Giá Chống Thấm WC CT", "báo giá chống thấm wc", "bao-gia-chong-tham-wc-ct"],
    ["Báo Giá Lợp Mái Tôn CT", "báo giá lợp mái tôn", "bao-gia-lop-mai-ton-ct"],
    ["Báo Giá Lợp Mái Ngói CT", "báo giá lợp mái ngói", "bao-gia-lop-mai-ngoi-ct"],
    ["Chi Phí Sửa Mái Dột CT", "chi phí sửa mái dột", "chi-phi-sua-mai-dot-ct"],
    ["Chi Phí Thay Mái Tôn CT", "chi phí thay mái tôn", "chi-phi-thay-mai-ton-ct"],
    ["Bảo Hành Chống Thấm CT", "bảo hành chống thấm", "bao-hanh-chong-tham-ct"],
    ["Bảo Hành Mái Tôn CT", "bảo hành mái tôn", "bao-hanh-mai-ton-ct"],
    ["Checklist Chống Thấm CT", "checklist chống thấm", "checklist-chong-tham-ct"],
    ["Checklist Nghiệm Thu Mái CT", "checklist nghiệm thu mái", "checklist-nghiem-thu-mai-ct"],
    ["Lỗi Chống Thấm Thường Gặp", "lỗi chống thấm thường gặp", "loi-chong-tham-thuong-gap-ct"],
    ["Vì Sao Chống Thấm Thất Bại", "vì sao chống thấm thất bại", "vi-sao-chong-tham-that-bai-ct"],
    ["Chọn Đơn Vị Chống Thấm", "chọn đơn vị chống thấm", "chon-don-vi-chong-tham-ct"],
    ["Chống Thấm Trước Ốp Lát", "chống thấm trước ốp lát", "chong-tham-truoc-op-lat-ct"],
    ["Chống Thấm Sau Ốp Lát", "chống thấm sau ốp lát", "chong-tham-sau-op-lat-ct"],
    ["Chống Thấm Mùa Mưa CT", "chống thấm mùa mưa", "chong-tham-mua-mua-ct"],
    ["Chống Thấm Khẩn Cấp CT", "chống thấm khẩn cấp", "chong-tham-khan-cap-ct"],
    ["Dịch Vụ Chống Thấm TPHCM CT", "dịch vụ chống thấm tphcm", "dich-vu-chong-tham-tphcm-ct"],
    ["Thợ Chống Thấm Uy Tín CT", "thợ chống thấm uy tín", "tho-chong-tham-uy-tin-ct"],
    ["Xu Hướng Chống Thấm 2026", "xu hướng chống thấm 2026", "xu-huong-chong-tham-2026-ct"],
    ["Vật Liệu Chống Thấm Mới", "vật liệu chống thấm mới", "vat-lieu-chong-tham-moi-ct"],
    ["Chống Thấm Xanh CT", "chống thấm xanh", "chong-tham-xanh-ct"],
    ["Thu Gom Nước Mưa Từ Mái", "thu gom nước mưa từ mái", "thu-gom-nuoc-mua-tu-mai-ct"],
  ]);

  // 57 — geo Thủ Đức / khu vực mới TPHCM sâu
  const b57 = pairs([
    ["Xây Nhà Linh Xuân", "xây nhà Linh Xuân", "xay-nha-linh-xuan-td"],
    ["Xây Nhà Linh Trung", "xây nhà Linh Trung", "xay-nha-linh-trung-td"],
    ["Xây Nhà Linh Chiểu", "xây nhà Linh Chiểu", "xay-nha-linh-chieu-td"],
    ["Xây Nhà Linh Tây", "xây nhà Linh Tây", "xay-nha-linh-tay-td"],
    ["Xây Nhà Linh Đông", "xây nhà Linh Đông", "xay-nha-linh-dong-td"],
    ["Xây Nhà Trường Thọ", "xây nhà Trường Thọ", "xay-nha-truong-tho-td"],
    ["Xây Nhà Bình Chiểu", "xây nhà Bình Chiểu", "xay-nha-binh-chieu-td"],
    ["Xây Nhà Hiệp Bình Chánh", "xây nhà Hiệp Bình Chánh", "xay-nha-hiep-binh-chanh-td"],
    ["Xây Nhà Hiệp Bình Phước", "xây nhà Hiệp Bình Phước", "xay-nha-hiep-binh-phuoc-td"],
    ["Xây Nhà Tam Bình TD", "xây nhà Tam Bình Thủ Đức", "xay-nha-tam-binh-td"],
    ["Xây Nhà Tam Phú", "xây nhà Tam Phú", "xay-nha-tam-phu-td"],
    ["Xây Nhà Thủ Thiêm", "xây nhà Thủ Thiêm", "xay-nha-thu-thiem-td"],
    ["Xây Nhà An Khánh TD", "xây nhà An Khánh Thủ Đức", "xay-nha-an-khanh-td"],
    ["Xây Nhà An Lợi Đông", "xây nhà An Lợi Đông", "xay-nha-an-loi-dong-td"],
    ["Xây Nhà Bình Trưng Đông", "xây nhà Bình Trưng Đông", "xay-nha-binh-trung-dong-td"],
    ["Xây Nhà Bình Trưng Tây", "xây nhà Bình Trưng Tây", "xay-nha-binh-trung-tay-td"],
    ["Xây Nhà Cát Lái", "xây nhà Cát Lái", "xay-nha-cat-lai-td"],
    ["Xây Nhà Thạnh Mỹ Lợi", "xây nhà Thạnh Mỹ Lợi", "xay-nha-thanh-my-loi-td"],
    ["Xây Nhà Phước Long A", "xây nhà Phước Long A", "xay-nha-phuoc-long-a-td"],
    ["Xây Nhà Phước Long B", "xây nhà Phước Long B", "xay-nha-phuoc-long-b-td"],
    ["Xây Nhà Tăng Nhơn Phú A", "xây nhà Tăng Nhơn Phú A", "xay-nha-tang-nhon-phu-a-td"],
    ["Xây Nhà Tăng Nhơn Phú B", "xây nhà Tăng Nhơn Phú B", "xay-nha-tang-nhon-phu-b-td"],
    ["Xây Nhà Long Trường", "xây nhà Long Trường", "xay-nha-long-truong-td"],
    ["Xây Nhà Long Phước TD", "xây nhà Long Phước Thủ Đức", "xay-nha-long-phuoc-td"],
    ["Xây Nhà Trường Thạnh", "xây nhà Trường Thạnh", "xay-nha-truong-thanh-td"],
    ["Xây Nhà Phú Hữu", "xây nhà Phú Hữu", "xay-nha-phu-huu-td"],
    ["Xây Nhà Hiệp Phú", "xây nhà Hiệp Phú", "xay-nha-hiep-phu-td"],
    ["Xây Nhà Tân Phú TD", "xây nhà Tân Phú Thủ Đức", "xay-nha-tan-phu-td"],
    ["Xây Nhà Long Bình TD", "xây nhà Long Bình Thủ Đức", "xay-nha-long-binh-td"],
    ["Xây Nhà Long Thạnh Mỹ", "xây nhà Long Thạnh Mỹ", "xay-nha-long-thanh-my-td"],
    ["Xây Nhà Gần ĐHQG", "xây nhà gần ĐHQG", "xay-nha-gan-dhqg-td"],
    ["Xây Nhà Gần Suối Tiên", "xây nhà gần Suối Tiên", "xay-nha-gan-suoi-tien-td"],
    ["Xây Nhà Gần Vincom Thủ Đức", "xây nhà gần Vincom Thủ Đức", "xay-nha-gan-vincom-thu-duc-td"],
    ["Xây Nhà Gần Ga Metro Bình Thái", "xây nhà gần ga metro Bình Thái", "xay-nha-gan-metro-binh-thai-td"],
    ["Xây Nhà Gần Ga Metro Thủ Đức", "xây nhà gần ga metro Thủ Đức", "xay-nha-gan-metro-thu-duc-td"],
    ["Xây Nhà Gần Xa Lộ Hà Nội", "xây nhà gần Xa lộ Hà Nội", "xay-nha-gan-xa-lo-ha-noi-td"],
    ["Xây Nhà Gần Phạm Văn Đồng", "xây nhà gần Phạm Văn Đồng", "xay-nha-gan-pham-van-dong-td"],
    ["Xây Nhà Gần Võ Nguyên Giáp", "xây nhà gần Võ Nguyên Giáp", "xay-nha-gan-vo-nguyen-giap-td"],
    ["Xây Nhà Gần Nguyễn Duy Trinh", "xây nhà gần Nguyễn Duy Trinh", "xay-nha-gan-nguyen-duy-trinh-td"],
    ["Xây Nhà Gần Đồng Văn Cống", "xây nhà gần Đồng Văn Cống", "xay-nha-gan-dong-van-cong-td"],
    ["Cải Tạo Nhà Linh Xuân", "cải tạo nhà Linh Xuân", "cai-tao-nha-linh-xuan-td"],
    ["Cải Tạo Nhà Hiệp Bình Chánh", "cải tạo nhà Hiệp Bình Chánh", "cai-tao-nha-hiep-binh-chanh-td"],
    ["Cải Tạo Nhà Cát Lái", "cải tạo nhà Cát Lái", "cai-tao-nha-cat-lai-td"],
    ["Cải Tạo Nhà Phước Long", "cải tạo nhà Phước Long", "cai-tao-nha-phuoc-long-td"],
    ["Cải Tạo Nhà Tăng Nhơn Phú", "cải tạo nhà Tăng Nhơn Phú", "cai-tao-nha-tang-nhon-phu-td"],
    ["Cải Tạo Nhà Thủ Thiêm", "cải tạo nhà Thủ Thiêm", "cai-tao-nha-thu-thiem-td"],
    ["Thiết Kế Nhà Linh Trung", "thiết kế nhà Linh Trung", "thiet-ke-nha-linh-trung-td"],
    ["Thiết Kế Nhà Hiệp Bình Phước", "thiết kế nhà Hiệp Bình Phước", "thiet-ke-nha-hiep-binh-phuoc-td"],
    ["Thiết Kế Nhà Cát Lái", "thiết kế nhà Cát Lái", "thiet-ke-nha-cat-lai-td"],
    ["Thiết Kế Nhà Phước Long A", "thiết kế nhà Phước Long A", "thiet-ke-nha-phuoc-long-a-td"],
    ["Thiết Kế Nhà Thủ Thiêm", "thiết kế nhà Thủ Thiêm", "thiet-ke-nha-thu-thiem-td"],
    ["Báo Giá Xây Nhà Thủ Đức TD", "báo giá xây nhà Thủ Đức", "bao-gia-xay-nha-thu-duc-td"],
    ["Báo Giá Xây Nhà Linh Xuân", "báo giá xây nhà Linh Xuân", "bao-gia-xay-nha-linh-xuan-td"],
    ["Báo Giá Xây Nhà Cát Lái", "báo giá xây nhà Cát Lái", "bao-gia-xay-nha-cat-lai-td"],
    ["Báo Giá Xây Nhà Hiệp Bình", "báo giá xây nhà Hiệp Bình", "bao-gia-xay-nha-hiep-binh-td"],
    ["Báo Giá Cải Tạo Thủ Đức", "báo giá cải tạo Thủ Đức", "bao-gia-cai-tao-thu-duc-td"],
    ["Nhà Thầu Thủ Đức TD", "nhà thầu Thủ Đức", "nha-thau-thu-duc-td"],
    ["Nhà Thầu Linh Xuân", "nhà thầu Linh Xuân", "nha-thau-linh-xuan-td"],
    ["Nhà Thầu Cát Lái", "nhà thầu Cát Lái", "nha-thau-cat-lai-td"],
    ["Nhà Thầu Hiệp Bình Chánh", "nhà thầu Hiệp Bình Chánh", "nha-thau-hiep-binh-chanh-td"],
    ["Nhà Thầu Phước Long", "nhà thầu Phước Long", "nha-thau-phuoc-long-td"],
    ["Xây Nhà Phố Thủ Đức", "xây nhà phố Thủ Đức", "xay-nha-pho-thu-duc-td"],
    ["Xây Nhà Ống Thủ Đức", "xây nhà ống Thủ Đức", "xay-nha-ong-thu-duc-td"],
    ["Xây Biệt Thự Thủ Đức", "xây biệt thự Thủ Đức", "xay-biet-thu-thu-duc-td"],
    ["Xây Nhà Vườn Thủ Đức", "xây nhà vườn Thủ Đức", "xay-nha-vuon-thu-duc-td"],
    ["Xây Nhà Trọ Thủ Đức", "xây nhà trọ Thủ Đức", "xay-nha-tro-thu-duc-td"],
    ["Xin Phép Xây Nhà Thủ Đức", "xin phép xây nhà Thủ Đức", "xin-phep-xay-nha-thu-duc-td"],
    ["Đơn Giá Xây Nhà Thủ Đức", "đơn giá xây nhà Thủ Đức", "don-gia-xay-nha-thu-duc-td"],
    ["Xây Nhà KĐT Vinhomes Grand Park", "xây nhà gần Vinhomes Grand Park", "xay-nha-gan-vinhomes-grand-park-td"],
    ["Xây Nhà KĐT Sala", "xây nhà gần Sala", "xay-nha-gan-sala-td"],
    ["Xây Nhà KĐT Thủ Thiêm", "xây nhà gần Thủ Thiêm", "xay-nha-gan-thu-thiem-kdt-td"],
    ["Xây Nhà Gần ĐHSPKT", "xây nhà gần ĐH SPKT", "xay-nha-gan-dhspkt-td"],
    ["Xây Nhà Gần ĐH Nông Lâm", "xây nhà gần ĐH Nông Lâm", "xay-nha-gan-dh-nong-lam-td"],
    ["Xây Nhà Gần Khu CNC", "xây nhà gần khu CNC", "xay-nha-gan-khu-cnc-td"],
    ["Xây Nhà Gần Sài Gòn Zoo", "xây nhà gần Thảo Cầm Viên mới", "xay-nha-gan-thao-cam-vien-moi-td"],
    ["Cải Tạo Mặt Tiền Thủ Đức", "cải tạo mặt tiền Thủ Đức", "cai-tao-mat-tien-thu-duc-td"],
    ["Nâng Tầng Nhà Thủ Đức", "nâng tầng nhà Thủ Đức", "nang-tang-nha-thu-duc-td"],
    ["Sửa Nhà Thủ Đức", "sửa nhà Thủ Đức", "sua-nha-thu-duc-td"],
    ["Chống Thấm Nhà Thủ Đức", "chống thấm nhà Thủ Đức", "chong-tham-nha-thu-duc-td"],
    ["Thiết Kế Nội Thất Thủ Đức", "thiết kế nội thất Thủ Đức", "thiet-ke-noi-that-thu-duc-td"],
    ["Xây Nhà An Phú Đông", "xây nhà An Phú Đông", "xay-nha-an-phu-dong-td"],
    ["Xây Nhà Thạnh Xuân", "xây nhà Thạnh Xuân", "xay-nha-thanh-xuan-q12"],
    ["Xây Nhà Thới An", "xây nhà Thới An", "xay-nha-thoi-an-q12"],
    ["Xây Nhà Trung Mỹ Tây", "xây nhà Trung Mỹ Tây", "xay-nha-trung-my-tay-q12"],
    ["Xây Nhà Tân Chánh Hiệp", "xây nhà Tân Chánh Hiệp", "xay-nha-tan-chanh-hiep-q12"],
    ["Xây Nhà Tân Thới Hiệp", "xây nhà Tân Thới Hiệp", "xay-nha-tan-thoi-hiep-q12"],
    ["Xây Nhà Đông Hưng Thuận", "xây nhà Đông Hưng Thuận", "xay-nha-dong-hung-thuan-q12"],
    ["Xây Nhà Tân Hưng Thuận", "xây nhà Tân Hưng Thuận", "xay-nha-tan-hung-thuan-q12"],
    ["Xây Nhà Hiệp Thành Q12", "xây nhà Hiệp Thành Q12", "xay-nha-hiep-thanh-q12"],
    ["Xây Nhà Thạnh Lộc Q12", "xây nhà Thạnh Lộc Q12", "xay-nha-thanh-loc-q12"],
    ["Xây Nhà An Phú Đông Q12", "xây nhà An Phú Đông Q12", "xay-nha-an-phu-dong-q12"],
    ["Nhà Thầu Quận 12", "nhà thầu Quận 12", "nha-thau-quan-12-td"],
    ["Báo Giá Xây Nhà Quận 12", "báo giá xây nhà Quận 12", "bao-gia-xay-nha-quan-12-td"],
    ["Cải Tạo Nhà Quận 12", "cải tạo nhà Quận 12", "cai-tao-nha-quan-12-td"],
  ]);

  // 58 — phong thủy / hướng nhà / tuổi xây
  const b58 = pairs([
    ["Hướng Nhà Đông Tốt Không", "hướng nhà đông tốt không", "huong-nha-dong-tot-khong-pt"],
    ["Hướng Nhà Tây Tốt Không", "hướng nhà tây tốt không", "huong-nha-tay-tot-khong-pt"],
    ["Hướng Nhà Nam Tốt Không", "hướng nhà nam tốt không", "huong-nha-nam-tot-khong-pt"],
    ["Hướng Nhà Bắc Tốt Không", "hướng nhà bắc tốt không", "huong-nha-bac-tot-khong-pt"],
    ["Hướng Đông Nam Nhà Phố", "hướng đông nam nhà phố", "huong-dong-nam-nha-pho-pt"],
    ["Hướng Tây Nam Nhà Phố", "hướng tây nam nhà phố", "huong-tay-nam-nha-pho-pt"],
    ["Hướng Đông Bắc Nhà Phố", "hướng đông bắc nhà phố", "huong-dong-bac-nha-pho-pt"],
    ["Hướng Tây Bắc Nhà Phố", "hướng tây bắc nhà phố", "huong-tay-bac-nha-pho-pt"],
    ["Chọn Hướng Nhà Theo Tuổi", "chọn hướng nhà theo tuổi", "chon-huong-nha-theo-tuoi-pt"],
    ["Hướng Nhà Tuổi Tý", "hướng nhà tuổi tý", "huong-nha-tuoi-ty-pt"],
    ["Hướng Nhà Tuổi Sửu", "hướng nhà tuổi sửu", "huong-nha-tuoi-suu-pt"],
    ["Hướng Nhà Tuổi Dần", "hướng nhà tuổi dần", "huong-nha-tuoi-dan-pt"],
    ["Hướng Nhà Tuổi Mão", "hướng nhà tuổi mão", "huong-nha-tuoi-mao-pt"],
    ["Hướng Nhà Tuổi Thìn", "hướng nhà tuổi thìn", "huong-nha-tuoi-thin-pt"],
    ["Hướng Nhà Tuổi Tỵ", "hướng nhà tuổi tỵ", "huong-nha-tuoi-ty-ran-pt"],
    ["Hướng Nhà Tuổi Ngọ", "hướng nhà tuổi ngọ", "huong-nha-tuoi-ngo-pt"],
    ["Hướng Nhà Tuổi Mùi", "hướng nhà tuổi mùi", "huong-nha-tuoi-mui-pt"],
    ["Hướng Nhà Tuổi Thân", "hướng nhà tuổi thân", "huong-nha-tuoi-than-pt"],
    ["Hướng Nhà Tuổi Dậu", "hướng nhà tuổi dậu", "huong-nha-tuoi-dau-pt"],
    ["Hướng Nhà Tuổi Tuất", "hướng nhà tuổi tuất", "huong-nha-tuoi-tuat-pt"],
    ["Hướng Nhà Tuổi Hợi", "hướng nhà tuổi hợi", "huong-nha-tuoi-hoi-pt"],
    ["Năm Xây Nhà 2026", "năm xây nhà 2026", "nam-xay-nha-2026-pt"],
    ["Tuổi Xây Nhà 2026", "tuổi xây nhà 2026", "tuoi-xay-nha-2026-pt"],
    ["Tuổi Phạm Thái Tuế 2026", "tuổi phạm thái tuế 2026", "tuoi-pham-thai-tue-2026-pt"],
    ["Cải Tạo Có Phạm Tuổi Không", "cải tạo có phạm tuổi không", "cai-tao-co-pham-tuoi-khong-pt"],
    ["Mượn Tuổi Xây Nhà", "mượn tuổi xây nhà", "muon-tuoi-xay-nha-pt"],
    ["Cách Mượn Tuổi Xây", "cách mượn tuổi xây", "cach-muon-tuoi-xay-pt"],
    ["Ngày Động Thổ Tốt", "ngày động thổ tốt", "ngay-dong-tho-tot-pt"],
    ["Ngày Đổ Móng Tốt", "ngày đổ móng tốt", "ngay-do-mong-tot-pt"],
    ["Ngày Lợp Mái Tốt", "ngày lợp mái tốt", "ngay-lop-mai-tot-pt"],
    ["Ngày Nhập Trạch Tốt", "ngày nhập trạch tốt", "ngay-nhap-trach-tot-pt"],
    ["Lễ Động Thổ Xây Nhà", "lễ động thổ xây nhà", "le-dong-tho-xay-nha-pt"],
    ["Lễ Cất Nóc Xây Nhà", "lễ cất nóc xây nhà", "le-cat-noc-xay-nha-pt"],
    ["Lễ Nhập Trạch Nhà Mới", "lễ nhập trạch nhà mới", "le-nhap-trach-nha-moi-pt"],
    ["Bài Trí Phòng Thờ Phong Thủy", "bài trí phòng thờ phong thủy", "bai-tri-phong-tho-phong-thuy-pt"],
    ["Hướng Bàn Thờ Đúng", "hướng bàn thờ đúng", "huong-ban-tho-dung-pt"],
    ["Vị Trí Bếp Phong Thủy PT", "vị trí bếp phong thủy", "vi-tri-bep-phong-thuy-pt"],
    ["Bếp Không Đối Cửa", "bếp không đối cửa", "bep-khong-doi-cua-pt"],
    ["WC Không Đối Cửa Chính", "wc không đối cửa chính", "wc-khong-doi-cua-chinh-pt"],
    ["Giường Ngủ Phong Thủy", "giường ngủ phong thủy", "giuong-ngu-phong-thuy-pt"],
    ["Cửa Chính Phong Thủy PT", "cửa chính phong thủy", "cua-chinh-phong-thuy-pt"],
    ["Cầu Thang Phong Thủy", "cầu thang phong thủy", "cau-thang-phong-thuy-pt"],
    ["Giếng Trời Phong Thủy", "giếng trời phong thủy", "gieng-troi-phong-thuy-pt"],
    ["Gương Phong Thủy Nhà", "gương phong thủy nhà", "guong-phong-thuy-nha-pt"],
    ["Cây Phong Thủy Trong Nhà", "cây phong thủy trong nhà", "cay-phong-thuy-trong-nha-pt"],
    ["Màu Sơn Theo Mệnh PT", "màu sơn theo mệnh", "mau-son-theo-menh-pt"],
    ["Màu Sơn Mệnh Kim PT", "màu sơn mệnh kim", "mau-son-menh-kim-pt"],
    ["Màu Sơn Mệnh Mộc PT", "màu sơn mệnh mộc", "mau-son-menh-moc-pt"],
    ["Màu Sơn Mệnh Thủy PT", "màu sơn mệnh thủy", "mau-son-menh-thuy-pt"],
    ["Màu Sơn Mệnh Hỏa PT", "màu sơn mệnh hỏa", "mau-son-menh-hoa-pt"],
    ["Màu Sơn Mệnh Thổ PT", "màu sơn mệnh thổ", "mau-son-menh-tho-pt"],
    ["Số Tầng Nhà Phong Thủy", "số tầng nhà phong thủy", "so-tang-nha-phong-thuy-pt"],
    ["Số Phòng Ngủ Phong Thủy", "số phòng ngủ phong thủy", "so-phong-ngu-phong-thuy-pt"],
    ["Hình Dáng Nhà Phong Thủy", "hình dáng nhà phong thủy", "hinh-dang-nha-phong-thuy-pt"],
    ["Nhà Lô Đất Tam Giác", "nhà lô đất tam giác", "nha-lo-dat-tam-giac-pt"],
    ["Nhà Lô Đất Chữ L", "nhà lô đất chữ l", "nha-lo-dat-chu-l-pt"],
    ["Nhà Lô Đất Méo", "nhà lô đất méo", "nha-lo-dat-meo-pt"],
    ["Đất Đầu Hẻm Phong Thủy", "đất đầu hẻm phong thủy", "dat-dau-hem-phong-thuy-pt"],
    ["Đất Cuối Hẻm Phong Thủy", "đất cuối hẻm phong thủy", "dat-cuoi-hem-phong-thuy-pt"],
    ["Đất Gần Chùa Phong Thủy", "đất gần chùa phong thủy", "dat-gan-chua-phong-thuy-pt"],
    ["Đất Gần Nghĩa Trang", "đất gần nghĩa trang", "dat-gan-nghia-trang-pt"],
    ["Đất Gần Điện Cao Thế", "đất gần điện cao thế", "dat-gan-dien-cao-the-pt"],
    ["Hóa Giải Phong Thủy Nhà", "hóa giải phong thủy nhà", "hoa-giai-phong-thuy-nha-pt"],
    ["Hóa Giải Nhà Hướng Xấu", "hóa giải nhà hướng xấu", "hoa-giai-nha-huong-xau-pt"],
    ["Hóa Giải WC Đối Cửa", "hóa giải wc đối cửa", "hoa-giai-wc-doi-cua-pt"],
    ["Hóa Giải Cột Giữa Nhà", "hóa giải cột giữa nhà", "hoa-giai-cot-giua-nha-pt"],
    ["Hóa Giải Xà Đà Phòng Ngủ", "hóa giải xà đà phòng ngủ", "hoa-giai-xa-da-phong-ngu-pt"],
    ["Tư Vấn Phong Thủy Xây Nhà", "tư vấn phong thủy xây nhà", "tu-van-phong-thuy-xay-nha-pt"],
    ["Kiến Trúc Sư Hiểu Phong Thủy", "kiến trúc sư hiểu phong thủy", "kien-truc-su-hieu-phong-thuy-pt"],
    ["Thiết Kế Nhà Hợp Phong Thủy", "thiết kế nhà hợp phong thủy", "thiet-ke-nha-hop-phong-thuy-pt"],
    ["Cân Bằng Phong Thủy Và Công Năng", "cân bằng phong thủy và công năng", "can-bang-phong-thuy-va-cong-nang-pt"],
    ["Phong Thủy Hiện Đại", "phong thủy hiện đại", "phong-thuy-hien-dai-pt"],
    ["Phong Thủy Nhà Ống", "phong thủy nhà ống", "phong-thuy-nha-ong-pt"],
    ["Phong Thủy Nhà Phố Hẹp", "phong thủy nhà phố hẹp", "phong-thuy-nha-pho-hep-pt"],
    ["Phong Thủy Biệt Thự", "phong thủy biệt thự", "phong-thuy-biet-thu-pt"],
    ["Ngũ Hành Trong Nhà Ở", "ngũ hành trong nhà ở", "ngu-hanh-trong-nha-o-pt"],
    ["Khí Trong Nhà Phong Thủy", "khí trong nhà phong thủy", "khi-trong-nha-phong-thuy-pt"],
    ["Minh Đường Nhà Phố", "minh đường nhà phố", "minh-duong-nha-pho-pt"],
    ["Huyền Vũ Nhà Phố", "huyền vũ nhà phố", "huyen-vu-nha-pho-pt"],
    ["Thanh Long Bạch Hổ", "thanh long bạch hổ", "thanh-long-bach-ho-pt"],
    ["Checklist Phong Thủy Trước Xây", "checklist phong thủy trước xây", "checklist-phong-thuy-truoc-xay-pt"],
    ["Sai Lầm Phong Thủy Xây Nhà", "sai lầm phong thủy xây nhà", "sai-lam-phong-thuy-xay-nha-pt"],
    ["Myth Phong Thủy Xây Nhà", "myth phong thủy xây nhà", "myth-phong-thuy-xay-nha-pt"],
  ]);

  // 59 — content cluster / seasonal / Ads remarketing
  const b59 = pairs([
    ["Xây Nhà Tháng 1 2026", "xây nhà tháng 1 2026", "xay-nha-thang-1-2026-ads5"],
    ["Xây Nhà Tháng 2 2026", "xây nhà tháng 2 2026", "xay-nha-thang-2-2026-ads5"],
    ["Xây Nhà Tháng 3 2026", "xây nhà tháng 3 2026", "xay-nha-thang-3-2026-ads5"],
    ["Xây Nhà Tháng 4 2026", "xây nhà tháng 4 2026", "xay-nha-thang-4-2026-ads5"],
    ["Xây Nhà Tháng 5 2026", "xây nhà tháng 5 2026", "xay-nha-thang-5-2026-ads5"],
    ["Xây Nhà Tháng 6 2026", "xây nhà tháng 6 2026", "xay-nha-thang-6-2026-ads5"],
    ["Xây Nhà Tháng 7 2026", "xây nhà tháng 7 2026", "xay-nha-thang-7-2026-ads5"],
    ["Xây Nhà Tháng 8 2026", "xây nhà tháng 8 2026", "xay-nha-thang-8-2026-ads5"],
    ["Xây Nhà Tháng 9 2026", "xây nhà tháng 9 2026", "xay-nha-thang-9-2026-ads5"],
    ["Xây Nhà Tháng 10 2026", "xây nhà tháng 10 2026", "xay-nha-thang-10-2026-ads5"],
    ["Xây Nhà Tháng 11 2026", "xây nhà tháng 11 2026", "xay-nha-thang-11-2026-ads5"],
    ["Xây Nhà Tháng 12 2026", "xây nhà tháng 12 2026", "xay-nha-thang-12-2026-ads5"],
    ["Cải Tạo Tháng Này", "cải tạo tháng này", "cai-tao-thang-nay-ads5"],
    ["Ưu Đãi Xây Nhà Tuần Này", "ưu đãi xây nhà tuần này", "uu-dai-xay-nha-tuan-nay-ads5"],
    ["Flash Deal Cải Tạo", "flash deal cải tạo", "flash-deal-cai-tao-ads5"],
    ["Weekend Survey Miễn Phí", "weekend survey miễn phí", "weekend-survey-mien-phi-ads5"],
    ["Nhắc Lại Báo Giá Xây", "nhắc lại báo giá xây", "nhac-lai-bao-gia-xay-ads5"],
    ["Bạn Đã Xem Báo Giá Chưa", "bạn đã xem báo giá chưa", "ban-da-xem-bao-gia-chua-ads5"],
    ["Vẫn Còn Quan Tâm Xây Nhà", "vẫn còn quan tâm xây nhà", "van-con-quan-tam-xay-nha-ads5"],
    ["Hoàn Tất Đăng Ký Tư Vấn", "hoàn tất đăng ký tư vấn", "hoan-tat-dang-ky-tu-van-ads5"],
    ["Tiếp Tục Quy Trình Xây", "tiếp tục quy trình xây", "tiep-tuc-quy-trinh-xay-ads5"],
    ["Khách Hàng Quay Lại Sao Khuê", "khách hàng quay lại sao khuê", "khach-hang-quay-lai-sao-khue-ads5"],
    ["Remarketing Xây Nhà TPHCM", "remarketing xây nhà tphcm", "remarketing-xay-nha-tphcm-ads5"],
    ["Remarketing Cải Tạo TPHCM", "remarketing cải tạo tphcm", "remarketing-cai-tao-tphcm-ads5"],
    ["Lookalike Khách Xây Nhà", "lookalike khách xây nhà", "lookalike-khach-xay-nha-ads5"],
    ["Audience Chủ Nhà TPHCM", "audience chủ nhà tphcm", "audience-chu-nha-tphcm-ads5"],
    ["Intent Xây Nhà Cao", "intent xây nhà cao", "intent-xay-nha-cao-ads5"],
    ["Intent Cải Tạo Cao", "intent cải tạo cao", "intent-cai-tao-cao-ads5"],
    ["Bottom Funnel Xây Nhà", "bottom funnel xây nhà", "bottom-funnel-xay-nha-ads5"],
    ["Middle Funnel Cải Tạo", "middle funnel cải tạo", "middle-funnel-cai-tao-ads5"],
    ["Top Funnel Mẫu Nhà", "top funnel mẫu nhà", "top-funnel-mau-nha-ads5"],
    ["Content Hub Xây Nhà", "content hub xây nhà", "content-hub-xay-nha-ads5"],
    ["Pillar Page Xây Nhà", "pillar page xây nhà", "pillar-page-xay-nha-ads5"],
    ["Cluster Cải Tạo Nhà", "cluster cải tạo nhà", "cluster-cai-tao-nha-ads5"],
    ["Internal Link Xây Nhà", "internal link xây nhà", "internal-link-xay-nha-ads5"],
    ["Topic Authority Xây Dựng", "topic authority xây dựng", "topic-authority-xay-dung-ads5"],
    ["Local SEO Xây Nhà", "local seo xây nhà", "local-seo-xay-nha-ads5"],
    ["Google Business Xây Nhà", "google business xây nhà", "google-business-xay-nha-ads5"],
    ["Map Pack Nhà Thầu", "map pack nhà thầu", "map-pack-nha-thau-ads5"],
    ["Review Generation Xây", "review generation xây", "review-generation-xay-ads5"],
    ["UGC Công Trình Thực", "ugc công trình thực", "ugc-cong-trinh-thuc-ads5"],
    ["Before After Gallery", "before after gallery", "before-after-gallery-ads5"],
    ["Case Study Series Xây", "case study series xây", "case-study-series-xay-ads5"],
    ["Video Series Thi Công", "video series thi công", "video-series-thi-cong-ads5"],
    ["Livestream Tư Vấn Xây", "livestream tư vấn xây", "livestream-tu-van-xay-ads5"],
    ["Stories Công Trình Ngày", "stories công trình ngày", "stories-cong-trinh-ngay-ads5"],
    ["Reels Mẫu Nhà Đẹp", "reels mẫu nhà đẹp", "reels-mau-nha-dep-ads5"],
    ["TikTok Xây Nhà Tips", "tiktok xây nhà tips", "tiktok-xay-nha-tips-ads5"],
    ["YouTube Xây Nhà Guide", "youtube xây nhà guide", "youtube-xay-nha-guide-ads5"],
    ["Podcast Kinh Nghiệm Xây", "podcast kinh nghiệm xây", "podcast-kinh-nghiem-xay-ads5"],
    ["Newsletter Xây Nhà", "newsletter xây nhà", "newsletter-xay-nha-ads5"],
    ["Email Nurture Xây Nhà", "email nurture xây nhà", "email-nurture-xay-nha-ads5"],
    ["SMS Nhắc Khảo Sát", "sms nhắc khảo sát", "sms-nhac-khao-sat-ads5"],
    ["Zalo OA Sao Khuê", "zalo oa sao khuê", "zalo-oa-sao-khue-ads5"],
    ["Chatbot Tư Vấn Xây", "chatbot tư vấn xây", "chatbot-tu-van-xay-ads5"],
    ["Quiz Chọn Gói Xây", "quiz chọn gói xây", "quiz-chon-goi-xay-ads5"],
    ["Calculator Chi Phí Xây", "calculator chi phí xây", "calculator-chi-phi-xay-ads5"],
    ["Estimate Tool Online", "estimate tool online", "estimate-tool-online-ads5"],
    ["Config Nhà Mơ Ước", "config nhà mơ ước", "config-nha-mo-uoc-ads5"],
    ["Wishlist Mẫu Nhà", "wishlist mẫu nhà", "wishlist-mau-nha-ads5"],
    ["Save For Later Xây", "save for later xây", "save-for-later-xay-ads5"],
    ["Share Báo Giá Bạn Bè", "share báo giá bạn bè", "share-bao-gia-ban-be-ads5"],
    ["Referral Xây Nhà", "referral xây nhà", "referral-xay-nha-ads5"],
    ["Affiliate Đối Tác Xây", "affiliate đối tác xây", "affiliate-doi-tac-xay-ads5"],
    ["Partner Architect Program", "partner architect program", "partner-architect-program-ads5"],
    ["Loyalty After Build", "loyalty after build", "loyalty-after-build-ads5"],
    ["Warranty Reminder", "warranty reminder", "warranty-reminder-ads5"],
    ["Maintenance Reminder Ads", "maintenance reminder ads", "maintenance-reminder-ads-ads5"],
    ["Upsell Nội Thất Sau Xây", "upsell nội thất sau xây", "upsell-noi-that-sau-xay-ads5"],
    ["Cross Sell Cải Tạo Mặt Tiền", "cross sell cải tạo mặt tiền", "cross-sell-cai-tao-mat-tien-ads5"],
    ["Anniversary Nhà 1 Năm", "anniversary nhà 1 năm", "anniversary-nha-1-nam-ads5"],
    ["Happy Customer Campaign", "happy customer campaign", "happy-customer-campaign-ads5"],
    ["Brand Search Sao Khuê", "brand search sao khuê", "brand-search-sao-khue-ads5"],
    ["Competitor Conquest Xây", "competitor conquest xây", "competitor-conquest-xay-ads5"],
    ["Category Domination Xây", "category domination xây", "category-domination-xay-ads5"],
    ["Seasonal Push Tết 2027", "seasonal push tết 2027", "seasonal-push-tet-2027-ads5"],
    ["Pre Tết Cải Tạo Rush", "pre tết cải tạo rush", "pre-tet-cai-tao-rush-ads5"],
    ["Post Tết Xây Nhà Wave", "post tết xây nhà wave", "post-tet-xay-nha-wave-ads5"],
    ["Rainy Season Promo", "rainy season promo", "rainy-season-promo-ads5"],
    ["Dry Season Build Push", "dry season build push", "dry-season-build-push-ads5"],
    ["Year End Closing Xây", "year end closing xây", "year-end-closing-xay-ads5"],
    ["New Year New Home 2027", "new year new home 2027", "new-year-new-home-2027-ads5"],
    ["Q1 Pipeline Xây Nhà", "q1 pipeline xây nhà", "q1-pipeline-xay-nha-ads5"],
    ["Q2 Pipeline Cải Tạo", "q2 pipeline cải tạo", "q2-pipeline-cai-tao-ads5"],
    ["Always On Lead Gen", "always on lead gen", "always-on-lead-gen-ads5"],
    ["Conversion Rate Xây Nhà", "conversion rate xây nhà", "conversion-rate-xay-nha-ads5"],
    ["ROAS Campaign Xây", "roas campaign xây", "roas-campaign-xay-ads5"],
    ["CPA Lead Xây Nhà", "cpa lead xây nhà", "cpa-lead-xay-nha-ads5"],
    ["LTV Khách Xây Nhà", "ltv khách xây nhà", "ltv-khach-xay-nha-ads5"],
  ]);

  return [b55, b56, b57, b58, b59].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 4947 + (batch - 55) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    55: "Cluster: phòng chức năng, layout, công năng sống.",
    56: "Cluster: chống thấm, mái, thoát nước chuyên sâu.",
    57: "Cluster: geo Thủ Đức, Q12, trục khu vực mới.",
    58: "Cluster: phong thủy, hướng nhà, tuổi xây.",
    59: "Cluster: seasonal, remarketing, Ads content hub.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: phòng chức năng, layout, công năng sống.",
  "Cluster: chống thấm, mái, thoát nước chuyên sâu.",
  "Cluster: geo Thủ Đức, Q12, trục khu vực mới.",
  "Cluster: phong thủy, hướng nhà, tuổi xây.",
  "Cluster: seasonal, remarketing, Ads content hub.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 55 + i;
  const startNo = 4947 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 55 ? 54 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
