/**
 * Generator: short-keyword batches 50–54 (500 articles, #4447–#4946).
 * Run: npx tsx scripts/gen-short-keyword-batches-50-54.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${50 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${50 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${50 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 50 — kết cấu / móng / gia cố sâu
  const b50 = pairs([
    ["Móng Băng Nhà Phố", "móng băng nhà phố", "mong-bang-nha-pho-kc"],
    ["Móng Đơn Nhà Phố", "móng đơn nhà phố", "mong-don-nha-pho-kc"],
    ["Móng Bè Nhà Phố", "móng bè nhà phố", "mong-be-nha-pho-kc"],
    ["Móng Cọc Nhà Phố", "móng cọc nhà phố", "mong-coc-nha-pho-kc"],
    ["Đài Móng Nhà Phố", "đài móng nhà phố", "dai-mong-nha-pho-kc"],
    ["Giằng Móng Nhà Phố", "giằng móng nhà phố", "giang-mong-nha-pho-kc"],
    ["Cọc Ép Bê Tông 200", "cọc ép bê tông 200", "coc-ep-be-tong-200-kc"],
    ["Cọc Ép Bê Tông 250", "cọc ép bê tông 250", "coc-ep-be-tong-250-kc"],
    ["Cọc Ép Bê Tông 300", "cọc ép bê tông 300", "coc-ep-be-tong-300-kc"],
    ["Cọc Khoan Nhồi D300", "cọc khoan nhồi d300", "coc-khoan-nhoi-d300-kc"],
    ["Cọc Khoan Nhồi D400", "cọc khoan nhồi d400", "coc-khoan-nhoi-d400-kc"],
    ["Cọc Tre Gia Cố Nền", "cọc tre gia cố nền", "coc-tre-gia-co-nen-kc"],
    ["Cọc Xi Măng Đất", "cọc xi măng đất", "coc-xi-mang-dat-kc"],
    ["Khảo Sát Địa Chất Nhà Phố", "khảo sát địa chất nhà phố", "khao-sat-dia-chat-nha-pho-kc"],
    ["Báo Cáo Địa Chất Xây Nhà", "báo cáo địa chất xây nhà", "bao-cao-dia-chat-xay-nha-kc"],
    ["Đất Yếu Xây Nhà", "đất yếu xây nhà", "dat-yeu-xay-nha-kc"],
    ["Đất Sét Xây Nhà", "đất sét xây nhà", "dat-set-xay-nha-kc"],
    ["Đất Cát Xây Nhà", "đất cát xây nhà", "dat-cat-xay-nha-kc"],
    ["Mực Nước Ngầm Công Trình", "mực nước ngầm công trình", "muc-nuoc-ngam-cong-trinh-kc"],
    ["Chống Thấm Hầm Móng", "chống thấm hầm móng", "chong-tham-ham-mong-kc"],
    ["Cột Bê Tông Cốt Thép", "cột bê tông cốt thép", "cot-be-tong-cot-thep-kc"],
    ["Dầm Bê Tông Cốt Thép", "dầm bê tông cốt thép", "dam-be-tong-cot-thep-kc"],
    ["Sàn Bê Tông Cốt Thép", "sàn bê tông cốt thép", "san-be-tong-cot-thep-kc"],
    ["Sàn Phẳng Không Dầm", "sàn phẳng không dầm", "san-phang-khong-dam-kc"],
    ["Sàn Dự Ứng Lực Nhà Phố", "sàn dự ứng lực nhà phố", "san-du-ung-luc-nha-pho-kc"],
    ["Sàn Bubble Deck", "sàn bubble deck", "san-bubble-deck-kc"],
    ["Vách Chịu Lực Nhà Phố", "vách chịu lực nhà phố", "vach-chiu-luc-nha-pho-kc"],
    ["Lõi Thang Nhà Phố", "lõi thang nhà phố", "loi-thang-nha-pho-kc"],
    ["Khung Thép Nhà Phố", "khung thép nhà phố", "khung-thep-nha-pho-kc"],
    ["Khung Thép Nhẹ LSF", "khung thép nhẹ lsf", "khung-thep-nhe-lsf-kc"],
    ["Liên Kết Thép Bê Tông", "liên kết thép bê tông", "lien-ket-thep-be-tong-kc"],
    ["Neo Thép Cột Dầm", "neo thép cột dầm", "neo-thep-cot-dam-kc"],
    ["Thép Chờ Nâng Tầng", "thép chờ nâng tầng", "thep-cho-nang-tang-kc"],
    ["Gia Cố Kết Cấu Nhà Cũ", "gia cố kết cấu nhà cũ", "gia-co-ket-cau-nha-cu-kc"],
    ["Gia Cố Cột Bằng Carbon", "gia cố cột bằng carbon", "gia-co-cot-bang-carbon-kc"],
    ["Gia Cố Dầm Bằng Thép", "gia cố dầm bằng thép", "gia-co-dam-bang-thep-kc"],
    ["Gia Cố Sàn Bằng CFRP", "gia cố sàn bằng cfrp", "gia-co-san-bang-cfrp-kc"],
    ["Jacketing Cột Nhà Cũ", "jacketing cột nhà cũ", "jacketing-cot-nha-cu-kc"],
    ["Underpinning Móng Nhà", "underpinning móng nhà", "underpinning-mong-nha-kc"],
    ["Micropile Gia Cố Móng", "micropile gia cố móng", "micropile-gia-co-mong-kc"],
    ["Kiểm Định Kết Cấu Nhà", "kiểm định kết cấu nhà", "kiem-dinh-ket-cau-nha-kc"],
    ["Đánh Giá An Toàn Kết Cấu", "đánh giá an toàn kết cấu", "danh-gia-an-toan-ket-cau-kc"],
    ["Tính Toán Kết Cấu Nhà Phố", "tính toán kết cấu nhà phố", "tinh-toan-ket-cau-nha-pho-kc"],
    ["Phần Mềm Kết Cấu Nhà", "phần mềm kết cấu nhà", "phan-mem-ket-cau-nha-kc"],
    ["Bản Vẽ Kết Cấu Chi Tiết", "bản vẽ kết cấu chi tiết", "ban-ve-ket-cau-chi-tiet-kc"],
    ["Mác Bê Tông Móng", "mác bê tông móng", "mac-be-tong-mong-kc"],
    ["Mác Bê Tông Cột", "mác bê tông cột", "mac-be-tong-cot-kc"],
    ["Mác Bê Tông Sàn", "mác bê tông sàn", "mac-be-tong-san-kc"],
    ["Thép CB300 V Và CB400 V", "thép cb300v và cb400v", "thep-cb300v-va-cb400v-kc"],
    ["Đường Kính Thép Cột", "đường kính thép cột", "duong-kinh-thep-cot-kc"],
    ["Khoảng Cách Thép Sàn", "khoảng cách thép sàn", "khoang-cach-thep-san-kc"],
    ["Lớp Bảo Vệ Bê Tông", "lớp bảo vệ bê tông", "lop-bao-ve-be-tong-kc"],
    ["Chống Ăn Mòn Cốt Thép", "chống ăn mòn cốt thép", "chong-an-mon-cot-thep-kc"],
    ["Rạn Nứt Bê Tông Cho Phép", "rạn nứt bê tông cho phép", "ran-nut-be-tong-cho-phep-kc"],
    ["Võng Sàn Cho Phép", "võng sàn cho phép", "vong-san-cho-phep-kc"],
    ["Độ Nghiêng Nhà Cho Phép", "độ nghiêng nhà cho phép", "do-nghieng-nha-cho-phep-kc"],
    ["Lún Cho Phép Nhà Phố", "lún cho phép nhà phố", "lun-cho-phep-nha-pho-kc"],
    ["Chống Động Đất Nhà Phố", "chống động đất nhà phố", "chong-dong-dat-nha-pho-kc"],
    ["Chống Gió Bão Kết Cấu", "chống gió bão kết cấu", "chong-gio-bao-ket-cau-kc"],
    ["Tường Chịu Lực Hay Chèn", "tường chịu lực hay chèn", "tuong-chiu-luc-hay-chen-kc"],
    ["Tường Xây Không Chịu Lực", "tường xây không chịu lực", "tuong-xay-khong-chiu-luc-kc"],
    ["Lintel Cửa Sổ Cửa Đi", "lintel cửa sổ cửa đi", "lintel-cua-so-cua-di-kc"],
    ["Giằng Tường Nhà Phố", "giằng tường nhà phố", "giang-tuong-nha-pho-kc"],
    ["Mái BTCT Nhà Phố", "mái btct nhà phố", "mai-btct-nha-pho-kc"],
    ["Mái Khung Thép Tôn", "mái khung thép tôn", "mai-khung-thep-ton-kc"],
    ["Kèo Thép Nhà Phố", "kèo thép nhà phố", "keo-thep-nha-pho-kc"],
    ["Xà Gồ Mái Tôn", "xà gồ mái tôn", "xa-go-mai-ton-kc"],
    ["Chống Nóng Kết Cấu Mái", "chống nóng kết cấu mái", "chong-nong-ket-cau-mai-kc"],
    ["Báo Giá Ép Cọc Nhà Phố", "báo giá ép cọc nhà phố", "bao-gia-ep-coc-nha-pho-kc"],
    ["Báo Giá Khoan Cọc Nhồi", "báo giá khoan cọc nhồi", "bao-gia-khoan-coc-nhoi-kc"],
    ["Báo Giá Gia Cố Kết Cấu", "báo giá gia cố kết cấu", "bao-gia-gia-co-ket-cau-kc"],
    ["Báo Giá Kiểm Định Nhà", "báo giá kiểm định nhà", "bao-gia-kiem-dinh-nha-kc"],
    ["Chi Phí Móng Nhà 4 Tầng", "chi phí móng nhà 4 tầng", "chi-phi-mong-nha-4-tang-kc"],
    ["Chi Phí Móng Nhà 5 Tầng", "chi phí móng nhà 5 tầng", "chi-phi-mong-nha-5-tang-kc"],
    ["Số Lượng Cọc Nhà Ống", "số lượng cọc nhà ống", "so-luong-coc-nha-ong-kc"],
    ["Chiều Dài Cọc Nhà Phố", "chiều dài cọc nhà phố", "chieu-dai-coc-nha-pho-kc"],
    ["Nghiệm Thu Ép Cọc", "nghiệm thu ép cọc", "nghiem-thu-ep-coc-kc"],
    ["Nghiệm Thu Khoan Nhồi", "nghiệm thu khoan nhồi", "nghiem-thu-khoan-nhoi-kc"],
    ["Thử Tải Cọc Nhà Phố", "thử tải cọc nhà phố", "thu-tai-coc-nha-pho-kc"],
    ["Biên Bản Nghiệm Thu Kết Cấu", "biên bản nghiệm thu kết cấu", "bien-ban-nghiem-thu-ket-cau-kc"],
    ["Sai Lầm Kết Cấu Thường Gặp", "sai lầm kết cấu thường gặp", "sai-lam-ket-cau-thuong-gap-kc"],
    ["Dấu Hiệu Kết Cấu Yếu", "dấu hiệu kết cấu yếu", "dau-hieu-ket-cau-yeu-kc"],
    ["Khi Nào Cần Gia Cố Nhà", "khi nào cần gia cố nhà", "khi-nao-can-gia-co-nha-kc"],
    ["Nâng Tầng Có Cần Gia Cố", "nâng tầng có cần gia cố", "nang-tang-co-can-gia-co-kc"],
    ["Phá Dỡ Có Ảnh Hưởng Kết Cấu", "phá dỡ có ảnh hưởng kết cấu", "pha-do-co-anh-huong-ket-cau-kc"],
    ["Kết Cấu Nhà Lệch Tầng", "kết cấu nhà lệch tầng", "ket-cau-nha-lech-tang-kc"],
    ["Kết Cấu Nhà Thông Tầng", "kết cấu nhà thông tầng", "ket-cau-nha-thong-tang-kc"],
    ["Kết Cấu Console Ban Công", "kết cấu console ban công", "ket-cau-console-ban-cong-kc"],
    ["Kết Cấu Sân Thượng", "kết cấu sân thượng", "ket-cau-san-thuong-kc"],
    ["Kết Cấu Bể Bơi Trên Mái", "kết cấu bể bơi trên mái", "ket-cau-be-boi-tren-mai-kc"],
    ["Kết Cấu Thang Máy Mini", "kết cấu thang máy mini", "ket-cau-thang-may-mini-kc"],
    ["Xu Hướng Kết Cấu 2026", "xu hướng kết cấu 2026", "xu-huong-ket-cau-2026-kc"],
    ["Kết Cấu Xanh Nhà Phố", "kết cấu xanh nhà phố", "ket-cau-xanh-nha-pho-kc"],
    ["Kết Cấu Prefab Nhà Ở", "kết cấu prefab nhà ở", "ket-cau-prefab-nha-o-kc"],
    ["Kết Cấu Modular Nhà", "kết cấu modular nhà", "ket-cau-modular-nha-kc"],
    ["Checklist Kết Cấu Trước Đổ", "checklist kết cấu trước đổ", "checklist-ket-cau-truoc-do-kc"],
    ["Checklist Kết Cấu Nghiệm Thu", "checklist kết cấu nghiệm thu", "checklist-ket-cau-nghiem-thu-kc"],
  ]);

  // 51 — hoàn thiện chi tiết hạng mục
  const b51 = pairs([
    ["Ốp Gạch Nhà Tắm 30x60", "ốp gạch nhà tắm 30x60", "op-gach-nha-tam-30x60-ht"],
    ["Ốp Gạch Nhà Tắm 60x60", "ốp gạch nhà tắm 60x60", "op-gach-nha-tam-60x60-ht"],
    ["Ốp Gạch Nhà Tắm 60x120", "ốp gạch nhà tắm 60x120", "op-gach-nha-tam-60x120-ht"],
    ["Lát Gạch Phòng Khách 80x80", "lát gạch phòng khách 80x80", "lat-gach-phong-khach-80x80-ht"],
    ["Lát Gạch Phòng Khách 60x60", "lát gạch phòng khách 60x60", "lat-gach-phong-khach-60x60-ht"],
    ["Lát Sàn Gỗ Phòng Ngủ", "lát sàn gỗ phòng ngủ", "lat-san-go-phong-ngu-ht"],
    ["Lát Sàn SPC Phòng Khách", "lát sàn spc phòng khách", "lat-san-spc-phong-khach-ht"],
    ["Lát Sàn Vinyl Nhà Phố", "lát sàn vinyl nhà phố", "lat-san-vinyl-nha-pho-ht"],
    ["Ốp Đá Cầu Thang Granite", "ốp đá cầu thang granite", "op-da-cau-thang-granite-ht"],
    ["Ốp Đá Cầu Thang Marble", "ốp đá cầu thang marble", "op-da-cau-thang-marble-ht"],
    ["Ốp Đá Mặt Bếp", "ốp đá mặt bếp", "op-da-mat-bep-ht"],
    ["Ốp Đá Quầy Bar", "ốp đá quầy bar", "op-da-quay-bar-ht"],
    ["Ốp Đá Lavabo", "ốp đá lavabo", "op-da-lavabo-ht"],
    ["Ron Epoxy Nhà Tắm", "ron epoxy nhà tắm", "ron-epoxy-nha-tam-ht"],
    ["Ron Xi Măng Phòng Khách", "ron xi măng phòng khách", "ron-xi-mang-phong-khach-ht"],
    ["Keo Dán Gạch C2", "keo dán gạch c2", "keo-dan-gach-c2-ht"],
    ["Keo Dán Đá", "keo dán đá", "keo-dan-da-ht"],
    ["Sơn Bả Trong Nhà", "sơn bả trong nhà", "son-ba-trong-nha-ht"],
    ["Sơn Bả Ngoài Nhà", "sơn bả ngoài nhà", "son-ba-ngoai-nha-ht"],
    ["Sơn Lót Kiềm", "sơn lót kiềm", "son-lot-kiem-ht"],
    ["Sơn Phủ Bóng", "sơn phủ bóng", "son-phu-bong-ht"],
    ["Sơn Phủ Mờ", "sơn phủ mờ", "son-phu-mo-ht"],
    ["Sơn Hiệu Ứng Bê Tông", "sơn hiệu ứng bê tông", "son-hieu-ung-be-tong-ht"],
    ["Sơn Hiệu Ứng Đá", "sơn hiệu ứng đá", "son-hieu-ung-da-ht"],
    ["Giấy Dán Tường Phòng Ngủ", "giấy dán tường phòng ngủ", "giay-dan-tuong-phong-ngu-ht"],
    ["Giấy Dán Tường Phòng Khách", "giấy dán tường phòng khách", "giay-dan-tuong-phong-khach-ht"],
    ["Trần Thạch Cao Phẳng", "trần thạch cao phẳng", "tran-thach-cao-phang-ht"],
    ["Trần Thạch Cao Giật Cấp", "trần thạch cao giật cấp", "tran-thach-cao-giat-cap-ht"],
    ["Trần Thạch Cao Kết Hợp Đèn", "trần thạch cao kết hợp đèn", "tran-thach-cao-ket-hop-den-ht"],
    ["Trần Xuyên Sáng", "trần xuyên sáng", "tran-xuyen-sang-ht"],
    ["Trần Lam Gỗ", "trần lam gỗ", "tran-lam-go-ht"],
    ["Trần Nhôm Nhà Phố", "trần nhôm nhà phố", "tran-nhom-nha-pho-ht"],
    ["Vách Ngăn Thạch Cao", "vách ngăn thạch cao", "vach-ngan-thach-cao-ht"],
    ["Vách Ngăn Kính Cường Lực", "vách ngăn kính cường lực", "vach-ngan-kinh-cuong-luc-ht"],
    ["Vách Ngăn Gỗ CNC", "vách ngăn gỗ cnc", "vach-ngan-go-cnc-ht"],
    ["Vách Tivi Phòng Khách", "vách tivi phòng khách", "vach-tivi-phong-khach-ht"],
    ["Phào Chỉ Trần PU", "phào chỉ trần pu", "phao-chi-tran-pu-ht"],
    ["Phào Chỉ Tường PU", "phào chỉ tường pu", "phao-chi-tuong-pu-ht"],
    ["Nẹp Đồng Sàn", "nẹp đồng sàn", "nep-dong-san-ht"],
    ["Nẹp Inox Góc Tường", "nẹp inox góc tường", "nep-inox-goc-tuong-ht"],
    ["Len Chân Tường Nhựa", "len chân tường nhựa", "len-chan-tuong-nhua-ht"],
    ["Len Chân Tường Gỗ", "len chân tường gỗ", "len-chan-tuong-go-ht"],
    ["Cửa Đi Nhôm Xingfa", "cửa đi nhôm xingfa", "cua-di-nhom-xingfa-ht"],
    ["Cửa Đi Nhôm PMA", "cửa đi nhôm pma", "cua-di-nhom-pma-ht"],
    ["Cửa Sổ Lùa Nhôm", "cửa sổ lùa nhôm", "cua-so-lua-nhom-ht"],
    ["Cửa Sổ Mở Quay Nhôm", "cửa sổ mở quay nhôm", "cua-so-mo-quay-nhom-ht"],
    ["Cửa Gỗ Công Nghiệp Melamine", "cửa gỗ công nghiệp melamine", "cua-go-cong-nghiep-melamine-ht"],
    ["Cửa Gỗ Tự Nhiên Óc Chó", "cửa gỗ tự nhiên óc chó", "cua-go-tu-nhien-oc-cho-ht"],
    ["Cửa Nhựa Composite", "cửa nhựa composite", "cua-nhua-composite-ht"],
    ["Cửa Nhựa Đài Loan", "cửa nhựa đài loan", "cua-nhua-dai-loan-ht"],
    ["Cửa Cuốn Austdoor", "cửa cuốn austdoor", "cua-cuon-austdoor-ht"],
    ["Cửa Kéo Đài Loan", "cửa kéo đài loan", "cua-keo-dai-loan-ht"],
    ["Lan Can Kính 10mm", "lan can kính 10mm", "lan-can-kinh-10mm-ht"],
    ["Lan Can Kính 12mm", "lan can kính 12mm", "lan-can-kinh-12mm-ht"],
    ["Lan Can Inox Tay Vịn Gỗ", "lan can inox tay vịn gỗ", "lan-can-inox-tay-vin-go-ht"],
    ["Lan Can Sắt Mỹ Thuật", "lan can sắt mỹ thuật", "lan-can-sat-my-thuat-ht"],
    ["Tay Vịn Cầu Thang Gỗ", "tay vịn cầu thang gỗ", "tay-vin-cau-thang-go-ht"],
    ["Bậc Cầu Thang Gỗ", "bậc cầu thang gỗ", "bac-cau-thang-go-ht"],
    ["Bậc Cầu Thang Đá", "bậc cầu thang đá", "bac-cau-thang-da-ht"],
    ["Tủ Bếp Chữ L Acrylic", "tủ bếp chữ l acrylic", "tu-bep-chu-l-acrylic-ht"],
    ["Tủ Bếp Chữ I Melamine", "tủ bếp chữ i melamine", "tu-bep-chu-i-melamine-ht"],
    ["Tủ Bếp Có Đảo", "tủ bếp có đảo", "tu-bep-co-dao-ht"],
    ["Tủ Quần Áo Cánh Lùa", "tủ quần áo cánh lùa", "tu-quan-ao-canh-lua-ht"],
    ["Tủ Quần Áo Cánh Mở", "tủ quần áo cánh mở", "tu-quan-ao-canh-mo-ht"],
    ["Tủ Giày Thông Minh HT", "tủ giày thông minh", "tu-giay-thong-minh-ht"],
    ["Kệ Tivi Gỗ Công Nghiệp", "kệ tivi gỗ công nghiệp", "ke-tivi-go-cong-nghiep-ht"],
    ["Bàn Trang Điểm Âm Tường", "bàn trang điểm âm tường", "ban-trang-diem-am-tuong-ht"],
    ["Giường Ngủ Có Hộc", "giường ngủ có hộc", "giuong-ngu-co-hoc-ht"],
    ["Rèm Vải Phòng Khách", "rèm vải phòng khách", "rem-vai-phong-khach-ht"],
    ["Rèm Cuốn Văn Phòng Nhà", "rèm cuốn văn phòng nhà", "rem-cuon-van-phong-nha-ht"],
    ["Rèm Cầu Vồng", "rèm cầu vồng", "rem-cau-vong-ht"],
    ["Đèn LED Âm Trần 7W", "đèn led âm trần 7w", "den-led-am-tran-7w-ht"],
    ["Đèn LED Âm Trần 12W", "đèn led âm trần 12w", "den-led-am-tran-12w-ht"],
    ["Đèn Thả Bàn Ăn", "đèn thả bàn ăn", "den-tha-ban-an-ht"],
    ["Đèn Đứng Góc Phòng", "đèn đứng góc phòng", "den-dung-goc-phong-ht"],
    ["Ổ Cắm Âm Sàn", "ổ cắm âm sàn", "o-cam-am-san-ht"],
    ["Công Tắc Cảm Ứng HT", "công tắc cảm ứng", "cong-tac-cam-ung-ht"],
    ["Sen Cây Âm Trần", "sen cây âm trần", "sen-cay-am-tran-ht"],
    ["Sen Tắm Nhiệt Độ", "sen tắm nhiệt độ", "sen-tam-nhiet-do-ht"],
    ["Bồn Tắm Nằm", "bồn tắm nằm", "bon-tam-nam-ht"],
    ["Cabin Tắm Kính", "cabin tắm kính", "cabin-tam-kinh-ht"],
    ["Báo Giá Hoàn Thiện m2", "báo giá hoàn thiện m2", "bao-gia-hoan-thien-m2-ht"],
    ["Báo Giá Ốp Lát m2", "báo giá ốp lát m2", "bao-gia-op-lat-m2-ht"],
    ["Báo Giá Sơn Nước m2", "báo giá sơn nước m2", "bao-gia-son-nuoc-m2-ht"],
    ["Báo Giá Trần Thạch Cao m2", "báo giá trần thạch cao m2", "bao-gia-tran-thach-cao-m2-ht"],
    ["Quy Trình Hoàn Thiện Nhà", "quy trình hoàn thiện nhà", "quy-trinh-hoan-thien-nha-ht"],
    ["Thứ Tự Thi Công Hoàn Thiện", "thứ tự thi công hoàn thiện", "thu-tu-thi-cong-hoan-thien-ht"],
    ["Nghiệm Thu Hoàn Thiện", "nghiệm thu hoàn thiện", "nghiem-thu-hoan-thien-ht"],
    ["Checklist Hoàn Thiện Nhà", "checklist hoàn thiện nhà", "checklist-hoan-thien-nha-ht"],
    ["Lỗi Hoàn Thiện Thường Gặp", "lỗi hoàn thiện thường gặp", "loi-hoan-thien-thuong-gap-ht"],
    ["Xu Hướng Hoàn Thiện 2026", "xu hướng hoàn thiện 2026", "xu-huong-hoan-thien-2026-ht"],
  ]);

  // 52 — geo Tây Nguyên / duyên hải / Hà Nội sâu hơn
  const b52 = pairs([
    ["Xây Nhà Buôn Hồ", "xây nhà Buôn Hồ", "xay-nha-buon-ho-geo3"],
    ["Xây Nhà Ea Hleo", "xây nhà Ea Hleo", "xay-nha-ea-hleo-geo3"],
    ["Xây Nhà Krông Buk", "xây nhà Krông Buk", "xay-nha-krong-buk-geo3"],
    ["Xây Nhà Krông Pắc", "xây nhà Krông Pắc", "xay-nha-krong-pac-geo3"],
    ["Xây Nhà Cư Mgar", "xây nhà Cư Mgar", "xay-nha-cu-mgar-geo3"],
    ["Xây Nhà Buôn Đôn", "xây nhà Buôn Đôn", "xay-nha-buon-don-geo3"],
    ["Xây Nhà Ea Súp", "xây nhà Ea Súp", "xay-nha-ea-sup-geo3"],
    ["Xây Nhà M Đrắk", "xây nhà M Đrắk", "xay-nha-m-drak-geo3"],
    ["Xây Nhà Krông Ana", "xây nhà Krông Ana", "xay-nha-krong-ana-geo3"],
    ["Xây Nhà Lắk", "xây nhà Lắk", "xay-nha-lak-geo3"],
    ["Xây Nhà Cư Kuin", "xây nhà Cư Kuin", "xay-nha-cu-kuin-geo3"],
    ["Xây Nhà Gia Nghĩa", "xây nhà Gia Nghĩa", "xay-nha-gia-nghia-geo3"],
    ["Xây Nhà Đắk Mil", "xây nhà Đắk Mil", "xay-nha-dak-mil-geo3"],
    ["Xây Nhà Đắk Song", "xây nhà Đắk Song", "xay-nha-dak-song-geo3"],
    ["Xây Nhà Cư Jút", "xây nhà Cư Jút", "xay-nha-cu-jut-geo3"],
    ["Xây Nhà Đắk RLấp", "xây nhà Đắk RLấp", "xay-nha-dak-rlap-geo3"],
    ["Xây Nhà Đắk Glong", "xây nhà Đắk Glong", "xay-nha-dak-glong-geo3"],
    ["Xây Nhà Krông Nô", "xây nhà Krông Nô", "xay-nha-krong-no-geo3"],
    ["Xây Nhà Đắk Tô", "xây nhà Đắk Tô", "xay-nha-dak-to-geo3"],
    ["Xây Nhà Ngọc Hồi", "xây nhà Ngọc Hồi", "xay-nha-ngoc-hoi-geo3"],
    ["Xây Nhà Sa Thầy", "xây nhà Sa Thầy", "xay-nha-sa-thay-geo3"],
    ["Xây Nhà Kon Plông", "xây nhà Kon Plông", "xay-nha-kon-plong-geo3"],
    ["Xây Nhà Đắk Hà", "xây nhà Đắk Hà", "xay-nha-dak-ha-geo3"],
    ["Xây Nhà Kon Rẫy", "xây nhà Kon Rẫy", "xay-nha-kon-ray-geo3"],
    ["Xây Nhà An Khê", "xây nhà An Khê", "xay-nha-an-khe-geo3"],
    ["Xây Nhà Ayun Pa", "xây nhà Ayun Pa", "xay-nha-ayun-pa-geo3"],
    ["Xây Nhà Chư Sê", "xây nhà Chư Sê", "xay-nha-chu-se-geo3"],
    ["Xây Nhà Chư Păh", "xây nhà Chư Păh", "xay-nha-chu-pah-geo3"],
    ["Xây Nhà Ia Grai", "xây nhà Ia Grai", "xay-nha-ia-grai-geo3"],
    ["Xây Nhà Đức Cơ", "xây nhà Đức Cơ", "xay-nha-duc-co-geo3"],
    ["Xây Nhà Chư Prông", "xây nhà Chư Prông", "xay-nha-chu-prong-geo3"],
    ["Xây Nhà KBang", "xây nhà KBang", "xay-nha-kbang-geo3"],
    ["Xây Nhà Kông Chro", "xây nhà Kông Chro", "xay-nha-kong-chro-geo3"],
    ["Xây Nhà Mang Yang", "xây nhà Mang Yang", "xay-nha-mang-yang-geo3"],
    ["Xây Nhà Đak Đoa", "xây nhà Đak Đoa", "xay-nha-dak-doa-geo3"],
    ["Xây Nhà Bảo Lộc", "xây nhà Bảo Lộc", "xay-nha-bao-loc-geo3"],
    ["Xây Nhà Đức Trọng", "xây nhà Đức Trọng", "xay-nha-duc-trong-geo3"],
    ["Xây Nhà Di Linh", "xây nhà Di Linh", "xay-nha-di-linh-geo3"],
    ["Xây Nhà Bảo Lâm LĐ", "xây nhà Bảo Lâm Lâm Đồng", "xay-nha-bao-lam-ld-geo3"],
    ["Xây Nhà Đạ Huoai", "xây nhà Đạ Huoai", "xay-nha-da-huoai-geo3"],
    ["Xây Nhà Đạ Tẻh", "xây nhà Đạ Tẻh", "xay-nha-da-teh-geo3"],
    ["Xây Nhà Cát Tiên", "xây nhà Cát Tiên", "xay-nha-cat-tien-geo3"],
    ["Xây Nhà Đơn Dương", "xây nhà Đơn Dương", "xay-nha-don-duong-geo3"],
    ["Xây Nhà Lạc Dương", "xây nhà Lạc Dương", "xay-nha-lac-duong-geo3"],
    ["Xây Nhà Đam Rông", "xây nhà Đam Rông", "xay-nha-dam-rong-geo3"],
    ["Xây Nhà Cam Ranh", "xây nhà Cam Ranh", "xay-nha-cam-ranh-geo3"],
    ["Xây Nhà Ninh Hòa", "xây nhà Ninh Hòa", "xay-nha-ninh-hoa-geo3"],
    ["Xây Nhà Vạn Ninh", "xây nhà Vạn Ninh", "xay-nha-van-ninh-geo3"],
    ["Xây Nhà Diên Khánh", "xây nhà Diên Khánh", "xay-nha-dien-khanh-geo3"],
    ["Xây Nhà Cam Lâm", "xây nhà Cam Lâm", "xay-nha-cam-lam-geo3"],
    ["Xây Nhà Khánh Vĩnh", "xây nhà Khánh Vĩnh", "xay-nha-khanh-vinh-geo3"],
    ["Xây Nhà Khánh Sơn", "xây nhà Khánh Sơn", "xay-nha-khanh-son-geo3"],
    ["Xây Nhà Tuy Hòa", "xây nhà Tuy Hòa", "xay-nha-tuy-hoa-geo3"],
    ["Xây Nhà Sông Cầu", "xây nhà Sông Cầu", "xay-nha-song-cau-geo3"],
    ["Xây Nhà Đông Hòa PY", "xây nhà Đông Hòa Phú Yên", "xay-nha-dong-hoa-py-geo3"],
    ["Xây Nhà Tây Hòa", "xây nhà Tây Hòa", "xay-nha-tay-hoa-geo3"],
    ["Xây Nhà Quy Nhơn", "xây nhà Quy Nhơn", "xay-nha-quy-nhon-geo3"],
    ["Xây Nhà An Nhơn", "xây nhà An Nhơn", "xay-nha-an-nhon-geo3"],
    ["Xây Nhà Hoài Nhơn", "xây nhà Hoài Nhơn", "xay-nha-hoai-nhon-geo3"],
    ["Xây Nhà Phù Cát", "xây nhà Phù Cát", "xay-nha-phu-cat-geo3"],
    ["Xây Nhà Tuy Phước", "xây nhà Tuy Phước", "xay-nha-tuy-phuoc-geo3"],
    ["Xây Nhà Tây Sơn BD", "xây nhà Tây Sơn Bình Định", "xay-nha-tay-son-bd-geo3"],
    ["Xây Nhà Hội An", "xây nhà Hội An", "xay-nha-hoi-an-geo3"],
    ["Xây Nhà Tam Kỳ", "xây nhà Tam Kỳ", "xay-nha-tam-ky-geo3"],
    ["Xây Nhà Điện Bàn", "xây nhà Điện Bàn", "xay-nha-dien-ban-geo3"],
    ["Xây Nhà Núi Thành", "xây nhà Núi Thành", "xay-nha-nui-thanh-geo3"],
    ["Xây Nhà Duy Xuyên", "xây nhà Duy Xuyên", "xay-nha-duy-xuyen-geo3"],
    ["Xây Nhà Quảng Ngãi TP", "xây nhà Quảng Ngãi", "xay-nha-quang-ngai-tp-geo3"],
    ["Xây Nhà Đức Phổ", "xây nhà Đức Phổ", "xay-nha-duc-pho-geo3"],
    ["Xây Nhà Sơn Tịnh", "xây nhà Sơn Tịnh", "xay-nha-son-tinh-geo3"],
    ["Xây Nhà Tư Nghĩa", "xây nhà Tư Nghĩa", "xay-nha-tu-nghia-geo3"],
    ["Cải Tạo Nhà Buôn Ma Thuột", "cải tạo nhà Buôn Ma Thuột", "cai-tao-nha-bmt-geo3"],
    ["Cải Tạo Nhà Pleiku", "cải tạo nhà Pleiku", "cai-tao-nha-pleiku-geo3"],
    ["Cải Tạo Nhà Bảo Lộc", "cải tạo nhà Bảo Lộc", "cai-tao-nha-bao-loc-geo3"],
    ["Cải Tạo Nhà Quy Nhơn", "cải tạo nhà Quy Nhơn", "cai-tao-nha-quy-nhon-geo3"],
    ["Cải Tạo Nhà Hội An", "cải tạo nhà Hội An", "cai-tao-nha-hoi-an-geo3"],
    ["Thiết Kế Nhà Buôn Ma Thuột", "thiết kế nhà Buôn Ma Thuột", "thiet-ke-nha-bmt-geo3"],
    ["Thiết Kế Nhà Pleiku", "thiết kế nhà Pleiku", "thiet-ke-nha-pleiku-geo3"],
    ["Thiết Kế Nhà Bảo Lộc", "thiết kế nhà Bảo Lộc", "thiet-ke-nha-bao-loc-geo3"],
    ["Thiết Kế Nhà Quy Nhơn", "thiết kế nhà Quy Nhơn", "thiet-ke-nha-quy-nhon-geo3"],
    ["Báo Giá Xây Nhà Đắk Lắk", "báo giá xây nhà Đắk Lắk", "bao-gia-xay-nha-dak-lak-geo3"],
    ["Báo Giá Xây Nhà Gia Lai", "báo giá xây nhà Gia Lai", "bao-gia-xay-nha-gia-lai-geo3"],
    ["Báo Giá Xây Nhà Lâm Đồng", "báo giá xây nhà Lâm Đồng", "bao-gia-xay-nha-lam-dong-geo3"],
    ["Báo Giá Xây Nhà Khánh Hòa", "báo giá xây nhà Khánh Hòa", "bao-gia-xay-nha-khanh-hoa-geo3"],
    ["Báo Giá Xây Nhà Bình Định", "báo giá xây nhà Bình Định", "bao-gia-xay-nha-binh-dinh-geo3"],
    ["Nhà Thầu Buôn Ma Thuột", "nhà thầu Buôn Ma Thuột", "nha-thau-bmt-geo3"],
    ["Nhà Thầu Pleiku", "nhà thầu Pleiku", "nha-thau-pleiku-geo3"],
    ["Nhà Thầu Bảo Lộc", "nhà thầu Bảo Lộc", "nha-thau-bao-loc-geo3"],
    ["Nhà Thầu Quy Nhơn", "nhà thầu Quy Nhơn", "nha-thau-quy-nhon-geo3"],
    ["Xây Nhà Cao Nguyên Chống Lạnh", "xây nhà cao nguyên chống lạnh", "xay-nha-cao-nguyen-chong-lanh-geo3"],
    ["Xây Nhà Ven Biển Chống Ăn Mòn", "xây nhà ven biển chống ăn mòn", "xay-nha-ven-bien-chong-an-mon-geo3"],
    ["Xây Nhà Ven Biển Chống Bão", "xây nhà ven biển chống bão", "xay-nha-ven-bien-chong-bao-geo3"],
    ["Xây Biệt Thự Đà Lạt", "xây biệt thự Đà Lạt", "xay-biet-thu-da-lat-geo3"],
    ["Xây Biệt Thự Quy Nhơn", "xây biệt thự Quy Nhơn", "xay-biet-thu-quy-nhon-geo3"],
    ["Xây Homestay Đà Lạt", "xây homestay Đà Lạt", "xay-homestay-da-lat-geo3"],
    ["Xây Homestay Hội An", "xây homestay Hội An", "xay-homestay-hoi-an-geo3"],
    ["Xây Nhà Vườn Tây Nguyên", "xây nhà vườn Tây Nguyên", "xay-nha-vuon-tay-nguyen-geo3"],
    ["Xây Nhà Farmstay Lâm Đồng", "xây nhà farmstay Lâm Đồng", "xay-nha-farmstay-lam-dong-geo3"],
  ]);

  // 53 — bảo trì / bảo hành / vòng đời nhà
  const b53 = pairs([
    ["Bảo Trì Nhà Định Kỳ", "bảo trì nhà định kỳ", "bao-tri-nha-dinh-ky-bt"],
    ["Bảo Trì Nhà Hàng Năm", "bảo trì nhà hàng năm", "bao-tri-nha-hang-nam-bt"],
    ["Bảo Trì Nhà Hàng Quý", "bảo trì nhà hàng quý", "bao-tri-nha-hang-quy-bt"],
    ["Checklist Bảo Trì Nhà", "checklist bảo trì nhà", "checklist-bao-tri-nha-bt"],
    ["Bảo Trì Mái Nhà", "bảo trì mái nhà", "bao-tri-mai-nha-bt"],
    ["Bảo Trì Hệ Thống Điện", "bảo trì hệ thống điện", "bao-tri-he-thong-dien-bt"],
    ["Bảo Trì Hệ Thống Nước", "bảo trì hệ thống nước", "bao-tri-he-thong-nuoc-bt"],
    ["Bảo Trì Máy Lạnh Nhà", "bảo trì máy lạnh nhà", "bao-tri-may-lanh-nha-bt"],
    ["Bảo Trì Bơm Nước", "bảo trì bơm nước", "bao-tri-bom-nuoc-bt"],
    ["Bảo Trì Bể Phốt", "bảo trì bể phốt", "bao-tri-be-phot-bt"],
    ["Hút Bể Phốt Định Kỳ", "hút bể phốt định kỳ", "hut-be-phot-dinh-ky-bt"],
    ["Thông Cống Nhà Phố", "thông cống nhà phố", "thong-cong-nha-pho-bt"],
    ["Vệ Sinh Mái Tôn", "vệ sinh mái tôn", "ve-sinh-mai-ton-bt"],
    ["Vệ Sinh Sân Thượng", "vệ sinh sân thượng", "ve-sinh-san-thuong-bt"],
    ["Vệ Sinh Giếng Trời", "vệ sinh giếng trời", "ve-sinh-gieng-troi-bt"],
    ["Vệ Sinh Cửa Kính", "vệ sinh cửa kính", "ve-sinh-cua-kinh-bt"],
    ["Bảo Dưỡng Sơn Ngoại Thất", "bảo dưỡng sơn ngoại thất", "bao-duong-son-ngoai-that-bt"],
    ["Bảo Dưỡng Gỗ Nội Thất", "bảo dưỡng gỗ nội thất", "bao-duong-go-noi-that-bt"],
    ["Bảo Dưỡng Sàn Gỗ", "bảo dưỡng sàn gỗ", "bao-duong-san-go-bt"],
    ["Đánh Bóng Sàn Đá", "đánh bóng sàn đá", "danh-bong-san-da-bt"],
    ["Chống Thấm Định Kỳ", "chống thấm định kỳ", "chong-tham-dinh-ky-bt"],
    ["Kiểm Tra Thấm Mùa Mưa", "kiểm tra thấm mùa mưa", "kiem-tra-tham-mua-mua-bt"],
    ["Kiểm Tra Điện An Toàn", "kiểm tra điện an toàn", "kiem-tra-dien-an-toan-bt"],
    ["Thay Pin Báo Cháy", "thay pin báo cháy", "thay-pin-bao-chay-bt"],
    ["Thay Lọc Máy Lạnh", "thay lọc máy lạnh", "thay-loc-may-lanh-bt"],
    ["Thay Lọc Nước RO", "thay lọc nước ro", "thay-loc-nuoc-ro-bt"],
    ["Bảo Hành Kết Cấu Nhà", "bảo hành kết cấu nhà", "bao-hanh-ket-cau-nha-bt"],
    ["Bảo Hành Chống Thấm", "bảo hành chống thấm", "bao-hanh-chong-tham-bt"],
    ["Bảo Hành Sơn Nhà", "bảo hành sơn nhà", "bao-hanh-son-nha-bt"],
    ["Bảo Hành Ốp Lát", "bảo hành ốp lát", "bao-hanh-op-lat-bt"],
    ["Bảo Hành Điện Nước", "bảo hành điện nước", "bao-hanh-dien-nuoc-bt"],
    ["Bảo Hành Cửa Nhôm", "bảo hành cửa nhôm", "bao-hanh-cua-nhom-bt"],
    ["Bảo Hành Nội Thất", "bảo hành nội thất", "bao-hanh-noi-that-bt"],
    ["Cách Đòi Bảo Hành Xây", "cách đòi bảo hành xây", "cach-doi-bao-hanh-xay-bt"],
    ["Thời Hạn Bảo Hành Xây", "thời hạn bảo hành xây", "thoi-han-bao-hanh-xay-bt"],
    ["Điều Khoản Bảo Hành Hợp Đồng", "điều khoản bảo hành hợp đồng", "dieu-khoan-bao-hanh-hop-dong-bt"],
    ["Sửa Chữa Trong Bảo Hành", "sửa chữa trong bảo hành", "sua-chua-trong-bao-hanh-bt"],
    ["Sửa Chữa Ngoài Bảo Hành", "sửa chữa ngoài bảo hành", "sua-chua-ngoai-bao-hanh-bt"],
    ["Chi Phí Bảo Trì Nhà Năm", "chi phí bảo trì nhà năm", "chi-phi-bao-tri-nha-nam-bt"],
    ["Ngân Sách Bảo Trì Nhà", "ngân sách bảo trì nhà", "ngan-sach-bao-tri-nha-bt"],
    ["Gói Bảo Trì Nhà Năm", "gói bảo trì nhà năm", "goi-bao-tri-nha-nam-bt"],
    ["Dịch Vụ Bảo Trì Nhà Phố", "dịch vụ bảo trì nhà phố", "dich-vu-bao-tri-nha-pho-bt"],
    ["Bảo Trì Nhà Cho Thuê", "bảo trì nhà cho thuê", "bao-tri-nha-cho-thue-bt"],
    ["Bảo Trì Nhà Vắng Chủ", "bảo trì nhà vắng chủ", "bao-tri-nha-vang-chu-bt"],
    ["Tuổi Thọ Nhà Phố", "tuổi thọ nhà phố", "tuoi-tho-nha-pho-bt"],
    ["Tuổi Thọ Mái Tôn", "tuổi thọ mái tôn", "tuoi-tho-mai-ton-bt"],
    ["Tuổi Thọ Mái Ngói", "tuổi thọ mái ngói", "tuoi-tho-mai-ngoi-bt"],
    ["Tuổi Thọ Sơn Ngoại Thất", "tuổi thọ sơn ngoại thất", "tuoi-tho-son-ngoai-that-bt"],
    ["Tuổi Thọ Sàn Gỗ", "tuổi thọ sàn gỗ", "tuoi-tho-san-go-bt"],
    ["Tuổi Thọ Cửa Nhôm", "tuổi thọ cửa nhôm", "tuoi-tho-cua-nhom-bt"],
    ["Khi Nào Sơn Lại Nhà", "khi nào sơn lại nhà", "khi-nao-son-lai-nha-bt"],
    ["Khi Nào Thay Mái Tôn", "khi nào thay mái tôn", "khi-nao-thay-mai-ton-bt"],
    ["Khi Nào Thay Ống Nước", "khi nào thay ống nước", "khi-nao-thay-ong-nuoc-bt"],
    ["Khi Nào Thay Dây Điện", "khi nào thay dây điện", "khi-nao-thay-day-dien-bt"],
    ["Dấu Hiệu Nhà Cần Bảo Trì", "dấu hiệu nhà cần bảo trì", "dau-hieu-nha-can-bao-tri-bt"],
    ["Dấu Hiệu Thấm Sắp Xảy Ra", "dấu hiệu thấm sắp xảy ra", "dau-hieu-tham-sap-xay-ra-bt"],
    ["Dấu Hiệu Hệ Điện Yếu", "dấu hiệu hệ điện yếu", "dau-hieu-he-dien-yeu-bt"],
    ["Dấu Hiệu Hệ Nước Lỗi", "dấu hiệu hệ nước lỗi", "dau-hieu-he-nuoc-loi-bt"],
    ["Phòng Ngừa Mối Nhà Gỗ", "phòng ngừa mối nhà gỗ", "phong-ngua-moi-nha-go-bt"],
    ["Phòng Ngừa Mốc Nhà", "phòng ngừa mốc nhà", "phong-ngua-moc-nha-bt"],
    ["Phòng Ngừa Rỉ Sét Lan Can", "phòng ngừa rỉ sét lan can", "phong-ngua-ri-set-lan-can-bt"],
    ["Phòng Ngừa Tắc Cống", "phòng ngừa tắc cống", "phong-ngua-tac-cong-bt"],
    ["Bảo Trì Trước Mùa Mưa", "bảo trì trước mùa mưa", "bao-tri-truoc-mua-mua-bt"],
    ["Bảo Trì Sau Mùa Mưa", "bảo trì sau mùa mưa", "bao-tri-sau-mua-mua-bt"],
    ["Bảo Trì Trước Tết", "bảo trì trước tết", "bao-tri-truoc-tet-bt"],
    ["Dọn Dẹp Công Trình Sau Xây", "dọn dẹp công trình sau xây", "don-dep-cong-trinh-sau-xay-bt"],
    ["Vệ Sinh Công Nghiệp Sau Bàn Giao", "vệ sinh công nghiệp sau bàn giao", "ve-sinh-cong-nghiep-sau-ban-giao-bt"],
    ["Chăm Sóc Nhà Mới Xây", "chăm sóc nhà mới xây", "cham-soc-nha-moi-xay-bt"],
    ["Chăm Sóc Nhà Sau Cải Tạo", "chăm sóc nhà sau cải tạo", "cham-soc-nha-sau-cai-tao-bt"],
    ["Hướng Dẫn Sử Dụng Nhà Mới", "hướng dẫn sử dụng nhà mới", "huong-dan-su-dung-nha-moi-bt"],
    ["Sổ Tay Bảo Trì Nhà", "sổ tay bảo trì nhà", "so-tay-bao-tri-nha-bt"],
    ["Lịch Bảo Trì 12 Tháng", "lịch bảo trì 12 tháng", "lich-bao-tri-12-thang-bt"],
    ["App Nhắc Bảo Trì Nhà", "app nhắc bảo trì nhà", "app-nhac-bao-tri-nha-bt"],
    ["Bảo Hiểm Nhà Và Bảo Trì", "bảo hiểm nhà và bảo trì", "bao-hiem-nha-va-bao-tri-bt"],
    ["Chi Phí Vòng Đời Nhà Ở", "chi phí vòng đời nhà ở", "chi-phi-vong-doi-nha-o-bt"],
    ["Tối Ưu Chi Phí Sở Hữu Nhà", "tối ưu chi phí sở hữu nhà", "toi-uu-chi-phi-so-huu-nha-bt"],
    ["Giá Trị Thanh Lý Nhà Cũ", "giá trị thanh lý nhà cũ", "gia-tri-thanh-ly-nha-cu-bt"],
    ["Nâng Cấp Nhà Thay Thế Mới", "nâng cấp nhà thay thế mới", "nang-cap-nha-thay-the-moi-bt"],
    ["Retrofit Nhà Phố", "retrofit nhà phố", "retrofit-nha-pho-bt"],
    ["Nâng Cấp Năng Lượng Nhà", "nâng cấp năng lượng nhà", "nang-cap-nang-luong-nha-bt"],
    ["Nâng Cấp Cách Nhiệt Nhà", "nâng cấp cách nhiệt nhà", "nang-cap-cach-nhiet-nha-bt"],
    ["Nâng Cấp Cách Âm Nhà", "nâng cấp cách âm nhà", "nang-cap-cach-am-nha-bt"],
    ["Nâng Cấp Smart Home Cũ", "nâng cấp smart home cũ", "nang-cap-smart-home-cu-bt"],
    ["Báo Giá Bảo Trì Nhà Năm", "báo giá bảo trì nhà năm", "bao-gia-bao-tri-nha-nam-bt"],
    ["Báo Giá Sơn Lại Nhà", "báo giá sơn lại nhà", "bao-gia-son-lai-nha-bt"],
    ["Báo Giá Thay Mái Tôn", "báo giá thay mái tôn", "bao-gia-thay-mai-ton-bt"],
    ["Đặt Lịch Bảo Trì Nhà", "đặt lịch bảo trì nhà", "dat-lich-bao-tri-nha-bt"],
    ["Hotline Bảo Hành Xây", "hotline bảo hành xây", "hotline-bao-hanh-xay-bt"],
    ["After Sales Sao Khuê", "after sales sao khuê", "after-sales-sao-khue-bt"],
  ]);

  // 54 — so sánh gói / intent mua / Ads cuối funnel
  const b54 = pairs([
    ["Gói Xây Nhà 3 Triệu m2", "gói xây nhà 3 triệu m2", "goi-xay-nha-3-trieu-m2-ads4"],
    ["Gói Xây Nhà 4 Triệu m2", "gói xây nhà 4 triệu m2", "goi-xay-nha-4-trieu-m2-ads4"],
    ["Gói Xây Nhà 5 Triệu m2", "gói xây nhà 5 triệu m2", "goi-xay-nha-5-trieu-m2-ads4"],
    ["Gói Xây Nhà 6 Triệu m2", "gói xây nhà 6 triệu m2", "goi-xay-nha-6-trieu-m2-ads4"],
    ["Gói Xây Nhà 7 Triệu m2", "gói xây nhà 7 triệu m2", "goi-xay-nha-7-trieu-m2-ads4"],
    ["Gói Xây Nhà 8 Triệu m2", "gói xây nhà 8 triệu m2", "goi-xay-nha-8-trieu-m2-ads4"],
    ["Gói Thô 3 Triệu m2", "gói thô 3 triệu m2", "goi-tho-3-trieu-m2-ads4"],
    ["Gói Thô 3.5 Triệu m2", "gói thô 3.5 triệu m2", "goi-tho-3-5-trieu-m2-ads4"],
    ["Gói Thô 4 Triệu m2", "gói thô 4 triệu m2", "goi-tho-4-trieu-m2-ads4"],
    ["Gói Hoàn Thiện 2 Triệu m2", "gói hoàn thiện 2 triệu m2", "goi-hoan-thien-2-trieu-m2-ads4"],
    ["Gói Hoàn Thiện 3 Triệu m2", "gói hoàn thiện 3 triệu m2", "goi-hoan-thien-3-trieu-m2-ads4"],
    ["Gói Hoàn Thiện 4 Triệu m2", "gói hoàn thiện 4 triệu m2", "goi-hoan-thien-4-trieu-m2-ads4"],
    ["So Sánh Gói 5 Triệu Và 6 Triệu", "so sánh gói 5 triệu và 6 triệu", "so-sanh-goi-5-va-6-trieu-ads4"],
    ["So Sánh Gói 6 Triệu Và 7 Triệu", "so sánh gói 6 triệu và 7 triệu", "so-sanh-goi-6-va-7-trieu-ads4"],
    ["Gói Nào Phù Hợp Ngân Sách 2 Tỷ", "gói nào phù hợp ngân sách 2 tỷ", "goi-nao-phu-hop-2-ty-ads4"],
    ["Gói Nào Phù Hợp Ngân Sách 3 Tỷ", "gói nào phù hợp ngân sách 3 tỷ", "goi-nao-phu-hop-3-ty-ads4"],
    ["Gói Nào Phù Hợp Ngân Sách 5 Tỷ", "gói nào phù hợp ngân sách 5 tỷ", "goi-nao-phu-hop-5-ty-ads4"],
    ["Báo Giá Chi Tiết Theo Gói", "báo giá chi tiết theo gói", "bao-gia-chi-tiet-theo-goi-ads4"],
    ["Báo Giá Minh Bạch Xây Nhà", "báo giá minh bạch xây nhà", "bao-gia-minh-bach-xay-nha-ads4"],
    ["Báo Giá Không Ẩn Phí", "báo giá không ẩn phí", "bao-gia-khong-an-phi-ads4"],
    ["Nhận Báo Giá Miễn Phí Ngay", "nhận báo giá miễn phí ngay", "nhan-bao-gia-mien-phi-ngay-ads4"],
    ["So Báo Giá 3 Nhà Thầu", "so báo giá 3 nhà thầu", "so-bao-gia-3-nha-thau-ads4"],
    ["Tư Vấn Chọn Gói Xây", "tư vấn chọn gói xây", "tu-van-chon-goi-xay-ads4"],
    ["Tư Vấn Chọn Gói Cải Tạo", "tư vấn chọn gói cải tạo", "tu-van-chon-goi-cai-tao-ads4"],
    ["Đặt Cọc Giữ Chỗ Xây", "đặt cọc giữ chỗ xây", "dat-coc-giu-cho-xay-ads4"],
    ["Ký Hợp Đồng Xây Online", "ký hợp đồng xây online", "ky-hop-dong-xay-online-ads4"],
    ["Thanh Toán Linh Hoạt Xây", "thanh toán linh hoạt xây", "thanh-toan-linh-hoat-xay-ads4"],
    ["Trả Góp Xây Nhà", "trả góp xây nhà", "tra-gop-xay-nha-ads4"],
    ["Hỗ Trợ Vay Xây Nhà", "hỗ trợ vay xây nhà", "ho-tro-vay-xay-nha-ads4"],
    ["Ưu Đãi Ký Hợp Đồng Tháng Này", "ưu đãi ký hợp đồng tháng này", "uu-dai-ky-hop-dong-thang-nay-ads4"],
    ["Giảm Giá Thiết Kế Khi Xây", "giảm giá thiết kế khi xây", "giam-gia-thiet-ke-khi-xay-ads4"],
    ["Tặng Nội Thất Cơ Bản", "tặng nội thất cơ bản", "tang-noi-that-co-ban-ads4"],
    ["Tặng Chống Thấm Cao Cấp", "tặng chống thấm cao cấp", "tang-chong-tham-cao-cap-ads4"],
    ["Tặng Bảo Hành Mở Rộng", "tặng bảo hành mở rộng", "tang-bao-hanh-mo-rong-ads4"],
    ["Slot Thi Công Còn Bao Nhiêu", "slot thi công còn bao nhiêu", "slot-thi-cong-con-bao-nhieu-ads4"],
    ["Đặt Lịch Khảo Sát Hôm Nay", "đặt lịch khảo sát hôm nay", "dat-lich-khao-sat-hom-nay-ads4"],
    ["Khảo Sát Trong 24h", "khảo sát trong 24h", "khao-sat-trong-24h-ads4"],
    ["Báo Giá Trong 48h", "báo giá trong 48h", "bao-gia-trong-48h-ads4"],
    ["Ký Hợp Đồng Trong Tuần", "ký hợp đồng trong tuần", "ky-hop-dong-trong-tuan-ads4"],
    ["Khởi Công Trong 15 Ngày", "khởi công trong 15 ngày", "khoi-cong-trong-15-ngay-ads4"],
    ["Công Trình Đang Thi Công", "công trình đang thi công", "cong-trinh-dang-thi-cong-ads4"],
    ["Xem Công Trình Thực Tế", "xem công trình thực tế", "xem-cong-trinh-thuc-te-ads4"],
    ["Tour Công Trình Cuối Tuần", "tour công trình cuối tuần", "tour-cong-trinh-cuoi-tuan-ads4"],
    ["Open House Cuối Tháng", "open house cuối tháng", "open-house-cuoi-thang-ads4"],
    ["Testimonial Video Khách", "testimonial video khách", "testimonial-video-khach-ads4"],
    ["Review 5 Sao Xây Nhà", "review 5 sao xây nhà", "review-5-sao-xay-nha-ads4"],
    ["Khách Hàng Quanh Quận Tôi", "khách hàng quanh quận tôi", "khach-hang-quanh-quan-toi-ads4"],
    ["Dự Án Gần Khu Vực Bạn", "dự án gần khu vực bạn", "du-an-gan-khu-vuc-ban-ads4"],
    ["Nhà Thầu Uy Tín Gần Bạn", "nhà thầu uy tín gần bạn", "nha-thau-uy-tin-gan-ban-ads4"],
    ["Công Ty Xây Có Giấy Phép", "công ty xây có giấy phép", "cong-ty-xay-co-giay-phep-ads4"],
    ["Công Ty Xây Có Bảo Hiểm", "công ty xây có bảo hiểm", "cong-ty-xay-co-bao-hiem-ads4"],
    ["Công Ty Xây Có Showroom", "công ty xây có showroom", "cong-ty-xay-co-showroom-ads4"],
    ["Sao Khuê Có Gì Khác", "sao khuê có gì khác", "sao-khue-co-gi-khac-ads4"],
    ["Vì Sao Chọn Sao Khuê", "vì sao chọn sao khuê", "vi-sao-chon-sao-khue-ads4"],
    ["Cam Kết Của Sao Khuê", "cam kết của sao khuê", "cam-ket-cua-sao-khue-ads4"],
    ["Quy Trình Sao Khuê 5 Bước", "quy trình sao khuê 5 bước", "quy-trinh-sao-khue-5-buoc-ads4"],
    ["Liên Hệ Sao Khuê Ngay", "liên hệ sao khuê ngay", "lien-he-sao-khue-ngay-ads4"],
    ["Zalo Sao Khuê", "zalo sao khuê", "zalo-sao-khue-ads4"],
    ["Hotline Sao Khuê", "hotline sao khuê", "hotline-sao-khue-ads4"],
    ["Email Sao Khuê", "email sao khuê", "email-sao-khue-ads4"],
    ["Form Liên Hệ Xây Nhà", "form liên hệ xây nhà", "form-lien-he-xay-nha-ads4"],
    ["Form Liên Hệ Cải Tạo", "form liên hệ cải tạo", "form-lien-he-cai-tao-ads4"],
    ["CTA Nhận Tư Vấn Miễn Phí", "cta nhận tư vấn miễn phí", "cta-nhan-tu-van-mien-phi-ads4"],
    ["CTA Đặt Khảo Sát", "cta đặt khảo sát", "cta-dat-khao-sat-ads4"],
    ["CTA Xem Bảng Giá", "cta xem bảng giá", "cta-xem-bang-gia-ads4"],
    ["CTA Tải Checklist Xây", "cta tải checklist xây", "cta-tai-checklist-xay-ads4"],
    ["CTA Tải Mẫu Hợp Đồng", "cta tải mẫu hợp đồng", "cta-tai-mau-hop-dong-ads4"],
    ["Lead Magnet Xây Nhà", "lead magnet xây nhà", "lead-magnet-xay-nha-ads4"],
    ["Ebook Xây Nhà Miễn Phí", "ebook xây nhà miễn phí", "ebook-xay-nha-mien-phi-ads4"],
    ["Webinar Tư Vấn Xây 2026", "webinar tư vấn xây 2026", "webinar-tu-van-xay-2026-ads4"],
    ["Consultation Call Xây", "consultation call xây", "consultation-call-xay-ads4"],
    ["Discovery Call Cải Tạo", "discovery call cải tạo", "discovery-call-cai-tao-ads4"],
    ["Proposal Xây Nhà PDF", "proposal xây nhà pdf", "proposal-xay-nha-pdf-ads4"],
    ["Quotation Xây Nhà Excel", "quotation xây nhà excel", "quotation-xay-nha-excel-ads4"],
    ["Compare Quotes Xây Nhà", "compare quotes xây nhà", "compare-quotes-xay-nha-ads4"],
    ["Ready To Build 2026", "ready to build 2026", "ready-to-build-2026-ads4"],
    ["Start Building Today", "start building today", "start-building-today-ads4"],
    ["Renovate Now 2026", "renovate now 2026", "renovate-now-2026-ads4"],
    ["Get Started Xây Nhà", "get started xây nhà", "get-started-xay-nha-ads4"],
    ["Talk To Expert Xây", "talk to expert xây", "talk-to-expert-xay-ads4"],
    ["Book Free Consult", "book free consult", "book-free-consult-ads4"],
    ["Limited Offer Xây Nhà", "limited offer xây nhà", "limited-offer-xay-nha-ads4"],
    ["Last Slots This Month", "last slots this month", "last-slots-this-month-ads4"],
    ["Act Now Xây Nhà", "act now xây nhà", "act-now-xay-nha-ads4"],
    ["Don't Wait Xây Nhà", "dont wait xây nhà", "dont-wait-xay-nha-ads4"],
    ["Final CTA Sao Khuê", "final cta sao khuê", "final-cta-sao-khue-ads4"],
  ]);

  return [b50, b51, b52, b53, b54].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 4447 + (batch - 50) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    50: "Cluster: kết cấu, móng, gia cố chuyên sâu.",
    51: "Cluster: hoàn thiện hạng mục chi tiết.",
    52: "Cluster: geo Tây Nguyên, duyên hải miền Trung.",
    53: "Cluster: bảo trì, bảo hành, vòng đời nhà.",
    54: "Cluster: so sánh gói, intent mua, Ads cuối funnel.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: kết cấu, móng, gia cố chuyên sâu.",
  "Cluster: hoàn thiện hạng mục chi tiết.",
  "Cluster: geo Tây Nguyên, duyên hải miền Trung.",
  "Cluster: bảo trì, bảo hành, vòng đời nhà.",
  "Cluster: so sánh gói, intent mua, Ads cuối funnel.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 50 + i;
  const startNo = 4447 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 50 ? 49 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
