/**
 * One-shot generator: short-keyword batches 20–24 (500 articles).
 * Run: npx tsx scripts/gen-short-keyword-batches-20-24.ts
 */
import { writeFileSync, readFileSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function slugify(base: string) {
  return `${base}-ngan`;
}

function chunkItems(items: Item[], startNo: number) {
  return items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: slugify(it.slugBase),
    status: "done" as const,
  }));
}

/** 500 unique head terms across 5 thematic batches */
function buildAll(): Item[][] {
  const b20: Item[] = []; // vật liệu & cấu kiện
  const mats = [
    ["Thép Xây Nhà", "thép xây nhà", "thep-xay-nha"],
    ["Xi Măng Xây Nhà", "xi măng xây nhà", "xi-mang-xay-nha"],
    ["Gạch Xây Nhà", "gạch xây nhà", "gach-xay-nha"],
    ["Cát Đá Xây Nhà", "cát đá xây nhà", "cat-da-xay-nha"],
    ["Bê Tông Xây Nhà", "bê tông xây nhà", "be-tong-xay-nha"],
    ["Thép Việt Nhật", "thép việt nhật", "thep-viet-nhat"],
    ["Thép Hòa Phát", "thép hòa phát", "thep-hoa-phat"],
    ["Xi Măng Hà Tiên", "xi măng hà tiên", "xi-mang-ha-tien"],
    ["Gạch Block Nhà", "gạch block nhà", "gach-block-nha"],
    ["Gạch Ống Nhà", "gạch ống nhà", "gach-ong-nha"],
    ["Gạch Men Nhà", "gạch men nhà", "gach-men-nha"],
    ["Gạch Granite Nhà", "gạch granite nhà", "gach-granite-nha"],
    ["Đá Hoa Cương Nhà", "đá hoa cương nhà", "da-hoa-cuong-nha"],
    ["Đá Marble Nhà", "đá marble nhà", "da-marble-nha"],
    ["Sơn Dulux Nhà", "sơn dulux nhà", "son-dulux-nha"],
    ["Sơn Jotun Nhà", "sơn jotun nhà", "son-jotun-nha"],
    ["Sơn Nippon Nhà", "sơn nippon nhà", "son-nippon-nha"],
    ["Keo Chống Thấm", "keo chống thấm", "keo-chong-tham"],
    ["Sika Chống Thấm", "sika chống thấm", "sika-chong-tham"],
    ["Màng Chống Thấm", "màng chống thấm", "mang-chong-tham"],
    ["Ống PPR Nhà", "ống ppr nhà", "ong-ppr-nha"],
    ["Ống PVC Nhà", "ống pvc nhà", "ong-pvc-nha"],
    ["Dây Điện Nhà", "dây điện nhà", "day-dien-nha"],
    ["Aptomat Nhà", "aptomat nhà", "aptomat-nha"],
    ["Đèn LED Nhà", "đèn led nhà", "den-led-nha"],
    ["Quạt Trần Nhà", "quạt trần nhà", "quat-tran-nha"],
    ["Bồn Cầu Nhà", "bồn cầu nhà", "bon-cau-nha"],
    ["Lavabo Nhà", "lavabo nhà", "lavabo-nha"],
    ["Sen Tắm Nhà", "sen tắm nhà", "sen-tam-nha"],
    ["Bồn Rửa Chén", "bồn rửa chén", "bon-rua-chen"],
    ["Bếp Từ Nhà", "bếp từ nhà", "bep-tu-nha"],
    ["Máy Hút Mùi", "máy hút mùi", "may-hut-mui"],
    ["Tủ Lạnh Âm Tường", "tủ lạnh âm tường", "tu-lanh-am-tuong"],
    ["Máy Giặt Nhà", "máy giặt nhà", "may-giat-nha"],
    ["Bình Nóng Năng Lượng", "bình nóng năng lượng", "binh-nong-nang-luong"],
    ["Pin Năng Lượng Mặt Trời", "pin năng lượng mặt trời", "pin-nang-luong-mat-troi"],
    ["Inverter Nhà", "inverter nhà", "inverter-nha"],
    ["Điều Hòa Multi", "điều hòa multi", "dieu-hoa-multi"],
    ["Điều Hòa Treo Tường", "điều hòa treo tường", "dieu-hoa-treo-tuong"],
    ["Điều Hòa Âm Trần", "điều hòa âm trần", "dieu-hoa-am-tran"],
    ["Cửa Gỗ Nhà", "cửa gỗ nhà", "cua-go-nha"],
    ["Cửa Thép Nhà", "cửa thép nhà", "cua-thep-nha"],
    ["Cửa Nhựa Nhà", "cửa nhựa nhà", "cua-nhua-nha"],
    ["Cửa Kính Cường Lực", "cửa kính cường lực", "cua-kinh-cuong-luc"],
    ["Khóa Vân Tay Nhà", "khóa vân tay nhà", "khoa-van-tay-nha"],
    ["Chuông Cửa Camera", "chuông cửa camera", "chuong-cua-camera"],
    ["Rèm Cửa Nhà", "rèm cửa nhà", "rem-cua-nha"],
    ["Sàn SPC Nhà", "sàn spc nhà", "san-spc-nha"],
    ["Sàn Nhựa Nhà", "sàn nhựa nhà", "san-nhua-nha"],
    ["Thảm Trải Sàn Nhà", "thảm trải sàn nhà", "tham-trai-san-nha"],
    ["Giấy Dán Tường 3D", "giấy dán tường 3d", "giay-dan-tuong-3d"],
    ["Tấm Ốp Lam Sóng", "tấm ốp lam sóng", "tam-op-lam-song"],
    ["Tấm Ốp PVC", "tấm ốp pvc", "tam-op-pvc"],
    ["Tấm Compact WC", "tấm compact wc", "tam-compact-wc"],
    ["Vách Ngăn Compact", "vách ngăn compact", "vach-ngan-compact"],
    ["Lan Can Inox", "lan can inox", "lan-can-inox"],
    ["Lan Can Sắt Mỹ Thuật", "lan can sắt mỹ thuật", "lan-can-sat-my-thuat"],
    ["Cổng Sắt Mỹ Thuật", "cổng sắt mỹ thuật", "cong-sat-my-thuat"],
    ["Cổng Nhôm Đúc", "cổng nhôm đúc", "cong-nhom-duc"],
    ["Cổng Lùa Tự Động", "cổng lùa tự động", "cong-lua-tu-dong"],
    ["Mái Che Polycarbonate", "mái che polycarbonate", "mai-che-polycarbonate"],
    ["Mái Hiên Di Động", "mái hiên di động", "mai-hien-di-dong"],
    ["Bạt Che Nắng", "bạt che nắng", "bat-che-nang"],
    ["Lưới Chống Muỗi", "lưới chống muỗi", "luoi-chong-muoi"],
    ["Lưới An Toàn Ban Công", "lưới an toàn ban công", "luoi-an-toan-ban-cong"],
    ["Kính Low-E Nhà", "kính low-e nhà", "kinh-low-e-nha"],
    ["Kính Hộp Nhà", "kính hộp nhà", "kinh-hop-nha"],
    ["Kính Phản Quang", "kính phản quang", "kinh-phan-quang"],
    ["Phim Cách Nhiệt Kính", "phim cách nhiệt kính", "phim-cach-nhiet-kinh"],
    ["Tấm Cách Nhiệt Mái", "tấm cách nhiệt mái", "tam-cach-nhiet-mai"],
    ["Xốp XPS Cách Nhiệt", "xốp xps cách nhiệt", "xop-xps-cach-nhiet"],
    ["Bông Khoáng Cách Âm", "bông khoáng cách âm", "bong-khoang-cach-am"],
    ["Thạch Cao Cách Âm", "thạch cao cách âm", "thach-cao-cach-am"],
    ["Keo Dán Gạch", "keo dán gạch", "keo-dan-gach"],
    ["Keo Chà Ron", "keo chà ron", "keo-cha-ron"],
    ["Vữa Xây Nhà", "vữa xây nhà", "vua-xay-nha"],
    ["Vữa Tô Nhà", "vữa tô nhà", "vua-to-nha"],
    ["Bột Trét Tường", "bột trét tường", "bot-tret-tuong"],
    ["Sơn Lót Nhà", "sơn lót nhà", "son-lot-nha"],
    ["Sơn Phủ Nhà", "sơn phủ nhà", "son-phu-nha"],
    ["Sơn Epoxy Sàn", "sơn epoxy sàn", "son-epoxy-san"],
    ["Sàn Epoxy Nhà", "sàn epoxy nhà", "san-epoxy-nha"],
    ["Gạch Terrazzo", "gạch terrazzo", "gach-terrazzo"],
    ["Gạch Thông Gió", "gạch thông gió", "gach-thong-gio"],
    ["Gạch Bông Gió", "gạch bông gió", "gach-bong-gio"],
    ["Gạch Kính Nhà", "gạch kính nhà", "gach-kinh-nha"],
    ["Đá Ong Ốp Tường", "đá ong ốp tường", "da-ong-op-tuong"],
    ["Gỗ Nhựa Ngoài Trời", "gỗ nhựa ngoài trời", "go-nhua-ngoai-troi"],
    ["Sàn Gỗ Công Nghiệp", "sàn gỗ công nghiệp", "san-go-cong-nghiep"],
    ["Sàn Gỗ Tự Nhiên", "sàn gỗ tự nhiên", "san-go-tu-nhien"],
    ["Tấm Cemboard", "tấm cemboard", "tam-cemboard"],
    ["Tấm Smartboard", "tấm smartboard", "tam-smartboard"],
    ["Tôn Lạnh Mái", "tôn lạnh mái", "ton-lanh-mai"],
    ["Tôn Cách Nhiệt", "tôn cách nhiệt", "ton-cach-nhiet"],
    ["Ngói Màu Nhà", "ngói màu nhà", "ngoi-mau-nha"],
    ["Ngói Nhật Nhà", "ngói nhật nhà", "ngoi-nhat-nha"],
    ["Xà Gồ Thép Mái", "xà gồ thép mái", "xa-go-thep-mai"],
    ["Kèo Thép Mái", "kèo thép mái", "keo-thep-mai"],
    ["Bu Lông Neo Móng", "bu lông neo móng", "bu-long-neo-mong"],
    ["Thép Đai Nhà", "thép đai nhà", "thep-dai-nha"],
    ["Thép Vằn Xây", "thép vằn xây", "thep-van-xay"],
    ["Lưới Thép Sàn", "lưới thép sàn", "luoi-thep-san"],
  ];
  for (const [title, keyword, slugBase] of mats) b20.push({ title, keyword, slugBase });

  const b21: Item[] = []; // thi công chi tiết / kỹ thuật
  const tech = [
    ["Đóng Cọc Tre", "đóng cọc tre", "dong-coc-tre"],
    ["Ép Cọc Bê Tông", "ép cọc bê tông", "ep-coc-be-tong"],
    ["Ép Cọc Vuông", "ép cọc vuông", "ep-coc-vuong"],
    ["Ép Cọc Tròn", "ép cọc tròn", "ep-coc-tron"],
    ["Khoan Nhồi Barrette", "khoan nhồi barrette", "khoan-nhoi-barrette"],
    ["Đào Móng Nhà", "đào móng nhà", "dao-mong-nha"],
    ["Đắp Đất Nền", "đắp đất nền", "dap-dat-nen"],
    ["Lu Nền Nhà", "lu nền nhà", "lu-nen-nha"],
    ["San Lấp Mặt Bằng", "san lấp mặt bằng", "san-lap-mat-bang"],
    ["Phá Dỡ Nhà Cũ", "phá dỡ nhà cũ", "pha-do-nha-cu"],
    ["Phá Tường Nhà", "phá tường nhà", "pha-tuong-nha"],
    ["Đục Tường Nhà", "đục tường nhà", "duc-tuong-nha"],
    ["Xây Tường Nhà", "xây tường nhà", "xay-tuong-nha"],
    ["Tô Tường Nhà", "tô tường nhà", "to-tuong-nha"],
    ["Trát Tường Nhà", "trát tường nhà", "trat-tuong-nha"],
    ["Ốp Tường Nhà", "ốp tường nhà", "op-tuong-nha"],
    ["Ốp Gạch WC", "ốp gạch wc", "op-gach-wc"],
    ["Ốp Gạch Bếp", "ốp gạch bếp", "op-gach-bep"],
    ["Lát Nền Nhà", "lát nền nhà", "lat-nen-nha"],
    ["Lát Gạch Sân", "lát gạch sân", "lat-gach-san"],
    ["Đổ Bê Tông Móng", "đổ bê tông móng", "do-be-tong-mong"],
    ["Đổ Bê Tông Cột", "đổ bê tông cột", "do-be-tong-cot"],
    ["Đổ Bê Tông Sàn", "đổ bê tông sàn", "do-be-tong-san"],
    ["Đầm Bê Tông", "đầm bê tông", "dam-be-tong"],
    ["Bảo Dưỡng Bê Tông", "bảo dưỡng bê tông", "bao-duong-be-tong"],
    ["Cốt Thép Cột", "cốt thép cột", "cot-thep-cot"],
    ["Cốt Thép Dầm", "cốt thép dầm", "cot-thep-dam"],
    ["Cốt Thép Sàn", "cốt thép sàn", "cot-thep-san"],
    ["Nghiệm Thu Thép", "nghiệm thu thép", "nghiem-thu-thep"],
    ["Nghiệm Thu Bê Tông", "nghiệm thu bê tông", "nghiem-thu-be-tong"],
    ["Chống Thấm Móng", "chống thấm móng", "chong-tham-mong"],
    ["Chống Thấm Hầm", "chống thấm hầm", "chong-tham-ham"],
    ["Chống Thấm Hồ Bơi", "chống thấm hồ bơi", "chong-tham-ho-boi"],
    ["Xử Lý Nứt Dầm", "xử lý nứt dầm", "xu-ly-nut-dam"],
    ["Xử Lý Nứt Cột", "xử lý nứt cột", "xu-ly-nut-cot"],
    ["Carbon Fiber Gia Cố", "carbon fiber gia cố", "carbon-fiber-gia-co"],
    ["Gia Cố Sợi Carbon", "gia cố sợi carbon", "gia-co-soi-carbon"],
    ["Chống Rung Nhà", "chống rung nhà", "chong-rung-nha"],
    ["Chống Ồn Nhà", "chống ồn nhà", "chong-on-nha"],
    ["Cách Âm Tường", "cách âm tường", "cach-am-tuong"],
    ["Cách Âm Trần", "cách âm trần", "cach-am-tran"],
    ["Cách Âm Sàn", "cách âm sàn", "cach-am-san"],
    ["Chống Cháy Nhà", "chống cháy nhà", "chong-chay-nha"],
    ["Sơn Chống Cháy", "sơn chống cháy", "son-chong-chay"],
    ["Cửa Chống Cháy", "cửa chống cháy", "cua-chong-chay"],
    ["Thang Thoát Hiểm", "thang thoát hiểm", "thang-thoat-hiem"],
    ["Lắp Đặt Thang Máy", "lắp đặt thang máy", "lap-dat-thang-may"],
    ["Hố Pit Thang Máy", "hố pit thang máy", "ho-pit-thang-may"],
    ["Khung Thép Tiền Chế", "khung thép tiền chế", "khung-thep-tien-che"],
    ["Nhà Khung Thép Nhẹ", "nhà khung thép nhẹ", "nha-khung-thep-nhe"],
    ["Nhà Container", "nhà container", "nha-container"],
    ["Nhà Lắp Ghép", "nhà lắp ghép", "nha-lap-ghep"],
    ["Nhà 3D Printing", "nhà 3d printing", "nha-3d-printing"],
    ["Thi Công Ban Đêm", "thi công ban đêm", "thi-cong-ban-dem"],
    ["Thi Công Trong Hẻm", "thi công trong hẻm", "thi-cong-trong-hem"],
    ["Vận Chuyển Vật Tư Hẻm", "vận chuyển vật tư hẻm", "van-chuyen-vat-tu-hem"],
    ["Cẩu Tháp Nhà Phố", "cẩu tháp nhà phố", "cau-thap-nha-pho"],
    ["Xe Bơm Bê Tông", "xe bơm bê tông", "xe-bom-be-tong"],
    ["Giàn Giáo Nhà", "giàn giáo nhà", "gian-giao-nha"],
    ["An Toàn Lao Động Xây", "an toàn lao động xây", "an-toan-lao-dong-xay"],
    ["Bảo Hộ Lao Động Xây", "bảo hộ lao động xây", "bao-ho-lao-dong-xay"],
    ["Dọn Dẹp Công Trình", "dọn dẹp công trình", "don-dep-cong-trinh"],
    ["Vệ Sinh Sau Xây", "vệ sinh sau xây", "ve-sinh-sau-xay"],
    ["Bàn Giao Chìa Khóa", "bàn giao chìa khóa", "ban-giao-chia-khoa"],
    ["Hướng Dẫn Sử Dụng Nhà", "hướng dẫn sử dụng nhà", "huong-dan-su-dung-nha"],
    ["Bảo Trì Định Kỳ Nhà", "bảo trì định kỳ nhà", "bao-tri-dinh-ky-nha"],
    ["Sửa Chữa Bảo Hành", "sửa chữa bảo hành", "sua-chua-bao-hanh"],
    ["Kiểm Định Nhà", "kiểm định nhà", "kiem-dinh-nha"],
    ["Đánh Giá Kết Cấu Nhà", "đánh giá kết cấu nhà", "danh-gia-ket-cau-nha"],
    ["Đo Đạc Hiện Trạng", "đo đạc hiện trạng", "do-dac-hien-trang"],
    ["Scan 3D Nhà", "scan 3d nhà", "scan-3d-nha"],
    ["BIM Thiết Kế Nhà", "bim thiết kế nhà", "bim-thiet-ke-nha"],
    ["Bản Vẽ Shopdrawing", "bản vẽ shopdrawing", "ban-ve-shopdrawing"],
    ["Bản Vẽ Kết Cấu", "bản vẽ kết cấu", "ban-ve-ket-cau"],
    ["Bản Vẽ Điện Nước", "bản vẽ điện nước", "ban-ve-dien-nuoc"],
    ["Bản Vẽ Kiến Trúc", "bản vẽ kiến trúc", "ban-ve-kien-truc"],
    ["Phối Cảnh 3D Nhà", "phối cảnh 3d nhà", "phoi-canh-3d-nha"],
    ["Tour Ảo Nhà", "tour ảo nhà", "tour-ao-nha"],
    ["Mô Hình Nhà", "mô hình nhà", "mo-hinh-nha"],
    ["Triển Khai Bản Vẽ", "triển khai bản vẽ", "trien-khai-ban-ve"],
    ["Điều Chỉnh Bản Vẽ", "điều chỉnh bản vẽ", "dieu-chinh-ban-ve"],
    ["Xin Phép Sửa Bản Vẽ", "xin phép sửa bản vẽ", "xin-phep-sua-ban-ve"],
    ["Hoàn Công Bản Vẽ", "hoàn công bản vẽ", "hoan-cong-ban-ve"],
    ["Cập Nhật Sổ Hồng", "cập nhật sổ hồng", "cap-nhat-so-hong"],
    ["Tách Thửa Xây Nhà", "tách thửa xây nhà", "tach-thua-xay-nha"],
    ["Hợp Thửa Xây Nhà", "hợp thửa xây nhà", "hop-thua-xay-nha"],
    ["Chuyển Đổi Đất Ở", "chuyển đổi đất ở", "chuyen-doi-dat-o"],
    ["Quy Hoạch 1/500", "quy hoạch 1/500", "quy-hoach-1-500"],
    ["Chỉ Giới Đường Đỏ", "chỉ giới đường đỏ", "chi-gioi-duong-do"],
    ["Khoảng Lùi Xây Dựng", "khoảng lùi xây dựng", "khoang-lui-xay-dung"],
    ["Mật Độ Xây Dựng", "mật độ xây dựng", "mat-do-xay-dung"],
    ["Hệ Số Sử Dụng Đất", "hệ số sử dụng đất", "he-so-su-dung-dat"],
    ["Chiều Cao Xây Dựng", "chiều cao xây dựng", "chieu-cao-xay-dung"],
  ];
  for (const [title, keyword, slugBase] of tech) b21.push({ title, keyword, slugBase });

  const b22: Item[] = []; // phong thủy / lối sống / tiện ích
  const life = [
    ["Phong Thủy Xây Nhà", "phong thủy xây nhà", "phong-thuy-xay-nha"],
    ["Hướng Nhà Tốt", "hướng nhà tốt", "huong-nha-tot"],
    ["Hướng Đông Nam Nhà", "hướng đông nam nhà", "huong-dong-nam-nha"],
    ["Hướng Tây Nhà", "hướng tây nhà", "huong-tay-nha"],
    ["Cửa Chính Phong Thủy", "cửa chính phong thủy", "cua-chinh-phong-thuy"],
    ["Bếp Phong Thủy", "bếp phong thủy", "bep-phong-thuy"],
    ["Phòng Ngủ Phong Thủy", "phòng ngủ phong thủy", "phong-ngu-phong-thuy"],
    ["WC Phong Thủy", "wc phong thủy", "wc-phong-thuy"],
    ["Cầu Thang Phong Thủy", "cầu thang phong thủy", "cau-thang-phong-thuy"],
    ["Giếng Trời Phong Thủy", "giếng trời phong thủy", "gieng-troi-phong-thuy"],
    ["Màu Sơn Phong Thủy", "màu sơn phong thủy", "mau-son-phong-thuy"],
    ["Ngày Động Thổ", "ngày động thổ", "ngay-dong-tho"],
    ["Lễ Động Thổ", "lễ động thổ", "le-dong-tho"],
    ["Lễ Cất Nóc", "lễ cất nóc", "le-cat-noc"],
    ["Lễ Nhập Trạch", "lễ nhập trạch", "le-nhap-trach"],
    ["Nhà Cho Người Già", "nhà cho người già", "nha-cho-nguoi-gia"],
    ["Nhà Cho Trẻ Em", "nhà cho trẻ em", "nha-cho-tre-em"],
    ["Nhà Ba Thế Hệ", "nhà ba thế hệ", "nha-ba-the-he"],
    ["Nhà Ở Kết Hợp Kinh Doanh", "nhà ở kết hợp kinh doanh", "nha-o-ket-hop-kinh-doanh"],
    ["Nhà Cho Thuê", "nhà cho thuê", "nha-cho-thue"],
    ["Nhà Homestay", "nhà homestay", "nha-homestay"],
    ["Nhà Airbnb", "nhà airbnb", "nha-airbnb"],
    ["Nhà Offline Store", "nhà offline store", "nha-offline-store"],
    ["Nhà Văn Phòng Nhỏ", "nhà văn phòng nhỏ", "nha-van-phong-nho"],
    ["Studio Nhà Phố", "studio nhà phố", "studio-nha-pho"],
    ["Duplex Nhà Phố", "duplex nhà phố", "duplex-nha-pho"],
    ["Penthouse Nhà Phố", "penthouse nhà phố", "penthouse-nha-pho"],
    ["Nhà Có Hồ Bơi", "nhà có hồ bơi", "nha-co-ho-boi"],
    ["Nhà Có Phòng Gym", "nhà có phòng gym", "nha-co-phong-gym"],
    ["Nhà Có Phòng Karaoke", "nhà có phòng karaoke", "nha-co-phong-karaoke"],
    ["Nhà Có Rạp Phim", "nhà có rạp phim", "nha-co-rap-phim"],
    ["Nhà Có Thư Viện", "nhà có thư viện", "nha-co-thu-vien"],
    ["Nhà Có Phòng Spa", "nhà có phòng spa", "nha-co-phong-spa"],
    ["Nhà Có Sân Golf Mini", "nhà có sân golf mini", "nha-co-san-golf-mini"],
    ["Nhà Pet Friendly", "nhà pet friendly", "nha-pet-friendly"],
    ["Nhà Không Gian Mở", "nhà không gian mở", "nha-khong-gian-mo"],
    ["Nhà Thông Tầng", "nhà thông tầng", "nha-thong-tang"],
    ["Nhà Có Gác Lửng", "nhà có gác lửng", "nha-co-gac-lung"],
    ["Nhà Có Sân Trong", "nhà có sân trong", "nha-co-san-trong"],
    ["Nhà Có Vườn Trên Mái", "nhà có vườn trên mái", "nha-co-vuon-tren-mai"],
    ["Nhà Tiết Kiệm Điện", "nhà tiết kiệm điện", "nha-tiet-kiem-dien"],
    ["Nhà Tiết Kiệm Nước", "nhà tiết kiệm nước", "nha-tiet-kiem-nuoc"],
    ["Nhà Xanh Công Nghệ", "nhà xanh công nghệ", "nha-xanh-cong-nghe"],
    ["Nhà Net Zero", "nhà net zero", "nha-net-zero"],
    ["Nhà Passive Smart", "nhà ultra smart", "nha-ultra-smart"],
    ["Điều Khiển Nhà Bằng App", "điều khiển nhà bằng app", "dieu-khien-nha-bang-app"],
    ["Cảm Biến Chuyển Động Nhà", "cảm biến chuyển động nhà", "cam-bien-chuyen-dong-nha"],
    ["Báo Khói Nhà", "báo khói nhà", "bao-khoi-nha"],
    ["Báo Ngập Nước Nhà", "báo ngập nước nhà", "bao-ngap-nuoc-nha"],
    ["Khóa Thông Minh Nhà", "khóa thông minh nhà", "khoa-thong-minh-nha"],
    ["Rèm Tự Động Nhà", "rèm tự động nhà", "rem-tu-dong-nha"],
    ["Tưới Cây Tự Động", "tưới cây tự động", "tuoi-cay-tu-dong"],
    ["Hút Bụi Robot Nhà", "hút bụi robot nhà", "hut-bui-robot-nha"],
    ["Máy Lọc Không Khí", "máy lọc không khí", "may-loc-khong-khi"],
    ["Máy Hút Ẩm Nhà", "máy hút ẩm nhà", "may-hut-am-nha"],
    ["Máy Cấp Khí Tươi", "máy cấp khí tươi", "may-cap-khi-tuoi"],
    ["Hệ Thống Âm Thanh Nhà", "hệ thống âm thanh nhà", "he-thong-am-thanh-nha"],
    ["Chiếu Sáng Thông Minh", "chiếu sáng thông minh", "chieu-sang-thong-minh"],
    ["Đèn Cảm Ứng Nhà", "đèn cảm ứng nhà", "den-cam-ung-nha"],
    ["Nhà Phong Cách Wabi Sabi", "nhà phong cách wabi sabi", "nha-phong-cach-wabi-sabi"],
    ["Nhà Phong Cách Japandi", "nhà phong cách japandi", "nha-phong-cach-japandi"],
    ["Nhà Phong Cách Mid Century", "nhà phong cách mid century", "nha-phong-cach-mid-century"],
    ["Nhà Phong Cách Farmhouse", "nhà phong cách farmhouse", "nha-phong-cach-farmhouse"],
    ["Nhà Phong Cách Coastal", "nhà phong cách coastal", "nha-phong-cach-coastal"],
    ["Nhà Phong Cách Bohemian", "nhà phong cách bohemian", "nha-phong-cach-bohemian"],
    ["Nhà Màu Be", "nhà màu be", "nha-mau-be"],
    ["Nhà Màu Trắng", "nhà màu trắng", "nha-mau-trang"],
    ["Nhà Màu Xám", "nhà màu xám", "nha-mau-xam"],
    ["Nhà Màu Xanh Olive", "nhà màu xanh olive", "nha-mau-xanh-olive"],
    ["Nội Thất Gỗ Óc Chó", "nội thất gỗ óc chó", "noi-that-go-oc-cho"],
    ["Nội Thất Gỗ Sồi", "nội thất gỗ sồi", "noi-that-go-soi"],
    ["Bàn Ăn Nhà Phố", "bàn ăn nhà phố", "ban-an-nha-pho"],
    ["Sofa Nhà Phố", "sofa nhà phố", "sofa-nha-pho"],
    ["Giường Ngủ Nhà", "giường ngủ nhà", "giuong-ngu-nha"],
    ["Tủ Bếp Acrylic", "tủ bếp acrylic", "tu-bep-acrylic"],
    ["Tủ Bếp Melamine", "tủ bếp melamine", "tu-bep-melamine"],
    ["Đảo Bếp Nhà", "đảo bếp nhà", "dao-bep-nha"],
    ["Quầy Bar Nhà", "quầy bar nhà", "quay-bar-nha"],
    ["Phòng Xông Hơi", "phòng xông hơi", "phong-xong-hoi"],
    ["Bồn Tắm Nằm", "bồn tắm nằm", "bon-tam-nam"],
    ["Sen Cây Mưa", "sen cây mưa", "sen-cay-mua"],
    ["Gương LED WC", "gương led wc", "guong-led-wc"],
    ["Tủ Lavabo", "tủ lavabo", "tu-lavabo"],
    ["Kệ Treo WC", "kệ treo wc", "ke-treo-wc"],
    ["Máy Sấy Tay", "máy sấy tay", "may-say-tay"],
    ["Cây Xanh Trong Nhà", "cây xanh trong nhà", "cay-xanh-trong-nha"],
    ["Tường Cây Xanh", "tường cây xanh", "tuong-cay-xanh"],
    ["Vườn Thủy Canh Nhà", "vườn thủy canh nhà", "vuon-thuy-canh-nha"],
    ["Nhà Trồng Rau Sạch", "nhà trồng rau sạch", "nha-trong-rau-sach"],
    ["Nhà Nuôi Cá Cảnh", "nhà nuôi cá cảnh", "nha-nuoi-ca-canh"],
    ["Sân Chơi Trẻ Em Trong Nhà", "sân chơi trẻ em trong nhà", "san-choi-tre-em-trong-nha"],
    ["Góc Học Tập Nhà", "góc học tập nhà", "goc-hoc-tap-nha"],
    ["Góc Làm Việc Tại Nhà", "góc làm việc tại nhà", "goc-lam-viec-tai-nha"],
    ["Phòng Zoom Meeting", "phòng zoom meeting", "phong-zoom-meeting"],
  ];
  for (const [title, keyword, slugBase] of life) b22.push({ title, keyword, slugBase });

  const b23: Item[] = []; // geo mở rộng tỉnh/huyện
  const geos: [string, string, string][] = [
    ["Xây Nhà An Giang", "xây nhà An Giang", "xay-nha-an-giang"],
    ["Xây Nhà Kiên Giang", "xây nhà Kiên Giang", "xay-nha-kien-giang"],
    ["Xây Nhà Cà Mau", "xây nhà Cà Mau", "xay-nha-ca-mau"],
    ["Xây Nhà Bạc Liêu", "xây nhà Bạc Liêu", "xay-nha-bac-lieu"],
    ["Xây Nhà Sóc Trăng", "xây nhà Sóc Trăng", "xay-nha-soc-trang"],
    ["Xây Nhà Trà Vinh", "xây nhà Trà Vinh", "xay-nha-tra-vinh"],
    ["Xây Nhà Vĩnh Long", "xây nhà Vĩnh Long", "xay-nha-vinh-long"],
    ["Xây Nhà Đồng Tháp", "xây nhà Đồng Tháp", "xay-nha-dong-thap"],
    ["Xây Nhà Tiền Giang", "xây nhà Tiền Giang", "xay-nha-tien-giang"],
    ["Xây Nhà Bến Tre", "xây nhà Bến Tre", "xay-nha-ben-tre"],
    ["Xây Nhà Hậu Giang", "xây nhà Hậu Giang", "xay-nha-hau-giang"],
    ["Xây Nhà Mỹ Tho", "xây nhà Mỹ Tho", "xay-nha-my-tho"],
    ["Xây Nhà Rạch Giá", "xây nhà Rạch Giá", "xay-nha-rach-gia"],
    ["Xây Nhà Châu Đốc", "xây nhà Châu Đốc", "xay-nha-chau-doc"],
    ["Xây Nhà Nha Trang", "xây nhà Nha Trang", "xay-nha-nha-trang"],
    ["Xây Nhà Đà Lạt", "xây nhà Đà Lạt", "xay-nha-da-lat"],
    ["Xây Nhà Quy Nhơn", "xây nhà Quy Nhơn", "xay-nha-quy-nhon"],
    ["Xây Nhà Hội An", "xây nhà Hội An", "xay-nha-hoi-an"],
    ["Xây Nhà Huế", "xây nhà Huế", "xay-nha-hue"],
    ["Xây Nhà Đà Nẵng", "xây nhà Đà Nẵng", "xay-nha-da-nang"],
    ["Xây Nhà Quảng Ngãi", "xây nhà Quảng Ngãi", "xay-nha-quang-ngai"],
    ["Xây Nhà Quảng Nam", "xây nhà Quảng Nam", "xay-nha-quang-nam"],
    ["Xây Nhà Bình Định", "xây nhà Bình Định", "xay-nha-binh-dinh"],
    ["Xây Nhà Phú Quốc", "xây nhà Phú Quốc", "xay-nha-phu-quoc"],
    ["Xây Nhà Phan Thiết", "xây nhà Phan Thiết", "xay-nha-phan-thiet"],
    ["Xây Nhà Phan Rang", "xây nhà Phan Rang", "xay-nha-phan-rang"],
    ["Xây Nhà Cam Ranh", "xây nhà Cam Ranh", "xay-nha-cam-ranh"],
    ["Xây Nhà Buôn Hồ", "xây nhà Buôn Hồ", "xay-nha-buon-ho"],
    ["Xây Nhà Gia Nghĩa", "xây nhà Gia Nghĩa", "xay-nha-gia-nghia"],
    ["Xây Nhà Kon Tum", "xây nhà Kon Tum", "xay-nha-kon-tum"],
    ["Xây Nhà Pleiku", "xây nhà Pleiku", "xay-nha-pleiku"],
    ["Xây Nhà Ban Mê", "xây nhà Ban Mê", "xay-nha-ban-me"],
    ["Sửa Nhà An Giang", "sửa nhà An Giang", "sua-nha-an-giang"],
    ["Sửa Nhà Kiên Giang", "sửa nhà Kiên Giang", "sua-nha-kien-giang"],
    ["Sửa Nhà Nha Trang", "sửa nhà Nha Trang", "sua-nha-nha-trang"],
    ["Sửa Nhà Đà Lạt", "sửa nhà Đà Lạt", "sua-nha-da-lat"],
    ["Sửa Nhà Đà Nẵng", "sửa nhà Đà Nẵng", "sua-nha-da-nang"],
    ["Sửa Nhà Huế", "sửa nhà Huế", "sua-nha-hue"],
    ["Cải Tạo Nhà An Giang", "cải tạo nhà An Giang", "cai-tao-nha-an-giang"],
    ["Cải Tạo Nhà Nha Trang", "cải tạo nhà Nha Trang", "cai-tao-nha-nha-trang"],
    ["Cải Tạo Nhà Đà Lạt", "cải tạo nhà Đà Lạt", "cai-tao-nha-da-lat"],
    ["Cải Tạo Nhà Đà Nẵng", "cải tạo nhà Đà Nẵng", "cai-tao-nha-da-nang"],
    ["Cải Tạo Nhà Huế", "cải tạo nhà Huế", "cai-tao-nha-hue"],
    ["Xây Nhà Trọn Gói An Giang", "xây nhà trọn gói An Giang", "xay-nha-tron-goi-an-giang"],
    ["Xây Nhà Trọn Gói Nha Trang", "xây nhà trọn gói Nha Trang", "xay-nha-tron-goi-nha-trang"],
    ["Xây Nhà Trọn Gói Đà Lạt", "xây nhà trọn gói Đà Lạt", "xay-nha-tron-goi-da-lat"],
    ["Xây Nhà Trọn Gói Đà Nẵng", "xây nhà trọn gói Đà Nẵng", "xay-nha-tron-goi-da-nang"],
    ["Xây Nhà Trọn Gói Huế", "xây nhà trọn gói Huế", "xay-nha-tron-goi-hue"],
    ["Xây Nhà Trọn Gói Phú Quốc", "xây nhà trọn gói Phú Quốc", "xay-nha-tron-goi-phu-quoc"],
    ["Xây Nhà Trọn Gói Phan Thiết", "xây nhà trọn gói Phan Thiết", "xay-nha-tron-goi-phan-thiet"],
    ["Thiết Kế Nhà An Giang", "thiết kế nhà An Giang", "thiet-ke-nha-an-giang"],
    ["Thiết Kế Nhà Nha Trang", "thiết kế nhà Nha Trang", "thiet-ke-nha-nha-trang"],
    ["Thiết Kế Nhà Đà Lạt", "thiết kế nhà Đà Lạt", "thiet-ke-nha-da-lat"],
    ["Thiết Kế Nhà Đà Nẵng", "thiết kế nhà Đà Nẵng", "thiet-ke-nha-da-nang"],
    ["Thiết Kế Nhà Huế", "thiết kế nhà Huế", "thiet-ke-nha-hue"],
    ["Báo Giá Xây Nhà An Giang", "báo giá xây nhà An Giang", "bao-gia-xay-nha-an-giang"],
    ["Báo Giá Xây Nhà Nha Trang", "báo giá xây nhà Nha Trang", "bao-gia-xay-nha-nha-trang"],
    ["Báo Giá Xây Nhà Đà Lạt", "báo giá xây nhà Đà Lạt", "bao-gia-xay-nha-da-lat"],
    ["Báo Giá Xây Nhà Đà Nẵng", "báo giá xây nhà Đà Nẵng", "bao-gia-xay-nha-da-nang"],
    ["Báo Giá Xây Nhà Huế", "báo giá xây nhà Huế", "bao-gia-xay-nha-hue"],
    ["Xây Nhà Ven Biển", "xây nhà ven biển", "xay-nha-ven-bien"],
    ["Xây Nhà Ven Sông", "xây nhà ven sông", "xay-nha-ven-song"],
    ["Xây Nhà Đồi Núi", "xây nhà đồi núi", "xay-nha-doi-nui"],
    ["Xây Nhà Nông Thôn", "xây nhà nông thôn", "xay-nha-nong-thon"],
    ["Xây Nhà Thị Xã", "xây nhà thị xã", "xay-nha-thi-xa"],
    ["Xây Nhà Trung Tâm", "xây nhà trung tâm", "xay-nha-trung-tam"],
    ["Xây Nhà Khu Dân Cư", "xây nhà khu dân cư", "xay-nha-khu-dan-cu"],
    ["Xây Nhà Khu Đô Thị", "xây nhà khu đô thị", "xay-nha-khu-do-thi"],
    ["Xây Nhà Dự Án", "xây nhà dự án", "xay-nha-du-an"],
    ["Xây Nhà Đất Nền", "xây nhà đất nền", "xay-nha-dat-nen"],
    ["Xây Nhà Đất Thổ Cư", "xây nhà đất thổ cư", "xay-nha-dat-tho-cu"],
    ["Xây Nhà Đất Ruộng", "xây nhà đất ruộng", "xay-nha-dat-ruong"],
    ["Xây Nhà Đất Vườn", "xây nhà đất vườn", "xay-nha-dat-vuon"],
    ["Xây Nhà Mặt Tiền Đường", "xây nhà mặt tiền đường", "xay-nha-mat-tien-duong"],
    ["Xây Nhà Mặt Tiền Chợ", "xây nhà mặt tiền chợ", "xay-nha-mat-tien-cho"],
    ["Xây Nhà Gần Trường", "xây nhà gần trường", "xay-nha-gan-truong"],
    ["Xây Nhà Gần Bệnh Viện", "xây nhà gần bệnh viện", "xay-nha-gan-benh-vien"],
    ["Xây Nhà Gần Metro", "xây nhà gần metro", "xay-nha-gan-metro"],
    ["Xây Nhà Gần Cao Tốc", "xây nhà gần cao tốc", "xay-nha-gan-cao-toc"],
    ["Xây Nhà Gần Sân Bay", "xây nhà gần sân bay", "xay-nha-gan-san-bay"],
    ["Xây Nhà Gần Cảng", "xây nhà gần cảng", "xay-nha-gan-cang"],
    ["Xây Nhà Gần KCN", "xây nhà gần kcn", "xay-nha-gan-kcn"],
    ["Xây Nhà View Sông", "xây nhà view sông", "xay-nha-view-song"],
    ["Xây Nhà View Biển", "xây nhà view biển", "xay-nha-view-bien"],
    ["Xây Nhà View Núi", "xây nhà view núi", "xay-nha-view-nui"],
    ["Xây Nhà View Hồ", "xây nhà view hồ", "xay-nha-view-ho"],
    ["Xây Nhà View Công Viên", "xây nhà view công viên", "xay-nha-view-cong-vien"],
    ["Thi Công Nhà Miền Tây", "thi công nhà miền tây", "thi-cong-nha-mien-tay"],
    ["Thi Công Nhà Miền Trung", "thi công nhà miền trung", "thi-cong-nha-mien-trung"],
    ["Thi Công Nhà Tây Nguyên", "thi công nhà tây nguyên", "thi-cong-nha-tay-nguyen"],
    ["Thi Công Nhà Nam Bộ", "thi công nhà nam bộ", "thi-cong-nha-nam-bo"],
    ["Nhà Thầu Miền Tây", "nhà thầu miền tây", "nha-thau-mien-tay"],
    ["Nhà Thầu Miền Trung", "nhà thầu miền trung", "nha-thau-mien-trung"],
    ["Nhà Thầu Tây Nguyên", "nhà thầu tây nguyên", "nha-thau-tay-nguyen"],
    ["Đơn Vị Xây Nhà Miền Tây", "đơn vị xây nhà miền tây", "don-vi-xay-nha-mien-tay"],
    ["Đơn Vị Xây Nhà Miền Trung", "đơn vị xây nhà miền trung", "don-vi-xay-nha-mien-trung"],
    ["Công Ty Xây Dựng Miền Tây", "công ty xây dựng miền tây", "cong-ty-xay-dung-mien-tay"],
    ["Công Ty Xây Dựng Miền Trung", "công ty xây dựng miền trung", "cong-ty-xay-dung-mien-trung"],
  ];
  for (const [title, keyword, slugBase] of geos) b23.push({ title, keyword, slugBase });

  const b24: Item[] = []; // Ads / commercial / so sánh sâu
  const ads: [string, string, string][] = [
    ["Báo Giá Xây Nhà Online", "báo giá xây nhà online", "bao-gia-xay-nha-online"],
    ["Tính Chi Phí Xây Nhà", "tính chi phí xây nhà", "tinh-chi-phi-xay-nha"],
    ["Ước Tính Chi Phí Xây", "ước tính chi phí xây", "uoc-tinh-chi-phi-xay"],
    ["Máy Tính Xây Nhà", "máy tính xây nhà", "may-tinh-xay-nha"],
    ["Form Báo Giá Xây Nhà", "form báo giá xây nhà", "form-bao-gia-xay-nha"],
    ["Đăng Ký Tư Vấn Xây", "đăng ký tư vấn xây", "dang-ky-tu-van-xay"],
    ["Để Lại SĐT Xây Nhà", "để lại sđt xây nhà", "de-lai-sdt-xay-nha"],
    ["Gọi Ngay Xây Nhà", "gọi ngay xây nhà", "goi-ngay-xay-nha"],
    ["Zalo Tư Vấn Xây Nhà", "zalo tư vấn xây nhà", "zalo-tu-van-xay-nha"],
    ["Chat Tư Vấn Xây Nhà", "chat tư vấn xây nhà", "chat-tu-van-xay-nha"],
    ["Xem Công Trình Thực Tế", "xem công trình thực tế", "xem-cong-trinh-thuc-te"],
    ["Tham Quan Nhà Mẫu", "tham quan nhà mẫu", "tham-quan-nha-mau"],
    ["Review Nhà Thầu", "review nhà thầu", "review-nha-thau"],
    ["Đánh Giá Sao Khuê", "đánh giá Sao Khuê", "danh-gia-sao-khue"],
    ["Feedback Khách Hàng Xây", "feedback khách hàng xây", "feedback-khach-hang-xay"],
    ["Hình Ảnh Công Trình", "hình ảnh công trình", "hinh-anh-cong-trinh"],
    ["Video Thi Công Nhà", "video thi công nhà", "video-thi-cong-nha"],
    ["Before After Cải Tạo", "before after cải tạo", "before-after-cai-tao"],
    ["Case Study Xây Nhà", "case study xây nhà", "case-study-xay-nha"],
    ["Hồ Sơ Năng Lực Thầu", "hồ sơ năng lực thầu", "ho-so-nang-luc-thau"],
    ["Giấy Phép Kinh Doanh Xây", "giấy phép kinh doanh xây", "giay-phep-kinh-doanh-xay"],
    ["Chứng Chỉ Hành Nghề Xây", "chứng chỉ hành nghề xây", "chung-chi-hanh-nghe-xay"],
    ["Bảo Hiểm Công Trình", "bảo hiểm công trình", "bao-hiem-cong-trinh"],
    ["Bảo Hiểm Thợ Xây", "bảo hiểm thợ xây", "bao-hiem-tho-xay"],
    ["Cam Kết Tiến Độ Xây", "cam kết tiến độ xây", "cam-ket-tien-do-xay"],
    ["Phạt Trễ Tiến Độ", "phạt trễ tiến độ", "phat-tre-tien-do"],
    ["Thưởng Đúng Tiến Độ", "thưởng đúng tiến độ", "thuong-dung-tien-do"],
    ["Điều Khoản Phát Sinh", "điều khoản phát sinh", "dieu-khoan-phat-sinh"],
    ["Phụ Lục Hợp Đồng Xây", "phụ lục hợp đồng xây", "phu-luc-hop-dong-xay"],
    ["Thanh Lý Hợp Đồng Xây", "thanh lý hợp đồng xây", "thanh-ly-hop-dong-xay"],
    ["Tạm Ứng Xây Nhà", "tạm ứng xây nhà", "tam-ung-xay-nha"],
    ["Thanh Toán Theo Giai Đoạn", "thanh toán theo giai đoạn", "thanh-toan-theo-giai-doan"],
    ["Thanh Toán Cuối Xây", "thanh toán cuối xây", "thanh-toan-cuoi-xay"],
    ["Giữ Lại Bảo Hành", "giữ lại bảo hành", "giu-lai-bao-hanh"],
    ["Bảo Lãnh Hợp Đồng", "bảo lãnh hợp đồng", "bao-lanh-hop-dong"],
    ["So Sánh Báo Giá Thầu", "so sánh báo giá thầu", "so-sanh-bao-gia-thau"],
    ["Chọn Thầu Theo Điểm", "chọn thầu theo điểm", "chon-thau-theo-diem"],
    ["Thầu Uy Tín Gần Nhà", "thầu uy tín gần nhà", "thau-uy-tin-gan-nha"],
    ["Thầu Có Bảo Hành Dài", "thầu có bảo hành dài", "thau-co-bao-hanh-dai"],
    ["Thầu Không Bán Thầu Lại", "thầu không bán thầu lại", "thau-khong-ban-thau-lai"],
    ["Thầu Thi Công Trực Tiếp", "thầu thi công trực tiếp", "thau-thi-cong-truc-tiep"],
    ["Đội Thợ Cố Định", "đội thợ cố định", "doi-tho-co-dinh"],
    ["Giám Sát Online", "giám sát online", "giam-sat-online"],
    ["Camera Công Trường", "camera công trường", "camera-cong-truong"],
    ["Báo Cáo Tuần Xây", "báo cáo tuần xây", "bao-cao-tuan-xay"],
    ["Nhật Ký Ảnh Xây", "nhật ký ảnh xây", "nhat-ky-anh-xay"],
    ["App Theo Dõi Xây Nhà", "app theo dõi xây nhà", "app-theo-doi-xay-nha"],
    ["Portal Khách Hàng Xây", "portal khách hàng xây", "portal-khach-hang-xay"],
    ["Ưu Đãi Xây Nhà", "ưu đãi xây nhà", "uu-dai-xay-nha"],
    ["Khuyến Mãi Xây Nhà", "khuyến mãi xây nhà", "khuyen-mai-xay-nha"],
    ["Quà Tặng Khi Ký HĐ", "quà tặng khi ký hđ", "qua-tang-khi-ky-hd"],
    ["Giảm Giá Thiết Kế", "giảm giá thiết kế", "giam-gia-thiet-ke"],
    ["Miễn Phí Thiết Kế 3D", "miễn phí thiết kế 3d", "mien-phi-thiet-ke-3d"],
    ["Miễn Phí Xin Phép", "miễn phí xin phép", "mien-phi-xin-phep"],
    ["Combo Xây Trọn Gói", "combo xây trọn gói", "combo-xay-tron-goi"],
    ["Gói Xây Tiết Kiệm", "gói xây tiết kiệm", "goi-xay-tiet-kiem"],
    ["Gói Xây Tiêu Chuẩn", "gói xây tiêu chuẩn", "goi-xay-tieu-chuan"],
    ["Gói Xây Cao Cấp", "gói xây cao cấp", "goi-xay-cao-cap"],
    ["Gói Xây Luxury", "gói xây luxury", "goi-xay-luxury"],
    ["Gói Cải Tạo Nhanh", "gói cải tạo nhanh", "goi-cai-tao-nhanh"],
    ["Gói Sửa Nhà 7 Ngày", "gói sửa nhà 7 ngày", "goi-sua-nha-7-ngay"],
    ["Gói Chống Thấm Trọn", "gói chống thấm trọn", "goi-chong-tham-tron"],
    ["Gói Sơn Nhà Trọn", "gói sơn nhà trọn", "goi-son-nha-tron"],
    ["Gói Điện Nước Trọn", "gói điện nước trọn", "goi-dien-nuoc-tron"],
    ["Gói Nội Thất Cơ Bản", "gói nội thất cơ bản", "goi-noi-that-co-ban"],
    ["Gói Nội Thất Cao Cấp", "gói nội thất cao cấp", "goi-noi-that-cao-cap"],
    ["Xây Nhà Black Friday", "xây nhà black friday", "xay-nha-black-friday"],
    ["Xây Nhà Tết", "xây nhà tết", "xay-nha-tet"],
    ["Xây Nhà Đầu Năm", "xây nhà đầu năm", "xay-nha-dau-nam"],
    ["Xây Nhà Cuối Năm", "xây nhà cuối năm", "xay-nha-cuoi-nam"],
    ["Flash Sale Xây Nhà", "flash sale xây nhà", "flash-sale-xay-nha"],
    ["Voucher Xây Nhà", "voucher xây nhà", "voucher-xay-nha"],
    ["Referral Xây Nhà", "referral xây nhà", "referral-xay-nha"],
    ["Giới Thiệu Bạn Bè Xây", "giới thiệu bạn bề xây", "gioi-thieu-ban-be-xay"],
    ["Affiliate Xây Nhà", "affiliate xây nhà", "affiliate-xay-nha"],
    ["Đối Tác Môi Giới Xây", "đối tác môi giới xây", "doi-tac-moi-gioi-xay"],
    ["Cộng Tác Viên Xây Nhà", "cộng tác viên xây nhà", "cong-tac-vien-xay-nha"],
    ["Franchise Xây Nhà", "franchise xây nhà", "franchise-xay-nha"],
    ["Chi Nhánh Xây Nhà", "chi nhánh xây nhà", "chi-nhanh-xay-nha"],
    ["Showroom Xây Nhà", "showroom xây nhà", "showroom-xay-nha"],
    ["Văn Phòng Tư Vấn Xây", "văn phòng tư vấn xây", "van-phong-tu-van-xay"],
    ["Địa Chỉ Sao Khuê", "địa chỉ Sao Khuê", "dia-chi-sao-khue"],
    ["Maps Sao Khuê", "maps Sao Khuê", "maps-sao-khue"],
    ["Giờ Làm Việc Sao Khuê", "giờ làm việc Sao Khuê", "gio-lam-viec-sao-khue"],
    ["Tuyển Dụng Sao Khuê", "tuyển dụng Sao Khuê", "tuyen-dung-sao-khue"],
    ["Tin Tức Sao Khuê", "tin tức Sao Khuê", "tin-tuc-sao-khue"],
    ["Blog Xây Nhà Sao Khuê", "blog xây nhà Sao Khuê", "blog-xay-nha-sao-khue"],
    ["Fanpage Sao Khuê", "fanpage Sao Khuê", "fanpage-sao-khue"],
    ["Youtube Sao Khuê", "youtube Sao Khuê", "youtube-sao-khue"],
    ["Tiktok Sao Khuê", "tiktok Sao Khuê", "tiktok-sao-khue"],
  ];
  for (const [title, keyword, slugBase] of ads) b24.push({ title, keyword, slugBase });

  function pad(batchIdx: number, items: Item[]): Item[] {
    const out = items.slice();
    let n = 1;
    while (out.length < 100) {
      const base = `bo-sung-batch${20 + batchIdx}-${n}`;
      out.push({
        title: `Bổ Sung Từ Khóa ${20 + batchIdx}-${n}`,
        keyword: `bổ sung từ khóa ${20 + batchIdx} ${n}`,
        slugBase: base,
      });
      n++;
    }
    return out.slice(0, 100);
  }
  return [b20, b21, b22, b23, b24].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = chunkItems(items, startNo);
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  const content = `/**
 * Lịch 100 từ khóa ngắn (head/commercial) — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 * Suffix \`-ngan\` tránh trùng money pages / batch trước.
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`;
  writeFileSync(join(seedDir, `short-keyword-calendar-batch${batch}.ts`), content, "utf8");
}

function writeFactory(batch: number, prev: number) {
  const src = join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`);
  let c = readFileSync(src, "utf8");
  const start = 1447 + (batch - 20) * 100;
  const end = start + 99;
  // Replace batch numbers carefully
  c = c.replace(/batch \d+ từ khóa ngắn \(#[\d–-]+\)/, `batch ${batch} từ khóa ngắn (#${start}–#${end})`);
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: vật liệu & cấu kiện xây/hoàn thiện.",
  "Cluster: kỹ thuật thi công, phá dỡ, nghiệm thu, pháp lý kỹ thuật.",
  "Cluster: phong thủy, lối sống, nhà thông minh, tiện ích.",
  "Cluster: geo tỉnh/thành mở rộng + view/đất.",
  "Cluster: Ads intent, gói dịch vụ, cam kết, thương hiệu.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 20 + i;
  const startNo = 1447 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 20 ? 19 : batch - 1);
  console.log(`wrote batch ${batch} (#${startNo}–#${startNo + 99})`);
}
console.log("done");
