/**
 * Generator: short-keyword batches 30–34 (500 articles, #2447–#2946).
 * Run: npx tsx scripts/gen-short-keyword-batches-30-34.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${30 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${30 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${30 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 30 — chi phí / đơn giá / vật tư / tối ưu ngân sách
  const b30 = pairs([
    ["Đơn Giá Xây Nhà 2026", "đơn giá xây nhà 2026", "don-gia-xay-nha-2026"],
    ["Đơn Giá Cải Tạo 2026", "đơn giá cải tạo 2026", "don-gia-cai-tao-2026"],
    ["Đơn Giá Phần Thô 2026", "đơn giá phần thô 2026", "don-gia-phan-tho-2026"],
    ["Đơn Giá Hoàn Thiện 2026", "đơn giá hoàn thiện 2026", "don-gia-hoan-thien-2026"],
    ["Giá Nhân Công Xây Nhà", "giá nhân công xây nhà", "gia-nhan-cong-xay-nha"],
    ["Giá Nhân Công Thợ Hồ", "giá nhân công thợ hồ", "gia-nhan-cong-tho-ho"],
    ["Giá Nhân Công Thợ Điện", "giá nhân công thợ điện", "gia-nhan-cong-tho-dien"],
    ["Giá Nhân Công Thợ Nước", "giá nhân công thợ nước", "gia-nhan-cong-tho-nuoc"],
    ["Giá Nhân Công Thợ Sơn", "giá nhân công thợ sơn", "gia-nhan-cong-tho-son"],
    ["Giá Nhân Công Thợ Ốp Lát", "giá nhân công thợ ốp lát", "gia-nhan-cong-tho-op-lat"],
    ["Giá Xi Măng Xây Nhà", "giá xi măng xây nhà", "gia-xi-mang-xay-nha"],
    ["Giá Thép Xây Nhà", "giá thép xây nhà", "gia-thep-xay-nha"],
    ["Giá Gạch Xây Nhà", "giá gạch xây nhà", "gia-gach-xay-nha"],
    ["Giá Cát Đá Xây Nhà", "giá cát đá xây nhà", "gia-cat-da-xay-nha"],
    ["Giá Bê Tông Tươi", "giá bê tông tươi", "gia-be-tong-tuoi"],
    ["Giá Tôn Lợp Mái", "giá tôn lợp mái", "gia-ton-lop-mai"],
    ["Giá Ngói Lợp Mái", "giá ngói lợp mái", "gia-ngoi-lop-mai"],
    ["Giá Sơn Nhà Phố", "giá sơn nhà phố", "gia-son-nha-pho"],
    ["Giá Gạch Ốp Lát", "giá gạch ốp lát", "gia-gach-op-lat"],
    ["Giá Trần Thạch Cao", "giá trần thạch cao", "gia-tran-thach-cao"],
    ["Giá Cửa Nhôm Kính", "giá cửa nhôm kính", "gia-cua-nhom-kinh"],
    ["Giá Cửa Gỗ Công Nghiệp", "giá cửa gỗ công nghiệp", "gia-cua-go-cong-nghiep"],
    ["Giá Lan Can Inox", "giá lan can inox", "gia-lan-can-inox"],
    ["Giá Lan Can Kính", "giá lan can kính", "gia-lan-can-kinh"],
    ["Giá Cầu Thang Gỗ", "giá cầu thang gỗ", "gia-cau-thang-go"],
    ["Giá Cầu Thang Sắt", "giá cầu thang sắt", "gia-cau-thang-sat"],
    ["Giá Sàn Gỗ Công Nghiệp", "giá sàn gỗ công nghiệp", "gia-san-go-cong-nghiep"],
    ["Giá Sàn Nhựa SPC", "giá sàn nhựa spc", "gia-san-nhua-spc"],
    ["Giá Tủ Bếp Acrylic", "giá tủ bếp acrylic", "gia-tu-bep-acrylic"],
    ["Giá Tủ Bếp Melamine", "giá tủ bếp melamine", "gia-tu-bep-melamine"],
    ["Giá Bồn Cầu Inax", "giá bồn cầu inax", "gia-bon-cau-inax"],
    ["Giá Sen Tắm Toto", "giá sen tắm toto", "gia-sen-tam-toto"],
    ["Giá Máy Nước Nóng", "giá máy nước nóng", "gia-may-nuoc-nong"],
    ["Giá Bơm Nước Gia Đình", "giá bơm nước gia đình", "gia-bom-nuoc-gia-dinh"],
    ["Giá Hệ Thống Điện Nhà", "giá hệ thống điện nhà", "gia-he-thong-dien-nha"],
    ["Giá Hệ Thống Nước Nhà", "giá hệ thống nước nhà", "gia-he-thong-nuoc-nha"],
    ["Chi Phí Xin Phép Xây", "chi phí xin phép xây", "chi-phi-xin-phep-xay"],
    ["Chi Phí Giám Sát Xây", "chi phí giám sát xây", "chi-phi-giam-sat-xay"],
    ["Chi Phí Thiết Kế Nhà", "chi phí thiết kế nhà", "chi-phi-thiet-ke-nha"],
    ["Chi Phí Khảo Sát Địa Chất", "chi phí khảo sát địa chất", "chi-phi-khao-sat-dia-chat"],
    ["Chi Phí Ép Cọc Nhà Phố", "chi phí ép cọc nhà phố", "chi-phi-ep-coc-nha-pho"],
    ["Chi Phí Phá Dỡ Nhà Cũ", "chi phí phá dỡ nhà cũ", "chi-phi-pha-do-nha-cu"],
    ["Chi Phí Vận Chuyển Phế Thải", "chi phí vận chuyển phế thải", "chi-phi-van-chuyen-phe-thai"],
    ["Chi Phí Chống Thấm Mái", "chi phí chống thấm mái", "chi-phi-chong-tham-mai"],
    ["Chi Phí Chống Thấm WC", "chi phí chống thấm wc", "chi-phi-chong-tham-wc"],
    ["Chi Phí Cách Nhiệt Mái", "chi phí cách nhiệt mái", "chi-phi-cach-nhiet-mai"],
    ["Chi Phí Cách Âm Phòng", "chi phí cách âm phòng", "chi-phi-cach-am-phong"],
    ["Tối Ưu Ngân Sách Xây Nhà", "tối ưu ngân sách xây nhà", "toi-uu-ngan-sach-xay-nha"],
    ["Cắt Giảm Chi Phí Xây Nhà", "cắt giảm chi phí xây nhà", "cat-giam-chi-phi-xay-nha"],
    ["Tiết Kiệm Chi Phí Cải Tạo", "tiết kiệm chi phí cải tạo", "tiet-kiem-chi-phi-cai-tao"],
    ["So Sánh Giá Thầu Xây", "so sánh giá thầu xây", "so-sanh-gia-thau-xay"],
    ["Báo Giá Ẩn Xây Nhà", "báo giá ẩn xây nhà", "bao-gia-an-xay-nha"],
    ["Phí Phát Sinh Xây Nhà", "phí phát sinh xây nhà", "phi-phat-sinh-xay-nha"],
    ["Dự Phòng Ngân Sách Xây", "dự phòng ngân sách xây", "du-phong-ngan-sach-xay"],
    ["Tỷ Lệ Phát Sinh Hợp Lý", "tỷ lệ phát sinh hợp lý", "ty-le-phat-sinh-hop-ly"],
    ["Giá Xây Nhà 40m2", "giá xây nhà 40m2", "gia-xay-nha-40m2"],
    ["Giá Xây Nhà 50m2", "giá xây nhà 50m2", "gia-xay-nha-50m2"],
    ["Giá Xây Nhà 60m2", "giá xây nhà 60m2", "gia-xay-nha-60m2"],
    ["Giá Xây Nhà 80m2", "giá xây nhà 80m2", "gia-xay-nha-80m2"],
    ["Giá Xây Nhà 100m2", "giá xây nhà 100m2", "gia-xay-nha-100m2"],
    ["Giá Xây Nhà 120m2", "giá xây nhà 120m2", "gia-xay-nha-120m2"],
    ["Giá Xây Nhà 150m2", "giá xây nhà 150m2", "gia-xay-nha-150m2"],
    ["Giá Xây Nhà 200m2", "giá xây nhà 200m2", "gia-xay-nha-200m2"],
    ["Giá Xây 1 Tầng", "giá xây 1 tầng", "gia-xay-1-tang"],
    ["Giá Xây 2 Tầng", "giá xây 2 tầng", "gia-xay-2-tang"],
    ["Giá Xây 3 Tầng", "giá xây 3 tầng", "gia-xay-3-tang"],
    ["Giá Xây 4 Tầng", "giá xây 4 tầng", "gia-xay-4-tang"],
    ["Giá Xây 5 Tầng", "giá xây 5 tầng", "gia-xay-5-tang"],
    ["Giá Nâng Thêm 1 Tầng", "giá nâng thêm 1 tầng", "gia-nang-them-1-tang"],
    ["Giá Sửa Mái Tôn", "giá sửa mái tôn", "gia-sua-mai-ton"],
    ["Giá Sửa Mái Ngói", "giá sửa mái ngói", "gia-sua-mai-ngoi"],
    ["Giá Sơn Lại Nhà", "giá sơn lại nhà", "gia-son-lai-nha"],
    ["Giá Ốp Lát Lại Nhà", "giá ốp lát lại nhà", "gia-op-lat-lai-nha"],
    ["Giá Thay Trần Thạch Cao", "giá thay trần thạch cao", "gia-thay-tran-thach-cao"],
    ["Giá Làm Mới Nhà Cũ", "giá làm mới nhà cũ", "gia-lam-moi-nha-cu"],
    ["Bảng Giá Vật Tư Xây 2026", "bảng giá vật tư xây 2026", "bang-gia-vat-tu-xay-2026"],
    ["Bảng Giá Nhân Công 2026", "bảng giá nhân công 2026", "bang-gia-nhan-cong-2026"],
    ["Bảng Giá Trọn Gói 2026", "bảng giá trọn gói 2026", "bang-gia-tron-goi-2026"],
    ["Ước Tính Chi Phí Xây Online", "ước tính chi phí xây online", "uoc-tinh-chi-phi-xay-online"],
    ["Công Thức Tính Giá Xây m2", "công thức tính giá xây m2", "cong-thuc-tinh-gia-xay-m2"],
    ["Cách Đọc Báo Giá Xây", "cách đọc báo giá xây", "cach-doc-bao-gia-xay"],
    ["Checklist So Báo Giá Thầu", "checklist so báo giá thầu", "checklist-so-bao-gia-thau"],
    ["Ẩn Phí Trong Báo Giá Xây", "ẩn phí trong báo giá xây", "an-phi-trong-bao-gia-xay"],
    ["Giá Xây Nhà Kinh Tế", "giá xây nhà kinh tế", "gia-xay-nha-kinh-te"],
    ["Giá Xây Nhà Trung Cấp", "giá xây nhà trung cấp", "gia-xay-nha-trung-cap"],
    ["Giá Xây Nhà Cao Cấp", "giá xây nhà cao cấp", "gia-xay-nha-cao-cap"],
    ["Giá Xây Nhà Luxury", "giá xây nhà luxury", "gia-xay-nha-luxury"],
    ["Chi Phí Nội Thất Cơ Bản", "chi phí nội thất cơ bản", "chi-phi-noi-that-co-ban"],
    ["Chi Phí Nội Thất Cao Cấp", "chi phí nội thất cao cấp", "chi-phi-noi-that-cao-cap"],
    ["Chi Phí Smart Home Cơ Bản", "chi phí smart home cơ bản", "chi-phi-smart-home-co-ban"],
    ["ROI Cải Tạo Nhà Phố", "roi cải tạo nhà phố", "roi-cai-tao-nha-pho"],
    ["ROI Xây Nhà Cho Thuê", "roi xây nhà cho thuê", "roi-xay-nha-cho-thue"],
    ["Vay Ngân Hàng Xây Nhà", "vay ngân hàng xây nhà", "vay-ngan-hang-xay-nha"],
    ["Lãi Suất Vay Xây Nhà", "lãi suất vay xây nhà", "lai-suat-vay-xay-nha"],
    ["Giải Ngân Theo Tiến Độ Xây", "giải ngân theo tiến độ xây", "giai-ngan-theo-tien-do-xay"],
    ["Thanh Toán Theo Đợt Xây", "thanh toán theo đợt xây", "thanh-toan-theo-dot-xay"],
    ["Giữ Lại Bảo Hành Xây", "giữ lại bảo hành xây", "giu-lai-bao-hanh-xay"],
    ["Tỷ Lệ Tạm Ứng Xây Nhà", "tỷ lệ tạm ứng xây nhà", "ty-le-tam-ung-xay-nha"],
    ["Chi Phí Bảo Trì Nhà Hàng Năm", "chi phí bảo trì nhà hàng năm", "chi-phi-bao-tri-nha-hang-nam"],
    ["Quỹ Bảo Trì Nhà Phố", "quỹ bảo trì nhà phố", "quy-bao-tri-nha-pho"],
  ]);

  // 31 — nhà xanh / thông minh / khí hậu / tiết kiệm năng lượng
  const b31 = pairs([
    ["Nhà Xanh Tiết Kiệm Điện", "nhà xanh tiết kiệm điện", "nha-xanh-tiet-kiem-dien"],
    ["Nhà Thông Minh Cơ Bản", "nhà thông minh cơ bản", "nha-thong-minh-co-ban"],
    ["Nhà Thông Minh Cao Cấp", "nhà thông minh cao cấp", "nha-thong-minh-cao-cap"],
    ["Lắp Đặt Smart Home", "lắp đặt smart home", "lap-dat-smart-home"],
    ["Công Tắc Cảm Ứng Nhà", "công tắc cảm ứng nhà", "cong-tac-cam-ung-nha"],
    ["Đèn LED Thông Minh", "đèn led thông minh", "den-led-thong-minh"],
    ["Camera An Ninh Nhà Phố", "camera an ninh nhà phố", "camera-an-ninh-nha-pho"],
    ["Khóa Cửa Vân Tay", "khóa cửa vân tay", "khoa-cua-van-tay"],
    ["Khóa Cửa Thông Minh", "khóa cửa thông minh", "khoa-cua-thong-minh"],
    ["Chuông Cửa Có Camera", "chuông cửa có camera", "chuong-cua-co-camera"],
    ["Hệ Thống Báo Cháy Nhà", "hệ thống báo cháy nhà", "he-thong-bao-chay-nha"],
    ["Báo Động Chống Trộm Nhà", "báo động chống trộm nhà", "bao-dong-chong-trom-nha"],
    ["Pin Năng Lượng Mặt Trời Nhà", "pin năng lượng mặt trời nhà", "pin-nang-luong-mat-troi-nha"],
    ["Điện Mặt Trời Áp Mái", "điện mặt trời áp mái", "dien-mat-troi-ap-mai"],
    ["Máy Nước Nóng Năng Lượng Mặt Trời", "máy nước nóng năng lượng mặt trời", "may-nuoc-nong-nlmt"],
    ["Thu Gom Nước Mưa Nhà", "thu gom nước mưa nhà", "thu-gom-nuoc-mua-nha"],
    ["Xử Lý Nước Thải Gia Đình", "xử lý nước thải gia đình", "xu-ly-nuoc-thai-gia-dinh"],
    ["Bể Phốt Không Mùi", "bể phốt không mùi", "be-phot-khong-mui"],
    ["Nhà Chống Nóng TPHCM", "nhà chống nóng tphcm", "nha-chong-nong-tphcm"],
    ["Nhà Chống Ẩm TPHCM", "nhà chống ẩm tphcm", "nha-chong-am-tphcm"],
    ["Nhà Chống Ồn Đường Phố", "nhà chống ồn đường phố", "nha-chong-on-duong-pho"],
    ["Nhà Thông Gió Tự Nhiên", "nhà thông gió tự nhiên", "nha-thong-gio-tu-nhien"],
    ["Giếng Trời Thông Gió", "giếng trời thông gió", "gieng-troi-thong-gio"],
    ["Giếng Trời Lấy Sáng", "giếng trời lấy sáng", "gieng-troi-lay-sang"],
    ["Cửa Sổ Trời Nhà Phố", "cửa sổ trời nhà phố", "cua-so-troi-nha-pho"],
    ["Mái Kính Lấy Sáng", "mái kính lấy sáng", "mai-kinh-lay-sang"],
    ["Mái Che Poly Nhà", "mái che poly nhà", "mai-che-poly-nha"],
    ["Mái Che Sân Thượng", "mái che sân thượng", "mai-che-san-thuong"],
    ["Cách Nhiệt Tường Nhà", "cách nhiệt tường nhà", "cach-nhiet-tuong-nha"],
    ["Cách Nhiệt Trần Nhà", "cách nhiệt trần nhà", "cach-nhiet-tran-nha"],
    ["Sơn Chống Nóng Tường", "sơn chống nóng tường", "son-chong-nong-tuong"],
    ["Sơn Chống Thấm Ngoài Trời", "sơn chống thấm ngoài trời", "son-chong-tham-ngoai-troi"],
    ["Vật Liệu Xanh Xây Nhà", "vật liệu xanh xây nhà", "vat-lieu-xanh-xay-nha"],
    ["Gạch Không Nung Xây Nhà", "gạch không nung xây nhà", "gach-khong-nung-xay-nha"],
    ["Gỗ Nhựa Ngoài Trời", "gỗ nhựa ngoài trời", "go-nhua-ngoai-troi-eco"],
    ["Sàn Tre Công Nghiệp", "sàn tre công nghiệp", "san-tre-cong-nghiep"],
    ["Sơn Sinh Thái Nhà", "sơn sinh thái nhà", "son-sinh-thai-nha"],
    ["Keo Chống Thấm Xanh", "keo chống thấm xanh", "keo-chong-tham-xanh"],
    ["Nhà Passive House Cơ Bản", "nhà passive house cơ bản", "nha-passive-house-co-ban"],
    ["Thiết Kế Bioclimatic", "thiết kế bioclimatic", "thiet-ke-bioclimatic"],
    ["Hướng Nhà Tốt TPHCM", "hướng nhà tốt tphcm", "huong-nha-tot-tphcm"],
    ["Nhà Hướng Đông Nam", "nhà hướng đông nam", "nha-huong-dong-nam"],
    ["Nhà Hướng Tây Nắng", "nhà hướng tây nắng", "nha-huong-tay-nang"],
    ["Che Nắng Mặt Tiền Tây", "che nắng mặt tiền tây", "che-nang-mat-tien-tay"],
    ["Lam Chắn Nắng Nhà Phố", "lam chắn nắng nhà phố", "lam-chan-nang-nha-pho"],
    ["Ban Công Xanh Nhà Phố", "ban công xanh nhà phố", "ban-cong-xanh-nha-pho"],
    ["Vườn Đứng Nhà Phố", "vườn đứng nhà phố", "vuon-dung-nha-pho"],
    ["Sân Thượng Xanh", "sân thượng xanh", "san-thuong-xanh-eco"],
    ["Trồng Cây Sân Thượng", "trồng cây sân thượng", "trong-cay-san-thuong-eco"],
    ["Hồ Cá Koi Nhà Phố", "hồ cá koi nhà phố", "ho-ca-koi-nha-pho"],
    ["Tiểu Cảnh Sân Trước", "tiểu cảnh sân trước", "tieu-canh-san-truoc"],
    ["Tiểu Cảnh Giếng Trời", "tiểu cảnh giếng trời", "tieu-canh-gieng-troi"],
    ["Máy Lạnh Inverter Tiết Kiệm", "máy lạnh inverter tiết kiệm", "may-lanh-inverter-tiet-kiem"],
    ["VRV Multi Nhà Phố", "vrv multi nhà phố", "vrv-multi-nha-pho"],
    ["Quạt Trần Thông Minh", "quạt trần thông minh", "quat-tran-thong-minh"],
    ["Máy Lọc Không Khí Nhà", "máy lọc không khí nhà", "may-loc-khong-khi-nha"],
    ["Hút Mùi Bếp Công Nghiệp Mini", "hút mùi bếp công nghiệp mini", "hut-mui-bep-cong-nghiep-mini"],
    ["Thông Gió Nhà Bếp", "thông gió nhà bếp", "thong-gio-nha-bep"],
    ["Thông Gió WC", "thông gió wc", "thong-gio-wc"],
    ["Chống Ẩm Tầng Hầm", "chống ẩm tầng hầm", "chong-am-tang-ham"],
    ["Chống Ngập Nhà Phố", "chống ngập nhà phố", "chong-ngap-nha-pho"],
    ["Nâng Cốt Nền Chống Ngập", "nâng cốt nền chống ngập", "nang-cot-nen-chong-ngap"],
    ["Rãnh Thoát Nước Mặt Tiền", "rãnh thoát nước mặt tiền", "ranh-thoat-nuoc-mat-tien"],
    ["Bơm Chống Ngập Gia Đình", "bơm chống ngập gia đình", "bom-chong-ngap-gia-dinh"],
    ["Nhà Chống Bão Cơ Bản", "nhà chống bão cơ bản", "nha-chong-bao-co-ban"],
    ["Gia Cố Mái Chống Bão", "gia cố mái chống bão", "gia-co-mai-chong-bao"],
    ["Cửa Chống Bão Nhà Phố", "cửa chống bão nhà phố", "cua-chong-bao-nha-pho"],
    ["Kính An Toàn Nhà Phố", "kính an toàn nhà phố", "kinh-an-toan-nha-pho"],
    ["Kính Cách Nhiệt Low-E", "kính cách nhiệt low-e", "kinh-cach-nhiet-low-e"],
    ["Kính Cách Âm Nhà Phố", "kính cách âm nhà phố", "kinh-cach-am-nha-pho"],
    ["Vách Kính Cách Âm", "vách kính cách âm", "vach-kinh-cach-am"],
    ["Cửa Cách Âm Phòng Ngủ", "cửa cách âm phòng ngủ", "cua-cach-am-phong-ngu"],
    ["Vách Ngăn Cách Âm", "vách ngăn cách âm", "vach-ngan-cach-am"],
    ["Trần Cách Âm Phòng Karaoke", "trần cách âm phòng karaoke", "tran-cach-am-phong-karaoke"],
    ["Phòng Karaoke Tại Gia", "phòng karaoke tại gia", "phong-karaoke-tai-gia"],
    ["Phòng Gym Tại Gia", "phòng gym tại gia", "phong-gym-tai-gia"],
    ["Phòng Làm Việc Tại Gia", "phòng làm việc tại gia", "phong-lam-viec-tai-gia"],
    ["Góc Học Tập Trẻ Em", "góc học tập trẻ em", "goc-hoc-tap-tre-em"],
    ["Phòng Chơi Trẻ Em", "phòng chơi trẻ em", "phong-choi-tre-em"],
    ["Phòng Ngủ Ông Bà", "phòng ngủ ông bà", "phong-ngu-ong-ba"],
    ["Thiết Kế Nhà Đa Thế Hệ", "thiết kế nhà đa thế hệ", "thiet-ke-nha-da-the-he"],
    ["Nhà Cho Người Cao Tuổi", "nhà cho người cao tuổi", "nha-cho-nguoi-cao-tuoi"],
    ["Nhà Không Rào Cản", "nhà không rào cản", "nha-khong-rao-can"],
    ["Thang Máy Mini Nhà Phố", "thang máy mini nhà phố", "thang-may-mini-nha-pho"],
    ["Thang Máy Gia Đình Giá", "thang máy gia đình giá", "thang-may-gia-dinh-gia"],
    ["Dự Trữ Không Gian Thang Máy", "dự trữ không gian thang máy", "du-tru-khong-gian-thang-may"],
    ["Nhà Sẵn Sàng Thang Máy", "nhà sẵn sàng thang máy", "nha-san-sang-thang-may"],
    ["Thiết Kế Nhà Linh Hoạt", "thiết kế nhà linh hoạt", "thiet-ke-nha-linh-hoat"],
    ["Nhà Module Lắp Ghép", "nhà module lắp ghép", "nha-module-lap-ghep"],
    ["Nhà Prefab Hiện Đại", "nhà prefab hiện đại", "nha-prefab-hien-dai"],
    ["Nhà Container Cải Tạo", "nhà container cải tạo", "nha-container-cai-tao"],
    ["Nhà Lắp Sẵn 1 Tầng", "nhà lắp sẵn 1 tầng", "nha-lap-san-1-tang"],
    ["Nhà Lắp Sẵn 2 Tầng", "nhà lắp sẵn 2 tầng", "nha-lap-san-2-tang"],
    ["Xu Hướng Nhà Xanh 2026", "xu hướng nhà xanh 2026", "xu-huong-nha-xanh-2026"],
    ["Xu Hướng Smart Home 2026", "xu hướng smart home 2026", "xu-huong-smart-home-2026"],
    ["Chứng Chỉ Công Trình Xanh", "chứng chỉ công trình xanh", "chung-chi-cong-trinh-xanh"],
    ["Nhà Đạt Chuẩn EDGE", "nhà đạt chuẩn edge", "nha-dat-chuan-edge"],
  ]);

  // 32 — geo tỉnh thành vùng phụ cận & miền Nam
  const b32 = pairs([
    ["Xây Nhà Thủ Dầu Một", "xây nhà Thủ Dầu Một", "xay-nha-thu-dau-mot-bd"],
    ["Xây Nhà Dĩ An", "xây nhà Dĩ An", "xay-nha-di-an-bd"],
    ["Xây Nhà Thuận An", "xây nhà Thuận An", "xay-nha-thuan-an-bd"],
    ["Xây Nhà Tân Uyên", "xây nhà Tân Uyên", "xay-nha-tan-uyen-bd"],
    ["Xây Nhà Bến Cát", "xây nhà Bến Cát", "xay-nha-ben-cat-bd"],
    ["Xây Nhà Bàu Bàng", "xây nhà Bàu Bàng", "xay-nha-bau-bang"],
    ["Xây Nhà Phú Giáo", "xây nhà Phú Giáo", "xay-nha-phu-giao"],
    ["Xây Nhà Dầu Tiếng", "xây nhà Dầu Tiếng", "xay-nha-dau-tieng"],
    ["Xây Nhà Biên Hòa", "xây nhà Biên Hòa", "xay-nha-bien-hoa-tinh"],
    ["Xây Nhà Long Thành", "xây nhà Long Thành", "xay-nha-long-thanh-dn"],
    ["Xây Nhà Nhơn Trạch", "xây nhà Nhơn Trạch", "xay-nha-nhon-trach-dn"],
    ["Xây Nhà Trảng Bom", "xây nhà Trảng Bom", "xay-nha-trang-bom-dn"],
    ["Xây Nhà Vĩnh Cửu", "xây nhà Vĩnh Cửu", "xay-nha-vinh-cuu"],
    ["Xây Nhà Thống Nhất", "xây nhà Thống Nhất", "xay-nha-thong-nhat"],
    ["Xây Nhà Định Quán", "xây nhà Định Quán", "xay-nha-dinh-quan"],
    ["Xây Nhà Xuân Lộc", "xây nhà Xuân Lộc", "xay-nha-xuan-loc"],
    ["Xây Nhà Cẩm Mỹ", "xây nhà Cẩm Mỹ", "xay-nha-cam-my"],
    ["Xây Nhà Tân Phú Đồng Nai", "xây nhà Tân Phú Đồng Nai", "xay-nha-tan-phu-dong-nai"],
    ["Xây Nhà Tân An", "xây nhà Tân An", "xay-nha-tan-an"],
    ["Xây Nhà Bến Lức", "xây nhà Bến Lức", "xay-nha-ben-luc-la"],
    ["Xây Nhà Cần Giuộc", "xây nhà Cần Giuộc", "xay-nha-can-giuoc"],
    ["Xây Nhà Cần Đước", "xây nhà Cần Đước", "xay-nha-can-duoc"],
    ["Xây Nhà Đức Hòa", "xây nhà Đức Hòa", "xay-nha-duc-hoa-la"],
    ["Xây Nhà Đức Huệ", "xây nhà Đức Huệ", "xay-nha-duc-hue"],
    ["Xây Nhà Thủ Thừa", "xây nhà Thủ Thừa", "xay-nha-thu-thua"],
    ["Xây Nhà Châu Thành Long An", "xây nhà Châu Thành Long An", "xay-nha-chau-thanh-long-an"],
    ["Xây Nhà Tân Trụ", "xây nhà Tân Trụ", "xay-nha-tan-tru"],
    ["Xây Nhà Tây Ninh Thành Phố", "xây nhà Tây Ninh", "xay-nha-tay-ninh-tp"],
    ["Xây Nhà Trảng Bàng", "xây nhà Trảng Bàng", "xay-nha-trang-bang"],
    ["Xây Nhà Gò Dầu", "xây nhà Gò Dầu", "xay-nha-go-dau"],
    ["Xây Nhà Hòa Thành", "xây nhà Hòa Thành", "xay-nha-hoa-thanh-tn"],
    ["Xây Nhà Dương Minh Châu", "xây nhà Dương Minh Châu", "xay-nha-duong-minh-chau"],
    ["Xây Nhà Châu Thành Tây Ninh", "xây nhà Châu Thành Tây Ninh", "xay-nha-chau-thanh-tay-ninh"],
    ["Xây Nhà Vũng Tàu", "xây nhà Vũng Tàu", "xay-nha-vung-tau-brvt"],
    ["Xây Nhà Bà Rịa", "xây nhà Bà Rịa", "xay-nha-ba-ria-brvt"],
    ["Xây Nhà Phú Mỹ BRVT", "xây nhà Phú Mỹ", "xay-nha-phu-my-brvt"],
    ["Xây Nhà Long Điền", "xây nhà Long Điền", "xay-nha-long-dien"],
    ["Xây Nhà Đất Đỏ", "xây nhà Đất Đỏ", "xay-nha-dat-do"],
    ["Xây Nhà Xuyên Mộc", "xây nhà Xuyên Mộc", "xay-nha-xuyen-moc"],
    ["Xây Nhà Châu Đức", "xây nhà Châu Đức", "xay-nha-chau-duc"],
    ["Xây Nhà Côn Đảo", "xây nhà Côn Đảo", "xay-nha-con-dao"],
    ["Xây Nhà Mỹ Tho", "xây nhà Mỹ Tho", "xay-nha-my-tho-tinh"],
    ["Xây Nhà Gò Công", "xây nhà Gò Công", "xay-nha-go-cong"],
    ["Xây Nhà Cai Lậy", "xây nhà Cai Lậy", "xay-nha-cai-lay"],
    ["Xây Nhà Bến Tre", "xây nhà Bến Tre", "xay-nha-ben-tre-tinh"],
    ["Xây Nhà Trà Vinh", "xây nhà Trà Vinh", "xay-nha-tra-vinh-tinh"],
    ["Xây Nhà Vĩnh Long", "xây nhà Vĩnh Long", "xay-nha-vinh-long-tinh"],
    ["Xây Nhà Sa Đéc", "xây nhà Sa Đéc", "xay-nha-sa-dec"],
    ["Xây Nhà Cao Lãnh", "xây nhà Cao Lãnh", "xay-nha-cao-lanh"],
    ["Xây Nhà Long Xuyên", "xây nhà Long Xuyên", "xay-nha-long-xuyen"],
    ["Xây Nhà Châu Đốc", "xây nhà Châu Đốc", "xay-nha-chau-doc-tinh"],
    ["Xây Nhà Rạch Giá", "xây nhà Rạch Giá", "xay-nha-rach-gia-tinh"],
    ["Xây Nhà Hà Tiên", "xây nhà Hà Tiên", "xay-nha-ha-tien"],
    ["Xây Nhà Cà Mau", "xây nhà Cà Mau", "xay-nha-ca-mau-tinh"],
    ["Xây Nhà Bạc Liêu", "xây nhà Bạc Liêu", "xay-nha-bac-lieu-tinh"],
    ["Xây Nhà Sóc Trăng", "xây nhà Sóc Trăng", "xay-nha-soc-trang-tinh"],
    ["Xây Nhà Cần Thơ Ninh Kiều", "xây nhà Ninh Kiều", "xay-nha-ninh-kieu"],
    ["Xây Nhà Cần Thơ Cái Răng", "xây nhà Cái Răng", "xay-nha-cai-rang"],
    ["Xây Nhà Cần Thơ Bình Thủy", "xây nhà Bình Thủy", "xay-nha-binh-thuy"],
    ["Xây Nhà Cần Thơ Ô Môn", "xây nhà Ô Môn", "xay-nha-o-mon"],
    ["Xây Nhà Cần Thơ Thốt Nốt", "xây nhà Thốt Nốt", "xay-nha-thot-not"],
    ["Cải Tạo Nhà Thủ Dầu Một", "cải tạo nhà Thủ Dầu Một", "cai-tao-nha-thu-dau-mot"],
    ["Cải Tạo Nhà Biên Hòa", "cải tạo nhà Biên Hòa", "cai-tao-nha-bien-hoa"],
    ["Cải Tạo Nhà Tân An", "cải tạo nhà Tân An", "cai-tao-nha-tan-an"],
    ["Cải Tạo Nhà Vũng Tàu", "cải tạo nhà Vũng Tàu", "cai-tao-nha-vung-tau-brvt"],
    ["Cải Tạo Nhà Mỹ Tho", "cải tạo nhà Mỹ Tho", "cai-tao-nha-my-tho"],
    ["Cải Tạo Nhà Cần Thơ", "cải tạo nhà Cần Thơ", "cai-tao-nha-can-tho-ct"],
    ["Thiết Kế Nhà Dĩ An", "thiết kế nhà Dĩ An", "thiet-ke-nha-di-an"],
    ["Thiết Kế Nhà Thuận An", "thiết kế nhà Thuận An", "thiet-ke-nha-thuan-an"],
    ["Thiết Kế Nhà Long Thành", "thiết kế nhà Long Thành", "thiet-ke-nha-long-thanh"],
    ["Thiết Kế Nhà Nhơn Trạch", "thiết kế nhà Nhơn Trạch", "thiet-ke-nha-nhon-trach"],
    ["Thiết Kế Nhà Đức Hòa", "thiết kế nhà Đức Hòa", "thiet-ke-nha-duc-hoa"],
    ["Thiết Kế Nhà Bến Lức", "thiết kế nhà Bến Lức", "thiet-ke-nha-ben-luc"],
    ["Báo Giá Xây Nhà Bình Dương", "báo giá xây nhà Bình Dương", "bao-gia-xay-nha-binh-duong"],
    ["Báo Giá Xây Nhà Đồng Nai", "báo giá xây nhà Đồng Nai", "bao-gia-xay-nha-dong-nai"],
    ["Báo Giá Xây Nhà Long An", "báo giá xây nhà Long An", "bao-gia-xay-nha-long-an"],
    ["Báo Giá Xây Nhà Tây Ninh", "báo giá xây nhà Tây Ninh", "bao-gia-xay-nha-tay-ninh"],
    ["Báo Giá Xây Nhà BRVT", "báo giá xây nhà bà rịa vũng tàu", "bao-gia-xay-nha-brvt"],
    ["Báo Giá Xây Nhà Tiền Giang", "báo giá xây nhà Tiền Giang", "bao-gia-xay-nha-tien-giang"],
    ["Báo Giá Xây Nhà Cần Thơ", "báo giá xây nhà Cần Thơ", "bao-gia-xay-nha-can-tho"],
    ["Nhà Thầu Bình Dương", "nhà thầu Bình Dương", "nha-thau-binh-duong"],
    ["Nhà Thầu Đồng Nai", "nhà thầu Đồng Nai", "nha-thau-dong-nai"],
    ["Nhà Thầu Long An", "nhà thầu Long An", "nha-thau-long-an"],
    ["Nhà Thầu Tây Ninh", "nhà thầu Tây Ninh", "nha-thau-tay-ninh"],
    ["Nhà Thầu BRVT", "nhà thầu bà rịa vũng tàu", "nha-thau-brvt"],
    ["Nhà Thầu Tiền Giang", "nhà thầu Tiền Giang", "nha-thau-tien-giang"],
    ["Nhà Thầu Cần Thơ", "nhà thầu Cần Thơ", "nha-thau-can-tho"],
    ["Xây Nhà KCN VSIP", "xây nhà gần VSIP", "xay-nha-gan-vsip"],
    ["Xây Nhà KCN Mỹ Phước", "xây nhà gần Mỹ Phước", "xay-nha-gan-my-phuoc"],
    ["Xây Nhà KCN Biên Hòa", "xây nhà gần KCN Biên Hòa", "xay-nha-gan-kcn-bien-hoa"],
    ["Xây Nhà Sân Bay Long Thành", "xây nhà gần sân bay Long Thành", "xay-nha-gan-san-bay-long-thanh"],
    ["Xây Nhà Cao Tốc Trung Lương", "xây nhà gần cao tốc Trung Lương", "xay-nha-gan-cao-toc-trung-luong"],
    ["Xây Nhà Cao Tốc Bến Lức", "xây nhà gần cao tốc Bến Lức", "xay-nha-gan-cao-toc-ben-luc"],
    ["Xây Biệt Thự Biên Hòa", "xây biệt thự Biên Hòa", "xay-biet-thu-bien-hoa"],
    ["Xây Biệt Thự Thủ Dầu Một", "xây biệt thự Thủ Dầu Một", "xay-biet-thu-thu-dau-mot"],
    ["Xây Biệt Thự Vũng Tàu", "xây biệt thự Vũng Tàu", "xay-biet-thu-vung-tau"],
    ["Xây Nhà Vườn Long An", "xây nhà vườn Long An", "xay-nha-vuon-long-an"],
    ["Xây Nhà Vườn Đồng Nai", "xây nhà vườn Đồng Nai", "xay-nha-vuon-dong-nai"],
    ["Xây Nhà Vườn Bình Dương", "xây nhà vườn Bình Dương", "xay-nha-vuon-binh-duong"],
  ]);

  // 33 — loại hình công trình / thương mại / chuyên biệt
  const b33 = pairs([
    ["Xây Nhà Ở Kết Hợp Kinh Doanh", "xây nhà ở kết hợp kinh doanh", "xay-nha-o-ket-hop-kinh-doanh"],
    ["Xây Nhà Mặt Tiền Cho Thuê", "xây nhà mặt tiền cho thuê", "xay-nha-mat-tien-cho-thue"],
    ["Xây Nhà Trọ Mini", "xây nhà trọ mini", "xay-nha-tro-mini"],
    ["Xây Nhà Trọ 10 Phòng", "xây nhà trọ 10 phòng", "xay-nha-tro-10-phong"],
    ["Xây Nhà Trọ 20 Phòng", "xây nhà trọ 20 phòng", "xay-nha-tro-20-phong"],
    ["Xây Chung Cư Mini", "xây chung cư mini", "xay-chung-cu-mini"],
    ["Xây Căn Hộ Dịch Vụ", "xây căn hộ dịch vụ", "xay-can-ho-dich-vu"],
    ["Xây Homestay Nhà Phố", "xây homestay nhà phố", "xay-homestay-nha-pho"],
    ["Xây Airbnb Nhà Phố", "xây airbnb nhà phố", "xay-airbnb-nha-pho"],
    ["Xây Boutique Hotel Mini", "xây boutique hotel mini", "xay-boutique-hotel-mini"],
    ["Xây Nhà Hàng Phố", "xây nhà hàng phố", "xay-nha-hang-pho"],
    ["Xây Quán Cafe Nhà Phố", "xây quán cafe nhà phố", "xay-quan-cafe-nha-pho"],
    ["Xây Spa Thẩm Mỹ Viện", "xây spa thẩm mỹ viện", "xay-spa-tham-my-vien"],
    ["Xây Phòng Khám Tư", "xây phòng khám tư", "xay-phong-kham-tu"],
    ["Xây Nha Khoa Tư Nhân", "xây nha khoa tư nhân", "xay-nha-khoa-tu-nhan"],
    ["Xây Phòng Gym Commercial", "xây phòng gym commercial", "xay-phong-gym-commercial"],
    ["Xây Showroom Bán Hàng", "xây showroom bán hàng", "xay-showroom-ban-hang"],
    ["Xây Cửa Hàng Tiện Lợi", "xây cửa hàng tiện lợi", "xay-cua-hang-tien-loi"],
    ["Xây Siêu Thị Mini", "xây siêu thị mini", "xay-sieu-thi-mini"],
    ["Xây Kho Xưởng Nhà Phố", "xây kho xưởng nhà phố", "xay-kho-xuong-nha-pho"],
    ["Xây Văn Phòng Cho Thuê", "xây văn phòng cho thuê", "xay-van-phong-cho-thue"],
    ["Xây Co-working Space", "xây co-working space", "xay-co-working-space"],
    ["Xây Trường Mầm Non Tư", "xây trường mầm non tư", "xay-truong-mam-non-tu"],
    ["Xây Nhà Trẻ Tư Thục", "xây nhà trẻ tư thục", "xay-nha-tre-tu-thuc"],
    ["Xây Trung Tâm Ngoại Ngữ", "xây trung tâm ngoại ngữ", "xay-trung-tam-ngoai-ngu"],
    ["Xây Studio Chụp Ảnh", "xây studio chụp ảnh", "xay-studio-chup-anh"],
    ["Xây Studio Livestream", "xây studio livestream", "xay-studio-livestream"],
    ["Xây Garage Ô Tô", "xây garage ô tô", "xay-garage-o-to"],
    ["Xây Hầm Để Xe", "xây hầm để xe", "xay-ham-de-xe"],
    ["Xây Sân Để Xe Máy", "xây sân để xe máy", "xay-san-de-xe-may"],
    ["Xây Nhà Xe Riêng", "xây nhà xe riêng", "xay-nha-xe-rieng"],
    ["Xây Biệt Thự Mini", "xây biệt thự mini", "xay-biet-thu-mini"],
    ["Xây Biệt Thự Song Lập", "xây biệt thự song lập", "xay-biet-thu-song-lap"],
    ["Xây Biệt Thự Đơn Lập", "xây biệt thự đơn lập", "xay-biet-thu-don-lap"],
    ["Xây Biệt Thự Nghỉ Dưỡng", "xây biệt thự nghỉ dưỡng", "xay-biet-thu-nghi-duong"],
    ["Xây Nhà Vườn Nghỉ Cuối Tuần", "xây nhà vườn nghỉ cuối tuần", "xay-nha-vuon-nghi-cuoi-tuan"],
    ["Xây Farmstay Cơ Bản", "xây farmstay cơ bản", "xay-farmstay-co-ban"],
    ["Xây Nhà Gỗ Hiện Đại", "xây nhà gỗ hiện đại", "xay-nha-go-hien-dai"],
    ["Xây Nhà Khung Thép Nhẹ", "xây nhà khung thép nhẹ", "xay-nha-khung-thep-nhe"],
    ["Xây Nhà LSF Frame", "xây nhà lsf frame", "xay-nha-lsf-frame"],
    ["Xây Nhà Bê Tông Dự Ứng Lực", "xây nhà bê tông dự ứng lực", "xay-nha-be-tong-du-ung-luc"],
    ["Xây Nhà Sàn Không Dầm", "xây nhà sàn không dầm", "xay-nha-san-khong-dam"],
    ["Xây Nhà Không Cột Giữa", "xây nhà không cột giữa", "xay-nha-khong-cot-giua"],
    ["Xây Nhà Thông Tầng", "xây nhà thông tầng", "xay-nha-thong-tang"],
    ["Xây Nhà Duplex", "xây nhà duplex", "xay-nha-duplex"],
    ["Xây Nhà Penthouse", "xây nhà penthouse", "xay-nha-penthouse"],
    ["Cải Tạo Nhà Thành Homestay", "cải tạo nhà thành homestay", "cai-tao-nha-thanh-homestay"],
    ["Cải Tạo Nhà Thành Văn Phòng", "cải tạo nhà thành văn phòng", "cai-tao-nha-thanh-van-phong"],
    ["Cải Tạo Nhà Thành Cafe", "cải tạo nhà thành cafe", "cai-tao-nha-thanh-cafe"],
    ["Cải Tạo Nhà Thành Nhà Trọ", "cải tạo nhà thành nhà trọ", "cai-tao-nha-thanh-nha-tro"],
    ["Cải Tạo Nhà Thành Spa", "cải tạo nhà thành spa", "cai-tao-nha-thanh-spa"],
    ["Cải Tạo Mặt Tiền Kinh Doanh", "cải tạo mặt tiền kinh doanh", "cai-tao-mat-tien-kinh-doanh"],
    ["Cải Tạo Tầng Trệt Shop", "cải tạo tầng trệt shop", "cai-tao-tang-tret-shop"],
    ["Cải Tạo Gác Lửng Kinh Doanh", "cải tạo gác lửng kinh doanh", "cai-tao-gac-lung-kinh-doanh"],
    ["Nâng Tầng Thành Nhà Trọ", "nâng tầng thành nhà trọ", "nang-tang-thanh-nha-tro"],
    ["Thiết Kế Shop Nhà Phố", "thiết kế shop nhà phố", "thiet-ke-shop-nha-pho"],
    ["Thiết Kế Cafe Nhà Phố", "thiết kế cafe nhà phố", "thiet-ke-cafe-nha-pho"],
    ["Thiết Kế Nhà Hàng Phố", "thiết kế nhà hàng phố", "thiet-ke-nha-hang-pho"],
    ["Thiết Kế Homestay", "thiết kế homestay", "thiet-ke-homestay"],
    ["Thiết Kế Nhà Trọ Tối Ưu", "thiết kế nhà trọ tối ưu", "thiet-ke-nha-tro-toi-uu"],
    ["Thiết Kế Văn Phòng Nhà Phố", "thiết kế văn phòng nhà phố", "thiet-ke-van-phong-nha-pho"],
    ["Báo Giá Xây Nhà Trọ", "báo giá xây nhà trọ", "bao-gia-xay-nha-tro"],
    ["Báo Giá Xây Homestay", "báo giá xây homestay", "bao-gia-xay-homestay"],
    ["Báo Giá Xây Showroom", "báo giá xây showroom", "bao-gia-xay-showroom"],
    ["Báo Giá Xây Văn Phòng", "báo giá xây văn phòng", "bao-gia-xay-van-phong"],
    ["Báo Giá Xây Biệt Thự", "báo giá xây biệt thự", "bao-gia-xay-biet-thu"],
    ["Pháp Lý Nhà Ở Kinh Doanh", "pháp lý nhà ở kinh doanh", "phap-ly-nha-o-kinh-doanh"],
    ["Xin Phép Xây Nhà Trọ", "xin phép xây nhà trọ", "xin-phep-xay-nha-tro"],
    ["Xin Phép Xây Homestay", "xin phép xây homestay", "xin-phep-xay-homestay"],
    ["PCCC Nhà Trọ Bắt Buộc", "pccc nhà trọ bắt buộc", "pccc-nha-tro-bat-buoc"],
    ["PCCC Nhà Hàng Cafe", "pccc nhà hàng cafe", "pccc-nha-hang-cafe"],
    ["Thoát Hiểm Nhà Trọ", "thoát hiểm nhà trọ", "thoat-hiem-nha-tro"],
    ["Cầu Thang Thoát Hiểm", "cầu thang thoát hiểm", "cau-thang-thoat-hiem"],
    ["Hệ Thống PCCC Tự Động", "hệ thống pccc tự động", "he-thong-pccc-tu-dong"],
    ["Bình Chữa Cháy Nhà Phố", "bình chữa cháy nhà phố", "binh-chua-chay-nha-pho"],
    ["Tủ Điện PCCC", "tủ điện pccc", "tu-dien-pccc"],
    ["Đầu Báo Khói Nhà", "đầu báo khói nhà", "dau-bao-khoi-nha"],
    ["Vòi Phun Sprinkler Nhà", "vòi phun sprinkler nhà", "voi-phun-sprinkler-nha"],
    ["Thiết Kế Mặt Tiền Thu Hút", "thiết kế mặt tiền thu hút", "thiet-ke-mat-tien-thu-hut"],
    ["Bảng Hiệu Nhà Phố", "bảng hiệu nhà phố", "bang-hieu-nha-pho"],
    ["Ánh Sáng Mặt Tiền Shop", "ánh sáng mặt tiền shop", "anh-sang-mat-tien-shop"],
    ["Vách Kính Shop Nhà Phố", "vách kính shop nhà phố", "vach-kinh-shop-nha-pho"],
    ["Cửa Cuốn Shop", "cửa cuốn shop", "cua-cuon-shop"],
    ["Cửa Kéo Shop", "cửa kéo shop", "cua-keo-shop"],
    ["Sàn Epoxy Xưởng", "sàn epoxy xưởng", "san-epoxy-xuong"],
    ["Sàn Vinyl Văn Phòng", "sàn vinyl văn phòng", "san-vinyl-van-phong"],
    ["Trần Xuyên Sáng Cafe", "trần xuyên sáng cafe", "tran-xuyen-sang-cafe"],
    ["Nội Thất Homestay Trọn Gói", "nội thất homestay trọn gói", "noi-that-homestay-tron-goi"],
    ["Nội Thất Nhà Trọ Tối Giản", "nội thất nhà trọ tối giản", "noi-that-nha-tro-toi-gian"],
    ["Nội Thất Văn Phòng Lean", "nội thất văn phòng lean", "noi-that-van-phong-lean"],
    ["ROI Nhà Trọ TPHCM", "roi nhà trọ tphcm", "roi-nha-tro-tphcm"],
    ["ROI Homestay TPHCM", "roi homestay tphcm", "roi-homestay-tphcm"],
    ["ROI Mặt Tiền Cho Thuê", "roi mặt tiền cho thuê", "roi-mat-tien-cho-thue"],
  ]);

  // 34 — thương hiệu vật tư / so sánh / Ads head commercial
  const b34 = pairs([
    ["Xi Măng Hà Tiên Xây Nhà", "xi măng Hà Tiên xây nhà", "xi-mang-ha-tien-xay-nha"],
    ["Xi Măng Nghi Sơn Xây Nhà", "xi măng Nghi Sơn xây nhà", "xi-mang-nghi-son-xay-nha"],
    ["Thép Hòa Phát Xây Nhà", "thép Hòa Phát xây nhà", "thep-hoa-phat-xay-nha"],
    ["Thép Việt Nhật Xây Nhà", "thép Việt Nhật xây nhà", "thep-viet-nhat-xay-nha"],
    ["Thép Pomina Xây Nhà", "thép Pomina xây nhà", "thep-pomina-xay-nha"],
    ["Gạch Đồng Tâm Ốp Lát", "gạch Đồng Tâm ốp lát", "gach-dong-tam-op-lat"],
    ["Gạch Viglacera Ốp Lát", "gạch Viglacera ốp lát", "gach-viglacera-op-lat"],
    ["Gạch Catalan Ốp Lát", "gạch Catalan ốp lát", "gach-catalan-op-lat"],
    ["Sơn Dulux Nhà Phố", "sơn Dulux nhà phố", "son-dulux-nha-pho"],
    ["Sơn Jotun Nhà Phố", "sơn Jotun nhà phố", "son-jotun-nha-pho"],
    ["Sơn Nippon Nhà Phố", "sơn Nippon nhà phố", "son-nippon-nha-pho"],
    ["Sơn Kova Chống Thấm", "sơn Kova chống thấm", "son-kova-chong-tham"],
    ["Keo Sika Chống Thấm", "keo Sika chống thấm", "keo-sika-chong-tham"],
    ["Keo Weber Ốp Lát", "keo Weber ốp lát", "keo-weber-op-lat"],
    ["Cửa Xingfa Chính Hãng", "cửa Xingfa chính hãng", "cua-xingfa-chinh-hang"],
    ["Cửa Eurowindow", "cửa Eurowindow", "cua-eurowindow"],
    ["Cửa Nhôm PMA", "cửa nhôm PMA", "cua-nhom-pma"],
    ["Cửa Nhôm Việt Pháp", "cửa nhôm Việt Pháp", "cua-nhom-viet-phap"],
    ["Kính Guardian Nhà Phố", "kính Guardian nhà phố", "kinh-guardian-nha-pho"],
    ["Kính Việt Nhật Nhà Phố", "kính Việt Nhật nhà phố", "kinh-viet-nhat-nha-pho"],
    ["Tôn Hoa Sen Lợp Mái", "tôn Hoa Sen lợp mái", "ton-hoa-sen-lop-mai"],
    ["Tôn Đông Á Lợp Mái", "tôn Đông Á lợp mái", "ton-dong-a-lop-mai"],
    ["Ngói Đồng Nai Lợp Mái", "ngói Đồng Nai lợp mái", "ngoi-dong-nai-lop-mai"],
    ["Ngói Thái Lan Lợp Mái", "ngói Thái Lan lợp mái", "ngoi-thai-lan-lop-mai"],
    ["Trần Vĩnh Tường", "trần Vĩnh Tường", "tran-vinh-tuong"],
    ["Trần Gyproc Nhà Phố", "trần Gyproc nhà phố", "tran-gyproc-nha-pho"],
    ["Sàn Gỗ An Cường", "sàn gỗ An Cường", "san-go-an-cuong"],
    ["Sàn Gỗ Robina", "sàn gỗ Robina", "san-go-robina"],
    ["Sàn Nhựa Awesome", "sàn nhựa Awesome", "san-nhua-awesome"],
    ["Thiết Bị Vệ Sinh Inax", "thiết bị vệ sinh Inax", "thiet-bi-ve-sinh-inax"],
    ["Thiết Bị Vệ Sinh Toto", "thiết bị vệ sinh Toto", "thiet-bi-ve-sinh-toto"],
    ["Thiết Bị Vệ Sinh American", "thiết bị vệ sinh American Standard", "thiet-bi-ve-sinh-american"],
    ["Bồn Nước Sơn Hà", "bồn nước Sơn Hà", "bon-nuoc-son-ha"],
    ["Bồn Nước Đại Thành", "bồn nước Đại Thành", "bon-nuoc-dai-thanh"],
    ["Ống Nhựa Bình Minh", "ống nhựa Bình Minh", "ong-nhua-binh-minh"],
    ["Ống Nhựa Tiền Phong", "ống nhựa Tiền Phong", "ong-nhua-tien-phong"],
    ["Dây Điện Cadivi", "dây điện Cadivi", "day-dien-cadivi"],
    ["Dây Điện Trần Phú", "dây điện Trần Phú", "day-dien-tran-phu"],
    ["Aptomat Schneider", "aptomat Schneider", "aptomat-schneider"],
    ["Aptomat Mitsubishi", "aptomat Mitsubishi", "aptomat-mitsubishi"],
    ["Công Tắc Panasonic", "công tắc Panasonic", "cong-tac-panasonic"],
    ["Công Tắc Sino", "công tắc Sino", "cong-tac-sino"],
    ["So Sánh Xingfa Và PMA", "so sánh Xingfa và PMA", "so-sanh-xingfa-va-pma"],
    ["So Sánh Dulux Và Jotun", "so sánh Dulux và Jotun", "so-sanh-dulux-va-jotun"],
    ["So Sánh Inax Và Toto", "so sánh Inax và Toto", "so-sanh-inax-va-toto"],
    ["So Sánh Tôn Hoa Sen Đông Á", "so sánh tôn Hoa Sen Đông Á", "so-sanh-ton-hoa-sen-dong-a"],
    ["So Sánh Gạch Đồng Tâm Catalan", "so sánh gạch Đồng Tâm Catalan", "so-sanh-gach-dong-tam-catalan"],
    ["Vật Tư Chính Hãng Xây Nhà", "vật tư chính hãng xây nhà", "vat-tu-chinh-hang-xay-nha"],
    ["Cách Nhận Hàng Fake Xây", "cách nhận hàng fake xây", "cach-nhan-hang-fake-xay"],
    ["Chứng Chỉ CO CQ Vật Tư", "chứng chỉ CO CQ vật tư", "chung-chi-co-cq-vat-tu"],
    ["Bảo Hành Vật Tư Xây Nhà", "bảo hành vật tư xây nhà", "bao-hanh-vat-tu-xay-nha"],
    ["Nhà Thầu Uy Tín TPHCM", "nhà thầu uy tín tphcm", "nha-thau-uy-tin-tphcm-ads"],
    ["Công Ty Xây Dựng Uy Tín", "công ty xây dựng uy tín", "cong-ty-xay-dung-uy-tin-ads"],
    ["Công Ty Thiết Kế Nhà Đẹp", "công ty thiết kế nhà đẹp", "cong-ty-thiet-ke-nha-dep-ads"],
    ["Xây Nhà Trọn Gói Giá Rẻ", "xây nhà trọn gói giá rẻ", "xay-nha-tron-goi-gia-re-ads"],
    ["Xây Nhà Phần Thô Giá Rẻ", "xây nhà phần thô giá rẻ", "xay-nha-phan-tho-gia-re-ads"],
    ["Cải Tạo Nhà Giá Rẻ TPHCM", "cải tạo nhà giá rẻ tphcm", "cai-tao-nha-gia-re-tphcm-ads"],
    ["Sửa Nhà Giá Rẻ TPHCM", "sửa nhà giá rẻ tphcm", "sua-nha-gia-re-tphcm-ads"],
    ["Báo Giá Xây Nhà Nhanh", "báo giá xây nhà nhanh", "bao-gia-xay-nha-nhanh-ads"],
    ["Báo Giá Cải Tạo Nhanh", "báo giá cải tạo nhanh", "bao-gia-cai-tao-nhanh-ads"],
    ["Tư Vấn Xây Nhà Miễn Phí", "tư vấn xây nhà miễn phí", "tu-van-xay-nha-mien-phi-ads"],
    ["Khảo Sát Công Trình Miễn Phí", "khảo sát công trình miễn phí", "khao-sat-cong-trinh-mien-phi-ads"],
    ["Xây Nhà Có Bảo Hành", "xây nhà có bảo hành", "xay-nha-co-bao-hanh-ads"],
    ["Xây Nhà Cam Kết Tiến Độ", "xây nhà cam kết tiến độ", "xay-nha-cam-ket-tien-do-ads"],
    ["Xây Nhà Không Phát Sinh", "xây nhà không phát sinh", "xay-nha-khong-phat-sinh-ads"],
    ["Đội Thợ Xây Chuyên Nghiệp", "đội thợ xây chuyên nghiệp", "doi-tho-xay-chuyen-nghiep-ads"],
    ["Thợ Hồ Lành Nghề TPHCM", "thợ hồ lành nghề tphcm", "tho-ho-lanh-nghe-tphcm-ads"],
    ["Kiến Trúc Sư Tư Vấn", "kiến trúc sư tư vấn", "kien-truc-su-tu-van-ads"],
    ["Thiết Kế 3D Nhà Phố", "thiết kế 3d nhà phố", "thiet-ke-3d-nha-pho-ads"],
    ["Phối Cảnh Nhà Phố 3D", "phối cảnh nhà phố 3d", "phoi-canh-nha-pho-3d-ads"],
    ["Mẫu Nhà Phố Đẹp 2026", "mẫu nhà phố đẹp 2026", "mau-nha-pho-dep-2026-ads"],
    ["Mẫu Nhà Cấp 4 Đẹp 2026", "mẫu nhà cấp 4 đẹp 2026", "mau-nha-cap-4-dep-2026-ads"],
    ["Mẫu Nhà 2 Tầng Đẹp 2026", "mẫu nhà 2 tầng đẹp 2026", "mau-nha-2-tang-dep-2026-ads"],
    ["Mẫu Nhà 3 Tầng Đẹp 2026", "mẫu nhà 3 tầng đẹp 2026", "mau-nha-3-tang-dep-2026-ads"],
    ["Mẫu Nhà 4 Tầng Đẹp 2026", "mẫu nhà 4 tầng đẹp 2026", "mau-nha-4-tang-dep-2026-ads"],
    ["Mẫu Biệt Thự Đẹp 2026", "mẫu biệt thự đẹp 2026", "mau-biet-thu-dep-2026-ads"],
    ["Xu Hướng Mặt Tiền 2026", "xu hướng mặt tiền 2026", "xu-huong-mat-tien-2026-ads"],
    ["Xu Hướng Nội Thất 2026", "xu hướng nội thất 2026", "xu-huong-noi-that-2026-ads"],
    ["Top Công Ty Xây Dựng 2026", "top công ty xây dựng 2026", "top-cong-ty-xay-dung-2026-ads"],
    ["Top Nhà Thầu TPHCM 2026", "top nhà thầu tphcm 2026", "top-nha-thau-tphcm-2026-ads"],
    ["Review Nhà Thầu Xây", "review nhà thầu xây", "review-nha-thau-xay-ads"],
    ["Đánh Giá Công Ty Xây Dựng", "đánh giá công ty xây dựng", "danh-gia-cong-ty-xay-dung-ads"],
    ["Kinh Nghiệm Chọn Thầu 2026", "kinh nghiệm chọn thầu 2026", "kinh-nghiem-chon-thau-2026-ads"],
    ["Kinh Nghiệm Xây Nhà 2026", "kinh nghiệm xây nhà 2026", "kinh-nghiem-xay-nha-2026-ads"],
    ["Kinh Nghiệm Cải Tạo 2026", "kinh nghiệm cải tạo 2026", "kinh-nghiem-cai-tao-2026-ads"],
    ["Hotline Tư Vấn Xây Nhà", "hotline tư vấn xây nhà", "hotline-tu-van-xay-nha-ads"],
    ["Zalo Tư Vấn Xây Nhà", "zalo tư vấn xây nhà", "zalo-tu-van-xay-nha-ads"],
    ["Đặt Lịch Khảo Sát Xây", "đặt lịch khảo sát xây", "dat-lich-khao-sat-xay-ads"],
    ["Nhận Báo Giá Trong 24h", "nhận báo giá trong 24h", "nhan-bao-gia-trong-24h-ads"],
    ["Ưu Đãi Xây Nhà Tháng Này", "ưu đãi xây nhà tháng này", "uu-dai-xay-nha-thang-nay-ads"],
    ["Khuyến Mãi Cải Tạo Nhà", "khuyến mãi cải tạo nhà", "khuyen-mai-cai-tao-nha-ads"],
    ["Gói Xây Nhà Siêu Tiết Kiệm", "gói xây nhà siêu tiết kiệm", "goi-xay-nha-sieu-tiet-kiem-ads"],
    ["Gói Xây Nhà Cao Cấp Plus", "gói xây nhà cao cấp plus", "goi-xay-nha-cao-cap-plus-ads"],
    ["Combo Thiết Kế Thi Công", "combo thiết kế thi công", "combo-thiet-ke-thi-cong-ads"],
    ["Sao Khuê Xây Nhà", "sao khuê xây nhà", "sao-khue-xay-nha-ads"],
    ["Kiến Trúc Sao Khuê", "kiến trúc sao khuê", "kien-truc-sao-khue-ads"],
  ]);

  return [b30, b31, b32, b33, b34].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 2447 + (batch - 30) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    30: "Cluster: chi phí, đơn giá, vật tư, tối ưu ngân sách.",
    31: "Cluster: nhà xanh, smart home, khí hậu, tiết kiệm năng lượng.",
    32: "Cluster: geo tỉnh thành vùng phụ cận & miền Nam.",
    33: "Cluster: loại hình thương mại, nhà trọ, homestay, PCCC.",
    34: "Cluster: thương hiệu vật tư, so sánh, Ads head commercial.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: chi phí, đơn giá, vật tư, tối ưu ngân sách.",
  "Cluster: nhà xanh, smart home, khí hậu, tiết kiệm năng lượng.",
  "Cluster: geo tỉnh thành vùng phụ cận & miền Nam.",
  "Cluster: loại hình thương mại, nhà trọ, homestay, PCCC.",
  "Cluster: thương hiệu vật tư, so sánh, Ads head commercial.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 30 + i;
  const startNo = 2447 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 30 ? 29 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
