/**
 * Generator: short-keyword batches 25–29 (500 articles, #1947–#2446).
 * Run: npx tsx scripts/gen-short-keyword-batches-25-29.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${25 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${25 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${25 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 25 — lỗi nhà / bệnh công trình
  const b25 = pairs([
    ["Nhà Bị Thấm Trần", "nhà bị thấm trần", "nha-bi-tham-tran"],
    ["Nhà Bị Thấm Tường", "nhà bị thấm tường", "nha-bi-tham-tuong"],
    ["Nhà Bị Nứt Tường", "nhà bị nứt tường", "nha-bi-nut-tuong"],
    ["Nhà Bị Nứt Trần", "nhà bị nứt trần", "nha-bi-nut-tran"],
    ["Nhà Bị Nghiêng", "nhà bị nghiêng", "nha-bi-nghieng"],
    ["Nhà Bị Lún", "nhà bị lún", "nha-bi-lun"],
    ["Nhà Bị Lún Không Đều", "nhà bị lún không đều", "nha-bi-lun-khong-deu"],
    ["Nhà Bị Rung", "nhà bị rung", "nha-bi-rung"],
    ["Nhà Bị Ồn", "nhà bị ồn", "nha-bi-on"],
    ["Nhà Bị Nóng", "nhà bị nóng", "nha-bi-nong"],
    ["Nhà Bị Ẩm", "nhà bị ẩm", "nha-bi-am"],
    ["Nhà Bị Mốc", "nhà bị mốc", "nha-bi-moc"],
    ["Nhà Bị Muối Hóa", "nhà bị muối hóa", "nha-bi-muoi-hoa"],
    ["Nhà Bị Phồng Sơn", "nhà bị phồng sơn", "nha-bi-phong-son"],
    ["Nhà Bị Bong Tróc Sơn", "nhà bị bong tróc sơn", "nha-bi-bong-troc-son"],
    ["Nhà Bị Nồm", "nhà bị nồm", "nha-bi-nom"],
    ["Nhà Bị Hôi", "nhà bị hôi", "nha-bi-hoi"],
    ["Nhà Bị Ruồi Muỗi", "nhà bị ruồi muỗi", "nha-bi-ruoi-muoi"],
    ["Nhà Bị Mối", "nhà bị mối", "nha-bi-moi"],
    ["Nhà Bị Mọt", "nhà bị mọt", "nha-bi-mot"],
    ["Sàn Nhà Bị Phồng", "sàn nhà bị phồng", "san-nha-bi-phong"],
    ["Sàn Nhà Bị Rộp", "sàn nhà bị rộp", "san-nha-bi-rop"],
    ["Gạch Lát Bị Rỗng", "gạch lát bị rỗng", "gach-lat-bi-rong"],
    ["Gạch Ốp Bị Bong", "gạch ốp bị bong", "gach-op-bi-bong"],
    ["Ron Gạch Bị Đen", "ron gạch bị đen", "ron-gach-bi-den"],
    ["Trần Thạch Cao Bị Sụp", "trần thạch cao bị sụp", "tran-thach-cao-bi-sup"],
    ["Trần Thạch Cao Bị Ố", "trần thạch cao bị ố", "tran-thach-cao-bi-o"],
    ["Cửa Gỗ Bị Cong", "cửa gỗ bị cong", "cua-go-bi-cong"],
    ["Cửa Nhôm Bị Kẹt", "cửa nhôm bị kẹt", "cua-nhom-bi-ket"],
    ["Cửa Kính Bị Ồn", "cửa kính bị ồn", "cua-kinh-bi-on"],
    ["Lan Can Bị Rỉ", "lan can bị rỉ", "lan-can-bi-ri"],
    ["Mái Tôn Bị Dột", "mái tôn bị dột", "mai-ton-bi-dot"],
    ["Mái Tôn Bị Nóng", "mái tôn bị nóng", "mai-ton-bi-nong"],
    ["Mái Tôn Bị Ồn Mưa", "mái tôn bị ồn mưa", "mai-ton-bi-on-mua"],
    ["Ống Nước Bị Tắc", "ống nước bị tắc", "ong-nuoc-bi-tac"],
    ["Ống Nước Bị Rò", "ống nước bị rò", "ong-nuoc-bi-ro"],
    ["Ống Nước Bị Ồn", "ống nước bị ồn", "ong-nuoc-bi-on"],
    ["Bồn Cầu Bị Tắc", "bồn cầu bị tắc", "bon-cau-bi-tac"],
    ["Bồn Cầu Bị Rò", "bồn cầu bị rò", "bon-cau-bi-ro"],
    ["Sen Tắm Áp Lực Yếu", "sen tắm áp lực yếu", "sen-tam-ap-luc-yeu"],
    ["Điện Nhà Bị Nhảy", "điện nhà bị nhảy", "dien-nha-bi-nhay"],
    ["Điện Nhà Bị Chập", "điện nhà bị chập", "dien-nha-bi-chap"],
    ["Đèn Nhà Hay Cháy", "đèn nhà hay cháy", "den-nha-hay-chay"],
    ["Máy Lạnh Không Mát", "máy lạnh không mát", "may-lanh-khong-mat"],
    ["Máy Lạnh Chảy Nước", "máy lạnh chảy nước", "may-lanh-chay-nuoc"],
    ["Nhà Bí Khí", "nhà bí khí", "nha-bi-khi"],
    ["Nhà Thiếu Sáng", "nhà thiếu sáng", "nha-thieu-sang"],
    ["Nhà Bí Bếp", "nhà bí bếp", "nha-bi-bep"],
    ["Nhà Bí WC", "nhà bí wc", "nha-bi-wc"],
    ["Nhà Hôi WC", "nhà hôi wc", "nha-hoi-wc"],
    ["Nhà Hôi Cống", "nhà hôi cống", "nha-hoi-cong"],
    ["Sân Thượng Ngập Nước", "sân thượng ngập nước", "san-thuong-ngap-nuoc"],
    ["Sân Trước Ngập", "sân trước ngập", "san-truoc-ngap"],
    ["Nhà Ngập Khi Mưa", "nhà ngập khi mưa", "nha-ngap-khi-mua"],
    ["Tường Nhà Bị Rêu", "tường nhà bị rêu", "tuong-nha-bi-reu"],
    ["Tường Nhà Bị Ố Vàng", "tường nhà bị ố vàng", "tuong-nha-bi-o-vang"],
    ["Cột Nhà Bị Nứt", "cột nhà bị nứt", "cot-nha-bi-nut"],
    ["Dầm Nhà Bị Nứt", "dầm nhà bị nứt", "dam-nha-bi-nut"],
    ["Sàn Nhà Bị Võng", "sàn nhà bị võng", "san-nha-bi-vong"],
    ["Cầu Thang Bị Rung", "cầu thang bị rung", "cau-thang-bi-rung"],
    ["Cầu Thang Bị Trơn", "cầu thang bị trơn", "cau-thang-bi-tron"],
    ["Ban Công Bị Dột", "ban công bị dột", "ban-cong-bi-dot"],
    ["Ban Công Bị Nứt", "ban công bị nứt", "ban-cong-bi-nut"],
    ["Giếng Trời Bị Dột", "giếng trời bị dột", "gieng-troi-bi-dot"],
    ["Giếng Trời Bị Nóng", "giếng trời bị nóng", "gieng-troi-bi-nong"],
    ["Nhà Bị Mất Điện Thường Xuyên", "nhà bị mất điện thường xuyên", "nha-bi-mat-dien-thuong-xuyen"],
    ["Nhà Bị Áp Lực Nước Yếu", "nhà bị áp lực nước yếu", "nha-bi-ap-luc-nuoc-yeu"],
    ["Bể Phốt Đầy", "bể phốt đầy", "be-phot-day"],
    ["Bể Phốt Hôi", "bể phốt hôi", "be-phot-hoi"],
    ["Hút Bể Phốt Định Kỳ", "hút bể phốt định kỳ", "hut-be-phot-dinh-ky"],
    ["Thông Cống Nghẹt", "thông cống nghẹt", "thong-cong-nghet"],
    ["Xử Lý Mối Nhà", "xử lý mối nhà", "xu-ly-moi-nha"],
    ["Phòng Chống Mối", "phòng chống mối", "phong-chong-moi"],
    ["Xử Lý Mốc Tường", "xử lý mốc tường", "xu-ly-moc-tuong"],
    ["Xử Lý Ẩm Tường", "xử lý ẩm tường", "xu-ly-am-tuong"],
    ["Xử Lý Muối Hóa Tường", "xử lý muối hóa tường", "xu-ly-muoi-hoa-tuong"],
    ["Xử Lý Nồm Nhà", "xử lý nồm nhà", "xu-ly-nom-nha"],
    ["Xử Lý Nhà Bí", "xử lý nhà bí", "xu-ly-nha-bi"],
    ["Xử Lý Nhà Thiếu Sáng", "xử lý nhà thiếu sáng", "xu-ly-nha-thieu-sang"],
    ["Xử Lý Nhà Nóng", "xử lý nhà nóng", "xu-ly-nha-nong"],
    ["Xử Lý Nhà Ồn", "xử lý nhà ồn", "xu-ly-nha-on"],
    ["Gia Cố Nhà Nghiêng", "gia cố nhà nghiêng", "gia-co-nha-nghieng"],
    ["Gia Cố Nhà Lún", "gia cố nhà lún", "gia-co-nha-lun"],
    ["Nâng Nhà Bị Lún", "nâng nhà bị lún", "nang-nha-bi-lun"],
    ["Ép Cọc Gia Cố Nhà Cũ", "ép cọc gia cố nhà cũ", "ep-coc-gia-co-nha-cu"],
    ["Neo Đất Chống Lún", "neo đất chống lún", "neo-dat-chong-lun"],
    ["Sửa Nhà Sau Mưa Bão", "sửa nhà sau mưa bão", "sua-nha-sau-mua-bao"],
    ["Sửa Nhà Sau Ngập", "sửa nhà sau ngập", "sua-nha-sau-ngap"],
    ["Khôi Phục Nhà Sau Hỏa Hoạn", "khôi phục nhà sau hỏa hoạn", "khoi-phuc-nha-sau-hoa-hoan"],
    ["Sửa Nhà Sau Động Đất", "sửa nhà sau động đất", "sua-nha-sau-dong-dat"],
    ["Kiểm Tra An Toàn Nhà Cũ", "kiểm tra an toàn nhà cũ", "kiem-tra-an-toan-nha-cu"],
    ["Đánh Giá Nguy Cơ Sập", "đánh giá nguy cơ sập", "danh-gia-nguy-co-sap"],
    ["Gia Cố Khẩn Cấp Nhà", "gia cố khẩn cấp nhà", "gia-co-khan-cap-nha"],
    ["Chống Sập Nhà Cũ", "chống sập nhà cũ", "chong-sap-nha-cu"],
    ["Gia Cố Tường Bao", "gia cố tường bao", "gia-co-tuong-bao"],
    ["Gia Cố Mái Cũ", "gia cố mái cũ", "gia-co-mai-cu"],
    ["Thay Mái Tôn Cũ", "thay mái tôn cũ", "thay-mai-ton-cu"],
    ["Thay Hệ Thống Điện Cũ", "thay hệ thống điện cũ", "thay-he-thong-dien-cu"],
    ["Thay Hệ Thống Nước Cũ", "thay hệ thống nước cũ", "thay-he-thong-nuoc-cu"],
    ["Nâng Cấp Nhà Cũ", "nâng cấp nhà cũ", "nang-cap-nha-cu"],
    ["Làm Mới Nhà 20 Năm", "làm mới nhà 20 năm", "lam-moi-nha-20-nam"],
    ["Làm Mới Nhà 30 Năm", "làm mới nhà 30 năm", "lam-moi-nha-30-nam"],
  ]);

  // 26 — quy mô diện tích / số tầng chi tiết
  const b26 = pairs([
    ["Xây Nhà 30m2", "xây nhà 30m2", "xay-nha-30m2"],
    ["Xây Nhà 35m2", "xây nhà 35m2", "xay-nha-35m2"],
    ["Xây Nhà 45m2", "xây nhà 45m2", "xay-nha-45m2"],
    ["Xây Nhà 55m2", "xây nhà 55m2", "xay-nha-55m2"],
    ["Xây Nhà 70m2", "xây nhà 70m2", "xay-nha-70m2"],
    ["Xây Nhà 90m2", "xây nhà 90m2", "xay-nha-90m2"],
    ["Xây Nhà 120m2", "xây nhà 120m2", "xay-nha-120m2"],
    ["Xây Nhà 150m2", "xây nhà 150m2", "xay-nha-150m2"],
    ["Xây Nhà 200m2", "xây nhà 200m2", "xay-nha-200m2"],
    ["Xây Nhà 250m2", "xây nhà 250m2", "xay-nha-250m2"],
    ["Xây Nhà 300m2", "xây nhà 300m2", "xay-nha-300m2"],
    ["Xây Nhà 4x12", "xây nhà 4x12", "xay-nha-4x12"],
    ["Xây Nhà 4x16", "xây nhà 4x16", "xay-nha-4x16"],
    ["Xây Nhà 4x20", "xây nhà 4x20", "xay-nha-4x20"],
    ["Xây Nhà 5x15", "xây nhà 5x15", "xay-nha-5x15"],
    ["Xây Nhà 5x20", "xây nhà 5x20", "xay-nha-5x20"],
    ["Xây Nhà 5x25", "xây nhà 5x25", "xay-nha-5x25"],
    ["Xây Nhà 6x15", "xây nhà 6x15", "xay-nha-6x15"],
    ["Xây Nhà 6x18", "xây nhà 6x18", "xay-nha-6x18"],
    ["Xây Nhà 6x20", "xây nhà 6x20", "xay-nha-6x20"],
    ["Xây Nhà 7x15", "xây nhà 7x15", "xay-nha-7x15"],
    ["Xây Nhà 7x20", "xây nhà 7x20", "xay-nha-7x20"],
    ["Xây Nhà 8x15", "xây nhà 8x15", "xay-nha-8x15"],
    ["Xây Nhà 8x20", "xây nhà 8x20", "xay-nha-8x20"],
    ["Xây Nhà 10x20", "xây nhà 10x20", "xay-nha-10x20"],
    ["Nhà 1 Trệt", "nhà 1 trệt", "nha-1-tret"],
    ["Nhà 1 Trệt 3 Lầu", "nhà 1 trệt 3 lầu", "nha-1-tret-3-lau"],
    ["Nhà 1 Trệt 4 Lầu", "nhà 1 trệt 4 lầu", "nha-1-tret-4-lau"],
    ["Nhà Lửng 1 Tầng", "nhà lửng 1 tầng", "nha-lung-1-tang"],
    ["Nhà Lửng 2 Tầng", "nhà lửng 2 tầng", "nha-lung-2-tang"],
    ["Nhà Có Áp Mái", "nhà có áp mái", "nha-co-ap-mai"],
    ["Nhà Có Tum", "nhà có tum", "nha-co-tum"],
    ["Nhà Có Sân Thượng", "nhà có sân thượng", "nha-co-san-thuong"],
    ["Nhà 3 Phòng Ngủ", "nhà 3 phòng ngủ", "nha-3-phong-ngu"],
    ["Nhà 4 Phòng Ngủ", "nhà 4 phòng ngủ", "nha-4-phong-ngu"],
    ["Nhà 5 Phòng Ngủ", "nhà 5 phòng ngủ", "nha-5-phong-ngu"],
    ["Nhà 2 WC", "nhà 2 wc", "nha-2-wc"],
    ["Nhà 3 WC", "nhà 3 wc", "nha-3-wc"],
    ["Nhà 4 WC", "nhà 4 wc", "nha-4-wc"],
    ["Nhà Có Master Bedroom", "nhà có master bedroom", "nha-co-master-bedroom"],
    ["Nhà Có Walk In Closet", "nhà có walk in closet", "nha-co-walk-in-closet"],
    ["Nhà Có Phòng Đệm", "nhà có phòng đệm", "nha-co-phong-dem"],
    ["Nhà Có Sảnh Đón", "nhà có sảnh đón", "nha-co-sanh-don"],
    ["Nhà Có Phòng Khách Đôi", "nhà có phòng khách đôi", "nha-co-phong-khach-doi"],
    ["Nhà Bếp Mở", "nhà bếp mở", "nha-bep-mo"],
    ["Nhà Bếp Kín", "nhà bếp kín", "nha-bep-kin"],
    ["Nhà Bếp Đảo", "nhà bếp đảo", "nha-bep-dao"],
    ["Nhà Có Phòng Ăn Riêng", "nhà có phòng ăn riêng", "nha-co-phong-an-rieng"],
    ["Nhà Có Gara 1 Xe", "nhà có gara 1 xe", "nha-co-gara-1-xe"],
    ["Nhà Có Gara 2 Xe", "nhà có gara 2 xe", "nha-co-gara-2-xe"],
    ["Nhà Có Chỗ Để Xe Máy", "nhà có chỗ để xe máy", "nha-co-cho-de-xe-may"],
    ["Nhà Hẻm 2m", "nhà hẻm 2m", "nha-hem-2m"],
    ["Nhà Hẻm 3m", "nhà hẻm 3m", "nha-hem-3m"],
    ["Nhà Hẻm 4m", "nhà hẻm 4m", "nha-hem-4m"],
    ["Nhà Hẻm 5m", "nhà hẻm 5m", "nha-hem-5m"],
    ["Nhà Hẻm Xe Hơi", "nhà hẻm xe hơi", "nha-hem-xe-hoi"],
    ["Nhà Mặt Tiền 4m", "nhà mặt tiền 4m", "nha-mat-tien-4m"],
    ["Nhà Mặt Tiền 5m", "nhà mặt tiền 5m", "nha-mat-tien-5m"],
    ["Nhà Mặt Tiền 6m", "nhà mặt tiền 6m", "nha-mat-tien-6m"],
    ["Nhà Mặt Tiền 8m", "nhà mặt tiền 8m", "nha-mat-tien-8m"],
    ["Nhà Mặt Tiền 10m", "nhà mặt tiền 10m", "nha-mat-tien-10m"],
    ["Xây Nhà Trên Đất 4x10", "xây nhà trên đất 4x10", "xay-nha-tren-dat-4x10"],
    ["Xây Nhà Trên Đất 5x12", "xây nhà trên đất 5x12", "xay-nha-tren-dat-5x12"],
    ["Xây Nhà Trên Đất 5x16", "xây nhà trên đất 5x16", "xay-nha-tren-dat-5x16"],
    ["Xây Nhà Trên Đất 6x12", "xây nhà trên đất 6x12", "xay-nha-tren-dat-6x12"],
    ["Xây Nhà Trên Đất 6x16", "xây nhà trên đất 6x16", "xay-nha-tren-dat-6x16"],
    ["Chi Phí Xây Nhà 4x12", "chi phí xây nhà 4x12", "chi-phi-xay-nha-4x12"],
    ["Chi Phí Xây Nhà 5x20", "chi phí xây nhà 5x20", "chi-phi-xay-nha-5x20"],
    ["Chi Phí Xây Nhà 6x20", "chi phí xây nhà 6x20", "chi-phi-xay-nha-6x20"],
    ["Chi Phí Xây Nhà 100m2", "chi phí xây nhà 100m2", "chi-phi-xay-nha-100m2"],
    ["Chi Phí Xây Nhà 150m2", "chi phí xây nhà 150m2", "chi-phi-xay-nha-150m2"],
    ["Báo Giá Nhà 1 Trệt 1 Lầu", "báo giá nhà 1 trệt 1 lầu", "bao-gia-nha-1-tret-1-lau"],
    ["Báo Giá Nhà 1 Trệt 2 Lầu", "báo giá nhà 1 trệt 2 lầu", "bao-gia-nha-1-tret-2-lau"],
    ["Báo Giá Nhà 3 Tầng", "báo giá nhà 3 tầng", "bao-gia-nha-3-tang"],
    ["Báo Giá Nhà 4 Tầng", "báo giá nhà 4 tầng", "bao-gia-nha-4-tang"],
    ["Báo Giá Nhà 5 Tầng", "báo giá nhà 5 tầng", "bao-gia-nha-5-tang"],
    ["Thiết Kế Nhà 4x12", "thiết kế nhà 4x12", "thiet-ke-nha-4x12"],
    ["Thiết Kế Nhà 5x20", "thiết kế nhà 5x20", "thiet-ke-nha-5x20"],
    ["Thiết Kế Nhà 6x20", "thiết kế nhà 6x20", "thiet-ke-nha-6x20"],
    ["Mẫu Nhà 4x12", "mẫu nhà 4x12", "mau-nha-4x12"],
    ["Mẫu Nhà 5x20", "mẫu nhà 5x20", "mau-nha-5x20"],
    ["Mẫu Nhà 6x20", "mẫu nhà 6x20", "mau-nha-6x20"],
    ["Mẫu Nhà 1 Trệt 1 Lầu", "mẫu nhà 1 trệt 1 lầu", "mau-nha-1-tret-1-lau"],
    ["Mẫu Nhà 1 Trệt 2 Lầu", "mẫu nhà 1 trệt 2 lầu", "mau-nha-1-tret-2-lau"],
    ["Mẫu Nhà 1 Trệt 3 Lầu", "mẫu nhà 1 trệt 3 lầu", "mau-nha-1-tret-3-lau"],
    ["Nhà Ống 4m", "nhà ống 4m", "nha-ong-4m"],
    ["Nhà Ống 5m", "nhà ống 5m", "nha-ong-5m"],
    ["Nhà Phố 2 Mặt Tiền", "nhà phố 2 mặt tiền", "nha-pho-2-mat-tien"],
    ["Nhà Phố 3 Mặt Tiền", "nhà phố 3 mặt tiền", "nha-pho-3-mat-tien"],
    ["Nhà Góc 2 Mặt Tiền", "nhà góc 2 mặt tiền", "nha-goc-2-mat-tien"],
    ["Nhà Cuối Hẻm", "nhà cuối hẻm", "nha-cuoi-hem"],
    ["Nhà Đầu Hẻm", "nhà đầu hẻm", "nha-dau-hem"],
    ["Nhà Giữa Hẻm", "nhà giữa hẻm", "nha-giua-hem"],
  ]);

  // 27 — dịch vụ chuyên biệt / hạng mục
  const b27 = pairs([
    ["Thi Công Sàn Gỗ", "thi công sàn gỗ", "thi-cong-san-go"],
    ["Thi Công Trần Thạch Cao", "thi công trần thạch cao", "thi-cong-tran-thach-cao"],
    ["Thi Công Sơn Nước", "thi công sơn nước", "thi-cong-son-nuoc"],
    ["Thi Công Ốp Lát", "thi công ốp lát", "thi-cong-op-lat"],
    ["Thi Công Điện Nước", "thi công điện nước", "thi-cong-dien-nuoc"],
    ["Thi Công Chống Thấm", "thi công chống thấm", "thi-cong-chong-tham"],
    ["Thi Công Cửa Nhôm", "thi công cửa nhôm", "thi-cong-cua-nhom"],
    ["Thi Công Cửa Gỗ", "thi công cửa gỗ", "thi-cong-cua-go"],
    ["Thi Công Lan Can", "thi công lan can", "thi-cong-lan-can"],
    ["Thi Công Cổng Rào", "thi công cổng rào", "thi-cong-cong-rao"],
    ["Thi Công Mái Tôn", "thi công mái tôn", "thi-cong-mai-ton"],
    ["Thi Công Mái Ngói", "thi công mái ngói", "thi-cong-mai-ngoi"],
    ["Thi Công Giếng Trời", "thi công giếng trời", "thi-cong-gieng-troi"],
    ["Thi Công Cầu Thang", "thi công cầu thang", "thi-cong-cau-thang"],
    ["Thi Công Thang Máy", "thi công thang máy", "thi-cong-thang-may"],
    ["Thi Công Gara", "thi công gara", "thi-cong-gara"],
    ["Thi Công Sân Thượng", "thi công sân thượng", "thi-cong-san-thuong"],
    ["Thi Công Sân Vườn", "thi công sân vườn", "thi-cong-san-vuon"],
    ["Thi Công Hồ Cá Koi", "thi công hồ cá koi", "thi-cong-ho-ca-koi"],
    ["Thi Công Hồ Bơi", "thi công hồ bơi", "thi-cong-ho-boi"],
    ["Thi Công Phòng Xông", "thi công phòng xông", "thi-cong-phong-xong"],
    ["Thi Công Phòng Gym", "thi công phòng gym", "thi-cong-phong-gym"],
    ["Thi Công Phòng Karaoke", "thi công phòng karaoke", "thi-cong-phong-karaoke"],
    ["Thi Công Tủ Bếp", "thi công tủ bếp", "thi-cong-tu-bep"],
    ["Thi Công Tủ Áo", "thi công tủ áo", "thi-cong-tu-ao"],
    ["Thi Công Vách Ngăn", "thi công vách ngăn", "thi-cong-vach-ngan"],
    ["Thi Công Sàn Epoxy", "thi công sàn epoxy", "thi-cong-san-epoxy"],
    ["Thi Công Sàn SPC", "thi công sàn spc", "thi-cong-san-spc"],
    ["Thi Công Giấy Dán Tường", "thi công giấy dán tường", "thi-cong-giay-dan-tuong"],
    ["Thi Công Đèn LED", "thi công đèn led", "thi-cong-den-led"],
    ["Lắp Đặt Camera Nhà", "lắp đặt camera nhà", "lap-dat-camera-nha"],
    ["Lắp Đặt Khóa Vân Tay", "lắp đặt khóa vân tay", "lap-dat-khoa-van-tay"],
    ["Lắp Đặt Cổng Tự Động", "lắp đặt cổng tự động", "lap-dat-cong-tu-dong"],
    ["Lắp Đặt Máy Lạnh Multi", "lắp đặt máy lạnh multi", "lap-dat-may-lanh-multi"],
    ["Lắp Đặt Năng Lượng Mặt Trời", "lắp đặt năng lượng mặt trời", "lap-dat-nang-luong-mat-troi"],
    ["Lắp Đặt Bình Nóng Lạnh", "lắp đặt bình nóng lạnh", "lap-dat-binh-nong-lanh"],
    ["Lắp Đặt Máy Bơm", "lắp đặt máy bơm", "lap-dat-may-bom"],
    ["Lắp Đặt Bồn Nước", "lắp đặt bồn nước", "lap-dat-bon-nuoc"],
    ["Lắp Đặt Bể Phốt", "lắp đặt bể phốt", "lap-dat-be-phot"],
    ["Lắp Đặt Hệ Thống PCCC", "lắp đặt hệ thống pccc", "lap-dat-he-thong-pccc"],
    ["Bảo Trì Máy Lạnh Nhà", "bảo trì máy lạnh nhà", "bao-tri-may-lanh-nha"],
    ["Bảo Trì Thang Máy Nhà", "bảo trì thang máy nhà", "bao-tri-thang-may-nha"],
    ["Bảo Trì Cổng Tự Động", "bảo trì cổng tự động", "bao-tri-cong-tu-dong"],
    ["Bảo Trì Hồ Bơi Nhà", "bảo trì hồ bơi nhà", "bao-tri-ho-boi-nha"],
    ["Vệ Sinh Hồ Cá Koi", "vệ sinh hồ cá koi", "ve-sinh-ho-ca-koi"],
    ["Vệ Sinh Sân Thượng", "vệ sinh sân thượng", "ve-sinh-san-thuong"],
    ["Vệ Sinh Mái Tôn", "vệ sinh mái tôn", "ve-sinh-mai-ton"],
    ["Vệ Sinh Trần Thạch Cao", "vệ sinh trần thạch cao", "ve-sinh-tran-thach-cao"],
    ["Sơn Lại Nhà Cũ", "sơn lại nhà cũ", "son-lai-nha-cu"],
    ["Sơn Lại Mặt Tiền", "sơn lại mặt tiền", "son-lai-mat-tien"],
    ["Sơn Lại Trong Nhà", "sơn lại trong nhà", "son-lai-trong-nha"],
    ["Đánh Bóng Sàn Nhà", "đánh bóng sàn nhà", "danh-bong-san-nha"],
    ["Đánh Bóng Đá Hoa Cương", "đánh bóng đá hoa cương", "danh-bong-da-hoa-cuong"],
    ["Chà Ron Gạch Lại", "chà ron gạch lại", "cha-ron-gach-lai"],
    ["Thay Ron Gạch", "thay ron gạch", "thay-ron-gach"],
    ["Thay Gạch Lát Nền", "thay gạch lát nền", "thay-gach-lat-nen"],
    ["Thay Gạch Ốp Tường", "thay gạch ốp tường", "thay-gach-op-tuong"],
    ["Thay Cửa Gỗ Cũ", "thay cửa gỗ cũ", "thay-cua-go-cu"],
    ["Thay Cửa Nhôm Cũ", "thay cửa nhôm cũ", "thay-cua-nhom-cu"],
    ["Thay Lan Can Cũ", "thay lan can cũ", "thay-lan-can-cu"],
    ["Thay Cổng Rào Cũ", "thay cổng rào cũ", "thay-cong-rao-cu"],
    ["Nâng Cấp Nội Thất", "nâng cấp nội thất", "nang-cap-noi-that"],
    ["Nâng Cấp Điện Nước", "nâng cấp điện nước", "nang-cap-dien-nuoc"],
    ["Nâng Cấp Mặt Tiền", "nâng cấp mặt tiền", "nang-cap-mat-tien"],
    ["Nâng Cấp Sân Vườn", "nâng cấp sân vườn", "nang-cap-san-vuon"],
    ["Nâng Cấp Sân Thượng", "nâng cấp sân thượng", "nang-cap-san-thuong"],
    ["Gói Bảo Trì Nhà Năm", "gói bảo trì nhà năm", "goi-bao-tri-nha-nam"],
    ["Gói Bảo Trì Nhà Quý", "gói bảo trì nhà quý", "goi-bao-tri-nha-quy"],
    ["Gói Vệ Sinh Nhà Tháng", "gói vệ sinh nhà tháng", "goi-ve-sinh-nha-thang"],
    ["Dịch Vụ Quản Gia Nhà", "dịch vụ quản gia nhà", "dich-vu-quan-gia-nha"],
    ["Dịch Vụ Chăm Sóc Nhà", "dịch vụ chăm sóc nhà", "dich-vu-cham-soc-nha"],
    ["Dịch Vụ Sửa Chữa Nhanh", "dịch vụ sửa chữa nhanh", "dich-vu-sua-chua-nhanh"],
    ["Thợ Sửa Nhà Khẩn Cấp", "thợ sửa nhà khẩn cấp", "tho-sua-nha-khan-cap"],
    ["Thợ Điện Nước Khẩn Cấp", "thợ điện nước khẩn cấp", "tho-dien-nuoc-khan-cap"],
    ["Thợ Chống Thấm Khẩn Cấp", "thợ chống thấm khẩn cấp", "tho-chong-tham-khan-cap"],
    ["Thợ Sơn Nhà Tận Nơi", "thợ sơn nhà tận nơi", "tho-son-nha-tan-noi"],
    ["Thợ Ốp Lát Tận Nơi", "thợ ốp lát tận nơi", "tho-op-lat-tan-noi"],
    ["Thợ Trần Thạch Cao", "thợ trần thạch cao", "tho-tran-thach-cao"],
    ["Thợ Nhôm Kính Tận Nơi", "thợ nhôm kính tận nơi", "tho-nhom-kinh-tan-noi"],
    ["Đội Thợ Xây Nhà", "đội thợ xây nhà", "doi-tho-xay-nha"],
    ["Đội Thợ Cải Tạo", "đội thợ cải tạo", "doi-tho-cai-tao"],
    ["Đội Thợ Hoàn Thiện", "đội thợ hoàn thiện", "doi-tho-hoan-thien"],
    ["Nhân Công Xây Nhà", "nhân công xây nhà", "nhan-cong-xay-nha"],
    ["Nhân Công Hoàn Thiện", "nhân công hoàn thiện", "nhan-cong-hoan-thien"],
    ["Thuê Nhân Công Xây", "thuê nhân công xây", "thue-nhan-cong-xay"],
    ["Thuê Đội Thợ Xây", "thuê đội thợ xây", "thue-doi-tho-xay"],
    ["Giá Nhân Công Xây 2026", "giá nhân công xây 2026", "gia-nhan-cong-xay-2026"],
    ["Đơn Giá Nhân Công m2", "đơn giá nhân công m2", "don-gia-nhan-cong-m2"],
    ["Bảng Giá Nhân Công Xây", "bảng giá nhân công xây", "bang-gia-nhan-cong-xay"],
  ]);

  // 28 — geo phường/xã & thương mại địa phương
  const b28 = pairs([
    ["Xây Nhà Thảo Điền", "xây nhà Thảo Điền", "xay-nha-thao-dien"],
    ["Xây Nhà An Phú", "xây nhà An Phú", "xay-nha-an-phu"],
    ["Xây Nhà Bình An", "xây nhà Bình An", "xay-nha-binh-an"],
    ["Xây Nhà Cat Lai", "xây nhà Cát Lái", "xay-nha-cat-lai"],
    ["Xây Nhà Phú Hữu", "xây nhà Phú Hữu", "xay-nha-phu-huu"],
    ["Xây Nhà Tăng Nhơn Phú", "xây nhà Tăng Nhơn Phú", "xay-nha-tang-nhon-phu"],
    ["Xây Nhà Long Trường", "xây nhà Long Trường", "xay-nha-long-truong"],
    ["Xây Nhà Long Phước", "xây nhà Long Phước", "xay-nha-long-phuoc"],
    ["Xây Nhà Trường Thọ", "xây nhà Trường Thọ", "xay-nha-truong-tho"],
    ["Xây Nhà Bình Thọ", "xây nhà Bình Thọ", "xay-nha-binh-tho"],
    ["Xây Nhà Linh Chiểu", "xây nhà Linh Chiểu", "xay-nha-linh-chieu"],
    ["Xây Nhà Linh Trung", "xây nhà Linh Trung", "xay-nha-linh-trung"],
    ["Xây Nhà Linh Đông", "xây nhà Linh Đông", "xay-nha-linh-dong"],
    ["Xây Nhà Hiệp Phú", "xây nhà Hiệp Phú", "xay-nha-hiep-phu"],
    ["Xây Nhà Tân Phú Thủ Đức", "xây nhà Tân Phú Thủ Đức", "xay-nha-tan-phu-thu-duc"],
    ["Xây Nhà Phước Long", "xây nhà Phước Long", "xay-nha-phuoc-long"],
    ["Xây Nhà An Khánh", "xây nhà An Khánh", "xay-nha-an-khanh"],
    ["Xây Nhà Thủ Thiêm Mới", "xây nhà Thủ Thiêm mới", "xay-nha-thu-thiem-moi"],
    ["Xây Nhà Vinhomes", "xây nhà Vinhomes", "xay-nha-vinhomes"],
    ["Cải Tạo Nhà Vinhomes", "cải tạo nhà Vinhomes", "cai-tao-nha-vinhomes"],
    ["Xây Nhà KĐT Phú Mỹ Hưng", "xây nhà KĐT Phú Mỹ Hưng", "xay-nha-kdt-phu-my-hung"],
    ["Cải Tạo Nhà Phú Mỹ Hưng", "cải tạo nhà Phú Mỹ Hưng", "cai-tao-nha-phu-my-hung"],
    ["Xây Nhà Sala", "xây nhà Sala", "xay-nha-sala"],
    ["Xây Nhà Landmark", "xây nhà Landmark", "xay-nha-landmark"],
    ["Sửa Nhà Thảo Điền", "sửa nhà Thảo Điền", "sua-nha-thao-dien"],
    ["Sửa Nhà An Phú", "sửa nhà An Phú", "sua-nha-an-phu"],
    ["Cải Tạo Nhà Thảo Điền", "cải tạo nhà Thảo Điền", "cai-tao-nha-thao-dien"],
    ["Cải Tạo Nhà An Phú", "cải tạo nhà An Phú", "cai-tao-nha-an-phu"],
    ["Xây Nhà Trọn Gói Thảo Điền", "xây nhà trọn gói Thảo Điền", "xay-nha-tron-goi-thao-dien"],
    ["Xây Nhà Trọn Gói An Phú", "xây nhà trọn gói An Phú", "xay-nha-tron-goi-an-phu"],
    ["Xây Nhà Quận Bình Tân", "xây nhà quận Bình Tân", "xay-nha-quan-binh-tan"],
    ["Xây Nhà An Lạc", "xây nhà An Lạc", "xay-nha-an-lac"],
    ["Xây Nhà Bình Trị Đông", "xây nhà Bình Trị Đông", "xay-nha-binh-tri-dong"],
    ["Xây Nhà Tân Tạo", "xây nhà Tân Tạo", "xay-nha-tan-tao"],
    ["Xây Nhà Bình Hưng Hòa", "xây nhà Bình Hưng Hòa", "xay-nha-binh-hung-hoa"],
    ["Xây Nhà Sơn Kỳ", "xây nhà Sơn Kỳ", "xay-nha-son-ky"],
    ["Xây Nhà Tân Quý", "xây nhà Tân Quý", "xay-nha-tan-quy"],
    ["Xây Nhà Hòa Thạnh", "xây nhà Hòa Thạnh", "xay-nha-hoa-thanh"],
    ["Xây Nhà Phú Thọ Hòa", "xây nhà Phú Thọ Hòa", "xay-nha-phu-tho-hoa"],
    ["Xây Nhà Tây Thạnh", "xây nhà Tây Thạnh", "xay-nha-tay-thanh"],
    ["Xây Nhà Hiệp Thành", "xây nhà Hiệp Thành", "xay-nha-hiep-thanh"],
    ["Xây Nhà Thạnh Xuân", "xây nhà Thạnh Xuân", "xay-nha-thanh-xuan"],
    ["Xây Nhà Thạnh Lộc", "xây nhà Thạnh Lộc", "xay-nha-thanh-loc"],
    ["Xây Nhà An Phú Đông", "xây nhà An Phú Đông", "xay-nha-an-phu-dong"],
    ["Xây Nhà Trung Mỹ Tây", "xây nhà Trung Mỹ Tây", "xay-nha-trung-my-tay"],
    ["Xây Nhà Tân Chánh Hiệp", "xây nhà Tân Chánh Hiệp", "xay-nha-tan-chanh-hiep"],
    ["Xây Nhà Đông Hưng Thuận", "xây nhà Đông Hưng Thuận", "xay-nha-dong-hung-thuan"],
    ["Xây Nhà Tân Hưng Thuận", "xây nhà Tân Hưng Thuận", "xay-nha-tan-hung-thuan"],
    ["Xây Nhà Tân Thới Nhất", "xây nhà Tân Thới Nhất", "xay-nha-tan-thoi-nhat"],
    ["Xây Nhà Bà Điểm", "xây nhà Bà Điểm", "xay-nha-ba-diem"],
    ["Xây Nhà Xuân Thới Sơn", "xây nhà Xuân Thới Sơn", "xay-nha-xuan-thoi-son"],
    ["Xây Nhà Đông Thạnh", "xây nhà Đông Thạnh", "xay-nha-dong-thanh"],
    ["Xây Nhà Nhị Bình", "xây nhà Nhị Bình", "xay-nha-nhi-binh"],
    ["Xây Nhà Trung Chánh", "xây nhà Trung Chánh", "xay-nha-trung-chanh"],
    ["Xây Nhà Thới Tam Thôn", "xây nhà Thới Tam Thôn", "xay-nha-thoi-tam-thon"],
    ["Xây Nhà Xuân Thới Đông", "xây nhà Xuân Thới Đông", "xay-nha-xuan-thoi-dong"],
    ["Xây Nhà Tân Thới Nhì", "xây nhà Tân Thới Nhì", "xay-nha-tan-thoi-nhi"],
    ["Xây Nhà Xuân Thới Thượng", "xây nhà Xuân Thới Thượng", "xay-nha-xuan-thoi-thuong"],
    ["Xây Nhà Phạm Văn Hai", "xây nhà Phạm Văn Hai", "xay-nha-pham-van-hai"],
    ["Xây Nhà Vĩnh Lộc A", "xây nhà Vĩnh Lộc A", "xay-nha-vinh-loc-a"],
    ["Xây Nhà Vĩnh Lộc B", "xây nhà Vĩnh Lộc B", "xay-nha-vinh-loc-b"],
    ["Xây Nhà Bình Hưng", "xây nhà Bình Hưng", "xay-nha-binh-hung"],
    ["Xây Nhà Phong Phú", "xây nhà Phong Phú", "xay-nha-phong-phu"],
    ["Xây Nhà Đa Phước", "xây nhà Đa Phước", "xay-nha-da-phuoc"],
    ["Xây Nhà Hưng Long", "xây nhà Hưng Long", "xay-nha-hung-long"],
    ["Xây Nhà Quy Đức", "xây nhà Quy Đức", "xay-nha-quy-duc"],
    ["Xây Nhà An Phú Tây", "xây nhà An Phú Tây", "xay-nha-an-phu-tay"],
    ["Xây Nhà Tân Quý Tây", "xây nhà Tân Quý Tây", "xay-nha-tan-quy-tay"],
    ["Xây Nhà Bình Chánh Trung", "xây nhà Bình Chánh", "xay-nha-binh-chanh-trung"],
    ["Xây Nhà Nhà Bè Thị Trấn", "xây nhà Nhà Bè", "xay-nha-nha-be-thi-tran"],
    ["Xây Nhà Phú Xuân", "xây nhà Phú Xuân", "xay-nha-phu-xuan"],
    ["Xây Nhà Nhơn Đức", "xây nhà Nhơn Đức", "xay-nha-nhon-duc"],
    ["Xây Nhà Phước Kiển", "xây nhà Phước Kiển", "xay-nha-phuoc-kien"],
    ["Xây Nhà Phước Lộc", "xây nhà Phước Lộc", "xay-nha-phuoc-loc"],
    ["Xây Nhà Long Thới", "xây nhà Long Thới", "xay-nha-long-thoi"],
    ["Xây Nhà Hiệp Phước", "xây nhà Hiệp Phước", "xay-nha-hiep-phuoc"],
    ["Xây Nhà Cần Thạnh", "xây nhà Cần Thạnh", "xay-nha-can-thanh"],
    ["Xây Nhà Long Hòa", "xây nhà Long Hòa", "xay-nha-long-hoa"],
    ["Xây Nhà Tam Thôn Hiệp", "xây nhà Tam Thôn Hiệp", "xay-nha-tam-thon-hiep"],
    ["Xây Nhà An Thới Đông", "xây nhà An Thới Đông", "xay-nha-an-thoi-dong"],
    ["Xây Nhà Lý Nhơn", "xây nhà Lý Nhơn", "xay-nha-ly-nhon"],
    ["Xây Nhà Thạnh An", "xây nhà Thạnh An", "xay-nha-thanh-an"],
    ["Thiết Kế Nhà Thảo Điền", "thiết kế nhà Thảo Điền", "thiet-ke-nha-thao-dien"],
    ["Thiết Kế Nhà An Phú", "thiết kế nhà An Phú", "thiet-ke-nha-an-phu"],
    ["Báo Giá Xây Nhà Thảo Điền", "báo giá xây nhà Thảo Điền", "bao-gia-xay-nha-thao-dien"],
    ["Báo Giá Xây Nhà An Phú", "báo giá xây nhà An Phú", "bao-gia-xay-nha-an-phu"],
    ["Nhà Thầu Thảo Điền", "nhà thầu Thảo Điền", "nha-thau-thao-dien"],
    ["Nhà Thầu An Phú", "nhà thầu An Phú", "nha-thau-an-phu"],
    ["Nhà Thầu Thủ Đức", "nhà thầu Thủ Đức", "nha-thau-thu-duc"],
    ["Nhà Thầu Bình Tân", "nhà thầu Bình Tân", "nha-thau-binh-tan"],
    ["Nhà Thầu Quận 12", "nhà thầu Quận 12", "nha-thau-quan-12"],
    ["Nhà Thầu Hóc Môn", "nhà thầu Hóc Môn", "nha-thau-hoc-mon"],
    ["Nhà Thầu Bình Chánh", "nhà thầu Bình Chánh", "nha-thau-binh-chanh"],
    ["Nhà Thầu Nhà Bè", "nhà thầu Nhà Bè", "nha-thau-nha-be"],
    ["Nhà Thầu Củ Chi", "nhà thầu Củ Chi", "nha-thau-cu-chi"],
    ["Nhà Thầu Cần Giờ", "nhà thầu Cần Giờ", "nha-thau-can-gio"],
  ]);

  // 29 — so sánh / quyết định mua / quy trình khách hàng
  const b29 = pairs([
    ["Nên Xây Nhà Hay Mua Sẵn", "nên xây nhà hay mua sẵn", "nen-xay-nha-hay-mua-san"],
    ["Nên Xây Hay Mua Chung Cư", "nên xây hay mua chung cư", "nen-xay-hay-mua-chung-cu"],
    ["Nên Cải Tạo Hay Bán Đất", "nên cải tạo hay bán đất", "nen-cai-tao-hay-ban-dat"],
    ["Nên Nâng Tầng Hay Xây Mới", "nên nâng tầng hay xây mới", "nen-nang-tang-hay-xay-moi"],
    ["Nên Thuê KTS Hay Gói Thầu", "nên thuê kts hay gói thầu", "nen-thue-kts-hay-goi-thau"],
    ["Nên Chọn Thầu Gần Hay Xa", "nên chọn thầu gần hay xa", "nen-chon-thau-gan-hay-xa"],
    ["Nên Chọn Gói Rẻ Hay Cao Cấp", "nên chọn gói rẻ hay cao cấp", "nen-chon-goi-re-hay-cao-cap"],
    ["Xây Nhà Bao Nhiêu Là Đủ", "xây nhà bao nhiêu là đủ", "xay-nha-bao-nhieu-la-du"],
    ["Cải Tạo Bao Nhiêu Là Đủ", "cải tạo bao nhiêu là đủ", "cai-tao-bao-nhieu-la-du"],
    ["Ngân Sách 1 Tỷ Xây Được Gì", "ngân sách 1 tỷ xây được gì", "ngan-sach-1-ty-xay-duoc-gi"],
    ["Ngân Sách 2 Tỷ Xây Được Gì", "ngân sách 2 tỷ xây được gì", "ngan-sach-2-ty-xay-duoc-gi"],
    ["Ngân Sách 3 Tỷ Xây Được Gì", "ngân sách 3 tỷ xây được gì", "ngan-sach-3-ty-xay-duoc-gi"],
    ["Ngân Sách 5 Tỷ Xây Được Gì", "ngân sách 5 tỷ xây được gì", "ngan-sach-5-ty-xay-duoc-gi"],
    ["Xây Nhà Cần Chuẩn Bị Gì", "xây nhà cần chuẩn bị gì", "xay-nha-can-chuan-bi-gi"],
    ["Cải Tạo Cần Chuẩn Bị Gì", "cải tạo cần chuẩn bị gì", "cai-tao-can-chuan-bi-gi"],
    ["Trước Khi Ký Hợp Đồng Xây", "trước khi ký hợp đồng xây", "truoc-khi-ky-hop-dong-xay"],
    ["Sau Khi Ký Hợp Đồng Xây", "sau khi ký hợp đồng xây", "sau-khi-ky-hop-dong-xay"],
    ["Trong Quá Trình Thi Công", "trong quá trình thi công", "trong-qua-trinh-thi-cong"],
    ["Khi Nghiệm Thu Nhà", "khi nghiệm thu nhà", "khi-nghiem-thu-nha"],
    ["Sau Khi Bàn Giao Nhà", "sau khi bàn giao nhà", "sau-khi-ban-giao-nha"],
    ["Quyền Lợi Chủ Nhà Khi Xây", "quyền lợi chủ nhà khi xây", "quyen-loi-chu-nha-khi-xay"],
    ["Nghĩa Vụ Chủ Nhà Khi Xây", "nghĩa vụ chủ nhà khi xây", "nghia-vu-chu-nha-khi-xay"],
    ["Quyền Lợi Nhà Thầu", "quyền lợi nhà thầu", "quyen-loi-nha-thau"],
    ["Nghĩa Vụ Nhà Thầu", "nghĩa vụ nhà thầu", "nghia-vu-nha-thau"],
    ["Tranh Chấp Hợp Đồng Xây", "tranh chấp hợp đồng xây", "tranh-chap-hop-dong-xay"],
    ["Hòa Giải Tranh Chấp Xây", "hòa giải tranh chấp xây", "hoa-giai-tranh-chap-xay"],
    ["Đơn Phương Chấm Dứt HĐ", "đơn phương chấm dứt hợp đồng xây", "don-phuong-cham-dut-hd-xay"],
    ["Đòi Bảo Hành Xây Nhà", "đòi bảo hành xây nhà", "doi-bao-hanh-xay-nha"],
    ["Khiếu Nại Chất Lượng Xây", "khiếu nại chất lượng xây", "khieu-nai-chat-luong-xay"],
    ["Biên Bản Nghiệm Thu Mẫu", "biên bản nghiệm thu mẫu", "bien-ban-nghiem-thu-mau"],
    ["Biên Bản Bàn Giao Mẫu", "biên bản bàn giao mẫu", "bien-ban-ban-giao-mau"],
    ["Hợp Đồng Xây Mẫu", "hợp đồng xây mẫu", "hop-dong-xay-mau"],
    ["Phụ Lục Phát Sinh Mẫu", "phụ lục phát sinh mẫu", "phu-luc-phat-sinh-mau"],
    ["Checklist Nghiệm Thu Thô", "checklist nghiệm thu thô", "checklist-nghiem-thu-tho"],
    ["Checklist Nghiệm Thu Hoàn Thiện", "checklist nghiệm thu hoàn thiện", "checklist-nghiem-thu-hoan-thien"],
    ["Checklist Bàn Giao Chìa Khóa", "checklist bàn giao chìa khóa", "checklist-ban-giao-chia-khoa"],
    ["Câu Hỏi Thường Gặp Xây Nhà", "câu hỏi thường gặp xây nhà", "cau-hoi-thuong-gap-xay-nha"],
    ["Câu Hỏi Thường Gặp Cải Tạo", "câu hỏi thường gặp cải tạo", "cau-hoi-thuong-gap-cai-tao"],
    ["Myth Xây Nhà Sai", "myth xây nhà sai", "myth-xay-nha-sai"],
    ["Hiểu Lầm Khi Xây Nhà", "hiểu lầm khi xây nhà", "hieu-lam-khi-xay-nha"],
    ["Hiểu Lầm Khi Cải Tạo", "hiểu lầm khi cải tạo", "hieu-lam-khi-cai-tao"],
    ["Hiểu Lầm Về Trọn Gói", "hiểu lầm về trọn gói", "hieu-lam-ve-tron-goi"],
    ["Hiểu Lầm Về Phần Thô", "hiểu lầm về phần thô", "hieu-lam-ve-phan-tho"],
    ["Hiểu Lầm Về Đơn Giá m2", "hiểu lầm về đơn giá m2", "hieu-lam-ve-don-gia-m2"],
    ["Vì Sao Báo Giá Chênh Lệch", "vì sao báo giá chênh lệch", "vi-sao-bao-gia-chenh-lech"],
    ["Vì Sao Phát Sinh Xây Nhà", "vì sao phát sinh xây nhà", "vi-sao-phat-sinh-xay-nha"],
    ["Vì Sao Trễ Tiến Độ Xây", "vì sao trễ tiến độ xây", "vi-sao-tre-tien-do-xay"],
    ["Vì Sao Nhà Thấm Sau Xây", "vì sao nhà thấm sau xây", "vi-sao-nha-tham-sau-xay"],
    ["Vì Sao Nên Khảo Sát Trước", "vì sao nên khảo sát trước", "vi-sao-nen-khao-sat-truoc"],
    ["Vì Sao Nên Có Giám Sát", "vì sao nên có giám sát", "vi-sao-nen-co-giam-sat"],
    ["Vì Sao Không Nên Bán Thầu", "vì sao không nên bán thầu", "vi-sao-khong-nen-ban-thau"],
    ["Lợi Ích Xây Trọn Gói", "lợi ích xây trọn gói", "loi-ich-xay-tron-goi"],
    ["Lợi Ích Xây Phần Thô", "lợi ích xây phần thô", "loi-ich-xay-phan-tho"],
    ["Lợi Ích Thiết Kế Trước", "lợi ích thiết kế trước", "loi-ich-thiet-ke-truoc"],
    ["Lợi Ích Cải Tạo Thay Xây Mới", "lợi ích cải tạo thay xây mới", "loi-ich-cai-tao-thay-xay-moi"],
    ["Rủi Ro Tự Xây Nhà", "rủi ro tự xây nhà", "rui-ro-tu-xay-nha"],
    ["Rủi Ro Thuê Thầu Rẻ", "rủi ro thuê thầu rẻ", "rui-ro-thue-thau-re"],
    ["Rủi Ro Không Xin Phép", "rủi ro không xin phép", "rui-ro-khong-xin-phep"],
    ["Rủi Ro Không Hợp Đồng", "rủi ro không hợp đồng", "rui-ro-khong-hop-dong"],
    ["Rủi Ro Không Bảo Hành", "rủi ro không bảo hành", "rui-ro-khong-bao-hanh"],
    ["Top Tiêu Chí Chọn Thầu", "top tiêu chí chọn thầu", "top-tieu-chi-chon-thau"],
    ["Top Câu Hỏi Cho Thầu", "top câu hỏi cho thầu", "top-cau-hoi-cho-thau"],
    ["Top Sai Lầm Chủ Nhà", "top sai lầm chủ nhà", "top-sai-lam-chu-nha"],
    ["Top Việc Nên Làm Trước Xây", "top việc nên làm trước xây", "top-viec-nen-lam-truoc-xay"],
    ["Top Việc Nên Tránh Khi Xây", "top việc nên tránh khi xây", "top-viec-nen-tranh-khi-xay"],
    ["Roadmap Xây Nhà 2026", "roadmap xây nhà 2026", "roadmap-xay-nha-2026"],
    ["Timeline Xây Nhà Phố", "timeline xây nhà phố", "timeline-xay-nha-pho"],
    ["Timeline Cải Tạo Nhà", "timeline cải tạo nhà", "timeline-cai-tao-nha"],
    ["Milestone Thanh Toán Xây", "milestone thanh toán xây", "milestone-thanh-toan-xay"],
    ["KPI Giám Sát Công Trình", "kpi giám sát công trình", "kpi-giam-sat-cong-trinh"],
    ["QC Checklist Xây Nhà", "qc checklist xây nhà", "qc-checklist-xay-nha"],
    ["Snag List Bàn Giao", "snag list bàn giao", "snag-list-ban-giao"],
    ["Punch List Sửa Chữa", "punch list sửa chữa", "punch-list-sua-chua"],
    ["As-Built Drawing Nhà", "as-built drawing nhà", "as-built-drawing-nha"],
    ["O&M Manual Nhà", "o&m manual nhà", "om-manual-nha"],
    ["Warranty Claim Xây Nhà", "warranty claim xây nhà", "warranty-claim-xay-nha"],
    ["After Sales Xây Nhà", "after sales xây nhà", "after-sales-xay-nha"],
    ["Loyalty Khách Hàng Xây", "loyalty khách hàng xây", "loyalty-khach-hang-xay"],
    ["Referral Program Xây", "referral program xây", "referral-program-xay"],
    ["Testimonial Xây Nhà", "testimonial xây nhà", "testimonial-xay-nha"],
    ["Case Study Cải Tạo", "case study cải tạo", "case-study-cai-tao"],
    ["Portfolio Công Trình", "portfolio công trình", "portfolio-cong-trinh"],
    ["Showroom Vật Tư Xây", "showroom vật tư xây", "showroom-vat-tu-xay"],
    ["Tour Công Trình Mở", "tour công trình mở", "tour-cong-trinh-mo"],
    ["Open House Xây Nhà", "open house xây nhà", "open-house-xay-nha"],
    ["Workshop Xây Nhà", "workshop xây nhà", "workshop-xay-nha"],
    ["Webinar Tư Vấn Xây", "webinar tư vấn xây", "webinar-tu-van-xay"],
    ["Ebook Kinh Nghiệm Xây", "ebook kinh nghiệm xây", "ebook-kinh-nghiem-xay"],
    ["Checklist PDF Xây Nhà", "checklist pdf xây nhà", "checklist-pdf-xay-nha"],
  ]);

  return [b25, b26, b27, b28, b29].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 1947 + (batch - 25) * 100;
  const end = start + 99;
  c = c.replace(/batch \d+ từ khóa ngắn \(#[\d–-]+\)/, `batch ${batch} từ khóa ngắn (#${start}–#${end})`);
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: bệnh công trình / xử lý sự cố nhà.",
  "Cluster: diện tích, kích thước, số tầng, mẫu nhà.",
  "Cluster: thi công hạng mục & dịch vụ chuyên biệt.",
  "Cluster: geo phường/KĐT TP.HCM.",
  "Cluster: quyết định mua, FAQ, quy trình khách hàng.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 25 + i;
  const startNo = 1947 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 25 ? 24 : batch - 1);
  console.log(`wrote batch ${batch}`);
}
console.log("done");
