/**
 * Generator: short-keyword batches 45–49 (500 articles, #3947–#4446).
 * Run: npx tsx scripts/gen-short-keyword-batches-45-49.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${45 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${45 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${45 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 45 — phong cách kiến trúc / mặt bằng / mẫu nhà
  const b45 = pairs([
    ["Nhà Phong Cách Hiện Đại", "nhà phong cách hiện đại", "nha-phong-cach-hien-dai-st"],
    ["Nhà Phong Cách Tối Giản", "nhà phong cách tối giản", "nha-phong-cach-toi-gian-st"],
    ["Nhà Phong Cách Scandinavian", "nhà phong cách scandinavian", "nha-phong-cach-scandinavian-st"],
    ["Nhà Phong Cách Industrial", "nhà phong cách industrial", "nha-phong-cach-industrial-st"],
    ["Nhà Phong Cách Japandi", "nhà phong cách japandi", "nha-phong-cach-japandi-st"],
    ["Nhà Phong Cách Đông Dương", "nhà phong cách đông dương", "nha-phong-cach-dong-duong-st"],
    ["Nhà Phong Cách Cổ Điển", "nhà phong cách cổ điển", "nha-phong-cach-co-dien-st"],
    ["Nhà Phong Cách Tân Cổ Điển", "nhà phong cách tân cổ điển", "nha-phong-cach-tan-co-dien-st"],
    ["Nhà Phong Cách Địa Trung Hải", "nhà phong cách địa trung hải", "nha-phong-cach-dia-trung-hai-st"],
    ["Nhà Phong Cách Tropical", "nhà phong cách tropical", "nha-phong-cach-tropical-st"],
    ["Nhà Phong Cách Farmhouse", "nhà phong cách farmhouse", "nha-phong-cach-farmhouse-st"],
    ["Nhà Phong Cách Luxury Modern", "nhà phong cách luxury modern", "nha-phong-cach-luxury-modern-st"],
    ["Mẫu Nhà Ống 3x10", "mẫu nhà ống 3x10", "mau-nha-ong-3x10-st"],
    ["Mẫu Nhà Ống 3x12", "mẫu nhà ống 3x12", "mau-nha-ong-3x12-st"],
    ["Mẫu Nhà Ống 4x12", "mẫu nhà ống 4x12", "mau-nha-ong-4x12-st"],
    ["Mẫu Nhà Ống 4x15", "mẫu nhà ống 4x15", "mau-nha-ong-4x15-st"],
    ["Mẫu Nhà Ống 4x16", "mẫu nhà ống 4x16", "mau-nha-ong-4x16-st"],
    ["Mẫu Nhà Ống 5x15", "mẫu nhà ống 5x15", "mau-nha-ong-5x15-st"],
    ["Mẫu Nhà Ống 5x18", "mẫu nhà ống 5x18", "mau-nha-ong-5x18-st"],
    ["Mẫu Nhà Ống 5x20", "mẫu nhà ống 5x20", "mau-nha-ong-5x20-st"],
    ["Mẫu Nhà Ống 6x15", "mẫu nhà ống 6x15", "mau-nha-ong-6x15-st"],
    ["Mẫu Nhà Ống 6x18", "mẫu nhà ống 6x18", "mau-nha-ong-6x18-st"],
    ["Mẫu Nhà Ống 6x20", "mẫu nhà ống 6x20", "mau-nha-ong-6x20-st"],
    ["Mẫu Nhà Lệch Tầng 4x12", "mẫu nhà lệch tầng 4x12", "mau-nha-lech-tang-4x12-st"],
    ["Mẫu Nhà Lệch Tầng 5x15", "mẫu nhà lệch tầng 5x15", "mau-nha-lech-tang-5x15-st"],
    ["Mẫu Nhà Có Giếng Trời", "mẫu nhà có giếng trời", "mau-nha-co-gieng-troi-st"],
    ["Mẫu Nhà Có Sân Vườn", "mẫu nhà có sân vườn", "mau-nha-co-san-vuon-st"],
    ["Mẫu Nhà Có Hồ Cá", "mẫu nhà có hồ cá", "mau-nha-co-ho-ca-st"],
    ["Mẫu Nhà Có Gác Lửng", "mẫu nhà có gác lửng", "mau-nha-co-gac-lung-st"],
    ["Mẫu Nhà Có Hầm Xe", "mẫu nhà có hầm xe", "mau-nha-co-ham-xe-st"],
    ["Mẫu Nhà 1 Trệt 1 Lầu", "mẫu nhà 1 trệt 1 lầu", "mau-nha-1-tret-1-lau-st"],
    ["Mẫu Nhà 1 Trệt 2 Lầu", "mẫu nhà 1 trệt 2 lầu", "mau-nha-1-tret-2-lau-st"],
    ["Mẫu Nhà 1 Trệt 3 Lầu", "mẫu nhà 1 trệt 3 lầu", "mau-nha-1-tret-3-lau-st"],
    ["Mẫu Nhà 1 Trệt 4 Lầu", "mẫu nhà 1 trệt 4 lầu", "mau-nha-1-tret-4-lau-st"],
    ["Mẫu Nhà Cấp 4 Mái Thái", "mẫu nhà cấp 4 mái thái", "mau-nha-cap-4-mai-thai-st"],
    ["Mẫu Nhà Cấp 4 Mái Nhật", "mẫu nhà cấp 4 mái nhật", "mau-nha-cap-4-mai-nhat-st"],
    ["Mẫu Nhà Cấp 4 Mái Bằng", "mẫu nhà cấp 4 mái bằng", "mau-nha-cap-4-mai-bang-st"],
    ["Mẫu Biệt Thự 1 Tầng", "mẫu biệt thự 1 tầng", "mau-biet-thu-1-tang-st"],
    ["Mẫu Biệt Thự 2 Tầng", "mẫu biệt thự 2 tầng", "mau-biet-thu-2-tang-st"],
    ["Mẫu Biệt Thự 3 Tầng", "mẫu biệt thự 3 tầng", "mau-biet-thu-3-tang-st"],
    ["Mặt Bằng Nhà Ống 3 Phòng Ngủ", "mặt bằng nhà ống 3 phòng ngủ", "mat-bang-nha-ong-3-phong-ngu-st"],
    ["Mặt Bằng Nhà Ống 4 Phòng Ngủ", "mặt bằng nhà ống 4 phòng ngủ", "mat-bang-nha-ong-4-phong-ngu-st"],
    ["Mặt Bằng Nhà Có Phòng Thờ", "mặt bằng nhà có phòng thờ", "mat-bang-nha-co-phong-tho-st"],
    ["Mặt Bằng Nhà Có Phòng Làm Việc", "mặt bằng nhà có phòng làm việc", "mat-bang-nha-co-phong-lam-viec-st"],
    ["Mặt Bằng Nhà Shop House", "mặt bằng nhà shop house", "mat-bang-nha-shop-house-st"],
    ["Bản Vẽ Nhà Phố Miễn Phí", "bản vẽ nhà phố miễn phí", "ban-ve-nha-pho-mien-phi-st"],
    ["Bản Vẽ Nhà Cấp 4 Miễn Phí", "bản vẽ nhà cấp 4 miễn phí", "ban-ve-nha-cap-4-mien-phi-st"],
    ["File CAD Nhà Phố", "file cad nhà phố", "file-cad-nha-pho-st"],
    ["File Sketchup Nhà Phố", "file sketchup nhà phố", "file-sketchup-nha-pho-st"],
    ["Phối Cảnh 3D Nhà Phố", "phối cảnh 3d nhà phố", "phoi-canh-3d-nha-pho-st"],
    ["Phối Cảnh Nội Thất 3D", "phối cảnh nội thất 3d", "phoi-canh-noi-that-3d-st"],
    ["Tour Ảo Nhà Mẫu", "tour ảo nhà mẫu", "tour-ao-nha-mau-st"],
    ["Nhà Mẫu Thực Tế", "nhà mẫu thực tế", "nha-mau-thuc-te-st"],
    ["Ý Tưởng Thiết Kế Nhà Hẹp", "ý tưởng thiết kế nhà hẹp", "y-tuong-thiet-ke-nha-hep-st"],
    ["Ý Tưởng Thiết Kế Nhà Nhỏ", "ý tưởng thiết kế nhà nhỏ", "y-tuong-thiet-ke-nha-nho-st"],
    ["Ý Tưởng Tối Ưu Ánh Sáng", "ý tưởng tối ưu ánh sáng", "y-tuong-toi-uu-anh-sang-st"],
    ["Ý Tưởng Tối Ưu Thông Gió", "ý tưởng tối ưu thông gió", "y-tuong-toi-uu-thong-gio-st"],
    ["Ý Tưởng Tối Ưu Công Năng", "ý tưởng tối ưu công năng", "y-tuong-toi-uu-cong-nang-st"],
    ["Thiết Kế Nhà Theo Tuổi", "thiết kế nhà theo tuổi", "thiet-ke-nha-theo-tuoi-st"],
    ["Thiết Kế Nhà Theo Mệnh", "thiết kế nhà theo mệnh", "thiet-ke-nha-theo-menh-st"],
    ["Thiết Kế Nhà Mệnh Kim", "thiết kế nhà mệnh kim", "thiet-ke-nha-menh-kim-st"],
    ["Thiết Kế Nhà Mệnh Mộc", "thiết kế nhà mệnh mộc", "thiet-ke-nha-menh-moc-st"],
    ["Thiết Kế Nhà Mệnh Thủy", "thiết kế nhà mệnh thủy", "thiet-ke-nha-menh-thuy-st"],
    ["Thiết Kế Nhà Mệnh Hỏa", "thiết kế nhà mệnh hỏa", "thiet-ke-nha-menh-hoa-st"],
    ["Thiết Kế Nhà Mệnh Thổ", "thiết kế nhà mệnh thổ", "thiet-ke-nha-menh-tho-st"],
    ["Tỷ Lệ Vàng Trong Kiến Trúc", "tỷ lệ vàng trong kiến trúc", "ty-le-vang-trong-kien-truc-st"],
    ["Module Không Gian Nhà Phố", "module không gian nhà phố", "module-khong-gian-nha-pho-st"],
    ["Zoning Công Năng Nhà Ở", "zoning công năng nhà ở", "zoning-cong-nang-nha-o-st"],
    ["Circulation Trong Nhà Phố", "circulation trong nhà phố", "circulation-trong-nha-pho-st"],
    ["Privacy Trong Nhà Ống", "privacy trong nhà ống", "privacy-trong-nha-ong-st"],
    ["Open Plan Nhà Phố", "open plan nhà phố", "open-plan-nha-pho-st"],
    ["Semi Open Plan Nhà", "semi open plan nhà", "semi-open-plan-nha-st"],
    ["Double Height Phòng Khách", "double height phòng khách", "double-height-phong-khach-st"],
    ["Void Giếng Trời Nhà Phố", "void giếng trời nhà phố", "void-gieng-troi-nha-pho-st"],
    ["Split Level Nhà Phố", "split level nhà phố", "split-level-nha-pho-st"],
    ["Courtyard House Hiện Đại", "courtyard house hiện đại", "courtyard-house-hien-dai-st"],
    ["Narrow House Design", "narrow house design", "narrow-house-design-st"],
    ["Tiny House Việt Nam", "tiny house việt nam", "tiny-house-viet-nam-st"],
    ["Container House Việt Nam", "container house việt nam", "container-house-viet-nam-st"],
    ["Prefab House Việt Nam", "prefab house việt nam", "prefab-house-viet-nam-st"],
    ["Báo Giá Thiết Kế Kiến Trúc", "báo giá thiết kế kiến trúc", "bao-gia-thiet-ke-kien-truc-st"],
    ["Báo Giá Thiết Kế Nội Thất", "báo giá thiết kế nội thất", "bao-gia-thiet-ke-noi-that-st"],
    ["Gói Thiết Kế Cơ Bản", "gói thiết kế cơ bản", "goi-thiet-ke-co-ban-st"],
    ["Gói Thiết Kế Chi Tiết", "gói thiết kế chi tiết", "goi-thiet-ke-chi-tiet-st"],
    ["Gói Thiết Kế Trọn Bộ", "gói thiết kế trọn bộ", "goi-thiet-ke-tron-bo-st"],
    ["Hồ Sơ Thiết Kế Xây Dựng", "hồ sơ thiết kế xây dựng", "ho-so-thiet-ke-xay-dung-st"],
    ["Bản Vẽ Kết Cấu Nhà Phố", "bản vẽ kết cấu nhà phố", "ban-ve-ket-cau-nha-pho-st"],
    ["Bản Vẽ Kiến Trúc Nhà Phố", "bản vẽ kiến trúc nhà phố", "ban-ve-kien-truc-nha-pho-st"],
    ["Bản Vẽ Điện Nước Nhà", "bản vẽ điện nước nhà", "ban-ve-dien-nuoc-nha-st"],
    ["Triển Khai Bản Vẽ Thi Công", "triển khai bản vẽ thi công", "trien-khai-ban-ve-thi-cong-st"],
    ["Chỉnh Sửa Bản Vẽ Thiết Kế", "chỉnh sửa bản vẽ thiết kế", "chinh-sua-ban-ve-thiet-ke-st"],
    ["Xu Hướng Kiến Trúc 2026", "xu hướng kiến trúc 2026", "xu-huong-kien-truc-2026-st"],
    ["Xu Hướng Mặt Bằng 2026", "xu hướng mặt bằng 2026", "xu-huong-mat-bang-2026-st"],
    ["Xu Hướng Mẫu Nhà 2026", "xu hướng mẫu nhà 2026", "xu-huong-mau-nha-2026-st"],
    ["Inspiration Nhà Phố Đẹp", "inspiration nhà phố đẹp", "inspiration-nha-pho-dep-st"],
    ["Moodboard Thiết Kế Nhà", "moodboard thiết kế nhà", "moodboard-thiet-ke-nha-st"],
    ["Concept Design Nhà Phố", "concept design nhà phố", "concept-design-nha-pho-st"],
    ["Schematic Design Nhà", "schematic design nhà", "schematic-design-nha-st"],
    ["Design Development Nhà", "design development nhà", "design-development-nha-st"],
  ]);

  // 46 — vật liệu chi tiết / so sánh vật liệu
  const b46 = pairs([
    ["Gạch Block Xây Nhà", "gạch block xây nhà", "gach-block-xay-nha-vl"],
    ["Gạch Ống Xây Nhà", "gạch ống xây nhà", "gach-ong-xay-nha-vl"],
    ["Gạch Đặc Xây Nhà", "gạch đặc xây nhà", "gach-dac-xay-nha-vl"],
    ["Gạch Không Nung AAC", "gạch không nung aac", "gach-khong-nung-aac-vl"],
    ["Gạch Bê Tông Nhẹ", "gạch bê tông nhẹ", "gach-be-tong-nhe-vl"],
    ["Gạch Clinker Mặt Tiền", "gạch clinker mặt tiền", "gach-clinker-mat-tien-vl"],
    ["Gạch Thẻ Ốp Tường", "gạch thẻ ốp tường", "gach-the-op-tuong-vl"],
    ["Gạch Mosaic Trang Trí", "gạch mosaic trang trí", "gach-mosaic-trang-tri-vl"],
    ["Gạch Thông Minh Ốp Lát", "gạch thông minh ốp lát", "gach-thong-minh-op-lat-vl"],
    ["Đá Granite Đen Ấn Độ", "đá granite đen ấn độ", "da-granite-den-an-do-vl"],
    ["Đá Granite Trắng Suối La", "đá granite trắng suối la", "da-granite-trang-suoi-la-vl"],
    ["Đá Marble Olivia", "đá marble olivia", "da-marble-olivia-vl"],
    ["Đá Marble Carrara", "đá marble carrara", "da-marble-carrara-vl"],
    ["Đá Nhân Tạo Bếp", "đá nhân tạo bếp", "da-nhan-tao-bep-vl"],
    ["Đá Quartz Bếp", "đá quartz bếp", "da-quartz-bep-vl"],
    ["Đá Compact Bếp", "đá compact bếp", "da-compact-bep-vl"],
    ["Gỗ Óc Chó Nội Thất", "gỗ óc chó nội thất", "go-oc-cho-noi-that-vl"],
    ["Gỗ Sồi Nội Thất", "gỗ sồi nội thất", "go-soi-noi-that-vl"],
    ["Gỗ Teak Nội Thất", "gỗ teak nội thất", "go-teak-noi-that-vl"],
    ["Gỗ Xoan Đào Nội Thất", "gỗ xoan đào nội thất", "go-xoan-dao-noi-that-vl"],
    ["Gỗ MDF Chống Ẩm", "gỗ mdf chống ẩm", "go-mdf-chong-am-vl"],
    ["Gỗ HDF Sàn", "gỗ hdf sàn", "go-hdf-san-vl"],
    ["Gỗ Plywood Nội Thất", "gỗ plywood nội thất", "go-plywood-noi-that-vl"],
    ["Nhựa PVC Cửa", "nhựa pvc cửa", "nhua-pvc-cua-vl"],
    ["Nhựa UPVC Cửa Sổ", "nhựa upvc cửa sổ", "nhua-upvc-cua-so-vl"],
    ["Nhôm Hệ 55", "nhôm hệ 55", "nhom-he-55-vl"],
    ["Nhôm Hệ 65", "nhôm hệ 65", "nhom-he-65-vl"],
    ["Nhôm Hệ 93", "nhôm hệ 93", "nhom-he-93-vl"],
    ["Kính Tempered 8mm", "kính tempered 8mm", "kinh-tempered-8mm-vl"],
    ["Kính Tempered 10mm", "kính tempered 10mm", "kinh-tempered-10mm-vl"],
    ["Kính Laminated An Toàn", "kính laminated an toàn", "kinh-laminated-an-toan-vl"],
    ["Kính Low-E Cách Nhiệt", "kính low-e cách nhiệt", "kinh-low-e-cach-nhiet-vl"],
    ["Kính Reflective Mặt Tiền", "kính reflective mặt tiền", "kinh-reflective-mat-tien-vl"],
    ["Tôn Lạnh Cách Nhiệt", "tôn lạnh cách nhiệt", "ton-lanh-cach-nhiet-vl"],
    ["Tôn Cách Nhiệt 3 Lớp", "tôn cách nhiệt 3 lớp", "ton-cach-nhiet-3-lop-vl"],
    ["Ngói Bitum Phủ Đá", "ngói bitum phủ đá", "ngoi-bitum-phu-da-vl"],
    ["Ngói Nhựa ASA", "ngói nhựa asa", "ngoi-nhua-asa-vl"],
    ["Ngói Xi Măng Màu", "ngói xi măng màu", "ngoi-xi-mang-mau-vl"],
    ["Sơn Epoxy Sàn", "sơn epoxy sàn", "son-epoxy-san-vl"],
    ["Sơn Polyurethane", "sơn polyurethane", "son-polyurethane-vl"],
    ["Sơn Chống Thấm Gốc Xi", "sơn chống thấm gốc xi", "son-chong-tham-goc-xi-vl"],
    ["Sơn Chống Thấm Gốc Nhựa", "sơn chống thấm gốc nhựa", "son-chong-tham-goc-nhua-vl"],
    ["Màng Chống Thấm Khò Nóng", "màng chống thấm khò nóng", "mang-chong-tham-kho-nong-vl"],
    ["Màng Chống Thấm Tự Dính", "màng chống thấm tự dính", "mang-chong-tham-tu-dinh-vl"],
    ["Keo Chống Thấm Polyurea", "keo chống thấm polyurea", "keo-chong-tham-polyurea-vl"],
    ["Foam Cách Nhiệt Phun", "foam cách nhiệt phun", "foam-cach-nhiet-phun-vl"],
    ["Xốp XPS Cách Nhiệt", "xốp xps cách nhiệt", "xop-xps-cach-nhiet-vl"],
    ["Xốp EPS Cách Nhiệt", "xốp eps cách nhiệt", "xop-eps-cach-nhiet-vl"],
    ["Bông Thủy Tinh Cách Âm", "bông thủy tinh cách âm", "bong-thuy-tinh-cach-am-vl"],
    ["Bông Khoáng Cách Âm", "bông khoáng cách âm", "bong-khoang-cach-am-vl"],
    ["Tấm Cemboard", "tấm cemboard", "tam-cemboard-vl"],
    ["Tấm Smartboard", "tấm smartboard", "tam-smartboard-vl"],
    ["Tấm Duraflex", "tấm duraflex", "tam-duraflex-vl"],
    ["Tấm Thạch Cao Chịu Ẩm", "tấm thạch cao chịu ẩm", "tam-thach-cao-chiu-am-vl"],
    ["Tấm Thạch Cao Chịu Lửa", "tấm thạch cao chịu lửa", "tam-thach-cao-chiu-lua-vl"],
    ["Inox 304 Lan Can", "inox 304 lan can", "inox-304-lan-can-vl"],
    ["Inox 201 Lan Can", "inox 201 lan can", "inox-201-lan-can-vl"],
    ["Sắt Hộp 40x40", "sắt hộp 40x40", "sat-hop-40x40-vl"],
    ["Sắt Hộp 50x50", "sắt hộp 50x50", "sat-hop-50x50-vl"],
    ["Thép Hình I Xây Nhà", "thép hình i xây nhà", "thep-hinh-i-xay-nha-vl"],
    ["Thép Hình H Xây Nhà", "thép hình h xây nhà", "thep-hinh-h-xay-nha-vl"],
    ["So Sánh Gạch Block Và Ống", "so sánh gạch block và ống", "so-sanh-gach-block-va-ong-vl"],
    ["So Sánh AAC Và Gạch Nung", "so sánh aac và gạch nung", "so-sanh-aac-va-gach-nung-vl"],
    ["So Sánh Granite Và Marble", "so sánh granite và marble", "so-sanh-granite-va-marble-vl"],
    ["So Sánh Quartz Và Granite", "so sánh quartz và granite", "so-sanh-quartz-va-granite-vl"],
    ["So Sánh MDF Và Plywood", "so sánh mdf và plywood", "so-sanh-mdf-va-plywood-vl"],
    ["So Sánh Nhôm Và UPVC", "so sánh nhôm và upvc", "so-sanh-nhom-va-upvc-vl"],
    ["So Sánh Tôn Và Ngói", "so sánh tôn và ngói", "so-sanh-ton-va-ngoi-vl"],
    ["So Sánh XPS Và EPS", "so sánh xps và eps", "so-sanh-xps-va-eps-vl"],
    ["So Sánh Inox 304 Và 201", "so sánh inox 304 và 201", "so-sanh-inox-304-va-201-vl"],
    ["Cách Chọn Gạch Ốp Lát", "cách chọn gạch ốp lát", "cach-chon-gach-op-lat-vl"],
    ["Cách Chọn Đá Bếp", "cách chọn đá bếp", "cach-chon-da-bep-vl"],
    ["Cách Chọn Gỗ Nội Thất", "cách chọn gỗ nội thất", "cach-chon-go-noi-that-vl"],
    ["Cách Chọn Nhôm Kính", "cách chọn nhôm kính", "cach-chon-nhom-kinh-vl"],
    ["Cách Chọn Tôn Lợp", "cách chọn tôn lợp", "cach-chon-ton-lop-vl"],
    ["Cách Chọn Sơn Ngoại Thất", "cách chọn sơn ngoại thất", "cach-chon-son-ngoai-that-vl"],
    ["Cách Chọn Sơn Nội Thất", "cách chọn sơn nội thất", "cach-chon-son-noi-that-vl"],
    ["Cách Chọn Vật Liệu Chống Thấm", "cách chọn vật liệu chống thấm", "cach-chon-vat-lieu-chong-tham-vl"],
    ["Bảng Giá Gạch Ốp Lát 2026", "bảng giá gạch ốp lát 2026", "bang-gia-gach-op-lat-2026-vl"],
    ["Bảng Giá Đá Granite 2026", "bảng giá đá granite 2026", "bang-gia-da-granite-2026-vl"],
    ["Bảng Giá Nhôm Kính 2026", "bảng giá nhôm kính 2026", "bang-gia-nhom-kinh-2026-vl"],
    ["Bảng Giá Tôn Lợp 2026", "bảng giá tôn lợp 2026", "bang-gia-ton-lop-2026-vl"],
    ["Bảng Giá Sơn Dulux 2026", "bảng giá sơn dulux 2026", "bang-gia-son-dulux-2026-vl"],
    ["Vật Liệu Xanh Tiết Kiệm", "vật liệu xanh tiết kiệm", "vat-lieu-xanh-tiet-kiem-vl"],
    ["Vật Liệu Tái Chế Xây Nhà", "vật liệu tái chế xây nhà", "vat-lieu-tai-che-xay-nha-vl"],
    ["Vật Liệu Local Source", "vật liệu local source", "vat-lieu-local-source-vl"],
    ["Kiểm Tra Chất Lượng Vật Tư", "kiểm tra chất lượng vật tư", "kiem-tra-chat-luong-vat-tu-vl"],
    ["Nhận Biết Vật Tư Fake", "nhận biết vật tư fake", "nhan-biet-vat-tu-fake-vl"],
    ["Bảo Quản Vật Tư Công Trình", "bảo quản vật tư công trình", "bao-quan-vat-tu-cong-trinh-vl"],
    ["Định Mức Vật Tư Xây Nhà", "định mức vật tư xây nhà", "dinh-muc-vat-tu-xay-nha-vl"],
    ["Định Mức Xi Măng m2", "định mức xi măng m2", "dinh-muc-xi-mang-m2-vl"],
    ["Định Mức Thép m2", "định mức thép m2", "dinh-muc-thep-m2-vl"],
    ["Định Mức Gạch m2", "định mức gạch m2", "dinh-muc-gach-m2-vl"],
    ["Định Mức Cát Đá m2", "định mức cát đá m2", "dinh-muc-cat-da-m2-vl"],
  ]);

  // 47 — geo Đông Nam Bộ sâu / KĐT / trục đường
  const b47 = pairs([
    ["Xây Nhà An Phú Thuận An", "xây nhà An Phú Thuận An", "xay-nha-an-phu-thuan-an-geo2"],
    ["Xây Nhà Bình Chuẩn", "xây nhà Bình Chuẩn", "xay-nha-binh-chuan-geo2"],
    ["Xây Nhà Bình Hòa BD", "xây nhà Bình Hòa Bình Dương", "xay-nha-binh-hoa-bd-geo2"],
    ["Xây Nhà Vĩnh Phú BD", "xây nhà Vĩnh Phú Bình Dương", "xay-nha-vinh-phu-bd-geo2"],
    ["Xây Nhà Lái Thiêu", "xây nhà Lái Thiêu", "xay-nha-lai-thieu-geo2"],
    ["Xây Nhà Bình Nhâm", "xây nhà Bình Nhâm", "xay-nha-binh-nham-geo2"],
    ["Xây Nhà Hưng Định", "xây nhà Hưng Định", "xay-nha-hung-dinh-geo2"],
    ["Xây Nhà An Thạnh BD", "xây nhà An Thạnh Bình Dương", "xay-nha-an-thanh-bd-geo2"],
    ["Xây Nhà Thuận Giao", "xây nhà Thuận Giao", "xay-nha-thuan-giao-geo2"],
    ["Xây Nhà Đông Hòa BD", "xây nhà Đông Hòa Bình Dương", "xay-nha-dong-hoa-bd-geo2"],
    ["Xây Nhà Tân Đông Hiệp", "xây nhà Tân Đông Hiệp", "xay-nha-tan-dong-hiep-geo2"],
    ["Xây Nhà Tân Bình Dĩ An", "xây nhà Tân Bình Dĩ An", "xay-nha-tan-binh-di-an-geo2"],
    ["Xây Nhà Dĩ An Phường", "xây nhà phường Dĩ An", "xay-nha-phuong-di-an-geo2"],
    ["Xây Nhà An Bình Dĩ An", "xây nhà An Bình Dĩ An", "xay-nha-an-binh-di-an-geo2"],
    ["Xây Nhà Đông Hòa Dĩ An", "xây nhà Đông Hòa Dĩ An", "xay-nha-dong-hoa-di-an-geo2"],
    ["Xây Nhà Bình An Dĩ An", "xây nhà Bình An Dĩ An", "xay-nha-binh-an-di-an-geo2"],
    ["Xây Nhà Phú Hòa TDM", "xây nhà Phú Hòa Thủ Dầu Một", "xay-nha-phu-hoa-tdm-geo2"],
    ["Xây Nhà Hiệp Thành TDM", "xây nhà Hiệp Thành Thủ Dầu Một", "xay-nha-hiep-thanh-tdm-geo2"],
    ["Xây Nhà Chánh Nghĩa", "xây nhà Chánh Nghĩa", "xay-nha-chanh-nghia-geo2"],
    ["Xây Nhà Phú Lợi TDM", "xây nhà Phú Lợi Thủ Dầu Một", "xay-nha-phu-loi-tdm-geo2"],
    ["Xây Nhà Phú Cường TDM", "xây nhà Phú Cường Thủ Dầu Một", "xay-nha-phu-cuong-tdm-geo2"],
    ["Xây Nhà Định Hòa TDM", "xây nhà Định Hòa Thủ Dầu Một", "xay-nha-dinh-hoa-tdm-geo2"],
    ["Xây Nhà Tân Hiệp Biên Hòa", "xây nhà Tân Hiệp Biên Hòa", "xay-nha-tan-hiep-bien-hoa-geo2"],
    ["Xây Nhà Tân Mai Biên Hòa", "xây nhà Tân Mai Biên Hòa", "xay-nha-tan-mai-bien-hoa-geo2"],
    ["Xây Nhà Tam Hiệp Biên Hòa", "xây nhà Tam Hiệp Biên Hòa", "xay-nha-tam-hiep-bien-hoa-geo2"],
    ["Xây Nhà Quyết Thắng BH", "xây nhà Quyết Thắng Biên Hòa", "xay-nha-quyet-thang-bh-geo2"],
    ["Xây Nhà Trung Dũng BH", "xây nhà Trung Dũng Biên Hòa", "xay-nha-trung-dung-bh-geo2"],
    ["Xây Nhà Quang Vinh BH", "xây nhà Quang Vinh Biên Hòa", "xay-nha-quang-vinh-bh-geo2"],
    ["Xây Nhà Bửu Long", "xây nhà Bửu Long", "xay-nha-buu-long-geo2"],
    ["Xây Nhà Bửu Hòa", "xây nhà Bửu Hòa", "xay-nha-buu-hoa-geo2"],
    ["Xây Nhà Long Bình Tân", "xây nhà Long Bình Tân", "xay-nha-long-binh-tan-geo2"],
    ["Xây Nhà An Hòa Biên Hòa", "xây nhà An Hòa Biên Hòa", "xay-nha-an-hoa-bien-hoa-geo2"],
    ["Xây Nhà Phước Tân", "xây nhà Phước Tân", "xay-nha-phuoc-tan-geo2"],
    ["Xây Nhà Tam Phước", "xây nhà Tam Phước", "xay-nha-tam-phuoc-geo2"],
    ["Xây Nhà Long Phước DN", "xây nhà Long Phước Đồng Nai", "xay-nha-long-phuoc-dn-geo2"],
    ["Xây Nhà An Phước Long Thành", "xây nhà An Phước Long Thành", "xay-nha-an-phuoc-long-thanh-geo2"],
    ["Xây Nhà Bình Sơn Long Thành", "xây nhà Bình Sơn Long Thành", "xay-nha-binh-son-long-thanh-geo2"],
    ["Xây Nhà Lộc An Long Thành", "xây nhà Lộc An Long Thành", "xay-nha-loc-an-long-thanh-geo2"],
    ["Xây Nhà Long An Long Thành", "xây nhà Long An Long Thành", "xay-nha-long-an-long-thanh-geo2"],
    ["Xây Nhà Phước Thái", "xây nhà Phước Thái", "xay-nha-phuoc-thai-geo2"],
    ["Xây Nhà Phước Bình NT", "xây nhà Phước Bình Nhơn Trạch", "xay-nha-phuoc-binh-nt-geo2"],
    ["Xây Nhà Long Thọ", "xây nhà Long Thọ", "xay-nha-long-tho-geo2"],
    ["Xây Nhà Phú Hội NT", "xây nhà Phú Hội Nhơn Trạch", "xay-nha-phu-hoi-nt-geo2"],
    ["Xây Nhà Phước An NT", "xây nhà Phước An Nhơn Trạch", "xay-nha-phuoc-an-nt-geo2"],
    ["Xây Nhà Vĩnh Thanh NT", "xây nhà Vĩnh Thanh Nhơn Trạch", "xay-nha-vinh-thanh-nt-geo2"],
    ["Xây Nhà Đại Phước", "xây nhà Đại Phước", "xay-nha-dai-phuoc-geo2"],
    ["Xây Nhà Phú Đông NT", "xây nhà Phú Đông Nhơn Trạch", "xay-nha-phu-dong-nt-geo2"],
    ["Xây Nhà Hựu Thạnh", "xây nhà Hựu Thạnh", "xay-nha-huu-thanh-geo2"],
    ["Xây Nhà Đức Lập Thượng", "xây nhà Đức Lập Thượng", "xay-nha-duc-lap-thuong-geo2"],
    ["Xây Nhà Đức Lập Hạ", "xây nhà Đức Lập Hạ", "xay-nha-duc-lap-ha-geo2"],
    ["Xây Nhà Mỹ Hạnh Bắc", "xây nhà Mỹ Hạnh Bắc", "xay-nha-my-hanh-bac-geo2"],
    ["Xây Nhà Mỹ Hạnh Nam", "xây nhà Mỹ Hạnh Nam", "xay-nha-my-hanh-nam-geo2"],
    ["Xây Nhà Lương Hòa", "xây nhà Lương Hòa", "xay-nha-luong-hoa-geo2"],
    ["Xây Nhà Tân Bửu", "xây nhà Tân Bửu", "xay-nha-tan-buu-geo2"],
    ["Xây Nhà Thạnh Lợi BL", "xây nhà Thạnh Lợi Bến Lức", "xay-nha-thanh-loi-bl-geo2"],
    ["Xây Nhà Lương Bình", "xây nhà Lương Bình", "xay-nha-luong-binh-geo2"],
    ["Xây Nhà An Thạnh BL", "xây nhà An Thạnh Bến Lức", "xay-nha-an-thanh-bl-geo2"],
    ["Xây Nhà Phước Lý", "xây nhà Phước Lý", "xay-nha-phuoc-ly-geo2"],
    ["Xây Nhà Long Thượng", "xây nhà Long Thượng", "xay-nha-long-thuong-geo2"],
    ["Xây Nhà Long Hậu", "xây nhà Long Hậu", "xay-nha-long-hau-geo2"],
    ["Xây Nhà Phước Lâm", "xây nhà Phước Lâm", "xay-nha-phuoc-lam-geo2"],
    ["Xây Nhà Mỹ Lộc CG", "xây nhà Mỹ Lộc Cần Giuộc", "xay-nha-my-loc-cg-geo2"],
    ["Xây Nhà KĐT Vsip 1", "xây nhà gần VSIP 1", "xay-nha-gan-vsip-1-geo2"],
    ["Xây Nhà KĐT Vsip 2", "xây nhà gần VSIP 2", "xay-nha-gan-vsip-2-geo2"],
    ["Xây Nhà KĐT Becamex", "xây nhà gần Becamex", "xay-nha-gan-becamex-geo2"],
    ["Xây Nhà KĐT Aqua City", "xây nhà gần Aqua City", "xay-nha-gan-aqua-city-geo2"],
    ["Xây Nhà KĐT Novaworld", "xây nhà gần NovaWorld", "xay-nha-gan-novaworld-geo2"],
    ["Xây Nhà KĐT Mizuki", "xây nhà gần Mizuki", "xay-nha-gan-mizuki-geo2"],
    ["Xây Nhà KĐT Waterpoint", "xây nhà gần Waterpoint", "xay-nha-gan-waterpoint-geo2"],
    ["Xây Nhà Trục QL1A", "xây nhà gần QL1A", "xay-nha-gan-ql1a-geo2"],
    ["Xây Nhà Trục QL13", "xây nhà gần QL13", "xay-nha-gan-ql13-geo2"],
    ["Xây Nhà Trục QL51", "xây nhà gần QL51", "xay-nha-gan-ql51-geo2"],
    ["Xây Nhà Trục QL22", "xây nhà gần QL22", "xay-nha-gan-ql22-geo2"],
    ["Xây Nhà Trục QL50", "xây nhà gần QL50", "xay-nha-gan-ql50-geo2"],
    ["Xây Nhà Cao Tốc HCM Long Thành", "xây nhà gần cao tốc Long Thành", "xay-nha-gan-cao-toc-long-thanh-geo2"],
    ["Xây Nhà Cao Tốc Trung Lương Mỹ Thuận", "xây nhà gần cao tốc Mỹ Thuận", "xay-nha-gan-cao-toc-my-thuan-geo2"],
    ["Xây Nhà Metro Số 1", "xây nhà gần metro số 1", "xay-nha-gan-metro-1-geo2"],
    ["Xây Nhà Metro Số 2", "xây nhà gần metro số 2", "xay-nha-gan-metro-2-geo2"],
    ["Cải Tạo Nhà Thuận An", "cải tạo nhà Thuận An", "cai-tao-nha-thuan-an-geo2"],
    ["Cải Tạo Nhà Dĩ An BD", "cải tạo nhà Dĩ An", "cai-tao-nha-di-an-bd-geo2"],
    ["Cải Tạo Nhà Long Thành DN", "cải tạo nhà Long Thành", "cai-tao-nha-long-thanh-dn-geo2"],
    ["Cải Tạo Nhà Nhơn Trạch DN", "cải tạo nhà Nhơn Trạch", "cai-tao-nha-nhon-trach-dn-geo2"],
    ["Thiết Kế Nhà Thuận An", "thiết kế nhà Thuận An", "thiet-ke-nha-thuan-an-geo2"],
    ["Thiết Kế Nhà Dĩ An BD", "thiết kế nhà Dĩ An BD", "thiet-ke-nha-di-an-bd-geo2"],
    ["Thiết Kế Nhà Biên Hòa Phường", "thiết kế nhà Biên Hòa", "thiet-ke-nha-bien-hoa-phuong-geo2"],
    ["Báo Giá Xây Nhà Thuận An", "báo giá xây nhà Thuận An", "bao-gia-xay-nha-thuan-an-geo2"],
    ["Báo Giá Xây Nhà Dĩ An BD", "báo giá xây nhà Dĩ An", "bao-gia-xay-nha-di-an-bd-geo2"],
    ["Báo Giá Xây Nhà Long Thành DN", "báo giá xây nhà Long Thành DN", "bao-gia-xay-nha-long-thanh-dn-geo2"],
    ["Nhà Thầu Thuận An", "nhà thầu Thuận An", "nha-thau-thuan-an-geo2"],
    ["Nhà Thầu Dĩ An", "nhà thầu Dĩ An", "nha-thau-di-an-geo2"],
    ["Nhà Thầu Long Thành", "nhà thầu Long Thành", "nha-thau-long-thanh-geo2"],
    ["Nhà Thầu Nhơn Trạch", "nhà thầu Nhơn Trạch", "nha-thau-nhon-trach-geo2"],
    ["Xây Nhà Ven Sông Đồng Nai", "xây nhà ven sông Đồng Nai", "xay-nha-ven-song-dong-nai-geo2"],
    ["Xây Nhà Ven Sông Sài Gòn BD", "xây nhà ven sông Sài Gòn BD", "xay-nha-ven-song-sai-gon-bd-geo2"],
    ["Xây Biệt Thự Thuận An", "xây biệt thự Thuận An", "xay-biet-thu-thuan-an-geo2"],
    ["Xây Biệt Thự Long Thành", "xây biệt thự Long Thành", "xay-biet-thu-long-thanh-geo2"],
    ["Xây Nhà Vườn Nhơn Trạch", "xây nhà vườn Nhơn Trạch", "xay-nha-vuon-nhon-trach-geo2"],
    ["Xây Nhà Vườn Đức Hòa", "xây nhà vườn Đức Hòa LA", "xay-nha-vuon-duc-hoa-la-geo2"],
  ]);

  // 48 — quản lý dự án / giám sát / tiến độ chuyên sâu
  const b48 = pairs([
    ["Quản Lý Dự Án Xây Nhà", "quản lý dự án xây nhà", "quan-ly-du-an-xay-nha-pm"],
    ["Project Manager Xây Nhà", "project manager xây nhà", "project-manager-xay-nha-pm"],
    ["Lập Kế Hoạch Xây Nhà", "lập kế hoạch xây nhà", "lap-ke-hoach-xay-nha-pm"],
    ["Lập Tiến Độ Gantt Xây", "lập tiến độ gantt xây", "lap-tien-do-gantt-xay-pm"],
    ["Critical Path Xây Nhà", "critical path xây nhà", "critical-path-xay-nha-pm"],
    ["Milestone Xây Nhà", "milestone xây nhà", "milestone-xay-nha-pm"],
    ["Baseline Tiến Độ Xây", "baseline tiến độ xây", "baseline-tien-do-xay-pm"],
    ["Cập Nhật Tiến Độ Hàng Tuần", "cập nhật tiến độ hàng tuần", "cap-nhat-tien-do-hang-tuan-pm"],
    ["Báo Cáo Tiến Độ Chủ Nhà", "báo cáo tiến độ chủ nhà", "bao-cao-tien-do-chu-nha-pm"],
    ["Họp Hiện Trường Xây", "họp hiện trường xây", "hop-hien-truong-xay-pm"],
    ["Biên Bản Họp Công Trình", "biên bản họp công trình", "bien-ban-hop-cong-trinh-pm"],
    ["RFI Công Trình Xây", "rfi công trình xây", "rfi-cong-trinh-xay-pm"],
    ["Submittal Vật Tư Xây", "submittal vật tư xây", "submittal-vat-tu-xay-pm"],
    ["Shop Drawing Nhà Phố", "shop drawing nhà phố", "shop-drawing-nha-pho-pm"],
    ["Change Order Xây Nhà", "change order xây nhà", "change-order-xay-nha-pm"],
    ["Variation Order Xây", "variation order xây", "variation-order-xay-pm"],
    ["Claim Phát Sinh Xây", "claim phát sinh xây", "claim-phat-sinh-xay-pm"],
    ["EOT Gia Hạn Tiến Độ", "eot gia hạn tiến độ", "eot-gia-han-tien-do-pm"],
    ["Risk Register Xây Nhà", "risk register xây nhà", "risk-register-xay-nha-pm"],
    ["Quản Lý Rủi Ro Công Trình", "quản lý rủi ro công trình", "quan-ly-rui-ro-cong-trinh-pm"],
    ["Quản Lý Chi Phí Công Trình", "quản lý chi phí công trình", "quan-ly-chi-phi-cong-trinh-pm"],
    ["Cost Control Xây Nhà", "cost control xây nhà", "cost-control-xay-nha-pm"],
    ["Earned Value Xây Nhà", "earned value xây nhà", "earned-value-xay-nha-pm"],
    ["Cash Flow Xây Nhà", "cash flow xây nhà", "cash-flow-xay-nha-pm"],
    ["Bill of Quantities Nhà", "bill of quantities nhà", "bill-of-quantities-nha-pm"],
    ["Đo Bóc Khối Lượng Xây", "đo bóc khối lượng xây", "do-boc-khoi-luong-xay-pm"],
    ["Nghiệm Thu Khối Lượng", "nghiệm thu khối lượng", "nghiem-thu-khoi-luong-pm"],
    ["Thanh Toán Theo Khối Lượng", "thanh toán theo khối lượng", "thanh-toan-theo-khoi-luong-pm"],
    ["Giám Sát Thi Công Nhà Phố", "giám sát thi công nhà phố", "giam-sat-thi-cong-nha-pho-pm"],
    ["Giám Sát Hiện Trường", "giám sát hiện trường", "giam-sat-hien-truong-pm"],
    ["Giám Sát Chất Lượng", "giám sát chất lượng", "giam-sat-chat-luong-pm"],
    ["Giám Sát An Toàn", "giám sát an toàn", "giam-sat-an-toan-pm"],
    ["Tư Vấn Giám Sát Độc Lập", "tư vấn giám sát độc lập", "tu-van-giam-sat-doc-lap-pm"],
    ["Chủ Nhiệm Dự Án Xây", "chủ nhiệm dự án xây", "chu-nhiem-du-an-xay-pm"],
    ["Chỉ Huy Trưởng Công Trình", "chỉ huy trưởng công trình", "chi-huy-truong-cong-trinh-pm"],
    ["Đội Ngũ Thi Công Nhà Phố", "đội ngũ thi công nhà phố", "doi-ngu-thi-cong-nha-pho-pm"],
    ["Phân Công Nhân Lực Xây", "phân công nhân lực xây", "phan-cong-nhan-luc-xay-pm"],
    ["Quản Lý Nhà Thầu Phụ", "quản lý nhà thầu phụ", "quan-ly-nha-thau-phu-pm"],
    ["Coordination MEP Xây", "coordination mep xây", "coordination-mep-xay-pm"],
    ["Clash Detection Bản Vẽ", "clash detection bản vẽ", "clash-detection-ban-ve-pm"],
    ["BIM Nhà Phố Cơ Bản", "bim nhà phố cơ bản", "bim-nha-pho-co-ban-pm"],
    ["Revit Nhà Phố", "revit nhà phố", "revit-nha-pho-pm"],
    ["App Quản Lý Công Trình", "app quản lý công trình", "app-quan-ly-cong-trinh-pm"],
    ["Phần Mềm Tiến Độ Xây", "phần mềm tiến độ xây", "phan-mem-tien-do-xay-pm"],
    ["Photo Log Công Trình", "photo log công trình", "photo-log-cong-trinh-pm"],
    ["Drone Survey Công Trình", "drone survey công trình", "drone-survey-cong-trinh-pm"],
    ["Time Lapse Công Trình", "time lapse công trình", "time-lapse-cong-trinh-pm"],
    ["Daily Report Công Trình", "daily report công trình", "daily-report-cong-trinh-pm"],
    ["Weekly Report Công Trình", "weekly report công trình", "weekly-report-cong-trinh-pm"],
    ["Punch List Cuối Công Trình", "punch list cuối công trình", "punch-list-cuoi-cong-trinh-pm"],
    ["Snagging Trước Bàn Giao", "snagging trước bàn giao", "snagging-truoc-ban-giao-pm"],
    ["Commissioning Hệ Thống", "commissioning hệ thống", "commissioning-he-thong-pm"],
    ["Handover Package Nhà", "handover package nhà", "handover-package-nha-pm"],
    ["As Built Drawing Bàn Giao", "as built drawing bàn giao", "as-built-drawing-ban-giao-pm"],
    ["O&M Manual Bàn Giao", "o&m manual bàn giao", "om-manual-ban-giao-pm"],
    ["Warranty Certificate Nhà", "warranty certificate nhà", "warranty-certificate-nha-pm"],
    ["Defect Liability Period", "defect liability period", "defect-liability-period-pm"],
    ["Retention Money Xây Nhà", "retention money xây nhà", "retention-money-xay-nha-pm"],
    ["Final Account Xây Nhà", "final account xây nhà", "final-account-xay-nha-pm"],
    ["Close Out Dự Án Xây", "close out dự án xây", "close-out-du-an-xay-pm"],
    ["Lesson Learned Xây Nhà", "lesson learned xây nhà", "lesson-learned-xay-nha-pm"],
    ["KPI Nhà Thầu Xây", "kpi nhà thầu xây", "kpi-nha-thau-xay-pm"],
    ["Scorecard Đánh Giá Thầu", "scorecard đánh giá thầu", "scorecard-danh-gia-thau-pm"],
    ["Vendor Evaluation Xây", "vendor evaluation xây", "vendor-evaluation-xay-pm"],
    ["Prequalification Nhà Thầu", "prequalification nhà thầu", "prequalification-nha-thau-pm"],
    ["Tender Package Xây Nhà", "tender package xây nhà", "tender-package-xay-nha-pm"],
    ["So Thầu Xây Nhà", "so thầu xây nhà", "so-thau-xay-nha-pm"],
    ["Negotiating Hợp Đồng Xây", "negotiating hợp đồng xây", "negotiating-hop-dong-xay-pm"],
    ["Kick Off Meeting Xây", "kick off meeting xây", "kick-off-meeting-xay-pm"],
    ["Site Induction Công Trình", "site induction công trình", "site-induction-cong-trinh-pm"],
    ["Method Statement Xây", "method statement xây", "method-statement-xay-pm"],
    ["ITP Inspection Test Plan", "itp inspection test plan", "itp-inspection-test-plan-pm"],
    ["NCR Non Conformance", "ncr non conformance", "ncr-non-conformance-pm"],
    ["CAR Corrective Action", "car corrective action", "car-corrective-action-pm"],
    ["Toolbox Talk Công Trình", "toolbox talk công trình", "toolbox-talk-cong-trinh-pm"],
    ["Permit To Work Công Trình", "permit to work công trình", "permit-to-work-cong-trinh-pm"],
    ["Hot Work Permit Xây", "hot work permit xây", "hot-work-permit-xay-pm"],
    ["Lifting Plan Công Trình", "lifting plan công trình", "lifting-plan-cong-trinh-pm"],
    ["Traffic Management Site", "traffic management site", "traffic-management-site-pm"],
    ["Waste Management Site", "waste management site", "waste-management-site-pm"],
    ["Environmental Plan Xây", "environmental plan xây", "environmental-plan-xay-pm"],
    ["Quality Plan Xây Nhà", "quality plan xây nhà", "quality-plan-xay-nha-pm"],
    ["HSE Plan Công Trình", "hse plan công trình", "hse-plan-cong-trinh-pm"],
    ["Emergency Response Site", "emergency response site", "emergency-response-site-pm"],
    ["First Aid Công Trình", "first aid công trình", "first-aid-cong-trinh-pm"],
    ["PPE Công Trường Xây", "ppe công trường xây", "ppe-cong-truong-xay-pm"],
    ["Scaffolding Inspection", "scaffolding inspection", "scaffolding-inspection-pm"],
    ["Formwork Inspection", "formwork inspection", "formwork-inspection-pm"],
    ["Rebar Inspection", "rebar inspection", "rebar-inspection-pm"],
    ["Concrete Pour Checklist", "concrete pour checklist", "concrete-pour-checklist-pm"],
    ["Waterproofing Checklist", "waterproofing checklist", "waterproofing-checklist-pm"],
    ["MEP Rough In Checklist", "mep rough in checklist", "mep-rough-in-checklist-pm"],
    ["Finishing Checklist Xây", "finishing checklist xây", "finishing-checklist-xay-pm"],
    ["Pre Handover Checklist", "pre handover checklist", "pre-handover-checklist-pm"],
    ["Client Walkthrough Nhà", "client walkthrough nhà", "client-walkthrough-nha-pm"],
    ["Soft Opening Nhà Ở", "soft opening nhà ở", "soft-opening-nha-o-pm"],
  ]);

  // 49 — FAQ dài / how-to / Ads local intent
  const b49 = pairs([
    ["Xây Nhà Bắt Đầu Từ Đâu", "xây nhà bắt đầu từ đâu", "xay-nha-bat-dau-tu-dau-faq2"],
    ["Cải Tạo Nhà Bắt Đầu Từ Đâu", "cải tạo nhà bắt đầu từ đâu", "cai-tao-nha-bat-dau-tu-dau-faq2"],
    ["Xây Nhà Cần Bao Nhiêu Vốn", "xây nhà cần bao nhiêu vốn", "xay-nha-can-bao-nhieu-von-faq2"],
    ["Cải Tạo Nhà Cần Bao Nhiêu Vốn", "cải tạo nhà cần bao nhiêu vốn", "cai-tao-nha-can-bao-nhieu-von-faq2"],
    ["Xây Nhà Mất Bao Lâu", "xây nhà mất bao lâu", "xay-nha-mat-bao-lau-faq2"],
    ["Cải Tạo Nhà Mất Bao Lâu", "cải tạo nhà mất bao lâu", "cai-tao-nha-mat-bao-lau-faq2"],
    ["Xin Phép Xây Mất Bao Lâu", "xin phép xây mất bao lâu", "xin-phep-xay-mat-bao-lau-faq2"],
    ["Thiết Kế Nhà Mất Bao Lâu", "thiết kế nhà mất bao lâu", "thiet-ke-nha-mat-bao-lau-faq2"],
    ["Làm Sao Chọn Nhà Thầu", "làm sao chọn nhà thầu", "lam-sao-chon-nha-thau-faq2"],
    ["Làm Sao Chọn Kiến Trúc Sư", "làm sao chọn kiến trúc sư", "lam-sao-chon-kien-truc-su-faq2"],
    ["Làm Sao Đọc Bản Vẽ Nhà", "làm sao đọc bản vẽ nhà", "lam-sao-doc-ban-ve-nha-faq2"],
    ["Làm Sao Đọc Báo Giá Xây", "làm sao đọc báo giá xây", "lam-sao-doc-bao-gia-xay-faq2"],
    ["Làm Sao Kiểm Tra Chất Lượng", "làm sao kiểm tra chất lượng", "lam-sao-kiem-tra-chat-luong-faq2"],
    ["Làm Sao Tránh Phát Sinh", "làm sao tránh phát sinh", "lam-sao-tranh-phat-sinh-faq2"],
    ["Làm Sao Giữ Tiến Độ Xây", "làm sao giữ tiến độ xây", "lam-sao-giu-tien-do-xay-faq2"],
    ["Làm Sao Xử Lý Thầu Trễ", "làm sao xử lý thầu trễ", "lam-sao-xu-ly-thau-tre-faq2"],
    ["Làm Sao Xử Lý Thầu Bỏ", "làm sao xử lý thầu bỏ", "lam-sao-xu-ly-thau-bo-faq2"],
    ["Có Nên Tự Mua Vật Tư", "có nên tự mua vật tư", "co-nen-tu-mua-vat-tu-faq2"],
    ["Có Nên Thuê Giám Sát", "có nên thuê giám sát", "co-nen-thue-giam-sat-faq2"],
    ["Có Nên Xây Trọn Gói", "có nên xây trọn gói", "co-nen-xay-tron-goi-faq2"],
    ["Có Nên Xây Phần Thô", "có nên xây phần thô", "co-nen-xay-phan-tho-faq2"],
    ["Có Nên Cải Tạo Hay Xây Mới", "có nên cải tạo hay xây mới", "co-nen-cai-tao-hay-xay-moi-faq2"],
    ["Có Nên Nâng Tầng Nhà Cũ", "có nên nâng tầng nhà cũ", "co-nen-nang-tang-nha-cu-faq2"],
    ["Có Nên Làm Giếng Trời", "có nên làm giếng trời", "co-nen-lam-gieng-troi-faq2"],
    ["Có Nên Làm Hầm Xe", "có nên làm hầm xe", "co-nen-lam-ham-xe-faq2"],
    ["Có Nên Làm Thang Máy", "có nên làm thang máy", "co-nen-lam-thang-may-faq2"],
    ["Có Nên Làm Sân Thượng", "có nên làm sân thượng", "co-nen-lam-san-thuong-faq2"],
    ["Nhà Hẹp Bao Nhiêu Tầng", "nhà hẹp bao nhiêu tầng", "nha-hep-bao-nhieu-tang-faq2"],
    ["Nhà 4m Nên Mấy Phòng", "nhà 4m nên mấy phòng", "nha-4m-nen-may-phong-faq2"],
    ["Nhà 5m Nên Mấy Phòng", "nhà 5m nên mấy phòng", "nha-5m-nen-may-phong-faq2"],
    ["How To Xây Nhà Lần Đầu", "how to xây nhà lần đầu", "how-to-xay-nha-lan-dau-faq2"],
    ["How To Cải Tạo Nhà Cũ", "how to cải tạo nhà cũ", "how-to-cai-tao-nha-cu-faq2"],
    ["How To Xin Phép Xây", "how to xin phép xây", "how-to-xin-phep-xay-faq2"],
    ["How To Chọn Phong Cách Nhà", "how to chọn phong cách nhà", "how-to-chon-phong-cach-nha-faq2"],
    ["How To Tối Ưu Ngân Sách", "how to tối ưu ngân sách", "how-to-toi-uu-ngan-sach-faq2"],
    ["How To Nghiệm Thu Nhà", "how to nghiệm thu nhà", "how-to-nghiem-thu-nha-faq2"],
    ["What Is Xây Trọn Gói", "what is xây trọn gói", "what-is-xay-tron-goi-faq2"],
    ["What Is Xây Phần Thô", "what is xây phần thô", "what-is-xay-phan-tho-faq2"],
    ["What Is Đơn Giá m2", "what is đơn giá m2", "what-is-don-gia-m2-faq2"],
    ["What Is Phát Sinh Xây", "what is phát sinh xây", "what-is-phat-sinh-xay-faq2"],
    ["Why Xây Nhà Đắt", "why xây nhà đắt", "why-xay-nha-dat-faq2"],
    ["Why Cải Tạo Đắt", "why cải tạo đắt", "why-cai-tao-dat-faq2"],
    ["Why Nhà Thấm", "why nhà thấm", "why-nha-tham-faq2"],
    ["Why Nhà Nóng", "why nhà nóng", "why-nha-nong-faq2"],
    ["Why Nhà Ồn", "why nhà ồn", "why-nha-on-faq2"],
    ["When Nên Xây Nhà", "when nên xây nhà", "when-nen-xay-nha-faq2"],
    ["When Nên Cải Tạo", "when nên cải tạo", "when-nen-cai-tao-faq2"],
    ["Where Thuê Thầu TPHCM", "where thuê thầu tphcm", "where-thue-thau-tphcm-faq2"],
    ["Where Mua Vật Tư Xây", "where mua vật tư xây", "where-mua-vat-tu-xay-faq2"],
    ["Who Nên Thuê Khi Xây", "who nên thuê khi xây", "who-nen-thue-khi-xay-faq2"],
    ["Xây Nhà Quận 1", "xây nhà quận 1", "xay-nha-quan-1-loc"],
    ["Xây Nhà Quận 3", "xây nhà quận 3", "xay-nha-quan-3-loc"],
    ["Xây Nhà Quận 4", "xây nhà quận 4", "xay-nha-quan-4-loc"],
    ["Xây Nhà Quận 5", "xây nhà quận 5", "xay-nha-quan-5-loc"],
    ["Xây Nhà Quận 6", "xây nhà quận 6", "xay-nha-quan-6-loc"],
    ["Xây Nhà Quận 8", "xây nhà quận 8", "xay-nha-quan-8-loc"],
    ["Xây Nhà Quận 10", "xây nhà quận 10", "xay-nha-quan-10-loc"],
    ["Xây Nhà Quận 11", "xây nhà quận 11", "xay-nha-quan-11-loc"],
    ["Xây Nhà Phú Nhuận Loc", "xây nhà Phú Nhuận", "xay-nha-phu-nhuan-loc"],
    ["Xây Nhà Tân Bình Loc", "xây nhà Tân Bình", "xay-nha-tan-binh-loc"],
    ["Xây Nhà Tân Phú Loc", "xây nhà Tân Phú", "xay-nha-tan-phu-loc"],
    ["Xây Nhà Gò Vấp Loc", "xây nhà Gò Vấp", "xay-nha-go-vap-loc"],
    ["Xây Nhà Bình Thạnh Loc", "xây nhà Bình Thạnh", "xay-nha-binh-thanh-loc"],
    ["Cải Tạo Nhà Quận 1", "cải tạo nhà quận 1", "cai-tao-nha-quan-1-loc"],
    ["Cải Tạo Nhà Quận 3", "cải tạo nhà quận 3", "cai-tao-nha-quan-3-loc"],
    ["Cải Tạo Nhà Bình Thạnh Loc", "cải tạo nhà Bình Thạnh", "cai-tao-nha-binh-thanh-loc"],
    ["Cải Tạo Nhà Gò Vấp Loc", "cải tạo nhà Gò Vấp", "cai-tao-nha-go-vap-loc"],
    ["Cải Tạo Nhà Tân Bình Loc", "cải tạo nhà Tân Bình", "cai-tao-nha-tan-binh-loc"],
    ["Nhà Thầu Quận 1", "nhà thầu quận 1", "nha-thau-quan-1-loc"],
    ["Nhà Thầu Quận 3", "nhà thầu quận 3", "nha-thau-quan-3-loc"],
    ["Nhà Thầu Bình Thạnh Loc", "nhà thầu Bình Thạnh", "nha-thau-binh-thanh-loc"],
    ["Nhà Thầu Gò Vấp Loc", "nhà thầu Gò Vấp", "nha-thau-go-vap-loc"],
    ["Nhà Thầu Thủ Đức Loc", "nhà thầu Thủ Đức", "nha-thau-thu-duc-loc"],
    ["Báo Giá Xây Nhà Quận 1", "báo giá xây nhà quận 1", "bao-gia-xay-nha-quan-1-loc"],
    ["Báo Giá Xây Nhà Bình Thạnh", "báo giá xây nhà Bình Thạnh", "bao-gia-xay-nha-binh-thanh-loc"],
    ["Báo Giá Xây Nhà Gò Vấp", "báo giá xây nhà Gò Vấp", "bao-gia-xay-nha-go-vap-loc"],
    ["Báo Giá Xây Nhà Thủ Đức Loc", "báo giá xây nhà Thủ Đức", "bao-gia-xay-nha-thu-duc-loc"],
    ["Near Me Xây Nhà TPHCM", "xây nhà near me tphcm", "xay-nha-near-me-tphcm-ads3"],
    ["Near Me Cải Tạo TPHCM", "cải tạo near me tphcm", "cai-tao-near-me-tphcm-ads3"],
    ["Near Me Nhà Thầu TPHCM", "nhà thầu near me tphcm", "nha-thau-near-me-tphcm-ads3"],
    ["Best Nhà Thầu TPHCM 2026", "best nhà thầu tphcm 2026", "best-nha-thau-tphcm-2026-ads3"],
    ["Best Công Ty Xây 2026", "best công ty xây 2026", "best-cong-ty-xay-2026-ads3"],
    ["Cheap Xây Nhà TPHCM", "cheap xây nhà tphcm", "cheap-xay-nha-tphcm-ads3"],
    ["Affordable Cải Tạo TPHCM", "affordable cải tạo tphcm", "affordable-cai-tao-tphcm-ads3"],
    ["Trusted Nhà Thầu TPHCM", "trusted nhà thầu tphcm", "trusted-nha-thau-tphcm-ads3"],
    ["Verified Công Ty Xây", "verified công ty xây", "verified-cong-ty-xay-ads3"],
    ["Get Quote Xây Nhà", "get quote xây nhà", "get-quote-xay-nha-ads3"],
    ["Free Estimate Xây Nhà", "free estimate xây nhà", "free-estimate-xay-nha-ads3"],
    ["Call Now Tư Vấn Xây", "call now tư vấn xây", "call-now-tu-van-xay-ads3"],
    ["WhatsApp Tư Vấn Xây", "whatsapp tư vấn xây", "whatsapp-tu-van-xay-ads3"],
    ["Book Survey Xây Nhà", "book survey xây nhà", "book-survey-xay-nha-ads3"],
    ["Schedule Visit Công Trình", "schedule visit công trình", "schedule-visit-cong-trinh-ads3"],
    ["Request Proposal Xây", "request proposal xây", "request-proposal-xay-ads3"],
  ]);

  return [b45, b46, b47, b48, b49].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 3947 + (batch - 45) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    45: "Cluster: phong cách kiến trúc, mặt bằng, mẫu nhà.",
    46: "Cluster: vật liệu chi tiết, so sánh vật liệu.",
    47: "Cluster: geo Đông Nam Bộ, KĐT, trục đường.",
    48: "Cluster: quản lý dự án, giám sát, tiến độ chuyên sâu.",
    49: "Cluster: FAQ how-to, local intent, Ads conversion.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: phong cách kiến trúc, mặt bằng, mẫu nhà.",
  "Cluster: vật liệu chi tiết, so sánh vật liệu.",
  "Cluster: geo Đông Nam Bộ, KĐT, trục đường.",
  "Cluster: quản lý dự án, giám sát, tiến độ chuyên sâu.",
  "Cluster: FAQ how-to, local intent, Ads conversion.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 45 + i;
  const startNo = 3947 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 45 ? 44 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
