/**
 * Generator: short-keyword batches 40–44 (500 articles, #3447–#3946).
 * Run: npx tsx scripts/gen-short-keyword-batches-40-44.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${40 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${40 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${40 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 40 — mặt tiền / ngoại thất / cảnh quan
  const b40 = pairs([
    ["Mặt Tiền Nhà Phố Hiện Đại", "mặt tiền nhà phố hiện đại", "mat-tien-nha-pho-hien-dai-fc"],
    ["Mặt Tiền Nhà Phố Tối Giản", "mặt tiền nhà phố tối giản", "mat-tien-nha-pho-toi-gian-fc"],
    ["Mặt Tiền Nhà Phố Luxury", "mặt tiền nhà phố luxury", "mat-tien-nha-pho-luxury-fc"],
    ["Mặt Tiền Nhà Phố Indochine", "mặt tiền nhà phố indochine", "mat-tien-nha-pho-indochine-fc"],
    ["Mặt Tiền Ốp Đá", "mặt tiền ốp đá", "mat-tien-op-da-fc"],
    ["Mặt Tiền Ốp Gạch", "mặt tiền ốp gạch", "mat-tien-op-gach-fc"],
    ["Mặt Tiền Sơn Giả Đá", "mặt tiền sơn giả đá", "mat-tien-son-gia-da-fc"],
    ["Mặt Tiền Gỗ Nhựa", "mặt tiền gỗ nhựa", "mat-tien-go-nhua-fc"],
    ["Mặt Tiền Lam Nhôm", "mặt tiền lam nhôm", "mat-tien-lam-nhom-fc"],
    ["Mặt Tiền Lam Gỗ", "mặt tiền lam gỗ", "mat-tien-lam-go-fc"],
    ["Mặt Tiền Kính Cường Lực", "mặt tiền kính cường lực", "mat-tien-kinh-cuong-luc-fc"],
    ["Mặt Tiền Tường Rào Kết Hợp", "mặt tiền tường rào kết hợp", "mat-tien-tuong-rao-ket-hop-fc"],
    ["Cổng Nhà Phố Hiện Đại", "cổng nhà phố hiện đại", "cong-nha-pho-hien-dai-fc"],
    ["Cổng Sắt CNC", "cổng sắt cnc", "cong-sat-cnc-fc"],
    ["Cổng Nhôm Đúc", "cổng nhôm đúc", "cong-nhom-duc-fc"],
    ["Cổng Tự Động Nhà Phố", "cổng tự động nhà phố", "cong-tu-dong-nha-pho-fc"],
    ["Tường Rào Nhà Phố", "tường rào nhà phố", "tuong-rao-nha-pho-fc"],
    ["Tường Rào Kết Hợp Cây Xanh", "tường rào kết hợp cây xanh", "tuong-rao-ket-hop-cay-xanh-fc"],
    ["Hàng Rào Sắt Mỹ Thuật", "hàng rào sắt mỹ thuật", "hang-rao-sat-my-thuat-fc"],
    ["Hàng Rào Inox", "hàng rào inox", "hang-rao-inox-fc"],
    ["Sân Trước Nhà Phố", "sân trước nhà phố", "san-truoc-nha-pho-fc"],
    ["Sân Sau Nhà Phố", "sân sau nhà phố", "san-sau-nha-pho-fc"],
    ["Sân Bên Hông Nhà", "sân bên hông nhà", "san-ben-hong-nha-fc"],
    ["Lát Sân Gạch Block", "lát sân gạch block", "lat-san-gach-block-fc"],
    ["Lát Sân Đá Tự Nhiên", "lát sân đá tự nhiên", "lat-san-da-tu-nhien-fc"],
    ["Lát Sân Bê Tông Vân Gỗ", "lát sân bê tông vân gỗ", "lat-san-be-tong-van-go-fc"],
    ["Đường Dẫn Vào Nhà", "đường dẫn vào nhà", "duong-dan-vao-nha-fc"],
    ["Bậc Tam Cấp Mặt Tiền", "bậc tam cấp mặt tiền", "bac-tam-cap-mat-tien-fc"],
    ["Mái Hiên Nhà Phố", "mái hiên nhà phố", "mai-hien-nha-pho-fc"],
    ["Mái Vòm Mặt Tiền", "mái vòm mặt tiền", "mai-vom-mat-tien-fc"],
    ["Ô Văng Cửa Sổ", "ô văng cửa sổ", "o-vang-cua-so-fc"],
    ["Ban Công Mặt Tiền", "ban công mặt tiền", "ban-cong-mat-tien-fc"],
    ["Ban Công Lan Can Kính", "ban công lan can kính", "ban-cong-lan-can-kinh-fc"],
    ["Ban Công Lan Can Sắt", "ban công lan can sắt", "ban-cong-lan-can-sat-fc"],
    ["Logia Nhà Phố", "logia nhà phố", "logia-nha-pho-fc"],
    ["Sân Thượng Trang Trí", "sân thượng trang trí", "san-thuong-trang-tri-fc"],
    ["Sân Thượng Có Mái Che", "sân thượng có mái che", "san-thuong-co-mai-che-fc"],
    ["Sân Thượng Không Mái", "sân thượng không mái", "san-thuong-khong-mai-fc"],
    ["Vườn Trước Nhà Nhỏ", "vườn trước nhà nhỏ", "vuon-truoc-nha-nho-fc"],
    ["Vườn Sau Nhà Nhỏ", "vườn sau nhà nhỏ", "vuon-sau-nha-nho-fc"],
    ["Vườn Đứng Mặt Tiền", "vườn đứng mặt tiền", "vuon-dung-mat-tien-fc"],
    ["Tường Xanh Mặt Tiền", "tường xanh mặt tiền", "tuong-xanh-mat-tien-fc"],
    ["Cây Bonsai Sân Trước", "cây bonsai sân trước", "cay-bonsai-san-truoc-fc"],
    ["Cây Ăn Trái Sân Sau", "cây ăn trái sân sau", "cay-an-trai-san-sau-fc"],
    ["Bồn Hoa Mặt Tiền", "bồn hoa mặt tiền", "bon-hoa-mat-tien-fc"],
    ["Đèn Sân Vườn Nhà Phố", "đèn sân vườn nhà phố", "den-san-vuon-nha-pho-fc"],
    ["Đèn Chiếu Mặt Tiền", "đèn chiếu mặt tiền", "den-chieu-mat-tien-fc"],
    ["Đèn Cổng Nhà", "đèn cổng nhà", "den-cong-nha-fc"],
    ["Hệ Thống Tưới Cây Tự Động", "hệ thống tưới cây tự động", "he-thong-tuoi-cay-tu-dong-fc"],
    ["Hồ Cá Mini Sân Trước", "hồ cá mini sân trước", "ho-ca-mini-san-truoc-fc"],
    ["Thác Nước Mini Nhà Phố", "thác nước mini nhà phố", "thac-nuoc-mini-nha-pho-fc"],
    ["Đá Cuội Trang Trí Sân", "đá cuội trang trí sân", "da-cuoi-trang-tri-san-fc"],
    ["Sỏi Trang Trí Vườn", "sỏi trang trí vườn", "soi-trang-tri-vuon-fc"],
    ["Chổi Cỏ Nhật Bản", "cỏ nhật bản sân vườn", "co-nhat-ban-san-vuon-fc"],
    ["Cỏ Nhung Nhật", "cỏ nhung nhật sân", "co-nhung-nhat-san-fc"],
    ["Gạch Chuyên Dụng Ngoài Trời", "gạch chuyên dụng ngoài trời", "gach-chuyen-dung-ngoai-troi-fc"],
    ["Sơn Ngoại Thất Chống Phai", "sơn ngoại thất chống phai", "son-ngoai-that-chong-phai-fc"],
    ["Sơn Ngoại Thất Chống Rêu", "sơn ngoại thất chống rêu", "son-ngoai-that-chong-reu-fc"],
    ["Chống Thấm Mặt Tiền", "chống thấm mặt tiền", "chong-tham-mat-tien-fc"],
    ["Vệ Sinh Mặt Tiền Nhà", "vệ sinh mặt tiền nhà", "ve-sinh-mat-tien-nha-fc"],
    ["Sơn Lại Mặt Tiền", "sơn lại mặt tiền", "son-lai-mat-tien-fc"],
    ["Cải Tạo Mặt Tiền Cũ", "cải tạo mặt tiền cũ", "cai-tao-mat-tien-cu-fc"],
    ["Nâng Cấp Cổng Rào", "nâng cấp cổng rào", "nang-cap-cong-rao-fc"],
    ["Thay Lan Can Ban Công", "thay lan can ban công", "thay-lan-can-ban-cong-fc"],
    ["Làm Mới Sân Trước", "làm mới sân trước", "lam-moi-san-truoc-fc"],
    ["Báo Giá Mặt Tiền Nhà Phố", "báo giá mặt tiền nhà phố", "bao-gia-mat-tien-nha-pho-fc"],
    ["Báo Giá Cổng Rào Nhà", "báo giá cổng rào nhà", "bao-gia-cong-rao-nha-fc"],
    ["Báo Giá Sân Vườn Nhà Phố", "báo giá sân vườn nhà phố", "bao-gia-san-vuon-nha-pho-fc"],
    ["Báo Giá Sân Thượng", "báo giá sân thượng", "bao-gia-san-thuong-fc"],
    ["Chi Phí Ốp Đá Mặt Tiền", "chi phí ốp đá mặt tiền", "chi-phi-op-da-mat-tien-fc"],
    ["Chi Phí Lam Nhôm Mặt Tiền", "chi phí lam nhôm mặt tiền", "chi-phi-lam-nhom-mat-tien-fc"],
    ["Chi Phí Vườn Đứng", "chi phí vườn đứng", "chi-phi-vuon-dung-fc"],
    ["Thiết Kế Cảnh Quan Nhà Phố", "thiết kế cảnh quan nhà phố", "thiet-ke-canh-quan-nha-pho-fc"],
    ["Thiết Kế Sân Vườn Nhỏ", "thiết kế sân vườn nhỏ", "thiet-ke-san-vuon-nho-fc"],
    ["Thiết Kế Sân Thượng Xanh", "thiết kế sân thượng xanh", "thiet-ke-san-thuong-xanh-fc"],
    ["Xu Hướng Mặt Tiền 2026", "xu hướng mặt tiền nhà 2026", "xu-huong-mat-tien-nha-2026-fc"],
    ["Xu Hướng Cảnh Quan 2026", "xu hướng cảnh quan 2026", "xu-huong-canh-quan-2026-fc"],
    ["Mặt Tiền Nhà Hẹp 3m", "mặt tiền nhà hẹp 3m", "mat-tien-nha-hep-3m-fc"],
    ["Mặt Tiền Nhà Hẹp 4m", "mặt tiền nhà hẹp 4m", "mat-tien-nha-hep-4m-fc"],
    ["Mặt Tiền Nhà 5m", "mặt tiền nhà 5m", "mat-tien-nha-5m-fc"],
    ["Mặt Tiền Nhà 6m", "mặt tiền nhà 6m", "mat-tien-nha-6m-fc"],
    ["Mặt Tiền Nhà 8m", "mặt tiền nhà 8m", "mat-tien-nha-8m-fc"],
    ["Mặt Tiền Biệt Thự", "mặt tiền biệt thự", "mat-tien-biet-thu-fc"],
    ["Mặt Tiền Nhà Vườn", "mặt tiền nhà vườn", "mat-tien-nha-vuon-fc"],
    ["Mặt Tiền Shop Nhà Phố", "mặt tiền shop nhà phố", "mat-tien-shop-nha-pho-fc"],
    ["Bảng Hiệu Kết Hợp Mặt Tiền", "bảng hiệu kết hợp mặt tiền", "bang-hieu-ket-hop-mat-tien-fc"],
    ["Ánh Sáng Trang Trí Mặt Tiền", "ánh sáng trang trí mặt tiền", "anh-sang-trang-tri-mat-tien-fc"],
    ["Led Viền Mặt Tiền", "led viền mặt tiền", "led-vien-mat-tien-fc"],
    ["Camera Cổng Nhà", "camera cổng nhà", "camera-cong-nha-fc"],
    ["Chuông Cổng Có Hình", "chuông cổng có hình", "chuong-cong-co-hinh-fc"],
    ["Khóa Cổng Vân Tay", "khóa cổng vân tay", "khoa-cong-van-tay-fc"],
    ["Motor Cổng Lùa", "motor cổng lùa", "motor-cong-lua-fc"],
    ["Motor Cổng Mở Quay", "motor cổng mở quay", "motor-cong-mo-quay-fc"],
    ["Nghiệm Thu Ngoại Thất", "nghiệm thu ngoại thất", "nghiem-thu-ngoai-that-fc"],
    ["Bảo Dưỡng Ngoại Thất", "bảo dưỡng ngoại thất", "bao-duong-ngoai-that-fc"],
    ["Bảo Hành Mặt Tiền", "bảo hành mặt tiền", "bao-hanh-mat-tien-fc"],
    ["Checklist Ngoại Thất Nhà", "checklist ngoại thất nhà", "checklist-ngoai-that-nha-fc"],
    ["Lỗi Thường Gặp Mặt Tiền", "lỗi thường gặp mặt tiền", "loi-thuong-gap-mat-tien-fc"],
    ["Cách Chọn Vật Liệu Mặt Tiền", "cách chọn vật liệu mặt tiền", "cach-chon-vat-lieu-mat-tien-fc"],
    ["Cách Chọn Cổng Rào", "cách chọn cổng rào", "cach-chon-cong-rao-fc"],
    ["Cách Thiết Kế Sân Nhỏ", "cách thiết kế sân nhỏ", "cach-thiet-ke-san-nho-fc"],
  ]);

  // 41 — MEP: điện nước HVAC chi tiết
  const b41 = pairs([
    ["Hệ Thống Điện 1 Pha Nhà Phố", "hệ thống điện 1 pha nhà phố", "he-thong-dien-1-pha-mep"],
    ["Hệ Thống Điện 3 Pha Nhà Phố", "hệ thống điện 3 pha nhà phố", "he-thong-dien-3-pha-mep"],
    ["Tủ Điện Tổng Nhà Phố", "tủ điện tổng nhà phố", "tu-dien-tong-nha-pho-mep"],
    ["Tủ Điện Tầng", "tủ điện tầng", "tu-dien-tang-mep"],
    ["Aptomat Chống Giật", "aptomat chống giật", "aptomat-chong-giat-mep"],
    ["Aptomat Chống Sét", "aptomat chống sét", "aptomat-chong-set-mep"],
    ["Tiếp Địa Nhà Phố", "tiếp địa nhà phố", "tiep-dia-nha-pho-mep"],
    ["Chống Sét Nhà Phố", "chống sét nhà phố", "chong-set-nha-pho-mep"],
    ["Ống Ruột Gà Điện", "ống ruột gà điện", "ong-ruot-ga-dien-mep"],
    ["Ống PVC Đi Dây Điện", "ống pvc đi dây điện", "ong-pvc-di-day-dien-mep"],
    ["Dây Điện Âm Tường", "dây điện âm tường", "day-dien-am-tuong-mep"],
    ["Dây Điện Nổi", "dây điện nổi", "day-dien-noi-mep"],
    ["Ổ Cắm Âm Tường", "ổ cắm âm tường", "o-cam-am-tuong-mep"],
    ["Ổ Cắm USB Nhà Phố", "ổ cắm usb nhà phố", "o-cam-usb-nha-pho-mep"],
    ["Công Tắc Đôi", "công tắc đôi", "cong-tac-doi-mep"],
    ["Công Tắc Ba", "công tắc ba", "cong-tac-ba-mep"],
    ["Công Tắc Cảm Ứng Hiện Diện", "công tắc cảm ứng hiện diện", "cong-tac-cam-ung-hien-dien-mep"],
    ["Đèn Cảm Biến Chuyển Động", "đèn cảm biến chuyển động", "den-cam-bien-chuyen-dong-mep"],
    ["Đèn Khẩn Cấp Nhà", "đèn khẩn cấp nhà", "den-khan-cap-nha-mep"],
    ["Hệ Thống Chiếu Sáng Ngoài Trời", "hệ thống chiếu sáng ngoài trời", "he-thong-chieu-sang-ngoai-troi-mep"],
    ["Bơm Tăng Áp Nhà Phố", "bơm tăng áp nhà phố", "bom-tang-ap-nha-pho-mep"],
    ["Bơm Hút Giếng", "bơm hút giếng", "bom-hut-gieng-mep"],
    ["Bồn Nước Inox 500L", "bồn nước inox 500l", "bon-nuoc-inox-500l-mep"],
    ["Bồn Nước Inox 1000L", "bồn nước inox 1000l", "bon-nuoc-inox-1000l-mep"],
    ["Bồn Nước Nhựa Composite", "bồn nước nhựa composite", "bon-nuoc-nhua-composite-mep"],
    ["Ống PPR Cấp Nước", "ống ppr cấp nước", "ong-ppr-cap-nuoc-mep"],
    ["Ống HDPE Cấp Nước", "ống hdpe cấp nước", "ong-hdpe-cap-nuoc-mep"],
    ["Ống uPVC Thoát Nước", "ống upvc thoát nước", "ong-upvc-thoat-nuoc-mep"],
    ["Ống Thoát Nước Mưa", "ống thoát nước mưa", "ong-thoat-nuoc-mua-mep"],
    ["Hố Ga Nhà Phố", "hố ga nhà phố", "ho-ga-nha-pho-mep"],
    ["Bể Tự Hoại 3 Ngăn", "bể tự hoại 3 ngăn", "be-tu-hoai-3-ngan-mep"],
    ["Bể Tự Hoại Composite", "bể tự hoại composite", "be-tu-hoai-composite-mep"],
    ["Van Một Chiều Nước", "van một chiều nước", "van-mot-chieu-nuoc-mep"],
    ["Van Giảm Áp", "van giảm áp", "van-giam-ap-mep"],
    ["Lọc Nước Đầu Nguồn", "lọc nước đầu nguồn", "loc-nuoc-dau-nguon-mep"],
    ["Máy Lọc Nước RO Gia Đình", "máy lọc nước ro gia đình", "may-loc-nuoc-ro-gia-dinh-mep"],
    ["Máy Nước Nóng Trung Tâm", "máy nước nóng trung tâm", "may-nuoc-nong-trung-tam-mep"],
    ["Máy Nước Nóng Trực Tiếp", "máy nước nóng trực tiếp", "may-nuoc-nong-truc-tiep-mep"],
    ["Máy Nước Nóng Gián Tiếp", "máy nước nóng gián tiếp", "may-nuoc-nong-gian-tiep-mep"],
    ["Hệ Thống Máy Lạnh Multi", "hệ thống máy lạnh multi", "he-thong-may-lanh-multi-mep"],
    ["Máy Lạnh Âm Trần", "máy lạnh âm trần", "may-lanh-am-tran-mep"],
    ["Máy Lạnh Tủ Đứng", "máy lạnh tủ đứng", "may-lanh-tu-dung-mep"],
    ["Ống Đồng Máy Lạnh", "ống đồng máy lạnh", "ong-dong-may-lanh-mep"],
    ["Ống Thoát Nước Condensate", "ống thoát nước condensate", "ong-thoat-nuoc-condensate-mep"],
    ["Giàn Nóng Máy Lạnh Vị Trí", "giàn nóng máy lạnh vị trí", "gian-nong-may-lanh-vi-tri-mep"],
    ["Thông Gió Cơ Khí Nhà", "thông gió cơ khí nhà", "thong-gio-co-khi-nha-mep"],
    ["Quạt Hút Trần", "quạt hút trần", "quat-hut-tran-mep"],
    ["Quạt Hút Tường", "quạt hút tường", "quat-hut-tuong-mep"],
    ["Ống Gió Nhựa", "ống gió nhựa", "ong-gio-nhua-mep"],
    ["Ống Gió Tôn Mạ", "ống gió tôn mạ", "ong-gio-ton-ma-mep"],
    ["Hệ Thống Internet Nhà", "hệ thống internet nhà", "he-thong-internet-nha-mep"],
    ["Mạng LAN Nhà Phố", "mạng lan nhà phố", "mang-lan-nha-pho-mep"],
    ["Wifi Mesh Nhà Phố", "wifi mesh nhà phố", "wifi-mesh-nha-pho-mep"],
    ["Tủ Rack Nhà Phố", "tủ rack nhà phố", "tu-rack-nha-pho-mep"],
    ["Hệ Thống Camera IP", "hệ thống camera ip", "he-thong-camera-ip-mep"],
    ["Đầu Ghi Hình NVR", "đầu ghi hình nvr", "dau-ghi-hinh-nvr-mep"],
    ["Chuông Cửa Video", "chuông cửa video", "chuong-cua-video-mep"],
    ["Intercom Nhà Phố", "intercom nhà phố", "intercom-nha-pho-mep"],
    ["Hệ Thống Âm Thanh Nhà", "hệ thống âm thanh nhà", "he-thong-am-thanh-nha-mep"],
    ["Loa Âm Trần", "loa âm trần", "loa-am-tran-mep"],
    ["TV Outlet Nhà Phố", "tv outlet nhà phố", "tv-outlet-nha-pho-mep"],
    ["Điểm Mạng Mỗi Phòng", "điểm mạng mỗi phòng", "diem-mang-moi-phong-mep"],
    ["Báo Giá Hệ Điện Nhà Phố", "báo giá hệ điện nhà phố", "bao-gia-he-dien-nha-pho-mep"],
    ["Báo Giá Hệ Nước Nhà Phố", "báo giá hệ nước nhà phố", "bao-gia-he-nuoc-nha-pho-mep"],
    ["Báo Giá Máy Lạnh Nhà Phố", "báo giá máy lạnh nhà phố", "bao-gia-may-lanh-nha-pho-mep"],
    ["Báo Giá Thông Gió Nhà", "báo giá thông gió nhà", "bao-gia-thong-gio-nha-mep"],
    ["Chi Phí Đi Điện Âm", "chi phí đi điện âm", "chi-phi-di-dien-am-mep"],
    ["Chi Phí Đi Nước Âm", "chi phí đi nước âm", "chi-phi-di-nuoc-am-mep"],
    ["Quy Trình Thi Công Điện", "quy trình thi công điện", "quy-trinh-thi-cong-dien-mep"],
    ["Quy Trình Thi Công Nước", "quy trình thi công nước", "quy-trinh-thi-cong-nuoc-mep"],
    ["Nghiệm Thu Hệ Điện", "nghiệm thu hệ điện", "nghiem-thu-he-dien-mep"],
    ["Nghiệm Thu Hệ Nước", "nghiệm thu hệ nước", "nghiem-thu-he-nuoc-mep"],
    ["Nghiệm Thu Máy Lạnh", "nghiệm thu máy lạnh", "nghiem-thu-may-lanh-mep"],
    ["Bảo Trì Hệ Điện Nhà", "bảo trì hệ điện nhà", "bao-tri-he-dien-nha-mep"],
    ["Bảo Trì Hệ Nước Nhà", "bảo trì hệ nước nhà", "bao-tri-he-nuoc-nha-mep"],
    ["Bảo Trì Máy Lạnh Định Kỳ", "bảo trì máy lạnh định kỳ", "bao-tri-may-lanh-dinh-ky-mep"],
    ["Sửa Chữa Điện Nhà", "sửa chữa điện nhà", "sua-chua-dien-nha-mep"],
    ["Sửa Chữa Nước Nhà", "sửa chữa nước nhà", "sua-chua-nuoc-nha-mep"],
    ["Thay Thế Ống Nước Cũ", "thay thế ống nước cũ", "thay-the-ong-nuoc-cu-mep"],
    ["Thay Thế Dây Điện Cũ", "thay thế dây điện cũ", "thay-the-day-dien-cu-mep"],
    ["Nâng Cấp Tủ Điện", "nâng cấp tủ điện", "nang-cap-tu-dien-mep"],
    ["Nâng Cấp Bơm Nước", "nâng cấp bơm nước", "nang-cap-bom-nuoc-mep"],
    ["Checklist MEP Trước Đổ Trần", "checklist mep trước đổ trần", "checklist-mep-truoc-do-tran"],
    ["Checklist MEP Trước Sơn", "checklist mep trước sơn", "checklist-mep-truoc-son"],
    ["Lỗi Thường Gặp Hệ Điện", "lỗi thường gặp hệ điện", "loi-thuong-gap-he-dien-mep"],
    ["Lỗi Thường Gặp Hệ Nước", "lỗi thường gặp hệ nước", "loi-thuong-gap-he-nuoc-mep"],
    ["Lỗi Thường Gặp Máy Lạnh", "lỗi thường gặp máy lạnh", "loi-thuong-gap-may-lanh-mep"],
    ["Tiết Kiệm Điện Nhà Phố", "tiết kiệm điện nhà phố", "tiet-kiem-dien-nha-pho-mep"],
    ["Tiết Kiệm Nước Nhà Phố", "tiết kiệm nước nhà phố", "tiet-kiem-nuoc-nha-pho-mep"],
    ["Đồng Hồ Điện Thông Minh", "đồng hồ điện thông minh", "dong-ho-dien-thong-minh-mep"],
    ["Đồng Hồ Nước Thông Minh", "đồng hồ nước thông minh", "dong-ho-nuoc-thong-minh-mep"],
    ["UPS Gia Đình", "ups gia đình", "ups-gia-dinh-mep"],
    ["Máy Phát Điện Gia Đình", "máy phát điện gia đình", "may-phat-dien-gia-dinh-mep"],
    ["Inverter Hybrid Nhà", "inverter hybrid nhà", "inverter-hybrid-nha-mep"],
    ["Tích Hợp Smart Home MEP", "tích hợp smart home mep", "tich-hop-smart-home-mep"],
    ["Bản Vẽ Điện Nhà Phố", "bản vẽ điện nhà phố", "ban-ve-dien-nha-pho-mep"],
    ["Bản Vẽ Nước Nhà Phố", "bản vẽ nước nhà phố", "ban-ve-nuoc-nha-pho-mep"],
    ["Bản Vẽ Điều Hòa Nhà", "bản vẽ điều hòa nhà", "ban-ve-dieu-hoa-nha-mep"],
  ]);

  // 42 — geo ĐBSCL / tỉnh cụ thể sâu hơn
  const b42 = pairs([
    ["Xây Nhà Châu Thành TG", "xây nhà Châu Thành Tiền Giang", "xay-nha-chau-thanh-tg-mk"],
    ["Xây Nhà Chợ Gạo", "xây nhà Chợ Gạo", "xay-nha-cho-gao-mk"],
    ["Xây Nhà Tân Phước TG", "xây nhà Tân Phước", "xay-nha-tan-phuoc-tg-mk"],
    ["Xây Nhà Gò Công Tây", "xây nhà Gò Công Tây", "xay-nha-go-cong-tay-mk"],
    ["Xây Nhà Gò Công Đông", "xây nhà Gò Công Đông", "xay-nha-go-cong-dong-mk"],
    ["Xây Nhà Châu Thành BT", "xây nhà Châu Thành Bến Tre", "xay-nha-chau-thanh-bt-mk"],
    ["Xây Nhà Chợ Lách", "xây nhà Chợ Lách", "xay-nha-cho-lach-mk"],
    ["Xây Nhà Mỏ Cày Nam", "xây nhà Mỏ Cày Nam", "xay-nha-mo-cay-nam-mk"],
    ["Xây Nhà Mỏ Cày Bắc", "xây nhà Mỏ Cày Bắc", "xay-nha-mo-cay-bac-mk"],
    ["Xây Nhà Giồng Trôm", "xây nhà Giồng Trôm", "xay-nha-giong-trom-mk"],
    ["Xây Nhà Ba Tri", "xây nhà Ba Tri", "xay-nha-ba-tri-mk"],
    ["Xây Nhà Bình Đại", "xây nhà Bình Đại", "xay-nha-binh-dai-mk"],
    ["Xây Nhà Thạnh Phú BT", "xây nhà Thạnh Phú Bến Tre", "xay-nha-thanh-phu-bt-mk"],
    ["Xây Nhà Trà Ôn", "xây nhà Trà Ôn", "xay-nha-tra-on-mk"],
    ["Xây Nhà Vũng Liêm", "xây nhà Vũng Liêm", "xay-nha-vung-liem-mk"],
    ["Xây Nhà Mang Thít", "xây nhà Mang Thít", "xay-nha-mang-thit-mk"],
    ["Xây Nhà Long Hồ", "xây nhà Long Hồ", "xay-nha-long-ho-mk"],
    ["Xây Nhà Tam Bình", "xây nhà Tam Bình", "xay-nha-tam-binh-mk"],
    ["Xây Nhà Bình Minh VL", "xây nhà Bình Minh Vĩnh Long", "xay-nha-binh-minh-vl-mk"],
    ["Xây Nhà Càng Long", "xây nhà Càng Long", "xay-nha-cang-long-mk"],
    ["Xây Nhà Cầu Kè", "xây nhà Cầu Kè", "xay-nha-cau-ke-mk"],
    ["Xây Nhà Tiểu Cần", "xây nhà Tiểu Cần", "xay-nha-tieu-can-mk"],
    ["Xây Nhà Châu Thành TV", "xây nhà Châu Thành Trà Vinh", "xay-nha-chau-thanh-tv-mk"],
    ["Xây Nhà Cầu Ngang", "xây nhà Cầu Ngang", "xay-nha-cau-ngang-mk"],
    ["Xây Nhà Trà Cú", "xây nhà Trà Cú", "xay-nha-tra-cu-mk"],
    ["Xây Nhà Duyên Hải", "xây nhà Duyên Hải", "xay-nha-duyen-hai-mk"],
    ["Xây Nhà Lai Vung", "xây nhà Lai Vung", "xay-nha-lai-vung-mk"],
    ["Xây Nhà Lấp Vò", "xây nhà Lấp Vò", "xay-nha-lap-vo-mk"],
    ["Xây Nhà Thanh Bình ĐT", "xây nhà Thanh Bình Đồng Tháp", "xay-nha-thanh-binh-dt-mk"],
    ["Xây Nhà Tân Hồng", "xây nhà Tân Hồng", "xay-nha-tan-hong-mk"],
    ["Xây Nhà Hồng Ngự", "xây nhà Hồng Ngự", "xay-nha-hong-ngu-mk"],
    ["Xây Nhà Tam Nông ĐT", "xây nhà Tam Nông Đồng Tháp", "xay-nha-tam-nong-dt-mk"],
    ["Xây Nhà Tháp Mười", "xây nhà Tháp Mười", "xay-nha-thap-muoi-mk"],
    ["Xây Nhà Châu Thành AG", "xây nhà Châu Thành An Giang", "xay-nha-chau-thanh-ag-mk"],
    ["Xây Nhà Chợ Mới AG", "xây nhà Chợ Mới An Giang", "xay-nha-cho-moi-ag-mk"],
    ["Xây Nhà Thoại Sơn", "xây nhà Thoại Sơn", "xay-nha-thoai-son-mk"],
    ["Xây Nhà Tri Tôn", "xây nhà Tri Tôn", "xay-nha-tri-ton-mk"],
    ["Xây Nhà Tịnh Biên", "xây nhà Tịnh Biên", "xay-nha-tinh-bien-mk"],
    ["Xây Nhà An Phú AG", "xây nhà An Phú An Giang", "xay-nha-an-phu-ag-mk"],
    ["Xây Nhà Phú Tân AG", "xây nhà Phú Tân An Giang", "xay-nha-phu-tan-ag-mk"],
    ["Xây Nhà Tân Hiệp KG", "xây nhà Tân Hiệp Kiên Giang", "xay-nha-tan-hiep-kg-mk"],
    ["Xây Nhà Châu Thành KG", "xây nhà Châu Thành Kiên Giang", "xay-nha-chau-thanh-kg-mk"],
    ["Xây Nhà Giồng Riềng", "xây nhà Giồng Riềng", "xay-nha-giong-rieng-mk"],
    ["Xây Nhà Gò Quao", "xây nhà Gò Quao", "xay-nha-go-quao-mk"],
    ["Xây Nhà An Biên", "xây nhà An Biên", "xay-nha-an-bien-mk"],
    ["Xây Nhà An Minh", "xây nhà An Minh", "xay-nha-an-minh-mk"],
    ["Xây Nhà Vĩnh Thuận", "xây nhà Vĩnh Thuận", "xay-nha-vinh-thuan-mk"],
    ["Xây Nhà Phú Quốc", "xây nhà Phú Quốc", "xay-nha-phu-quoc-mk"],
    ["Xây Nhà Hà Tiên KG", "xây nhà Hà Tiên Kiên Giang", "xay-nha-ha-tien-kg-mk"],
    ["Xây Nhà Kiên Lương", "xây nhà Kiên Lương", "xay-nha-kien-luong-mk"],
    ["Xây Nhà Hồng Dân", "xây nhà Hồng Dân", "xay-nha-hong-dan-mk"],
    ["Xây Nhà Phước Long BL", "xây nhà Phước Long Bạc Liêu", "xay-nha-phuoc-long-bl-mk"],
    ["Xây Nhà Vĩnh Lợi", "xây nhà Vĩnh Lợi", "xay-nha-vinh-loi-mk"],
    ["Xây Nhà Giá Rai", "xây nhà Giá Rai", "xay-nha-gia-rai-mk"],
    ["Xây Nhà Đông Hải BL", "xây nhà Đông Hải Bạc Liêu", "xay-nha-dong-hai-bl-mk"],
    ["Xây Nhà Hòa Bình BL", "xây nhà Hòa Bình Bạc Liêu", "xay-nha-hoa-binh-bl-mk"],
    ["Xây Nhà Trần Đề", "xây nhà Trần Đề", "xay-nha-tran-de-mk"],
    ["Xây Nhà Mỹ Xuyên", "xây nhà Mỹ Xuyên", "xay-nha-my-xuyen-mk"],
    ["Xây Nhà Long Phú", "xây nhà Long Phú", "xay-nha-long-phu-mk"],
    ["Xây Nhà Thạnh Trị", "xây nhà Thạnh Trị", "xay-nha-thanh-tri-st-mk"],
    ["Xây Nhà Châu Thành ST", "xây nhà Châu Thành Sóc Trăng", "xay-nha-chau-thanh-st-mk"],
    ["Xây Nhà Kế Sách", "xây nhà Kế Sách", "xay-nha-ke-sach-mk"],
    ["Xây Nhà Mỹ Tú", "xây nhà Mỹ Tú", "xay-nha-my-tu-mk"],
    ["Xây Nhà Ngã Năm", "xây nhà Ngã Năm", "xay-nha-nga-nam-mk"],
    ["Xây Nhà Vĩnh Châu", "xây nhà Vĩnh Châu", "xay-nha-vinh-chau-mk"],
    ["Xây Nhà U Minh", "xây nhà U Minh", "xay-nha-u-minh-mk"],
    ["Xây Nhà Thới Bình", "xây nhà Thới Bình", "xay-nha-thoi-binh-mk"],
    ["Xây Nhà Trần Văn Thời", "xây nhà Trần Văn Thời", "xay-nha-tran-van-thoi-mk"],
    ["Xây Nhà Cái Nước", "xây nhà Cái Nước", "xay-nha-cai-nuoc-mk"],
    ["Xây Nhà Đầm Dơi", "xây nhà Đầm Dơi", "xay-nha-dam-doi-mk"],
    ["Xây Nhà Năm Căn", "xây nhà Năm Căn", "xay-nha-nam-can-mk"],
    ["Xây Nhà Ngọc Hiển", "xây nhà Ngọc Hiển", "xay-nha-ngoc-hien-mk"],
    ["Xây Nhà Phú Tân CM", "xây nhà Phú Tân Cà Mau", "xay-nha-phu-tan-cm-mk"],
    ["Cải Tạo Nhà Phú Quốc", "cải tạo nhà Phú Quốc", "cai-tao-nha-phu-quoc-mk"],
    ["Cải Tạo Nhà Châu Đốc AG", "cải tạo nhà Châu Đốc", "cai-tao-nha-chau-doc-ag-mk"],
    ["Cải Tạo Nhà Rạch Giá", "cải tạo nhà Rạch Giá", "cai-tao-nha-rach-gia-mk"],
    ["Cải Tạo Nhà Sa Đéc", "cải tạo nhà Sa Đéc", "cai-tao-nha-sa-dec-mk"],
    ["Thiết Kế Nhà Phú Quốc", "thiết kế nhà Phú Quốc", "thiet-ke-nha-phu-quoc-mk"],
    ["Thiết Kế Nhà Châu Đốc", "thiết kế nhà Châu Đốc", "thiet-ke-nha-chau-doc-mk"],
    ["Thiết Kế Nhà Rạch Giá", "thiết kế nhà Rạch Giá", "thiet-ke-nha-rach-gia-mk"],
    ["Báo Giá Xây Nhà Kiên Giang", "báo giá xây nhà Kiên Giang", "bao-gia-xay-nha-kien-giang-mk"],
    ["Báo Giá Xây Nhà An Giang", "báo giá xây nhà An Giang", "bao-gia-xay-nha-an-giang-mk"],
    ["Báo Giá Xây Nhà Đồng Tháp", "báo giá xây nhà Đồng Tháp", "bao-gia-xay-nha-dong-thap-mk"],
    ["Báo Giá Xây Nhà Vĩnh Long", "báo giá xây nhà Vĩnh Long", "bao-gia-xay-nha-vinh-long-mk"],
    ["Báo Giá Xây Nhà Bến Tre", "báo giá xây nhà Bến Tre", "bao-gia-xay-nha-ben-tre-mk"],
    ["Báo Giá Xây Nhà Trà Vinh", "báo giá xây nhà Trà Vinh", "bao-gia-xay-nha-tra-vinh-mk"],
    ["Báo Giá Xây Nhà Sóc Trăng", "báo giá xây nhà Sóc Trăng", "bao-gia-xay-nha-soc-trang-mk"],
    ["Báo Giá Xây Nhà Bạc Liêu", "báo giá xây nhà Bạc Liêu", "bao-gia-xay-nha-bac-lieu-mk"],
    ["Báo Giá Xây Nhà Cà Mau", "báo giá xây nhà Cà Mau", "bao-gia-xay-nha-ca-mau-mk"],
    ["Nhà Thầu Kiên Giang", "nhà thầu Kiên Giang", "nha-thau-kien-giang-mk"],
    ["Nhà Thầu An Giang", "nhà thầu An Giang", "nha-thau-an-giang-mk"],
    ["Nhà Thầu Đồng Tháp", "nhà thầu Đồng Tháp", "nha-thau-dong-thap-mk"],
    ["Nhà Thầu Phú Quốc", "nhà thầu Phú Quốc", "nha-thau-phu-quoc-mk"],
    ["Xây Nhà Ven Sông ĐBSCL", "xây nhà ven sông ĐBSCL", "xay-nha-ven-song-dbscl-mk"],
    ["Xây Nhà Chống Lún ĐBSCL", "xây nhà chống lún ĐBSCL", "xay-nha-chong-lun-dbscl-mk"],
    ["Xây Nhà Chống Ngập ĐBSCL", "xây nhà chống ngập ĐBSCL", "xay-nha-chong-ngap-dbscl-mk"],
    ["Xây Nhà Trên Đất Yếu", "xây nhà trên đất yếu", "xay-nha-tren-dat-yeu-mk"],
    ["Xây Nhà Gần Biển Cà Mau", "xây nhà gần biển Cà Mau", "xay-nha-gan-bien-ca-mau-mk"],
    ["Xây Biệt Thự Phú Quốc", "xây biệt thự Phú Quốc", "xay-biet-thu-phu-quoc-mk"],
    ["Xây Homestay Phú Quốc", "xây homestay Phú Quốc", "xay-homestay-phu-quoc-mk"],
    ["Xây Nhà Vườn Miền Tây", "xây nhà vườn miền Tây", "xay-nha-vuon-mien-tay-mk"],
  ]);

  // 43 — cải tạo theo phòng / sự cố cụ thể
  const b43 = pairs([
    ["Cải Tạo Phòng Khách Cũ", "cải tạo phòng khách cũ", "cai-tao-phong-khach-cu-ct2"],
    ["Cải Tạo Phòng Ngủ Cũ", "cải tạo phòng ngủ cũ", "cai-tao-phong-ngu-cu-ct2"],
    ["Cải Tạo Phòng Bếp Cũ", "cải tạo phòng bếp cũ", "cai-tao-phong-bep-cu-ct2"],
    ["Cải Tạo Phòng WC Cũ", "cải tạo phòng wc cũ", "cai-tao-phong-wc-cu-ct2"],
    ["Cải Tạo Phòng Thờ Cũ", "cải tạo phòng thờ cũ", "cai-tao-phong-tho-cu-ct2"],
    ["Cải Tạo Gác Lửng Cũ", "cải tạo gác lửng cũ", "cai-tao-gac-lung-cu-ct2"],
    ["Cải Tạo Sân Thượng Cũ", "cải tạo sân thượng cũ", "cai-tao-san-thuong-cu-ct2"],
    ["Cải Tạo Ban Công Cũ", "cải tạo ban công cũ", "cai-tao-ban-cong-cu-ct2"],
    ["Cải Tạo Cầu Thang Cũ", "cải tạo cầu thang cũ", "cai-tao-cau-thang-cu-ct2"],
    ["Cải Tạo Hành Lang Cũ", "cải tạo hành lang cũ", "cai-tao-hanh-lang-cu-ct2"],
    ["Cải Tạo Tầng Trệt", "cải tạo tầng trệt", "cai-tao-tang-tret-ct2"],
    ["Cải Tạo Tầng Lầu", "cải tạo tầng lầu", "cai-tao-tang-lau-ct2"],
    ["Cải Tạo Tầng Hầm", "cải tạo tầng hầm", "cai-tao-tang-ham-ct2"],
    ["Cải Tạo Mái Nhà Cũ", "cải tạo mái nhà cũ", "cai-tao-mai-nha-cu-ct2"],
    ["Cải Tạo Móng Nhà Cũ", "cải tạo móng nhà cũ", "cai-tao-mong-nha-cu-ct2"],
    ["Sửa Trần Thấm Dột", "sửa trần thấm dột", "sua-tran-tham-dot-ct2"],
    ["Sửa Tường Thấm Ẩm", "sửa tường thấm ẩm", "sua-tuong-tham-am-ct2"],
    ["Sửa Sàn Phồng Rộp", "sửa sàn phồng rộp", "sua-san-phong-rop-ct2"],
    ["Sửa Gạch Bong Tróc", "sửa gạch bong tróc", "sua-gach-bong-troc-ct2"],
    ["Sửa Sơn Bong Tróc", "sửa sơn bong tróc", "sua-son-bong-troc-ct2"],
    ["Sửa Cửa Cong Vênh", "sửa cửa cong vênh", "sua-cua-cong-venh-ct2"],
    ["Sửa Cửa Kẹt", "sửa cửa kẹt", "sua-cua-ket-ct2"],
    ["Sửa Lan Can Rỉ Sét", "sửa lan can rỉ sét", "sua-lan-can-ri-set-ct2"],
    ["Sửa Mái Tôn Dột", "sửa mái tôn dột", "sua-mai-ton-dot-ct2"],
    ["Sửa Mái Ngói Vỡ", "sửa mái ngói vỡ", "sua-mai-ngoi-vo-ct2"],
    ["Sửa Ống Nước Rò", "sửa ống nước rò", "sua-ong-nuoc-ro-ct2"],
    ["Sửa Ống Nước Tắc", "sửa ống nước tắc", "sua-ong-nuoc-tac-ct2"],
    ["Sửa Điện Chập", "sửa điện chập", "sua-dien-chap-ct2"],
    ["Sửa Điện Yếu", "sửa điện yếu", "sua-dien-yeu-ct2"],
    ["Sửa Bồn Cầu Tắc", "sửa bồn cầu tắc", "sua-bon-cau-tac-ct2"],
    ["Sửa Sen Tắm Yếu", "sửa sen tắm yếu", "sua-sen-tam-yeu-ct2"],
    ["Sửa Máy Lạnh Không Mát", "sửa máy lạnh không mát", "sua-may-lanh-khong-mat-ct2"],
    ["Xử Lý Mốc Tường", "xử lý mốc tường", "xu-ly-moc-tuong-ct2"],
    ["Xử Lý Muối Hóa Tường", "xử lý muối hóa tường", "xu-ly-muoi-hoa-tuong-ct2"],
    ["Xử Lý Nứt Tường Nhỏ", "xử lý nứt tường nhỏ", "xu-ly-nut-tuong-nho-ct2"],
    ["Xử Lý Nứt Tường Lớn", "xử lý nứt tường lớn", "xu-ly-nut-tuong-lon-ct2"],
    ["Xử Lý Lún Nền", "xử lý lún nền", "xu-ly-lun-nen-ct2"],
    ["Xử Lý Nhà Nghiêng Nhẹ", "xử lý nhà nghiêng nhẹ", "xu-ly-nha-nghieng-nhe-ct2"],
    ["Gia Cố Cột Nhà Cũ", "gia cố cột nhà cũ", "gia-co-cot-nha-cu-ct2"],
    ["Gia Cố Dầm Nhà Cũ", "gia cố dầm nhà cũ", "gia-co-dam-nha-cu-ct2"],
    ["Gia Cố Sàn Nhà Cũ", "gia cố sàn nhà cũ", "gia-co-san-nha-cu-ct2"],
    ["Gia Cố Móng Nhà Cũ", "gia cố móng nhà cũ", "gia-co-mong-nha-cu-ct2"],
    ["Nâng Tầng Nhà Cũ An Toàn", "nâng tầng nhà cũ an toàn", "nang-tang-nha-cu-an-toan-ct2"],
    ["Mở Rộng Nhà Sang Bên", "mở rộng nhà sang bên", "mo-rong-nha-sang-ben-ct2"],
    ["Mở Rộng Nhà Ra Sau", "mở rộng nhà ra sau", "mo-rong-nha-ra-sau-ct2"],
    ["Gộp Hai Căn Nhà", "gộp hai căn nhà", "gop-hai-can-nha-ct2"],
    ["Tách Một Căn Thành Hai", "tách một căn thành hai", "tach-mot-can-thanh-hai-ct2"],
    ["Đổi Layout Nhà Ống", "đổi layout nhà ống", "doi-layout-nha-ong-ct2"],
    ["Thêm Giếng Trời Cải Tạo", "thêm giếng trời cải tạo", "them-gieng-troi-cai-tao-ct2"],
    ["Thêm Ban Công Cải Tạo", "thêm ban công cải tạo", "them-ban-cong-cai-tao-ct2"],
    ["Thêm Phòng Ngủ Cải Tạo", "thêm phòng ngủ cải tạo", "them-phong-ngu-cai-tao-ct2"],
    ["Thêm WC Cải Tạo", "thêm wc cải tạo", "them-wc-cai-tao-ct2"],
    ["Dời Cầu Thang Cải Tạo", "dời cầu thang cải tạo", "doi-cau-thang-cai-tao-ct2"],
    ["Dời Bếp Cải Tạo", "dời bếp cải tạo", "doi-bep-cai-tao-ct2"],
    ["Dời WC Cải Tạo", "dời wc cải tạo", "doi-wc-cai-tao-ct2"],
    ["Phá Vách Ngăn Cải Tạo", "phá vách ngăn cải tạo", "pha-vach-ngan-cai-tao-ct2"],
    ["Xây Vách Ngăn Mới", "xây vách ngăn mới", "xay-vach-ngan-moi-ct2"],
    ["Thay Sàn Gạch Mới", "thay sàn gạch mới", "thay-san-gach-moi-ct2"],
    ["Thay Sàn Gỗ Mới", "thay sàn gỗ mới", "thay-san-go-moi-ct2"],
    ["Thay Trần Thạch Cao Mới", "thay trần thạch cao mới", "thay-tran-thach-cao-moi-ct2"],
    ["Thay Cửa Nhôm Mới", "thay cửa nhôm mới", "thay-cua-nhom-moi-ct2"],
    ["Thay Cửa Gỗ Mới", "thay cửa gỗ mới", "thay-cua-go-moi-ct2"],
    ["Sơn Lại Toàn Bộ Nhà", "sơn lại toàn bộ nhà", "son-lai-toan-bo-nha-ct2"],
    ["Ốp Lát Lại Toàn Bộ", "ốp lát lại toàn bộ", "op-lat-lai-toan-bo-ct2"],
    ["Cải Tạo Tiết Kiệm 50 Triệu", "cải tạo tiết kiệm 50 triệu", "cai-tao-tiet-kiem-50-trieu-ct2"],
    ["Cải Tạo Tiết Kiệm 100 Triệu", "cải tạo tiết kiệm 100 triệu", "cai-tao-tiet-kiem-100-trieu-ct2"],
    ["Cải Tạo Ngân Sách 200 Triệu", "cải tạo ngân sách 200 triệu", "cai-tao-ngan-sach-200-trieu-ct2"],
    ["Cải Tạo Ngân Sách 500 Triệu", "cải tạo ngân sách 500 triệu", "cai-tao-ngan-sach-500-trieu-ct2"],
    ["Cải Tạo Ngân Sách 1 Tỷ", "cải tạo ngân sách 1 tỷ", "cai-tao-ngan-sach-1-ty-ct2"],
    ["Cải Tạo Nhanh 15 Ngày", "cải tạo nhanh 15 ngày", "cai-tao-nhanh-15-ngay-ct2"],
    ["Cải Tạo Nhanh 30 Ngày", "cải tạo nhanh 30 ngày", "cai-tao-nhanh-30-ngay-ct2"],
    ["Cải Tạo Vừa Ở Vừa Sửa", "cải tạo vừa ở vừa sửa", "cai-tao-vua-o-vua-sua-ct2"],
    ["Cải Tạo Không Phá Dỡ Nhiều", "cải tạo không phá dỡ nhiều", "cai-tao-khong-pha-do-nhieu-ct2"],
    ["Cải Tạo Giữ Kết Cấu Cũ", "cải tạo giữ kết cấu cũ", "cai-tao-giu-ket-cau-cu-ct2"],
    ["Báo Giá Cải Tạo Phòng Khách", "báo giá cải tạo phòng khách", "bao-gia-cai-tao-phong-khach-ct2"],
    ["Báo Giá Cải Tạo Phòng Ngủ", "báo giá cải tạo phòng ngủ", "bao-gia-cai-tao-phong-ngu-ct2"],
    ["Báo Giá Cải Tạo Bếp", "báo giá cải tạo bếp", "bao-gia-cai-tao-bep-ct2"],
    ["Báo Giá Cải Tạo WC", "báo giá cải tạo wc", "bao-gia-cai-tao-wc-ct2"],
    ["Báo Giá Cải Tạo Mái", "báo giá cải tạo mái", "bao-gia-cai-tao-mai-ct2"],
    ["Quy Trình Cải Tạo Nhà Cũ", "quy trình cải tạo nhà cũ", "quy-trinh-cai-tao-nha-cu-ct2"],
    ["Khảo Sát Trước Cải Tạo", "khảo sát trước cải tạo", "khao-sat-truoc-cai-tao-ct2"],
    ["Thiết Kế Trước Cải Tạo", "thiết kế trước cải tạo", "thiet-ke-truoc-cai-tao-ct2"],
    ["Nghiệm Thu Sau Cải Tạo", "nghiệm thu sau cải tạo", "nghiem-thu-sau-cai-tao-ct2"],
    ["Bảo Hành Cải Tạo Nhà", "bảo hành cải tạo nhà", "bao-hanh-cai-tao-nha-ct2"],
    ["Checklist Cải Tạo Nhà Cũ", "checklist cải tạo nhà cũ", "checklist-cai-tao-nha-cu-ct2"],
    ["Sai Lầm Khi Cải Tạo Nhà", "sai lầm khi cải tạo nhà", "sai-lam-khi-cai-tao-nha-ct2"],
    ["Nên Cải Tạo Hay Xây Mới 2026", "nên cải tạo hay xây mới 2026", "nen-cai-tao-hay-xay-moi-2026-ct2"],
    ["Cải Tạo Tăng Giá Trị Nhà", "cải tạo tăng giá trị nhà", "cai-tao-tang-gia-tri-nha-ct2"],
    ["Cải Tạo Để Bán Nhà", "cải tạo để bán nhà", "cai-tao-de-ban-nha-ct2"],
    ["Cải Tạo Để Cho Thuê", "cải tạo để cho thuê", "cai-tao-de-cho-thue-ct2"],
    ["Before After Cải Tạo Nhà", "before after cải tạo nhà", "before-after-cai-tao-nha-ct2"],
  ]);

  // 44 — so sánh sâu / năm / Ads conversion
  const b44 = pairs([
    ["Xây Nhà 2026 Hay Đợi 2027", "xây nhà 2026 hay đợi 2027", "xay-nha-2026-hay-doi-2027-ads2"],
    ["Giá Xây Nhà Quý 1 2026", "giá xây nhà quý 1 2026", "gia-xay-nha-quy-1-2026-ads2"],
    ["Giá Xây Nhà Quý 2 2026", "giá xây nhà quý 2 2026", "gia-xay-nha-quy-2-2026-ads2"],
    ["Giá Xây Nhà Quý 3 2026", "giá xây nhà quý 3 2026", "gia-xay-nha-quy-3-2026-ads2"],
    ["Giá Xây Nhà Quý 4 2026", "giá xây nhà quý 4 2026", "gia-xay-nha-quy-4-2026-ads2"],
    ["Dự Báo Giá VLXD 2026", "dự báo giá vlxd 2026", "du-bao-gia-vlxd-2026-ads2"],
    ["Dự Báo Giá Nhân Công 2026", "dự báo giá nhân công 2026", "du-bao-gia-nhan-cong-2026-ads2"],
    ["So Sánh Thầu A Và Thầu B", "so sánh thầu a và thầu b", "so-sanh-thau-a-va-thau-b-ads2"],
    ["So Sánh Gói Thô Và Trọn Gói", "so sánh gói thô và trọn gói", "so-sanh-goi-tho-va-tron-goi-ads2"],
    ["So Sánh Tự Xây Và Thuê Thầu", "so sánh tự xây và thuê thầu", "so-sanh-tu-xay-va-thue-thau-ads2"],
    ["So Sánh Thiết Kế Riêng Và Mẫu", "so sánh thiết kế riêng và mẫu", "so-sanh-thiet-ke-rieng-va-mau-ads2"],
    ["So Sánh Giám Sát Và Không", "so sánh có giám sát và không", "so-sanh-co-giam-sat-va-khong-ads2"],
    ["Top 5 Lỗi Chọn Thầu", "top 5 lỗi chọn thầu", "top-5-loi-chon-thau-ads2"],
    ["Top 5 Cách Tiết Kiệm Xây", "top 5 cách tiết kiệm xây", "top-5-cach-tiet-kiem-xay-ads2"],
    ["Top 5 Việc Làm Trước Xây", "top 5 việc làm trước xây", "top-5-viec-lam-truoc-xay-ads2"],
    ["Top 10 Câu Hỏi Xây Nhà", "top 10 câu hỏi xây nhà", "top-10-cau-hoi-xay-nha-ads2"],
    ["Top 10 Câu Hỏi Cải Tạo", "top 10 câu hỏi cải tạo", "top-10-cau-hoi-cai-tao-ads2"],
    ["Công Ty Xây Dựng Gần Tôi", "công ty xây dựng gần tôi", "cong-ty-xay-dung-gan-toi-ads2"],
    ["Nhà Thầu Gần Tôi", "nhà thầu gần tôi", "nha-thau-gan-toi-ads2"],
    ["Thợ Hồ Gần Tôi", "thợ hồ gần tôi", "tho-ho-gan-toi-ads2"],
    ["Kiến Trúc Sư Gần Tôi", "kiến trúc sư gần tôi", "kien-truc-su-gan-toi-ads2"],
    ["Báo Giá Xây Nhà Online", "báo giá xây nhà online", "bao-gia-xay-nha-online-ads2"],
    ["Báo Giá Cải Tạo Online", "báo giá cải tạo online", "bao-gia-cai-tao-online-ads2"],
    ["Tính Giá Xây Nhà Theo m2", "tính giá xây nhà theo m2", "tinh-gia-xay-nha-theo-m2-ads2"],
    ["Máy Tính Chi Phí Xây Nhà", "máy tính chi phí xây nhà", "may-tinh-chi-phi-xay-nha-ads2"],
    ["Form Đăng Ký Tư Vấn Xây", "form đăng ký tư vấn xây", "form-dang-ky-tu-van-xay-ads2"],
    ["Chat Zalo Tư Vấn Xây", "chat zalo tư vấn xây", "chat-zalo-tu-van-xay-ads2"],
    ["Gọi Hotline Xây Nhà", "gọi hotline xây nhà", "goi-hotline-xay-nha-ads2"],
    ["Đặt Lịch Hẹn Tư Vấn", "đặt lịch hẹn tư vấn", "dat-lich-hen-tu-van-ads2"],
    ["Khảo Sát Miễn Phí TPHCM", "khảo sát miễn phí tphcm", "khao-sat-mien-phi-tphcm-ads2"],
    ["Thiết Kế 3D Miễn Phí", "thiết kế 3d miễn phí", "thiet-ke-3d-mien-phi-ads2"],
    ["Phối Cảnh Miễn Phí", "phối cảnh miễn phí", "phoi-canh-mien-phi-ads2"],
    ["Báo Giá Trong 24 Giờ", "báo giá trong 24 giờ", "bao-gia-trong-24-gio-ads2"],
    ["Cam Kết Không Phát Sinh", "cam kết không phát sinh", "cam-ket-khong-phat-sinh-ads2"],
    ["Cam Kết Đúng Tiến Độ", "cam kết đúng tiến độ", "cam-ket-dung-tien-do-ads2"],
    ["Cam Kết Bảo Hành Dài", "cam kết bảo hành dài", "cam-ket-bao-hanh-dai-ads2"],
    ["Bảo Hành Kết Cấu 10 Năm", "bảo hành kết cấu 10 năm", "bao-hanh-ket-cau-10-nam-ads2"],
    ["Bảo Hành Thấm 5 Năm", "bảo hành thấm 5 năm", "bao-hanh-tham-5-nam-ads2"],
    ["Bảo Hành Hoàn Thiện 2 Năm", "bảo hành hoàn thiện 2 năm", "bao-hanh-hoan-thien-2-nam-ads2"],
    ["Gói Xây Nhà Economy", "gói xây nhà economy", "goi-xay-nha-economy-ads2"],
    ["Gói Xây Nhà Standard", "gói xây nhà standard", "goi-xay-nha-standard-ads2"],
    ["Gói Xây Nhà Premium", "gói xây nhà premium", "goi-xay-nha-premium-ads2"],
    ["Gói Xây Nhà Luxury Plus", "gói xây nhà luxury plus", "goi-xay-nha-luxury-plus-ads2"],
    ["Gói Cải Tạo Nhanh", "gói cải tạo nhanh", "goi-cai-tao-nhanh-ads2"],
    ["Gói Cải Tạo Toàn Diện", "gói cải tạo toàn diện", "goi-cai-tao-toan-dien-ads2"],
    ["Gói Cải Tạo Mặt Tiền", "gói cải tạo mặt tiền", "goi-cai-tao-mat-tien-ads2"],
    ["Gói Cải Tạo Nội Thất", "gói cải tạo nội thất", "goi-cai-tao-noi-that-ads2"],
    ["Combo Xây Và Nội Thất", "combo xây và nội thất", "combo-xay-va-noi-that-ads2"],
    ["Combo Thiết Kế Và Xây", "combo thiết kế và xây", "combo-thiet-ke-va-xay-ads2"],
    ["Flash Sale Xây Nhà", "flash sale xây nhà", "flash-sale-xay-nha-ads2"],
    ["Early Bird Xây Nhà", "early bird xây nhà", "early-bird-xay-nha-ads2"],
    ["Ưu Đãi Tháng Này Xây", "ưu đãi tháng này xây", "uu-dai-thang-nay-xay-ads2"],
    ["Giảm 5% Xây Trọn Gói", "giảm 5% xây trọn gói", "giam-5-phan-tram-xay-tron-goi-ads2"],
    ["Giảm 10% Cải Tạo", "giảm 10% cải tạo", "giam-10-phan-tram-cai-tao-ads2"],
    ["Tặng Bản Vẽ Khi Ký", "tặng bản vẽ khi ký", "tang-ban-ve-khi-ky-ads2"],
    ["Tặng Giám Sát Khi Ký", "tặng giám sát khi ký", "tang-giam-sat-khi-ky-ads2"],
    ["Review Thực Tế Sao Khuê", "review thực tế sao khuê", "review-thuc-te-sao-khue-ads2"],
    ["Khách Hàng Nói Gì Sao Khuê", "khách hàng nói gì sao khuê", "khach-hang-noi-gi-sao-khue-ads2"],
    ["Công Trình Mẫu Sao Khuê", "công trình mẫu sao khuê", "cong-trinh-mau-sao-khue-ads2"],
    ["Tham Quan Công Trình Sao Khuê", "tham quan công trình sao khuê", "tham-quan-cong-trinh-sao-khue-ads2"],
    ["Hình Ảnh Thi Công Thực Tế", "hình ảnh thi công thực tế", "hinh-anh-thi-cong-thuc-te-ads2"],
    ["Video Tiến Độ Công Trình", "video tiến độ công trình", "video-tien-do-cong-trinh-ads2"],
    ["Case Study Nhà Phố 3 Tầng", "case study nhà phố 3 tầng", "case-study-nha-pho-3-tang-ads2"],
    ["Case Study Cải Tạo Nhà Ống", "case study cải tạo nhà ống", "case-study-cai-tao-nha-ong-ads2"],
    ["Case Study Biệt Thự Mini", "case study biệt thự mini", "case-study-biet-thu-mini-ads2"],
    ["Why Choose Sao Khue", "why choose sao khuê", "why-choose-sao-khue-ads2"],
    ["Điểm Khác Biệt Sao Khuê", "điểm khác biệt sao khuê", "diem-khac-biet-sao-khue-ads2"],
    ["Quy Trình Làm Việc Sao Khuê", "quy trình làm việc sao khuê", "quy-trinh-lam-viec-sao-khue-ads2"],
    ["Đội Ngũ Sao Khuê", "đội ngũ sao khuê", "doi-ngu-sao-khue-ads2"],
    ["Chứng Nhận Sao Khuê", "chứng nhận sao khuê", "chung-nhan-sao-khue-ads2"],
    ["Liên Hệ Sao Khuê", "liên hệ sao khuê", "lien-he-sao-khue-ads2"],
    ["Địa Chỉ Văn Phòng Sao Khuê", "địa chỉ văn phòng sao khuê", "dia-chi-van-phong-sao-khue-ads2"],
    ["Fanpage Sao Khuê", "fanpage sao khuê", "fanpage-sao-khue-ads2"],
    ["Website Sao Khuê", "website sao khuê", "website-sao-khue-ads2"],
    ["Google Maps Sao Khuê", "google maps sao khuê", "google-maps-sao-khue-ads2"],
    ["Đánh Giá Google Sao Khuê", "đánh giá google sao khuê", "danh-gia-google-sao-khue-ads2"],
    ["Book Ngay Tư Vấn Xây", "book ngay tư vấn xây", "book-ngay-tu-van-xay-ads2"],
    ["Nhận Ưu Đãi Hôm Nay", "nhận ưu đãi hôm nay", "nhan-uu-dai-hom-nay-ads2"],
    ["Số Lượng Slot Tháng Này", "số lượng slot tháng này", "so-luong-slot-thang-nay-ads2"],
    ["Đăng Ký Giữ Chỗ Xây", "đăng ký giữ chỗ xây", "dang-ky-giu-cho-xay-ads2"],
    ["CTA Xây Nhà Ngay", "cta xây nhà ngay", "cta-xay-nha-ngay-ads2"],
    ["CTA Cải Tạo Ngay", "cta cải tạo ngay", "cta-cai-tao-ngay-ads2"],
    ["CTA Nhận Báo Giá", "cta nhận báo giá", "cta-nhan-bao-gia-ads2"],
    ["Landing Xây Nhà TPHCM", "landing xây nhà tphcm", "landing-xay-nha-tphcm-ads2"],
    ["Landing Cải Tạo TPHCM", "landing cải tạo tphcm", "landing-cai-tao-tphcm-ads2"],
    ["Landing Thiết Kế Nhà", "landing thiết kế nhà", "landing-thiet-ke-nha-ads2"],
    ["PPC Xây Nhà Keywords", "ppc xây nhà keywords", "ppc-xay-nha-keywords-ads2"],
    ["SEO Xây Nhà Local", "seo xây nhà local", "seo-xay-nha-local-ads2"],
    ["Lead Gen Xây Nhà", "lead gen xây nhà", "lead-gen-xay-nha-ads2"],
    ["Conversion Xây Nhà", "conversion xây nhà", "conversion-xay-nha-ads2"],
    ["Remarketing Xây Nhà", "remarketing xây nhà", "remarketing-xay-nha-ads2"],
    ["Retargeting Cải Tạo", "retargeting cải tạo", "retargeting-cai-tao-ads2"],
  ]);

  return [b40, b41, b42, b43, b44].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 3447 + (batch - 40) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    40: "Cluster: mặt tiền, ngoại thất, cảnh quan.",
    41: "Cluster: MEP điện nước HVAC chi tiết.",
    42: "Cluster: geo ĐBSCL huyện/thị xã.",
    43: "Cluster: cải tạo theo phòng và sự cố.",
    44: "Cluster: so sánh, quý năm 2026, Ads conversion.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: mặt tiền, ngoại thất, cảnh quan.",
  "Cluster: MEP điện nước HVAC chi tiết.",
  "Cluster: geo ĐBSCL huyện/thị xã.",
  "Cluster: cải tạo theo phòng và sự cố.",
  "Cluster: so sánh, quý năm 2026, Ads conversion.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 40 + i;
  const startNo = 3447 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 40 ? 39 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
