/**
 * Generator: short-keyword batches 35–39 (500 articles, #2947–#3446).
 * Run: npx tsx scripts/gen-short-keyword-batches-35-39.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${35 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${35 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${35 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 35 — nội thất phòng / hoàn thiện chi tiết
  const b35 = pairs([
    ["Thiết Kế Phòng Khách Nhà Phố", "thiết kế phòng khách nhà phố", "thiet-ke-phong-khach-nha-pho-nt"],
    ["Thiết Kế Phòng Ngủ Master", "thiết kế phòng ngủ master", "thiet-ke-phong-ngu-master-nt"],
    ["Thiết Kế Phòng Ngủ Nhỏ", "thiết kế phòng ngủ nhỏ", "thiet-ke-phong-ngu-nho-nt"],
    ["Thiết Kế Phòng Bếp Hiện Đại", "thiết kế phòng bếp hiện đại", "thiet-ke-phong-bep-hien-dai-nt"],
    ["Thiết Kế Phòng Ăn Nhà Phố", "thiết kế phòng ăn nhà phố", "thiet-ke-phong-an-nha-pho-nt"],
    ["Thiết Kế Phòng WC Hiện Đại", "thiết kế phòng wc hiện đại", "thiet-ke-phong-wc-hien-dai-nt"],
    ["Thiết Kế Phòng WC Khách", "thiết kế phòng wc khách", "thiet-ke-phong-wc-khach-nt"],
    ["Thiết Kế Phòng Giặt", "thiết kế phòng giặt", "thiet-ke-phong-giat-nt"],
    ["Thiết Kế Phòng Thờ Nhà Phố", "thiết kế phòng thờ nhà phố", "thiet-ke-phong-tho-nha-pho-nt"],
    ["Thiết Kế Phòng Kho", "thiết kế phòng kho", "thiet-ke-phong-kho-nt"],
    ["Thiết Kế Gác Lửng Nội Thất", "thiết kế gác lửng nội thất", "thiet-ke-gac-lung-noi-that-nt"],
    ["Thiết Kế Sân Thượng Nội Thất", "thiết kế sân thượng nội thất", "thiet-ke-san-thuong-noi-that-nt"],
    ["Thiết Kế Ban Công Nội Thất", "thiết kế ban công nội thất", "thiet-ke-ban-cong-noi-that-nt"],
    ["Nội Thất Phong Cách Tối Giản", "nội thất phong cách tối giản", "noi-that-phong-cach-toi-gian"],
    ["Nội Thất Phong Cách Scandinavian", "nội thất phong cách scandinavian", "noi-that-phong-cach-scandinavian"],
    ["Nội Thất Phong Cách Industrial", "nội thất phong cách industrial", "noi-that-phong-cach-industrial"],
    ["Nội Thất Phong Cách Japandi", "nội thất phong cách japandi", "noi-that-phong-cach-japandi"],
    ["Nội Thất Phong Cách Đông Dương", "nội thất phong cách đông dương", "noi-that-phong-cach-dong-duong"],
    ["Nội Thất Phong Cách Luxury", "nội thất phong cách luxury", "noi-that-phong-cach-luxury"],
    ["Nội Thất Phong Cách Wabi Sabi", "nội thất phong cách wabi sabi", "noi-that-phong-cach-wabi-sabi"],
    ["Chọn Sofa Phòng Khách", "chọn sofa phòng khách", "chon-sofa-phong-khach"],
    ["Chọn Bàn Ăn Nhà Phố", "chọn bàn ăn nhà phố", "chon-ban-an-nha-pho"],
    ["Chọn Giường Ngủ", "chọn giường ngủ", "chon-giuong-ngu"],
    ["Chọn Tủ Quần Áo", "chọn tủ quần áo", "chon-tu-quan-ao"],
    ["Chọn Tủ Bếp", "chọn tủ bếp", "chon-tu-bep"],
    ["Chọn Đá Bếp", "chọn đá bếp", "chon-da-bep"],
    ["Chọn Bếp Từ", "chọn bếp từ", "chon-bep-tu"],
    ["Chọn Máy Hút Mùi", "chọn máy hút mùi", "chon-may-hut-mui"],
    ["Chọn Chậu Rửa Bát", "chọn chậu rửa bát", "chon-chau-rua-bat"],
    ["Chọn Vòi Rửa Bát", "chọn vòi rửa bát", "chon-voi-rua-bat"],
    ["Chọn Gạch Nhà Tắm", "chọn gạch nhà tắm", "chon-gach-nha-tam"],
    ["Chọn Sen Cây", "chọn sen cây", "chon-sen-cay"],
    ["Chọn Lavabo", "chọn lavabo", "chon-lavabo"],
    ["Chọn Gương Nhà Tắm", "chọn gương nhà tắm", "chon-guong-nha-tam"],
    ["Chọn Đèn Trần Nhà", "chọn đèn trần nhà", "chon-den-tran-nha"],
    ["Chọn Đèn Phòng Ngủ", "chọn đèn phòng ngủ", "chon-den-phong-ngu"],
    ["Chọn Rèm Cửa", "chọn rèm cửa", "chon-rem-cua"],
    ["Chọn Giấy Dán Tường", "chọn giấy dán tường", "chon-giay-dan-tuong"],
    ["Chọn Thảm Trải Sàn", "chọn thảm trải sàn", "chon-tham-trai-san"],
    ["Chọn Tranh Trang Trí", "chọn tranh trang trí", "chon-tranh-trang-tri"],
    ["Hoàn Thiện Trần Thạch Cao Chi Tiết", "hoàn thiện trần thạch cao chi tiết", "hoan-thien-tran-thach-cao-chi-tiet"],
    ["Hoàn Thiện Sơn Nước Chi Tiết", "hoàn thiện sơn nước chi tiết", "hoan-thien-son-nuoc-chi-tiet"],
    ["Hoàn Thiện Ốp Lát Chi Tiết", "hoàn thiện ốp lát chi tiết", "hoan-thien-op-lat-chi-tiet"],
    ["Hoàn Thiện Hệ Điện Chi Tiết", "hoàn thiện hệ điện chi tiết", "hoan-thien-he-dien-chi-tiet"],
    ["Hoàn Thiện Hệ Nước Chi Tiết", "hoàn thiện hệ nước chi tiết", "hoan-thien-he-nuoc-chi-tiet"],
    ["Nẹp Inox Trang Trí", "nẹp inox trang trí", "nep-inox-trang-tri"],
    ["Nẹp Đồng Trang Trí", "nẹp đồng trang trí", "nep-dong-trang-tri"],
    ["Phào Chỉ Trần Nhà", "phào chỉ trần nhà", "phao-chi-tran-nha"],
    ["Phào Chỉ Tường Nhà", "phào chỉ tường nhà", "phao-chi-tuong-nha"],
    ["Vách CNC Phòng Khách", "vách cnc phòng khách", "vach-cnc-phong-khach"],
    ["Vách Lam Gỗ Phòng Khách", "vách lam gỗ phòng khách", "vach-lam-go-phong-khach"],
    ["Vách Kính Cường Lực Nội Thất", "vách kính cường lực nội thất", "vach-kinh-cuong-luc-noi-that"],
    ["Cầu Thang Gỗ Óc Chó", "cầu thang gỗ óc chó", "cau-thang-go-oc-cho"],
    ["Cầu Thang Kính Không Trụ", "cầu thang kính không trụ", "cau-thang-kinh-khong-tru"],
    ["Cầu Thang Xoắn Ốc Nội Thất", "cầu thang xoắn ốc nội thất", "cau-thang-xoan-oc-noi-that"],
    ["Tay Vịn Cầu Thang", "tay vịn cầu thang", "tay-vin-cau-thang"],
    ["Chiếu Nghỉ Cầu Thang", "chiếu nghỉ cầu thang", "chieu-nghi-cau-thang"],
    ["Tủ Âm Tường Tối Ưu", "tủ âm tường tối ưu", "tu-am-tuong-toi-uu"],
    ["Kệ Tivi Treo Tường", "kệ tivi treo tường", "ke-tivi-treo-tuong"],
    ["Bàn Làm Việc Góc", "bàn làm việc góc", "ban-lam-viec-goc"],
    ["Giường Tầng Trẻ Em", "giường tầng trẻ em", "giuong-tang-tre-em"],
    ["Bàn Học Cho Bé", "bàn học cho bé", "ban-hoc-cho-be"],
    ["Tủ Giày Thông Minh", "tủ giày thông minh", "tu-giay-thong-minh"],
    ["Tủ Đồ Dưới Cầu Thang", "tủ đồ dưới cầu thang", "tu-do-duoi-cau-thang"],
    ["Màu Sơn Phòng Khách", "màu sơn phòng khách", "mau-son-phong-khach"],
    ["Màu Sơn Phòng Ngủ", "màu sơn phòng ngủ", "mau-son-phong-ngu"],
    ["Màu Sơn Phòng Bếp", "màu sơn phòng bếp", "mau-son-phong-bep"],
    ["Phối Màu Nội Thất", "phối màu nội thất", "phoi-mau-noi-that"],
    ["Ánh Sáng Tự Nhiên Nội Thất", "ánh sáng tự nhiên nội thất", "anh-sang-tu-nhien-noi-that"],
    ["Ánh Sáng Nhân Tạo Nội Thất", "ánh sáng nhân tạo nội thất", "anh-sang-nhan-tao-noi-that"],
    ["Đèn Downlight Âm Trần", "đèn downlight âm trần", "den-downlight-am-tran"],
    ["Đèn Track Light", "đèn track light", "den-track-light"],
    ["Đèn Chùm Phòng Khách", "đèn chùm phòng khách", "den-chum-phong-khach"],
    ["Đèn Tường Trang Trí", "đèn tường trang trí", "den-tuong-trang-tri"],
    ["Nội Thất Gỗ Công Nghiệp", "nội thất gỗ công nghiệp", "noi-that-go-cong-nghiep"],
    ["Nội Thất Gỗ Tự Nhiên", "nội thất gỗ tự nhiên", "noi-that-go-tu-nhien"],
    ["Nội Thất MDF Chống Ẩm", "nội thất mdf chống ẩm", "noi-that-mdf-chong-am"],
    ["Nội Thất Acrylic Bóng Gương", "nội thất acrylic bóng gương", "noi-that-acrylic-bong-guong"],
    ["Báo Giá Nội Thất Trọn Gói", "báo giá nội thất trọn gói", "bao-gia-noi-that-tron-goi-nt"],
    ["Báo Giá Nội Thất Phòng Khách", "báo giá nội thất phòng khách", "bao-gia-noi-that-phong-khach"],
    ["Báo Giá Nội Thất Phòng Ngủ", "báo giá nội thất phòng ngủ", "bao-gia-noi-that-phong-ngu"],
    ["Báo Giá Nội Thất Bếp", "báo giá nội thất bếp", "bao-gia-noi-that-bep"],
    ["Báo Giá Nội Thất WC", "báo giá nội thất wc", "bao-gia-noi-that-wc"],
    ["Thi Công Nội Thất Bao Lâu", "thi công nội thất bao lâu", "thi-cong-noi-that-bao-lau"],
    ["Quy Trình Thi Công Nội Thất", "quy trình thi công nội thất", "quy-trinh-thi-cong-noi-that"],
    ["Nghiệm Thu Nội Thất", "nghiệm thu nội thất", "nghiem-thu-noi-that"],
    ["Bảo Hành Nội Thất", "bảo hành nội thất", "bao-hanh-noi-that"],
    ["Sửa Chữa Nội Thất", "sửa chữa nội thất", "sua-chua-noi-that"],
    ["Làm Mới Nội Thất Cũ", "làm mới nội thất cũ", "lam-moi-noi-that-cu"],
    ["Thay Đổi Layout Nội Thất", "thay đổi layout nội thất", "thay-doi-layout-noi-that"],
    ["Nội Thất Nhà Hẹp", "nội thất nhà hẹp", "noi-that-nha-hep"],
    ["Nội Thất Nhà Nhỏ Dưới 40m2", "nội thất nhà nhỏ dưới 40m2", "noi-that-nha-nho-duoi-40m2"],
    ["Nội Thất Tối Ưu Diện Tích", "nội thất tối ưu diện tích", "noi-that-toi-uu-dien-tich"],
    ["Nội Thất Đa Năng", "nội thất đa năng", "noi-that-da-nang"],
    ["Nội Thất Gấp Gọn", "nội thất gấp gọn", "noi-that-gap-gon"],
    ["Xu Hướng Nội Thất Nhà Phố 2026", "xu hướng nội thất nhà phố 2026", "xu-huong-noi-that-nha-pho-2026"],
    ["Xu Hướng Màu Sơn 2026", "xu hướng màu sơn 2026", "xu-huong-mau-son-2026"],
    ["Xu Hướng Sàn Nhà 2026", "xu hướng sàn nhà 2026", "xu-huong-san-nha-2026"],
    ["Xu Hướng Trần Nhà 2026", "xu hướng trần nhà 2026", "xu-huong-tran-nha-2026"],
    ["Combo Nội Thất Tiết Kiệm", "combo nội thất tiết kiệm", "combo-noi-that-tiet-kiem"],
    ["Combo Nội Thất Cao Cấp", "combo nội thất cao cấp", "combo-noi-that-cao-cap"],
  ]);

  // 36 — kỹ thuật thi công / giai đoạn / QC
  const b36 = pairs([
    ["Ép Cọc Bê Tông Cốt Thép", "ép cọc bê tông cốt thép", "ep-coc-be-tong-cot-thep"],
    ["Ép Cọc Tre Nhà Phố", "ép cọc tre nhà phố", "ep-coc-tre-nha-pho"],
    ["Khoan Cọc Nhồi Mini", "khoan cọc nhồi mini", "khoan-coc-nhoi-mini"],
    ["Đóng Cọc Bê Tông", "đóng cọc bê tông", "dong-coc-be-tong"],
    ["Đào Móng Nhà Phố", "đào móng nhà phố", "dao-mong-nha-pho"],
    ["Đổ Bê Tông Móng", "đổ bê tông móng", "do-be-tong-mong-kt"],
    ["Đổ Bê Tông Cột", "đổ bê tông cột", "do-be-tong-cot-kt"],
    ["Đổ Bê Tông Dầm", "đổ bê tông dầm", "do-be-tong-dam"],
    ["Đổ Bê Tông Sàn", "đổ bê tông sàn", "do-be-tong-san-kt"],
    ["Đổ Bê Tông Mái", "đổ bê tông mái", "do-be-tong-mai"],
    ["Buộc Thép Cột", "buộc thép cột", "buoc-thep-cot"],
    ["Buộc Thép Dầm", "buộc thép dầm", "buoc-thep-dam"],
    ["Buộc Thép Sàn", "buộc thép sàn", "buoc-thep-san"],
    ["Ghép Ván Khuôn Cột", "ghép ván khuôn cột", "ghep-van-khuon-cot"],
    ["Ghép Ván Khuôn Sàn", "ghép ván khuôn sàn", "ghep-van-khuon-san"],
    ["Tháo Ván Khuôn Bao Lâu", "tháo ván khuôn bao lâu", "thao-van-khuon-bao-lau"],
    ["Bảo Dưỡng Bê Tông", "bảo dưỡng bê tông", "bao-duong-be-tong-kt"],
    ["Xây Tường Gạch", "xây tường gạch", "xay-tuong-gach"],
    ["Xây Tường 100", "xây tường 100", "xay-tuong-100"],
    ["Xây Tường 200", "xây tường 200", "xay-tuong-200"],
    ["Trát Tường Trong", "trát tường trong", "trat-tuong-trong"],
    ["Trát Tường Ngoài", "trát tường ngoài", "trat-tuong-ngoai"],
    ["Cán Nền Sàn", "cán nền sàn", "can-nen-san"],
    ["Cán Nền Chống Dốc", "cán nền chống dốc", "can-nen-chong-doc"],
    ["Chống Thấm Móng", "chống thấm móng", "chong-tham-mong-kt"],
    ["Chống Thấm Sàn Vệ Sinh", "chống thấm sàn vệ sinh", "chong-tham-san-ve-sinh"],
    ["Chống Thấm Sân Thượng Kỹ Thuật", "chống thấm sân thượng kỹ thuật", "chong-tham-san-thuong-ky-thuat"],
    ["Lợp Mái Tôn Kỹ Thuật", "lợp mái tôn kỹ thuật", "lop-mai-ton-ky-thuat"],
    ["Lợp Mái Ngói Kỹ Thuật", "lợp mái ngói kỹ thuật", "lop-mai-ngoi-ky-thuat"],
    ["Lắp Đặt Cửa Nhôm Kỹ Thuật", "lắp đặt cửa nhôm kỹ thuật", "lap-dat-cua-nhom-ky-thuat"],
    ["Lắp Đặt Cửa Gỗ Kỹ Thuật", "lắp đặt cửa gỗ kỹ thuật", "lap-dat-cua-go-ky-thuat"],
    ["Ốp Lát Gạch Kỹ Thuật", "ốp lát gạch kỹ thuật", "op-lat-gach-ky-thuat"],
    ["Ốp Đá Granite Kỹ Thuật", "ốp đá granite kỹ thuật", "op-da-granite-ky-thuat"],
    ["Ốp Đá Marble Kỹ Thuật", "ốp đá marble kỹ thuật", "op-da-marble-ky-thuat"],
    ["Sơn Bả Matit", "sơn bả matit", "son-ba-matit"],
    ["Sơn Lót Nhà", "sơn lót nhà", "son-lot-nha-kt"],
    ["Sơn Phủ Nhà", "sơn phủ nhà", "son-phu-nha-kt"],
    ["Thi Công Trần Thạch Cao Kỹ Thuật", "thi công trần thạch cao kỹ thuật", "thi-cong-tran-thach-cao-ky-thuat"],
    ["Thi Công Hệ Thống Điện Âm", "thi công hệ thống điện âm", "thi-cong-he-thong-dien-am"],
    ["Thi Công Hệ Thống Nước Âm", "thi công hệ thống nước âm", "thi-cong-he-thong-nuoc-am"],
    ["Thi Công Ống Cấp Nước", "thi công ống cấp nước", "thi-cong-ong-cap-nuoc"],
    ["Thi Công Ống Thoát Nước", "thi công ống thoát nước", "thi-cong-ong-thoat-nuoc"],
    ["Thi Công Hộp Kỹ Thuật", "thi công hộp kỹ thuật", "thi-cong-hop-ky-thuat"],
    ["Thi Công Giếng Trời Kỹ Thuật", "thi công giếng trời kỹ thuật", "thi-cong-gieng-troi-ky-thuat"],
    ["Giai Đoạn Phần Móng", "giai đoạn phần móng", "giai-doan-phan-mong"],
    ["Giai Đoạn Phần Thân", "giai đoạn phần thân", "giai-doan-phan-than"],
    ["Giai Đoạn Phần Mái", "giai đoạn phần mái", "giai-doan-phan-mai"],
    ["Giai Đoạn Hoàn Thiện Thô", "giai đoạn hoàn thiện thô", "giai-doan-hoan-thien-tho"],
    ["Giai Đoạn Hoàn Thiện Mịn", "giai đoạn hoàn thiện mịn", "giai-doan-hoan-thien-min"],
    ["Tiến Độ Xây Nhà 2 Tháng", "tiến độ xây nhà 2 tháng", "tien-do-xay-nha-2-thang"],
    ["Tiến Độ Xây Nhà 3 Tháng", "tiến độ xây nhà 3 tháng", "tien-do-xay-nha-3-thang"],
    ["Tiến Độ Xây Nhà 4 Tháng", "tiến độ xây nhà 4 tháng", "tien-do-xay-nha-4-thang"],
    ["Tiến Độ Xây Nhà 6 Tháng", "tiến độ xây nhà 6 tháng", "tien-do-xay-nha-6-thang"],
    ["Tiến Độ Cải Tạo 1 Tháng", "tiến độ cải tạo 1 tháng", "tien-do-cai-tao-1-thang"],
    ["Tiến Độ Cải Tạo 2 Tháng", "tiến độ cải tạo 2 tháng", "tien-do-cai-tao-2-thang"],
    ["Nhật Ký Công Trình", "nhật ký công trình", "nhat-ky-cong-trinh-kt"],
    ["Biên Bản Nghiệm Thu Móng", "biên bản nghiệm thu móng", "bien-ban-nghiem-thu-mong"],
    ["Biên Bản Nghiệm Thu Cột", "biên bản nghiệm thu cột", "bien-ban-nghiem-thu-cot"],
    ["Biên Bản Nghiệm Thu Sàn", "biên bản nghiệm thu sàn", "bien-ban-nghiem-thu-san"],
    ["Biên Bản Nghiệm Thu Điện", "biên bản nghiệm thu điện", "bien-ban-nghiem-thu-dien"],
    ["Biên Bản Nghiệm Thu Nước", "biên bản nghiệm thu nước", "bien-ban-nghiem-thu-nuoc"],
    ["Kiểm Tra Thép Trước Đổ", "kiểm tra thép trước đổ", "kiem-tra-thep-truoc-do"],
    ["Kiểm Tra Ván Khuôn", "kiểm tra ván khuôn", "kiem-tra-van-khuon"],
    ["Kiểm Tra Độ Sụt Bê Tông", "kiểm tra độ sụt bê tông", "kiem-tra-do-sut-be-tong"],
    ["Lấy Mẫu Bê Tông", "lấy mẫu bê tông", "lay-mau-be-tong"],
    ["Thử Áp Hệ Nước", "thử áp hệ nước", "thu-ap-he-nuoc"],
    ["Thử Tải Hệ Điện", "thử tải hệ điện", "thu-tai-he-dien"],
    ["Ngâm Nước Chống Thấm", "ngâm nước chống thấm", "ngam-nuoc-chong-tham"],
    ["QC Chất Lượng Hồ Vữa", "qc chất lượng hồ vữa", "qc-chat-luong-ho-vua"],
    ["QC Chất Lượng Gạch", "qc chất lượng gạch", "qc-chat-luong-gach"],
    ["QC Độ Thẳng Tường", "qc độ thẳng tường", "qc-do-thang-tuong"],
    ["QC Độ Phẳng Sàn", "qc độ phẳng sàn", "qc-do-phang-san"],
    ["QC Ron Gạch", "qc ron gạch", "qc-ron-gach"],
    ["QC Lớp Sơn", "qc lớp sơn", "qc-lop-son"],
    ["An Toàn Lao Động Công Trường", "an toàn lao động công trường", "an-toan-lao-dong-cong-truong"],
    ["Giàn Giáo An Toàn", "giàn giáo an toàn", "gian-giao-an-toan"],
    ["Rào Chắn Công Trường", "rào chắn công trường", "rao-chan-cong-truong"],
    ["Che Chắn Bụi Công Trường", "che chắn bụi công trường", "che-chan-bui-cong-truong"],
    ["Xử Lý Phế Thải Xây Dựng", "xử lý phế thải xây dựng", "xu-ly-phe-thai-xay-dung"],
    ["Tạm Dừng Thi Công Khi Mưa", "tạm dừng thi công khi mưa", "tam-dung-thi-cong-khi-mua"],
    ["Thi Công Mùa Mưa", "thi công mùa mưa", "thi-cong-mua-mua"],
    ["Thi Công Mùa Nắng", "thi công mùa nắng", "thi-cong-mua-nang"],
    ["Ca Đêm Thi Công", "ca đêm thi công", "ca-dem-thi-cong"],
    ["Đổ Bê Tông Ban Đêm", "đổ bê tông ban đêm", "do-be-tong-ban-dem"],
    ["Máy Trộn Bê Tông Tại Chỗ", "máy trộn bê tông tại chỗ", "may-tron-be-tong-tai-cho"],
    ["Bê Tông Tươi Xe Bơm", "bê tông tươi xe bơm", "be-tong-tuoi-xe-bom"],
    ["Cần Cẩu Mini Nhà Phố", "cần cẩu mini nhà phố", "can-cau-mini-nha-pho"],
    ["Vận Thăng Công Trình", "vận thăng công trình", "van-thang-cong-trinh"],
    ["Máy Cắt Sắt Công Trình", "máy cắt sắt công trình", "may-cat-sat-cong-trinh"],
    ["Máy Đầm Dùi Bê Tông", "máy đầm dùi bê tông", "may-dam-dui-be-tong"],
    ["Sai Số Cho Phép Thi Công", "sai số cho phép thi công", "sai-so-cho-phep-thi-cong"],
    ["Sửa Lỗi Thi Công Bê Tông", "sửa lỗi thi công bê tông", "sua-loi-thi-cong-be-tong"],
    ["Sửa Lỗi Thi Công Tường", "sửa lỗi thi công tường", "sua-loi-thi-cong-tuong"],
    ["Sửa Lỗi Thi Công Ốp Lát", "sửa lỗi thi công ốp lát", "sua-loi-thi-cong-op-lat"],
    ["Sửa Lỗi Thi Công Sơn", "sửa lỗi thi công sơn", "sua-loi-thi-cong-son"],
    ["Checklist QC Hàng Ngày", "checklist qc hàng ngày", "checklist-qc-hang-ngay"],
    ["Checklist QC Theo Giai Đoạn", "checklist qc theo giai đoạn", "checklist-qc-theo-giai-doan"],
  ]);

  // 37 — geo Hà Nội / miền Bắc / miền Trung
  const b37 = pairs([
    ["Xây Nhà Cầu Giấy", "xây nhà Cầu Giấy", "xay-nha-cau-giay"],
    ["Xây Nhà Đống Đa", "xây nhà Đống Đa", "xay-nha-dong-da"],
    ["Xây Nhà Ba Đình", "xây nhà Ba Đình", "xay-nha-ba-dinh"],
    ["Xây Nhà Hoàn Kiếm", "xây nhà Hoàn Kiếm", "xay-nha-hoan-kiem"],
    ["Xây Nhà Hai Bà Trưng", "xây nhà Hai Bà Trưng", "xay-nha-hai-ba-trung"],
    ["Xây Nhà Hoàng Mai", "xây nhà Hoàng Mai", "xay-nha-hoang-mai"],
    ["Xây Nhà Thanh Xuân", "xây nhà Thanh Xuân", "xay-nha-thanh-xuan-hn"],
    ["Xây Nhà Tây Hồ", "xây nhà Tây Hồ", "xay-nha-tay-ho"],
    ["Xây Nhà Long Biên", "xây nhà Long Biên", "xay-nha-long-bien"],
    ["Xây Nhà Hà Đông", "xây nhà Hà Đông", "xay-nha-ha-dong"],
    ["Xây Nhà Nam Từ Liêm", "xây nhà Nam Từ Liêm", "xay-nha-nam-tu-liem"],
    ["Xây Nhà Bắc Từ Liêm", "xây nhà Bắc Từ Liêm", "xay-nha-bac-tu-liem"],
    ["Xây Nhà Cầu Diễn", "xây nhà Cầu Diễn", "xay-nha-cau-dien"],
    ["Xây Nhà Mỹ Đình", "xây nhà Mỹ Đình", "xay-nha-my-dinh"],
    ["Xây Nhà Gia Lâm", "xây nhà Gia Lâm", "xay-nha-gia-lam"],
    ["Xây Nhà Đông Anh", "xây nhà Đông Anh", "xay-nha-dong-anh"],
    ["Xây Nhà Sóc Sơn", "xây nhà Sóc Sơn", "xay-nha-soc-son"],
    ["Xây Nhà Hoài Đức", "xây nhà Hoài Đức", "xay-nha-hoai-duc"],
    ["Xây Nhà Thanh Trì", "xây nhà Thanh Trì", "xay-nha-thanh-tri"],
    ["Xây Nhà Thường Tín", "xây nhà Thường Tín", "xay-nha-thuong-tin"],
    ["Xây Nhà Hải Dương", "xây nhà Hải Dương", "xay-nha-hai-duong-tinh"],
    ["Xây Nhà Hải Phòng", "xây nhà Hải Phòng", "xay-nha-hai-phong-tinh"],
    ["Xây Nhà Quảng Ninh", "xây nhà Quảng Ninh", "xay-nha-quang-ninh-tinh"],
    ["Xây Nhà Bắc Ninh", "xây nhà Bắc Ninh", "xay-nha-bac-ninh-tinh"],
    ["Xây Nhà Bắc Giang", "xây nhà Bắc Giang", "xay-nha-bac-giang-tinh"],
    ["Xây Nhà Hưng Yên", "xây nhà Hưng Yên", "xay-nha-hung-yen-tinh"],
    ["Xây Nhà Vĩnh Phúc", "xây nhà Vĩnh Phúc", "xay-nha-vinh-phuc-tinh"],
    ["Xây Nhà Thái Nguyên", "xây nhà Thái Nguyên", "xay-nha-thai-nguyen-tinh"],
    ["Xây Nhà Phú Thọ", "xây nhà Phú Thọ", "xay-nha-phu-tho-tinh"],
    ["Xây Nhà Nam Định", "xây nhà Nam Định", "xay-nha-nam-dinh-tinh"],
    ["Xây Nhà Thái Bình", "xây nhà Thái Bình", "xay-nha-thai-binh-tinh"],
    ["Xây Nhà Ninh Bình", "xây nhà Ninh Bình", "xay-nha-ninh-binh-tinh"],
    ["Xây Nhà Thanh Hóa", "xây nhà Thanh Hóa", "xay-nha-thanh-hoa-tinh"],
    ["Xây Nhà Nghệ An", "xây nhà Nghệ An", "xay-nha-nghe-an-tinh"],
    ["Xây Nhà Hà Tĩnh", "xây nhà Hà Tĩnh", "xay-nha-ha-tinh-tinh"],
    ["Xây Nhà Quảng Bình", "xây nhà Quảng Bình", "xay-nha-quang-binh-tinh"],
    ["Xây Nhà Quảng Trị", "xây nhà Quảng Trị", "xay-nha-quang-tri-tinh"],
    ["Xây Nhà Huế", "xây nhà Huế", "xay-nha-hue-tinh"],
    ["Xây Nhà Đà Nẵng", "xây nhà Đà Nẵng", "xay-nha-da-nang-tinh"],
    ["Xây Nhà Quảng Nam", "xây nhà Quảng Nam", "xay-nha-quang-nam-tinh"],
    ["Xây Nhà Quảng Ngãi", "xây nhà Quảng Ngãi", "xay-nha-quang-ngai-tinh"],
    ["Xây Nhà Bình Định", "xây nhà Bình Định", "xay-nha-binh-dinh-tinh"],
    ["Xây Nhà Phú Yên", "xây nhà Phú Yên", "xay-nha-phu-yen-tinh"],
    ["Xây Nhà Khánh Hòa", "xây nhà Khánh Hòa", "xay-nha-khanh-hoa-tinh"],
    ["Xây Nhà Nha Trang", "xây nhà Nha Trang", "xay-nha-nha-trang-tinh"],
    ["Xây Nhà Ninh Thuận", "xây nhà Ninh Thuận", "xay-nha-ninh-thuan-tinh"],
    ["Xây Nhà Bình Thuận", "xây nhà Bình Thuận", "xay-nha-binh-thuan-tinh"],
    ["Xây Nhà Phan Thiết", "xây nhà Phan Thiết", "xay-nha-phan-thiet-tinh"],
    ["Xây Nhà Buôn Ma Thuột", "xây nhà Buôn Ma Thuột", "xay-nha-buon-ma-thuot-tinh"],
    ["Xây Nhà Đà Lạt", "xây nhà Đà Lạt", "xay-nha-da-lat-tinh"],
    ["Xây Nhà Pleiku", "xây nhà Pleiku", "xay-nha-pleiku-tinh"],
    ["Cải Tạo Nhà Cầu Giấy", "cải tạo nhà Cầu Giấy", "cai-tao-nha-cau-giay"],
    ["Cải Tạo Nhà Hà Đông", "cải tạo nhà Hà Đông", "cai-tao-nha-ha-dong"],
    ["Cải Tạo Nhà Long Biên", "cải tạo nhà Long Biên", "cai-tao-nha-long-bien"],
    ["Cải Tạo Nhà Đà Nẵng", "cải tạo nhà Đà Nẵng", "cai-tao-nha-da-nang-geo"],
    ["Cải Tạo Nhà Nha Trang", "cải tạo nhà Nha Trang", "cai-tao-nha-nha-trang-geo"],
    ["Cải Tạo Nhà Đà Lạt", "cải tạo nhà Đà Lạt", "cai-tao-nha-da-lat-geo"],
    ["Thiết Kế Nhà Cầu Giấy", "thiết kế nhà Cầu Giấy", "thiet-ke-nha-cau-giay"],
    ["Thiết Kế Nhà Hà Đông", "thiết kế nhà Hà Đông", "thiet-ke-nha-ha-dong"],
    ["Thiết Kế Nhà Đà Nẵng", "thiết kế nhà Đà Nẵng", "thiet-ke-nha-da-nang-geo"],
    ["Thiết Kế Nhà Nha Trang", "thiết kế nhà Nha Trang", "thiet-ke-nha-nha-trang-geo"],
    ["Thiết Kế Nhà Đà Lạt", "thiết kế nhà Đà Lạt", "thiet-ke-nha-da-lat-geo"],
    ["Báo Giá Xây Nhà Hà Nội", "báo giá xây nhà Hà Nội", "bao-gia-xay-nha-ha-noi"],
    ["Báo Giá Xây Nhà Hải Phòng", "báo giá xây nhà Hải Phòng", "bao-gia-xay-nha-hai-phong"],
    ["Báo Giá Xây Nhà Đà Nẵng", "báo giá xây nhà Đà Nẵng", "bao-gia-xay-nha-da-nang-geo"],
    ["Báo Giá Xây Nhà Nha Trang", "báo giá xây nhà Nha Trang", "bao-gia-xay-nha-nha-trang-geo"],
    ["Báo Giá Xây Nhà Đà Lạt", "báo giá xây nhà Đà Lạt", "bao-gia-xay-nha-da-lat-geo"],
    ["Nhà Thầu Hà Nội", "nhà thầu Hà Nội", "nha-thau-ha-noi"],
    ["Nhà Thầu Hải Phòng", "nhà thầu Hải Phòng", "nha-thau-hai-phong"],
    ["Nhà Thầu Đà Nẵng", "nhà thầu Đà Nẵng", "nha-thau-da-nang"],
    ["Nhà Thầu Nha Trang", "nhà thầu Nha Trang", "nha-thau-nha-trang"],
    ["Nhà Thầu Đà Lạt", "nhà thầu Đà Lạt", "nha-thau-da-lat"],
    ["Xây Nhà Ống Hà Nội", "xây nhà ống Hà Nội", "xay-nha-ong-ha-noi"],
    ["Xây Nhà Phố Hà Nội", "xây nhà phố Hà Nội", "xay-nha-pho-ha-noi"],
    ["Xây Biệt Thự Hà Nội", "xây biệt thự Hà Nội", "xay-biet-thu-ha-noi"],
    ["Xây Nhà Vườn Hà Nội", "xây nhà vườn Hà Nội", "xay-nha-vuon-ha-noi"],
    ["Xây Nhà Ven Biển Đà Nẵng", "xây nhà ven biển Đà Nẵng", "xay-nha-ven-bien-da-nang"],
    ["Xây Nhà Ven Biển Nha Trang", "xây nhà ven biển Nha Trang", "xay-nha-ven-bien-nha-trang"],
    ["Xây Nhà Núi Đà Lạt", "xây nhà núi Đà Lạt", "xay-nha-nui-da-lat"],
    ["Xây Nhà Chống Lạnh Đà Lạt", "xây nhà chống lạnh Đà Lạt", "xay-nha-chong-lanh-da-lat"],
    ["Xây Nhà Chống Bão Miền Trung", "xây nhà chống bão miền Trung", "xay-nha-chong-bao-mien-trung"],
    ["Xây Nhà Chống Lũ Miền Trung", "xây nhà chống lũ miền Trung", "xay-nha-chong-lu-mien-trung"],
    ["Xin Phép Xây Nhà Hà Nội", "xin phép xây nhà Hà Nội", "xin-phep-xay-nha-ha-noi"],
    ["Xin Phép Xây Nhà Đà Nẵng", "xin phép xây nhà Đà Nẵng", "xin-phep-xay-nha-da-nang"],
    ["Đơn Giá Xây Nhà Hà Nội", "đơn giá xây nhà Hà Nội", "don-gia-xay-nha-ha-noi"],
    ["Đơn Giá Xây Nhà Đà Nẵng", "đơn giá xây nhà Đà Nẵng", "don-gia-xay-nha-da-nang"],
    ["Đơn Giá Xây Nhà Nha Trang", "đơn giá xây nhà Nha Trang", "don-gia-xay-nha-nha-trang"],
    ["Xây Nhà KĐT Dương Nội", "xây nhà Dương Nội", "xay-nha-duong-noi"],
    ["Xây Nhà KĐT Văn Quán", "xây nhà Văn Quán", "xay-nha-van-quan"],
    ["Xây Nhà KĐT Linh Đàm", "xây nhà Linh Đàm", "xay-nha-linh-dam"],
    ["Xây Nhà KĐT Ciputra", "xây nhà Ciputra", "xay-nha-ciputra"],
    ["Xây Nhà KĐT Ecopark", "xây nhà Ecopark", "xay-nha-ecopark"],
    ["Xây Nhà KĐT Vinhomes Ocean Park", "xây nhà Vinhomes Ocean Park", "xay-nha-vinhomes-ocean-park"],
    ["Xây Nhà KĐT Vinhomes Smart City", "xây nhà Vinhomes Smart City", "xay-nha-vinhomes-smart-city"],
    ["Xây Nhà Ngũ Hành Sơn", "xây nhà Ngũ Hành Sơn", "xay-nha-ngu-hanh-son"],
    ["Xây Nhà Sơn Trà", "xây nhà Sơn Trà", "xay-nha-son-tra"],
    ["Xây Nhà Hải Châu", "xây nhà Hải Châu", "xay-nha-hai-chau"],
    ["Xây Nhà Thanh Khê", "xây nhà Thanh Khê", "xay-nha-thanh-khe"],
    ["Xây Nhà Liên Chiểu", "xây nhà Liên Chiểu", "xay-nha-lien-chieu"],
    ["Xây Nhà Cẩm Lệ", "xây nhà Cẩm Lệ", "xay-nha-cam-le"],
  ]);

  // 38 — pháp lý / tài chính / bảo hiểm / hợp đồng sâu
  const b38 = pairs([
    ["Hồ Sơ Xin Phép Xây Dựng", "hồ sơ xin phép xây dựng", "ho-so-xin-phep-xay-dung"],
    ["Thời Gian Xin Phép Xây", "thời gian xin phép xây", "thoi-gian-xin-phep-xay"],
    ["Lệ Phí Xin Phép Xây", "lệ phí xin phép xây", "le-phi-xin-phep-xay"],
    ["Giấy Phép Xây Dựng Hết Hạn", "giấy phép xây dựng hết hạn", "giay-phep-xay-dung-het-han"],
    ["Gia Hạn Giấy Phép Xây", "gia hạn giấy phép xây", "gia-han-giay-phep-xay"],
    ["Sửa Đổi Giấy Phép Xây", "sửa đổi giấy phép xây", "sua-doi-giay-phep-xay"],
    ["Xây Không Phép Xử Lý", "xây không phép xử lý", "xay-khong-phep-xu-ly"],
    ["Phạt Xây Vượt Phép", "phạt xây vượt phép", "phat-xay-vuot-phep"],
    ["Phạt Xây Sai Phép", "phạt xây sai phép", "phat-xay-sai-phep"],
    ["Hợp Thức Hóa Công Trình", "hợp thức hóa công trình", "hop-thuc-hoa-cong-trinh"],
    ["Cấp Phép Xây Nhà Cải Tạo", "cấp phép xây nhà cải tạo", "cap-phep-xay-nha-cai-tao"],
    ["Thông Báo Cải Tạo Nhà", "thông báo cải tạo nhà", "thong-bao-cai-tao-nha"],
    ["Quy Hoạch Xây Dựng Khu Vực", "quy hoạch xây dựng khu vực", "quy-hoach-xay-dung-khu-vuc"],
    ["Chỉ Giới Đường Đỏ", "chỉ giới đường đỏ", "chi-gioi-duong-do-pl"],
    ["Chỉ Giới Xây Dựng", "chỉ giới xây dựng", "chi-gioi-xay-dung-pl"],
    ["Mật Độ Xây Dựng Cho Phép", "mật độ xây dựng cho phép", "mat-do-xay-dung-cho-phep"],
    ["Hệ Số Sử Dụng Đất", "hệ số sử dụng đất", "he-so-su-dung-dat-pl"],
    ["Chiều Cao Tầng Cho Phép", "chiều cao tầng cho phép", "chieu-cao-tang-cho-phep"],
    ["Khoảng Lùi Công Trình", "khoảng lùi công trình", "khoang-lui-cong-trinh"],
    ["Quyền Sử Dụng Đất Xây Nhà", "quyền sử dụng đất xây nhà", "quyen-su-dung-dat-xay-nha"],
    ["Đất Ở Xây Nhà", "đất ở xây nhà", "dat-o-xay-nha"],
    ["Đất Nông Nghiệp Xây Nhà", "đất nông nghiệp xây nhà", "dat-nong-nghiep-xay-nha"],
    ["Chuyển Đổi Đất Xây Nhà", "chuyển đổi đất xây nhà", "chuyen-doi-dat-xay-nha"],
    ["Sổ Hồng Xây Nhà", "sổ hồng xây nhà", "so-hong-xay-nha-pl"],
    ["Sổ Đỏ Xây Nhà", "sổ đỏ xây nhà", "so-do-xay-nha"],
    ["Thế Chấp Sổ Vay Xây", "thế chấp sổ vay xây", "the-chap-so-vay-xay"],
    ["Vay Xây Sửa Nhà", "vay xây sửa nhà", "vay-xay-sua-nha"],
    ["Vay Mua Đất Xây Nhà", "vay mua đất xây nhà", "vay-mua-dat-xay-nha"],
    ["Gói Vay Xây Nhà Ngân Hàng", "gói vay xây nhà ngân hàng", "goi-vay-xay-nha-ngan-hang"],
    ["Hồ Sơ Vay Xây Nhà", "hồ sơ vay xây nhà", "ho-so-vay-xay-nha"],
    ["Điều Kiện Vay Xây Nhà", "điều kiện vay xây nhà", "dieu-kien-vay-xay-nha"],
    ["Bảo Hiểm Công Trình Xây", "bảo hiểm công trình xây", "bao-hiem-cong-trinh-xay"],
    ["Bảo Hiểm Trách Nhiệm Thầu", "bảo hiểm trách nhiệm thầu", "bao-hiem-trach-nhiem-thau"],
    ["Bảo Hiểm Tai Nạn Lao Động", "bảo hiểm tai nạn lao động", "bao-hiem-tai-nan-lao-dong"],
    ["Bảo Hiểm Nhà Ở", "bảo hiểm nhà ở", "bao-hiem-nha-o"],
    ["Bảo Hiểm Cháy Nổ Nhà", "bảo hiểm cháy nổ nhà", "bao-hiem-chay-no-nha"],
    ["Hợp Đồng Thiết Kế Nhà", "hợp đồng thiết kế nhà", "hop-dong-thiet-ke-nha"],
    ["Hợp Đồng Thi Công Xây", "hợp đồng thi công xây", "hop-dong-thi-cong-xay"],
    ["Hợp Đồng Trọn Gói Xây", "hợp đồng trọn gói xây", "hop-dong-tron-goi-xay"],
    ["Hợp Đồng Đơn Giá Xây", "hợp đồng đơn giá xây", "hop-dong-don-gia-xay"],
    ["Hợp Đồng Nhân Công Xây", "hợp đồng nhân công xây", "hop-dong-nhan-cong-xay"],
    ["Điều Khoản Phát Sinh HĐ", "điều khoản phát sinh hợp đồng", "dieu-khoan-phat-sinh-hd"],
    ["Điều Khoản Bảo Hành HĐ", "điều khoản bảo hành hợp đồng", "dieu-khoan-bao-hanh-hd"],
    ["Điều Khoản Phạt Trễ HĐ", "điều khoản phạt trễ hợp đồng", "dieu-khoan-phat-tre-hd"],
    ["Điều Khoản Tạm Ứng HĐ", "điều khoản tạm ứng hợp đồng", "dieu-khoan-tam-ung-hd"],
    ["Điều Khoản Nghiệm Thu HĐ", "điều khoản nghiệm thu hợp đồng", "dieu-khoan-nghiem-thu-hd"],
    ["Phụ Lục Hợp Đồng Xây", "phụ lục hợp đồng xây", "phu-luc-hop-dong-xay-pl"],
    ["Thanh Lý Hợp Đồng Xây", "thanh lý hợp đồng xây", "thanh-ly-hop-dong-xay-pl"],
    ["Chấm Dứt Hợp Đồng Xây", "chấm dứt hợp đồng xây", "cham-dut-hop-dong-xay"],
    ["Trọng Tài Tranh Chấp Xây", "trọng tài tranh chấp xây", "trong-tai-tranh-chap-xay"],
    ["Luật Xây Dựng Cơ Bản", "luật xây dựng cơ bản", "luat-xay-dung-co-ban"],
    ["Nghị Định Xây Dựng Nhà Ở", "nghị định xây dựng nhà ở", "nghi-dinh-xay-dung-nha-o"],
    ["Tiêu Chuẩn Xây Dựng Việt Nam", "tiêu chuẩn xây dựng việt nam", "tieu-chuan-xay-dung-viet-nam"],
    ["Quy Chuẩn Kỹ Thuật Xây", "quy chuẩn kỹ thuật xây", "quy-chuan-ky-thuat-xay"],
    ["An Toàn Kết Cấu Nhà Ở", "an toàn kết cấu nhà ở", "an-toan-ket-cau-nha-o"],
    ["Chứng Chỉ Hành Nghề KTS", "chứng chỉ hành nghề kts", "chung-chi-hanh-nghe-kts"],
    ["Chứng Chỉ Hành Nghề Giám Sát", "chứng chỉ hành nghề giám sát", "chung-chi-hanh-nghe-giam-sat"],
    ["Năng Lực Nhà Thầu Xây", "năng lực nhà thầu xây", "nang-luc-nha-thau-xay"],
    ["Giấy Phép Kinh Doanh Xây", "giấy phép kinh doanh xây", "giay-phep-kinh-doanh-xay-pl"],
    ["MST Công Ty Xây Dựng", "mst công ty xây dựng", "mst-cong-ty-xay-dung"],
    ["Hóa Đơn VAT Xây Nhà", "hóa đơn vat xây nhà", "hoa-don-vat-xay-nha"],
    ["Thuế Xây Nhà Cá Nhân", "thuế xây nhà cá nhân", "thue-xay-nha-ca-nhan"],
    ["Chi Phí Pháp Lý Xây Nhà", "chi phí pháp lý xây nhà", "chi-phi-phap-ly-xay-nha"],
    ["Công Chứng Hợp Đồng Xây", "công chứng hợp đồng xây", "cong-chung-hop-dong-xay"],
    ["Ủy Quyền Xây Nhà", "ủy quyền xây nhà", "uy-quyen-xay-nha"],
    ["Đồng Sở Hữu Xây Nhà", "đồng sở hữu xây nhà", "dong-so-huu-xay-nha"],
    ["Xây Nhà Trên Đất Chung", "xây nhà trên đất chung", "xay-nha-tren-dat-chung"],
    ["Tách Thửa Xây Nhà", "tách thửa xây nhà", "tach-thua-xay-nha-pl"],
    ["Hợp Thửa Xây Nhà", "hợp thửa xây nhà", "hop-thua-xay-nha-pl"],
    ["Giấy Phép Môi Trường Xây", "giấy phép môi trường xây", "giay-phep-moi-truong-xay"],
    ["Cam Kết Bảo Vệ Môi Trường", "cam kết bảo vệ môi trường", "cam-ket-bao-ve-moi-truong"],
    ["Thẩm Duyệt PCCC Nhà Ở", "thẩm duyệt pccc nhà ở", "tham-duyet-pccc-nha-o"],
    ["Nghiệm Thu PCCC Nhà Ở", "nghiệm thu pccc nhà ở", "nghiem-thu-pccc-nha-o"],
    ["Biên Bản Hiện Trường Xây", "biên bản hiện trường xây", "bien-ban-hien-truong-xay"],
    ["Khiếu Nại Hàng Xóm Xây", "khiếu nại hàng xóm xây", "khieu-nai-hang-xom-xay"],
    ["Tranh Chấp Ranh Giới Đất", "tranh chấp ranh giới đất", "tranh-chap-ranh-gioi-dat"],
    ["Hỗ Trợ Pháp Lý Xây Nhà", "hỗ trợ pháp lý xây nhà", "ho-tro-phap-ly-xay-nha"],
    ["Tư Vấn Luật Xây Dựng", "tư vấn luật xây dựng", "tu-van-luat-xay-dung"],
    ["Checklist Pháp Lý Trước Xây", "checklist pháp lý trước xây", "checklist-phap-ly-truoc-xay"],
    ["Checklist Pháp Lý Sau Xây", "checklist pháp lý sau xây", "checklist-phap-ly-sau-xay"],
    ["Hoàn Công Nhà Ở", "hoàn công nhà ở", "hoan-cong-nha-o"],
    ["Hồ Sơ Hoàn Công", "hồ sơ hoàn công", "ho-so-hoan-cong"],
    ["Thời Gian Hoàn Công", "thời gian hoàn công", "thoi-gian-hoan-cong"],
    ["Chi Phí Hoàn Công", "chi phí hoàn công", "chi-phi-hoan-cong"],
    ["Cập Nhật Sổ Sau Xây", "cập nhật sổ sau xây", "cap-nhat-so-sau-xay"],
    ["Đăng Ký Biến Động Đất Đai", "đăng ký biến động đất đai", "dang-ky-bien-dong-dat-dai"],
    ["Thuế Trước Bạ Nhà Đất", "thuế trước bạ nhà đất", "thue-truoc-ba-nha-dat"],
    ["Lệ Phí Trước Bạ Xây Mới", "lệ phí trước bạ xây mới", "le-phi-truoc-ba-xay-moi"],
    ["Giá Tính Thuế Nhà Ở", "giá tính thuế nhà ở", "gia-tinh-thue-nha-o"],
    ["Miễn Giảm Thuế Xây Nhà", "miễn giảm thuế xây nhà", "mien-giam-thue-xay-nha"],
    ["Rủi Ro Pháp Lý Xây Nhà", "rủi ro pháp lý xây nhà", "rui-ro-phap-ly-xay-nha"],
    ["Rủi Ro Tài Chính Xây Nhà", "rủi ro tài chính xây nhà", "rui-ro-tai-chinh-xay-nha"],
    ["Quản Lý Dòng Tiền Xây Nhà", "quản lý dòng tiền xây nhà", "quan-ly-dong-tien-xay-nha"],
    ["Escrow Thanh Toán Xây", "escrow thanh toán xây", "escrow-thanh-toan-xay"],
    ["Chứng Từ Thanh Toán Xây", "chứng từ thanh toán xây", "chung-tu-thanh-toan-xay"],
  ]);

  // 39 — kịch bản gia đình / so sánh / mùa vụ / lifestyle Ads
  const b39 = pairs([
    ["Xây Nhà Cho Gia Đình 3 Người", "xây nhà cho gia đình 3 người", "xay-nha-cho-gia-dinh-3-nguoi"],
    ["Xây Nhà Cho Gia Đình 4 Người", "xây nhà cho gia đình 4 người", "xay-nha-cho-gia-dinh-4-nguoi"],
    ["Xây Nhà Cho Gia Đình 5 Người", "xây nhà cho gia đình 5 người", "xay-nha-cho-gia-dinh-5-nguoi"],
    ["Xây Nhà Cho Gia Đình 3 Thế Hệ", "xây nhà cho gia đình 3 thế hệ", "xay-nha-cho-gia-dinh-3-the-he"],
    ["Xây Nhà Cho Vợ Chồng Trẻ", "xây nhà cho vợ chồng trẻ", "xay-nha-cho-vo-chong-tre"],
    ["Xây Nhà Cho Người Độc Thân", "xây nhà cho người độc thân", "xay-nha-cho-nguoi-doc-than"],
    ["Xây Nhà Cho Người Về Hưu", "xây nhà cho người về hưu", "xay-nha-cho-nguoi-ve-huu"],
    ["Xây Nhà Cho Con Cái", "xây nhà cho con cái", "xay-nha-cho-con-cai"],
    ["Xây Nhà Tặng Cha Mẹ", "xây nhà tặng cha mẹ", "xay-nha-tang-cha-me"],
    ["Xây Nhà Sau Kết Hôn", "xây nhà sau kết hôn", "xay-nha-sau-ket-hon"],
    ["Xây Nhà Khi Có Em Bé", "xây nhà khi có em bé", "xay-nha-khi-co-em-be"],
    ["Cải Tạo Nhà Khi Có Em Bé", "cải tạo nhà khi có em bé", "cai-tao-nha-khi-co-em-be"],
    ["Cải Tạo Nhà Khi Con Lớn", "cải tạo nhà khi con lớn", "cai-tao-nha-khi-con-lon"],
    ["Cải Tạo Nhà Khi Cha Mẹ Ở Chung", "cải tạo nhà khi cha mẹ ở chung", "cai-tao-nha-khi-cha-me-o-chung"],
    ["Xây Nhà Để Ở Hay Cho Thuê", "xây nhà để ở hay cho thuê", "xay-nha-de-o-hay-cho-thue"],
    ["Xây Nhà Đầu Tư Hay Ở", "xây nhà đầu tư hay ở", "xay-nha-dau-tu-hay-o"],
    ["Xây Nhà Cấp 4 Hay 2 Tầng", "xây nhà cấp 4 hay 2 tầng", "xay-nha-cap-4-hay-2-tang"],
    ["Xây Nhà 2 Tầng Hay 3 Tầng", "xây nhà 2 tầng hay 3 tầng", "xay-nha-2-tang-hay-3-tang"],
    ["Xây Nhà 3 Tầng Hay 4 Tầng", "xây nhà 3 tầng hay 4 tầng", "xay-nha-3-tang-hay-4-tang"],
    ["Xây Nhà Phố Hay Biệt Thự", "xây nhà phố hay biệt thự", "xay-nha-pho-hay-biet-thu"],
    ["Xây Nhà Ống Hay Nhà Lệch Tầng", "xây nhà ống hay nhà lệch tầng", "xay-nha-ong-hay-nha-lech-tang"],
    ["Mái Bằng Hay Mái Thái", "mái bằng hay mái thái", "mai-bang-hay-mai-thai"],
    ["Mái Tôn Hay Mái Ngói", "mái tôn hay mái ngói", "mai-ton-hay-mai-ngoi"],
    ["Sàn Gỗ Hay Gạch Men", "sàn gỗ hay gạch men", "san-go-hay-gach-men"],
    ["Sàn Nhựa Hay Sàn Gỗ", "sàn nhựa hay sàn gỗ", "san-nhua-hay-san-go"],
    ["Cửa Nhôm Hay Cửa Gỗ", "cửa nhôm hay cửa gỗ", "cua-nhom-hay-cua-go"],
    ["Cửa Nhựa Hay Cửa Nhôm", "cửa nhựa hay cửa nhôm", "cua-nhua-hay-cua-nhom"],
    ["Sơn Nước Hay Sơn Dầu", "sơn nước hay sơn dầu", "son-nuoc-hay-son-dau"],
    ["Trần Thạch Cao Hay Trần Gỗ", "trần thạch cao hay trần gỗ", "tran-thach-cao-hay-tran-go"],
    ["Bếp Đảo Hay Bếp Chữ L", "bếp đảo hay bếp chữ l", "bep-dao-hay-bep-chu-l"],
    ["Bếp Chữ U Hay Chữ I", "bếp chữ u hay chữ i", "bep-chu-u-hay-chu-i"],
    ["WC Khô Hay WC Ướt", "wc khô hay wc ướt", "wc-kho-hay-wc-uot"],
    ["Giếng Trời Hay Cửa Sổ", "giếng trời hay cửa sổ", "gieng-troi-hay-cua-so"],
    ["Xây Mùa Xuân", "xây nhà mùa xuân", "xay-nha-mua-xuan"],
    ["Xây Mùa Hè", "xây nhà mùa hè", "xay-nha-mua-he"],
    ["Xây Mùa Thu", "xây nhà mùa thu", "xay-nha-mua-thu"],
    ["Xây Mùa Đông", "xây nhà mùa đông", "xay-nha-mua-dong"],
    ["Xây Nhà Trước Tết", "xây nhà trước tết", "xay-nha-truoc-tet"],
    ["Xây Nhà Sau Tết", "xây nhà sau tết", "xay-nha-sau-tet"],
    ["Cải Tạo Trước Tết", "cải tạo trước tết", "cai-tao-truoc-tet"],
    ["Cải Tạo Sau Tết", "cải tạo sau tết", "cai-tao-sau-tet"],
    ["Xây Nhà Năm 2026", "xây nhà năm 2026", "xay-nha-nam-2026"],
    ["Cải Tạo Nhà Năm 2026", "cải tạo nhà năm 2026", "cai-tao-nha-nam-2026"],
    ["Nên Xây Nhà Tháng Nào", "nên xây nhà tháng nào", "nen-xay-nha-thang-nao"],
    ["Nên Cải Tạo Tháng Nào", "nên cải tạo tháng nào", "nen-cai-tao-thang-nao"],
    ["Xây Nhà Khi Giá VLXD Tăng", "xây nhà khi giá vlxd tăng", "xay-nha-khi-gia-vlxd-tang"],
    ["Xây Nhà Khi Giá VLXD Giảm", "xây nhà khi giá vlxd giảm", "xay-nha-khi-gia-vlxd-giam"],
    ["Chờ Giá Vật Tư Hay Xây Ngay", "chờ giá vật tư hay xây ngay", "cho-gia-vat-tu-hay-xay-ngay"],
    ["Xây Nhà Khi Lãi Suất Cao", "xây nhà khi lãi suất cao", "xay-nha-khi-lai-suat-cao"],
    ["Xây Nhà Khi Lãi Suất Thấp", "xây nhà khi lãi suất thấp", "xay-nha-khi-lai-suat-thap"],
    ["Nhà Đẹp Cho Đón Khách", "nhà đẹp cho đón khách", "nha-dep-cho-don-khach"],
    ["Nhà Đẹp Cho Chụp Ảnh", "nhà đẹp cho chụp ảnh", "nha-dep-cho-chup-anh"],
    ["Nhà Đẹp Cho Quay Video", "nhà đẹp cho quay video", "nha-dep-cho-quay-video"],
    ["Nhà Phong Thủy Tốt", "nhà phong thủy tốt", "nha-phong-thuy-tot"],
    ["Hướng Cửa Chính Phong Thủy", "hướng cửa chính phong thủy", "huong-cua-chinh-phong-thuy"],
    ["Vị Trí Bếp Phong Thủy", "vị trí bếp phong thủy", "vi-tri-bep-phong-thuy"],
    ["Vị Trí Phòng Ngủ Phong Thủy", "vị trí phòng ngủ phong thủy", "vi-tri-phong-ngu-phong-thuy"],
    ["Vị Trí WC Phong Thủy", "vị trí wc phong thủy", "vi-tri-wc-phong-thuy"],
    ["Màu Sơn Phong Thủy", "màu sơn phong thủy", "mau-son-phong-thuy-ls"],
    ["Cây Cảnh Phong Thủy Nhà", "cây cảnh phong thủy nhà", "cay-canh-phong-thuy-nha"],
    ["Nhà Cho Pet", "nhà cho pet", "nha-cho-pet"],
    ["Góc Chơi Cho Chó Mèo", "góc chơi cho chó mèo", "goc-choi-cho-cho-meo"],
    ["Sân Chơi Trẻ Em Trong Nhà", "sân chơi trẻ em trong nhà", "san-choi-tre-em-trong-nha-ls"],
    ["Góc Đọc Sách Nhà Phố", "góc đọc sách nhà phố", "goc-doc-sach-nha-pho"],
    ["Góc Cà Phê Tại Gia", "góc cà phê tại gia", "goc-ca-phe-tai-gia"],
    ["Góc Làm Vườn Mini", "góc làm vườn mini", "goc-lam-vuon-mini"],
    ["Nhà Ở Kết Hợp Làm Việc", "nhà ở kết hợp làm việc", "nha-o-ket-hop-lam-viec"],
    ["Nhà Ở Kết Hợp Shop Online", "nhà ở kết hợp shop online", "nha-o-ket-hop-shop-online"],
    ["Nhà Ở Kết Hợp Studio", "nhà ở kết hợp studio", "nha-o-ket-hop-studio"],
    ["Trước Khi Xây Nhà Hỏi Gì", "trước khi xây nhà hỏi gì", "truoc-khi-xay-nha-hoi-gi"],
    ["Trước Khi Cải Tạo Hỏi Gì", "trước khi cải tạo hỏi gì", "truoc-khi-cai-tao-hoi-gi"],
    ["Câu Hỏi Cho Kiến Trúc Sư", "câu hỏi cho kiến trúc sư", "cau-hoi-cho-kien-truc-su"],
    ["Câu Hỏi Cho Nhà Thầu", "câu hỏi cho nhà thầu", "cau-hoi-cho-nha-thau-faq"],
    ["Red Flag Nhà Thầu Xấu", "red flag nhà thầu xấu", "red-flag-nha-thau-xau"],
    ["Green Flag Nhà Thầu Tốt", "green flag nhà thầu tốt", "green-flag-nha-thau-tot"],
    ["Checklist Chủ Nhà Mới", "checklist chủ nhà mới", "checklist-chu-nha-moi"],
    ["Checklist Chủ Nhà Cải Tạo", "checklist chủ nhà cải tạo", "checklist-chu-nha-cai-tao"],
    ["Nhật Ký Xây Nhà Thực Tế", "nhật ký xây nhà thực tế", "nhat-ky-xay-nha-thuc-te"],
    ["Nhật Ký Cải Tạo Thực Tế", "nhật ký cải tạo thực tế", "nhat-ky-cai-tao-thuc-te"],
    ["Bài Học Xây Nhà Lần Đầu", "bài học xây nhà lần đầu", "bai-hoc-xay-nha-lan-dau"],
    ["Bài Học Cải Tạo Lần Đầu", "bài học cải tạo lần đầu", "bai-hoc-cai-tao-lan-dau"],
    ["Sai Lầm Đắt Giá Khi Xây", "sai lầm đắt giá khi xây", "sai-lam-dat-gia-khi-xay"],
    ["Sai Lầm Đắt Giá Khi Cải Tạo", "sai lầm đắt giá khi cải tạo", "sai-lam-dat-gia-khi-cai-tao"],
    ["Xây Nhà Tiết Kiệm Thông Minh", "xây nhà tiết kiệm thông minh", "xay-nha-tiet-kiem-thong-minh"],
    ["Cải Tạo Tiết Kiệm Thông Minh", "cải tạo tiết kiệm thông minh", "cai-tao-tiet-kiem-thong-minh"],
    ["Ưu Đãi Xây Nhà Hôm Nay", "ưu đãi xây nhà hôm nay", "uu-dai-xay-nha-hom-nay-ads"],
    ["Ưu Đãi Cải Tạo Hôm Nay", "ưu đãi cải tạo hôm nay", "uu-dai-cai-tao-hom-nay-ads"],
    ["Tặng Thiết Kế Khi Ký Thầu", "tặng thiết kế khi ký thầu", "tang-thiet-ke-khi-ky-thau-ads"],
    ["Giảm Giá Xây Phần Thô", "giảm giá xây phần thô", "giam-gia-xay-phan-tho-ads"],
    ["Giảm Giá Xây Trọn Gói", "giảm giá xây trọn gói", "giam-gia-xay-tron-goi-ads"],
    ["Liên Hệ Tư Vấn Ngay", "liên hệ tư vấn ngay", "lien-he-tu-van-ngay-ads"],
    ["Đăng Ký Nhận Báo Giá", "đăng ký nhận báo giá", "dang-ky-nhan-bao-gia-ads"],
    ["Gọi Ngay Nhận Khảo Sát", "gọi ngay nhận khảo sát", "goi-ngay-nhan-khao-sat-ads"],
    ["Xây Nhà Sao Khuê 2026", "xây nhà sao khuê 2026", "xay-nha-sao-khue-2026-ads"],
    ["Cải Tạo Sao Khuê 2026", "cải tạo sao khuê 2026", "cai-tao-sao-khue-2026-ads"],
  ]);

  return [b35, b36, b37, b38, b39].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 2947 + (batch - 35) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    35: "Cluster: nội thất phòng, hoàn thiện chi tiết, phong cách.",
    36: "Cluster: kỹ thuật thi công, giai đoạn, QC chất lượng.",
    37: "Cluster: geo Hà Nội, miền Bắc, miền Trung.",
    38: "Cluster: pháp lý, tài chính, bảo hiểm, hợp đồng sâu.",
    39: "Cluster: kịch bản gia đình, so sánh, mùa vụ, lifestyle Ads.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: nội thất phòng, hoàn thiện chi tiết, phong cách.",
  "Cluster: kỹ thuật thi công, giai đoạn, QC chất lượng.",
  "Cluster: geo Hà Nội, miền Bắc, miền Trung.",
  "Cluster: pháp lý, tài chính, bảo hiểm, hợp đồng sâu.",
  "Cluster: kịch bản gia đình, so sánh, mùa vụ, lifestyle Ads.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 35 + i;
  const startNo = 2947 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 35 ? 34 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
