/**
 * Generator: short-keyword batches 60–64 (500 articles, #5447–#5946).
 * Run: npx tsx scripts/gen-short-keyword-batches-60-64.ts
 */
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = join(root, "lib", "seed-content", "src");
const articlesDir = join(seedDir, "articles");

type Item = { title: string; keyword: string; slugBase: string };

function pad(batchIdx: number, items: Item[]): Item[] {
  const out = items.slice();
  let n = 1;
  while (out.length < 100) {
    out.push({
      title: `Chủ Đề Mở Rộng ${60 + batchIdx} ${n}`,
      keyword: `chủ đề mở rộng ${60 + batchIdx} ${n}`,
      slugBase: `chu-de-mo-rong-${60 + batchIdx}-${n}`,
    });
    n++;
  }
  return out.slice(0, 100);
}

function pairs(list: [string, string, string][]): Item[] {
  return list.map(([title, keyword, slugBase]) => ({ title, keyword, slugBase }));
}

function buildAll(): Item[][] {
  // 60 — nhà theo diện tích / số tầng / ngân sách cụ thể
  const b60 = pairs([
    ["Xây Nhà 3x8 2 Tầng", "xây nhà 3x8 2 tầng", "xay-nha-3x8-2-tang-dt"],
    ["Xây Nhà 3x10 2 Tầng", "xây nhà 3x10 2 tầng", "xay-nha-3x10-2-tang-dt"],
    ["Xây Nhà 3x10 3 Tầng", "xây nhà 3x10 3 tầng", "xay-nha-3x10-3-tang-dt"],
    ["Xây Nhà 3x12 3 Tầng", "xây nhà 3x12 3 tầng", "xay-nha-3x12-3-tang-dt"],
    ["Xây Nhà 4x10 2 Tầng", "xây nhà 4x10 2 tầng", "xay-nha-4x10-2-tang-dt"],
    ["Xây Nhà 4x10 3 Tầng", "xây nhà 4x10 3 tầng", "xay-nha-4x10-3-tang-dt"],
    ["Xây Nhà 4x12 3 Tầng", "xây nhà 4x12 3 tầng", "xay-nha-4x12-3-tang-dt"],
    ["Xây Nhà 4x12 4 Tầng", "xây nhà 4x12 4 tầng", "xay-nha-4x12-4-tang-dt"],
    ["Xây Nhà 4x15 3 Tầng", "xây nhà 4x15 3 tầng", "xay-nha-4x15-3-tang-dt"],
    ["Xây Nhà 4x15 4 Tầng", "xây nhà 4x15 4 tầng", "xay-nha-4x15-4-tang-dt"],
    ["Xây Nhà 4x16 4 Tầng", "xây nhà 4x16 4 tầng", "xay-nha-4x16-4-tang-dt"],
    ["Xây Nhà 5x12 3 Tầng", "xây nhà 5x12 3 tầng", "xay-nha-5x12-3-tang-dt"],
    ["Xây Nhà 5x15 3 Tầng", "xây nhà 5x15 3 tầng", "xay-nha-5x15-3-tang-dt"],
    ["Xây Nhà 5x15 4 Tầng", "xây nhà 5x15 4 tầng", "xay-nha-5x15-4-tang-dt"],
    ["Xây Nhà 5x18 4 Tầng", "xây nhà 5x18 4 tầng", "xay-nha-5x18-4-tang-dt"],
    ["Xây Nhà 5x20 4 Tầng", "xây nhà 5x20 4 tầng", "xay-nha-5x20-4-tang-dt"],
    ["Xây Nhà 6x15 3 Tầng", "xây nhà 6x15 3 tầng", "xay-nha-6x15-3-tang-dt"],
    ["Xây Nhà 6x18 3 Tầng", "xây nhà 6x18 3 tầng", "xay-nha-6x18-3-tang-dt"],
    ["Xây Nhà 6x20 4 Tầng", "xây nhà 6x20 4 tầng", "xay-nha-6x20-4-tang-dt"],
    ["Xây Nhà 7x15 3 Tầng", "xây nhà 7x15 3 tầng", "xay-nha-7x15-3-tang-dt"],
    ["Xây Nhà 8x20 2 Tầng", "xây nhà 8x20 2 tầng", "xay-nha-8x20-2-tang-dt"],
    ["Xây Nhà 8x20 3 Tầng", "xây nhà 8x20 3 tầng", "xay-nha-8x20-3-tang-dt"],
    ["Xây Nhà 10x20 Biệt Thự", "xây nhà 10x20 biệt thự", "xay-nha-10x20-biet-thu-dt"],
    ["Xây Nhà Cấp 4 5x20", "xây nhà cấp 4 5x20", "xay-nha-cap-4-5x20-dt"],
    ["Xây Nhà Cấp 4 6x20", "xây nhà cấp 4 6x20", "xay-nha-cap-4-6x20-dt"],
    ["Xây Nhà Cấp 4 Có Gác Lửng", "xây nhà cấp 4 có gác lửng", "xay-nha-cap-4-co-gac-lung-dt"],
    ["Chi Phí Xây Nhà 40m2", "chi phí xây nhà 40m2", "chi-phi-xay-nha-40m2-dt"],
    ["Chi Phí Xây Nhà 50m2", "chi phí xây nhà 50m2", "chi-phi-xay-nha-50m2-dt"],
    ["Chi Phí Xây Nhà 60m2", "chi phí xây nhà 60m2", "chi-phi-xay-nha-60m2-dt"],
    ["Chi Phí Xây Nhà 70m2", "chi phí xây nhà 70m2", "chi-phi-xay-nha-70m2-dt"],
    ["Chi Phí Xây Nhà 80m2", "chi phí xây nhà 80m2", "chi-phi-xay-nha-80m2-dt"],
    ["Chi Phí Xây Nhà 90m2", "chi phí xây nhà 90m2", "chi-phi-xay-nha-90m2-dt"],
    ["Chi Phí Xây Nhà 100m2 DT", "chi phí xây nhà 100m2", "chi-phi-xay-nha-100m2-dt"],
    ["Chi Phí Xây Nhà 120m2 DT", "chi phí xây nhà 120m2", "chi-phi-xay-nha-120m2-dt"],
    ["Chi Phí Xây Nhà 150m2 DT", "chi phí xây nhà 150m2", "chi-phi-xay-nha-150m2-dt"],
    ["Chi Phí Xây Nhà 200m2 DT", "chi phí xây nhà 200m2", "chi-phi-xay-nha-200m2-dt"],
    ["Xây Nhà 800 Triệu", "xây nhà 800 triệu", "xay-nha-800-trieu-dt"],
    ["Xây Nhà 1 Tỷ Đồng", "xây nhà 1 tỷ đồng", "xay-nha-1-ty-dong-dt"],
    ["Xây Nhà 1.5 Tỷ", "xây nhà 1.5 tỷ", "xay-nha-1-5-ty-dt"],
    ["Xây Nhà 2 Tỷ Đồng", "xây nhà 2 tỷ đồng", "xay-nha-2-ty-dong-dt"],
    ["Xây Nhà 2.5 Tỷ", "xây nhà 2.5 tỷ", "xay-nha-2-5-ty-dt"],
    ["Xây Nhà 3 Tỷ Đồng", "xây nhà 3 tỷ đồng", "xay-nha-3-ty-dong-dt"],
    ["Xây Nhà 4 Tỷ Đồng", "xây nhà 4 tỷ đồng", "xay-nha-4-ty-dong-dt"],
    ["Xây Nhà 5 Tỷ Đồng", "xây nhà 5 tỷ đồng", "xay-nha-5-ty-dong-dt"],
    ["Xây Nhà 7 Tỷ Đồng", "xây nhà 7 tỷ đồng", "xay-nha-7-ty-dong-dt"],
    ["Xây Nhà 10 Tỷ Đồng", "xây nhà 10 tỷ đồng", "xay-nha-10-ty-dong-dt"],
    ["Cải Tạo Nhà 100 Triệu", "cải tạo nhà 100 triệu", "cai-tao-nha-100-trieu-dt"],
    ["Cải Tạo Nhà 200 Triệu DT", "cải tạo nhà 200 triệu", "cai-tao-nha-200-trieu-dt"],
    ["Cải Tạo Nhà 300 Triệu", "cải tạo nhà 300 triệu", "cai-tao-nha-300-trieu-dt"],
    ["Cải Tạo Nhà 500 Triệu DT", "cải tạo nhà 500 triệu", "cai-tao-nha-500-trieu-dt"],
    ["Cải Tạo Nhà 700 Triệu", "cải tạo nhà 700 triệu", "cai-tao-nha-700-trieu-dt"],
    ["Cải Tạo Nhà 1 Tỷ DT", "cải tạo nhà 1 tỷ", "cai-tao-nha-1-ty-dt"],
    ["Nhà 2 Tầng 3 Phòng Ngủ", "nhà 2 tầng 3 phòng ngủ", "nha-2-tang-3-phong-ngu-dt"],
    ["Nhà 3 Tầng 4 Phòng Ngủ", "nhà 3 tầng 4 phòng ngủ", "nha-3-tang-4-phong-ngu-dt"],
    ["Nhà 4 Tầng 5 Phòng Ngủ", "nhà 4 tầng 5 phòng ngủ", "nha-4-tang-5-phong-ngu-dt"],
    ["Nhà 5 Tầng Có Thang Máy", "nhà 5 tầng có thang máy", "nha-5-tang-co-thang-may-dt"],
    ["Nhà Lửng 1 Trệt 1 Lửng", "nhà lửng 1 trệt 1 lửng", "nha-lung-1-tret-1-lung-dt"],
    ["Nhà 1 Trệt 1 Lầu 1 Áp Mái", "nhà 1 trệt 1 lầu 1 áp mái", "nha-1-tret-1-lau-1-ap-mai-dt"],
    ["Nhà Có Hầm 1 Trệt 2 Lầu", "nhà có hầm 1 trệt 2 lầu", "nha-co-ham-1-tret-2-lau-dt"],
    ["Nhà Có Hầm 1 Trệt 3 Lầu", "nhà có hầm 1 trệt 3 lầu", "nha-co-ham-1-tret-3-lau-dt"],
    ["Diện Tích Sàn Xây Dựng", "diện tích sàn xây dựng", "dien-tich-san-xay-dung-dt"],
    ["Cách Tính Diện Tích Xây", "cách tính diện tích xây", "cach-tinh-dien-tich-xay-dt"],
    ["Hệ Số Diện Tích Xây", "hệ số diện tích xây", "he-so-dien-tich-xay-dt"],
    ["Diện Tích Thông Thủy", "diện tích thông thủy", "dien-tich-thong-thuy-dt"],
    ["Diện Tích Tim Tường", "diện tích tim tường", "dien-tich-tim-tuong-dt"],
    ["Mật Độ Xây 60 Phần Trăm", "mật độ xây 60%", "mat-do-xay-60-phan-tram-dt"],
    ["Mật Độ Xây 80 Phần Trăm", "mật độ xây 80%", "mat-do-xay-80-phan-tram-dt"],
    ["Mật Độ Xây 100 Phần Trăm", "mật độ xây 100%", "mat-do-xay-100-phan-tram-dt"],
    ["Nhà Hẹp 3m Làm Sao Đẹp", "nhà hẹp 3m làm sao đẹp", "nha-hep-3m-lam-sao-dep-dt"],
    ["Nhà Hẹp 3.5m Layout", "nhà hẹp 3.5m layout", "nha-hep-3-5m-layout-dt"],
    ["Nhà Hẹp 4m Layout Đẹp", "nhà hẹp 4m layout đẹp", "nha-hep-4m-layout-dep-dt"],
    ["Nhà Nông 12m Layout", "nhà nông 12m layout", "nha-nong-12m-layout-dt"],
    ["Nhà Nông 15m Layout", "nhà nông 15m layout", "nha-nong-15m-layout-dt"],
    ["Nhà Nông 20m Layout", "nhà nông 20m layout", "nha-nong-20m-layout-dt"],
    ["Báo Giá Nhà 4x12 Trọn Gói", "báo giá nhà 4x12 trọn gói", "bao-gia-nha-4x12-tron-goi-dt"],
    ["Báo Giá Nhà 5x15 Trọn Gói", "báo giá nhà 5x15 trọn gói", "bao-gia-nha-5x15-tron-goi-dt"],
    ["Báo Giá Nhà 5x20 Trọn Gói", "báo giá nhà 5x20 trọn gói", "bao-gia-nha-5x20-tron-goi-dt"],
    ["Báo Giá Nhà 6x20 Trọn Gói", "báo giá nhà 6x20 trọn gói", "bao-gia-nha-6x20-tron-goi-dt"],
    ["Xây Nhà Phần Thô 4x12", "xây nhà phần thô 4x12", "xay-nha-phan-tho-4x12-dt"],
    ["Xây Nhà Phần Thô 5x15", "xây nhà phần thô 5x15", "xay-nha-phan-tho-5x15-dt"],
    ["Xây Nhà Phần Thô 5x20", "xây nhà phần thô 5x20", "xay-nha-phan-tho-5x20-dt"],
    ["Hoàn Thiện Nhà 4x12", "hoàn thiện nhà 4x12", "hoan-thien-nha-4x12-dt"],
    ["Hoàn Thiện Nhà 5x15", "hoàn thiện nhà 5x15", "hoan-thien-nha-5x15-dt"],
    ["Hoàn Thiện Nhà 5x20", "hoàn thiện nhà 5x20", "hoan-thien-nha-5x20-dt"],
    ["Tiến Độ Nhà 3 Tầng", "tiến độ nhà 3 tầng", "tien-do-nha-3-tang-dt"],
    ["Tiến Độ Nhà 4 Tầng", "tiến độ nhà 4 tầng", "tien-do-nha-4-tang-dt"],
    ["Tiến Độ Nhà 5 Tầng", "tiến độ nhà 5 tầng", "tien-do-nha-5-tang-dt"],
    ["Mẫu Nhà 4x12 Hiện Đại", "mẫu nhà 4x12 hiện đại", "mau-nha-4x12-hien-dai-dt"],
    ["Mẫu Nhà 5x15 Hiện Đại", "mẫu nhà 5x15 hiện đại", "mau-nha-5x15-hien-dai-dt"],
    ["Mẫu Nhà 5x20 Hiện Đại", "mẫu nhà 5x20 hiện đại", "mau-nha-5x20-hien-dai-dt"],
    ["Mẫu Nhà 4x12 Mái Thái", "mẫu nhà 4x12 mái thái", "mau-nha-4x12-mai-thai-dt"],
    ["Mẫu Nhà 5x15 Mái Nhật", "mẫu nhà 5x15 mái nhật", "mau-nha-5x15-mai-nhat-dt"],
    ["Checklist Chọn Diện Tích Xây", "checklist chọn diện tích xây", "checklist-chon-dien-tich-xay-dt"],
    ["Nên Xây Mấy Tầng", "nên xây mấy tầng", "nen-xay-may-tang-dt"],
    ["Diện Tích Bao Nhiêu Là Đủ", "diện tích bao nhiêu là đủ", "dien-tich-bao-nhieu-la-du-dt"],
    ["Tối Ưu Diện Tích Nhà Hẹp", "tối ưu diện tích nhà hẹp", "toi-uu-dien-tich-nha-hep-dt"],
    ["Tối Ưu Ngân Sách Theo m2", "tối ưu ngân sách theo m2", "toi-uu-ngan-sach-theo-m2-dt"],
  ]);

  // 61 — thiết bị / phụ kiện / phụ trợ xây dựng
  const b61 = pairs([
    ["Camera Giám Sát Công Trình", "camera giám sát công trình", "camera-giam-sat-cong-trinh-tb"],
    ["Máy Chấm Công Công Trình", "máy chấm công công trình", "may-cham-cong-cong-trinh-tb"],
    ["Đèn Công Trường", "đèn công trường", "den-cong-truong-tb"],
    ["Máy Phát Điện Công Trình", "máy phát điện công trình", "may-phat-dien-cong-trinh-tb"],
    ["Máy Bơm Nước Công Trình", "máy bơm nước công trình", "may-bom-nuoc-cong-trinh-tb"],
    ["Máy Trộn Hồ Tại Chỗ", "máy trộn hồ tại chỗ", "may-tron-ho-tai-cho-tb"],
    ["Máy Đầm Cóc", "máy đầm cóc", "may-dam-coc-tb"],
    ["Máy Cắt Gạch", "máy cắt gạch", "may-cat-gach-tb"],
    ["Máy Mài Sàn", "máy mài sàn", "may-mai-san-tb"],
    ["Máy Phun Sơn", "máy phun sơn", "may-phun-son-tb"],
    ["Máy Khoan Bê Tông", "máy khoan bê tông", "may-khoan-be-tong-tb"],
    ["Máy Hàn Công Trình", "máy hàn công trình", "may-han-cong-trinh-tb"],
    ["Giàn Giáo Nêm", "giàn giáo nêm", "gian-giao-nem-tb"],
    ["Giàn Giáo Ống", "giàn giáo ống", "gian-giao-ong-tb"],
    ["Ván Ép Cốp Pha", "ván ép cốp pha", "van-ep-cop-pha-tb"],
    ["Cốp Pha Thép", "cốp pha thép", "cop-pha-thep-tb"],
    ["Cốp Pha Nhôm", "cốp pha nhôm", "cop-pha-nhom-tb"],
    ["Chống Thép Sàn", "chống thép sàn", "chong-thep-san-tb"],
    ["Ty Ren Cốp Pha", "ty ren cốp pha", "ty-ren-cop-pha-tb"],
    ["Dây Buộc Thép", "dây buộc thép", "day-buoc-thep-tb"],
    ["Băng Keo Chống Thấm", "băng keo chống thấm", "bang-keo-chong-tham-tb"],
    ["Lưới Thủy Tinh", "lưới thủy tinh", "luoi-thuy-tinh-tb"],
    ["Lưới Mắt Cáo", "lưới mắt cáo", "luoi-mat-cao-tb"],
    ["Màng Nylon Công Trình", "màng nylon công trình", "mang-nylon-cong-trinh-tb"],
    ["Bao Tay Lao Động", "bao tay lao động", "bao-tay-lao-dong-tb"],
    ["Mũ Bảo Hộ Công Trình", "mũ bảo hộ công trình", "mu-bao-ho-cong-trinh-tb"],
    ["Giày Bảo Hộ Xây Dựng", "giày bảo hộ xây dựng", "giay-bao-ho-xay-dung-tb"],
    ["Dây An Toàn Treo", "dây an toàn treo", "day-an-toan-treo-tb"],
    ["Thước Laser Đo Nhà", "thước laser đo nhà", "thuoc-laser-do-nha-tb"],
    ["Máy Cân Mực Laser", "máy cân mực laser", "may-can-muc-laser-tb"],
    ["Máy Đo Độ Ẩm Tường", "máy đo độ ẩm tường", "may-do-do-am-tuong-tb"],
    ["Máy Đo Điện Áp", "máy đo điện áp", "may-do-dien-ap-tb"],
    ["Ống Nhựa Xoắn Điện", "ống nhựa xoắn điện", "ong-nhua-xoan-dien-tb"],
    ["Hộp Nối Điện Âm", "hộp nối điện âm", "hop-noi-dien-am-tb"],
    ["Ống Luồn Dây Điện", "ống luồn dây điện", "ong-luon-day-dien-tb"],
    ["Băng Keo Điện", "băng keo điện", "bang-keo-dien-tb"],
    ["Cút Nối Ống Nước", "cút nối ống nước", "cut-noi-ong-nuoc-tb"],
    ["Tê Ống Nước", "tê ống nước", "te-ong-nuoc-tb"],
    ["Van Khóa Nước", "van khóa nước", "van-khoa-nuoc-tb"],
    ["Phốt Chống Thấm Ống", "phốt chống thấm ống", "phot-chong-tham-ong-tb"],
    ["Ron Cao Su Cửa", "ron cao su cửa", "ron-cao-su-cua-tb"],
    ["Bản Lề Cửa", "bản lề cửa", "ban-le-cua-tb"],
    ["Khóa Tay Gạt", "khóa tay gạt", "khoa-tay-gat-tb"],
    ["Khóa Âm Cửa", "khóa âm cửa", "khoa-am-cua-tb"],
    ["Tay Nắm Cửa", "tay nắm cửa", "tay-nam-cua-tb"],
    ["Thanh Trượt Cửa Lùa", "thanh trượt cửa lùa", "thanh-truot-cua-lua-tb"],
    ["Bánh Xe Cửa Lùa", "bánh xe cửa lùa", "banh-xe-cua-lua-tb"],
    ["Ray Cửa Lùa", "ray cửa lùa", "ray-cua-lua-tb"],
    ["Nẹp Chỉ Trần", "nẹp chỉ trần", "nep-chi-tran-tb"],
    ["Đinh Vít Trần", "đinh vít trần", "dinh-vit-tran-tb"],
    ["Khung Xương Trần", "khung xương trần", "khung-xuong-tran-tb"],
    ["Ke Góc Trần", "ke góc trần", "ke-goc-tran-tb"],
    ["Bột Bả Matit", "bột bả matit", "bot-ba-matit-tb"],
    ["Giấy Nhám Tường", "giấy nhám tường", "giay-nham-tuong-tb"],
    ["Con Lăn Sơn", "con lăn sơn", "con-lan-son-tb"],
    ["Cọ Sơn Cạnh", "cọ sơn cạnh", "co-son-canh-tb"],
    ["Băng Keo Che Sơn", "băng keo che sơn", "bang-keo-che-son-tb"],
    ["Keo Dán Gỗ", "keo dán gỗ", "keo-dan-go-tb"],
    ["Keo Silicon Trong Suốt", "keo silicon trong suốt", "keo-silicon-trong-suot-tb"],
    ["Keo Silicon Trung Tính", "keo silicon trung tính", "keo-silicon-trung-tinh-tb"],
    ["Foam Bọt Nở", "foam bọt nở", "foam-bot-no-tb"],
    ["Đinh Công Nghiệp", "đinh công nghiệp", "dinh-cong-nghiep-tb"],
    ["Vít Tự Khoan", "vít tự khoan", "vit-tu-khoan-tb"],
    ["Tắc Kê Nở", "tắc kê nở", "tac-ke-no-tb"],
    ["Neo Hóa Chất", "neo hóa chất", "neo-hoa-chat-tb"],
    ["Bulong Neo Móng", "bulong neo móng", "bulong-neo-mong-tb"],
    ["Thép Buộc Đai", "thép buộc đai", "thep-buoc-dai-tb"],
    ["Con Kê Thép", "con kê thép", "con-ke-thep-tb"],
    ["Báo Giá Thuê Giàn Giáo", "báo giá thuê giàn giáo", "bao-gia-thue-gian-giao-tb"],
    ["Báo Giá Thuê Máy Trộn", "báo giá thuê máy trộn", "bao-gia-thue-may-tron-tb"],
    ["Báo Giá Thuê Cần Cẩu Mini", "báo giá thuê cần cẩu mini", "bao-gia-thue-can-cau-mini-tb"],
    ["Báo Giá Thuê Vận Thăng", "báo giá thuê vận thăng", "bao-gia-thue-van-thang-tb"],
    ["Cho Thuê Thiết Bị Xây", "cho thuê thiết bị xây", "cho-thue-thiet-bi-xay-tb"],
    ["Mua Hay Thuê Máy Xây", "mua hay thuê máy xây", "mua-hay-thue-may-xay-tb"],
    ["Bảo Dưỡng Máy Xây Dựng", "bảo dưỡng máy xây dựng", "bao-duong-may-xay-dung-tb"],
    ["An Toàn Thiết Bị Công Trường", "an toàn thiết bị công trường", "an-toan-thiet-bi-cong-truong-tb"],
    ["Checklist Thiết Bị Công Trình", "checklist thiết bị công trình", "checklist-thiet-bi-cong-trinh-tb"],
    ["Vật Tư Phụ Xây Nhà", "vật tư phụ xây nhà", "vat-tu-phu-xay-nha-tb"],
    ["Chi Phí Vật Tư Phụ", "chi phí vật tư phụ", "chi-phi-vat-tu-phu-tb"],
    ["Kho Vật Tư Công Trình", "kho vật tư công trình", "kho-vat-tu-cong-trinh-tb"],
    ["Quản Lý Vật Tư Công Trường", "quản lý vật tư công trường", "quan-ly-vat-tu-cong-truong-tb"],
    ["Định Mức Vật Tư Phụ", "định mức vật tư phụ", "dinh-muc-vat-tu-phu-tb"],
    ["Nhà Cung Cấp Vật Tư Xây", "nhà cung cấp vật tư xây", "nha-cung-cap-vat-tu-xay-tb"],
    ["Đại Lý Vật Tư Gần Công Trình", "đại lý vật tư gần công trình", "dai-ly-vat-tu-gan-cong-trinh-tb"],
    ["Giao Vật Tư Đúng Tiến Độ", "giao vật tư đúng tiến độ", "giao-vat-tu-dung-tien-do-tb"],
    ["Kiểm Hàng Vật Tư Nhập", "kiểm hàng vật tư nhập", "kiem-hang-vat-tu-nhap-tb"],
    ["Xu Hướng Thiết Bị Xây 2026", "xu hướng thiết bị xây 2026", "xu-huong-thiet-bi-xay-2026-tb"],
  ]);

  // 62 — geo Bình Tân / Tân Phú / Hóc Môn / Củ Chi sâu
  const b62 = pairs([
    ["Xây Nhà Bình Hưng Hòa", "xây nhà Bình Hưng Hòa", "xay-nha-binh-hung-hoa-btan"],
    ["Xây Nhà Bình Hưng Hòa A", "xây nhà Bình Hưng Hòa A", "xay-nha-binh-hung-hoa-a-btan"],
    ["Xây Nhà Bình Hưng Hòa B", "xây nhà Bình Hưng Hòa B", "xay-nha-binh-hung-hoa-b-btan"],
    ["Xây Nhà Bình Trị Đông", "xây nhà Bình Trị Đông", "xay-nha-binh-tri-dong-btan"],
    ["Xây Nhà Bình Trị Đông A", "xây nhà Bình Trị Đông A", "xay-nha-binh-tri-dong-a-btan"],
    ["Xây Nhà Bình Trị Đông B", "xây nhà Bình Trị Đông B", "xay-nha-binh-tri-dong-b-btan"],
    ["Xây Nhà An Lạc", "xây nhà An Lạc", "xay-nha-an-lac-btan"],
    ["Xây Nhà An Lạc A", "xây nhà An Lạc A", "xay-nha-an-lac-a-btan"],
    ["Xây Nhà Tân Tạo", "xây nhà Tân Tạo", "xay-nha-tan-tao-btan"],
    ["Xây Nhà Tân Tạo A", "xây nhà Tân Tạo A", "xay-nha-tan-tao-a-btan"],
    ["Xây Nhà Bình Hưng Hòa A Gần Aeon", "xây nhà gần Aeon Bình Tân", "xay-nha-gan-aeon-binh-tan"],
    ["Xây Nhà Gần Tên Lửa", "xây nhà gần Tên Lửa", "xay-nha-gan-ten-lua"],
    ["Xây Nhà Gần Kinh Dương Vương", "xây nhà gần Kinh Dương Vương", "xay-nha-gan-kinh-duong-vuong"],
    ["Xây Nhà Gần Quốc Lộ 1A Bình Tân", "xây nhà gần QL1A Bình Tân", "xay-nha-gan-ql1a-binh-tan"],
    ["Xây Nhà Hòa Thạnh", "xây nhà Hòa Thạnh", "xay-nha-hoa-thanh-tphu"],
    ["Xây Nhà Hiệp Tân", "xây nhà Hiệp Tân", "xay-nha-hiep-tan-tphu"],
    ["Xây Nhà Hòa Thạnh Tân Phú", "xây nhà Hòa Thạnh Tân Phú", "xay-nha-hoa-thanh-tan-phu"],
    ["Xây Nhà Phú Thọ Hòa", "xây nhà Phú Thọ Hòa", "xay-nha-phu-tho-hoa-tp"],
    ["Xây Nhà Phú Trung", "xây nhà Phú Trung", "xay-nha-phu-trung"],
    ["Xây Nhà Sơn Kỳ", "xây nhà Sơn Kỳ", "xay-nha-son-ky-tp"],
    ["Xây Nhà Tân Quý", "xây nhà Tân Quý", "xay-nha-tan-quy-tp"],
    ["Xây Nhà Tân Sơn Nhì", "xây nhà Tân Sơn Nhì", "xay-nha-tan-son-nhi"],
    ["Xây Nhà Tây Thạnh", "xây nhà Tây Thạnh", "xay-nha-tay-thanh-tp"],
    ["Xây Nhà Tân Thành", "xây nhà Tân Thành Tân Phú", "xay-nha-tan-thanh-tan-phu"],
    ["Xây Nhà Gần Công Viên Đầm Sen", "xây nhà gần Đầm Sen", "xay-nha-gan-dam-sen"],
    ["Xây Nhà Gần Lũy Bán Bích", "xây nhà gần Lũy Bán Bích", "xay-nha-gan-luy-ban-bich"],
    ["Xây Nhà Gần Âu Cơ", "xây nhà gần Âu Cơ", "xay-nha-gan-au-co"],
    ["Xây Nhà Xuân Thới Sơn", "xây nhà Xuân Thới Sơn", "xay-nha-xuan-thoi-son-hm"],
    ["Xây Nhà Xuân Thới Đông", "xây nhà Xuân Thới Đông", "xay-nha-xuan-thoi-dong-hm"],
    ["Xây Nhà Xuân Thới Thượng", "xây nhà Xuân Thới Thượng", "xay-nha-xuan-thoi-thuong-hm"],
    ["Xây Nhà Đông Thạnh", "xây nhà Đông Thạnh", "xay-nha-dong-thanh-hm"],
    ["Xây Nhà Tân Thới Nhì", "xây nhà Tân Thới Nhì", "xay-nha-tan-thoi-nhi-hm"],
    ["Xây Nhà Trung Chánh", "xây nhà Trung Chánh", "xay-nha-trung-chanh-hm"],
    ["Xây Nhà Thới Tam Thôn", "xây nhà Thới Tam Thôn", "xay-nha-thoi-tam-thon-hm"],
    ["Xây Nhà Bà Điểm", "xây nhà Bà Điểm", "xay-nha-ba-diem-hm"],
    ["Xây Nhà Nhị Bình", "xây nhà Nhị Bình", "xay-nha-nhi-binh-hm"],
    ["Xây Nhà Tân Hiệp Hóc Môn", "xây nhà Tân Hiệp Hóc Môn", "xay-nha-tan-hiep-hoc-mon"],
    ["Xây Nhà Thái Mỹ", "xây nhà Thái Mỹ", "xay-nha-thai-my"],
    ["Xây Nhà Trung Lập Hạ", "xây nhà Trung Lập Hạ", "xay-nha-trung-lap-ha"],
    ["Xây Nhà Trung Lập Thượng", "xây nhà Trung Lập Thượng", "xay-nha-trung-lap-thuong"],
    ["Xây Nhà Phước Thạnh", "xây nhà Phước Thạnh Củ Chi", "xay-nha-phuoc-thanh-cu-chi"],
    ["Xây Nhà Phước Hiệp", "xây nhà Phước Hiệp", "xay-nha-phuoc-hiep"],
    ["Xây Nhà An Nhơn Tây", "xây nhà An Nhơn Tây", "xay-nha-an-nhon-tay"],
    ["Xây Nhà Nhuận Đức", "xây nhà Nhuận Đức", "xay-nha-nhuan-duc"],
    ["Xây Nhà Phạm Văn Cội", "xây nhà Phạm Văn Cội", "xay-nha-pham-van-coi"],
    ["Xây Nhà Phú Hòa Đông", "xây nhà Phú Hòa Đông", "xay-nha-phu-hoa-dong"],
    ["Xây Nhà Tân Thông Hội", "xây nhà Tân Thông Hội", "xay-nha-tan-thong-hoi"],
    ["Xây Nhà Tân Phú Trung", "xây nhà Tân Phú Trung", "xay-nha-tan-phu-trung"],
    ["Xây Nhà Hòa Phú Củ Chi", "xây nhà Hòa Phú Củ Chi", "xay-nha-hoa-phu-cu-chi"],
    ["Xây Nhà Bình Mỹ Củ Chi", "xây nhà Bình Mỹ Củ Chi", "xay-nha-binh-my-cu-chi"],
    ["Xây Nhà Gần Khu Du Lịch Củ Chi", "xây nhà gần khu du lịch Củ Chi", "xay-nha-gan-kdl-cu-chi"],
    ["Xây Nhà Gần Hồ Dầu Tiếng", "xây nhà gần Hồ Dầu Tiếng", "xay-nha-gan-ho-dau-tieng"],
    ["Cải Tạo Nhà Bình Tân", "cải tạo nhà Bình Tân", "cai-tao-nha-binh-tan-geo"],
    ["Cải Tạo Nhà Tân Phú TP", "cải tạo nhà Tân Phú", "cai-tao-nha-tan-phu-geo"],
    ["Cải Tạo Nhà Hóc Môn", "cải tạo nhà Hóc Môn", "cai-tao-nha-hoc-mon-geo"],
    ["Cải Tạo Nhà Củ Chi", "cải tạo nhà Củ Chi", "cai-tao-nha-cu-chi-geo"],
    ["Cải Tạo Nhà An Lạc", "cải tạo nhà An Lạc", "cai-tao-nha-an-lac"],
    ["Cải Tạo Nhà Sơn Kỳ", "cải tạo nhà Sơn Kỳ", "cai-tao-nha-son-ky"],
    ["Cải Tạo Nhà Bà Điểm", "cải tạo nhà Bà Điểm", "cai-tao-nha-ba-diem"],
    ["Thiết Kế Nhà Bình Tân", "thiết kế nhà Bình Tân", "thiet-ke-nha-binh-tan-geo"],
    ["Thiết Kế Nhà Tân Phú TP", "thiết kế nhà Tân Phú", "thiet-ke-nha-tan-phu-geo"],
    ["Thiết Kế Nhà Hóc Môn", "thiết kế nhà Hóc Môn", "thiet-ke-nha-hoc-mon-geo"],
    ["Thiết Kế Nhà Củ Chi", "thiết kế nhà Củ Chi", "thiet-ke-nha-cu-chi-geo"],
    ["Báo Giá Xây Nhà Bình Tân", "báo giá xây nhà Bình Tân", "bao-gia-xay-nha-binh-tan-geo"],
    ["Báo Giá Xây Nhà Tân Phú", "báo giá xây nhà Tân Phú", "bao-gia-xay-nha-tan-phu-geo"],
    ["Báo Giá Xây Nhà Hóc Môn", "báo giá xây nhà Hóc Môn", "bao-gia-xay-nha-hoc-mon-geo"],
    ["Báo Giá Xây Nhà Củ Chi", "báo giá xây nhà Củ Chi", "bao-gia-xay-nha-cu-chi-geo"],
    ["Nhà Thầu Bình Tân", "nhà thầu Bình Tân", "nha-thau-binh-tan-geo"],
    ["Nhà Thầu Tân Phú TP", "nhà thầu Tân Phú", "nha-thau-tan-phu-geo"],
    ["Nhà Thầu Hóc Môn", "nhà thầu Hóc Môn", "nha-thau-hoc-mon-geo"],
    ["Nhà Thầu Củ Chi", "nhà thầu Củ Chi", "nha-thau-cu-chi-geo"],
    ["Xây Nhà Phố Bình Tân", "xây nhà phố Bình Tân", "xay-nha-pho-binh-tan"],
    ["Xây Nhà Ống Tân Phú", "xây nhà ống Tân Phú", "xay-nha-ong-tan-phu"],
    ["Xây Nhà Vườn Hóc Môn", "xây nhà vườn Hóc Môn", "xay-nha-vuon-hoc-mon"],
    ["Xây Nhà Vườn Củ Chi", "xây nhà vườn Củ Chi", "xay-nha-vuon-cu-chi"],
    ["Xây Nhà Trọ Bình Tân", "xây nhà trọ Bình Tân", "xay-nha-tro-binh-tan"],
    ["Xây Biệt Thự Củ Chi", "xây biệt thự Củ Chi", "xay-biet-thu-cu-chi"],
    ["Xin Phép Xây Bình Tân", "xin phép xây Bình Tân", "xin-phep-xay-binh-tan"],
    ["Xin Phép Xây Hóc Môn", "xin phép xây Hóc Môn", "xin-phep-xay-hoc-mon"],
    ["Đơn Giá Xây Bình Tân", "đơn giá xây Bình Tân", "don-gia-xay-binh-tan"],
    ["Đơn Giá Xây Củ Chi", "đơn giá xây Củ Chi", "don-gia-xay-cu-chi"],
    ["Nâng Tầng Nhà Bình Tân", "nâng tầng nhà Bình Tân", "nang-tang-nha-binh-tan"],
    ["Nâng Tầng Nhà Tân Phú", "nâng tầng nhà Tân Phú", "nang-tang-nha-tan-phu"],
    ["Sửa Nhà Bình Tân", "sửa nhà Bình Tân", "sua-nha-binh-tan"],
    ["Sửa Nhà Hóc Môn", "sửa nhà Hóc Môn", "sua-nha-hoc-mon"],
    ["Chống Thấm Nhà Bình Tân", "chống thấm nhà Bình Tân", "chong-tham-nha-binh-tan"],
    ["Chống Thấm Nhà Củ Chi", "chống thấm nhà Củ Chi", "chong-tham-nha-cu-chi"],
    ["Xây Nhà Gần Metro Số 2", "xây nhà gần metro số 2 Tân Phú", "xay-nha-gan-metro-2-tan-phu"],
    ["Xây Nhà Gần Vành Đai 3", "xây nhà gần vành đai 3", "xay-nha-gan-vanh-dai-3"],
    ["Xây Nhà Gần Vành Đai 4", "xây nhà gần vành đai 4", "xay-nha-gan-vanh-dai-4"],
  ]);

  // 63 — so sánh vật liệu / công nghệ mới / xu hướng kỹ thuật
  const b63 = pairs([
    ["Bê Tông Siêu Tính Năng", "bê tông siêu tính năng", "be-tong-sieu-tinh-nang-cn2"],
    ["Bê Tông Tự Lèn", "bê tông tự lèn", "be-tong-tu-len-cn2"],
    ["Bê Tông Nhẹ Cách Nhiệt", "bê tông nhẹ cách nhiệt", "be-tong-nhe-cach-nhiet-cn2"],
    ["Bê Tông Sợi Thép", "bê tông sợi thép", "be-tong-soi-thep-cn2"],
    ["Bê Tông In 3D", "bê tông in 3d", "be-tong-in-3d-cn2"],
    ["In Nhà 3D Việt Nam", "in nhà 3d việt nam", "in-nha-3d-viet-nam-cn2"],
    ["Công Nghệ Prefab Nhà Ở", "công nghệ prefab nhà ở", "cong-nghe-prefab-nha-o-cn2"],
    ["Panel Tường Prefab", "panel tường prefab", "panel-tuong-prefab-cn2"],
    ["Sàn Prefab Nhà Phố", "sàn prefab nhà phố", "san-prefab-nha-pho-cn2"],
    ["Module Bathroom Prefab", "module bathroom prefab", "module-bathroom-prefab-cn2"],
    ["Khung Thép Tiền Chế Nhà", "khung thép tiền chế nhà", "khung-thep-tien-che-nha-cn2"],
    ["Nhà Thép Tiền Chế 1 Tầng", "nhà thép tiền chế 1 tầng", "nha-thep-tien-che-1-tang-cn2"],
    ["Nhà Thép Tiền Chế 2 Tầng", "nhà thép tiền chế 2 tầng", "nha-thep-tien-che-2-tang-cn2"],
    ["CLB Wall Panel", "clb wall panel", "clb-wall-panel-cn2"],
    ["ALC Panel Tường", "alc panel tường", "alc-panel-tuong-cn2"],
    ["EPS Cement Panel", "eps cement panel", "eps-cement-panel-cn2"],
    ["Tấm Panel Cách Nhiệt PU", "tấm panel cách nhiệt pu", "tam-panel-cach-nhiet-pu-cn2"],
    ["Vách Panel Phòng Sạch Mini", "vách panel phòng sạch mini", "vach-panel-phong-sach-mini-cn2"],
    ["Sàn Raised Floor Nhà", "sàn raised floor nhà", "san-raised-floor-nha-cn2"],
    ["Sàn Access Floor", "sàn access floor", "san-access-floor-cn2"],
    ["Hệ Thống BIM Level 2", "hệ thống bim level 2", "he-thong-bim-level-2-cn2"],
    ["Digital Twin Nhà Ở", "digital twin nhà ở", "digital-twin-nha-o-cn2"],
    ["IoT Giám Sát Công Trình", "iot giám sát công trình", "iot-giam-sat-cong-trinh-cn2"],
    ["Sensor Độ Ẩm Tường", "sensor độ ẩm tường", "sensor-do-am-tuong-cn2"],
    ["Sensor Nứt Kết Cấu", "sensor nứt kết cấu", "sensor-nut-ket-cau-cn2"],
    ["Drone Kiểm Tra Mái", "drone kiểm tra mái", "drone-kiem-tra-mai-cn2"],
    ["Thermal Camera Nhà", "thermal camera nhà", "thermal-camera-nha-cn2"],
    ["Scan 3D Hiện Trạng Nhà", "scan 3d hiện trạng nhà", "scan-3d-hien-trang-nha-cn2"],
    ["Point Cloud Cải Tạo", "point cloud cải tạo", "point-cloud-cai-tao-cn2"],
    ["AR Visualize Nhà Mới", "ar visualize nhà mới", "ar-visualize-nha-moi-cn2"],
    ["VR Tour Thiết Kế Nhà", "vr tour thiết kế nhà", "vr-tour-thiet-ke-nha-cn2"],
    ["So Sánh Prefab Và Xây Truyền Thống", "so sánh prefab và xây truyền thống", "so-sanh-prefab-va-xay-truyen-thong-cn2"],
    ["So Sánh Thép Và BTCT", "so sánh thép và btct", "so-sanh-thep-va-btct-cn2"],
    ["So Sánh AAC Và Gạch Đất Nung", "so sánh aac và gạch đất nung", "so-sanh-aac-va-gach-dat-nung-cn2"],
    ["So Sánh Panel Và Xây Tường", "so sánh panel và xây tường", "so-sanh-panel-va-xay-tuong-cn2"],
    ["Ưu Nhược Điểm Nhà Prefab", "ưu nhược điểm nhà prefab", "uu-nhuoc-diem-nha-prefab-cn2"],
    ["Ưu Nhược Điểm Nhà Thép", "ưu nhược điểm nhà thép", "uu-nhuoc-diem-nha-thep-cn2"],
    ["Chi Phí Nhà Prefab m2", "chi phí nhà prefab m2", "chi-phi-nha-prefab-m2-cn2"],
    ["Chi Phí Nhà Thép m2", "chi phí nhà thép m2", "chi-phi-nha-thep-m2-cn2"],
    ["Tiến Độ Prefab Nhanh Hơn", "tiến độ prefab nhanh hơn", "tien-do-prefab-nhanh-hon-cn2"],
    ["Pháp Lý Nhà Prefab", "pháp lý nhà prefab", "phap-ly-nha-prefab-cn2"],
    ["Xin Phép Nhà Thép Tiền Chế", "xin phép nhà thép tiền chế", "xin-phep-nha-thep-tien-che-cn2"],
    ["Chống Cháy Nhà Thép", "chống cháy nhà thép", "chong-chay-nha-thep-cn2"],
    ["Cách Âm Nhà Prefab", "cách âm nhà prefab", "cach-am-nha-prefab-cn2"],
    ["Cách Nhiệt Nhà Prefab", "cách nhiệt nhà prefab", "cach-nhiet-nha-prefab-cn2"],
    ["Tuổi Thọ Nhà Prefab", "tuổi thọ nhà prefab", "tuoi-tho-nha-prefab-cn2"],
    ["Tuổi Thọ Nhà Thép", "tuổi thọ nhà thép", "tuoi-tho-nha-thep-cn2"],
    ["Bảo Dưỡng Nhà Thép", "bảo dưỡng nhà thép", "bao-duong-nha-thep-cn2"],
    ["Sơn Chống Gỉ Khung Thép", "sơn chống gỉ khung thép", "son-chong-gi-khung-thep-cn2"],
    ["Mạ Kẽm Kết Cấu Thép", "mạ kẽm kết cấu thép", "ma-kem-ket-cau-thep-cn2"],
    ["Bu Lông Cường Độ Cao", "bu lông cường độ cao", "bu-long-cuong-do-cao-cn2"],
    ["Hàn Kết Cấu Thép Nhà", "hàn kết cấu thép nhà", "han-ket-cau-thep-nha-cn2"],
    ["Nghiệm Thu Nhà Prefab", "nghiệm thu nhà prefab", "nghiem-thu-nha-prefab-cn2"],
    ["Nghiệm Thu Khung Thép", "nghiệm thu khung thép", "nghiem-thu-khung-thep-cn2"],
    ["Xu Hướng Prefab 2026", "xu hướng prefab 2026", "xu-huong-prefab-2026-cn2"],
    ["Xu Hướng Nhà Thép 2026", "xu hướng nhà thép 2026", "xu-huong-nha-thep-2026-cn2"],
    ["Xu Hướng BIM Xây Nhà", "xu hướng bim xây nhà", "xu-huong-bim-xay-nha-cn2"],
    ["Green Concrete Việt Nam", "green concrete việt nam", "green-concrete-viet-nam-cn2"],
    ["Xi Măng Carbon Thấp", "xi măng carbon thấp", "xi-mang-carbon-thap-cn2"],
    ["Vật Liệu Tái Chế Xây", "vật liệu tái chế xây", "vat-lieu-tai-che-xay-cn2"],
    ["Gạch Từ Tro Bay", "gạch từ tro bay", "gach-tu-tro-bay-cn2"],
    ["Gỗ Engineered Nội Thất", "gỗ engineered nội thất", "go-engineered-noi-that-cn2"],
    ["Bamboo Construction", "bamboo construction", "bamboo-construction-cn2"],
    ["Nhà Tre Hiện Đại", "nhà tre hiện đại", "nha-tre-hien-dai-cn2"],
    ["Rammed Earth Nhà Ở", "rammed earth nhà ở", "rammed-earth-nha-o-cn2"],
    ["Nhà Đất Nện Việt Nam", "nhà đất nện việt nam", "nha-dat-nen-viet-nam-cn2"],
    ["Passive House Việt Nam", "passive house việt nam", "passive-house-viet-nam-cn2"],
    ["Nearly Zero Energy House", "nearly zero energy house", "nearly-zero-energy-house-cn2"],
    ["Heat Pump Nhà Phố", "heat pump nhà phố", "heat-pump-nha-pho-cn2"],
    ["ERV Thông Gió Thu Hồi Nhiệt", "erv thông gió thu hồi nhiệt", "erv-thong-gio-thu-hoi-nhiet-cn2"],
    ["HRV Nhà Ở", "hrv nhà ở", "hrv-nha-o-cn2"],
    ["Pin Lưu Trữ Gia Đình", "pin lưu trữ gia đình", "pin-luu-tru-gia-dinh-cn2"],
    ["Microgrid Nhà Ở", "microgrid nhà ở", "microgrid-nha-o-cn2"],
    ["Báo Giá Nhà Prefab", "báo giá nhà prefab", "bao-gia-nha-prefab-cn2"],
    ["Báo Giá Nhà Thép Tiền Chế", "báo giá nhà thép tiền chế", "bao-gia-nha-thep-tien-che-cn2"],
    ["Nhà Thầu Prefab TPHCM", "nhà thầu prefab tphcm", "nha-thau-prefab-tphcm-cn2"],
    ["Nhà Thầu Thép Tiền Chế", "nhà thầu thép tiền chế", "nha-thau-thep-tien-che-cn2"],
    ["Có Nên Xây Prefab 2026", "có nên xây prefab 2026", "co-nen-xay-prefab-2026-cn2"],
    ["Có Nên Xây Nhà Thép", "có nên xây nhà thép", "co-nen-xay-nha-thep-cn2"],
    ["Khi Nào Chọn Prefab", "khi nào chọn prefab", "khi-nao-chon-prefab-cn2"],
    ["Khi Nào Chọn BTCT", "khi nào chọn btct", "khi-nao-chon-btct-cn2"],
    ["Checklist Công Nghệ Xây Mới", "checklist công nghệ xây mới", "checklist-cong-nghe-xay-moi-cn2"],
  ]);

  // 64 — FAQ quyết định / Ads local / brand conversion
  const b64 = pairs([
    ["Xây Nhà Cần Giấy Tờ Gì", "xây nhà cần giấy tờ gì", "xay-nha-can-giay-to-gi-faq3"],
    ["Cải Tạo Cần Giấy Tờ Gì", "cải tạo cần giấy tờ gì", "cai-tao-nha-can-giay-to-gi-faq3"],
    ["Xây Nhà Hỏi Thầu Gì", "xây nhà hỏi thầu gì", "xay-nha-hoi-thau-gi-faq3"],
    ["Ký Hợp Đồng Cần Chú Ý Gì", "ký hợp đồng cần chú ý gì", "ky-hop-dong-can-chu-y-gi-faq3"],
    ["Thanh Toán Xây Như Thế Nào", "thanh toán xây như thế nào", "thanh-toan-xay-nhu-the-nao-faq3"],
    ["Giữ Lại Bao Nhiêu Phần Trăm", "giữ lại bao nhiêu %", "giu-lai-bao-nhieu-phan-tram-faq3"],
    ["Bảo Hành Xây Bao Lâu", "bảo hành xây bao lâu", "bao-hanh-xay-bao-lau-faq3"],
    ["Phát Sinh Bao Nhiêu Là Bình Thường", "phát sinh bao nhiêu là bình thường", "phat-sinh-bao-nhieu-binh-thuong-faq3"],
    ["Nhà Thầu Trễ Phải Làm Sao", "nhà thầu trễ phải làm sao", "nha-thau-tre-phai-lam-sao-faq3"],
    ["Chất Lượng Kém Phải Làm Sao", "chất lượng kém phải làm sao", "chat-luong-kem-phai-lam-sao-faq3"],
    ["Có Nên Đặt Cọc Trước", "có nên đặt cọc trước", "co-nen-dat-coc-truoc-faq3"],
    ["Cọc Bao Nhiêu Là Hợp Lý", "cọc bao nhiêu là hợp lý", "coc-bao-nhieu-hop-ly-faq3"],
    ["Có Nên Công Chứng Hợp Đồng", "có nên công chứng hợp đồng", "co-nen-cong-chung-hop-dong-faq3"],
    ["Có Nên Thuê Luật Sư Xây", "có nên thuê luật sư xây", "co-nen-thue-luat-su-xay-faq3"],
    ["Giám Sát Có Đắt Không", "giám sát có đắt không", "giam-sat-co-dat-khong-faq3"],
    ["Thiết Kế Có Bắt Buộc Không", "thiết kế có bắt buộc không", "thiet-ke-co-bat-buoc-khong-faq3"],
    ["Xây Không Bản Vẽ Được Không", "xây không bản vẽ được không", "xay-khong-ban-ve-duoc-khong-faq3"],
    ["Tự Mua Vật Tư Có Lợi Không", "tự mua vật tư có lợi không", "tu-mua-vat-tu-co-loi-khong-faq3"],
    ["Thầu Bao Vật Tư Có Lợi Không", "thầu bao vật tư có lợi không", "thau-bao-vat-tu-co-loi-khong-faq3"],
    ["Giá Rẻ Có Đáng Ngờ Không", "giá rẻ có đáng ngờ không", "gia-re-co-dang-ngo-khong-faq3"],
    ["Làm Sao Biết Thầu Uy Tín", "làm sao biết thầu uy tín", "lam-sao-biet-thau-uy-tin-faq3"],
    ["Xem Công Trình Mẫu Ở Đâu", "xem công trình mẫu ở đâu", "xem-cong-trinh-mau-o-dau-faq3"],
    ["Thời Điểm Xây Tốt Nhất", "thời điểm xây tốt nhất", "thoi-diem-xay-tot-nhat-faq3"],
    ["Xây Mùa Mưa Có Sao Không", "xây mùa mưa có sao không", "xay-mua-mua-co-sao-khong-faq3"],
    ["Xây Mùa Nắng Có Sao Không", "xây mùa nắng có sao không", "xay-mua-nang-co-sao-khong-faq3"],
    ["Hàng Xóm Phản Đối Xây", "hàng xóm phản đối xây", "hang-xom-phan-doi-xay-faq3"],
    ["Xây Ảnh Hưởng Nhà Bên Cạnh", "xây ảnh hưởng nhà bên cạnh", "xay-anh-huong-nha-ben-canh-faq3"],
    ["Ép Cọc Rung Nhà Hàng Xóm", "ép cọc rung nhà hàng xóm", "ep-coc-rung-nha-hang-xom-faq3"],
    ["Bụi Tiếng Ồn Công Trình", "bụi tiếng ồn công trình", "bui-tieng-on-cong-trinh-faq3"],
    ["Nghiệm Thu Cần Có Ai", "nghiệm thu cần có ai", "nghiem-thu-can-co-ai-faq3"],
    ["Bàn Giao Cần Kiểm Tra Gì", "bàn giao cần kiểm tra gì", "ban-giao-can-kiem-tra-gi-faq3"],
    ["Sau Bàn Giao Làm Gì", "sau bàn giao làm gì", "sau-ban-giao-lam-gi-faq3"],
    ["Nhập Trạch Khi Nào", "nhập trạch khi nào", "nhap-trach-khi-nao-faq3"],
    ["Sơn Bao Lâu Mới Ở Được", "sơn bao lâu mới ở được", "son-bao-lau-moi-o-duoc-faq3"],
    ["Nhà Mới Có Mùi Sơn", "nhà mới có mùi sơn", "nha-moi-co-mui-son-faq3"],
    ["Xây Nhà Gần Tôi TPHCM", "xây nhà gần tôi tphcm", "xay-nha-gan-toi-tphcm-ads6"],
    ["Cải Tạo Gần Tôi TPHCM", "cải tạo gần tôi tphcm", "cai-tao-gan-toi-tphcm-ads6"],
    ["Nhà Thầu Gần Tôi Quận", "nhà thầu gần tôi quận", "nha-thau-gan-toi-quan-ads6"],
    ["Thợ Xây Gần Đây", "thợ xây gần đây", "tho-xay-gan-day-ads6"],
    ["Kiến Trúc Sư Gần Đây", "kiến trúc sư gần đây", "kien-truc-su-gan-day-ads6"],
    ["Báo Giá Nhanh Trong Ngày", "báo giá nhanh trong ngày", "bao-gia-nhanh-trong-ngay-ads6"],
    ["Khảo Sát Hôm Nay", "khảo sát hôm nay", "khao-sat-hom-nay-ads6"],
    ["Tư Vấn Ngay Bây Giờ", "tư vấn ngay bây giờ", "tu-van-ngay-bay-gio-ads6"],
    ["Gọi Ngay Sao Khuê", "gọi ngay sao khuê", "goi-ngay-sao-khue-ads6"],
    ["Chat Ngay Sao Khuê", "chat ngay sao khuê", "chat-ngay-sao-khue-ads6"],
    ["Đặt Hẹn Sao Khuê", "đặt hẹn sao khuê", "dat-hen-sao-khue-ads6"],
    ["Nhận Ưu Đãi Sao Khuê", "nhận ưu đãi sao khuê", "nhan-uu-dai-sao-khue-ads6"],
    ["Bảng Giá Sao Khuê 2026", "bảng giá sao khuê 2026", "bang-gia-sao-khue-2026-ads6"],
    ["Gói Dịch Vụ Sao Khuê", "gói dịch vụ sao khuê", "goi-dich-vu-sao-khue-ads6"],
    ["Quy Trình Sao Khuê", "quy trình sao khuê", "quy-trinh-sao-khue-ads6"],
    ["Cam Kết Sao Khuê", "cam kết sao khuê", "cam-ket-sao-khue-ads6"],
    ["Bảo Hành Sao Khuê", "bảo hành sao khuê", "bao-hanh-sao-khue-ads6"],
    ["Công Trình Sao Khuê", "công trình sao khuê", "cong-trinh-sao-khue-ads6"],
    ["Khách Hàng Sao Khuê", "khách hàng sao khuê", "khach-hang-sao-khue-ads6"],
    ["Review Sao Khuê", "review sao khuê", "review-sao-khue-ads6"],
    ["Đánh Giá Sao Khuê", "đánh giá sao khuê", "danh-gia-sao-khue-ads6"],
    ["Sao Khuê Ở Đâu", "sao khuê ở đâu", "sao-khue-o-dau-ads6"],
    ["Văn Phòng Sao Khuê", "văn phòng sao khuê", "van-phong-sao-khue-ads6"],
    ["Website Kiến Trúc Sao Khuê", "website kiến trúc sao khuê", "website-kien-truc-sao-khue-ads6"],
    ["Fanpage Sao Khuê Xây Nhà", "fanpage sao khuê xây nhà", "fanpage-sao-khue-xay-nha-ads6"],
    ["YouTube Sao Khuê", "youtube sao khuê", "youtube-sao-khue-ads6"],
    ["TikTok Sao Khuê", "tiktok sao khuê", "tiktok-sao-khue-ads6"],
    ["Best Builder TPHCM", "best builder tphcm", "best-builder-tphcm-ads6"],
    ["Top Builder 2026", "top builder 2026", "top-builder-2026-ads6"],
    ["Trusted Builder Near Me", "trusted builder near me", "trusted-builder-near-me-ads6"],
    ["Licensed Contractor TPHCM", "licensed contractor tphcm", "licensed-contractor-tphcm-ads6"],
    ["Insured Builder TPHCM", "insured builder tphcm", "insured-builder-tphcm-ads6"],
    ["Fixed Price Xây Nhà", "fixed price xây nhà", "fixed-price-xay-nha-ads6"],
    ["No Hidden Fees Xây", "no hidden fees xây", "no-hidden-fees-xay-ads6"],
    ["On Time Delivery Xây", "on time delivery xây", "on-time-delivery-xay-ads6"],
    ["Quality Guaranteed Xây", "quality guaranteed xây", "quality-guaranteed-xay-ads6"],
    ["Free Site Visit TPHCM", "free site visit tphcm", "free-site-visit-tphcm-ads6"],
    ["Free Quote Today", "free quote today", "free-quote-today-ads6"],
    ["Same Day Quote Xây", "same day quote xây", "same-day-quote-xay-ads6"],
    ["Instant Estimate Xây", "instant estimate xây", "instant-estimate-xay-ads6"],
    ["Book Appointment Xây", "book appointment xây", "book-appointment-xay-ads6"],
    ["Schedule Free Consult", "schedule free consult", "schedule-free-consult-ads6"],
    ["Talk To Builder Now", "talk to builder now", "talk-to-builder-now-ads6"],
    ["Get Proposal Today", "get proposal today", "get-proposal-today-ads6"],
    ["Start Your Build 2026", "start your build 2026", "start-your-build-2026-ads6"],
    ["Renovate Your Home Now", "renovate your home now", "renovate-your-home-now-ads6"],
    ["Limited Slots August", "limited slots august", "limited-slots-august-ads6"],
    ["Closing Offer This Week", "closing offer this week", "closing-offer-this-week-ads6"],
    ["Last Chance Promo Xây", "last chance promo xây", "last-chance-promo-xay-ads6"],
    ["CTA Xây Với Sao Khuê", "cta xây với sao khuê", "cta-xay-voi-sao-khue-ads6"],
    ["CTA Cải Tạo Với Sao Khuê", "cta cải tạo với sao khuê", "cta-cai-tao-voi-sao-khue-ads6"],
    ["Final Call Xây Nhà", "final call xây nhà", "final-call-xay-nha-ads6"],
  ]);

  return [b60, b61, b62, b63, b64].map((b, i) => pad(i, b));
}

function writeCalendar(batch: number, startNo: number, items: Item[], theme: string) {
  const rows = items.map((it, i) => ({
    no: startNo + i,
    title: it.title,
    keyword: it.keyword,
    slug: `${it.slugBase}-ngan`,
    status: "done" as const,
  }));
  const body = rows
    .map(
      (r) =>
        `  { no: ${r.no}, title: ${JSON.stringify(r.title)}, keyword: ${JSON.stringify(r.keyword)}, slug: ${JSON.stringify(r.slug)}, status: "done" },`,
    )
    .join("\n");
  const endNo = startNo + 99;
  writeFileSync(
    join(seedDir, `short-keyword-calendar-batch${batch}.ts`),
    `/**
 * Lịch 100 từ khóa ngắn — batch ${batch} (#${startNo}–#${endNo}).
 * ${theme}
 */
import type { ContentCalendarItem } from "./content-calendar";

export const shortKeywordCalendarBatch${batch}: ContentCalendarItem[] = [
${body}
];
`,
    "utf8",
  );
}

function writeFactory(batch: number, prev: number) {
  let c = readFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${prev}.ts`), "utf8");
  const start = 5447 + (batch - 60) * 100;
  const end = start + 99;
  const themes: Record<number, string> = {
    60: "Cluster: diện tích, số tầng, ngân sách cụ thể.",
    61: "Cluster: thiết bị, phụ kiện, vật tư phụ công trình.",
    62: "Cluster: geo Bình Tân, Tân Phú, Hóc Môn, Củ Chi.",
    63: "Cluster: công nghệ mới, prefab, thép, BIM.",
    64: "Cluster: FAQ quyết định, local Ads, brand conversion.",
  };
  c = c.replace(
    /\/\*\*[\s\S]*?\*\//,
    `/**
 * 100 bài tin tức SEO — batch ${batch} từ khóa ngắn (#${start}–#${end}).
 * Chuẩn: 1500+ từ, ≥6 H2, 3 ảnh (alt = từ khóa), FAQ, bảng giá, internal link.
 * ${themes[batch]}
 */`,
  );
  c = c.replace(/short-keyword-calendar-batch\d+/g, `short-keyword-calendar-batch${batch}`);
  c = c.replace(/shortKeywordCalendarBatch\d+/g, `shortKeywordCalendarBatch${batch}`);
  c = c.replace(/shortKeywordBatch\d+/g, `shortKeywordBatch${batch}`);
  c = c.replace(/getShortKeywordBatch\d+Article/g, `getShortKeywordBatch${batch}Article`);
  writeFileSync(join(articlesDir, `short-keyword-tin-tuc-articles-batch${batch}.ts`), c, "utf8");
}

const themes = [
  "Cluster: diện tích, số tầng, ngân sách cụ thể.",
  "Cluster: thiết bị, phụ kiện, vật tư phụ công trình.",
  "Cluster: geo Bình Tân, Tân Phú, Hóc Môn, Củ Chi.",
  "Cluster: công nghệ mới, prefab, thép, BIM.",
  "Cluster: FAQ quyết định, local Ads, brand conversion.",
];

const batches = buildAll();
for (let i = 0; i < 5; i++) {
  const batch = 60 + i;
  const startNo = 5447 + i * 100;
  writeCalendar(batch, startNo, batches[i]!, themes[i]!);
  writeFactory(batch, batch === 60 ? 59 : batch - 1);
  console.log(`wrote batch ${batch} (${batches[i]!.length} items)`);
}
console.log("done");
